(function() {
var v1 = [
  {num:1,words:[["Pablo,","Paul,"],["Silvano","and"],["y","and"],["Timoteo,","Timotheus,"],["a","to"],["la","the"],["iglesia","church"],["de","of"],["los","the"],["tesalonicenses","which"],["en","in"],["Dios","God"],["el","the"],["Padre","father"],["y","and"],["en","in"],["el","the"],["Señor","Lord"],["Jesucristo:","Jesus-Christ:"],["Gracia","grace"],["y","and"],["paz","peace"],["a","to"],["vosotros,","you,"],["de","of"],["Dios","God"],["nuestro","our"],["Padre","father"],["y","and"],["del","of-the"],["Señor","Lord"],["Jesucristo.","Jesus-Christ."]]},
  {num:2,words:[["Damos","we"],["siempre","always"],["gracias","thanks"],["a","to"],["Dios","God"],["por","for"],["todos","all"],["vosotros,","you,"],["haciendo","making"],["memoria","remembrance"],["de","of"],["vosotros","you"],["en","in"],["nuestras","our"],["oraciones,","prayers,"]]},
  {num:3,words:[["acordándonos","remembering"],["sin","without"],["cesar","ceasing"],["delante","before"],["del","of-the"],["Dios","God"],["y","and"],["Padre","father"],["nuestro","our"],["de","of"],["la","the"],["obra","work"],["de","of"],["vuestra","your"],["fe,","faith,"],["del","of-the"],["trabajo","work"],["de","of"],["amor","love"],["y","and"],["de","of"],["vuestra","your"],["perseverancia","perseverance"],["en","in"],["la","the"],["esperanza","hope"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo;","Jesus-Christ;"]]},
  {num:4,words:[["sabiendo,", "knowing,"], ["hermanos","brothers"], ["amados", "beloved"], ["de", "of"], ["Dios,", "God,"], ["vuestra", "your"], ["elección;", "election;"]]},
  {num:5,words:[["por cuanto","because"],["nuestro","our"],["evangelio","gospel"],["no","not"],["fue","was"],["a","to"],["vosotros","you"],["en","in"],["palabra","word"],["solamente,","only,"],["sino","but"],["también","also"],["en","in"],["poder,","power,"],["y","and"],["en","in"],["el","the"],["Espíritu","Spirit"],["Santo","holy"],["y","and"],["en","in"],["gran","great"],["certidumbre;","know;"],["bien","well"],["sabéis","you-know"],["cómo","how"],["fuimos","we-went"],["entre","among"],["vosotros","you"],["por","for"],["amor","love"],["a","to"],["vosotros.","you."]]},
  {num:6,words:[["Y","and"],["vosotros","you"],["os","you"],["hicisteis","you-made"],["imitadores","imitators"],["de","of"],["nosotros","we"],["y","and"],["del","of-the"],["Señor,","Lord,"],["recibiendo","receiveing"],["la","the"],["palabra","word"],["en","in"],["medio","midst"],["de","of"],["mucha","much"],["tribulación,","tribulation,"],["con","with"],["gozo","joy"],["del","of-the"],["Espíritu","Spirit"],["Santo,","holy,"]]},
  {num:7,words:[["de","of"],["tal","such"],["manera","manner"],["que","that"],["habéis","you-have"],["sido","been"],["ejemplo","example"],["a","to"],["todos","all"],["los","the"],["que","that"],["han","they-have"],["creído","believed"],["en","in"],["Macedonia","Macedonia"],["y","and"],["en","in"],["Acaya.","Achaia."]]},
  {num:8,words:[["Porque","because"],["desde","from"],["vosotros","you"],["ha","has"],["resonado","out"],["la","the"],["palabra","word"],["del","of-the"],["Señor,","Lord,"],["no","not"],["solo","alone"],["en","in"],["Macedonia","Macedonia"],["y","and"],["en","in"],["Acaya,","Achaia,"],["sino que","but"],["también","also"],["en","in"],["todo","all"],["lugar","place"],["vuestra","your"],["fe","faith"],["en","in"],["Dios","God"],["se","himself"],["ha","has"],["extendido,","stretched,"],["de modo que","so that"],["no","not"],["tenemos","we-have"],["necesidad","need"],["de","of"],["hablar","to-speak"],["nada.","nothing."]]},
  {num:9,words:[["Porque","because"],["ellos","they"],["cuentan","themselves"],["de","of"],["nosotros","we"],["la","the"],["manera","manner"],["como","as"],["nos","us"],["recibisteis,","received,"],["y","and"],["cómo","how"],["os","you"],["convertisteis","you-converted"],["de","of"],["los","the"],["ídolos","idols"],["a","to"],["Dios,","God,"],["para","for"],["servir","serve"],["al","to-the"],["Dios","God"],["vivo","live"],["y","and"],["verdadero,","true,"]]},
  {num:10,words:[["y","and"],["esperar","to-wait"],["a","to"],["su","his"],["Hijo","son"],["de","of"],["los","the"],["cielos,","heavens,"],["al","to-the"],["que","that"],["resucitó","raised"],["de","of"],["los","the"],["muertos,","dead,"],["a","to"],["Jesús,","Jesus,"],["quien","who"],["nos","us"],["libró","delivered"],["de","of"],["la","the"],["ira","wrath"],["que","that"],["ha","has"],["de","of"],["venir.","to-come."]]},
];
renderVerseSet(v1, '1th-ch1-verses');

var v2 = [
  {num:1,words:[["Porque,", "because,"], ["hermanos,","brothers,"], ["vosotros", "you"], ["mismos", "selves"], ["sabéis", "you-know"], ["que", "that"], ["nuestra", "our"], ["visita", "lord"], ["a", "to"], ["vosotros", "you"], ["no", "not"], ["fue","was"], ["en", "in"], ["vano,", "vain,"]]},
  {num:2,words:[["pues","for"],["aun","even"],["habiendo","having"],["padecido","suffered"],["antes,","before,"],["y","and"],["sido","been"],["afrentados","reproached"],["en","in"],["Filipos,","Philippi,"],["como","as"],["sabéis,","you-know,"],["tuvimos","we-had"],["valentía","Philippi"],["en","in"],["nuestro","our"],["Dios","God"],["para","for"],["anunciaros","God"],["el","the"],["evangelio","gospel"],["de","of"],["Dios","God"],["en","in"],["medio","midst"],["de","of"],["gran","great"],["oposición.","contention."]]},
  {num:3,words:[["Porque","because"],["nuestra","our"],["exhortación","exhortation"],["no","not"],["procedió","proceeded"],["de","of"],["error,","error,"],["ni","nor"],["de","of"],["impureza,","uncleanness,"],["ni","nor"],["fue","was"],["por","for"],["engaño,","guile,"]]},
  {num:4,words:[["sino que","but"],["según","according-to"],["fuimos","we-went"],["aprobados","allowed"],["por","for"],["Dios","God"],["para que","that"],["se","himself"],["nos","us"],["confiase","trusts-himself"],["el","the"],["evangelio,","gospel,"],["así","thus"],["hablamos;","we-speak;"],["no","not"],["como","as"],["para","for"],["agradar","to-please"],["a","to"],["los","the"],["hombres,","men,"],["sino","but"],["a","to"],["Dios,","God,"],["que","that"],["examina","tries"],["nuestros","our"],["corazones.","hearts."]]},
  {num:5,words:[["Porque","because"],["nunca","never"],["fuimos","we-went"],["lisonjeros","time"],["en","in"],["la","the"],["palabra,","word,"],["como","as"],["sabéis,","you-know,"],["ni","nor"],["encubrimos","we-cover-up"],["avaricia;","covetousness;"],["Dios","God"],["es","is"],["testigo;","witness;"]]},
  {num:6,words:[["ni","nor"],["buscamos","we-seek"],["gloria","glory"],["de","of"],["los","the"],["hombres,","men,"],["ni","nor"],["de","of"],["vosotros,","you,"],["ni","nor"],["de","of"],["otros,","others,"],["aunque","although"],["podíamos","we-was-power/caning"],["seros","been"],["carga","burden"],["como","as"],["apóstoles","apostles"],["de","of"],["Cristo.","Christ."]]},
  {num:7,words:[["Antes","before"],["bien,","well,"],["fuimos","we-went"],["afectuosos","gentle"],["entre","among"],["vosotros","you"],["como","as"],["la","the"],["que","that"],["cría","your"],["con","with"],["ternura","cherishes"],["a","to"],["sus","her"],["hijos.","children."]]},
  {num:8,words:[["Tan","so"],["grande","great"],["es","is"],["nuestro","our"],["afecto","affection"],["por","for"],["vosotros,","you,"],["que","that"],["hubiéramos","we-might-have"],["querido","lord"],["entregaros","imparted"],["no","not"],["solo","alone"],["el","the"],["evangelio","gospel"],["de","of"],["Dios,","God,"],["sino","but"],["también","also"],["nuestras","our"],["propias","own"],["vidas,","lives,"],["porque","because"],["habéis","you-have"],["llegado","hour"],["a","to"],["sernos","be-us"],["muy","very"],["queridos.","lords."]]},
  {num:9,words:[["Porque,","because,"],["hermanos,","brothers,"],["os","you"],["acordáis","remember"],["de","of"],["nuestro","our"],["trabajo","work"],["y","and"],["fatiga,","of,"],["cómo","how"],["trabajando","working"],["de","of"],["noche","night"],["y","and"],["de","of"],["día,","day,"],["para","for"],["no","not"],["ser","be"],["gravosos","burdensome"],["a","to"],["ninguno","none"],["de","of"],["vosotros,","you,"],["os","you"],["predicamos","we-preach"],["el","the"],["evangelio","gospel"],["de","of"],["Dios.","God."]]},
  {num:10,words:[["Vosotros","you"],["sois","are"],["testigos,","witnesses,"],["y","and"],["Dios","God"],["también,","also,"],["de","of"],["cuán","how"],["santa","holy"],["y","and"],["justa","just"],["e","and"],["irreprensiblemente","unblameably"],["nos","us"],["condujimos","behaved"],["con","with"],["vosotros","you"],["los","the"],["que","that"],["creísteis,","you-believed,"]]},
  {num:11,words:[["así","thus"],["como","as"],["también","also"],["sabéis","you-know"],["de","of"],["qué","what"],["modo","manner"],["exhortábamos","we-was-exhorting"],["y","and"],["consolábamos","we-charged"],["a","to"],["cada","each"],["uno","one"],["de","of"],["vosotros,","you,"],["como","as"],["un","a"],["padre","father"],["a","to"],["sus","his"],["hijos,","children,"]]},
  {num:12,words:[["y","and"],["os","you"],["encargábamos","we-ordered"],["que","that"],["anduvieseis","worthy"],["como","as"],["es","is"],["digno","worthy"],["de","of"],["Dios,","God,"],["que","that"],["os","you"],["llamó","called"],["a","to"],["su","his"],["reino","kingdom"],["y","and"],["gloria.","glory."]]},
  {num:13,words:[["Por","for"],["lo","it"],["cual","which"],["también","also"],["nosotros","we"],["damos","give"],["gracias","thanks"],["a","to"],["Dios","God"],["sin","without"],["cesar,","ceasing,"],["porque","because"],["cuando","when"],["recibisteis","you-received"],["la","the"],["palabra","word"],["de","of"],["Dios","God"],["que","that"],["oísteis","you-heard"],["de","of"],["nosotros,","we,"],["la","the"],["recibisteis","received"],["no","not"],["como","as"],["palabra","word"],["de","of"],["hombres,","men,"],["sino","but"],["según","according-to"],["es","is"],["en verdad,","truly,"],["la","the"],["palabra","word"],["de","of"],["Dios,","God,"],["la","the"],["cual","which"],["actúa","acts"],["en","in"],["vosotros","you"],["los","the"],["que","that"],["creísteis.","you-believed."]]},
  {num:14,words:[["Porque","because"],["vosotros,","you,"],["hermanos,","brothers,"],["llegasteis","you-became"],["a","to"],["ser","be"],["imitadores","imitators"],["de","of"],["las","the"],["iglesias","churches"],["de","of"],["Dios","God"],["en","in"],["Cristo","Christ"],["Jesús","Jesus"],["que","that"],["están","they-are"],["en","in"],["Judea;","Judaea;"],["pues","for"],["habéis","you-have"],["padecido","suffered"],["vosotros","you"],["las","the"],["mismas","same"],["cosas","things"],["que","that"],["los","the"],["de","of"],["vuestra","your"],["propia","own"],["nación,","nation,"],["como","as"],["también","also"],["ellos","they"],["de","of"],["los","the"],["judíos;","Jews;"]]},
  {num:15,words:[["los","the"],["cuales","which"],["mataron","they-slew"],["al","to-the"],["Señor","Lord"],["Jesús","Jesus"],["y","and"],["a","to"],["sus","their"],["propios","own"],["profetas,","prophets,"],["y","and"],["a","to"],["nosotros","we"],["nos","us"],["han","have"],["perseguido;","pursued;"],["y","and"],["no","not"],["agradan","they-please"],["a","to"],["Dios,","God,"],["y","and"],["se","themselves"],["oponen","contrary"],["a","to"],["todos","all"],["los","the"],["hombres;","men;"]]},
  {num:16,words:[["impidiéndonos","forbidding"],["hablar","to-speak"],["a","to"],["los","the"],["gentiles,","Gentiles,"],["a fin de que","so that"],["se","themselves"],["salven;","may-save;"],["así","thus"],["colman","to"],["ellos","they"],["siempre","always"],["la","the"],["medida","measure"],["de","of"],["sus","their"],["pecados,","sins,"],["pues","for"],["vino","wine"],["sobre","upon"],["ellos","they"],["la","the"],["ira","wrath"],["hasta","until"],["el","the"],["extremo.","end."]]},
  {num:17,words:[["Pero","but"],["nosotros,","we,"],["hermanos,","brothers,"],["separados","presence"],["de","of"],["vosotros","you"],["por","for"],["un","a"],["poco","little"],["de","of"],["tiempo,","time,"],["de","of"],["vista","sight"],["pero","but"],["no","not"],["de","of"],["corazón,","heart,"],["tanto","therefore"],["más","more"],["procuramos","we-seek"],["con","with"],["mucho","much"],["deseo","I-desire"],["ver","see"],["vuestro","your"],["rostro.","face."]]},
  {num:18,words:[["Por","for"],["lo","it/him"],["cual","which"],["quisimos","we-loved"],["ir","to-go"],["a","to"],["vosotros,","you,"],["yo,","I,"],["Pablo,","Paul,"],["a","to"],["la","the"],["verdad,","truth,"],["una","a"],["y","and"],["otra","other"],["vez;","time;"],["pero","but"],["Satanás","Satan"],["nos","us"],["lo","it/him"],["impidió.","prevented."]]},
  {num:19,words:[["Porque,","because,"],["¿cuál","which"],["es","is"],["nuestra","our"],["esperanza,","hope,"],["o","or"],["gozo,","I-joy,"],["o","or"],["corona","crown"],["de que","that"],["me","me"],["gloríe?","not?"],["¿No","not"],["lo","it/him"],["sois","are"],["vosotros,","you,"],["delante","before"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo","Jesus-Christ"],["en","in"],["su","his"],["venida?","coming?"]]},
  {num:20,words:[["Porque","because"],["vosotros","you"],["sois","are"],["nuestra","our"],["gloria","glory"],["y","and"],["gozo.","I-joy."]]},
];
renderVerseSet(v2, '1th-ch2-verses');

var v3 = [
  {num:1,words:[["Por","for"],["lo","it"],["cual,","which,"],["no pudiendo","cannot"],["soportarlo","bear-it"],["más,","more,"],["acordamos","good"],["quedarnos","remain-us"],["solos","alone"],["en","in"],["Atenas,","Athens,"]]},
  {num:2,words:[["y","and"],["enviamos","we-send"],["a","to"],["Timoteo,","Timotheus,"],["nuestro","our"],["hermano,","brother,"],["ministro","minister"],["de","of"],["Dios","God"],["y","and"],["colaborador","fellowlabourer"],["nuestro","our"],["en","in"],["el","the"],["evangelio","gospel"],["de","of"],["Cristo,","Christ,"],["para","for"],["confirmaros","confirm"],["y","and"],["exhortaros","exhort"],["en","in"],["vuestra","your"],["fe,","faith,"]]},
  {num:3,words:[["a fin de que","so that"],["nadie","no-one"],["se","himself"],["inquiete","moved"],["por","for"],["estas","these"],["tribulaciones,","tribulations,"],["porque","because"],["vosotros","you"],["mismos","selves"],["sabéis","you-know"],["que","that"],["hemos","we-have"],["sido","been"],["puestos","set"],["para","for"],["esto.","this."]]},
  {num:4,words:[["Porque","because"],["aun","even"],["estando","being"],["con","with"],["vosotros,","you,"],["os","you"],["predecíamos","told"],["que","that"],["íbamos","we-went"],["a","to"],["pasar","pass"],["tribulaciones,","tribulations,"],["como","as"],["ha","has"],["acontecido","happened"],["y","and"],["bien","well"],["sabéis.","you-know."]]},
  {num:5,words:[["Por","for"],["lo","it/him"],["cual","which"],["también","also"],["yo,","I,"],["no pudiendo","cannot"],["soportar","bear"],["más,","more,"],["he","I-have"],["enviado","sent"],["para","for"],["informarme","informs"],["de","of"],["vuestra","your"],["fe,","faith,"],["no","not"],["sea","be"],["que","that"],["os","you"],["haya","let-there-be"],["tentado","tempted"],["el","the"],["tentador,","tempted,"],["y","and"],["que","that"],["nuestro","our"],["trabajo","work"],["haya","let-there-be"],["sido","been"],["en","in"],["vano.","vain."]]},
  {num:6,words:[["Pero","but"],["cuando","when"],["Timoteo","Timotheus"],["volvió","returned"],["de","of"],["vosotros","you"],["a","to"],["nosotros,","we,"],["nos","us"],["dio","gave"],["buenas","good"],["nuevas","new"],["de","of"],["vuestra","your"],["fe","faith"],["y","and"],["amor,","love,"],["y","and"],["que","that"],["siempre","always"],["tenéis","you-have"],["gratos","savours"],["recuerdos","remembrances"],["de","of"],["nosotros,","we,"],["deseando","desiring"],["vernos,","see-us,"],["como","as"],["también","also"],["nosotros","we"],["a","to"],["vosotros.","you."]]},
  {num:7,words:[["Por","by"],["ello,","it,"],["hermanos,","brothers,"],["recibimos","we-receive"],["consuelo","consolation"],["con","with"],["respecto","concerning"],["a","to"],["vosotros,","you,"],["en","in"],["medio","midst"],["de","of"],["nuestra","our"],["necesidad","need"],["y","and"],["aflicción,","affliction,"],["por","by"],["causa","cause/sake"],["de","of"],["vuestra","your"],["fe;","faith;"]]},
  {num:8,words:[["porque","because"],["ahora","now"],["vivimos,","we-live,"],["si","if"],["vosotros","you"],["estáis","stand"],["firmes","you-firm"],["en","in"],["el","the"],["Señor.","Lord."]]},
  {num:9,words:[["Por","for"],["lo","it/him"],["cual,","which,"],["¿qué","what"],["acción","thanksgiving"],["de","of"],["gracias","thanks"],["podremos","we-will-power"],["dar","to-give"],["a","to"],["Dios","God"],["por","for"],["vosotros,","you,"],["por","for"],["todo","all"],["el","the"],["gozo","joy"],["con que","wherewith"],["nos","us"],["regocijamos","joy"],["a causa de","because of"],["vosotros","you"],["delante","before"],["de","of"],["nuestro","our"],["Dios,","God,"]]},
  {num:10,words:[["orando","praying"],["de","of"],["noche","night"],["y","and"],["de","of"],["día","day"],["con","with"],["gran","great"],["fervor,","fervor,"],["para que","that"],["veamos","we-see"],["vuestro","your"],["rostro,","face,"],["y","and"],["para que","that"],["completemos","we-may-complete"],["lo","it/him"],["que","that"],["falta","lack"],["a","to"],["vuestra","your"],["fe?","faith?"]]},
  {num:11,words:[["Mas","but"],["el","the"],["mismo","same"],["Dios","God"],["y","and"],["Padre","father"],["nuestro,","our,"],["y","and"],["nuestro","our"],["Señor","Lord"],["Jesucristo,","Jesus-Christ,"],["encaminen","they-direct"],["nuestro","our"],["viaje","journey"],["a","to"],["vosotros.","you."]]},
  {num:12,words:[["Y","and"],["el","the"],["Señor","Lord"],["os","you"],["multiplique","make"],["y","and"],["os","you"],["haga","let-do"],["abundar","to-abound"],["en","in"],["amor","love"],["unos","some"],["para","for"],["con","with"],["otros,","others,"],["y","and"],["para","for"],["con","with"],["todos,","all,"],["como","as"],["también","also"],["lo","it/him"],["es","is"],["de","of"],["nosotros","we"],["para","for"],["con","with"],["vosotros;","you;"]]},
  {num:13,words:[["para que","that"],["sean","they-let-be"],["confirmados","confirmed"],["vuestros","your"],["corazones,","hearts,"],["irreprensibles","of"],["en","in"],["santidad","holiness"],["delante","before"],["de","of"],["Dios","God"],["nuestro","our"],["Padre","father"],["en","in"],["la","the"],["venida","coming"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo","Jesus-Christ"],["con","with"],["todos","all"],["sus","his"],["santos.","saints."]]},
];
renderVerseSet(v3, '1th-ch3-verses');

var v4 = [
  {num:1,words:[["Por","by"],["lo","it/him"],["demás,","rest,"],["hermanos,","brothers,"],["os","you"],["rogamos","beseech"],["y","and"],["exhortamos","we-exhort"],["en","in"],["el","the"],["Señor","Lord"],["Jesús,","Jesus,"],["que","that"],["de","of"],["la","the"],["manera","manner"],["que","that"],["fuisteis","you-went"],["enseñados","taught"],["por","by"],["nosotros","we"],["de","of"],["cómo","how"],["os","you"],["conviene","expedient"],["andar","to-walk"],["y","and"],["agradar","to-please"],["a","to"],["Dios,","God,"],["abundéis","you-may-abound"],["más","more"],["y","and"],["más.","more."]]},
  {num:2,words:[["Porque","because"],["ya","already"],["sabéis","you-know"],["qué","what"],["mandamientos","commandments"],["os","you"],["dimos","we-gave"],["de","of"],["parte","part"],["del","of-the"],["Señor","Lord"],["Jesús.","Jesus."]]},
  {num:3,words:[["Porque","because"],["la","the"],["voluntad","will"],["de","of"],["Dios","God"],["es","is"],["vuestra","your"],["santificación;","sanctification;"],["que","that"],["os","you"],["apartéis","you-may-separate"],["de","of"],["la","the"],["fornicación;","fornication;"]]},
  {num:4,words:[["que","that"],["cada","each"],["uno","one"],["de","of"],["vosotros","you"],["sepa","may-know"],["tener","have"],["su","his"],["vaso","vessel"],["en","in"],["santificación","sanctification"],["y","and"],["honor;","honour;"]]},
  {num:5,words:[["no","not"],["con","with"],["pasión","passion"],["de","of"],["concupiscencia,","of,"],["como","as"],["los","the"],["gentiles","Gentiles"],["que","that"],["no","not"],["conocen","they-know"],["a","to"],["Dios;","God;"]]},
  {num:6,words:[["que","that"],["ninguno","none"],["oprima","man"],["ni","nor"],["engañe","may-deceive"],["en","in"],["nada","nothing"],["a","to"],["su","his"],["hermano,","brother,"],["porque","because"],["el","the"],["Señor","Lord"],["es","is"],["vengador","avenger"],["de","of"],["todo","all"],["esto,","this,"],["como","as"],["ya","already"],["os","you"],["hemos","we-have"],["dicho","said"],["y","and"],["testificado.","testified."]]},
  {num:7,words:[["Porque", "because"], ["no", "not"], ["nos", "us"], ["ha", "has"], ["llamado", "called"], ["Dios", "God"], ["a", "to"], ["impureza,", "uncleanness,"], ["sino", "but"], ["a", "to"], ["santificación.", "sanctification."]]},
  {num:8,words:[["Así que,","so,"], ["el", "the"], ["que", "that"], ["menosprecia","despises"], ["esto,", "this,"], ["no", "not"], ["menosprecia","despises"], ["a", "to"], ["hombre,", "man,"], ["sino", "but"], ["a", "to"], ["Dios,", "God,"], ["que", "that"], ["también", "also"], ["nos", "us"], ["dio", "gave"], ["su","his"], ["Espíritu", "Spirit"], ["Santo.", "holy."]]},
  {num:9,words:[["Pero", "but"], ["acerca", "about"], ["del", "of-the"], ["amor", "love"], ["fraternal", "love"], ["no", "not"], ["es", "is"], ["necesario", "needful"], ["que", "that"], ["os", "you"], ["escriba,", "scribe,"], ["porque", "because"], ["vosotros", "you"], ["mismos", "selves"], ["habéis", "you-have"], ["aprendido", "learned"], ["de", "of"], ["Dios", "God"], ["que", "that"], ["os", "you"], ["améis", "love"], ["los", "the"], ["unos", "some"], ["a", "to"], ["los", "the"], ["otros;", "others;"]]},
  {num:10,words:[["y","and"],["también","also"],["lo","it"],["hacéis","you-do"],["así","thus"],["con","with"],["todos","all"],["los","the"],["hermanos","brothers"],["que","that"],["están","they-are"],["por","for"],["toda","all"],["Macedonia.","Macedonia."],["Pero","but"],["os","you"],["rogamos,","beseech,"],["hermanos,","brothers,"],["que","that"],["abundéis","you-may-abound"],["en","in"],["ello","it"],["más","more"],["y","and"],["más;","more;"]]},
  {num:11,words:[["y","and"],["que","that"],["procuréis","you-may-seek"],["tener","have"],["tranquilidad,","tranquility,"],["y","and"],["ocuparos","occupy"],["de","of"],["vuestros","your"],["asuntos,","affairs,"],["y","and"],["trabajar","to-work"],["con","with"],["vuestras","your"],["manos","hands"],["de","of"],["la","the"],["manera","manner"],["que","that"],["os","you"],["hemos","we-have"],["mandado;","commanded;"]]},
  {num:12,words:[["a fin de que","so that"],["andéis","you-may-walk"],["honradamente","honors"],["para","for"],["con","with"],["los","the"],["extraños,","strangers,"],["y","and"],["no","not"],["tengáis","you-afraid"],["necesidad","need"],["de","of"],["nada.","nothing."]]},
  {num:13,words:[["Tampoco","neither"],["queremos,","we-want,"],["hermanos,","brothers,"],["que","that"],["ignoréis","you-may-ignore"],["acerca","about"],["de","of"],["los","the"],["que","that"],["duermen,","they-sleep,"],["para que","that"],["no","not"],["os","you"],["entristezcáis","sorrow"],["como","as"],["los","the"],["otros","others"],["que","that"],["no","not"],["tienen","they-have"],["esperanza.","hope."]]},
  {num:14,words:[["Porque","because"],["si","if"],["creemos","we-believe"],["que","that"],["Jesús","Jesus"],["murió","died"],["y","and"],["resucitó,","raised,"],["así","thus"],["también","also"],["traerá","will-bring"],["Dios","God"],["con","with"],["Jesús","Jesus"],["a","to"],["los","the"],["que","that"],["durmieron","they-slept"],["en","in"],["él.","he."]]},
  {num:15,words:[["Por","for"],["lo","it/him"],["cual,","which,"],["os","you"],["decimos","we-say"],["esto","this"],["en","in"],["palabra","word"],["del","of-the"],["Señor:","Lord:"],["que","that"],["nosotros","we"],["que","that"],["vivimos,","we-live,"],["que","that"],["habremos","we-will-have"],["quedado","remained"],["hasta","until"],["la","the"],["venida","coming"],["del","of-the"],["Señor,","Lord,"],["no","not"],["precederemos","we-will-precede"],["a","to"],["los","the"],["que","that"],["durmieron.","they-slept."]]},
  {num:16,words:[["Porque","because"],["el","the"],["Señor","Lord"],["mismo","same"],["con","with"],["voz","voice"],["de","of"],["mando,","command,"],["con","with"],["voz","voice"],["de","of"],["arcángel,","voice,"],["y","and"],["con","with"],["trompeta","trump"],["de","of"],["Dios,","God,"],["descenderá","down"],["del","of-the"],["cielo;","heaven;"],["y","and"],["los","the"],["muertos","dead"],["en","in"],["Cristo","Christ"],["resucitarán","they-rise"],["primero.","first."]]},
  {num:17,words:[["Luego","then"],["nosotros,","we,"],["los","the"],["que","that"],["vivamos,","we-may-live,"],["los","the"],["que","that"],["hayamos","we-may-have"],["quedado,","remained,"],["seremos","we-saved"],["arrebatados","caught"],["juntamente","together"],["con","with"],["ellos","they"],["en","in"],["las","the"],["nubes","clouds"],["para","for"],["recibir","receive"],["al","to-the"],["Señor","Lord"],["en","in"],["el","the"],["aire,","air,"],["y","and"],["así","thus"],["estaremos","we-shall-be"],["siempre","always"],["con","with"],["el","the"],["Señor.","Lord."]]},
  {num:18,words:[["Por tanto,","therefore,"], ["consolaos", "comfort"], ["los", "the"], ["unos", "some"], ["a", "to"], ["los", "the"], ["otros", "others"], ["con", "with"], ["estas", "these"], ["palabras.", "words."]]},
];
renderVerseSet(v4, '1th-ch4-verses');

var v5 = [
  {num:1,words:[["Pero","but"],["acerca","about"],["de","of"],["los","the"],["tiempos","times"],["y","and"],["de","of"],["las","the"],["estaciones,","seasons,"],["no","not"],["tenéis","you-have"],["necesidad,","need,"],["hermanos,","brothers,"],["de que","that"],["yo","I"],["os","you"],["escriba.","scribe."]]},
  {num:2,words:[["Porque","because"],["vosotros","you"],["sabéis","know"],["perfectamente","perfectly"],["que","that"],["el","the"],["día","day"],["del","of-the"],["Señor","Lord"],["vendrá","shall-come"],["así","thus"],["como","as"],["ladrón","thief"],["en","in"],["la","the"],["noche,","night,"]]},
  {num:3,words:[["que","that"],["cuando","when"],["digan:","they-may-say:"],["Paz","peace"],["y","and"],["seguridad,","safety,"],["entonces","then"],["vendrá","shall-come"],["sobre","upon"],["ellos","they"],["destrucción","destruction"],["repentina,","sudden,"],["como","as"],["los","the"],["dolores","sorrows"],["a","to"],["la","the"],["mujer","woman"],["encinta,","child,"],["y","and"],["no","not"],["escaparán.","they-will-escape."]]},
  {num:4,words:[["Mas","but"],["vosotros,","you,"],["hermanos,","brothers,"],["no","not"],["estáis","you-are"],["en","in"],["tinieblas,","darkness,"],["para que","that"],["aquel","that"],["día","day"],["os","you"],["sorprenda","may-surprise"],["como","as"],["ladrón;","thief;"]]},
  {num:5,words:[["porque","because"],["todos","all"],["vosotros","you"],["sois","are"],["hijos","children"],["de","of"],["luz,","light,"],["e","and"],["hijos","children"],["del","of-the"],["día;","day;"],["no","not"],["somos","we-are"],["de","of"],["la","the"],["noche,","night,"],["ni","nor"],["de","of"],["las","the"],["tinieblas.","darkness."]]},
  {num:6,words:[["Por tanto,","therefore,"],["no","not"],["durmamos","we-may-sleep"],["como","as"],["los","the"],["demás,","others,"],["sino","but"],["velemos","we-may-watch-over"],["y","and"],["seamos","we"],["sobrios.","sober."]]},
  {num:7,words:[["Porque","because"],["los","the"],["que","that"],["duermen,","they-sleep,"],["de","of"],["noche","night"],["duermen;","they-night;"],["y","and"],["los","the"],["que","that"],["se","themselves"],["emborrachan,","drunken,"],["de","of"],["noche","night"],["se","themselves"],["emborrachan.","night."]]},
  {num:8,words:[["Pero","but"],["nosotros,","we,"],["que","that"],["somos","we-are"],["del","of-the"],["día,","day,"],["seamos","we"],["sobrios,","sobers,"],["habiéndonos","having-us"],["vestido","clothed"],["con","with"],["la","the"],["coraza","breastplate"],["de","of"],["la","the"],["fe","faith"],["y","and"],["del","of-the"],["amor,","love,"],["y","and"],["con","with"],["la","the"],["esperanza","hope"],["de","of"],["la","the"],["salvación","salvation"],["como","as"],["yelmo.","salvation."]]},
  {num:9,words:[["Porque","because"],["no","not"],["nos","us"],["ha","has"],["puesto","placed"],["Dios","God"],["para","for"],["ira,","wrath,"],["sino","but"],["para","for"],["alcanzar","to-reach"],["salvación","salvation"],["por medio de","by means of"],["nuestro","our"],["Señor","Lord"],["Jesucristo,","Jesus-Christ,"]]},
  {num:10,words:[["quien","who"],["murió","died"],["por","for"],["nosotros,","we,"],["ya","already"],["sea","be"],["que","that"],["velemos,","we-wake,"],["o","or"],["que","that"],["durmamos,","we-may-sleep,"],["vivamos","we-may-live"],["juntamente","together"],["con","with"],["él.","he."]]},
  {num:11,words:[["Por","for"],["lo","it/him"],["cual,","which,"],["consolaos","himself"],["los","the"],["unos","some"],["a","to"],["los","the"],["otros,","others,"],["y","and"],["edificaos","another"],["los","the"],["unos","some"],["a","to"],["los","the"],["otros,","others,"],["así","thus"],["como","as"],["lo","it/him"],["hacéis.","you-do."]]},
  {num:12,words:[["Y","and"],["os","you"],["rogamos,","beseech,"],["hermanos,","brothers,"],["que","that"],["reconozcáis","you-may-recognize"],["a","to"],["los","the"],["que","that"],["trabajan","they-work"],["entre","among"],["vosotros,","you,"],["y","and"],["os","you"],["presiden","may-preside"],["en","in"],["el","the"],["Señor,","Lord,"],["y","and"],["os","you"],["amonestan;","you;"]]},
  {num:13,words:[["y","and"],["que","that"],["los","the"],["tengáis","afraid"],["en","in"],["mucha","much"],["estima","estimates"],["por","for"],["causa","sake"],["de","of"],["su","their"],["obra.","work."],["Tened","you-good"],["paz","peace"],["los","the"],["unos","some"],["con","with"],["los","the"],["otros.","others."]]},
  {num:14,words:[["También","also"],["os","you"],["rogamos,","beseech,"],["hermanos,","brothers,"],["que","that"],["amonestéis","brothers"],["a","to"],["los","the"],["que","that"],["andan","they-walk"],["desordenadamente,","without-formly,"],["que","that"],["consoléis","unruly"],["a","to"],["los","the"],["de","of"],["poco","little"],["ánimo,","cheer,"],["que","that"],["sostengáis","you-may-hold"],["a","to"],["los","the"],["débiles,","weak,"],["que","that"],["seáis","you-may-be"],["pacientes","toward"],["para","for"],["con","with"],["todos.","all."]]},
  {num:15,words:[["Mirad","you-heed"],["que","that"],["ninguno","none"],["devuelva","render"],["a","to"],["otro","other"],["mal","evil"],["por","for"],["mal,","evil,"],["sino","but"],["seguid","you-follow"],["lo","it/him"],["bueno","good"],["siempre","always"],["los","the"],["unos","some"],["para","for"],["con","with"],["los","the"],["otros,","others,"],["y","and"],["para","for"],["con","with"],["todos.","all."]]},
  {num:16,words:[["Estad", "your"], ["siempre", "always"], ["gozosos.", "evermore."]]},
  {num:17,words:[["Orad","you-pray"],["sin","without"],["cesar.","ceasing."]]},
  {num:18,words:[["Dad","you-ear"],["gracias","thanks"],["en","in"],["todo,","all,"],["porque","because"],["esta","this"],["es","is"],["la","the"],["voluntad","will"],["de","of"],["Dios","God"],["para","for"],["con","with"],["vosotros","you"],["en","in"],["Cristo","Christ"],["Jesús.","Jesus."]]},
  {num:19,words:[["No","not"],["apaguéis","may-turn-off"],["el","the"],["Espíritu.","Spirit."]]},
  {num:20,words:[["No","not"],["menospreciéis","you-may-despise"],["las","the"],["profecías.","prophecies."]]},
  {num:21,words:[["Examinadlo", "prove"], ["todo;", "all;"], ["retened", "fast"], ["lo", "it/him"], ["bueno.", "good."]]},
  {num:22,words:[["Apartaos", "depart"], ["de", "of"], ["toda", "all"], ["apariencia", "appearance"], ["de", "of"], ["mal.", "evil."]]},
  {num:23,words:[["Y","and"],["el","the"],["mismo","same"],["Dios","God"],["de","of"],["paz","peace"],["os","you"],["santifique","may-sanctify"],["por","for"],["completo;","utterly;"],["y","and"],["todo","all"],["vuestro","your"],["ser,","be,"],["y","and"],["espíritu,","Spirit,"],["y","and"],["alma","soul"],["y","and"],["cuerpo","body"],["sea","be"],["guardado","kept"],["irreprensible","to"],["para","for"],["la","the"],["venida","coming"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo.","Jesus-Christ."]]},
  {num:24,words:[["Fiel", "faithful"], ["es", "is"], ["el", "the"], ["que", "that"], ["os", "you"], ["ha", "has"], ["llamado,", "called,"], ["quien", "who"], ["también", "also"], ["lo","it"], ["hará.", "shall-make."]]},
  {num:25,words:[["Hermanos,","brothers,"],["orad","you-pray"],["por","for"],["nosotros.","we."]]},
  {num:26,words:[["Saludad","you-salute"],["a","to"],["todos","all"],["los","the"],["hermanos","brothers"],["con","with"],["beso","kissed"],["santo.","holy."]]},
  {num:27,words:[["Os", "you"], ["encargo,", "charge,"], ["por","by"], ["el", "the"], ["Señor,", "Lord,"], ["que", "that"], ["esta", "this"], ["carta", "divorcement"], ["sea","be"], ["leída", "read"], ["a", "to"], ["todos", "all"], ["los", "the"], ["santos", "saints"], ["hermanos.","brothers."]]},
  {num:28,words:[["La","the"],["gracia","grace"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo","Jesus-Christ"],["sea","be"],["con","with"],["vosotros.","you."],["Amén.","Amen."]]},
];
renderVerseSet(v5, '1th-ch5-verses');

})();
