(function() {
var v1 = [
  {num:1,words:[["Pablo,", "paul,"], ["Silvano", "and"], ["y", "and"], ["Timoteo,", "timotheus,"], ["a", "to"], ["la", "the"], ["iglesia", "church"], ["de", "of"], ["los", "the"], ["tesalonicenses", "which"], ["en", "in"], ["Dios", "God"], ["el", "the"], ["Padre", "father"], ["y", "and"], ["en", "in"], ["el", "the"], ["Señor", "Lord"], ["Jesucristo:", "Jesus-Christ:"], ["Gracia", "grace"], ["y", "and"], ["paz", "peace"], ["a", "to"], ["vosotros,", "you,"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["y", "and"], ["del", "of-the"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:2,words:[["Damos", "we"], ["siempre", "always"], ["gracias", "thanks"], ["a", "to"], ["Dios", "God"], ["por", "by/for"], ["todos", "all"], ["vosotros,", "you,"], ["haciendo", "doing/making"], ["memoria", "remembrance"], ["de", "of"], ["vosotros", "you"], ["en", "in"], ["nuestras", "provisions"], ["oraciones,", "prayers,"]]},
  {num:3,words:[["acordándonos", "remembering"], ["sin", "without"], ["cesar", "ceasing"], ["delante", "before"], ["del", "of-the"], ["Dios", "God"], ["y", "and"], ["Padre", "father"], ["nuestro", "our"], ["de", "of"], ["la", "the"], ["obra", "work"], ["de", "of"], ["vuestra", "your"], ["fe,", "faith,"], ["del", "of-the"], ["trabajo", "work/labor"], ["de", "of"], ["amor", "love"], ["y", "and"], ["de", "of"], ["vuestra", "your"], ["perseverancia", "the"], ["en", "in"], ["la", "the"], ["esperanza", "hope"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo;", "Jesus-Christ;"]]},
  {num:4,words:[["sabiendo,", "knowing,"], ["hermanos", "brethren"], ["amados", "beloved"], ["de", "of"], ["Dios,", "God,"], ["vuestra", "your"], ["elección;", "election;"]]},
  {num:5,words:[["por", "by/for"], ["cuanto", "as-much-as"], ["nuestro", "our"], ["evangelio", "gospel"], ["no", "not"], ["fue", "was/went"], ["a", "to"], ["vosotros", "you"], ["en", "in"], ["palabra", "word"], ["solamente,", "only,"], ["sino", "but"], ["también", "also"], ["en", "in"], ["poder,", "power/can,"], ["y", "and"], ["en", "in"], ["el", "the"], ["Espíritu", "Spirit"], ["Santo", "holy"], ["y", "and"], ["en", "in"], ["gran", "great"], ["certidumbre;", "know;"], ["bien", "well"], ["sabéis", "you-know"], ["cómo", "how"], ["fuimos", "we"], ["entre", "among"], ["vosotros", "you"], ["por", "by/for"], ["amor", "love"], ["a", "to"], ["vosotros.", "you."]]},
  {num:6,words:[["Y", "and"], ["vosotros", "you"], ["os", "you"], ["hicisteis", "ye"], ["imitadores", "of"], ["de", "of"], ["nosotros", "we"], ["y", "and"], ["del", "of-the"], ["Señor,", "Lord,"], ["recibiendo", "receiveing"], ["la", "the"], ["palabra", "word"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["mucha", "much"], ["tribulación,", "tribulation,"], ["con", "with"], ["gozo", "joy"], ["del", "of-the"], ["Espíritu", "Spirit"], ["Santo,", "holy,"]]},
  {num:7,words:[["de", "of"], ["tal", "such"], ["manera", "manner"], ["que", "that"], ["habéis", "you-have"], ["sido", "been"], ["ejemplo", "example"], ["a", "to"], ["todos", "all"], ["los", "the"], ["que", "that"], ["han", "have"], ["creído", "believed"], ["en", "in"], ["Macedonia", "macedonia"], ["y", "and"], ["en", "in"], ["Acaya.", "achaia."]]},
  {num:8,words:[["Porque", "because"], ["desde", "from"], ["vosotros", "you"], ["ha", "has"], ["resonado", "out"], ["la", "the"], ["palabra", "word"], ["del", "of-the"], ["Señor,", "Lord,"], ["no", "not"], ["solo", "alone"], ["en", "in"], ["Macedonia", "macedonia"], ["y", "and"], ["en", "in"], ["Acaya,", "achaia,"], ["sino", "but"], ["que", "that"], ["también", "also"], ["en", "in"], ["todo", "all"], ["lugar", "place"], ["vuestra", "your"], ["fe", "faith"], ["en", "in"], ["Dios", "God"], ["se", "[refl.]"], ["ha", "has"], ["extendido,", "stretched,"], ["de", "of"], ["modo", "manner/way"], ["que", "that"], ["no", "not"], ["tenemos", "we-have"], ["necesidad", "need"], ["de", "of"], ["hablar", "speak"], ["nada.", "nothing."]]},
  {num:9,words:[["Porque", "because"], ["ellos", "they"], ["cuentan", "themselves"], ["de", "of"], ["nosotros", "we"], ["la", "the"], ["manera", "manner"], ["como", "as"], ["nos", "us"], ["recibisteis,", "received,"], ["y", "and"], ["cómo", "how"], ["os", "you"], ["convertisteis", "and"], ["de", "of"], ["los", "the"], ["ídolos", "idols"], ["a", "to"], ["Dios,", "God,"], ["para", "for"], ["servir", "serve"], ["al", "to-the"], ["Dios", "God"], ["vivo", "live"], ["y", "and"], ["verdadero,", "true,"]]},
  {num:10,words:[["y", "and"], ["esperar", "for"], ["a", "to"], ["su", "his/her"], ["Hijo", "son"], ["de", "of"], ["los", "the"], ["cielos,", "heavens,"], ["al", "to-the"], ["que", "that"], ["resucitó", "raised"], ["de", "of"], ["los", "the"], ["muertos,", "dead,"], ["a", "to"], ["Jesús,", "Jesus,"], ["quien", "who"], ["nos", "us"], ["libró", "delivered"], ["de", "of"], ["la", "the"], ["ira", "wrath"], ["que", "that"], ["ha", "has"], ["de", "of"], ["venir.", "come."]]},
];
renderVerseSet(v1, '1th-ch1-verses');

var v2 = [
  {num:1,words:[["Porque,", "because,"], ["hermanos,", "brethren,"], ["vosotros", "you"], ["mismos", "selves"], ["sabéis", "you-know"], ["que", "that"], ["nuestra", "our"], ["visita", "you,"], ["a", "to"], ["vosotros", "you"], ["no", "not"], ["fue", "was/went"], ["en", "in"], ["vano,", "vain,"]]},
  {num:2,words:[["pues", "for"], ["aun", "even"], ["habiendo", "having"], ["padecido", "suffered"], ["antes,", "before,"], ["y", "and"], ["sido", "been"], ["afrentados", "were"], ["en", "in"], ["Filipos,", "entreated,"], ["como", "as"], ["sabéis,", "you-know,"], ["tuvimos", "at"], ["valentía", "philippi,"], ["en", "in"], ["nuestro", "our"], ["Dios", "God"], ["para", "for"], ["anunciaros", "god"], ["el", "the"], ["evangelio", "gospel"], ["de", "of"], ["Dios", "God"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["gran", "great"], ["oposición.", "contention."]]},
  {num:3,words:[["Porque", "because"], ["nuestra", "our"], ["exhortación", "exhortation"], ["no", "not"], ["procedió", "not"], ["de", "of"], ["error,", "error,"], ["ni", "nor"], ["de", "of"], ["impureza,", "uncleanness,"], ["ni", "nor"], ["fue", "was/went"], ["por", "by/for"], ["engaño,", "guile,"]]},
  {num:4,words:[["sino", "but"], ["que", "that"], ["según", "according-to"], ["fuimos", "we"], ["aprobados", "allowed"], ["por", "by/for"], ["Dios", "God"], ["para", "for"], ["que", "that"], ["se", "[refl.]"], ["nos", "us"], ["confiase", "trust"], ["el", "the"], ["evangelio,", "gospel,"], ["así", "thus"], ["hablamos;", "speak;"], ["no", "not"], ["como", "as"], ["para", "for"], ["agradar", "please"], ["a", "to"], ["los", "the"], ["hombres,", "men,"], ["sino", "but"], ["a", "to"], ["Dios,", "God,"], ["que", "that"], ["examina", "trieth"], ["nuestros", "our"], ["corazones.", "hearts."]]},
  {num:5,words:[["Porque", "because"], ["nunca", "never"], ["fuimos", "we"], ["lisonjeros", "time"], ["en", "in"], ["la", "the"], ["palabra,", "word,"], ["como", "as"], ["sabéis,", "you-know,"], ["ni", "nor"], ["encubrimos", "a"], ["avaricia;", "covetousness;"], ["Dios", "God"], ["es", "is"], ["testigo;", "witness;"]]},
  {num:6,words:[["ni", "nor"], ["buscamos", "of"], ["gloria", "glory"], ["de", "of"], ["los", "the"], ["hombres,", "men,"], ["ni", "nor"], ["de", "of"], ["vosotros,", "you,"], ["ni", "nor"], ["de", "of"], ["otros,", "others,"], ["aunque", "although"], ["podíamos", "have"], ["seros", "been"], ["carga", "burden"], ["como", "as"], ["apóstoles", "apostles"], ["de", "of"], ["Cristo.", "Christ."]]},
  {num:7,words:[["Antes", "before"], ["bien,", "well,"], ["fuimos", "we"], ["afectuosos", "gentle"], ["entre", "among"], ["vosotros", "you"], ["como", "as"], ["la", "the"], ["que", "that"], ["cría", "thy"], ["con", "with"], ["ternura", "cherisheth"], ["a", "to"], ["sus", "his/her"], ["hijos.", "children."]]},
  {num:8,words:[["Tan", "so"], ["grande", "great"], ["es", "is"], ["nuestro", "our"], ["afecto", "of"], ["por", "by/for"], ["vosotros,", "you,"], ["que", "that"], ["hubiéramos", "we"], ["querido", "lord"], ["entregaros", "imparted"], ["no", "not"], ["solo", "alone"], ["el", "the"], ["evangelio", "gospel"], ["de", "of"], ["Dios,", "God,"], ["sino", "but"], ["también", "also"], ["nuestras", "provisions"], ["propias", "own"], ["vidas,", "lives,"], ["porque", "because"], ["habéis", "you-have"], ["llegado", "hour"], ["a", "to"], ["sernos", "be-us"], ["muy", "very"], ["queridos.", "lords."]]},
  {num:9,words:[["Porque,", "because,"], ["hermanos,", "brethren,"], ["os", "you"], ["acordáis", "remember"], ["de", "of"], ["nuestro", "our"], ["trabajo", "work/labor"], ["y", "and"], ["fatiga,", "of,"], ["cómo", "how"], ["trabajando", "with"], ["de", "of"], ["noche", "night"], ["y", "and"], ["de", "of"], ["día,", "day,"], ["para", "for"], ["no", "not"], ["ser", "be"], ["gravosos", "any"], ["a", "to"], ["ninguno", "none"], ["de", "of"], ["vosotros,", "you,"], ["os", "you"], ["predicamos", "you"], ["el", "the"], ["evangelio", "gospel"], ["de", "of"], ["Dios.", "God."]]},
  {num:10,words:[["Vosotros", "you"], ["sois", "ye-are"], ["testigos,", "witnesses,"], ["y", "and"], ["Dios", "God"], ["también,", "also,"], ["de", "of"], ["cuán", "beautiful"], ["santa", "holy"], ["y", "and"], ["justa", "just"], ["e", "and"], ["irreprensiblemente", "unblameably"], ["nos", "us"], ["condujimos", "behaved"], ["con", "with"], ["vosotros", "you"], ["los", "the"], ["que", "that"], ["creísteis,", "ye,"]]},
  {num:11,words:[["así", "thus"], ["como", "as"], ["también", "also"], ["sabéis", "you-know"], ["de", "of"], ["qué", "what"], ["modo", "manner/way"], ["exhortábamos", "comforted"], ["y", "and"], ["consolábamos", "charged"], ["a", "to"], ["cada", "each"], ["uno", "one"], ["de", "of"], ["vosotros,", "you,"], ["como", "as"], ["un", "a"], ["padre", "father"], ["a", "to"], ["sus", "his/her"], ["hijos,", "children,"]]},
  {num:12,words:[["y", "and"], ["os", "you"], ["encargábamos", "would"], ["que", "that"], ["anduvieseis", "worthy"], ["como", "as"], ["es", "is"], ["digno", "worthy"], ["de", "of"], ["Dios,", "God,"], ["que", "that"], ["os", "you"], ["llamó", "called"], ["a", "to"], ["su", "his/her"], ["reino", "kingdom"], ["y", "and"], ["gloria.", "glory."]]},
  {num:13,words:[["Por", "by/for"], ["lo", "it/him"], ["cual", "which"], ["también", "also"], ["nosotros", "we"], ["damos", "we"], ["gracias", "thanks"], ["a", "to"], ["Dios", "God"], ["sin", "without"], ["cesar,", "ceasing,"], ["porque", "because"], ["cuando", "when"], ["recibisteis", "received"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Dios", "God"], ["que", "that"], ["oísteis", "heard"], ["de", "of"], ["nosotros,", "we,"], ["la", "the"], ["recibisteis", "received"], ["no", "not"], ["como", "as"], ["palabra", "word"], ["de", "of"], ["hombres,", "men,"], ["sino", "but"], ["según", "according-to"], ["es", "is"], ["en", "in"], ["verdad,", "truth,"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Dios,", "God,"], ["la", "the"], ["cual", "which"], ["actúa", "in"], ["en", "in"], ["vosotros", "you"], ["los", "the"], ["que", "that"], ["creísteis.", "ye."]]},
  {num:14,words:[["Porque", "because"], ["vosotros,", "you,"], ["hermanos,", "brethren,"], ["llegasteis", "became"], ["a", "to"], ["ser", "be"], ["imitadores", "the"], ["de", "of"], ["las", "the"], ["iglesias", "churches"], ["de", "of"], ["Dios", "God"], ["en", "in"], ["Cristo", "Christ"], ["Jesús", "Jesus"], ["que", "that"], ["están", "are"], ["en", "in"], ["Judea;", "judaea;"], ["pues", "for"], ["habéis", "you-have"], ["padecido", "suffered"], ["vosotros", "you"], ["las", "the"], ["mismas", "same"], ["cosas", "things"], ["que", "that"], ["los", "the"], ["de", "of"], ["vuestra", "your"], ["propia", "own"], ["nación,", "nation,"], ["como", "as"], ["también", "also"], ["ellos", "they"], ["de", "of"], ["los", "the"], ["judíos;", "jews;"]]},
  {num:15,words:[["los", "the"], ["cuales", "which"], ["mataron", "slew"], ["al", "to-the"], ["Señor", "Lord"], ["Jesús", "Jesus"], ["y", "and"], ["a", "to"], ["sus", "his/her"], ["propios", "own"], ["profetas,", "prophets,"], ["y", "and"], ["a", "to"], ["nosotros", "we"], ["nos", "us"], ["han", "have"], ["perseguido;", "had;"], ["y", "and"], ["no", "not"], ["agradan", "please"], ["a", "to"], ["Dios,", "God,"], ["y", "and"], ["se", "[refl.]"], ["oponen", "contrary"], ["a", "to"], ["todos", "all"], ["los", "the"], ["hombres;", "men;"]]},
  {num:16,words:[["impidiéndonos", "forbidding"], ["hablar", "speak"], ["a", "to"], ["los", "the"], ["gentiles,", "gentiles,"], ["a", "to"], ["fin", "end"], ["de", "of"], ["que", "that"], ["se", "[refl.]"], ["salven;", "be;"], ["así", "thus"], ["colman", "to"], ["ellos", "they"], ["siempre", "always"], ["la", "the"], ["medida", "measure"], ["de", "of"], ["sus", "his/her"], ["pecados,", "sins,"], ["pues", "for"], ["vino", "wine"], ["sobre", "upon"], ["ellos", "they"], ["la", "the"], ["ira", "wrath"], ["hasta", "until"], ["el", "the"], ["extremo.", "end."]]},
  {num:17,words:[["Pero", "but"], ["nosotros,", "we,"], ["hermanos,", "brethren,"], ["separados", "presence"], ["de", "of"], ["vosotros", "you"], ["por", "by/for"], ["un", "a"], ["poco", "little"], ["de", "of"], ["tiempo,", "time,"], ["de", "of"], ["vista", "sight"], ["pero", "but"], ["no", "not"], ["de", "of"], ["corazón,", "heart,"], ["tanto", "so-much"], ["más", "more"], ["procuramos", "to"], ["con", "with"], ["mucho", "much"], ["deseo", "desire"], ["ver", "see"], ["vuestro", "your"], ["rostro.", "face."]]},
  {num:18,words:[["Por", "by/for"], ["lo", "it/him"], ["cual", "which"], ["quisimos", "would"], ["ir", "go"], ["a", "to"], ["vosotros,", "you,"], ["yo,", "I,"], ["Pablo,", "paul,"], ["a", "to"], ["la", "the"], ["verdad,", "truth,"], ["una", "a"], ["y", "and"], ["otra", "other"], ["vez;", "time;"], ["pero", "but"], ["Satanás", "satan"], ["nos", "us"], ["lo", "it/him"], ["impidió.", "us."]]},
  {num:19,words:[["Porque,", "because,"], ["¿cuál", "which"], ["es", "is"], ["nuestra", "our"], ["esperanza,", "hope,"], ["o", "or"], ["gozo,", "joy,"], ["o", "or"], ["corona", "crown"], ["de", "of"], ["que", "that"], ["me", "me"], ["gloríe?", "not?"], ["¿No", "not"], ["lo", "it/him"], ["sois", "ye-are"], ["vosotros,", "you,"], ["delante", "before"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["en", "in"], ["su", "his/her"], ["venida?", "coming?"]]},
  {num:20,words:[["Porque", "because"], ["vosotros", "you"], ["sois", "ye-are"], ["nuestra", "our"], ["gloria", "glory"], ["y", "and"], ["gozo.", "joy."]]},
];
renderVerseSet(v2, '1th-ch2-verses');

var v3 = [
  {num:1,words:[["Por", "by/for"], ["lo", "it/him"], ["cual,", "which,"], ["no", "not"], ["pudiendo", "forbear,"], ["soportarlo", "bear-it"], ["más,", "more,"], ["acordamos", "good"], ["quedarnos", "remain-us"], ["solos", "alone"], ["en", "in"], ["Atenas,", "alone,"]]},
  {num:2,words:[["y", "and"], ["enviamos", "the"], ["a", "to"], ["Timoteo,", "timotheus,"], ["nuestro", "our"], ["hermano,", "brother,"], ["ministro", "minister"], ["de", "of"], ["Dios", "God"], ["y", "and"], ["colaborador", "fellowlabourer"], ["nuestro", "our"], ["en", "in"], ["el", "the"], ["evangelio", "gospel"], ["de", "of"], ["Cristo,", "Christ,"], ["para", "for"], ["confirmaros", "and"], ["y", "and"], ["exhortaros", "exhort"], ["en", "in"], ["vuestra", "your"], ["fe,", "faith,"]]},
  {num:3,words:[["a", "to"], ["fin", "end"], ["de", "of"], ["que", "that"], ["nadie", "no-one"], ["se", "[refl.]"], ["inquiete", "moved"], ["por", "by/for"], ["estas", "these"], ["tribulaciones,", "tribulations,"], ["porque", "because"], ["vosotros", "you"], ["mismos", "selves"], ["sabéis", "you-know"], ["que", "that"], ["hemos", "we-have"], ["sido", "been"], ["puestos", "set"], ["para", "for"], ["esto.", "this."]]},
  {num:4,words:[["Porque", "because"], ["aun", "even"], ["estando", "being"], ["con", "with"], ["vosotros,", "you,"], ["os", "you"], ["predecíamos", "told"], ["que", "that"], ["íbamos", "that"], ["a", "to"], ["pasar", "pass"], ["tribulaciones,", "tribulations,"], ["como", "as"], ["ha", "has"], ["acontecido", "happened"], ["y", "and"], ["bien", "well"], ["sabéis.", "you-know."]]},
  {num:5,words:[["Por", "by/for"], ["lo", "it/him"], ["cual", "which"], ["también", "also"], ["yo,", "I,"], ["no", "not"], ["pudiendo", "no"], ["soportar", "bear"], ["más,", "more,"], ["he", "I-have"], ["enviado", "sent"], ["para", "for"], ["informarme", "to"], ["de", "of"], ["vuestra", "your"], ["fe,", "faith,"], ["no", "not"], ["sea", "let-be/be"], ["que", "that"], ["os", "you"], ["haya", "let-there-be"], ["tentado", "tempted"], ["el", "the"], ["tentador,", "tempted,"], ["y", "and"], ["que", "that"], ["nuestro", "our"], ["trabajo", "work/labor"], ["haya", "let-there-be"], ["sido", "been"], ["en", "in"], ["vano.", "vain."]]},
  {num:6,words:[["Pero", "but"], ["cuando", "when"], ["Timoteo", "timotheus"], ["volvió", "returned"], ["de", "of"], ["vosotros", "you"], ["a", "to"], ["nosotros,", "we,"], ["nos", "us"], ["dio", "gave"], ["buenas", "good"], ["nuevas", "new"], ["de", "of"], ["vuestra", "your"], ["fe", "faith"], ["y", "and"], ["amor,", "love,"], ["y", "and"], ["que", "that"], ["siempre", "always"], ["tenéis", "you-have"], ["gratos", "savours"], ["recuerdos", "remembrances"], ["de", "of"], ["nosotros,", "we,"], ["deseando", "desiring"], ["vernos,", "see-us,"], ["como", "as"], ["también", "also"], ["nosotros", "we"], ["a", "to"], ["vosotros.", "you."]]},
  {num:7,words:[["Por", "by/for"], ["ello,", "it,"], ["hermanos,", "brethren,"], ["recibimos", "we"], ["consuelo", "consolation"], ["con", "with"], ["respecto", "concerning"], ["a", "to"], ["vosotros,", "you,"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["nuestra", "our"], ["necesidad", "need"], ["y", "and"], ["aflicción,", "affliction,"], ["por", "by/for"], ["causa", "cause/sake"], ["de", "of"], ["vuestra", "your"], ["fe;", "faith;"]]},
  {num:8,words:[["porque", "because"], ["ahora", "now"], ["vivimos,", "live,"], ["si", "if"], ["vosotros", "you"], ["estáis", "stand"], ["firmes", "firm"], ["en", "in"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:9,words:[["Por", "by/for"], ["lo", "it/him"], ["cual,", "which,"], ["¿qué", "what"], ["acción", "thanksgiving"], ["de", "of"], ["gracias", "thanks"], ["podremos", "we"], ["dar", "give"], ["a", "to"], ["Dios", "God"], ["por", "by/for"], ["vosotros,", "you,"], ["por", "by/for"], ["todo", "all"], ["el", "the"], ["gozo", "joy"], ["con", "with"], ["que", "that"], ["nos", "us"], ["regocijamos", "joy"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["vosotros", "you"], ["delante", "before"], ["de", "of"], ["nuestro", "our"], ["Dios,", "God,"]]},
  {num:10,words:[["orando", "praying"], ["de", "of"], ["noche", "night"], ["y", "and"], ["de", "of"], ["día", "day"], ["con", "with"], ["gran", "great"], ["fervor,", "might,"], ["para", "for"], ["que", "that"], ["veamos", "see"], ["vuestro", "your"], ["rostro,", "face,"], ["y", "and"], ["para", "for"], ["que", "that"], ["completemos", "which"], ["lo", "it/him"], ["que", "that"], ["falta", "want"], ["a", "to"], ["vuestra", "your"], ["fe?", "faith?"]]},
  {num:11,words:[["Mas", "but"], ["el", "the"], ["mismo", "same"], ["Dios", "God"], ["y", "and"], ["Padre", "father"], ["nuestro,", "our,"], ["y", "and"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo,", "Jesus-Christ,"], ["encaminen", "direct"], ["nuestro", "our"], ["viaje", "journey"], ["a", "to"], ["vosotros.", "you."]]},
  {num:12,words:[["Y", "and"], ["el", "the"], ["Señor", "Lord"], ["os", "you"], ["multiplique", "make"], ["y", "and"], ["os", "you"], ["haga", "let-do"], ["abundar", "and"], ["en", "in"], ["amor", "love"], ["unos", "some"], ["para", "for"], ["con", "with"], ["otros,", "others,"], ["y", "and"], ["para", "for"], ["con", "with"], ["todos,", "all,"], ["como", "as"], ["también", "also"], ["lo", "it/him"], ["es", "is"], ["de", "of"], ["nosotros", "we"], ["para", "for"], ["con", "with"], ["vosotros;", "you;"]]},
  {num:13,words:[["para", "for"], ["que", "that"], ["sean", "let-be"], ["confirmados", "whichs"], ["vuestros", "your"], ["corazones,", "hearts,"], ["irreprensibles", "of"], ["en", "in"], ["santidad", "holiness"], ["delante", "before"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["en", "in"], ["la", "the"], ["venida", "coming"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["con", "with"], ["todos", "all"], ["sus", "his/her"], ["santos.", "saints."]]},
];
renderVerseSet(v3, '1th-ch3-verses');

var v4 = [
  {num:1,words:[["Por", "by/for"], ["lo", "it/him"], ["demás,", "rest/others,"], ["hermanos,", "brethren,"], ["os", "you"], ["rogamos", "beseech"], ["y", "and"], ["exhortamos", "exhort"], ["en", "in"], ["el", "the"], ["Señor", "Lord"], ["Jesús,", "Jesus,"], ["que", "that"], ["de", "of"], ["la", "the"], ["manera", "manner"], ["que", "that"], ["fuisteis", "ye"], ["enseñados", "taughts"], ["por", "by/for"], ["nosotros", "we"], ["de", "of"], ["cómo", "how"], ["os", "you"], ["conviene", "expedient"], ["andar", "walk"], ["y", "and"], ["agradar", "please"], ["a", "to"], ["Dios,", "God,"], ["abundéis", "abound"], ["más", "more"], ["y", "and"], ["más.", "more."]]},
  {num:2,words:[["Porque", "because"], ["ya", "already"], ["sabéis", "you-know"], ["qué", "what"], ["mandamientos", "commandments"], ["os", "you"], ["dimos", "we"], ["de", "of"], ["parte", "part"], ["del", "of-the"], ["Señor", "Lord"], ["Jesús.", "Jesus."]]},
  {num:3,words:[["Porque", "because"], ["la", "the"], ["voluntad", "will"], ["de", "of"], ["Dios", "God"], ["es", "is"], ["vuestra", "your"], ["santificación;", "sanctification;"], ["que", "that"], ["os", "you"], ["apartéis", "ye"], ["de", "of"], ["la", "the"], ["fornicación;", "fornication;"]]},
  {num:4,words:[["que", "that"], ["cada", "each"], ["uno", "one"], ["de", "of"], ["vosotros", "you"], ["sepa", "know"], ["tener", "have"], ["su", "his/her"], ["vaso", "vessel"], ["en", "in"], ["santificación", "sanctification"], ["y", "and"], ["honor;", "honour;"]]},
  {num:5,words:[["no", "not"], ["con", "with"], ["pasión", "the"], ["de", "of"], ["concupiscencia,", "of,"], ["como", "as"], ["los", "the"], ["gentiles", "gentiles"], ["que", "that"], ["no", "not"], ["conocen", "know"], ["a", "to"], ["Dios;", "God;"]]},
  {num:6,words:[["que", "that"], ["ninguno", "none"], ["oprima", "man"], ["ni", "nor"], ["engañe", "deceive"], ["en", "in"], ["nada", "nothing"], ["a", "to"], ["su", "his/her"], ["hermano,", "brother,"], ["porque", "because"], ["el", "the"], ["Señor", "Lord"], ["es", "is"], ["vengador", "blood"], ["de", "of"], ["todo", "all"], ["esto,", "this,"], ["como", "as"], ["ya", "already"], ["os", "you"], ["hemos", "we-have"], ["dicho", "said"], ["y", "and"], ["testificado.", "testified."]]},
  {num:7,words:[["Porque", "because"], ["no", "not"], ["nos", "us"], ["ha", "has"], ["llamado", "called"], ["Dios", "God"], ["a", "to"], ["impureza,", "uncleanness,"], ["sino", "but"], ["a", "to"], ["santificación.", "sanctification."]]},
  {num:8,words:[["Así", "thus"], ["que,", "that,"], ["el", "the"], ["que", "that"], ["menosprecia", "despiseth"], ["esto,", "this,"], ["no", "not"], ["menosprecia", "despiseth"], ["a", "to"], ["hombre,", "man,"], ["sino", "but"], ["a", "to"], ["Dios,", "God,"], ["que", "that"], ["también", "also"], ["nos", "us"], ["dio", "gave"], ["su", "his/her"], ["Espíritu", "Spirit"], ["Santo.", "holy."]]},
  {num:9,words:[["Pero", "but"], ["acerca", "about"], ["del", "of-the"], ["amor", "love"], ["fraternal", "love"], ["no", "not"], ["es", "is"], ["necesario", "needful"], ["que", "that"], ["os", "you"], ["escriba,", "scribe,"], ["porque", "because"], ["vosotros", "you"], ["mismos", "selves"], ["habéis", "you-have"], ["aprendido", "learned"], ["de", "of"], ["Dios", "God"], ["que", "that"], ["os", "you"], ["améis", "love"], ["los", "the"], ["unos", "some"], ["a", "to"], ["los", "the"], ["otros;", "others;"]]},
  {num:10,words:[["y", "and"], ["también", "also"], ["lo", "it/him"], ["hacéis", "do"], ["así", "thus"], ["con", "with"], ["todos", "all"], ["los", "the"], ["hermanos", "brethren"], ["que", "that"], ["están", "are"], ["por", "by/for"], ["toda", "all"], ["Macedonia.", "macedonia."], ["Pero", "but"], ["os", "you"], ["rogamos,", "beseech,"], ["hermanos,", "brethren,"], ["que", "that"], ["abundéis", "that"], ["en", "in"], ["ello", "it"], ["más", "more"], ["y", "and"], ["más;", "more;"]]},
  {num:11,words:[["y", "and"], ["que", "that"], ["procuréis", "ye"], ["tener", "have"], ["tranquilidad,", "to,"], ["y", "and"], ["ocuparos", "and"], ["de", "of"], ["vuestros", "your"], ["asuntos,", "affairs,"], ["y", "and"], ["trabajar", "labor"], ["con", "with"], ["vuestras", "your"], ["manos", "hands"], ["de", "of"], ["la", "the"], ["manera", "manner"], ["que", "that"], ["os", "you"], ["hemos", "we-have"], ["mandado;", "commanded;"]]},
  {num:12,words:[["a", "to"], ["fin", "end"], ["de", "of"], ["que", "that"], ["andéis", "walk"], ["honradamente", "andly"], ["para", "for"], ["con", "with"], ["los", "the"], ["extraños,", "strangers,"], ["y", "and"], ["no", "not"], ["tengáis", "afraid"], ["necesidad", "need"], ["de", "of"], ["nada.", "nothing."]]},
  {num:13,words:[["Tampoco", "neither"], ["queremos,", "us,"], ["hermanos,", "brethren,"], ["que", "that"], ["ignoréis", "you"], ["acerca", "about"], ["de", "of"], ["los", "the"], ["que", "that"], ["duermen,", "them,"], ["para", "for"], ["que", "that"], ["no", "not"], ["os", "you"], ["entristezcáis", "sorrow"], ["como", "as"], ["los", "the"], ["otros", "others"], ["que", "that"], ["no", "not"], ["tienen", "have"], ["esperanza.", "hope."]]},
  {num:14,words:[["Porque", "because"], ["si", "if"], ["creemos", "believe"], ["que", "that"], ["Jesús", "Jesus"], ["murió", "died"], ["y", "and"], ["resucitó,", "raised,"], ["así", "thus"], ["también", "also"], ["traerá", "bring"], ["Dios", "God"], ["con", "with"], ["Jesús", "Jesus"], ["a", "to"], ["los", "the"], ["que", "that"], ["durmieron", "they"], ["en", "in"], ["él.", "he."]]},
  {num:15,words:[["Por", "by/for"], ["lo", "it/him"], ["cual,", "which,"], ["os", "you"], ["decimos", "we"], ["esto", "this"], ["en", "in"], ["palabra", "word"], ["del", "of-the"], ["Señor:", "Lord:"], ["que", "that"], ["nosotros", "we"], ["que", "that"], ["vivimos,", "live,"], ["que", "that"], ["habremos", "and"], ["quedado", "remained"], ["hasta", "until"], ["la", "the"], ["venida", "coming"], ["del", "of-the"], ["Señor,", "Lord,"], ["no", "not"], ["precederemos", "not"], ["a", "to"], ["los", "the"], ["que", "that"], ["durmieron.", "they."]]},
  {num:16,words:[["Porque", "because"], ["el", "the"], ["Señor", "Lord"], ["mismo", "same"], ["con", "with"], ["voz", "voice"], ["de", "of"], ["mando,", "command,"], ["con", "with"], ["voz", "voice"], ["de", "of"], ["arcángel,", "voice,"], ["y", "and"], ["con", "with"], ["trompeta", "trump"], ["de", "of"], ["Dios,", "God,"], ["descenderá", "down"], ["del", "of-the"], ["cielo;", "heaven;"], ["y", "and"], ["los", "the"], ["muertos", "dead"], ["en", "in"], ["Cristo", "Christ"], ["resucitarán", "rise"], ["primero.", "first."]]},
  {num:17,words:[["Luego", "then"], ["nosotros,", "we,"], ["los", "the"], ["que", "that"], ["vivamos,", "live,"], ["los", "the"], ["que", "that"], ["hayamos", "we"], ["quedado,", "remained,"], ["seremos", "saved"], ["arrebatados", "caught"], ["juntamente", "together"], ["con", "with"], ["ellos", "they"], ["en", "in"], ["las", "the"], ["nubes", "clouds"], ["para", "for"], ["recibir", "receive"], ["al", "to-the"], ["Señor", "Lord"], ["en", "in"], ["el", "the"], ["aire,", "air,"], ["y", "and"], ["así", "thus"], ["estaremos", "ever"], ["siempre", "always"], ["con", "with"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:18,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["consolaos", "comfort"], ["los", "the"], ["unos", "some"], ["a", "to"], ["los", "the"], ["otros", "others"], ["con", "with"], ["estas", "these"], ["palabras.", "words."]]},
];
renderVerseSet(v4, '1th-ch4-verses');

var v5 = [
  {num:1,words:[["Pero", "but"], ["acerca", "about"], ["de", "of"], ["los", "the"], ["tiempos", "times"], ["y", "and"], ["de", "of"], ["las", "the"], ["estaciones,", "seasons,"], ["no", "not"], ["tenéis", "you-have"], ["necesidad,", "need,"], ["hermanos,", "brethren,"], ["de", "of"], ["que", "that"], ["yo", "I"], ["os", "you"], ["escriba.", "scribe."]]},
  {num:2,words:[["Porque", "because"], ["vosotros", "you"], ["sabéis", "you-know"], ["perfectamente", "perfectly"], ["que", "that"], ["el", "the"], ["día", "day"], ["del", "of-the"], ["Señor", "Lord"], ["vendrá", "shall-come"], ["así", "thus"], ["como", "as"], ["ladrón", "thief"], ["en", "in"], ["la", "the"], ["noche,", "night,"]]},
  {num:3,words:[["que", "that"], ["cuando", "when"], ["digan:", "say:"], ["Paz", "peace"], ["y", "and"], ["seguridad,", "safety,"], ["entonces", "then"], ["vendrá", "shall-come"], ["sobre", "upon"], ["ellos", "they"], ["destrucción", "destruction"], ["repentina,", "them,"], ["como", "as"], ["los", "the"], ["dolores", "sorrows"], ["a", "to"], ["la", "the"], ["mujer", "woman"], ["encinta,", "child,"], ["y", "and"], ["no", "not"], ["escaparán.", "escape."]]},
  {num:4,words:[["Mas", "but"], ["vosotros,", "you,"], ["hermanos,", "brethren,"], ["no", "not"], ["estáis", "stand"], ["en", "in"], ["tinieblas,", "darkness,"], ["para", "for"], ["que", "that"], ["aquel", "that"], ["día", "day"], ["os", "you"], ["sorprenda", "as"], ["como", "as"], ["ladrón;", "thief;"]]},
  {num:5,words:[["porque", "because"], ["todos", "all"], ["vosotros", "you"], ["sois", "ye-are"], ["hijos", "children"], ["de", "of"], ["luz,", "light,"], ["e", "and"], ["hijos", "children"], ["del", "of-the"], ["día;", "day;"], ["no", "not"], ["somos", "we-are"], ["de", "of"], ["la", "the"], ["noche,", "night,"], ["ni", "nor"], ["de", "of"], ["las", "the"], ["tinieblas.", "darkness."]]},
  {num:6,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["no", "not"], ["durmamos", "sleep,"], ["como", "as"], ["los", "the"], ["demás,", "rest/others,"], ["sino", "but"], ["velemos", "us"], ["y", "and"], ["seamos", "we"], ["sobrios.", "sober."]]},
  {num:7,words:[["Porque", "because"], ["los", "the"], ["que", "that"], ["duermen,", "sleep,"], ["de", "of"], ["noche", "night"], ["duermen;", "night;"], ["y", "and"], ["los", "the"], ["que", "that"], ["se", "[refl.]"], ["emborrachan,", "drunken,"], ["de", "of"], ["noche", "night"], ["se", "[refl.]"], ["emborrachan.", "night."]]},
  {num:8,words:[["Pero", "but"], ["nosotros,", "we,"], ["que", "that"], ["somos", "we-are"], ["del", "of-the"], ["día,", "day,"], ["seamos", "we"], ["sobrios,", "day,"], ["habiéndonos", "the"], ["vestido", "clothed"], ["con", "with"], ["la", "the"], ["coraza", "on"], ["de", "of"], ["la", "the"], ["fe", "faith"], ["y", "and"], ["del", "of-the"], ["amor,", "love,"], ["y", "and"], ["con", "with"], ["la", "the"], ["esperanza", "hope"], ["de", "of"], ["la", "the"], ["salvación", "salvation"], ["como", "as"], ["yelmo.", "salvation."]]},
  {num:9,words:[["Porque", "because"], ["no", "not"], ["nos", "us"], ["ha", "has"], ["puesto", "placed"], ["Dios", "God"], ["para", "for"], ["ira,", "wrath,"], ["sino", "but"], ["para", "for"], ["alcanzar", "to"], ["salvación", "salvation"], ["por", "by/for"], ["medio", "midst"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo,", "Jesus-Christ,"]]},
  {num:10,words:[["quien", "who"], ["murió", "died"], ["por", "by/for"], ["nosotros,", "we,"], ["ya", "already"], ["sea", "let-be/be"], ["que", "that"], ["velemos,", "wake,"], ["o", "or"], ["que", "that"], ["durmamos,", "should,"], ["vivamos", "live"], ["juntamente", "together"], ["con", "with"], ["él.", "he."]]},
  {num:11,words:[["Por", "by/for"], ["lo", "it/him"], ["cual,", "which,"], ["consolaos", "yourselves"], ["los", "the"], ["unos", "some"], ["a", "to"], ["los", "the"], ["otros,", "others,"], ["y", "and"], ["edificaos", "another,"], ["los", "the"], ["unos", "some"], ["a", "to"], ["los", "the"], ["otros,", "others,"], ["así", "thus"], ["como", "as"], ["lo", "it/him"], ["hacéis.", "do."]]},
  {num:12,words:[["Y", "and"], ["os", "you"], ["rogamos,", "beseech,"], ["hermanos,", "brethren,"], ["que", "that"], ["reconozcáis", "to"], ["a", "to"], ["los", "the"], ["que", "that"], ["trabajan", "the"], ["entre", "among"], ["vosotros,", "you,"], ["y", "and"], ["os", "you"], ["presiden", "you"], ["en", "in"], ["el", "the"], ["Señor,", "Lord,"], ["y", "and"], ["os", "you"], ["amonestan;", "you;"]]},
  {num:13,words:[["y", "and"], ["que", "that"], ["los", "the"], ["tengáis", "afraid"], ["en", "in"], ["mucha", "much"], ["estima", "he"], ["por", "by/for"], ["causa", "cause/sake"], ["de", "of"], ["su", "his/her"], ["obra.", "work."], ["Tened", "good"], ["paz", "peace"], ["los", "the"], ["unos", "some"], ["con", "with"], ["los", "the"], ["otros.", "others."]]},
  {num:14,words:[["También", "also"], ["os", "you"], ["rogamos,", "beseech,"], ["hermanos,", "brethren,"], ["que", "that"], ["amonestéis", "brethren,"], ["a", "to"], ["los", "the"], ["que", "that"], ["andan", "walking"], ["desordenadamente,", "without-formly,"], ["que", "that"], ["consoléis", "unruly,"], ["a", "to"], ["los", "the"], ["de", "of"], ["poco", "little"], ["ánimo,", "cheer,"], ["que", "that"], ["sostengáis", "the"], ["a", "to"], ["los", "the"], ["débiles,", "weak,"], ["que", "that"], ["seáis", "you-may-be"], ["pacientes", "toward"], ["para", "for"], ["con", "with"], ["todos.", "all."]]},
  {num:15,words:[["Mirad", "heed"], ["que", "that"], ["ninguno", "none"], ["devuelva", "render"], ["a", "to"], ["otro", "other"], ["mal", "evil"], ["por", "by/for"], ["mal,", "evil,"], ["sino", "but"], ["seguid", "but"], ["lo", "it/him"], ["bueno", "good"], ["siempre", "always"], ["los", "the"], ["unos", "some"], ["para", "for"], ["con", "with"], ["los", "the"], ["otros,", "others,"], ["y", "and"], ["para", "for"], ["con", "with"], ["todos.", "all."]]},
  {num:16,words:[["Estad", "your"], ["siempre", "always"], ["gozosos.", "evermore."]]},
  {num:17,words:[["Orad", "pray"], ["sin", "without"], ["cesar.", "ceasing."]]},
  {num:18,words:[["Dad", "ear"], ["gracias", "thanks"], ["en", "in"], ["todo,", "all,"], ["porque", "because"], ["esta", "this"], ["es", "is"], ["la", "the"], ["voluntad", "will"], ["de", "of"], ["Dios", "God"], ["para", "for"], ["con", "with"], ["vosotros", "you"], ["en", "in"], ["Cristo", "Christ"], ["Jesús.", "Jesus."]]},
  {num:19,words:[["No", "not"], ["apaguéis", "not"], ["el", "the"], ["Espíritu.", "Spirit."]]},
  {num:20,words:[["No", "not"], ["menospreciéis", "not"], ["las", "the"], ["profecías.", "prophecies."]]},
  {num:21,words:[["Examinadlo", "prove"], ["todo;", "all;"], ["retened", "fast"], ["lo", "it/him"], ["bueno.", "good."]]},
  {num:22,words:[["Apartaos", "depart"], ["de", "of"], ["toda", "all"], ["apariencia", "appearance"], ["de", "of"], ["mal.", "evil."]]},
  {num:23,words:[["Y", "and"], ["el", "the"], ["mismo", "same"], ["Dios", "God"], ["de", "of"], ["paz", "peace"], ["os", "you"], ["santifique", "you"], ["por", "by/for"], ["completo;", "utterly;"], ["y", "and"], ["todo", "all"], ["vuestro", "your"], ["ser,", "be,"], ["y", "and"], ["espíritu,", "Spirit,"], ["y", "and"], ["alma", "soul"], ["y", "and"], ["cuerpo", "body"], ["sea", "let-be/be"], ["guardado", "kept"], ["irreprensible", "unto"], ["para", "for"], ["la", "the"], ["venida", "coming"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:24,words:[["Fiel", "faithful"], ["es", "is"], ["el", "the"], ["que", "that"], ["os", "you"], ["ha", "has"], ["llamado,", "called,"], ["quien", "who"], ["también", "also"], ["lo", "it/him"], ["hará.", "shall-make."]]},
  {num:25,words:[["Hermanos,", "brethren,"], ["orad", "pray"], ["por", "by/for"], ["nosotros.", "we."]]},
  {num:26,words:[["Saludad", "salute"], ["a", "to"], ["todos", "all"], ["los", "the"], ["hermanos", "brethren"], ["con", "with"], ["beso", "holy"], ["santo.", "holy."]]},
  {num:27,words:[["Os", "you"], ["encargo,", "charge,"], ["por", "by/for"], ["el", "the"], ["Señor,", "Lord,"], ["que", "that"], ["esta", "this"], ["carta", "divorcement"], ["sea", "let-be/be"], ["leída", "read"], ["a", "to"], ["todos", "all"], ["los", "the"], ["santos", "saints"], ["hermanos.", "brethren."]]},
  {num:28,words:[["La", "the"], ["gracia", "grace"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["sea", "let-be/be"], ["con", "with"], ["vosotros.", "you."], ["Amén.", "amen."]]},
];
renderVerseSet(v5, '1th-ch5-verses');

})();
