(function() {
var v1 = [
  {num:1,words:[["El","the"],["anciano","ancient"],["a","to"],["la","the"],["señora","and"],["elegida","chosen"],["y","and"],["a","to"],["sus","her"],["hijos,","children,"],["a","to"],["quienes","who"],["yo","I"],["amo","love"],["en","in"],["la","the"],["verdad,","truth,"],["y","and"],["no","not"],["solo","alone"],["yo,","I,"],["sino","but"],["también","also"],["todos","all"],["los","the"],["que","that"],["han","they-have"],["conocido","known"],["la","the"],["verdad,","truth,"]]},
  {num:2,words:[["a causa de","because of"], ["la", "the"], ["verdad", "truth"], ["que", "that"], ["permanece","abides"], ["en", "in"], ["nosotros", "we"], ["y", "and"], ["que", "that"], ["estará", "shall-be"], ["perpetuamente", "ever"], ["con", "with"], ["nosotros:", "we:"]]},
  {num:3,words:[["Sean","they-let-be"],["con","with"],["vosotros","you"],["la","the"],["gracia,","grace,"],["la","the"],["misericordia","mercy"],["y","and"],["la","the"],["paz","peace"],["de","of"],["Dios","God"],["el","the"],["Padre","father"],["y","and"],["del","of-the"],["Señor","Lord"],["Jesucristo,","Jesus-Christ,"],["Hijo","son"],["del","of-the"],["Padre,","father,"],["en","in"],["la","the"],["verdad","truth"],["y","and"],["en","in"],["el","the"],["amor.","love."]]},
  {num:4,words:[["Mucho","much"],["me","me"],["he","I-have"],["regocijado","greatly"],["porque","because"],["he","I-have"],["hallado","found"],["a","to"],["algunos","some"],["de","of"],["entre","among"],["tus","your"],["hijos","children"],["que","that"],["andan","they-walk"],["en","in"],["la","the"],["verdad,","truth,"],["tal","such"],["como","as"],["hemos","we-have"],["recibido","received"],["el","the"],["mandamiento","commandment"],["del","of-the"],["Padre.","father."]]},
  {num:5,words:[["Y","and"],["ahora","now"],["te","you"],["ruego,","beseech,"],["señora,","and,"],["no","not"],["como","as"],["escribiéndote","writes"],["un","a"],["nuevo","new"],["mandamiento,","commandment,"],["sino","but"],["el","the"],["que","that"],["hemos","we-have"],["tenido","had"],["desde","from"],["el","the"],["principio,","beginning,"],["que","that"],["nos","us"],["amemos","we-may-love"],["unos","some"],["a","to"],["otros.","others."]]},
  {num:6,words:[["Y","and"],["este","this"],["es","is"],["el","the"],["amor:","love:"],["Que","that"],["andemos","we-may-walk"],["según","according-to"],["sus","his"],["mandamientos.","commandments."],["Este","this"],["es","is"],["el","the"],["mandamiento:","commandment:"],["Que","that"],["andéis","you-may-walk"],["en","in"],["el","the"],["amor,","love,"],["como","as"],["habéis","you-have"],["oído","heard"],["desde","from"],["el","the"],["principio.","beginning."]]},
  {num:7,words:[["Porque","because"],["muchos","many"],["engañadores","deceivers"],["han","they-have"],["salido","gone-out"],["al","to-the"],["mundo,","world,"],["quienes","who"],["no","not"],["confiesan","they-confess"],["que","that"],["Jesucristo","Jesus-Christ"],["ha","has"],["venido","come"],["en","in"],["carne.","flesh."],["Este","this"],["es","is"],["el","the"],["engañador","a"],["y","and"],["el","the"],["anticristo.","antichrist."]]},
  {num:8,words:[["Mirad","you-heed"],["por","for"],["vosotros","you"],["mismos,","selves,"],["para que","that"],["no","not"],["perdamos","we-may-lose"],["las","the"],["cosas","things"],["que","that"],["hemos","we-have"],["logrado,","obtained,"],["sino que","but"],["recibamos","we-receive"],["el","the"],["galardón","reward"],["completo.","full."]]},
  {num:9,words:[["Todo","all"],["el","the"],["que","that"],["se","himself"],["desvía","diverts"],["y","and"],["no","not"],["persevera","perseveres"],["en","in"],["la","the"],["doctrina","doctrine"],["de","of"],["Cristo","Christ"],["no","not"],["tiene","has"],["a","to"],["Dios;","God;"],["el","the"],["que","that"],["persevera","perseveres"],["en","in"],["la","the"],["doctrina","doctrine"],["de","of"],["Cristo,","Christ,"],["ese","that"],["sí","yes"],["tiene","has"],["al","to-the"],["Padre","father"],["y","and"],["al","to-the"],["Hijo.","son."]]},
  {num:10,words:[["Si","if"],["alguno","some"],["viene","comes"],["a","to"],["vosotros","you"],["y","and"],["no","not"],["trae","brings"],["esta","this"],["doctrina,","doctrine,"],["no","not"],["lo","him"],["recibáis","you-receive"],["en","in"],["casa","house"],["ni","nor"],["le","him"],["digáis:","you-may-say:"],["¡Bienvenido!","speed!"]]},
  {num:11,words:[["Porque","because"],["el","the"],["que","that"],["le","him"],["dice","says"],["bienvenido","speed"],["participa","participates"],["en","in"],["sus","his"],["malas","evil"],["obras.","works."]]},
  {num:12,words:[["Aunque","although"],["tengo","I-have"],["muchas","many"],["cosas","things"],["que","that"],["escribiros,","write,"],["no","not"],["he","I-have"],["querido","lord"],["comunicarlas","communicates"],["por medio de","by means of"],["papel","paper"],["y","and"],["tinta,","inks,"],["pues","for"],["espero","I-trust"],["ir","to-go"],["a","to"],["vosotros","you"],["y","and"],["hablar","to-speak"],["cara","face"],["a","to"],["cara,","face,"],["para que","that"],["nuestro","our"],["gozo","joy"],["sea","be"],["completo.","full."]]},
  {num:13,words:[["Los","the"],["hijos","children"],["de","of"],["tu","your"],["hermana","sister"],["elegida","chosen"],["te","you"],["saludan.","salute."],["Amén.","Amen."]]},
];
renderVerseSet(v1, '2jn-ch1-verses');

})();
