(function() {
var v1 = [
  {num:1,words:[["Pablo,", "Paul,"], ["y", "and"], ["Silvano", "silvanus,"], ["y", "and"], ["Timoteo,", "timotheus,"], ["a", "to"], ["la", "the"], ["iglesia", "church"], ["de", "of"], ["los", "the"], ["tesalonicenses", "thessalonians"], ["en", "in"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["y", "and"], ["en", "in"], ["el", "the"], ["Señor", "Lord"], ["Jesucristo:", "Jesus-Christ:"]]},
  {num:2,words:[["Gracia", "grace"], ["y", "and"], ["paz", "peace"], ["a", "to"], ["vosotros,", "you,"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["y", "and"], ["del", "of-the"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:3,words:[["Debemos", "we-must"], ["siempre", "always"], ["dar", "give"], ["gracias", "thanks"], ["a", "to"], ["Dios", "God"], ["por", "by/for"], ["vosotros,", "you,"], ["hermanos,", "brethren,"], ["como", "as"], ["es", "is"], ["justo,", "just/righteous,"], ["por", "by/for"], ["cuanto", "as-much-as"], ["vuestra", "your"], ["fe", "faith"], ["va", "goes"], ["creciendo", "in"], ["mucho,", "much,"], ["y", "and"], ["abunda", "the"], ["el", "the"], ["amor", "love"], ["de", "of"], ["cada", "each"], ["uno", "one"], ["de", "of"], ["vosotros", "you"], ["hacia", "toward"], ["los", "the"], ["demás;", "rest/others;"]]},
  {num:4,words:[["tanto,", "therefore,"], ["que", "that"], ["nosotros", "we"], ["mismos", "selves"], ["nos", "us"], ["gloriamos", "in"], ["de", "of"], ["vosotros", "you"], ["en", "in"], ["las", "the"], ["iglesias", "churches"], ["de", "of"], ["Dios,", "God,"], ["por", "by/for"], ["vuestra", "your"], ["paciencia", "patience"], ["y", "and"], ["fe", "faith"], ["en", "in"], ["todas", "all"], ["vuestras", "your"], ["persecuciones", "persecutions"], ["y", "and"], ["tribulaciones", "tribulations"], ["que", "that"], ["soportáis.", "endure."]]},
  {num:5,words:[["Esto", "this"], ["es", "is"], ["una", "a"], ["demostración", "manifest"], ["del", "of-the"], ["justo", "just/righteous"], ["juicio", "judgment"], ["de", "of"], ["Dios,", "God,"], ["para", "for"], ["que", "that"], ["seáis", "you-may-be"], ["tenidos", "hads"], ["por", "by/for"], ["dignos", "worthy"], ["del", "of-the"], ["reino", "kingdom"], ["de", "of"], ["Dios,", "God,"], ["por", "by/for"], ["el", "the"], ["cual", "which"], ["asimismo", "likewise"], ["padecéis.", "suffer."]]},
  {num:6,words:[["Porque", "because"], ["es", "is"], ["justo", "just/righteous"], ["para", "for"], ["Dios", "God"], ["pagar", "pay"], ["con", "with"], ["tribulación", "tribulation"], ["a", "to"], ["los", "the"], ["que", "that"], ["os", "you"], ["atribulan;", "you;"]]},
  {num:7,words:[["y", "and"], ["a", "to"], ["vosotros,", "you,"], ["que", "that"], ["sois", "ye-are"], ["atribulados,", "troubled,"], ["daros", "give"], ["reposo", "rest"], ["con", "with"], ["nosotros,", "we,"], ["cuando", "when"], ["se", "[refl.]"], ["manifieste", "manifest"], ["el", "the"], ["Señor", "Lord"], ["Jesús", "Jesus"], ["desde", "from"], ["el", "the"], ["cielo", "heaven"], ["con", "with"], ["sus", "his/her"], ["poderosos", "mighty"], ["ángeles,", "angels,"]]},
  {num:8,words:[["en", "in"], ["llama", "calls/flame"], ["de", "of"], ["fuego,", "fire,"], ["para", "for"], ["dar", "give"], ["retribución", "them"], ["a", "to"], ["los", "the"], ["que", "that"], ["no", "not"], ["conocen", "know"], ["a", "to"], ["Dios,", "God,"], ["ni", "nor"], ["obedecen", "obey"], ["el", "the"], ["evangelio", "gospel"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo;", "Jesus-Christ;"]]},
  {num:9,words:[["los", "the"], ["que", "that"], ["serán", "shall-be"], ["castigados", "punished"], ["con", "with"], ["eterna", "eternal"], ["perdición,", "perdition,"], ["separados", "presence"], ["de", "of"], ["la", "the"], ["presencia", "presence"], ["del", "of-the"], ["Señor", "Lord"], ["y", "and"], ["de", "of"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["su", "his/her"], ["poder,", "power/can,"]]},
  {num:10,words:[["cuando", "when"], ["venga", "let-come"], ["en", "in"], ["aquel", "that"], ["día", "day"], ["para", "for"], ["ser", "be"], ["glorificado", "glorified"], ["en", "in"], ["sus", "his/her"], ["santos,", "saints,"], ["y", "and"], ["para", "for"], ["ser", "be"], ["admirado", "in"], ["en", "in"], ["todos", "all"], ["los", "the"], ["que", "that"], ["hayan", "may-have"], ["creído", "believed"], ["(por", "by/for"], ["cuanto", "as-much-as"], ["nuestro", "our"], ["testimonio", "testimony"], ["ha", "has"], ["sido", "been"], ["creído", "believed"], ["entre", "among"], ["vosotros).", "you)."]]},
  {num:11,words:[["Por", "by/for"], ["lo", "it/him"], ["cual,", "which,"], ["asimismo", "likewise"], ["oramos", "always"], ["siempre", "always"], ["por", "by/for"], ["vosotros,", "you,"], ["para", "for"], ["que", "that"], ["nuestro", "our"], ["Dios", "God"], ["os", "you"], ["tenga", "may-have"], ["por", "by/for"], ["dignos", "worthy"], ["del", "of-the"], ["llamamiento,", "calling,"], ["y", "and"], ["colme", "the"], ["de", "of"], ["bondad", "goodness"], ["todo", "all"], ["buen", "cheer"], ["intento,", "goodness,"], ["y", "and"], ["toda", "all"], ["obra", "work"], ["de", "of"], ["fe", "faith"], ["con", "with"], ["poder,", "power/can,"]]},
  {num:12,words:[["para", "for"], ["que", "that"], ["el", "the"], ["nombre", "name"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["sea", "let-be/be"], ["glorificado", "glorified"], ["en", "in"], ["vosotros,", "you,"], ["y", "and"], ["vosotros", "you"], ["en", "in"], ["él,", "he,"], ["por", "by/for"], ["la", "the"], ["gracia", "grace"], ["de", "of"], ["nuestro", "our"], ["Dios", "God"], ["y", "and"], ["del", "of-the"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
];
renderVerseSet(v1, '2th-ch1-verses');

var v2 = [
  {num:1,words:[["Pero", "but"], ["os", "you"], ["rogamos,", "beseech,"], ["hermanos,", "brethren,"], ["en", "in"], ["cuanto", "as-much-as"], ["a", "to"], ["la", "the"], ["venida", "coming"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo,", "Jesus-Christ,"], ["y", "and"], ["a", "to"], ["nuestro", "our"], ["recogimiento", "gathering"], ["con", "with"], ["él,", "he,"]]},
  {num:2,words:[["que", "that"], ["no", "not"], ["cambiéis", "be"], ["fácilmente", "that"], ["vuestro", "your"], ["modo", "manner/way"], ["de", "of"], ["pensar,", "not,"], ["ni", "nor"], ["os", "you"], ["conturbéis,", "be,"], ["ni", "nor"], ["por", "by/for"], ["espíritu,", "Spirit,"], ["ni", "nor"], ["por", "by/for"], ["palabra", "word"], ["ni", "nor"], ["por", "by/for"], ["carta", "divorcement"], ["como", "as"], ["si", "if"], ["fuera", "outside/were"], ["nuestra,", "our,"], ["en", "in"], ["el", "the"], ["sentido", "god"], ["de", "of"], ["que", "that"], ["el", "the"], ["día", "day"], ["del", "of-the"], ["Señor", "Lord"], ["está", "is"], ["cerca.", "near."]]},
  {num:3,words:[["No", "not"], ["os", "you"], ["engañe", "deceive"], ["nadie", "no-one"], ["de", "of"], ["ninguna", "none"], ["manera,", "manner,"], ["porque", "because"], ["no", "not"], ["vendrá", "shall-come"], ["sin", "without"], ["que", "that"], ["antes", "before"], ["venga", "let-come"], ["la", "the"], ["apostasía,", "falling,"], ["y", "and"], ["se", "[refl.]"], ["manifieste", "manifest"], ["el", "the"], ["hombre", "man"], ["de", "of"], ["pecado,", "sin,"], ["el", "the"], ["hijo", "son"], ["de", "of"], ["perdición,", "perdition,"]]},
  {num:4,words:[["oponiéndose", "who"], ["y", "and"], ["levantándose", "arose"], ["contra", "against"], ["todo", "all"], ["lo", "it/him"], ["que", "that"], ["se", "[refl.]"], ["llama", "calls/flame"], ["Dios,", "God,"], ["o", "or"], ["lo", "it/him"], ["que", "that"], ["se", "[refl.]"], ["adora;", "worshipped;"], ["tanto", "therefore"], ["que", "that"], ["se", "[refl.]"], ["sienta", "sitteth"], ["en", "in"], ["el", "the"], ["templo", "temple"], ["de", "of"], ["Dios", "God"], ["como", "as"], ["Dios,", "God,"], ["haciéndose", "doing/making-[refl.]"], ["pasar", "pass"], ["por", "by/for"], ["Dios.", "God."]]},
  {num:5,words:[["¿No", "not"], ["os", "you"], ["acordáis", "remember"], ["de", "of"], ["que", "that"], ["cuando", "when"], ["yo", "I"], ["estaba", "was"], ["todavía", "still/yet"], ["con", "with"], ["vosotros,", "you,"], ["os", "you"], ["decía", "said"], ["esto?", "this?"]]},
  {num:6,words:[["Y", "and"], ["ahora", "now"], ["vosotros", "you"], ["sabéis", "you-know"], ["lo", "it/him"], ["que", "that"], ["impide", "that"], ["que", "that"], ["a", "to"], ["su", "his/her"], ["debido", "due"], ["tiempo", "time"], ["sea", "let-be/be"], ["manifestado.", "manifested."]]},
  {num:7,words:[["Porque", "because"], ["ya", "already"], ["está", "is"], ["actuando", "toing"], ["el", "the"], ["misterio", "mystery"], ["de", "of"], ["la", "the"], ["iniquidad;", "iniquity;"], ["solamente", "only"], ["espera", "thee"], ["hasta", "until"], ["que", "that"], ["sea", "let-be/be"], ["quitado", "taken"], ["de", "of"], ["en", "in"], ["medio", "midst"], ["el", "the"], ["que", "that"], ["ahora", "now"], ["lo", "it/him"], ["impide;", "way;"]]},
  {num:8,words:[["y", "and"], ["entonces", "then"], ["se", "[refl.]"], ["manifestará", "forth"], ["aquel", "that"], ["inicuo,", "wicked,"], ["al", "to-the"], ["que", "that"], ["el", "the"], ["Señor", "Lord"], ["matará", "slay"], ["con", "with"], ["el", "the"], ["espíritu", "Spirit"], ["de", "of"], ["su", "his/her"], ["boca", "mouth"], ["y", "and"], ["destruirá", "destroy"], ["con", "with"], ["el", "the"], ["resplandor", "luster"], ["de", "of"], ["su", "his/her"], ["venida;", "coming;"]]},
  {num:9,words:[["a", "to"], ["aquel", "that"], ["inicuo,", "wicked,"], ["cuyo", "whose"], ["advenimiento", "is"], ["es", "is"], ["según", "according-to"], ["la", "the"], ["obra", "work"], ["de", "of"], ["Satanás,", "Satan,"], ["con", "with"], ["todo", "all"], ["poder,", "power/can,"], ["y", "and"], ["señales,", "signs,"], ["y", "and"], ["prodigios", "wonders"], ["mentirosos,", "and,"]]},
  {num:10,words:[["y", "and"], ["con", "with"], ["todo", "all"], ["engaño", "guile"], ["de", "of"], ["iniquidad", "iniquity"], ["para", "for"], ["los", "the"], ["que", "that"], ["perecen,", "perish,"], ["por", "by/for"], ["cuanto", "as-much-as"], ["no", "not"], ["recibieron", "received"], ["el", "the"], ["amor", "love"], ["de", "of"], ["la", "the"], ["verdad", "truth"], ["para", "for"], ["ser", "be"], ["salvos.", "saved."]]},
  {num:11,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["Dios", "God"], ["les", "them"], ["envía", "sendeth"], ["un", "a"], ["poderoso", "mighty"], ["engaño,", "guile,"], ["para", "for"], ["que", "that"], ["crean", "believe"], ["en", "in"], ["la", "the"], ["mentira,", "lies,"]]},
  {num:12,words:[["a", "to"], ["fin", "end"], ["de", "of"], ["que", "that"], ["sean", "let-be"], ["condenados", "condemned"], ["todos", "all"], ["los", "the"], ["que", "that"], ["no", "not"], ["creyeron", "believed"], ["en", "in"], ["la", "the"], ["verdad,", "truth,"], ["sino", "but"], ["que", "that"], ["se", "[refl.]"], ["complacieron", "pleasure"], ["en", "in"], ["la", "the"], ["iniquidad.", "iniquity."]]},
  {num:13,words:[["Pero", "but"], ["nosotros", "we"], ["debemos", "we-must"], ["dar", "give"], ["siempre", "always"], ["gracias", "thanks"], ["a", "to"], ["Dios", "God"], ["por", "by/for"], ["vosotros,", "you,"], ["hermanos", "brethren"], ["amados", "beloved"], ["por", "by/for"], ["el", "the"], ["Señor,", "Lord,"], ["de", "of"], ["que", "that"], ["Dios", "God"], ["os", "you"], ["haya", "let-there-be"], ["escogido", "chosen"], ["desde", "from"], ["el", "the"], ["principio", "beginning"], ["para", "for"], ["salvación,", "salvation,"], ["mediante", "through"], ["la", "the"], ["santificación", "sanctification"], ["por", "by/for"], ["el", "the"], ["Espíritu", "Spirit"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["fe", "faith"], ["en", "in"], ["la", "the"], ["verdad;", "truth;"]]},
  {num:14,words:[["para", "for"], ["lo", "it/him"], ["cual", "which"], ["os", "you"], ["llamó", "called"], ["por", "by/for"], ["medio", "midst"], ["de", "of"], ["nuestro", "our"], ["evangelio,", "gospel,"], ["para", "for"], ["alcanzar", "to"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:15,words:[["Así", "thus"], ["que,", "that,"], ["hermanos,", "brethren,"], ["permaneced", "in"], ["firmes", "firm"], ["y", "and"], ["retened", "the"], ["las", "the"], ["enseñanzas", "ofs"], ["que", "that"], ["habéis", "you-have"], ["aprendido,", "learned,"], ["sea", "let-be/be"], ["por", "by/for"], ["palabra,", "word,"], ["o", "or"], ["por", "by/for"], ["carta", "divorcement"], ["nuestra.", "our."]]},
  {num:16,words:[["Que", "that"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["mismo", "same"], ["y", "and"], ["Dios,", "God,"], ["nuestro", "our"], ["Padre,", "father,"], ["quien", "who"], ["nos", "us"], ["amó,", "loved,"], ["y", "and"], ["nos", "us"], ["dio", "gave"], ["consuelo", "consolation"], ["eterno,", "eternal,"], ["y", "and"], ["buena", "good"], ["esperanza", "hope"], ["mediante", "through"], ["la", "the"], ["gracia,", "grace,"]]},
  {num:17,words:[["consuele", "comfort"], ["vuestros", "your"], ["corazones,", "hearts,"], ["y", "and"], ["os", "you"], ["confirme", "to"], ["en", "in"], ["toda", "all"], ["buena", "good"], ["palabra", "word"], ["y", "and"], ["obra.", "work."]]},
];
renderVerseSet(v2, '2th-ch2-verses');

var v3 = [
  {num:1,words:[["Por", "by/for"], ["lo", "it/him"], ["demás,", "rest/others,"], ["hermanos,", "brethren,"], ["orad", "pray"], ["por", "by/for"], ["nosotros,", "we,"], ["para", "for"], ["que", "that"], ["la", "the"], ["palabra", "word"], ["del", "of-the"], ["Señor", "Lord"], ["avance", "course,"], ["y", "and"], ["sea", "let-be/be"], ["glorificada", "glorified"], ["así", "thus"], ["como", "as"], ["lo", "it/him"], ["fue", "was/went"], ["entre", "among"], ["vosotros,", "you,"]]},
  {num:2,words:[["y", "and"], ["para", "for"], ["que", "that"], ["seamos", "we"], ["librados", "delivered"], ["de", "of"], ["hombres", "men"], ["perversos", "men"], ["y", "and"], ["malos,", "spirits,"], ["porque", "because"], ["no", "not"], ["es", "is"], ["de", "of"], ["todos", "all"], ["la", "the"], ["fe.", "faith."]]},
  {num:3,words:[["Pero", "but"], ["fiel", "faithful"], ["es", "is"], ["el", "the"], ["Señor,", "Lord,"], ["que", "that"], ["os", "you"], ["fortalecerá", "shall-strengthen"], ["y", "and"], ["guardará", "keep"], ["del", "of-the"], ["mal.", "evil."]]},
  {num:4,words:[["Y", "and"], ["tenemos", "we-have"], ["confianza", "confidence"], ["en", "in"], ["el", "the"], ["Señor", "Lord"], ["con", "with"], ["respecto", "respect/concerning"], ["a", "to"], ["vosotros,", "you,"], ["en", "in"], ["que", "that"], ["hacéis", "do"], ["y", "and"], ["haréis", "servile"], ["lo", "it/him"], ["que", "that"], ["os", "you"], ["hemos", "we-have"], ["mandado.", "commanded."]]},
  {num:5,words:[["Y", "and"], ["el", "the"], ["Señor", "Lord"], ["encamine", "direct"], ["vuestros", "your"], ["corazones", "hearts"], ["al", "to-the"], ["amor", "love"], ["de", "of"], ["Dios,", "God,"], ["y", "and"], ["a", "to"], ["la", "the"], ["paciencia", "patience"], ["de", "of"], ["Cristo.", "Christ."]]},
  {num:6,words:[["Pero", "but"], ["os", "you"], ["mandamos,", "command,"], ["hermanos,", "brethren,"], ["en", "in"], ["el", "the"], ["nombre", "name"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo,", "Jesus-Christ,"], ["que", "that"], ["os", "you"], ["apartéis", "ye"], ["de", "of"], ["todo", "all"], ["hermano", "brother"], ["que", "that"], ["ande", "his"], ["desordenadamente,", "without-formly,"], ["y", "and"], ["no", "not"], ["conforme", "according-to"], ["a", "to"], ["la", "the"], ["enseñanza", "of"], ["que", "that"], ["recibieron", "received"], ["de", "of"], ["nosotros.", "we."]]},
  {num:7,words:[["Porque", "because"], ["vosotros", "you"], ["mismos", "selves"], ["sabéis", "you-know"], ["de", "of"], ["qué", "what"], ["manera", "manner"], ["debéis", "suppose"], ["imitarnos,", "for,"], ["pues", "for"], ["no", "not"], ["anduvimos", "not"], ["desordenadamente", "without-formly"], ["entre", "among"], ["vosotros,", "you,"]]},
  {num:8,words:[["ni", "nor"], ["comimos", "did"], ["de", "of"], ["balde", "for"], ["el", "the"], ["pan", "bread"], ["de", "of"], ["nadie;", "no-one;"], ["sino", "but"], ["que", "that"], ["trabajamos", "wrought"], ["arduamente", "with"], ["y", "and"], ["con", "with"], ["fatiga", "of"], ["de", "of"], ["noche", "night"], ["y", "and"], ["de", "of"], ["día,", "day,"], ["para", "for"], ["no", "not"], ["ser", "be"], ["gravosos", "chargeable"], ["a", "to"], ["ninguno", "none"], ["de", "of"], ["vosotros;", "you;"]]},
  {num:9,words:[["no", "not"], ["porque", "because"], ["no", "not"], ["tuviésemos", "have"], ["autoridad,", "authority,"], ["sino", "but"], ["para", "for"], ["daros", "give"], ["en", "in"], ["nosotros", "we"], ["un", "a"], ["ejemplo,", "example,"], ["a", "to"], ["fin", "end"], ["de", "of"], ["que", "that"], ["nos", "us"], ["imitaseis.", "us."]]},
  {num:10,words:[["Porque", "because"], ["aun", "even"], ["estando", "being"], ["con", "with"], ["vosotros,", "you,"], ["os", "you"], ["mandábamos", "was-commanding"], ["esto:", "this:"], ["Que", "that"], ["si", "if"], ["alguno", "some"], ["no", "not"], ["quiere", "if"], ["trabajar,", "labor,"], ["que", "that"], ["tampoco", "neither"], ["coma.", "eateth."]]},
  {num:11,words:[["Porque", "because"], ["oímos", "heard"], ["que", "that"], ["algunos", "some"], ["de", "of"], ["entre", "among"], ["vosotros", "you"], ["andan", "walking"], ["desordenadamente,", "without-formly,"], ["no", "not"], ["trabajando", "with"], ["en", "in"], ["nada,", "nothing,"], ["sino", "but"], ["entremetiéndose", "all,"], ["en", "in"], ["lo", "it/him"], ["ajeno.", "busybodies."]]},
  {num:12,words:[["Y", "and"], ["a", "to"], ["los", "the"], ["tales", "such"], ["les", "them"], ["mandamos", "command"], ["y", "and"], ["exhortamos", "exhort"], ["por", "by/for"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["que,", "that,"], ["trabajando", "with"], ["con", "with"], ["sosiego,", "work,"], ["coman", "eat"], ["su", "his/her"], ["propio", "own"], ["pan.", "bread."]]},
  {num:13,words:[["Pero", "but"], ["vosotros,", "you,"], ["hermanos,", "brethren,"], ["no", "not"], ["os", "you"], ["canséis", "weary"], ["de", "of"], ["hacer", "make/do"], ["el", "the"], ["bien.", "well."]]},
  {num:14,words:[["Y", "and"], ["si", "if"], ["alguno", "some"], ["no", "not"], ["obedece", "obey"], ["nuestra", "our"], ["palabra", "word"], ["por", "by/for"], ["carta,", "divorcement,"], ["señaladle,", "note,"], ["y", "and"], ["no", "not"], ["os", "you"], ["juntéis", "no"], ["con", "with"], ["él,", "he,"], ["para", "for"], ["que", "that"], ["se", "[refl.]"], ["avergüence.", "ashamed."]]},
  {num:15,words:[["Pero", "but"], ["no", "not"], ["lo", "it/him"], ["tengáis", "afraid"], ["por", "by/for"], ["enemigo,", "enemy,"], ["sino", "but"], ["amonestadle", "admonish"], ["como", "as"], ["a", "to"], ["hermano.", "brother."]]},
  {num:16,words:[["Y", "and"], ["el", "the"], ["mismo", "same"], ["Señor", "Lord"], ["de", "of"], ["paz", "peace"], ["os", "you"], ["dé", "yield"], ["siempre", "always"], ["paz", "peace"], ["en", "in"], ["toda", "all"], ["circunstancia.", "means."], ["El", "the"], ["Señor", "Lord"], ["sea", "let-be/be"], ["con", "with"], ["todos", "all"], ["vosotros.", "you."]]},
  {num:17,words:[["Esta", "this"], ["salutación", "salutation"], ["es", "is"], ["de", "of"], ["mi", "my"], ["propia", "own"], ["mano,", "hand,"], ["de", "of"], ["Pablo,", "Paul,"], ["que", "that"], ["es", "is"], ["el", "the"], ["signo", "token"], ["en", "in"], ["toda", "all"], ["carta", "divorcement"], ["mía;", "mother;"], ["así", "thus"], ["escribo.", "I-write."]]},
  {num:18,words:[["La", "the"], ["gracia", "grace"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["sea", "let-be/be"], ["con", "with"], ["todos", "all"], ["vosotros.", "you."], ["Amén.", "amen."]]},
];
renderVerseSet(v3, '2th-ch3-verses');

})();
