(function() {
var v1 = [
  {num:1,words:[["Pablo,", "Paul,"], ["y", "and"], ["Silvano", "silvanus,"], ["y", "and"], ["Timoteo,", "timotheus,"], ["a", "to"], ["la", "the"], ["iglesia", "church"], ["de", "of"], ["los", "the"], ["tesalonicenses", "thessalonians"], ["en", "in"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["y", "and"], ["en", "in"], ["el", "the"], ["Señor", "Lord"], ["Jesucristo:", "Jesus-Christ:"]]},
  {num:2,words:[["Gracia", "grace"], ["y", "and"], ["paz", "peace"], ["a", "to"], ["vosotros,", "you,"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["y", "and"], ["del", "of-the"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:3,words:[["Debemos","we-must"],["siempre","always"],["dar","to-give"],["gracias","thanks"],["a","to"],["Dios","God"],["por","for"],["vosotros,","you,"],["hermanos,","brothers,"],["como","as"],["es","is"],["justo,","righteous,"],["por cuanto","because"],["vuestra","your"],["fe","faith"],["va","goes"],["creciendo","growing"],["mucho,","much,"],["y","and"],["abunda","abounds"],["el","the"],["amor","love"],["de","of"],["cada","each"],["uno","one"],["de","of"],["vosotros","you"],["hacia","toward"],["los","the"],["demás;","others;"]]},
  {num:4,words:[["tanto,","therefore,"],["que","that"],["nosotros","we"],["mismos","selves"],["nos","us"],["gloriamos","in"],["de","of"],["vosotros","you"],["en","in"],["las","the"],["iglesias","churches"],["de","of"],["Dios,","God,"],["por","for"],["vuestra","your"],["paciencia","patience"],["y","and"],["fe","faith"],["en","in"],["todas","all"],["vuestras","your"],["persecuciones","persecutions"],["y","and"],["tribulaciones","tribulations"],["que","that"],["soportáis.","you-endure."]]},
  {num:5,words:[["Esto","this"],["es","is"],["una","a"],["demostración","manifest"],["del","of-the"],["justo","righteous"],["juicio","judgment"],["de","of"],["Dios,","God,"],["para","for"],["que","that"],["seáis","you-may-be"],["tenidos","had"],["por","for"],["dignos","worthy"],["del","of-the"],["reino","kingdom"],["de","of"],["Dios,","God,"],["por","for"],["el","the"],["cual","which"],["asimismo","likewise"],["padecéis.","you-suffer."]]},
  {num:6,words:[["Porque","because"],["es","is"],["justo","righteous"],["para","for"],["Dios","God"],["pagar","to-pay"],["con","with"],["tribulación","tribulation"],["a","to"],["los","the"],["que","that"],["os","you"],["atribulan;","you;"]]},
  {num:7,words:[["y","and"],["a","to"],["vosotros,","you,"],["que","that"],["sois","you-are"],["atribulados,","troubled,"],["daros","give"],["reposo","I-rest"],["con","with"],["nosotros,","we,"],["cuando","when"],["se","himself"],["manifieste","manifest"],["el","the"],["Señor","Lord"],["Jesús","Jesus"],["desde","from"],["el","the"],["cielo","heaven"],["con","with"],["sus","his"],["poderosos","mighty"],["ángeles,","angels,"]]},
  {num:8,words:[["en","in"],["llama","flame"],["de","of"],["fuego,","fire,"],["para","for"],["dar","to-give"],["retribución","them"],["a","to"],["los","the"],["que","that"],["no","not"],["conocen","they-know"],["a","to"],["Dios,","God,"],["ni","nor"],["obedecen","they-obey"],["el","the"],["evangelio","gospel"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo;","Jesus-Christ;"]]},
  {num:9,words:[["los","the"],["que","that"],["serán","they-shall-be"],["castigados","punished"],["con","with"],["eterna","eternal"],["perdición,","perdition,"],["separados","presence"],["de","of"],["la","the"],["presencia","presence"],["del","of-the"],["Señor","Lord"],["y","and"],["de","of"],["la","the"],["gloria","glory"],["de","of"],["su","his"],["poder,","power,"]]},
  {num:10,words:[["cuando","when"],["venga","let-come"],["en","in"],["aquel","that"],["día","day"],["para","for"],["ser","be"],["glorificado","glorified"],["en","in"],["sus","his"],["santos,","saints,"],["y","and"],["para","for"],["ser","be"],["admirado","admired"],["en","in"],["todos","all"],["los","the"],["que","that"],["hayan","they-may-have"],["creído","believed"],["(por cuanto","(because"],["nuestro","our"],["testimonio","testimony"],["ha","has"],["sido","been"],["creído","believed"],["entre","among"],["vosotros).","you)."]]},
  {num:11,words:[["Por","for"],["lo","it/him"],["cual,","which,"],["asimismo","likewise"],["oramos","we-always"],["siempre","always"],["por","for"],["vosotros,","you,"],["para","for"],["que","that"],["nuestro","our"],["Dios","God"],["os","you"],["tenga","may-have"],["por","for"],["dignos","worthy"],["del","of-the"],["llamamiento,","calling,"],["y","and"],["colme","may-satisfy"],["de","of"],["bondad","goodness"],["todo","all"],["buen","good"],["intento,","goodness,"],["y","and"],["toda","all"],["obra","work"],["de","of"],["fe","faith"],["con","with"],["poder,","power,"]]},
  {num:12,words:[["para","for"],["que","that"],["el","the"],["nombre","name"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo","Jesus-Christ"],["sea","be"],["glorificado","glorified"],["en","in"],["vosotros,","you,"],["y","and"],["vosotros","you"],["en","in"],["él,","he,"],["por","for"],["la","the"],["gracia","grace"],["de","of"],["nuestro","our"],["Dios","God"],["y","and"],["del","of-the"],["Señor","Lord"],["Jesucristo.","Jesus-Christ."]]},
];
renderVerseSet(v1, '2th-ch1-verses');

var v2 = [
  {num:1,words:[["Pero", "but"], ["os", "you"], ["rogamos,", "beseech,"], ["hermanos,","brothers,"], ["en cuanto a","as for"], ["la", "the"], ["venida", "coming"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo,", "Jesus-Christ,"], ["y", "and"], ["a", "to"], ["nuestro", "our"], ["recogimiento", "gathering"], ["con", "with"], ["él,", "he,"]]},
  {num:2,words:[["que","that"],["no","not"],["cambiéis","you-be"],["fácilmente","that"],["vuestro","your"],["modo","manner"],["de","of"],["pensar,","to-think,"],["ni","nor"],["os","you"],["conturbéis,","be,"],["ni","nor"],["por","by"],["espíritu,","Spirit,"],["ni","nor"],["por","by"],["palabra","word"],["ni","nor"],["por","by"],["carta","divorcement"],["como","as"],["si","if"],["fuera","were"],["nuestra,","our,"],["en","in"],["el","the"],["sentido","god"],["de","of"],["que","that"],["el","the"],["día","day"],["del","of-the"],["Señor","Lord"],["está","is"],["cerca.","near."]]},
  {num:3,words:[["No","not"],["os","you"],["engañe","deceive"],["nadie","no-one"],["de","of"],["ninguna","none"],["manera,","manner,"],["porque","because"],["no","not"],["vendrá","shall-come"],["sin","without"],["que","that"],["antes","before"],["venga","let-come"],["la","the"],["apostasía,","apostasy,"],["y","and"],["se","himself"],["manifieste","manifest"],["el","the"],["hombre","man"],["de","of"],["pecado,","sin,"],["el","the"],["hijo","son"],["de","of"],["perdición,","perdition,"]]},
  {num:4,words:[["oponiéndose","who"],["y","and"],["levantándose","arose"],["contra","against"],["todo","all"],["lo","it/him"],["que","that"],["se","himself"],["llama","calls"],["Dios,","God,"],["o","or"],["lo","it/him"],["que","that"],["se","himself"],["adora;","worshipped;"],["tanto","therefore"],["que","that"],["se","himself"],["sienta","sitts"],["en","in"],["el","the"],["templo","temple"],["de","of"],["Dios","God"],["como","as"],["Dios,","God,"],["haciéndose","doing/making-oneself"],["pasar","to-pass"],["por","for"],["Dios.","God."]]},
  {num:5,words:[["¿No", "not"], ["os", "you"], ["acordáis", "remember"], ["de", "of"], ["que", "that"], ["cuando", "when"], ["yo", "I"], ["estaba", "was"], ["todavía","yet"], ["con", "with"], ["vosotros,", "you,"], ["os", "you"], ["decía", "said"], ["esto?", "this?"]]},
  {num:6,words:[["Y","and"],["ahora","now"],["vosotros","you"],["sabéis","know"],["lo","it/him"],["que","that"],["impide","prevents"],["que","that"],["a","to"],["su","his"],["debido","due"],["tiempo","time"],["sea","be"],["manifestado.","manifested."]]},
  {num:7,words:[["Porque","because"],["ya","already"],["está","is"],["actuando","acting"],["el","the"],["misterio","mystery"],["de","of"],["la","the"],["iniquidad;","iniquity;"],["solamente","only"],["espera","you"],["hasta que","until"],["sea","be"],["quitado","taken"],["de","of"],["en","in"],["medio","midst"],["el","the"],["que","that"],["ahora","now"],["lo","it/him"],["impide;","way;"]]},
  {num:8,words:[["y","and"],["entonces","then"],["se","himself"],["manifestará","forth"],["aquel","that"],["inicuo,","wicked,"],["al","to-the"],["que","that"],["el","the"],["Señor","Lord"],["matará","slay"],["con","with"],["el","the"],["espíritu","Spirit"],["de","of"],["su","his"],["boca","mouth"],["y","and"],["destruirá","destroy"],["con","with"],["el","the"],["resplandor","luster"],["de","of"],["su","his"],["venida;","coming;"]]},
  {num:9,words:[["a","to"],["aquel","that"],["inicuo,","wicked,"],["cuyo","whose"],["advenimiento","is"],["es","is"],["según","according-to"],["la","the"],["obra","work"],["de","of"],["Satanás,","Satan,"],["con","with"],["todo","all"],["poder,","power,"],["y","and"],["señales,","you-signs,"],["y","and"],["prodigios","wonders"],["mentirosos,","and,"]]},
  {num:10,words:[["y","and"],["con","with"],["todo","all"],["engaño","guile"],["de","of"],["iniquidad","iniquity"],["para","for"],["los","the"],["que","that"],["perecen,","they-perish,"],["por cuanto","because"],["no","not"],["recibieron","they-received"],["el","the"],["amor","love"],["de","of"],["la","the"],["verdad","truth"],["para","for"],["ser","be"],["salvos.","saved."]]},
  {num:11,words:[["Por tanto,","therefore,"],["Dios","God"],["les","them"],["envía","sends"],["un","a"],["poderoso","mighty"],["engaño,","guile,"],["para","for"],["que","that"],["crean","they-believe"],["en","in"],["la","the"],["mentira,","lies,"]]},
  {num:12,words:[["a fin de que","so that"],["sean","they-let-be"],["condenados","condemned"],["todos","all"],["los","the"],["que","that"],["no","not"],["creyeron","they-believed"],["en","in"],["la","the"],["verdad,","truth,"],["sino","but"],["que","that"],["se","itself"],["complacieron","pleasure"],["en","in"],["la","the"],["iniquidad.","iniquity."]]},
  {num:13,words:[["Pero","but"],["nosotros","we"],["debemos","must"],["dar","to-give"],["siempre","always"],["gracias","thanks"],["a","to"],["Dios","God"],["por","for"],["vosotros,","you,"],["hermanos","brothers"],["amados","beloved"],["por","for"],["el","the"],["Señor,","Lord,"],["de","of"],["que","that"],["Dios","God"],["os","you"],["haya","let-there-be"],["escogido","chosen"],["desde","from"],["el","the"],["principio","beginning"],["para","for"],["salvación,","salvation,"],["mediante","through"],["la","the"],["santificación","sanctification"],["por","for"],["el","the"],["Espíritu","Spirit"],["y","and"],["por","for"],["la","the"],["fe","faith"],["en","in"],["la","the"],["verdad;","truth;"]]},
  {num:14,words:[["para","for"],["lo","it/him"],["cual","which"],["os","you"],["llamó","called"],["por medio de","by means of"],["nuestro","our"],["evangelio,","gospel,"],["para","for"],["alcanzar","to-reach"],["la","the"],["gloria","glory"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo.","Jesus-Christ."]]},
  {num:15,words:[["Así que,","so,"],["hermanos,","brothers,"],["permaneced","you-remain"],["firmes","you-firm"],["y","and"],["retened","you-retain"],["las","the"],["enseñanzas","teachings"],["que","that"],["habéis","you-have"],["aprendido,","learned,"],["sea","be"],["por","by"],["palabra,","word,"],["o","or"],["por","by"],["carta","divorcement"],["nuestra.","our."]]},
  {num:16,words:[["Que", "that"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["mismo", "same"], ["y", "and"], ["Dios,", "God,"], ["nuestro", "our"], ["Padre,", "father,"], ["quien", "who"], ["nos", "us"], ["amó,", "loved,"], ["y", "and"], ["nos", "us"], ["dio", "gave"], ["consuelo", "consolation"], ["eterno,", "eternal,"], ["y", "and"], ["buena", "good"], ["esperanza", "hope"], ["mediante", "through"], ["la", "the"], ["gracia,", "grace,"]]},
  {num:17,words:[["consuele","comfort"],["vuestros","your"],["corazones,","hearts,"],["y","and"],["os","you"],["confirme","may-confirm"],["en","in"],["toda","all"],["buena","good"],["palabra","word"],["y","and"],["obra.","work."]]},
];
renderVerseSet(v2, '2th-ch2-verses');

var v3 = [
  {num:1,words:[["Por","for"],["lo","it"],["demás,","rest,"],["hermanos,","brothers,"],["orad","you-pray"],["por","for"],["nosotros,","we,"],["para","for"],["que","that"],["la","the"],["palabra","word"],["del","of-the"],["Señor","Lord"],["avance","course,"],["y","and"],["sea","be"],["glorificada","glorified"],["así","thus"],["como","as"],["lo","it"],["fue","was"],["entre","among"],["vosotros,","you,"]]},
  {num:2,words:[["y", "and"], ["para", "for"], ["que", "that"], ["seamos", "we"], ["librados", "delivered"], ["de", "of"], ["hombres", "men"], ["perversos", "men"], ["y", "and"], ["malos,", "spirits,"], ["porque", "because"], ["no", "not"], ["es", "is"], ["de", "of"], ["todos", "all"], ["la", "the"], ["fe.", "faith."]]},
  {num:3,words:[["Pero","but"],["fiel","faithful"],["es","is"],["el","the"],["Señor,","Lord,"],["que","that"],["os","you"],["fortalecerá","shall-strengthen"],["y","and"],["guardará","will-keep"],["del","of-the"],["mal.","evil."]]},
  {num:4,words:[["Y","and"],["tenemos","we-have"],["confianza","confidence"],["en","in"],["el","the"],["Señor","Lord"],["con","with"],["respecto","concerning"],["a","to"],["vosotros,","you,"],["en","in"],["que","that"],["hacéis","you-do"],["y","and"],["haréis","you-servile"],["lo","it/him"],["que","that"],["os","you"],["hemos","we-have"],["mandado.","commanded."]]},
  {num:5,words:[["Y", "and"], ["el", "the"], ["Señor", "Lord"], ["encamine", "direct"], ["vuestros", "your"], ["corazones", "hearts"], ["al", "to-the"], ["amor", "love"], ["de", "of"], ["Dios,", "God,"], ["y", "and"], ["a", "to"], ["la", "the"], ["paciencia", "patience"], ["de", "of"], ["Cristo.", "Christ."]]},
  {num:6,words:[["Pero","but"],["os","you"],["mandamos,","command,"],["hermanos,","brothers,"],["en","in"],["el","the"],["nombre","name"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo,","Jesus-Christ,"],["que","that"],["os","you"],["apartéis","you"],["de","of"],["todo","all"],["hermano","brother"],["que","that"],["ande","may-walk"],["desordenadamente,","without-formly,"],["y","and"],["no","not"],["conforme","according-to"],["a","to"],["la","the"],["enseñanza","teaching"],["que","that"],["recibieron","they-received"],["de","of"],["nosotros.","we."]]},
  {num:7,words:[["Porque","because"],["vosotros","you"],["mismos","selves"],["sabéis","you-know"],["de","of"],["qué","what"],["manera","manner"],["debéis","you-suppose"],["imitarnos,","imitate,"],["pues","for"],["no","not"],["anduvimos","we-walked"],["desordenadamente","without-formly"],["entre","among"],["vosotros,","you,"]]},
  {num:8,words:[["ni","nor"],["comimos","we-did"],["de","of"],["balde","for"],["el","the"],["pan","bread"],["de","of"],["nadie;","no-one;"],["sino","but"],["que","that"],["trabajamos","we-wrought"],["arduamente","with"],["y","and"],["con","with"],["fatiga","of"],["de","of"],["noche","night"],["y","and"],["de","of"],["día,","day,"],["para","for"],["no","not"],["ser","be"],["gravosos","chargeable"],["a","to"],["ninguno","none"],["de","of"],["vosotros;","you;"]]},
  {num:9,words:[["no","not"],["porque","because"],["no","not"],["tuviésemos","we-have"],["autoridad,","authority,"],["sino","but"],["para","for"],["daros","give"],["en","in"],["nosotros","we"],["un","a"],["ejemplo,","example,"],["a fin de que","so that"],["nos","us"],["imitaseis.","you-might-imitate."]]},
  {num:10,words:[["Porque","because"],["aun","even"],["estando","being"],["con","with"],["vosotros,","you,"],["os","you"],["mandábamos","was-commanding"],["esto:","this:"],["Que","that"],["si","if"],["alguno","some"],["no","not"],["quiere","wants"],["trabajar,","labor,"],["que","that"],["tampoco","neither"],["coma.","eats."]]},
  {num:11,words:[["Porque","because"],["oímos","we-heard"],["que","that"],["algunos","some"],["de","of"],["entre","among"],["vosotros","you"],["andan","walk"],["desordenadamente,","without-formly,"],["no","not"],["trabajando","working"],["en","in"],["nada,","nothing,"],["sino","but"],["entremetiéndose","all,"],["en","in"],["lo","it/him"],["ajeno.","busybodies."]]},
  {num:12,words:[["Y","and"],["a","to"],["los","the"],["tales","such"],["les","them"],["mandamos","we-command"],["y","and"],["exhortamos","we-exhort"],["por","by"],["nuestro","our"],["Señor","Lord"],["Jesucristo","Jesus-Christ"],["que,","that,"],["trabajando","working"],["con","with"],["sosiego,","work,"],["coman","they-may-eat"],["su","his"],["propio","own"],["pan.","bread."]]},
  {num:13,words:[["Pero","but"],["vosotros,","you,"],["hermanos,","brothers,"],["no","not"],["os","you"],["canséis","weary"],["de","of"],["hacer","do"],["el","the"],["bien.","well."]]},
  {num:14,words:[["Y","and"],["si","if"],["alguno","some"],["no","not"],["obedece","obey"],["nuestra","our"],["palabra","word"],["por","by"],["carta,","divorcement,"],["señaladle,","note,"],["y","and"],["no","not"],["os","you"],["juntéis","you-may-gather"],["con","with"],["él,","he,"],["para","for"],["que","that"],["se","himself"],["avergüence.","ashamed."]]},
  {num:15,words:[["Pero","but"],["no","not"],["lo","him"],["tengáis","you-afraid"],["por","for"],["enemigo,","enemy,"],["sino","but"],["amonestadle","admonish"],["como","as"],["a","to"],["hermano.","brother."]]},
  {num:16,words:[["Y", "and"], ["el", "the"], ["mismo", "same"], ["Señor", "Lord"], ["de", "of"], ["paz", "peace"], ["os", "you"], ["dé","give"], ["siempre", "always"], ["paz", "peace"], ["en", "in"], ["toda", "all"], ["circunstancia.", "means."], ["El", "the"], ["Señor", "Lord"], ["sea","be"], ["con", "with"], ["todos", "all"], ["vosotros.", "you."]]},
  {num:17,words:[["Esta", "this"], ["salutación", "salutation"], ["es", "is"], ["de", "of"], ["mi", "my"], ["propia", "own"], ["mano,", "hand,"], ["de", "of"], ["Pablo,", "Paul,"], ["que", "that"], ["es", "is"], ["el", "the"], ["signo", "token"], ["en", "in"], ["toda", "all"], ["carta", "divorcement"], ["mía;", "mother;"], ["así", "thus"], ["escribo.", "I-write."]]},
  {num:18,words:[["La", "the"], ["gracia", "grace"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["sea","be"], ["con", "with"], ["todos", "all"], ["vosotros.", "you."], ["Amén.", "amen."]]},
];
renderVerseSet(v3, '2th-ch3-verses');

})();
