(function() {
var v1 = [
  {num:1,words:[["El", "the"], ["anciano", "ancient"], ["al", "to-the"], ["muy", "very"], ["amado", "beloved"], ["Gayo,", "gaius,"], ["a", "to"], ["quien", "who"], ["yo", "I"], ["amo", "master"], ["en", "in"], ["la", "the"], ["verdad.", "truth."]]},
  {num:2,words:[["Amado,", "beloved,"], ["yo", "I"], ["deseo", "desire"], ["que", "that"], ["tú", "thou"], ["seas", "mayest"], ["prosperado", "prospered"], ["en", "in"], ["todas", "all"], ["las", "the"], ["cosas", "things"], ["y", "and"], ["que", "that"], ["tengas", "afraid"], ["salud,", "health,"], ["así", "thus"], ["como", "as"], ["prospera", "the"], ["tu", "thy"], ["alma.", "soul."]]},
  {num:3,words:[["Pues", "for"], ["me", "me"], ["regocijé", "rejoice"], ["mucho", "much"], ["cuando", "when"], ["vinieron", "came"], ["los", "the"], ["hermanos", "brethren"], ["y", "and"], ["dieron", "gave"], ["testimonio", "testimony"], ["de", "of"], ["la", "the"], ["verdad", "truth"], ["que", "that"], ["hay", "there-is"], ["en", "in"], ["ti,", "thee,"], ["de", "of"], ["cómo", "how"], ["andas", "walk"], ["en", "in"], ["la", "the"], ["verdad.", "truth."]]},
  {num:4,words:[["No", "not"], ["tengo", "I-have"], ["yo", "I"], ["mayor", "greater"], ["gozo", "joy"], ["que", "that"], ["este,", "this,"], ["el", "the"], ["oír", "hear"], ["que", "that"], ["mis", "my"], ["hijos", "children"], ["andan", "walking"], ["en", "in"], ["la", "the"], ["verdad.", "truth."]]},
  {num:5,words:[["Amado,", "beloved,"], ["fielmente", "faithfully"], ["actúas", "ins"], ["en", "in"], ["todo", "all"], ["lo", "it/him"], ["que", "that"], ["haces", "doest"], ["para", "for"], ["con", "with"], ["los", "the"], ["hermanos", "brethren"], ["y", "and"], ["para", "for"], ["con", "with"], ["los", "the"], ["extranjeros,", "strangers,"]]},
  {num:6,words:[["quienes", "who"], ["han", "have"], ["dado", "given"], ["testimonio", "testimony"], ["de", "of"], ["tu", "thy"], ["amor", "love"], ["en", "in"], ["presencia", "presence"], ["de", "of"], ["la", "the"], ["iglesia;", "church;"], ["y", "and"], ["harás", "thou-shalt-make"], ["bien", "well"], ["en", "in"], ["encaminarlos", "a"], ["como", "as"], ["es", "is"], ["digno", "worthy"], ["de", "of"], ["Dios.", "God."]]},
  {num:7,words:[["Porque", "because"], ["ellos", "they"], ["salieron", "went-out"], ["por", "by/for"], ["causa", "cause/sake"], ["del", "of-the"], ["nombre", "name"], ["de", "of"], ["él,", "he,"], ["sin", "without"], ["aceptar", "taking"], ["nada", "nothing"], ["de", "of"], ["los", "the"], ["gentiles.", "gentiles."]]},
  {num:8,words:[["Nosotros,", "we,"], ["pues,", "for,"], ["debemos", "we-must"], ["acoger", "to"], ["a", "to"], ["tales", "such"], ["personas,", "persons,"], ["para", "for"], ["que", "that"], ["seamos", "we"], ["colaboradores", "fellowhelpers"], ["en", "in"], ["la", "the"], ["verdad.", "truth."]]},
  {num:9,words:[["Yo", "I"], ["he", "I-have"], ["escrito", "written"], ["a", "to"], ["la", "the"], ["iglesia;", "church;"], ["pero", "but"], ["Diótrefes,", "who,"], ["que", "that"], ["desea", "desireth"], ["ser", "be"], ["el", "the"], ["primero", "first"], ["entre", "among"], ["ellos,", "they,"], ["no", "not"], ["nos", "us"], ["recibe.", "receiveth."]]},
  {num:10,words:[["Por", "by/for"], ["esta", "this"], ["causa,", "cause/sake,"], ["si", "if"], ["yo", "I"], ["voy,", "whither,"], ["recordaré", "shall-remembrance"], ["las", "the"], ["obras", "works"], ["que", "that"], ["hace,", "does/makes,"], ["parloteando", "he"], ["con", "with"], ["palabras", "words"], ["malignas", "thes"], ["contra", "against"], ["nosotros;", "we;"], ["y", "and"], ["no", "not"], ["contento", "and"], ["con", "with"], ["estas", "these"], ["cosas,", "things,"], ["no", "not"], ["recibe", "receiveth"], ["a", "to"], ["los", "the"], ["hermanos,", "brethren,"], ["y", "and"], ["a", "to"], ["los", "the"], ["que", "that"], ["quieren", "will"], ["recibirlos", "them"], ["se", "[refl.]"], ["lo", "it/him"], ["prohíbe", "and"], ["y", "and"], ["los", "the"], ["echa", "cast"], ["de", "of"], ["la", "the"], ["iglesia.", "church."]]},
  {num:11,words:[["Amado,", "beloved,"], ["no", "not"], ["imites", "not"], ["lo", "it/him"], ["malo,", "evil,"], ["sino", "but"], ["lo", "it/him"], ["bueno.", "good."], ["El", "the"], ["que", "that"], ["hace", "does/makes"], ["lo", "it/him"], ["bueno", "good"], ["es", "is"], ["de", "of"], ["Dios,", "God,"], ["pero", "but"], ["el", "the"], ["que", "that"], ["hace", "does/makes"], ["lo", "it/him"], ["malo", "evil"], ["no", "not"], ["ha", "has"], ["visto", "seen"], ["a", "to"], ["Dios.", "God."]]},
  {num:12,words:[["Todos", "all"], ["dan", "dan"], ["buen", "cheer"], ["testimonio", "testimony"], ["de", "of"], ["Demetrio,", "all,"], ["y", "and"], ["aun", "even"], ["la", "the"], ["verdad", "truth"], ["misma;", "same;"], ["y", "and"], ["también", "also"], ["nosotros", "we"], ["damos", "we"], ["testimonio,", "testimony,"], ["y", "and"], ["vosotros", "you"], ["sabéis", "you-know"], ["que", "that"], ["nuestro", "our"], ["testimonio", "testimony"], ["es", "is"], ["verdadero.", "true."]]},
  {num:13,words:[["Yo", "I"], ["tenía", "had"], ["muchas", "many"], ["cosas", "things"], ["que", "that"], ["escribirte,", "write-thee,"], ["pero", "but"], ["no", "not"], ["quiero", "would"], ["escribírtelas", "write-thee-them"], ["con", "with"], ["tinta", "pen"], ["y", "and"], ["pluma,", "thee,"]]},
  {num:14,words:[["porque", "because"], ["espero", "trust"], ["verte", "thee"], ["en", "in"], ["breve,", "come,"], ["y", "and"], ["hablaremos", "shall-speak"], ["cara", "face"], ["a", "to"], ["cara.", "face."]]},
  {num:15,words:[["La paz sea contigo. Los amigos te saludan. Saluda tú a cada uno de los amigos por su nombre.", ""]]},
];
renderVerseSet(v1, '3jn-ch1-verses');

})();
