(function() {
var v1 = [
  {num:1,words:[["Las", "the"], ["palabras", "words"], ["de", "of"], ["Amós,", "amos,"], ["que", "that"], ["fue", "was/went"], ["uno", "one"], ["de", "of"], ["los", "the"], ["pastores", "pastors"], ["de", "of"], ["Tecoa,", "and,"], ["sobre", "upon"], ["lo", "it/him"], ["que", "that"], ["vio", "saw"], ["acerca", "about"], ["de", "of"], ["Israel", "Israel"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["Uzías,", "uzziah,"], ["rey", "king"], ["de", "of"], ["Judá,", "Judah,"], ["y", "and"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["Jeroboam", "jeroboam"], ["hijo", "son"], ["de", "of"], ["Joás,", "joash,"], ["rey", "king"], ["de", "of"], ["Israel,", "Israel,"], ["dos", "two"], ["años", "years"], ["antes", "before"], ["del", "of-the"], ["terremoto.", "earthquake."]]},
  {num:2,words:[["Y", "and"], ["dijo:", "said:"], ["Jehová", "jehovah"], ["rugirá", "the"], ["desde", "from"], ["Sion", "zion"], ["y", "and"], ["dará", "shall-give"], ["su", "his/her"], ["voz", "voice"], ["desde", "from"], ["Jerusalén;", "jerusalem;"], ["y", "and"], ["los", "the"], ["pastizales", "and"], ["de", "of"], ["los", "the"], ["pastores", "pastors"], ["estarán", "stand"], ["de", "of"], ["duelo,", "mourned,"], ["y", "and"], ["se", "[refl.]"], ["secará", "the"], ["la", "the"], ["cumbre", "top"], ["del", "of-the"], ["Carmelo.", "carmel."]]},
  {num:3,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["Damasco,", "damascus,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["trillaron", "have"], ["a", "to"], ["Galaad", "Gilead"], ["con", "with"], ["trillos", "threshing"], ["de", "of"], ["hierro.", "iron."]]},
  {num:4,words:[["Y", "and"], ["enviaré", "send"], ["fuego", "fire"], ["a", "to"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Hazael,", "hazael,"], ["y", "and"], ["consumirá", "palaces"], ["los", "the"], ["palacios", "palaces"], ["de", "of"], ["Ben-adad.", "benhadad."]]},
  {num:5,words:[["Y", "and"], ["quebraré", "will"], ["el", "the"], ["cerrojo", "the"], ["de", "of"], ["Damasco,", "damascus,"], ["y", "and"], ["talaré", "cut"], ["a", "to"], ["los", "the"], ["moradores", "inhabitants"], ["del", "of-the"], ["valle", "valley"], ["de", "of"], ["Avén", "and"], ["y", "and"], ["a", "to"], ["los", "the"], ["gobernadores", "governors"], ["de", "of"], ["Bet-edén;", "house;"], ["y", "and"], ["el", "the"], ["pueblo", "people"], ["de", "of"], ["Siria", "syria"], ["será", "shall-be"], ["llevado", "carried"], ["cautivo", "captive"], ["a", "to"], ["Kir,", "kir,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:6,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["Gaza,", "gaza,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["llevó", "carried"], ["cautivo", "captive"], ["a", "to"], ["todo", "all"], ["un", "a"], ["pueblo", "people"], ["para", "for"], ["entregarlo", "betray-it"], ["a", "to"], ["Edom.", "edom."]]},
  {num:7,words:[["Y", "and"], ["enviaré", "send"], ["fuego", "fire"], ["al", "to-the"], ["muro", "wall"], ["de", "of"], ["Gaza,", "gaza,"], ["y", "and"], ["consumirá", "palaces"], ["sus", "his/her"], ["palacios.", "palaces."]]},
  {num:8,words:[["Y", "and"], ["talaré", "cut"], ["a", "to"], ["los", "the"], ["moradores", "inhabitants"], ["de", "of"], ["Asdod", "ashdod"], ["y", "and"], ["a", "to"], ["los", "the"], ["gobernadores", "governors"], ["de", "of"], ["Ascalón;", "ashkelon;"], ["y", "and"], ["volveré", "return"], ["mi", "my"], ["mano", "hand"], ["contra", "against"], ["Ecrón,", "ekron,"], ["y", "and"], ["el", "the"], ["remanente", "remnant"], ["de", "of"], ["los", "the"], ["filisteos", "philistines"], ["perecerá,", "perish,"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:9,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["Tiro,", "tyrus,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["entregaron", "delivered"], ["a", "to"], ["todo", "all"], ["un", "a"], ["pueblo", "people"], ["cautivo", "captive"], ["a", "to"], ["Edom", "edom"], ["y", "and"], ["no", "not"], ["se", "[refl.]"], ["acordaron", "they"], ["del", "of-the"], ["pacto", "covenant"], ["de", "of"], ["hermanos.", "brethren."]]},
  {num:10,words:[["Y", "and"], ["enviaré", "send"], ["fuego", "fire"], ["al", "to-the"], ["muro", "wall"], ["de", "of"], ["Tiro,", "tyrus,"], ["y", "and"], ["consumirá", "palaces"], ["sus", "his/her"], ["palacios.", "palaces."]]},
  {num:11,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["Edom,", "edom,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["persiguió", "pursued"], ["a", "to"], ["espada", "sword"], ["a", "to"], ["su", "his/her"], ["hermano", "brother"], ["y", "and"], ["no", "not"], ["tuvo", "had"], ["compasión", "compassion"], ["alguna;", "some;"], ["y", "and"], ["en", "in"], ["su", "his/her"], ["furor", "fury"], ["se", "[refl.]"], ["enardecía", "did"], ["de", "of"], ["continuo", "continual"], ["y", "and"], ["ha", "has"], ["guardado", "kept"], ["el", "the"], ["enojo", "fury"], ["perpetuamente", "ever"]]},
  {num:12,words:[["Y", "and"], ["enviaré", "send"], ["fuego", "fire"], ["a", "to"], ["Temán,", "teman,"], ["y", "and"], ["consumirá", "palaces"], ["los", "the"], ["palacios", "palaces"], ["de", "of"], ["Bosra.", "bozrah."]]},
  {num:13,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Amón,", "amon,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["les", "them"], ["abrieron", "opened"], ["el", "the"], ["vientre", "belly"], ["a", "to"], ["las", "the"], ["de", "of"], ["Galaad", "Gilead"], ["que", "that"], ["estaban", "were"], ["encintas,", "child,"], ["para", "for"], ["ensanchar", "enlarge"], ["sus", "his/her"], ["fronteras.", "borders."]]},
  {num:14,words:[["Y", "and"], ["encenderé", "i"], ["fuego", "fire"], ["en", "in"], ["el", "the"], ["muro", "wall"], ["de", "of"], ["Rabá,", "rabbah,"], ["y", "and"], ["consumirá", "palaces"], ["sus", "his/her"], ["palacios", "palaces"], ["con", "with"], ["estruendo", "noise"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["batalla,", "battle,"], ["con", "with"], ["tempestad", "storm"], ["en", "in"], ["el", "the"], ["día", "day"], ["tempestuoso;", "whirlwind;"]]},
  {num:15,words:[["y", "and"], ["su", "his/her"], ["rey", "king"], ["irá", "well"], ["al", "to-the"], ["cautiverio,", "captivity,"], ["él", "he"], ["y", "and"], ["todos", "all"], ["sus", "his/her"], ["príncipes,", "princes,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
];
renderVerseSet(v1, 'amo-ch1-verses');

var v2 = [
  {num:1,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["Moab,", "moab,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["quemó", "burned"], ["los", "the"], ["huesos", "bones"], ["del", "of-the"], ["rey", "king"], ["de", "of"], ["Edom", "edom"], ["hasta", "until"], ["calcinarlos.", "lime."]]},
  {num:2,words:[["Y", "and"], ["enviaré", "send"], ["fuego", "fire"], ["a", "to"], ["Moab,", "moab,"], ["y", "and"], ["consumirá", "palaces"], ["los", "the"], ["palacios", "palaces"], ["de", "of"], ["Queriot;", "devour;"], ["y", "and"], ["morirá", "die"], ["Moab", "moab"], ["en", "in"], ["medio", "midst"], ["del", "of-the"], ["alboroto,", "tumult,"], ["en", "in"], ["medio", "midst"], ["del", "of-the"], ["estrépito", "and"], ["y", "and"], ["con", "with"], ["sonido", "trumpet"], ["de", "of"], ["trompeta.", "trump."]]},
  {num:3,words:[["Y", "and"], ["quitaré", "take"], ["al", "to-the"], ["juez", "judge"], ["de", "of"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["él", "he"], ["y", "and"], ["mataré", "will"], ["junto", "together"], ["con", "with"], ["él", "he"], ["a", "to"], ["todos", "all"], ["sus", "his/her"], ["príncipes,", "princes,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:4,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["Judá,", "Judah,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["menospreciaron", "they"], ["la", "the"], ["ley", "law"], ["de", "of"], ["Jehová", "jehovah"], ["y", "and"], ["no", "not"], ["guardaron", "kept"], ["sus", "his/her"], ["estatutos;", "statutes;"], ["y", "and"], ["los", "the"], ["hicieron", "did/made"], ["errar", "err"], ["sus", "his/her"], ["mentiras,", "lyings,"], ["en", "in"], ["pos", "follow"], ["de", "of"], ["las", "the"], ["cuales", "which"], ["anduvieron", "walked"], ["sus", "his/her"], ["padres.", "parents."]]},
  {num:5,words:[["Enviaré,", "send,"], ["por", "by/for"], ["tanto,", "so-much,"], ["fuego", "fire"], ["a", "to"], ["Judá,", "Judah,"], ["el", "the"], ["cual", "which"], ["consumirá", "palaces"], ["los", "the"], ["palacios", "palaces"], ["de", "of"], ["Jerusalén.", "jerusalem."]]},
  {num:6,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Por", "by/for"], ["tres", "three"], ["transgresiones", "transgressions"], ["de", "of"], ["Israel,", "Israel,"], ["y", "and"], ["por", "by/for"], ["la", "the"], ["cuarta,", "fourth,"], ["no", "not"], ["revocaré", "punishment"], ["su", "his/her"], ["castigo,", "punishment,"], ["porque", "because"], ["vendieron", "because"], ["por", "by/for"], ["dinero", "sacks"], ["al", "to-the"], ["justo", "just/righteous"], ["y", "and"], ["al", "to-the"], ["pobre", "poor"], ["por", "by/for"], ["un", "a"], ["par", "of"], ["de", "of"], ["sandalias;", "and;"]]},
  {num:7,words:[["porque", "because"], ["pisotean", "pant"], ["hasta", "until"], ["el", "the"], ["polvo", "dust"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["la", "the"], ["cabeza", "head"], ["de", "of"], ["los", "the"], ["pobres", "poor"], ["y", "and"], ["tuercen", "aside"], ["el", "the"], ["camino", "way"], ["de", "of"], ["los", "the"], ["humildes;", "humble;"], ["y", "and"], ["un", "a"], ["hombre", "man"], ["y", "and"], ["su", "his/her"], ["padre", "father"], ["se", "[refl.]"], ["llegan", "they"], ["a", "to"], ["la", "the"], ["misma", "same"], ["joven,", "young-man,"], ["profanando", "profane"], ["mi", "my"], ["santo", "holy"], ["nombre.", "name."]]},
  {num:8,words:[["Y", "and"], ["sobre", "upon"], ["las", "the"], ["ropas", "robes"], ["empeñadas", "upon"], ["se", "[refl.]"], ["acuestan", "laid"], ["junto", "together"], ["a", "to"], ["cualquier", "any"], ["altar,", "altar,"], ["y", "and"], ["el", "the"], ["vino", "wine"], ["de", "of"], ["los", "the"], ["multados", "of"], ["beben", "drink"], ["en", "in"], ["la", "the"], ["casa", "house"], ["de", "of"], ["sus", "his/her"], ["dioses.", "gods."]]},
  {num:9,words:[["Y", "and"], ["yo", "I"], ["destruí", "i"], ["delante", "before"], ["de", "of"], ["ellos", "they"], ["al", "to-the"], ["amorreo,", "amorite,"], ["cuya", "whose"], ["altura", "height"], ["era", "was"], ["como", "as"], ["la", "the"], ["altura", "height"], ["de", "of"], ["los", "the"], ["cedros,", "cedars,"], ["y", "and"], ["que", "that"], ["era", "was"], ["fuerte", "strong"], ["como", "as"], ["una", "a"], ["encina;", "oak;"], ["y", "and"], ["destruí", "fruit"], ["su", "his/her"], ["fruto", "fruit"], ["arriba", "above"], ["y", "and"], ["sus", "his/her"], ["raíces", "roots"], ["abajo.", "below."]]},
  {num:10,words:[["Y", "and"], ["a", "to"], ["vosotros", "you"], ["os", "you"], ["hice", "I-did"], ["subir", "go-up"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto", "Egypt"], ["y", "and"], ["os", "you"], ["conduje", "forty"], ["por", "by/for"], ["el", "the"], ["desierto", "wilderness"], ["cuarenta", "forty"], ["años", "years"], ["para", "for"], ["que", "that"], ["poseyeseis", "the"], ["la", "the"], ["tierra", "land/earth"], ["del", "of-the"], ["amorreo.", "amorite."]]},
  {num:11,words:[["Y", "and"], ["levanté", "arose"], ["profetas", "prophets"], ["de", "of"], ["vuestros", "your"], ["hijos", "children"], ["y", "and"], ["nazareos", "nazarites"], ["de", "of"], ["vuestros", "your"], ["jóvenes.", "young-men."], ["¿No", "not"], ["es", "is"], ["esto", "this"], ["así,", "thus,"], ["oh", "oh"], ["hijos", "children"], ["de", "of"], ["Israel?,", "Israel?,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:12,words:[["Mas", "but"], ["vosotros", "you"], ["disteis", "gave"], ["de", "of"], ["beber", "drink"], ["vino", "wine"], ["a", "to"], ["los", "the"], ["nazareos,", "nazarites,"], ["y", "and"], ["a", "to"], ["los", "the"], ["profetas", "prophets"], ["mandasteis,", "prophets,"], ["diciendo:", "saying:"], ["No", "not"], ["profeticéis.", "not."]]},
  {num:13,words:[["Pues", "for"], ["he", "I-have"], ["aquí,", "here,"], ["yo", "I"], ["estoy", "I-am"], ["apretujado", "you,"], ["debajo", "beneath"], ["de", "of"], ["vosotros,", "you,"], ["como", "as"], ["se", "[refl.]"], ["apretuja", "pressed"], ["el", "the"], ["carro", "cart"], ["lleno", "full"], ["de", "of"], ["gavillas;", "sheaves;"]]},
  {num:14,words:[["y", "and"], ["el", "the"], ["ligero", "flight"], ["no", "not"], ["podrá", "able"], ["huir;", "flee;"], ["y", "and"], ["al", "to-the"], ["fuerte", "strong"], ["no", "not"], ["le", "him/her"], ["servirá", "serve"], ["su", "his/her"], ["fuerza,", "strength,"], ["ni", "nor"], ["el", "the"], ["valiente", "valiant"], ["salvará", "save"], ["su", "his/her"], ["vida;", "life;"]]},
  {num:15,words:[["y", "and"], ["el", "the"], ["que", "that"], ["toma", "take"], ["el", "the"], ["arco", "bow"], ["no", "not"], ["resistirá,", "he,"], ["ni", "nor"], ["escapará", "escape"], ["el", "the"], ["ligero", "of"], ["de", "of"], ["pies,", "feet,"], ["ni", "nor"], ["el", "the"], ["que", "that"], ["cabalga", "he"], ["en", "in"], ["caballo", "horse"], ["salvará", "save"], ["su", "his/her"], ["vida.", "life."]]},
  {num:16,words:[["Y", "and"], ["el", "the"], ["más", "more"], ["valiente", "valiant"], ["de", "of"], ["corazón", "heart"], ["entre", "among"], ["los", "the"], ["valientes", "valour"], ["huirá", "flee"], ["desnudo", "naked"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
];
renderVerseSet(v2, 'amo-ch2-verses');

var v3 = [
  {num:1,words:[["Oíd", "hear"], ["esta", "this"], ["palabra", "word"], ["que", "that"], ["ha", "has"], ["hablado", "spoken"], ["Jehová", "jehovah"], ["contra", "against"], ["vosotros,", "you,"], ["oh", "oh"], ["hijos", "children"], ["de", "of"], ["Israel,", "Israel,"], ["contra", "against"], ["toda", "all"], ["la", "the"], ["familia", "family"], ["que", "that"], ["hice", "I-did"], ["subir", "go-up"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto.", "Egypt."], ["Dice", "says"], ["así:", "thus:"]]},
  {num:2,words:[["Solamente", "only"], ["a", "to"], ["vosotros", "you"], ["he", "I-have"], ["conocido", "known"], ["de", "of"], ["todas", "all"], ["las", "the"], ["familias", "families"], ["de", "of"], ["la", "the"], ["tierra;", "land/earth;"], ["por", "by/for"], ["tanto,", "so-much,"], ["os", "you"], ["castigaré", "punish"], ["por", "by/for"], ["todas", "all"], ["vuestras", "your"], ["iniquidades.", "iniquities."]]},
  {num:3,words:[["¿Andarán", "walk"], ["dos", "two"], ["juntos", "together"], ["si", "if"], ["no", "not"], ["están", "are"], ["de", "of"], ["acuerdo?", "agreement?"]]},
  {num:4,words:[["¿Rugirá", "will"], ["el", "the"], ["león", "lion"], ["en", "in"], ["el", "the"], ["bosque", "forest"], ["sin", "without"], ["haber", "have"], ["presa?", "prey?"], ["¿Dará", "shall-give"], ["el", "the"], ["leoncillo", "lion"], ["su", "his/her"], ["rugido", "the"], ["desde", "from"], ["su", "his/her"], ["guarida", "a"], ["sin", "without"], ["haber", "have"], ["apresado", "taken"], ["algo?", "something?"]]},
  {num:5,words:[["¿Caerá", "fall"], ["el", "the"], ["ave", "fowl"], ["en", "in"], ["la", "the"], ["trampa,", "snare,"], ["en", "in"], ["la", "the"], ["tierra,", "land/earth,"], ["sin", "without"], ["haber", "have"], ["cebo?", "for?"], ["¿Se", "[refl.]"], ["levanta", "raiseth"], ["la", "the"], ["trampa", "snare"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["si", "if"], ["no", "not"], ["se", "[refl.]"], ["ha", "has"], ["atrapado", "at"], ["algo?", "something?"]]},
  {num:6,words:[["¿Se", "[refl.]"], ["tocará", "trump"], ["la", "the"], ["trompeta", "trump"], ["en", "in"], ["la", "the"], ["ciudad,", "city,"], ["y", "and"], ["no", "not"], ["se", "[refl.]"], ["alborotará", "be"], ["el", "the"], ["pueblo?", "people?"], ["¿Habrá", "there-shall-be"], ["algún", "some"], ["mal", "evil"], ["en", "in"], ["la", "the"], ["ciudad", "city"], ["que", "that"], ["Jehová", "jehovah"], ["no", "not"], ["haya", "let-there-be"], ["hecho?", "done/made?"]]},
  {num:7,words:[["Porque", "because"], ["no", "not"], ["hará", "shall-make"], ["nada", "nothing"], ["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["sin", "without"], ["que", "that"], ["revele", "revealeth"], ["su", "his/her"], ["secreto", "openly"], ["a", "to"], ["sus", "his/her"], ["siervos", "servants"], ["los", "the"], ["profetas.", "prophets."]]},
  {num:8,words:[["Si", "if"], ["ruge", "lion"], ["el", "the"], ["león,", "lion,"], ["¿quién", "who"], ["no", "not"], ["temerá?", "fear?"], ["Si", "if"], ["habla", "speaks"], ["Jehová", "jehovah"], ["el", "the"], ["Señor,", "Lord,"], ["¿quién", "who"], ["no", "not"], ["profetizará?", "prophesy?"]]},
  {num:9,words:[["Haced", "do"], ["pregonar", "the"], ["sobre", "upon"], ["los", "the"], ["palacios", "palaces"], ["de", "of"], ["Asdod", "ashdod"], ["y", "and"], ["sobre", "upon"], ["los", "the"], ["palacios", "palaces"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto,", "Egypt,"], ["y", "and"], ["decid:", "tell:"], ["Reuníos", "yourselves"], ["sobre", "upon"], ["los", "the"], ["montes", "mountains"], ["de", "of"], ["Samaria", "samaria"], ["y", "and"], ["ved", "see"], ["los", "the"], ["muchos", "many"], ["tumultos", "tumults"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ella", "she"], ["y", "and"], ["las", "the"], ["opresiones", "oppressed"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ella.", "she."]]},
  {num:10,words:[["Y", "and"], ["no", "not"], ["saben", "know"], ["hacer", "make/do"], ["lo", "it/him"], ["recto,", "upright,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["los", "the"], ["que", "that"], ["atesoran", "store"], ["violencia", "violence"], ["y", "and"], ["despojo", "spoil"], ["en", "in"], ["sus", "his/her"], ["palacios.", "palaces."]]},
  {num:11,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["ha", "has"], ["dicho", "said"], ["así:", "thus:"], ["Un", "a"], ["enemigo", "enemy"], ["vendrá", "shall-come"], ["por", "by/for"], ["todos", "all"], ["los", "the"], ["lados", "sides"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["y", "and"], ["derribará", "shall"], ["tu", "thy"], ["fortaleza,", "castle,"], ["y", "and"], ["tus", "thy"], ["palacios", "palaces"], ["serán", "shall-be"], ["saqueados.", "spoiled."]]},
  {num:12,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["De", "of"], ["la", "the"], ["manera", "manner"], ["que", "that"], ["el", "the"], ["pastor", "shepherd"], ["libra", "delivereth"], ["de", "of"], ["la", "the"], ["boca", "mouth"], ["del", "of-the"], ["león", "lion"], ["dos", "two"], ["patas", "upon"], ["o", "or"], ["la", "the"], ["punta", "in"], ["de", "of"], ["una", "a"], ["oreja,", "ear,"], ["así", "thus"], ["serán", "shall-be"], ["librados", "delivered"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Israel", "Israel"], ["que", "that"], ["en", "in"], ["Samaria", "samaria"], ["se", "[refl.]"], ["sientan", "in"], ["en", "in"], ["el", "the"], ["borde", "border"], ["de", "of"], ["la", "the"], ["cama,", "bed,"], ["y", "and"], ["en", "in"], ["Damasco,", "damascus,"], ["en", "in"], ["un", "a"], ["diván.", "couch."]]},
  {num:13,words:[["Oíd", "hear"], ["y", "and"], ["testificad", "and"], ["contra", "against"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jacob,", "Jacob,"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos:", "armies:"]]},
  {num:14,words:[["El", "the"], ["día", "day"], ["en", "in"], ["que", "that"], ["castigue", "shall"], ["las", "the"], ["transgresiones", "transgressions"], ["de", "of"], ["Israel,", "Israel,"], ["castigaré", "punish"], ["también", "also"], ["los", "the"], ["altares", "altars"], ["de", "of"], ["Bet-el;", "bethel;"], ["y", "and"], ["serán", "shall-be"], ["cortados", "of"], ["los", "the"], ["cuernos", "horns"], ["del", "of-the"], ["altar", "altar"], ["y", "and"], ["caerán", "fall"], ["a", "to"], ["tierra.", "land/earth."]]},
  {num:15,words:[["Y", "and"], ["heriré", "smite"], ["la", "the"], ["casa", "house"], ["de", "of"], ["invierno", "winter"], ["junto", "together"], ["con", "with"], ["la", "the"], ["casa", "house"], ["de", "of"], ["verano,", "summer,"], ["y", "and"], ["las", "the"], ["casas", "houses"], ["de", "of"], ["marfil", "ivory"], ["perecerán;", "perish;"], ["y", "and"], ["muchas", "many"], ["casas", "houses"], ["serán", "shall-be"], ["arruinadas,", "saith,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
];
renderVerseSet(v3, 'amo-ch3-verses');

var v4 = [
  {num:1,words:[["Oíd", "hear"], ["esta", "this"], ["palabra,", "word,"], ["vacas", "kine"], ["de", "of"], ["Basán,", "bashan,"], ["que", "that"], ["estáis", "stand"], ["en", "in"], ["el", "the"], ["monte", "mount"], ["de", "of"], ["Samaria,", "samaria,"], ["que", "that"], ["oprimís", "which"], ["a", "to"], ["los", "the"], ["pobres,", "poor,"], ["que", "that"], ["quebrantáis", "the"], ["a", "to"], ["los", "the"], ["menesterosos,", "needy,"], ["que", "that"], ["decís", "say"], ["a", "to"], ["vuestros", "your"], ["señores:", "shechem:"], ["Traed,", "bring,"], ["y", "and"], ["beberemos.", "drink."]]},
  {num:2,words:[["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["juró", "swore"], ["por", "by/for"], ["su", "his/her"], ["santidad:", "holiness:"], ["He", "I-have"], ["aquí,", "here,"], ["vienen", "come"], ["días", "days"], ["sobre", "upon"], ["vosotras", "your"], ["en", "in"], ["que", "that"], ["os", "you"], ["llevarán", "bear"], ["con", "with"], ["ganchos,", "hooks,"], ["y", "and"], ["a", "to"], ["vuestros", "your"], ["descendientes", "descendants"], ["con", "with"], ["anzuelos", "posterity"], ["de", "of"], ["pescador.", "fishhooks."]]},
  {num:3,words:[["Y", "and"], ["saldréis", "go"], ["por", "by/for"], ["las", "the"], ["brechas", "breaches"], ["una", "a"], ["tras", "after"], ["otra", "other"], ["y", "and"], ["seréis", "you-shall-be"], ["echadas", "casts"], ["del", "of-the"], ["palacio,", "palace,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:4,words:[["Id", "go"], ["a", "to"], ["Bet-el", "bethel"], ["y", "and"], ["pecad;", "transgress;"], ["en", "in"], ["Gilgal", "gilgal"], ["multiplicad", "multiply"], ["la", "the"], ["rebelión;", "rebellion;"], ["y", "and"], ["traed", "bring"], ["de", "of"], ["mañana", "morning"], ["vuestros", "your"], ["sacrificios", "sacrifices"], ["y", "and"], ["vuestros", "your"], ["diezmos", "tithes"], ["cada", "each"], ["tres", "three"], ["días.", "days."]]},
  {num:5,words:[["Y", "and"], ["ofreced", "offer"], ["ofrenda", "offering"], ["de", "of"], ["gratitud", "of"], ["con", "with"], ["pan", "bread"], ["leudado", "leavened"], ["y", "and"], ["pregonad;", "and;"], ["anunciad", "publish"], ["ofrendas", "offerings"], ["voluntarias,", "freewill,"], ["puesto", "placed"], ["que", "that"], ["así", "thus"], ["lo", "it/him"], ["queréis,", "what,"], ["hijos", "children"], ["de", "of"], ["Israel,", "Israel,"], ["dice", "says"], ["Jehová", "jehovah"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:6,words:[["Yo", "I"], ["también", "also"], ["os", "you"], ["hice", "I-did"], ["estar", "be"], ["a", "to"], ["diente", "cleanness"], ["limpio", "clean"], ["en", "in"], ["todas", "all"], ["vuestras", "your"], ["ciudades,", "cities,"], ["y", "and"], ["hubo", "there-was"], ["falta", "want"], ["de", "of"], ["pan", "bread"], ["en", "in"], ["todos", "all"], ["vuestros", "your"], ["pueblos;", "peoples;"], ["pero", "but"], ["no", "not"], ["os", "you"], ["volvisteis", "unto"], ["a", "to"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:7,words:[["Y", "and"], ["también", "also"], ["os", "you"], ["retuve", "withholden"], ["la", "the"], ["lluvia", "rain"], ["tres", "three"], ["meses", "months"], ["antes", "before"], ["de", "of"], ["la", "the"], ["siega;", "harvest;"], ["e", "and"], ["hice", "I-did"], ["llover", "rain"], ["sobre", "upon"], ["una", "a"], ["ciudad", "city"], ["y", "and"], ["sobre", "upon"], ["otra", "other"], ["ciudad", "city"], ["no", "not"], ["hice", "I-did"], ["llover;", "rain;"], ["sobre", "upon"], ["una", "a"], ["parte", "part"], ["llovió,", "city,"], ["y", "and"], ["la", "the"], ["parte", "part"], ["sobre", "upon"], ["la", "the"], ["cual", "which"], ["no", "not"], ["llovió,", "it,"], ["se", "[refl.]"], ["secó.", "withered."]]},
  {num:8,words:[["Y", "and"], ["venían", "came"], ["dos", "two"], ["o", "or"], ["tres", "three"], ["ciudades", "cities"], ["a", "to"], ["una", "a"], ["ciudad", "city"], ["para", "for"], ["beber", "drink"], ["agua,", "water,"], ["y", "and"], ["no", "not"], ["se", "[refl.]"], ["saciaban;", "satisfied;"], ["con", "with"], ["todo,", "all,"], ["no", "not"], ["os", "you"], ["volvisteis", "unto"], ["a", "to"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:9,words:[["Os", "you"], ["herí", "i"], ["con", "with"], ["tizoncillo", "with"], ["y", "and"], ["añublo;", "and;"], ["la", "the"], ["langosta", "locust"], ["devoró", "devoured"], ["vuestros", "your"], ["muchos", "many"], ["huertos,", "gardens,"], ["y", "and"], ["vuestras", "your"], ["viñas,", "vineyards,"], ["y", "and"], ["vuestros", "your"], ["higuerales", "fig-them"], ["y", "and"], ["vuestros", "your"], ["olivares,", "vineyards,"], ["pero", "but"], ["nunca", "never"], ["os", "you"], ["volvisteis", "returned"], ["a", "to"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:10,words:[["Envié", "sent"], ["entre", "among"], ["vosotros", "you"], ["pestilencia", "pestilence"], ["tal", "such"], ["como", "as"], ["en", "in"], ["Egipto;", "Egypt;"], ["maté", "i"], ["a", "to"], ["espada", "sword"], ["a", "to"], ["vuestros", "your"], ["jóvenes;", "young-men;"], ["vuestros", "your"], ["caballos", "horses"], ["fueron", "were"], ["capturados,", "away,"], ["e", "and"], ["hice", "I-did"], ["subir", "go-up"], ["el", "the"], ["hedor", "the"], ["de", "of"], ["vuestros", "your"], ["campamentos", "camps"], ["hasta", "until"], ["vuestras", "your"], ["narices;", "unto;"], ["pero", "but"], ["no", "not"], ["os", "you"], ["volvisteis", "not"], ["a", "to"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:11,words:[["Os", "you"], ["destruí,", "have,"], ["como", "as"], ["cuando", "when"], ["Dios", "God"], ["destruyó", "destroyed"], ["a", "to"], ["Sodoma", "gomorrah"], ["y", "and"], ["a", "to"], ["Gomorra,", "gomorrah,"], ["y", "and"], ["fuisteis", "ye"], ["como", "as"], ["tizón", "plucked"], ["sacado", "led"], ["del", "of-the"], ["fuego;", "fire;"], ["pero", "but"], ["no", "not"], ["os", "you"], ["volvisteis", "returned"], ["a", "to"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:12,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["de", "of"], ["esta", "this"], ["manera", "manner"], ["te", "thee"], ["haré", "I-shall-make"], ["a", "to"], ["ti,", "thee,"], ["oh", "oh"], ["Israel;", "Israel;"], ["y", "and"], ["porque", "because"], ["te", "thee"], ["he", "I-have"], ["de", "of"], ["hacer", "make/do"], ["esto,", "this,"], ["prepárate", "unto"], ["para", "for"], ["venir", "come"], ["al", "to-the"], ["encuentro", "met"], ["de", "of"], ["tu", "thy"], ["Dios,", "God,"], ["oh", "oh"], ["Israel.", "Israel."]]},
  {num:13,words:[["Porque", "because"], ["he", "I-have"], ["aquí,", "here,"], ["el", "the"], ["que", "that"], ["forma", "form"], ["los", "the"], ["montes,", "mountains,"], ["y", "and"], ["crea", "believeth"], ["el", "the"], ["viento", "wind"], ["y", "and"], ["anuncia", "the"], ["al", "to-the"], ["hombre", "man"], ["su", "his/her"], ["pensamiento,", "thought,"], ["el", "the"], ["que", "that"], ["hace", "does/makes"], ["del", "of-the"], ["alba", "morning"], ["tinieblas", "darkness"], ["y", "and"], ["pasa", "passeth"], ["sobre", "upon"], ["las", "the"], ["alturas", "places"], ["de", "of"], ["la", "the"], ["tierra:", "land/earth:"], ["Jehová", "jehovah"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["es", "is"], ["su", "his/her"], ["nombre.", "name."]]},
];
renderVerseSet(v4, 'amo-ch4-verses');

var v5 = [
  {num:1,words:[["Oíd", "hear"], ["esta", "this"], ["palabra", "word"], ["que", "that"], ["yo", "I"], ["levanto", "take"], ["para", "for"], ["lamentación", "lamentation"], ["contra", "against"], ["vosotros,", "you,"], ["oh", "oh"], ["casa", "house"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:2,words:[["Cayó", "fell"], ["la", "the"], ["virginal", "of"], ["Israel;", "Israel;"], ["no", "not"], ["podrá", "able"], ["levantarse", "to"], ["ya", "already"], ["más;", "more;"], ["fue", "was/went"], ["dejada", "left"], ["sobre", "upon"], ["su", "his/her"], ["tierra,", "land/earth,"], ["y", "and"], ["no", "not"], ["hay", "there-is"], ["quien", "who"], ["la", "the"], ["levante.", "up."]]},
  {num:3,words:[["Porque", "because"], ["así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["el", "the"], ["Señor:", "Lord:"], ["La", "the"], ["ciudad", "city"], ["que", "that"], ["salga", "cometh"], ["con", "with"], ["mil", "thousand"], ["volverá", "return"], ["con", "with"], ["cien,", "talents,"], ["y", "and"], ["la", "the"], ["que", "that"], ["salga", "cometh"], ["con", "with"], ["cien", "talents"], ["volverá", "return"], ["con", "with"], ["diez,", "ten,"], ["en", "in"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:4,words:[["Pero", "but"], ["así", "thus"], ["dice", "says"], ["Jehová", "jehovah"], ["a", "to"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel:", "Israel:"], ["Buscadme", "seek-me"], ["y", "and"], ["viviréis;", "live;"]]},
  {num:5,words:[["y", "and"], ["no", "not"], ["busquéis", "not"], ["a", "to"], ["Bet-el,", "bethel,"], ["ni", "nor"], ["entréis", "enter"], ["en", "in"], ["Gilgal", "gilgal"], ["ni", "nor"], ["paséis", "to"], ["a", "to"], ["Beerseba,", "beersheba,"], ["porque", "because"], ["Gilgal", "gilgal"], ["será", "shall-be"], ["ciertamente", "surely"], ["llevada", "into"], ["en", "in"], ["cautiverio,", "captivity,"], ["y", "and"], ["Bet-el", "bethel"], ["será", "shall-be"], ["deshecha.", "nought."]]},
  {num:6,words:[["Buscad", "seek"], ["a", "to"], ["Jehová", "jehovah"], ["y", "and"], ["vivid,", "the,"], ["no", "not"], ["sea", "let-be/be"], ["que", "that"], ["acometa", "break"], ["como", "as"], ["fuego", "fire"], ["a", "to"], ["la", "the"], ["casa", "house"], ["de", "of"], ["José", "Joseph"], ["y", "and"], ["la", "the"], ["consuma,", "of,"], ["sin", "without"], ["haber", "have"], ["en", "in"], ["Bet-el", "bethel"], ["quien", "who"], ["lo", "it/him"], ["apague.", "bethel."]]},
  {num:7,words:[["Los", "the"], ["que", "that"], ["convertís", "turn"], ["en", "in"], ["ajenjo", "to"], ["el", "the"], ["juicio", "judgment"], ["y", "and"], ["echáis", "off"], ["por", "by/for"], ["tierra", "land/earth"], ["la", "the"], ["justicia,", "justice/righteousness,"]]},
  {num:8,words:[["buscad", "seek"], ["al", "to-the"], ["que", "that"], ["hizo", "made/did"], ["las", "the"], ["Pléyades", "stars"], ["y", "and"], ["el", "the"], ["Orión,", "and,"], ["y", "and"], ["las", "the"], ["tinieblas", "darkness"], ["vuelve", "return"], ["en", "in"], ["mañana", "morning"], ["y", "and"], ["hace", "does/makes"], ["oscurecer", "maketh"], ["el", "the"], ["día", "day"], ["como", "as"], ["noche;", "night;"], ["el", "the"], ["que", "that"], ["llama", "calls/flame"], ["a", "to"], ["las", "the"], ["aguas", "waters"], ["del", "of-the"], ["mar", "sea"], ["y", "and"], ["las", "the"], ["derrama", "upon"], ["sobre", "upon"], ["la", "the"], ["faz", "face"], ["de", "of"], ["la", "the"], ["tierra:", "land/earth:"], ["Jehová", "jehovah"], ["es", "is"], ["su", "his/her"], ["nombre;", "name;"]]},
  {num:9,words:[["Él", "he"], ["es", "is"], ["el", "the"], ["que", "that"], ["desencadena", "against"], ["destrucción", "destruction"], ["sobre", "upon"], ["el", "the"], ["fuerte", "strong"], ["y", "and"], ["hace", "does/makes"], ["que", "that"], ["la", "the"], ["destrucción", "destruction"], ["venga", "let-come"], ["contra", "against"], ["la", "the"], ["fortaleza.", "castle."]]},
  {num:10,words:[["Ellos", "they"], ["aborrecen", "hate"], ["al", "to-the"], ["reprensor", "that"], ["en", "in"], ["la", "the"], ["puerta", "gate"], ["de", "of"], ["la", "the"], ["ciudad,", "city,"], ["y", "and"], ["al", "to-the"], ["que", "that"], ["habla", "speaks"], ["lo", "it/him"], ["recto", "upright"], ["abominan.", "uprightly."]]},
  {num:11,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["puesto", "placed"], ["que", "that"], ["pisoteáis", "is"], ["al", "to-the"], ["pobre", "poor"], ["y", "and"], ["tomáis", "ye"], ["de", "of"], ["él", "he"], ["carga", "burden"], ["de", "of"], ["trigo,", "wheat,"], ["aun", "even"], ["cuando", "when"], ["edificasteis", "of"], ["casas", "houses"], ["de", "of"], ["piedra", "stone"], ["labrada,", "the,"], ["no", "not"], ["las", "the"], ["habitaréis;", "dwell;"], ["plantasteis", "ye"], ["hermosas", "and"], ["viñas,", "vineyards,"], ["pero", "but"], ["no", "not"], ["beberéis", "drink"], ["el", "the"], ["vino", "wine"], ["de", "of"], ["ellas.", "they."]]},
  {num:12,words:[["Porque", "because"], ["yo", "I"], ["sé", "I-know"], ["de", "of"], ["vuestras", "your"], ["muchas", "many"], ["rebeliones", "for"], ["y", "and"], ["de", "of"], ["vuestros", "your"], ["grandes", "great"], ["pecados;", "sins;"], ["afligís", "they"], ["al", "to-the"], ["justo,", "just/righteous,"], ["y", "and"], ["recibís", "receive"], ["cohecho", "turn"], ["y", "and"], ["apartáis", "the"], ["a", "to"], ["los", "the"], ["pobres", "poor"], ["en", "in"], ["la", "the"], ["puerta.", "gate."]]},
  {num:13,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["el", "the"], ["prudente", "prudent"], ["en", "in"], ["tal", "such"], ["tiempo", "time"], ["calla,", "time,"], ["porque", "because"], ["el", "the"], ["tiempo", "time"], ["es", "is"], ["malo.", "evil."]]},
  {num:14,words:[["Buscad", "seek"], ["lo", "it/him"], ["bueno", "good"], ["y", "and"], ["no", "not"], ["lo", "it/him"], ["malo,", "evil,"], ["para", "for"], ["que", "that"], ["viváis,", "live,"], ["porque", "because"], ["así", "thus"], ["Jehová", "jehovah"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["estará", "shall-be"], ["con", "with"], ["vosotros,", "you,"], ["como", "as"], ["decís.", "say."]]},
  {num:15,words:[["Aborreced", "hate"], ["el", "the"], ["mal,", "evil,"], ["y", "and"], ["amad", "love"], ["el", "the"], ["bien", "well"], ["y", "and"], ["poned", "set"], ["juicio", "judgment"], ["en", "in"], ["la", "the"], ["puerta;", "gate;"], ["quizá", "perhaps"], ["Jehová", "jehovah"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["tendrá", "shall-have"], ["piedad", "godliness"], ["del", "of-the"], ["remanente", "remnant"], ["de", "of"], ["José.", "Joseph."]]},
  {num:16,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos,", "armies,"], ["el", "the"], ["Señor:", "Lord:"], ["En", "in"], ["todas", "all"], ["las", "the"], ["plazas", "strongholds"], ["habrá", "there-shall-be"], ["llanto,", "gnashing,"], ["y", "and"], ["en", "in"], ["todas", "all"], ["las", "the"], ["calles", "streets"], ["dirán:", "say:"], ["¡Ay!", "wo!"], ["¡ay!;", "wo!;"], ["y", "and"], ["al", "to-the"], ["labrador", "the"], ["llamarán", "call"], ["a", "to"], ["duelo,", "mourned,"], ["y", "and"], ["a", "to"], ["llorar", "weep"], ["a", "to"], ["los", "the"], ["que", "that"], ["sepan", "know"], ["lamentarse.", "and."]]},
  {num:17,words:[["Y", "and"], ["en", "in"], ["todas", "all"], ["las", "the"], ["viñas", "vineyards"], ["habrá", "there-shall-be"], ["llanto,", "gnashing,"], ["porque", "because"], ["pasaré", "pass"], ["por", "by/for"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti,", "thee,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:18,words:[["¡Ay", "wo"], ["de", "of"], ["los", "the"], ["que", "that"], ["desean", "desire"], ["el", "the"], ["día", "day"], ["de", "of"], ["Jehová!", "jehovah!"], ["¿Para", "for"], ["qué", "what"], ["queréis", "what"], ["este", "this"], ["día", "day"], ["de", "of"], ["Jehová?", "jehovah?"], ["Será", "shall-be"], ["de", "of"], ["tinieblas", "darkness"], ["y", "and"], ["no", "not"], ["de", "of"], ["luz,", "light,"]]},
  {num:19,words:[["como", "as"], ["el", "the"], ["que", "that"], ["huye", "flee"], ["de", "of"], ["delante", "before"], ["del", "of-the"], ["león", "lion"], ["y", "and"], ["se", "[refl.]"], ["topa", "and"], ["con", "with"], ["el", "the"], ["oso;", "bear;"], ["o", "or"], ["como", "as"], ["el", "the"], ["que,", "that,"], ["al", "to-the"], ["entrar", "enter"], ["en", "in"], ["casa,", "house,"], ["apoya", "the"], ["su", "his/her"], ["mano", "hand"], ["en", "in"], ["la", "the"], ["pared", "wall"], ["y", "and"], ["le", "him/her"], ["muerde", "serpent"], ["una", "a"], ["culebra.", "him."]]},
  {num:20,words:[["¿No", "not"], ["será", "shall-be"], ["el", "the"], ["día", "day"], ["de", "of"], ["Jehová", "jehovah"], ["tinieblas", "darkness"], ["y", "and"], ["no", "not"], ["luz;", "light;"], ["oscuridad,", "darkness,"], ["que", "that"], ["no", "not"], ["tiene", "has"], ["resplandor?", "luster?"]]},
  {num:21,words:[["Aborrezco,", "hate,"], ["desprecio", "in"], ["vuestras", "your"], ["fiestas,", "moons,"], ["y", "and"], ["no", "not"], ["me", "me"], ["darán", "give"], ["olor", "savour"], ["grato", "savour"], ["vuestras", "your"], ["asambleas.", "assemblys."]]},
  {num:22,words:[["Y", "and"], ["si", "if"], ["me", "me"], ["ofrecéis", "me"], ["holocaustos", "sacrifices"], ["y", "and"], ["vuestras", "your"], ["ofrendas", "offerings"], ["de", "of"], ["grano,", "grain,"], ["no", "not"], ["los", "the"], ["recibiré", "receive"], ["ni", "nor"], ["miraré", "neither"], ["a", "to"], ["las", "the"], ["ofrendas", "offerings"], ["de", "of"], ["paz", "peace"], ["de", "of"], ["vuestros", "your"], ["animales", "animals"], ["engordados.", "of."]]},
  {num:23,words:[["Quita", "taketh"], ["de", "of"], ["mí", "me"], ["el", "the"], ["ruido", "noise"], ["de", "of"], ["tus", "thy"], ["cantares,", "sings,"], ["pues", "for"], ["no", "not"], ["escucharé", "not"], ["las", "the"], ["salmodias", "the"], ["de", "of"], ["tus", "thy"], ["arpas.", "harps."]]},
  {num:24,words:[["Antes", "before"], ["bien,", "well,"], ["corra", "judgment"], ["el", "the"], ["juicio", "judgment"], ["como", "as"], ["las", "the"], ["aguas", "waters"], ["y", "and"], ["la", "the"], ["justicia", "justice/righteousness"], ["como", "as"], ["impetuoso", "mighty"], ["arroyo.", "arnon."]]},
  {num:25,words:[["¿Me", "me"], ["ofrecisteis", "ye"], ["sacrificios", "sacrifices"], ["y", "and"], ["ofrendas", "offerings"], ["en", "in"], ["el", "the"], ["desierto", "wilderness"], ["en", "in"], ["cuarenta", "forty"], ["años,", "years,"], ["oh", "oh"], ["casa", "house"], ["de", "of"], ["Israel?", "Israel?"]]},
  {num:26,words:[["Antes", "before"], ["bien,", "well,"], ["llevabais", "have"], ["el", "the"], ["tabernáculo", "tabernacle"], ["de", "of"], ["vuestros", "your"], ["Moloc", "molech"], ["y", "and"], ["Quiún,", "chiun,"], ["ídolos", "idols"], ["vuestros,", "your,"], ["la", "the"], ["estrella", "star"], ["de", "of"], ["vuestros", "your"], ["dioses", "gods"], ["que", "that"], ["os", "you"], ["hicisteis.", "ye."]]},
  {num:27,words:[["Os", "you"], ["haré,", "I-shall-make,"], ["pues,", "for,"], ["entrar", "enter"], ["en", "in"], ["cautividad", "captivity"], ["más", "more"], ["allá", "thither"], ["de", "of"], ["Damasco,", "damascus,"], ["ha", "has"], ["dicho", "said"], ["Jehová,", "jehovah,"], ["cuyo", "whose"], ["nombre", "name"], ["es", "is"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos.", "armies."]]},
];
renderVerseSet(v5, 'amo-ch5-verses');

var v6 = [
  {num:1,words:[["¡Ay", "wo"], ["de", "of"], ["los", "the"], ["reposados", "that"], ["en", "in"], ["Sion", "zion"], ["y", "and"], ["de", "of"], ["los", "the"], ["confiados", "the"], ["en", "in"], ["el", "the"], ["monte", "mount"], ["de", "of"], ["Samaria,", "samaria,"], ["los", "the"], ["nombrados", "appointed"], ["como", "as"], ["principales", "chief"], ["entre", "among"], ["las", "the"], ["naciones,", "nations,"], ["a", "to"], ["quienes", "who"], ["acude", "the"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel!", "Israel!"]]},
  {num:2,words:[["Pasad", "pass"], ["a", "to"], ["Calne", "unto"], ["y", "and"], ["mirad;", "heed;"], ["y", "and"], ["de", "of"], ["allí", "there"], ["id", "go"], ["a", "to"], ["la", "the"], ["gran", "great"], ["Hamat;", "hamath;"], ["descended", "great:"], ["luego", "then"], ["a", "to"], ["Gat", "gath"], ["de", "of"], ["los", "the"], ["filisteos.", "philistines."], ["¿Son", "are"], ["aquellos", "those"], ["reinos", "kingdoms"], ["mejores", "better"], ["que", "that"], ["estos", "these"], ["reinos?", "kingdoms?"], ["¿Es", "is"], ["mayor", "greater"], ["su", "his/her"], ["territorio", "coast"], ["que", "that"], ["vuestro", "your"], ["territorio?", "coast?"]]},
  {num:3,words:[["Vosotros", "you"], ["que", "that"], ["alejáis", "far"], ["el", "the"], ["día", "day"], ["malo", "evil"], ["y", "and"], ["acercáis", "cause"], ["la", "the"], ["silla", "seat"], ["de", "of"], ["la", "the"], ["violencia;", "violence;"]]},
  {num:4,words:[["los", "the"], ["que", "that"], ["duermen", "upon"], ["en", "in"], ["camas", "beds"], ["de", "of"], ["marfil,", "ivory,"], ["y", "and"], ["se", "[refl.]"], ["estiran", "their"], ["sobre", "upon"], ["sus", "his/her"], ["lechos,", "beds,"], ["y", "and"], ["comen", "eat"], ["los", "the"], ["corderos", "lambs"], ["del", "of-the"], ["rebaño", "flock"], ["y", "and"], ["los", "the"], ["becerros", "calves"], ["sacados", "leds"], ["de", "of"], ["en", "in"], ["medio", "midst"], ["del", "of-the"], ["establo;", "stall;"]]},
  {num:5,words:[["gorjean", "that"], ["al", "to-the"], ["son", "are"], ["de", "of"], ["la", "the"], ["flauta", "harp"], ["e", "and"], ["inventan", "to"], ["instrumentos", "musick"], ["musicales,", "of,"], ["como", "as"], ["David;", "David;"]]},
  {num:6,words:[["beben", "drink"], ["vino", "wine"], ["en", "in"], ["tazones", "basons"], ["y", "and"], ["se", "[refl.]"], ["ungen", "anoint"], ["con", "with"], ["los", "the"], ["ungüentos", "the"], ["más", "more"], ["finos;", "purples;"], ["y", "and"], ["no", "not"], ["se", "[refl.]"], ["afligen", "grieved"], ["por", "by/for"], ["el", "the"], ["quebranto", "destruction"], ["de", "of"], ["José;", "Joseph;"]]},
  {num:7,words:[["por", "by/for"], ["tanto,", "so-much,"], ["ahora", "now"], ["irán", "go"], ["cautivos", "captives"], ["a", "to"], ["la", "the"], ["cabeza", "head"], ["de", "of"], ["los", "the"], ["que", "that"], ["van", "go"], ["a", "to"], ["la", "the"], ["cautividad,", "captivity,"], ["y", "and"], ["se", "[refl.]"], ["acabará", "banquet"], ["el", "the"], ["festín", "them"], ["de", "of"], ["los", "the"], ["que", "that"], ["se", "[refl.]"], ["entregan", "shall"], ["a", "to"], ["los", "the"], ["placeres.", "pleasures."]]},
  {num:8,words:[["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["juró", "swore"], ["por", "by/for"], ["sí", "yea"], ["mismo,", "same,"], ["Jehová", "jehovah"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["ha", "has"], ["dicho:", "said:"], ["Abomino", "abhor"], ["la", "the"], ["soberbia", "pride"], ["de", "of"], ["Jacob", "Jacob"], ["y", "and"], ["aborrezco", "hate"], ["sus", "his/her"], ["palacios;", "palaces;"], ["entregaré", "deliver"], ["al", "to-the"], ["enemigo", "enemy"], ["la", "the"], ["ciudad", "city"], ["y", "and"], ["cuanto", "as-much-as"], ["hay", "there-is"], ["en", "in"], ["ella.", "she."]]},
  {num:9,words:[["Y", "and"], ["acontecerá", "shall-come-to-pass"], ["que", "that"], ["si", "if"], ["diez", "ten"], ["hombres", "men"], ["quedan", "are"], ["en", "in"], ["una", "a"], ["casa,", "house,"], ["morirán.", "die."]]},
  {num:10,words:[["Y", "and"], ["su", "his/her"], ["tío", "uncle"], ["levantará", "raise"], ["a", "to"], ["cada", "each"], ["uno,", "one,"], ["y", "and"], ["lo", "it/him"], ["quemará,", "burn,"], ["para", "for"], ["sacar", "bring"], ["los", "the"], ["huesos", "bones"], ["de", "of"], ["la", "the"], ["casa;", "house;"], ["y", "and"], ["dirá", "shall-say"], ["al", "to-the"], ["que", "that"], ["esté", "be"], ["en", "in"], ["los", "the"], ["rincones", "sides"], ["de", "of"], ["la", "the"], ["casa:", "house:"], ["¿Hay", "there-is"], ["aún", "still/yet"], ["alguno", "some"], ["contigo?", "with-thee?"], ["Y", "and"], ["el", "the"], ["otro", "other"], ["dirá:", "shall-say:"], ["No.", "not."], ["Y", "and"], ["dirá", "shall-say"], ["aquel:", "that:"], ["Calla,", "tongue,"], ["porque", "because"], ["no", "not"], ["debemos", "we-must"], ["hacer", "make/do"], ["mención", "mention"], ["del", "of-the"], ["nombre", "name"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:11,words:[["Porque", "because"], ["he", "I-have"], ["aquí,", "here,"], ["Jehová", "jehovah"], ["mandará", "command"], ["y", "and"], ["herirá", "smite"], ["con", "with"], ["hendiduras", "of"], ["la", "the"], ["casa", "house"], ["mayor,", "greater,"], ["y", "and"], ["la", "the"], ["casa", "house"], ["menor", "lesser"], ["con", "with"], ["grietas.", "clefts."]]},
  {num:12,words:[["¿Correrán", "run"], ["los", "the"], ["caballos", "horses"], ["por", "by/for"], ["las", "the"], ["peñas?", "rocks?"], ["¿Ararán", "will"], ["en", "in"], ["ellas", "they"], ["con", "with"], ["bueyes?", "oxen?"], ["¿Por", "by/for"], ["qué", "what"], ["habéis", "you-have"], ["vosotros", "you"], ["convertido", "converted"], ["el", "the"], ["juicio", "judgment"], ["en", "in"], ["veneno", "poison"], ["y", "and"], ["el", "the"], ["fruto", "fruit"], ["de", "of"], ["justicia", "justice/righteousness"], ["en", "in"], ["ajenjo?", "hemlock?"]]},
  {num:13,words:[["Vosotros", "you"], ["que", "that"], ["os", "you"], ["alegráis", "a"], ["por", "by/for"], ["nada,", "nothing,"], ["que", "that"], ["decís:", "say:"], ["¿No", "not"], ["hemos", "we-have"], ["adquirido", "gotten"], ["poder", "power/can"], ["con", "with"], ["nuestra", "our"], ["propia", "own"], ["fuerza?", "strength?"]]},
  {num:14,words:[["Pues", "for"], ["he", "I-have"], ["aquí,", "here,"], ["levantaré", "raise"], ["yo", "I"], ["sobre", "upon"], ["vosotros,", "you,"], ["oh", "oh"], ["casa", "house"], ["de", "of"], ["Israel,", "Israel,"], ["dice", "says"], ["Jehová", "jehovah"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos,", "armies,"], ["a", "to"], ["una", "a"], ["nación", "nation"], ["que", "that"], ["os", "you"], ["oprimirá", "you"], ["desde", "from"], ["la", "the"], ["entrada", "entrance"], ["de", "of"], ["Hamat", "hamath"], ["hasta", "until"], ["el", "the"], ["arroyo", "arnon"], ["del", "of-the"], ["desierto.", "wilderness."]]},
];
renderVerseSet(v6, 'amo-ch6-verses');

var v7 = [
  {num:1,words:[["Así", "thus"], ["me", "me"], ["ha", "has"], ["mostrado", "shown"], ["Jehová", "jehovah"], ["el", "the"], ["Señor:", "Lord:"], ["Y", "and"], ["he", "I-have"], ["aquí,", "here,"], ["él", "he"], ["formaba", "grasshoppers"], ["langostas", "as"], ["cuando", "when"], ["comenzaba", "beginning"], ["a", "to"], ["crecer", "grow"], ["el", "the"], ["heno", "up"], ["tardío;", "of;"], ["y", "and"], ["he", "I-have"], ["aquí,", "here,"], ["el", "the"], ["heno", "lo,"], ["tardío", "was"], ["venía", "coming"], ["después", "after/afterward"], ["de", "of"], ["las", "the"], ["siegas", "harvests"], ["del", "of-the"], ["rey.", "king."]]},
  {num:2,words:[["Y", "and"], ["acaeció", "pass"], ["que", "that"], ["cuando", "when"], ["las", "the"], ["langostas", "as"], ["acabaron", "pass"], ["de", "of"], ["comer", "eat"], ["la", "the"], ["hierba", "herb"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["yo", "I"], ["dije:", "I-said:"], ["Oh", "oh"], ["Señor,", "Lord,"], ["Jehová,", "jehovah,"], ["perdona,", "forgive,"], ["te", "thee"], ["ruego;", "I-pray/beseech;"], ["¿quién", "who"], ["levantará", "raise"], ["a", "to"], ["Jacob?,", "Jacob?,"], ["porque", "because"], ["es", "is"], ["pequeño.", "small."]]},
  {num:3,words:[["Se", "[refl.]"], ["arrepintió", "repented"], ["Jehová", "jehovah"], ["de", "of"], ["esto:", "this:"], ["No", "not"], ["será,", "shall-be,"], ["dijo", "said"], ["Jehová.", "jehovah."]]},
  {num:4,words:[["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["me", "me"], ["mostró", "showed"], ["así:", "thus:"], ["Y", "and"], ["he", "I-have"], ["aquí,", "here,"], ["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["llamaba", "was-called"], ["para", "for"], ["juzgar", "judge"], ["con", "with"], ["fuego;", "fire;"], ["y", "and"], ["consumió", "devoured"], ["el", "the"], ["gran", "great"], ["abismo", "deep"], ["y", "and"], ["consumió", "devoured"], ["una", "a"], ["parte", "part"], ["de", "of"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:5,words:[["Y", "and"], ["dije:", "I-said:"], ["Señor,", "Lord,"], ["Jehová,", "jehovah,"], ["cesa,", "god,"], ["te", "thee"], ["ruego;", "I-pray/beseech;"], ["¿quién", "who"], ["levantará", "raise"], ["a", "to"], ["Jacob?,", "Jacob?,"], ["porque", "because"], ["es", "is"], ["pequeño.", "small."]]},
  {num:6,words:[["Se", "[refl.]"], ["arrepintió", "repented"], ["Jehová", "jehovah"], ["de", "of"], ["esto:", "this:"], ["No", "not"], ["será", "shall-be"], ["esto", "this"], ["tampoco,", "neither,"], ["dijo", "said"], ["Jehová", "jehovah"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:7,words:[["Me", "me"], ["enseñó", "taught"], ["así:", "thus:"], ["Y", "and"], ["he", "I-have"], ["aquí,", "here,"], ["el", "the"], ["Señor", "Lord"], ["estaba", "was"], ["sobre", "upon"], ["un", "a"], ["muro", "wall"], ["hecho", "done/made"], ["a", "to"], ["plomo,", "lead,"], ["y", "and"], ["en", "in"], ["su", "his/her"], ["mano", "hand"], ["tenía", "had"], ["una", "a"], ["plomada", "in"], ["de", "of"], ["albañil.", "hand."]]},
  {num:8,words:[["Jehová", "jehovah"], ["entonces", "then"], ["me", "me"], ["dijo:", "said:"], ["¿Qué", "what"], ["ves,", "seest,"], ["Amós?", "amos?"], ["Y", "and"], ["dije:", "I-said:"], ["Una", "a"], ["plomada", "said,"], ["de", "of"], ["albañil.", "plumbline."], ["Y", "and"], ["el", "the"], ["Señor", "Lord"], ["dijo:", "said:"], ["He", "I-have"], ["aquí,", "here,"], ["yo", "I"], ["pongo", "lay"], ["plomada", "in"], ["de", "of"], ["albañil", "midst"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["mi", "my"], ["pueblo", "people"], ["Israel;", "Israel;"], ["ya", "already"], ["no", "not"], ["lo", "it/him"], ["toleraré", "any"], ["más.", "more."]]},
  {num:9,words:[["Y", "and"], ["los", "the"], ["lugares", "places"], ["altos", "high"], ["de", "of"], ["Isaac", "Isaac"], ["serán", "shall-be"], ["destruidos,", "destroyed,"], ["y", "and"], ["los", "the"], ["santuarios", "sanctuaries"], ["de", "of"], ["Israel", "Israel"], ["serán", "shall-be"], ["asolados;", "the;"], ["y", "and"], ["me", "me"], ["levantaré", "raise"], ["con", "with"], ["espada", "sword"], ["contra", "against"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jeroboam.", "jeroboam."]]},
  {num:10,words:[["Entonces", "then"], ["el", "the"], ["sacerdote", "priest"], ["Amasías", "amaziah"], ["de", "of"], ["Bet-el", "bethel"], ["envió", "sent"], ["a", "to"], ["decir", "say"], ["a", "to"], ["Jeroboam,", "jeroboam,"], ["rey", "king"], ["de", "of"], ["Israel:", "Israel:"], ["Amós", "amos"], ["ha", "has"], ["conspirado", "thee"], ["contra", "against"], ["ti", "thee"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel;", "Israel;"], ["la", "the"], ["tierra", "land/earth"], ["no", "not"], ["puede", "can"], ["soportar", "bear"], ["todas", "all"], ["sus", "his/her"], ["palabras.", "words."]]},
  {num:11,words:[["Porque", "because"], ["así", "thus"], ["ha", "has"], ["dicho", "said"], ["Amós:", "amos:"], ["Jeroboam", "jeroboam"], ["morirá", "die"], ["a", "to"], ["espada,", "sword,"], ["e", "and"], ["Israel", "Israel"], ["ciertamente", "surely"], ["será", "shall-be"], ["llevado", "carried"], ["de", "of"], ["su", "his/her"], ["tierra", "land/earth"], ["en", "in"], ["cautiverio.", "captivity."]]},
  {num:12,words:[["Y", "and"], ["Amasías", "amaziah"], ["dijo", "said"], ["a", "to"], ["Amós:", "amos:"], ["Vidente,", "seer,"], ["vete;", "get;"], ["huye", "flee"], ["a", "to"], ["tierra", "land/earth"], ["de", "of"], ["Judá,", "Judah,"], ["y", "and"], ["come", "eateth"], ["allá", "thither"], ["tu", "thy"], ["pan", "bread"], ["y", "and"], ["profetiza", "prophesieth"], ["allá;", "thither;"]]},
  {num:13,words:[["y", "and"], ["no", "not"], ["profetices", "again"], ["más", "more"], ["en", "in"], ["Bet-el,", "bethel,"], ["porque", "because"], ["es", "is"], ["santuario", "sanctuary"], ["del", "of-the"], ["rey", "king"], ["y", "and"], ["casa", "house"], ["del", "of-the"], ["reino.", "kingdom."]]},
  {num:14,words:[["Entonces", "then"], ["respondió", "answered"], ["Amós,", "amos,"], ["y", "and"], ["dijo", "said"], ["a", "to"], ["Amasías:", "amaziah:"], ["No", "not"], ["soy", "I-am"], ["profeta", "prophet"], ["ni", "nor"], ["soy", "I-am"], ["hijo", "son"], ["de", "of"], ["profeta,", "prophet,"], ["sino", "but"], ["que", "that"], ["soy", "I-am"], ["boyero", "and"], ["y", "and"], ["recojo", "gatherer"], ["higos", "figs"], ["silvestres;", "wild;"]]},
  {num:15,words:[["y", "and"], ["Jehová", "jehovah"], ["me", "me"], ["tomó", "took"], ["de", "of"], ["detrás", "behind"], ["del", "of-the"], ["ganado,", "cattle/gained,"], ["y", "and"], ["me", "me"], ["dijo", "said"], ["Jehová:", "jehovah:"], ["Ve", "sees"], ["y", "and"], ["profetiza", "prophesieth"], ["a", "to"], ["mi", "my"], ["pueblo", "people"], ["Israel.", "Israel."]]},
  {num:16,words:[["Ahora,", "now,"], ["pues,", "for,"], ["oye", "hears"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová.", "jehovah."], ["Tú", "thou"], ["dices:", "sayest:"], ["No", "not"], ["profetices", "against"], ["contra", "against"], ["Israel", "Israel"], ["ni", "nor"], ["hables", "not"], ["contra", "against"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Isaac.", "Isaac."]]},
  {num:17,words:[["Por", "by/for"], ["tanto,", "so-much,"], ["así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Tu", "thy"], ["esposa", "wife"], ["se", "[refl.]"], ["prostituirá", "harlot"], ["en", "in"], ["la", "the"], ["ciudad,", "city,"], ["y", "and"], ["tus", "thy"], ["hijos", "children"], ["y", "and"], ["tus", "thy"], ["hijas", "daughters"], ["caerán", "fall"], ["a", "to"], ["espada,", "sword,"], ["y", "and"], ["tu", "thy"], ["tierra", "land/earth"], ["será", "shall-be"], ["repartida", "divided"], ["a", "to"], ["cordel;", "line;"], ["y", "and"], ["tú", "thou"], ["morirás", "die"], ["en", "in"], ["tierra", "land/earth"], ["inmunda,", "unclean,"], ["e", "and"], ["Israel", "Israel"], ["ciertamente", "surely"], ["será", "shall-be"], ["llevado", "carried"], ["cautivo", "captive"], ["lejos", "far"], ["de", "of"], ["su", "his/her"], ["tierra.", "land/earth."]]},
];
renderVerseSet(v7, 'amo-ch7-verses');

var v8 = [
  {num:1,words:[["Así", "thus"], ["me", "me"], ["ha", "has"], ["mostrado", "shown"], ["Jehová", "jehovah"], ["el", "the"], ["Señor:", "Lord:"], ["Y", "and"], ["he", "I-have"], ["aquí,", "here,"], ["un", "a"], ["canastillo", "basket"], ["de", "of"], ["fruta", "the"], ["de", "of"], ["verano.", "summer."]]},
  {num:2,words:[["Y", "and"], ["dijo:", "said:"], ["¿Qué", "what"], ["ves,", "seest,"], ["Amós?", "amos?"], ["Y", "and"], ["dije:", "I-said:"], ["Un", "a"], ["canastillo", "basket"], ["de", "of"], ["fruta", "the"], ["de", "of"], ["verano.", "summer."], ["Y", "and"], ["me", "me"], ["dijo", "said"], ["Jehová:", "jehovah:"], ["Ha", "has"], ["venido", "come"], ["el", "the"], ["fin", "end"], ["sobre", "upon"], ["mi", "my"], ["pueblo", "people"], ["Israel;", "Israel;"], ["ya", "already"], ["no", "not"], ["lo", "it/him"], ["toleraré", "them"], ["más.", "more."]]},
  {num:3,words:[["Y", "and"], ["los", "the"], ["cantores", "singers"], ["del", "of-the"], ["templo", "temple"], ["aullarán", "shall"], ["en", "in"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová", "jehovah"], ["el", "the"], ["Señor;", "Lord;"], ["muchos", "many"], ["serán", "shall-be"], ["los", "the"], ["cuerpos", "carcases"], ["muertos;", "dead;"], ["en", "in"], ["cualquier", "any"], ["lugar", "place"], ["serán", "shall-be"], ["echados", "driven"], ["en", "in"], ["silencio.", "silence."]]},
  {num:4,words:[["Oíd", "hear"], ["esto,", "this,"], ["los", "the"], ["que", "that"], ["pisoteáis", "swallow"], ["a", "to"], ["los", "the"], ["menesterosos", "needy"], ["y", "and"], ["arruináis", "make"], ["a", "to"], ["los", "the"], ["pobres", "poor"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"]]},
  {num:5,words:[["diciendo:", "saying:"], ["¿Cuándo", "when"], ["pasará", "through"], ["la", "the"], ["luna", "moon"], ["nueva,", "new,"], ["para", "for"], ["que", "that"], ["vendamos", "that"], ["el", "the"], ["trigo,", "wheat,"], ["y", "and"], ["el", "the"], ["día", "day"], ["de", "of"], ["reposo,", "rest,"], ["para", "for"], ["que", "that"], ["abramos", "may"], ["los", "the"], ["alfolíes", "set"], ["del", "of-the"], ["trigo,", "wheat,"], ["y", "and"], ["achiquemos", "the"], ["la", "the"], ["medida,", "measure,"], ["y", "and"], ["subamos", "us"], ["el", "the"], ["precio", "price"], ["y", "and"], ["falseemos", "falsifying"], ["con", "with"], ["engaño", "guile"], ["la", "the"], ["balanza;", "the;"]]},
  {num:6,words:[["para", "for"], ["que", "that"], ["compremos", "may"], ["a", "to"], ["los", "the"], ["pobres", "poor"], ["por", "by/for"], ["dinero", "sacks"], ["y", "and"], ["a", "to"], ["los", "the"], ["necesitados", "needy"], ["por", "by/for"], ["un", "a"], ["par", "of"], ["de", "of"], ["sandalias,", "and,"], ["y", "and"], ["vendamos", "the"], ["los", "the"], ["desechos", "of"], ["del", "of-the"], ["trigo?", "wheat?"]]},
  {num:7,words:[["Jehová", "jehovah"], ["ha", "has"], ["jurado", "sworn"], ["por", "by/for"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["Jacob:", "Jacob:"], ["No", "not"], ["me", "me"], ["olvidaré", "forget"], ["jamás", "never"], ["de", "of"], ["ninguna", "none"], ["de", "of"], ["sus", "his/her"], ["obras.", "works."]]},
  {num:8,words:[["¿No", "not"], ["se", "[refl.]"], ["estremecerá", "the"], ["la", "the"], ["tierra", "land/earth"], ["por", "by/for"], ["esto?", "this?"], ["¿Y", "and"], ["no", "not"], ["llorará", "that"], ["todo", "all"], ["habitante", "dwell-thee"], ["de", "of"], ["ella?", "she?"], ["Y", "and"], ["subirá", "up"], ["toda", "all"], ["ella", "she"], ["como", "as"], ["un", "a"], ["río,", "river,"], ["y", "and"], ["se", "[refl.]"], ["desbordará", "cast"], ["y", "and"], ["menguará", "drowned,"], ["como", "as"], ["el", "the"], ["río", "river"], ["de", "of"], ["Egipto.", "Egypt."]]},
  {num:9,words:[["Y", "and"], ["acaecerá", "it"], ["en", "in"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová", "jehovah"], ["el", "the"], ["Señor,", "Lord,"], ["que", "that"], ["haré", "I-shall-make"], ["que", "that"], ["se", "[refl.]"], ["ponga", "set"], ["el", "the"], ["sol", "sun"], ["a", "to"], ["mediodía", "noonday"], ["y", "and"], ["cubriré", "and"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["tinieblas", "darkness"], ["en", "in"], ["pleno", "in"], ["día.", "day."]]},
  {num:10,words:[["Y", "and"], ["cambiaré", "i"], ["vuestras", "your"], ["fiestas", "moons"], ["en", "in"], ["duelo", "mourned"], ["y", "and"], ["todos", "all"], ["vuestros", "your"], ["cantares", "sings"], ["en", "in"], ["lamentaciones;", "of;"], ["y", "and"], ["haré", "I-shall-make"], ["poner", "put/place"], ["cilicio", "sackcloth"], ["sobre", "upon"], ["todo", "all"], ["lomo,", "all,"], ["y", "and"], ["que", "that"], ["se", "[refl.]"], ["rape", "upon"], ["toda", "all"], ["cabeza;", "head;"], ["y", "and"], ["la", "the"], ["volveré", "return"], ["como", "as"], ["en", "in"], ["llanto", "gnashing"], ["por", "by/for"], ["el", "the"], ["hijo", "son"], ["único,", "only,"], ["y", "and"], ["su", "his/her"], ["final", "end"], ["será", "shall-be"], ["como", "as"], ["día", "day"], ["amargo.", "bitter."]]},
  {num:11,words:[["He", "I-have"], ["aquí,", "here,"], ["vienen", "come"], ["días,", "days,"], ["dice", "says"], ["Jehová", "jehovah"], ["el", "the"], ["Señor,", "Lord,"], ["en", "in"], ["los", "the"], ["cuales", "which"], ["enviaré", "send"], ["hambre", "famine"], ["a", "to"], ["la", "the"], ["tierra,", "land/earth,"], ["no", "not"], ["hambre", "famine"], ["de", "of"], ["pan", "bread"], ["ni", "nor"], ["sed", "thirst/be"], ["de", "of"], ["agua,", "water,"], ["sino", "but"], ["de", "of"], ["oír", "hear"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:12,words:[["E", "and"], ["irán", "go"], ["errantes", "wilderness"], ["de", "of"], ["mar", "sea"], ["a", "to"], ["mar;", "sea;"], ["desde", "from"], ["el", "the"], ["norte", "north"], ["hasta", "until"], ["el", "the"], ["oriente", "east"], ["andarán", "walk"], ["buscando", "seeking"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["y", "and"], ["no", "not"], ["la", "the"], ["hallarán.", "find."]]},
  {num:13,words:[["En", "in"], ["aquel", "that"], ["día", "day"], ["las", "the"], ["doncellas", "the"], ["hermosas", "and"], ["y", "and"], ["los", "the"], ["jóvenes", "young-men"], ["desmayarán", "faint"], ["de", "of"], ["sed.", "thirst/be."]]},
  {num:14,words:[["Los", "the"], ["que", "that"], ["juran", "swear"], ["por", "by/for"], ["el", "the"], ["pecado", "sin"], ["de", "of"], ["Samaria", "samaria"], ["y", "and"], ["dicen:", "say:"], ["¡Viva", "quick"], ["tu", "thy"], ["dios,", "God,"], ["oh", "oh"], ["Dan!", "dan!"], ["y:", "and:"], ["¡Viva", "quick"], ["el", "the"], ["camino", "way"], ["de", "of"], ["Beerseba!", "beersheba!"], ["caerán", "fall"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["se", "[refl.]"], ["levantarán.", "rise."]]},
];
renderVerseSet(v8, 'amo-ch8-verses');

var v9 = [
  {num:1,words:[["Vi", "I-saw"], ["al", "to-the"], ["Señor", "Lord"], ["que", "that"], ["estaba", "was"], ["sobre", "upon"], ["el", "the"], ["altar,", "altar,"], ["y", "and"], ["dijo:", "said:"], ["Golpea", "the"], ["los", "the"], ["capiteles,", "chapiters,"], ["y", "and"], ["estremézcanse", "may"], ["los", "the"], ["umbrales,", "thresholds,"], ["y", "and"], ["hazlos", "do-them"], ["pedazos", "pieces"], ["sobre", "upon"], ["la", "the"], ["cabeza", "head"], ["de", "of"], ["todos;", "all;"], ["y", "and"], ["al", "to-the"], ["resto", "remnant"], ["de", "of"], ["ellos", "they"], ["mataré", "will"], ["a", "to"], ["espada;", "sword;"], ["no", "not"], ["habrá", "there-shall-be"], ["de", "of"], ["ellos", "they"], ["quien", "who"], ["huya", "flee"], ["ni", "nor"], ["quien", "who"], ["escape.", "escape."]]},
  {num:2,words:[["Aunque", "although"], ["caven", "they"], ["hasta", "until"], ["el", "the"], ["Seol,", "grave,"], ["de", "of"], ["allá", "thither"], ["los", "the"], ["tomará", "take"], ["mi", "my"], ["mano;", "hand;"], ["y", "and"], ["aunque", "although"], ["suban", "up"], ["hasta", "until"], ["el", "the"], ["cielo,", "heaven,"], ["de", "of"], ["allá", "thither"], ["los", "the"], ["haré", "I-shall-make"], ["descender.", "grave."]]},
  {num:3,words:[["Y", "and"], ["aunque", "although"], ["se", "[refl.]"], ["escondan", "hide"], ["en", "in"], ["la", "the"], ["cumbre", "top"], ["del", "of-the"], ["Carmelo,", "carmel,"], ["allí", "there"], ["los", "the"], ["buscaré", "will"], ["y", "and"], ["los", "the"], ["tomaré;", "take;"], ["y", "and"], ["aunque", "although"], ["se", "[refl.]"], ["escondan", "be"], ["de", "of"], ["delante", "before"], ["de", "of"], ["mis", "my"], ["ojos", "eyes"], ["en", "in"], ["lo", "it/him"], ["profundo", "deep"], ["del", "of-the"], ["mar,", "sea,"], ["allí", "there"], ["mandaré", "command"], ["a", "to"], ["la", "the"], ["serpiente,", "serpent,"], ["y", "and"], ["los", "the"], ["morderá.", "them."]]},
  {num:4,words:[["Y", "and"], ["si", "if"], ["van", "go"], ["al", "to-the"], ["cautiverio", "captivity"], ["delante", "before"], ["de", "of"], ["sus", "his/her"], ["enemigos,", "enemies,"], ["allí", "there"], ["mandaré", "command"], ["la", "the"], ["espada,", "sword,"], ["y", "and"], ["los", "the"], ["matará;", "slay;"], ["y", "and"], ["pondré", "I-shall-put"], ["sobre", "upon"], ["ellos", "they"], ["mis", "my"], ["ojos", "eyes"], ["para", "for"], ["mal", "evil"], ["y", "and"], ["no", "not"], ["para", "for"], ["bien.", "well."]]},
  {num:5,words:[["El", "the"], ["Señor", "Lord"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["es", "is"], ["el", "the"], ["que", "that"], ["toca", "if"], ["la", "the"], ["tierra,", "land/earth,"], ["y", "and"], ["esta", "this"], ["se", "[refl.]"], ["derretirá,", "and,"], ["y", "and"], ["llorarán", "shall"], ["todos", "all"], ["los", "the"], ["que", "that"], ["en", "in"], ["ella", "she"], ["moran;", "dwell;"], ["y", "and"], ["subirá", "up"], ["toda", "all"], ["ella", "she"], ["como", "as"], ["un", "a"], ["río", "river"], ["y", "and"], ["menguará", "be"], ["luego", "then"], ["como", "as"], ["el", "the"], ["río", "river"], ["de", "of"], ["Egipto.", "Egypt."]]},
  {num:6,words:[["Él", "he"], ["edificó", "built"], ["en", "in"], ["el", "the"], ["cielo", "heaven"], ["sus", "his/her"], ["moradas", "shall"], ["y", "and"], ["ha", "has"], ["establecido", "established"], ["su", "his/her"], ["expansión", "expanse"], ["sobre", "upon"], ["la", "the"], ["tierra;", "land/earth;"], ["él", "he"], ["llama", "calls/flame"], ["a", "to"], ["las", "the"], ["aguas", "waters"], ["del", "of-the"], ["mar", "sea"], ["y", "and"], ["sobre", "upon"], ["la", "the"], ["faz", "face"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["las", "the"], ["derrama;", "upon;"], ["Jehová", "jehovah"], ["es", "is"], ["su", "his/her"], ["nombre.", "name."]]},
  {num:7,words:[["Hijos", "children"], ["de", "of"], ["Israel,", "Israel,"], ["¿no", "not"], ["me", "me"], ["sois", "ye-are"], ["vosotros", "you"], ["como", "as"], ["hijos", "children"], ["de", "of"], ["etíopes?,", "children?,"], ["dice", "says"], ["Jehová.", "jehovah."], ["¿No", "not"], ["hice", "I-did"], ["yo", "I"], ["subir", "go-up"], ["a", "to"], ["Israel", "Israel"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto,", "Egypt,"], ["y", "and"], ["a", "to"], ["los", "the"], ["filisteos", "philistines"], ["de", "of"], ["Caftor,", "philistines,"], ["y", "and"], ["de", "of"], ["Kir", "the"], ["a", "to"], ["los", "the"], ["arameos?", "kir?"]]},
  {num:8,words:[["He", "I-have"], ["aquí,", "here,"], ["los", "the"], ["ojos", "eyes"], ["de", "of"], ["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["están", "are"], ["sobre", "upon"], ["el", "the"], ["reino", "kingdom"], ["pecador,", "sinner,"], ["y", "and"], ["yo", "I"], ["lo", "it/him"], ["destruiré", "destroy"], ["de", "of"], ["la", "the"], ["faz", "face"], ["de", "of"], ["la", "the"], ["tierra;", "land/earth;"], ["mas", "but"], ["no", "not"], ["destruiré", "destroy"], ["del", "of-the"], ["todo", "all"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jacob,", "Jacob,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:9,words:[["Porque", "because"], ["he", "I-have"], ["aquí,", "here,"], ["yo", "I"], ["mandaré", "command"], ["y", "and"], ["haré", "I-shall-make"], ["que", "that"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel", "Israel"], ["sea", "let-be/be"], ["zarandeada", "among"], ["entre", "among"], ["todas", "all"], ["las", "the"], ["naciones,", "nations,"], ["como", "as"], ["se", "[refl.]"], ["zarandea", "is"], ["el", "the"], ["grano", "grain"], ["en", "in"], ["una", "a"], ["criba,", "yet,"], ["sin", "without"], ["que", "that"], ["caiga", "fall"], ["ni", "nor"], ["un", "a"], ["granito", "little-great"], ["en", "in"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:10,words:[["A", "to"], ["espada", "sword"], ["morirán", "die"], ["todos", "all"], ["los", "the"], ["pecadores", "sinners"], ["de", "of"], ["mi", "my"], ["pueblo,", "people,"], ["los", "the"], ["que", "that"], ["dicen:", "say:"], ["No", "not"], ["se", "[refl.]"], ["acercará", "come"], ["ni", "nor"], ["nos", "us"], ["alcanzará", "shall"], ["el", "the"], ["mal.", "evil."]]},
  {num:11,words:[["En", "in"], ["aquel", "that"], ["día", "day"], ["yo", "I"], ["levantaré", "raise"], ["el", "the"], ["tabernáculo", "tabernacle"], ["caído", "fallen"], ["de", "of"], ["David,", "David,"], ["y", "and"], ["cerraré", "up"], ["sus", "his/her"], ["brechas,", "breaches,"], ["y", "and"], ["levantaré", "raise"], ["sus", "his/her"], ["ruinas", "waste"], ["y", "and"], ["lo", "it/him"], ["reedificaré", "will"], ["como", "as"], ["en", "in"], ["el", "the"], ["tiempo", "time"], ["pasado,", "past,"]]},
  {num:12,words:[["para", "for"], ["que", "that"], ["posean", "possess"], ["el", "the"], ["remanente", "remnant"], ["de", "of"], ["Edom", "edom"], ["y", "and"], ["de", "of"], ["todas", "all"], ["las", "the"], ["naciones", "nations"], ["que", "that"], ["son", "are"], ["llamadas", "calleds"], ["por", "by/for"], ["mi", "my"], ["nombre,", "name,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["que", "that"], ["hace", "does/makes"], ["esto.", "this."]]},
  {num:13,words:[["He", "I-have"], ["aquí,", "here,"], ["vienen", "come"], ["días,", "days,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["en", "in"], ["que", "that"], ["el", "the"], ["que", "that"], ["ara", "of"], ["alcanzará", "shall"], ["al", "to-the"], ["segador,", "reaper,"], ["y", "and"], ["el", "the"], ["pisador", "treader"], ["de", "of"], ["las", "the"], ["uvas", "grapes"], ["al", "to-the"], ["que", "that"], ["lleve", "you"], ["la", "the"], ["simiente;", "seed;"], ["y", "and"], ["los", "the"], ["montes", "mountains"], ["destilarán", "drop"], ["vino", "wine"], ["dulce,", "sweet,"], ["y", "and"], ["todos", "all"], ["los", "the"], ["collados", "hills"], ["se", "[refl.]"], ["derretirán.", "melt."]]},
  {num:14,words:[["Y", "and"], ["traeré", "bring"], ["del", "of-the"], ["cautiverio", "captivity"], ["a", "to"], ["mi", "my"], ["pueblo", "people"], ["Israel,", "Israel,"], ["y", "and"], ["reedificarán", "israel,"], ["ellos", "they"], ["las", "the"], ["ciudades", "cities"], ["asoladas", "desolate"], ["y", "and"], ["las", "the"], ["habitarán;", "dwell;"], ["y", "and"], ["plantarán", "shall"], ["viñas", "vineyards"], ["y", "and"], ["beberán", "drink"], ["el", "the"], ["vino", "wine"], ["de", "of"], ["ellas,", "they,"], ["y", "and"], ["harán", "shall-make"], ["huertos", "gardens"], ["y", "and"], ["comerán", "eat"], ["el", "the"], ["fruto", "fruit"], ["de", "of"], ["ellos.", "they."]]},
  {num:15,words:[["Pues", "for"], ["los", "the"], ["plantaré", "plant"], ["sobre", "upon"], ["su", "his/her"], ["tierra,", "land/earth,"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["serán", "shall-be"], ["arrancados", "be"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["que", "that"], ["yo", "I"], ["les", "them"], ["di,", "give/I-gave,"], ["ha", "has"], ["dicho", "said"], ["Jehová,", "jehovah,"], ["Dios", "God"], ["tuyo.", "thine."]]},
];
renderVerseSet(v9, 'amo-ch9-verses');

})();
