(function() {
var v1 = [
  {num:1,words:[["Las", "the"], ["palabras", "words"], ["de", "of"], ["Amós,","Amos,"], ["que", "that"], ["fue","was"], ["uno", "one"], ["de", "of"], ["los", "the"], ["pastores", "pastors"], ["de", "of"], ["Tecoa,","Tekoa,"], ["sobre", "upon"], ["lo", "it/him"], ["que", "that"], ["vio", "saw"], ["acerca", "about"], ["de", "of"], ["Israel", "Israel"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["Uzías,","Uzziah,"], ["rey", "king"], ["de", "of"], ["Judá,", "Judah,"], ["y", "and"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["Jeroboam","Jeroboam"], ["hijo", "son"], ["de", "of"], ["Joás,","Joash,"], ["rey", "king"], ["de", "of"], ["Israel,", "Israel,"], ["dos", "two"], ["años", "years"], ["antes", "before"], ["del", "of-the"], ["terremoto.", "earthquake."]]},
  {num:2,words:[["Y","and"],["dijo:","said:"],["Jehová","jehovah"],["rugirá","will-roar"],["desde","from"],["Sion","Zion"],["y","and"],["dará","shall-give"],["su","his"],["voz","voice"],["desde","from"],["Jerusalén;","Jerusalem;"],["y","and"],["los","the"],["pastizales","grassy areas"],["de","of"],["los","the"],["pastores","pastors"],["estarán","they-stand"],["de","of"],["duelo,","mourned,"],["y","and"],["se","himself"],["secará","will-dry"],["la","the"],["cumbre","top"],["del","of-the"],["Carmelo.","Carmel."]]},
  {num:3,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["Damasco,","Damascus,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","his"],["castigo,","punishment,"],["porque","because"],["trillaron","have"],["a","to"],["Galaad","Gilead"],["con","with"],["trillos","threshing"],["de","of"],["hierro.","iron."]]},
  {num:4,words:[["Y","and"],["enviaré","I-will-send"],["fuego","fire"],["a","to"],["la","the"],["casa","house"],["de","of"],["Hazael,","Hazael,"],["y","and"],["consumirá","palaces"],["los","the"],["palacios","palaces"],["de","of"],["Ben-adad.","Ben-hadad."]]},
  {num:5,words:[["Y","and"],["quebraré","I-will"],["el","the"],["cerrojo","the"],["de","of"],["Damasco,","Damascus,"],["y","and"],["talaré","I-cut"],["a","to"],["los","the"],["moradores","inhabitants"],["del","of-the"],["valle","valley"],["de","of"],["Avén","Aven"],["y","and"],["a","to"],["los","the"],["gobernadores","governors"],["de","of"],["Bet-edén;","house;"],["y","and"],["el","the"],["pueblo","people"],["de","of"],["Siria","Syria"],["será","shall-be"],["llevado","carried"],["cautivo","captive"],["a","to"],["Kir,","Kir,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:6,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["Gaza,","Gaza,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","his"],["castigo,","punishment,"],["porque","because"],["llevó","carried"],["cautivo","captive"],["a","to"],["todo","all"],["un","a"],["pueblo","people"],["para","for"],["entregarlo","betray-it"],["a","to"],["Edom.","Edom."]]},
  {num:7,words:[["Y","and"],["enviaré","I-will-send"],["fuego","fire"],["al","to-the"],["muro","wall"],["de","of"],["Gaza,","Gaza,"],["y","and"],["consumirá","palaces"],["sus","his"],["palacios.","palaces."]]},
  {num:8,words:[["Y","and"],["talaré","I-cut"],["a","to"],["los","the"],["moradores","inhabitants"],["de","of"],["Asdod","Ashdod"],["y","and"],["a","to"],["los","the"],["gobernadores","governors"],["de","of"],["Ascalón;","Ashkelon;"],["y","and"],["volveré","I-will-return"],["mi","my"],["mano","hand"],["contra","against"],["Ecrón,","Ekron,"],["y","and"],["el","the"],["remanente","remnant"],["de","of"],["los","the"],["filisteos","philistines"],["perecerá,","will-perish,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["el","the"],["Señor.","Lord."]]},
  {num:9,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["Tiro,","tyrus,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","his"],["castigo,","punishment,"],["porque","because"],["entregaron","they-delivered"],["a","to"],["todo","all"],["un","a"],["pueblo","people"],["cautivo","captive"],["a","to"],["Edom","Edom"],["y","and"],["no","not"],["se","themselves"],["acordaron","they"],["del","of-the"],["pacto","covenant"],["de","of"],["hermanos.","brothers."]]},
  {num:10,words:[["Y","and"],["enviaré","I-will-send"],["fuego","fire"],["al","to-the"],["muro","wall"],["de","of"],["Tiro,","tyrus,"],["y","and"],["consumirá","palaces"],["sus","his"],["palacios.","palaces."]]},
  {num:11,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["Edom,","Edom,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","his"],["castigo,","punishment,"],["porque","because"],["persiguió","pursued"],["a","to"],["espada","sword"],["a","to"],["su","his"],["hermano","brother"],["y","and"],["no","not"],["tuvo","had"],["compasión","compassion"],["alguna;","some;"],["y","and"],["en","in"],["su","his"],["furor","fury"],["se","himself"],["enardecía","did"],["de","of"],["continuo","continual"],["y","and"],["ha","has"],["guardado","kept"],["el","the"],["enojo","fury"],["perpetuamente","ever"]]},
  {num:12,words:[["Y","and"],["enviaré","I-will-send"],["fuego","fire"],["a","to"],["Temán,","Teman,"],["y","and"],["consumirá","palaces"],["los","the"],["palacios","palaces"],["de","of"],["Bosra.","Bozrah."]]},
  {num:13,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["los","the"],["hijos","children"],["de","of"],["Amón,","Ammon,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","their"],["castigo,","punishment,"],["porque","because"],["les","them"],["abrieron","they-opened"],["el","the"],["vientre","belly"],["a","to"],["las","the"],["de","of"],["Galaad","Gilead"],["que","that"],["estaban","they-were"],["encintas,","child,"],["para","for"],["ensanchar","enlarge"],["sus","their"],["fronteras.","borders."]]},
  {num:14,words:[["Y","and"],["encenderé","i"],["fuego","fire"],["en","in"],["el","the"],["muro","wall"],["de","of"],["Rabá,","Rabbah,"],["y","and"],["consumirá","palaces"],["sus","his"],["palacios","palaces"],["con","with"],["estruendo","noise"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["batalla,","battle,"],["con","with"],["tempestad","storm"],["en","in"],["el","the"],["día","day"],["tempestuoso;","whirlwind;"]]},
  {num:15,words:[["y","and"],["su","his"],["rey","king"],["irá","well"],["al","to-the"],["cautiverio,","captivity,"],["él","he"],["y","and"],["todos","all"],["sus","his"],["príncipes,","princes,"],["dice","says"],["Jehová.","jehovah."]]},
];
renderVerseSet(v1, 'amo-ch1-verses');

var v2 = [
  {num:1,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["Moab,","Moab,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","his"],["castigo,","punishment,"],["porque","because"],["quemó","burned"],["los","the"],["huesos","bones"],["del","of-the"],["rey","king"],["de","of"],["Edom","Edom"],["hasta","until"],["calcinarlos.","lime."]]},
  {num:2,words:[["Y","and"],["enviaré","I-will-send"],["fuego","fire"],["a","to"],["Moab,","Moab,"],["y","and"],["consumirá","palaces"],["los","the"],["palacios","palaces"],["de","of"],["Queriot;","Kerioth;"],["y","and"],["morirá","will-die"],["Moab","Moab"],["en","in"],["medio","midst"],["del","of-the"],["alboroto,","tumult,"],["en","in"],["medio","midst"],["del","of-the"],["estrépito","clamor"],["y","and"],["con","with"],["sonido","trumpet"],["de","of"],["trompeta.","trump."]]},
  {num:3,words:[["Y","and"],["quitaré","I-take"],["al","to-the"],["juez","judge"],["de","of"],["en","in"],["medio","midst"],["de","of"],["él","he"],["y","and"],["mataré","will"],["junto","together"],["con","with"],["él","he"],["a","to"],["todos","all"],["sus","his"],["príncipes,","princes,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:4,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["Judá,","Judah,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","his"],["castigo,","punishment,"],["porque","because"],["menospreciaron","they"],["la","the"],["ley","law"],["de","of"],["Jehová","jehovah"],["y","and"],["no","not"],["guardaron","they-kept"],["sus","his"],["estatutos;","statutes;"],["y","and"],["los","the"],["hicieron","did/made"],["errar","err"],["sus","his"],["mentiras,","lyings,"],["en pos de","after"],["las","the"],["cuales","which"],["anduvieron","they-walked"],["sus","his"],["padres.","parents."]]},
  {num:5,words:[["Enviaré,","I-will-send,"],["por tanto,","therefore,"],["fuego","fire"],["a","to"],["Judá,","Judah,"],["el","the"],["cual","which"],["consumirá","palaces"],["los","the"],["palacios","palaces"],["de","of"],["Jerusalén.","Jerusalem."]]},
  {num:6,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Por","for"],["tres","three"],["transgresiones","transgressions"],["de","of"],["Israel,","Israel,"],["y","and"],["por","for"],["la","the"],["cuarta,","fourth,"],["no","not"],["revocaré","I-punishment"],["su","his"],["castigo,","punishment,"],["porque","because"],["vendieron","because"],["por","for"],["dinero","sacks"],["al","to-the"],["justo","righteous"],["y","and"],["al","to-the"],["pobre","poor"],["por","for"],["un","a"],["par","of"],["de","of"],["sandalias;","and;"]]},
  {num:7,words:[["porque","because"],["pisotean","they-pant"],["hasta","until"],["el","the"],["polvo","dust"],["de","of"],["la","the"],["tierra","earth"],["la","the"],["cabeza","head"],["de","of"],["los","the"],["pobres","poor"],["y","and"],["tuercen","they-aside"],["el","the"],["camino","way"],["de","of"],["los","the"],["humildes;","humble;"],["y","and"],["un","a"],["hombre","man"],["y","and"],["su","his"],["padre","father"],["se","themselves"],["llegan","they"],["a","to"],["la","the"],["misma","same"],["joven,","young-man,"],["profanando","profane"],["mi","my"],["santo","holy"],["nombre.","name."]]},
  {num:8,words:[["Y","and"],["sobre","upon"],["las","the"],["ropas","robes"],["empeñadas","pledged"],["se","themselves"],["acuestan","laid"],["junto","together"],["a","to"],["cualquier","any"],["altar,","altar,"],["y","and"],["el","the"],["vino","wine"],["de","of"],["los","the"],["multados","fined"],["beben","they-drink"],["en","in"],["la","the"],["casa","house"],["de","of"],["sus","their"],["dioses.","gods."]]},
  {num:9,words:[["Y","and"],["yo","I"],["destruí","i"],["delante","before"],["de","of"],["ellos","they"],["al","to-the"],["amorreo,","amorite,"],["cuya","whose"],["altura","height"],["era","was"],["como","as"],["la","the"],["altura","height"],["de","of"],["los","the"],["cedros,","cedars,"],["y","and"],["que","that"],["era","was"],["fuerte","strong"],["como","as"],["una","a"],["encina;","oak;"],["y","and"],["destruí","I-fruit"],["su","his"],["fruto","fruit"],["arriba","above"],["y","and"],["sus","his"],["raíces","roots"],["abajo.","below."]]},
  {num:10,words:[["Y","and"],["a","to"],["vosotros","you"],["os","you"],["hice","I-did"],["subir","go-up"],["de","of"],["la","the"],["tierra","land"],["de","of"],["Egipto","Egypt"],["y","and"],["os","you"],["conduje","forty"],["por","for"],["el","the"],["desierto","wilderness"],["cuarenta","forty"],["años","years"],["para","for"],["que","that"],["poseyeseis","you-might-possess"],["la","the"],["tierra","land"],["del","of-the"],["amorreo.","amorite."]]},
  {num:11,words:[["Y","and"],["levanté","I-arose"],["profetas","prophets"],["de","of"],["vuestros","your"],["hijos","children"],["y","and"],["nazareos","nazarites"],["de","of"],["vuestros","your"],["jóvenes.","young-men."],["¿No","not"],["es","is"],["esto","this"],["así,","thus,"],["oh","oh"],["hijos","children"],["de","of"],["Israel?,","Israel?,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:12,words:[["Mas","but"],["vosotros","you"],["disteis","gave"],["de","of"],["beber","to-drink"],["vino","wine"],["a","to"],["los","the"],["nazareos,","nazarites,"],["y","and"],["a","to"],["los","the"],["profetas","prophets"],["mandasteis,","you-prophets,"],["diciendo:","saying:"],["No","not"],["profeticéis.","you-may-prophesy."]]},
  {num:13,words:[["Pues","for"],["he aquí,","behold,"],["yo","I"],["estoy","am"],["apretujado","you,"],["debajo","beneath"],["de","of"],["vosotros,","you,"],["como","as"],["se","himself"],["apretuja","pressed"],["el","the"],["carro","cart"],["lleno","full"],["de","of"],["gavillas;","sheaves;"]]},
  {num:14,words:[["y","and"],["el","the"],["ligero","flight"],["no","not"],["podrá","able"],["huir;","to-flee;"],["y","and"],["al","to-the"],["fuerte","strong"],["no","not"],["le","his"],["servirá","serve"],["su","his"],["fuerza,","strength,"],["ni","nor"],["el","the"],["valiente","valiant"],["salvará","will-save"],["su","his"],["vida;","life;"]]},
  {num:15,words:[["y","and"],["el","the"],["que","that"],["toma","take"],["el","the"],["arco","bow"],["no","not"],["resistirá,","shall-stand,"],["ni","nor"],["escapará","will-escape"],["el","the"],["ligero","light"],["de","of"],["pies,","feet,"],["ni","nor"],["el","the"],["que","that"],["cabalga","he"],["en","in"],["caballo","horse"],["salvará","will-save"],["su","his"],["vida.","life."]]},
  {num:16,words:[["Y","and"],["el","the"],["más","more"],["valiente","valiant"],["de","of"],["corazón","heart"],["entre","among"],["los","the"],["valientes","valour"],["huirá","will-flee"],["desnudo","naked"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová.","jehovah."]]},
];
renderVerseSet(v2, 'amo-ch2-verses');

var v3 = [
  {num:1,words:[["Oíd","you-hear"],["esta","this"],["palabra","word"],["que","that"],["ha","has"],["hablado","spoken"],["Jehová","jehovah"],["contra","against"],["vosotros,","you,"],["oh","oh"],["hijos","children"],["de","of"],["Israel,","Israel,"],["contra","against"],["toda","all"],["la","the"],["familia","family"],["que","that"],["hice","I-did"],["subir","go-up"],["de","of"],["la","the"],["tierra","land"],["de","of"],["Egipto.","Egypt."],["Dice","says"],["así:","thus:"]]},
  {num:2,words:[["Solamente", "only"], ["a", "to"], ["vosotros", "you"], ["he", "I-have"], ["conocido", "known"], ["de", "of"], ["todas", "all"], ["las", "the"], ["familias", "families"], ["de", "of"], ["la", "the"], ["tierra;","earth;"], ["por tanto,","therefore,"], ["os", "you"], ["castigaré", "punish"], ["por","for"], ["todas", "all"], ["vuestras", "your"], ["iniquidades.", "iniquities."]]},
  {num:3,words:[["¿Andarán","they-will-walk"],["dos","two"],["juntos","together"],["si","if"],["no","not"],["están","they-are"],["de","of"],["acuerdo?","agreement?"]]},
  {num:4,words:[["¿Rugirá","will"],["el","the"],["león","lion"],["en","in"],["el","the"],["bosque","forest"],["sin","without"],["haber","have"],["presa?","prey?"],["¿Dará","shall-give"],["el","the"],["leoncillo","lion"],["su","his"],["rugido","roared"],["desde","from"],["su","his"],["guarida","lair"],["sin","without"],["haber","have"],["apresado","taken"],["algo?","something?"]]},
  {num:5,words:[["¿Caerá","will-fall"],["el","the"],["ave","fowl"],["en","in"],["la","the"],["trampa,","snare,"],["en","in"],["la","the"],["tierra,","earth,"],["sin","without"],["haber","have"],["cebo?","bait?"],["¿Se","himself"],["levanta","raises"],["la","the"],["trampa","snare"],["de","of"],["la","the"],["tierra","earth"],["si","if"],["no","not"],["se","himself"],["ha","has"],["atrapado","trapped"],["algo?","something?"]]},
  {num:6,words:[["¿Se","himself"],["tocará","trump"],["la","the"],["trompeta","trump"],["en","in"],["la","the"],["ciudad,","city,"],["y","and"],["no","not"],["se","himself"],["alborotará","be"],["el","the"],["pueblo?","people?"],["¿Habrá","there-shall-be"],["algún","some"],["mal","evil"],["en","in"],["la","the"],["ciudad","city"],["que","that"],["Jehová","jehovah"],["no","not"],["haya","let-there-be"],["hecho?","done?"]]},
  {num:7,words:[["Porque","because"],["no","not"],["hará","shall-make"],["nada","nothing"],["Jehová","jehovah"],["el","the"],["Señor","Lord"],["sin","without"],["que","that"],["revele","may-reveal"],["su","his"],["secreto","openly"],["a","to"],["sus","his"],["siervos","servants"],["los","the"],["profetas.","prophets."]]},
  {num:8,words:[["Si","if"],["ruge","lion"],["el","the"],["león,","lion,"],["¿quién","who"],["no","not"],["temerá?","will-fear?"],["Si","if"],["habla","speaks"],["Jehová","jehovah"],["el","the"],["Señor,","Lord,"],["¿quién","who"],["no","not"],["profetizará?","shall-prophesy?"]]},
  {num:9,words:[["Haced","you-do"],["pregonar","the"],["sobre","upon"],["los","the"],["palacios","palaces"],["de","of"],["Asdod","Ashdod"],["y","and"],["sobre","upon"],["los","the"],["palacios","palaces"],["de","of"],["la","the"],["tierra","land"],["de","of"],["Egipto,","Egypt,"],["y","and"],["decid:","you-tell:"],["Reuníos","yourselves"],["sobre","upon"],["los","the"],["montes","mountains"],["de","of"],["Samaria","Samaria"],["y","and"],["ved","you-see"],["los","the"],["muchos","many"],["tumultos","tumults"],["en","in"],["medio","midst"],["de","of"],["ella","she"],["y","and"],["las","the"],["opresiones","oppressions"],["en","in"],["medio","midst"],["de","of"],["ella.","she."]]},
  {num:10,words:[["Y","and"],["no","not"],["saben","they-know"],["hacer","do"],["lo","it/him"],["recto,","upright,"],["dice","says"],["Jehová,","jehovah,"],["los","the"],["que","that"],["atesoran","they-store"],["violencia","violence"],["y","and"],["despojo","spoil"],["en","in"],["sus","their"],["palacios.","palaces."]]},
  {num:11,words:[["Por tanto,","therefore,"],["Jehová","jehovah"],["el","the"],["Señor","Lord"],["ha","has"],["dicho","said"],["así:","thus:"],["Un","a"],["enemigo","enemy"],["vendrá","shall-come"],["por","for"],["todos","all"],["los","the"],["lados","sides"],["de","of"],["la","the"],["tierra","land"],["y","and"],["derribará","shall"],["tu","your"],["fortaleza,","castle,"],["y","and"],["tus","your"],["palacios","palaces"],["serán","they-shall-be"],["saqueados.","spoiled."]]},
  {num:12,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["De","of"],["la","the"],["manera","manner"],["que","that"],["el","the"],["pastor","shepherd"],["libra","delivers"],["de","of"],["la","the"],["boca","mouth"],["del","of-the"],["león","lion"],["dos","two"],["patas","legs"],["o","or"],["la","the"],["punta","in"],["de","of"],["una","a"],["oreja,","ear,"],["así","thus"],["serán","they-shall-be"],["librados","delivered"],["los","the"],["hijos","children"],["de","of"],["Israel","Israel"],["que","that"],["en","in"],["Samaria","Samaria"],["se","themselves"],["sientan","they-sit"],["en","in"],["el","the"],["borde","border"],["de","of"],["la","the"],["cama,","bed,"],["y","and"],["en","in"],["Damasco,","Damascus,"],["en","in"],["un","a"],["diván.","couch."]]},
  {num:13,words:[["Oíd","you-hear"],["y","and"],["testificad","you-testify"],["contra","against"],["la","the"],["casa","house"],["de","of"],["Jacob,","Jacob,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["Dios","God"],["de","of"],["los","the"],["ejércitos:","armies:"]]},
  {num:14,words:[["El","the"],["día","day"],["en","in"],["que","that"],["castigue","shall"],["las","the"],["transgresiones","transgressions"],["de","of"],["Israel,","Israel,"],["castigaré","I-will-punish"],["también","also"],["los","the"],["altares","altars"],["de","of"],["Bet-el;","bethel;"],["y","and"],["serán","they-shall-be"],["cortados","cut"],["los","the"],["cuernos","horns"],["del","of-the"],["altar","altar"],["y","and"],["caerán","they-will-fall"],["a","to"],["tierra.","land."]]},
  {num:15,words:[["Y","and"],["heriré","I-strike"],["la","the"],["casa","house"],["de","of"],["invierno","winter"],["junto","together"],["con","with"],["la","the"],["casa","house"],["de","of"],["verano,","summer,"],["y","and"],["las","the"],["casas","houses"],["de","of"],["marfil","ivory"],["perecerán;","they-will-perish;"],["y","and"],["muchas","many"],["casas","houses"],["serán","they-shall-be"],["arruinadas,","says,"],["dice","says"],["Jehová.","jehovah."]]},
];
renderVerseSet(v3, 'amo-ch3-verses');

var v4 = [
  {num:1,words:[["Oíd","you-hear"],["esta","this"],["palabra,","word,"],["vacas","kine"],["de","of"],["Basán,","Bashan,"],["que","that"],["estáis","you-stand"],["en","in"],["el","the"],["monte","mount"],["de","of"],["Samaria,","Samaria,"],["que","that"],["oprimís","you-oppress"],["a","to"],["los","the"],["pobres,","poor,"],["que","that"],["quebrantáis","you-break"],["a","to"],["los","the"],["menesterosos,","needy,"],["que","that"],["decís","you-say"],["a","to"],["vuestros","your"],["señores:","shechem:"],["Traed,","you-bring,"],["y","and"],["beberemos.","we-will-drink."]]},
  {num:2,words:[["Jehová","jehovah"],["el","the"],["Señor","Lord"],["juró","swore"],["por","by"],["su","his"],["santidad:","holiness:"],["He aquí,","behold,"],["vienen","they-come"],["días","days"],["sobre","upon"],["vosotras","your"],["en","in"],["que","that"],["os","you"],["llevarán","bear"],["con","with"],["ganchos,","hooks,"],["y","and"],["a","to"],["vuestros","your"],["descendientes","descendants"],["con","with"],["anzuelos","posterity"],["de","of"],["pescador.","fishhooks."]]},
  {num:3,words:[["Y","and"],["saldréis","you-go"],["por","for"],["las","the"],["brechas","breaches"],["una","a"],["tras","after"],["otra","other"],["y","and"],["seréis","you-shall-be"],["echadas","casts"],["del","of-the"],["palacio,","palace,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:4,words:[["Id","you-go"],["a","to"],["Bet-el","bethel"],["y","and"],["pecad;","you-transgress;"],["en","in"],["Gilgal","Gilgal"],["multiplicad","you-multiply"],["la","the"],["rebelión;","rebellion;"],["y","and"],["traed","you-bring"],["de","of"],["mañana","morning"],["vuestros","your"],["sacrificios","sacrifices"],["y","and"],["vuestros","your"],["diezmos","tithes"],["cada","each"],["tres","three"],["días.","days."]]},
  {num:5,words:[["Y","and"],["ofreced","you-offer"],["ofrenda","offering"],["de","of"],["gratitud","gratitude"],["con","with"],["pan","bread"],["leudado","leavened"],["y","and"],["pregonad;","you-proclaim;"],["anunciad","you-publish"],["ofrendas","offerings"],["voluntarias,","freewill,"],["puesto que","since"],["así","thus"],["lo","it/him"],["queréis,","you-want,"],["hijos","children"],["de","of"],["Israel,","Israel,"],["dice","says"],["Jehová","jehovah"],["el","the"],["Señor.","Lord."]]},
  {num:6,words:[["Yo","I"],["también","also"],["os","you"],["hice","I-did"],["estar","be"],["a","to"],["diente","cleanness"],["limpio","I-clean"],["en","in"],["todas","all"],["vuestras","your"],["ciudades,","cities,"],["y","and"],["hubo","there-was"],["falta","want"],["de","of"],["pan","bread"],["en","in"],["todos","all"],["vuestros","your"],["pueblos;","peoples;"],["pero","but"],["no","not"],["os","you"],["volvisteis","you-returned"],["a","to"],["mí,","me,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:7,words:[["Y","and"],["también","also"],["os","you"],["retuve","withholden"],["la","the"],["lluvia","rain"],["tres","three"],["meses","months"],["antes","before"],["de","of"],["la","the"],["siega;","harvest;"],["e","and"],["hice","I-did"],["llover","to-rain"],["sobre","upon"],["una","a"],["ciudad","city"],["y","and"],["sobre","upon"],["otra","other"],["ciudad","city"],["no","not"],["hice","I-did"],["llover;","to-rain;"],["sobre","upon"],["una","a"],["parte","part"],["llovió,","city,"],["y","and"],["la","the"],["parte","part"],["sobre","upon"],["la","the"],["cual","which"],["no","not"],["llovió,","it,"],["se","himself"],["secó.","withered."]]},
  {num:8,words:[["Y","and"],["venían","they-came"],["dos","two"],["o","or"],["tres","three"],["ciudades","cities"],["a","to"],["una","a"],["ciudad","city"],["para","for"],["beber","to-drink"],["agua,","water,"],["y","and"],["no","not"],["se","themselves"],["saciaban;","satisfied;"],["con","with"],["todo,","all,"],["no","not"],["os","you"],["volvisteis","you-returned"],["a","to"],["mí,","me,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:9,words:[["Os", "you"], ["herí", "i"], ["con", "with"], ["tizoncillo", "with"], ["y", "and"], ["añublo;", "and;"], ["la", "the"], ["langosta", "locust"], ["devoró", "devoured"], ["vuestros", "your"], ["muchos", "many"], ["huertos,", "gardens,"], ["y", "and"], ["vuestras", "your"], ["viñas,", "vineyards,"], ["y", "and"], ["vuestros", "your"], ["higuerales", "fig-them"], ["y", "and"], ["vuestros", "your"], ["olivares,", "vineyards,"], ["pero", "but"], ["nunca", "never"], ["os", "you"], ["volvisteis", "returned"], ["a", "to"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:10,words:[["Envié","I-sent"],["entre","among"],["vosotros","you"],["pestilencia","pestilence"],["tal","such"],["como","as"],["en","in"],["Egipto;","Egypt;"],["maté","i"],["a","to"],["espada","sword"],["a","to"],["vuestros","your"],["jóvenes;","young-men;"],["vuestros","your"],["caballos","horses"],["fueron","they-were"],["capturados,","away,"],["e","and"],["hice","I-did"],["subir","go-up"],["el","the"],["hedor","the"],["de","of"],["vuestros","your"],["campamentos","camps"],["hasta","until"],["vuestras","your"],["narices;","noses;"],["pero","but"],["no","not"],["os","you"],["volvisteis","you-returned"],["a","to"],["mí,","me,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:11,words:[["Os", "you"], ["destruí,", "have,"], ["como", "as"], ["cuando", "when"], ["Dios", "God"], ["destruyó", "destroyed"], ["a", "to"], ["Sodoma", "gomorrah"], ["y", "and"], ["a", "to"], ["Gomorra,","Gomorrah,"], ["y", "and"], ["fuisteis","you"], ["como", "as"], ["tizón", "plucked"], ["sacado", "led"], ["del", "of-the"], ["fuego;", "fire;"], ["pero", "but"], ["no", "not"], ["os", "you"], ["volvisteis", "returned"], ["a", "to"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:12,words:[["Por tanto,","therefore,"],["de","of"],["esta","this"],["manera","manner"],["te","you"],["haré","I will make"],["a","to"],["ti,","you,"],["oh","oh"],["Israel;","Israel;"],["y","and"],["porque","because"],["te","you"],["he","I-have"],["de","of"],["hacer","do"],["esto,","this,"],["prepárate","for-you"],["para","for"],["venir","to-come"],["al","to-the"],["encuentro","met"],["de","of"],["tu","your"],["Dios,","God,"],["oh","oh"],["Israel.","Israel."]]},
  {num:13,words:[["Porque","because"],["he aquí,","behold,"],["el","the"],["que","that"],["forma","form"],["los","the"],["montes,","mountains,"],["y","and"],["crea","believes"],["el","the"],["viento","wind"],["y","and"],["anuncia","announces"],["al","to-the"],["hombre","man"],["su","his"],["pensamiento,","thought,"],["el","the"],["que","that"],["hace","makes"],["del","of-the"],["alba","morning"],["tinieblas","darkness"],["y","and"],["pasa","passes"],["sobre","upon"],["las","the"],["alturas","heights"],["de","of"],["la","the"],["tierra:","earth:"],["Jehová","jehovah"],["Dios","God"],["de","of"],["los","the"],["ejércitos","armies"],["es","is"],["su","his"],["nombre.","name."]]},
];
renderVerseSet(v4, 'amo-ch4-verses');

var v5 = [
  {num:1,words:[["Oíd","you-hear"],["esta","this"],["palabra","word"],["que","that"],["yo","I"],["levanto","arose"],["para","for"],["lamentación","lamentation"],["contra","against"],["vosotros,","you,"],["oh","oh"],["casa","house"],["de","of"],["Israel.","Israel."]]},
  {num:2,words:[["Cayó","fell"],["la","the"],["virginal","of"],["Israel;","Israel;"],["no","not"],["podrá","able"],["levantarse","lifts"],["ya","already"],["más;","more;"],["fue","was"],["dejada","left"],["sobre","upon"],["su","her"],["tierra,","land,"],["y","and"],["no","not"],["hay","there-is"],["quien","who"],["la","the"],["levante.","up."]]},
  {num:3,words:[["Porque","because"],["así","thus"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["el","the"],["Señor:","Lord:"],["La","the"],["ciudad","city"],["que","that"],["salga","comes"],["con","with"],["mil","thousand"],["volverá","will-return"],["con","with"],["cien,","hundred,"],["y","and"],["la","the"],["que","that"],["salga","comes"],["con","with"],["cien","hundred"],["volverá","will-return"],["con","with"],["diez,","ten,"],["en","in"],["la","the"],["casa","house"],["de","of"],["Israel.","Israel."]]},
  {num:4,words:[["Pero","but"],["así","thus"],["dice","says"],["Jehová","jehovah"],["a","to"],["la","the"],["casa","house"],["de","of"],["Israel:","Israel:"],["Buscadme","seek-me"],["y","and"],["viviréis;","you-will-live;"]]},
  {num:5,words:[["y","and"],["no","not"],["busquéis","you-may-seek"],["a","to"],["Bet-el,","bethel,"],["ni","nor"],["entréis","you-enter"],["en","in"],["Gilgal","Gilgal"],["ni","nor"],["paséis","pass"],["a","to"],["Beerseba,","beersheba,"],["porque","because"],["Gilgal","Gilgal"],["será","shall-be"],["ciertamente","surely"],["llevada","into"],["en","in"],["cautiverio,","captivity,"],["y","and"],["Bet-el","bethel"],["será","shall-be"],["deshecha.","nought."]]},
  {num:6,words:[["Buscad","you-seek"],["a","to"],["Jehová","jehovah"],["y","and"],["vivid,","you-live,"],["no","not"],["sea","be"],["que","that"],["acometa","break"],["como","as"],["fuego","fire"],["a","to"],["la","the"],["casa","house"],["de","of"],["José","Joseph"],["y","and"],["la","the"],["consuma,","consummates,"],["sin","without"],["haber","have"],["en","in"],["Bet-el","bethel"],["quien","who"],["lo","it"],["apague.","bethel."]]},
  {num:7,words:[["Los","the"],["que","that"],["convertís","you-turn"],["en","in"],["ajenjo","to"],["el","the"],["juicio","judgment"],["y","and"],["echáis","you-off"],["por","for"],["tierra","earth"],["la","the"],["justicia,","righteousness,"]]},
  {num:8,words:[["buscad","you-seek"],["al","to-the"],["que","that"],["hizo","made/did"],["las","the"],["Pléyades","stars"],["y","and"],["el","the"],["Orión,","Orion,"],["y","and"],["las","the"],["tinieblas","darkness"],["vuelve","return"],["en","in"],["mañana","morning"],["y","and"],["hace","makes"],["oscurecer","makes"],["el","the"],["día","day"],["como","as"],["noche;","night;"],["el","the"],["que","that"],["llama","calls"],["a","to"],["las","the"],["aguas","waters"],["del","of-the"],["mar","sea"],["y","and"],["las","the"],["derrama","spills"],["sobre","upon"],["la","the"],["faz","face"],["de","of"],["la","the"],["tierra:","earth:"],["Jehová","jehovah"],["es","is"],["su","his"],["nombre;","name;"]]},
  {num:9,words:[["Él","he"],["es","is"],["el","the"],["que","that"],["desencadena","against"],["destrucción","destruction"],["sobre","upon"],["el","the"],["fuerte","strong"],["y","and"],["hace","makes"],["que","that"],["la","the"],["destrucción","destruction"],["venga","let-come"],["contra","against"],["la","the"],["fortaleza.","castle."]]},
  {num:10,words:[["Ellos","they"],["aborrecen","hate"],["al","to-the"],["reprensor","that"],["en","in"],["la","the"],["puerta","gate"],["de","of"],["la","the"],["ciudad,","city,"],["y","and"],["al","to-the"],["que","that"],["habla","speaks"],["lo","him"],["recto","upright"],["abominan.","they-uprightly."]]},
  {num:11,words:[["Por tanto,","therefore,"],["puesto que","since"],["pisoteáis","you-is"],["al","to-the"],["pobre","poor"],["y","and"],["tomáis","you"],["de","of"],["él","he"],["carga","burden"],["de","of"],["trigo,","wheat,"],["aun","even"],["cuando","when"],["edificasteis","you-built"],["casas","houses"],["de","of"],["piedra","stone"],["labrada,","worked,"],["no","not"],["las","the"],["habitaréis;","dwell;"],["plantasteis","you"],["hermosas","and"],["viñas,","vineyards,"],["pero","but"],["no","not"],["beberéis","you-will-drink"],["el","the"],["vino","wine"],["de","of"],["ellas.","they."]]},
  {num:12,words:[["Porque","because"],["yo","I"],["sé","know"],["de","of"],["vuestras","your"],["muchas","many"],["rebeliones","rebellions"],["y","and"],["de","of"],["vuestros","your"],["grandes","great"],["pecados;","sins;"],["afligís","they"],["al","to-the"],["justo,","righteous,"],["y","and"],["recibís","you-receive"],["cohecho","turn"],["y","and"],["apartáis","you-move-aside"],["a","to"],["los","the"],["pobres","poor"],["en","in"],["la","the"],["puerta.","gate."]]},
  {num:13,words:[["Por tanto,","therefore,"], ["el", "the"], ["prudente", "prudent"], ["en", "in"], ["tal", "such"], ["tiempo", "time"], ["calla,", "time,"], ["porque", "because"], ["el", "the"], ["tiempo", "time"], ["es", "is"], ["malo.", "evil."]]},
  {num:14,words:[["Buscad","you-seek"],["lo","it/him"],["bueno","good"],["y","and"],["no","not"],["lo","it/him"],["malo,","evil,"],["para","for"],["que","that"],["viváis,","you-may-live,"],["porque","because"],["así","thus"],["Jehová","jehovah"],["Dios","God"],["de","of"],["los","the"],["ejércitos","armies"],["estará","shall-be"],["con","with"],["vosotros,","you,"],["como","as"],["decís.","you-say."]]},
  {num:15,words:[["Aborreced","you-hate"],["el","the"],["mal,","evil,"],["y","and"],["amad","you-love"],["el","the"],["bien","well"],["y","and"],["poned","you-set"],["juicio","judgment"],["en","in"],["la","the"],["puerta;","gate;"],["quizá","perhaps"],["Jehová","jehovah"],["Dios","God"],["de","of"],["los","the"],["ejércitos","armies"],["tendrá","will have"],["piedad","godliness"],["del","of-the"],["remanente","remnant"],["de","of"],["José.","Joseph."]]},
  {num:16,words:[["Por tanto,","therefore,"],["así","thus"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["Dios","God"],["de","of"],["los","the"],["ejércitos,","armies,"],["el","the"],["Señor:","Lord:"],["En","in"],["todas","all"],["las","the"],["plazas","strongholds"],["habrá","there-shall-be"],["llanto,","gnashing,"],["y","and"],["en","in"],["todas","all"],["las","the"],["calles","streets"],["dirán:","they-will-say:"],["¡Ay!","wo!"],["¡ay!;","wo!;"],["y","and"],["al","to-the"],["labrador","the"],["llamarán","they-call"],["a","to"],["duelo,","mourned,"],["y","and"],["a","to"],["llorar","weep"],["a","to"],["los","the"],["que","that"],["sepan","they-may-know"],["lamentarse.","regrets."]]},
  {num:17,words:[["Y", "and"], ["en", "in"], ["todas", "all"], ["las", "the"], ["viñas", "vineyards"], ["habrá", "there-shall-be"], ["llanto,", "gnashing,"], ["porque", "because"], ["pasaré", "pass"], ["por","for"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti,","you,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:18,words:[["¡Ay","wo"],["de","of"],["los","the"],["que","that"],["desean","they-desire"],["el","the"],["día","day"],["de","of"],["Jehová!","jehovah!"],["¿Para","for"],["qué","what"],["queréis","you-want"],["este","this"],["día","day"],["de","of"],["Jehová?","jehovah?"],["Será","shall-be"],["de","of"],["tinieblas","darkness"],["y","and"],["no","not"],["de","of"],["luz,","light,"]]},
  {num:19,words:[["como","as"],["el","the"],["que","that"],["huye","flees"],["de","of"],["delante","before"],["del","of-the"],["león","lion"],["y","and"],["se","himself"],["topa","encounters"],["con","with"],["el","the"],["oso;","bear;"],["o","or"],["como","as"],["el","the"],["que,","that,"],["al","to-the"],["entrar","enter"],["en","in"],["casa,","house,"],["apoya","supports"],["su","his"],["mano","hand"],["en","in"],["la","the"],["pared","wall"],["y","and"],["le","him"],["muerde","serpent"],["una","a"],["culebra.","snake."]]},
  {num:20,words:[["¿No", "not"], ["será", "shall-be"], ["el", "the"], ["día", "day"], ["de", "of"], ["Jehová", "jehovah"], ["tinieblas", "darkness"], ["y", "and"], ["no", "not"], ["luz;", "light;"], ["oscuridad,", "darkness,"], ["que", "that"], ["no", "not"], ["tiene", "has"], ["resplandor?", "luster?"]]},
  {num:21,words:[["Aborrezco,","I-hate,"],["desprecio","in"],["vuestras","your"],["fiestas,","moons,"],["y","and"],["no","not"],["me","me"],["darán","give"],["olor","savour"],["grato","savour"],["vuestras","your"],["asambleas.","assemblies."]]},
  {num:22,words:[["Y","and"],["si","if"],["me","me"],["ofrecéis","you-offer"],["holocaustos","sacrifices"],["y","and"],["vuestras","your"],["ofrendas","offerings"],["de","of"],["grano,","grain,"],["no","not"],["los","the"],["recibiré","receive"],["ni","nor"],["miraré","I-will-look"],["a","to"],["las","the"],["ofrendas","offerings"],["de","of"],["paz","peace"],["de","of"],["vuestros","your"],["animales","animals"],["engordados.","gained-weight."]]},
  {num:23,words:[["Quita","takes"],["de","of"],["mí","me"],["el","the"],["ruido","noise"],["de","of"],["tus","your"],["cantares,","sings,"],["pues","for"],["no","not"],["escucharé","I-shall-hearken"],["las","the"],["salmodias","the"],["de","of"],["tus","your"],["arpas.","harps."]]},
  {num:24,words:[["Antes", "before"], ["bien,", "well,"], ["corra", "judgment"], ["el", "the"], ["juicio", "judgment"], ["como", "as"], ["las", "the"], ["aguas", "waters"], ["y", "and"], ["la", "the"], ["justicia","righteousness"], ["como", "as"], ["impetuoso", "mighty"], ["arroyo.", "arnon."]]},
  {num:25,words:[["¿Me", "me"], ["ofrecisteis","you"], ["sacrificios", "sacrifices"], ["y", "and"], ["ofrendas", "offerings"], ["en", "in"], ["el", "the"], ["desierto", "wilderness"], ["en", "in"], ["cuarenta", "forty"], ["años,", "years,"], ["oh", "oh"], ["casa", "house"], ["de", "of"], ["Israel?", "Israel?"]]},
  {num:26,words:[["Antes","before"],["bien,","well,"],["llevabais","you-have"],["el","the"],["tabernáculo","tabernacle"],["de","of"],["vuestros","your"],["Moloc","molech"],["y","and"],["Quiún,","chiun,"],["ídolos","idols"],["vuestros,","your,"],["la","the"],["estrella","star"],["de","of"],["vuestros","your"],["dioses","gods"],["que","that"],["os","you"],["hicisteis.","you."]]},
  {num:27,words:[["Os", "you"], ["haré,","I will make,"], ["pues,", "for,"], ["entrar", "enter"], ["en", "in"], ["cautividad", "captivity"], ["más", "more"], ["allá","there"], ["de", "of"], ["Damasco,","Damascus,"], ["ha", "has"], ["dicho", "said"], ["Jehová,", "jehovah,"], ["cuyo", "whose"], ["nombre", "name"], ["es", "is"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos.", "armies."]]},
];
renderVerseSet(v5, 'amo-ch5-verses');

var v6 = [
  {num:1,words:[["¡Ay","wo"],["de","of"],["los","the"],["reposados","rested"],["en","in"],["Sion","Zion"],["y","and"],["de","of"],["los","the"],["confiados","trust"],["en","in"],["el","the"],["monte","mount"],["de","of"],["Samaria,","Samaria,"],["los","the"],["nombrados","appointed"],["como","as"],["principales","chief"],["entre","among"],["las","the"],["naciones,","nations,"],["a","to"],["quienes","who"],["acude","attends"],["la","the"],["casa","house"],["de","of"],["Israel!","Israel!"]]},
  {num:2,words:[["Pasad","pass"],["a","to"],["Calne","Calneh"],["y","and"],["mirad;","you-heed;"],["y","and"],["de","of"],["allí","there"],["id","you-go"],["a","to"],["la","the"],["gran","great"],["Hamat;","Hamath;"],["descended","you-great:"],["luego","then"],["a","to"],["Gat","Gath"],["de","of"],["los","the"],["filisteos.","philistines."],["¿Son","they-are"],["aquellos","those"],["reinos","kingdoms"],["mejores","better"],["que","that"],["estos","these"],["reinos?","kingdoms?"],["¿Es","is"],["mayor","greater"],["su","his"],["territorio","coast"],["que","that"],["vuestro","your"],["territorio?","coast?"]]},
  {num:3,words:[["Vosotros","you"],["que","that"],["alejáis","you-far"],["el","the"],["día","day"],["malo","evil"],["y","and"],["acercáis","you-cause"],["la","the"],["silla","seat"],["de","of"],["la","the"],["violencia;","violence;"]]},
  {num:4,words:[["los","the"],["que","that"],["duermen","they-sleep"],["en","in"],["camas","beds"],["de","of"],["marfil,","ivory,"],["y","and"],["se","themselves"],["estiran","they-stretch"],["sobre","upon"],["sus","their"],["lechos,","beds,"],["y","and"],["comen","they-eat"],["los","the"],["corderos","lambs"],["del","of-the"],["rebaño","flock"],["y","and"],["los","the"],["becerros","calves"],["sacados","take outed"],["de","of"],["en","in"],["medio","midst"],["del","of-the"],["establo;","stall;"]]},
  {num:5,words:[["gorjean","that"],["al","to-the"],["son","are"],["de","of"],["la","the"],["flauta","harp"],["e","and"],["inventan","they-invent"],["instrumentos","musick"],["musicales,","musical,"],["como","as"],["David;","David;"]]},
  {num:6,words:[["beben","they-drink"],["vino","wine"],["en","in"],["tazones","basons"],["y","and"],["se","themselves"],["ungen","anoint"],["con","with"],["los","the"],["ungüentos","the"],["más","more"],["finos;","fine;"],["y","and"],["no","not"],["se","themselves"],["afligen","grieved"],["por","for"],["el","the"],["quebranto","destruction"],["de","of"],["José;","Joseph;"]]},
  {num:7,words:[["por tanto,","therefore,"],["ahora","now"],["irán","go"],["cautivos","captives"],["a","to"],["la","the"],["cabeza","head"],["de","of"],["los","the"],["que","that"],["van","they-go"],["a","to"],["la","the"],["cautividad,","captivity,"],["y","and"],["se","himself"],["acabará","shall-finish"],["el","the"],["festín","them"],["de","of"],["los","the"],["que","that"],["se","themselves"],["entregan","betray"],["a","to"],["los","the"],["placeres.","pleasures."]]},
  {num:8,words:[["Jehová","jehovah"],["el","the"],["Señor","Lord"],["juró","swore"],["por","by"],["sí","yes"],["mismo,","same,"],["Jehová","jehovah"],["Dios","God"],["de","of"],["los","the"],["ejércitos","armies"],["ha","has"],["dicho:","said:"],["Abomino","I-abhor"],["la","the"],["soberbia","pride"],["de","of"],["Jacob","Jacob"],["y","and"],["aborrezco","I-hate"],["sus","his"],["palacios;","palaces;"],["entregaré","I-will-deliver"],["al","to-the"],["enemigo","enemy"],["la","the"],["ciudad","city"],["y","and"],["cuanto","as-much-as"],["hay","there-is"],["en","in"],["ella.","she."]]},
  {num:9,words:[["Y","and"],["acontecerá","shall-come-to-pass"],["que","that"],["si","if"],["diez","ten"],["hombres","men"],["quedan","they-are"],["en","in"],["una","a"],["casa,","house,"],["morirán.","they-will-die."]]},
  {num:10,words:[["Y","and"],["su","his"],["tío","uncle"],["levantará","raise"],["a","to"],["cada","each"],["uno,","one,"],["y","and"],["lo","him"],["quemará,","will-burn,"],["para","for"],["sacar","bring"],["los","the"],["huesos","bones"],["de","of"],["la","the"],["casa;","house;"],["y","and"],["dirá","will-say"],["al","to-the"],["que","that"],["esté","be"],["en","in"],["los","the"],["rincones","sides"],["de","of"],["la","the"],["casa:","house:"],["¿Hay","there-is"],["aún","yet"],["alguno","some"],["contigo?","with-you?"],["Y","and"],["el","the"],["otro","other"],["dirá:","shall-say:"],["No.","not."],["Y","and"],["dirá","will-say"],["aquel:","that:"],["Calla,","tongue,"],["porque","because"],["no","not"],["debemos","we-must"],["hacer","make"],["mención","mention"],["del","of-the"],["nombre","name"],["de","of"],["Jehová.","jehovah."]]},
  {num:11,words:[["Porque", "because"], ["he aquí,","behold,"], ["Jehová", "jehovah"], ["mandará", "command"], ["y", "and"], ["herirá","strike"], ["con", "with"], ["hendiduras", "of"], ["la", "the"], ["casa", "house"], ["mayor,", "greater,"], ["y", "and"], ["la", "the"], ["casa", "house"], ["menor", "lesser"], ["con", "with"], ["grietas.", "clefts."]]},
  {num:12,words:[["¿Correrán","they-will-run"],["los","the"],["caballos","horses"],["por","for"],["las","the"],["peñas?","rocks?"],["¿Ararán","they-will"],["en","in"],["ellas","they"],["con","with"],["bueyes?","oxen?"],["¿Por","for"],["qué","what"],["habéis","you-have"],["vosotros","you"],["convertido","converted"],["el","the"],["juicio","judgment"],["en","in"],["veneno","poison"],["y","and"],["el","the"],["fruto","fruit"],["de","of"],["justicia","righteousness"],["en","in"],["ajenjo?","hemlock?"]]},
  {num:13,words:[["Vosotros","you"],["que","that"],["os","you"],["alegráis","you-cheer-up"],["por","by"],["nada,","nothing,"],["que","that"],["decís:","you-say:"],["¿No","not"],["hemos","we-have"],["adquirido","gotten"],["poder","power"],["con","with"],["nuestra","our"],["propia","own"],["fuerza?","strength?"]]},
  {num:14,words:[["Pues","for"],["he aquí,","behold,"],["levantaré","I-raise"],["yo","I"],["sobre","upon"],["vosotros,","you,"],["oh","oh"],["casa","house"],["de","of"],["Israel,","Israel,"],["dice","says"],["Jehová","jehovah"],["Dios","God"],["de","of"],["los","the"],["ejércitos,","armies,"],["a","to"],["una","a"],["nación","nation"],["que","that"],["os","you"],["oprimirá","you"],["desde","from"],["la","the"],["entrada","entrance"],["de","of"],["Hamat","Hamath"],["hasta","until"],["el","the"],["arroyo","arnon"],["del","of-the"],["desierto.","wilderness."]]},
];
renderVerseSet(v6, 'amo-ch6-verses');

var v7 = [
  {num:1,words:[["Así","thus"],["me","me"],["ha","has"],["mostrado","shown"],["Jehová","jehovah"],["el","the"],["Señor:","Lord:"],["Y","and"],["he aquí,","behold,"],["él","he"],["formaba","grasshoppers"],["langostas","as"],["cuando","when"],["comenzaba","was-begining"],["a","to"],["crecer","grow"],["el","the"],["heno","up"],["tardío;","late;"],["y","and"],["he aquí,","behold,"],["el","the"],["heno","look,"],["tardío","was"],["venía","coming"],["después","after"],["de","of"],["las","the"],["siegas","harvests"],["del","of-the"],["rey.","king."]]},
  {num:2,words:[["Y","and"],["acaeció","it-came-to-pass"],["que","that"],["cuando","when"],["las","the"],["langostas","as"],["acabaron","they-pass"],["de","of"],["comer","to-eat"],["la","the"],["hierba","herb"],["de","of"],["la","the"],["tierra,","land,"],["yo","I"],["dije:","said:"],["Oh","oh"],["Señor,","Lord,"],["Jehová,","jehovah,"],["perdona,","forgive,"],["te","you"],["ruego;","beseech;"],["¿quién","who"],["levantará","raise"],["a","to"],["Jacob?,","Jacob?,"],["porque","because"],["es","is"],["pequeño.","small."]]},
  {num:3,words:[["Se","himself"],["arrepintió","repented"],["Jehová","jehovah"],["de","of"],["esto:","this:"],["No","not"],["será,","shall-be,"],["dijo","said"],["Jehová.","jehovah."]]},
  {num:4,words:[["Jehová","jehovah"],["el","the"],["Señor","Lord"],["me","me"],["mostró","showed"],["así:","thus:"],["Y","and"],["he aquí,","behold,"],["Jehová","jehovah"],["el","the"],["Señor","Lord"],["llamaba","was-called"],["para","for"],["juzgar","to-judge"],["con","with"],["fuego;","fire;"],["y","and"],["consumió","devoured"],["el","the"],["gran","great"],["abismo","deep"],["y","and"],["consumió","devoured"],["una","a"],["parte","part"],["de","of"],["la","the"],["tierra.","land."]]},
  {num:5,words:[["Y", "and"], ["dije:", "I-said:"], ["Señor,", "Lord,"], ["Jehová,", "jehovah,"], ["cesa,", "did,"], ["te","you"], ["ruego;","beseech;"], ["¿quién", "who"], ["levantará", "raise"], ["a", "to"], ["Jacob?,", "Jacob?,"], ["porque", "because"], ["es", "is"], ["pequeño.", "small."]]},
  {num:6,words:[["Se","himself"],["arrepintió","repented"],["Jehová","jehovah"],["de","of"],["esto:","this:"],["No","not"],["será","shall-be"],["esto","this"],["tampoco,","neither,"],["dijo","said"],["Jehová","jehovah"],["el","the"],["Señor.","Lord."]]},
  {num:7,words:[["Me", "me"], ["enseñó", "taught"], ["así:", "thus:"], ["Y", "and"], ["he aquí,","behold,"], ["el", "the"], ["Señor", "Lord"], ["estaba", "was"], ["sobre", "upon"], ["un", "a"], ["muro", "wall"], ["hecho","made"], ["a", "to"], ["plomo,", "lead,"], ["y", "and"], ["en", "in"], ["su","his"], ["mano", "hand"], ["tenía", "had"], ["una", "a"], ["plomada", "in"], ["de", "of"], ["albañil.", "hand."]]},
  {num:8,words:[["Jehová","jehovah"],["entonces","then"],["me","me"],["dijo:","said:"],["¿Qué","what"],["ves,","you-see,"],["Amós?","Amos?"],["Y","and"],["dije:","I-said:"],["Una","a"],["plomada","said,"],["de","of"],["albañil.","plumbline."],["Y","and"],["el","the"],["Señor","Lord"],["dijo:","said:"],["He aquí,","behold,"],["yo","I"],["pongo","lay"],["plomada","in"],["de","of"],["albañil","midst"],["en","in"],["medio","midst"],["de","of"],["mi","my"],["pueblo","people"],["Israel;","Israel;"],["ya","already"],["no","not"],["lo","it/him"],["toleraré","I-will-tolerate"],["más.","more."]]},
  {num:9,words:[["Y","and"],["los","the"],["lugares","places"],["altos","high"],["de","of"],["Isaac","Isaac"],["serán","they-shall-be"],["destruidos,","destroyed,"],["y","and"],["los","the"],["santuarios","sanctuaries"],["de","of"],["Israel","Israel"],["serán","they-shall-be"],["asolados;","devastated;"],["y","and"],["me","me"],["levantaré","raise"],["con","with"],["espada","sword"],["contra","against"],["la","the"],["casa","house"],["de","of"],["Jeroboam.","Jeroboam."]]},
  {num:10,words:[["Entonces","then"],["el","the"],["sacerdote","priest"],["Amasías","Amaziah"],["de","of"],["Bet-el","bethel"],["envió","sent"],["a","to"],["decir","say"],["a","to"],["Jeroboam,","Jeroboam,"],["rey","king"],["de","of"],["Israel:","Israel:"],["Amós","Amos"],["ha","has"],["conspirado","you"],["contra","against"],["ti","you"],["en","in"],["medio","midst"],["de","of"],["la","the"],["casa","house"],["de","of"],["Israel;","Israel;"],["la","the"],["tierra","land"],["no","not"],["puede","can"],["soportar","bear"],["todas","all"],["sus","his"],["palabras.","words."]]},
  {num:11,words:[["Porque","because"],["así","thus"],["ha","has"],["dicho","said"],["Amós:","Amos:"],["Jeroboam","Jeroboam"],["morirá","will-die"],["a","to"],["espada,","sword,"],["e","and"],["Israel","Israel"],["ciertamente","surely"],["será","shall-be"],["llevado","carried"],["de","of"],["su","their"],["tierra","land"],["en","in"],["cautiverio.","captivity."]]},
  {num:12,words:[["Y","and"],["Amasías","Amaziah"],["dijo","said"],["a","to"],["Amós:","Amos:"],["Vidente,","seer,"],["vete;","get;"],["huye","flees"],["a","to"],["tierra","land"],["de","of"],["Judá,","Judah,"],["y","and"],["come","eats"],["allá","there"],["tu","your"],["pan","bread"],["y","and"],["profetiza","prophesies"],["allá;","there;"]]},
  {num:13,words:[["y", "and"], ["no", "not"], ["profetices", "again"], ["más", "more"], ["en", "in"], ["Bet-el,", "bethel,"], ["porque", "because"], ["es", "is"], ["santuario", "sanctuary"], ["del", "of-the"], ["rey", "king"], ["y", "and"], ["casa", "house"], ["del", "of-the"], ["reino.", "kingdom."]]},
  {num:14,words:[["Entonces","then"],["respondió","answered"],["Amós,","Amos,"],["y","and"],["dijo","said"],["a","to"],["Amasías:","Amaziah:"],["No","not"],["soy","I-am"],["profeta","prophet"],["ni","nor"],["soy","I-am"],["hijo","son"],["de","of"],["profeta,","prophet,"],["sino","but"],["que","that"],["soy","I-am"],["boyero","and"],["y","and"],["recojo","I-gatherer"],["higos","figs"],["silvestres;","wild;"]]},
  {num:15,words:[["y","and"],["Jehová","jehovah"],["me","me"],["tomó","took"],["de","of"],["detrás","behind"],["del","of-the"],["ganado,","cattle,"],["y","and"],["me","me"],["dijo","said"],["Jehová:","jehovah:"],["Ve","you-sees"],["y","and"],["profetiza","prophesies"],["a","to"],["mi","my"],["pueblo","people"],["Israel.","Israel."]]},
  {num:16,words:[["Ahora,","now,"],["pues,","for,"],["oye","hears"],["la","the"],["palabra","word"],["de","of"],["Jehová.","jehovah."],["Tú","you"],["dices:","say:"],["No","not"],["profetices","against"],["contra","against"],["Israel","Israel"],["ni","nor"],["hables","you-may-speak"],["contra","against"],["la","the"],["casa","house"],["de","of"],["Isaac.","Isaac."]]},
  {num:17,words:[["Por tanto,","therefore,"],["así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Tu","your"],["esposa","wife"],["se","himself"],["prostituirá","harlot"],["en","in"],["la","the"],["ciudad,","city,"],["y","and"],["tus","your"],["hijos","children"],["y","and"],["tus","your"],["hijas","daughters"],["caerán","they-will-fall"],["a","to"],["espada,","sword,"],["y","and"],["tu","your"],["tierra","land"],["será","shall-be"],["repartida","divided"],["a","to"],["cordel;","line;"],["y","and"],["tú","you"],["morirás","will-die"],["en","in"],["tierra","land"],["inmunda,","unclean,"],["e","and"],["Israel","Israel"],["ciertamente","surely"],["será","shall-be"],["llevado","carried"],["cautivo","captive"],["lejos","far"],["de","of"],["su","his"],["tierra.","land."]]},
];
renderVerseSet(v7, 'amo-ch7-verses');

var v8 = [
  {num:1,words:[["Así","thus"],["me","me"],["ha","has"],["mostrado","shown"],["Jehová","jehovah"],["el","the"],["Señor:","Lord:"],["Y","and"],["he aquí,","behold,"],["un","a"],["canastillo","basket"],["de","of"],["fruta","fruit"],["de","of"],["verano.","summer."]]},
  {num:2,words:[["Y","and"],["dijo:","said:"],["¿Qué","what"],["ves,","you-see,"],["Amós?","Amos?"],["Y","and"],["dije:","I-said:"],["Un","a"],["canastillo","basket"],["de","of"],["fruta","fruit"],["de","of"],["verano.","summer."],["Y","and"],["me","me"],["dijo","said"],["Jehová:","jehovah:"],["Ha","has"],["venido","come"],["el","the"],["fin","end"],["sobre","upon"],["mi","my"],["pueblo","people"],["Israel;","Israel;"],["ya","already"],["no","not"],["lo","it/him"],["toleraré","I-will-tolerate"],["más.","more."]]},
  {num:3,words:[["Y","and"],["los","the"],["cantores","singers"],["del","of-the"],["templo","temple"],["aullarán","they-shall"],["en","in"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová","jehovah"],["el","the"],["Señor;","Lord;"],["muchos","many"],["serán","shall-be"],["los","the"],["cuerpos","carcases"],["muertos;","dead;"],["en","in"],["cualquier","any"],["lugar","place"],["serán","they-shall-be"],["echados","driven"],["en","in"],["silencio.","silence."]]},
  {num:4,words:[["Oíd","you-hear"],["esto,","this,"],["los","the"],["que","that"],["pisoteáis","you-swallow"],["a","to"],["los","the"],["menesterosos","needy"],["y","and"],["arruináis","you-make"],["a","to"],["los","the"],["pobres","poor"],["de","of"],["la","the"],["tierra,","land,"]]},
  {num:5,words:[["diciendo:","saying:"],["¿Cuándo","when"],["pasará","will-pass"],["la","the"],["luna","moon"],["nueva,","new,"],["para","for"],["que","that"],["vendamos","we-bandage"],["el","the"],["trigo,","wheat,"],["y","and"],["el","the"],["día","day"],["de","of"],["reposo,","rest,"],["para","for"],["que","that"],["abramos","we-may"],["los","the"],["alfolíes","set"],["del","of-the"],["trigo,","wheat,"],["y","and"],["achiquemos","we-may-shrink"],["la","the"],["medida,","measure,"],["y","and"],["subamos","we-may-go-up"],["el","the"],["precio","price"],["y","and"],["falseemos","falsifying"],["con","with"],["engaño","guile"],["la","the"],["balanza;","balance;"]]},
  {num:6,words:[["para","for"],["que","that"],["compremos","we-may"],["a","to"],["los","the"],["pobres","poor"],["por","for"],["dinero","sacks"],["y","and"],["a","to"],["los","the"],["necesitados","needy"],["por","for"],["un","a"],["par","of"],["de","of"],["sandalias,","and,"],["y","and"],["vendamos","we-bandage"],["los","the"],["desechos","of"],["del","of-the"],["trigo?","wheat?"]]},
  {num:7,words:[["Jehová", "jehovah"], ["ha", "has"], ["jurado", "sworn"], ["por","by"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["Jacob:", "Jacob:"], ["No", "not"], ["me", "me"], ["olvidaré", "forget"], ["jamás", "never"], ["de", "of"], ["ninguna", "none"], ["de", "of"], ["sus","their"], ["obras.", "works."]]},
  {num:8,words:[["¿No","not"],["se","himself"],["estremecerá","will-shiver"],["la","the"],["tierra","land"],["por","for"],["esto?","this?"],["¿Y","and"],["no","not"],["llorará","shall-weep"],["todo","all"],["habitante","dwell-you"],["de","of"],["ella?","she?"],["Y","and"],["subirá","up"],["toda","all"],["ella","she"],["como","as"],["un","a"],["río,","river,"],["y","and"],["se","himself"],["desbordará","cast"],["y","and"],["menguará","drowned,"],["como","as"],["el","the"],["río","river"],["de","of"],["Egipto.","Egypt."]]},
  {num:9,words:[["Y","and"],["acaecerá","it"],["en","in"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová","jehovah"],["el","the"],["Señor,","Lord,"],["que","that"],["haré","I will make"],["que","that"],["se","himself"],["ponga","set"],["el","the"],["sol","sun"],["a","to"],["mediodía","noonday"],["y","and"],["cubriré","I-will-cover"],["la","the"],["tierra","earth"],["de","of"],["tinieblas","darkness"],["en","in"],["pleno","in"],["día.","day."]]},
  {num:10,words:[["Y","and"],["cambiaré","i"],["vuestras","your"],["fiestas","moons"],["en","in"],["duelo","mourned"],["y","and"],["todos","all"],["vuestros","your"],["cantares","sings"],["en","in"],["lamentaciones;","of;"],["y","and"],["haré","I will make"],["poner","put/place"],["cilicio","sackcloth"],["sobre","upon"],["todo","all"],["lomo,","loin,"],["y","and"],["que","that"],["se","himself"],["rape","may-shave"],["toda","all"],["cabeza;","head;"],["y","and"],["la","the"],["volveré","return"],["como","as"],["en","in"],["llanto","gnashing"],["por","for"],["el","the"],["hijo","son"],["único,","only,"],["y","and"],["su","your"],["final","end"],["será","shall-be"],["como","as"],["día","day"],["amargo.","bitter."]]},
  {num:11,words:[["He aquí,","behold,"],["vienen","they-come"],["días,","days,"],["dice","says"],["Jehová","jehovah"],["el","the"],["Señor,","Lord,"],["en","in"],["los","the"],["cuales","which"],["enviaré","I-will-send"],["hambre","famine"],["a","to"],["la","the"],["tierra,","land,"],["no","not"],["hambre","famine"],["de","of"],["pan","bread"],["ni","nor"],["sed","thirst"],["de","of"],["agua,","water,"],["sino","but"],["de","of"],["oír","hear"],["la","the"],["palabra","word"],["de","of"],["Jehová.","jehovah."]]},
  {num:12,words:[["E","and"],["irán","go"],["errantes","wilderness"],["de","of"],["mar","sea"],["a","to"],["mar;","sea;"],["desde","from"],["el","the"],["norte","north"],["hasta","until"],["el","the"],["oriente","east"],["andarán","they-will-walk"],["buscando","seeking"],["la","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["y","and"],["no","not"],["la","the"],["hallarán.","find."]]},
  {num:13,words:[["En","in"],["aquel","that"],["día","day"],["las","the"],["doncellas","maidens"],["hermosas","and"],["y","and"],["los","the"],["jóvenes","young-men"],["desmayarán","they-will-faint"],["de","of"],["sed.","thirst."]]},
  {num:14,words:[["Los","the"],["que","that"],["juran","they-swear"],["por","by"],["el","the"],["pecado","sin"],["de","of"],["Samaria","Samaria"],["y","and"],["dicen:","they-say:"],["¡Viva","quick"],["tu","your"],["dios,","God,"],["oh","oh"],["Dan!","they-Dan!"],["y:","and:"],["¡Viva","quick"],["el","the"],["camino","way"],["de","of"],["Beerseba!","beersheba!"],["caerán","they-will-fall"],["y","and"],["nunca","never"],["más","more"],["se","themselves"],["levantarán.","rise."]]},
];
renderVerseSet(v8, 'amo-ch8-verses');

var v9 = [
  {num:1,words:[["Vi","I-saw"],["al","to-the"],["Señor","Lord"],["que","that"],["estaba","was"],["sobre","upon"],["el","the"],["altar,","altar,"],["y","and"],["dijo:","said:"],["Golpea","struck"],["los","the"],["capiteles,","chapiters,"],["y","and"],["estremézcanse","may"],["los","the"],["umbrales,","thresholds,"],["y","and"],["hazlos","do-them"],["pedazos","pieces"],["sobre","upon"],["la","the"],["cabeza","head"],["de","of"],["todos;","all;"],["y","and"],["al","to-the"],["resto","remnant"],["de","of"],["ellos","they"],["mataré","will"],["a","to"],["espada;","sword;"],["no","not"],["habrá","there-shall-be"],["de","of"],["ellos","they"],["quien","who"],["huya","may-flee"],["ni","nor"],["quien","who"],["escape.","escape."]]},
  {num:2,words:[["Aunque", "although"], ["caven", "they"], ["hasta", "until"], ["el", "the"], ["Seol,", "grave,"], ["de", "of"], ["allá","there"], ["los", "the"], ["tomará", "take"], ["mi", "my"], ["mano;", "hand;"], ["y", "and"], ["aunque", "although"], ["suban", "up"], ["hasta", "until"], ["el", "the"], ["cielo,", "heaven,"], ["de", "of"], ["allá","there"], ["los", "the"], ["haré","I will make"], ["descender.", "descend."]]},
  {num:3,words:[["Y","and"],["aunque","although"],["se","themselves"],["escondan","hide"],["en","in"],["la","the"],["cumbre","top"],["del","of-the"],["Carmelo,","Carmel,"],["allí","there"],["los","the"],["buscaré","will"],["y","and"],["los","the"],["tomaré;","take;"],["y","and"],["aunque","although"],["se","themselves"],["escondan","be"],["de","of"],["delante","before"],["de","of"],["mis","my"],["ojos","eyes"],["en","in"],["lo","it/him"],["profundo","deep"],["del","of-the"],["mar,","sea,"],["allí","there"],["mandaré","I-command"],["a","to"],["la","the"],["serpiente,","serpent,"],["y","and"],["los","the"],["morderá.","will-bite."]]},
  {num:4,words:[["Y","and"],["si","if"],["van","they-go"],["al","to-the"],["cautiverio","captivity"],["delante","before"],["de","of"],["sus","their"],["enemigos,","enemies,"],["allí","there"],["mandaré","I-command"],["la","the"],["espada,","sword,"],["y","and"],["los","the"],["matará;","slay;"],["y","and"],["pondré","I-shall-put"],["sobre","upon"],["ellos","they"],["mis","my"],["ojos","eyes"],["para","for"],["mal","evil"],["y","and"],["no","not"],["para","for"],["bien.","well."]]},
  {num:5,words:[["El","the"],["Señor","Lord"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos","armies"],["es","is"],["el","the"],["que","that"],["toca","touches"],["la","the"],["tierra,","land,"],["y","and"],["esta","this"],["se","himself"],["derretirá,","will-melt,"],["y","and"],["llorarán","they-shall"],["todos","all"],["los","the"],["que","that"],["en","in"],["ella","she"],["moran;","they-dwell;"],["y","and"],["subirá","up"],["toda","all"],["ella","she"],["como","as"],["un","a"],["río","river"],["y","and"],["menguará","be"],["luego","then"],["como","as"],["el","the"],["río","river"],["de","of"],["Egipto.","Egypt."]]},
  {num:6,words:[["Él","he"],["edificó","built"],["en","in"],["el","the"],["cielo","heaven"],["sus","his"],["moradas","shall"],["y","and"],["ha","has"],["establecido","established"],["su","his"],["expansión","expanse"],["sobre","upon"],["la","the"],["tierra;","earth;"],["él","he"],["llama","calls"],["a","to"],["las","the"],["aguas","waters"],["del","of-the"],["mar","sea"],["y","and"],["sobre","upon"],["la","the"],["faz","face"],["de","of"],["la","the"],["tierra","earth"],["las","the"],["derrama;","spills;"],["Jehová","jehovah"],["es","is"],["su","his"],["nombre.","name."]]},
  {num:7,words:[["Hijos", "children"], ["de", "of"], ["Israel,", "Israel,"], ["¿no", "not"], ["me", "me"], ["sois","you-are"], ["vosotros", "you"], ["como", "as"], ["hijos", "children"], ["de", "of"], ["etíopes?,", "children?,"], ["dice", "says"], ["Jehová.", "jehovah."], ["¿No", "not"], ["hice", "I-did"], ["yo", "I"], ["subir", "go-up"], ["a", "to"], ["Israel", "Israel"], ["de", "of"], ["la", "the"], ["tierra","land"], ["de", "of"], ["Egipto,", "Egypt,"], ["y", "and"], ["a", "to"], ["los", "the"], ["filisteos", "philistines"], ["de", "of"], ["Caftor,", "philistines,"], ["y", "and"], ["de", "of"], ["Kir","Kir"], ["a", "to"], ["los", "the"], ["arameos?", "kir?"]]},
  {num:8,words:[["He aquí,","behold,"],["los","the"],["ojos","eyes"],["de","of"],["Jehová","jehovah"],["el","the"],["Señor","Lord"],["están","they-are"],["sobre","upon"],["el","the"],["reino","kingdom"],["pecador,","sinner,"],["y","and"],["yo","I"],["lo","it"],["destruiré","I-will-destroy"],["de","of"],["la","the"],["faz","face"],["de","of"],["la","the"],["tierra;","earth;"],["mas","but"],["no","not"],["destruiré","I-will-destroy"],["del","of-the"],["todo","all"],["la","the"],["casa","house"],["de","of"],["Jacob,","Jacob,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:9,words:[["Porque","because"],["he aquí,","behold,"],["yo","I"],["mandaré","command"],["y","and"],["haré","I will make"],["que","that"],["la","the"],["casa","house"],["de","of"],["Israel","Israel"],["sea","be"],["zarandeada","shake"],["entre","among"],["todas","all"],["las","the"],["naciones,","nations,"],["como","as"],["se","himself"],["zarandea","is"],["el","the"],["grano","grain"],["en","in"],["una","a"],["criba,","yet,"],["sin","without"],["que","that"],["caiga","may-fall"],["ni","nor"],["un","a"],["granito","little-great"],["en","in"],["la","the"],["tierra.","earth."]]},
  {num:10,words:[["A","to"],["espada","sword"],["morirán","they-will-die"],["todos","all"],["los","the"],["pecadores","sinners"],["de","of"],["mi","my"],["pueblo,","people,"],["los","the"],["que","that"],["dicen:","they-say:"],["No","not"],["se","himself"],["acercará","come"],["ni","nor"],["nos","us"],["alcanzará","shall"],["el","the"],["mal.","evil."]]},
  {num:11,words:[["En","in"],["aquel","that"],["día","day"],["yo","I"],["levantaré","raise"],["el","the"],["tabernáculo","tabernacle"],["caído","fallen"],["de","of"],["David,","David,"],["y","and"],["cerraré","I-will-close"],["sus","his"],["brechas,","breaches,"],["y","and"],["levantaré","I-raise"],["sus","his"],["ruinas","waste"],["y","and"],["lo","it"],["reedificaré","will"],["como","as"],["en","in"],["el","the"],["tiempo","time"],["pasado,","past,"]]},
  {num:12,words:[["para","for"],["que","that"],["posean","they-may-possess"],["el","the"],["remanente","remnant"],["de","of"],["Edom","Edom"],["y","and"],["de","of"],["todas","all"],["las","the"],["naciones","nations"],["que","that"],["son","they-are"],["llamadas","phone call"],["por","by"],["mi","my"],["nombre,","name,"],["dice","says"],["Jehová,","jehovah,"],["que","that"],["hace","makes"],["esto.","this."]]},
  {num:13,words:[["He aquí,","behold,"],["vienen","they-come"],["días,","days,"],["dice","says"],["Jehová,","jehovah,"],["en","in"],["que","that"],["el","the"],["que","that"],["ara","of"],["alcanzará","shall"],["al","to-the"],["segador,","reaper,"],["y","and"],["el","the"],["pisador","treader"],["de","of"],["las","the"],["uvas","grapes"],["al","to-the"],["que","that"],["lleve","you"],["la","the"],["simiente;","seed;"],["y","and"],["los","the"],["montes","mountains"],["destilarán","they-drop"],["vino","wine"],["dulce,","sweet,"],["y","and"],["todos","all"],["los","the"],["collados","hills"],["se","themselves"],["derretirán.","melt."]]},
  {num:14,words:[["Y","and"],["traeré","I-will-bring"],["del","of-the"],["cautiverio","captivity"],["a","to"],["mi","my"],["pueblo","people"],["Israel,","Israel,"],["y","and"],["reedificarán","israel,"],["ellos","they"],["las","the"],["ciudades","cities"],["asoladas","desolate"],["y","and"],["las","the"],["habitarán;","dwell;"],["y","and"],["plantarán","they-shall"],["viñas","vineyards"],["y","and"],["beberán","they-will-drink"],["el","the"],["vino","wine"],["de","of"],["ellas,","they,"],["y","and"],["harán","they-shall-make"],["huertos","gardens"],["y","and"],["comerán","they-will-eat"],["el","the"],["fruto","fruit"],["de","of"],["ellos.","they."]]},
  {num:15,words:[["Pues","for"],["los","the"],["plantaré","plant"],["sobre","upon"],["su","their"],["tierra,","land,"],["y","and"],["nunca","never"],["más","more"],["serán","they-shall-be"],["arrancados","be"],["de","of"],["la","the"],["tierra","land"],["que","that"],["yo","I"],["les","them"],["di,","I-give/I-gave,"],["ha","has"],["dicho","said"],["Jehová,","jehovah,"],["Dios","God"],["tuyo.","yours."]]},
];
renderVerseSet(v9, 'amo-ch9-verses');

})();
