(function() {
var v1 = [
  {num:1,words:[["Nosotros", "we"], ["creemos", "believe"], ["en", "in"], ["Dios", "God"], ["el", "the"], ["Eterno", "eternal"], ["Padre,", "father,"], ["y", "and"], ["en", "in"], ["su", "his/her"], ["Hijo", "son"], ["Jesucristo,", "Jesus-Christ,"], ["y", "and"], ["en", "in"], ["el", "the"], ["Espíritu", "Spirit"], ["Santo.", "holy."]]},
  {num:2,words:[["Creemos", "believe"], ["que", "that"], ["los", "the"], ["hombres", "men"], ["serán", "shall-be"], ["castigados", "punished"], ["por", "by/for"], ["sus", "his/her"], ["propios", "own"], ["pecados,", "sins,"], ["y", "and"], ["no", "not"], ["por", "by/for"], ["la", "the"], ["transgresión", "transgression"], ["de", "of"], ["Adán.", "adam."]]},
  {num:3,words:[["Creemos", "believe"], ["que", "that"], ["por", "by/for"], ["la", "the"], ["expiación", "atonement"], ["de", "of"], ["Cristo,", "Christ,"], ["todo", "all"], ["el", "the"], ["género", "mankind"], ["humano", "mankind"], ["puede", "can"], ["salvarse,", "saved,"], ["mediante", "through"], ["la", "the"], ["obediencia", "obedience"], ["a", "to"], ["las", "the"], ["leyes", "laws"], ["y", "and"], ["ordenanzas", "ordinances"], ["del", "of-the"], ["Evangelio.", "gospel."]]},
  {num:4,words:[["Creemos", "believe"], ["que", "that"], ["los", "the"], ["primeros", "parents"], ["principios", "principles"], ["y", "and"], ["ordenanzas", "ordinances"], ["del", "of-the"], ["Evangelio", "gospel"], ["son:", "are:"], ["primero,", "first,"], ["Fe", "faith"], ["en", "in"], ["el", "the"], ["Señor", "Lord"], ["Jesucristo;", "Jesus-Christ;"], ["segundo,", "second,"], ["Arrepentimiento;", "repentance;"], ["tercero,", "third,"], ["Bautismo", "baptism"], ["por", "by/for"], ["inmersión", "baptism"], ["para", "for"], ["la", "the"], ["remisión", "remission"], ["de", "of"], ["los", "the"], ["pecados;", "sins;"], ["cuarto,", "fourth,"], ["Imposición", "laying"], ["de", "of"], ["manos", "hands"], ["para", "for"], ["comunicar", "for"], ["el", "the"], ["don", "gift"], ["del", "of-the"], ["Espíritu", "Spirit"], ["Santo.", "holy."]]},
  {num:5,words:[["Creemos", "believe"], ["que", "that"], ["el", "the"], ["hombre", "man"], ["debe", "must"], ["ser", "be"], ["llamado", "called"], ["por", "by/for"], ["Dios,", "God,"], ["por", "by/for"], ["profecía", "prophecy"], ["y", "and"], ["la", "the"], ["imposición", "laying"], ["de", "of"], ["manos,", "hands,"], ["por", "by/for"], ["aquellos", "those"], ["que", "that"], ["tienen", "have"], ["la", "the"], ["autoridad,", "authority,"], ["a", "to"], ["fin", "end"], ["de", "of"], ["que", "that"], ["pueda", "whereby"], ["predicar", "preach"], ["el", "the"], ["evangelio", "gospel"], ["y", "and"], ["administrar", "administer"], ["sus", "his/her"], ["ordenanzas.", "ordinances."]]},
  {num:6,words:[["Creemos", "believe"], ["en", "in"], ["la", "the"], ["misma", "same"], ["organización", "organization"], ["que", "that"], ["existió", "in"], ["en", "in"], ["la", "the"], ["Iglesia", "church"], ["Primitiva,", "apostles,"], ["esto", "this"], ["es,", "is,"], ["apóstoles,", "apostles,"], ["profetas,", "prophets,"], ["pastores,", "pastors,"], ["maestros,", "teachers,"], ["evangelistas,", "and,"], ["etc.", "forth."]]},
  {num:7,words:[["Creemos", "believe"], ["en", "in"], ["el", "the"], ["don", "gift"], ["de", "of"], ["lenguas,", "tongues,"], ["profecía,", "prophecy,"], ["revelación,", "revelation,"], ["visiones,", "visions,"], ["sanidades,", "the,"], ["interpretación", "interpretation"], ["de", "of"], ["lenguas,", "tongues,"], ["etc.", "so."]]},
  {num:8,words:[["Creemos", "believe"], ["que", "that"], ["la", "the"], ["Biblia", "bible"], ["es", "is"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Dios", "God"], ["hasta", "until"], ["donde", "where"], ["esté", "be"], ["traducida", "the"], ["correctamente;", "toly;"], ["también", "also"], ["creemos", "believe"], ["que", "that"], ["el", "the"], ["Libro", "book"], ["de", "of"], ["Mormón", "mormon"], ["es", "is"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Dios.", "God."]]},
  {num:9,words:[["Creemos", "believe"], ["todo", "all"], ["lo", "it/him"], ["que", "that"], ["Dios", "God"], ["ha", "has"], ["revelado,", "revealed,"], ["todo", "all"], ["lo", "it/him"], ["que", "that"], ["actualmente", "now"], ["revela,", "of,"], ["y", "and"], ["creemos", "believe"], ["que", "that"], ["aún", "still/yet"], ["revelará", "yet"], ["muchos", "many"], ["grandes", "great"], ["e", "and"], ["importantes", "and"], ["asuntos", "affairs"], ["pertenecientes", "pertaining"], ["al", "to-the"], ["reino", "kingdom"], ["de", "of"], ["Dios.", "God."]]},
  {num:10,words:[["Creemos", "believe"], ["en", "in"], ["la", "the"], ["congregación", "congregation"], ["literal", "literal"], ["del", "of-the"], ["pueblo", "people"], ["de", "of"], ["Israel", "Israel"], ["y", "and"], ["en", "in"], ["la", "the"], ["restauración", "restoration"], ["de", "of"], ["las", "the"], ["Diez", "ten"], ["Tribus;", "tribes;"], ["que", "that"], ["Sion", "zion"], ["(la", "the"], ["Nueva", "new"], ["Jerusalén)", "jerusalem)"], ["será", "shall-be"], ["edificada", "built"], ["sobre", "upon"], ["el", "the"], ["continente", "continent;"], ["americano;", "that;"], ["que", "that"], ["Cristo", "Christ"], ["reinará", "reign"], ["personalmente", "upon"], ["sobre", "upon"], ["la", "the"], ["tierra,", "land/earth,"], ["y", "and"], ["que", "that"], ["la", "the"], ["tierra", "land/earth"], ["será", "shall-be"], ["renovada", "renewed"], ["y", "and"], ["recibirá", "receive"], ["su", "his/her"], ["gloria", "glory"], ["paradisíaca.", "."]]},
  {num:11,words:[["Reclamamos", "we"], ["el", "the"], ["derecho", "right"], ["de", "of"], ["adorar", "worship"], ["a", "to"], ["Dios", "God"], ["Todopoderoso", "almighty"], ["conforme", "according-to"], ["a", "to"], ["los", "the"], ["dictados", "dictates"], ["de", "of"], ["nuestra", "our"], ["propia", "own"], ["conciencia,", "conscience,"], ["y", "and"], ["concedemos", "and"], ["a", "to"], ["todos", "all"], ["los", "the"], ["hombres", "men"], ["el", "the"], ["mismo", "same"], ["privilegio:", "privilege:"], ["que", "that"], ["adoren", "worship"], ["cómo,", "how,"], ["dónde", "where"], ["o", "or"], ["lo", "it/him"], ["que", "that"], ["deseen.", "may."]]},
  {num:12,words:[["Creemos", "believe"], ["en", "in"], ["estar", "be"], ["sujetos", "subject"], ["a", "to"], ["los", "the"], ["reyes,", "kings,"], ["presidentes,", "presidents,"], ["gobernantes", "rulers"], ["y", "and"], ["magistrados;", "magistrates;"], ["en", "in"], ["obedecer,", "obey,"], ["honrar", "to"], ["y", "and"], ["sostener", "their"], ["la", "the"], ["ley.", "law."]]},
  {num:13,words:[["Creemos", "believe"], ["en", "in"], ["ser", "be"], ["honrados,", "men,"], ["verídicos,", ","], ["castos,", "true,"], ["benevolentes,", "chaste,"], ["virtuosos", ","], ["y", "and"], ["en", "in"], ["hacer", "make/do"], ["el", "the"], ["bien", "well"], ["a", "to"], ["todos", "all"], ["los", "the"], ["hombres;", "men;"], ["en", "in"], ["verdad,", "truth,"], ["podemos", "cannot"], ["decir", "say"], ["que", "that"], ["seguimos", "the"], ["la", "the"], ["admonición", "of"], ["de", "of"], ["Pablo:", "paul:"], ["Todo", "all"], ["lo", "it/him"], ["creemos,", "believe,"], ["todo", "all"], ["lo", "it/him"], ["esperamos;", "we;"], ["hemos", "we-have"], ["sufrido", "all"], ["muchas", "many"], ["cosas,", "things,"], ["y", "and"], ["esperamos", "we"], ["poder", "power/can"], ["sufrir", "of"], ["todas", "all"], ["las", "the"], ["cosas.", "things."], ["Si", "if"], ["hay", "there-is"], ["algo", "something"], ["virtuoso,", "virtuous,"], ["o", "or"], ["bello,", ","], ["o", "or"], ["de", "of"], ["buena", "good"], ["reputación,", "or,"], ["o", "or"], ["digno", "worthy"], ["de", "of"], ["alabanza,", "praise,"], ["a", "to"], ["esto", "this"], ["aspiramos.", "smith."]]},
];
renderVerseSet(v1, 'af-ch1-verses');

})();
