(function() {
var v1 = [
  {num:1,words:[["Nosotros","we"],["creemos","we-believe"],["en","in"],["Dios","God"],["el","the"],["Eterno","eternal"],["Padre,","father,"],["y","and"],["en","in"],["su","his"],["Hijo","son"],["Jesucristo,","Jesus-Christ,"],["y","and"],["en","in"],["el","the"],["Espíritu","Spirit"],["Santo.","holy."]]},
  {num:2,words:[["Creemos","we-believe"],["que","that"],["los","the"],["hombres","men"],["serán","they-shall-be"],["castigados","punished"],["por","for"],["sus","their"],["propios","own"],["pecados,","sins,"],["y","and"],["no","not"],["por","for"],["la","the"],["transgresión","transgression"],["de","of"],["Adán.","Adam."]]},
  {num:3,words:[["Creemos","we-believe"],["que","that"],["por","by"],["la","the"],["expiación","atonement"],["de","of"],["Cristo,","Christ,"],["todo","all"],["el","the"],["género","mankind"],["humano","mankind"],["puede","can"],["salvarse,","saved,"],["mediante","through"],["la","the"],["obediencia","obedience"],["a","to"],["las","the"],["leyes","laws"],["y","and"],["ordenanzas","ordinances"],["del","of-the"],["Evangelio.","gospel."]]},
  {num:4,words:[["Creemos","we-believe"],["que","that"],["los","the"],["primeros","first"],["principios","principles"],["y","and"],["ordenanzas","ordinances"],["del","of-the"],["Evangelio","gospel"],["son:","they-are:"],["primero,","first,"],["Fe","faith"],["en","in"],["el","the"],["Señor","Lord"],["Jesucristo;","Jesus-Christ;"],["segundo,","second,"],["Arrepentimiento;","repentance;"],["tercero,","third,"],["Bautismo","baptism"],["por","by/for"],["inmersión","baptism"],["para","for"],["la","the"],["remisión","remission"],["de","of"],["los","the"],["pecados;","sins;"],["cuarto,","fourth,"],["Imposición","laying"],["de","of"],["manos","hands"],["para","for"],["comunicar","for"],["el","the"],["don","gift"],["del","of-the"],["Espíritu","Spirit"],["Santo.","holy."]]},
  {num:5,words:[["Creemos","we-believe"],["que","that"],["el","the"],["hombre","man"],["debe","must"],["ser","be"],["llamado","called"],["por","by"],["Dios,","God,"],["por","by"],["profecía","prophecy"],["y","and"],["la","the"],["imposición","laying"],["de","of"],["manos,","hands,"],["por","by"],["aquellos","those"],["que","that"],["tienen","they-have"],["la","the"],["autoridad,","authority,"],["a fin de que","so that"],["pueda","by which"],["predicar","to-preach"],["el","the"],["evangelio","gospel"],["y","and"],["administrar","administer"],["sus","his/her"],["ordenanzas.","ordinances."]]},
  {num:6,words:[["Creemos","we-believe"],["en","in"],["la","the"],["misma","same"],["organización","organization"],["que","that"],["existió","in"],["en","in"],["la","the"],["Iglesia","church"],["Primitiva,","apostles,"],["esto","this"],["es,","is,"],["apóstoles,","apostles,"],["profetas,","prophets,"],["pastores,","pastors,"],["maestros,","teachers,"],["evangelistas,","and,"],["etc.","forth."]]},
  {num:7,words:[["Creemos","we-believe"],["en","in"],["el","the"],["don","gift"],["de","of"],["lenguas,","tongues,"],["profecía,","prophecy,"],["revelación,","revelation,"],["visiones,","you-visions,"],["sanidades,","the,"],["interpretación","interpretation"],["de","of"],["lenguas,","tongues,"],["etc.","so."]]},
  {num:8,words:[["Creemos","we-believe"],["que","that"],["la","the"],["Biblia","Bible"],["es","is"],["la","the"],["palabra","word"],["de","of"],["Dios","God"],["hasta","until"],["donde","where"],["esté","be"],["traducida","the"],["correctamente;","toly;"],["también","also"],["creemos","we-believe"],["que","that"],["el","the"],["Libro","book"],["de","of"],["Mormón","Mormon"],["es","is"],["la","the"],["palabra","word"],["de","of"],["Dios.","God."]]},
  {num:9,words:[["Creemos","we-believe"],["todo","all"],["lo","it/him"],["que","that"],["Dios","God"],["ha","has"],["revelado,","revealed,"],["todo","all"],["lo","it/him"],["que","that"],["actualmente","now"],["revela,","of,"],["y","and"],["creemos","we-believe"],["que","that"],["aún","yet"],["revelará","will-reveal"],["muchos","many"],["grandes","great"],["e","and"],["importantes","and"],["asuntos","affairs"],["pertenecientes","pertaining"],["al","to-the"],["reino","kingdom"],["de","of"],["Dios.","God."]]},
  {num:10,words:[["Creemos","we-believe"],["en","in"],["la","the"],["congregación","congregation"],["literal","literal"],["del","of-the"],["pueblo","people"],["de","of"],["Israel","Israel"],["y","and"],["en","in"],["la","the"],["restauración","restoration"],["de","of"],["las","the"],["Diez","ten"],["Tribus;","tribes;"],["que","that"],["Sion","Zion"],["(la","the"],["Nueva","new"],["Jerusalén)","Jerusalem)"],["será","shall-be"],["edificada","built"],["sobre","upon"],["el","the"],["continente","continent;"],["americano;","that;"],["que","that"],["Cristo","Christ"],["reinará","will-reign"],["personalmente","upon"],["sobre","upon"],["la","the"],["tierra,","earth,"],["y","and"],["que","that"],["la","the"],["tierra","earth"],["será","shall-be"],["renovada","renewed"],["y","and"],["recibirá","receive"],["su","its"],["gloria","glory"],["paradisíaca.","."]]},
  {num:11,words:[["Reclamamos","we"],["el","the"],["derecho","right"],["de","of"],["adorar","worship"],["a","to"],["Dios","God"],["Todopoderoso","Almighty"],["conforme","according-to"],["a","to"],["los","the"],["dictados","dictates"],["de","of"],["nuestra","our"],["propia","own"],["conciencia,","conscience,"],["y","and"],["concedemos","and"],["a","to"],["todos","all"],["los","the"],["hombres","men"],["el","the"],["mismo","same"],["privilegio:","I-privilege:"],["que","that"],["adoren","they-worship"],["cómo,","how,"],["dónde","where"],["o","or"],["lo","it/him"],["que","that"],["deseen.","they-may."]]},
  {num:12,words:[["Creemos","we-believe"],["en","in"],["estar","be"],["sujetos","subject"],["a","to"],["los","the"],["reyes,","kings,"],["presidentes,","presidents,"],["gobernantes","rulers"],["y","and"],["magistrados;","magistrates;"],["en","in"],["obedecer,","obey,"],["honrar","to"],["y","and"],["sostener","their"],["la","the"],["ley.","law."]]},
  {num:13,words:[["Creemos","we-believe"],["en","in"],["ser","be"],["honrados,","men,"],["verídicos,",","],["castos,","true,"],["benevolentes,","chaste,"],["virtuosos",","],["y","and"],["en","in"],["hacer","make/do"],["el","the"],["bien","well"],["a","to"],["todos","all"],["los","the"],["hombres;","men;"],["en verdad,","truly,"],["podemos","we-cannot"],["decir","to-say"],["que","that"],["seguimos","the"],["la","the"],["admonición","of"],["de","of"],["Pablo:","Paul:"],["Todo","all"],["lo","it/him"],["creemos,","we-believe,"],["todo","all"],["lo","it/him"],["esperamos;","we;"],["hemos","we-have"],["sufrido","all"],["muchas","many"],["cosas,","things,"],["y","and"],["esperamos","we"],["poder","power/can"],["sufrir","of"],["todas","all"],["las","the"],["cosas.","things."],["Si","if"],["hay","there-is"],["algo","something"],["virtuoso,","virtuous,"],["o","or"],["bello,",","],["o","or"],["de","of"],["buena","good"],["reputación,","or,"],["o","or"],["digno","worthy"],["de","of"],["alabanza,","praise,"],["a","to"],["esto","this"],["aspiramos.","we-smith."]]},
];
renderVerseSet(v1, 'af-ch1-verses');

})();
