(function() {
var v1 = [
  {num:1,words:[["Y","and"],["aconteció","it-came-to-pass"],["en","in"],["los","the"],["días","days"],["de","of"],["Asuero","Ahasuerus"],["(el","the"],["Asuero","Ahasuerus"],["que","that"],["reinó","reigned"],["desde","from"],["la","the"],["India","India"],["hasta","until"],["Etiopía","Ethiopia"],["sobre","upon"],["ciento","hundred"],["veintisiete","seventh"],["provincias)","provinces)"]]},
  {num:2,words:[["que","that"],["en","in"],["aquellos","those"],["días,","days,"],["cuando","when"],["el","the"],["rey","king"],["Asuero","Ahasuerus"],["se","himself"],["sentaba","sat"],["en","in"],["el","the"],["trono","throne"],["de","of"],["su","his"],["reino,","kingdom,"],["el","the"],["cual","which"],["estaba","was"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa,","Shushan,"]]},
  {num:3,words:[["en","in"],["el","the"],["tercer","third"],["año","year"],["de","of"],["su","his"],["reinado,","reign,"],["hizo","made"],["un","a"],["banquete","banquet"],["para","for"],["todos","all"],["sus","his"],["príncipes","princes"],["y","and"],["servidores,","servants,"],["teniendo","having"],["delante","before"],["de","of"],["él","he"],["a","to"],["los","the"],["poderosos","mighty"],["de","of"],["Persia","Persia"],["y","and"],["de","of"],["Media,","Media,"],["los","the"],["nobles","nobles"],["y","and"],["los","the"],["príncipes","princes"],["de","of"],["las","the"],["provincias,","provinces,"]]},
  {num:4,words:[["mientras","while"],["les","them"],["mostraba","showed"],["las","the"],["riquezas","riches"],["de","of"],["la","the"],["gloria","glory"],["de","of"],["su","his"],["reino","kingdom"],["y","and"],["el","the"],["esplendor","splendor"],["de","of"],["la","the"],["magnificencia","majesty"],["de","of"],["su","his"],["majestad","majesty"],["durante","during"],["muchos","many"],["días,","days,"],["ciento","hundred"],["ochenta","eighty"],["días.","days."]]},
  {num:5,words:[["Y","and"],["cuando","when"],["se","themselves"],["cumplieron","fulfilled"],["estos","these"],["días,","days,"],["hizo","made"],["el","the"],["rey","king"],["un","a"],["banquete","banquet"],["durante","during"],["siete","seven"],["días","days"],["en","in"],["el","the"],["patio","court"],["del","of-the"],["huerto","garden"],["del","of-the"],["palacio","palace"],["real","royal"],["para","for"],["todo","all"],["el","the"],["pueblo","people"],["que","that"],["se","himself"],["hallaba","was-found"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa,","Shushan,"],["desde","from"],["el","the"],["mayor","greater"],["hasta","until"],["el","the"],["menor.","lesser."]]},
  {num:6,words:[["El","the"],["cortinaje","were"],["era","was"],["de","of"],["lino","twined"],["blanco","white"],["y","and"],["material","hangings"],["azul,","blue,"],["sujeto","to"],["por","for"],["cuerdas","cords"],["de","of"],["lino","twined"],["fino","purple"],["y","and"],["material","purple"],["púrpura","purple"],["en","in"],["aros","silver"],["de","of"],["plata","silver"],["y","and"],["columnas","pillars"],["de","of"],["mármol;","marble;"],["los","the"],["reclinatorios","prie-dieus"],["eran","they-were"],["de","of"],["oro","gold"],["y","and"],["de","of"],["plata","silver"],["sobre","upon"],["un","a"],["suelo","ground"],["de","of"],["pórfido","porphyry"],["y","and"],["de","of"],["mármol,","blue,"],["de","of"],["alabastro","white"],["y","and"],["de","of"],["piedras","stones"],["valiosas.","marble."]]},
  {num:7,words:[["Y","and"],["daban","they-gave"],["a","to"],["beber","drink"],["en","in"],["vasos","vessels"],["de","of"],["oro,","gold,"],["vasos","vessels"],["diferentes","in"],["unos","some"],["de","of"],["otros,","others,"],["y","and"],["mucho","much"],["vino","wine"],["real,","royal,"],["conforme","according-to"],["a","to"],["la","the"],["generosidad","state"],["del","of-the"],["rey.","king."]]},
  {num:8,words:[["Y","and"],["el","the"],["beber","drink"],["fue","was"],["según","according-to"],["la","the"],["ley:","law:"],["Que","that"],["a","to"],["nadie","no-one"],["se","himself"],["le","his"],["obligara;","might-force;"],["porque","because"],["así","thus"],["lo","it/him"],["había","had"],["mandado","commanded"],["el","the"],["rey","king"],["a","to"],["todos","all"],["los","the"],["oficiales","officers"],["de","of"],["su","his"],["casa,","house,"],["que","that"],["se","himself"],["hiciese","might-make"],["según","according-to"],["la","the"],["voluntad","will"],["de","of"],["cada","each"],["uno.","one."]]},
  {num:9,words:[["Asimismo","likewise"],["la","the"],["reina","queen"],["Vasti","Vashti"],["hizo","made"],["un","a"],["banquete","banquet"],["para","for"],["las","the"],["mujeres","women"],["en","in"],["la","the"],["casa","house"],["real","royal"],["del","of-the"],["rey","king"],["Asuero.","Ahasuerus."]]},
  {num:10,words:[["El","the"],["séptimo","seventh"],["día,","day,"],["cuando","when"],["el","the"],["corazón","heart"],["del","of-the"],["rey","king"],["estaba","was"],["alegre","merry"],["por","for"],["el","the"],["vino,","wine,"],["mandó","commanded"],["a","to"],["Mehumán,","commanded,"],["a","to"],["Bizta,","biztha,"],["a","to"],["Harbona,","bigtha,"],["a","to"],["Bigta,","abagtha,"],["a","to"],["Abagta,","and,"],["a","to"],["Zetar","the"],["y","and"],["a","to"],["Carcas,","that,"],["siete","seven"],["eunucos","chamberlains"],["que","that"],["servían","they-served"],["delante","before"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"]]},
  {num:11,words:[["que","that"],["trajesen","they-might-bring"],["a","to"],["la","the"],["reina","queen"],["Vasti","Vashti"],["delante","before"],["del","of-the"],["rey","king"],["con","with"],["la","the"],["corona","crown"],["real,","royal,"],["para","for"],["mostrar","to-show"],["a","to"],["los","the"],["pueblos","peoples"],["y","and"],["a","to"],["los","the"],["príncipes","princes"],["su","her"],["belleza,","beauty,"],["porque","because"],["era","was"],["de","of"],["hermosa","beautiful"],["apariencia.","appearance."]]},
  {num:12,words:[["Pero","but"],["la","the"],["reina","queen"],["Vasti","Vashti"],["no","not"],["quiso","wanted"],["comparecer,","judged,"],["a pesar de","despite"],["la","the"],["orden","order"],["del","of-the"],["rey,","king,"],["enviada","sent"],["por medio de","by means of"],["los","the"],["eunucos;","chamberlains;"],["y","and"],["se","himself"],["enojó","wroth"],["el","the"],["rey","king"],["muchísimo,","and,"],["y","and"],["se","himself"],["encendió","kindled"],["en","in"],["él","he"],["su","his"],["ira.","anger."]]},
  {num:13,words:[["Preguntó","asked"],["entonces","then"],["el","the"],["rey","king"],["a","to"],["los","the"],["sabios","wise"],["que","that"],["entendían","they-understood"],["los","the"],["tiempos,","times,"],["porque","because"],["así","thus"],["era","was"],["la","the"],["costumbre","custom"],["del","of-the"],["rey","king"],["con","with"],["todos","all"],["los","the"],["que","that"],["conocían","they-knew"],["la","the"],["ley","law"],["y","and"],["el","the"],["derecho;","right;"]]},
  {num:14,words:[["y","and"],["estaban","they-were"],["junto","together"],["a","to"],["él","he"],["Carsena,","was,"],["Setar,","carshena,"],["Admata,","shethar,"],["Tarsis,","Tarshish,"],["Meres,","Tarshish,"],["Marsena","meres"],["y","and"],["Memucán,","Memucan,"],["siete","seven"],["príncipes","princes"],["de","of"],["Persia","Persia"],["y","and"],["de","of"],["Media","Media"],["que","that"],["tenían","they-had"],["acceso","saw"],["al","to-the"],["rey","king"],["y","and"],["que","that"],["ocupaban","they-occupied"],["los","the"],["primeros","first"],["puestos","set"],["en","in"],["el","the"],["reino.","kingdom."]]},
  {num:15,words:[["Según","according-to"],["la","the"],["ley,","law,"],["¿qué","what"],["se","himself"],["debe","must"],["hacer","do"],["con","with"],["la","the"],["reina","queen"],["Vasti,","Vashti,"],["por cuanto","because"],["no","not"],["ha","has"],["cumplido","performed"],["la","the"],["orden","order"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"],["enviada","sent"],["por medio de","by means of"],["los","the"],["eunucos?","chamberlains?"]]},
  {num:16,words:[["Y","and"],["dijo","said"],["Memucán","Memucan"],["delante","before"],["del","of-the"],["rey","king"],["y","and"],["de","of"],["los","the"],["príncipes:","princes:"],["La","the"],["reina","queen"],["Vasti","Vashti"],["no","not"],["solamente","only"],["ha","has"],["ofendido","offended"],["al","to-the"],["rey,","king,"],["sino","but"],["también","also"],["a","to"],["todos","all"],["los","the"],["príncipes","princes"],["y","and"],["a","to"],["todos","all"],["los","the"],["pueblos","peoples"],["que","that"],["hay","there-is"],["en","in"],["todas","all"],["las","the"],["provincias","provinces"],["del","of-the"],["rey","king"],["Asuero.","Ahasuerus."]]},
  {num:17,words:[["Porque","because"],["este","this"],["hecho","done/made"],["de","of"],["la","the"],["reina","queen"],["llegará","will-come"],["a","to"],["oídos","ears"],["de","of"],["todas","all"],["las","the"],["mujeres","women"],["y","and"],["las","the"],["hará","shall-make"],["tener","have"],["en","in"],["poca","little"],["estima","estimates"],["a","to"],["sus","their"],["maridos,","husbands,"],["diciendo:","saying:"],["El","the"],["rey","king"],["Asuero","Ahasuerus"],["mandó","commanded"],["traer","to-bring"],["ante","before"],["su","their"],["presencia","presence"],["a","to"],["la","the"],["reina","queen"],["Vasti,","Vashti,"],["y","and"],["ella","she"],["no","not"],["quiso","wanted"],["ir.","to-go."]]},
  {num:18,words:[["Y","and"],["entonces","then"],["dirán","they-will-say"],["lo","it/him"],["mismo","same"],["las","the"],["señoras","ands"],["de","of"],["Persia","Persia"],["y","and"],["de","of"],["Media","Media"],["que","that"],["hayan","they-may-have"],["oído","heard"],["lo","it/him"],["que","that"],["hizo","made/did"],["la","the"],["reina","queen"],["a","to"],["todos","all"],["los","the"],["príncipes","princes"],["del","of-the"],["rey;","king;"],["y","and"],["habrá","there-shall-be"],["mucho","much"],["menosprecio","despised"],["y","and"],["enojo.","fury."]]},
  {num:19,words:[["Si","if"],["le","him"],["parece","seems"],["bien","well"],["al","to-the"],["rey,","king,"],["salga","comes"],["un","a"],["decreto","decree"],["real","royal"],["de","of"],["él,","he,"],["y","and"],["escríbase","scribe-oneself"],["en","in"],["las","the"],["leyes","laws"],["de","of"],["Persia","Persia"],["y","and"],["de","of"],["Media,","gadites,"],["para que","that"],["no","not"],["sea","be"],["abrogado:","repealed:"],["Que","that"],["no","not"],["se","himself"],["presente","present"],["más","more"],["Vasti","Vashti"],["delante","before"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"],["y","and"],["que","that"],["el","the"],["rey","king"],["haga","let-do"],["reina","queen"],["a","to"],["otra","other"],["que","that"],["sea","be"],["mejor","better"],["que","that"],["ella.","she."]]},
  {num:20,words:[["Y","and"],["el","the"],["decreto","decree"],["que","that"],["dicte","may-dictate"],["el","the"],["rey","king"],["será","shall-be"],["oído","heard"],["en","in"],["todo","all"],["su","his"],["reino,","kingdom,"],["aunque","although"],["es","is"],["grande;","great;"],["y","and"],["todas","all"],["las","the"],["mujeres","women"],["honrarán","they-shall-to"],["a","to"],["sus","his"],["maridos,","husbands,"],["desde","from"],["el","the"],["mayor","greater"],["hasta","until"],["el","the"],["menor.","lesser."]]},
  {num:21,words:[["Y","and"],["esta","this"],["palabra","word"],["pareció","pleased"],["bien","well"],["ante","before"],["los","the"],["ojos","eyes"],["del","of-the"],["rey","king"],["y","and"],["de","of"],["los","the"],["príncipes,","princes,"],["e","and"],["hizo","did"],["el","the"],["rey","king"],["conforme","according-to"],["a","to"],["lo","it/him"],["dicho","said"],["por","for"],["Memucán;","Memucan;"]]},
  {num:22,words:[["pues","for"],["envió","sent"],["cartas","letters"],["a","to"],["todas","all"],["las","the"],["provincias","provinces"],["del","of-the"],["rey,","king,"],["a","to"],["cada","each"],["provincia","province"],["conforme","according-to"],["a","to"],["su","his"],["escritura,","writing,"],["y","and"],["a","to"],["cada","each"],["pueblo","people"],["conforme","according-to"],["a","to"],["su","his"],["lenguaje,","language,"],["diciendo","saying"],["que","that"],["todo","all"],["hombre","man"],["fuese","might-be"],["señor","Lord"],["en","in"],["su","his"],["casa,","house,"],["y","and"],["que","that"],["se","himself"],["publicase","might-publish"],["esto","this"],["según","according-to"],["la","the"],["lengua","tongue"],["de","of"],["su","his"],["pueblo.","people."]]},
];
renderVerseSet(v1, 'est-ch1-verses');

var v2 = [
  {num:1,words:[["Después","after"],["de","of"],["estas","these"],["cosas,","things,"],["cuando","when"],["la","the"],["ira","wrath"],["del","of-the"],["rey","king"],["Asuero","Ahasuerus"],["se","himself"],["había","had"],["aplacado,","placated,"],["este","this"],["se","himself"],["acordó","remembered"],["de","of"],["Vasti,","Vashti,"],["y","and"],["de","of"],["lo","it/him"],["que","that"],["ella","she"],["había","had"],["hecho","done"],["y","and"],["de","of"],["lo","it/him"],["que","that"],["se","himself"],["había","had"],["decretado","decreed"],["contra","against"],["ella.","she."]]},
  {num:2,words:[["Y","and"],["dijeron","they-said"],["los","the"],["que","that"],["estaban","they-were"],["al","to-the"],["servicio","service"],["del","of-the"],["rey:","king:"],["Busquen","they-seek"],["para","for"],["el","the"],["rey","king"],["jóvenes","young-men"],["vírgenes","virgins"],["de","of"],["buen","cheer"],["parecer;","should;"]]},
  {num:3,words:[["y","and"],["nombre","name"],["el","the"],["rey","king"],["personas","persons"],["en","in"],["todas","all"],["las","the"],["provincias","provinces"],["de","of"],["su","his"],["reino","kingdom"],["que","that"],["reúnan","they-may-gather"],["a","to"],["todas","all"],["las","the"],["jóvenes","young-men"],["vírgenes","virgins"],["de","of"],["buen","cheer"],["parecer","should"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa,","Shushan,"],["en","in"],["la","the"],["casa","house"],["de","of"],["las","the"],["mujeres,","women,"],["bajo","under"],["la","the"],["custodia","custody"],["de","of"],["Hegai,","of,"],["eunuco","of"],["del","of-the"],["rey,","king,"],["encargado","kings"],["de","of"],["las","the"],["mujeres,","women,"],["dándoles","giving-them"],["sus","his"],["atavíos;","them;"]]},
  {num:4,words:[["y","and"],["la","the"],["joven","young-man"],["que","that"],["agrade","may-please"],["a","to"],["los","the"],["ojos","eyes"],["del","of-the"],["rey,","king,"],["reine","reign"],["en","in"],["lugar","place"],["de","of"],["Vasti.","Vashti."],["Y","and"],["esto","this"],["agradó","pleased"],["al","to-the"],["rey,","king,"],["y","and"],["lo","it/him"],["hizo","did"],["así.","thus."]]},
  {num:5,words:[["Había","had"],["un","a"],["hombre","man"],["judío","Jew"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa,","Shushan,"],["cuyo","whose"],["nombre","name"],["era","was"],["Mardoqueo","Mordecai"],["hijo","son"],["de","of"],["Jair,","Jair,"],["hijo","son"],["de","of"],["Simei,","Shimei,"],["hijo","son"],["de","of"],["Cis,","Kish,"],["del","of-the"],["linaje","lineage"],["de","of"],["Benjamín,","Benjamin,"]]},
  {num:6,words:[["que","that"],["había","had"],["sido","been"],["llevado","carried"],["cautivo","captive"],["de","of"],["Jerusalén","Jerusalem"],["con","with"],["los","the"],["cautivos","captives"],["que","that"],["fueron","they-were"],["llevados","carried"],["con","with"],["Jeconías,","the,"],["rey","king"],["de","of"],["Judá,","Judah,"],["a","to"],["quien","who"],["Nabucodonosor,","Nebuchadnezzar,"],["rey","king"],["de","of"],["Babilonia,","Babylon,"],["llevó","carried"],["cautivo.","captive."]]},
  {num:7,words:[["Y","and"],["había","had"],["criado","servant"],["a","to"],["Hadasa,","hadassah,"],["es","is"],["decir,","to-say,"],["Ester,","Esther,"],["hija","daughter"],["de","of"],["su","his"],["tío,","uncle,"],["porque","because"],["ella","she"],["no","not"],["tenía","had"],["padre","father"],["ni","nor"],["madre;","mother;"],["y","and"],["la","the"],["joven","young-man"],["era","was"],["de","of"],["hermosa","beautiful"],["figura","a"],["y","and"],["de","of"],["buen","cheer"],["parecer;","should;"],["y","and"],["cuando","when"],["su","his"],["padre","father"],["y","and"],["su","his"],["madre","mother"],["murieron,","they-died,"],["Mardoqueo","Mordecai"],["la","the"],["tomó","took"],["como","as"],["hija","daughter"],["suya.","his."]]},
  {num:8,words:[["Sucedió,","it-came-to-pass,"],["pues,","for,"],["que","that"],["cuando","when"],["fueron","they-were"],["oídos","ears"],["el","the"],["mandato","decree"],["y","and"],["el","the"],["decreto","decree"],["del","of-the"],["rey,","king,"],["fueron","they-were"],["reunidas","gathered"],["muchas","many"],["jóvenes","young-men"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa,","Shushan,"],["bajo","under"],["la","the"],["custodia","custody"],["de","of"],["Hegai;","Hegai;"],["Ester","Esther"],["también","also"],["fue","was"],["llevada","into"],["a","to"],["la","the"],["casa","house"],["del","of-the"],["rey,","king,"],["al","to-the"],["cuidado","care"],["de","of"],["Hegai,","Hegai,"],["encargado","kings"],["de","of"],["las","the"],["mujeres.","women."]]},
  {num:9,words:[["Y","and"],["la","the"],["joven","young-man"],["agradó","pleased"],["a","to"],["sus","her"],["ojos","eyes"],["y","and"],["halló","found"],["gracia","grace"],["delante","before"],["de","of"],["él,","he,"],["por","for"],["lo","him"],["que","that"],["se","himself"],["apresuró","hurried"],["a","to"],["darle","give-him"],["sus","her"],["atavíos","belonged"],["y","and"],["sus","her"],["alimentos","food"],["especiales,","special,"],["dándole","giving-him"],["también","also"],["siete","seven"],["doncellas","maidens"],["aptas","given"],["de","of"],["la","the"],["casa","house"],["del","of-the"],["rey;","king;"],["y","and"],["la","the"],["llevó","carried"],["con","with"],["sus","her"],["doncellas","maidens"],["al","to-the"],["mejor","better"],["lugar","place"],["de","of"],["la","the"],["casa","house"],["de","of"],["las","the"],["mujeres.","women."]]},
  {num:10,words:[["Ester","Esther"],["no","not"],["declaró","declared"],["cuál","which"],["era","was"],["su","her"],["pueblo","people"],["ni","nor"],["su","her"],["parentela,","kindred,"],["porque","because"],["Mardoqueo","Mordecai"],["le","her"],["había","had"],["mandado","commanded"],["que","that"],["no","not"],["lo","it"],["declarase.","to-himself."]]},
  {num:11,words:[["Y","and"],["cada","each"],["día","day"],["Mardoqueo","Mordecai"],["se","itself"],["paseaba","took-a-walk"],["delante","before"],["del","of-the"],["patio","court"],["de","of"],["la","the"],["casa","house"],["de","of"],["las","the"],["mujeres,","women,"],["para","for"],["saber","to-know"],["cómo","how"],["le","her"],["iba","went"],["a","to"],["Ester","Esther"],["y","and"],["qué","what"],["le","her"],["sucedía","came-to-pass"],["a","to"],["ella.","she."]]},
  {num:12,words:[["Y","and"],["cuando","when"],["llegaba","came"],["el","the"],["turno","turn"],["a","to"],["cada","each"],["una","a"],["de","of"],["las","the"],["jóvenes","young-men"],["para","for"],["presentarse","to-present-himself"],["ante","before"],["el","the"],["rey","king"],["Asuero,","Ahasuerus,"],["después","after"],["de","of"],["haber","have"],["estado","state"],["ya","already"],["doce","twelve"],["meses","months"],["conforme","according-to"],["a","to"],["la","the"],["ley","law"],["acerca","about"],["de","of"],["las","the"],["mujeres","women"],["(porque","because"],["así","thus"],["se","itself"],["cumplía","was-fulfilling"],["el","the"],["tiempo","time"],["de","of"],["su","their"],["embellecimiento,","with,"],["esto","this"],["es,","is,"],["seis","six"],["meses","months"],["con","with"],["óleo","months"],["de","of"],["mirra,","myrrh,"],["y","and"],["seis","six"],["meses","months"],["con","with"],["bálsamos","balms"],["aromáticos","anointings"],["y","and"],["embellecedores","purifying"],["para","for"],["las","the"],["mujeres),","women),"]]},
  {num:13,words:[["entonces","then"],["cada","each"],["joven","young-man"],["se","itself"],["presentaba","presented"],["así","thus"],["ante","before"],["el","the"],["rey;","king;"],["todo","all"],["lo","it/him"],["que","that"],["ella","she"],["pedía","asked"],["se","himself"],["le","her"],["daba,","gave,"],["para","for"],["llevarlo","to-carry-it"],["consigo","with-him"],["desde","from"],["la","the"],["casa","house"],["de","of"],["las","the"],["mujeres","women"],["hasta","until"],["la","the"],["casa","house"],["del","of-the"],["rey.","king."]]},
  {num:14,words:[["Ella","she"],["iba","went"],["al","to-the"],["anochecer,","nightfall,"],["y","and"],["a","to"],["la","the"],["mañana","morning"],["siguiente","morrow"],["volvía","returned"],["a","to"],["la","the"],["segunda","second"],["casa","house"],["de","of"],["las","the"],["mujeres,","women,"],["a","to"],["cargo","charge"],["de","of"],["Saasgaz,","shaashgaz,"],["eunuco","of"],["del","of-the"],["rey,","king,"],["encargado","kings"],["de","of"],["las","the"],["concubinas;","concubines;"],["no","not"],["volvía","returned"],["más","more"],["ante","before"],["el","the"],["rey,","king,"],["salvo","I-except"],["que","that"],["el","the"],["rey","king"],["lo","it/him"],["quisiera","would-like"],["y","and"],["fuera","were"],["llamada","called"],["por","by"],["su","her"],["nombre.","name."]]},
  {num:15,words:[["Y","and"],["cuando","when"],["llegó","arrived"],["el","the"],["turno","shift"],["de","of"],["Ester","Esther"],["hija","daughter"],["de","of"],["Abihail,","Abihail,"],["tío","uncle"],["de","of"],["Mardoqueo,","Mordecai,"],["a","to"],["la","the"],["que","that"],["este","this"],["había","had"],["tomado","taken"],["como","as"],["hija,","daughter,"],["para","for"],["presentarse","to-present-himself"],["ante","before"],["el","the"],["rey,","king,"],["ninguna","none"],["cosa","thing"],["pidió","king"],["sino","but"],["lo","it/him"],["que","that"],["le","her"],["dijo","said"],["Hegai,","Hegai,"],["eunuco","of"],["del","of-the"],["rey,","king,"],["encargado","kings"],["de","of"],["las","the"],["mujeres;","women;"],["y","and"],["Ester","Esther"],["hallaba","found"],["gracia","grace"],["ante","before"],["los","the"],["ojos","eyes"],["de","of"],["todos","all"],["los","the"],["que","that"],["la","the"],["veían.","saw."]]},
  {num:16,words:[["Fue,","was,"],["pues,","for,"],["Ester","Esther"],["llevada","into"],["ante","before"],["el","the"],["rey","king"],["Asuero","Ahasuerus"],["a","to"],["la","the"],["casa","house"],["real","royal"],["en","in"],["el","the"],["mes","month"],["décimo,","tenth,"],["que","that"],["es","is"],["el","the"],["mes","month"],["de","of"],["Tebet,","in,"],["en","in"],["el","the"],["año","year"],["séptimo","seventh"],["de","of"],["su","his"],["reinado.","reign."]]},
  {num:17,words:[["Y","and"],["el","the"],["rey","king"],["amó","loved"],["a","to"],["Ester","Esther"],["más","more"],["que","that"],["a","to"],["todas","all"],["las","the"],["otras","others"],["mujeres,","women,"],["y","and"],["ella","she"],["halló","found"],["gracia","grace"],["y","and"],["benevolencia","benevolence"],["delante","before"],["de","of"],["él,","he,"],["más","more"],["que","that"],["todas","all"],["las","the"],["otras","others"],["vírgenes;","virgins;"],["y","and"],["puso","placed"],["la","the"],["corona","crown"],["real","royal"],["sobre","upon"],["su","his"],["cabeza","head"],["y","and"],["la","the"],["hizo","made"],["reina","queen"],["en","in"],["lugar","place"],["de","of"],["Vasti.","Vashti."]]},
  {num:18,words:[["Hizo","made"],["entonces","then"],["el","the"],["rey","king"],["un","a"],["gran","great"],["banquete","banquet"],["para","for"],["todos","all"],["sus","his"],["príncipes","princes"],["y","and"],["servidores,","servants,"],["el","the"],["banquete","banquet"],["de","of"],["Ester;","Esther;"],["y","and"],["dio","gave"],["descanso","I-rest"],["a","to"],["las","the"],["provincias","provinces"],["y","and"],["dio","gave"],["presentes,","you-gifts,"],["conforme","according-to"],["a","to"],["la","the"],["generosidad","generosity"],["del","of-the"],["rey.","king."]]},
  {num:19,words:[["Y","and"],["cuando","when"],["fueron","they-were"],["reunidas","gathered"],["las","the"],["vírgenes","virgins"],["por","for"],["segunda","second"],["vez,","time,"],["Mardoqueo","Mordecai"],["estaba","was"],["sentado","sitting"],["a","to"],["la","the"],["puerta","gate"],["del","of-the"],["rey.","king."]]},
  {num:20,words:[["Y","and"],["Ester,","Esther,"],["según","according-to"],["le","him"],["había","had"],["mandado","commanded"],["Mardoqueo,","Mordecai,"],["no","not"],["había","had"],["declarado","declared"],["cuál","which"],["era","was"],["su","her"],["parentela","kindred"],["ni","nor"],["su","her"],["pueblo,","people,"],["porque","because"],["Ester","Esther"],["hacía","did"],["lo","him"],["que","that"],["le","him"],["decía","said"],["Mardoqueo,","Mordecai,"],["como","as"],["cuando","when"],["él","he"],["la","the"],["educaba.","educated."]]},
  {num:21,words:[["En","in"],["aquellos","those"],["días,","days,"],["estando","being"],["Mardoqueo","Mordecai"],["sentado","sitting"],["a","to"],["la","the"],["puerta","gate"],["del","of-the"],["rey,","king,"],["se","themselves"],["enojaron","angry"],["Bigtán","chamberlains"],["y","and"],["Teres,","Teresh,"],["dos","two"],["eunucos","chamberlains"],["del","of-the"],["rey,","king,"],["de","of"],["la","the"],["guardia","nebuzaradan"],["de","of"],["la","the"],["puerta,","gate,"],["y","and"],["tramaban","lay"],["echar","cast"],["mano","hand"],["al","to-the"],["rey","king"],["Asuero.","Ahasuerus."]]},
  {num:22,words:[["Pero","but"],["cuando","when"],["Mardoqueo","Mordecai"],["se","itself"],["enteró","whole"],["de","of"],["esto,","this,"],["se","itself"],["lo","it"],["dijo","said"],["a","to"],["la","the"],["reina","queen"],["Ester,","Esther,"],["y","and"],["Ester","Esther"],["se","itself"],["lo","it"],["dijo","said"],["al","to-the"],["rey","king"],["en","in"],["nombre","name"],["de","of"],["Mardoqueo.","Mordecai."]]},
  {num:23,words:[["Y","and"],["cuando","when"],["se","itself"],["inquirió","inquired"],["el","the"],["asunto,","matter,"],["fue","was"],["hallado","found"],["cierto;","certain;"],["por tanto,","therefore,"],["los","the"],["dos","two"],["fueron","were"],["colgados","hang"],["en","in"],["una","a"],["horca.","the."],["Y","and"],["esto","this"],["se","itself"],["escribió","wrote"],["en","in"],["el","the"],["libro","book"],["de","of"],["las","the"],["crónicas","chronicles"],["en","in"],["presencia","presence"],["del","of-the"],["rey.","king."]]},
];
renderVerseSet(v2, 'est-ch2-verses');

var v3 = [
  {num:1,words:[["Después","after"],["de","of"],["estas","these"],["cosas,","things,"],["el","the"],["rey","king"],["Asuero","Ahasuerus"],["ascendió","ascended"],["de","of"],["posición","for"],["a","to"],["Amán","Haman"],["hijo","son"],["de","of"],["Hamedata,","Hammedatha,"],["el","the"],["agagueo,","advanced,"],["y","and"],["le","him"],["honró","toed"],["y","and"],["puso","placed"],["su","his"],["sitial","above"],["sobre","upon"],["todos","all"],["los","the"],["príncipes","princes"],["que","that"],["estaban","they-were"],["con","with"],["él.","he."]]},
  {num:2,words:[["Y","and"],["todos","all"],["los","the"],["servidores","servants"],["del","of-the"],["rey","king"],["que","that"],["estaban","they-were"],["a","to"],["la","the"],["puerta","gate"],["del","of-the"],["rey","king"],["se","themselves"],["arrodillaban","reverenced"],["e","and"],["inclinaban","they-inclined"],["ante","before"],["Amán,","Haman,"],["porque","because"],["así","thus"],["lo","him"],["había","had"],["mandado","commanded"],["el","the"],["rey;","king;"],["pero","but"],["Mardoqueo","Mordecai"],["ni","nor"],["se","himself"],["arrodillaba","knelt-down"],["ni","nor"],["se","himself"],["inclinaba.","reverence."]]},
  {num:3,words:[["Y","and"],["los","the"],["servidores","servants"],["del","of-the"],["rey","king"],["que","that"],["estaban","they-were"],["a","to"],["la","the"],["puerta","gate"],["dijeron","they-said"],["a","to"],["Mardoqueo:","Mordecai:"],["¿Por","for"],["qué","what"],["traspasas","you-transgress"],["el","the"],["mandato","decree"],["del","of-the"],["rey?","king?"]]},
  {num:4,words:[["Y","and"],["aconteció","it-came-to-pass"],["que,","that,"],["cuando","when"],["le","him"],["hablaban","they-spoke"],["cada","each"],["día","day"],["de","of"],["esta","this"],["manera,","manner,"],["y","and"],["él","he"],["no","not"],["los","the"],["escuchaba,","was-hearkening,"],["lo","it/him"],["denunciaron","they-denounced"],["a","to"],["Amán,","Haman,"],["para","for"],["ver","see"],["si","if"],["las","the"],["palabras","words"],["de","of"],["Mardoqueo","Mordecai"],["se","themselves"],["mantendrían,","they-would-maintain,"],["porque","because"],["él","he"],["ya","already"],["les","them"],["había","had"],["declarado","declared"],["que","that"],["era","was"],["judío.","Jew."]]},
  {num:5,words:[["Y","and"],["vio","saw"],["Amán","Haman"],["que","that"],["Mardoqueo","Mordecai"],["ni","nor"],["se","himself"],["arrodillaba","knelt-down"],["ni","nor"],["le","him"],["rendía","reverence"],["homenaje,","tribute,"],["y","and"],["se","himself"],["llenó","filled"],["de","of"],["ira.","wrath."]]},
  {num:6,words:[["Pero","but"],["le","him"],["pareció","pleased"],["poco","little"],["echar","cast"],["mano","hand"],["solo","alone"],["a","to"],["Mardoqueo,","Mordecai,"],["porque","because"],["ya","already"],["le","him"],["habían","they-had"],["declarado","declared"],["cuál","which"],["era","was"],["el","the"],["pueblo","people"],["de","of"],["Mardoqueo;","Mordecai;"],["y","and"],["procuró","sought"],["Amán","Haman"],["destruir","to-destroy"],["a","to"],["todos","all"],["los","the"],["judíos","Jews"],["que","that"],["había","had"],["en","in"],["el","the"],["reino","kingdom"],["de","of"],["Asuero,","Ahasuerus,"],["al","to-the"],["pueblo","people"],["de","of"],["Mardoqueo.","Mordecai."]]},
  {num:7,words:[["En","in"],["el","the"],["mes","month"],["primero,","first,"],["que","that"],["es","is"],["el","the"],["mes","month"],["de","of"],["Nisán,","Nisan,"],["en","in"],["el","the"],["año","year"],["duodécimo","twelfth"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"],["echaron","they-lots"],["pur,","Pur,"],["esto","this"],["es,","is,"],["la","the"],["suerte,","lot,"],["delante","before"],["de","of"],["Amán,","Haman,"],["por","for"],["día","day"],["y","and"],["por","for"],["mes;","month;"],["y","and"],["salió","departed"],["el","the"],["mes","month"],["duodécimo,","twelfth,"],["que","that"],["es","is"],["el","the"],["mes","month"],["de","of"],["Adar.","Adar."]]},
  {num:8,words:[["Y","and"],["dijo","said"],["Amán","Haman"],["al","to-the"],["rey","king"],["Asuero:","Ahasuerus:"],["Hay","there-is"],["un","a"],["pueblo","people"],["esparcido","scattered"],["y","and"],["diseminado","abroad"],["entre","among"],["los","the"],["pueblos","peoples"],["en","in"],["todas","all"],["las","the"],["provincias","provinces"],["de","of"],["tu","your"],["reino,","kingdom,"],["y","and"],["sus","their"],["leyes","laws"],["son","they-are"],["diferentes","in"],["de","of"],["las","the"],["de","of"],["todo","all"],["pueblo","people"],["y","and"],["no","not"],["observan","they-observe"],["las","the"],["leyes","laws"],["del","of-the"],["rey;","king;"],["y","and"],["al","to-the"],["rey","king"],["no","not"],["le","their"],["beneficia","benefits"],["dejarlos","to-leave-them"],["vivir.","to-live."]]},
  {num:9,words:[["Si","if"],["le","him"],["parece","seems"],["bien","well"],["al","to-the"],["rey,","king,"],["decrétese","be"],["que","that"],["sean","they-let-be"],["destruidos;","destroyed;"],["y","and"],["yo","I"],["pagaré","will-pay"],["diez","ten"],["mil","thousand"],["talentos","talents"],["de","of"],["plata","silver"],["en","in"],["manos","hands"],["de","of"],["los","the"],["que","that"],["manejan","they-drive"],["los","the"],["asuntos","affairs"],["reales,","in,"],["para que","that"],["sean","they-let-be"],["traídos","brought"],["a","to"],["los","the"],["tesoros","treasures"],["del","of-the"],["rey.","king."]]},
  {num:10,words:[["Entonces","then"],["el","the"],["rey","king"],["se","himself"],["quitó","removed"],["el","the"],["anillo","ring"],["de","of"],["su","his"],["mano","hand"],["y","and"],["lo","it"],["dio","gave"],["a","to"],["Amán","Haman"],["hijo","son"],["de","of"],["Hamedata,","Hammedatha,"],["el","the"],["agagueo,","the,"],["enemigo","enemy"],["de","of"],["los","the"],["judíos,","Jews,"]]},
  {num:11,words:[["y","and"],["el","the"],["rey","king"],["dijo","said"],["a","to"],["Amán:","Haman:"],["Quédate","you"],["con","with"],["la","the"],["plata","silver"],["y","and"],["también","also"],["con","with"],["el","the"],["pueblo,","people,"],["para que","that"],["hagas","you-pray"],["con","with"],["él","he"],["lo","it"],["que","that"],["bien","well"],["te","you"],["parezca.","seems."]]},
  {num:12,words:[["Entonces","then"],["fueron","they-were"],["llamados","called"],["los","the"],["escribas","scribes"],["del","of-the"],["rey","king"],["en","in"],["el","the"],["mes","month"],["primero,","first,"],["el","the"],["día","day"],["trece","thirteen"],["del","of-the"],["mismo","same"],["mes,","month,"],["y","and"],["fue","was"],["escrito","written"],["conforme","according-to"],["a","to"],["todo","all"],["lo","it"],["que","that"],["mandó","commanded"],["Amán,","Haman,"],["a","to"],["los","the"],["sátrapas","princes"],["del","of-the"],["rey,","king,"],["y","and"],["a","to"],["los","the"],["gobernadores","governors"],["que","that"],["estaban","they-were"],["sobre","upon"],["cada","each"],["provincia","province"],["y","and"],["a","to"],["los","the"],["príncipes","princes"],["de","of"],["cada","each"],["pueblo,","people,"],["a","to"],["cada","each"],["provincia","province"],["según","according-to"],["su","their"],["escritura","writing"],["y","and"],["a","to"],["cada","each"],["pueblo","people"],["según","according-to"],["su","their"],["lengua.","tongue."],["En","in"],["nombre","name"],["del","of-the"],["rey","king"],["Asuero","Ahasuerus"],["fue","was"],["escrito","written"],["y","and"],["sellado","sealed"],["con","with"],["el","the"],["anillo","ring"],["del","of-the"],["rey.","king."]]},
  {num:13,words:[["Y","and"],["fueron","they-were"],["enviadas","sent"],["cartas","letters"],["por medio de","by means of"],["mensajeros","messengers"],["a","to"],["todas","all"],["las","the"],["provincias","provinces"],["del","of-the"],["rey","king"],["para","for"],["destruir,","to-destroy,"],["matar","slay"],["y","and"],["exterminar","to-exterminate"],["a","to"],["todos","all"],["los","the"],["judíos,","Jews,"],["tanto","therefore"],["a","to"],["los","the"],["jóvenes","young-men"],["como","as"],["a","to"],["los","the"],["ancianos,","elders,"],["a","to"],["los","the"],["niños","children"],["pequeños","small"],["y","and"],["a","to"],["las","the"],["mujeres,","women,"],["en","in"],["un","a"],["solo","alone"],["día,","day,"],["en","in"],["el","the"],["día","day"],["trece","thirteen"],["del","of-the"],["mes","month"],["duodécimo,","twelfth,"],["que","that"],["es","is"],["el","the"],["mes","month"],["de","of"],["Adar,","Adar,"],["y","and"],["para","for"],["apoderarse","to-empower-himself"],["de","of"],["sus","his"],["bienes.","goods."]]},
  {num:14,words:[["La","the"],["copia","copy"],["del","of-the"],["escrito","written"],["que","that"],["se","itself"],["había","had"],["de","to"],["dar","give"],["por","for"],["decreto","decree"],["en","in"],["cada","each"],["provincia","province"],["fue","was"],["proclamada","proclaimed"],["a","to"],["todos","all"],["los","the"],["pueblos,","peoples,"],["a fin de que","so that"],["estuviesen","they"],["preparados","ready"],["para","for"],["aquel","that"],["día.","day."]]},
  {num:15,words:[["Y","and"],["salieron","they-went-out"],["los","the"],["mensajeros","messengers"],["deprisa","the"],["por","by"],["mandato","decree"],["del","of-the"],["rey,","king,"],["y","and"],["el","the"],["decreto","decree"],["fue","was"],["dado","given"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa.","Shushan."],["Y","and"],["el","the"],["rey","king"],["y","and"],["Amán","Haman"],["se","themselves"],["sentaron","sat"],["a","to"],["beber,","drink,"],["mientras","while"],["la","the"],["ciudad","city"],["de","of"],["Susa","Shushan"],["estaba","was"],["consternada.","perplexed."]]},
];
renderVerseSet(v3, 'est-ch3-verses');

var v4 = [
  {num:1,words:[["Cuando","when"],["supo","knew"],["Mardoqueo","Mordecai"],["todo","all"],["lo","it/him"],["que","that"],["se","himself"],["había","had"],["hecho,","done,"],["rasgó","rent"],["sus","his"],["vestidos,","garments,"],["y","and"],["se","himself"],["vistió","put"],["de","of"],["cilicio","sackcloth"],["y","and"],["de","of"],["ceniza,","ashes,"],["y","and"],["se","himself"],["fue","was"],["por","for"],["en","in"],["medio","midst"],["de","of"],["la","the"],["ciudad","city"],["clamando","loud"],["con","with"],["grande","great"],["y","and"],["amargo","bitter"],["clamor.","cry."]]},
  {num:2,words:[["Y", "and"], ["llegó", "arrived"], ["hasta", "until"], ["la", "the"], ["puerta", "gate"], ["del", "of-the"], ["rey,", "king,"], ["porque", "because"], ["no", "not"], ["era", "was"], ["lícito", "lawful"], ["entrar", "enter"], ["por","for"], ["la", "the"], ["puerta", "gate"], ["del", "of-the"], ["rey", "king"], ["vestido", "clothed"], ["de", "of"], ["cilicio.", "sackcloth."]]},
  {num:3,words:[["Y","and"],["en","in"],["cada","each"],["provincia","province"],["y","and"],["lugar","place"],["donde","where"],["el","the"],["mandato","decree"],["del","of-the"],["rey","king"],["y","and"],["su","his"],["decreto","decree"],["llegaban,","they-arrived,"],["había","had"],["entre","among"],["los","the"],["judíos","Jews"],["gran","great"],["luto,","mourning,"],["y","and"],["ayuno,","fasting,"],["y","and"],["llanto","weeping"],["y","and"],["lamentación;","lamentation;"],["cilicio","sackcloth"],["y","and"],["ceniza","ashes"],["eran","they-were"],["la","the"],["cama","bed"],["de","of"],["muchos.","many."]]},
  {num:4,words:[["Y","and"],["vinieron","they-came"],["las","the"],["doncellas","maidens"],["de","of"],["Ester","Esther"],["y","and"],["sus","his"],["eunucos","chamberlains"],["y","and"],["se","themselves"],["lo","it/him"],["dijeron;","they-said;"],["y","and"],["la","the"],["reina","queen"],["sintió","felt"],["gran","great"],["dolor,","pain,"],["y","and"],["envió","sent"],["vestidos","garments"],["para","for"],["hacer","do"],["vestir","eat"],["a","to"],["Mardoqueo","Mordecai"],["y","and"],["hacerle","to-make-him"],["quitar","take"],["el","the"],["cilicio","sackcloth"],["de","of"],["sobre","upon"],["él;","he;"],["pero","but"],["él","he"],["no","not"],["los","the"],["aceptó.","accepted."]]},
  {num:5,words:[["Entonces","then"],["Ester","Esther"],["llamó","called"],["a","to"],["Hatac,","Hatach,"],["uno","one"],["de","of"],["los","the"],["eunucos","chamberlains"],["del","of-the"],["rey","king"],["que","that"],["él","he"],["había","had"],["designado","appointed"],["para","for"],["el","the"],["servicio","service"],["de","of"],["ella,","she,"],["y","and"],["lo","it/him"],["mandó","commanded"],["a","to"],["Mardoqueo,","Mordecai,"],["con","with"],["orden","order"],["de","of"],["averiguar","to-find-out"],["qué","what"],["era","was"],["aquello","thing"],["y","and"],["el","the"],["porqué.","why."]]},
  {num:6,words:[["Salió,", "departed,"], ["pues,", "for,"], ["Hatac","Hatach"], ["adonde","where"], ["estaba", "was"], ["Mardoqueo,","Mordecai,"], ["a", "to"], ["la", "the"], ["plaza", "street"], ["de", "of"], ["la", "the"], ["ciudad", "city"], ["que", "that"], ["estaba", "was"], ["delante", "before"], ["de", "of"], ["la", "the"], ["puerta", "gate"], ["del", "of-the"], ["rey.", "king."]]},
  {num:7,words:[["Y","and"],["Mardoqueo","Mordecai"],["le","him"],["declaró","declared"],["todo","all"],["lo","him"],["que","that"],["le","him"],["había","had"],["acontecido,","happened,"],["y","and"],["le","him"],["dijo","said"],["de","of"],["la","the"],["plata","silver"],["que","that"],["Amán","Haman"],["había","had"],["dicho","said"],["que","that"],["pagaría","would-pay"],["a","to"],["los","the"],["tesoros","treasures"],["del","of-the"],["rey","king"],["a","to"],["cambio","change"],["de","of"],["la","the"],["destrucción","destruction"],["de","of"],["los","the"],["judíos.","Jews."]]},
  {num:8,words:[["Le","him"],["dio","gave"],["también","also"],["una","a"],["copia","copy"],["del","of-the"],["texto","text"],["del","of-the"],["decreto","decree"],["que","that"],["había","had"],["sido","been"],["promulgado","given"],["en","in"],["Susa","Shushan"],["para que","that"],["fuesen","they-might"],["destruidos,","destroyed,"],["a fin de que","so that"],["la","the"],["mostrara","might-show"],["a","to"],["Ester,","Esther,"],["y","and"],["se","itself"],["lo","it/him"],["declarase,","might-declare,"],["y","and"],["le","him"],["encargara","go"],["que","that"],["fuese","might-be"],["ante","before"],["el","the"],["rey","king"],["a","to"],["suplicarle","to-beg-him"],["y","and"],["a","to"],["interceder","to"],["delante","before"],["de","of"],["él","he"],["por","for"],["su","her"],["pueblo.","people."]]},
  {num:9,words:[["Y","and"],["regresó","returned"],["Hatac","Hatach"],["y","and"],["contó","told"],["a","to"],["Ester","Esther"],["las","the"],["palabras","words"],["de","of"],["Mardoqueo.","Mordecai."]]},
  {num:10,words:[["Entonces","then"],["Ester","Esther"],["habló","spoke"],["con","with"],["Hatac","Hatach"],["y","and"],["le","him"],["mandó","commanded"],["decir","to-say"],["a","to"],["Mardoqueo:","Mordecai:"]]},
  {num:11,words:[["Todos","all"],["los","the"],["servidores","servants"],["del","of-the"],["rey","king"],["y","and"],["el","the"],["pueblo","people"],["de","of"],["las","the"],["provincias","provinces"],["del","of-the"],["rey","king"],["saben","they-know"],["que","that"],["para","for"],["cualquier","any"],["hombre","man"],["o","or"],["mujer","woman"],["que","that"],["entre","among"],["al","to-the"],["patio","court"],["interior","inner"],["para","for"],["ver","see"],["al","to-the"],["rey,","king,"],["sin","without"],["ser","be"],["llamado,","called,"],["hay","there-is"],["una","a"],["sola","alone"],["ley:","law:"],["Ha","has"],["de","to"],["morir,","die,"],["salvo","I-except"],["aquel","that"],["a","to"],["quien","who"],["el","the"],["rey","king"],["extienda","forth"],["el","the"],["cetro","sceptre"],["de","of"],["oro;","gold;"],["ese","that"],["vivirá,","live,"],["y","and"],["yo","I"],["no","not"],["he","I-have"],["sido","been"],["llamada","called"],["para","for"],["entrar","enter"],["a","to"],["ver","see"],["al","to-the"],["rey","king"],["estos","these"],["treinta","thirty"],["días.","days."]]},
  {num:12,words:[["Y","and"],["dijeron","they-said"],["a","to"],["Mardoqueo","Mordecai"],["las","the"],["palabras","words"],["de","of"],["Ester.","Esther."]]},
  {num:13,words:[["Entonces","then"],["dijo","said"],["Mardoqueo","Mordecai"],["que","that"],["respondiesen","they-might-answer"],["a","to"],["Ester:","Esther:"],["No","not"],["pienses","you-may-think"],["en","in"],["tu","your"],["alma","soul"],["que,","that,"],["estando","being"],["en","in"],["la","the"],["casa","house"],["del","of-the"],["rey,","king,"],["solo","alone"],["tú","you"],["escaparás","will-escape"],["entre","among"],["todos","all"],["los","the"],["judíos.","Jews."]]},
  {num:14,words:[["Porque","because"],["si","if"],["permaneces","you-remain"],["callada","you-hold"],["en","in"],["este","this"],["tiempo,","time,"],["el","the"],["alivio","relief"],["y","and"],["la","the"],["liberación","deliverance"],["de","of"],["los","the"],["judíos","Jews"],["surgirán","they-will-arise"],["de","of"],["otra","other"],["parte;","part;"],["pero","but"],["tú","you"],["y","and"],["la","the"],["casa","house"],["de","of"],["tu","your"],["padre","father"],["pereceréis.","you-will-perish."],["¿Y","and"],["quién","who"],["sabe","knows"],["si","if"],["para","for"],["esta","this"],["hora","hour"],["tú","you"],["has","have"],["llegado","come"],["al","to-the"],["reino?","kingdom?"]]},
  {num:15,words:[["Y","and"],["Ester","Esther"],["dijo","said"],["que","that"],["respondiesen","they-might-answer"],["a","to"],["Mardoqueo:","Mordecai:"]]},
  {num:16,words:[["Ve","you-sees"],["y","and"],["reúne","together"],["a","to"],["todos","all"],["los","the"],["judíos","Jews"],["que","that"],["se","themselves"],["hallan","find"],["en","in"],["Susa,","Shushan,"],["y","and"],["ayunad","you-fast"],["por","for"],["mí","me"],["y","and"],["no","not"],["comáis","you-may-eat"],["ni","nor"],["bebáis","you-may-drink"],["en","in"],["tres","three"],["días,","days,"],["ni","nor"],["de","of"],["noche","night"],["ni","nor"],["de","of"],["día.","day."],["Yo","I"],["también","also"],["ayunaré","I-fast"],["con","with"],["mis","my"],["doncellas","maidens"],["igualmente,","likewise,"],["y","and"],["así","thus"],["entraré","I-will-enter"],["a","to"],["ver","see"],["al","to-the"],["rey,","king,"],["aunque","although"],["no","not"],["sea","be"],["conforme","according-to"],["a","to"],["la","the"],["ley;","law;"],["y","and"],["si","if"],["perezco,","I-perish,"],["que","that"],["perezca.","may-perish."]]},
  {num:17,words:[["Entonces","then"],["Mardoqueo","Mordecai"],["se","himself"],["fue","went"],["e","and"],["hizo","did"],["conforme","according-to"],["a","to"],["todo","all"],["lo","him"],["que","that"],["le","him"],["había","had"],["mandado","commanded"],["Ester.","Esther."]]},
];
renderVerseSet(v4, 'est-ch4-verses');

var v5 = [
  {num:1,words:[["Y","and"],["aconteció","it-came-to-pass"],["que","that"],["al","to-the"],["tercer","third"],["día","day"],["se","itself"],["vistió","put"],["Ester","Esther"],["con","with"],["su","his"],["vestidura","garment"],["real","royal"],["y","and"],["entró","entered"],["en","in"],["el","the"],["patio","court"],["interior","inner"],["del","of-the"],["palacio","palace"],["del","of-the"],["rey,","king,"],["frente","forehead"],["a","to"],["los","the"],["aposentos","chambers"],["del","of-the"],["rey;","king;"],["y","and"],["estaba","was"],["el","the"],["rey","king"],["sentado","sitting"],["en","in"],["su","his"],["trono","throne"],["real","royal"],["en","in"],["la","the"],["sala","room"],["real,","royal,"],["frente","forehead"],["a","to"],["la","the"],["entrada","entrance"],["del","of-the"],["palacio.","palace."]]},
  {num:2,words:[["Y","and"],["sucedió","it-came-to-pass"],["que,","that,"],["cuando","when"],["vio","saw"],["a","to"],["la","the"],["reina","queen"],["Ester","Esther"],["que","that"],["estaba","was"],["en","in"],["el","the"],["patio,","court,"],["ella","she"],["halló","found"],["gracia","grace"],["ante","before"],["sus","his"],["ojos;","eyes;"],["y","and"],["el","the"],["rey","king"],["extendió","stretched"],["hacia","toward"],["Ester","Esther"],["el","the"],["cetro","sceptre"],["de","of"],["oro","gold"],["que","that"],["tenía","had"],["en","in"],["la","the"],["mano.","hand."],["Entonces","then"],["se","himself"],["acercó","drew"],["Ester","Esther"],["y","and"],["tocó","touched"],["la","the"],["punta","in"],["del","of-the"],["cetro.","sceptre."]]},
  {num:3,words:[["Y","and"],["dijo","said"],["el","the"],["rey:","king:"],["¿Qué","what"],["deseas,","you-desire,"],["reina","queen"],["Ester?","Esther?"],["¿Y","and"],["cuál","which"],["es","is"],["tu","your"],["petición?","petition?"],["Hasta","until"],["la","the"],["mitad","half"],["del","of-the"],["reino","kingdom"],["se","itself"],["te","you"],["dará.","shall-give."]]},
  {num:4,words:[["Y", "and"], ["Ester","Esther"], ["dijo:", "said:"], ["Si", "if"], ["le","him"], ["parece","seems"], ["bien", "well"], ["al", "to-the"], ["rey,", "king,"], ["venga", "let-come"], ["hoy", "today"], ["el", "the"], ["rey", "king"], ["con", "with"], ["Amán","Haman"], ["al", "to-the"], ["banquete", "banquet"], ["que", "that"], ["le","him"], ["he", "I-have"], ["preparado.", "prepared."]]},
  {num:5,words:[["Y","and"],["respondió","answered"],["el","the"],["rey:","king:"],["Daos","cause"],["prisa,","haste,"],["llamad","you-call"],["a","to"],["Amán","Haman"],["para que","that"],["hagamos","we-may-make"],["lo","it/him"],["que","that"],["Ester","Esther"],["ha","has"],["dicho.","said."],["Fueron,","they-were,"],["pues,","for,"],["el","the"],["rey","king"],["y","and"],["Amán","Haman"],["al","to-the"],["banquete","banquet"],["que","that"],["Ester","Esther"],["dispuso.","prepared."]]},
  {num:6,words:[["Y","and"],["dijo","said"],["el","the"],["rey","king"],["a","to"],["Ester","Esther"],["en","in"],["el","the"],["banquete,","banquet,"],["mientras","while"],["bebían","they-drank"],["vino:","wine:"],["¿Cuál","which"],["es","is"],["tu","your"],["petición?","petition?"],["Pues","for"],["te","you"],["será","shall-be"],["otorgada.","granted."],["¿Cuál","which"],["es","is"],["tu","your"],["deseo?","desire?"],["Aunque","although"],["sea","be"],["la","the"],["mitad","half"],["del","of-the"],["reino,","kingdom,"],["te","you"],["será","shall-be"],["concedido.","granted."]]},
  {num:7,words:[["Entonces", "then"], ["respondió", "answered"], ["Ester","Esther"], ["y", "and"], ["dijo:", "said:"], ["Mi", "my"], ["petición", "petition"], ["y", "and"], ["mi", "my"], ["deseo", "desire"], ["es", "is"], ["este:", "this:"]]},
  {num:8,words:[["Si","if"],["he","I-have"],["hallado","found"],["gracia","grace"],["ante","before"],["los","the"],["ojos","eyes"],["del","of-the"],["rey,","king,"],["y","and"],["si","if"],["le","my"],["place","the"],["al","to-the"],["rey","king"],["otorgar","to-grant"],["mi","my"],["petición","petition"],["y","and"],["conceder","to-grant"],["mi","my"],["deseo,","desire,"],["que","that"],["venga","let-come"],["el","the"],["rey","king"],["con","with"],["Amán","Haman"],["al","to-the"],["banquete","banquet"],["que","that"],["les","them"],["dispondré;","I-will-arrange;"],["y","and"],["mañana","morning"],["haré","I will make"],["conforme","according-to"],["a","to"],["la","the"],["palabra","word"],["del","of-the"],["rey.","king."]]},
  {num:9,words:[["Y","and"],["salió","departed"],["Amán","Haman"],["aquel","that"],["día","day"],["contento","day"],["y","and"],["alegre","joyful"],["de","of"],["corazón;","heart;"],["pero","but"],["cuando","when"],["vio","saw"],["a","to"],["Mardoqueo","Mordecai"],["a","to"],["la","the"],["puerta","gate"],["del","of-the"],["rey,","king,"],["que","that"],["no","not"],["se","himself"],["levantaba","lifted"],["ni","nor"],["temblaba","was-trembleing"],["delante","before"],["de","of"],["él,","he,"],["se","himself"],["llenó","filled"],["de","of"],["ira","anger"],["contra","against"],["Mardoqueo.","Mordecai."]]},
  {num:10,words:[["Pero","but"],["se","himself"],["refrenó","refrained"],["Amán,","Haman,"],["y","and"],["cuando","when"],["llegó","arrived"],["a","to"],["su","his"],["casa,","house,"],["mandó","commanded"],["llamar","call"],["e","and"],["hizo","made/did"],["venir","to-come"],["a","to"],["sus","his"],["amigos","friends"],["y","and"],["a","to"],["Zeres,","Zeresh,"],["su","his"],["esposa.","wife."]]},
  {num:11,words:[["Y","and"],["les","them"],["refirió","referred"],["Amán","Haman"],["la","the"],["gloria","glory"],["de","of"],["sus","his"],["riquezas,","riches,"],["y","and"],["la","the"],["multitud","multitude"],["de","of"],["sus","his"],["hijos","children"],["y","and"],["todas","all"],["las","the"],["cosas","things"],["con","with"],["las","the"],["que","that"],["el","the"],["rey","king"],["le","him"],["había","had"],["favorecido","favored"],["y","and"],["ascendido","ascended"],["de","of"],["posición","for"],["y","and"],["cómo","how"],["le","him"],["había","had"],["honrado","and"],["elevándole","raising-him"],["sobre","upon"],["los","the"],["príncipes","princes"],["y","and"],["servidores","servants"],["del","of-the"],["rey.","king."]]},
  {num:12,words:[["Y","and"],["añadió","said"],["Amán:","Haman:"],["También","also"],["la","the"],["reina","queen"],["Ester","Esther"],["a","to"],["ninguno","none"],["hizo","did"],["venir","to-come"],["con","with"],["el","the"],["rey","king"],["al","to-the"],["banquete","banquet"],["que","that"],["ella","she"],["dispuso,","prepared,"],["sino","but"],["a","to"],["mí;","me;"],["y","and"],["también","also"],["para","for"],["mañana","morning"],["estoy","I-am"],["convidado","invited"],["por","for"],["ella","she"],["con","with"],["el","the"],["rey.","king."]]},
  {num:13,words:[["Pero","but"],["todo","all"],["esto","this"],["de","of"],["nada","nothing"],["me","me"],["sirve","nothing"],["cada","each"],["vez","time"],["que","that"],["veo","I-see"],["al","to-the"],["judío","Jew"],["Mardoqueo","Mordecai"],["sentado","sitting"],["a","to"],["la","the"],["puerta","gate"],["del","of-the"],["rey.","king."]]},
  {num:14,words:[["Y","and"],["Zeres,","Zeresh,"],["su","his"],["esposa,","wife,"],["y","and"],["todos","all"],["sus","his"],["amigos","friends"],["le","him"],["dijeron:","they-said:"],["Hagan","they-do"],["una","a"],["horca","gallows"],["de","of"],["cincuenta","fifty"],["codos","cubits"],["de","of"],["altura,","height,"],["y","and"],["mañana","morning"],["di","I-give/I-gave"],["al","to-the"],["rey","king"],["que","that"],["cuelguen","they-may-hang"],["a","to"],["Mardoqueo","Mordecai"],["en","in"],["ella;","she;"],["y","and"],["entra","enter"],["alegre","merry"],["con","with"],["el","the"],["rey","king"],["al","to-the"],["banquete.","banquet."],["Y","and"],["esto","this"],["agradó","pleased"],["a","to"],["los","the"],["ojos","eyes"],["de","of"],["Amán,","Haman,"],["e","and"],["hizo","made"],["preparar","to-prepare"],["la","the"],["horca.","gallows."]]},
];
renderVerseSet(v5, 'est-ch5-verses');

var v6 = [
  {num:1,words:[["Aquella","that"],["misma","same"],["noche","night"],["se","himself"],["le","him"],["fue","was"],["el","the"],["sueño","dream"],["al","to-the"],["rey,","king,"],["y","and"],["mandó","commanded"],["que","that"],["le","him"],["trajesen","they-might-bring"],["el","the"],["libro","book"],["de","of"],["las","the"],["memorias","remembrances"],["de","of"],["las","the"],["crónicas","chronicles"],["y","and"],["las","the"],["leyeron","read"],["delante","before"],["del","of-the"],["rey.","king."]]},
  {num:2,words:[["Entonces","then"],["se","itself"],["halló","found"],["escrito","written"],["que","that"],["Mardoqueo","Mordecai"],["había","had"],["denunciado","denounced"],["a","to"],["Bigtán","of"],["y","and"],["a","to"],["Teres,","Teresh,"],["dos","two"],["eunucos","chamberlains"],["del","of-the"],["rey,","king,"],["de","of"],["la","the"],["guardia","nebuzaradan"],["de","of"],["la","the"],["puerta,","door,"],["que","that"],["habían","they-had"],["tramado","lay"],["echar","cast"],["mano","hand"],["al","to-the"],["rey","king"],["Asuero.","Ahasuerus."]]},
  {num:3,words:[["Entonces","then"],["dijo","said"],["el","the"],["rey:","king:"],["¿Qué","what"],["honor","honour"],["o","or"],["que","that"],["distinción","distinction"],["se","himself"],["hizo","made/did"],["a","to"],["Mardoqueo","Mordecai"],["por","for"],["esto?","this?"],["Y","and"],["respondieron","they-answered"],["los","the"],["servidores","servants"],["del","of-the"],["rey,","king,"],["sus","his"],["oficiales:","officer:"],["Nada","nothing"],["se","himself"],["ha","has"],["hecho","done"],["por","for"],["él.","he."]]},
  {num:4,words:[["Entonces","then"],["dijo","said"],["el","the"],["rey:","king:"],["¿Quién","who"],["está","is"],["en","in"],["el","the"],["patio?","court?"],["Y","and"],["Amán","Haman"],["había","had"],["venido","come"],["al","to-the"],["patio","court"],["exterior","outward"],["de","of"],["la","the"],["casa","house"],["del","of-the"],["rey","king"],["para","for"],["pedir","to-ask"],["al","to-the"],["rey","king"],["que","that"],["hiciese","might-make"],["colgar","hang"],["a","to"],["Mardoqueo","Mordecai"],["en","in"],["la","the"],["horca","gallows"],["que","that"],["él","he"],["le","him"],["tenía","had"],["preparada.","prepared."]]},
  {num:5,words:[["Y","and"],["los","the"],["servidores","servants"],["del","of-the"],["rey","king"],["le","him"],["respondieron:","they-answered:"],["He aquí,","behold,"],["Amán","Haman"],["está","is"],["en","in"],["el","the"],["patio.","court."],["Y","and"],["el","the"],["rey","king"],["dijo:","said:"],["Que","that"],["entre.","among."]]},
  {num:6,words:[["Entró,","entered,"],["pues,","for,"],["Amán,","Haman,"],["y","and"],["el","the"],["rey","king"],["le","him"],["preguntó:","asked:"],["¿Qué","what"],["se","himself"],["hará","shall-make"],["al","to-the"],["hombre","man"],["a","to"],["quien","who"],["el","the"],["rey","king"],["desea","desires"],["honrar?","to-honor?"],["Y","and"],["dijo","said"],["Amán","Haman"],["en","in"],["su","his"],["corazón:","heart:"],["¿A","to"],["quién","who"],["deseará","will-desire"],["el","the"],["rey","king"],["honrar","to-honor"],["más","more"],["que","that"],["a","to"],["mí?","me?"]]},
  {num:7,words:[["Y","and"],["respondió","answered"],["Amán","Haman"],["al","to-the"],["rey:","king:"],["Para","for"],["el","the"],["hombre","man"],["a","to"],["quien","who"],["el","the"],["rey","king"],["desea","desires"],["honrar,","to-honor,"]]},
  {num:8,words:[["traigan","they-may-bring"],["la","the"],["vestidura","garment"],["real","royal"],["con","with"],["la","the"],["que","that"],["el","the"],["rey","king"],["se","himself"],["viste,","you-saw,"],["y","and"],["el","the"],["caballo","horse"],["en","in"],["el","the"],["que","that"],["el","the"],["rey","king"],["cabalga","rides"],["y","and"],["la","the"],["corona","crown"],["real","royal"],["que","that"],["está","is"],["puesta","set"],["sobre","upon"],["su","his"],["cabeza;","head;"]]},
  {num:9,words:[["y","and"],["entreguen","they-may-deliver"],["la","the"],["vestidura","garment"],["y","and"],["el","the"],["caballo","horse"],["en","in"],["manos","hands"],["de","of"],["uno","one"],["de","of"],["los","the"],["príncipes","princes"],["más","more"],["nobles","nobles"],["del","of-the"],["rey,","king,"],["y","and"],["vistan","they-may-wear"],["al","to-the"],["hombre","man"],["a","to"],["quien","who"],["el","the"],["rey","king"],["desea","desires"],["honrar,","to-honor,"],["y","and"],["llévenlo","them-it"],["en","in"],["el","the"],["caballo","horse"],["por","for"],["la","the"],["plaza","street"],["de","of"],["la","the"],["ciudad","city"],["y","and"],["pregonen","they-may-proclaim"],["delante","before"],["de","of"],["él:","he:"],["Así","thus"],["se","himself"],["hace","makes"],["al","to-the"],["hombre","man"],["a","to"],["quien","who"],["el","the"],["rey","king"],["desea","desires"],["honrar.","to-honor."]]},
  {num:10,words:[["Entonces","then"],["el","the"],["rey","king"],["dijo","said"],["a","to"],["Amán:","Haman:"],["Date","gives-you"],["prisa,","haste,"],["toma","take"],["la","the"],["vestidura","garment"],["y","and"],["el","the"],["caballo,","horse,"],["como","as"],["tú","you"],["has","have"],["dicho,","said,"],["y","and"],["hazlo","do"],["así","thus"],["con","with"],["el","the"],["judío","Jew"],["Mardoqueo,","Mordecai,"],["quien","who"],["se","himself"],["sienta","sits"],["a","to"],["la","the"],["puerta","gate"],["del","of-the"],["rey;","king;"],["no","not"],["omitas","nothing"],["nada","nothing"],["de","of"],["todo","all"],["lo","it/him"],["que","that"],["has","you-have"],["dicho.","said."]]},
  {num:11,words:[["Y","and"],["Amán","Haman"],["tomó","took"],["la","the"],["vestidura","garment"],["y","and"],["el","the"],["caballo,","horse,"],["y","and"],["vistió","put"],["a","to"],["Mardoqueo,","Mordecai,"],["y","and"],["lo","it/him"],["llevó","carried"],["en","in"],["el","the"],["caballo","horse"],["por","for"],["la","the"],["plaza","street"],["de","of"],["la","the"],["ciudad","city"],["e","and"],["hizo","made/did"],["pregonar","to-proclaim"],["delante","before"],["de","of"],["él:","he:"],["Así","thus"],["se","himself"],["hace","makes"],["al","to-the"],["hombre","man"],["a","to"],["quien","who"],["el","the"],["rey","king"],["desea","desires"],["honrar.","to-honor."]]},
  {num:12,words:[["Después","after"],["de","of"],["esto","this"],["Mardoqueo","Mordecai"],["volvió","returned"],["a","to"],["la","the"],["puerta","gate"],["del","of-the"],["rey,","king,"],["y","and"],["Amán","Haman"],["se","himself"],["apresuró","hurried"],["a","to"],["volver","return"],["a","to"],["su","his"],["casa,","house,"],["apesadumbrado","distressed"],["y","and"],["con","with"],["la","the"],["cabeza","head"],["cubierta.","cover."]]},
  {num:13,words:[["Y","and"],["contó","told"],["Amán","Haman"],["a","to"],["Zeres,","Zeresh,"],["su","his"],["esposa,","wife,"],["y","and"],["a","to"],["todos","all"],["sus","his"],["amigos","friends"],["todo","all"],["lo","him"],["que","that"],["le","him"],["había","had"],["acontecido;","happened;"],["entonces","then"],["le","him"],["dijeron","they-said"],["sus","his"],["sabios","wise"],["y","and"],["Zeres,","Zeresh,"],["su","his"],["esposa:","wife:"],["Si","if"],["Mardoqueo,","Mordecai,"],["delante","before"],["de","of"],["quien","who"],["has","you-have"],["comenzado","begun"],["a","to"],["caer,","fall,"],["es","is"],["de","of"],["la","the"],["descendencia","seed"],["de","of"],["los","the"],["judíos,","Jews,"],["no","not"],["lo","him"],["vencerás,","you-shall-to,"],["sino que","but"],["ciertamente","surely"],["caerás","you-will-fall"],["delante","before"],["de","of"],["él.","he."]]},
  {num:14,words:[["Aún","yet"],["estaban","were"],["ellos","they"],["hablando","speaking"],["con","with"],["él","he"],["cuando","when"],["los","the"],["eunucos","chamberlains"],["del","of-the"],["rey","king"],["llegaron","they-arrived"],["y","and"],["se","themselves"],["apresuraron","hasted"],["a","to"],["llevar","carry"],["a","to"],["Amán","Haman"],["al","to-the"],["banquete","banquet"],["que","that"],["Ester","Esther"],["había","had"],["preparado.","prepared."]]},
];
renderVerseSet(v6, 'est-ch6-verses');

var v7 = [
  {num:1,words:[["Fue,","was,"],["pues,","for,"],["el","the"],["rey","king"],["con","with"],["Amán","Haman"],["al","to-the"],["banquete","banquet"],["de","of"],["la","the"],["reina","queen"],["Ester.","Esther."]]},
  {num:2,words:[["También","also"],["en","in"],["el","the"],["segundo","second"],["día,","day,"],["dijo","said"],["el","the"],["rey","king"],["a","to"],["Ester,","Esther,"],["mientras","while"],["bebían","they-drank"],["vino:","wine:"],["¿Cuál","which"],["es","is"],["tu","your"],["petición,","petition,"],["reina","queen"],["Ester?","Esther?"],["Y","and"],["se","itself"],["te","you"],["concederá.","will-grant."],["¿Cuál","which"],["es","is"],["tu","your"],["deseo?","desire?"],["Aunque","although"],["sea","be"],["la","the"],["mitad","half"],["del","of-the"],["reino,","kingdom,"],["te","you"],["será","shall-be"],["concedido.","granted."]]},
  {num:3,words:[["Entonces","then"],["la","the"],["reina","queen"],["Ester","Esther"],["respondió","answered"],["y","and"],["dijo:","said:"],["Oh","oh"],["rey,","king,"],["si","if"],["he","I-have"],["hallado","found"],["gracia","grace"],["ante","before"],["tus","your"],["ojos,","eyes,"],["y","and"],["si","if"],["le","my"],["place","the"],["al","to-the"],["rey,","king,"],["mi","my"],["petición","petition"],["es","is"],["que","that"],["se","itself"],["me","me"],["conceda","grant"],["la","the"],["vida,","life,"],["y","and"],["mi","my"],["deseo,","desire,"],["la","the"],["vida","life"],["de","of"],["mi","my"],["pueblo.","people."]]},
  {num:4,words:[["Porque","because"],["hemos","we-have"],["sido","been"],["vendidos,","sold,"],["yo","I"],["y","and"],["mi","my"],["pueblo,","people,"],["para","for"],["ser","be"],["destruidos,","destroyed,"],["para","for"],["ser","be"],["muertos","dead"],["y","and"],["exterminados.","perish."],["Y","and"],["si","if"],["para","for"],["siervos","servants"],["y","and"],["siervas","he"],["hubiéramos","we-might-have"],["sido","been"],["vendidos,","sold,"],["me","me"],["habría","would-have"],["callado,","held,"],["porque","because"],["tal","such"],["adversidad","although"],["no","not"],["sería","should-be"],["suficiente","sufficient"],["para","for"],["inquietar","to-disturb"],["al","to-the"],["rey.","king."]]},
  {num:5,words:[["Y","and"],["respondió","answered"],["el","the"],["rey","king"],["Asuero","Ahasuerus"],["y","and"],["dijo","said"],["a","to"],["la","the"],["reina","queen"],["Ester:","Esther:"],["¿Quién","who"],["es,","is,"],["y","and"],["dónde","where"],["está","is"],["aquel","that"],["que","that"],["pretende","durst"],["en","in"],["su","his"],["corazón","heart"],["hacer","do"],["tal","such"],["cosa?","thing?"]]},
  {num:6,words:[["Y","and"],["Ester","Esther"],["dijo:","said:"],["El","the"],["enemigo","enemy"],["y","and"],["adversario","adversary"],["es","is"],["este","this"],["malvado","wicked"],["Amán.","Haman."],["Entonces","then"],["Amán","Haman"],["se","himself"],["llenó","filled"],["de","of"],["miedo","afraid"],["delante","before"],["del","of-the"],["rey","king"],["y","and"],["de","of"],["la","the"],["reina.","queen."]]},
  {num:7,words:[["Y","and"],["se","himself"],["levantó","arose"],["el","the"],["rey","king"],["del","of-the"],["banquete","banquet"],["del","of-the"],["vino","wine"],["en","in"],["su","his"],["ira","wrath"],["y","and"],["se","himself"],["fue","was"],["al","to-the"],["huerto","garden"],["del","of-the"],["palacio;","palace;"],["y","and"],["se","himself"],["quedó","remained"],["Amán","Haman"],["para","for"],["suplicar","to-beg"],["a","to"],["la","the"],["reina","queen"],["Ester","Esther"],["por","for"],["su","his"],["vida,","life,"],["porque","because"],["vio","saw"],["que","that"],["el","the"],["rey","king"],["estaba","was"],["resuelto","solved"],["a","to"],["hacerle","to-make-him"],["mal.","evil."]]},
  {num:8,words:[["Volvió","returned"],["después","after"],["el","the"],["rey","king"],["del","of-the"],["huerto","garden"],["del","of-the"],["palacio","palace"],["al","to-the"],["lugar","place"],["del","of-the"],["banquete,","banquet,"],["y","and"],["Amán","Haman"],["se","himself"],["había","had"],["dejado","left"],["caer","to-fall"],["sobre","upon"],["el","the"],["lecho","bed"],["en que","that"],["estaba","was"],["Ester.","Esther."],["Entonces","then"],["dijo","said"],["el","the"],["rey:","king:"],["¿Forzará","will-force"],["a","to"],["la","the"],["reina","queen"],["también,","also,"],["estando","being"],["yo","I"],["en","in"],["casa?","house?"],["Cuando","when"],["esta","this"],["palabra","word"],["salió","departed"],["de","of"],["la","the"],["boca","mouth"],["del","of-the"],["rey,","king,"],["le","him"],["cubrieron","they-covered"],["el","the"],["rostro","face"],["a","to"],["Amán.","Haman."]]},
  {num:9,words:[["Y","and"],["Harbona,","harbonah,"],["uno","one"],["de","of"],["los","the"],["eunucos","chamberlains"],["del","of-the"],["rey,","king,"],["dijo:","said:"],["También","also"],["he aquí,","behold,"],["la","the"],["horca","gallows"],["de","of"],["cincuenta","fifty"],["codos","cubits"],["de","of"],["altura","height"],["que","that"],["Amán","Haman"],["hizo","made"],["para","for"],["Mardoqueo,","Mordecai,"],["quien","who"],["había","had"],["hablado","spoken"],["para","for"],["bien","well"],["del","of-the"],["rey,","king,"],["está","is"],["en","in"],["casa","house"],["de","of"],["Amán.","Haman."],["Entonces","then"],["el","the"],["rey","king"],["dijo:","said:"],["Colgadlo","hang"],["en","in"],["ella.","she."]]},
  {num:10,words:[["Así","thus"],["colgaron","they-hung"],["a","to"],["Amán","Haman"],["en","in"],["la","the"],["horca","gallows"],["que","that"],["él","he"],["había","had"],["hecho","done/made"],["preparar","to-prepare"],["para","for"],["Mardoqueo;","Mordecai;"],["y","and"],["se","himself"],["apaciguó","appeased"],["la","the"],["ira","wrath"],["del","of-the"],["rey.","king."]]},
];
renderVerseSet(v7, 'est-ch7-verses');

var v8 = [
  {num:1,words:[["El","the"],["mismo","same"],["día","day"],["dio","gave"],["el","the"],["rey","king"],["Asuero","Ahasuerus"],["a","to"],["la","the"],["reina","queen"],["Ester","Esther"],["la","the"],["casa","house"],["de","of"],["Amán,","Haman,"],["enemigo","enemy"],["de","of"],["los","the"],["judíos;","Jews;"],["y","and"],["Mardoqueo","Mordecai"],["fue","was"],["ante","before"],["el","the"],["rey,","king,"],["porque","because"],["Ester","Esther"],["le","her"],["había","had"],["dicho","said"],["lo","it/him"],["que","that"],["él","he"],["era","was"],["para","for"],["ella.","she."]]},
  {num:2,words:[["Y","and"],["se","himself"],["quitó","removed"],["el","the"],["rey","king"],["su","his"],["anillo","ring"],["que","that"],["había","had"],["vuelto","returned"],["a","to"],["tomar","take"],["de","of"],["Amán","Haman"],["y","and"],["se","himself"],["lo","it"],["dio","gave"],["a","to"],["Mardoqueo.","Mordecai."],["Y","and"],["Ester","Esther"],["puso","placed"],["a","to"],["Mardoqueo","Mordecai"],["a","to"],["cargo","charge"],["de","of"],["la","the"],["casa","house"],["de","of"],["Amán.","Haman."]]},
  {num:3,words:[["Y","and"],["volvió","returned"],["Ester","Esther"],["a","to"],["hablar","speak"],["delante","before"],["del","of-the"],["rey,","king,"],["y","and"],["cayó","fell"],["a","to"],["sus","his"],["pies,","feet,"],["rogándole","pleading-him"],["con","with"],["lágrimas","tears"],["que","that"],["anulara","put"],["la","the"],["maldad","wickedness"],["de","of"],["Amán,","Haman,"],["el","the"],["agagueo,","the,"],["y","and"],["el","the"],["plan","plan"],["que","that"],["había","had"],["tramado","plotted"],["contra","against"],["los","the"],["judíos.","Jews."]]},
  {num:4,words:[["Entonces","then"],["el","the"],["rey","king"],["extendió","stretched"],["a","to"],["Ester","Esther"],["el","the"],["cetro","sceptre"],["de","of"],["oro,","gold,"],["y","and"],["Ester","Esther"],["se","itself"],["levantó","arose"],["y","and"],["se","itself"],["puso","placed"],["de","of"],["pie","foot"],["delante","before"],["del","of-the"],["rey","king"]]},
  {num:5,words:[["y","and"],["dijo:","said:"],["Si","if"],["le","his"],["place","the"],["al","to-the"],["rey,","king,"],["y","and"],["si","if"],["he","I-have"],["hallado","found"],["gracia","grace"],["ante","before"],["él,","he,"],["y","and"],["si","if"],["el","the"],["asunto","matter"],["es","is"],["justo","righteous"],["delante","before"],["del","of-the"],["rey","king"],["y","and"],["soy","I-am"],["agradable","acceptable"],["ante","before"],["sus","his"],["ojos,","eyes,"],["que","that"],["se","itself"],["escriba","scribe"],["para","for"],["revocar","written"],["las","the"],["cartas","letters"],["del","of-the"],["plan","plan"],["maquinado","devised"],["por","by"],["Amán","Haman"],["hijo","son"],["de","of"],["Hamedata,","Hammedatha,"],["el","the"],["agagueo,","the,"],["que","that"],["escribió","wrote"],["para","for"],["destruir","to-destroy"],["a","to"],["los","the"],["judíos","Jews"],["que","that"],["están","they-are"],["en","in"],["todas","all"],["las","the"],["provincias","provinces"],["del","of-the"],["rey.","king."]]},
  {num:6,words:[["Porque,", "because,"], ["¿cómo", "how"], ["podría", "could"], ["yo", "I"], ["soportar", "bear"], ["y", "and"], ["ver", "see"], ["el", "the"], ["mal", "evil"], ["que", "that"], ["alcanzaría", "would-to"], ["a", "to"], ["mi", "my"], ["pueblo?", "people?"], ["¿Cómo", "how"], ["podría", "could"], ["yo", "I"], ["soportar", "bear"], ["y", "and"], ["ver", "see"], ["la", "the"], ["destrucción", "destruction"], ["de", "of"], ["mi", "my"], ["gente?", "people?"]]},
  {num:7,words:[["Y","and"],["respondió","answered"],["el","the"],["rey","king"],["Asuero","Ahasuerus"],["a","to"],["la","the"],["reina","queen"],["Ester","Esther"],["y","and"],["al","to-the"],["judío","Jew"],["Mardoqueo:","Mordecai:"],["He aquí,","behold,"],["yo","I"],["he","have"],["dado","given"],["a","to"],["Ester","Esther"],["la","the"],["casa","house"],["de","of"],["Amán,","Haman,"],["y","and"],["a","to"],["él","he"],["le","him"],["han","they-have"],["colgado","hanged"],["en","in"],["la","the"],["horca,","gallows,"],["por cuanto","because"],["extendió","stretched"],["su","his"],["mano","hand"],["contra","against"],["los","the"],["judíos.","Jews."]]},
  {num:8,words:[["Escribid,","you-write,"],["pues,","for,"],["vosotros","you"],["a","to"],["los","the"],["judíos","Jews"],["como","as"],["bien","well"],["os","you"],["parezca,","seems,"],["en","in"],["nombre","name"],["del","of-the"],["rey,","king,"],["y","and"],["selladlo","seal"],["con","with"],["el","the"],["anillo","ring"],["del","of-the"],["rey;","king;"],["porque","because"],["el","the"],["decreto","decree"],["que","that"],["se","itself"],["escribe","write"],["en","in"],["nombre","name"],["del","of-the"],["rey","king"],["y","and"],["se","itself"],["sella","seal"],["con","with"],["el","the"],["anillo","ring"],["del","of-the"],["rey","king"],["no puede","cannot"],["ser","be"],["revocado.","reverse."]]},
  {num:9,words:[["Entonces","then"],["fueron","they-were"],["llamados","called"],["los","the"],["escribas","scribes"],["del","of-the"],["rey","king"],["en","in"],["el","the"],["mes","month"],["tercero,","third,"],["que","that"],["es","is"],["Siván,","is,"],["a","to"],["los","the"],["veintitrés","twenty"],["días","days"],["de","of"],["ese","that"],["mes;","month;"],["y","and"],["se","itself"],["escribió","wrote"],["conforme","according-to"],["a","to"],["todo","all"],["lo","it"],["que","that"],["mandó","commanded"],["Mardoqueo","Mordecai"],["a","to"],["los","the"],["judíos,","Jews,"],["y","and"],["a","to"],["los","the"],["sátrapas,","princes,"],["y","and"],["a","to"],["los","the"],["gobernadores","governors"],["y","and"],["a","to"],["los","the"],["príncipes","princes"],["de","of"],["las","the"],["provincias","provinces"],["que","that"],["había","had"],["desde","from"],["la","the"],["India","India"],["hasta","until"],["Etiopía,","Ethiopia,"],["ciento","hundred"],["veintisiete","seventh"],["provincias;","provinces;"],["a","to"],["cada","each"],["provincia","province"],["según","according-to"],["su","their"],["escritura,","writing,"],["y","and"],["a","to"],["cada","each"],["pueblo","people"],["conforme","according-to"],["a","to"],["su","their"],["lengua,","tongue,"],["y","and"],["también","also"],["a","to"],["los","the"],["judíos","Jews"],["conforme","according-to"],["a","to"],["su","their"],["escritura","writing"],["y","and"],["su","their"],["lengua.","tongue."]]},
  {num:10,words:[["Y","and"],["se","himself"],["escribió","wrote"],["en","in"],["nombre","name"],["del","of-the"],["rey","king"],["Asuero","Ahasuerus"],["y","and"],["se","himself"],["selló","seal"],["con","with"],["el","the"],["anillo","ring"],["del","of-the"],["rey,","king,"],["y","and"],["se","themselves"],["enviaron","sent"],["cartas","letters"],["por medio de","by means of"],["mensajeros","messengers"],["a","to"],["caballo,","horse,"],["montados","mounted"],["en","in"],["corceles","mules"],["vástagos","camels"],["de","of"],["yeguas","young"],["reales;","in;"]]},
  {num:11,words:[["en","in"],["ellas","they"],["el","the"],["rey","king"],["concedía","granted"],["a","to"],["los","the"],["judíos","Jews"],["que","that"],["estaban","they-were"],["en","in"],["todas","all"],["las","the"],["ciudades","cities"],["que","that"],["se","themselves"],["reuniesen","might-gather"],["y","and"],["estuviesen","they"],["a","to"],["la","the"],["defensa","defense"],["de","of"],["su","their"],["vida,","life,"],["para","for"],["exterminar,","to-exterminate,"],["y","and"],["matar","slay"],["y","and"],["destruir","to-destroy"],["el","the"],["poder","power"],["del","of-the"],["pueblo","people"],["o","or"],["provincia","province"],["que","that"],["viniese","might-come"],["contra","against"],["ellos,","they,"],["aun","even"],["a","to"],["niños","children"],["y","and"],["a","to"],["mujeres,","women,"],["y","and"],["para","for"],["apoderarse","to-empower-himself"],["de","of"],["sus","their"],["bienes,","goods,"]]},
  {num:12,words:[["esto","this"],["en","in"],["un","a"],["mismo","same"],["día,","day,"],["en","in"],["todas","all"],["las","the"],["provincias","provinces"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"],["en","in"],["el","the"],["día","day"],["trece","thirteen"],["del","of-the"],["mes","month"],["duodécimo,","twelfth,"],["que","that"],["es","is"],["el","the"],["mes","month"],["de","of"],["Adar.","Adar."]]},
  {num:13,words:[["La","the"],["copia","copy"],["del","of-the"],["escrito","written"],["que","that"],["se","themselves"],["había","had"],["de","to"],["dar","give"],["por","for"],["mandato","decree"],["en","in"],["cada","each"],["provincia","province"],["fue","was"],["proclamada","published"],["a","to"],["todos","all"],["los","the"],["pueblos,","peoples,"],["a fin de que","so that"],["los","the"],["judíos","Jews"],["estuviesen","they"],["preparados","ready"],["para","for"],["aquel","that"],["día","day"],["para","for"],["vengarse","to-avenge-himself"],["de","of"],["sus","their"],["enemigos.","enemies."]]},
  {num:14,words:[["Los","the"],["mensajeros,","messengers,"],["pues,","for,"],["cabalgando","riding"],["en","in"],["corceles","mules"],["reales,","in,"],["salieron","they-went-out"],["apresurados","went"],["y","and"],["urgidos","urged"],["por","by"],["el","the"],["mandato","decree"],["del","of-the"],["rey;","king;"],["y","and"],["el","the"],["decreto","decree"],["fue","was"],["dado","given"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa.","Shushan."]]},
  {num:15,words:[["Y","and"],["salió","departed"],["Mardoqueo","Mordecai"],["de","of"],["la","the"],["presencia","presence"],["del","of-the"],["rey","king"],["con","with"],["vestiduras","garments"],["reales","in"],["de","of"],["azul","blue"],["y","and"],["blanco,","white,"],["y","and"],["una","a"],["gran","great"],["corona","crown"],["de","of"],["oro,","gold,"],["y","and"],["un","a"],["manto","mantle"],["de","of"],["lino","twined"],["fino","purple"],["y","and"],["material","fine"],["púrpura;","purple;"],["entonces","then"],["la","the"],["ciudad","city"],["de","of"],["Susa","Shushan"],["se","himself"],["alegró","glad"],["y","and"],["se","himself"],["regocijó.","rejoiced."]]},
  {num:16,words:[["Y","and"],["los","the"],["judíos","Jews"],["tuvieron","they-afraid"],["luz","light"],["y","and"],["alegría,","joy,"],["y","and"],["gozo","I-joy"],["y","and"],["honra.","honor."]]},
  {num:17,words:[["Y","and"],["en","in"],["cada","each"],["provincia","province"],["y","and"],["en","in"],["cada","each"],["ciudad","city"],["adonde","where"],["llegó","arrived"],["el","the"],["mandato","decree"],["del","of-the"],["rey","king"],["y","and"],["su","his"],["decreto,","decree,"],["los","the"],["judíos","Jews"],["tuvieron","they-afraid"],["alegría","joy"],["y","and"],["gozo,","I-joy,"],["banquete","banquet"],["y","and"],["día","day"],["bueno.","good."],["Y","and"],["muchos","many"],["de","of"],["entre","among"],["los","the"],["pueblos","peoples"],["de","of"],["la","the"],["tierra","land"],["se","themselves"],["hacían","did/made"],["judíos,","Jews,"],["porque","because"],["el","the"],["temor","fear"],["a","to"],["los","the"],["judíos","Jews"],["había","had"],["caído","fallen"],["sobre","upon"],["ellos.","they."]]},
];
renderVerseSet(v8, 'est-ch8-verses');

var v9 = [
  {num:1,words:[["Y","and"],["en","in"],["el","the"],["mes","month"],["duodécimo,","twelfth,"],["que","that"],["es","is"],["el","the"],["mes","month"],["de","of"],["Adar,","Adar,"],["el","the"],["día","day"],["trece","thirteen"],["del","of-the"],["mismo","same"],["mes,","month,"],["en","in"],["el","the"],["que","that"],["debía","ought"],["ejecutarse","to-execute-himself"],["el","the"],["mandato","decree"],["del","of-the"],["rey","king"],["y","and"],["su","his"],["decreto,","decree,"],["el","the"],["mismo","same"],["día","day"],["en que","that"],["esperaban","they-waited"],["los","the"],["enemigos","enemies"],["de","of"],["los","the"],["judíos","Jews"],["enseñorearse","to-take-control-of-himself"],["de","of"],["ellos,","they,"],["sucedió","it-came-to-pass"],["lo","it"],["contrario;","contrary;"],["porque","because"],["los","the"],["judíos","Jews"],["se","themselves"],["enseñorearon","they-took-control-of"],["de","of"],["los","the"],["que","that"],["los","the"],["aborrecían.","they-hated."]]},
  {num:2,words:[["Los","the"],["judíos","Jews"],["se","themselves"],["reunieron","assembled"],["en","in"],["sus","their"],["ciudades","cities"],["por","for"],["todas","all"],["las","the"],["provincias","provinces"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"],["para","for"],["echar","cast"],["mano","hand"],["a","to"],["los","the"],["que","that"],["habían","they-had"],["procurado","sought"],["su","their"],["mal;","evil;"],["y","and"],["nadie","no-one"],["se","themselves"],["opuso","opposed"],["a","to"],["ellos,","they,"],["porque","because"],["el","the"],["temor","fear"],["a","to"],["ellos","they"],["había","had"],["caído","fallen"],["sobre","upon"],["todos","all"],["los","the"],["pueblos.","peoples."]]},
  {num:3,words:[["Y","and"],["todos","all"],["los","the"],["príncipes","princes"],["de","of"],["las","the"],["provincias,","provinces,"],["y","and"],["los","the"],["sátrapas,","princes,"],["y","and"],["gobernadores","governors"],["y","and"],["oficiales","officers"],["del","of-the"],["rey","king"],["apoyaban","they-supported"],["a","to"],["los","the"],["judíos,","Jews,"],["porque","because"],["el","the"],["temor","fear"],["a","to"],["Mardoqueo","Mordecai"],["había","had"],["caído","fallen"],["sobre","upon"],["ellos,","they,"]]},
  {num:4,words:[["pues","for"],["Mardoqueo","Mordecai"],["era","was"],["grande","great"],["en","in"],["la","the"],["casa","house"],["del","of-the"],["rey,","king,"],["y","and"],["su","his"],["fama","fame"],["iba","went"],["por","for"],["todas","all"],["las","the"],["provincias;","provinces;"],["así,","thus,"],["aquel","that"],["hombre,","man,"],["Mardoqueo,","Mordecai,"],["iba","went"],["engrandeciéndose.","enlarging-himself."]]},
  {num:5,words:[["E","and"],["hirieron","they-edge"],["los","the"],["judíos","Jews"],["a","to"],["todos","all"],["sus","their"],["enemigos","enemies"],["a","to"],["filo","edge"],["de","of"],["espada,","sword,"],["con","with"],["matanza","slaughter"],["y","and"],["destrucción;","destruction;"],["e","and"],["hicieron","they-did"],["lo","it/him"],["que","that"],["quisieron","they-loved"],["con","with"],["los","the"],["que","that"],["los","the"],["odiaban.","were-hateing."]]},
  {num:6,words:[["Y","and"],["en","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa,","Shushan,"],["los","the"],["judíos","Jews"],["mataron","they-slew"],["y","and"],["destruyeron","they-destroyed"],["a","to"],["quinientos","five hundred"],["hombres.","men."]]},
  {num:7,words:[["Mataron","they-slew"],["entonces","then"],["a","to"],["Parsandata,","and,"],["y","and"],["a","to"],["Dalfón,","and,"],["y","and"],["a","to"],["Aspata,","aspatha,"]]},
  {num:8,words:[["y", "and"], ["a", "to"], ["Porata,", "poratha,"], ["y", "and"], ["a", "to"], ["Adalía,", "adalia,"], ["y", "and"], ["a", "to"], ["Aridata,", "aridatha,"]]},
  {num:9,words:[["y","and"],["a","to"],["Parmasta,","parmashta,"],["y","and"],["a","to"],["Arisai,","arisai,"],["y","and"],["a","to"],["Aridai","aridai"],["y","and"],["a","to"],["Vaizata,","vajezatha,"]]},
  {num:10,words:[["los","the"],["diez","ten"],["hijos","children"],["de","of"],["Amán","Haman"],["hijo","son"],["de","of"],["Hamedata,","Hammedatha,"],["enemigo","enemy"],["de","of"],["los","the"],["judíos;","Jews;"],["pero","but"],["en","in"],["el","the"],["botín","spoil"],["no","not"],["pusieron","they-placed"],["su","their"],["mano.","hand."]]},
  {num:11,words:[["El","the"],["mismo","same"],["día","day"],["llegó","arrived"],["ante","before"],["el","the"],["rey","king"],["la","the"],["cuenta","account"],["de","of"],["los","the"],["muertos","dead"],["en","in"],["Susa,","Shushan,"],["la","the"],["ciudadela.","Shushan."]]},
  {num:12,words:[["Y","and"],["dijo","said"],["el","the"],["rey","king"],["a","to"],["la","the"],["reina","queen"],["Ester:","Esther:"],["En","in"],["la","the"],["ciudadela","Shushan"],["de","of"],["Susa,","Shushan,"],["los","the"],["judíos","Jews"],["han","they-have"],["matado","killed"],["y","and"],["destruido","destroyed"],["a","to"],["quinientos","five hundred"],["hombres","men"],["y","and"],["a","to"],["los","the"],["diez","ten"],["hijos","children"],["de","of"],["Amán.","Haman."],["¿Qué","what"],["habrán","they-shall"],["hecho","done"],["en","in"],["las","the"],["otras","others"],["provincias","provinces"],["del","of-the"],["rey?","king?"],["¿Cuál,","which,"],["pues,","for,"],["es","is"],["tu","your"],["petición?","petition?"],["Y","and"],["te","you"],["será","shall-be"],["concedida.","granted."],["¿Qué","what"],["más","more"],["deseas?","you-desire?"],["Y","and"],["será","shall-be"],["hecho.","done."]]},
  {num:13,words:[["Y","and"],["respondió","answered"],["Ester:","Esther:"],["Si","if"],["place","the"],["al","to-the"],["rey,","king,"],["concédase","grant-oneself"],["también","also"],["mañana","morning"],["a","to"],["los","the"],["judíos","Jews"],["en","in"],["Susa","Shushan"],["que","that"],["hagan","they-do"],["conforme","according-to"],["al","to-the"],["decreto","decree"],["de","of"],["hoy","today"],["y","and"],["que","that"],["cuelguen","they-decree"],["en","in"],["la","the"],["horca","gallows"],["a","to"],["los","the"],["diez","ten"],["hijos","children"],["de","of"],["Amán.","Haman."]]},
  {num:14,words:[["Y","and"],["mandó","commanded"],["el","the"],["rey","king"],["que","that"],["se","itself"],["hiciese","might-make"],["así;","thus;"],["y","and"],["se","itself"],["dio","gave"],["la","the"],["orden","order"],["en","in"],["Susa,","Shushan,"],["y","and"],["colgaron","they-hung"],["a","to"],["los","the"],["diez","ten"],["hijos","children"],["de","of"],["Amán.","Haman."]]},
  {num:15,words:[["Y","and"],["los","the"],["judíos","Jews"],["que","that"],["estaban","they-were"],["en","in"],["Susa","Shushan"],["se","themselves"],["reunieron","assembled"],["también","also"],["el","the"],["día","day"],["catorce","fourteen"],["del","of-the"],["mes","month"],["de","of"],["Adar","Adar"],["y","and"],["mataron","they-slew"],["en","in"],["Susa","Shushan"],["a","to"],["trescientos","three hundred"],["hombres;","men;"],["pero","but"],["en","in"],["el","the"],["botín","spoil"],["no","not"],["pusieron","they-placed"],["su","their"],["mano.","hand."]]},
  {num:16,words:[["Y","and"],["los","the"],["otros","others"],["judíos","Jews"],["que","that"],["estaban","they-were"],["en","in"],["las","the"],["provincias","provinces"],["del","of-the"],["rey","king"],["también","also"],["se","themselves"],["reunieron","assembled"],["y","and"],["se","themselves"],["pusieron","placed"],["en","in"],["defensa","defense"],["de","of"],["su","their"],["vida,","life,"],["y","and"],["tuvieron","they-afraid"],["descanso","I-rest"],["de","of"],["sus","their"],["enemigos","enemies"],["y","and"],["mataron","they-slew"],["a","to"],["setenta","seventy"],["y","and"],["cinco","five"],["mil","thousand"],["de","of"],["los","the"],["que","that"],["los","the"],["odiaban;","were-hateing;"],["pero","but"],["en","in"],["el","the"],["botín","spoil"],["no","not"],["pusieron","they-placed"],["su","their"],["mano;","hand;"]]},
  {num:17,words:[["y","and"],["sucedió","it-came-to-pass"],["esto","this"],["en","in"],["el","the"],["día","day"],["trece","thirteen"],["del","of-the"],["mes","month"],["de","of"],["Adar.","Adar."],["Y","and"],["reposaron","they-rested"],["en","in"],["el","the"],["día","day"],["catorce","fourteen"],["del","of-the"],["mismo","same"],["mes,","month,"],["y","and"],["lo","it"],["proclamaron","they-proclaimed"],["día","day"],["de","of"],["banquete","banquet"],["y","and"],["de","of"],["regocijo.","rejoicing."]]},
  {num:18,words:[["Pero","but"],["los","the"],["judíos","Jews"],["que","that"],["estaban","they-were"],["en","in"],["Susa","Shushan"],["se","themselves"],["reunieron","assembled"],["el","the"],["trece","thirteen"],["y","and"],["el","the"],["catorce","fourteen"],["del","of-the"],["mismo","same"],["mes;","month;"],["y","and"],["el","the"],["quince","fifteen"],["del","of-the"],["mismo","same"],["mes","month"],["reposaron","they-rested"],["y","and"],["lo","it"],["proclamaron","they-proclaimed"],["día","day"],["de","of"],["banquete","banquet"],["y","and"],["de","of"],["regocijo.","rejoicing."]]},
  {num:19,words:[["Por tanto,","therefore,"],["los","the"],["judíos","Jews"],["que","that"],["habitan","they-dwell"],["en","in"],["el","the"],["campo,","field,"],["en","in"],["las","the"],["ciudades","cities"],["sin","without"],["muro,","wall,"],["celebran","they-keep"],["el","the"],["catorce","fourteen"],["del","of-the"],["mes","month"],["de","of"],["Adar","Adar"],["como","as"],["día","day"],["de","of"],["regocijo","rejoicing"],["y","and"],["de","of"],["banquete,","banquet,"],["y","and"],["un","a"],["día","day"],["bueno,","good,"],["y","and"],["de","of"],["enviar","to-send"],["porciones","portions"],["cada","each"],["uno","one"],["a","to"],["su","his"],["vecino.","to."]]},
  {num:20,words:[["Y","and"],["escribió","wrote"],["Mardoqueo","Mordecai"],["estas","these"],["cosas","things"],["y","and"],["envió","sent"],["cartas","letters"],["a","to"],["todos","all"],["los","the"],["judíos,","Jews,"],["cercanos","near-us"],["y","and"],["distantes,","distant,"],["que","that"],["estaban","they-were"],["en","in"],["todas","all"],["las","the"],["provincias","provinces"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"]]},
  {num:21,words:[["para","for"],["establecer","to-establish"],["que","that"],["celebrasen","they-might-keep"],["el","the"],["día","day"],["decimocuarto","the"],["y","and"],["el","the"],["decimoquinto","month"],["del","of-the"],["mes","month"],["de","of"],["Adar,","Adar,"],["cada","each"],["año,","year,"]]},
  {num:22,words:[["como","as"],["días","days"],["en","in"],["los","the"],["que","that"],["los","the"],["judíos","Jews"],["tuvieron","they-afraid"],["descanso","I-rest"],["de","of"],["sus","their"],["enemigos,","enemies,"],["y","and"],["el","the"],["mes","month"],["en que","that"],["se","itself"],["les","them"],["convirtió","became"],["la","the"],["tristeza","sorrow"],["en","in"],["alegría,","joy,"],["y","and"],["el","the"],["luto","mourning"],["en","in"],["día","day"],["bueno;","good;"],["que","that"],["los","the"],["celebrasen","might-keep"],["como","as"],["días","days"],["de","of"],["banquete,","banquet,"],["y","and"],["de","of"],["regocijo,","rejoicing,"],["y","and"],["de","of"],["enviar","to-send"],["porciones","portions"],["cada","each"],["uno","one"],["a","to"],["su","their"],["vecino","to"],["y","and"],["dádivas","gifts"],["a","to"],["los","the"],["pobres.","poor."]]},
  {num:23,words:[["Y","and"],["los","the"],["judíos","Jews"],["aceptaron","they-undertook"],["hacer","do"],["lo","it/him"],["que","that"],["habían","they-had"],["comenzado,","begun,"],["según","according-to"],["lo","it/him"],["que","that"],["les","them"],["escribió","wrote"],["Mardoqueo.","Mordecai."]]},
  {num:24,words:[["Porque","because"],["Amán","Haman"],["hijo","son"],["de","of"],["Hamedata,","Hammedatha,"],["el","the"],["agagueo,","the,"],["enemigo","enemy"],["de","of"],["todos","all"],["los","the"],["judíos,","Jews,"],["había","had"],["ideado","devised"],["un","a"],["plan","plan"],["contra","against"],["los","the"],["judíos","Jews"],["para","for"],["destruirlos","to-destroy-them"],["y","and"],["había","had"],["echado","cast"],["pur,","Pur,"],["que","that"],["quiere","wants"],["decir","to-say"],["suerte,","lot,"],["para","for"],["afligirlos","to-afflict-them"],["y","and"],["acabar","to-finish"],["con","with"],["ellos.","they."]]},
  {num:25,words:[["Pero","but"],["cuando","when"],["Ester","Esther"],["fue","was"],["ante","before"],["el","the"],["rey,","king,"],["este","this"],["ordenó","ordained"],["por","by"],["carta","letter"],["que","that"],["el","the"],["perverso","wicked"],["plan","plan"],["que","that"],["aquel","that"],["tramó","plotted"],["contra","against"],["los","the"],["judíos","Jews"],["recayera","return"],["sobre","upon"],["su","his"],["cabeza","head"],["y","and"],["que","that"],["los","the"],["colgaran","they-might-hang"],["a","to"],["él","he"],["y","and"],["a","to"],["sus","his"],["hijos","children"],["en","in"],["la","the"],["horca.","gallows."]]},
  {num:26,words:[["Por","for"],["esto","this"],["llamaron","they-called"],["a","to"],["estos","these"],["días","days"],["Purim,","Purim,"],["del","of-the"],["nombre","name"],["pur.","of."],["Debido","due"],["a","to"],["todas","all"],["las","the"],["palabras","words"],["de","of"],["esta","this"],["carta,","letter,"],["y","and"],["a","to"],["lo","it/him"],["que","that"],["ellos","they"],["vieron","saw"],["sobre","upon"],["este","this"],["asunto,","matter,"],["y","and"],["a","to"],["lo","it/him"],["que","that"],["llegó","arrived"],["a","to"],["su","his"],["conocimiento,","knowledge,"]]},
  {num:27,words:[["los","the"],["judíos","Jews"],["establecieron","they-established"],["y","and"],["tomaron","they-took"],["sobre","upon"],["sí,","yes,"],["y","and"],["sobre","upon"],["su","their"],["descendencia","seed"],["y","and"],["sobre","upon"],["todos","all"],["sus","their"],["aliados,","ally,"],["que","that"],["sin","without"],["falta","want"],["celebrarían","they-would-keep"],["estos","these"],["dos","two"],["días","days"],["según","according-to"],["lo","it"],["escrito","written"],["tocante","concerning"],["a","to"],["ellos","they"],["y","and"],["conforme","according-to"],["a","to"],["su","their"],["tiempo","time"],["cada","each"],["año.","year."]]},
  {num:28,words:[["Y","and"],["que","that"],["estos","these"],["días","days"],["serían","they-should-be"],["recordados","remembered"],["y","and"],["celebrados","remembered"],["por","for"],["todas","all"],["las","the"],["generaciones,","generations,"],["por","for"],["cada","each"],["familia,","family,"],["por","for"],["cada","each"],["provincia","province"],["y","and"],["por","for"],["cada","each"],["ciudad.","city."],["Y","and"],["que","that"],["estos","these"],["días","days"],["de","of"],["Purim","Purim"],["no","not"],["dejarían","they-would-leave"],["de","to"],["celebrarse","keep-himself"],["de","of"],["entre","among"],["los","the"],["judíos,","Jews,"],["y","and"],["que","that"],["el","the"],["recuerdo","remembrance"],["de","of"],["ellos","they"],["no","not"],["cesaría","would-ceasing"],["entre","among"],["su","their"],["descendencia.","seed."]]},
  {num:29,words:[["Y","and"],["la","the"],["reina","queen"],["Ester","Esther"],["hija","daughter"],["de","of"],["Abihail","Abihail"],["y","and"],["el","the"],["judío","Jew"],["Mardoqueo,","Mordecai,"],["escribieron","they-wrote"],["con","with"],["toda","all"],["autoridad","authority"],["para","for"],["confirmar","to-confirm"],["esta","this"],["segunda","second"],["carta","letter"],["de","of"],["Purim.","Purim."]]},
  {num:30,words:[["Y","and"],["envió","sent"],["Mardoqueo","Mordecai"],["cartas","letters"],["a","to"],["todos","all"],["los","the"],["judíos,","Jews,"],["a","to"],["las","the"],["ciento","hundred"],["veintisiete","seventh"],["provincias","provinces"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"],["con","with"],["palabras","words"],["de","of"],["paz","peace"],["y","and"],["de","of"],["verdad,","truth,"]]},
  {num:31,words:[["para","for"],["confirmar","to-confirm"],["estos","these"],["días","days"],["de","of"],["Purim","Purim"],["en","in"],["sus","their"],["tiempos","times"],["señalados,","appointed,"],["según","according-to"],["los","the"],["habían","had"],["establecido","established"],["el","the"],["judío","Jew"],["Mardoqueo","Mordecai"],["y","and"],["la","the"],["reina","queen"],["Ester,","Esther,"],["y","and"],["como","as"],["ellos","they"],["lo","it/him"],["habían","they-had"],["establecido","established"],["para","for"],["sí","yes"],["y","and"],["para","for"],["su","their"],["descendencia","seed"],["en","in"],["lo","it/him"],["relacionado","matters"],["con","with"],["los","the"],["ayunos","fastings"],["y","and"],["su","their"],["clamor.","cry."]]},
  {num:32,words:[["Y","and"],["el","the"],["mandato","decree"],["de","of"],["Ester","Esther"],["confirmó","confirmed"],["estas","these"],["prácticas","in"],["acerca","about"],["de","of"],["Purim,","Purim,"],["y","and"],["esto","this"],["se","itself"],["escribió","wrote"],["en","in"],["el","the"],["libro.","book."]]},
];
renderVerseSet(v9, 'est-ch9-verses');

var v10 = [
  {num:1,words:[["Y","and"],["el","the"],["rey","king"],["Asuero","Ahasuerus"],["impuso","imposed"],["tributo","tribute"],["sobre","upon"],["la","the"],["tierra","land"],["y","and"],["sobre","upon"],["las","the"],["islas","islands"],["del","of-the"],["mar.","sea."]]},
  {num:2,words:[["Y","and"],["todas","all"],["las","the"],["obras","works"],["de","of"],["su","his"],["autoridad","authority"],["y","and"],["de","of"],["su","his"],["poder,","power,"],["y","and"],["la","the"],["declaración","declaration"],["de","of"],["la","the"],["grandeza","greatness"],["de","of"],["Mardoqueo,","Mordecai,"],["con que","wherewith"],["el","the"],["rey","king"],["le","him"],["engrandeció,","enlarged,"],["¿no","not"],["está","is"],["todo","all"],["escrito","written"],["en","in"],["el","the"],["libro","book"],["de","of"],["las","the"],["crónicas","chronicles"],["de","of"],["los","the"],["reyes","kings"],["de","of"],["Media","Media"],["y","and"],["de","of"],["Persia?","Persia?"]]},
  {num:3,words:[["Porque","because"],["el","the"],["judío","Jew"],["Mardoqueo","Mordecai"],["fue","was"],["segundo","second"],["después","after"],["del","of-the"],["rey","king"],["Asuero,","Ahasuerus,"],["y","and"],["grande","great"],["entre","among"],["los","the"],["judíos","Jews"],["y","and"],["bien","well"],["recibido","received"],["por","for"],["la","the"],["multitud","multitude"],["de","of"],["sus","his"],["hermanos,","brothers,"],["pues","for"],["procuró","sought"],["el","the"],["bien","well"],["de","of"],["su","his"],["pueblo","people"],["y","and"],["habló","spoke"],["paz","peace"],["para","for"],["toda","all"],["su","his"],["descendencia.","seed."]]},
];
renderVerseSet(v10, 'est-ch10-verses');

})();
