(function() {
var v1 = [
  {num:1,words:[["La", "the"], ["profecía", "prophecy"], ["que", "that"], ["vio", "saw"], ["el", "the"], ["profeta", "prophet"], ["Habacuc.","Habakkuk."]]},
  {num:2,words:[["¿Hasta","until"],["cuándo,","when,"],["oh","oh"],["Jehová,","jehovah,"],["clamaré,","I-cry,"],["y","and"],["no","not"],["oirás;","you-hear;"],["y","and"],["daré","I-shall-give"],["voces","voices"],["a","to"],["ti","you"],["a causa de","because of"],["la","the"],["violencia,","violence,"],["y","and"],["no","not"],["salvarás?","you?"]]},
  {num:3,words:[["¿Por","for"],["qué","what"],["me","me"],["haces","you-do"],["ver","see"],["iniquidad","iniquity"],["y","and"],["haces","you-do"],["que","that"],["contemple","grievance?"],["molestia?","for?"],["Y","and"],["destrucción","destruction"],["y","and"],["violencia","violence"],["hay","there-is"],["delante","before"],["de","of"],["mí,","me,"],["y","and"],["surgen","they-may-among"],["pleito","dispute"],["y","and"],["contienda.","strife."]]},
  {num:4,words:[["Por","for"],["lo","it/him"],["cual","which"],["la","the"],["ley","law"],["es","is"],["debilitada,","weaken,"],["y","and"],["el","the"],["juicio","judgment"],["nunca","never"],["sale","goes"],["adelante;","forward/henceforth;"],["por cuanto","because"],["el","the"],["malvado","wicked"],["asedia","siege"],["al","to-the"],["justo,","righteous,"],["por eso","therefore"],["sale","goes"],["torcido","twined"],["el","the"],["juicio.","judgment."]]},
  {num:5,words:[["Mirad","you-heed"],["entre","among"],["las","the"],["naciones","nations"],["y","and"],["ved;","you-see;"],["y","and"],["maravillaos","wonder"],["y","and"],["asombraos,","for,"],["porque","because"],["haré","I will make"],["una","a"],["obra","work"],["en","in"],["vuestros","your"],["días","days"],["que,","that,"],["aun","even"],["cuando","when"],["se","[refl.]"],["os","you"],["cuente,","it,"],["no","not"],["la","the"],["creeréis.","believe."]]},
  {num:6,words:[["Porque","because"],["he aquí,","behold,"],["yo","I"],["levanto","I-arose"],["a","to"],["los","the"],["caldeos,","chaldees,"],["nación","nation"],["feroz","hasty"],["e","and"],["impetuosa,","shall,"],["que","that"],["camina","walks"],["por","for"],["la","the"],["anchura","breadth"],["de","of"],["la","the"],["tierra","land"],["para","for"],["poseer","to-possess"],["las","the"],["moradas","shall"],["ajenas.","theirs."]]},
  {num:7,words:[["Espantosa","they"],["es","is"],["y","and"],["terrible;","awful;"],["de","of"],["ella","she"],["misma","same"],["proceden","they-proceed"],["su","their"],["propio","own"],["juicio","judgment"],["y","and"],["su","their"],["propia","own"],["grandeza.","greatness."]]},
  {num:8,words:[["Y","and"],["serán","they-shall-be"],["sus","their"],["caballos","horses"],["más","more"],["ligeros","lights"],["que","that"],["leopardos","leopards"],["y","and"],["más","more"],["feroces","wild"],["que","that"],["lobos","wolves"],["nocturnos;","wolves;"],["y","and"],["sus","their"],["jinetes","horsemen"],["se","[refl.]"],["dispersarán;","themselves;"],["vendrán","they-will-come"],["de","of"],["lejos","far"],["sus","their"],["jinetes","horsemen"],["y","and"],["volarán","they-shall"],["como","as"],["águilas","eagles"],["que","that"],["se","[refl.]"],["apresuran","they-hurry"],["a","to"],["devorar.","to-devour."]]},
  {num:9,words:[["Toda", "all"], ["ella", "she"], ["vendrá", "shall-come"], ["para", "for"], ["hacer", "make/do"], ["violencia;", "violence;"], ["delante", "before"], ["de", "of"], ["sus","their"], ["caras", "faces"], ["viento", "wind"], ["solano,", "wind,"], ["y", "and"], ["recogerá", "gather"], ["cautivos", "captives"], ["como", "as"], ["arena.", "sand."]]},
  {num:10,words:[["Y", "and"], ["escarnecerá", "they"], ["a", "to"], ["los", "the"], ["reyes,", "kings,"], ["y", "and"], ["de", "of"], ["los", "the"], ["príncipes", "princes"], ["hará", "shall-make"], ["burla;", "an;"], ["se", "[refl.]"], ["reirá", "they"], ["de", "of"], ["las", "the"], ["fortalezas,", "holds,"], ["y", "and"], ["levantará", "raise"], ["terraplén", "heap"], ["y", "and"], ["las", "the"], ["tomará.", "take."]]},
  {num:11,words:[["Luego","then"],["pasará","will-pass"],["como","as"],["el","the"],["viento,","wind,"],["y","and"],["seguirá","shall"],["adelante","forward/henceforth"],["y","and"],["ofenderá,","will-offend,"],["atribuyendo","imputing"],["su","his"],["poder","power"],["a","to"],["su","his"],["dios.","God."]]},
  {num:12,words:[["¿No","not"],["eres","you-are"],["tú","you"],["desde","from"],["el","the"],["principio,","beginning,"],["oh","oh"],["Jehová,","jehovah,"],["Dios","God"],["mío,","mine,"],["Santo","holy"],["mío?","mine?"],["No","not"],["moriremos.","we-will-die."],["Oh","oh"],["Jehová,","jehovah,"],["para","for"],["juicio","judgment"],["los","the"],["pusiste;","have;"],["y","and"],["tú,","you,"],["oh","oh"],["Roca,","rock,"],["los","the"],["has","you-have"],["puesto","placed"],["para","for"],["castigar.","to-punish."]]},
  {num:13,words:[["Muy","very"],["limpio","I-clean"],["eres","you-are"],["de","of"],["ojos","eyes"],["para","for"],["ver","see"],["el","the"],["mal","evil"],["y","and"],["no","not"],["puedes","you-can"],["ver","see"],["el","the"],["agravio.","wrong."],["¿Por","by/for"],["qué","what"],["toleras","you-tolerate"],["a","to"],["los","the"],["que","that"],["actúan","they-act"],["pérfidamente,","you-hold,"],["y","and"],["callas","you-tongue"],["cuando","when"],["el","the"],["malvado","wicked"],["destruye","destroys"],["al","to-the"],["que","that"],["es","is"],["más","more"],["justo","righteous"],["que","that"],["él","he"]]},
  {num:14,words:[["y","and"],["haces","you-do"],["que","that"],["sean","they-let-be"],["los","the"],["hombres","men"],["como","as"],["los","the"],["peces","fish"],["del","of-the"],["mar,","sea,"],["como","as"],["reptiles","creeping"],["que","that"],["no","not"],["tienen","they-have"],["señor?","Lord?"]]},
  {num:15,words:[["Sacará","bring"],["a","to"],["todos","all"],["con","with"],["anzuelo;","fishing hook;"],["los","the"],["recogerá","gather"],["con","with"],["su","their"],["red","net"],["y","and"],["los","the"],["juntará","will-gather"],["en","in"],["su","their"],["malla,","evil-her,"],["por","by/for"],["lo","it/him"],["cual,","which,"],["se","[refl.]"],["alegrará","rejoice"],["y","and"],["se","[refl.]"],["regocijará.","rejoice."]]},
  {num:16,words:[["Por","by"],["esto","this"],["ofrecerá","blemish"],["sacrificios","sacrifices"],["a","to"],["su","their"],["red","net"],["y","and"],["quemará","will-burn"],["incienso","incense"],["a","to"],["su","their"],["malla,","evil-her,"],["porque","because"],["con","with"],["ellas","they"],["engordó","portion"],["su","their"],["porción","portion"],["y","and"],["aumentó","increased"],["su","their"],["comida.","meat."]]},
  {num:17,words:[["¿Vaciará", "shall"], ["por eso","therefore"], ["su","their"], ["red", "net"], ["y", "and"], ["seguirá", "shall"], ["aniquilando", "spare"], ["sin", "without"], ["piedad", "godliness"], ["a", "to"], ["las", "the"], ["naciones?", "nations?"]]},
];
renderVerseSet(v1, 'hab-ch1-verses');

var v2 = [
  {num:1,words:[["En","in"],["mi","my"],["puesto","placed"],["de","of"],["guardia","nebuzaradan"],["estaré,","I-will,"],["y","and"],["sobre","upon"],["la","the"],["fortaleza","castle"],["afirmaré","I-will-assert"],["el","the"],["pie,","foot,"],["y","and"],["velaré","I-shall-watch"],["para","for"],["ver","see"],["lo","it/him"],["que","that"],["él","he"],["me","me"],["dirá","shall-say"],["y","and"],["lo","it/him"],["que","that"],["he","I-have"],["de","of"],["responder","answer"],["cuando","when"],["sea","let-be/be"],["reprendido.","reprimanded."]]},
  {num:2,words:[["Y", "and"], ["Jehová", "jehovah"], ["me", "me"], ["respondió", "answered"], ["y", "and"], ["dijo:", "said:"], ["Escribe", "write"], ["la", "the"], ["visión", "vision"], ["y", "and"], ["grábala", "and"], ["claramente", "plainly"], ["en", "in"], ["tablas", "boards"], ["para", "for"], ["que", "that"], ["corra", "he"], ["el", "the"], ["que", "that"], ["lea", "leah"], ["en", "in"], ["ella.", "she."]]},
  {num:3,words:[["Aunque","although"],["la","the"],["visión","vision"],["es","is"],["aún","yet"],["para","for"],["un","a"],["tiempo","time"],["señalado,","appointed,"],["al","to-the"],["final","end"],["hablará","will-speak"],["y","and"],["no","not"],["mentirá;","will-lie;"],["aunque","although"],["se","[refl.]"],["tarde,","evening,"],["espérala,","you-her,"],["porque","because"],["sin","without"],["duda","surely"],["vendrá;","shall-come;"],["no","not"],["tardará.","tarry."]]},
  {num:4,words:[["He aquí,","behold,"],["se","[refl.]"],["enorgullece","is"],["aquel","that"],["cuya","whose"],["alma","soul"],["no","not"],["es","is"],["recta;","the;"],["mas","but"],["el","the"],["justo","righteous"],["por","by"],["su","his"],["fe","faith"],["vivirá.","will-live."]]},
  {num:5,words:[["Y", "and"], ["también,", "also,"], ["el", "the"], ["vino", "wine"], ["traiciona","transgresses"], ["al", "to-the"], ["hombre", "man"], ["soberbio", "proud"], ["de modo que","so that"], ["no", "not"], ["permanece;","abides;"], ["ensancha","keeps"], ["su","his"], ["deseo", "desire"], ["como", "as"], ["el", "the"], ["Seol", "grave"], ["y", "and"], ["es", "is"], ["como", "as"], ["la", "the"], ["muerte", "death"], ["que", "that"], ["no", "not"], ["se", "[refl.]"], ["sacia,", "is,"], ["sino", "but"], ["que", "that"], ["reúne", "together"], ["para", "for"], ["sí","yes"], ["todas", "all"], ["las", "the"], ["naciones", "nations"], ["y", "and"], ["recoge","gathers"], ["para", "for"], ["sí","yes"], ["todos", "all"], ["los", "the"], ["pueblos.", "peoples."]]},
  {num:6,words:[["¿No","not"],["han","they-have"],["de","of"],["levantar","raise"],["todos","all"],["estos","these"],["refrán","proverb"],["contra","against"],["él","he"],["y","and"],["sarcasmos","taunting"],["contra","against"],["él?","he?"],["Y","and"],["dirán:","they-will-say:"],["¡Ay","wo"],["del","of-the"],["que","that"],["multiplica","multiplies"],["lo","him"],["que","that"],["no","not"],["es","is"],["suyo!","his!"],["¿Hasta","until"],["cuándo","when"],["seguirá","shall"],["acumulando","accumulating"],["sobre","upon"],["sí","yes"],["prendas","pledges"],["empeñadas?","clay?"]]},
  {num:7,words:[["¿No","not"],["se","[refl.]"],["levantarán","rise"],["de","of"],["repente","suddenly"],["tus","your"],["acreedores,","creditors,"],["y","and"],["se","[refl.]"],["despertarán","you,"],["los","the"],["que","that"],["te","you"],["hagan","do"],["temblar?","to-tremble?"],["Y","and"],["tú","you"],["serás","you-will-be"],["para","for"],["ellos","they"],["objeto","intent"],["de","of"],["rapiña.","to."]]},
  {num:8,words:[["Por cuanto","because"],["tú","you"],["has","you-have"],["despojado","stripped"],["a","to"],["muchas","many"],["naciones,","nations,"],["todos","all"],["los","the"],["otros","others"],["pueblos","peoples"],["te","you"],["despojarán,","people,"],["a causa de","because of"],["la","the"],["sangre","blood"],["de","of"],["los","the"],["hombres","men"],["y","and"],["de","of"],["la","the"],["violencia","violence"],["hecha","done"],["a","to"],["la","the"],["tierra,","land,"],["a","to"],["las","the"],["ciudades","cities"],["y","and"],["a","to"],["todos","all"],["los","the"],["que","that"],["moraban","they-dwelt"],["en","in"],["ellas.","they."]]},
  {num:9,words:[["¡Ay", "wo"], ["del", "of-the"], ["que", "that"], ["obtiene","covets"], ["injusta", "evil"], ["ganancia", "gain"], ["para", "for"], ["su","his"], ["casa,", "house,"], ["para", "for"], ["poner", "put/place"], ["en", "in"], ["alto", "high"], ["su","his"], ["nido,", "nest,"], ["para", "for"], ["escaparse", "escape-[refl.]"], ["del", "of-the"], ["poder","power"], ["del", "of-the"], ["mal!", "evil!"]]},
  {num:10,words:[["Has","you-have"],["tramado","have"],["vergüenza","shame"],["para","for"],["tu","your"],["casa","house"],["al","to-the"],["destruir","to-destroy"],["a","to"],["muchos","many"],["pueblos,","peoples,"],["y","and"],["has","you-have"],["pecado","sin"],["contra","against"],["tu","your"],["alma.","soul."]]},
  {num:11,words:[["Porque", "because"], ["la", "the"], ["piedra", "stone"], ["clamará", "cry"], ["desde", "from"], ["el", "the"], ["muro,", "wall,"], ["y", "and"], ["la", "the"], ["viga", "mote"], ["del", "of-the"], ["enmaderado", "timber"], ["le", "him/her"], ["responderá.", "answer."]]},
  {num:12,words:[["¡Ay","wo"],["del","of-the"],["que","that"],["edifica","builds"],["la","the"],["ciudad","city"],["con","with"],["sangre","blood"],["y","and"],["del","of-the"],["que","that"],["funda","has"],["una","a"],["aldea","village"],["con","with"],["injusticia!","unrighteousness!"]]},
  {num:13,words:[["He aquí,","behold,"],["¿no","not"],["es","is"],["esto","this"],["de","of"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos","armies"],["que","that"],["los","the"],["pueblos","peoples"],["trabajen","they-may-labor"],["para","for"],["el","the"],["fuego","fire"],["y","and"],["las","the"],["naciones","nations"],["se","[refl.]"],["fatiguen","they-may-fatigue"],["en","in"],["vano?","vain?"]]},
  {num:14,words:[["Porque","because"],["la","the"],["tierra","earth"],["estará","shall-be"],["llena","full"],["del","of-the"],["conocimiento","knowledge"],["de","of"],["la","the"],["gloria","glory"],["de","of"],["Jehová","jehovah"],["como","as"],["las","the"],["aguas","waters"],["cubren","they-cover"],["el","the"],["mar.","sea."]]},
  {num:15,words:[["¡Ay","wo"],["del","of-the"],["que","that"],["da","gives"],["de","of"],["beber","to-drink"],["a","to"],["su","his/her"],["prójimo!","neighbor!"],["¡Ay","wo"],["de","of"],["ti,","you,"],["que","that"],["le","him/her"],["acercas","you-approach"],["tu","your"],["hiel","gall"],["y","and"],["le","him/her"],["embriagas","you-may"],["para","for"],["mirar","to-look"],["su","his/her"],["desnudez!","nakedness!"]]},
  {num:16,words:[["Te","you"],["has","you-have"],["llenado","filled"],["de","of"],["deshonra","shame"],["más","more"],["que","that"],["de","of"],["honra;","honor;"],["bebe","drinks"],["tú","you"],["también,","also,"],["y","and"],["serás","you-will-be"],["como","as"],["incircunciso;","uncircumcised;"],["la","the"],["copa","cup"],["de","of"],["la","the"],["mano","hand"],["derecha","right"],["de","of"],["Jehová","jehovah"],["se","[refl.]"],["volverá","return"],["contra","against"],["ti,","you,"],["y","and"],["la","the"],["deshonra","shall"],["caerá","will-fall"],["sobre","upon"],["tu","your"],["gloria.","glory."]]},
  {num:17,words:[["Porque","because"],["la","the"],["violencia","violence"],["del","of-the"],["Líbano","lebanon"],["te","you"],["cubrirá,","cover,"],["y","and"],["la","the"],["destrucción","destruction"],["de","of"],["las","the"],["fieras","beasts"],["las","the"],["aterrorizará","beasts,"],["a causa de","because of"],["la","the"],["sangre","blood"],["de","of"],["los","the"],["hombres","men"],["y","and"],["de","of"],["la","the"],["violencia","violence"],["hecha","done"],["a","to"],["la","the"],["tierra,","land,"],["a","to"],["las","the"],["ciudades","cities"],["y","and"],["a","to"],["todos","all"],["los","the"],["que","that"],["en","in"],["ellas","they"],["moran.","they-dwell."]]},
  {num:18,words:[["¿De","of"],["qué","what"],["sirve","nothing"],["la","the"],["imagen","image"],["tallada","graven"],["que","that"],["talló","maker"],["el","the"],["que","that"],["la","the"],["hizo,","made/did,"],["la","the"],["imagen","image"],["de","of"],["fundición","molten"],["y","and"],["maestra","teacher"],["de","of"],["mentiras,","lyings,"],["para","for"],["que","that"],["haciendo","doing/making"],["imágenes","groves"],["mudas","you-change"],["confíe","trusts"],["el","the"],["hacedor","maker"],["en","in"],["su","his"],["obra?","work?"]]},
  {num:19,words:[["¡Ay","wo"],["del","of-the"],["que","that"],["dice","says"],["al","to-the"],["palo:","staff:"],["Despiértate;","awake-you;"],["y","and"],["a","to"],["la","the"],["piedra","stone"],["muda:","dumb:"],["Levántate!","arise!"],["¿Podrá","able"],["él","he"],["enseñar?","to-teach?"],["He aquí,","behold,"],["está","is"],["cubierto","covered"],["de","of"],["oro","gold"],["y","and"],["de","of"],["plata,","silver,"],["y","and"],["no","not"],["hay","there-is"],["espíritu","Spirit"],["dentro","within"],["de","of"],["él.","he."]]},
  {num:20,words:[["Mas", "but"], ["Jehová", "jehovah"], ["está", "is"], ["en", "in"], ["su","his"], ["santo", "holy"], ["templo:", "temple:"], ["¡Calle", "street"], ["delante", "before"], ["de", "of"], ["él", "he"], ["toda", "all"], ["la", "the"], ["tierra!","earth!"]]},
];
renderVerseSet(v2, 'hab-ch2-verses');

var v3 = [
  {num:1,words:[["Oración", "prayer"], ["del", "of-the"], ["profeta", "prophet"], ["Habacuc,","Habakkuk,"], ["sobre", "upon"], ["Sigionot.", "shigionoth."]]},
  {num:2,words:[["Oh", "oh"], ["Jehová,", "jehovah,"], ["he", "I-have"], ["oído", "heard"], ["tu","your"], ["palabra", "word"], ["y", "and"], ["temí.Oh", "was"], ["Jehová,", "jehovah,"], ["aviva", "o"], ["tu","your"], ["obra", "work"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["los", "the"], ["tiempos,en", "of"], ["medio", "midst"], ["de", "of"], ["los", "the"], ["tiempos", "times"], ["hazla", "do-her"], ["conocer;en", "the"], ["la", "the"], ["ira", "wrath"], ["acuérdate", "remember"], ["de", "of"], ["la", "the"], ["misericordia.", "mercy."]]},
  {num:3,words:[["Dios", "God"], ["viene", "comes"], ["de", "of"], ["Temán,y", "teman,"], ["el", "the"], ["Santo", "holy"], ["desde", "from"], ["el", "the"], ["monte", "mount"], ["Parán.","Paran."], ["SelahSu", "selah."], ["gloria", "glory"], ["cubrió", "covered"], ["los", "the"], ["cielos,y", "the"], ["la", "the"], ["tierra","earth"], ["se", "[refl.]"], ["llenó", "filled"], ["de", "of"], ["su","his"], ["alabanza.", "praise."]]},
  {num:4,words:[["Y","and"],["su","his"],["resplandor","luster"],["es","is"],["como","as"],["la","the"],["luz,rayos","had"],["brillantes","horns"],["salen","they-forth"],["de","of"],["su","his"],["mano,y","hand"],["allí","there"],["está","is"],["escondido","hid"],["su","his"],["poder.","power."]]},
  {num:5,words:[["Delante","before"],["de","of"],["su","his"],["rostro","face"],["va","goes"],["la","the"],["mortandad,y","coals"],["llamaradas","went"],["salen","they-forth"],["tras","after"],["sus","his"],["pies.","feet."]]},
  {num:6,words:[["Se","[refl.]"],["levantó","arose"],["y","and"],["midió","measured"],["la","the"],["tierra;miró","he"],["e","and"],["hizo","did"],["temblar","to-tremble"],["las","the"],["naciones;y","heathen"],["los","the"],["montes","mountains"],["antiguos","ancient"],["fueron","they-were"],["desmenuzados;los","scattered,"],["collados","hills"],["antiguos","ancient"],["se","[refl.]"],["inclinaron.Sus","bow:"],["caminos","ways"],["son","they-are"],["eternos.","eternal."]]},
  {num:7,words:[["He","I-have"],["visto","seen"],["las","the"],["tiendas","tents"],["de","of"],["Cusán","in"],["en","in"],["aflicción;las","affliction-them"],["cortinas","curtains"],["de","of"],["la","the"],["tierra","land"],["de","of"],["Madián","Midian"],["temblaron.","they-trembled."]]},
  {num:8,words:[["¿Se","[refl.]"],["airó","angered"],["Jehová","jehovah"],["contra","against"],["los","the"],["ríos?¿Contra","rivers?"],["los","the"],["ríos","rivers"],["fue","was"],["tu","your"],["enojo?¿Fue","rivers?"],["tu","your"],["ira","wrath"],["contra","against"],["el","the"],["mar,para","sea,"],["que","that"],["montases","you"],["en","in"],["tus","your"],["caballosy","yours"],["en","in"],["tus","your"],["carros","chariots"],["de","of"],["salvación?","salvation?"]]},
  {num:9,words:[["Se", "[refl.]"], ["desnudó", "naked"], ["enteramente", "utterly"], ["tu","your"], ["arco,según", "naked,"], ["los", "the"], ["juramentos", "oaths"], ["de", "of"], ["las", "the"], ["saetas", "arrows"], ["de", "of"], ["tu","your"], ["palabra.", "word."], ["SelahHendiste","you"], ["la", "the"], ["tierra","earth"], ["con", "with"], ["ríos.", "rivers."]]},
  {num:10,words:[["Te","you"],["vieron","saw"],["los","the"],["montes","mountains"],["y","and"],["temblaron;pasó","the"],["la","the"],["inundación","flood"],["de","of"],["las","the"],["aguas;el","by:"],["abismo","deep"],["dio","gave"],["su","his"],["voz;a","voice,"],["lo","it/him"],["alto","high"],["alzó","lifted"],["sus","his"],["manos.","hands."]]},
  {num:11,words:[["El", "the"], ["sol", "sun"], ["y", "and"], ["la", "the"], ["luna", "moon"], ["se", "[refl.]"], ["detuvieron", "stood"], ["en", "in"], ["su","their"], ["cenit;a", "little-supper"], ["la", "the"], ["luz", "light"], ["de", "of"], ["tus","your"], ["saetas", "arrows"], ["anduvierony", "and"], ["al", "to-the"], ["resplandor", "luster"], ["de", "of"], ["tu","your"], ["refulgente", "glittering"], ["lanza.", "spear."]]},
  {num:12,words:[["Con","with"],["ira","wrath"],["hollaste","you-through"],["la","the"],["tierra;con","indignation,"],["furor","fury"],["trillaste","you-threshed"],["las","the"],["naciones.","nations."]]},
  {num:13,words:[["Saliste","out"],["para","for"],["salvar","to-save"],["a","to"],["tu","your"],["pueblo,para","your"],["salvar","to-save"],["con","with"],["tu","your"],["ungido.Traspasaste","yours"],["la","the"],["cabeza","head"],["de","of"],["la","the"],["casa","house"],["del","of-the"],["malvado,descubriendo","the"],["el","the"],["cimiento","foundation"],["hasta","until"],["el","the"],["cuello.","neck."],["Selah","Selah"]]},
  {num:14,words:[["Traspasaste","you"],["con","with"],["sus","his/her"],["propias","own"],["saetas","arrows"],["las","the"],["cabezas","heads"],["de","of"],["sus","his/her"],["guerreros,que","they"],["como","as"],["tempestad","storm"],["acometieron","the"],["para","for"],["dispersarme;su","to"],["regocijo","rejoicing"],["era","was"],["como","as"],["para","for"],["devorar","to-devour"],["al","to-the"],["pobre","poor"],["encubiertamente.","secretly."]]},
  {num:15,words:[["Caminaste","you-walkeths-you"],["en","in"],["el","the"],["mar","sea"],["con","with"],["tus","your"],["caballos,sobre","yours"],["la","the"],["mole","through"],["de","of"],["las","the"],["grandes","great"],["aguas.","waters."]]},
  {num:16,words:[["Oí,","I-heard,"],["y","and"],["se","[refl.]"],["conmovieron","belly"],["mis","my"],["entrañas;a","lips"],["la","the"],["voz","voice"],["temblaron","they-trembled"],["mis","my"],["labios;pudrición","into"],["entró","entered"],["en","in"],["mis","my"],["huesos,y","trembled"],["dentro","within"],["de","of"],["mí","me"],["me","me"],["estremecí.Tranquilo","in"],["espero","I-trust"],["el","the"],["día","day"],["de","of"],["la","the"],["angustiaque","up"],["vendrá","shall-come"],["sobre","upon"],["el","the"],["pueblo","people"],["que","that"],["nos","us"],["ataca.","struck."]]},
  {num:17,words:[["Aunque","although"],["la","the"],["higuera","fig"],["no","not"],["florezcani","blossom,"],["en","in"],["las","the"],["vides","and"],["haya","let-there-be"],["frutos,aunque","vines;"],["falle","may-fail"],["la","the"],["cosecha","harvest"],["del","of-the"],["olivo,y","fail,"],["los","the"],["campos","fields"],["no","not"],["produzcan","they-may-produce"],["alimento,y","meat;"],["las","the"],["ovejas","sheep"],["sean","they-let-be"],["quitadas","taken"],["del","of-the"],["redily","fold,"],["no","not"],["haya","let-there-be"],["vacas","kine"],["en","in"],["los","the"],["establos,","stalls,"]]},
  {num:18,words:[["con","with"],["todo","all"],["yo","I"],["me","me"],["alegraré","I-will-cheer-up"],["en","in"],["Jehováy","o"],["me","me"],["regocijaré","rejoice"],["en","in"],["el","the"],["Dios","God"],["de","of"],["mi","my"],["salvación.","salvation."]]},
  {num:19,words:[["Jehová","jehovah"],["el","the"],["Señor","Lord"],["es","is"],["mi","my"],["fortaleza,y","make"],["él","he"],["hará","shall-make"],["mis","my"],["pies","feet"],["como","as"],["de","of"],["ciervasy","to"],["me","me"],["hará","shall-make"],["andar","to-walk"],["sobre","upon"],["mis","my"],["lugares","places"],["altos.","high."]]},
];
renderVerseSet(v3, 'hab-ch3-verses');

})();
