(function() {
var v1 = [
  {num:1,words:[["La", "the"], ["profecía", "prophecy"], ["que", "that"], ["vio", "saw"], ["el", "the"], ["profeta", "prophet"], ["Habacuc.", "see."]]},
  {num:2,words:[["¿Hasta", "until"], ["cuándo,", "when,"], ["oh", "oh"], ["Jehová,", "jehovah,"], ["clamaré,", "cry,"], ["y", "and"], ["no", "not"], ["oirás;", "hear;"], ["y", "and"], ["daré", "I-shall-give"], ["voces", "voices"], ["a", "to"], ["ti", "thee"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["la", "the"], ["violencia,", "violence,"], ["y", "and"], ["no", "not"], ["salvarás?", "thou?"]]},
  {num:3,words:[["¿Por", "by/for"], ["qué", "what"], ["me", "me"], ["haces", "doest"], ["ver", "see"], ["iniquidad", "iniquity"], ["y", "and"], ["haces", "doest"], ["que", "that"], ["contemple", "grievance?"], ["molestia?", "for?"], ["Y", "and"], ["destrucción", "destruction"], ["y", "and"], ["violencia", "violence"], ["hay", "there-is"], ["delante", "before"], ["de", "of"], ["mí,", "me,"], ["y", "and"], ["surgen", "raise"], ["pleito", "the"], ["y", "and"], ["contienda.", "strife."]]},
  {num:4,words:[["Por", "by/for"], ["lo", "it/him"], ["cual", "which"], ["la", "the"], ["ley", "law"], ["es", "is"], ["debilitada,", "and,"], ["y", "and"], ["el", "the"], ["juicio", "judgment"], ["nunca", "never"], ["sale", "goeth"], ["adelante;", "forward/henceforth;"], ["por", "by/for"], ["cuanto", "as-much-as"], ["el", "the"], ["malvado", "wicked"], ["asedia", "siege"], ["al", "to-the"], ["justo,", "just/righteous,"], ["por", "by/for"], ["eso", "that"], ["sale", "goeth"], ["torcido", "twined"], ["el", "the"], ["juicio.", "judgment."]]},
  {num:5,words:[["Mirad", "heed"], ["entre", "among"], ["las", "the"], ["naciones", "nations"], ["y", "and"], ["ved;", "see;"], ["y", "and"], ["maravillaos", "wonder"], ["y", "and"], ["asombraos,", "for,"], ["porque", "because"], ["haré", "I-shall-make"], ["una", "a"], ["obra", "work"], ["en", "in"], ["vuestros", "your"], ["días", "days"], ["que,", "that,"], ["aun", "even"], ["cuando", "when"], ["se", "[refl.]"], ["os", "you"], ["cuente,", "it,"], ["no", "not"], ["la", "the"], ["creeréis.", "believe."]]},
  {num:6,words:[["Porque", "because"], ["he", "I-have"], ["aquí,", "here,"], ["yo", "I"], ["levanto", "the"], ["a", "to"], ["los", "the"], ["caldeos,", "chaldees,"], ["nación", "nation"], ["feroz", "hasty"], ["e", "and"], ["impetuosa,", "shall,"], ["que", "that"], ["camina", "walketh"], ["por", "by/for"], ["la", "the"], ["anchura", "breadth"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["para", "for"], ["poseer", "possess"], ["las", "the"], ["moradas", "shall"], ["ajenas.", "theirs."]]},
  {num:7,words:[["Espantosa", "they"], ["es", "is"], ["y", "and"], ["terrible;", "awful;"], ["de", "of"], ["ella", "she"], ["misma", "same"], ["proceden", "of"], ["su", "his/her"], ["propio", "own"], ["juicio", "judgment"], ["y", "and"], ["su", "his/her"], ["propia", "own"], ["grandeza.", "greatness."]]},
  {num:8,words:[["Y", "and"], ["serán", "shall-be"], ["sus", "his/her"], ["caballos", "horses"], ["más", "more"], ["ligeros", "the"], ["que", "that"], ["leopardos", "leopards"], ["y", "and"], ["más", "more"], ["feroces", "wild"], ["que", "that"], ["lobos", "wolves"], ["nocturnos;", "wolves;"], ["y", "and"], ["sus", "his/her"], ["jinetes", "horsemen"], ["se", "[refl.]"], ["dispersarán;", "themselves;"], ["vendrán", "far"], ["de", "of"], ["lejos", "far"], ["sus", "his/her"], ["jinetes", "horsemen"], ["y", "and"], ["volarán", "shall"], ["como", "as"], ["águilas", "eagles"], ["que", "that"], ["se", "[refl.]"], ["apresuran", "that"], ["a", "to"], ["devorar.", "to."]]},
  {num:9,words:[["Toda", "all"], ["ella", "she"], ["vendrá", "shall-come"], ["para", "for"], ["hacer", "make/do"], ["violencia;", "violence;"], ["delante", "before"], ["de", "of"], ["sus", "his/her"], ["caras", "faces"], ["viento", "wind"], ["solano,", "wind,"], ["y", "and"], ["recogerá", "gather"], ["cautivos", "captives"], ["como", "as"], ["arena.", "sand."]]},
  {num:10,words:[["Y", "and"], ["escarnecerá", "they"], ["a", "to"], ["los", "the"], ["reyes,", "kings,"], ["y", "and"], ["de", "of"], ["los", "the"], ["príncipes", "princes"], ["hará", "shall-make"], ["burla;", "an;"], ["se", "[refl.]"], ["reirá", "they"], ["de", "of"], ["las", "the"], ["fortalezas,", "holds,"], ["y", "and"], ["levantará", "raise"], ["terraplén", "heap"], ["y", "and"], ["las", "the"], ["tomará.", "take."]]},
  {num:11,words:[["Luego", "then"], ["pasará", "through"], ["como", "as"], ["el", "the"], ["viento,", "wind,"], ["y", "and"], ["seguirá", "shall"], ["adelante", "forward/henceforth"], ["y", "and"], ["ofenderá,", "offend,"], ["atribuyendo", "imputing"], ["su", "his/her"], ["poder", "power/can"], ["a", "to"], ["su", "his/her"], ["dios.", "God."]]},
  {num:12,words:[["¿No", "not"], ["eres", "thou-art"], ["tú", "thou"], ["desde", "from"], ["el", "the"], ["principio,", "beginning,"], ["oh", "oh"], ["Jehová,", "jehovah,"], ["Dios", "God"], ["mío,", "mine,"], ["Santo", "holy"], ["mío?", "mine?"], ["No", "not"], ["moriremos.", "die."], ["Oh", "oh"], ["Jehová,", "jehovah,"], ["para", "for"], ["juicio", "judgment"], ["los", "the"], ["pusiste;", "hast;"], ["y", "and"], ["tú,", "thou,"], ["oh", "oh"], ["Roca,", "rock,"], ["los", "the"], ["has", "thou-hast"], ["puesto", "placed"], ["para", "for"], ["castigar.", "for."]]},
  {num:13,words:[["Muy", "very"], ["limpio", "clean"], ["eres", "thou-art"], ["de", "of"], ["ojos", "eyes"], ["para", "for"], ["ver", "see"], ["el", "the"], ["mal", "evil"], ["y", "and"], ["no", "not"], ["puedes", "canst"], ["ver", "see"], ["el", "the"], ["agravio.", "wrong."], ["¿Por", "by/for"], ["qué", "what"], ["toleras", "upon"], ["a", "to"], ["los", "the"], ["que", "that"], ["actúan", "and"], ["pérfidamente,", "holdest,"], ["y", "and"], ["callas", "tongue"], ["cuando", "when"], ["el", "the"], ["malvado", "wicked"], ["destruye", "them"], ["al", "to-the"], ["que", "that"], ["es", "is"], ["más", "more"], ["justo", "just/righteous"], ["que", "that"], ["él", "he"]]},
  {num:14,words:[["y", "and"], ["haces", "doest"], ["que", "that"], ["sean", "let-be"], ["los", "the"], ["hombres", "men"], ["como", "as"], ["los", "the"], ["peces", "fish"], ["del", "of-the"], ["mar,", "sea,"], ["como", "as"], ["reptiles", "creeping"], ["que", "that"], ["no", "not"], ["tienen", "have"], ["señor?", "Lord?"]]},
  {num:15,words:[["Sacará", "bring"], ["a", "to"], ["todos", "all"], ["con", "with"], ["anzuelo;", "them;"], ["los", "the"], ["recogerá", "gather"], ["con", "with"], ["su", "his/her"], ["red", "net"], ["y", "and"], ["los", "the"], ["juntará", "and"], ["en", "in"], ["su", "his/her"], ["malla,", "evil-her,"], ["por", "by/for"], ["lo", "it/him"], ["cual,", "which,"], ["se", "[refl.]"], ["alegrará", "rejoice"], ["y", "and"], ["se", "[refl.]"], ["regocijará.", "rejoice."]]},
  {num:16,words:[["Por", "by/for"], ["esto", "this"], ["ofrecerá", "blemish"], ["sacrificios", "sacrifices"], ["a", "to"], ["su", "his/her"], ["red", "net"], ["y", "and"], ["quemará", "burn"], ["incienso", "incense"], ["a", "to"], ["su", "his/her"], ["malla,", "evil-her,"], ["porque", "because"], ["con", "with"], ["ellas", "they"], ["engordó", "portion"], ["su", "his/her"], ["porción", "portion"], ["y", "and"], ["aumentó", "their"], ["su", "his/her"], ["comida.", "meat."]]},
  {num:17,words:[["¿Vaciará", "shall"], ["por", "by/for"], ["eso", "that"], ["su", "his/her"], ["red", "net"], ["y", "and"], ["seguirá", "shall"], ["aniquilando", "spare"], ["sin", "without"], ["piedad", "godliness"], ["a", "to"], ["las", "the"], ["naciones?", "nations?"]]},
];
renderVerseSet(v1, 'hab-ch1-verses');

var v2 = [
  {num:1,words:[["En", "in"], ["mi", "my"], ["puesto", "placed"], ["de", "of"], ["guardia", "nebuzaradan"], ["estaré,", "will,"], ["y", "and"], ["sobre", "upon"], ["la", "the"], ["fortaleza", "castle"], ["afirmaré", "the"], ["el", "the"], ["pie,", "foot,"], ["y", "and"], ["velaré", "watch"], ["para", "for"], ["ver", "see"], ["lo", "it/him"], ["que", "that"], ["él", "he"], ["me", "me"], ["dirá", "shall-say"], ["y", "and"], ["lo", "it/him"], ["que", "that"], ["he", "I-have"], ["de", "of"], ["responder", "answer"], ["cuando", "when"], ["sea", "let-be/be"], ["reprendido.", "and."]]},
  {num:2,words:[["Y", "and"], ["Jehová", "jehovah"], ["me", "me"], ["respondió", "answered"], ["y", "and"], ["dijo:", "said:"], ["Escribe", "write"], ["la", "the"], ["visión", "vision"], ["y", "and"], ["grábala", "and"], ["claramente", "plainly"], ["en", "in"], ["tablas", "boards"], ["para", "for"], ["que", "that"], ["corra", "he"], ["el", "the"], ["que", "that"], ["lea", "leah"], ["en", "in"], ["ella.", "she."]]},
  {num:3,words:[["Aunque", "although"], ["la", "the"], ["visión", "vision"], ["es", "is"], ["aún", "still/yet"], ["para", "for"], ["un", "a"], ["tiempo", "time"], ["señalado,", "appointed,"], ["al", "to-the"], ["final", "end"], ["hablará", "speak"], ["y", "and"], ["no", "not"], ["mentirá;", "though;"], ["aunque", "although"], ["se", "[refl.]"], ["tarde,", "evening,"], ["espérala,", "it,"], ["porque", "because"], ["sin", "without"], ["duda", "surely"], ["vendrá;", "shall-come;"], ["no", "not"], ["tardará.", "tarry."]]},
  {num:4,words:[["He", "I-have"], ["aquí,", "here,"], ["se", "[refl.]"], ["enorgullece", "is"], ["aquel", "that"], ["cuya", "whose"], ["alma", "soul"], ["no", "not"], ["es", "is"], ["recta;", "the;"], ["mas", "but"], ["el", "the"], ["justo", "just/righteous"], ["por", "by/for"], ["su", "his/her"], ["fe", "faith"], ["vivirá.", "live."]]},
  {num:5,words:[["Y", "and"], ["también,", "also,"], ["el", "the"], ["vino", "wine"], ["traiciona", "transgresseth"], ["al", "to-the"], ["hombre", "man"], ["soberbio", "proud"], ["de", "of"], ["modo", "manner/way"], ["que", "that"], ["no", "not"], ["permanece;", "abideth;"], ["ensancha", "keepeth"], ["su", "his/her"], ["deseo", "desire"], ["como", "as"], ["el", "the"], ["Seol", "grave"], ["y", "and"], ["es", "is"], ["como", "as"], ["la", "the"], ["muerte", "death"], ["que", "that"], ["no", "not"], ["se", "[refl.]"], ["sacia,", "is,"], ["sino", "but"], ["que", "that"], ["reúne", "together"], ["para", "for"], ["sí", "yea"], ["todas", "all"], ["las", "the"], ["naciones", "nations"], ["y", "and"], ["recoge", "gathereth"], ["para", "for"], ["sí", "yea"], ["todos", "all"], ["los", "the"], ["pueblos.", "peoples."]]},
  {num:6,words:[["¿No", "not"], ["han", "have"], ["de", "of"], ["levantar", "raise"], ["todos", "all"], ["estos", "these"], ["refrán", "proverb"], ["contra", "against"], ["él", "he"], ["y", "and"], ["sarcasmos", "taunting"], ["contra", "against"], ["él?", "he?"], ["Y", "and"], ["dirán:", "say:"], ["¡Ay", "wo"], ["del", "of-the"], ["que", "that"], ["multiplica", "increaseth"], ["lo", "it/him"], ["que", "that"], ["no", "not"], ["es", "is"], ["suyo!", "own!"], ["¿Hasta", "until"], ["cuándo", "when"], ["seguirá", "shall"], ["acumulando", "that"], ["sobre", "upon"], ["sí", "yea"], ["prendas", "pledges"], ["empeñadas?", "clay?"]]},
  {num:7,words:[["¿No", "not"], ["se", "[refl.]"], ["levantarán", "rise"], ["de", "of"], ["repente", "suddenly"], ["tus", "thy"], ["acreedores,", "that,"], ["y", "and"], ["se", "[refl.]"], ["despertarán", "thee,"], ["los", "the"], ["que", "that"], ["te", "thee"], ["hagan", "do"], ["temblar?", "tremble?"], ["Y", "and"], ["tú", "thou"], ["serás", "thou-shalt-be"], ["para", "for"], ["ellos", "they"], ["objeto", "intent"], ["de", "of"], ["rapiña.", "to."]]},
  {num:8,words:[["Por", "by/for"], ["cuanto", "as-much-as"], ["tú", "thou"], ["has", "thou-hast"], ["despojado", "that"], ["a", "to"], ["muchas", "many"], ["naciones,", "nations,"], ["todos", "all"], ["los", "the"], ["otros", "others"], ["pueblos", "peoples"], ["te", "thee"], ["despojarán,", "people,"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["la", "the"], ["sangre", "blood"], ["de", "of"], ["los", "the"], ["hombres", "men"], ["y", "and"], ["de", "of"], ["la", "the"], ["violencia", "violence"], ["hecha", "done"], ["a", "to"], ["la", "the"], ["tierra,", "land/earth,"], ["a", "to"], ["las", "the"], ["ciudades", "cities"], ["y", "and"], ["a", "to"], ["todos", "all"], ["los", "the"], ["que", "that"], ["moraban", "which"], ["en", "in"], ["ellas.", "they."]]},
  {num:9,words:[["¡Ay", "wo"], ["del", "of-the"], ["que", "that"], ["obtiene", "coveteth"], ["injusta", "evil"], ["ganancia", "gain"], ["para", "for"], ["su", "his/her"], ["casa,", "house,"], ["para", "for"], ["poner", "put/place"], ["en", "in"], ["alto", "high"], ["su", "his/her"], ["nido,", "nest,"], ["para", "for"], ["escaparse", "escape-[refl.]"], ["del", "of-the"], ["poder", "power/can"], ["del", "of-the"], ["mal!", "evil!"]]},
  {num:10,words:[["Has", "thou-hast"], ["tramado", "hast"], ["vergüenza", "shame"], ["para", "for"], ["tu", "thy"], ["casa", "house"], ["al", "to-the"], ["destruir", "destroy"], ["a", "to"], ["muchos", "many"], ["pueblos,", "peoples,"], ["y", "and"], ["has", "thou-hast"], ["pecado", "sin"], ["contra", "against"], ["tu", "thy"], ["alma.", "soul."]]},
  {num:11,words:[["Porque", "because"], ["la", "the"], ["piedra", "stone"], ["clamará", "cry"], ["desde", "from"], ["el", "the"], ["muro,", "wall,"], ["y", "and"], ["la", "the"], ["viga", "mote"], ["del", "of-the"], ["enmaderado", "timber"], ["le", "him/her"], ["responderá.", "answer."]]},
  {num:12,words:[["¡Ay", "wo"], ["del", "of-the"], ["que", "that"], ["edifica", "build"], ["la", "the"], ["ciudad", "city"], ["con", "with"], ["sangre", "blood"], ["y", "and"], ["del", "of-the"], ["que", "that"], ["funda", "stablisheth"], ["una", "a"], ["aldea", "village"], ["con", "with"], ["injusticia!", "unrighteousness!"]]},
  {num:13,words:[["He", "I-have"], ["aquí,", "here,"], ["¿no", "not"], ["es", "is"], ["esto", "this"], ["de", "of"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["que", "that"], ["los", "the"], ["pueblos", "peoples"], ["trabajen", "the"], ["para", "for"], ["el", "the"], ["fuego", "fire"], ["y", "and"], ["las", "the"], ["naciones", "nations"], ["se", "[refl.]"], ["fatiguen", "for"], ["en", "in"], ["vano?", "vain?"]]},
  {num:14,words:[["Porque", "because"], ["la", "the"], ["tierra", "land/earth"], ["estará", "shall-be"], ["llena", "full"], ["del", "of-the"], ["conocimiento", "knowledge"], ["de", "of"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["Jehová", "jehovah"], ["como", "as"], ["las", "the"], ["aguas", "waters"], ["cubren", "of"], ["el", "the"], ["mar.", "sea."]]},
  {num:15,words:[["¡Ay", "wo"], ["del", "of-the"], ["que", "that"], ["da", "gives"], ["de", "of"], ["beber", "drink"], ["a", "to"], ["su", "his/her"], ["prójimo!", "neighbor!"], ["¡Ay", "wo"], ["de", "of"], ["ti,", "thee,"], ["que", "that"], ["le", "him/her"], ["acercas", "abouts"], ["tu", "thy"], ["hiel", "gall"], ["y", "and"], ["le", "him/her"], ["embriagas", "mayest"], ["para", "for"], ["mirar", "look"], ["su", "his/her"], ["desnudez!", "nakedness!"]]},
  {num:16,words:[["Te", "thee"], ["has", "thou-hast"], ["llenado", "filled"], ["de", "of"], ["deshonra", "shame"], ["más", "more"], ["que", "that"], ["de", "of"], ["honra;", "honor;"], ["bebe", "drinketh"], ["tú", "thou"], ["también,", "also,"], ["y", "and"], ["serás", "thou-shalt-be"], ["como", "as"], ["incircunciso;", "uncircumcised;"], ["la", "the"], ["copa", "cup"], ["de", "of"], ["la", "the"], ["mano", "hand"], ["derecha", "right"], ["de", "of"], ["Jehová", "jehovah"], ["se", "[refl.]"], ["volverá", "return"], ["contra", "against"], ["ti,", "thee,"], ["y", "and"], ["la", "the"], ["deshonra", "shall"], ["caerá", "fall"], ["sobre", "upon"], ["tu", "thy"], ["gloria.", "glory."]]},
  {num:17,words:[["Porque", "because"], ["la", "the"], ["violencia", "violence"], ["del", "of-the"], ["Líbano", "lebanon"], ["te", "thee"], ["cubrirá,", "cover,"], ["y", "and"], ["la", "the"], ["destrucción", "destruction"], ["de", "of"], ["las", "the"], ["fieras", "beasts"], ["las", "the"], ["aterrorizará", "beasts,"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["la", "the"], ["sangre", "blood"], ["de", "of"], ["los", "the"], ["hombres", "men"], ["y", "and"], ["de", "of"], ["la", "the"], ["violencia", "violence"], ["hecha", "done"], ["a", "to"], ["la", "the"], ["tierra,", "land/earth,"], ["a", "to"], ["las", "the"], ["ciudades", "cities"], ["y", "and"], ["a", "to"], ["todos", "all"], ["los", "the"], ["que", "that"], ["en", "in"], ["ellas", "they"], ["moran.", "dwell."]]},
  {num:18,words:[["¿De", "of"], ["qué", "what"], ["sirve", "nothing"], ["la", "the"], ["imagen", "image"], ["tallada", "graven"], ["que", "that"], ["talló", "maker"], ["el", "the"], ["que", "that"], ["la", "the"], ["hizo,", "made/did,"], ["la", "the"], ["imagen", "image"], ["de", "of"], ["fundición", "molten"], ["y", "and"], ["maestra", "teacher"], ["de", "of"], ["mentiras,", "lyings,"], ["para", "for"], ["que", "that"], ["haciendo", "doing/making"], ["imágenes", "groves"], ["mudas", "of"], ["confíe", "trusteth"], ["el", "the"], ["hacedor", "maker"], ["en", "in"], ["su", "his/her"], ["obra?", "work?"]]},
  {num:19,words:[["¡Ay", "wo"], ["del", "of-the"], ["que", "that"], ["dice", "says"], ["al", "to-the"], ["palo:", "staff:"], ["Despiértate;", "wood;"], ["y", "and"], ["a", "to"], ["la", "the"], ["piedra", "stone"], ["muda:", "dumb:"], ["Levántate!", "arise!"], ["¿Podrá", "able"], ["él", "he"], ["enseñar?", "teach?"], ["He", "I-have"], ["aquí,", "here,"], ["está", "is"], ["cubierto", "covered"], ["de", "of"], ["oro", "gold"], ["y", "and"], ["de", "of"], ["plata,", "silver,"], ["y", "and"], ["no", "not"], ["hay", "there-is"], ["espíritu", "Spirit"], ["dentro", "within"], ["de", "of"], ["él.", "he."]]},
  {num:20,words:[["Mas", "but"], ["Jehová", "jehovah"], ["está", "is"], ["en", "in"], ["su", "his/her"], ["santo", "holy"], ["templo:", "temple:"], ["¡Calle", "street"], ["delante", "before"], ["de", "of"], ["él", "he"], ["toda", "all"], ["la", "the"], ["tierra!", "land/earth!"]]},
];
renderVerseSet(v2, 'hab-ch2-verses');

var v3 = [
  {num:1,words:[["Oración", "prayer"], ["del", "of-the"], ["profeta", "prophet"], ["Habacuc,", "the,"], ["sobre", "upon"], ["Sigionot.", "shigionoth."]]},
  {num:2,words:[["Oh", "oh"], ["Jehová,", "jehovah,"], ["he", "I-have"], ["oído", "heard"], ["tu", "thy"], ["palabra", "word"], ["y", "and"], ["temí.Oh", "was"], ["Jehová,", "jehovah,"], ["aviva", "o"], ["tu", "thy"], ["obra", "work"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["los", "the"], ["tiempos,en", "of"], ["medio", "midst"], ["de", "of"], ["los", "the"], ["tiempos", "times"], ["hazla", "do-her"], ["conocer;en", "the"], ["la", "the"], ["ira", "wrath"], ["acuérdate", "remember"], ["de", "of"], ["la", "the"], ["misericordia.", "mercy."]]},
  {num:3,words:[["Dios", "God"], ["viene", "comes"], ["de", "of"], ["Temán,y", "teman,"], ["el", "the"], ["Santo", "holy"], ["desde", "from"], ["el", "the"], ["monte", "mount"], ["Parán.", "paran."], ["SelahSu", "selah."], ["gloria", "glory"], ["cubrió", "covered"], ["los", "the"], ["cielos,y", "the"], ["la", "the"], ["tierra", "land/earth"], ["se", "[refl.]"], ["llenó", "filled"], ["de", "of"], ["su", "his/her"], ["alabanza.", "praise."]]},
  {num:4,words:[["Y", "and"], ["su", "his/her"], ["resplandor", "luster"], ["es", "is"], ["como", "as"], ["la", "the"], ["luz,rayos", "had"], ["brillantes", "horns"], ["salen", "forth"], ["de", "of"], ["su", "his/her"], ["mano,y", "hand"], ["allí", "there"], ["está", "is"], ["escondido", "hid"], ["su", "his/her"], ["poder.", "power/can."]]},
  {num:5,words:[["Delante", "before"], ["de", "of"], ["su", "his/her"], ["rostro", "face"], ["va", "goes"], ["la", "the"], ["mortandad,y", "coals"], ["llamaradas", "went"], ["salen", "forth"], ["tras", "after"], ["sus", "his/her"], ["pies.", "feet."]]},
  {num:6,words:[["Se", "[refl.]"], ["levantó", "arose"], ["y", "and"], ["midió", "measured"], ["la", "the"], ["tierra;miró", "he"], ["e", "and"], ["hizo", "made/did"], ["temblar", "tremble"], ["las", "the"], ["naciones;y", "heathen"], ["los", "the"], ["montes", "mountains"], ["antiguos", "ancient"], ["fueron", "were"], ["desmenuzados;los", "scattered,"], ["collados", "hills"], ["antiguos", "ancient"], ["se", "[refl.]"], ["inclinaron.Sus", "bow:"], ["caminos", "ways"], ["son", "are"], ["eternos.", "eternal."]]},
  {num:7,words:[["He", "I-have"], ["visto", "seen"], ["las", "the"], ["tiendas", "tents"], ["de", "of"], ["Cusán", "in"], ["en", "in"], ["aflicción;las", "affliction-them"], ["cortinas", "curtains"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Madián", "midian"], ["temblaron.", "the."]]},
  {num:8,words:[["¿Se", "[refl.]"], ["airó", "the"], ["Jehová", "jehovah"], ["contra", "against"], ["los", "the"], ["ríos?¿Contra", "rivers?"], ["los", "the"], ["ríos", "rivers"], ["fue", "was/went"], ["tu", "thy"], ["enojo?¿Fue", "rivers?"], ["tu", "thy"], ["ira", "wrath"], ["contra", "against"], ["el", "the"], ["mar,para", "sea,"], ["que", "that"], ["montases", "thou"], ["en", "in"], ["tus", "thy"], ["caballosy", "thine"], ["en", "in"], ["tus", "thy"], ["carros", "chariots"], ["de", "of"], ["salvación?", "salvation?"]]},
  {num:9,words:[["Se", "[refl.]"], ["desnudó", "bow"], ["enteramente", "utterly"], ["tu", "thy"], ["arco,según", "naked,"], ["los", "the"], ["juramentos", "oaths"], ["de", "of"], ["las", "the"], ["saetas", "arrows"], ["de", "of"], ["tu", "thy"], ["palabra.", "word."], ["SelahHendiste", "thou"], ["la", "the"], ["tierra", "land/earth"], ["con", "with"], ["ríos.", "rivers."]]},
  {num:10,words:[["Te", "thee"], ["vieron", "saw"], ["los", "the"], ["montes", "mountains"], ["y", "and"], ["temblaron;pasó", "the"], ["la", "the"], ["inundación", "of"], ["de", "of"], ["las", "the"], ["aguas;el", "by:"], ["abismo", "deep"], ["dio", "gave"], ["su", "his/her"], ["voz;a", "voice,"], ["lo", "it/him"], ["alto", "high"], ["alzó", "lifted"], ["sus", "his/her"], ["manos.", "hands."]]},
  {num:11,words:[["El", "the"], ["sol", "sun"], ["y", "and"], ["la", "the"], ["luna", "moon"], ["se", "[refl.]"], ["detuvieron", "stood"], ["en", "in"], ["su", "his/her"], ["cenit;a", "little-supper"], ["la", "the"], ["luz", "light"], ["de", "of"], ["tus", "thy"], ["saetas", "arrows"], ["anduvierony", "and"], ["al", "to-the"], ["resplandor", "luster"], ["de", "of"], ["tu", "thy"], ["refulgente", "glittering"], ["lanza.", "spear."]]},
  {num:12,words:[["Con", "with"], ["ira", "wrath"], ["hollaste", "through"], ["la", "the"], ["tierra;con", "indignation,"], ["furor", "fury"], ["trillaste", "thresh"], ["las", "the"], ["naciones.", "nations."]]},
  {num:13,words:[["Saliste", "out"], ["para", "for"], ["salvar", "save"], ["a", "to"], ["tu", "thy"], ["pueblo,para", "thy"], ["salvar", "save"], ["con", "with"], ["tu", "thy"], ["ungido.Traspasaste", "thine"], ["la", "the"], ["cabeza", "head"], ["de", "of"], ["la", "the"], ["casa", "house"], ["del", "of-the"], ["malvado,descubriendo", "the"], ["el", "the"], ["cimiento", "foundation"], ["hasta", "until"], ["el", "the"], ["cuello.", "neck."], ["Selah", "selah"]]},
  {num:14,words:[["Traspasaste", "thou"], ["con", "with"], ["sus", "his/her"], ["propias", "own"], ["saetas", "arrows"], ["las", "the"], ["cabezas", "heads"], ["de", "of"], ["sus", "his/her"], ["guerreros,que", "they"], ["como", "as"], ["tempestad", "storm"], ["acometieron", "the"], ["para", "for"], ["dispersarme;su", "to"], ["regocijo", "rejoicing"], ["era", "was"], ["como", "as"], ["para", "for"], ["devorar", "to"], ["al", "to-the"], ["pobre", "poor"], ["encubiertamente.", "secretly."]]},
  {num:15,words:[["Caminaste", "thou"], ["en", "in"], ["el", "the"], ["mar", "sea"], ["con", "with"], ["tus", "thy"], ["caballos,sobre", "thine"], ["la", "the"], ["mole", "through"], ["de", "of"], ["las", "the"], ["grandes", "great"], ["aguas.", "waters."]]},
  {num:16,words:[["Oí,", "heard,"], ["y", "and"], ["se", "[refl.]"], ["conmovieron", "belly"], ["mis", "my"], ["entrañas;a", "lips"], ["la", "the"], ["voz", "voice"], ["temblaron", "the"], ["mis", "my"], ["labios;pudrición", "into"], ["entró", "entered"], ["en", "in"], ["mis", "my"], ["huesos,y", "trembled"], ["dentro", "within"], ["de", "of"], ["mí", "me"], ["me", "me"], ["estremecí.Tranquilo", "in"], ["espero", "trust"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["angustiaque", "up"], ["vendrá", "shall-come"], ["sobre", "upon"], ["el", "the"], ["pueblo", "people"], ["que", "that"], ["nos", "us"], ["ataca.", "troops."]]},
  {num:17,words:[["Aunque", "although"], ["la", "the"], ["higuera", "fig"], ["no", "not"], ["florezcani", "blossom,"], ["en", "in"], ["las", "the"], ["vides", "and"], ["haya", "let-there-be"], ["frutos,aunque", "vines;"], ["falle", "the"], ["la", "the"], ["cosecha", "harvest"], ["del", "of-the"], ["olivo,y", "fail,"], ["los", "the"], ["campos", "fields"], ["no", "not"], ["produzcan", "the"], ["alimento,y", "meat;"], ["las", "the"], ["ovejas", "sheep"], ["sean", "let-be"], ["quitadas", "taken"], ["del", "of-the"], ["redily", "fold,"], ["no", "not"], ["haya", "let-there-be"], ["vacas", "kine"], ["en", "in"], ["los", "the"], ["establos,", "stalls,"]]},
  {num:18,words:[["con", "with"], ["todo", "all"], ["yo", "I"], ["me", "me"], ["alegraré", "in"], ["en", "in"], ["Jehováy", "o"], ["me", "me"], ["regocijaré", "rejoice"], ["en", "in"], ["el", "the"], ["Dios", "God"], ["de", "of"], ["mi", "my"], ["salvación.", "salvation."]]},
  {num:19,words:[["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["es", "is"], ["mi", "my"], ["fortaleza,y", "make"], ["él", "he"], ["hará", "shall-make"], ["mis", "my"], ["pies", "feet"], ["como", "as"], ["de", "of"], ["ciervasy", "to"], ["me", "me"], ["hará", "shall-make"], ["andar", "walk"], ["sobre", "upon"], ["mis", "my"], ["lugares", "places"], ["altos.", "high."]]},
];
renderVerseSet(v3, 'hab-ch3-verses');

})();
