(function() {
var v1 = [
  {num:1,words:[["En","in"],["el","the"],["año","year"],["segundo","second"],["del","of-the"],["rey","king"],["Darío,","Darius,"],["en","in"],["el","the"],["mes","month"],["sexto,","sixth,"],["en","in"],["el","the"],["primer","first"],["día","day"],["del","of-the"],["mes,","month,"],["vino","wine"],["la","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["por","by"],["medio","midst"],["del","of-the"],["profeta","prophet"],["Hageo","Haggai"],["a","to"],["Zorobabel","Zerubbabel"],["hijo","son"],["de","of"],["Salatiel,","Shealtiel,"],["gobernador","governor"],["de","of"],["Judá,","Judah,"],["y","and"],["a","to"],["Josué","Joshua"],["hijo","son"],["de","of"],["Josadac,","Zerubbabel,"],["sumo","high"],["sacerdote,","priest,"],["diciendo:","saying:"]]},
  {num:2,words:[["Así","thus"],["ha","has"],["hablado","spoken"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["diciendo:","saying:"],["Este","this"],["pueblo","people"],["dice:","says:"],["No","not"],["ha","has"],["llegado","come"],["aún","yet"],["el","the"],["tiempo,","time,"],["el","the"],["tiempo","time"],["en que","that"],["la","the"],["casa","house"],["de","of"],["Jehová","jehovah"],["sea","be"],["reedificada.","built."]]},
  {num:3,words:[["Entonces", "then"], ["vino", "wine"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["por","by"], ["medio", "midst"], ["del", "of-the"], ["profeta", "prophet"], ["Hageo,","Haggai,"], ["diciendo:", "saying:"]]},
  {num:4,words:[["¿Es","is"],["acaso","perhaps"],["para","for"],["vosotros","you"],["tiempo","time"],["de","of"],["morar","dwell"],["en","in"],["vuestras","your"],["casas","houses"],["enmaderadas,","cieled,"],["mientras que","while"],["esta","this"],["casa","house"],["está","is"],["desierta?","desolate?"]]},
  {num:5,words:[["Pues","for"],["así","thus"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos:","armies:"],["Meditad","you-hosts"],["bien","well"],["sobre","upon"],["vuestros","your"],["caminos.","ways."]]},
  {num:6,words:[["Sembráis","you"],["mucho","much"],["y","and"],["recogéis","you-gather"],["poco;","little;"],["coméis","you-eat"],["y","and"],["no","not"],["quedáis","you-remain"],["satisfechos;","satisfy;"],["bebéis","enough"],["y","and"],["no","not"],["os","you"],["saciáis;","not;"],["os","you"],["vestís","drink"],["y","and"],["no","not"],["conseguís","you-achieve"],["abrigaros;","keep warm;"],["y","and"],["el","the"],["que","that"],["trabaja","work/labor"],["a","to"],["jornal","earns"],["recibe","receives"],["su","his"],["jornal","it"],["en","in"],["saco","brought-out"],["roto.","broken."]]},
  {num:7,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos:","armies:"],["Meditad","you-hosts"],["bien","well"],["sobre","upon"],["vuestros","your"],["caminos.","ways."]]},
  {num:8,words:[["Subid","you-go"],["al","to-the"],["monte,","mount,"],["y","and"],["traed","you-bring"],["madera","wood"],["y","and"],["reedificad","build"],["la","the"],["casa;","house;"],["y","and"],["me","me"],["complaceré","take"],["en","in"],["ella","she"],["y","and"],["seré","I will be"],["glorificado,","glorified,"],["ha","has"],["dicho","said"],["Jehová.","jehovah."]]},
  {num:9,words:[["Buscáis","you-seek"],["mucho,","much,"],["y","and"],["he aquí","behold"],["halláis","you-find"],["poco;","little;"],["y","and"],["lo","it"],["que","that"],["traéis","you-bring"],["a","to"],["casa","house"],["lo","it"],["disperso","home"],["con","with"],["un","a"],["soplo.","of."],["¿Por","for"],["qué?,","what?,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."],["Porque","because"],["mi","my"],["casa","house"],["está","is"],["desierta","desolate"],["mientras que","while"],["cada","each"],["uno","one"],["de","of"],["vosotros","you"],["corre","runs"],["a","to"],["su","his"],["propia","own"],["casa.","house."]]},
  {num:10,words:[["Por eso","therefore"],["se","himself"],["detuvo","stood"],["de","of"],["los","the"],["cielos","heavens"],["sobre","upon"],["vosotros","you"],["la","the"],["lluvia,","rain,"],["y","and"],["la","the"],["tierra","earth"],["detuvo","stood"],["sus","her"],["frutos.","fruits."]]},
  {num:11,words:[["Y","and"],["llamé","I-called"],["la","the"],["sequía","drought"],["sobre","upon"],["esta","this"],["tierra","land"],["y","and"],["sobre","upon"],["los","the"],["montes,","mountains,"],["y","and"],["sobre","upon"],["el","the"],["trigo,","wheat,"],["y","and"],["sobre","upon"],["el","the"],["mosto,","corn,"],["y","and"],["sobre","upon"],["el","the"],["aceite,","oil,"],["y","and"],["sobre","upon"],["todo","all"],["lo","it/him"],["que","that"],["la","the"],["tierra","land"],["produce,","brings,"],["y","and"],["sobre","upon"],["los","the"],["hombres","men"],["y","and"],["sobre","upon"],["las","the"],["bestias,","beasts,"],["y","and"],["sobre","upon"],["todo","all"],["trabajo","work"],["de","of"],["las","the"],["manos.","hands."]]},
  {num:12,words:[["Entonces","then"],["Zorobabel","Zerubbabel"],["hijo","son"],["de","of"],["Salatiel,","Shealtiel,"],["y","and"],["el","the"],["sumo","high"],["sacerdote","priest"],["Josué","Joshua"],["hijo","son"],["de","of"],["Josadac","Zerubbabel"],["y","and"],["todo","all"],["el","the"],["resto","remnant"],["del","of-the"],["pueblo","people"],["obedecieron","they-obeyed"],["la","the"],["voz","voice"],["de","of"],["Jehová","jehovah"],["su","their"],["Dios","God"],["y","and"],["las","the"],["palabras","words"],["del","of-the"],["profeta","prophet"],["Hageo,","Haggai,"],["como","as"],["lo","him"],["había","had"],["mandado","commanded"],["Jehová","jehovah"],["su","their"],["Dios;","God;"],["y","and"],["temió","feared"],["el","the"],["pueblo","people"],["delante","before"],["de","of"],["Jehová.","jehovah."]]},
  {num:13,words:[["Entonces","then"],["Hageo,","Haggai,"],["mensajero","messenger"],["de","of"],["Jehová,","jehovah,"],["dio","gave"],["el","the"],["mensaje","message"],["de","of"],["Jehová","jehovah"],["al","to-the"],["pueblo,","people,"],["diciendo:","saying:"],["Yo","I"],["estoy","am"],["con","with"],["vosotros,","you,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:14,words:[["Y","and"],["despertó","awoke"],["Jehová","jehovah"],["el","the"],["espíritu","Spirit"],["de","of"],["Zorobabel","Zerubbabel"],["hijo","son"],["de","of"],["Salatiel,","Shealtiel,"],["gobernador","governor"],["de","of"],["Judá,","Judah,"],["y","and"],["el","the"],["espíritu","Spirit"],["del","of-the"],["sumo","high"],["sacerdote","priest"],["Josué","Joshua"],["hijo","son"],["de","of"],["Josadac","Zerubbabel"],["y","and"],["el","the"],["espíritu","Spirit"],["de","of"],["todo","all"],["el","the"],["resto","remnant"],["del","of-the"],["pueblo;","people;"],["y","and"],["vinieron","they-came"],["y","and"],["trabajaron","they-worked"],["en","in"],["la","the"],["casa","house"],["de","of"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["su","their"],["Dios,","God,"]]},
  {num:15,words:[["en","in"],["el","the"],["día","day"],["veinticuatro","course"],["del","of-the"],["mes","month"],["sexto,","sixth,"],["en","in"],["el","the"],["segundo","second"],["año","year"],["del","of-the"],["rey","king"],["Darío.","Darius."]]},
];
renderVerseSet(v1, 'hag-ch1-verses');

var v2 = [
  {num:1,words:[["En", "in"], ["el", "the"], ["mes", "month"], ["séptimo,", "seventh,"], ["a", "to"], ["los", "the"], ["veintiún", "and"], ["días", "days"], ["del", "of-the"], ["mes,", "month,"], ["vino", "wine"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["por","by"], ["medio", "midst"], ["del", "of-the"], ["profeta", "prophet"], ["Hageo,","Haggai,"], ["diciendo:", "saying:"]]},
  {num:2,words:[["Habla","speaks"],["ahora","now"],["a","to"],["Zorobabel","Zerubbabel"],["hijo","son"],["de","of"],["Salatiel,","Shealtiel,"],["gobernador","governor"],["de","of"],["Judá,","Judah,"],["y","and"],["al","to-the"],["sumo","high"],["sacerdote","priest"],["Josué","Joshua"],["hijo","son"],["de","of"],["Josadac","Zerubbabel"],["y","and"],["al","to-the"],["resto","remnant"],["del","of-the"],["pueblo,","people,"],["y","and"],["diles:","speak:"]]},
  {num:3,words:[["¿Quién","who"],["ha","has"],["quedado","remained"],["entre","among"],["vosotros","you"],["que","that"],["haya","let-there-be"],["visto","seen"],["esta","this"],["casa","house"],["en","in"],["su","her"],["gloria","glory"],["primera?","first?"],["¿Y","and"],["cómo","how"],["la","the"],["veis","see"],["ahora?","now?"],["¿No","not"],["es","is"],["ella","she"],["como","as"],["nada","nothing"],["delante","before"],["de","of"],["vuestros","your"],["ojos?","eyes?"]]},
  {num:4,words:[["Pues","for"],["ahora,","now,"],["Zorobabel,","Zerubbabel,"],["esfuérzate,","courage,"],["dice","says"],["Jehová;","jehovah;"],["esfuérzate","courage"],["tú","you"],["también","also"],["Josué","Joshua"],["hijo","son"],["de","of"],["Josadac,","Zerubbabel,"],["sumo","high"],["sacerdote;","priest;"],["y","and"],["cobrad","priest"],["ánimo,","cheer,"],["pueblo","people"],["todo","all"],["de","of"],["la","the"],["tierra,","land,"],["dice","says"],["Jehová,","jehovah,"],["y","and"],["trabajad;","you-work;"],["porque","because"],["yo","I"],["estoy","am"],["con","with"],["vosotros,","you,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:5,words:[["Según","according-to"],["el","the"],["convenio","covenant"],["que","that"],["concerté","I-arranged"],["con","with"],["vosotros","you"],["cuando","when"],["salisteis","you-leaved"],["de","of"],["Egipto,","Egypt,"],["así","thus"],["mi","my"],["espíritu","Spirit"],["estará","shall-be"],["en","in"],["medio","midst"],["de","of"],["vosotros;","you;"],["no","not"],["temáis.","afraid."]]},
  {num:6,words:[["Porque","because"],["así","thus"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos:","armies:"],["Dentro","within"],["de","of"],["poco","little"],["yo","I"],["haré","I will make"],["temblar","to-tremble"],["los","the"],["cielos","heavens"],["y","and"],["la","the"],["tierra,","land,"],["y","and"],["el","the"],["mar","sea"],["y","and"],["la","the"],["tierra","land"],["seca;","dries;"]]},
  {num:7,words:[["y","and"],["haré","I will make"],["temblar","to-tremble"],["a","to"],["todas","all"],["las","the"],["naciones,","nations,"],["y","and"],["vendrá","shall-come"],["el","the"],["Deseado","desired"],["de","of"],["todas","all"],["las","the"],["naciones;","nations;"],["y","and"],["llenaré","I-will-fill"],["de","of"],["gloria","glory"],["esta","this"],["casa,","house,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:8,words:[["Mía", "mother"], ["es", "is"], ["la", "the"], ["plata", "silver"], ["y", "and"], ["mío", "mine"], ["es", "is"], ["el", "the"], ["oro,", "gold,"], ["dice", "says"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos.", "armies."]]},
  {num:9,words:[["La", "the"], ["gloria", "glory"], ["de", "of"], ["esta", "this"], ["última", "last"], ["casa", "house"], ["será", "shall-be"], ["mayor", "greater"], ["que", "that"], ["la", "the"], ["de", "of"], ["la", "the"], ["primera,", "first,"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos;", "armies;"], ["y", "and"], ["daré", "I-shall-give"], ["paz", "peace"], ["en", "in"], ["este", "this"], ["lugar,", "place,"], ["dice", "says"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos.", "armies."]]},
  {num:10,words:[["A","to"],["los","the"],["veinticuatro","course"],["días","days"],["del","of-the"],["noveno","ninth"],["mes,","month,"],["en","in"],["el","the"],["segundo","second"],["año","year"],["de","of"],["Darío,","Darius,"],["vino","wine"],["la","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["por","by"],["medio","midst"],["del","of-the"],["profeta","prophet"],["Hageo,","Haggai,"],["diciendo:","saying:"]]},
  {num:11,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos:", "armies:"], ["Pregunta", "ask"], ["ahora", "now"], ["a", "to"], ["los", "the"], ["sacerdotes", "priests"], ["acerca", "about"], ["de", "of"], ["la", "the"], ["ley,", "law,"], ["y", "and"], ["diles:", "speak:"]]},
  {num:12,words:[["Si","if"],["alguno","some"],["lleva","brings"],["carne","flesh"],["consagrada","holy"],["en","in"],["la","the"],["falda","skirt"],["de","of"],["su","his"],["ropa,","garment,"],["y","and"],["con","with"],["el","the"],["vuelo","flight"],["de","of"],["ella","she"],["toca","touches"],["el","the"],["pan,","bread,"],["o","or"],["la","the"],["comida,","meat,"],["o","or"],["el","the"],["vino,","wine,"],["o","or"],["el","the"],["aceite","oil"],["o","or"],["cualquier","any"],["otra","other"],["comida,","meat,"],["¿acaso","perhaps"],["quedarán","they-will-remain"],["estas","these"],["cosas","things"],["consagradas?","consecrate?"],["Y","and"],["respondieron","they-answered"],["los","the"],["sacerdotes","priests"],["y","and"],["dijeron:","they-said:"],["No.","not."]]},
  {num:13,words:[["Y","and"],["dijo","said"],["Hageo:","Haggai:"],["Si","if"],["una","a"],["persona","person"],["impura","unclean"],["a causa de","because of"],["haber","have"],["tocado","touched"],["un","a"],["cuerpo","body"],["muerto","dead"],["toca","touches"],["alguna","some"],["de","of"],["estas","these"],["cosas,","things,"],["¿quedará","shall-remain"],["esta","this"],["inmunda?","unclean?"],["Y","and"],["respondieron","they-answered"],["los","the"],["sacerdotes","priests"],["y","and"],["dijeron:","they-said:"],["Inmunda","unclean"],["quedará.","shall-remain."]]},
  {num:14,words:[["Y","and"],["respondió","answered"],["Hageo","Haggai"],["y","and"],["dijo:","said:"],["Así","thus"],["es","is"],["este","this"],["pueblo","people"],["y","and"],["esta","this"],["nación","nation"],["delante","before"],["de","of"],["mí,","me,"],["dice","says"],["Jehová;","jehovah;"],["y","and"],["asimismo","likewise"],["toda","all"],["obra","work"],["de","of"],["sus","their"],["manos","hands"],["y","and"],["todo","all"],["lo","it/him"],["que","that"],["aquí","here"],["ofrecen","they-offer"],["es","is"],["inmundo.","unclean."]]},
  {num:15,words:[["Ahora","now"],["pues,","for,"],["meditad","you-meditate"],["en","in"],["vuestro","your"],["corazón","heart"],["desde","from"],["este","this"],["día","day"],["en","in"],["adelante,","forward/henceforth,"],["antes que","before"],["pongan","they-may-put"],["piedra","stone"],["sobre","upon"],["piedra","stone"],["en","in"],["el","the"],["templo","temple"],["de","of"],["Jehová.","jehovah."]]},
  {num:16,words:[["Antes que","before"],["sucediesen","might-things"],["estas","these"],["cosas,","things,"],["venía","coming"],["alguno","some"],["al","to-the"],["montón","heap"],["de","of"],["veinte","twenty"],["efas,","dealss,"],["y","and"],["había","had"],["solo","alone"],["diez;","ten;"],["venía","coming"],["alguno","some"],["al","to-the"],["lagar","wine press"],["para","for"],["sacar","draw"],["cincuenta","fifty"],["cántaros","pitchers"],["del","of-the"],["lagar,","wine press,"],["y","and"],["había","had"],["solo","alone"],["veinte.","twenty."]]},
  {num:17,words:[["Os","you"],["herí","I-struck"],["con","with"],["viento","wind"],["solano,","wind,"],["y","and"],["con","with"],["tizoncillo","and"],["y","and"],["con","with"],["granizo","hail"],["en","in"],["toda","all"],["obra","work"],["de","of"],["vuestras","your"],["manos,","hands,"],["pero","but"],["no","not"],["os","you"],["volvisteis","you-returned"],["a","to"],["mí,","me,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:18,words:[["Meditad,","you-consider,"],["pues,","for,"],["en","in"],["vuestro","your"],["corazón","heart"],["desde","from"],["este","this"],["día","day"],["en","in"],["adelante,","forward/henceforth,"],["desde","from"],["el","the"],["día","day"],["veinticuatro","course"],["del","of-the"],["noveno","ninth"],["mes,","month,"],["desde","from"],["el","the"],["día","day"],["en que","that"],["se","itself"],["echó","cast"],["el","the"],["cimiento","foundation"],["del","of-the"],["templo","temple"],["de","of"],["Jehová;","jehovah;"],["meditad","you-meditate"],["en","in"],["vuestro","your"],["corazón.","heart."]]},
  {num:19,words:[["¿No","not"],["está","is"],["aún","yet"],["la","the"],["semilla","seed"],["en","in"],["el","the"],["granero?","as?"],["Todavía","yet"],["no","not"],["han","they-have"],["dado","given"],["fruta,","fruit,"],["ni","nor"],["la","the"],["vid,","vine,"],["ni","nor"],["la","the"],["higuera,","fig,"],["ni","nor"],["el","the"],["granado","has"],["ni","nor"],["el","the"],["olivo;","olive;"],["mas","but"],["desde","from"],["este","this"],["día","day"],["daré","I-shall-give"],["bendición.","blessing."]]},
  {num:20,words:[["Y","and"],["vino","wine"],["por","for"],["segunda","second"],["vez","time"],["la","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["a","to"],["Hageo,","Haggai,"],["a","to"],["los","the"],["veinticuatro","course"],["días","days"],["del","of-the"],["mismo","same"],["mes,","month,"],["diciendo:","saying:"]]},
  {num:21,words:[["Habla","speaks"],["a","to"],["Zorobabel,","Zerubbabel,"],["gobernador","governor"],["de","of"],["Judá,","Judah,"],["diciendo:","saying:"],["Yo","I"],["haré","I will make"],["temblar","to-tremble"],["los","the"],["cielos","heavens"],["y","and"],["la","the"],["tierra,","earth,"]]},
  {num:22,words:[["y","and"],["trastornaré","I-will-disturb"],["el","the"],["trono","throne"],["de","of"],["los","the"],["reinos","kingdoms"],["y","and"],["destruiré","I-will-destroy"],["la","the"],["fuerza","strength"],["de","of"],["los","the"],["reinos","kingdoms"],["de","of"],["las","the"],["naciones;","nations;"],["y","and"],["trastornaré","heathen"],["los","the"],["carros","chariots"],["y","and"],["a","to"],["los","the"],["que","that"],["en","in"],["ellos","they"],["suben;","go-up;"],["y","and"],["caerán","they-will-fall"],["los","the"],["caballos","horses"],["y","and"],["los","the"],["que","that"],["en","in"],["ellos","they"],["montan,","come,"],["cada","each"],["cual","which"],["por","by"],["la","the"],["espada","sword"],["de","of"],["su","his"],["hermano.","brother."]]},
  {num:23,words:[["En","in"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["te","you"],["tomaré,","take,"],["oh","oh"],["Zorobabel","Zerubbabel"],["hijo","son"],["de","of"],["Salatiel,","Shealtiel,"],["siervo","servant"],["mío,","mine,"],["dice","says"],["Jehová,","jehovah,"],["y","and"],["te","you"],["pondré","I-shall-put"],["como","as"],["anillo","ring"],["de","of"],["sellar,","to-seal,"],["porque","because"],["yo","I"],["te","you"],["escogí,","chosen,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
];
renderVerseSet(v2, 'hag-ch2-verses');

})();
