(function() {
var v1 = [
  {num:1,words:[["La", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["que", "that"], ["vino", "wine"], ["a", "to"], ["Oseas", "hoshea"], ["hijo", "son"], ["de", "of"], ["Beeri,", "beeri,"], ["en", "in"], ["días", "days"], ["de", "of"], ["Uzías,", "uzziah,"], ["Jotam,", "jotham,"], ["Acaz", "ahaz"], ["y", "and"], ["Ezequías,", "Hezekiah,"], ["reyes", "kings"], ["de", "of"], ["Judá,", "Judah,"], ["y", "and"], ["en", "in"], ["días", "days"], ["de", "of"], ["Jeroboam", "jeroboam"], ["hijo", "son"], ["de", "of"], ["Joás,", "joash,"], ["rey", "king"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:2,words:[["El", "the"], ["principio", "beginning"], ["de", "of"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["por", "by/for"], ["medio", "midst"], ["de", "of"], ["Oseas.", "hoshea."], ["Y", "and"], ["dijo", "said"], ["Jehová", "jehovah"], ["a", "to"], ["Oseas:", "hoshea:"], ["Ve,", "sees,"], ["toma", "take"], ["para", "for"], ["ti", "thee"], ["como", "as"], ["esposa", "wife"], ["una", "a"], ["mujer", "woman"], ["dada", "given"], ["a", "to"], ["la", "the"], ["prostitución", "whoredoms"], ["y", "and"], ["ten", "merciful"], ["hijos", "children"], ["de", "of"], ["prostitución;", "for;"], ["porque", "because"], ["la", "the"], ["tierra", "land/earth"], ["se", "[refl.]"], ["ha", "has"], ["dado", "given"], ["a", "to"], ["la", "the"], ["fornicación,", "fornication,"], ["apartándose", "from"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:3,words:[["Fue,", "was/went,"], ["pues,", "for,"], ["y", "and"], ["tomó", "took"], ["a", "to"], ["Gomer", "of"], ["hija", "daughter"], ["de", "of"], ["Diblaim,", "daughter,"], ["la", "the"], ["cual", "which"], ["concibió", "conceived"], ["y", "and"], ["le", "him/her"], ["dio", "gave"], ["a", "to"], ["luz", "light"], ["un", "a"], ["hijo.", "son."]]},
  {num:4,words:[["Y", "and"], ["le", "him/her"], ["dijo", "said"], ["Jehová:", "jehovah:"], ["Ponle", "prophesy-him"], ["por", "by/for"], ["nombre", "name"], ["Jezreel,", "jezreel,"], ["porque", "because"], ["dentro", "within"], ["de", "of"], ["poco", "little"], ["yo", "I"], ["castigaré", "punish"], ["a", "to"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jehú", "jehu"], ["por", "by/for"], ["motivo", "reason"], ["de", "of"], ["la", "the"], ["sangre", "blood"], ["de", "of"], ["Jezreel,", "jezreel,"], ["y", "and"], ["haré", "I-shall-make"], ["cesar", "ceasing"], ["el", "the"], ["reino", "kingdom"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:5,words:[["Y", "and"], ["acaecerá", "it"], ["que", "that"], ["en", "in"], ["aquel", "that"], ["día", "day"], ["quebraré", "day,"], ["yo", "I"], ["el", "the"], ["arco", "bow"], ["de", "of"], ["Israel", "Israel"], ["en", "in"], ["el", "the"], ["valle", "valley"], ["de", "of"], ["Jezreel.", "jezreel."]]},
  {num:6,words:[["Y", "and"], ["ella", "she"], ["concibió", "conceived"], ["otra", "other"], ["vez", "time"], ["y", "and"], ["dio", "gave"], ["a", "to"], ["luz", "light"], ["una", "a"], ["hija.", "daughter."], ["Y", "and"], ["le", "him/her"], ["dijo", "said"], ["Dios:", "God:"], ["Ponle", "prophesy-him"], ["por", "by/for"], ["nombre", "name"], ["Lo-ruhama;", "will;"], ["porque", "because"], ["no", "not"], ["tendré", "spare"], ["más", "more"], ["misericordia", "mercy"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel,", "Israel,"], ["sino", "but"], ["que", "that"], ["los", "the"], ["quitaré", "take"], ["del", "of-the"], ["todo.", "all."]]},
  {num:7,words:[["Mas", "but"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Judá", "Judah"], ["tendré", "spare"], ["misericordia", "mercy"], ["y", "and"], ["los", "the"], ["salvaré", "save"], ["por", "by/for"], ["Jehová", "jehovah"], ["su", "his/her"], ["Dios;", "God;"], ["y", "and"], ["no", "not"], ["los", "the"], ["salvaré", "save"], ["con", "with"], ["arco,", "bow,"], ["ni", "nor"], ["con", "with"], ["espada,", "sword,"], ["ni", "nor"], ["con", "with"], ["batalla,", "battle,"], ["ni", "nor"], ["con", "with"], ["caballos", "horses"], ["ni", "nor"], ["jinetes.", "horsemen."]]},
  {num:8,words:[["Y", "and"], ["después", "after/afterward"], ["de", "of"], ["haber", "have"], ["destetado", "weaned"], ["a", "to"], ["Lo-ruhama,", "loruhamah,"], ["Gomer", "of"], ["concibió", "conceived"], ["y", "and"], ["dio", "gave"], ["a", "to"], ["luz", "light"], ["un", "a"], ["hijo.", "son."]]},
  {num:9,words:[["Y", "and"], ["dijo", "said"], ["Dios:", "God:"], ["Ponle", "prophesy-him"], ["por", "by/for"], ["nombre", "name"], ["Lo-ammi,", "for,"], ["porque", "because"], ["vosotros", "you"], ["no", "not"], ["sois", "ye-are"], ["mi", "my"], ["pueblo,", "people,"], ["ni", "nor"], ["yo", "I"], ["seré", "I-shall-be"], ["vuestro", "your"], ["Dios.", "God."]]},
  {num:10,words:[["Con", "with"], ["todo,", "all,"], ["será", "shall-be"], ["el", "the"], ["número", "number"], ["de", "of"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Israel", "Israel"], ["como", "as"], ["la", "the"], ["arena", "sand"], ["del", "of-the"], ["mar,", "sea,"], ["que", "that"], ["no", "not"], ["se", "[refl.]"], ["puede", "can"], ["medir", "measuring"], ["ni", "nor"], ["contar.", "beside."], ["Y", "and"], ["sucederá", "pass"], ["que", "that"], ["en", "in"], ["el", "the"], ["lugar", "place"], ["donde", "where"], ["se", "[refl.]"], ["les", "them"], ["dijo:", "said:"], ["Vosotros", "you"], ["no", "not"], ["sois", "ye-are"], ["mi", "my"], ["pueblo,", "people,"], ["se", "[refl.]"], ["les", "them"], ["dirá:", "shall-say:"], ["Sois", "ye-are"], ["hijos", "children"], ["del", "of-the"], ["Dios", "God"], ["viviente.", "living."]]},
  {num:11,words:[["Y", "and"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Judá", "Judah"], ["y", "and"], ["de", "of"], ["Israel", "Israel"], ["serán", "shall-be"], ["congregados", "gathered"], ["en", "in"], ["uno,", "one,"], ["y", "and"], ["nombrarán", "shall-the"], ["para", "for"], ["sí", "yea"], ["un", "a"], ["solo", "alone"], ["jefe", "chief"], ["y", "and"], ["subirán", "up"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["porque", "because"], ["grande", "great"], ["será", "shall-be"], ["el", "the"], ["día", "day"], ["de", "of"], ["Jezreel.", "jezreel."]]},
];
renderVerseSet(v1, 'hos-ch1-verses');

var v2 = [
  {num:1,words:[["Decid", "tell"], ["a", "to"], ["vuestros", "your"], ["hermanos:", "brethren:"], ["Ammi,", "brethren,"], ["y", "and"], ["a", "to"], ["vuestras", "your"], ["hermanas:", "sisters:"], ["Ruhama.", "ruhamah."]]},
  {num:2,words:[["Contended", "plead"], ["con", "with"], ["vuestra", "your"], ["madre,", "mother,"], ["contended,", "for,"], ["porque", "because"], ["ella", "she"], ["no", "not"], ["es", "is"], ["mi", "my"], ["esposa", "wife"], ["ni", "nor"], ["yo", "I"], ["su", "his/her"], ["marido;", "husband;"], ["que", "that"], ["quite,", "away,"], ["pues,", "for,"], ["sus", "his/her"], ["fornicaciones", "whoredoms"], ["de", "of"], ["su", "his/her"], ["rostro", "face"], ["y", "and"], ["sus", "his/her"], ["adulterios", "adulterys"], ["de", "of"], ["entre", "among"], ["sus", "his/her"], ["pechos;", "breasts;"]]},
  {num:3,words:[["no", "not"], ["sea", "let-be/be"], ["que", "that"], ["yo", "I"], ["la", "the"], ["desnude", "and"], ["del", "of-the"], ["todo,", "all,"], ["y", "and"], ["la", "the"], ["deje", "said"], ["como", "as"], ["el", "the"], ["día", "day"], ["en", "in"], ["que", "that"], ["nació,", "was-born,"], ["y", "and"], ["la", "the"], ["haga", "let-do"], ["como", "as"], ["un", "a"], ["desierto,", "wilderness,"], ["y", "and"], ["la", "the"], ["deje", "said"], ["como", "as"], ["tierra", "land/earth"], ["seca", "dry"], ["y", "and"], ["la", "the"], ["mate", "him"], ["de", "of"], ["sed.", "thirst/be."]]},
  {num:4,words:[["No", "not"], ["tendré", "spare"], ["misericordia", "mercy"], ["de", "of"], ["sus", "his/her"], ["hijos,", "children,"], ["porque", "because"], ["son", "are"], ["hijos", "children"], ["de", "of"], ["prostitución.", "whoredoms."]]},
  {num:5,words:[["Porque", "because"], ["su", "his/her"], ["madre", "mother"], ["se", "[refl.]"], ["prostituyó;", "played;"], ["la", "the"], ["que", "that"], ["los", "the"], ["dio", "gave"], ["a", "to"], ["luz", "light"], ["se", "[refl.]"], ["deshonró,", "shamefully,"], ["porque", "because"], ["dijo:", "said:"], ["Iré", "go"], ["tras", "after"], ["mis", "my"], ["amantes,", "lovers,"], ["que", "that"], ["me", "me"], ["dan", "dan"], ["mi", "my"], ["pan", "bread"], ["y", "and"], ["mi", "my"], ["agua,", "water,"], ["mi", "my"], ["lana", "wool"], ["y", "and"], ["mi", "my"], ["lino,", "twined,"], ["mi", "my"], ["aceite", "oil"], ["y", "and"], ["mi", "my"], ["bebida.", "drink."]]},
  {num:6,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["he", "I-have"], ["aquí,", "here,"], ["yo", "I"], ["cercaré", "up"], ["tu", "thy"], ["camino", "way"], ["con", "with"], ["espinos,", "briers,"], ["y", "and"], ["la", "the"], ["cercaré", "a"], ["con", "with"], ["seto,", "that,"], ["y", "and"], ["no", "not"], ["hallará", "find"], ["ella", "she"], ["sus", "his/her"], ["caminos.", "ways."]]},
  {num:7,words:[["Y", "and"], ["seguirá", "shall"], ["a", "to"], ["sus", "his/her"], ["amantes,", "lovers,"], ["pero", "but"], ["no", "not"], ["los", "the"], ["alcanzará;", "shall;"], ["los", "the"], ["buscará,", "shall-seek,"], ["pero", "but"], ["no", "not"], ["los", "the"], ["hallará.", "find."], ["Entonces", "then"], ["dirá:", "shall-say:"], ["Iré", "go"], ["y", "and"], ["volveré", "return"], ["a", "to"], ["mi", "my"], ["primer", "first"], ["marido,", "husband,"], ["porque", "because"], ["mejor", "better"], ["me", "me"], ["iba", "went"], ["entonces", "then"], ["que", "that"], ["ahora.", "now."]]},
  {num:8,words:[["Y", "and"], ["ella", "she"], ["no", "not"], ["reconoció", "knew"], ["que", "that"], ["yo", "I"], ["le", "him/her"], ["daba", "gave"], ["el", "the"], ["trigo,", "wheat,"], ["y", "and"], ["el", "the"], ["vino", "wine"], ["y", "and"], ["el", "the"], ["aceite,", "oil,"], ["y", "and"], ["que", "that"], ["le", "him/her"], ["multipliqué", "her"], ["la", "the"], ["plata", "silver"], ["y", "and"], ["el", "the"], ["oro", "gold"], ["que", "that"], ["usaban", "were-ining"], ["para", "for"], ["Baal.", "baal."]]},
  {num:9,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["yo", "I"], ["volveré", "return"], ["y", "and"], ["tomaré", "take"], ["mi", "my"], ["trigo", "wheat"], ["a", "to"], ["su", "his/her"], ["tiempo", "time"], ["y", "and"], ["mi", "my"], ["vino", "wine"], ["en", "in"], ["su", "his/her"], ["sazón,", "in,"], ["y", "and"], ["le", "him/her"], ["quitaré", "take"], ["mi", "my"], ["lana", "wool"], ["y", "and"], ["mi", "my"], ["lino", "twined"], ["que", "that"], ["le", "him/her"], ["había", "had"], ["dado", "given"], ["para", "for"], ["cubrir", "cover"], ["su", "his/her"], ["desnudez.", "nakedness."]]},
  {num:10,words:[["Y", "and"], ["ahora", "now"], ["descubriré", "shall-to"], ["yo", "I"], ["su", "his/her"], ["lascivia", "lewdness"], ["delante", "before"], ["de", "of"], ["los", "the"], ["ojos", "eyes"], ["de", "of"], ["sus", "his/her"], ["amantes,", "lovers,"], ["y", "and"], ["nadie", "no-one"], ["la", "the"], ["librará", "deliver"], ["de", "of"], ["mi", "my"], ["mano.", "hand."]]},
  {num:11,words:[["Y", "and"], ["haré", "I-shall-make"], ["cesar", "ceasing"], ["todo", "all"], ["su", "his/her"], ["gozo,", "joy,"], ["sus", "his/her"], ["fiestas,", "moons,"], ["sus", "his/her"], ["lunas", "moons"], ["nuevas", "new"], ["y", "and"], ["sus", "his/her"], ["días", "days"], ["de", "of"], ["reposo", "rest"], ["y", "and"], ["todas", "all"], ["sus", "his/her"], ["fiestas", "moons"], ["solemnes.", "moons."]]},
  {num:12,words:[["Asolaré", "will"], ["sus", "his/her"], ["vides", "and"], ["y", "and"], ["sus", "his/her"], ["higueras,", "figs,"], ["de", "of"], ["las", "the"], ["cuales", "which"], ["ha", "has"], ["dicho:", "said:"], ["Esta", "this"], ["es", "is"], ["la", "the"], ["paga", "thou"], ["que", "that"], ["me", "me"], ["han", "have"], ["dado", "given"], ["mis", "my"], ["amantes.", "lovers."], ["Y", "and"], ["las", "the"], ["reduciré", "will"], ["a", "to"], ["un", "a"], ["matorral,", "forest,"], ["y", "and"], ["se", "[refl.]"], ["las", "the"], ["comerán", "eat"], ["las", "the"], ["bestias", "beasts"], ["del", "of-the"], ["campo.", "field."]]},
  {num:13,words:[["Y", "and"], ["la", "the"], ["castigaré", "punish"], ["por", "by/for"], ["los", "the"], ["días", "days"], ["en", "in"], ["que", "that"], ["quemaba", "incense"], ["incienso", "incense"], ["a", "to"], ["los", "the"], ["baales,", "baalim,"], ["y", "and"], ["se", "[refl.]"], ["adornaba", "and"], ["con", "with"], ["sus", "his/her"], ["zarcillos", "earrings"], ["y", "and"], ["sus", "his/her"], ["joyeles,", "and,"], ["y", "and"], ["se", "[refl.]"], ["iba", "went"], ["tras", "after"], ["sus", "his/her"], ["amantes", "lovers"], ["y", "and"], ["se", "[refl.]"], ["olvidaba", "forgat"], ["de", "of"], ["mí,", "me,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:14,words:[["Pero", "but"], ["he", "I-have"], ["aquí,", "here,"], ["yo", "I"], ["la", "the"], ["atraeré,", "her,"], ["y", "and"], ["la", "the"], ["llevaré", "bring"], ["al", "to-the"], ["desierto", "wilderness"], ["y", "and"], ["hablaré", "speak"], ["a", "to"], ["su", "his/her"], ["corazón.", "heart."]]},
  {num:15,words:[["Y", "and"], ["le", "him/her"], ["daré", "I-shall-give"], ["sus", "his/her"], ["viñas", "vineyards"], ["desde", "from"], ["allí,", "there,"], ["y", "and"], ["el", "the"], ["valle", "valley"], ["de", "of"], ["Acor", "achor"], ["será", "shall-be"], ["como", "as"], ["puerta", "gate"], ["de", "of"], ["esperanza;", "hope;"], ["y", "and"], ["allí", "there"], ["cantará", "shall"], ["como", "as"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["su", "his/her"], ["juventud,", "youth,"], ["y", "and"], ["como", "as"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["su", "his/her"], ["subida", "going"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto.", "Egypt."]]},
  {num:16,words:[["Y", "and"], ["sucederá", "pass"], ["que", "that"], ["en", "in"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["me", "me"], ["llamarás", "call"], ["Ishi,", "me,"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["me", "me"], ["llamarás", "call"], ["Baali.", "baali."]]},
  {num:17,words:[["Porque", "because"], ["quitaré", "take"], ["de", "of"], ["su", "his/her"], ["boca", "mouth"], ["los", "the"], ["nombres", "names"], ["de", "of"], ["los", "the"], ["baales,", "baalim,"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["serán", "shall-be"], ["recordados", "be"], ["por", "by/for"], ["sus", "his/her"], ["nombres.", "names."]]},
  {num:18,words:[["Y", "and"], ["haré", "I-shall-make"], ["por", "by/for"], ["ellos", "they"], ["convenio", "covenant"], ["en", "in"], ["aquel", "that"], ["día", "day"], ["con", "with"], ["las", "the"], ["bestias", "beasts"], ["del", "of-the"], ["campo,", "field,"], ["y", "and"], ["con", "with"], ["las", "the"], ["aves", "fowl"], ["del", "of-the"], ["cielo", "heaven"], ["y", "and"], ["con", "with"], ["las", "the"], ["serpientes", "serpents"], ["de", "of"], ["la", "the"], ["tierra;", "land/earth;"], ["y", "and"], ["quebraré", "will"], ["el", "the"], ["arco", "bow"], ["y", "and"], ["la", "the"], ["espada,", "sword,"], ["y", "and"], ["quitaré", "take"], ["la", "the"], ["guerra", "war"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["y", "and"], ["los", "the"], ["haré", "I-shall-make"], ["reposar", "rest"], ["seguros.", "i."]]},
  {num:19,words:[["Y", "and"], ["te", "thee"], ["desposaré", "betroth"], ["conmigo", "with-me"], ["para", "for"], ["siempre;", "always;"], ["te", "thee"], ["desposaré", "yea,"], ["conmigo", "with-me"], ["en", "in"], ["justicia,", "justice/righteousness,"], ["y", "and"], ["en", "in"], ["juicio,", "judgment,"], ["y", "and"], ["en", "in"], ["benignidad", "the"], ["y", "and"], ["en", "in"], ["misericordia.", "mercy."]]},
  {num:20,words:[["Y", "and"], ["te", "thee"], ["desposaré", "betroth"], ["conmigo", "with-me"], ["en", "in"], ["fidelidad,", "faithfulness,"], ["y", "and"], ["conocerás", "shall-know"], ["a", "to"], ["Jehová.", "jehovah."]]},
  {num:21,words:[["Y", "and"], ["acontecerá", "shall-come-to-pass"], ["que", "that"], ["en", "in"], ["aquel", "that"], ["día", "day"], ["responderé,", "answer,"], ["dice", "says"], ["Jehová;", "jehovah;"], ["yo", "I"], ["responderé", "answer"], ["a", "to"], ["los", "the"], ["cielos,", "heavens,"], ["y", "and"], ["ellos", "they"], ["responderán", "shall"], ["a", "to"], ["la", "the"], ["tierra;", "land/earth;"]]},
  {num:22,words:[["y", "and"], ["la", "the"], ["tierra", "land/earth"], ["responderá", "answer"], ["al", "to-the"], ["trigo,", "wheat,"], ["y", "and"], ["al", "to-the"], ["vino", "wine"], ["y", "and"], ["al", "to-the"], ["aceite,", "oil,"], ["y", "and"], ["ellos", "they"], ["responderán", "shall"], ["a", "to"], ["Jezreel.", "jezreel."]]},
  {num:23,words:[["Y", "and"], ["la", "the"], ["sembraré", "shall-sow"], ["para", "for"], ["mí", "me"], ["en", "in"], ["la", "the"], ["tierra,", "land/earth,"], ["y", "and"], ["tendré", "spare"], ["misericordia", "mercy"], ["de", "of"], ["Lo-ruhama;", "mercy;"], ["y", "and"], ["diré", "tell"], ["a", "to"], ["Lo-ammi:", "which:"], ["¡Pueblo", "people"], ["mío", "mine"], ["eres", "thou-art"], ["tú!,", "thou!,"], ["y", "and"], ["él", "he"], ["dirá:", "shall-say:"], ["¡Dios", "God"], ["mío!", "mine!"]]},
];
renderVerseSet(v2, 'hos-ch2-verses');

var v3 = [
  {num:1,words:[["Y", "and"], ["me", "me"], ["dijo", "said"], ["otra", "other"], ["vez", "time"], ["Jehová:", "jehovah:"], ["Ve,", "sees,"], ["ama", "loveth"], ["a", "to"], ["una", "a"], ["mujer", "woman"], ["amada", "beloved"], ["de", "of"], ["su", "his/her"], ["compañero,", "companion,"], ["aunque", "although"], ["adúltera,", "adulteress,"], ["tal", "such"], ["como", "as"], ["Jehová", "jehovah"], ["ama", "loveth"], ["a", "to"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Israel,", "Israel,"], ["los", "the"], ["cuales", "which"], ["miran", "look"], ["a", "to"], ["dioses", "gods"], ["ajenos", "gods"], ["y", "and"], ["aman", "love"], ["los", "the"], ["panes", "loaves"], ["de", "of"], ["pasas.", "of."]]},
  {num:2,words:[["La", "the"], ["compré", "and"], ["entonces", "then"], ["para", "for"], ["mí", "me"], ["por", "by/for"], ["quince", "fifteen"], ["piezas", "pieces"], ["de", "of"], ["plata", "silver"], ["y", "and"], ["un", "a"], ["homer", "barley,"], ["y", "and"], ["medio", "midst"], ["de", "of"], ["cebada.", "barley."]]},
  {num:3,words:[["Y", "and"], ["le", "him/her"], ["dije:", "I-said:"], ["Tú", "thou"], ["estarás", "shalt"], ["conmigo", "with-me"], ["muchos", "many"], ["días;", "days;"], ["no", "not"], ["fornicarás", "the"], ["ni", "nor"], ["tomarás", "take"], ["otro", "other"], ["hombre;", "man;"], ["lo", "it/him"], ["mismo", "same"], ["haré", "I-shall-make"], ["yo", "I"], ["contigo.", "with-thee."]]},
  {num:4,words:[["Porque", "because"], ["muchos", "many"], ["días", "days"], ["estarán", "stand"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Israel", "Israel"], ["sin", "without"], ["rey,", "king,"], ["y", "and"], ["sin", "without"], ["príncipe,", "prince,"], ["y", "and"], ["sin", "without"], ["sacrificio,", "sacrifice,"], ["y", "and"], ["sin", "without"], ["estatua,", "image,"], ["y", "and"], ["sin", "without"], ["efod", "ephod"], ["y", "and"], ["sin", "without"], ["terafines.", "teraphim."]]},
  {num:5,words:[["Después", "after/afterward"], ["volverán", "return"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Israel", "Israel"], ["y", "and"], ["buscarán", "seek"], ["a", "to"], ["Jehová", "jehovah"], ["su", "his/her"], ["Dios", "God"], ["y", "and"], ["a", "to"], ["David,", "David,"], ["su", "his/her"], ["rey;", "king;"], ["y", "and"], ["temerán", "fear"], ["a", "to"], ["Jehová", "jehovah"], ["y", "and"], ["a", "to"], ["su", "his/her"], ["bondad", "goodness"], ["en", "in"], ["los", "the"], ["últimos", "latterday"], ["días.", "days."]]},
];
renderVerseSet(v3, 'hos-ch3-verses');

var v4 = [
  {num:1,words:[["Oíd", "hear"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová,", "jehovah,"], ["hijos", "children"], ["de", "of"], ["Israel,", "Israel,"], ["porque", "because"], ["Jehová", "jehovah"], ["contiende", "lord"], ["con", "with"], ["los", "the"], ["moradores", "inhabitants"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["porque", "because"], ["no", "not"], ["hay", "there-is"], ["verdad,", "truth,"], ["ni", "nor"], ["misericordia", "mercy"], ["ni", "nor"], ["conocimiento", "knowledge"], ["de", "of"], ["Dios", "God"], ["en", "in"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:2,words:[["El", "the"], ["perjurar,", "swearing,"], ["y", "and"], ["el", "the"], ["mentir,", "lie,"], ["y", "and"], ["el", "the"], ["matar,", "slay,"], ["y", "and"], ["el", "the"], ["hurtar", "and"], ["y", "and"], ["el", "the"], ["cometer", "commit"], ["adulterio", "adultery"], ["prevalecen,", "break,"], ["y", "and"], ["el", "the"], ["derramar", "shedding"], ["sangre", "blood"], ["tras", "after"], ["sangre.", "blood."]]},
  {num:3,words:[["Por", "by/for"], ["lo", "it/him"], ["cual", "which"], ["la", "the"], ["tierra", "land/earth"], ["estará", "shall-be"], ["de", "of"], ["duelo,", "mourned,"], ["y", "and"], ["desfallecerá", "therein"], ["todo", "all"], ["morador", "inhabitant"], ["de", "of"], ["ella", "she"], ["con", "with"], ["las", "the"], ["bestias", "beasts"], ["del", "of-the"], ["campo", "field"], ["y", "and"], ["las", "the"], ["aves", "fowl"], ["del", "of-the"], ["cielo;", "heaven;"], ["y", "and"], ["aun", "even"], ["los", "the"], ["peces", "fish"], ["del", "of-the"], ["mar", "sea"], ["desaparecerán.", "away."]]},
  {num:4,words:[["Que", "that"], ["ningún", "no"], ["hombre", "man"], ["contienda", "strife"], ["ni", "nor"], ["reprenda", "nor"], ["a", "to"], ["otro", "other"], ["hombre,", "man,"], ["porque", "because"], ["tu", "thy"], ["pueblo", "people"], ["es", "is"], ["como", "as"], ["los", "the"], ["que", "that"], ["contienden", "strive"], ["con", "with"], ["el", "the"], ["sacerdote.", "priest."]]},
  {num:5,words:[["Caerás,", "shall-fall,"], ["por", "by/for"], ["tanto,", "therefore,"], ["en", "in"], ["pleno", "in"], ["día,", "day,"], ["y", "and"], ["caerá", "fall"], ["también", "also"], ["contigo", "with-thee"], ["el", "the"], ["profeta", "prophet"], ["de", "of"], ["noche;", "night;"], ["y", "and"], ["a", "to"], ["tu", "thy"], ["madre", "mother"], ["destruiré.", "destroy."]]},
  {num:6,words:[["Mi", "my"], ["pueblo", "people"], ["fue", "was/went"], ["destruido", "destroyed"], ["porque", "because"], ["le", "him/her"], ["faltó", "and"], ["conocimiento.", "knowledge."], ["Por", "by/for"], ["cuanto", "as-much-as"], ["tú", "thou"], ["desechaste", "rejected"], ["el", "the"], ["conocimiento,", "knowledge,"], ["yo", "I"], ["te", "thee"], ["desecharé", "shall-to"], ["a", "to"], ["ti", "thee"], ["y", "and"], ["no", "not"], ["serás", "thou-shalt-be"], ["sacerdote", "priest"], ["para", "for"], ["mí;", "me;"], ["y", "and"], ["porque", "because"], ["olvidaste", "hast"], ["la", "the"], ["ley", "law"], ["de", "of"], ["tu", "thy"], ["Dios,", "God,"], ["también", "also"], ["yo", "I"], ["me", "me"], ["olvidaré", "forget"], ["de", "of"], ["tus", "thy"], ["hijos.", "children."]]},
  {num:7,words:[["Cuanto", "as-much-as"], ["más", "more"], ["se", "[refl.]"], ["multiplicaban,", "increased,"], ["más", "more"], ["pecaban", "were-sining"], ["contra", "against"], ["mí;", "me;"], ["también", "also"], ["yo", "I"], ["cambiaré", "i"], ["su", "his/her"], ["honra", "honor"], ["en", "in"], ["afrenta.", "reproach."]]},
  {num:8,words:[["Comen", "eat"], ["del", "of-the"], ["pecado", "sin"], ["de", "of"], ["mi", "my"], ["pueblo,", "people,"], ["y", "and"], ["en", "in"], ["su", "his/her"], ["iniquidad", "iniquity"], ["ponen", "their"], ["su", "his/her"], ["alma.", "soul."]]},
  {num:9,words:[["Y", "and"], ["será", "shall-be"], ["el", "the"], ["pueblo", "people"], ["como", "as"], ["el", "the"], ["sacerdote;", "priest;"], ["y", "and"], ["los", "the"], ["castigaré", "punish"], ["por", "by/for"], ["sus", "his/her"], ["caminos", "ways"], ["y", "and"], ["les", "them"], ["pagaré", "will"], ["conforme", "according-to"], ["a", "to"], ["sus", "his/her"], ["obras.", "works."]]},
  {num:10,words:[["Y", "and"], ["comerán,", "eat,"], ["mas", "but"], ["no", "not"], ["se", "[refl.]"], ["saciarán;", "they;"], ["fornicarán,", "shall,"], ["mas", "but"], ["no", "not"], ["se", "[refl.]"], ["multiplicarán,", "increase,"], ["porque", "because"], ["dejaron", "left"], ["de", "of"], ["hacer", "make/do"], ["caso", "case"], ["a", "to"], ["Jehová.", "jehovah."]]},
  {num:11,words:[["Fornicación,", "fornication,"], ["y", "and"], ["vino", "wine"], ["y", "and"], ["mosto", "corn"], ["quitan", "take"], ["el", "the"], ["juicio.", "judgment."]]},
  {num:12,words:[["Mi", "my"], ["pueblo", "people"], ["a", "to"], ["su", "his/her"], ["ídolo", "idol"], ["de", "of"], ["madera", "wood"], ["pregunta,", "ask,"], ["y", "and"], ["su", "his/her"], ["palo", "staff"], ["le", "him/her"], ["responde;", "unto;"], ["porque", "because"], ["un", "a"], ["espíritu", "Spirit"], ["de", "of"], ["fornicaciones", "whoredoms"], ["lo", "it/him"], ["hizo", "made/did"], ["errar,", "err,"], ["y", "and"], ["dejaron", "left"], ["a", "to"], ["su", "his/her"], ["Dios", "God"], ["para", "for"], ["fornicar.", "god."]]},
  {num:13,words:[["Sobre", "upon"], ["las", "the"], ["cimas", "tops"], ["de", "of"], ["los", "the"], ["montes", "mountains"], ["sacrifican,", "the,"], ["y", "and"], ["queman", "burn"], ["incienso", "incense"], ["sobre", "upon"], ["los", "the"], ["collados,", "hills,"], ["debajo", "beneath"], ["de", "of"], ["las", "the"], ["encinas,", "oaks,"], ["y", "and"], ["de", "of"], ["los", "the"], ["álamos", "elms,"], ["y", "and"], ["de", "of"], ["los", "the"], ["olmos,", "thereof,"], ["porque", "because"], ["tenían", "had"], ["buena", "good"], ["sombra;", "shadow;"], ["por", "by/for"], ["tanto,", "therefore,"], ["vuestras", "your"], ["hijas", "daughters"], ["fornicarán,", "and,"], ["y", "and"], ["vuestras", "your"], ["nueras", "daughters"], ["cometerán", "shall-commit"], ["adulterio.", "adultery."]]},
  {num:14,words:[["No", "not"], ["castigaré", "punish"], ["a", "to"], ["vuestras", "your"], ["hijas", "daughters"], ["cuando", "when"], ["forniquen,", "they,"], ["ni", "nor"], ["a", "to"], ["vuestras", "your"], ["nueras", "daughters"], ["cuando", "when"], ["cometan", "commit"], ["adulterio;", "adultery;"], ["porque", "because"], ["ellos", "they"], ["mismos", "selves"], ["se", "[refl.]"], ["van", "go"], ["con", "with"], ["rameras", "harlots"], ["y", "and"], ["con", "with"], ["malas", "evil"], ["mujeres", "women"], ["ofrecían", "and"], ["sacrificios;", "sacrifices;"], ["por", "by/for"], ["tanto,", "therefore,"], ["el", "the"], ["pueblo", "people"], ["sin", "without"], ["entendimiento", "understanding"], ["caerá.", "fall."]]},
  {num:15,words:[["Si", "if"], ["fornicas", "thou,"], ["tú,", "thou,"], ["oh", "oh"], ["Israel,", "Israel,"], ["al", "to-the"], ["menos", "less"], ["que", "that"], ["Judá", "Judah"], ["no", "not"], ["se", "[refl.]"], ["haga", "let-do"], ["culpable.", "guilty."], ["¡Y", "and"], ["no", "not"], ["entréis", "enter"], ["en", "in"], ["Gilgal,", "gilgal,"], ["ni", "nor"], ["subáis", "up"], ["a", "to"], ["Bet-avén", "nor"], ["ni", "nor"], ["juréis:", "the:"], ["Vive", "lives"], ["Jehová!", "jehovah!"]]},
  {num:16,words:[["Porque", "because"], ["como", "as"], ["novilla", "bullock"], ["terca", "as"], ["se", "[refl.]"], ["apartó", "nebat"], ["Israel.", "Israel."], ["¿Los", "the"], ["apacentará", "shall-feed"], ["ahora", "now"], ["Jehová", "jehovah"], ["como", "as"], ["a", "to"], ["un", "a"], ["cordero", "lamb"], ["en", "in"], ["lugar", "place"], ["espacioso?", "a?"]]},
  {num:17,words:[["Efraín", "ephraim"], ["se", "[refl.]"], ["ha", "has"], ["unido", "joined"], ["a", "to"], ["ídolos;", "idols;"], ["déjalo.", "leave-it."]]},
  {num:18,words:[["Su", "his/her"], ["bebida", "drink"], ["se", "[refl.]"], ["corrompió;", "they;"], ["fornicaron", "have"], ["pertinazmente;", "committed;"], ["sus", "his/her"], ["príncipes", "princes"], ["amaron", "loveed"], ["con", "with"], ["pasión", "shame"], ["lo", "it/him"], ["que", "that"], ["avergüenza.", "is."]]},
  {num:19,words:[["La", "the"], ["ató", "bound"], ["el", "the"], ["viento", "wind"], ["en", "in"], ["sus", "his/her"], ["alas,", "wings,"], ["y", "and"], ["de", "of"], ["sus", "his/her"], ["sacrificios", "sacrifices"], ["se", "[refl.]"], ["avergonzarán.", "ashamed."]]},
];
renderVerseSet(v4, 'hos-ch4-verses');

var v5 = [
  {num:1,words:[["Sacerdotes,", "priests,"], ["oíd", "hear"], ["esto;", "this;"], ["y", "and"], ["estad", "your"], ["atentos,", "hear,"], ["casa", "house"], ["de", "of"], ["Israel;", "Israel;"], ["y", "and"], ["casa", "house"], ["del", "of-the"], ["rey,", "king,"], ["escuchad.", "listen."], ["Porque", "because"], ["contra", "against"], ["vosotros", "you"], ["es", "is"], ["el", "the"], ["juicio,", "judgment,"], ["pues", "for"], ["habéis", "you-have"], ["sido", "been"], ["trampa", "snare"], ["en", "in"], ["Mizpa", "mizpah"], ["y", "and"], ["red", "net"], ["tendida", "his"], ["sobre", "upon"], ["Tabor.", "tabor."]]},
  {num:2,words:[["Y", "and"], ["los", "the"], ["rebeldes", "rebellious"], ["se", "[refl.]"], ["han", "have"], ["sumergido", "to"], ["en", "in"], ["la", "the"], ["matanza;", "slaughter;"], ["por", "by/for"], ["tanto,", "therefore,"], ["yo", "I"], ["los", "the"], ["castigaré", "punish"], ["a", "to"], ["todos", "all"], ["ellos.", "they."]]},
  {num:3,words:[["Yo", "I"], ["conozco", "know"], ["a", "to"], ["Efraín,", "ephraim,"], ["e", "and"], ["Israel", "Israel"], ["no", "not"], ["me", "me"], ["es", "is"], ["desconocido;", "me;"], ["porque", "because"], ["ahora,", "now,"], ["oh", "oh"], ["Efraín,", "ephraim,"], ["has", "thou-hast"], ["fornicado,", "the,"], ["y", "and"], ["se", "[refl.]"], ["ha", "has"], ["contaminado", "defiled"], ["Israel.", "Israel."]]},
  {num:4,words:[["Su", "his/her"], ["conducta", "conversation"], ["no", "not"], ["los", "the"], ["encamina", "doings"], ["a", "to"], ["volver", "return"], ["a", "to"], ["su", "his/her"], ["Dios,", "God,"], ["porque", "because"], ["un", "a"], ["espíritu", "Spirit"], ["de", "of"], ["fornicación", "fornication"], ["hay", "there-is"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ellos,", "they,"], ["y", "and"], ["no", "not"], ["conocen", "know"], ["a", "to"], ["Jehová.", "jehovah."]]},
  {num:5,words:[["Y", "and"], ["la", "the"], ["soberbia", "pride"], ["de", "of"], ["Israel", "Israel"], ["testificará", "shall-testify"], ["en", "in"], ["su", "his/her"], ["propia", "own"], ["cara;", "face;"], ["e", "and"], ["Israel", "Israel"], ["y", "and"], ["Efraín", "ephraim"], ["tropezarán", "shall"], ["en", "in"], ["su", "his/her"], ["iniquidad;", "iniquity;"], ["tropezará", "shall-and"], ["también", "also"], ["Judá", "Judah"], ["con", "with"], ["ellos.", "they."]]},
  {num:6,words:[["Con", "with"], ["sus", "his/her"], ["ovejas", "sheep"], ["y", "and"], ["con", "with"], ["sus", "his/her"], ["vacas", "kine"], ["andarán", "walk"], ["buscando", "seeking"], ["a", "to"], ["Jehová,", "jehovah,"], ["pero", "but"], ["no", "not"], ["le", "him/her"], ["hallarán;", "find;"], ["se", "[refl.]"], ["ha", "has"], ["apartado", "separated"], ["de", "of"], ["ellos.", "they."]]},
  {num:7,words:[["Contra", "against"], ["Jehová", "jehovah"], ["actuaron", "toed"], ["pérfidamente,", "treacherously,"], ["porque", "because"], ["hijos", "children"], ["extraños", "strangers"], ["han", "have"], ["engendrado;", "begotten;"], ["ahora", "now"], ["los", "the"], ["devorará", "devour"], ["en", "in"], ["solo", "alone"], ["un", "a"], ["mes", "month"], ["con", "with"], ["sus", "his/her"], ["heredades.", "inheritances."]]},
  {num:8,words:[["¡Tocad", "the"], ["corneta", "ye"], ["en", "in"], ["Gabaa,", "gibeah,"], ["trompeta", "trump"], ["en", "in"], ["Ramá!", "ramah!"], ["¡Gritad", "trumpet"], ["en", "in"], ["alarma", "the"], ["en", "in"], ["Bet-avén:", "at:"], ["Tras", "after"], ["ti,", "thee,"], ["oh", "oh"], ["Benjamín!", "benjamin!"]]},
  {num:9,words:[["Efraín", "ephraim"], ["será", "shall-be"], ["asolado", "be"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["reprensión;", "reproof;"], ["entre", "among"], ["las", "the"], ["tribus", "tribes"], ["de", "of"], ["Israel", "Israel"], ["hago", "I-do/make"], ["saber", "know"], ["lo", "it/him"], ["que", "that"], ["con", "with"], ["certeza", "surety"], ["es.", "is."]]},
  {num:10,words:[["Los", "the"], ["príncipes", "princes"], ["de", "of"], ["Judá", "Judah"], ["fueron", "were"], ["como", "as"], ["los", "the"], ["que", "that"], ["mueven", "the"], ["los", "the"], ["linderos;", "i;"], ["derramaré", "pour"], ["mi", "my"], ["ira", "wrath"], ["sobre", "upon"], ["ellos", "they"], ["como", "as"], ["agua.", "water."]]},
  {num:11,words:[["Efraín", "ephraim"], ["está", "is"], ["oprimido,", "oppressed,"], ["quebrantado", "contrite"], ["en", "in"], ["juicio,", "judgment,"], ["porque", "because"], ["quiso", "wanted"], ["andar", "walk"], ["en", "in"], ["pos", "follow"], ["de", "of"], ["vanidades.", "vanities."]]},
  {num:12,words:[["Yo,", "I,"], ["pues,", "for,"], ["seré", "I-shall-be"], ["como", "as"], ["polilla", "moth"], ["para", "for"], ["Efraín", "ephraim"], ["y", "and"], ["como", "as"], ["carcoma", "to"], ["para", "for"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Judá.", "Judah."]]},
  {num:13,words:[["Y", "and"], ["verá", "see"], ["Efraín", "ephraim"], ["su", "his/her"], ["enfermedad,", "disease,"], ["y", "and"], ["Judá", "Judah"], ["su", "his/her"], ["llaga;", "pronounce;"], ["irá", "well"], ["entonces", "then"], ["Efraín", "ephraim"], ["a", "to"], ["Asiria", "assyria"], ["y", "and"], ["enviará", "send"], ["al", "to-the"], ["rey", "king"], ["Jareb;", "jareb;"], ["pero", "but"], ["él", "he"], ["no", "not"], ["os", "you"], ["podrá", "able"], ["sanar", "to"], ["ni", "nor"], ["os", "you"], ["curará", "of"], ["la", "the"], ["llaga.", "pronounce."]]},
  {num:14,words:[["Porque", "because"], ["yo", "I"], ["seré", "I-shall-be"], ["como", "as"], ["león", "lion"], ["para", "for"], ["Efraín", "ephraim"], ["y", "and"], ["como", "as"], ["cachorro", "lion"], ["de", "of"], ["león", "lion"], ["para", "for"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Judá;", "Judah;"], ["yo,", "I,"], ["yo", "I"], ["mismo", "same"], ["despedazaré", "and"], ["y", "and"], ["me", "me"], ["iré;", "go;"], ["quitaré,", "take,"], ["y", "and"], ["no", "not"], ["habrá", "there-shall-be"], ["quien", "who"], ["libre.", "free."]]},
  {num:15,words:[["Andaré", "walk"], ["y", "and"], ["volveré", "return"], ["a", "to"], ["mi", "my"], ["lugar,", "place,"], ["hasta", "until"], ["que", "that"], ["reconozcan", "they"], ["su", "his/her"], ["culpa", "guilt"], ["y", "and"], ["busquen", "seek"], ["mi", "my"], ["rostro.", "face."], ["En", "in"], ["su", "his/her"], ["angustia", "anguish"], ["me", "me"], ["buscarán", "seek"], ["con", "with"], ["afán.", "for."]]},
];
renderVerseSet(v5, 'hos-ch5-verses');

var v6 = [
  {num:1,words:[["Venid", "come"], ["y", "and"], ["volvamos", "us"], ["a", "to"], ["Jehová;", "jehovah;"], ["porque", "because"], ["él", "he"], ["despedazó,", "and,"], ["y", "and"], ["nos", "us"], ["curará;", "he;"], ["hirió,", "smote,"], ["y", "and"], ["nos", "us"], ["vendará.", "us."]]},
  {num:2,words:[["Nos", "us"], ["dará", "shall-give"], ["vida", "life"], ["después", "after/afterward"], ["de", "of"], ["dos", "two"], ["días;", "days;"], ["al", "to-the"], ["tercer", "third"], ["día", "day"], ["nos", "us"], ["levantará,", "raise,"], ["y", "and"], ["viviremos", "live"], ["delante", "before"], ["de", "of"], ["él.", "he."]]},
  {num:3,words:[["Y", "and"], ["conoceremos", "shall-know"], ["y", "and"], ["proseguiremos", "if"], ["en", "in"], ["conocer", "know"], ["a", "to"], ["Jehová;", "jehovah;"], ["segura", "the"], ["como", "as"], ["el", "the"], ["alba", "morning"], ["es", "is"], ["su", "his/her"], ["salida;", "out;"], ["y", "and"], ["vendrá", "shall-come"], ["a", "to"], ["nosotros", "we"], ["como", "as"], ["la", "the"], ["lluvia,", "rain,"], ["como", "as"], ["la", "the"], ["lluvia", "rain"], ["tardía", "latter"], ["y", "and"], ["temprana", "the"], ["a", "to"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:4,words:[["¿Qué", "what"], ["te", "thee"], ["haré", "I-shall-make"], ["a", "to"], ["ti,", "thee,"], ["oh", "oh"], ["Efraín?", "ephraim?"], ["¿Qué", "what"], ["te", "thee"], ["haré", "I-shall-make"], ["a", "to"], ["ti,", "thee,"], ["oh", "oh"], ["Judá?", "Judah?"], ["La", "the"], ["piedad", "godliness"], ["vuestra", "your"], ["es", "is"], ["como", "as"], ["nube", "cloud"], ["de", "of"], ["la", "the"], ["mañana", "morning"], ["y", "and"], ["como", "as"], ["el", "the"], ["rocío", "dew"], ["de", "of"], ["la", "the"], ["madrugada", "dew"], ["que", "that"], ["se", "[refl.]"], ["desvanece.", "away."]]},
  {num:5,words:[["Por", "by/for"], ["esta", "this"], ["causa", "cause/sake"], ["los", "the"], ["he", "I-have"], ["despedazado", "torn"], ["por", "by/for"], ["medio", "midst"], ["de", "of"], ["los", "the"], ["profetas;", "prophets;"], ["con", "with"], ["las", "the"], ["palabras", "words"], ["de", "of"], ["mi", "my"], ["boca", "mouth"], ["los", "the"], ["he", "I-have"], ["matado,", "killed,"], ["y", "and"], ["tus", "thy"], ["juicios", "judgments"], ["serán", "shall-be"], ["como", "as"], ["luz", "light"], ["que", "that"], ["sale.", "goeth."]]},
  {num:6,words:[["Porque", "because"], ["misericordia", "mercy"], ["quiero", "would"], ["y", "and"], ["no", "not"], ["sacrificio,", "sacrifice,"], ["y", "and"], ["conocimiento", "knowledge"], ["de", "of"], ["Dios", "God"], ["más", "more"], ["que", "that"], ["holocaustos.", "sacrifices."]]},
  {num:7,words:[["Mas", "but"], ["ellos,", "they,"], ["cual", "which"], ["Adán,", "Adam,"], ["transgredieron", "transgressed"], ["el", "the"], ["convenio;", "covenant;"], ["allí", "there"], ["actuaron", "toed"], ["pérfidamente", "dealt"], ["contra", "against"], ["mí.", "me."]]},
  {num:8,words:[["Galaad,", "Gilead,"], ["ciudad", "city"], ["de", "of"], ["obradores", "workers"], ["de", "of"], ["iniquidad,", "iniquity,"], ["manchada", "and"], ["de", "of"], ["sangre.", "blood."]]},
  {num:9,words:[["Y", "and"], ["como", "as"], ["ladrones", "thieves"], ["al", "to-the"], ["acecho", "robbers"], ["de", "of"], ["algún", "some"], ["hombre,", "man,"], ["así", "thus"], ["una", "a"], ["compañía", "company"], ["de", "of"], ["sacerdotes", "priests"], ["mata", "man"], ["en", "in"], ["el", "the"], ["camino", "way"], ["hacia", "toward"], ["Siquem;", "shechem;"], ["así", "thus"], ["cometen", "commit"], ["perversidad.", "lewdness."]]},
  {num:10,words:[["En", "in"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel", "Israel"], ["he", "I-have"], ["visto", "seen"], ["algo", "something"], ["horrible;", "of;"], ["allí", "there"], ["fornicó", "the"], ["Efraín;", "ephraim;"], ["se", "[refl.]"], ["contaminó", "israel"], ["Israel.", "Israel."]]},
  {num:11,words:[["Para", "for"], ["ti", "thee"], ["también,", "also,"], ["oh", "oh"], ["Judá,", "Judah,"], ["está", "is"], ["preparada", "prepared"], ["una", "a"], ["siega,", "harvest,"], ["cuando", "when"], ["yo", "I"], ["haga", "let-do"], ["volver", "return"], ["de", "of"], ["la", "the"], ["cautividad", "captivity"], ["a", "to"], ["mi", "my"], ["pueblo.", "people."]]},
];
renderVerseSet(v6, 'hos-ch6-verses');

var v7 = [
  {num:1,words:[["Mientras", "while"], ["yo", "I"], ["quería", "wanted"], ["curar", "have"], ["a", "to"], ["Israel,", "Israel,"], ["se", "[refl.]"], ["descubrió", "discovered"], ["la", "the"], ["iniquidad", "iniquity"], ["de", "of"], ["Efraín", "ephraim"], ["y", "and"], ["las", "the"], ["maldades", "wickedness"], ["de", "of"], ["Samaria,", "samaria,"], ["porque", "because"], ["hacen", "do/make"], ["engaño;", "guile;"], ["y", "and"], ["entra", "enter"], ["el", "the"], ["ladrón,", "thief,"], ["y", "and"], ["la", "the"], ["banda", "band"], ["de", "of"], ["salteadores", "of"], ["despoja", "spoil"], ["por", "by/for"], ["fuera.", "outside/were."]]},
  {num:2,words:[["Y", "and"], ["no", "not"], ["consideran", "consider"], ["en", "in"], ["su", "his/her"], ["corazón", "heart"], ["que", "that"], ["tengo", "I-have"], ["memoria", "remembrance"], ["de", "of"], ["toda", "all"], ["su", "his/her"], ["maldad;", "wickedness;"], ["ahora", "now"], ["los", "the"], ["rodean", "about"], ["sus", "his/her"], ["propias", "own"], ["obras;", "works;"], ["delante", "before"], ["de", "of"], ["mí", "me"], ["están.", "are."]]},
  {num:3,words:[["Con", "with"], ["su", "his/her"], ["maldad", "wickedness"], ["alegran", "rejoice"], ["al", "to-the"], ["rey,", "king,"], ["y", "and"], ["a", "to"], ["los", "the"], ["príncipes", "princes"], ["con", "with"], ["sus", "his/her"], ["mentiras.", "lyings."]]},
  {num:4,words:[["Todos", "all"], ["ellos", "they"], ["son", "are"], ["adúlteros;", "adulterers;"], ["son", "are"], ["como", "as"], ["horno", "furnace"], ["encendido", "kindled"], ["por", "by/for"], ["el", "the"], ["hornero,", "the,"], ["que", "that"], ["cesa", "did"], ["de", "of"], ["avivar", "from"], ["el", "the"], ["fuego", "fire"], ["después", "after/afterward"], ["que", "that"], ["está", "is"], ["hecha", "done"], ["la", "the"], ["masa,", "it,"], ["hasta", "until"], ["que", "that"], ["se", "[refl.]"], ["haya", "let-there-be"], ["leudado.", "leavened."]]},
  {num:5,words:[["En", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["nuestro", "our"], ["rey,", "king,"], ["los", "the"], ["príncipes", "princes"], ["lo", "it/him"], ["hicieron", "did/made"], ["enfermar", "sick"], ["con", "with"], ["copas", "bowls"], ["de", "of"], ["vino;", "wine;"], ["extendió", "stretched"], ["su", "his/her"], ["mano", "hand"], ["con", "with"], ["los", "the"], ["escarnecedores.", "scorners."]]},
  {num:6,words:[["Porque", "because"], ["disponen", "they"], ["su", "his/her"], ["corazón", "heart"], ["para", "for"], ["la", "the"], ["intriga,", "like,"], ["como", "as"], ["se", "[refl.]"], ["prepara", "for"], ["un", "a"], ["horno;", "furnace;"], ["toda", "all"], ["la", "the"], ["noche", "night"], ["duerme", "sleepeth"], ["su", "his/her"], ["hornero;", "the;"], ["a", "to"], ["la", "the"], ["mañana", "morning"], ["está", "is"], ["encendido", "kindled"], ["como", "as"], ["llama", "calls/flame"], ["de", "of"], ["fuego.", "fire."]]},
  {num:7,words:[["Todos", "all"], ["ellos", "they"], ["arden", "may-savour"], ["como", "as"], ["un", "a"], ["horno", "furnace"], ["y", "and"], ["devoran", "to"], ["a", "to"], ["sus", "his/her"], ["jueces;", "judges;"], ["han", "have"], ["caído", "fallen"], ["todos", "all"], ["sus", "his/her"], ["reyes;", "kings;"], ["no", "not"], ["hay", "there-is"], ["entre", "among"], ["ellos", "they"], ["quien", "who"], ["a", "to"], ["mí", "me"], ["clame.", "cried."]]},
  {num:8,words:[["Efraín", "ephraim"], ["se", "[refl.]"], ["mezcla", "of"], ["con", "with"], ["los", "the"], ["demás", "rest/others"], ["pueblos;", "peoples;"], ["Efraín", "ephraim"], ["es", "is"], ["como", "as"], ["torta", "a"], ["no", "not"], ["volteada.", "turned."]]},
  {num:9,words:[["Extraños", "strangers"], ["han", "have"], ["devorado", "and"], ["sus", "his/her"], ["fuerzas,", "forces,"], ["y", "and"], ["él", "he"], ["no", "not"], ["lo", "it/him"], ["sabe;", "knows;"], ["y", "and"], ["aun", "even"], ["las", "the"], ["canas", "and"], ["se", "[refl.]"], ["han", "have"], ["esparcido", "scattered"], ["sobre", "upon"], ["él,", "he,"], ["y", "and"], ["él", "he"], ["no", "not"], ["lo", "it/him"], ["sabe.", "knows."]]},
  {num:10,words:[["Y", "and"], ["la", "the"], ["soberbia", "pride"], ["de", "of"], ["Israel", "Israel"], ["testificará", "shall-testify"], ["contra", "against"], ["él", "he"], ["en", "in"], ["su", "his/her"], ["propia", "own"], ["cara;", "face;"], ["y", "and"], ["ellos", "they"], ["no", "not"], ["se", "[refl.]"], ["vuelven", "return"], ["a", "to"], ["Jehová", "jehovah"], ["su", "his/her"], ["Dios", "God"], ["ni", "nor"], ["le", "him/her"], ["buscan", "seek"], ["a", "to"], ["pesar", "sorrow"], ["de", "of"], ["todo", "all"], ["eso.", "that."]]},
  {num:11,words:[["Y", "and"], ["Efraín", "ephraim"], ["es", "is"], ["como", "as"], ["una", "a"], ["paloma", "dove"], ["incauta,", "without,"], ["sin", "without"], ["entendimiento;", "understanding;"], ["llaman", "call"], ["a", "to"], ["Egipto,", "Egypt,"], ["acuden", "may-come"], ["a", "to"], ["Asiria.", "assyria."]]},
  {num:12,words:[["Cuando", "when"], ["vayan,", "servants,"], ["tenderé", "shall"], ["sobre", "upon"], ["ellos", "they"], ["mi", "my"], ["red;", "net;"], ["los", "the"], ["haré", "I-shall-make"], ["caer", "fall"], ["como", "as"], ["aves", "fowl"], ["del", "of-the"], ["cielo;", "heaven;"], ["los", "the"], ["castigaré", "punish"], ["conforme", "according-to"], ["a", "to"], ["lo", "it/him"], ["que", "that"], ["se", "[refl.]"], ["ha", "has"], ["oído", "heard"], ["en", "in"], ["su", "his/her"], ["congregación.", "congregation."]]},
  {num:13,words:[["¡Ay", "wo"], ["de", "of"], ["ellos,", "they,"], ["porque", "because"], ["se", "[refl.]"], ["apartaron", "departed"], ["de", "of"], ["mí!", "me!"], ["¡Destrucción", "destruction"], ["sobre", "upon"], ["ellos,", "they,"], ["porque", "because"], ["contra", "against"], ["mí", "me"], ["transgredieron!", "though!"], ["Yo", "I"], ["los", "the"], ["redimiría,", "would-redeem,"], ["pero", "but"], ["ellos", "they"], ["hablaron", "spake"], ["mentiras", "lyings"], ["contra", "against"], ["mí.", "me."]]},
  {num:14,words:[["Y", "and"], ["no", "not"], ["clamaron", "cried"], ["a", "to"], ["mí", "me"], ["con", "with"], ["su", "his/her"], ["corazón", "heart"], ["cuando", "when"], ["gemían", "when"], ["sobre", "upon"], ["sus", "his/her"], ["camas;", "beds;"], ["por", "by/for"], ["el", "the"], ["trigo", "wheat"], ["y", "and"], ["el", "the"], ["mosto", "corn"], ["se", "[refl.]"], ["congregaron;", "wine;"], ["se", "[refl.]"], ["rebelaron", "rebelled"], ["contra", "against"], ["mí.", "me."]]},
  {num:15,words:[["Aunque", "although"], ["yo", "I"], ["adiestré", "bound"], ["y", "and"], ["fortalecí", "strengthened"], ["sus", "his/her"], ["brazos,", "arms,"], ["contra", "against"], ["mí", "me"], ["traman", "they"], ["el", "the"], ["mal.", "evil."]]},
  {num:16,words:[["Se", "[refl.]"], ["volvieron,", "returned,"], ["pero", "but"], ["no", "not"], ["al", "to-the"], ["Altísimo;", "most;"], ["fueron", "were"], ["como", "as"], ["arco", "bow"], ["engañoso;", "a;"], ["caerán", "fall"], ["sus", "his/her"], ["príncipes", "princes"], ["a", "to"], ["espada", "sword"], ["por", "by/for"], ["la", "the"], ["insolencia", "for"], ["de", "of"], ["su", "his/her"], ["lengua;", "tongue;"], ["esto", "this"], ["será", "shall-be"], ["su", "his/her"], ["escarnio", "derision"], ["en", "in"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto.", "Egypt."]]},
];
renderVerseSet(v7, 'hos-ch7-verses');

var v8 = [
  {num:1,words:[["Pon", "prophesy"], ["a", "to"], ["tu", "thy"], ["boca", "mouth"], ["la", "the"], ["trompeta.", "trump."], ["Vendrá", "shall-come"], ["como", "as"], ["águila", "eagle"], ["contra", "against"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jehová,", "jehovah,"], ["porque", "because"], ["traspasaron", "because"], ["mi", "my"], ["convenio", "covenant"], ["y", "and"], ["se", "[refl.]"], ["rebelaron", "rebelled"], ["contra", "against"], ["mi", "my"], ["ley.", "law."]]},
  {num:2,words:[["A", "to"], ["mí", "me"], ["clamará", "cry"], ["Israel:", "Israel:"], ["¡Dios", "God"], ["mío,", "mine,"], ["te", "thee"], ["conocemos!", "know!"]]},
  {num:3,words:[["Israel", "Israel"], ["desechó", "toed"], ["el", "the"], ["bien;", "well;"], ["el", "the"], ["enemigo", "enemy"], ["lo", "it/him"], ["perseguirá.", "shall-should."]]},
  {num:4,words:[["Ellos", "they"], ["establecieron", "they"], ["reyes,", "kings,"], ["pero", "but"], ["no", "not"], ["de", "of"], ["parte", "part"], ["mía;", "mother;"], ["constituyeron", "they"], ["príncipes,", "princes,"], ["pero", "but"], ["yo", "I"], ["no", "not"], ["los", "the"], ["reconocí;", "it;"], ["de", "of"], ["su", "his/her"], ["plata", "silver"], ["y", "and"], ["de", "of"], ["su", "his/her"], ["oro", "gold"], ["hicieron", "did/made"], ["ídolos", "idols"], ["para", "for"], ["sí,", "yea,"], ["para", "for"], ["ser", "be"], ["ellos", "they"], ["mismos", "selves"], ["destruidos.", "destroyed."]]},
  {num:5,words:[["Tu", "thy"], ["becerro,", "calf,"], ["oh", "oh"], ["Samaria,", "samaria,"], ["te", "thee"], ["hizo", "made/did"], ["alejarte;", "off;"], ["se", "[refl.]"], ["encendió", "kindled"], ["mi", "my"], ["enojo", "fury"], ["contra", "against"], ["ellos.", "they."], ["¿Hasta", "until"], ["cuándo", "when"], ["serán", "shall-be"], ["incapaces", "be"], ["de", "of"], ["lograr", "obtain"], ["la", "the"], ["purificación?", "purifying?"]]},
  {num:6,words:[["Porque", "because"], ["de", "of"], ["Israel", "Israel"], ["es", "is"], ["este", "this"], ["becerro;", "calf;"], ["y", "and"], ["un", "a"], ["artífice", "in"], ["lo", "it/him"], ["hizo,", "made/did,"], ["y", "and"], ["no", "not"], ["es", "is"], ["Dios,", "God,"], ["por", "by/for"], ["lo", "it/him"], ["que", "that"], ["será", "shall-be"], ["deshecho", "of"], ["en", "in"], ["pedazos", "pieces"], ["el", "the"], ["becerro", "calf"], ["de", "of"], ["Samaria.", "samaria."]]},
  {num:7,words:[["Porque", "because"], ["sembraron", "sowed"], ["viento,", "wind,"], ["torbellino", "whirlwind"], ["segarán;", "they;"], ["no", "not"], ["tendrán", "power"], ["mies,", "harvest,"], ["ni", "nor"], ["la", "the"], ["espiga", "bud"], ["dará", "shall-give"], ["harina;", "meal;"], ["y", "and"], ["si", "if"], ["la", "the"], ["diere,", "yield,"], ["extraños", "strangers"], ["la", "the"], ["comerán.", "eat."]]},
  {num:8,words:[["Será", "shall-be"], ["devorado", "and"], ["Israel;", "Israel;"], ["pronto", "soon"], ["será", "shall-be"], ["entre", "among"], ["las", "the"], ["naciones", "nations"], ["como", "as"], ["vasija", "vessel"], ["que", "that"], ["no", "not"], ["contiene", "it"], ["nada", "nothing"], ["que", "that"], ["deleite.", "shall."]]},
  {num:9,words:[["Porque", "because"], ["ellos", "they"], ["subieron", "went"], ["a", "to"], ["Asiria", "assyria"], ["como", "as"], ["asno", "ass"], ["montés", "mountains"], ["solitario;", "by;"], ["Efraín", "ephraim"], ["alquiló", "hath"], ["amantes.", "lovers."]]},
  {num:10,words:[["Aunque", "although"], ["se", "[refl.]"], ["alquilen", "they"], ["entre", "among"], ["las", "the"], ["naciones,", "nations,"], ["ahora", "now"], ["los", "the"], ["juntaré;", "gather;"], ["y", "and"], ["comenzarán", "shall-begin"], ["a", "to"], ["disminuir", "shall"], ["por", "by/for"], ["la", "the"], ["carga", "burden"], ["del", "of-the"], ["rey", "king"], ["y", "and"], ["de", "of"], ["los", "the"], ["príncipes.", "princes."]]},
  {num:11,words:[["Porque", "because"], ["multiplicó", "the"], ["Efraín", "ephraim"], ["altares", "altars"], ["para", "for"], ["pecar,", "sin,"], ["ahora", "now"], ["le", "him/her"], ["son", "are"], ["altares", "altars"], ["para", "for"], ["pecar.", "sin."]]},
  {num:12,words:[["Le", "him/her"], ["escribí", "wrote"], ["las", "the"], ["grandezas", "greatnesss"], ["de", "of"], ["mi", "my"], ["ley,", "law,"], ["pero", "but"], ["fueron", "were"], ["tenidas", "were"], ["como", "as"], ["cosa", "thing"], ["extraña.", "strange."]]},
  {num:13,words:[["En", "in"], ["los", "the"], ["sacrificios", "sacrifices"], ["de", "of"], ["mis", "my"], ["ofrendas", "offerings"], ["sacrificaron", "they"], ["carne", "flesh"], ["y", "and"], ["comieron;", "eat;"], ["no", "not"], ["los", "the"], ["aceptó", "the"], ["Jehová.", "jehovah."], ["Ahora", "now"], ["se", "[refl.]"], ["acordará", "remember"], ["de", "of"], ["su", "his/her"], ["iniquidad", "iniquity"], ["y", "and"], ["castigará", "the"], ["sus", "his/her"], ["pecados;", "sins;"], ["ellos", "they"], ["volverán", "return"], ["a", "to"], ["Egipto.", "Egypt."]]},
  {num:14,words:[["Olvidó,", "for,"], ["pues,", "for,"], ["Israel", "Israel"], ["a", "to"], ["su", "his/her"], ["Hacedor", "maker"], ["y", "and"], ["edificó", "built"], ["templos,", "temples,"], ["y", "and"], ["Judá", "Judah"], ["multiplicó", "the"], ["ciudades", "cities"], ["fortificadas;", "fenced;"], ["mas", "but"], ["yo", "I"], ["mandaré", "command"], ["fuego", "fire"], ["a", "to"], ["sus", "his/her"], ["ciudades,", "cities,"], ["el", "the"], ["cual", "which"], ["devorará", "devour"], ["sus", "his/her"], ["palacios.", "palaces."]]},
];
renderVerseSet(v8, 'hos-ch8-verses');

var v9 = [
  {num:1,words:[["No", "not"], ["te", "thee"], ["alegres,", "tidings,"], ["oh", "oh"], ["Israel,", "Israel,"], ["hasta", "until"], ["saltar", "joy,"], ["de", "of"], ["gozo", "joy"], ["como", "as"], ["los", "the"], ["pueblos,", "peoples,"], ["pues", "for"], ["te", "thee"], ["has", "thou-hast"], ["prostituido,", "a,"], ["apartándote", "whoring"], ["de", "of"], ["tu", "thy"], ["Dios;", "God;"], ["amaste", "lovest-thee"], ["salario", "wages"], ["de", "of"], ["ramera", "whore"], ["en", "in"], ["todas", "all"], ["las", "the"], ["eras", "wast"], ["de", "of"], ["trigo.", "wheat."]]},
  {num:2,words:[["La", "the"], ["era", "was"], ["y", "and"], ["el", "the"], ["lagar", "winepress"], ["no", "not"], ["los", "the"], ["mantendrán,", "and,"], ["y", "and"], ["les", "them"], ["fallará", "shall"], ["el", "the"], ["mosto.", "corn."]]},
  {num:3,words:[["No", "not"], ["se", "[refl.]"], ["quedarán", "shall"], ["en", "in"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Jehová,", "jehovah,"], ["sino", "but"], ["que", "that"], ["volverá", "return"], ["Efraín", "ephraim"], ["a", "to"], ["Egipto,", "Egypt,"], ["y", "and"], ["en", "in"], ["Asiria", "assyria"], ["comerán", "eat"], ["vianda", "in"], ["inmunda.", "unclean."]]},
  {num:4,words:[["No", "not"], ["derramarán", "shall-shedding"], ["libación", "continual"], ["de", "of"], ["vino", "wine"], ["a", "to"], ["Jehová,", "jehovah,"], ["ni", "nor"], ["sus", "his/her"], ["sacrificios", "sacrifices"], ["le", "him/her"], ["serán", "shall-be"], ["gratos;", "savours;"], ["será", "shall-be"], ["para", "for"], ["ellos", "they"], ["como", "as"], ["pan", "bread"], ["de", "of"], ["duelo;", "mourned;"], ["todos", "all"], ["los", "the"], ["que", "that"], ["coman", "eat"], ["de", "of"], ["él", "he"], ["serán", "shall-be"], ["impuros.", "unholy."], ["Será,", "shall-be,"], ["pues,", "for,"], ["el", "the"], ["pan", "bread"], ["de", "of"], ["ellos", "they"], ["para", "for"], ["sí", "yea"], ["mismos;", "selves;"], ["ese", "that"], ["pan", "bread"], ["no", "not"], ["entrará", "enter"], ["en", "in"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:5,words:[["¿Qué", "what"], ["haréis", "servile"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["solemnidad", "day,"], ["y", "and"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["fiesta", "feast"], ["de", "of"], ["Jehová?", "jehovah?"]]},
  {num:6,words:[["Porque,", "because,"], ["he", "I-have"], ["aquí,", "here,"], ["se", "[refl.]"], ["fueron", "were"], ["ellos", "they"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["la", "the"], ["destrucción;", "destruction;"], ["Egipto", "Egypt"], ["los", "the"], ["recogerá;", "gather;"], ["Menfis", "shall"], ["los", "the"], ["enterrará;", "the;"], ["la", "the"], ["ortiga", "places"], ["poseerá", "shall-possess"], ["lo", "it/him"], ["deseable", "a"], ["de", "of"], ["su", "his/her"], ["plata,", "silver,"], ["y", "and"], ["el", "the"], ["espino", "shall"], ["crecerá", "shall-grow"], ["en", "in"], ["sus", "his/her"], ["tiendas.", "tents."]]},
  {num:7,words:[["Vinieron", "came"], ["los", "the"], ["días", "days"], ["del", "of-the"], ["castigo;", "punishment;"], ["vinieron", "came"], ["los", "the"], ["días", "days"], ["de", "of"], ["la", "the"], ["retribución.", "are."], ["¡Lo", "it/him"], ["sabrá", "know"], ["Israel!", "Israel!"], ["Necio", "fool"], ["es", "is"], ["el", "the"], ["profeta,", "prophet,"], ["insensato", "fool"], ["el", "the"], ["hombre", "man"], ["de", "of"], ["espíritu,", "Spirit,"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["la", "the"], ["multitud", "multitude"], ["de", "of"], ["tu", "thy"], ["maldad", "wickedness"], ["y", "and"], ["de", "of"], ["tu", "thy"], ["gran", "great"], ["odio.", "hatred."]]},
  {num:8,words:[["El", "the"], ["atalaya", "watchman"], ["de", "of"], ["Efraín", "ephraim"], ["estuvo", "stood"], ["con", "with"], ["mi", "my"], ["Dios,", "God,"], ["pero", "but"], ["el", "the"], ["profeta", "prophet"], ["es", "is"], ["trampa", "snare"], ["de", "of"], ["cazador", "a"], ["en", "in"], ["todos", "all"], ["sus", "his/her"], ["caminos;", "ways;"], ["hay", "there-is"], ["odio", "hatred"], ["en", "in"], ["la", "the"], ["casa", "house"], ["de", "of"], ["su", "his/her"], ["Dios.", "God."]]},
  {num:9,words:[["Se", "[refl.]"], ["han", "have"], ["corrompido", "corrupted"], ["profundamente", "in"], ["como", "as"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["Gabaa;", "gibeah;"], ["ahora", "now"], ["se", "[refl.]"], ["acordará", "remember"], ["de", "of"], ["su", "his/her"], ["iniquidad;", "iniquity;"], ["castigará", "the"], ["sus", "his/her"], ["pecados.", "sins."]]},
  {num:10,words:[["Como", "as"], ["uvas", "grapes"], ["en", "in"], ["el", "the"], ["desierto", "wilderness"], ["hallé", "found"], ["a", "to"], ["Israel;", "Israel;"], ["como", "as"], ["la", "the"], ["fruta", "the"], ["temprana", "the"], ["de", "of"], ["la", "the"], ["higuera", "fig"], ["en", "in"], ["sus", "his/her"], ["principios", "principles"], ["vi", "I-saw"], ["a", "to"], ["vuestros", "your"], ["padres.", "parents."], ["Ellos", "they"], ["acudieron", "comeed"], ["a", "to"], ["Baal-peor,", "baalpeor,"], ["y", "and"], ["se", "[refl.]"], ["apartaron", "departed"], ["para", "for"], ["vergüenza", "shame"], ["y", "and"], ["se", "[refl.]"], ["hicieron", "did/made"], ["abominables", "abominable"], ["como", "as"], ["aquello", "thing"], ["que", "that"], ["amaron.", "loveed."]]},
  {num:11,words:[["La", "the"], ["gloria", "glory"], ["de", "of"], ["Efraín", "ephraim"], ["volará", "shall"], ["cual", "which"], ["ave", "fowl"], ["desde", "from"], ["el", "the"], ["nacimiento,", "birth,"], ["aun", "even"], ["desde", "from"], ["el", "the"], ["vientre", "belly"], ["y", "and"], ["desde", "from"], ["la", "the"], ["concepción.", "conception."]]},
  {num:12,words:[["Y", "and"], ["si", "if"], ["llegan", "they"], ["a", "to"], ["grandes", "great"], ["sus", "his/her"], ["hijos,", "children,"], ["se", "[refl.]"], ["los", "the"], ["quitaré", "take"], ["de", "of"], ["entre", "among"], ["los", "the"], ["hombres,", "men,"], ["porque,", "because,"], ["¡ay", "wo"], ["de", "of"], ["ellos", "they"], ["también,", "also,"], ["cuando", "when"], ["de", "of"], ["ellos", "they"], ["me", "me"], ["aparte!", "turn!"]]},
  {num:13,words:[["Efraín,", "ephraim,"], ["según", "according-to"], ["veo,", "perceive,"], ["es", "is"], ["semejante", "like"], ["a", "to"], ["Tiro,", "tyrus,"], ["asentado", "in"], ["en", "in"], ["un", "a"], ["lugar", "place"], ["delicioso;", "but;"], ["pero", "but"], ["Efraín", "ephraim"], ["sacará", "bring"], ["a", "to"], ["sus", "his/her"], ["hijos", "children"], ["a", "to"], ["la", "the"], ["matanza.", "slaughter."]]},
  {num:14,words:[["Dales,", "gives-them,"], ["oh", "oh"], ["Jehová,", "jehovah,"], ["lo", "it/him"], ["que", "that"], ["les", "them"], ["has", "thou-hast"], ["de", "of"], ["dar;", "give;"], ["dales", "gives-them"], ["matriz", "womb"], ["que", "that"], ["aborte", "womb"], ["y", "and"], ["pechos", "breasts"], ["enjutos.", "breasts."]]},
  {num:15,words:[["Toda", "all"], ["la", "the"], ["maldad", "wickedness"], ["de", "of"], ["ellos", "they"], ["fue", "was/went"], ["en", "in"], ["Gilgal;", "gilgal;"], ["allí,", "there,"], ["pues,", "for,"], ["les", "them"], ["tomé", "took"], ["aversión;", "wickedness;"], ["por", "by/for"], ["la", "the"], ["maldad", "wickedness"], ["de", "of"], ["sus", "his/her"], ["obras", "works"], ["los", "the"], ["echaré", "cast"], ["de", "of"], ["mi", "my"], ["casa;", "house;"], ["no", "not"], ["los", "the"], ["amaré", "shall-love"], ["más;", "more;"], ["todos", "all"], ["sus", "his/her"], ["príncipes", "princes"], ["son", "are"], ["rebeldes.", "rebellious."]]},
  {num:16,words:[["Efraín", "ephraim"], ["fue", "was/went"], ["herido;", "wounded;"], ["se", "[refl.]"], ["secó", "withered"], ["su", "his/her"], ["raíz", "root"], ["y", "and"], ["no", "not"], ["dará", "shall-give"], ["más", "more"], ["fruto;", "fruit;"], ["aunque", "although"], ["engendren,", "forth,"], ["yo", "I"], ["mataré", "will"], ["el", "the"], ["preciado", "even"], ["fruto", "fruit"], ["de", "of"], ["su", "his/her"], ["vientre.", "belly."]]},
  {num:17,words:[["Mi", "my"], ["Dios", "God"], ["los", "the"], ["desechará,", "shall-to,"], ["porque", "because"], ["ellos", "they"], ["no", "not"], ["le", "him/her"], ["escucharon;", "hearkened;"], ["y", "and"], ["andarán", "walk"], ["errantes", "wilderness"], ["entre", "among"], ["las", "the"], ["naciones.", "nations."]]},
];
renderVerseSet(v9, 'hos-ch9-verses');

var v10 = [
  {num:1,words:[["Israel", "Israel"], ["es", "is"], ["una", "a"], ["frondosa", "green"], ["viña", "vineyard"], ["que", "that"], ["da", "gives"], ["fruto", "fruit"], ["para", "for"], ["sí;", "yea;"], ["conforme", "according-to"], ["a", "to"], ["la", "the"], ["abundancia", "abundance"], ["de", "of"], ["su", "his/her"], ["fruto,", "fruit,"], ["multiplicaba", "hath"], ["los", "the"], ["altares;", "altars;"], ["conforme", "according-to"], ["a", "to"], ["la", "the"], ["bondad", "goodness"], ["de", "of"], ["su", "his/her"], ["tierra,", "land/earth,"], ["mejor", "better"], ["adorna", "made"], ["sus", "his/her"], ["ídolos.", "idols."]]},
  {num:2,words:[["Está", "is"], ["dividido", "divided"], ["su", "his/her"], ["corazón.", "heart."], ["Ahora", "now"], ["serán", "shall-be"], ["hallados", "found"], ["culpables;", "guilty;"], ["él", "he"], ["quebrantará", "shall-the"], ["sus", "his/her"], ["altares", "altars"], ["y", "and"], ["destruirá", "destroy"], ["sus", "his/her"], ["ídolos.", "idols."]]},
  {num:3,words:[["Porque", "because"], ["dirán", "say"], ["ahora:", "now:"], ["No", "not"], ["tenemos", "we-have"], ["rey", "king"], ["porque", "because"], ["no", "not"], ["temimos", "we"], ["a", "to"], ["Jehová;", "jehovah;"], ["¿y", "and"], ["qué", "what"], ["haría", "would"], ["el", "the"], ["rey", "king"], ["por", "by/for"], ["nosotros?", "we?"]]},
  {num:4,words:[["Han", "have"], ["hablado", "spoken"], ["palabras,", "words,"], ["jurando", "hand"], ["en", "in"], ["vano", "vain"], ["al", "to-the"], ["hacer", "make/do"], ["convenio;", "covenant;"], ["por", "by/for"], ["tanto,", "therefore,"], ["el", "the"], ["juicio", "judgment"], ["florecerá", "shall"], ["como", "as"], ["hierba", "herb"], ["venenosa", "in"], ["en", "in"], ["los", "the"], ["surcos", "of"], ["del", "of-the"], ["campo.", "field."]]},
  {num:5,words:[["Por", "by/for"], ["las", "the"], ["becerras", "heifers"], ["de", "of"], ["Bet-avén", "shall"], ["serán", "shall-be"], ["atemorizados", "because"], ["los", "the"], ["moradores", "inhabitants"], ["de", "of"], ["Samaria;", "samaria;"], ["porque", "because"], ["su", "his/her"], ["pueblo", "people"], ["se", "[refl.]"], ["lamentará", "thereof"], ["a", "to"], ["causa", "cause/sake"], ["del", "of-the"], ["becerro,", "calf,"], ["y", "and"], ["también", "also"], ["sus", "his/her"], ["sacerdotes", "priests"], ["que", "that"], ["en", "in"], ["ello", "it"], ["se", "[refl.]"], ["regocijaban,", "for,"], ["por", "by/for"], ["su", "his/her"], ["gloria,", "glory,"], ["la", "the"], ["cual", "which"], ["será", "shall-be"], ["disipada", "departed"], ["de", "of"], ["él.", "he."]]},
  {num:6,words:[["Y", "and"], ["aun", "even"], ["será", "shall-be"], ["llevado", "carried"], ["a", "to"], ["Asiria", "assyria"], ["como", "as"], ["presente", "present"], ["al", "to-the"], ["rey", "king"], ["Jareb;", "jareb;"], ["Efraín", "ephraim"], ["será", "shall-be"], ["avergonzado,", "ashamed,"], ["e", "and"], ["Israel", "Israel"], ["se", "[refl.]"], ["avergonzará", "shall"], ["de", "of"], ["su", "his/her"], ["propio", "own"], ["consejo.", "counsel."]]},
  {num:7,words:[["De", "of"], ["Samaria", "samaria"], ["fue", "was/went"], ["cortado", "cut"], ["su", "his/her"], ["rey", "king"], ["como", "as"], ["espuma", "off"], ["sobre", "upon"], ["la", "the"], ["superficie", "face"], ["de", "of"], ["las", "the"], ["aguas.", "waters."]]},
  {num:8,words:[["Y", "and"], ["los", "the"], ["lugares", "places"], ["altos", "high"], ["de", "of"], ["Avén,", "the,"], ["el", "the"], ["pecado", "sin"], ["de", "of"], ["Israel,", "Israel,"], ["serán", "shall-be"], ["destruidos;", "destroyed;"], ["crecerán", "shall"], ["sobre", "upon"], ["sus", "his/her"], ["altares", "altars"], ["espino", "up"], ["y", "and"], ["cardo.", "altars."], ["Y", "and"], ["dirán", "say"], ["a", "to"], ["los", "the"], ["montes:", "mountains:"], ["¡Cubridnos!,", "mountains!,"], ["y", "and"], ["a", "to"], ["los", "the"], ["collados:", "hills:"], ["¡Caed", "hills,"], ["sobre", "upon"], ["nosotros!", "we!"]]},
  {num:9,words:[["Desde", "from"], ["los", "the"], ["días", "days"], ["de", "of"], ["Gabaa", "gibeah"], ["has", "thou-hast"], ["pecado,", "sin,"], ["oh", "oh"], ["Israel;", "Israel;"], ["allí", "there"], ["se", "[refl.]"], ["han", "have"], ["quedado.", "remained."], ["¿No", "not"], ["los", "the"], ["alcanzó", "toed"], ["la", "the"], ["batalla", "battle"], ["en", "in"], ["Gabaa", "gibeah"], ["contra", "against"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["los", "the"], ["inicuos?", "wicked?"]]},
  {num:10,words:[["Y", "and"], ["los", "the"], ["castigaré", "punish"], ["cuando", "when"], ["lo", "it/him"], ["desee;", "should;"], ["y", "and"], ["pueblos", "peoples"], ["se", "[refl.]"], ["juntarán", "gathered"], ["contra", "against"], ["ellos", "they"], ["cuando", "when"], ["sean", "let-be"], ["atados", "bound"], ["por", "by/for"], ["su", "his/her"], ["doble", "double"], ["iniquidad.", "iniquity."]]},
  {num:11,words:[["Y", "and"], ["Efraín", "ephraim"], ["era", "was"], ["novilla", "bullock"], ["domada,", "heifer,"], ["amadora", "is"], ["del", "of-the"], ["trillar;", "and;"], ["mas", "but"], ["yo", "I"], ["pasaré", "pass"], ["sobre", "upon"], ["su", "his/her"], ["lozana", "i"], ["cerviz.", "stiffnecked."], ["Pero", "but"], ["yo", "I"], ["haré", "I-shall-make"], ["llevar", "carry"], ["yugo", "yoke"], ["a", "to"], ["Efraín;", "ephraim;"], ["arará", "judah"], ["Judá;", "Judah;"], ["quebrará", "plow,"], ["sus", "his/her"], ["propios", "own"], ["terrones", "break"], ["Jacob.", "Jacob."]]},
  {num:12,words:[["Sembrad", "sow"], ["para", "for"], ["vosotros", "you"], ["en", "in"], ["justicia;", "justice/righteousness;"], ["segad", "reap"], ["para", "for"], ["vosotros", "you"], ["en", "in"], ["misericordia;", "mercy;"], ["haced", "do"], ["para", "for"], ["vosotros", "you"], ["barbecho,", "ground,"], ["porque", "because"], ["es", "is"], ["el", "the"], ["tiempo", "time"], ["de", "of"], ["buscar", "seek"], ["a", "to"], ["Jehová,", "jehovah,"], ["hasta", "until"], ["que", "that"], ["venga", "let-come"], ["y", "and"], ["haga", "let-do"], ["llover", "rain"], ["justicia", "justice/righteousness"], ["sobre", "upon"], ["vosotros.", "you."]]},
  {num:13,words:[["Habéis", "you-have"], ["arado", "the"], ["maldad;", "wickedness;"], ["segasteis", "ye"], ["iniquidad.", "iniquity."], ["Habéis", "you-have"], ["comido", "eaten"], ["fruto", "fruit"], ["de", "of"], ["mentira,", "lies,"], ["porque", "because"], ["confiaste", "thou-thee"], ["en", "in"], ["tu", "thy"], ["camino,", "way,"], ["en", "in"], ["la", "the"], ["multitud", "multitude"], ["de", "of"], ["tus", "thy"], ["valientes.", "valour."]]},
  {num:14,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["en", "in"], ["tus", "thy"], ["pueblos", "peoples"], ["se", "[refl.]"], ["levantará", "raise"], ["un", "a"], ["alboroto,", "tumult,"], ["y", "and"], ["todas", "all"], ["tus", "thy"], ["fortalezas", "holds"], ["serán", "shall-be"], ["destruidas,", "destroyed,"], ["como", "as"], ["destruyó", "destroyed"], ["Salmán", "spoiled"], ["a", "to"], ["Bet-arbel", "betharbel"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["batalla;", "battle;"], ["la", "the"], ["madre", "mother"], ["fue", "was/went"], ["estrellada", "in"], ["junto", "together"], ["con", "with"], ["sus", "his/her"], ["hijos.", "children."]]},
  {num:15,words:[["Así", "thus"], ["hará", "shall-make"], ["a", "to"], ["vosotros", "you"], ["Bet-el", "bethel"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["vuestra", "your"], ["gran", "great"], ["maldad;", "wickedness;"], ["al", "to-the"], ["amanecer", "morning"], ["será", "shall-be"], ["del", "of-the"], ["todo", "all"], ["destruido", "destroyed"], ["el", "the"], ["rey", "king"], ["de", "of"], ["Israel.", "Israel."]]},
];
renderVerseSet(v10, 'hos-ch10-verses');

var v11 = [
  {num:1,words:[["Cuando", "when"], ["Israel", "Israel"], ["era", "was"], ["niño,", "child,"], ["yo", "I"], ["lo", "it/him"], ["amé,", "loved,"], ["y", "and"], ["de", "of"], ["Egipto", "Egypt"], ["llamé", "called"], ["a", "to"], ["mi", "my"], ["hijo.", "son."]]},
  {num:2,words:[["Cuanto", "as-much-as"], ["más", "more"], ["los", "the"], ["llamaban", "called"], ["los", "the"], ["profetas,", "prophets,"], ["más", "more"], ["se", "[refl.]"], ["alejaban", "from"], ["de", "of"], ["ellos;", "they;"], ["a", "to"], ["los", "the"], ["baales", "baalim"], ["ofrecían", "and"], ["sacrificios", "sacrifices"], ["y", "and"], ["a", "to"], ["las", "the"], ["imágenes", "groves"], ["talladas", "graven"], ["quemaban", "and"], ["incienso.", "incense."]]},
  {num:3,words:[["Yo", "I"], ["con", "with"], ["todo", "all"], ["eso", "that"], ["enseñaba", "taught"], ["a", "to"], ["andar", "walk"], ["al", "to-the"], ["mismo", "same"], ["Efraín,", "ephraim,"], ["tomándolo", "taking-it"], ["por", "by/for"], ["los", "the"], ["brazos;", "arms;"], ["pero", "but"], ["ellos", "they"], ["no", "not"], ["comprendieron", "their"], ["que", "that"], ["yo", "I"], ["los", "the"], ["sanaba.", "was-toing."]]},
  {num:4,words:[["Con", "with"], ["cuerdas", "cords"], ["humanas", "buts"], ["los", "the"], ["atraje,", "cords,"], ["con", "with"], ["cuerdas", "cords"], ["de", "of"], ["amor;", "love;"], ["y", "and"], ["fui", "am"], ["para", "for"], ["ellos", "they"], ["como", "as"], ["los", "the"], ["que", "that"], ["alzan", "up"], ["el", "the"], ["yugo", "yoke"], ["de", "of"], ["sobre", "upon"], ["su", "his/her"], ["cerviz,", "stiffnecked,"], ["y", "and"], ["puse", "set"], ["delante", "before"], ["de", "of"], ["ellos", "they"], ["la", "the"], ["comida.", "meat."]]},
  {num:5,words:[["No", "not"], ["volverá", "return"], ["a", "to"], ["tierra", "land/earth"], ["de", "of"], ["Egipto,", "Egypt,"], ["sino", "but"], ["que", "that"], ["el", "the"], ["mismo", "same"], ["asirio", "assyrian"], ["será", "shall-be"], ["su", "his/her"], ["rey,", "king,"], ["porque", "because"], ["no", "not"], ["quisieron", "would"], ["volverse", "return-[refl.]"], ["a", "to"], ["mí.", "me."]]},
  {num:6,words:[["Y", "and"], ["caerá", "fall"], ["la", "the"], ["espada", "sword"], ["sobre", "upon"], ["sus", "his/her"], ["ciudades", "cities"], ["y", "and"], ["consumirá", "palaces"], ["sus", "his/her"], ["aldeas,", "villages,"], ["y", "and"], ["las", "the"], ["consumirá", "palaces"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["sus", "his/her"], ["propios", "own"], ["consejos.", "counsels."]]},
  {num:7,words:[["Y", "and"], ["mi", "my"], ["pueblo", "people"], ["está", "is"], ["aferrado", "to"], ["a", "to"], ["la", "the"], ["rebelión", "rebellion"], ["contra", "against"], ["mí;", "me;"], ["aunque", "although"], ["llaman", "call"], ["al", "to-the"], ["Altísimo,", "most,"], ["ninguno", "none"], ["absolutamente", "all"], ["quiere", "if"], ["enaltecerle.", "him."]]},
  {num:8,words:[["¿Cómo", "how"], ["podré", "me"], ["abandonarte,", "i,"], ["oh", "oh"], ["Efraín?", "ephraim?"], ["¿Te", "thee"], ["entregaré", "deliver"], ["yo,", "I,"], ["Israel?", "Israel?"], ["¿Cómo", "how"], ["podré", "me"], ["yo", "I"], ["hacerte", "make"], ["como", "as"], ["Adma", "thee"], ["o", "or"], ["ponerte", "put/place-thee"], ["como", "as"], ["a", "to"], ["Zeboim?", "set?"], ["Mi", "my"], ["corazón", "heart"], ["se", "[refl.]"], ["conmueve", "mine"], ["dentro", "within"], ["de", "of"], ["mí,", "me,"], ["se", "[refl.]"], ["inflama", "my"], ["toda", "all"], ["mi", "my"], ["compasión.", "compassion."]]},
  {num:9,words:[["No", "not"], ["ejecutaré", "shall-for"], ["el", "the"], ["furor", "fury"], ["de", "of"], ["mi", "my"], ["ira", "wrath"], ["ni", "nor"], ["volveré", "return"], ["para", "for"], ["destruir", "destroy"], ["a", "to"], ["Efraín,", "ephraim,"], ["porque", "because"], ["Dios", "God"], ["soy,", "I-am,"], ["y", "and"], ["no", "not"], ["hombre;", "man;"], ["soy", "I-am"], ["el", "the"], ["Santo", "holy"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti,", "thee,"], ["y", "and"], ["no", "not"], ["entraré", "into"], ["en", "in"], ["la", "the"], ["ciudad.", "city."]]},
  {num:10,words:[["En", "in"], ["pos", "follow"], ["de", "of"], ["Jehová", "jehovah"], ["caminarán;", "lord;"], ["él", "he"], ["rugirá", "roar"], ["como", "as"], ["león;", "lion;"], ["cuando", "when"], ["ruja,", "he,"], ["entonces", "then"], ["los", "the"], ["hijos", "children"], ["vendrán", "far"], ["temblando", "and"], ["del", "of-the"], ["occidente.", "westward."]]},
  {num:11,words:[["Acudirán", "shall-come"], ["temblando", "and"], ["como", "as"], ["ave", "fowl"], ["de", "of"], ["Egipto", "Egypt"], ["y", "and"], ["como", "as"], ["paloma", "dove"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Asiria;", "assyria;"], ["y", "and"], ["los", "the"], ["haré", "I-shall-make"], ["morar", "dwell"], ["en", "in"], ["sus", "his/her"], ["casas,", "houses,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:12,words:[["Me", "me"], ["rodeó", "about"], ["Efraín", "ephraim"], ["con", "with"], ["mentira,", "lies,"], ["y", "and"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel", "Israel"], ["con", "with"], ["engaño,", "guile,"], ["pero", "but"], ["Judá", "Judah"], ["aún", "still/yet"], ["camina", "walketh"], ["con", "with"], ["Dios", "God"], ["y", "and"], ["es", "is"], ["fiel", "faithful"], ["con", "with"], ["los", "the"], ["santos.", "saints."]]},
];
renderVerseSet(v11, 'hos-ch11-verses');

var v12 = [
  {num:1,words:[["Efraín", "ephraim"], ["se", "[refl.]"], ["apacienta", "he"], ["de", "of"], ["viento", "wind"], ["y", "and"], ["va", "goes"], ["tras", "after"], ["el", "the"], ["solano;", "wind;"], ["mentira", "lies"], ["y", "and"], ["destrucción", "destruction"], ["aumentan", "and"], ["continuamente,", "continually,"], ["porque", "because"], ["hicieron", "did/made"], ["alianza", "league"], ["con", "with"], ["los", "the"], ["asirios", "assyria"], ["y", "and"], ["llevan", "are"], ["aceite", "oil"], ["a", "to"], ["Egipto.", "Egypt."]]},
  {num:2,words:[["Pleito", "the"], ["tiene", "has"], ["Jehová", "jehovah"], ["con", "with"], ["Judá", "Judah"], ["y", "and"], ["castigará", "the"], ["a", "to"], ["Jacob", "Jacob"], ["conforme", "according-to"], ["a", "to"], ["sus", "his/her"], ["caminos;", "ways;"], ["le", "him/her"], ["pagará", "or"], ["conforme", "according-to"], ["a", "to"], ["sus", "his/her"], ["obras.", "works."]]},
  {num:3,words:[["En", "in"], ["el", "the"], ["vientre", "belly"], ["tomó", "took"], ["por", "by/for"], ["el", "the"], ["calcañar", "heel"], ["a", "to"], ["su", "his/her"], ["hermano,", "brother,"], ["y", "and"], ["con", "with"], ["su", "his/her"], ["fuerza", "strength"], ["luchó", "fought"], ["con", "with"], ["Dios.", "God."]]},
  {num:4,words:[["Luchó", "fought"], ["con", "with"], ["el", "the"], ["ángel", "angel"], ["y", "and"], ["prevaleció;", "and;"], ["lloró", "wept"], ["y", "and"], ["le", "him/her"], ["suplicó;", "the;"], ["en", "in"], ["Bet-el", "bethel"], ["le", "him/her"], ["halló,", "found,"], ["y", "and"], ["allí", "there"], ["habló", "spoke"], ["con", "with"], ["nosotros.", "we."]]},
  {num:5,words:[["Mas", "but"], ["Jehová", "jehovah"], ["es", "is"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos.", "armies."], ["¡Jehová", "jehovah"], ["es", "is"], ["su", "his/her"], ["nombre!", "name!"]]},
  {num:6,words:[["Tú,", "thou,"], ["pues,", "for,"], ["conviértete", "the-thee"], ["a", "to"], ["tu", "thy"], ["Dios;", "God;"], ["guarda", "keeps"], ["la", "the"], ["misericordia", "mercy"], ["y", "and"], ["el", "the"], ["juicio,", "judgment,"], ["y", "and"], ["en", "in"], ["tu", "thy"], ["Dios", "God"], ["confía", "trusteth"], ["siempre.", "always."]]},
  {num:7,words:[["Al", "to-the"], ["mercader", "is"], ["que", "that"], ["tiene", "has"], ["en", "in"], ["su", "his/her"], ["mano", "hand"], ["pesas", "thes"], ["falsas,", "to,"], ["le", "him/her"], ["gusta", "of"], ["oprimir.", "oppress."]]},
  {num:8,words:[["Y", "and"], ["dijo", "said"], ["Efraín:", "ephraim:"], ["Ciertamente", "surely"], ["yo", "I"], ["me", "me"], ["he", "I-have"], ["enriquecido;", "i;"], ["he", "I-have"], ["hallado", "found"], ["riquezas", "riches"], ["para", "for"], ["mí;", "me;"], ["nadie", "no-one"], ["hallará", "find"], ["iniquidad", "iniquity"], ["en", "in"], ["mí", "me"], ["ni", "nor"], ["pecado", "sin"], ["en", "in"], ["todos", "all"], ["mis", "my"], ["trabajos.", "they."]]},
  {num:9,words:[["Sin", "without"], ["embargo,", "nevertheless,"], ["yo", "I"], ["soy", "I-am"], ["Jehová", "jehovah"], ["tu", "thy"], ["Dios", "God"], ["desde", "from"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto;", "Egypt;"], ["aún", "still/yet"], ["te", "thee"], ["haré", "I-shall-make"], ["morar", "dwell"], ["en", "in"], ["tiendas,", "tents,"], ["como", "as"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["la", "the"], ["fiesta", "feast"], ["solemne.", "solemn."]]},
  {num:10,words:[["Y", "and"], ["he", "I-have"], ["hablado", "spoken"], ["a", "to"], ["los", "the"], ["profetas,", "prophets,"], ["y", "and"], ["yo", "I"], ["multipliqué", "have"], ["las", "the"], ["visiones", "visions"], ["y", "and"], ["por", "by/for"], ["medio", "midst"], ["de", "of"], ["los", "the"], ["profetas", "prophets"], ["usé", "the"], ["similitudes.", "prophets."]]},
  {num:11,words:[["¿Hay", "there-is"], ["iniquidad", "iniquity"], ["en", "in"], ["Galaad?", "Gilead?"], ["Ciertamente", "surely"], ["vanidad", "vanity"], ["han", "have"], ["sido.", "been."], ["En", "in"], ["Gilgal", "gilgal"], ["sacrificaron", "they"], ["bueyes,", "oxen,"], ["y", "and"], ["aún", "still/yet"], ["son", "are"], ["sus", "his/her"], ["altares", "altars"], ["como", "as"], ["montones", "heaps"], ["en", "in"], ["los", "the"], ["surcos", "of"], ["del", "of-the"], ["campo.", "field."]]},
  {num:12,words:[["Mas", "but"], ["Jacob", "Jacob"], ["huyó", "fled"], ["a", "to"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Aram;", "aram;"], ["y", "and"], ["sirvió", "served"], ["Israel", "Israel"], ["para", "for"], ["adquirir", "to"], ["una", "a"], ["esposa,", "wife,"], ["y", "and"], ["para", "for"], ["adquirir", "to"], ["una", "a"], ["esposa", "wife"], ["fue", "was/went"], ["pastor.", "shepherd."]]},
  {num:13,words:[["Y", "and"], ["por", "by/for"], ["medio", "midst"], ["de", "of"], ["un", "a"], ["profeta", "prophet"], ["Jehová", "jehovah"], ["hizo", "made/did"], ["subir", "go-up"], ["a", "to"], ["Israel", "Israel"], ["de", "of"], ["Egipto,", "Egypt,"], ["y", "and"], ["por", "by/for"], ["un", "a"], ["profeta", "prophet"], ["fue", "was/went"], ["guardado.", "kept."]]},
  {num:14,words:[["Efraín", "ephraim"], ["ha", "has"], ["irritado", "angered"], ["a", "to"], ["Dios", "God"], ["amargamente;", "the;"], ["por", "by/for"], ["tanto,", "therefore,"], ["su", "his/her"], ["sangre", "blood"], ["dejará", "leave"], ["sobre", "upon"], ["él,", "he,"], ["y", "and"], ["su", "his/her"], ["Señor", "Lord"], ["le", "him/her"], ["devolverá", "shall"], ["su", "his/her"], ["oprobio.", "reproach."]]},
];
renderVerseSet(v12, 'hos-ch12-verses');

var v13 = [
  {num:1,words:[["Cuando", "when"], ["Efraín", "ephraim"], ["hablaba,", "talked,"], ["había", "had"], ["temor;", "fear;"], ["fue", "was/went"], ["ensalzado", "exalted"], ["en", "in"], ["Israel,", "Israel,"], ["pero", "but"], ["pecó", "sinned"], ["por", "by/for"], ["causa", "cause/sake"], ["de", "of"], ["Baal", "baal"], ["y", "and"], ["murió.", "died."]]},
  {num:2,words:[["Y", "and"], ["ahora", "now"], ["continúan", "continue"], ["en", "in"], ["su", "his/her"], ["pecado,", "sin,"], ["y", "and"], ["de", "of"], ["su", "his/her"], ["plata", "silver"], ["se", "[refl.]"], ["han", "have"], ["hecho,", "done/made,"], ["según", "according-to"], ["su", "his/her"], ["entendimiento,", "understanding,"], ["imágenes", "groves"], ["de", "of"], ["fundición,", "molten,"], ["ídolos,", "idols,"], ["todo", "all"], ["ello", "it"], ["obra", "work"], ["de", "of"], ["artífices.", "of."], ["De", "of"], ["ellos", "they"], ["dicen:", "say:"], ["Que", "that"], ["los", "the"], ["hombres", "men"], ["que", "that"], ["sacrifican", "men"], ["besen", "that"], ["a", "to"], ["los", "the"], ["becerros.", "calves."]]},
  {num:3,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["serán", "shall-be"], ["como", "as"], ["la", "the"], ["niebla", "the"], ["de", "of"], ["la", "the"], ["mañana", "morning"], ["o", "or"], ["como", "as"], ["el", "the"], ["rocío", "dew"], ["de", "of"], ["la", "the"], ["madrugada", "away,"], ["que", "that"], ["se", "[refl.]"], ["desvanece,", "chaff,"], ["como", "as"], ["el", "the"], ["tamo", "chaff"], ["que", "that"], ["la", "the"], ["tempestad", "storm"], ["arroja", "cast"], ["de", "of"], ["la", "the"], ["era", "was"], ["y", "and"], ["como", "as"], ["el", "the"], ["humo", "smoke"], ["que", "that"], ["sale", "goeth"], ["de", "of"], ["la", "the"], ["chimenea.", "chimney."]]},
  {num:4,words:[["Mas", "but"], ["yo", "I"], ["soy", "I-am"], ["Jehová", "jehovah"], ["tu", "thy"], ["Dios", "God"], ["desde", "from"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto;", "Egypt;"], ["no", "not"], ["reconocerás", "shall-spy"], ["a", "to"], ["otro", "other"], ["Dios", "God"], ["fuera", "outside/were"], ["de", "of"], ["mí,", "me,"], ["ni", "nor"], ["a", "to"], ["otro", "other"], ["Salvador", "savior"], ["sino", "but"], ["a", "to"], ["mí.", "me."]]},
  {num:5,words:[["Yo", "I"], ["te", "thee"], ["conocí", "thee"], ["en", "in"], ["el", "the"], ["desierto,", "wilderness,"], ["en", "in"], ["tierra", "land/earth"], ["de", "of"], ["sequía.", "drought."]]},
  {num:6,words:[["En", "in"], ["sus", "his/her"], ["pastos", "pasture"], ["se", "[refl.]"], ["saciaron;", "filled;"], ["se", "[refl.]"], ["saciaron", "filled"], ["y", "and"], ["se", "[refl.]"], ["ensoberbeció", "filled,"], ["su", "his/her"], ["corazón;", "heart;"], ["por", "by/for"], ["esta", "this"], ["causa", "cause/sake"], ["se", "[refl.]"], ["olvidaron", "they"], ["de", "of"], ["mí.", "me."]]},
  {num:7,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["yo", "I"], ["seré", "I-shall-be"], ["para", "for"], ["ellos", "they"], ["como", "as"], ["león;", "lion;"], ["como", "as"], ["un", "a"], ["leopardo", "leopard"], ["en", "in"], ["el", "the"], ["camino", "way"], ["los", "the"], ["acecharé.", "them."]]},
  {num:8,words:[["Como", "as"], ["osa", "bear"], ["que", "that"], ["ha", "has"], ["perdido", "lost"], ["sus", "his/her"], ["cachorros", "whelps"], ["los", "the"], ["encontraré", "shall-find"], ["y", "and"], ["desgarraré", "and"], ["las", "the"], ["fibras", "rend"], ["de", "of"], ["su", "his/her"], ["corazón,", "heart,"], ["y", "and"], ["allí", "there"], ["los", "the"], ["devoraré", "shall-to"], ["como", "as"], ["león;", "lion;"], ["una", "a"], ["fiera", "the"], ["del", "of-the"], ["campo", "field"], ["los", "the"], ["despedazará.", "them."]]},
  {num:9,words:[["Te", "thee"], ["destruiste,", "israel,"], ["oh", "oh"], ["Israel,", "Israel,"], ["pero", "but"], ["en", "in"], ["mí", "me"], ["está", "is"], ["tu", "thy"], ["ayuda.", "assistance."]]},
  {num:10,words:[["¿Dónde", "where"], ["está", "is"], ["tu", "thy"], ["rey,", "king,"], ["para", "for"], ["que", "that"], ["te", "thee"], ["salve", "the"], ["en", "in"], ["todas", "all"], ["tus", "thy"], ["ciudades,", "cities,"], ["y", "and"], ["tus", "thy"], ["jueces,", "judges,"], ["de", "of"], ["quienes", "who"], ["dijiste:", "saidst:"], ["Dame", "give"], ["rey", "king"], ["y", "and"], ["príncipes?", "princes?"]]},
  {num:11,words:[["Te", "thee"], ["di", "give/I-gave"], ["rey", "king"], ["en", "in"], ["mi", "my"], ["furor,", "fury,"], ["y", "and"], ["te", "thee"], ["lo", "it/him"], ["quité", "away"], ["en", "in"], ["mi", "my"], ["ira.", "wrath."]]},
  {num:12,words:[["Atada", "loose"], ["está", "is"], ["la", "the"], ["iniquidad", "iniquity"], ["de", "of"], ["Efraín;", "ephraim;"], ["su", "his/her"], ["pecado", "sin"], ["está", "is"], ["guardado.", "kept."]]},
  {num:13,words:[["Dolores", "sorrows"], ["como", "as"], ["de", "of"], ["mujer", "woman"], ["que", "that"], ["está", "is"], ["de", "of"], ["parto", "travail"], ["le", "him/her"], ["vendrán;", "far;"], ["es", "is"], ["un", "a"], ["hijo", "son"], ["insensato", "fool"], ["que", "that"], ["no", "not"], ["se", "[refl.]"], ["coloca", "he"], ["en", "in"], ["posición", "for"], ["al", "to-the"], ["momento", "moment"], ["del", "of-the"], ["alumbramiento.", "children."]]},
  {num:14,words:[["De", "of"], ["manos", "hands"], ["del", "of-the"], ["Seol", "grave"], ["los", "the"], ["rescataré,", "power,"], ["los", "the"], ["redimiré", "shall-redeem"], ["de", "of"], ["la", "the"], ["muerte.", "death."], ["¿Dónde", "where"], ["están,", "are,"], ["oh", "oh"], ["muerte,", "death,"], ["tus", "thy"], ["plagas?", "plagues?"], ["¿Dónde", "where"], ["está,", "is,"], ["oh", "oh"], ["Seol,", "grave,"], ["tu", "thy"], ["destrucción?", "destruction?"], ["La", "the"], ["compasión", "compassion"], ["se", "[refl.]"], ["esconderá", "be"], ["de", "of"], ["mis", "my"], ["ojos.", "eyes."]]},
  {num:15,words:[["Aunque", "although"], ["él", "he"], ["fructifique", "fruitful"], ["entre", "among"], ["los", "the"], ["hermanos,", "brethren,"], ["vendrá", "shall-come"], ["el", "the"], ["solano,", "wind,"], ["viento", "wind"], ["de", "of"], ["Jehová,", "jehovah,"], ["subiendo", "went"], ["del", "of-the"], ["desierto,", "wilderness,"], ["y", "and"], ["se", "[refl.]"], ["secará", "the"], ["su", "his/her"], ["fuente,", "laver,"], ["y", "and"], ["se", "[refl.]"], ["secará", "the"], ["su", "his/her"], ["manantial;", "fountain;"], ["él", "he"], ["saqueará", "dried"], ["el", "the"], ["tesoro", "treasure"], ["de", "of"], ["todos", "all"], ["los", "the"], ["objetos", "things"], ["preciosos.", "precious."]]},
  {num:16,words:[["Samaria", "samaria"], ["será", "shall-be"], ["considerada", "a"], ["culpable,", "guilty,"], ["porque", "because"], ["se", "[refl.]"], ["rebeló", "rebelled"], ["contra", "against"], ["su", "his/her"], ["Dios;", "God;"], ["caerán", "fall"], ["a", "to"], ["espada;", "sword;"], ["sus", "his/her"], ["niños", "children"], ["serán", "shall-be"], ["estrellados,", "pieces,"], ["y", "and"], ["sus", "his/her"], ["mujeres", "women"], ["encintas", "child"], ["serán", "shall-be"], ["abiertas.", "the."]]},
];
renderVerseSet(v13, 'hos-ch13-verses');

var v14 = [
  {num:1,words:[["¡Vuélvete,", "return,"], ["oh", "oh"], ["Israel,", "Israel,"], ["a", "to"], ["Jehová", "jehovah"], ["tu", "thy"], ["Dios,", "God,"], ["porque", "because"], ["por", "by/for"], ["tu", "thy"], ["iniquidad", "iniquity"], ["has", "thou-hast"], ["caído!", "fallen!"]]},
  {num:2,words:[["Tomad", "take"], ["con", "with"], ["vosotros", "you"], ["palabras,", "words,"], ["y", "and"], ["volveos", "turn"], ["a", "to"], ["Jehová", "jehovah"], ["y", "and"], ["decidle:", "and:"], ["Quita", "taketh"], ["toda", "all"], ["iniquidad", "iniquity"], ["y", "and"], ["acéptanos", "he-us"], ["bien,", "well,"], ["y", "and"], ["ofreceremos", "shall-offer"], ["el", "the"], ["fruto", "fruit"], ["de", "of"], ["nuestros", "our"], ["labios.", "lips."]]},
  {num:3,words:[["No", "not"], ["nos", "us"], ["librará", "deliver"], ["Asiria;", "assyria;"], ["no", "not"], ["montaremos", "will"], ["a", "to"], ["caballo", "horse"], ["ni", "nor"], ["nunca", "never"], ["más", "more"], ["diremos", "what"], ["a", "to"], ["la", "the"], ["obra", "work"], ["de", "of"], ["nuestras", "provisions"], ["manos:", "hands:"], ["Dioses", "gods"], ["nuestros,", "our,"], ["porque", "because"], ["en", "in"], ["ti", "thee"], ["el", "the"], ["huérfano", "fatherless"], ["alcanzará", "shall"], ["misericordia.", "mercy."]]},
  {num:4,words:[["Yo", "I"], ["los", "the"], ["sanaré", "heal"], ["de", "of"], ["su", "his/her"], ["rebelión;", "rebellion;"], ["los", "the"], ["amaré", "shall-love"], ["por", "by/for"], ["mi", "my"], ["propia", "own"], ["voluntad,", "will,"], ["porque", "because"], ["mi", "my"], ["furor", "fury"], ["se", "[refl.]"], ["apartó", "nebat"], ["de", "of"], ["ellos.", "they."]]},
  {num:5,words:[["Yo", "I"], ["seré", "I-shall-be"], ["a", "to"], ["Israel", "Israel"], ["como", "as"], ["el", "the"], ["rocío;", "dew;"], ["él", "he"], ["florecerá", "shall"], ["como", "as"], ["lirio", "the"], ["y", "and"], ["extenderá", "hand"], ["sus", "his/her"], ["raíces", "roots"], ["como", "as"], ["el", "the"], ["Líbano.", "lebanon."]]},
  {num:6,words:[["Se", "[refl.]"], ["extenderán", "spread"], ["sus", "his/her"], ["ramas,", "branches,"], ["y", "and"], ["será", "shall-be"], ["su", "his/her"], ["gloria", "glory"], ["como", "as"], ["la", "the"], ["del", "of-the"], ["olivo", "olive"], ["y", "and"], ["su", "his/her"], ["fragancia", "and"], ["como", "as"], ["la", "the"], ["del", "of-the"], ["Líbano.", "lebanon."]]},
  {num:7,words:[["Volverán", "return"], ["los", "the"], ["que", "that"], ["moran", "dwell"], ["bajo", "under"], ["su", "his/her"], ["sombra;", "shadow;"], ["serán", "shall-be"], ["vivificados", "shall"], ["como", "as"], ["trigo", "wheat"], ["y", "and"], ["florecerán", "and"], ["como", "as"], ["la", "the"], ["vid;", "vine;"], ["su", "his/her"], ["fama", "fame"], ["será", "shall-be"], ["como", "as"], ["la", "the"], ["del", "of-the"], ["vino", "wine"], ["del", "of-the"], ["Líbano.", "lebanon."]]},
  {num:8,words:[["Efraín:", "ephraim:"], ["¿Qué", "what"], ["tengo", "I-have"], ["yo", "I"], ["que", "that"], ["ver", "see"], ["ya", "already"], ["con", "with"], ["los", "the"], ["ídolos?", "idols?"], ["Yo", "I"], ["respondo", "i"], ["y", "and"], ["lo", "it/him"], ["cuido;", "him;"], ["yo", "I"], ["seré", "I-shall-be"], ["a", "to"], ["él", "he"], ["como", "as"], ["el", "the"], ["ciprés", "fir"], ["verde;", "green;"], ["en", "in"], ["mí", "me"], ["será", "shall-be"], ["hallado", "found"], ["tu", "thy"], ["fruto.", "fruit."]]},
  {num:9,words:[["¿Quién", "who"], ["es", "is"], ["sabio", "wise"], ["para", "for"], ["que", "that"], ["entienda", "understand"], ["esto,", "this,"], ["y", "and"], ["prudente", "prudent"], ["para", "for"], ["que", "that"], ["lo", "it/him"], ["sepa?", "know?"], ["Porque", "because"], ["los", "the"], ["caminos", "ways"], ["de", "of"], ["Jehová", "jehovah"], ["son", "are"], ["rectos,", "upright,"], ["y", "and"], ["los", "the"], ["justos", "righteous"], ["andarán", "walk"], ["por", "by/for"], ["ellos;", "they;"], ["mas", "but"], ["los", "the"], ["rebeldes", "rebellious"], ["caerán", "fall"], ["en", "in"], ["ellos.", "they."]]},
];
renderVerseSet(v14, 'hos-ch14-verses');

})();
