(function() {
var v1 = [
  {num:1,words:[["La", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["que", "that"], ["vino", "wine"], ["a", "to"], ["Oseas","Hoshea"], ["hijo", "son"], ["de", "of"], ["Beeri,","Beeri,"], ["en", "in"], ["días", "days"], ["de", "of"], ["Uzías,","Uzziah,"], ["Jotam,","Jotham,"], ["Acaz", "ahaz"], ["y", "and"], ["Ezequías,", "Hezekiah,"], ["reyes", "kings"], ["de", "of"], ["Judá,", "Judah,"], ["y", "and"], ["en", "in"], ["días", "days"], ["de", "of"], ["Jeroboam","Jeroboam"], ["hijo", "son"], ["de", "of"], ["Joás,","Joash,"], ["rey", "king"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:2,words:[["El","the"],["principio","beginning"],["de","of"],["la","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["por medio de","by means of"],["Oseas.","hoshea."],["Y","and"],["dijo","said"],["Jehová","jehovah"],["a","to"],["Oseas:","hoshea:"],["Ve,","you-sees,"],["toma","take"],["para","for"],["ti","you"],["como","as"],["esposa","wife"],["una","a"],["mujer","woman"],["dada","given"],["a","to"],["la","the"],["prostitución","whoredoms"],["y","and"],["ten","merciful"],["hijos","children"],["de","of"],["prostitución;","prostitution;"],["porque","because"],["la","the"],["tierra","land"],["se","himself"],["ha","has"],["dado","given"],["a","to"],["la","the"],["fornicación,","fornication,"],["apartándose","from"],["de","of"],["Jehová.","jehovah."]]},
  {num:3,words:[["Fue,","went,"], ["pues,", "for,"], ["y", "and"], ["tomó", "took"], ["a", "to"], ["Gomer","Gomer"], ["hija", "daughter"], ["de", "of"], ["Diblaim,", "daughter,"], ["la", "the"], ["cual", "which"], ["concibió", "conceived"], ["y", "and"], ["le","him"], ["dio", "gave"], ["a", "to"], ["luz", "light"], ["un", "a"], ["hijo.", "son."]]},
  {num:4,words:[["Y","and"],["le","him"],["dijo","said"],["Jehová:","jehovah:"],["Ponle","prophesy-him"],["por","for"],["nombre","name"],["Jezreel,","Jezreel,"],["porque","because"],["dentro","within"],["de","of"],["poco","little"],["yo","I"],["castigaré","will-punish"],["a","to"],["la","the"],["casa","house"],["de","of"],["Jehú","Jehu"],["por","for"],["motivo","reason"],["de","of"],["la","the"],["sangre","blood"],["de","of"],["Jezreel,","Jezreel,"],["y","and"],["haré","I will make"],["cesar","ceasing"],["el","the"],["reino","kingdom"],["de","of"],["la","the"],["casa","house"],["de","of"],["Israel.","Israel."]]},
  {num:5,words:[["Y","and"],["acaecerá","it"],["que","that"],["en","in"],["aquel","that"],["día","day"],["quebraré","day,"],["yo","I"],["el","the"],["arco","bow"],["de","of"],["Israel","Israel"],["en","in"],["el","the"],["valle","valley"],["de","of"],["Jezreel.","Jezreel."]]},
  {num:6,words:[["Y","and"],["ella","she"],["concibió","conceived"],["otra","other"],["vez","time"],["y","and"],["dio","gave"],["a","to"],["luz","light"],["una","a"],["hija.","daughter."],["Y","and"],["le","him"],["dijo","said"],["Dios:","God:"],["Ponle","prophesy-him"],["por","for"],["nombre","name"],["Lo-ruhama;","Lo-ruhamah;"],["porque","because"],["no","not"],["tendré","I-spare"],["más","more"],["misericordia","mercy"],["de","of"],["la","the"],["casa","house"],["de","of"],["Israel,","Israel,"],["sino que","but"],["los","the"],["quitaré","take"],["del","of-the"],["todo.","all."]]},
  {num:7,words:[["Mas","but"],["de","of"],["la","the"],["casa","house"],["de","of"],["Judá","Judah"],["tendré","I-spare"],["misericordia","mercy"],["y","and"],["los","the"],["salvaré","save"],["por","by"],["Jehová","jehovah"],["su","their"],["Dios;","God;"],["y","and"],["no","not"],["los","the"],["salvaré","save"],["con","with"],["arco,","bow,"],["ni","nor"],["con","with"],["espada,","sword,"],["ni","nor"],["con","with"],["batalla,","battle,"],["ni","nor"],["con","with"],["caballos","horses"],["ni","nor"],["jinetes.","horsemen."]]},
  {num:8,words:[["Y","and"],["después","after"],["de","of"],["haber","have"],["destetado","weaned"],["a","to"],["Lo-ruhama,","Lo-ruhamah,"],["Gomer","Gomer"],["concibió","conceived"],["y","and"],["dio","gave"],["a","to"],["luz","light"],["un","a"],["hijo.","son."]]},
  {num:9,words:[["Y", "and"], ["dijo", "said"], ["Dios:", "God:"], ["Ponle", "prophesy-him"], ["por","for"], ["nombre", "name"], ["Lo-ammi,", "for,"], ["porque", "because"], ["vosotros", "you"], ["no", "not"], ["sois","you-are"], ["mi", "my"], ["pueblo,", "people,"], ["ni", "nor"], ["yo", "I"], ["seré","I will be"], ["vuestro", "your"], ["Dios.", "God."]]},
  {num:10,words:[["Con","with"],["todo,","all,"],["será","shall-be"],["el","the"],["número","number"],["de","of"],["los","the"],["hijos","children"],["de","of"],["Israel","Israel"],["como","as"],["la","the"],["arena","sand"],["del","of-the"],["mar,","sea,"],["que","that"],["no","not"],["se","itself"],["puede","can"],["medir","to-measure"],["ni","nor"],["contar.","beside."],["Y","and"],["sucederá","pass"],["que","that"],["en","in"],["el","the"],["lugar","place"],["donde","where"],["se","itself"],["les","them"],["dijo:","said:"],["Vosotros","you"],["no","not"],["sois","you-are"],["mi","my"],["pueblo,","people,"],["se","itself"],["les","them"],["dirá:","will-say:"],["Sois","you-are"],["hijos","children"],["del","of-the"],["Dios","God"],["viviente.","living."]]},
  {num:11,words:[["Y","and"],["los","the"],["hijos","children"],["de","of"],["Judá","Judah"],["y","and"],["de","of"],["Israel","Israel"],["serán","they-shall-be"],["congregados","gathered"],["en","in"],["uno,","one,"],["y","and"],["nombrarán","they-shall-the"],["para","for"],["sí","yes"],["un","a"],["solo","alone"],["jefe","chief"],["y","and"],["subirán","up"],["de","of"],["la","the"],["tierra,","land,"],["porque","because"],["grande","great"],["será","shall-be"],["el","the"],["día","day"],["de","of"],["Jezreel.","Jezreel."]]},
];
renderVerseSet(v1, 'hos-ch1-verses');

var v2 = [
  {num:1,words:[["Decid","you-tell"],["a","to"],["vuestros","your"],["hermanos:","brothers:"],["Ammi,","brothers,"],["y","and"],["a","to"],["vuestras","your"],["hermanas:","sisters:"],["Ruhama.","ruhamah."]]},
  {num:2,words:[["Contended","you-plead"],["con","with"],["vuestra","your"],["madre,","mother,"],["contended,","you-contend,"],["porque","because"],["ella","she"],["no","not"],["es","is"],["mi","my"],["esposa","wife"],["ni","nor"],["yo","I"],["su","her"],["marido;","husband;"],["que","that"],["quite,","away,"],["pues,","for,"],["sus","her"],["fornicaciones","whoredoms"],["de","of"],["su","her"],["rostro","face"],["y","and"],["sus","her"],["adulterios","adulteries"],["de","of"],["entre","among"],["sus","her"],["pechos;","breasts;"]]},
  {num:3,words:[["no","not"],["sea","be"],["que","that"],["yo","I"],["la","the"],["desnude","may-undress"],["del","of-the"],["todo,","all,"],["y","and"],["la","the"],["deje","said"],["como","as"],["el","the"],["día","day"],["en que","that"],["nació,","was-born,"],["y","and"],["la","the"],["haga","let-do"],["como","as"],["un","a"],["desierto,","wilderness,"],["y","and"],["la","the"],["deje","said"],["como","as"],["tierra","land"],["seca","dries"],["y","and"],["la","the"],["mate","mate"],["de","of"],["sed.","thirst."]]},
  {num:4,words:[["No","not"],["tendré","I-spare"],["misericordia","mercy"],["de","of"],["sus","her"],["hijos,","children,"],["porque","because"],["son","they-are"],["hijos","children"],["de","of"],["prostitución.","whoredoms."]]},
  {num:5,words:[["Porque","because"],["su","his"],["madre","mother"],["se","himself"],["prostituyó;","played;"],["la","the"],["que","that"],["los","the"],["dio","gave"],["a","to"],["luz","light"],["se","himself"],["deshonró,","shamefully,"],["porque","because"],["dijo:","said:"],["Iré","I-will-go"],["tras","after"],["mis","my"],["amantes,","lovers,"],["que","that"],["me","me"],["dan","dan"],["mi","my"],["pan","bread"],["y","and"],["mi","my"],["agua,","water,"],["mi","my"],["lana","wool"],["y","and"],["mi","my"],["lino,","twined,"],["mi","my"],["aceite","oil"],["y","and"],["mi","my"],["bebida.","drink."]]},
  {num:6,words:[["Por tanto,","therefore,"],["he aquí,","behold,"],["yo","I"],["cercaré","up"],["tu","your"],["camino","way"],["con","with"],["espinos,","briers,"],["y","and"],["la","the"],["cercaré","I-will-surround"],["con","with"],["seto,","that,"],["y","and"],["no","not"],["hallará","will-find"],["ella","she"],["sus","her"],["caminos.","ways."]]},
  {num:7,words:[["Y","and"],["seguirá","will-follow"],["a","to"],["sus","her"],["amantes,","lovers,"],["pero","but"],["no","not"],["los","the"],["alcanzará;","will-reach;"],["los","the"],["buscará,","shall-seek,"],["pero","but"],["no","not"],["los","the"],["hallará.","find."],["Entonces","then"],["dirá:","will-say:"],["Iré","I-will-go"],["y","and"],["volveré","I-will-return"],["a","to"],["mi","my"],["primer","first"],["marido,","husband,"],["porque","because"],["mejor","better"],["me","me"],["iba","went"],["entonces","then"],["que","that"],["ahora.","now."]]},
  {num:8,words:[["Y","and"],["ella","she"],["no","not"],["reconoció","knew"],["que","that"],["yo","I"],["le","her"],["daba","gave"],["el","the"],["trigo,","wheat,"],["y","and"],["el","the"],["vino","wine"],["y","and"],["el","the"],["aceite,","oil,"],["y","and"],["que","that"],["le","her"],["multipliqué","I-multiplied"],["la","the"],["plata","silver"],["y","and"],["el","the"],["oro","gold"],["que","that"],["usaban","they-used"],["para","for"],["Baal.","Baal."]]},
  {num:9,words:[["Por tanto,","therefore,"],["yo","I"],["volveré","will-return"],["y","and"],["tomaré","I-will-take"],["mi","my"],["trigo","wheat"],["a","to"],["su","her"],["tiempo","time"],["y","and"],["mi","my"],["vino","wine"],["en","in"],["su","her"],["sazón,","seasoning,"],["y","and"],["le","her"],["quitaré","I-take"],["mi","my"],["lana","wool"],["y","and"],["mi","my"],["lino","twined"],["que","that"],["le","her"],["había","had"],["dado","given"],["para","for"],["cubrir","to-cover"],["su","her"],["desnudez.","nakedness."]]},
  {num:10,words:[["Y","and"],["ahora","now"],["descubriré","I-shall-to"],["yo","I"],["su","her"],["lascivia","lewdness"],["delante","before"],["de","of"],["los","the"],["ojos","eyes"],["de","of"],["sus","her"],["amantes,","lovers,"],["y","and"],["nadie","no-one"],["la","the"],["librará","deliver"],["de","of"],["mi","my"],["mano.","hand."]]},
  {num:11,words:[["Y", "and"], ["haré","I will make"], ["cesar", "ceasing"], ["todo", "all"], ["su","her"], ["gozo,", "joy,"], ["sus","her"], ["fiestas,", "moons,"], ["sus","her"], ["lunas", "moons"], ["nuevas", "new"], ["y", "and"], ["sus","her"], ["días", "days"], ["de", "of"], ["reposo", "rest"], ["y", "and"], ["todas", "all"], ["sus","her"], ["fiestas", "moons"], ["solemnes.", "moons."]]},
  {num:12,words:[["Asolaré","I-will"],["sus","her"],["vides","and"],["y","and"],["sus","her"],["higueras,","figs,"],["de","of"],["las","the"],["cuales","which"],["ha","has"],["dicho:","said:"],["Esta","this"],["es","is"],["la","the"],["paga","pays"],["que","that"],["me","me"],["han","have"],["dado","given"],["mis","my"],["amantes.","lovers."],["Y","and"],["las","the"],["reduciré","I-will-reduce"],["a","to"],["un","a"],["matorral,","forest,"],["y","and"],["se","themselves"],["las","the"],["comerán","will eat"],["las","the"],["bestias","beasts"],["del","of-the"],["campo.","field."]]},
  {num:13,words:[["Y","and"],["la","the"],["castigaré","punish"],["por","for"],["los","the"],["días","days"],["en que","that"],["quemaba","incense"],["incienso","incense"],["a","to"],["los","the"],["baales,","baalim,"],["y","and"],["se","herself"],["adornaba","adorned"],["con","with"],["sus","her"],["zarcillos","earrings"],["y","and"],["sus","her"],["joyeles,","and,"],["y","and"],["se","herself"],["iba","went"],["tras","after"],["sus","her"],["amantes","lovers"],["y","and"],["se","herself"],["olvidaba","forgat"],["de","of"],["mí,","me,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:14,words:[["Pero","but"],["he aquí,","behold,"],["yo","I"],["la","the"],["atraeré,","I-will-attract,"],["y","and"],["la","the"],["llevaré","bring"],["al","to-the"],["desierto","wilderness"],["y","and"],["hablaré","I-will-speak"],["a","to"],["su","her"],["corazón.","heart."]]},
  {num:15,words:[["Y","and"],["le","her"],["daré","I-shall-give"],["sus","her"],["viñas","vineyards"],["desde","from"],["allí,","there,"],["y","and"],["el","the"],["valle","valley"],["de","of"],["Acor","Achor"],["será","shall-be"],["como","as"],["puerta","gate"],["de","of"],["esperanza;","hope;"],["y","and"],["allí","there"],["cantará","will-sing"],["como","as"],["en","in"],["los","the"],["días","days"],["de","of"],["su","her"],["juventud,","youth,"],["y","and"],["como","as"],["en","in"],["el","the"],["día","day"],["de","of"],["su","her"],["subida","going"],["de","of"],["la","the"],["tierra","land"],["de","of"],["Egipto.","Egypt."]]},
  {num:16,words:[["Y", "and"], ["sucederá", "pass"], ["que", "that"], ["en", "in"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["me", "me"], ["llamarás", "call"], ["Ishi,","Ishi,"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["me", "me"], ["llamarás", "call"], ["Baali.", "baali."]]},
  {num:17,words:[["Porque","because"],["quitaré","I-take"],["de","of"],["su","her"],["boca","mouth"],["los","the"],["nombres","names"],["de","of"],["los","the"],["baales,","baalim,"],["y","and"],["nunca","never"],["más","more"],["serán","they-shall-be"],["recordados","remembered"],["por","for"],["sus","her"],["nombres.","names."]]},
  {num:18,words:[["Y","and"],["haré","I will make"],["por","for"],["ellos","they"],["convenio","covenant"],["en","in"],["aquel","that"],["día","day"],["con","with"],["las","the"],["bestias","beasts"],["del","of-the"],["campo,","field,"],["y","and"],["con","with"],["las","the"],["aves","fowls"],["del","of-the"],["cielo","heaven"],["y","and"],["con","with"],["las","the"],["serpientes","serpents"],["de","of"],["la","the"],["tierra;","earth;"],["y","and"],["quebraré","I-will-break"],["el","the"],["arco","bow"],["y","and"],["la","the"],["espada,","sword,"],["y","and"],["quitaré","I-take"],["la","the"],["guerra","war"],["de","of"],["la","the"],["tierra","earth"],["y","and"],["los","the"],["haré","I will make"],["reposar","to-rest"],["seguros.","sure."]]},
  {num:19,words:[["Y", "and"], ["te","you"], ["desposaré", "betroth"], ["conmigo", "with-me"], ["para", "for"], ["siempre;", "always;"], ["te","you"], ["desposaré","yes,"], ["conmigo", "with-me"], ["en", "in"], ["justicia,","righteousness,"], ["y", "and"], ["en", "in"], ["juicio,", "judgment,"], ["y", "and"], ["en", "in"], ["benignidad", "the"], ["y", "and"], ["en", "in"], ["misericordia.", "mercy."]]},
  {num:20,words:[["Y","and"],["te","you"],["desposaré","betroth"],["conmigo","with-me"],["en","in"],["fidelidad,","faithfulness,"],["y","and"],["conocerás","you-will-know"],["a","to"],["Jehová.","jehovah."]]},
  {num:21,words:[["Y","and"],["acontecerá","shall-come-to-pass"],["que","that"],["en","in"],["aquel","that"],["día","day"],["responderé,","I-answer,"],["dice","says"],["Jehová;","jehovah;"],["yo","I"],["responderé","answer"],["a","to"],["los","the"],["cielos,","heavens,"],["y","and"],["ellos","they"],["responderán","will-answer"],["a","to"],["la","the"],["tierra;","earth;"]]},
  {num:22,words:[["y","and"],["la","the"],["tierra","earth"],["responderá","answer"],["al","to-the"],["trigo,","wheat,"],["y","and"],["al","to-the"],["vino","wine"],["y","and"],["al","to-the"],["aceite,","oil,"],["y","and"],["ellos","they"],["responderán","will-answer"],["a","to"],["Jezreel.","Jezreel."]]},
  {num:23,words:[["Y","and"],["la","the"],["sembraré","shall-sow"],["para","for"],["mí","me"],["en","in"],["la","the"],["tierra,","earth,"],["y","and"],["tendré","I-spare"],["misericordia","mercy"],["de","of"],["Lo-ruhama;","mercy;"],["y","and"],["diré","I-tell"],["a","to"],["Lo-ammi:","which:"],["¡Pueblo","people"],["mío","mine"],["eres","are"],["tú!,","you!,"],["y","and"],["él","he"],["dirá:","will-say:"],["¡Dios","God"],["mío!","mine!"]]},
];
renderVerseSet(v2, 'hos-ch2-verses');

var v3 = [
  {num:1,words:[["Y","and"],["me","me"],["dijo","said"],["otra","other"],["vez","time"],["Jehová:","jehovah:"],["Ve,","you-sees,"],["ama","loves"],["a","to"],["una","a"],["mujer","woman"],["amada","beloved"],["de","of"],["su","her"],["compañero,","companion,"],["aunque","although"],["adúltera,","adulteress,"],["tal","such"],["como","as"],["Jehová","jehovah"],["ama","loves"],["a","to"],["los","the"],["hijos","children"],["de","of"],["Israel,","Israel,"],["los","the"],["cuales","which"],["miran","they-look"],["a","to"],["dioses","gods"],["ajenos","gods"],["y","and"],["aman","they-love"],["los","the"],["panes","loaves"],["de","of"],["pasas.","To passes."]]},
  {num:2,words:[["La","the"],["compré","I-bought"],["entonces","then"],["para","for"],["mí","me"],["por","for"],["quince","fifteen"],["piezas","pieces"],["de","of"],["plata","silver"],["y","and"],["un","a"],["homer","barley,"],["y","and"],["medio","midst"],["de","of"],["cebada.","barley."]]},
  {num:3,words:[["Y","and"],["le","her"],["dije:","I-said:"],["Tú","you"],["estarás","will"],["conmigo","with-me"],["muchos","many"],["días;","days;"],["no","not"],["fornicarás","will-fornicate"],["ni","nor"],["tomarás","you-will-take"],["otro","other"],["hombre;","man;"],["lo","it/him"],["mismo","same"],["haré","I will make"],["yo","I"],["contigo.","with-you."]]},
  {num:4,words:[["Porque","because"],["muchos","many"],["días","days"],["estarán","they-will-be"],["los","the"],["hijos","children"],["de","of"],["Israel","Israel"],["sin","without"],["rey,","king,"],["y","and"],["sin","without"],["príncipe,","prince,"],["y","and"],["sin","without"],["sacrificio,","sacrifice,"],["y","and"],["sin","without"],["estatua,","image,"],["y","and"],["sin","without"],["efod","ephod"],["y","and"],["sin","without"],["terafines.","teraphim."]]},
  {num:5,words:[["Después","afterward"],["volverán","they-will-return"],["los","the"],["hijos","children"],["de","of"],["Israel","Israel"],["y","and"],["buscarán","they-seek"],["a","to"],["Jehová","jehovah"],["su","his"],["Dios","God"],["y","and"],["a","to"],["David,","David,"],["su","his"],["rey;","king;"],["y","and"],["temerán","they-will-fear"],["a","to"],["Jehová","jehovah"],["y","and"],["a","to"],["su","his"],["bondad","goodness"],["en","in"],["los","the"],["últimos","last"],["días.","days."]]},
];
renderVerseSet(v3, 'hos-ch3-verses');

var v4 = [
  {num:1,words:[["Oíd","you-hear"],["la","the"],["palabra","word"],["de","of"],["Jehová,","jehovah,"],["hijos","children"],["de","of"],["Israel,","Israel,"],["porque","because"],["Jehová","jehovah"],["contiende","lord"],["con","with"],["los","the"],["moradores","inhabitants"],["de","of"],["la","the"],["tierra,","land,"],["porque","because"],["no","not"],["hay","there-is"],["verdad,","truth,"],["ni","nor"],["misericordia","mercy"],["ni","nor"],["conocimiento","knowledge"],["de","of"],["Dios","God"],["en","in"],["la","the"],["tierra.","land."]]},
  {num:2,words:[["El","the"],["perjurar,","swearing,"],["y","and"],["el","the"],["mentir,","lie,"],["y","and"],["el","the"],["matar,","slay,"],["y","and"],["el","the"],["hurtar","and"],["y","and"],["el","the"],["cometer","commit"],["adulterio","adultery"],["prevalecen,","they-break,"],["y","and"],["el","the"],["derramar","shedding"],["sangre","blood"],["tras","after"],["sangre.","blood."]]},
  {num:3,words:[["Por","for"],["lo","it/him"],["cual","which"],["la","the"],["tierra","land"],["estará","shall-be"],["de","of"],["duelo,","mourned,"],["y","and"],["desfallecerá","will-faint"],["todo","all"],["morador","inhabitant"],["de","of"],["ella","she"],["con","with"],["las","the"],["bestias","beasts"],["del","of-the"],["campo","field"],["y","and"],["las","the"],["aves","fowls"],["del","of-the"],["cielo;","heaven;"],["y","and"],["aun","even"],["los","the"],["peces","fish"],["del","of-the"],["mar","sea"],["desaparecerán.","away."]]},
  {num:4,words:[["Que","that"],["ningún","no"],["hombre","man"],["contienda","strife"],["ni","nor"],["reprenda","may-reprimand"],["a","to"],["otro","other"],["hombre,","man,"],["porque","because"],["tu","your"],["pueblo","people"],["es","is"],["como","as"],["los","the"],["que","that"],["contienden","they-strive"],["con","with"],["el","the"],["sacerdote.","priest."]]},
  {num:5,words:[["Caerás,","you-will-fall,"],["por tanto,","therefore,"],["en","in"],["pleno","in"],["día,","day,"],["y","and"],["caerá","will-fall"],["también","also"],["contigo","with-you"],["el","the"],["profeta","prophet"],["de","of"],["noche;","night;"],["y","and"],["a","to"],["tu","your"],["madre","mother"],["destruiré.","I-will-destroy."]]},
  {num:6,words:[["Mi","my"],["pueblo","people"],["fue","was"],["destruido","destroyed"],["porque","because"],["le","my"],["faltó","lacked"],["conocimiento.","knowledge."],["Por cuanto","because"],["tú","you"],["desechaste","rejected"],["el","the"],["conocimiento,","knowledge,"],["yo","I"],["te","you"],["desecharé","shall-to"],["a","to"],["ti","you"],["y","and"],["no","not"],["serás","you-will-be"],["sacerdote","priest"],["para","for"],["mí;","me;"],["y","and"],["porque","because"],["olvidaste","you-forgot"],["la","the"],["ley","law"],["de","of"],["tu","your"],["Dios,","God,"],["también","also"],["yo","I"],["me","me"],["olvidaré","forget"],["de","of"],["tus","your"],["hijos.","children."]]},
  {num:7,words:[["Cuanto","as-much-as"],["más","more"],["se","themselves"],["multiplicaban,","increased,"],["más","more"],["pecaban","they-sined"],["contra","against"],["mí;","me;"],["también","also"],["yo","I"],["cambiaré","will-change"],["su","their"],["honra","honor"],["en","in"],["afrenta.","reproach."]]},
  {num:8,words:[["Comen","they-eat"],["del","of-the"],["pecado","sin"],["de","of"],["mi","my"],["pueblo,","people,"],["y","and"],["en","in"],["su","his"],["iniquidad","iniquity"],["ponen","they-put"],["su","his"],["alma.","soul."]]},
  {num:9,words:[["Y","and"],["será","shall-be"],["el","the"],["pueblo","people"],["como","as"],["el","the"],["sacerdote;","priest;"],["y","and"],["los","the"],["castigaré","punish"],["por","for"],["sus","their"],["caminos","ways"],["y","and"],["les","them"],["pagaré","I-will-pay"],["conforme","according-to"],["a","to"],["sus","their"],["obras.","works."]]},
  {num:10,words:[["Y","and"],["comerán,","they-will-eat,"],["mas","but"],["no","not"],["se","themselves"],["saciarán;","they;"],["fornicarán,","will-fornicate,"],["mas","but"],["no","not"],["se","themselves"],["multiplicarán,","increase,"],["porque","because"],["dejaron","they-left"],["de","of"],["hacer","do"],["caso","case"],["a","to"],["Jehová.","jehovah."]]},
  {num:11,words:[["Fornicación,","fornication,"],["y","and"],["vino","wine"],["y","and"],["mosto","corn"],["quitan","they-take"],["el","the"],["juicio.","judgment."]]},
  {num:12,words:[["Mi","my"],["pueblo","people"],["a","to"],["su","his"],["ídolo","idol"],["de","of"],["madera","wood"],["pregunta,","ask,"],["y","and"],["su","his"],["palo","staff"],["le","him"],["responde;","answers;"],["porque","because"],["un","a"],["espíritu","Spirit"],["de","of"],["fornicaciones","whoredoms"],["lo","it/him"],["hizo","made/did"],["errar,","err,"],["y","and"],["dejaron","they-left"],["a","to"],["su","his"],["Dios","God"],["para","for"],["fornicar.","god."]]},
  {num:13,words:[["Sobre","upon"],["las","the"],["cimas","tops"],["de","of"],["los","the"],["montes","mountains"],["sacrifican,","they-sacrifice,"],["y","and"],["queman","they-burn"],["incienso","incense"],["sobre","upon"],["los","the"],["collados,","hills,"],["debajo","beneath"],["de","of"],["las","the"],["encinas,","oaks,"],["y","and"],["de","of"],["los","the"],["álamos","elms,"],["y","and"],["de","of"],["los","the"],["olmos,","thereof,"],["porque","because"],["tenían","they-had"],["buena","good"],["sombra;","shadow;"],["por tanto,","therefore,"],["vuestras","your"],["hijas","daughters"],["fornicarán,","will-fornicate,"],["y","and"],["vuestras","your"],["nueras","daughters"],["cometerán","they-will-commit"],["adulterio.","adultery."]]},
  {num:14,words:[["No","not"],["castigaré","I-will-punish"],["a","to"],["vuestras","your"],["hijas","daughters"],["cuando","when"],["forniquen,","fornicate,"],["ni","nor"],["a","to"],["vuestras","your"],["nueras","daughters"],["cuando","when"],["cometan","they-may-commit"],["adulterio;","adultery;"],["porque","because"],["ellos","they"],["mismos","selves"],["se","themselves"],["van","go"],["con","with"],["rameras","harlots"],["y","and"],["con","with"],["malas","evil"],["mujeres","women"],["ofrecían","they-offered"],["sacrificios;","sacrifices;"],["por tanto,","therefore,"],["el","the"],["pueblo","people"],["sin","without"],["entendimiento","understanding"],["caerá.","will-fall."]]},
  {num:15,words:[["Si","if"],["fornicas","fornicate,"],["tú,","you,"],["oh","oh"],["Israel,","Israel,"],["al","to-the"],["menos","less"],["que","that"],["Judá","Judah"],["no","not"],["se","itself"],["haga","let-do"],["culpable.","guilty."],["¡Y","and"],["no","not"],["entréis","you-enter"],["en","in"],["Gilgal,","Gilgal,"],["ni","nor"],["subáis","up"],["a","to"],["Bet-avén","Beth-aven"],["ni","nor"],["juréis:","you-may-swear:"],["Vive","lives"],["Jehová!","jehovah!"]]},
  {num:16,words:[["Porque","because"],["como","as"],["novilla","bullock"],["terca","stubborn"],["se","himself"],["apartó","nebat"],["Israel.","Israel."],["¿Los","the"],["apacentará","shall-feed"],["ahora","now"],["Jehová","jehovah"],["como","as"],["a","to"],["un","a"],["cordero","lamb"],["en","in"],["lugar","place"],["espacioso?","a?"]]},
  {num:17,words:[["Efraín","Ephraim"],["se","himself"],["ha","has"],["unido","joined"],["a","to"],["ídolos;","idols;"],["déjalo.","leave-it."]]},
  {num:18,words:[["Su","her"],["bebida","drink"],["se","itself"],["corrompió;","corrupted;"],["fornicaron","fornicated"],["pertinazmente;","committed;"],["sus","her"],["príncipes","princes"],["amaron","they-loveed"],["con","with"],["pasión","shame"],["lo","it/him"],["que","that"],["avergüenza.","shames."]]},
  {num:19,words:[["La","the"],["ató","bound"],["el","the"],["viento","wind"],["en","in"],["sus","her"],["alas,","wings,"],["y","and"],["de","of"],["sus","her"],["sacrificios","sacrifices"],["se","themselves"],["avergonzarán.","ashamed."]]},
];
renderVerseSet(v4, 'hos-ch4-verses');

var v5 = [
  {num:1,words:[["Sacerdotes,","priests,"],["oíd","you-hear"],["esto;","this;"],["y","and"],["estad","your"],["atentos,","hear,"],["casa","house"],["de","of"],["Israel;","Israel;"],["y","and"],["casa","house"],["del","of-the"],["rey,","king,"],["escuchad.","you-listen."],["Porque","because"],["contra","against"],["vosotros","you"],["es","is"],["el","the"],["juicio,","judgment,"],["pues","for"],["habéis","you-have"],["sido","been"],["trampa","snare"],["en","in"],["Mizpa","Mizpah"],["y","and"],["red","net"],["tendida","tented"],["sobre","upon"],["Tabor.","Tabor."]]},
  {num:2,words:[["Y","and"],["los","the"],["rebeldes","rebellious"],["se","themselves"],["han","have"],["sumergido","submerged"],["en","in"],["la","the"],["matanza;","slaughter;"],["por tanto,","therefore,"],["yo","I"],["los","the"],["castigaré","punish"],["a","to"],["todos","all"],["ellos.","they."]]},
  {num:3,words:[["Yo","I"],["conozco","know"],["a","to"],["Efraín,","Ephraim,"],["e","and"],["Israel","Israel"],["no","not"],["me","me"],["es","is"],["desconocido;","unknown;"],["porque","because"],["ahora,","now,"],["oh","oh"],["Efraín,","Ephraim,"],["has","you-have"],["fornicado,","fornicated,"],["y","and"],["se","itself"],["ha","has"],["contaminado","defiled"],["Israel.","Israel."]]},
  {num:4,words:[["Su","their"],["conducta","conversation"],["no","not"],["los","the"],["encamina","doings"],["a","to"],["volver","return"],["a","to"],["su","their"],["Dios,","God,"],["porque","because"],["un","a"],["espíritu","Spirit"],["de","of"],["fornicación","fornication"],["hay","there-is"],["en","in"],["medio","midst"],["de","of"],["ellos,","they,"],["y","and"],["no","not"],["conocen","they-know"],["a","to"],["Jehová.","jehovah."]]},
  {num:5,words:[["Y","and"],["la","the"],["soberbia","pride"],["de","of"],["Israel","Israel"],["testificará","shall-testify"],["en","in"],["su","his"],["propia","own"],["cara;","face;"],["e","and"],["Israel","Israel"],["y","and"],["Efraín","Ephraim"],["tropezarán","they-will-stumble"],["en","in"],["su","his"],["iniquidad;","iniquity;"],["tropezará","shall-and"],["también","also"],["Judá","Judah"],["con","with"],["ellos.","they."]]},
  {num:6,words:[["Con","with"],["sus","their"],["ovejas","sheep"],["y","and"],["con","with"],["sus","their"],["vacas","kine"],["andarán","they-will-walk"],["buscando","seeking"],["a","to"],["Jehová,","jehovah,"],["pero","but"],["no","not"],["le","him"],["hallarán;","they-will-find;"],["se","himself"],["ha","has"],["apartado","separated"],["de","of"],["ellos.","they."]]},
  {num:7,words:[["Contra","against"],["Jehová","jehovah"],["actuaron","they-toed"],["pérfidamente,","treacherously,"],["porque","because"],["hijos","children"],["extraños","strangers"],["han","they-have"],["engendrado;","begotten;"],["ahora","now"],["los","the"],["devorará","devour"],["en","in"],["solo","alone"],["un","a"],["mes","month"],["con","with"],["sus","their"],["heredades.","inheritances."]]},
  {num:8,words:[["¡Tocad","you-touch"],["corneta","you"],["en","in"],["Gabaa,","gibeah,"],["trompeta","trump"],["en","in"],["Ramá!","Ramah!"],["¡Gritad","you-trumpet"],["en","in"],["alarma","the"],["en","in"],["Bet-avén:","Beth-aven:"],["Tras","after"],["ti,","you,"],["oh","oh"],["Benjamín!","Benjamin!"]]},
  {num:9,words:[["Efraín","Ephraim"],["será","shall-be"],["asolado","destroyed"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["reprensión;","reproof;"],["entre","among"],["las","the"],["tribus","tribes"],["de","of"],["Israel","Israel"],["hago","make"],["saber","to-know"],["lo","it/him"],["que","that"],["con","with"],["certeza","surety"],["es.","is."]]},
  {num:10,words:[["Los","the"],["príncipes","princes"],["de","of"],["Judá","Judah"],["fueron","they-were"],["como","as"],["los","the"],["que","that"],["mueven","they-move"],["los","the"],["linderos;","i;"],["derramaré","I-pour"],["mi","my"],["ira","wrath"],["sobre","upon"],["ellos","they"],["como","as"],["agua.","water."]]},
  {num:11,words:[["Efraín","Ephraim"],["está","is"],["oprimido,","oppressed,"],["quebrantado","broken"],["en","in"],["juicio,","judgment,"],["porque","because"],["quiso","wanted"],["andar","to-walk"],["en pos de","after"],["vanidades.","vanities."]]},
  {num:12,words:[["Yo,","I,"],["pues,","for,"],["seré","I will be"],["como","as"],["polilla","moth"],["para","for"],["Efraín","Ephraim"],["y","and"],["como","as"],["carcoma","may-eat-away"],["para","for"],["la","the"],["casa","house"],["de","of"],["Judá.","Judah."]]},
  {num:13,words:[["Y","and"],["verá","see"],["Efraín","Ephraim"],["su","his"],["enfermedad,","disease,"],["y","and"],["Judá","Judah"],["su","his"],["llaga;","pronounce;"],["irá","well"],["entonces","then"],["Efraín","Ephraim"],["a","to"],["Asiria","Assyria"],["y","and"],["enviará","will-send"],["al","to-the"],["rey","king"],["Jareb;","Jareb;"],["pero","but"],["él","he"],["no","not"],["os","you"],["podrá","able"],["sanar","to"],["ni","nor"],["os","you"],["curará","will-heal"],["la","the"],["llaga.","pronounce."]]},
  {num:14,words:[["Porque","because"],["yo","I"],["seré","I will be"],["como","as"],["león","lion"],["para","for"],["Efraín","Ephraim"],["y","and"],["como","as"],["cachorro","lion"],["de","of"],["león","lion"],["para","for"],["la","the"],["casa","house"],["de","of"],["Judá;","Judah;"],["yo,","I,"],["yo","I"],["mismo","same"],["despedazaré","will-tear-apart"],["y","and"],["me","me"],["iré;","go;"],["quitaré,","I-take,"],["y","and"],["no","not"],["habrá","there-shall-be"],["quien","who"],["libre.","free."]]},
  {num:15,words:[["Andaré","I-will-walk"],["y","and"],["volveré","I-will-return"],["a","to"],["mi","my"],["lugar,","place,"],["hasta que","until"],["reconozcan","they-may-acknowledge"],["su","his"],["culpa","guilt"],["y","and"],["busquen","they-seek"],["mi","my"],["rostro.","face."],["En","in"],["su","his"],["angustia","anguish"],["me","me"],["buscarán","seek"],["con","with"],["afán.","eagerness."]]},
];
renderVerseSet(v5, 'hos-ch5-verses');

var v6 = [
  {num:1,words:[["Venid","you-come"],["y","and"],["volvamos","we-may-return"],["a","to"],["Jehová;","jehovah;"],["porque","because"],["él","he"],["despedazó,","tore-apart,"],["y","and"],["nos","us"],["curará;","will-heal;"],["hirió,","struck,"],["y","and"],["nos","us"],["vendará.","will-bandage."]]},
  {num:2,words:[["Nos","us"],["dará","shall-give"],["vida","life"],["después","after"],["de","of"],["dos","two"],["días;","days;"],["al","to-the"],["tercer","third"],["día","day"],["nos","us"],["levantará,","raise,"],["y","and"],["viviremos","we-will-live"],["delante","before"],["de","of"],["él.","he."]]},
  {num:3,words:[["Y","and"],["conoceremos","we-will-know"],["y","and"],["proseguiremos","we-will-continue"],["en","in"],["conocer","to-know"],["a","to"],["Jehová;","jehovah;"],["segura","the"],["como","as"],["el","the"],["alba","morning"],["es","is"],["su","his"],["salida;","out;"],["y","and"],["vendrá","shall-come"],["a","to"],["nosotros","we"],["como","as"],["la","the"],["lluvia,","rain,"],["como","as"],["la","the"],["lluvia","rain"],["tardía","latter"],["y","and"],["temprana","the"],["a","to"],["la","the"],["tierra.","earth."]]},
  {num:4,words:[["¿Qué","what"],["te","you"],["haré","I-shall-make"],["a","to"],["ti,","you,"],["oh","oh"],["Efraín?","Ephraim?"],["¿Qué","what"],["te","you"],["haré","I-shall-make"],["a","to"],["ti,","you,"],["oh","oh"],["Judá?","Judah?"],["La","the"],["piedad","godliness"],["vuestra","your"],["es","is"],["como","as"],["nube","cloud"],["de","of"],["la","the"],["mañana","morning"],["y","and"],["como","as"],["el","the"],["rocío","dew"],["de","of"],["la","the"],["madrugada","dew"],["que","that"],["se","itself"],["desvanece.","away."]]},
  {num:5,words:[["Por","by"],["esta","this"],["causa","cause/sake"],["los","the"],["he","I-have"],["despedazado","torn"],["por medio de","by means of"],["los","the"],["profetas;","prophets;"],["con","with"],["las","the"],["palabras","words"],["de","of"],["mi","my"],["boca","mouth"],["los","the"],["he","I-have"],["matado,","killed,"],["y","and"],["tus","your"],["juicios","judgments"],["serán","they-shall-be"],["como","as"],["luz","light"],["que","that"],["sale.","goes."]]},
  {num:6,words:[["Porque","because"],["misericordia","mercy"],["quiero","I-would"],["y","and"],["no","not"],["sacrificio,","sacrifice,"],["y","and"],["conocimiento","knowledge"],["de","of"],["Dios","God"],["más","more"],["que","that"],["holocaustos.","sacrifices."]]},
  {num:7,words:[["Mas","but"],["ellos,","they,"],["cual","which"],["Adán,","Adam,"],["transgredieron","transgressed"],["el","the"],["convenio;","covenant;"],["allí","there"],["actuaron","they-toed"],["pérfidamente","dealt"],["contra","against"],["mí.","me."]]},
  {num:8,words:[["Galaad,","Gilead,"],["ciudad","city"],["de","of"],["obradores","workers"],["de","of"],["iniquidad,","iniquity,"],["manchada","stained"],["de","of"],["sangre.","blood."]]},
  {num:9,words:[["Y","and"],["como","as"],["ladrones","thieves"],["al","to-the"],["acecho","robbers"],["de","of"],["algún","some"],["hombre,","man,"],["así","thus"],["una","a"],["compañía","company"],["de","of"],["sacerdotes","priests"],["mata","man"],["en","in"],["el","the"],["camino","way"],["hacia","toward"],["Siquem;","shechem;"],["así","thus"],["cometen","they-commit"],["perversidad.","lewdness."]]},
  {num:10,words:[["En","in"],["la","the"],["casa","house"],["de","of"],["Israel","Israel"],["he","I-have"],["visto","seen"],["algo","something"],["horrible;","horrible;"],["allí","there"],["fornicó","fornicated"],["Efraín;","Ephraim;"],["se","itself"],["contaminó","israel"],["Israel.","Israel."]]},
  {num:11,words:[["Para","for"],["ti","you"],["también,","also,"],["oh","oh"],["Judá,","Judah,"],["está","is"],["preparada","prepared"],["una","a"],["siega,","harvest,"],["cuando","when"],["yo","I"],["haga","let-do"],["volver","to-return"],["de","of"],["la","the"],["cautividad","captivity"],["a","to"],["mi","my"],["pueblo.","people."]]},
];
renderVerseSet(v6, 'hos-ch6-verses');

var v7 = [
  {num:1,words:[["Mientras","while"],["yo","I"],["quería","wanted"],["curar","to-heal"],["a","to"],["Israel,","Israel,"],["se","itself"],["descubrió","discovered"],["la","the"],["iniquidad","iniquity"],["de","of"],["Efraín","Ephraim"],["y","and"],["las","the"],["maldades","wickedness"],["de","of"],["Samaria,","Samaria,"],["porque","because"],["hacen","they-do"],["engaño;","guile;"],["y","and"],["entra","enter"],["el","the"],["ladrón,","thief,"],["y","and"],["la","the"],["banda","band"],["de","of"],["salteadores","of"],["despoja","spoil"],["por","for"],["fuera.","were."]]},
  {num:2,words:[["Y","and"],["no","not"],["consideran","they-consider"],["en","in"],["su","his"],["corazón","heart"],["que","that"],["tengo","I-have"],["memoria","remembrance"],["de","of"],["toda","all"],["su","his"],["maldad;","wickedness;"],["ahora","now"],["los","the"],["rodean","about"],["sus","his"],["propias","own"],["obras;","works;"],["delante","before"],["de","of"],["mí","me"],["están.","they-are."]]},
  {num:3,words:[["Con","with"],["su","their"],["maldad","wickedness"],["alegran","they-rejoice"],["al","to-the"],["rey,","king,"],["y","and"],["a","to"],["los","the"],["príncipes","princes"],["con","with"],["sus","their"],["mentiras.","lyings."]]},
  {num:4,words:[["Todos","all"],["ellos","they"],["son","are"],["adúlteros;","adulterers;"],["son","they-are"],["como","as"],["horno","furnace"],["encendido","kindled"],["por","by"],["el","the"],["hornero,","the,"],["que","that"],["cesa","ceases"],["de","of"],["avivar","to-revive"],["el","the"],["fuego","fire"],["después que","after"],["está","is"],["hecha","done"],["la","the"],["masa,","mass,"],["hasta que","until"],["se","itself"],["haya","let-there-be"],["leudado.","leavened."]]},
  {num:5,words:[["En","in"],["el","the"],["día","day"],["de","of"],["nuestro","our"],["rey,","king,"],["los","the"],["príncipes","princes"],["lo","him"],["hicieron","they-made"],["enfermar","sick"],["con","with"],["copas","bowls"],["de","of"],["vino;","wine;"],["extendió","stretched"],["su","his"],["mano","hand"],["con","with"],["los","the"],["escarnecedores.","scorners."]]},
  {num:6,words:[["Porque","because"],["disponen","they-prepare"],["su","their"],["corazón","heart"],["para","for"],["la","the"],["intriga,","like,"],["como","as"],["se","itself"],["prepara","prepares"],["un","a"],["horno;","furnace;"],["toda","all"],["la","the"],["noche","night"],["duerme","sleeps"],["su","their"],["hornero;","the;"],["a","to"],["la","the"],["mañana","morning"],["está","is"],["encendido","kindled"],["como","as"],["llama","flame"],["de","of"],["fuego.","fire."]]},
  {num:7,words:[["Todos","all"],["ellos","they"],["arden","may-savour"],["como","as"],["un","a"],["horno","furnace"],["y","and"],["devoran","they-devour"],["a","to"],["sus","their"],["jueces;","judges;"],["han","they-have"],["caído","fallen"],["todos","all"],["sus","their"],["reyes;","kings;"],["no","not"],["hay","there-is"],["entre","among"],["ellos","they"],["quien","who"],["a","to"],["mí","me"],["clame.","cried."]]},
  {num:8,words:[["Efraín","Ephraim"],["se","himself"],["mezcla","of"],["con","with"],["los","the"],["demás","rest"],["pueblos;","peoples;"],["Efraín","Ephraim"],["es","is"],["como","as"],["torta","a"],["no","not"],["volteada.","turned."]]},
  {num:9,words:[["Extraños","strangers"],["han","they-have"],["devorado","devoured"],["sus","his"],["fuerzas,","forces,"],["y","and"],["él","he"],["no","not"],["lo","it/him"],["sabe;","knows;"],["y","and"],["aun","even"],["las","the"],["canas","gray hairs"],["se","themselves"],["han","have"],["esparcido","scattered"],["sobre","upon"],["él,","he,"],["y","and"],["él","he"],["no","not"],["lo","it/him"],["sabe.","knows."]]},
  {num:10,words:[["Y","and"],["la","the"],["soberbia","pride"],["de","of"],["Israel","Israel"],["testificará","shall-testify"],["contra","against"],["él","he"],["en","in"],["su","his"],["propia","own"],["cara;","face;"],["y","and"],["ellos","they"],["no","not"],["se","themselves"],["vuelven","return"],["a","to"],["Jehová","jehovah"],["su","his"],["Dios","God"],["ni","nor"],["le","him"],["buscan","they-seek"],["a pesar de","despite"],["todo","all"],["eso.","that."]]},
  {num:11,words:[["Y","and"],["Efraín","Ephraim"],["es","is"],["como","as"],["una","a"],["paloma","dove"],["incauta,","seizes,"],["sin","without"],["entendimiento;","understanding;"],["llaman","they-call"],["a","to"],["Egipto,","Egypt,"],["acuden","they-may-come"],["a","to"],["Asiria.","Assyria."]]},
  {num:12,words:[["Cuando","when"],["vayan,","they-servants,"],["tenderé","I-will-tent"],["sobre","upon"],["ellos","they"],["mi","my"],["red;","net;"],["los","the"],["haré","I will make"],["caer","to-fall"],["como","as"],["aves","fowls"],["del","of-the"],["cielo;","heaven;"],["los","the"],["castigaré","punish"],["conforme","according-to"],["a","to"],["lo","it/him"],["que","that"],["se","itself"],["ha","has"],["oído","heard"],["en","in"],["su","his"],["congregación.","congregation."]]},
  {num:13,words:[["¡Ay","wo"],["de","of"],["ellos,","they,"],["porque","because"],["se","themselves"],["apartaron","departed"],["de","of"],["mí!","me!"],["¡Destrucción","destruction"],["sobre","upon"],["ellos,","they,"],["porque","because"],["contra","against"],["mí","me"],["transgredieron!","though!"],["Yo","I"],["los","the"],["redimiría,","would-redeem,"],["pero","but"],["ellos","they"],["hablaron","spoke"],["mentiras","lyings"],["contra","against"],["mí.","me."]]},
  {num:14,words:[["Y","and"],["no","not"],["clamaron","they-cried"],["a","to"],["mí","me"],["con","with"],["su","their"],["corazón","heart"],["cuando","when"],["gemían","they-moaned"],["sobre","upon"],["sus","their"],["camas;","beds;"],["por","for"],["el","the"],["trigo","wheat"],["y","and"],["el","the"],["mosto","corn"],["se","themselves"],["congregaron;","wine;"],["se","themselves"],["rebelaron","rebelled"],["contra","against"],["mí.","me."]]},
  {num:15,words:[["Aunque","although"],["yo","I"],["adiestré","bound"],["y","and"],["fortalecí","I-strengthened"],["sus","their"],["brazos,","arms,"],["contra","against"],["mí","me"],["traman","they-plot"],["el","the"],["mal.","evil."]]},
  {num:16,words:[["Se","themselves"],["volvieron,","returned,"],["pero","but"],["no","not"],["al","to-the"],["Altísimo;","most;"],["fueron","they-were"],["como","as"],["arco","bow"],["engañoso;","a;"],["caerán","they-will-fall"],["sus","their"],["príncipes","princes"],["a","to"],["espada","sword"],["por","for"],["la","the"],["insolencia","for"],["de","of"],["su","their"],["lengua;","tongue;"],["esto","this"],["será","shall-be"],["su","their"],["escarnio","derision"],["en","in"],["la","the"],["tierra","land"],["de","of"],["Egipto.","Egypt."]]},
];
renderVerseSet(v7, 'hos-ch7-verses');

var v8 = [
  {num:1,words:[["Pon","you-prophesy"],["a","to"],["tu","your"],["boca","mouth"],["la","the"],["trompeta.","trump."],["Vendrá","shall-come"],["como","as"],["águila","eagle"],["contra","against"],["la","the"],["casa","house"],["de","of"],["Jehová,","jehovah,"],["porque","because"],["traspasaron","because"],["mi","my"],["convenio","covenant"],["y","and"],["se","themselves"],["rebelaron","rebelled"],["contra","against"],["mi","my"],["ley.","law."]]},
  {num:2,words:[["A", "to"], ["mí", "me"], ["clamará", "cry"], ["Israel:", "Israel:"], ["¡Dios", "God"], ["mío,", "mine,"], ["te","you"], ["conocemos!", "know!"]]},
  {num:3,words:[["Israel","Israel"],["desechó","toed"],["el","the"],["bien;","well;"],["el","the"],["enemigo","enemy"],["lo","him"],["perseguirá.","will-pursue."]]},
  {num:4,words:[["Ellos","they"],["establecieron","established"],["reyes,","kings,"],["pero","but"],["no","not"],["de","of"],["parte","part"],["mía;","mother;"],["constituyeron","constituted"],["príncipes,","princes,"],["pero","but"],["yo","I"],["no","not"],["los","the"],["reconocí;","I-acknowledged;"],["de","of"],["su","their"],["plata","silver"],["y","and"],["de","of"],["su","their"],["oro","gold"],["hicieron","they-made"],["ídolos","idols"],["para","for"],["sí,","yes,"],["para","for"],["ser","be"],["ellos","they"],["mismos","selves"],["destruidos.","destroyed."]]},
  {num:5,words:[["Tu","your"],["becerro,","calf,"],["oh","oh"],["Samaria,","Samaria,"],["te","you"],["hizo","made/did"],["alejarte;","off;"],["se","itself"],["encendió","kindled"],["mi","my"],["enojo","fury"],["contra","against"],["ellos.","they."],["¿Hasta","until"],["cuándo","when"],["serán","they-shall-be"],["incapaces","incapable"],["de","of"],["lograr","obtain"],["la","the"],["purificación?","purifying?"]]},
  {num:6,words:[["Porque","because"],["de","of"],["Israel","Israel"],["es","is"],["este","this"],["becerro;","calf;"],["y","and"],["un","a"],["artífice","craftsman"],["lo","it"],["hizo,","made,"],["y","and"],["no","not"],["es","is"],["Dios,","God,"],["por","for"],["lo","it"],["que","that"],["será","shall-be"],["deshecho","undone"],["en","in"],["pedazos","pieces"],["el","the"],["becerro","calf"],["de","of"],["Samaria.","Samaria."]]},
  {num:7,words:[["Porque","because"],["sembraron","they-sowed"],["viento,","wind,"],["torbellino","whirlwind"],["segarán;","they-will-reap;"],["no","not"],["tendrán","they-will have"],["mies,","harvest,"],["ni","nor"],["la","the"],["espiga","bud"],["dará","shall-give"],["harina;","meal;"],["y","and"],["si","if"],["la","the"],["diere,","yield,"],["extraños","strangers"],["la","the"],["comerán.","eat."]]},
  {num:8,words:[["Será","shall-be"],["devorado","devoured"],["Israel;","Israel;"],["pronto","soon"],["será","shall-be"],["entre","among"],["las","the"],["naciones","nations"],["como","as"],["vasija","vessel"],["que","that"],["no","not"],["contiene","contains"],["nada","nothing"],["que","that"],["deleite.","may-delight."]]},
  {num:9,words:[["Porque","because"],["ellos","they"],["subieron","went"],["a","to"],["Asiria","Assyria"],["como","as"],["asno","ass"],["montés","mountain"],["solitario;","solitary;"],["Efraín","Ephraim"],["alquiló","hired"],["amantes.","lovers."]]},
  {num:10,words:[["Aunque","although"],["se","themselves"],["alquilen","they-may-hire"],["entre","among"],["las","the"],["naciones,","nations,"],["ahora","now"],["los","the"],["juntaré;","gather;"],["y","and"],["comenzarán","they-will-begin"],["a","to"],["disminuir","diminish"],["por","for"],["la","the"],["carga","burden"],["del","of-the"],["rey","king"],["y","and"],["de","of"],["los","the"],["príncipes.","princes."]]},
  {num:11,words:[["Porque","because"],["multiplicó","multiplied"],["Efraín","Ephraim"],["altares","altars"],["para","for"],["pecar,","to-sin,"],["ahora","now"],["le","him"],["son","they-are"],["altares","altars"],["para","for"],["pecar.","to-sin."]]},
  {num:12,words:[["Le","him"],["escribí","I-wrote"],["las","the"],["grandezas","greatness"],["de","of"],["mi","my"],["ley,","law,"],["pero","but"],["fueron","they-were"],["tenidas","had"],["como","as"],["cosa","thing"],["extraña.","strange."]]},
  {num:13,words:[["En","in"],["los","the"],["sacrificios","sacrifices"],["de","of"],["mis","my"],["ofrendas","offerings"],["sacrificaron","they-sacrificed"],["carne","flesh"],["y","and"],["comieron;","they-ate;"],["no","not"],["los","the"],["aceptó","accepted"],["Jehová.","jehovah."],["Ahora","now"],["se","itself"],["acordará","remember"],["de","of"],["su","their"],["iniquidad","iniquity"],["y","and"],["castigará","will-punish"],["sus","their"],["pecados;","sins;"],["ellos","they"],["volverán","will-return"],["a","to"],["Egipto.","Egypt."]]},
  {num:14,words:[["Olvidó,","for,"],["pues,","for,"],["Israel","Israel"],["a","to"],["su","his"],["Hacedor","maker"],["y","and"],["edificó","built"],["templos,","temples,"],["y","and"],["Judá","Judah"],["multiplicó","multiplied"],["ciudades","cities"],["fortificadas;","fenced;"],["mas","but"],["yo","I"],["mandaré","command"],["fuego","fire"],["a","to"],["sus","his"],["ciudades,","cities,"],["el","the"],["cual","which"],["devorará","devour"],["sus","his"],["palacios.","palaces."]]},
];
renderVerseSet(v8, 'hos-ch8-verses');

var v9 = [
  {num:1,words:[["No","not"],["te","you"],["alegres,","tidings,"],["oh","oh"],["Israel,","Israel,"],["hasta","until"],["saltar","joy,"],["de","of"],["gozo","joy"],["como","as"],["los","the"],["pueblos,","peoples,"],["pues","for"],["te","you"],["has","you-have"],["prostituido,","prostituted,"],["apartándote","whoring"],["de","of"],["tu","your"],["Dios;","God;"],["amaste","you-love-you"],["salario","wages"],["de","of"],["ramera","whore"],["en","in"],["todas","all"],["las","the"],["eras","were"],["de","of"],["trigo.","wheat."]]},
  {num:2,words:[["La","the"],["era","was"],["y","and"],["el","the"],["lagar","winepress"],["no","not"],["los","the"],["mantendrán,","they-will-maintain,"],["y","and"],["les","them"],["fallará","will-fail"],["el","the"],["mosto.","corn."]]},
  {num:3,words:[["No","not"],["se","themselves"],["quedarán","they-will-remain"],["en","in"],["la","the"],["tierra","land"],["de","of"],["Jehová,","jehovah,"],["sino que","but"],["volverá","will-return"],["Efraín","Ephraim"],["a","to"],["Egipto,","Egypt,"],["y","and"],["en","in"],["Asiria","Assyria"],["comerán","they-will-eat"],["vianda","in"],["inmunda.","unclean."]]},
  {num:4,words:[["No","not"],["derramarán","they-shall-shedding"],["libación","continual"],["de","of"],["vino","wine"],["a","to"],["Jehová,","jehovah,"],["ni","nor"],["sus","their"],["sacrificios","sacrifices"],["le","him"],["serán","they-shall-be"],["gratos;","savours;"],["será","shall-be"],["para","for"],["ellos","they"],["como","as"],["pan","bread"],["de","of"],["duelo;","mourned;"],["todos","all"],["los","the"],["que","that"],["coman","they-may-eat"],["de","of"],["él","he"],["serán","they-shall-be"],["impuros.","unclean."],["Será,","shall-be,"],["pues,","for,"],["el","the"],["pan","bread"],["de","of"],["ellos","they"],["para","for"],["sí","yes"],["mismos;","selves;"],["ese","that"],["pan","bread"],["no","not"],["entrará","enter"],["en","in"],["la","the"],["casa","house"],["de","of"],["Jehová.","jehovah."]]},
  {num:5,words:[["¿Qué","what"],["haréis","servile"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["solemnidad","day,"],["y","and"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["fiesta","feast"],["de","of"],["Jehová?","jehovah?"]]},
  {num:6,words:[["Porque,","because,"],["he aquí,","behold,"],["se","themselves"],["fueron","were"],["ellos","they"],["a causa de","because of"],["la","the"],["destrucción;","destruction;"],["Egipto","Egypt"],["los","the"],["recogerá;","gather;"],["Menfis","shall"],["los","the"],["enterrará;","will-bury;"],["la","the"],["ortiga","places"],["poseerá","will-possess"],["lo","it/him"],["deseable","desirable"],["de","of"],["su","their"],["plata,","silver,"],["y","and"],["el","the"],["espino","shall"],["crecerá","will-grow"],["en","in"],["sus","their"],["tiendas.","tents."]]},
  {num:7,words:[["Vinieron","they-came"],["los","the"],["días","days"],["del","of-the"],["castigo;","punishment;"],["vinieron","they-came"],["los","the"],["días","days"],["de","of"],["la","the"],["retribución.","are."],["¡Lo","it"],["sabrá","will-know"],["Israel!","Israel!"],["Necio","fool"],["es","is"],["el","the"],["profeta,","prophet,"],["insensato","fool"],["el","the"],["hombre","man"],["de","of"],["espíritu,","Spirit,"],["a causa de","because of"],["la","the"],["multitud","multitude"],["de","of"],["tu","your"],["maldad","wickedness"],["y","and"],["de","of"],["tu","your"],["gran","great"],["odio.","hatred."]]},
  {num:8,words:[["El","the"],["atalaya","watchman"],["de","of"],["Efraín","Ephraim"],["estuvo","stood"],["con","with"],["mi","my"],["Dios,","God,"],["pero","but"],["el","the"],["profeta","prophet"],["es","is"],["trampa","snare"],["de","of"],["cazador","a"],["en","in"],["todos","all"],["sus","his"],["caminos;","ways;"],["hay","there-is"],["odio","hatred"],["en","in"],["la","the"],["casa","house"],["de","of"],["su","his"],["Dios.","God."]]},
  {num:9,words:[["Se","themselves"],["han","have"],["corrompido","corrupted"],["profundamente","in"],["como","as"],["en","in"],["los","the"],["días","days"],["de","of"],["Gabaa;","gibeah;"],["ahora","now"],["se","themselves"],["acordará","remember"],["de","of"],["su","their"],["iniquidad;","iniquity;"],["castigará","will-punish"],["sus","their"],["pecados.","sins."]]},
  {num:10,words:[["Como","as"],["uvas","grapes"],["en","in"],["el","the"],["desierto","wilderness"],["hallé","I-found"],["a","to"],["Israel;","Israel;"],["como","as"],["la","the"],["fruta","fruit"],["temprana","the"],["de","of"],["la","the"],["higuera","fig"],["en","in"],["sus","her"],["principios","principles"],["vi","I-saw"],["a","to"],["vuestros","your"],["padres.","parents."],["Ellos","they"],["acudieron","attended"],["a","to"],["Baal-peor,","Baal-peor,"],["y","and"],["se","themselves"],["apartaron","departed"],["para","for"],["vergüenza","shame"],["y","and"],["se","themselves"],["hicieron","did/made"],["abominables","abominable"],["como","as"],["aquello","thing"],["que","that"],["amaron.","they-loveed."]]},
  {num:11,words:[["La","the"],["gloria","glory"],["de","of"],["Efraín","Ephraim"],["volará","will-fly"],["cual","which"],["ave","fowl"],["desde","from"],["el","the"],["nacimiento,","birth,"],["aun","even"],["desde","from"],["el","the"],["vientre","belly"],["y","and"],["desde","from"],["la","the"],["concepción.","conception."]]},
  {num:12,words:[["Y","and"],["si","if"],["llegan","they-come"],["a","to"],["grandes","great"],["sus","their"],["hijos,","children,"],["se","myself"],["los","the"],["quitaré","take"],["de","of"],["entre","among"],["los","the"],["hombres,","men,"],["porque,","because,"],["¡ay","wo"],["de","of"],["ellos","they"],["también,","also,"],["cuando","when"],["de","of"],["ellos","they"],["me","me"],["aparte!","turn!"]]},
  {num:13,words:[["Efraín,","Ephraim,"],["según","according-to"],["veo,","perceive,"],["es","is"],["semejante","like"],["a","to"],["Tiro,","tyrus,"],["asentado","settled"],["en","in"],["un","a"],["lugar","place"],["delicioso;","delicious;"],["pero","but"],["Efraín","Ephraim"],["sacará","bring"],["a","to"],["sus","his"],["hijos","children"],["a","to"],["la","the"],["matanza.","slaughter."]]},
  {num:14,words:[["Dales,","gives-them,"],["oh","oh"],["Jehová,","jehovah,"],["lo","it/him"],["que","that"],["les","them"],["has","you-have"],["de","of"],["dar;","to-give;"],["dales","gives-them"],["matriz","womb"],["que","that"],["aborte","womb"],["y","and"],["pechos","breasts"],["enjutos.","breasts."]]},
  {num:15,words:[["Toda","all"],["la","the"],["maldad","wickedness"],["de","of"],["ellos","they"],["fue","was"],["en","in"],["Gilgal;","Gilgal;"],["allí,","there,"],["pues,","for,"],["les","them"],["tomé","took"],["aversión;","wickedness;"],["por","for"],["la","the"],["maldad","wickedness"],["de","of"],["sus","their"],["obras","works"],["los","the"],["echaré","cast"],["de","of"],["mi","my"],["casa;","house;"],["no","not"],["los","the"],["amaré","shall-love"],["más;","more;"],["todos","all"],["sus","their"],["príncipes","princes"],["son","they-are"],["rebeldes.","rebellious."]]},
  {num:16,words:[["Efraín","Ephraim"],["fue","was"],["herido;","wounded;"],["se","itself"],["secó","withered"],["su","their"],["raíz","root"],["y","and"],["no","not"],["dará","shall-give"],["más","more"],["fruto;","fruit;"],["aunque","although"],["engendren,","forth,"],["yo","I"],["mataré","will-slay"],["el","the"],["preciado","precious"],["fruto","fruit"],["de","of"],["su","their"],["vientre.","belly."]]},
  {num:17,words:[["Mi","my"],["Dios","God"],["los","the"],["desechará,","shall-to,"],["porque","because"],["ellos","they"],["no","not"],["le","him"],["escucharon;","they-hearkened;"],["y","and"],["andarán","they-will-walk"],["errantes","wilderness"],["entre","among"],["las","the"],["naciones.","nations."]]},
];
renderVerseSet(v9, 'hos-ch9-verses');

var v10 = [
  {num:1,words:[["Israel","Israel"],["es","is"],["una","a"],["frondosa","green"],["viña","vineyard"],["que","that"],["da","gives"],["fruto","fruit"],["para","for"],["sí;","yes;"],["conforme","according-to"],["a","to"],["la","the"],["abundancia","abundance"],["de","of"],["su","his"],["fruto,","fruit,"],["multiplicaba","multiplied"],["los","the"],["altares;","altars;"],["conforme","according-to"],["a","to"],["la","the"],["bondad","goodness"],["de","of"],["su","his"],["tierra,","land,"],["mejor","better"],["adorna","made"],["sus","his"],["ídolos.","idols."]]},
  {num:2,words:[["Está","is"],["dividido","divided"],["su","their"],["corazón.","heart."],["Ahora","now"],["serán","they-shall-be"],["hallados","found"],["culpables;","guilty;"],["él","he"],["quebrantará","shall-the"],["sus","their"],["altares","altars"],["y","and"],["destruirá","destroy"],["sus","their"],["ídolos.","idols."]]},
  {num:3,words:[["Porque","because"],["dirán","they-will-say"],["ahora:","now:"],["No","not"],["tenemos","we-have"],["rey","king"],["porque","because"],["no","not"],["temimos","we-feared"],["a","to"],["Jehová;","jehovah;"],["¿y","and"],["qué","what"],["haría","would"],["el","the"],["rey","king"],["por","for"],["nosotros?","we?"]]},
  {num:4,words:[["Han","they-have"],["hablado","spoken"],["palabras,","words,"],["jurando","hand"],["en","in"],["vano","vain"],["al","to-the"],["hacer","make"],["convenio;","covenant;"],["por tanto,","therefore,"],["el","the"],["juicio","judgment"],["florecerá","shall"],["como","as"],["hierba","herb"],["venenosa","poisonous"],["en","in"],["los","the"],["surcos","of"],["del","of-the"],["campo.","field."]]},
  {num:5,words:[["Por","for"],["las","the"],["becerras","heifers"],["de","of"],["Bet-avén","Beth-aven"],["serán","they-shall-be"],["atemorizados","because"],["los","the"],["moradores","inhabitants"],["de","of"],["Samaria;","Samaria;"],["porque","because"],["su","his"],["pueblo","people"],["se","itself"],["lamentará","will-regret"],["a","to"],["causa","cause/sake"],["del","of-the"],["becerro,","calf,"],["y","and"],["también","also"],["sus","his"],["sacerdotes","priests"],["que","that"],["en","in"],["ello","it"],["se","themselves"],["regocijaban,","they-rejoiced,"],["por","for"],["su","his"],["gloria,","glory,"],["la","the"],["cual","which"],["será","shall-be"],["disipada","departed"],["de","of"],["él.","he."]]},
  {num:6,words:[["Y","and"],["aun","even"],["será","shall-be"],["llevado","carried"],["a","to"],["Asiria","Assyria"],["como","as"],["presente","present"],["al","to-the"],["rey","king"],["Jareb;","Jareb;"],["Efraín","Ephraim"],["será","shall-be"],["avergonzado,","ashamed,"],["e","and"],["Israel","Israel"],["se","itself"],["avergonzará","will-shame"],["de","of"],["su","his"],["propio","own"],["consejo.","counsel."]]},
  {num:7,words:[["De","of"],["Samaria","Samaria"],["fue","was"],["cortado","cut"],["su","her"],["rey","king"],["como","as"],["espuma","off"],["sobre","upon"],["la","the"],["superficie","face"],["de","of"],["las","the"],["aguas.","waters."]]},
  {num:8,words:[["Y","and"],["los","the"],["lugares","places"],["altos","high"],["de","of"],["Avén,","Aven,"],["el","the"],["pecado","sin"],["de","of"],["Israel,","Israel,"],["serán","they-shall-be"],["destruidos;","destroyed;"],["crecerán","they-will-grow"],["sobre","upon"],["sus","their"],["altares","altars"],["espino","up"],["y","and"],["cardo.","altars."],["Y","and"],["dirán","they-will-say"],["a","to"],["los","the"],["montes:","mountains:"],["¡Cubridnos!,","mountains!,"],["y","and"],["a","to"],["los","the"],["collados:","hills:"],["¡Caed","you-hills,"],["sobre","upon"],["nosotros!","we!"]]},
  {num:9,words:[["Desde","from"],["los","the"],["días","days"],["de","of"],["Gabaa","gibeah"],["has","you-have"],["pecado,","sin,"],["oh","oh"],["Israel;","Israel;"],["allí","there"],["se","themselves"],["han","have"],["quedado.","remained."],["¿No","not"],["los","the"],["alcanzó","toed"],["la","the"],["batalla","battle"],["en","in"],["Gabaa","gibeah"],["contra","against"],["los","the"],["hijos","children"],["de","of"],["los","the"],["inicuos?","wicked?"]]},
  {num:10,words:[["Y","and"],["los","the"],["castigaré","punish"],["cuando","when"],["lo","it"],["desee;","may-desire;"],["y","and"],["pueblos","peoples"],["se","themselves"],["juntarán","gathered"],["contra","against"],["ellos","they"],["cuando","when"],["sean","they-let-be"],["atados","bound"],["por","for"],["su","his"],["doble","double"],["iniquidad.","iniquity."]]},
  {num:11,words:[["Y","and"],["Efraín","Ephraim"],["era","was"],["novilla","bullock"],["domada,","heifer,"],["amadora","is"],["del","of-the"],["trillar;","and;"],["mas","but"],["yo","I"],["pasaré","pass"],["sobre","upon"],["su","his"],["lozana","i"],["cerviz.","stiffnecked."],["Pero","but"],["yo","I"],["haré","I will make"],["llevar","to-carry"],["yugo","yoke"],["a","to"],["Efraín;","Ephraim;"],["arará","judah"],["Judá;","Judah;"],["quebrará","plow,"],["sus","his"],["propios","own"],["terrones","break"],["Jacob.","Jacob."]]},
  {num:12,words:[["Sembrad","you-sow"],["para","for"],["vosotros","you"],["en","in"],["justicia;","righteousness;"],["segad","you-reap"],["para","for"],["vosotros","you"],["en","in"],["misericordia;","mercy;"],["haced","you-do"],["para","for"],["vosotros","you"],["barbecho,","ground,"],["porque","because"],["es","is"],["el","the"],["tiempo","time"],["de","of"],["buscar","seek"],["a","to"],["Jehová,","jehovah,"],["hasta que","until"],["venga","let-come"],["y","and"],["haga","let-do"],["llover","to-rain"],["justicia","righteousness"],["sobre","upon"],["vosotros.","you."]]},
  {num:13,words:[["Habéis","you-have"],["arado","plowed"],["maldad;","wickedness;"],["segasteis","you-reaped"],["iniquidad.","iniquity."],["Habéis","you-have"],["comido","eaten"],["fruto","fruit"],["de","of"],["mentira,","lies,"],["porque","because"],["confiaste","you-trusted"],["en","in"],["tu","your"],["camino,","way,"],["en","in"],["la","the"],["multitud","multitude"],["de","of"],["tus","your"],["valientes.","valour."]]},
  {num:14,words:[["Por tanto,","therefore,"],["en","in"],["tus","your"],["pueblos","peoples"],["se","himself"],["levantará","raise"],["un","a"],["alboroto,","tumult,"],["y","and"],["todas","all"],["tus","your"],["fortalezas","holds"],["serán","they-shall-be"],["destruidas,","destroyed,"],["como","as"],["destruyó","destroyed"],["Salmán","spoiled"],["a","to"],["Bet-arbel","betharbel"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["batalla;","battle;"],["la","the"],["madre","mother"],["fue","was"],["estrellada","crashed"],["junto","together"],["con","with"],["sus","her"],["hijos.","children."]]},
  {num:15,words:[["Así", "thus"], ["hará", "shall-make"], ["a", "to"], ["vosotros", "you"], ["Bet-el", "bethel"], ["a causa de","because of"], ["vuestra", "your"], ["gran", "great"], ["maldad;", "wickedness;"], ["al", "to-the"], ["amanecer", "morning"], ["será", "shall-be"], ["del", "of-the"], ["todo", "all"], ["destruido", "destroyed"], ["el", "the"], ["rey", "king"], ["de", "of"], ["Israel.", "Israel."]]},
];
renderVerseSet(v10, 'hos-ch10-verses');

var v11 = [
  {num:1,words:[["Cuando","when"],["Israel","Israel"],["era","was"],["niño,","child,"],["yo","I"],["lo","him"],["amé,","I-loved,"],["y","and"],["de","of"],["Egipto","Egypt"],["llamé","I-called"],["a","to"],["mi","my"],["hijo.","son."]]},
  {num:2,words:[["Cuanto","as-much-as"],["más","more"],["los","the"],["llamaban","called"],["los","the"],["profetas,","prophets,"],["más","more"],["se","themselves"],["alejaban","they-moved-away"],["de","of"],["ellos;","they;"],["a","to"],["los","the"],["baales","baalim"],["ofrecían","they-offered"],["sacrificios","sacrifices"],["y","and"],["a","to"],["las","the"],["imágenes","groves"],["talladas","graven"],["quemaban","they-burnt"],["incienso.","incense."]]},
  {num:3,words:[["Yo","I"],["con","with"],["todo","all"],["eso","that"],["enseñaba","taught"],["a","to"],["andar","walk"],["al","to-the"],["mismo","same"],["Efraín,","Ephraim,"],["tomándolo","taking-it"],["por","by"],["los","the"],["brazos;","arms;"],["pero","but"],["ellos","they"],["no","not"],["comprendieron","they-understood"],["que","that"],["yo","I"],["los","the"],["sanaba.","healed."]]},
  {num:4,words:[["Con","with"],["cuerdas","cords"],["humanas","human"],["los","the"],["atraje,","cords,"],["con","with"],["cuerdas","cords"],["de","of"],["amor;","love;"],["y","and"],["fui","I-am"],["para","for"],["ellos","they"],["como","as"],["los","the"],["que","that"],["alzan","up"],["el","the"],["yugo","yoke"],["de","of"],["sobre","upon"],["su","their"],["cerviz,","stiffnecked,"],["y","and"],["puse","I-set"],["delante","before"],["de","of"],["ellos","they"],["la","the"],["comida.","meat."]]},
  {num:5,words:[["No","not"],["volverá","will-return"],["a","to"],["tierra","land"],["de","of"],["Egipto,","Egypt,"],["sino que","but"],["el","the"],["mismo","same"],["asirio","assyrian"],["será","shall-be"],["su","his"],["rey,","king,"],["porque","because"],["no","not"],["quisieron","they-loved"],["volverse","return-oneself"],["a","to"],["mí.","me."]]},
  {num:6,words:[["Y","and"],["caerá","will-fall"],["la","the"],["espada","sword"],["sobre","upon"],["sus","his"],["ciudades","cities"],["y","and"],["consumirá","palaces"],["sus","his"],["aldeas,","villages,"],["y","and"],["las","the"],["consumirá","palaces"],["a causa de","because of"],["sus","his"],["propios","own"],["consejos.","counsels."]]},
  {num:7,words:[["Y","and"],["mi","my"],["pueblo","people"],["está","is"],["aferrado","gript"],["a","to"],["la","the"],["rebelión","rebellion"],["contra","against"],["mí;","me;"],["aunque","although"],["llaman","they-call"],["al","to-the"],["Altísimo,","most,"],["ninguno","none"],["absolutamente","absolutely"],["quiere","wants"],["enaltecerle.","exalts."]]},
  {num:8,words:[["¿Cómo","how"],["podré","I-will-power"],["abandonarte,","forsakes,"],["oh","oh"],["Efraín?","Ephraim?"],["¿Te","you"],["entregaré","deliver"],["yo,","I,"],["Israel?","Israel?"],["¿Cómo","how"],["podré","I-will-power"],["yo","I"],["hacerte","make"],["como","as"],["Adma","Admah"],["o","or"],["ponerte","put/place-you"],["como","as"],["a","to"],["Zeboim?","Zeboim?"],["Mi","my"],["corazón","heart"],["se","itself"],["conmueve","mine"],["dentro","within"],["de","of"],["mí,","me,"],["se","itself"],["inflama","inflames"],["toda","all"],["mi","my"],["compasión.","compassion."]]},
  {num:9,words:[["No","not"],["ejecutaré","I-shall-for"],["el","the"],["furor","fury"],["de","of"],["mi","my"],["ira","anger"],["ni","nor"],["volveré","I-will-return"],["para","for"],["destruir","to-destroy"],["a","to"],["Efraín,","Ephraim,"],["porque","because"],["Dios","God"],["soy,","I-am,"],["y","and"],["no","not"],["hombre;","man;"],["soy","I-am"],["el","the"],["Santo","holy"],["en","in"],["medio","midst"],["de","of"],["ti,","you,"],["y","and"],["no","not"],["entraré","I-will-enter"],["en","in"],["la","the"],["ciudad.","city."]]},
  {num:10,words:[["En pos de","after"],["Jehová","jehovah"],["caminarán;","they-lord;"],["él","he"],["rugirá","roar"],["como","as"],["león;","lion;"],["cuando","when"],["ruja,","may-roar,"],["entonces","then"],["los","the"],["hijos","children"],["vendrán","they-far"],["temblando","trembling"],["del","of-the"],["occidente.","westward."]]},
  {num:11,words:[["Acudirán","they-shall-come"],["temblando","trembling"],["como","as"],["ave","fowl"],["de","of"],["Egipto","Egypt"],["y","and"],["como","as"],["paloma","dove"],["de","of"],["la","the"],["tierra","land"],["de","of"],["Asiria;","Assyria;"],["y","and"],["los","the"],["haré","I will make"],["morar","dwell"],["en","in"],["sus","their"],["casas,","houses,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:12,words:[["Me", "me"], ["rodeó", "about"], ["Efraín","Ephraim"], ["con", "with"], ["mentira,", "lies,"], ["y", "and"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel", "Israel"], ["con", "with"], ["engaño,", "guile,"], ["pero", "but"], ["Judá", "Judah"], ["aún","yet"], ["camina","walks"], ["con", "with"], ["Dios", "God"], ["y", "and"], ["es", "is"], ["fiel", "faithful"], ["con", "with"], ["los", "the"], ["santos.", "saints."]]},
];
renderVerseSet(v11, 'hos-ch11-verses');

var v12 = [
  {num:1,words:[["Efraín","Ephraim"],["se","himself"],["apacienta","he"],["de","of"],["viento","wind"],["y","and"],["va","goes"],["tras","after"],["el","the"],["solano;","wind;"],["mentira","lies"],["y","and"],["destrucción","destruction"],["aumentan","they-increase"],["continuamente,","continually,"],["porque","because"],["hicieron","they-did"],["alianza","league"],["con","with"],["los","the"],["asirios","assyria"],["y","and"],["llevan","they-carry"],["aceite","oil"],["a","to"],["Egipto.","Egypt."]]},
  {num:2,words:[["Pleito","the"],["tiene","has"],["Jehová","jehovah"],["con","with"],["Judá","Judah"],["y","and"],["castigará","will-punish"],["a","to"],["Jacob","Jacob"],["conforme","according-to"],["a","to"],["sus","his"],["caminos;","ways;"],["le","him"],["pagará","will-pay"],["conforme","according-to"],["a","to"],["sus","his"],["obras.","works."]]},
  {num:3,words:[["En", "in"], ["el", "the"], ["vientre", "belly"], ["tomó", "took"], ["por","by"], ["el", "the"], ["calcañar", "heel"], ["a", "to"], ["su","his"], ["hermano,", "brother,"], ["y", "and"], ["con", "with"], ["su","his"], ["fuerza", "strength"], ["luchó", "fought"], ["con", "with"], ["Dios.", "God."]]},
  {num:4,words:[["Luchó","fought"],["con","with"],["el","the"],["ángel","angel"],["y","and"],["prevaleció;","prevailed;"],["lloró","wept"],["y","and"],["le","him"],["suplicó;","begged;"],["en","in"],["Bet-el","bethel"],["le","him"],["halló,","found,"],["y","and"],["allí","there"],["habló","spoke"],["con","with"],["nosotros.","we."]]},
  {num:5,words:[["Mas", "but"], ["Jehová", "jehovah"], ["es", "is"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["ejércitos.", "armies."], ["¡Jehová", "jehovah"], ["es", "is"], ["su","his"], ["nombre!", "name!"]]},
  {num:6,words:[["Tú,","you,"], ["pues,", "for,"], ["conviértete","the-you"], ["a", "to"], ["tu","your"], ["Dios;", "God;"], ["guarda", "keeps"], ["la", "the"], ["misericordia", "mercy"], ["y", "and"], ["el", "the"], ["juicio,", "judgment,"], ["y", "and"], ["en", "in"], ["tu","your"], ["Dios", "God"], ["confía","trusts"], ["siempre.", "always."]]},
  {num:7,words:[["Al","to-the"],["mercader","is"],["que","that"],["tiene","has"],["en","in"],["su","his"],["mano","hand"],["pesas","weights"],["falsas,","to,"],["le","his"],["gusta","likes"],["oprimir.","to-oppress."]]},
  {num:8,words:[["Y","and"],["dijo","said"],["Efraín:","Ephraim:"],["Ciertamente","surely"],["yo","I"],["me","me"],["he","I-have"],["enriquecido;","i;"],["he","I-have"],["hallado","found"],["riquezas","riches"],["para","for"],["mí;","me;"],["nadie","no-one"],["hallará","will-find"],["iniquidad","iniquity"],["en","in"],["mí","me"],["ni","nor"],["pecado","sin"],["en","in"],["todos","all"],["mis","my"],["trabajos.","works."]]},
  {num:9,words:[["Sin embargo,","nevertheless,"],["yo","I"],["soy","am"],["Jehová","jehovah"],["tu","your"],["Dios","God"],["desde","from"],["la","the"],["tierra","land"],["de","of"],["Egipto;","Egypt;"],["aún","yet"],["te","you"],["haré","I will make"],["morar","dwell"],["en","in"],["tiendas,","tents,"],["como","as"],["en","in"],["los","the"],["días","days"],["de","of"],["la","the"],["fiesta","feast"],["solemne.","solemn."]]},
  {num:10,words:[["Y","and"],["he","I-have"],["hablado","spoken"],["a","to"],["los","the"],["profetas,","prophets,"],["y","and"],["yo","I"],["multipliqué","multiplied"],["las","the"],["visiones","visions"],["y","and"],["por medio de","by means of"],["los","the"],["profetas","prophets"],["usé","I-used"],["similitudes.","prophets."]]},
  {num:11,words:[["¿Hay","there-is"],["iniquidad","iniquity"],["en","in"],["Galaad?","Gilead?"],["Ciertamente","surely"],["vanidad","vanity"],["han","they-have"],["sido.","been."],["En","in"],["Gilgal","Gilgal"],["sacrificaron","they-sacrificed"],["bueyes,","oxen,"],["y","and"],["aún","yet"],["son","they-are"],["sus","their"],["altares","altars"],["como","as"],["montones","heaps"],["en","in"],["los","the"],["surcos","of"],["del","of-the"],["campo.","field."]]},
  {num:12,words:[["Mas","but"],["Jacob","Jacob"],["huyó","fled"],["a","to"],["la","the"],["tierra","land"],["de","of"],["Aram;","aram;"],["y","and"],["sirvió","served"],["Israel","Israel"],["para","for"],["adquirir","to-acquire"],["una","a"],["esposa,","wife,"],["y","and"],["para","for"],["adquirir","to-acquire"],["una","a"],["esposa","wife"],["fue","was"],["pastor.","shepherd."]]},
  {num:13,words:[["Y", "and"], ["por medio de","by means of"], ["un", "a"], ["profeta", "prophet"], ["Jehová", "jehovah"], ["hizo", "made/did"], ["subir", "go-up"], ["a", "to"], ["Israel", "Israel"], ["de", "of"], ["Egipto,", "Egypt,"], ["y", "and"], ["por","by"], ["un", "a"], ["profeta", "prophet"], ["fue","was"], ["guardado.", "kept."]]},
  {num:14,words:[["Efraín","Ephraim"],["ha","has"],["irritado","angered"],["a","to"],["Dios","God"],["amargamente;","the;"],["por tanto,","therefore,"],["su","his"],["sangre","blood"],["dejará","will-leave"],["sobre","upon"],["él,","he,"],["y","and"],["su","his"],["Señor","Lord"],["le","him"],["devolverá","will-return"],["su","his"],["oprobio.","reproach."]]},
];
renderVerseSet(v12, 'hos-ch12-verses');

var v13 = [
  {num:1,words:[["Cuando","when"],["Efraín","Ephraim"],["hablaba,","talked,"],["había","had"],["temor;","fear;"],["fue","was"],["ensalzado","exalted"],["en","in"],["Israel,","Israel,"],["pero","but"],["pecó","sinned"],["por","for"],["causa","cause/sake"],["de","of"],["Baal","Baal"],["y","and"],["murió.","died."]]},
  {num:2,words:[["Y","and"],["ahora","now"],["continúan","they-continue"],["en","in"],["su","their"],["pecado,","sin,"],["y","and"],["de","of"],["su","their"],["plata","silver"],["se","themselves"],["han","have"],["hecho,","made,"],["según","according-to"],["su","their"],["entendimiento,","understanding,"],["imágenes","groves"],["de","of"],["fundición,","molten,"],["ídolos,","idols,"],["todo","all"],["ello","it"],["obra","work"],["de","of"],["artífices.","craftsmen."],["De","of"],["ellos","they"],["dicen:","say:"],["Que","that"],["los","the"],["hombres","men"],["que","that"],["sacrifican","they-men"],["besen","they-may-kiss"],["a","to"],["los","the"],["becerros.","calves."]]},
  {num:3,words:[["Por tanto,","therefore,"],["serán","they-shall-be"],["como","as"],["la","the"],["niebla","the"],["de","of"],["la","the"],["mañana","morning"],["o","or"],["como","as"],["el","the"],["rocío","dew"],["de","of"],["la","the"],["madrugada","away,"],["que","that"],["se","itself"],["desvanece,","chaff,"],["como","as"],["el","the"],["tamo","chaff"],["que","that"],["la","the"],["tempestad","storm"],["arroja","cast"],["de","of"],["la","the"],["era","was"],["y","and"],["como","as"],["el","the"],["humo","smoke"],["que","that"],["sale","goes"],["de","of"],["la","the"],["chimenea.","chimney."]]},
  {num:4,words:[["Mas","but"],["yo","I"],["soy","am"],["Jehová","jehovah"],["tu","your"],["Dios","God"],["desde","from"],["la","the"],["tierra","land"],["de","of"],["Egipto;","Egypt;"],["no","not"],["reconocerás","you-shall-spy"],["a","to"],["otro","other"],["Dios","God"],["fuera","were"],["de","of"],["mí,","me,"],["ni","nor"],["a","to"],["otro","other"],["Salvador","Savior"],["sino","but"],["a","to"],["mí.","me."]]},
  {num:5,words:[["Yo","I"],["te","you"],["conocí","I-knew"],["en","in"],["el","the"],["desierto,","wilderness,"],["en","in"],["tierra","land"],["de","of"],["sequía.","drought."]]},
  {num:6,words:[["En","in"],["sus","their"],["pastos","pasture"],["se","themselves"],["saciaron;","filled;"],["se","themselves"],["saciaron","filled"],["y","and"],["se","himself"],["ensoberbeció","filled,"],["su","their"],["corazón;","heart;"],["por","for"],["esta","this"],["causa","cause/sake"],["se","themselves"],["olvidaron","they-forgot"],["de","of"],["mí.","me."]]},
  {num:7,words:[["Por tanto,","therefore,"],["yo","I"],["seré","I will be"],["para","for"],["ellos","they"],["como","as"],["león;","lion;"],["como","as"],["un","a"],["leopardo","leopard"],["en","in"],["el","the"],["camino","way"],["los","the"],["acecharé.","I-will-stalk."]]},
  {num:8,words:[["Como","as"],["osa","bear"],["que","that"],["ha","has"],["perdido","lost"],["sus","her"],["cachorros","whelps"],["los","the"],["encontraré","shall-find"],["y","and"],["desgarraré","I-will-tear"],["las","the"],["fibras","rend"],["de","of"],["su","her"],["corazón,","heart,"],["y","and"],["allí","there"],["los","the"],["devoraré","shall-to"],["como","as"],["león;","lion;"],["una","a"],["fiera","ferocious"],["del","of-the"],["campo","field"],["los","the"],["despedazará.","will-tear-apart."]]},
  {num:9,words:[["Te","you"], ["destruiste,", "israel,"], ["oh", "oh"], ["Israel,", "Israel,"], ["pero", "but"], ["en", "in"], ["mí", "me"], ["está", "is"], ["tu","your"], ["ayuda.", "assistance."]]},
  {num:10,words:[["¿Dónde","where"],["está","is"],["tu","your"],["rey,","king,"],["para que","that"],["te","you"],["salve","the"],["en","in"],["todas","all"],["tus","your"],["ciudades,","cities,"],["y","and"],["tus","your"],["jueces,","judges,"],["de","of"],["quienes","who"],["dijiste:","saidst:"],["Dame","give"],["rey","king"],["y","and"],["príncipes?","princes?"]]},
  {num:11,words:[["Te","you"],["di","give"],["rey","king"],["en","in"],["mi","my"],["furor,","fury,"],["y","and"],["te","you"],["lo","him"],["quité","away"],["en","in"],["mi","my"],["ira.","anger."]]},
  {num:12,words:[["Atada", "loose"], ["está", "is"], ["la", "the"], ["iniquidad", "iniquity"], ["de", "of"], ["Efraín;","Ephraim;"], ["su","his"], ["pecado", "sin"], ["está", "is"], ["guardado.", "kept."]]},
  {num:13,words:[["Dolores","sorrows"],["como","as"],["de","of"],["mujer","woman"],["que","that"],["está","is"],["de","of"],["parto","travail"],["le","him"],["vendrán;","they-will-come;"],["es","is"],["un","a"],["hijo","son"],["insensato","fool"],["que","that"],["no","not"],["se","himself"],["coloca","places"],["en","in"],["posición","for"],["al","to-the"],["momento","moment"],["del","of-the"],["alumbramiento.","children."]]},
  {num:14,words:[["De","of"],["manos","hands"],["del","of-the"],["Seol","grave"],["los","the"],["rescataré,","power,"],["los","the"],["redimiré","shall-redeem"],["de","of"],["la","the"],["muerte.","death."],["¿Dónde","where"],["están,","they-are,"],["oh","oh"],["muerte,","death,"],["tus","your"],["plagas?","plagues?"],["¿Dónde","where"],["está,","is,"],["oh","oh"],["Seol,","grave,"],["tu","your"],["destrucción?","destruction?"],["La","the"],["compasión","compassion"],["se","itself"],["esconderá","will-hide"],["de","of"],["mis","my"],["ojos.","eyes."]]},
  {num:15,words:[["Aunque","although"],["él","he"],["fructifique","fruitful"],["entre","among"],["los","the"],["hermanos,","brothers,"],["vendrá","shall-come"],["el","the"],["solano,","wind,"],["viento","wind"],["de","of"],["Jehová,","jehovah,"],["subiendo","went"],["del","of-the"],["desierto,","wilderness,"],["y","and"],["se","himself"],["secará","will-dry"],["su","his"],["fuente,","laver,"],["y","and"],["se","himself"],["secará","will-dry"],["su","his"],["manantial;","fountain;"],["él","he"],["saqueará","dried"],["el","the"],["tesoro","treasure"],["de","of"],["todos","all"],["los","the"],["objetos","things"],["preciosos.","precious."]]},
  {num:16,words:[["Samaria","Samaria"],["será","shall-be"],["considerada","consider"],["culpable,","guilty,"],["porque","because"],["se","itself"],["rebeló","rebelled"],["contra","against"],["su","her"],["Dios;","God;"],["caerán","they-will-fall"],["a","to"],["espada;","sword;"],["sus","her"],["niños","children"],["serán","they-shall-be"],["estrellados,","pieces,"],["y","and"],["sus","her"],["mujeres","women"],["encintas","child"],["serán","they-shall-be"],["abiertas.","the."]]},
];
renderVerseSet(v13, 'hos-ch13-verses');

var v14 = [
  {num:1,words:[["¡Vuélvete,","return,"],["oh","oh"],["Israel,","Israel,"],["a","to"],["Jehová","jehovah"],["tu","your"],["Dios,","God,"],["porque","because"],["por","for"],["tu","your"],["iniquidad","iniquity"],["has","you-have"],["caído!","fallen!"]]},
  {num:2,words:[["Tomad","you-take"],["con","with"],["vosotros","you"],["palabras,","words,"],["y","and"],["volveos","turn"],["a","to"],["Jehová","jehovah"],["y","and"],["decidle:","and:"],["Quita","takes"],["toda","all"],["iniquidad","iniquity"],["y","and"],["acéptanos","he-us"],["bien,","well,"],["y","and"],["ofreceremos","we-will-offer"],["el","the"],["fruto","fruit"],["de","of"],["nuestros","our"],["labios.","lips."]]},
  {num:3,words:[["No","not"],["nos","us"],["librará","deliver"],["Asiria;","Assyria;"],["no","not"],["montaremos","we-will-mount"],["a","to"],["caballo","horse"],["ni","nor"],["nunca","never"],["más","more"],["diremos","we-will-say"],["a","to"],["la","the"],["obra","work"],["de","of"],["nuestras","our"],["manos:","hands:"],["Dioses","gods"],["nuestros,","our,"],["porque","because"],["en","in"],["ti","you"],["el","the"],["huérfano","fatherless"],["alcanzará","will-reach"],["misericordia.","mercy."]]},
  {num:4,words:[["Yo","I"],["los","the"],["sanaré","heal"],["de","of"],["su","their"],["rebelión;","rebellion;"],["los","the"],["amaré","shall-love"],["por","for"],["mi","my"],["propia","own"],["voluntad,","will,"],["porque","because"],["mi","my"],["furor","fury"],["se","himself"],["apartó","nebat"],["de","of"],["ellos.","they."]]},
  {num:5,words:[["Yo","I"],["seré","I will be"],["a","to"],["Israel","Israel"],["como","as"],["el","the"],["rocío;","dew;"],["él","he"],["florecerá","shall"],["como","as"],["lirio","lily"],["y","and"],["extenderá","hand"],["sus","his"],["raíces","roots"],["como","as"],["el","the"],["Líbano.","lebanon."]]},
  {num:6,words:[["Se","themselves"],["extenderán","spread"],["sus","his"],["ramas,","branches,"],["y","and"],["será","shall-be"],["su","his"],["gloria","glory"],["como","as"],["la","the"],["del","of-the"],["olivo","olive"],["y","and"],["su","his"],["fragancia","and"],["como","as"],["la","the"],["del","of-the"],["Líbano.","lebanon."]]},
  {num:7,words:[["Volverán","they-will-return"],["los","the"],["que","that"],["moran","they-dwell"],["bajo","under"],["su","his"],["sombra;","shadow;"],["serán","they-shall-be"],["vivificados","shall"],["como","as"],["trigo","wheat"],["y","and"],["florecerán","and"],["como","as"],["la","the"],["vid;","vine;"],["su","his"],["fama","fame"],["será","shall-be"],["como","as"],["la","the"],["del","of-the"],["vino","wine"],["del","of-the"],["Líbano.","lebanon."]]},
  {num:8,words:[["Efraín:","Ephraim:"],["¿Qué","what"],["tengo","I-have"],["yo","I"],["que","that"],["ver","see"],["ya","already"],["con","with"],["los","the"],["ídolos?","idols?"],["Yo","I"],["respondo","answer"],["y","and"],["lo","him"],["cuido;","I-take-care-of;"],["yo","I"],["seré","shall-be"],["a","to"],["él","he"],["como","as"],["el","the"],["ciprés","fir"],["verde;","green;"],["en","in"],["mí","me"],["será","shall-be"],["hallado","found"],["tu","your"],["fruto.","fruit."]]},
  {num:9,words:[["¿Quién","who"],["es","is"],["sabio","wise"],["para que","that"],["entienda","may-understand"],["esto,","this,"],["y","and"],["prudente","prudent"],["para que","that"],["lo","it/him"],["sepa?","may-know?"],["Porque","because"],["los","the"],["caminos","ways"],["de","of"],["Jehová","jehovah"],["son","they-are"],["rectos,","upright,"],["y","and"],["los","the"],["justos","righteous"],["andarán","they-will-walk"],["por","for"],["ellos;","they;"],["mas","but"],["los","the"],["rebeldes","rebellious"],["caerán","they-will-fall"],["en","in"],["ellos.","they."]]},
];
renderVerseSet(v14, 'hos-ch14-verses');

})();
