(function() {
var v1 = [
  {num:1,words:[["Y","and"],["vino","came"],["la","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["a","to"],["Jonás","Jonah"],["hijo","son"],["de","of"],["Amitai,","Amittai,"],["diciendo:","saying:"]]},
  {num:2,words:[["Levántate,","arise,"],["ve","you-go"],["a","to"],["Nínive,","Nineveh,"],["la","the"],["gran","great"],["ciudad,","city,"],["y","and"],["clama","cries"],["contra","against"],["ella,","she,"],["porque","because"],["su","their"],["maldad","wickedness"],["ha","has"],["subido","gone-up"],["delante","before"],["de","of"],["mí.","me."]]},
  {num:3,words:[["Pero","but"],["Jonás","Jonah"],["se","himself"],["levantó","arose"],["para","for"],["huir","to-flee"],["de","of"],["la","the"],["presencia","presence"],["de","of"],["Jehová","jehovah"],["a","to"],["Tarsis,","Tarshish,"],["y","and"],["descendió","descended"],["a","to"],["Jope","Joppa"],["y","and"],["halló","found"],["una","a"],["nave","ship"],["que","that"],["partía","was-departing"],["para","for"],["Tarsis;","Tarshish;"],["y","and"],["pagando","paying"],["su","his"],["pasaje,","passage,"],["entró","entered"],["en","in"],["ella","she"],["para","for"],["irse","he"],["con","with"],["ellos","they"],["a","to"],["Tarsis,","Tarshish,"],["lejos","far"],["de","of"],["la","the"],["presencia","presence"],["de","of"],["Jehová.","jehovah."]]},
  {num:4,words:[["Pero","but"],["Jehová","jehovah"],["hizo","made/did"],["levantar","raise"],["un","a"],["gran","great"],["viento","wind"],["en","in"],["el","the"],["mar,","sea,"],["y","and"],["hubo","there-was"],["una","a"],["tempestad","storm"],["tan","so"],["grande","great"],["en","in"],["el","the"],["mar","sea"],["que","that"],["se","itself"],["pensó","noted"],["que","that"],["se","itself"],["partiría","would-depart"],["la","the"],["nave.","ship."]]},
  {num:5,words:[["Y","and"],["los","the"],["marineros","mariners"],["tuvieron","they-afraid"],["miedo,","afraid,"],["y","and"],["cada","each"],["uno","one"],["clamaba","cried"],["a","to"],["su","his"],["dios;","God;"],["y","and"],["echaron","they-cast"],["al","to-the"],["mar","sea"],["los","the"],["enseres","vessels"],["que","that"],["había","had"],["en","in"],["la","the"],["nave,","ship,"],["para","for"],["aligerarla.","to-lighten-it."],["Pero","but"],["Jonás","Jonah"],["había","had"],["bajado","gone-down"],["al","to-the"],["interior","inner"],["de","of"],["la","the"],["nave,","ship,"],["y","and"],["se","itself"],["había","had"],["acostado","to"],["y","and"],["dormía","slept"],["profundamente.","in."]]},
  {num:6,words:[["Y","and"],["el","the"],["maestre","shipmaster"],["de","of"],["la","the"],["nave","ship"],["se","himself"],["acercó","drew"],["a","to"],["él","he"],["y","and"],["le","him"],["dijo:","said:"],["¿Qué","what"],["tienes,","you-have,"],["dormilón?","call?"],["Levántate","arise"],["y","and"],["clama","cries"],["a","to"],["tu","your"],["Dios.","God."],["Quizá","perhaps"],["tu","your"],["Dios","God"],["piense","may-think"],["en","in"],["nosotros","we"],["y","and"],["no","not"],["perezcamos.","we-may-perish."]]},
  {num:7,words:[["Y","and"],["dijo","said"],["cada","each"],["uno","one"],["a","to"],["su","his"],["compañero:","companion:"],["Venid","you-come"],["y","and"],["echemos","we-may-cast"],["suertes,","lots,"],["para","for"],["saber","to-know"],["por","for"],["culpa","guilt"],["de","of"],["quién","who"],["nos","us"],["ha","has"],["venido","come"],["este","this"],["mal.","evil."],["Y","and"],["echaron","they-lots"],["suertes,","lots,"],["y","and"],["la","the"],["suerte","lot"],["cayó","fell"],["sobre","upon"],["Jonás.","Jonah."]]},
  {num:8,words:[["Entonces","then"],["le","him"],["dijeron","said"],["ellos:","they:"],["Decláranos,","to-us,"],["te","you"],["rogamos,","beseech,"],["por","for"],["qué","what"],["nos","us"],["ha","has"],["venido","come"],["este","this"],["mal.","evil."],["¿Qué","what"],["oficio","occupation"],["tienes","you-have"],["y","and"],["de","of"],["dónde","where"],["vienes?","you-come?"],["¿Cuál","which"],["es","is"],["tu","your"],["tierra,","land,"],["y","and"],["de","of"],["qué","what"],["pueblo","people"],["eres?","you-are?"]]},
  {num:9,words:[["Y","and"],["él","he"],["les","them"],["respondió:","answered:"],["Soy","I-am"],["hebreo","Hebrew"],["y","and"],["temo","I-fear"],["a","to"],["Jehová,","jehovah,"],["Dios","God"],["de","of"],["los","the"],["cielos,","heavens,"],["que","that"],["hizo","made"],["el","the"],["mar","sea"],["y","and"],["la","the"],["tierra.","land."]]},
  {num:10,words:[["Y","and"],["aquellos","those"],["hombres","men"],["temieron","they-feared"],["sobremanera","exceedingly"],["y","and"],["le","him"],["dijeron:","they-said:"],["¿Por","for"],["qué","what"],["has","you-have"],["hecho","done"],["esto?","this?"],["Porque","because"],["ellos","they"],["sabían","knew"],["que","that"],["huía","fled"],["de","of"],["la","the"],["presencia","presence"],["de","of"],["Jehová,","jehovah,"],["porque","because"],["él","he"],["se","himself"],["lo","him"],["había","had"],["declarado.","declared."]]},
  {num:11,words:[["Y","and"],["le","him"],["dijeron:","they-said:"],["¿Qué","what"],["haremos","we-will-make"],["contigo","with-you"],["para que","that"],["el","the"],["mar","sea"],["se","himself"],["nos","us"],["aquiete?","may-quieten?"],["Porque","because"],["el","the"],["mar","sea"],["se","himself"],["iba","went"],["embraveciendo","sea"],["más","more"],["y","and"],["más.","more."]]},
  {num:12,words:[["Y","and"],["él","he"],["les","them"],["respondió:","answered:"],["Tomadme","take-me"],["y","and"],["echadme","and-me"],["al","to-the"],["mar,","sea,"],["y","and"],["el","the"],["mar","sea"],["se","himself"],["os","you"],["aquietará,","will-quieten,"],["porque","because"],["yo","I"],["sé","know"],["que","that"],["por","for"],["mi","my"],["causa","sake"],["ha","has"],["venido","come"],["esta","this"],["gran","great"],["tempestad","storm"],["sobre","upon"],["vosotros.","you."]]},
  {num:13,words:[["Y","and"],["aquellos","those"],["hombres","men"],["remaron","they-rowed"],["con","with"],["todas","all"],["sus","his"],["fuerzas","forces"],["para","for"],["hacer","do"],["volver","to-return"],["la","the"],["nave","ship"],["a","to"],["tierra,","land,"],["pero","but"],["no pudieron,","they-could-not,"],["porque","because"],["el","the"],["mar","sea"],["se","itself"],["iba","went"],["embraveciendo","and"],["más","more"],["y","and"],["más","more"],["contra","against"],["ellos.","they."]]},
  {num:14,words:[["Entonces","then"],["clamaron","they-cried"],["a","to"],["Jehová","jehovah"],["y","and"],["dijeron:","they-said:"],["Te","you"],["rogamos,","beseech,"],["oh","oh"],["Jehová,","jehovah,"],["te","you"],["suplicamos","we-beg"],["que","that"],["no","not"],["perezcamos","may-perish"],["nosotros","we"],["por","for"],["la","the"],["vida","life"],["de","of"],["este","this"],["hombre,","man,"],["ni","nor"],["pongas","you-may-put"],["sobre","upon"],["nosotros","we"],["sangre","blood"],["inocente,","innocent,"],["porque","because"],["tú,","you,"],["Jehová,","jehovah,"],["has","you-have"],["hecho","done"],["como","as"],["has","you-have"],["querido.","lord."]]},
  {num:15,words:[["Y","and"],["tomaron","they-took"],["a","to"],["Jonás","Jonah"],["y","and"],["lo","him"],["echaron","they-cast"],["al","to-the"],["mar,","sea,"],["y","and"],["el","the"],["furor","fury"],["del","of-the"],["mar","sea"],["se","himself"],["aquietó.","raging."]]},
  {num:16,words:[["Y","and"],["temieron","they-feared"],["aquellos","those"],["hombres","men"],["a","to"],["Jehová","jehovah"],["con","with"],["gran","great"],["temor,","fear,"],["y","and"],["ofrecieron","they-offered"],["sacrificio","sacrifice"],["a","to"],["Jehová","jehovah"],["e","and"],["hicieron","they-made"],["votos.","vows."]]},
  {num:17,words:[["Pero","but"],["Jehová","jehovah"],["tenía","had"],["preparado","prepared"],["un","a"],["gran","great"],["pez","fish"],["para que","that"],["se","himself"],["tragase","up"],["a","to"],["Jonás;","Jonah;"],["y","and"],["estuvo","stood"],["Jonás","Jonah"],["en","in"],["el","the"],["vientre","belly"],["del","of-the"],["pez","fish"],["tres","three"],["días","days"],["y","and"],["tres","three"],["noches.","nights."]]},
];
renderVerseSet(v1, 'jon-ch1-verses');

var v2 = [
  {num:1,words:[["Entonces", "then"], ["oró", "prayed"], ["Jonás","Jonah"], ["desde", "from"], ["el", "the"], ["vientre", "belly"], ["del", "of-the"], ["pez", "fish"], ["a", "to"], ["Jehová,", "jehovah,"], ["su","his"], ["Dios,", "God,"]]},
  {num:2,words:[["y","and"],["dijo:Clamé","i"],["en","in"],["mi","my"],["angustia","anguish"],["a","to"],["Jehová,y","o"],["él","he"],["me","me"],["oyó;desde","me"],["el","the"],["seno","bosom"],["del","of-the"],["Seol","grave"],["clamé,y","i"],["mi","my"],["voz","voice"],["oíste.","you-heard."]]},
  {num:3,words:[["Me","me"],["echaste","casts-you"],["a","to"],["lo","it/him"],["profundo,en","the"],["medio","midst"],["de","of"],["los","the"],["mares,y","of"],["me","me"],["rodeó","about"],["la","the"],["corriente;todas","compassed"],["tus","your"],["ondas","waves"],["y","and"],["tus","your"],["olas","waves"],["pasaron","passed"],["sobre","about"],["mí.","me."]]},
  {num:4,words:[["Entonces","then"],["dije:","I-said:"],["Desechado","rejected"],["soyde","am"],["delante","before"],["de","of"],["tus","your"],["ojos;mas","yet"],["aún","yet"],["veré","I-see"],["tu","your"],["santo","holy"],["templo.","temple."]]},
  {num:5,words:[["Las","the"],["aguas","waters"],["me","me"],["rodearon","compassed"],["hasta","until"],["el","the"],["alma;me","soul-me"],["rodeó","about"],["el","the"],["abismo;las","deep-them"],["algas","about"],["se","themselves"],["enredaron","they-entangled"],["en","in"],["mi","my"],["cabeza.","head."]]},
  {num:6,words:[["Descendí","i"],["a","to"],["los","the"],["cimientos","foundations"],["de","of"],["los","the"],["montes;la","mountains-her"],["tierra","earth"],["echó","cast"],["sus","her"],["cerrojos","bars"],["sobre","about"],["mí","me"],["para","for"],["siempre;pero","ever"],["tú","you"],["sacaste","brought"],["mi","my"],["vida","life"],["de","of"],["la","the"],["fosa,oh","corruption"],["Jehová,","jehovah,"],["Dios","God"],["mío.","mine."]]},
  {num:7,words:[["Cuando","when"],["mi","my"],["alma","soul"],["desfallecía","within"],["en","in"],["mí,me","me-me"],["acordé","I-remembered"],["de","of"],["Jehová;y","o"],["mi","my"],["oración","prayer"],["llegó","came"],["hasta","until"],["ti,hasta","you"],["tu","your"],["santo","holy"],["templo.","temple."]]},
  {num:8,words:[["Los","the"],["que","that"],["siguen","they-follow"],["vanidades","vanities"],["ilusoriassu","forsake"],["propia","own"],["misericordia","mercy"],["abandonan.","they-forsake."]]},
  {num:9,words:[["Pero","but"],["yo,","I,"],["con","with"],["voz","voice"],["de","of"],["alabanza,te","praise-you"],["ofreceré","I-will-offer"],["sacrificios;cumpliré","i"],["lo","it/him"],["que","that"],["prometí.La","i"],["salvación","salvation"],["pertenece","belongs"],["a","to"],["Jehová.","jehovah."]]},
  {num:10,words:[["Y", "and"], ["mandó", "commanded"], ["Jehová", "jehovah"], ["al", "to-the"], ["pez,", "fish,"], ["y", "and"], ["este", "this"], ["vomitó", "vomited"], ["a", "to"], ["Jonás","Jonah"], ["en", "in"], ["tierra.","land."]]},
];
renderVerseSet(v2, 'jon-ch2-verses');

var v3 = [
  {num:1,words:[["Y","and"],["vino","came"],["la","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["por","for"],["segunda","second"],["vez","time"],["a","to"],["Jonás,","Jonah,"],["diciendo:","saying:"]]},
  {num:2,words:[["Levántate,","arise,"],["ve","you-go"],["a","to"],["Nínive,","Nineveh,"],["la","the"],["gran","great"],["ciudad,","city,"],["y","and"],["proclámale","lord-him"],["el","the"],["mensaje","message"],["que","that"],["yo","I"],["te","you"],["diré.","tell."]]},
  {num:3,words:[["Y","and"],["se","himself"],["levantó","arose"],["Jonás","Jonah"],["y","and"],["fue","was"],["a","to"],["Nínive,","Nineveh,"],["conforme","according-to"],["a","to"],["la","the"],["palabra","word"],["de","of"],["Jehová.","jehovah."],["Y","and"],["era","was"],["Nínive","Nineveh"],["una","a"],["ciudad","city"],["grande,","great,"],["de","of"],["tres","three"],["días","days"],["de","of"],["camino.","way."]]},
  {num:4,words:[["Y","and"],["comenzó","began"],["Jonás","Jonah"],["a","to"],["entrar","enter"],["por","for"],["la","the"],["ciudad,","city,"],["camino","way"],["de","of"],["un","a"],["día,","day,"],["y","and"],["proclamaba,","proclaimed,"],["diciendo:","saying:"],["De","of"],["aquí","here"],["a","to"],["cuarenta","forty"],["días","days"],["Nínive","Nineveh"],["será","shall-be"],["destruida.","destroyed."]]},
  {num:5,words:[["Y","and"],["los","the"],["hombres","men"],["de","of"],["Nínive","Nineveh"],["creyeron","they-believed"],["a","to"],["Dios,","God,"],["y","and"],["proclamaron","they-proclaimed"],["ayuno","fasting"],["y","and"],["se","themselves"],["vistieron","sackcloth"],["de","of"],["cilicio","sackcloth"],["desde","from"],["el","the"],["mayor","greater"],["hasta","until"],["el","the"],["menor","lesser"],["de","of"],["ellos.","they."]]},
  {num:6,words:[["Y","and"],["llegó","came"],["la","the"],["noticia","news"],["hasta","until"],["el","the"],["rey","king"],["de","of"],["Nínive,","Nineveh,"],["y","and"],["se","himself"],["levantó","arose"],["de","of"],["su","his"],["trono,","throne,"],["y","and"],["se","himself"],["despojó","spoil"],["de","of"],["su","his"],["vestido,","clothed,"],["y","and"],["se","himself"],["cubrió","covered"],["de","of"],["cilicio","sackcloth"],["y","and"],["se","himself"],["sentó","sat"],["sobre","upon"],["ceniza.","ashes."]]},
  {num:7,words:[["E","and"],["hizo","made/did"],["proclamar","to-proclaim"],["y","and"],["anunciar","to-announce"],["en","in"],["Nínive,","Nineveh,"],["por","by"],["mandato","decree"],["del","of-the"],["rey","king"],["y","and"],["de","of"],["sus","his"],["grandes,","great,"],["diciendo:","saying:"],["Hombres","men"],["y","and"],["animales,","animals,"],["bueyes","oxen"],["y","and"],["ovejas,","sheep,"],["no","not"],["prueben","they-may-try"],["cosa","thing"],["alguna;","some;"],["no","not"],["se","itself"],["les","them"],["dé","yield"],["alimento","food"],["ni","nor"],["beban","they-may-drink"],["agua,","water,"]]},
  {num:8,words:[["sino","but"],["cúbranse","cover-oneself"],["de","of"],["cilicio","sackcloth"],["hombres","men"],["y","and"],["animales,","animals,"],["y","and"],["clamen","they-may-cry"],["a","to"],["Dios","God"],["fuertemente;","mightily;"],["y","and"],["vuélvase","his"],["cada","each"],["uno","one"],["de","of"],["su","his"],["mal","evil"],["camino","way"],["y","and"],["de","of"],["la","the"],["violencia","violence"],["que","that"],["hay","there-is"],["en","in"],["sus","his"],["manos.","hands."]]},
  {num:9,words:[["¿Quién","who"],["sabe?","knows?"],["Puede","can"],["que","that"],["Dios","God"],["se","himself"],["vuelva","return"],["y","and"],["se","himself"],["arrepienta,","repents,"],["y","and"],["se","himself"],["aparte","turn"],["del","of-the"],["furor","fury"],["de","of"],["su","his"],["ira,","anger,"],["y","and"],["no","not"],["perezcamos.","we-may-perish."]]},
  {num:10,words:[["Y","and"],["vio","saw"],["Dios","God"],["lo","it"],["que","that"],["hicieron,","they-did,"],["que","that"],["se","themselves"],["volvieron","returned"],["de","of"],["su","their"],["mal","evil"],["camino;","way;"],["y","and"],["se","itself"],["arrepintió","repented"],["Dios","God"],["del","of-the"],["mal","evil"],["que","that"],["había","had"],["dicho","said"],["que","that"],["les","them"],["haría,","would,"],["y","and"],["no","not"],["lo","it"],["hizo.","did."]]},
];
renderVerseSet(v3, 'jon-ch3-verses');

var v4 = [
  {num:1,words:[["Pero","but"],["esto","this"],["desagradó","displeased"],["a","to"],["Jonás","Jonah"],["en","in"],["extremo,","end,"],["y","and"],["se","himself"],["enojó.","made-angry."]]},
  {num:2,words:[["Y","and"],["oró","prayed"],["a","to"],["Jehová","jehovah"],["y","and"],["dijo:","said:"],["Ahora,","now,"],["oh","oh"],["Jehová,","jehovah,"],["¿no","not"],["es","is"],["esto","this"],["lo","it/him"],["que","that"],["yo","I"],["decía","said"],["estando","being"],["aún","yet"],["en","in"],["mi","my"],["tierra?","land?"],["Por eso","therefore"],["me","me"],["apresuré","therefore"],["a","to"],["huir","flee"],["a","to"],["Tarsis,","Tarshish,"],["porque","because"],["yo","I"],["sabía","knew"],["que","that"],["tú","you"],["eres","are"],["Dios","God"],["clemente","gracious"],["y","and"],["piadoso,","and,"],["tardo","slow"],["en","in"],["enojarte","to-make-angry-you"],["y","and"],["de","of"],["gran","great"],["misericordia,","mercy,"],["y","and"],["que","that"],["te","you"],["arrepientes","you-repent"],["del","of-the"],["mal.","evil."]]},
  {num:3,words:[["Ahora","now"],["pues,","for,"],["oh","oh"],["Jehová,","jehovah,"],["te","you"],["ruego","beseech"],["que","that"],["me","me"],["quites","you-may-remove"],["la","the"],["vida,","life,"],["porque","because"],["mejor","better"],["me","me"],["es","is"],["la","the"],["muerte","death"],["que","that"],["la","the"],["vida.","life."]]},
  {num:4,words:[["Y","and"],["Jehová","jehovah"],["le","him"],["respondió:","answered:"],["¿Haces","make"],["tú","you"],["bien","well"],["en","in"],["enojarte","to-make-angry-you"],["tanto?","therefore?"]]},
  {num:5,words:[["Y","and"],["salió","departed"],["Jonás","Jonah"],["de","of"],["la","the"],["ciudad,","city,"],["y","and"],["se","himself"],["asentó","settled"],["hacia","toward"],["el","the"],["oriente","east"],["de","of"],["la","the"],["ciudad,","city,"],["y","and"],["se","himself"],["hizo","made"],["allí","there"],["una","a"],["enramada","booth"],["y","and"],["se","himself"],["sentó","sat"],["debajo","beneath"],["de","of"],["ella,","she,"],["a","to"],["la","the"],["sombra,","shadow,"],["hasta","until"],["ver","see"],["qué","what"],["sería","should-be"],["de","of"],["la","the"],["ciudad.","city."]]},
  {num:6,words:[["Y","and"],["preparó","prepared"],["Jehová","jehovah"],["Dios","God"],["una","a"],["calabacera,","gourd,"],["la","the"],["cual","which"],["creció","grew"],["sobre","upon"],["Jonás","Jonah"],["para que","that"],["hiciese","might-make"],["sombra","shadow"],["sobre","upon"],["su","his"],["cabeza","head"],["y","and"],["le","him"],["librase","delivers-himself"],["de","of"],["su","his"],["malestar;","discomfort;"],["y","and"],["Jonás","Jonah"],["se","itself"],["alegró","glad"],["grandemente","greatly"],["por","for"],["la","the"],["calabacera.","gourd."]]},
  {num:7,words:[["Mas","but"],["al","to-the"],["venir","come"],["la","the"],["mañana","morning"],["del","of-the"],["día","day"],["siguiente,","next,"],["Dios","God"],["preparó","prepared"],["un","a"],["gusano,","worm,"],["el","the"],["cual","which"],["hirió","struck"],["la","the"],["calabacera,","the,"],["y","and"],["esta","this"],["se","itself"],["secó.","withered."]]},
  {num:8,words:[["Y","and"],["acaeció","it-came-to-pass"],["que","that"],["al","to-the"],["salir","go-forth"],["el","the"],["sol,","sun,"],["preparó","prepared"],["Dios","God"],["un","a"],["recio","prepared"],["viento","wind"],["solano;","wind;"],["y","and"],["el","the"],["sol","sun"],["hirió","struck"],["a","to"],["Jonás","Jonah"],["en","in"],["la","the"],["cabeza,","head,"],["y","and"],["se","himself"],["desmayaba","fainted"],["y","and"],["deseaba","desired"],["la","the"],["muerte,","death,"],["diciendo:","saying:"],["Mejor","better"],["sería","should-be"],["para","for"],["mí","me"],["la","the"],["muerte","death"],["que","that"],["la","the"],["vida.","life."]]},
  {num:9,words:[["Entonces","then"],["dijo","said"],["Dios","God"],["a","to"],["Jonás:","Jonah:"],["¿Tanto","therefore"],["te","you"],["enojas","make-angry"],["por","for"],["la","the"],["calabacera?","gourd?"],["Y","and"],["él","he"],["respondió:","answered:"],["Mucho","much"],["me","me"],["enojo,","I-make-angry,"],["hasta","until"],["la","the"],["muerte.","death."]]},
  {num:10,words:[["Y","and"],["dijo","said"],["Jehová:","jehovah:"],["Tuviste","you"],["tú","you"],["lástima","pity"],["de","of"],["la","the"],["calabacera,","on,"],["en","in"],["la","the"],["cual","which"],["no","not"],["trabajaste","you-worked"],["ni","nor"],["tú","you"],["la","the"],["hiciste","you-made"],["crecer,","to-grow,"],["que","that"],["en","in"],["espacio","hours"],["de","of"],["una","a"],["noche","night"],["nació","was-born"],["y","and"],["en","in"],["espacio","hours"],["de","of"],["otra","other"],["noche","night"],["pereció.","perished."]]},
  {num:11,words:[["¿Y","and"],["no","not"],["tendré","will-have"],["yo","I"],["piedad","godliness"],["de","of"],["Nínive,","Nineveh,"],["aquella","that"],["gran","great"],["ciudad","city"],["donde","where"],["hay","there-is"],["más","more"],["de","of"],["ciento","hundred"],["veinte","twenty"],["mil","thousand"],["personas","persons"],["que","that"],["no","not"],["saben","they-know"],["discernir","discern"],["entre","among"],["su","their"],["mano","hand"],["derecha","right"],["y","and"],["su","their"],["mano","hand"],["izquierda,","left,"],["y","and"],["muchos","many"],["animales?","animals?"]]},
];
renderVerseSet(v4, 'jon-ch4-verses');

})();
