(function() {
var v1 = [
  {num:1,words:[["Y", "and"], ["vino", "wine"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["a", "to"], ["Jonás", "jonah"], ["hijo", "son"], ["de", "of"], ["Amitai,", "amittai,"], ["diciendo:", "saying:"]]},
  {num:2,words:[["Levántate,", "arise,"], ["ve", "sees"], ["a", "to"], ["Nínive,", "nineveh,"], ["la", "the"], ["gran", "great"], ["ciudad,", "city,"], ["y", "and"], ["clama", "crieth"], ["contra", "against"], ["ella,", "she,"], ["porque", "because"], ["su", "his/her"], ["maldad", "wickedness"], ["ha", "has"], ["subido", "gone-up"], ["delante", "before"], ["de", "of"], ["mí.", "me."]]},
  {num:3,words:[["Pero", "but"], ["Jonás", "jonah"], ["se", "[refl.]"], ["levantó", "arose"], ["para", "for"], ["huir", "flee"], ["de", "of"], ["la", "the"], ["presencia", "presence"], ["de", "of"], ["Jehová", "jehovah"], ["a", "to"], ["Tarsis,", "tarshish,"], ["y", "and"], ["descendió", "descended"], ["a", "to"], ["Jope", "joppa"], ["y", "and"], ["halló", "found"], ["una", "a"], ["nave", "ship"], ["que", "that"], ["partía", "to"], ["para", "for"], ["Tarsis;", "tarshish;"], ["y", "and"], ["pagando", "paying"], ["su", "his/her"], ["pasaje,", "to,"], ["entró", "entered"], ["en", "in"], ["ella", "she"], ["para", "for"], ["irse", "he"], ["con", "with"], ["ellos", "they"], ["a", "to"], ["Tarsis,", "tarshish,"], ["lejos", "far"], ["de", "of"], ["la", "the"], ["presencia", "presence"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:4,words:[["Pero", "but"], ["Jehová", "jehovah"], ["hizo", "made/did"], ["levantar", "raise"], ["un", "a"], ["gran", "great"], ["viento", "wind"], ["en", "in"], ["el", "the"], ["mar,", "sea,"], ["y", "and"], ["hubo", "there-was"], ["una", "a"], ["tempestad", "storm"], ["tan", "so"], ["grande", "great"], ["en", "in"], ["el", "the"], ["mar", "sea"], ["que", "that"], ["se", "[refl.]"], ["pensó", "ship"], ["que", "that"], ["se", "[refl.]"], ["partiría", "to"], ["la", "the"], ["nave.", "ship."]]},
  {num:5,words:[["Y", "and"], ["los", "the"], ["marineros", "mariners"], ["tuvieron", "afraid"], ["miedo,", "afraid,"], ["y", "and"], ["cada", "each"], ["uno", "one"], ["clamaba", "cried"], ["a", "to"], ["su", "his/her"], ["dios;", "God;"], ["y", "and"], ["echaron", "lots"], ["al", "to-the"], ["mar", "sea"], ["los", "the"], ["enseres", "vessels"], ["que", "that"], ["había", "had"], ["en", "in"], ["la", "the"], ["nave,", "ship,"], ["para", "for"], ["aligerarla.", "of."], ["Pero", "but"], ["Jonás", "jonah"], ["había", "had"], ["bajado", "gone-down"], ["al", "to-the"], ["interior", "inner"], ["de", "of"], ["la", "the"], ["nave,", "ship,"], ["y", "and"], ["se", "[refl.]"], ["había", "had"], ["acostado", "to"], ["y", "and"], ["dormía", "fast"], ["profundamente.", "in."]]},
  {num:6,words:[["Y", "and"], ["el", "the"], ["maestre", "shipmaster"], ["de", "of"], ["la", "the"], ["nave", "ship"], ["se", "[refl.]"], ["acercó", "drew"], ["a", "to"], ["él", "he"], ["y", "and"], ["le", "him/her"], ["dijo:", "said:"], ["¿Qué", "what"], ["tienes,", "hast,"], ["dormilón?", "call?"], ["Levántate", "arise"], ["y", "and"], ["clama", "crieth"], ["a", "to"], ["tu", "thy"], ["Dios.", "God."], ["Quizá", "perhaps"], ["tu", "thy"], ["Dios", "God"], ["piense", "the"], ["en", "in"], ["nosotros", "we"], ["y", "and"], ["no", "not"], ["perezcamos.", "not."]]},
  {num:7,words:[["Y", "and"], ["dijo", "said"], ["cada", "each"], ["uno", "one"], ["a", "to"], ["su", "his/her"], ["compañero:", "companion:"], ["Venid", "come"], ["y", "and"], ["echemos", "let"], ["suertes,", "lots,"], ["para", "for"], ["saber", "know"], ["por", "by/for"], ["culpa", "guilt"], ["de", "of"], ["quién", "who"], ["nos", "us"], ["ha", "has"], ["venido", "come"], ["este", "this"], ["mal.", "evil."], ["Y", "and"], ["echaron", "lots"], ["suertes,", "lots,"], ["y", "and"], ["la", "the"], ["suerte", "lot"], ["cayó", "fell"], ["sobre", "upon"], ["Jonás.", "jonah."]]},
  {num:8,words:[["Entonces", "then"], ["le", "him/her"], ["dijeron", "said"], ["ellos:", "they:"], ["Decláranos,", "tell,"], ["te", "thee"], ["rogamos,", "beseech,"], ["por", "by/for"], ["qué", "what"], ["nos", "us"], ["ha", "has"], ["venido", "come"], ["este", "this"], ["mal.", "evil."], ["¿Qué", "what"], ["oficio", "office"], ["tienes", "hast"], ["y", "and"], ["de", "of"], ["dónde", "where"], ["vienes?", "comest?"], ["¿Cuál", "which"], ["es", "is"], ["tu", "thy"], ["tierra,", "land/earth,"], ["y", "and"], ["de", "of"], ["qué", "what"], ["pueblo", "people"], ["eres?", "thou-art?"]]},
  {num:9,words:[["Y", "and"], ["él", "he"], ["les", "them"], ["respondió:", "answered:"], ["Soy", "I-am"], ["hebreo", "hebrew"], ["y", "and"], ["temo", "fear"], ["a", "to"], ["Jehová,", "jehovah,"], ["Dios", "God"], ["de", "of"], ["los", "the"], ["cielos,", "heavens,"], ["que", "that"], ["hizo", "made/did"], ["el", "the"], ["mar", "sea"], ["y", "and"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:10,words:[["Y", "and"], ["aquellos", "those"], ["hombres", "men"], ["temieron", "feared"], ["sobremanera", "exceedingly"], ["y", "and"], ["le", "him/her"], ["dijeron:", "said:"], ["¿Por", "by/for"], ["qué", "what"], ["has", "thou-hast"], ["hecho", "done/made"], ["esto?", "this?"], ["Porque", "because"], ["ellos", "they"], ["sabían", "knew"], ["que", "that"], ["huía", "the"], ["de", "of"], ["la", "the"], ["presencia", "presence"], ["de", "of"], ["Jehová,", "jehovah,"], ["porque", "because"], ["él", "he"], ["se", "[refl.]"], ["lo", "it/him"], ["había", "had"], ["declarado.", "declared."]]},
  {num:11,words:[["Y", "and"], ["le", "him/her"], ["dijeron:", "said:"], ["¿Qué", "what"], ["haremos", "we"], ["contigo", "with-thee"], ["para", "for"], ["que", "that"], ["el", "the"], ["mar", "sea"], ["se", "[refl.]"], ["nos", "us"], ["aquiete?", "may?"], ["Porque", "because"], ["el", "the"], ["mar", "sea"], ["se", "[refl.]"], ["iba", "went"], ["embraveciendo", "sea"], ["más", "more"], ["y", "and"], ["más.", "more."]]},
  {num:12,words:[["Y", "and"], ["él", "he"], ["les", "them"], ["respondió:", "answered:"], ["Tomadme", "take-me"], ["y", "and"], ["echadme", "and-me"], ["al", "to-the"], ["mar,", "sea,"], ["y", "and"], ["el", "the"], ["mar", "sea"], ["se", "[refl.]"], ["os", "you"], ["aquietará,", "the,"], ["porque", "because"], ["yo", "I"], ["sé", "I-know"], ["que", "that"], ["por", "by/for"], ["mi", "my"], ["causa", "cause/sake"], ["ha", "has"], ["venido", "come"], ["esta", "this"], ["gran", "great"], ["tempestad", "storm"], ["sobre", "upon"], ["vosotros.", "you."]]},
  {num:13,words:[["Y", "and"], ["aquellos", "those"], ["hombres", "men"], ["remaron", "men"], ["con", "with"], ["todas", "all"], ["sus", "his/her"], ["fuerzas", "forces"], ["para", "for"], ["hacer", "make/do"], ["volver", "return"], ["la", "the"], ["nave", "ship"], ["a", "to"], ["tierra,", "land/earth,"], ["pero", "but"], ["no", "not"], ["pudieron,", "could,"], ["porque", "because"], ["el", "the"], ["mar", "sea"], ["se", "[refl.]"], ["iba", "went"], ["embraveciendo", "and"], ["más", "more"], ["y", "and"], ["más", "more"], ["contra", "against"], ["ellos.", "they."]]},
  {num:14,words:[["Entonces", "then"], ["clamaron", "cried"], ["a", "to"], ["Jehová", "jehovah"], ["y", "and"], ["dijeron:", "said:"], ["Te", "thee"], ["rogamos,", "beseech,"], ["oh", "oh"], ["Jehová,", "jehovah,"], ["te", "thee"], ["suplicamos", "we"], ["que", "that"], ["no", "not"], ["perezcamos", "let"], ["nosotros", "we"], ["por", "by/for"], ["la", "the"], ["vida", "life"], ["de", "of"], ["este", "this"], ["hombre,", "man,"], ["ni", "nor"], ["pongas", "thee"], ["sobre", "upon"], ["nosotros", "we"], ["sangre", "blood"], ["inocente,", "innocent,"], ["porque", "because"], ["tú,", "thou,"], ["Jehová,", "jehovah,"], ["has", "thou-hast"], ["hecho", "done/made"], ["como", "as"], ["has", "thou-hast"], ["querido.", "lord."]]},
  {num:15,words:[["Y", "and"], ["tomaron", "took"], ["a", "to"], ["Jonás", "jonah"], ["y", "and"], ["lo", "it/him"], ["echaron", "lots"], ["al", "to-the"], ["mar,", "sea,"], ["y", "and"], ["el", "the"], ["furor", "fury"], ["del", "of-the"], ["mar", "sea"], ["se", "[refl.]"], ["aquietó.", "raging."]]},
  {num:16,words:[["Y", "and"], ["temieron", "feared"], ["aquellos", "those"], ["hombres", "men"], ["a", "to"], ["Jehová", "jehovah"], ["con", "with"], ["gran", "great"], ["temor,", "fear,"], ["y", "and"], ["ofrecieron", "offered"], ["sacrificio", "sacrifice"], ["a", "to"], ["Jehová", "jehovah"], ["e", "and"], ["hicieron", "did/made"], ["votos.", "vows."]]},
  {num:17,words:[["Pero", "but"], ["Jehová", "jehovah"], ["tenía", "had"], ["preparado", "prepared"], ["un", "a"], ["gran", "great"], ["pez", "fish"], ["para", "for"], ["que", "that"], ["se", "[refl.]"], ["tragase", "up"], ["a", "to"], ["Jonás;", "jonah;"], ["y", "and"], ["estuvo", "stood"], ["Jonás", "jonah"], ["en", "in"], ["el", "the"], ["vientre", "belly"], ["del", "of-the"], ["pez", "fish"], ["tres", "three"], ["días", "days"], ["y", "and"], ["tres", "three"], ["noches.", "nights."]]},
];
renderVerseSet(v1, 'jon-ch1-verses');

var v2 = [
  {num:1,words:[["Entonces", "then"], ["oró", "prayed"], ["Jonás", "jonah"], ["desde", "from"], ["el", "the"], ["vientre", "belly"], ["del", "of-the"], ["pez", "fish"], ["a", "to"], ["Jehová,", "jehovah,"], ["su", "his/her"], ["Dios,", "God,"]]},
  {num:2,words:[["y", "and"], ["dijo:Clamé", "i"], ["en", "in"], ["mi", "my"], ["angustia", "anguish"], ["a", "to"], ["Jehová,y", "o"], ["él", "he"], ["me", "me"], ["oyó;desde", "me;"], ["el", "the"], ["seno", "bosom"], ["del", "of-the"], ["Seol", "grave"], ["clamé,y", "i,"], ["mi", "my"], ["voz", "voice"], ["oíste.", "heardest."]]},
  {num:3,words:[["Me", "me"], ["echaste", "thou"], ["a", "to"], ["lo", "it/him"], ["profundo,en", "the"], ["medio", "midst"], ["de", "of"], ["los", "the"], ["mares,y", "of"], ["me", "me"], ["rodeó", "about"], ["la", "the"], ["corriente;todas", "compassed"], ["tus", "thy"], ["ondas", "about:"], ["y", "and"], ["tus", "thy"], ["olas", "waves"], ["pasaron", "passed"], ["sobre", "upon"], ["mí.", "me."]]},
  {num:4,words:[["Entonces", "then"], ["dije:", "I-said:"], ["Desechado", "rejected"], ["soyde", "am"], ["delante", "before"], ["de", "of"], ["tus", "thy"], ["ojos;mas", "yet"], ["aún", "still/yet"], ["veré", "see"], ["tu", "thy"], ["santo", "holy"], ["templo.", "temple."]]},
  {num:5,words:[["Las", "the"], ["aguas", "waters"], ["me", "me"], ["rodearon", "compassed"], ["hasta", "until"], ["el", "the"], ["alma;me", "soul-me"], ["rodeó", "about"], ["el", "the"], ["abismo;las", "deep-them"], ["algas", "about,"], ["se", "[refl.]"], ["enredaron", "were"], ["en", "in"], ["mi", "my"], ["cabeza.", "head."]]},
  {num:6,words:[["Descendí", "i"], ["a", "to"], ["los", "the"], ["cimientos", "foundations"], ["de", "of"], ["los", "the"], ["montes;la", "mountains-her"], ["tierra", "land/earth"], ["echó", "cast"], ["sus", "his/her"], ["cerrojos", "bars"], ["sobre", "upon"], ["mí", "me"], ["para", "for"], ["siempre;pero", "ever:"], ["tú", "thou"], ["sacaste", "broughtest"], ["mi", "my"], ["vida", "life"], ["de", "of"], ["la", "the"], ["fosa,oh", "corruption,"], ["Jehová,", "jehovah,"], ["Dios", "God"], ["mío.", "mine."]]},
  {num:7,words:[["Cuando", "when"], ["mi", "my"], ["alma", "soul"], ["desfallecía", "within"], ["en", "in"], ["mí,me", "me-me"], ["acordé", "remembered"], ["de", "of"], ["Jehová;y", "o"], ["mi", "my"], ["oración", "prayer"], ["llegó", "arrived"], ["hasta", "until"], ["ti,hasta", "thee,"], ["tu", "thy"], ["santo", "holy"], ["templo.", "temple."]]},
  {num:8,words:[["Los", "the"], ["que", "that"], ["siguen", "follow"], ["vanidades", "vanities"], ["ilusoriassu", "forsake"], ["propia", "own"], ["misericordia", "mercy"], ["abandonan.", "mercy."]]},
  {num:9,words:[["Pero", "but"], ["yo,", "I,"], ["con", "with"], ["voz", "voice"], ["de", "of"], ["alabanza,te", "praise-thee"], ["ofreceré", "thanksgiving;"], ["sacrificios;cumpliré", "i"], ["lo", "it/him"], ["que", "that"], ["prometí.La", "i"], ["salvación", "salvation"], ["pertenece", "which"], ["a", "to"], ["Jehová.", "jehovah."]]},
  {num:10,words:[["Y", "and"], ["mandó", "commanded"], ["Jehová", "jehovah"], ["al", "to-the"], ["pez,", "fish,"], ["y", "and"], ["este", "this"], ["vomitó", "vomited"], ["a", "to"], ["Jonás", "jonah"], ["en", "in"], ["tierra.", "land/earth."]]},
];
renderVerseSet(v2, 'jon-ch2-verses');

var v3 = [
  {num:1,words:[["Y", "and"], ["vino", "wine"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["por", "by/for"], ["segunda", "second"], ["vez", "time"], ["a", "to"], ["Jonás,", "jonah,"], ["diciendo:", "saying:"]]},
  {num:2,words:[["Levántate,", "arise,"], ["ve", "sees"], ["a", "to"], ["Nínive,", "nineveh,"], ["la", "the"], ["gran", "great"], ["ciudad,", "city,"], ["y", "and"], ["proclámale", "unto"], ["el", "the"], ["mensaje", "message"], ["que", "that"], ["yo", "I"], ["te", "thee"], ["diré.", "tell."]]},
  {num:3,words:[["Y", "and"], ["se", "[refl.]"], ["levantó", "arose"], ["Jonás", "jonah"], ["y", "and"], ["fue", "was/went"], ["a", "to"], ["Nínive,", "nineveh,"], ["conforme", "according-to"], ["a", "to"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová.", "jehovah."], ["Y", "and"], ["era", "was"], ["Nínive", "nineveh"], ["una", "a"], ["ciudad", "city"], ["grande,", "great,"], ["de", "of"], ["tres", "three"], ["días", "days"], ["de", "of"], ["camino.", "way."]]},
  {num:4,words:[["Y", "and"], ["comenzó", "began"], ["Jonás", "jonah"], ["a", "to"], ["entrar", "enter"], ["por", "by/for"], ["la", "the"], ["ciudad,", "city,"], ["camino", "way"], ["de", "of"], ["un", "a"], ["día,", "day,"], ["y", "and"], ["proclamaba,", "and,"], ["diciendo:", "saying:"], ["De", "of"], ["aquí", "here"], ["a", "to"], ["cuarenta", "forty"], ["días", "days"], ["Nínive", "nineveh"], ["será", "shall-be"], ["destruida.", "destroyed."]]},
  {num:5,words:[["Y", "and"], ["los", "the"], ["hombres", "men"], ["de", "of"], ["Nínive", "nineveh"], ["creyeron", "believed"], ["a", "to"], ["Dios,", "God,"], ["y", "and"], ["proclamaron", "the"], ["ayuno", "fasting"], ["y", "and"], ["se", "[refl.]"], ["vistieron", "sackcloth,"], ["de", "of"], ["cilicio", "sackcloth"], ["desde", "from"], ["el", "the"], ["mayor", "greater"], ["hasta", "until"], ["el", "the"], ["menor", "lesser"], ["de", "of"], ["ellos.", "they."]]},
  {num:6,words:[["Y", "and"], ["llegó", "arrived"], ["la", "the"], ["noticia", "they"], ["hasta", "until"], ["el", "the"], ["rey", "king"], ["de", "of"], ["Nínive,", "nineveh,"], ["y", "and"], ["se", "[refl.]"], ["levantó", "arose"], ["de", "of"], ["su", "his/her"], ["trono,", "throne,"], ["y", "and"], ["se", "[refl.]"], ["despojó", "laid"], ["de", "of"], ["su", "his/her"], ["vestido,", "clothed,"], ["y", "and"], ["se", "[refl.]"], ["cubrió", "covered"], ["de", "of"], ["cilicio", "sackcloth"], ["y", "and"], ["se", "[refl.]"], ["sentó", "sat"], ["sobre", "upon"], ["ceniza.", "ashes."]]},
  {num:7,words:[["E", "and"], ["hizo", "made/did"], ["proclamar", "proclaim"], ["y", "and"], ["anunciar", "to"], ["en", "in"], ["Nínive,", "nineveh,"], ["por", "by/for"], ["mandato", "decree"], ["del", "of-the"], ["rey", "king"], ["y", "and"], ["de", "of"], ["sus", "his/her"], ["grandes,", "great,"], ["diciendo:", "saying:"], ["Hombres", "men"], ["y", "and"], ["animales,", "animals,"], ["bueyes", "oxen"], ["y", "and"], ["ovejas,", "sheep,"], ["no", "not"], ["prueben", "herd"], ["cosa", "thing"], ["alguna;", "some;"], ["no", "not"], ["se", "[refl.]"], ["les", "them"], ["dé", "yield"], ["alimento", "food"], ["ni", "nor"], ["beban", "drink"], ["agua,", "water,"]]},
  {num:8,words:[["sino", "but"], ["cúbranse", "let"], ["de", "of"], ["cilicio", "sackcloth"], ["hombres", "men"], ["y", "and"], ["animales,", "animals,"], ["y", "and"], ["clamen", "and"], ["a", "to"], ["Dios", "God"], ["fuertemente;", "mightily;"], ["y", "and"], ["vuélvase", "his"], ["cada", "each"], ["uno", "one"], ["de", "of"], ["su", "his/her"], ["mal", "evil"], ["camino", "way"], ["y", "and"], ["de", "of"], ["la", "the"], ["violencia", "violence"], ["que", "that"], ["hay", "there-is"], ["en", "in"], ["sus", "his/her"], ["manos.", "hands."]]},
  {num:9,words:[["¿Quién", "who"], ["sabe?", "knows?"], ["Puede", "can"], ["que", "that"], ["Dios", "God"], ["se", "[refl.]"], ["vuelva", "return"], ["y", "and"], ["se", "[refl.]"], ["arrepienta,", "repenteth,"], ["y", "and"], ["se", "[refl.]"], ["aparte", "turn"], ["del", "of-the"], ["furor", "fury"], ["de", "of"], ["su", "his/her"], ["ira,", "wrath,"], ["y", "and"], ["no", "not"], ["perezcamos.", "not."]]},
  {num:10,words:[["Y", "and"], ["vio", "saw"], ["Dios", "God"], ["lo", "it/him"], ["que", "that"], ["hicieron,", "did/made,"], ["que", "that"], ["se", "[refl.]"], ["volvieron", "returned"], ["de", "of"], ["su", "his/her"], ["mal", "evil"], ["camino;", "way;"], ["y", "and"], ["se", "[refl.]"], ["arrepintió", "repented"], ["Dios", "God"], ["del", "of-the"], ["mal", "evil"], ["que", "that"], ["había", "had"], ["dicho", "said"], ["que", "that"], ["les", "them"], ["haría,", "would,"], ["y", "and"], ["no", "not"], ["lo", "it/him"], ["hizo.", "made/did."]]},
];
renderVerseSet(v3, 'jon-ch3-verses');

var v4 = [
  {num:1,words:[["Pero", "but"], ["esto", "this"], ["desagradó", "displeased"], ["a", "to"], ["Jonás", "jonah"], ["en", "in"], ["extremo,", "end,"], ["y", "and"], ["se", "[refl.]"], ["enojó.", "wroth."]]},
  {num:2,words:[["Y", "and"], ["oró", "prayed"], ["a", "to"], ["Jehová", "jehovah"], ["y", "and"], ["dijo:", "said:"], ["Ahora,", "now,"], ["oh", "oh"], ["Jehová,", "jehovah,"], ["¿no", "not"], ["es", "is"], ["esto", "this"], ["lo", "it/him"], ["que", "that"], ["yo", "I"], ["decía", "said"], ["estando", "being"], ["aún", "still/yet"], ["en", "in"], ["mi", "my"], ["tierra?", "land/earth?"], ["Por", "by/for"], ["eso", "that"], ["me", "me"], ["apresuré", "therefore"], ["a", "to"], ["huir", "flee"], ["a", "to"], ["Tarsis,", "tarshish,"], ["porque", "because"], ["yo", "I"], ["sabía", "knew"], ["que", "that"], ["tú", "thou"], ["eres", "thou-art"], ["Dios", "God"], ["clemente", "gracious"], ["y", "and"], ["piadoso,", "and,"], ["tardo", "slow"], ["en", "in"], ["enojarte", "to"], ["y", "and"], ["de", "of"], ["gran", "great"], ["misericordia,", "mercy,"], ["y", "and"], ["que", "that"], ["te", "thee"], ["arrepientes", "of"], ["del", "of-the"], ["mal.", "evil."]]},
  {num:3,words:[["Ahora", "now"], ["pues,", "for,"], ["oh", "oh"], ["Jehová,", "jehovah,"], ["te", "thee"], ["ruego", "I-pray/beseech"], ["que", "that"], ["me", "me"], ["quites", "aways"], ["la", "the"], ["vida,", "life,"], ["porque", "because"], ["mejor", "better"], ["me", "me"], ["es", "is"], ["la", "the"], ["muerte", "death"], ["que", "that"], ["la", "the"], ["vida.", "life."]]},
  {num:4,words:[["Y", "and"], ["Jehová", "jehovah"], ["le", "him/her"], ["respondió:", "answered:"], ["¿Haces", "doest"], ["tú", "thou"], ["bien", "well"], ["en", "in"], ["enojarte", "be"], ["tanto?", "so-much?"]]},
  {num:5,words:[["Y", "and"], ["salió", "departed"], ["Jonás", "jonah"], ["de", "of"], ["la", "the"], ["ciudad,", "city,"], ["y", "and"], ["se", "[refl.]"], ["asentó", "his"], ["hacia", "toward"], ["el", "the"], ["oriente", "east"], ["de", "of"], ["la", "the"], ["ciudad,", "city,"], ["y", "and"], ["se", "[refl.]"], ["hizo", "made/did"], ["allí", "there"], ["una", "a"], ["enramada", "booth,"], ["y", "and"], ["se", "[refl.]"], ["sentó", "sat"], ["debajo", "beneath"], ["de", "of"], ["ella,", "she,"], ["a", "to"], ["la", "the"], ["sombra,", "shadow,"], ["hasta", "until"], ["ver", "see"], ["qué", "what"], ["sería", "should"], ["de", "of"], ["la", "the"], ["ciudad.", "city."]]},
  {num:6,words:[["Y", "and"], ["preparó", "prepared"], ["Jehová", "jehovah"], ["Dios", "God"], ["una", "a"], ["calabacera,", "gourd,"], ["la", "the"], ["cual", "which"], ["creció", "grew"], ["sobre", "upon"], ["Jonás", "jonah"], ["para", "for"], ["que", "that"], ["hiciese", "had"], ["sombra", "shadow"], ["sobre", "upon"], ["su", "his/her"], ["cabeza", "head"], ["y", "and"], ["le", "him/her"], ["librase", "delivereth-[refl.]"], ["de", "of"], ["su", "his/her"], ["malestar;", "from;"], ["y", "and"], ["Jonás", "jonah"], ["se", "[refl.]"], ["alegró", "glad"], ["grandemente", "greatly"], ["por", "by/for"], ["la", "the"], ["calabacera.", "gourd."]]},
  {num:7,words:[["Mas", "but"], ["al", "to-the"], ["venir", "come"], ["la", "the"], ["mañana", "morning"], ["del", "of-the"], ["día", "day"], ["siguiente,", "morrow,"], ["Dios", "God"], ["preparó", "prepared"], ["un", "a"], ["gusano,", "worm,"], ["el", "the"], ["cual", "which"], ["hirió", "smote"], ["la", "the"], ["calabacera,", "the,"], ["y", "and"], ["esta", "this"], ["se", "[refl.]"], ["secó.", "withered."]]},
  {num:8,words:[["Y", "and"], ["acaeció", "pass"], ["que", "that"], ["al", "to-the"], ["salir", "go-forth"], ["el", "the"], ["sol,", "sun,"], ["preparó", "prepared"], ["Dios", "God"], ["un", "a"], ["recio", "prepared"], ["viento", "wind"], ["solano;", "wind;"], ["y", "and"], ["el", "the"], ["sol", "sun"], ["hirió", "smote"], ["a", "to"], ["Jonás", "jonah"], ["en", "in"], ["la", "the"], ["cabeza,", "head,"], ["y", "and"], ["se", "[refl.]"], ["desmayaba", "and"], ["y", "and"], ["deseaba", "desired"], ["la", "the"], ["muerte,", "death,"], ["diciendo:", "saying:"], ["Mejor", "better"], ["sería", "should"], ["para", "for"], ["mí", "me"], ["la", "the"], ["muerte", "death"], ["que", "that"], ["la", "the"], ["vida.", "life."]]},
  {num:9,words:[["Entonces", "then"], ["dijo", "said"], ["Dios", "God"], ["a", "to"], ["Jonás:", "jonah:"], ["¿Tanto", "so-much"], ["te", "thee"], ["enojas", "be"], ["por", "by/for"], ["la", "the"], ["calabacera?", "gourd?"], ["Y", "and"], ["él", "he"], ["respondió:", "answered:"], ["Mucho", "much"], ["me", "me"], ["enojo,", "fury,"], ["hasta", "until"], ["la", "the"], ["muerte.", "death."]]},
  {num:10,words:[["Y", "and"], ["dijo", "said"], ["Jehová:", "jehovah:"], ["Tuviste", "thou"], ["tú", "thou"], ["lástima", "hast"], ["de", "of"], ["la", "the"], ["calabacera,", "on,"], ["en", "in"], ["la", "the"], ["cual", "which"], ["no", "not"], ["trabajaste", "which"], ["ni", "nor"], ["tú", "thou"], ["la", "the"], ["hiciste", "madest"], ["crecer,", "grow,"], ["que", "that"], ["en", "in"], ["espacio", "hours"], ["de", "of"], ["una", "a"], ["noche", "night"], ["nació", "was-born"], ["y", "and"], ["en", "in"], ["espacio", "hours"], ["de", "of"], ["otra", "other"], ["noche", "night"], ["pereció.", "perished."]]},
  {num:11,words:[["¿Y", "and"], ["no", "not"], ["tendré", "spare"], ["yo", "I"], ["piedad", "godliness"], ["de", "of"], ["Nínive,", "nineveh,"], ["aquella", "that"], ["gran", "great"], ["ciudad", "city"], ["donde", "where"], ["hay", "there-is"], ["más", "more"], ["de", "of"], ["ciento", "hundred"], ["veinte", "twenty"], ["mil", "thousand"], ["personas", "persons"], ["que", "that"], ["no", "not"], ["saben", "know"], ["discernir", "discern"], ["entre", "among"], ["su", "his/her"], ["mano", "hand"], ["derecha", "right"], ["y", "and"], ["su", "his/her"], ["mano", "hand"], ["izquierda,", "left,"], ["y", "and"], ["muchos", "many"], ["animales?", "animals?"]]},
];
renderVerseSet(v4, 'jon-ch4-verses');

})();
