(function() {
var v1 = [
  {num:1,words:[["Judas,","iscariot,"],["siervo","servant"],["de","of"],["Jesucristo","Jesus-Christ"],["y","and"],["hermano","brother"],["de","of"],["Jacobo,","James,"],["a","to"],["los","the"],["llamados,","called,"],["santificados","sanctified"],["en","in"],["Dios","God"],["el","the"],["Padre,","father,"],["y","and"],["guardados","kept"],["para","for"],["Jesucristo:","Jesus-Christ:"]]},
  {num:2,words:[["Misericordia,","mercy,"],["y","and"],["paz","peace"],["y","and"],["amor","love"],["os","you"],["sean","let-be"],["multiplicados.","multiplied."]]},
  {num:3,words:[["Amados,","beloved,"],["por","for"],["el","the"],["gran","great"],["deseo","I-desire"],["que","that"],["tenía","had"],["de","of"],["escribiros","to-write-you"],["de","of"],["nuestra","our"],["común","common"],["salvación,","salvation,"],["me","me"],["ha","has"],["sido","been"],["necesario","needful"],["escribiros","to-write-you"],["para","for"],["exhortaros","to-exhort-you"],["a que","that"],["luchéis","you-may-fight"],["enérgicamente","energetically"],["por","for"],["la","the"],["fe","faith"],["que","that"],["se","itself"],["ha","has"],["dado","given"],["a","to"],["los","the"],["santos.","saints."]]},
  {num:4,words:[["Porque","because"],["algunos","some"],["hombres","men"],["han","they-have"],["entrado","entered"],["encubiertamente,","crept,"],["los","the"],["que","that"],["desde","from"],["antes","before"],["habían","they-had"],["sido","been"],["designados","appointed"],["para","for"],["esta","this"],["condenación,","condemnation,"],["hombres","men"],["impíos,","ungodly,"],["que","that"],["convierten","they-turning"],["en","in"],["disolución","dissolution"],["la","the"],["gracia","grace"],["de","of"],["nuestro","our"],["Dios","God"],["y","and"],["niegan","they-deny"],["a","to"],["Dios,","God,"],["el","the"],["único","only"],["soberano,","sovereign,"],["y","and"],["a","to"],["nuestro","our"],["Señor","Lord"],["Jesucristo.","Jesus-Christ."]]},
  {num:5,words:[["Quiero,","I-would,"],["pues,","for,"],["recordaros,","to-remember-you,"],["ya que","since"],["alguna","some"],["vez","time"],["habéis","you-have"],["sabido","known"],["esto,","this,"],["que","that"],["el","the"],["Señor,","Lord,"],["habiendo","having"],["salvado","saved"],["al","to-the"],["pueblo","people"],["sacándolo","taking-out-it"],["de","of"],["Egipto,","Egypt,"],["después","afterward"],["destruyó","destroyed"],["a","to"],["los","the"],["que","that"],["no","not"],["creían.","they-believed."]]},
  {num:6,words:[["Y","and"],["a","to"],["los","the"],["ángeles","angels"],["que","that"],["no","not"],["guardaron","they-kept"],["su","their"],["estado","state"],["original,","of,"],["sino que","but"],["dejaron","they-left"],["su","their"],["propia","own"],["morada,","habitation,"],["los","the"],["ha","has"],["guardado","kept"],["bajo","under"],["oscuridad,","darkness,"],["en","in"],["prisiones","bonds"],["eternas,","eternal,"],["hasta","until"],["el","the"],["juicio","judgment"],["del","of-the"],["gran","great"],["día;","day;"]]},
  {num:7,words:[["así","thus"],["también","also"],["Sodoma","Sodom"],["y","and"],["Gomorra,","Gomorrah,"],["y","and"],["las","the"],["ciudades","cities"],["circunvecinas,","regions,"],["las","the"],["cuales","which"],["de","of"],["la","the"],["misma","same"],["manera","manner"],["que","that"],["aquellos,","those,"],["habiendo","having"],["fornicado","fornicated"],["y","and"],["seguido","followed"],["vicios","vices"],["contra","against"],["la","the"],["naturaleza,","nature,"],["fueron","they-were"],["puestas","sets"],["como","as"],["ejemplo","example"],["al","to-the"],["sufrir","suffer"],["el","the"],["juicio","judgment"],["del","of-the"],["fuego","fire"],["eterno.","eternal."]]},
  {num:8,words:[["De","of"],["la","the"],["misma","same"],["manera","manner"],["también","also"],["estos","these"],["soñadores","dreamer"],["mancillan","they-defile"],["su","his"],["carne,","flesh,"],["y","and"],["menosprecian","dominion"],["la","the"],["autoridad,","authority,"],["y","and"],["vituperan","evil"],["las","the"],["potestades","principalities"],["superiores.","of."]]},
  {num:9,words:[["Pero","but"],["cuando","when"],["el","the"],["arcángel","archangel"],["Miguel","Michael"],["argumentaba","argued"],["con","with"],["el","the"],["diablo,","devil,"],["disputando","disputing"],["con","with"],["él","he"],["por","for"],["el","the"],["cuerpo","body"],["de","of"],["Moisés,","Moses,"],["no","not"],["se","himself"],["atrevió","not"],["a","to"],["pronunciar","against"],["juicio","judgment"],["de","of"],["maldición","curse"],["contra","against"],["él,","he,"],["sino que","but"],["dijo:","said:"],["El","the"],["Señor","Lord"],["te","you"],["reprenda.","may-reprimand."]]},
  {num:10,words:[["Pero","but"],["estos","these"],["maldicen","speak"],["las","the"],["cosas","things"],["que","that"],["no","not"],["conocen;","they-know;"],["y","and"],["en","in"],["las","the"],["cosas","things"],["que","that"],["por","for"],["naturaleza","nature"],["conocen,","they-know,"],["como","as"],["animales","animals"],["irracionales,","things,"],["se","themselves"],["corrompen.","themselves."]]},
  {num:11,words:[["¡Ay","wo"],["de","of"],["ellos!,","they!,"],["porque","because"],["han","they-have"],["seguido","followed"],["el","the"],["camino","way"],["de","of"],["Caín,","Cain,"],["y","and"],["se","themselves"],["lanzaron","ran"],["por","for"],["lucro","gain"],["en","in"],["el","the"],["error","error"],["de","of"],["Balaam,","Balaam,"],["y","and"],["perecieron","they-perished"],["en","in"],["la","the"],["rebelión","rebellion"],["de","of"],["Coré.","korah."]]},
  {num:12,words:[["Estos","these"],["son","are"],["manchas","spots"],["en","in"],["vuestros","your"],["convites","your"],["fraternales","feasts"],["cuando","when"],["festejan","they-charity"],["juntamente","together"],["con","with"],["vosotros,","you,"],["apacentándose","feast"],["a","to"],["sí","yes"],["mismos","selves"],["sin","without"],["temor","fear"],["alguno;","some;"],["nubes","clouds"],["sin","without"],["agua,","water,"],["las","the"],["cuales","which"],["son","they-are"],["llevadas","carried"],["de","of"],["acá","here"],["para","for"],["allá","there"],["por","by"],["los","the"],["vientos;","winds;"],["árboles","trees"],["marchitos","little-his"],["como","as"],["en","in"],["otoño,","twice,"],["sin","without"],["fruto,","fruit,"],["dos","two"],["veces","times"],["muertos","dead"],["y","and"],["desarraigados;","cut;"]]},
  {num:13,words:[["fieras","beasts"],["ondas","waves"],["del","of-the"],["mar,","sea,"],["que","that"],["espuman","foaming"],["sus","their"],["mismas","same"],["vergüenzas;","shames;"],["estrellas","stars"],["errantes,","wandering,"],["para","for"],["las","the"],["cuales","which"],["está","is"],["reservada","reserved"],["eternamente","ever"],["la","the"],["oscuridad","darkness"],["de","of"],["las","the"],["tinieblas.","darkness."]]},
  {num:14,words:[["De", "of"], ["estos", "these"], ["también", "also"], ["profetizó", "prophesied"], ["Enoc,","Enoch,"], ["séptimo", "seventh"], ["desde", "from"], ["Adán,", "Adam,"], ["diciendo:", "saying:"], ["He aquí,","behold,"], ["el", "the"], ["Señor", "Lord"], ["viene", "comes"], ["con", "with"], ["sus","his"], ["muchos", "many"], ["millares", "thousands"], ["de", "of"], ["santos,", "saints,"]]},
  {num:15,words:[["para","for"],["hacer","do"],["juicio","judgment"],["contra","against"],["todos,","all,"],["y","and"],["para","for"],["reprender","to"],["a","to"],["todos","all"],["los","the"],["impíos","ungodly"],["de","of"],["entre","among"],["ellos","they"],["tocante","concerning"],["a","to"],["todas","all"],["sus","their"],["obras","works"],["de","of"],["impiedad","of"],["que","that"],["han","they-have"],["hecho","done/made"],["impíamente,","wickedly,"],["y","and"],["tocante","concerning"],["a","to"],["todas","all"],["las","the"],["cosas","things"],["duras","hard"],["que","that"],["los","the"],["pecadores","sinners"],["impíos","ungodly"],["han","they-have"],["hablado","spoken"],["contra","against"],["él.","he."]]},
  {num:16,words:[["Estos","these"],["son","are"],["murmuradores,","murmurers,"],["quejumbrosos,","complainers,"],["que","that"],["andan","they-walk"],["según","according-to"],["sus","their"],["propios","own"],["deseos,","desires,"],["cuya","whose"],["boca","mouth"],["habla","speaks"],["con","with"],["arrogancia,","arrogance,"],["adulando","having"],["a","to"],["las","the"],["personas","persons"],["para","for"],["sacar","bring"],["provecho.","profit."]]},
  {num:17,words:[["Pero","but"],["vosotros,","you,"],["amados,","beloved,"],["tened","you-good"],["memoria","remembrance"],["de","of"],["las","the"],["palabras","words"],["que","that"],["antes","before"],["fueron","they-were"],["dichas","thiss"],["por","for"],["los","the"],["apóstoles","apostles"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo,","Jesus-Christ,"]]},
  {num:18,words:[["los","the"],["que","that"],["os","you"],["decían:","said:"],["En","in"],["los","the"],["postreros","lasts"],["tiempos","times"],["habrá","there-shall-be"],["burladores","time"],["que","that"],["andarán","they-will-walk"],["según","according-to"],["sus","their"],["malvados","wicked"],["deseos.","desires."]]},
  {num:19,words:[["Estos","these"],["son","are"],["los","the"],["que","that"],["causan","they-cause"],["divisiones;","divisions;"],["los","the"],["sensuales,","sensual,"],["que","that"],["no","not"],["tienen","they-have"],["al","to-the"],["Espíritu.","Spirit."]]},
  {num:20,words:[["Pero","but"],["vosotros,","you,"],["oh","oh"],["amados,","beloved,"],["edificándoos","building-you"],["sobre","upon"],["vuestra","your"],["santísima","most"],["fe,","faith,"],["orando","praying"],["en","in"],["el","the"],["Espíritu","Spirit"],["Santo,","holy,"]]},
  {num:21,words:[["conservaos","keep"],["en","in"],["el","the"],["amor","love"],["de","of"],["Dios,","God,"],["esperando","waiting"],["la","the"],["misericordia","mercy"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo,","Jesus-Christ,"],["para","for"],["vida","life"],["eterna.","eternal."]]},
  {num:22,words:[["Y","and"],["tened","you-good"],["compasión","compassion"],["de","of"],["los","the"],["que","that"],["dudan.","they-difference."]]},
  {num:23,words:[["Pero","but"],["haced","you-do"],["salvos","except"],["a","to"],["otros","others"],["por","by"],["temor,","fear,"],["arrebatándolos","snatching-them"],["del","of-the"],["fuego;","fire;"],["aborreciendo","hating"],["aun","even"],["la","the"],["ropa","garment"],["que","that"],["se","itself"],["ha","has"],["contaminado","defiled"],["por","by"],["su","his"],["carne.","flesh."]]},
  {num:24,words:[["A","to"],["aquel,","that,"],["pues,","for,"],["que","that"],["es","is"],["poderoso","mighty"],["para","for"],["guardaros","to-keep-you"],["sin","without"],["caída","fall"],["y","and"],["presentaros","to-present-you"],["irreprensibles","of"],["delante","before"],["de","of"],["su","his"],["gloria","glory"],["con","with"],["gran","great"],["alegría,","joy,"]]},
  {num:25,words:[["al","to-the"],["único","only"],["y","and"],["sabio","wise"],["Dios,","God,"],["nuestro","our"],["Salvador,","Savior,"],["sean","they-let-be"],["la","the"],["gloria","glory"],["y","and"],["la","the"],["majestad,","majesty,"],["el","the"],["dominio","dominion"],["y","and"],["la","the"],["potestad,","power,"],["ahora","now"],["y","and"],["por","for"],["todos","all"],["los","the"],["siglos.","Amen."],["Amén.","Amen."]]},
];
renderVerseSet(v1, 'jud-ch1-verses');

})();
