(function() {
var v1 = [
  {num:1,words:[["Profecía", "prophecy"], ["de", "of"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["contra", "against"], ["Israel,", "Israel,"], ["por medio de","by means of"], ["Malaquías:","Malachi:"]]},
  {num:2,words:[["Yo", "I"], ["os", "you"], ["he", "I-have"], ["amado,", "beloved,"], ["dice", "says"], ["Jehová.", "jehovah."], ["Pero", "but"], ["dijisteis:","you:"], ["¿En", "in"], ["qué", "what"], ["nos", "us"], ["has","you-have"], ["amado?", "beloved?"], ["¿No", "not"], ["era", "was"], ["Esaú","Esau"], ["hermano", "brother"], ["de", "of"], ["Jacob?,", "Jacob?,"], ["dice", "says"], ["Jehová;", "jehovah;"], ["sin embargo,","nevertheless,"], ["amé", "i"], ["a", "to"], ["Jacob,", "Jacob,"]]},
  {num:3,words:[["y","and"],["a","to"],["Esaú","Esau"],["aborrecí,","I-hated,"],["y","and"],["convertí","I-laid"],["sus","his"],["montes","mountains"],["en","in"],["desolación","desolation"],["y","and"],["di","I-give/I-gave"],["su","his"],["heredad","heritage"],["a","to"],["los","the"],["chacales","dragons"],["del","of-the"],["desierto.","wilderness."]]},
  {num:4,words:[["Aunque","although"],["Edom","Edom"],["diga:","may-say:"],["Hemos","we-have"],["sido","been"],["devastados,","devastate,"],["pero","but"],["volveremos","we-will-return"],["a","to"],["edificar","build"],["lo","it/him"],["arruinado;","desolate;"],["así","thus"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos:","armies:"],["Ellos","they"],["edificarán,","will-build,"],["pero","but"],["yo","I"],["destruiré;","will-destroy;"],["y","and"],["los","the"],["llamarán","call"],["territorio","coast"],["de","of"],["maldad","wickedness"],["y","and"],["pueblo","people"],["contra","against"],["el","the"],["cual","which"],["Jehová","jehovah"],["está","is"],["indignado","has"],["para","for"],["siempre.","always."]]},
  {num:5,words:[["Y","and"],["vuestros","your"],["ojos","eyes"],["lo","it/him"],["verán,","they-see,"],["y","and"],["diréis:","you-will-say:"],["Sea","be"],["Jehová","jehovah"],["engrandecido","magnified"],["más","more"],["allá","there"],["del","of-the"],["territorio","coast"],["de","of"],["Israel.","Israel."]]},
  {num:6,words:[["El","the"],["hijo","son"],["honra","honor"],["al","to-the"],["padre","father"],["y","and"],["el","the"],["siervo","servant"],["a","to"],["su","his"],["señor.","Lord."],["Si,","if,"],["pues,","for,"],["soy","I-am"],["yo","I"],["padre,","father,"],["¿dónde","where"],["está","is"],["mi","my"],["honra?","honor?"],["Y","and"],["si","if"],["soy","I-am"],["señor,","Lord,"],["¿dónde","where"],["está","is"],["mi","my"],["temor?,","fear?,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos","armies"],["a","to"],["vosotros,","you,"],["oh","oh"],["sacerdotes,","priests,"],["que","that"],["menospreciáis","you-despise"],["mi","my"],["nombre.","name."],["Y","and"],["decís:","you-say:"],["¿En","in"],["qué","what"],["hemos","we-have"],["menospreciado","despised"],["tu","your"],["nombre?","name?"]]},
  {num:7,words:[["En","in"],["que","that"],["ofrecéis","you-polluted"],["sobre","upon"],["mi","my"],["altar","altar"],["pan","bread"],["inmundo,","unclean,"],["y","and"],["decís:","you-say:"],["¿En","in"],["qué","what"],["te","you"],["hemos","we-have"],["profanado?","polluted?"],["En","in"],["que","that"],["decís:","you-say:"],["La","the"],["mesa","table"],["de","of"],["Jehová","jehovah"],["es","is"],["despreciable.","contemptible."]]},
  {num:8,words:[["Y","and"],["cuando","when"],["ofrecéis","you"],["el","the"],["animal","creeps"],["ciego","blind"],["para","for"],["el","the"],["sacrificio,","sacrifice,"],["¿no","not"],["es","is"],["malo?","evil?"],["Asimismo,","likewise,"],["cuando","when"],["ofrecéis","you-offer"],["el","the"],["cojo","lame"],["o","or"],["el","the"],["enfermo,","sick,"],["¿no","not"],["es","is"],["malo?","evil?"],["Preséntalo,","it,"],["pues,","for,"],["a","to"],["tu","your"],["gobernante.","ruler."],["¿Acaso","perhaps"],["se","himself"],["agradará","shall-please"],["de","of"],["ti,","you,"],["o","or"],["le","him"],["serás","you-will-be"],["acepto?,","I-accept?,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:9,words:[["Ahora,","now,"],["os","you"],["ruego,","beseech,"],["pues,","for,"],["implorad","you,"],["el","the"],["favor","favor"],["de","of"],["Dios","God"],["para","for"],["que","that"],["tenga","may-have"],["piedad","godliness"],["de","of"],["nosotros;","we;"],["con","with"],["esto","this"],["que","that"],["de","of"],["vuestra","your"],["mano","hand"],["ha","has"],["venido,","come,"],["¿le","your"],["seréis","you-shall-be"],["aceptos?,","I accepts?,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:10,words:[["También,","also,"],["¿quién","who"],["hay","there-is"],["entre","among"],["vosotros","you"],["que","that"],["cierre","shut"],["las","the"],["puertas","gates"],["o","or"],["alumbre","may-illuminate"],["mi","my"],["altar","altar"],["de","of"],["balde?","for?"],["Yo","I"],["no","not"],["me","me"],["complazco","i"],["en","in"],["vosotros,","you,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["ni","nor"],["de","of"],["vuestra","your"],["mano","hand"],["aceptaré","I-will-accept"],["ofrenda.","offering."]]},
  {num:11,words:[["Porque","because"],["desde","from"],["donde","where"],["el","the"],["sol","sun"],["nace","is-born"],["hasta","until"],["donde","where"],["se","himself"],["pone,","putts,"],["es","is"],["grande","great"],["mi","my"],["nombre","name"],["entre","among"],["las","the"],["naciones;","nations;"],["y","and"],["en","in"],["todo","all"],["lugar","place"],["se","himself"],["ofrece","offers"],["a","to"],["mi","my"],["nombre","name"],["incienso","incense"],["y","and"],["ofrenda","offering"],["limpia,","cleans,"],["porque","because"],["grande","great"],["es","is"],["mi","my"],["nombre","name"],["entre","among"],["las","the"],["naciones,","nations,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:12,words:[["Y","and"],["vosotros","you"],["lo","it"],["profanáis","it,"],["cuando","when"],["decís:","you-say:"],["Inmunda","unclean"],["es","is"],["la","the"],["mesa","table"],["de","of"],["Jehová","jehovah"],["y","and"],["su","his"],["fruto,","fruit,"],["su","his"],["alimento","food"],["es","is"],["despreciable.","contemptible."]]},
  {num:13,words:[["Además,","moreover,"],["habéis","you-have"],["dicho:","said:"],["He aquí,","behold,"],["¡qué","what"],["fastidio","is"],["es","is"],["esto!,","this!,"],["y","and"],["lo","it"],["olisteis","it,"],["con","with"],["desprecio,","in,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos;","armies;"],["y","and"],["trajisteis","you-was"],["lo","it"],["hurtado,","and,"],["o","or"],["cojo","lame"],["o","or"],["enfermo,","sick,"],["y","and"],["presentasteis","you"],["ofrenda.","offering."],["¿Me","me"],["será","shall-be"],["acepto","I-accept"],["eso","that"],["de","of"],["vuestra","your"],["mano?,","hand?,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:14,words:[["Y","and"],["maldito","cursed"],["el","the"],["que","that"],["engaña,","deceives,"],["el","the"],["que,","that,"],["teniendo","having"],["macho","goat"],["en","in"],["su","his"],["rebaño,","flock,"],["promete","vows,"],["y","and"],["sacrifica","sacrifices"],["lo","it/him"],["dañado","lord"],["al","to-the"],["Señor,","Lord,"],["porque","because"],["yo","I"],["soy","am"],["Gran","great"],["Rey,","king,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["y","and"],["mi","my"],["nombre","name"],["es","is"],["temible","terrible"],["entre","among"],["las","the"],["naciones.","nations."]]},
];
renderVerseSet(v1, 'mal-ch1-verses');

var v2 = [
  {num:1,words:[["Ahora", "now"], ["pues,", "for,"], ["oh", "oh"], ["sacerdotes,", "priests,"], ["para", "for"], ["vosotros", "you"], ["es", "is"], ["este", "this"], ["mandamiento:", "commandment:"]]},
  {num:2,words:[["Si","if"],["no","not"],["escucháis","you-hearken"],["y","and"],["si","if"],["no","not"],["decidís","you-will"],["de","of"],["corazón","heart"],["dar","to-give"],["gloria","glory"],["a","to"],["mi","my"],["nombre,","name,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["enviaré","I-will-send"],["maldición","curse"],["sobre","upon"],["vosotros","you"],["y","and"],["maldeciré","I-will-curse"],["vuestras","your"],["bendiciones;","blessings;"],["y","and"],["ya","already"],["las","the"],["he","I-have"],["maldecido,","cursed,"],["porque","because"],["no","not"],["os","you"],["habéis","you-have"],["decidido","lay"],["de","of"],["corazón.","heart."]]},
  {num:3,words:[["He aquí,","behold,"],["yo","I"],["reprenderé","corrupt"],["a","to"],["vuestra","your"],["descendencia,","seed,"],["y","and"],["echaré","I-cast"],["el","the"],["estiércol","dung"],["sobre","upon"],["vuestros","your"],["rostros,","faces,"],["el","the"],["estiércol","dung"],["de","of"],["los","the"],["sacrificios","sacrifices"],["de","of"],["vuestras","your"],["solemnidades;","solemnities;"],["y","and"],["seréis","you-shall-be"],["arrojados","cast"],["juntamente","together"],["con","with"],["él.","he."]]},
  {num:4,words:[["Y","and"],["sabréis","you-will-know"],["que","that"],["yo","I"],["os","you"],["envié","sent"],["este","this"],["mandamiento","commandment"],["para","for"],["que","that"],["mi","my"],["convenio","covenant"],["estuviese","were"],["con","with"],["Leví,","Levi,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:5,words:[["Mi","my"],["convenio","covenant"],["con","with"],["él","he"],["fue","was"],["de","of"],["vida","life"],["y","and"],["de","of"],["paz,","peace,"],["lo","him"],["cual","which"],["yo","I"],["le","him"],["di","I-give/I-gave"],["por","for"],["el","the"],["temor","fear"],["con","with"],["que","that"],["me","me"],["temió;","feared;"],["y","and"],["ante","before"],["mi","my"],["nombre","name"],["estuvo","stood"],["humillado.","humbled."]]},
  {num:6,words:[["La","the"],["ley","law"],["de","of"],["la","the"],["verdad","truth"],["estuvo","stood"],["en","in"],["su","his"],["boca,","mouth,"],["e","and"],["iniquidad","iniquity"],["no","not"],["fue","was"],["hallada","found"],["en","in"],["sus","his"],["labios;","lips;"],["en","in"],["paz","peace"],["y","and"],["en","in"],["rectitud","righteousness"],["anduvo","walked"],["conmigo,","with-me,"],["y","and"],["a","to"],["muchos","many"],["hizo","did"],["apartar","turn"],["de","of"],["la","the"],["iniquidad.","iniquity."]]},
  {num:7,words:[["Porque","because"],["los","the"],["labios","lips"],["del","of-the"],["sacerdote","priest"],["han","they-have"],["de","of"],["guardar","to-keep"],["el","the"],["conocimiento,","knowledge,"],["y","and"],["de","of"],["su","his"],["boca","mouth"],["buscarán","they-seek"],["la","the"],["ley,","law,"],["porque","because"],["mensajero","messenger"],["es","is"],["de","of"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:8,words:[["Mas","but"],["vosotros","you"],["os","you"],["habéis","you-have"],["apartado","separated"],["del","of-the"],["camino;","way;"],["habéis","you-have"],["hecho","done/made"],["tropezar","to-stumble"],["a","to"],["muchos","many"],["en","in"],["la","the"],["ley;","law;"],["habéis","you-have"],["corrompido","corrupted"],["el","the"],["convenio","covenant"],["de","of"],["Leví,","Levi,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:9,words:[["Por tanto,","therefore,"],["yo","I"],["también","also"],["os","you"],["he","I-have"],["hecho","made"],["viles","I-saw-them"],["y","and"],["bajos","under"],["ante","before"],["todo","all"],["el","the"],["pueblo,","people,"],["puesto que","since"],["vosotros","you"],["no","not"],["habéis","you-have"],["guardado","kept"],["mis","my"],["caminos","ways"],["y","and"],["en","in"],["la","the"],["ley","law"],["hacéis","you-do"],["acepción","respect"],["de","of"],["personas.","persons."]]},
  {num:10,words:[["¿No","not"],["tenemos","we-have"],["todos","all"],["un","a"],["mismo","same"],["padre?","father?"],["¿No","not"],["nos","us"],["ha","has"],["creado","created"],["un","a"],["mismo","same"],["Dios?","God?"],["¿Por","by"],["qué","what"],["actuamos","we-treacherously"],["pérfidamente,","every,"],["cada","each"],["uno","one"],["con","with"],["su","his"],["hermano,","brother,"],["profanando","profaning"],["el","the"],["convenio","covenant"],["de","of"],["nuestros","our"],["padres?","parents?"]]},
  {num:11,words:[["Judá","Judah"],["ha","has"],["actuado","done"],["pérfidamente,","treacherously,"],["y","and"],["en","in"],["Israel","Israel"],["y","and"],["en","in"],["Jerusalén","Jerusalem"],["se","himself"],["ha","has"],["cometido","committed"],["abominación,","abomination,"],["porque","because"],["Judá","Judah"],["ha","has"],["profanado","polluted"],["el","the"],["santuario","sanctuary"],["de","of"],["Jehová","jehovah"],["que","that"],["él","he"],["amó","loved"],["y","and"],["se","himself"],["ha","has"],["casado","has"],["con","with"],["la","the"],["hija","daughter"],["de","of"],["un","a"],["dios","God"],["extraño.","stranger."]]},
  {num:12,words:[["Jehová","jehovah"],["talará","shall-cut"],["de","of"],["las","the"],["tiendas","tents"],["de","of"],["Jacob","Jacob"],["al","to-the"],["hombre","man"],["que","that"],["haga","let-do"],["esto,","this,"],["al","to-the"],["que","that"],["vela,","a,"],["y","and"],["al","to-the"],["que","that"],["responde","answers"],["y","and"],["al","to-the"],["que","that"],["ofrece","offers"],["ofrenda","offering"],["a","to"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:13,words:[["Y","and"],["esta","this"],["otra","other"],["cosa","thing"],["hacéis:","you-do:"],["cubrís","you-cover"],["el","the"],["altar","altar"],["de","of"],["Jehová","jehovah"],["de","of"],["lágrimas,","tears,"],["de","of"],["llanto","gnashing"],["y","and"],["de","of"],["clamor;","cry;"],["así que","so"],["no","not"],["miraré","I-will-look"],["más","more"],["la","the"],["ofrenda","offering"],["para","for"],["aceptarla","it"],["con","with"],["gusto","of"],["de","of"],["vuestra","your"],["mano.","hand."]]},
  {num:14,words:[["Mas","but"],["diréis:","you-will-say:"],["¿Por","for"],["qué?","what?"],["Porque","because"],["Jehová","jehovah"],["ha","has"],["atestiguado","has"],["entre","among"],["tú","you"],["y","and"],["la","the"],["esposa","wife"],["de","of"],["tu","your"],["juventud,","youth,"],["con","with"],["la","the"],["cual","which"],["tú","you"],["has","have"],["sido","been"],["desleal,","treacherously,"],["siendo","being"],["ella","she"],["tu","your"],["compañera","companion"],["y","and"],["la","the"],["esposa","wife"],["de","of"],["tu","your"],["convenio.","covenant."]]},
  {num:15,words:[["¿Y","and"],["no","not"],["los","the"],["hizo","did"],["él","he"],["uno,","one,"],["teniendo","having"],["él","he"],["un","a"],["vestigio","residue"],["del","of-the"],["espíritu?","Spirit?"],["¿Y","and"],["por","for"],["qué","what"],["uno?","one?"],["Porque","because"],["buscaba","sought"],["una","a"],["descendencia","seed"],["para","for"],["Dios.","God."],["Cuidaos,","therefore,"],["pues,","for,"],["en","in"],["vuestro","your"],["espíritu","Spirit"],["y","and"],["con","with"],["la","the"],["esposa","wife"],["de","of"],["vuestra","your"],["juventud","youth"],["no","not"],["seáis","you-may-be"],["desleales.","youth."]]},
  {num:16,words:[["Porque","because"],["Jehová","jehovah"],["Dios","God"],["de","of"],["Israel","Israel"],["ha","has"],["dicho","said"],["que","that"],["él","he"],["aborrece","hates"],["el","the"],["repudio","putting"],["y","and"],["al","to-the"],["que","that"],["cubre","covers"],["la","the"],["violencia","violence"],["con","with"],["su","his"],["manto,","mantle,"],["dijo","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."],["Cuidaos,","heed,"],["pues,","for,"],["en","in"],["vuestro","your"],["espíritu","Spirit"],["y","and"],["no","not"],["seáis","you-may-be"],["desleales.","treacherously."]]},
  {num:17,words:[["Habéis","you-have"],["hecho","done/made"],["cansar","wearied"],["a","to"],["Jehová","jehovah"],["con","with"],["vuestras","your"],["palabras.","words."],["Y","and"],["decís:","you-say:"],["¿En","in"],["qué","what"],["le","him"],["hemos","we-have"],["cansado?","weary?"],["En","in"],["que","that"],["decís:","you-say:"],["Todo","all"],["el","the"],["que","that"],["hace","makes"],["mal","evil"],["es","is"],["bueno","good"],["ante","before"],["los","the"],["ojos","eyes"],["de","of"],["Jehová,","jehovah,"],["y","and"],["en","in"],["los","the"],["tales","such"],["se","himself"],["complace;","pleases;"],["o:","or:"],["¿Dónde","where"],["está","is"],["el","the"],["Dios","God"],["de","of"],["la","the"],["justicia?","righteousness?"]]},
];
renderVerseSet(v2, 'mal-ch2-verses');

var v3 = [
  {num:1,words:[["He aquí,","behold,"],["yo","I"],["envío","send"],["a","to"],["mi","my"],["mensajero,","messenger,"],["y","and"],["él","he"],["preparará","will-prepare"],["el","the"],["camino","way"],["delante","before"],["de","of"],["mí;","me;"],["y","and"],["vendrá","shall-come"],["súbitamente","suddenly"],["a","to"],["su","his"],["templo","temple"],["el","the"],["Señor","Lord"],["a","to"],["quien","who"],["vosotros","you"],["buscáis,","seek,"],["el","the"],["mensajero","messenger"],["del","of-the"],["convenio","covenant"],["en","in"],["quien","who"],["vosotros","you"],["os","you"],["complacéis.","you-please."],["He aquí,","behold,"],["viene,","comes,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:2,words:[["¿Y","and"],["quién","who"],["podrá","able"],["soportar","bear"],["el","the"],["día","day"],["de","of"],["su","his"],["venida?,","coming?,"],["o,","or,"],["¿quién","who"],["podrá","able"],["estar","be"],["cuando","when"],["él","he"],["se","himself"],["manifieste?","manifest?"],["Porque","because"],["él","he"],["es","is"],["como","as"],["fuego","fire"],["purificador","refiners"],["y","and"],["como","as"],["jabón","like"],["de","of"],["lavadores.","sope."]]},
  {num:3,words:[["Y","and"],["se","himself"],["sentará","sit"],["para","for"],["refinar","a"],["y","and"],["purificar","and"],["la","the"],["plata,","silver,"],["porque","because"],["purificará","shall"],["a","to"],["los","the"],["hijos","children"],["de","of"],["Leví;","Levi;"],["los","the"],["refinará","purge"],["como","as"],["a","to"],["oro","gold"],["y","and"],["como","as"],["a","to"],["plata,","silver,"],["y","and"],["ofrecerán","they-will-offer"],["a","to"],["Jehová","jehovah"],["ofrenda","offering"],["en","in"],["justicia.","righteousness."]]},
  {num:4,words:[["Y", "and"], ["será", "shall-be"], ["grata", "savour"], ["a", "to"], ["Jehová", "jehovah"], ["la", "the"], ["ofrenda", "offering"], ["de", "of"], ["Judá", "Judah"], ["y", "and"], ["de", "of"], ["Jerusalén,", "Jerusalem,"], ["como", "as"], ["en", "in"], ["los", "the"], ["días", "days"], ["pasados", "years"], ["y", "and"], ["como", "as"], ["en", "in"], ["los", "the"], ["años", "years"], ["antiguos.", "ancient."]]},
  {num:5,words:[["Y","and"],["me","me"],["acercaré","will"],["a","to"],["vosotros","you"],["para","for"],["juicio;","judgment;"],["y","and"],["seré","I will be"],["testigo","witness"],["veloz","i"],["contra","against"],["los","the"],["hechiceros,","and,"],["y","and"],["contra","against"],["los","the"],["adúlteros,","adulterers,"],["y","and"],["contra","against"],["los","the"],["que","that"],["juran","they-swear"],["falsamente","falsely"],["y","and"],["contra","against"],["los","the"],["que","that"],["oprimen","against"],["al","to-the"],["jornalero","day laborer"],["en","in"],["su","his"],["salario,","wages,"],["a","to"],["la","the"],["viuda","widow"],["y","and"],["al","to-the"],["huérfano,","fatherless,"],["y","and"],["contra","against"],["los","the"],["que","that"],["apartan","they-turn"],["al","to-the"],["extranjero","sojourns"],["de","of"],["su","his"],["derecho","right"],["y","and"],["sin","without"],["tener","have"],["temor","fear"],["de","of"],["mí,","me,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:6,words:[["Porque","because"],["yo","I"],["soy","am"],["Jehová","jehovah"],["y","and"],["no","not"],["cambio;","I-change;"],["por","for"],["esto","this"],["vosotros,","you,"],["hijos","children"],["de","of"],["Jacob,","Jacob,"],["no","not"],["habéis","you-have"],["sido","been"],["consumidos.","consumed."]]},
  {num:7,words:[["Desde", "from"], ["los", "the"], ["días", "days"], ["de", "of"], ["vuestros", "your"], ["padres", "parents"], ["os", "you"], ["habéis", "you-have"], ["apartado", "separated"], ["de", "of"], ["mis", "my"], ["estatutos,", "statutes,"], ["y", "and"], ["no", "not"], ["los", "the"], ["habéis", "you-have"], ["guardado.", "kept."], ["Volveos", "turn"], ["a", "to"], ["mí,", "me,"], ["y", "and"], ["yo", "I"], ["me", "me"], ["volveré", "return"], ["a", "to"], ["vosotros,", "you,"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos.", "armies."], ["Pero", "but"], ["dijisteis:","you:"], ["¿En", "in"], ["qué", "what"], ["hemos", "we-have"], ["de", "of"], ["volvernos?", "return-us?"]]},
  {num:8,words:[["¿Robará", "shall-their"], ["el", "the"], ["hombre", "man"], ["a", "to"], ["Dios?", "God?"], ["Pues", "for"], ["vosotros", "you"], ["me", "me"], ["habéis", "you-have"], ["robado.", "theired."], ["Y", "and"], ["dijisteis:","you:"], ["¿En", "in"], ["qué", "what"], ["te","you"], ["hemos", "we-have"], ["robado?", "theired?"], ["En", "in"], ["vuestros", "your"], ["diezmos", "tithes"], ["y", "and"], ["ofrendas.", "offerings."]]},
  {num:9,words:[["Malditos", "cursed"], ["sois","you-are"], ["con", "with"], ["maldición,", "curse,"], ["porque", "because"], ["vosotros,", "you,"], ["la", "the"], ["nación", "nation"], ["toda,", "all,"], ["me", "me"], ["habéis", "you-have"], ["robado.", "theired."]]},
  {num:10,words:[["Traed","you-bring"],["todos","all"],["los","the"],["diezmos","tithes"],["al","to-the"],["alfolí,","storehouse,"],["y","and"],["haya","let-there-be"],["alimento","food"],["en","in"],["mi","my"],["casa;","house;"],["y","and"],["probadme","prove"],["ahora","now"],["en","in"],["esto,","this,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["si","if"],["no","not"],["os","you"],["abriré","will"],["las","the"],["ventanas","windows"],["de","of"],["los","the"],["cielos","heavens"],["y","and"],["derramaré","I-pour"],["sobre","upon"],["vosotros","you"],["bendición","blessing"],["hasta que","until"],["sobreabunde.","it."]]},
  {num:11,words:[["Reprenderé","and"],["también","also"],["por","for"],["vosotros","you"],["al","to-the"],["devorador,","your,"],["y","and"],["no","not"],["os","you"],["destruirá","destroy"],["el","the"],["fruto","fruit"],["de","of"],["la","the"],["tierra,","land,"],["ni","nor"],["vuestra","your"],["vid","vine"],["en","in"],["el","the"],["campo","field"],["será","shall-be"],["estéril,","barren,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:12,words:[["Y","and"],["todas","all"],["las","the"],["naciones","nations"],["os","you"],["llamarán","call"],["bienaventurados,","blessed,"],["porque","because"],["seréis","you-shall-be"],["tierra","land"],["deseable,","desirable,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:13,words:[["Vuestras","your"],["palabras","words"],["contra","against"],["mí","me"],["han","they-have"],["sido","been"],["duras,","hard,"],["dice","says"],["Jehová.","jehovah."],["Y","and"],["dijisteis:","you:"],["¿Qué","what"],["hemos","we-have"],["hablado","spoken"],["contra","against"],["ti?","you?"]]},
  {num:14,words:[["Habéis","you-have"],["dicho:","said:"],["Por","for"],["demás","rest"],["es","is"],["servir","serve"],["a","to"],["Dios.","God."],["Y,","and,"],["¿qué","what"],["aprovecha","is"],["que","that"],["guardemos","we"],["su","his"],["ley","law"],["y","and"],["que","that"],["andemos","we-may-walk"],["afligidos","afflicted"],["delante","before"],["de","of"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos?","armies?"]]},
  {num:15,words:[["Decimos,","we,"],["pues,","for,"],["ahora:","now:"],["Bienaventurados","blessed"],["los","the"],["soberbios;","proud;"],["sí,","yes,"],["los","the"],["que","that"],["hacen","they-do"],["lo","it/him"],["malo","evil"],["son","they-are"],["prosperados;","prospered;"],["sí,","yes,"],["tientan","they-tempt"],["a","to"],["Dios","God"],["y","and"],["escapan.","they-escape."]]},
  {num:16,words:[["Entonces","then"],["los","the"],["que","that"],["temían","they-feared"],["a","to"],["Jehová","jehovah"],["hablaron,","they-spoke,"],["cada","each"],["uno","one"],["a","to"],["su","his"],["compañero;","companion;"],["y","and"],["Jehová","jehovah"],["escuchó","hearkened"],["y","and"],["oyó,","heard,"],["y","and"],["fue","was"],["escrito","written"],["un","a"],["libro","book"],["de","of"],["memorias","remembrances"],["delante","before"],["de","of"],["él","he"],["para","for"],["los","the"],["que","that"],["temen","they-fear"],["a","to"],["Jehová","jehovah"],["y","and"],["para","for"],["los","the"],["que","that"],["piensan","they-think"],["en","in"],["su","his"],["nombre.","name."]]},
  {num:17,words:[["Y","and"],["serán","they-shall-be"],["especial","special"],["tesoro","treasure"],["para","for"],["mí,","me,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["en","in"],["el","the"],["día","day"],["en","in"],["que","that"],["yo","I"],["integre","may-integrate"],["mis","my"],["joyas;","jewels;"],["y","and"],["los","the"],["perdonaré,","forgive,"],["como","as"],["el","the"],["hombre","man"],["que","that"],["perdona","forgive"],["a","to"],["su","his"],["hijo","son"],["que","that"],["le","him"],["sirve.","nothing."]]},
  {num:18,words:[["Entonces","then"],["os","you"],["volveréis","return"],["y","and"],["discerniréis","you-shall-discern"],["la","the"],["diferencia","between"],["que","that"],["hay","there-is"],["entre","among"],["el","the"],["justo","righteous"],["y","and"],["el","the"],["malo,","evil,"],["entre","among"],["el","the"],["que","that"],["sirve","nothing"],["a","to"],["Dios","God"],["y","and"],["el","the"],["que","that"],["no","not"],["le","him"],["sirve.","nothing."]]},
];
renderVerseSet(v3, 'mal-ch3-verses');

var v4 = [
  {num:1,words:[["Porque","because"],["he aquí,","behold,"],["viene","comes"],["el","the"],["día","day"],["ardiente","fiery"],["como","as"],["un","a"],["horno,","furnace,"],["y","and"],["todos","all"],["los","the"],["soberbios","proud"],["y","and"],["todos","all"],["los","the"],["que","that"],["hacen","they-do"],["maldad","wickedness"],["serán","they-shall-be"],["estopa;","stubble;"],["y","and"],["aquel","that"],["día","day"],["que","that"],["vendrá","shall-come"],["los","the"],["abrasará,","will-burn,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["y","and"],["no","not"],["les","them"],["dejará","will-leave"],["ni","nor"],["raíz","root"],["ni","nor"],["rama.","branch."]]},
  {num:2,words:[["Mas","but"],["para","for"],["vosotros,","you,"],["los","the"],["que","that"],["teméis","you-fear"],["mi","my"],["nombre,","name,"],["nacerá","shall"],["el","the"],["Sol","sun"],["de","of"],["justicia","righteousness"],["y","and"],["en","in"],["sus","his"],["alas","wings"],["traerá","will-bring"],["sanidad;","of;"],["y","and"],["saldréis","you-go"],["y","and"],["saltaréis","up"],["como","as"],["terneros","calves"],["del","of-the"],["establo.","stall."]]},
  {num:3,words:[["Y","and"],["hollaréis","you"],["a","to"],["los","the"],["malos,","spirits,"],["porque","because"],["serán","they-shall-be"],["ceniza","ashes"],["bajo","under"],["las","the"],["plantas","feet"],["de","of"],["vuestros","your"],["pies","feet"],["en","in"],["el","the"],["día","day"],["en","in"],["que","that"],["yo","I"],["actúe,","shall,"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos.","armies."]]},
  {num:4,words:[["Acordaos","remember"],["de","of"],["la","the"],["ley","law"],["de","of"],["Moisés,","Moses,"],["mi","my"],["siervo,","servant,"],["a","to"],["quien","who"],["encargué","I-ordered"],["en","in"],["Horeb","Horeb"],["estatutos","statutes"],["y","and"],["decretos","decrees"],["para","for"],["todo","all"],["Israel.","Israel."]]},
  {num:5,words:[["He aquí,","behold,"], ["yo", "I"], ["os", "you"], ["envío", "send"], ["a", "to"], ["Elías", "Elijah"], ["el", "the"], ["Profeta", "prophet"], ["antes", "before"], ["que", "that"], ["venga", "let-come"], ["el", "the"], ["día", "day"], ["de", "of"], ["Jehová,", "jehovah,"], ["grande", "great"], ["y", "and"], ["terrible.", "awful."]]},
  {num:6,words:[["Él","he"],["hará","shall-make"],["volver","to-return"],["el","the"],["corazón","heart"],["de","of"],["los","the"],["padres","parents"],["hacia","toward"],["los","the"],["hijos,","children,"],["y","and"],["el","the"],["corazón","heart"],["de","of"],["los","the"],["hijos","children"],["hacia","toward"],["los","the"],["padres,","parents,"],["no","not"],["sea","be"],["que","that"],["yo","I"],["venga","let-come"],["y","and"],["hiera","strike"],["la","the"],["tierra","earth"],["con","with"],["maldición.","curse."]]},
];
renderVerseSet(v4, 'mal-ch4-verses');

})();
