(function() {
var v1 = [
  {num:1,words:[["La","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["que","that"],["vino","came"],["a","to"],["Miqueas","Micah"],["de","of"],["Moreset","the"],["en","in"],["los","the"],["días","days"],["de","of"],["Jotam,","Jotham,"],["de","of"],["Acaz","Ahaz"],["y","and"],["de","of"],["Ezequías,","Hezekiah,"],["reyes","kings"],["de","of"],["Judá;","Judah;"],["lo","it/him"],["que","that"],["vio","saw"],["sobre","upon"],["Samaria","Samaria"],["y","and"],["Jerusalén.","Jerusalem."]]},
  {num:2,words:[["Oíd,","you-hear,"],["pueblos","peoples"],["todos;","all;"],["atended,","people,"],["oh","oh"],["tierra,","earth,"],["y","and"],["todo","all"],["lo","it/him"],["que","that"],["en","in"],["ella","she"],["hay;","there-is;"],["y","and"],["Jehová","jehovah"],["el","the"],["Señor,","Lord,"],["el","the"],["Señor","Lord"],["desde","from"],["su","his"],["santo","holy"],["templo,","temple,"],["sea","be"],["testigo","witness"],["contra","against"],["vosotros.","you."]]},
  {num:3,words:[["Porque","because"],["he aquí,","behold,"],["Jehová","jehovah"],["sale","goes"],["de","of"],["su","his"],["lugar,","place,"],["y","and"],["descenderá","down"],["y","and"],["caminará","will-walk"],["sobre","upon"],["las","the"],["alturas","heights"],["de","of"],["la","the"],["tierra.","earth."]]},
  {num:4,words:[["Y","and"],["debajo","beneath"],["de","of"],["él","he"],["se","themselves"],["derretirán","they-will-melt"],["los","the"],["montes,","mountains,"],["y","and"],["los","the"],["valles","valleys"],["se","themselves"],["hendirán","cleft"],["como","as"],["la","the"],["cera","wax"],["ante","before"],["el","the"],["fuego,","fire,"],["como","as"],["las","the"],["aguas","waters"],["que","that"],["corren","they-run"],["por","for"],["un","a"],["precipicio.","place."]]},
  {num:5,words:[["Todo","all"],["esto","this"],["por","for"],["la","the"],["rebelión","rebellion"],["de","of"],["Jacob","Jacob"],["y","and"],["por","for"],["los","the"],["pecados","sins"],["de","of"],["la","the"],["casa","house"],["de","of"],["Israel.","Israel."],["¿Cuál","which"],["es","is"],["la","the"],["rebelión","rebellion"],["de","of"],["Jacob?","Jacob?"],["¿No","not"],["es","is"],["Samaria?","Samaria?"],["¿Y","and"],["cuáles","which"],["son","they-are"],["los","the"],["lugares","places"],["altos","high"],["de","of"],["Judá?","Judah?"],["¿No","not"],["es","is"],["Jerusalén?","Jerusalem?"]]},
  {num:6,words:[["Haré,","I will make,"],["pues,","for,"],["de","of"],["Samaria","Samaria"],["un","a"],["montón","heap"],["de","of"],["ruinas,","waste,"],["lugares","places"],["para","for"],["plantar","to-plant"],["viñas;","vineyards;"],["y","and"],["derramaré","I-pour"],["sus","his"],["piedras","stones"],["por","for"],["el","the"],["valle","valley"],["y","and"],["descubriré","I-shall-to"],["sus","his"],["cimientos.","foundations."]]},
  {num:7,words:[["Y","and"],["todas","all"],["sus","his"],["estatuas","groves"],["serán","they-shall-be"],["despedazadas,","beaten,"],["y","and"],["todas","all"],["sus","his"],["pagas","pay"],["serán","they-shall-be"],["quemadas","burned"],["en","in"],["el","the"],["fuego,","fire,"],["y","and"],["asolaré","I-will-destroy"],["todos","all"],["sus","his"],["ídolos,","idols,"],["porque","because"],["de","of"],["paga","pays"],["de","of"],["rameras","harlots"],["las","the"],["juntó,","gathered,"],["y","and"],["a","to"],["paga","pays"],["de","of"],["rameras","harlots"],["volverán.","they-will-return."]]},
  {num:8,words:[["Por tanto,","therefore,"],["lamentaré,","I-wail,"],["y","and"],["aullaré,","I-howl,"],["y","and"],["andaré","I-will-walk"],["despojado","stripped"],["y","and"],["desnudo;","naked;"],["haré","I will make"],["aullido","howl"],["como","as"],["de","of"],["chacales","dragons"],["y","and"],["lamento","and"],["como","as"],["de","of"],["avestruces.","owls."]]},
  {num:9,words:[["Porque","because"],["su","her"],["llaga","pronounce"],["es","is"],["incurable,","incurable,"],["pues","for"],["llegó","came"],["hasta","until"],["Judá;","Judah;"],["llegó","came"],["hasta","until"],["la","the"],["puerta","gate"],["de","of"],["mi","my"],["pueblo,","people,"],["hasta","until"],["Jerusalén.","Jerusalem."]]},
  {num:10,words:[["No","not"],["lo","it"],["digáis","you-may-say"],["en","in"],["Gat","Gath"],["ni","nor"],["tampoco","neither"],["lloréis;","you-may-weep;"],["revuélcate","roll"],["en","in"],["el","the"],["polvo","dust"],["de","of"],["Bet-le-afra.","dust."]]},
  {num:11,words:[["Pásate","passes-you"],["desnuda","naked"],["y","and"],["con","with"],["vergüenza,","shame,"],["oh","oh"],["moradora","inhabitant"],["de","of"],["Safir;","Saphir;"],["la","the"],["moradora","inhabitant"],["de","of"],["Zaanán","Zaanan"],["no","not"],["salió;","departed;"],["el","the"],["llanto","gnashing"],["de","of"],["Bet-esel","Beth-ezel"],["quitará","fat"],["de","of"],["vosotros","you"],["su","his"],["apoyo.","the."]]},
  {num:12,words:[["Porque", "because"], ["la", "the"], ["moradora", "inhabitant"], ["de", "of"], ["Marot", "maroth"], ["anheló", "desire"], ["intensamente", "carefully"], ["el", "the"], ["bien,", "well,"], ["por cuanto","because"], ["el", "the"], ["mal", "evil"], ["descendió", "descended"], ["de", "of"], ["Jehová", "jehovah"], ["hasta", "until"], ["la", "the"], ["puerta", "gate"], ["de", "of"], ["Jerusalén.", "Jerusalem."]]},
  {num:13,words:[["Unce","o"],["al","to-the"],["carro","cart"],["los","the"],["corceles,","bind,"],["oh","oh"],["moradora","inhabitant"],["de","of"],["Laquis;","Lachish;"],["ella","she"],["fue","was"],["principio","beginning"],["de","of"],["pecado","sin"],["para","for"],["la","the"],["hija","daughter"],["de","of"],["Sion,","Zion,"],["porque","because"],["en","in"],["ti","you"],["se","themselves"],["hallaron","found"],["las","the"],["rebeliones","rebellions"],["de","of"],["Israel.","Israel."]]},
  {num:14,words:[["Por tanto,","therefore,"],["tú","you"],["darás","will-give"],["presentes","you-may-present"],["de","of"],["despedida","farewell"],["a","to"],["Moreset-gat;","Moresheth-gath;"],["las","the"],["casas","houses"],["de","of"],["Aczib","Achzib"],["serán","they-shall-be"],["un","a"],["engaño","guile"],["para","for"],["los","the"],["reyes","kings"],["de","of"],["Israel.","Israel."]]},
  {num:15,words:[["Aún","yet"], ["te","you"], ["traeré", "bring"], ["heredero,", "heir,"], ["oh", "oh"], ["moradora", "inhabitant"], ["de", "of"], ["Maresa;","Mareshah;"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["Israel", "Israel"], ["vendrá", "shall-come"], ["hasta", "until"], ["Adulam.","Adullam."]]},
  {num:16,words:[["Rápate","make"],["y","and"],["córtate","little-you"],["el","the"],["cabello","hair"],["por","for"],["los","the"],["hijos","children"],["de","of"],["tus","your"],["delicias;","delights;"],["ensancha","baldness"],["tu","your"],["calva","bald"],["como","as"],["águila,","eagle,"],["porque","because"],["fueron","they-were"],["llevados","carried"],["cautivos","captives"],["de","of"],["ti.","you."]]},
];
renderVerseSet(v1, 'mic-ch1-verses');

var v2 = [
  {num:1,words:[["¡Ay","wo"],["de","of"],["los","the"],["que","that"],["en","in"],["sus","their"],["camas","beds"],["traman","they-plot"],["iniquidad","iniquity"],["y","and"],["maquinan","they-plot"],["el","the"],["mal,","evil,"],["y","and"],["cuando","when"],["llega","arrives"],["la","the"],["mañana","morning"],["lo","it"],["ponen","they-put"],["por","for"],["obra,","work,"],["porque","because"],["tienen","they-have"],["en","in"],["su","their"],["mano","hand"],["el","the"],["poder!","power!"]]},
  {num:2,words:[["Y","and"],["codician","they-covet"],["los","the"],["campos","fields"],["y","and"],["los","the"],["roban;","they-steal;"],["y","and"],["casas,","houses,"],["y","and"],["las","the"],["quitan;","take;"],["así","thus"],["oprimen","they-oppress"],["al","to-the"],["hombre","man"],["y","and"],["a","to"],["su","his"],["casa,","house,"],["al","to-the"],["hombre","man"],["y","and"],["a","to"],["su","his"],["heredad.","heritage."]]},
  {num:3,words:[["Por tanto,","therefore,"],["así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["He aquí,","behold,"],["yo","I"],["tramo","of"],["contra","against"],["esta","this"],["familia","family"],["un","a"],["mal,","evil,"],["del","of-the"],["cual","which"],["no","not"],["sacaréis","you-shall-bring"],["vuestros","your"],["cuellos","necks"],["ni","nor"],["andaréis","you-will-walk"],["erguidos,","go,"],["porque","because"],["el","the"],["tiempo","time"],["será","shall-be"],["malo.","evil."]]},
  {num:4,words:[["En","in"],["aquel","that"],["día","day"],["se","itself"],["levantará","raise"],["contra","against"],["vosotros","you"],["un","a"],["refrán,","proverb,"],["y","and"],["se","itself"],["lamentará","will-regret"],["con","with"],["triste","my"],["lamentación,","lamentation,"],["diciendo:","saying:"],["Del","of-the"],["todo","all"],["fuimos","went"],["destruidos;","destroyed;"],["él","he"],["ha","has"],["cambiado","changed"],["la","the"],["heredad","inheritance"],["de","of"],["mi","my"],["pueblo.","people."],["¡Cómo","how"],["nos","us"],["quitó","removed"],["nuestros","our"],["campos!","fields!"],["Los","the"],["repartió","divided"],["a","to"],["otros.","others."]]},
  {num:5,words:[["Por tanto,","therefore,"],["no","not"],["tendrás","you-will-have"],["quien","who"],["reparta","may-distribute"],["heredades","inheritances"],["a","to"],["suerte","lot"],["en","in"],["la","the"],["congregación","congregation"],["de","of"],["Jehová.","jehovah."]]},
  {num:6,words:[["No","not"],["profeticéis,","prophesies,"],["dicen","they-say"],["a","to"],["los","the"],["que","that"],["profetizan;","prophesy;"],["no","not"],["les","them"],["profeticen,","they-may-prophesy,"],["porque","because"],["no","not"],["van","they-go"],["a","to"],["avergonzarse.","shame-himself."]]},
  {num:7,words:[["Tú","you"],["que","that"],["te","you"],["dices","you-say"],["casa","house"],["de","of"],["Jacob,","Jacob,"],["¿se","himself"],["ha","has"],["reducido","reduced"],["el","the"],["espíritu","Spirit"],["de","of"],["Jehová?","jehovah?"],["¿Son","they-are"],["estas","these"],["sus","his"],["obras?","works?"],["¿No","not"],["hacen","they-do"],["bien","well"],["mis","my"],["palabras","words"],["al","to-the"],["que","that"],["camina","walks"],["rectamente?","uprightly?"]]},
  {num:8,words:[["El","the"],["que","that"],["ayer","yesterday"],["era","was"],["mi","my"],["pueblo","people"],["se","myself"],["ha","has"],["levantado","risen"],["como","as"],["enemigo;","enemy;"],["a","to"],["los","the"],["que","that"],["pasan","pass"],["confiadamente,","that,"],["los","the"],["que","that"],["vuelven","they-return"],["de","of"],["la","the"],["guerra,","war,"],["les","them"],["quitáis","you-remove"],["el","the"],["manto","mantle"],["de","of"],["sobre","upon"],["la","the"],["vestimenta.","war."]]},
  {num:9,words:[["A","to"],["las","the"],["mujeres","women"],["de","of"],["mi","my"],["pueblo","people"],["echasteis","you-cast"],["fuera","were"],["de","of"],["las","the"],["casas","houses"],["de","of"],["sus","his"],["delicias;","delights;"],["a","to"],["sus","his"],["niños","children"],["quitasteis","you-took"],["mi","my"],["gloria","glory"],["para","for"],["siempre.","always."]]},
  {num:10,words:[["Levantaos","arise"],["y","and"],["andad,","you-walk,"],["porque","because"],["este","this"],["no","not"],["es","is"],["lugar","place"],["de","of"],["reposo;","rest;"],["puesto que","since"],["está","is"],["contaminado,","defiled,"],["destruirá","destroy"],["con","with"],["gran","great"],["destrucción.","destruction."]]},
  {num:11,words:[["Si","if"],["alguno","some"],["anda","walks"],["con","with"],["espíritu","Spirit"],["falso","false"],["y","and"],["miente,","may-mention,"],["diciendo:","saying:"],["Yo","I"],["te","you"],["profetizaré","shall-prophesy"],["de","of"],["vino","wine"],["y","and"],["de","of"],["sidra;","wine;"],["este","this"],["será","shall-be"],["el","the"],["profeta","prophet"],["para","for"],["este","this"],["pueblo.","people."]]},
  {num:12,words:[["De cierto","truly"],["os","you"],["reuniré","gather"],["a","to"],["todos,","all,"],["oh","oh"],["Jacob;","Jacob;"],["recogeré","I-gather"],["ciertamente","surely"],["al","to-the"],["remanente","remnant"],["de","of"],["Israel;","Israel;"],["los","the"],["pondré","I-shall-put"],["juntos","together"],["como","as"],["ovejas","sheep"],["de","of"],["Bosra,","Bozrah,"],["como","as"],["rebaño","flock"],["en","in"],["medio","midst"],["de","of"],["su","their"],["redil;","fold;"],["harán","they-shall-make"],["estruendo","noise"],["por","by"],["la","the"],["multitud","multitude"],["de","of"],["hombres.","men."]]},
  {num:13,words:[["Subirá","up"],["el","the"],["que","that"],["abre","opens"],["brechas","breaches"],["delante","before"],["de","of"],["ellos;","they;"],["abrirán","will-open"],["brecha,","breach,"],["y","and"],["pasarán","they will pass"],["la","the"],["puerta","gate"],["y","and"],["saldrán","they-forth"],["por","by"],["ella;","she;"],["y","and"],["su","their"],["rey","king"],["pasará","will-pass"],["delante","before"],["de","of"],["ellos,","they,"],["y","and"],["a","to"],["la","the"],["cabeza","head"],["de","of"],["ellos","they"],["Jehová.","jehovah."]]},
];
renderVerseSet(v2, 'mic-ch2-verses');

var v3 = [
  {num:1,words:[["Y","and"],["dije:","I-said:"],["Oíd","you-hear"],["ahora,","now,"],["oh","oh"],["gobernantes","rulers"],["de","of"],["Jacob","Jacob"],["y","and"],["jefes","chiefs"],["de","of"],["la","the"],["casa","house"],["de","of"],["Israel:","Israel:"],["¿No","not"],["os","you"],["corresponde","corresponds"],["a","to"],["vosotros","you"],["saber","to-know"],["lo","it"],["que","that"],["es","is"],["justo?","righteous?"]]},
  {num:2,words:[["Vosotros","you"],["que","that"],["aborrecéis","you-hate"],["lo","it/him"],["bueno","good"],["y","and"],["amáis","you-love"],["lo","it/him"],["malo,","evil,"],["que","that"],["les","them"],["quitáis","you-skin"],["su","their"],["piel","skin"],["y","and"],["su","their"],["carne","flesh"],["de","of"],["sobre","upon"],["los","the"],["huesos;","bones;"]]},
  {num:3,words:[["que","that"],["coméis","you-eat"],["asimismo","likewise"],["la","the"],["carne","flesh"],["de","of"],["mi","my"],["pueblo,","people,"],["y","and"],["les","them"],["arrancáis","you-start"],["la","the"],["piel","skin"],["de","of"],["sobre","upon"],["ellos,","they,"],["y","and"],["les","them"],["quebráis","you-break"],["los","the"],["huesos","bones"],["y","and"],["los","the"],["rompéis,","pieces,"],["como","as"],["para","for"],["el","the"],["caldero,","pot,"],["y","and"],["como","as"],["carne","flesh"],["en","in"],["la","the"],["olla.","pot."]]},
  {num:4,words:[["Entonces","then"],["clamarán","they-cry"],["a","to"],["Jehová","jehovah"],["y","and"],["no","not"],["les","them"],["responderá,","answer,"],["sino que","but"],["esconderá","will-hide"],["de","of"],["ellos","they"],["su","his"],["rostro","face"],["en","in"],["aquel","that"],["tiempo,","time,"],["por cuanto","because"],["hicieron","they-did"],["obras","works"],["malas.","evil."]]},
  {num:5,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová","jehovah"],["acerca","about"],["de","of"],["los","the"],["profetas","prophets"],["que","that"],["hacen","they-make"],["errar","err"],["a","to"],["mi","my"],["pueblo,","people,"],["que","that"],["muerden","they-bite"],["con","with"],["sus","his"],["dientes","gnashing"],["y","and"],["claman:","they-cry:"],["Paz,","peace,"],["y","and"],["al","to-the"],["que","that"],["no","not"],["les","them"],["da","gives"],["de","of"],["comer,","to-eat,"],["declaran","they-declare"],["contra","against"],["él","he"],["guerra","war"],["santa.","holy."]]},
  {num:6,words:[["Por tanto,","therefore,"],["habrá","there-shall-be"],["para","for"],["vosotros","you"],["noche","night"],["sin","without"],["visión","vision"],["y","and"],["oscuridad","darkness"],["sin","without"],["adivinación;","divination;"],["y","and"],["sobre","upon"],["los","the"],["profetas","prophets"],["se","itself"],["pondrá","pour"],["el","the"],["sol,","sun,"],["y","and"],["el","the"],["día","day"],["se","itself"],["entenebrecerá","shall"],["sobre","upon"],["ellos.","they."]]},
  {num:7,words:[["Y","and"],["serán","they-shall-be"],["avergonzados","ashamed"],["los","the"],["profetas,","prophets,"],["y","and"],["se","themselves"],["confundirán","they-will-confuse"],["los","the"],["adivinos;","wizards;"],["y","and"],["todos","all"],["ellos","they"],["se","themselves"],["cubrirán","cover"],["los","the"],["labios,","lips,"],["porque","because"],["no","not"],["hay","there-is"],["respuesta","answer"],["de","of"],["Dios.","God."]]},
  {num:8,words:[["Pero","but"],["yo","I"],["estoy","am"],["lleno","full"],["del","of-the"],["poder","power"],["mediante","through"],["el","the"],["espíritu","Spirit"],["de","of"],["Jehová,","jehovah,"],["y","and"],["de","of"],["juicio","judgment"],["y","and"],["de","of"],["fuerza,","strength,"],["para","for"],["denunciar","to-denounce"],["a","to"],["Jacob","Jacob"],["su","his"],["rebelión","rebellion"],["y","and"],["a","to"],["Israel","Israel"],["su","his"],["pecado.","sin."]]},
  {num:9,words:[["Oíd","you-hear"],["ahora","now"],["esto,","this,"],["gobernantes","rulers"],["de","of"],["la","the"],["casa","house"],["de","of"],["Jacob","Jacob"],["y","and"],["jefes","chiefs"],["de","of"],["la","the"],["casa","house"],["de","of"],["Israel,","Israel,"],["que","that"],["abomináis","you-house"],["la","the"],["justicia","righteousness"],["y","and"],["pervertís","you-abhor"],["todo","all"],["lo","it/him"],["que","that"],["es","is"],["recto,","upright,"]]},
  {num:10,words:[["que","that"],["edificáis","you-build"],["a","to"],["Sion","Zion"],["con","with"],["sangre","blood"],["y","and"],["a","to"],["Jerusalén","Jerusalem"],["con","with"],["injusticia.","unrighteousness."]]},
  {num:11,words:[["Sus","his"],["gobernantes","rulers"],["juzgan","they-judge"],["por","for"],["cohecho,","reward,"],["y","and"],["sus","his"],["sacerdotes","priests"],["enseñan","they-teach"],["por","for"],["precio,","price,"],["y","and"],["sus","his"],["profetas","prophets"],["adivinan","they-divine"],["por","for"],["dinero;","money;"],["y","and"],["se","themselves"],["apoyan","they-support"],["en","in"],["Jehová,","jehovah,"],["diciendo:","saying:"],["¿No","not"],["está","is"],["Jehová","jehovah"],["entre","among"],["nosotros?","we?"],["No","not"],["vendrá","shall-come"],["mal","evil"],["sobre","upon"],["nosotros.","we."]]},
  {num:12,words:[["Por tanto,","therefore,"],["a causa de","because of"],["vosotros","you"],["Sion","Zion"],["será","shall-be"],["arada","plowed"],["como","as"],["campo,","field,"],["y","and"],["Jerusalén","Jerusalem"],["será","shall-be"],["montones","heaps"],["de","of"],["ruinas;","waste;"],["y","and"],["el","the"],["monte","mount"],["de","of"],["la","the"],["casa,","house,"],["como","as"],["cumbres","tops"],["de","of"],["bosque.","forest."]]},
];
renderVerseSet(v3, 'mic-ch3-verses');

var v4 = [
  {num:1,words:[["Y","and"],["acontecerá","shall-come-to-pass"],["en","in"],["los","the"],["postreros","lasts"],["días","days"],["que","that"],["el","the"],["monte","mount"],["de","of"],["la","the"],["casa","house"],["de","of"],["Jehová","jehovah"],["será","shall-be"],["establecido","established"],["como","as"],["cabeza","head"],["de","of"],["los","the"],["montes,","mountains,"],["y","and"],["más","more"],["alto","high"],["que","that"],["los","the"],["collados,","hills,"],["y","and"],["correrán","they-will-run"],["a","to"],["él","he"],["los","the"],["pueblos.","peoples."]]},
  {num:2,words:[["Y","and"],["vendrán","they-will-come"],["muchas","many"],["naciones","nations"],["y","and"],["dirán:","they-will-say:"],["Venid,","you-come,"],["y","and"],["subamos","we-may-go-up"],["al","to-the"],["monte","mount"],["de","of"],["Jehová","jehovah"],["y","and"],["a","to"],["la","the"],["casa","house"],["del","of-the"],["Dios","God"],["de","of"],["Jacob;","Jacob;"],["y","and"],["nos","us"],["enseñará","teach"],["acerca","about"],["de","of"],["sus","his"],["caminos,","ways,"],["y","and"],["andaremos","we-will-walk"],["por","for"],["sus","his"],["veredas;","paths;"],["porque","because"],["de","of"],["Sion","Zion"],["saldrá","forth"],["la","the"],["ley,","law,"],["y","and"],["de","of"],["Jerusalén","Jerusalem"],["la","the"],["palabra","word"],["de","of"],["Jehová.","jehovah."]]},
  {num:3,words:[["Y","and"],["él","he"],["juzgará","will-judge"],["entre","among"],["muchos","many"],["pueblos","peoples"],["y","and"],["reprenderá","will-reprimand"],["a","to"],["naciones","nations"],["poderosas","mighty"],["hasta","until"],["muy","very"],["lejos;","far;"],["y","and"],["forjarán","they-beat"],["sus","their"],["espadas","swords"],["en","in"],["rejas","plowshares"],["de","of"],["arado","plowed"],["y","and"],["sus","their"],["lanzas","spears"],["en","in"],["hoces;","shall;"],["no","not"],["alzará","lift"],["espada","sword"],["nación","nation"],["contra","against"],["nación","nation"],["ni","nor"],["se","themselves"],["adiestrarán","they-will-train"],["más","more"],["para","for"],["la","the"],["guerra.","war."]]},
  {num:4,words:[["Y","and"],["se","himself"],["sentará","sit"],["cada","each"],["uno","one"],["debajo","beneath"],["de","of"],["su","his"],["vid","vine"],["y","and"],["debajo","beneath"],["de","of"],["su","his"],["higuera,","fig,"],["y","and"],["no","not"],["habrá","there-shall-be"],["quien","who"],["los","the"],["amedrente,","afraid,"],["porque","because"],["la","the"],["boca","mouth"],["de","of"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos","armies"],["lo","it"],["ha","has"],["hablado.","spoken."]]},
  {num:5,words:[["Todos","all"],["los","the"],["pueblos","peoples"],["andarán","they-will-walk"],["cada","each"],["uno","one"],["en","in"],["el","the"],["nombre","name"],["de","of"],["su","his"],["dios,","God,"],["y","and"],["nosotros","we"],["andaremos","will-walk"],["en","in"],["el","the"],["nombre","name"],["de","of"],["Jehová","jehovah"],["nuestro","our"],["Dios","God"],["eternamente","ever"],["y","and"],["para","for"],["siempre.","always."]]},
  {num:6,words:[["En","in"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová,","jehovah,"],["juntaré","I-gather"],["a","to"],["la","the"],["que","that"],["cojea,","limps,"],["y","and"],["recogeré","I-gather"],["a","to"],["la","the"],["desterrada","banished"],["y","and"],["a","to"],["la","the"],["que","that"],["afligí;","I-afflicted;"]]},
  {num:7,words:[["y","and"],["haré","I will make"],["de","of"],["la","the"],["que","that"],["cojea","halted"],["un","a"],["remanente,","remnant,"],["y","and"],["de","of"],["la","the"],["desterrada,","banished,"],["nación","nation"],["robusta;","robust;"],["y","and"],["Jehová","jehovah"],["reinará","will-reign"],["sobre","upon"],["ellos","they"],["en","in"],["el","the"],["monte","mount"],["Sion","Zion"],["desde","from"],["ahora","now"],["y","and"],["para","for"],["siempre.","always."]]},
  {num:8,words:[["Y", "and"], ["tú,","you,"], ["oh", "oh"], ["torre", "tower"], ["del", "of-the"], ["rebaño,", "flock,"], ["fortaleza", "castle"], ["de", "of"], ["la", "the"], ["hija", "daughter"], ["de", "of"], ["Sion,", "Zion,"], ["hasta", "until"], ["ti","you"], ["vendrá", "shall-come"], ["el", "the"], ["primer", "first"], ["señorío,", "first,"], ["el", "the"], ["reino", "kingdom"], ["vendrá", "shall-come"], ["a", "to"], ["la", "the"], ["hija", "daughter"], ["de", "of"], ["Jerusalén.", "Jerusalem."]]},
  {num:9,words:[["Ahora,", "now,"], ["¿por","for"], ["qué", "what"], ["gritas", "cry"], ["tanto?", "therefore?"], ["¿No", "not"], ["hay", "there-is"], ["rey", "king"], ["en", "in"], ["ti?","you?"], ["¿Pereció", "perished"], ["tu","your"], ["consejero?", "counselor?"], ["¿Te","you"], ["ha", "has"], ["sobrevenido", "us"], ["dolor", "pain"], ["como", "as"], ["a", "to"], ["mujer", "woman"], ["de", "of"], ["parto?", "travail?"]]},
  {num:10,words:[["Retuércete","be"],["y","and"],["gime,","moans,"],["hija","daughter"],["de","of"],["Sion,","Zion,"],["como","as"],["mujer","woman"],["que","that"],["está","is"],["de","of"],["parto,","travail,"],["porque","because"],["ahora","now"],["saldrás","you-will-leave"],["de","of"],["la","the"],["ciudad,","city,"],["y","and"],["morarás","you-shall-dwell"],["en","in"],["el","the"],["campo","field"],["y","and"],["llegarás","you-will-come"],["hasta","until"],["Babilonia;","Babylon;"],["allí","there"],["serás","you-will-be"],["librada;","delivered;"],["allí","there"],["te","you"],["redimirá","redeem"],["Jehová","jehovah"],["de","of"],["manos","hands"],["de","of"],["tus","your"],["enemigos.","enemies."]]},
  {num:11,words:[["Y","and"],["ahora","now"],["se","themselves"],["han","have"],["juntado","gathered"],["muchas","many"],["naciones","nations"],["contra","against"],["ti","you"],["y","and"],["dicen:","they-say:"],["Sea","be"],["profanada,","polluted,"],["y","and"],["contemplen","they-may-contemplate"],["nuestros","our"],["ojos","eyes"],["Sion.","Zion."]]},
  {num:12,words:[["Mas","but"],["ellos","they"],["no","not"],["conocieron","they-knew"],["los","the"],["pensamientos","thoughts"],["de","of"],["Jehová","jehovah"],["ni","nor"],["entendieron","they-understood"],["su","his"],["consejo;","counsel;"],["los","the"],["juntó,","gathered,"],["pues,","for,"],["como","as"],["gavillas","sheaves"],["en","in"],["la","the"],["era.","was."]]},
  {num:13,words:[["Levántate","arise"],["y","and"],["trilla,","o,"],["hija","daughter"],["de","of"],["Sion,","Zion,"],["porque","because"],["haré","I will make"],["tu","your"],["cuerno","horn"],["de","of"],["hierro","iron"],["y","and"],["tus","your"],["uñas","fingernails"],["de","of"],["bronce,","brass,"],["y","and"],["desmenuzarás","you-will-crumbles"],["a","to"],["muchos","many"],["pueblos;","peoples;"],["y","and"],["consagraré","I-will-consecrate"],["a","to"],["Jehová","jehovah"],["su","their"],["botín,","spoil,"],["y","and"],["sus","their"],["riquezas","riches"],["al","to-the"],["Señor","Lord"],["de","of"],["toda","all"],["la","the"],["tierra.","earth."]]},
];
renderVerseSet(v4, 'mic-ch4-verses');

var v5 = [
  {num:1,words:[["Agrúpate","now"],["ahora","now"],["en","in"],["tropas,","troops,"],["oh","oh"],["hija","daughter"],["de","of"],["tropas;","troops;"],["nos","us"],["han","have"],["sitiado;","against;"],["con","with"],["vara","rod"],["herirán","they-shall-strike"],["en","in"],["la","the"],["mejilla","cheek"],["al","to-the"],["juez","judge"],["de","of"],["Israel.","Israel."]]},
  {num:2,words:[["Mas","but"],["tú,","you,"],["Belén","Bethlehem"],["Efrata,","Ephratah,"],["pequeña","small"],["para","for"],["estar","be"],["entre","among"],["los","the"],["millares","thousands"],["de","of"],["Judá,","Judah,"],["de","of"],["ti","you"],["me","me"],["saldrá","forth"],["el","the"],["que","that"],["será","shall-be"],["gobernante","ruler"],["en","in"],["Israel;","Israel;"],["y","and"],["sus","his"],["orígenes","ruler"],["son","they-are"],["desde","from"],["tiempos","times"],["antiguos,","ancient,"],["desde","from"],["los","the"],["días","days"],["de","of"],["la","the"],["eternidad.","eternity."]]},
  {num:3,words:[["Por tanto,","therefore,"],["los","the"],["dejará","leave"],["hasta","until"],["el","the"],["tiempo","time"],["en que","that"],["dé","give"],["a","to"],["luz","light"],["la","the"],["que","that"],["ha","has"],["de","to"],["dar","give"],["a","to"],["luz;","light;"],["entonces","then"],["el","the"],["resto","remnant"],["de","of"],["sus","his"],["hermanos","brothers"],["volverá","will-return"],["a","to"],["los","the"],["hijos","children"],["de","of"],["Israel.","Israel."]]},
  {num:4,words:[["Y","and"],["él","he"],["se","himself"],["levantará","raise"],["y","and"],["apacentará","shall-feed"],["con","with"],["el","the"],["poder","power"],["de","of"],["Jehová,","jehovah,"],["con","with"],["la","the"],["grandeza","greatness"],["del","of-the"],["nombre","name"],["de","of"],["Jehová","jehovah"],["su","his"],["Dios;","God;"],["y","and"],["permanecerán,","they-will-remain,"],["porque","because"],["entonces","then"],["él","he"],["será","shall-be"],["engrandecido","magnified"],["hasta","until"],["los","the"],["confines","ends"],["de","of"],["la","the"],["tierra.","earth."]]},
  {num:5,words:[["Y","and"],["ese","that"],["hombre","man"],["será","shall-be"],["la","the"],["paz.","peace."],["Cuando","when"],["el","the"],["asirio","Assyrian"],["venga","let-come"],["a","to"],["nuestra","our"],["tierra","land"],["y","and"],["pisotee","may-trample"],["nuestros","our"],["palacios,","palaces,"],["entonces","then"],["levantaremos","we-shall-raise"],["contra","against"],["él","he"],["siete","seven"],["pastores","shepherds"],["y","and"],["ocho","eight"],["hombres","men"],["principales;","chief;"]]},
  {num:6,words:[["y","and"],["devastarán","they-will-devastate"],["la","the"],["tierra","land"],["de","of"],["Asiria","Assyria"],["a","to"],["espada,","sword,"],["y","and"],["la","the"],["tierra","land"],["de","of"],["Nimrod","Nimrod"],["en","in"],["sus","our"],["entradas;","entrances;"],["y","and"],["nos","us"],["librará","deliver"],["del","of-the"],["asirio","Assyrian"],["cuando","when"],["venga","let-come"],["a","to"],["nuestra","our"],["tierra","land"],["y","and"],["pise","treads"],["nuestras","our"],["fronteras.","borders."]]},
  {num:7,words:[["Y","and"],["el","the"],["remanente","remnant"],["de","of"],["Jacob","Jacob"],["será","shall-be"],["en","in"],["medio","midst"],["de","of"],["muchos","many"],["pueblos","peoples"],["como","as"],["el","the"],["rocío","dew"],["que","that"],["viene","comes"],["de","of"],["Jehová,","jehovah,"],["como","as"],["las","the"],["lluvias","rains"],["sobre","upon"],["la","the"],["hierba,","grass,"],["las","the"],["cuales","which"],["no","not"],["esperan","they-wait"],["al","to-the"],["hombre","man"],["ni","nor"],["aguardan","they-nor"],["a","to"],["los","the"],["hijos","children"],["de","of"],["los","the"],["hombres.","men."]]},
  {num:8,words:[["Asimismo,","likewise,"],["el","the"],["remanente","remnant"],["de","of"],["Jacob","Jacob"],["será","shall-be"],["entre","among"],["las","the"],["naciones,","nations,"],["en","in"],["medio","midst"],["de","of"],["muchos","many"],["pueblos,","peoples,"],["como","as"],["el","the"],["león","lion"],["entre","among"],["las","the"],["bestias","beasts"],["del","of-the"],["bosque,","forest,"],["como","as"],["el","the"],["cachorro","lion"],["del","of-the"],["león","lion"],["entre","among"],["los","the"],["rebaños","flocks"],["de","of"],["las","the"],["ovejas,","sheep,"],["el","the"],["cual","which"],["si","if"],["pasa,","passes,"],["y","and"],["pisotea","tramples"],["y","and"],["arrebata,","snatches,"],["no","not"],["hay","there-is"],["quien","who"],["escape.","escape."]]},
  {num:9,words:[["Tu","your"],["mano","hand"],["se","himself"],["alzará","lift"],["sobre","upon"],["tus","your"],["enemigos,","enemies,"],["y","and"],["todos","all"],["tus","your"],["adversarios","adversaries"],["serán","they-shall-be"],["talados.","cut."]]},
  {num:10,words:[["Y","and"],["acontecerá","shall-come-to-pass"],["en","in"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová,","jehovah,"],["que","that"],["haré","I will make"],["matar","slay"],["tus","your"],["caballos","horses"],["de","of"],["en","in"],["medio","midst"],["de","of"],["ti","you"],["y","and"],["haré","I will make"],["destruir","to-destroy"],["tus","your"],["carros.","chariots."]]},
  {num:11,words:[["Haré","I will make"],["también","also"],["destruir","to-destroy"],["las","the"],["ciudades","cities"],["de","of"],["tu","your"],["tierra,","land,"],["y","and"],["derribaré","down"],["todas","all"],["tus","your"],["fortalezas.","holds."]]},
  {num:12,words:[["Asimismo,","likewise,"],["destruiré","I-will-destroy"],["de","of"],["tu","your"],["mano","hand"],["las","the"],["hechicerías,","of,"],["y","and"],["no","not"],["se","themselves"],["hallarán","find"],["en","in"],["ti","you"],["agoreros.","soothsayers."]]},
  {num:13,words:[["Y","and"],["haré","I will make"],["destruir","to-destroy"],["tus","your"],["esculturas","sculptures"],["y","and"],["tus","your"],["imágenes","images"],["talladas","graven"],["de","of"],["en","in"],["medio","midst"],["de","of"],["ti,","you,"],["y","and"],["nunca","never"],["más","more"],["te","you"],["inclinarás","you-will-incline"],["ante","before"],["la","the"],["obra","work"],["de","of"],["tus","your"],["manos;","hands;"]]},
  {num:14,words:[["y","and"],["arrancaré","I-will-start"],["tus","your"],["imágenes","groves"],["de","of"],["Asera","groves"],["de","of"],["en","in"],["medio","midst"],["de","of"],["ti","you"],["y","and"],["destruiré","I-will-destroy"],["tus","your"],["ciudades.","cities."]]},
  {num:15,words:[["Y","and"],["con","with"],["ira","anger"],["y","and"],["con","with"],["furor","fury"],["haré","I will make"],["venganza","vengeance"],["en","in"],["las","the"],["naciones","nations"],["que","that"],["no","not"],["escucharon.","they-hearkened."]]},
];
renderVerseSet(v5, 'mic-ch5-verses');

var v6 = [
  {num:1,words:[["Oíd","you-hear"],["ahora","now"],["lo","it/him"],["que","that"],["dice","says"],["Jehová:","jehovah:"],["Levántate,","arise,"],["contiende","contends"],["con","with"],["los","the"],["montes,","mountains,"],["y","and"],["oigan","they-hear"],["los","the"],["collados","hills"],["tu","your"],["voz.","voice."]]},
  {num:2,words:[["Oíd,","you-hear,"],["montes","mountains"],["y","and"],["fuertes","strong"],["cimientos","foundations"],["de","of"],["la","the"],["tierra,","earth,"],["el","the"],["pleito","dispute"],["de","of"],["Jehová,","jehovah,"],["porque","because"],["Jehová","jehovah"],["tiene","has"],["pleito","dispute"],["con","with"],["su","his"],["pueblo","people"],["y","and"],["altercará","will"],["con","with"],["Israel.","Israel."]]},
  {num:3,words:[["Pueblo", "people"], ["mío,", "mine,"], ["¿qué", "what"], ["te","you"], ["he", "I-have"], ["hecho","done"], ["o", "or"], ["en", "in"], ["qué", "what"], ["te","you"], ["he", "I-have"], ["molestado?", "wearied?"], ["Responde","to"], ["contra", "against"], ["mí.", "me."]]},
  {num:4,words:[["Porque","because"],["yo","I"],["te","you"],["hice","I-did"],["subir","go-up"],["de","of"],["la","the"],["tierra","land"],["de","of"],["Egipto,","Egypt,"],["y","and"],["de","of"],["la","the"],["casa","house"],["de","of"],["servidumbre","bondage"],["te","you"],["redimí;","I-redeemed;"],["y","and"],["envié","I-sent"],["delante","before"],["de","of"],["ti","you"],["a","to"],["Moisés,","Moses,"],["y","and"],["a","to"],["Aarón","Aaron"],["y","and"],["a","to"],["María.","Miriam."]]},
  {num:5,words:[["Pueblo","people"],["mío,","mine,"],["acuérdate","remember"],["ahora","now"],["de","of"],["lo","him"],["que","that"],["aconsejó","king"],["Balac,","Balak,"],["rey","king"],["de","of"],["Moab,","Moab,"],["y","and"],["de","of"],["lo","him"],["que","that"],["le","him"],["respondió","answered"],["Balaam","Balaam"],["hijo","son"],["de","of"],["Beor,","Beor,"],["desde","from"],["Sitim","Gilgal"],["hasta","until"],["Gilgal,","Gilgal,"],["para que","that"],["conozcas","you-may-know"],["las","the"],["justicias","justice/righteousnesss"],["de","of"],["Jehová.","jehovah."]]},
  {num:6,words:[["¿Con","with"],["qué","what"],["me","me"],["presentaré","shall-to"],["ante","before"],["Jehová","jehovah"],["y","and"],["adoraré","I-shall-worship"],["al","to-the"],["Dios","God"],["Altísimo?","most?"],["¿Me","me"],["presentaré","shall-to"],["ante","before"],["él","he"],["con","with"],["holocaustos,","burnt offerings,"],["con","with"],["becerros","calves"],["de","of"],["un","a"],["año?","year?"]]},
  {num:7,words:[["¿Se","himself"],["agradará","shall-please"],["Jehová","jehovah"],["de","of"],["millares","thousands"],["de","of"],["carneros","rams"],["o","or"],["de","of"],["diez","ten"],["mil","thousand"],["arroyos","rivers"],["de","of"],["aceite?","oil?"],["¿Daré","I-shall-give"],["mi","my"],["primogénito","firstborn"],["por","for"],["mi","my"],["rebelión,","rebellion,"],["el","the"],["fruto","fruit"],["de","of"],["mis","my"],["entrañas","bowels"],["por","for"],["el","the"],["pecado","sin"],["de","of"],["mi","my"],["alma?","soul?"]]},
  {num:8,words:[["Oh","oh"],["hombre,","man,"],["él","he"],["te","you"],["ha","has"],["declarado","declared"],["lo","it/him"],["que","that"],["es","is"],["bueno","good"],["y","and"],["lo","it/him"],["que","that"],["pide","asks"],["Jehová","jehovah"],["de","of"],["ti:","you:"],["solamente","only"],["hacer","do"],["justicia,","righteousness,"],["y","and"],["amar","to-love"],["la","the"],["misericordia","mercy"],["y","and"],["humillarte","to-humble-you"],["para","for"],["andar","to-walk"],["con","with"],["tu","your"],["Dios.","God."]]},
  {num:9,words:[["La","the"],["voz","voice"],["de","of"],["Jehová","jehovah"],["clama","cries"],["a","to"],["la","the"],["ciudad,","city,"],["y","and"],["sabio","wise"],["es","is"],["temer","to-fear"],["tu","your"],["nombre.","name."],["Oíd","you-hear"],["la","the"],["vara,","rod,"],["y","and"],["a","to"],["quien","who"],["la","the"],["establece.","establishes."]]},
  {num:10,words:[["¿Hay","there-is"],["aún","yet"],["en","in"],["casa","house"],["del","of-the"],["impío","ungodly"],["tesoros","treasures"],["de","of"],["impiedad","of"],["y","and"],["medida","measure"],["escasa","scant"],["que","that"],["sea","be"],["detestable?","abominable?"]]},
  {num:11,words:[["¿Debo","I-must"],["considerar","to-consider"],["justas","are"],["la","the"],["balanza","balance"],["falsa","false"],["y","and"],["la","the"],["bolsa","bag"],["de","of"],["pesas","weights"],["engañosas?","weights?"]]},
  {num:12,words:[["Sus","their"],["ricos","rich"],["se","themselves"],["llenaron","filled"],["de","of"],["rapiña,","to,"],["y","and"],["sus","their"],["moradores","inhabitants"],["hablaron","they-spoke"],["mentira,","lies,"],["y","and"],["su","their"],["lengua","tongue"],["es","is"],["engañosa","deceptive"],["en","in"],["su","their"],["boca.","mouth."]]},
  {num:13,words:[["Por eso","therefore"],["yo","I"],["también","also"],["te","you"],["debilitaré","smiting"],["hiriéndote,","hurting-you,"],["asolándote","devastating-you"],["por","for"],["tus","your"],["pecados.","sins."]]},
  {num:14,words:[["Tú","you"],["comerás","will-eat"],["y","and"],["no","not"],["te","you"],["saciarás,","shalls,"],["y","and"],["tu","your"],["escasez","down"],["estará","shall-be"],["en","in"],["medio","midst"],["de","of"],["ti;","you;"],["y","and"],["tú","you"],["recogerás,","will-gather,"],["pero","but"],["no","not"],["retendrás;","you-will-retain;"],["y","and"],["lo","it/him"],["que","that"],["retengas,","you-may-retain,"],["lo","it/him"],["entregaré","will-deliver"],["yo","I"],["a","to"],["la","the"],["espada.","sword."]]},
  {num:15,words:[["Tú","you"],["sembrarás,","will-sow,"],["mas","but"],["no","not"],["segarás;","you-will-mow;"],["pisarás","you-reap"],["aceitunas,","olives,"],["mas","but"],["no","not"],["te","you"],["ungirás","anoint"],["con","with"],["el","the"],["aceite;","oil;"],["y","and"],["mosto,","corn,"],["mas","but"],["no","not"],["beberás","you-will-drink"],["el","the"],["vino.","wine."]]},
  {num:16,words:[["Porque","because"],["los","the"],["estatutos","statutes"],["de","of"],["Omri","Omri"],["se","themselves"],["han","have"],["guardado","kept"],["y","and"],["toda","all"],["obra","work"],["de","of"],["la","the"],["casa","house"],["de","of"],["Acab;","Ahab;"],["y","and"],["en","in"],["los","the"],["consejos","counsels"],["de","of"],["ellos","they"],["anduvisteis,","walked,"],["para que","that"],["yo","I"],["te","you"],["entregase","of-himself"],["a","to"],["la","the"],["desolación,","desolation,"],["y","and"],["a","to"],["tus","your"],["moradores","inhabitants"],["a","to"],["la","the"],["burla.","an."],["Llevaréis,","your,"],["por tanto,","therefore,"],["el","the"],["oprobio","reproach"],["de","of"],["mi","my"],["pueblo.","people."]]},
];
renderVerseSet(v6, 'mic-ch6-verses');

var v7 = [
  {num:1,words:[["¡Ay","wo"],["de","of"],["mí!,","me!,"],["porque","because"],["he","I-have"],["venido","come"],["a","to"],["ser","be"],["como","as"],["cuando","when"],["han","they-have"],["recogido","gathered"],["los","the"],["frutos","fruits"],["del","of-the"],["verano,","summer,"],["como","as"],["cuando","when"],["han","they-have"],["rebuscado","searched-again"],["después","after"],["de","of"],["la","the"],["vendimia","harvests"],["y","and"],["no","not"],["queda","remains"],["racimo","to"],["para","for"],["comer;","to-eat;"],["mi","my"],["alma","soul"],["deseó","desired"],["los","the"],["primeros","first"],["frutos.","fruits."]]},
  {num:2,words:[["Ha","has"],["desaparecido","disappeared"],["el","the"],["misericordioso","merciful"],["de","of"],["la","the"],["tierra,","earth,"],["y","and"],["ninguno","none"],["hay","there-is"],["recto","upright"],["entre","among"],["los","the"],["hombres;","men;"],["todos","all"],["acechan","lie"],["para","for"],["derramar","shedding"],["sangre;","blood;"],["cada","each"],["cual","which"],["tiende","man"],["red","net"],["a","to"],["su","his"],["hermano.","brother."]]},
  {num:3,words:[["Para","for"],["completar","complete"],["la","the"],["maldad","wickedness"],["con","with"],["sus","his"],["manos,","hands,"],["el","the"],["príncipe","prince"],["exige,","prince,"],["y","and"],["el","the"],["juez","judge"],["juzga","judges"],["por","for"],["recompensa;","reward;"],["y","and"],["el","the"],["poderoso","mighty"],["habla","speaks"],["según","according-to"],["el","the"],["capricho","utters"],["de","of"],["su","his"],["alma,","soul,"],["y","and"],["juntos","together"],["lo","it"],["traman.","they-plot."]]},
  {num:4,words:[["El", "the"], ["mejor", "better"], ["de", "of"], ["ellos", "they"], ["es", "is"], ["como", "as"], ["el", "the"], ["espino;", "brier;"], ["el", "the"], ["más", "more"], ["recto,", "upright,"], ["peor", "worse"], ["que", "that"], ["el", "the"], ["zarzal;", "thorn;"], ["el", "the"], ["día", "day"], ["de", "of"], ["tus","your"], ["atalayas", "watchmans"], ["y", "and"], ["de", "of"], ["tu","your"], ["castigo", "punishment"], ["viene;", "comes;"], ["ahora", "now"], ["será", "shall-be"], ["su","their"], ["confusión.", "confusion."]]},
  {num:5,words:[["No","not"],["creáis","you-believe"],["en","in"],["amigo","friend"],["ni","nor"],["confiéis","you trust"],["en","in"],["compañero;","companion;"],["de","of"],["la","the"],["que","that"],["duerme","sleeps"],["a","to"],["tu","your"],["lado,","side,"],["cuídate","her"],["de","of"],["abrir","to-open"],["tu","your"],["boca.","mouth."]]},
  {num:6,words:[["Porque","because"],["el","the"],["hijo","son"],["deshonra","dishonours"],["al","to-the"],["padre,","father,"],["la","the"],["hija","daughter"],["se","himself"],["levanta","raises"],["contra","against"],["la","the"],["madre,","mother,"],["la","the"],["nuera","daughter"],["contra","against"],["su","his"],["suegra,","mother,"],["y","and"],["los","the"],["enemigos","enemies"],["del","of-the"],["hombre","man"],["son","they-are"],["los","the"],["de","of"],["su","his"],["propia","own"],["casa.","house."]]},
  {num:7,words:[["Pero","but"],["yo","I"],["acudiré","shall-come"],["a","to"],["Jehová;","jehovah;"],["esperaré","I-will-wait"],["al","to-the"],["Dios","God"],["de","of"],["mi","my"],["salvación;","salvation;"],["el","the"],["Dios","God"],["mío","mine"],["me","me"],["oirá.","hear."]]},
  {num:8,words:[["Tú,","you,"],["enemiga","enemy"],["mía,","mother,"],["no","not"],["te","you"],["alegres","tidings"],["de","of"],["mí,","me,"],["porque","because"],["aunque","although"],["caí,","I-fell,"],["he","I-have"],["de","to"],["levantarme;","lift-me;"],["aunque","although"],["more","dwell"],["en","in"],["tinieblas,","darkness,"],["Jehová","jehovah"],["será","shall-be"],["mi","my"],["luz.","light."]]},
  {num:9,words:[["La","the"],["ira","anger"],["de","of"],["Jehová","jehovah"],["soportaré,","I-shall-bear,"],["porque","because"],["pequé","I-sinned"],["contra","against"],["él,","he,"],["hasta que","until"],["juzgue","may-judge"],["mi","my"],["causa","cause"],["y","and"],["me","me"],["haga","let-do"],["justicia.","righteousness."],["Él","he"],["me","me"],["sacará","bring"],["a","to"],["la","the"],["luz;","light;"],["veré","I-see"],["su","his"],["justicia.","righteousness."]]},
  {num:10,words:[["Y","and"],["mi","my"],["enemiga","enemy"],["lo","it"],["verá","see"],["y","and"],["se","itself"],["cubrirá","cover"],["de","of"],["vergüenza,","shame,"],["la","the"],["que","that"],["me","me"],["decía:","said:"],["¿Dónde","where"],["está","is"],["Jehová","jehovah"],["tu","your"],["Dios?","God?"],["Mis","my"],["ojos","eyes"],["la","the"],["verán;","see;"],["ahora","now"],["será","shall-be"],["hollada","trodden"],["como","as"],["el","the"],["lodo","mire"],["de","of"],["las","the"],["calles.","streets."]]},
  {num:11,words:[["El","the"],["día","day"],["en que","that"],["se","themselves"],["reedifiquen","to"],["tus","your"],["muros,","walls,"],["aquel","that"],["día","day"],["se","themselves"],["extenderán","spread"],["los","the"],["límites.","bounds."]]},
  {num:12,words:[["En","in"],["ese","that"],["día","day"],["vendrán","they-will-come"],["hasta","until"],["ti","you"],["desde","from"],["Asiria","Assyria"],["y","and"],["desde","from"],["las","the"],["ciudades","cities"],["de","of"],["Egipto,","Egypt,"],["y","and"],["desde","from"],["Egipto","Egypt"],["hasta","until"],["el","the"],["río,","river,"],["y","and"],["de","of"],["mar","sea"],["a","to"],["mar","sea"],["y","and"],["de","of"],["monte","mount"],["a","to"],["monte.","mount."]]},
  {num:13,words:[["Y", "and"], ["la", "the"], ["tierra","land"], ["será", "shall-be"], ["asolada", "desolate"], ["a causa de","because of"], ["sus","their"], ["moradores,", "inhabitants,"], ["por","for"], ["el", "the"], ["fruto", "fruit"], ["de", "of"], ["sus","their"], ["obras.", "works."]]},
  {num:14,words:[["Apacienta","he"],["a","to"],["tu","your"],["pueblo","people"],["con","with"],["tu","your"],["cayado,","the,"],["el","the"],["rebaño","flock"],["de","of"],["tu","your"],["heredad,","heritage,"],["que","that"],["mora","dwells"],["solitario","solitary"],["en","in"],["el","the"],["bosque,","forest,"],["en","in"],["medio","midst"],["del","of-the"],["Carmelo;","Carmel;"],["que","that"],["se","themselves"],["apacienten","in"],["en","in"],["Basán","Bashan"],["y","and"],["Galaad,","Gilead,"],["como","as"],["en","in"],["el","the"],["tiempo","time"],["pasado.","past."]]},
  {num:15,words:[["Yo","I"],["les","them"],["mostraré","I-will-show"],["maravillas","wondrous"],["como","as"],["el","the"],["día","day"],["en que","that"],["saliste","out"],["de","of"],["Egipto.","Egypt."]]},
  {num:16,words:[["Las","the"],["naciones","nations"],["verán","they-see"],["y","and"],["se","themselves"],["avergonzarán","ashamed"],["de","of"],["todo","all"],["su","their"],["poderío;","shall;"],["pondrán","they-lay"],["la","the"],["mano","hand"],["sobre","upon"],["su","their"],["boca;","mouth;"],["se","themselves"],["ensordecerán","ears"],["sus","their"],["oídos.","ears."]]},
  {num:17,words:[["Lamerán","they"],["el","the"],["polvo","dust"],["como","as"],["la","the"],["culebra,","snake,"],["como","as"],["las","the"],["serpientes","serpents"],["de","of"],["la","the"],["tierra;","earth;"],["saldrán","they-forth"],["temblando","trembling"],["de","of"],["sus","his"],["escondrijos;","places;"],["tendrán","they-power"],["miedo","fear"],["de","of"],["Jehová","jehovah"],["nuestro","our"],["Dios","God"],["y","and"],["temerán","they-will-fear"],["a causa de","because of"],["ti.","you."]]},
  {num:18,words:[["¿Qué","what"],["Dios","God"],["hay","there-is"],["como","as"],["tú,","you,"],["que","that"],["perdona","forgive"],["la","the"],["iniquidad","iniquity"],["y","and"],["olvida","passes"],["el","the"],["pecado","sin"],["del","of-the"],["remanente","remnant"],["de","of"],["su","his"],["heredad?","heritage?"],["No","not"],["retiene","retains"],["para","for"],["siempre","always"],["su","his"],["enojo,","fury,"],["porque","because"],["se","himself"],["deleita","delights"],["en","in"],["la","the"],["misericordia.","mercy."]]},
  {num:19,words:[["Él","he"],["volverá;","will-return;"],["volverá","will-return"],["a","to"],["tener","have"],["misericordia","mercy"],["de","of"],["nosotros;","we;"],["él","he"],["hollará","will"],["nuestras","our"],["iniquidades","iniquities"],["y","and"],["echará","cast"],["en","in"],["lo","it/him"],["profundo","deep"],["del","of-the"],["mar","sea"],["todos","all"],["nuestros","our"],["pecados.","sins."]]},
  {num:20,words:[["Otorgarás","you"],["a","to"],["Jacob","Jacob"],["la","the"],["verdad","truth"],["y","and"],["a","to"],["Abraham","Abraham"],["la","the"],["misericordia,","mercy,"],["como","as"],["juraste","you-swore"],["a","to"],["nuestros","our"],["padres","fathers"],["desde","from"],["tiempos","times"],["antiguos.","ancient."]]},
];
renderVerseSet(v7, 'mic-ch7-verses');

})();
