(function() {
var v1 = [
  {num:1,words:[["La", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["que", "that"], ["vino", "wine"], ["a", "to"], ["Miqueas", "to"], ["de", "of"], ["Moreset", "the"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["Jotam,", "jotham,"], ["de", "of"], ["Acaz", "ahaz"], ["y", "and"], ["de", "of"], ["Ezequías,", "Hezekiah,"], ["reyes", "kings"], ["de", "of"], ["Judá;", "Judah;"], ["lo", "it/him"], ["que", "that"], ["vio", "saw"], ["sobre", "upon"], ["Samaria", "samaria"], ["y", "and"], ["Jerusalén.", "Jerusalem."]]},
  {num:2,words:[["Oíd,", "hear,"], ["pueblos", "peoples"], ["todos;", "all;"], ["atended,", "people,"], ["oh", "oh"], ["tierra,", "land/earth,"], ["y", "and"], ["todo", "all"], ["lo", "it/him"], ["que", "that"], ["en", "in"], ["ella", "she"], ["hay;", "there-is;"], ["y", "and"], ["Jehová", "jehovah"], ["el", "the"], ["Señor,", "Lord,"], ["el", "the"], ["Señor", "Lord"], ["desde", "from"], ["su", "his/her"], ["santo", "holy"], ["templo,", "temple,"], ["sea", "let-be/be"], ["testigo", "witness"], ["contra", "against"], ["vosotros.", "you."]]},
  {num:3,words:[["Porque", "because"], ["he", "I-have"], ["aquí,", "here,"], ["Jehová", "jehovah"], ["sale", "goeth"], ["de", "of"], ["su", "his/her"], ["lugar,", "place,"], ["y", "and"], ["descenderá", "down"], ["y", "and"], ["caminará", "and"], ["sobre", "upon"], ["las", "the"], ["alturas", "heights"], ["de", "of"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:4,words:[["Y", "and"], ["debajo", "beneath"], ["de", "of"], ["él", "he"], ["se", "[refl.]"], ["derretirán", "under"], ["los", "the"], ["montes,", "mountains,"], ["y", "and"], ["los", "the"], ["valles", "valleys"], ["se", "[refl.]"], ["hendirán", "cleft,"], ["como", "as"], ["la", "the"], ["cera", "the"], ["ante", "before"], ["el", "the"], ["fuego,", "fire,"], ["como", "as"], ["las", "the"], ["aguas", "waters"], ["que", "that"], ["corren", "the"], ["por", "by/for"], ["un", "a"], ["precipicio.", "place."]]},
  {num:5,words:[["Todo", "all"], ["esto", "this"], ["por", "by/for"], ["la", "the"], ["rebelión", "rebellion"], ["de", "of"], ["Jacob", "Jacob"], ["y", "and"], ["por", "by/for"], ["los", "the"], ["pecados", "sins"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel.", "Israel."], ["¿Cuál", "which"], ["es", "is"], ["la", "the"], ["rebelión", "rebellion"], ["de", "of"], ["Jacob?", "Jacob?"], ["¿No", "not"], ["es", "is"], ["Samaria?", "samaria?"], ["¿Y", "and"], ["cuáles", "which"], ["son", "are"], ["los", "the"], ["lugares", "places"], ["altos", "high"], ["de", "of"], ["Judá?", "Judah?"], ["¿No", "not"], ["es", "is"], ["Jerusalén?", "Jerusalem?"]]},
  {num:6,words:[["Haré,", "I-shall-make,"], ["pues,", "for,"], ["de", "of"], ["Samaria", "samaria"], ["un", "a"], ["montón", "heap"], ["de", "of"], ["ruinas,", "waste,"], ["lugares", "places"], ["para", "for"], ["plantar", "plant"], ["viñas;", "vineyards;"], ["y", "and"], ["derramaré", "pour"], ["sus", "his/her"], ["piedras", "stones"], ["por", "by/for"], ["el", "the"], ["valle", "valley"], ["y", "and"], ["descubriré", "shall-to"], ["sus", "his/her"], ["cimientos.", "foundations."]]},
  {num:7,words:[["Y", "and"], ["todas", "all"], ["sus", "his/her"], ["estatuas", "groves"], ["serán", "shall-be"], ["despedazadas,", "beaten,"], ["y", "and"], ["todas", "all"], ["sus", "his/her"], ["pagas", "thous"], ["serán", "shall-be"], ["quemadas", "burned"], ["en", "in"], ["el", "the"], ["fuego,", "fire,"], ["y", "and"], ["asolaré", "will"], ["todos", "all"], ["sus", "his/her"], ["ídolos,", "idols,"], ["porque", "because"], ["de", "of"], ["paga", "thou"], ["de", "of"], ["rameras", "harlots"], ["las", "the"], ["juntó,", "gathered,"], ["y", "and"], ["a", "to"], ["paga", "thou"], ["de", "of"], ["rameras", "harlots"], ["volverán.", "return."]]},
  {num:8,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["lamentaré,", "wail,"], ["y", "and"], ["aullaré,", "howl,"], ["y", "and"], ["andaré", "walk"], ["despojado", "that"], ["y", "and"], ["desnudo;", "naked;"], ["haré", "I-shall-make"], ["aullido", "make"], ["como", "as"], ["de", "of"], ["chacales", "dragons"], ["y", "and"], ["lamento", "and"], ["como", "as"], ["de", "of"], ["avestruces.", "owls."]]},
  {num:9,words:[["Porque", "because"], ["su", "his/her"], ["llaga", "pronounce"], ["es", "is"], ["incurable,", "for,"], ["pues", "for"], ["llegó", "arrived"], ["hasta", "until"], ["Judá;", "Judah;"], ["llegó", "arrived"], ["hasta", "until"], ["la", "the"], ["puerta", "gate"], ["de", "of"], ["mi", "my"], ["pueblo,", "people,"], ["hasta", "until"], ["Jerusalén.", "Jerusalem."]]},
  {num:10,words:[["No", "not"], ["lo", "it/him"], ["digáis", "say"], ["en", "in"], ["Gat", "gath"], ["ni", "nor"], ["tampoco", "neither"], ["lloréis;", "in;"], ["revuélcate", "the"], ["en", "in"], ["el", "the"], ["polvo", "dust"], ["de", "of"], ["Bet-le-afra.", "dust."]]},
  {num:11,words:[["Pásate", "passeth-thee"], ["desnuda", "naked"], ["y", "and"], ["con", "with"], ["vergüenza,", "shame,"], ["oh", "oh"], ["moradora", "inhabitant"], ["de", "of"], ["Safir;", "naked;"], ["la", "the"], ["moradora", "inhabitant"], ["de", "of"], ["Zaanán", "came"], ["no", "not"], ["salió;", "departed;"], ["el", "the"], ["llanto", "gnashing"], ["de", "of"], ["Bet-esel", "he"], ["quitará", "fat"], ["de", "of"], ["vosotros", "you"], ["su", "his/her"], ["apoyo.", "the."]]},
  {num:12,words:[["Porque", "because"], ["la", "the"], ["moradora", "inhabitant"], ["de", "of"], ["Marot", "maroth"], ["anheló", "desire"], ["intensamente", "carefully"], ["el", "the"], ["bien,", "well,"], ["por", "by/for"], ["cuanto", "as-much-as"], ["el", "the"], ["mal", "evil"], ["descendió", "descended"], ["de", "of"], ["Jehová", "jehovah"], ["hasta", "until"], ["la", "the"], ["puerta", "gate"], ["de", "of"], ["Jerusalén.", "Jerusalem."]]},
  {num:13,words:[["Unce", "o"], ["al", "to-the"], ["carro", "cart"], ["los", "the"], ["corceles,", "bind,"], ["oh", "oh"], ["moradora", "inhabitant"], ["de", "of"], ["Laquis;", "lachish;"], ["ella", "she"], ["fue", "was/went"], ["principio", "beginning"], ["de", "of"], ["pecado", "sin"], ["para", "for"], ["la", "the"], ["hija", "daughter"], ["de", "of"], ["Sion,", "Zion,"], ["porque", "because"], ["en", "in"], ["ti", "thee"], ["se", "[refl.]"], ["hallaron", "found"], ["las", "the"], ["rebeliones", "for"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:14,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["tú", "thou"], ["darás", "shalt"], ["presentes", "gifts"], ["de", "of"], ["despedida", "moreshethgath:"], ["a", "to"], ["Moreset-gat;", "houses;"], ["las", "the"], ["casas", "houses"], ["de", "of"], ["Aczib", "shall"], ["serán", "shall-be"], ["un", "a"], ["engaño", "guile"], ["para", "for"], ["los", "the"], ["reyes", "kings"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:15,words:[["Aún", "still/yet"], ["te", "thee"], ["traeré", "bring"], ["heredero,", "heir,"], ["oh", "oh"], ["moradora", "inhabitant"], ["de", "of"], ["Maresa;", "mareshah;"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["Israel", "Israel"], ["vendrá", "shall-come"], ["hasta", "until"], ["Adulam.", "adullam."]]},
  {num:16,words:[["Rápate", "make"], ["y", "and"], ["córtate", "little-thee"], ["el", "the"], ["cabello", "hair"], ["por", "by/for"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["tus", "thy"], ["delicias;", "thy;"], ["ensancha", "baldness"], ["tu", "thy"], ["calva", "the"], ["como", "as"], ["águila,", "eagle,"], ["porque", "because"], ["fueron", "were"], ["llevados", "carried"], ["cautivos", "captives"], ["de", "of"], ["ti.", "thee."]]},
];
renderVerseSet(v1, 'mic-ch1-verses');

var v2 = [
  {num:1,words:[["¡Ay", "wo"], ["de", "of"], ["los", "the"], ["que", "that"], ["en", "in"], ["sus", "his/her"], ["camas", "beds"], ["traman", "they"], ["iniquidad", "iniquity"], ["y", "and"], ["maquinan", "their"], ["el", "the"], ["mal,", "evil,"], ["y", "and"], ["cuando", "when"], ["llega", "if"], ["la", "the"], ["mañana", "morning"], ["lo", "it/him"], ["ponen", "their"], ["por", "by/for"], ["obra,", "work,"], ["porque", "because"], ["tienen", "have"], ["en", "in"], ["su", "his/her"], ["mano", "hand"], ["el", "the"], ["poder!", "power/can!"]]},
  {num:2,words:[["Y", "and"], ["codician", "they"], ["los", "the"], ["campos", "fields"], ["y", "and"], ["los", "the"], ["roban;", "their;"], ["y", "and"], ["casas,", "houses,"], ["y", "and"], ["las", "the"], ["quitan;", "take;"], ["así", "thus"], ["oprimen", "so"], ["al", "to-the"], ["hombre", "man"], ["y", "and"], ["a", "to"], ["su", "his/her"], ["casa,", "house,"], ["al", "to-the"], ["hombre", "man"], ["y", "and"], ["a", "to"], ["su", "his/her"], ["heredad.", "heritage."]]},
  {num:3,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["He", "I-have"], ["aquí,", "here,"], ["yo", "I"], ["tramo", "of"], ["contra", "against"], ["esta", "this"], ["familia", "family"], ["un", "a"], ["mal,", "evil,"], ["del", "of-the"], ["cual", "which"], ["no", "not"], ["sacaréis", "shall-bring"], ["vuestros", "your"], ["cuellos", "necks"], ["ni", "nor"], ["andaréis", "shall-walk"], ["erguidos,", "go,"], ["porque", "because"], ["el", "the"], ["tiempo", "time"], ["será", "shall-be"], ["malo.", "evil."]]},
  {num:4,words:[["En", "in"], ["aquel", "that"], ["día", "day"], ["se", "[refl.]"], ["levantará", "raise"], ["contra", "against"], ["vosotros", "you"], ["un", "a"], ["refrán,", "proverb,"], ["y", "and"], ["se", "[refl.]"], ["lamentará", "with"], ["con", "with"], ["triste", "my"], ["lamentación,", "lamentation,"], ["diciendo:", "saying:"], ["Del", "of-the"], ["todo", "all"], ["fuimos", "we"], ["destruidos;", "destroyed;"], ["él", "he"], ["ha", "has"], ["cambiado", "changed"], ["la", "the"], ["heredad", "heritage"], ["de", "of"], ["mi", "my"], ["pueblo.", "people."], ["¡Cómo", "how"], ["nos", "us"], ["quitó", "removed"], ["nuestros", "our"], ["campos!", "fields!"], ["Los", "the"], ["repartió", "divided"], ["a", "to"], ["otros.", "others."]]},
  {num:5,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["no", "not"], ["tendrás", "shalt"], ["quien", "who"], ["reparta", "shall"], ["heredades", "inheritances"], ["a", "to"], ["suerte", "lot"], ["en", "in"], ["la", "the"], ["congregación", "congregation"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:6,words:[["No", "not"], ["profeticéis,", "ye,"], ["dicen", "say"], ["a", "to"], ["los", "the"], ["que", "that"], ["profetizan;", "prophesy;"], ["no", "not"], ["les", "them"], ["profeticen,", "to,"], ["porque", "because"], ["no", "not"], ["van", "go"], ["a", "to"], ["avergonzarse.", "shame."]]},
  {num:7,words:[["Tú", "thou"], ["que", "that"], ["te", "thee"], ["dices", "sayest"], ["casa", "house"], ["de", "of"], ["Jacob,", "Jacob,"], ["¿se", "[refl.]"], ["ha", "has"], ["reducido", "to"], ["el", "the"], ["espíritu", "Spirit"], ["de", "of"], ["Jehová?", "jehovah?"], ["¿Son", "are"], ["estas", "these"], ["sus", "his/her"], ["obras?", "works?"], ["¿No", "not"], ["hacen", "do/make"], ["bien", "well"], ["mis", "my"], ["palabras", "words"], ["al", "to-the"], ["que", "that"], ["camina", "walketh"], ["rectamente?", "uprightly?"]]},
  {num:8,words:[["El", "the"], ["que", "that"], ["ayer", "yesterday"], ["era", "was"], ["mi", "my"], ["pueblo", "people"], ["se", "[refl.]"], ["ha", "has"], ["levantado", "risen"], ["como", "as"], ["enemigo;", "enemy;"], ["a", "to"], ["los", "the"], ["que", "that"], ["pasan", "pass"], ["confiadamente,", "that,"], ["los", "the"], ["que", "that"], ["vuelven", "return"], ["de", "of"], ["la", "the"], ["guerra,", "war,"], ["les", "them"], ["quitáis", "by"], ["el", "the"], ["manto", "mantle"], ["de", "of"], ["sobre", "upon"], ["la", "the"], ["vestimenta.", "war."]]},
  {num:9,words:[["A", "to"], ["las", "the"], ["mujeres", "women"], ["de", "of"], ["mi", "my"], ["pueblo", "people"], ["echasteis", "cast"], ["fuera", "outside/were"], ["de", "of"], ["las", "the"], ["casas", "houses"], ["de", "of"], ["sus", "his/her"], ["delicias;", "their;"], ["a", "to"], ["sus", "his/her"], ["niños", "children"], ["quitasteis", "away"], ["mi", "my"], ["gloria", "glory"], ["para", "for"], ["siempre.", "always."]]},
  {num:10,words:[["Levantaos", "arise"], ["y", "and"], ["andad,", "walk,"], ["porque", "because"], ["este", "this"], ["no", "not"], ["es", "is"], ["lugar", "place"], ["de", "of"], ["reposo;", "rest;"], ["puesto", "placed"], ["que", "that"], ["está", "is"], ["contaminado,", "defiled,"], ["destruirá", "destroy"], ["con", "with"], ["gran", "great"], ["destrucción.", "destruction."]]},
  {num:11,words:[["Si", "if"], ["alguno", "some"], ["anda", "walketh"], ["con", "with"], ["espíritu", "Spirit"], ["falso", "false"], ["y", "and"], ["miente,", "do,"], ["diciendo:", "saying:"], ["Yo", "I"], ["te", "thee"], ["profetizaré", "shall-prophesy"], ["de", "of"], ["vino", "wine"], ["y", "and"], ["de", "of"], ["sidra;", "wine;"], ["este", "this"], ["será", "shall-be"], ["el", "the"], ["profeta", "prophet"], ["para", "for"], ["este", "this"], ["pueblo.", "people."]]},
  {num:12,words:[["De", "of"], ["cierto", "certain"], ["os", "you"], ["reuniré", "gather"], ["a", "to"], ["todos,", "all,"], ["oh", "oh"], ["Jacob;", "Jacob;"], ["recogeré", "gather"], ["ciertamente", "surely"], ["al", "to-the"], ["remanente", "remnant"], ["de", "of"], ["Israel;", "Israel;"], ["los", "the"], ["pondré", "I-shall-put"], ["juntos", "together"], ["como", "as"], ["ovejas", "sheep"], ["de", "of"], ["Bosra,", "bozrah,"], ["como", "as"], ["rebaño", "flock"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["su", "his/her"], ["redil;", "fold;"], ["harán", "shall-make"], ["estruendo", "noise"], ["por", "by/for"], ["la", "the"], ["multitud", "multitude"], ["de", "of"], ["hombres.", "men."]]},
  {num:13,words:[["Subirá", "up"], ["el", "the"], ["que", "that"], ["abre", "openeth"], ["brechas", "breaches"], ["delante", "before"], ["de", "of"], ["ellos;", "they;"], ["abrirán", "shall"], ["brecha,", "breach,"], ["y", "and"], ["pasarán", "away"], ["la", "the"], ["puerta", "gate"], ["y", "and"], ["saldrán", "forth"], ["por", "by/for"], ["ella;", "she;"], ["y", "and"], ["su", "his/her"], ["rey", "king"], ["pasará", "through"], ["delante", "before"], ["de", "of"], ["ellos,", "they,"], ["y", "and"], ["a", "to"], ["la", "the"], ["cabeza", "head"], ["de", "of"], ["ellos", "they"], ["Jehová.", "jehovah."]]},
];
renderVerseSet(v2, 'mic-ch2-verses');

var v3 = [
  {num:1,words:[["Y", "and"], ["dije:", "I-said:"], ["Oíd", "hear"], ["ahora,", "now,"], ["oh", "oh"], ["gobernantes", "rulers"], ["de", "of"], ["Jacob", "Jacob"], ["y", "and"], ["jefes", "chiefs"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel:", "Israel:"], ["¿No", "not"], ["os", "you"], ["corresponde", "it"], ["a", "to"], ["vosotros", "you"], ["saber", "know"], ["lo", "it/him"], ["que", "that"], ["es", "is"], ["justo?", "just/righteous?"]]},
  {num:2,words:[["Vosotros", "you"], ["que", "that"], ["aborrecéis", "the"], ["lo", "it/him"], ["bueno", "good"], ["y", "and"], ["amáis", "love"], ["lo", "it/him"], ["malo,", "evil,"], ["que", "that"], ["les", "them"], ["quitáis", "skin"], ["su", "his/her"], ["piel", "skin"], ["y", "and"], ["su", "his/her"], ["carne", "flesh"], ["de", "of"], ["sobre", "upon"], ["los", "the"], ["huesos;", "bones;"]]},
  {num:3,words:[["que", "that"], ["coméis", "eat"], ["asimismo", "likewise"], ["la", "the"], ["carne", "flesh"], ["de", "of"], ["mi", "my"], ["pueblo,", "people,"], ["y", "and"], ["les", "them"], ["arrancáis", "their"], ["la", "the"], ["piel", "skin"], ["de", "of"], ["sobre", "upon"], ["ellos,", "they,"], ["y", "and"], ["les", "them"], ["quebráis", "bones,"], ["los", "the"], ["huesos", "bones"], ["y", "and"], ["los", "the"], ["rompéis,", "pieces,"], ["como", "as"], ["para", "for"], ["el", "the"], ["caldero,", "pot,"], ["y", "and"], ["como", "as"], ["carne", "flesh"], ["en", "in"], ["la", "the"], ["olla.", "pot."]]},
  {num:4,words:[["Entonces", "then"], ["clamarán", "cry"], ["a", "to"], ["Jehová", "jehovah"], ["y", "and"], ["no", "not"], ["les", "them"], ["responderá,", "answer,"], ["sino", "but"], ["que", "that"], ["esconderá", "will"], ["de", "of"], ["ellos", "they"], ["su", "his/her"], ["rostro", "face"], ["en", "in"], ["aquel", "that"], ["tiempo,", "time,"], ["por", "by/for"], ["cuanto", "as-much-as"], ["hicieron", "did/made"], ["obras", "works"], ["malas.", "evil."]]},
  {num:5,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová", "jehovah"], ["acerca", "about"], ["de", "of"], ["los", "the"], ["profetas", "prophets"], ["que", "that"], ["hacen", "do/make"], ["errar", "err"], ["a", "to"], ["mi", "my"], ["pueblo,", "people,"], ["que", "that"], ["muerden", "their"], ["con", "with"], ["sus", "his/her"], ["dientes", "gnashing"], ["y", "and"], ["claman:", "cry:"], ["Paz,", "peace,"], ["y", "and"], ["al", "to-the"], ["que", "that"], ["no", "not"], ["les", "them"], ["da", "gives"], ["de", "of"], ["comer,", "eat,"], ["declaran", "declare"], ["contra", "against"], ["él", "he"], ["guerra", "war"], ["santa.", "holy."]]},
  {num:6,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["habrá", "there-shall-be"], ["para", "for"], ["vosotros", "you"], ["noche", "night"], ["sin", "without"], ["visión", "vision"], ["y", "and"], ["oscuridad", "darkness"], ["sin", "without"], ["adivinación;", "divination;"], ["y", "and"], ["sobre", "upon"], ["los", "the"], ["profetas", "prophets"], ["se", "[refl.]"], ["pondrá", "pour"], ["el", "the"], ["sol,", "sun,"], ["y", "and"], ["el", "the"], ["día", "day"], ["se", "[refl.]"], ["entenebrecerá", "shall"], ["sobre", "upon"], ["ellos.", "they."]]},
  {num:7,words:[["Y", "and"], ["serán", "shall-be"], ["avergonzados", "ashamed"], ["los", "the"], ["profetas,", "prophets,"], ["y", "and"], ["se", "[refl.]"], ["confundirán", "the"], ["los", "the"], ["adivinos;", "wizards;"], ["y", "and"], ["todos", "all"], ["ellos", "they"], ["se", "[refl.]"], ["cubrirán", "cover"], ["los", "the"], ["labios,", "lips,"], ["porque", "because"], ["no", "not"], ["hay", "there-is"], ["respuesta", "answer"], ["de", "of"], ["Dios.", "God."]]},
  {num:8,words:[["Pero", "but"], ["yo", "I"], ["estoy", "I-am"], ["lleno", "full"], ["del", "of-the"], ["poder", "power/can"], ["mediante", "through"], ["el", "the"], ["espíritu", "Spirit"], ["de", "of"], ["Jehová,", "jehovah,"], ["y", "and"], ["de", "of"], ["juicio", "judgment"], ["y", "and"], ["de", "of"], ["fuerza,", "strength,"], ["para", "for"], ["denunciar", "to"], ["a", "to"], ["Jacob", "Jacob"], ["su", "his/her"], ["rebelión", "rebellion"], ["y", "and"], ["a", "to"], ["Israel", "Israel"], ["su", "his/her"], ["pecado.", "sin."]]},
  {num:9,words:[["Oíd", "hear"], ["ahora", "now"], ["esto,", "this,"], ["gobernantes", "rulers"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jacob", "Jacob"], ["y", "and"], ["jefes", "chiefs"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Israel,", "Israel,"], ["que", "that"], ["abomináis", "house"], ["la", "the"], ["justicia", "justice/righteousness"], ["y", "and"], ["pervertís", "abhor"], ["todo", "all"], ["lo", "it/him"], ["que", "that"], ["es", "is"], ["recto,", "upright,"]]},
  {num:10,words:[["que", "that"], ["edificáis", "build"], ["a", "to"], ["Sion", "Zion"], ["con", "with"], ["sangre", "blood"], ["y", "and"], ["a", "to"], ["Jerusalén", "Jerusalem"], ["con", "with"], ["injusticia.", "unrighteousness."]]},
  {num:11,words:[["Sus", "his/her"], ["gobernantes", "rulers"], ["juzgan", "judge"], ["por", "by/for"], ["cohecho,", "reward,"], ["y", "and"], ["sus", "his/her"], ["sacerdotes", "priests"], ["enseñan", "teach"], ["por", "by/for"], ["precio,", "price,"], ["y", "and"], ["sus", "his/her"], ["profetas", "prophets"], ["adivinan", "divine"], ["por", "by/for"], ["dinero;", "sacks;"], ["y", "and"], ["se", "[refl.]"], ["apoyan", "upon"], ["en", "in"], ["Jehová,", "jehovah,"], ["diciendo:", "saying:"], ["¿No", "not"], ["está", "is"], ["Jehová", "jehovah"], ["entre", "among"], ["nosotros?", "we?"], ["No", "not"], ["vendrá", "shall-come"], ["mal", "evil"], ["sobre", "upon"], ["nosotros.", "we."]]},
  {num:12,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["vosotros", "you"], ["Sion", "Zion"], ["será", "shall-be"], ["arada", "the"], ["como", "as"], ["campo,", "field,"], ["y", "and"], ["Jerusalén", "Jerusalem"], ["será", "shall-be"], ["montones", "heaps"], ["de", "of"], ["ruinas;", "waste;"], ["y", "and"], ["el", "the"], ["monte", "mount"], ["de", "of"], ["la", "the"], ["casa,", "house,"], ["como", "as"], ["cumbres", "of"], ["de", "of"], ["bosque.", "forest."]]},
];
renderVerseSet(v3, 'mic-ch3-verses');

var v4 = [
  {num:1,words:[["Y", "and"], ["acontecerá", "shall-come-to-pass"], ["en", "in"], ["los", "the"], ["postreros", "latter"], ["días", "days"], ["que", "that"], ["el", "the"], ["monte", "mount"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Jehová", "jehovah"], ["será", "shall-be"], ["establecido", "established"], ["como", "as"], ["cabeza", "head"], ["de", "of"], ["los", "the"], ["montes,", "mountains,"], ["y", "and"], ["más", "more"], ["alto", "high"], ["que", "that"], ["los", "the"], ["collados,", "hills,"], ["y", "and"], ["correrán", "run"], ["a", "to"], ["él", "he"], ["los", "the"], ["pueblos.", "peoples."]]},
  {num:2,words:[["Y", "and"], ["vendrán", "far"], ["muchas", "many"], ["naciones", "nations"], ["y", "and"], ["dirán:", "say:"], ["Venid,", "come,"], ["y", "and"], ["subamos", "us"], ["al", "to-the"], ["monte", "mount"], ["de", "of"], ["Jehová", "jehovah"], ["y", "and"], ["a", "to"], ["la", "the"], ["casa", "house"], ["del", "of-the"], ["Dios", "God"], ["de", "of"], ["Jacob;", "Jacob;"], ["y", "and"], ["nos", "us"], ["enseñará", "teach"], ["acerca", "about"], ["de", "of"], ["sus", "his/her"], ["caminos,", "ways,"], ["y", "and"], ["andaremos", "shall-walk"], ["por", "by/for"], ["sus", "his/her"], ["veredas;", "paths;"], ["porque", "because"], ["de", "of"], ["Sion", "Zion"], ["saldrá", "forth"], ["la", "the"], ["ley,", "law,"], ["y", "and"], ["de", "of"], ["Jerusalén", "Jerusalem"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:3,words:[["Y", "and"], ["él", "he"], ["juzgará", "judge"], ["entre", "among"], ["muchos", "many"], ["pueblos", "peoples"], ["y", "and"], ["reprenderá", "shall"], ["a", "to"], ["naciones", "nations"], ["poderosas", "mighty"], ["hasta", "until"], ["muy", "very"], ["lejos;", "far;"], ["y", "and"], ["forjarán", "beat"], ["sus", "his/her"], ["espadas", "swords"], ["en", "in"], ["rejas", "plowshares,"], ["de", "of"], ["arado", "the"], ["y", "and"], ["sus", "his/her"], ["lanzas", "spears"], ["en", "in"], ["hoces;", "shall;"], ["no", "not"], ["alzará", "lift"], ["espada", "sword"], ["nación", "nation"], ["contra", "against"], ["nación", "nation"], ["ni", "nor"], ["se", "[refl.]"], ["adiestrarán", "they"], ["más", "more"], ["para", "for"], ["la", "the"], ["guerra.", "war."]]},
  {num:4,words:[["Y", "and"], ["se", "[refl.]"], ["sentará", "sit"], ["cada", "each"], ["uno", "one"], ["debajo", "beneath"], ["de", "of"], ["su", "his/her"], ["vid", "vine"], ["y", "and"], ["debajo", "beneath"], ["de", "of"], ["su", "his/her"], ["higuera,", "fig,"], ["y", "and"], ["no", "not"], ["habrá", "there-shall-be"], ["quien", "who"], ["los", "the"], ["amedrente,", "afraid,"], ["porque", "because"], ["la", "the"], ["boca", "mouth"], ["de", "of"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["lo", "it/him"], ["ha", "has"], ["hablado.", "spoken."]]},
  {num:5,words:[["Todos", "all"], ["los", "the"], ["pueblos", "peoples"], ["andarán", "walk"], ["cada", "each"], ["uno", "one"], ["en", "in"], ["el", "the"], ["nombre", "name"], ["de", "of"], ["su", "his/her"], ["dios,", "God,"], ["y", "and"], ["nosotros", "we"], ["andaremos", "shall-walk"], ["en", "in"], ["el", "the"], ["nombre", "name"], ["de", "of"], ["Jehová", "jehovah"], ["nuestro", "our"], ["Dios", "God"], ["eternamente", "ever"], ["y", "and"], ["para", "for"], ["siempre.", "always."]]},
  {num:6,words:[["En", "in"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["juntaré", "gather"], ["a", "to"], ["la", "the"], ["que", "that"], ["cojea,", "and,"], ["y", "and"], ["recogeré", "gather"], ["a", "to"], ["la", "the"], ["desterrada", "the"], ["y", "and"], ["a", "to"], ["la", "the"], ["que", "that"], ["afligí;", "afflicted;"]]},
  {num:7,words:[["y", "and"], ["haré", "I-shall-make"], ["de", "of"], ["la", "the"], ["que", "that"], ["cojea", "halted"], ["un", "a"], ["remanente,", "remnant,"], ["y", "and"], ["de", "of"], ["la", "the"], ["desterrada,", "the,"], ["nación", "nation"], ["robusta;", "a;"], ["y", "and"], ["Jehová", "jehovah"], ["reinará", "reign"], ["sobre", "upon"], ["ellos", "they"], ["en", "in"], ["el", "the"], ["monte", "mount"], ["Sion", "Zion"], ["desde", "from"], ["ahora", "now"], ["y", "and"], ["para", "for"], ["siempre.", "always."]]},
  {num:8,words:[["Y", "and"], ["tú,", "thou,"], ["oh", "oh"], ["torre", "tower"], ["del", "of-the"], ["rebaño,", "flock,"], ["fortaleza", "castle"], ["de", "of"], ["la", "the"], ["hija", "daughter"], ["de", "of"], ["Sion,", "Zion,"], ["hasta", "until"], ["ti", "thee"], ["vendrá", "shall-come"], ["el", "the"], ["primer", "first"], ["señorío,", "first,"], ["el", "the"], ["reino", "kingdom"], ["vendrá", "shall-come"], ["a", "to"], ["la", "the"], ["hija", "daughter"], ["de", "of"], ["Jerusalén.", "Jerusalem."]]},
  {num:9,words:[["Ahora,", "now,"], ["¿por", "by/for"], ["qué", "what"], ["gritas", "cry"], ["tanto?", "therefore?"], ["¿No", "not"], ["hay", "there-is"], ["rey", "king"], ["en", "in"], ["ti?", "thee?"], ["¿Pereció", "perished"], ["tu", "thy"], ["consejero?", "counselor?"], ["¿Te", "thee"], ["ha", "has"], ["sobrevenido", "us"], ["dolor", "pain"], ["como", "as"], ["a", "to"], ["mujer", "woman"], ["de", "of"], ["parto?", "travail?"]]},
  {num:10,words:[["Retuércete", "be"], ["y", "and"], ["gime,", "the,"], ["hija", "daughter"], ["de", "of"], ["Sion,", "Zion,"], ["como", "as"], ["mujer", "woman"], ["que", "that"], ["está", "is"], ["de", "of"], ["parto,", "travail,"], ["porque", "because"], ["ahora", "now"], ["saldrás", "shalt"], ["de", "of"], ["la", "the"], ["ciudad,", "city,"], ["y", "and"], ["morarás", "shall-dwell"], ["en", "in"], ["el", "the"], ["campo", "field"], ["y", "and"], ["llegarás", "shalt"], ["hasta", "until"], ["Babilonia;", "Babylon;"], ["allí", "there"], ["serás", "thou-shalt-be"], ["librada;", "delivered;"], ["allí", "there"], ["te", "thee"], ["redimirá", "redeem"], ["Jehová", "jehovah"], ["de", "of"], ["manos", "hands"], ["de", "of"], ["tus", "thy"], ["enemigos.", "enemies."]]},
  {num:11,words:[["Y", "and"], ["ahora", "now"], ["se", "[refl.]"], ["han", "have"], ["juntado", "gathered"], ["muchas", "many"], ["naciones", "nations"], ["contra", "against"], ["ti", "thee"], ["y", "and"], ["dicen:", "say:"], ["Sea", "let-be/be"], ["profanada,", "polluted,"], ["y", "and"], ["contemplen", "our"], ["nuestros", "our"], ["ojos", "eyes"], ["Sion.", "Zion."]]},
  {num:12,words:[["Mas", "but"], ["ellos", "they"], ["no", "not"], ["conocieron", "they"], ["los", "the"], ["pensamientos", "thoughts"], ["de", "of"], ["Jehová", "jehovah"], ["ni", "nor"], ["entendieron", "understood"], ["su", "his/her"], ["consejo;", "counsel;"], ["los", "the"], ["juntó,", "gathered,"], ["pues,", "for,"], ["como", "as"], ["gavillas", "sheaves"], ["en", "in"], ["la", "the"], ["era.", "was."]]},
  {num:13,words:[["Levántate", "arise"], ["y", "and"], ["trilla,", "o,"], ["hija", "daughter"], ["de", "of"], ["Sion,", "Zion,"], ["porque", "because"], ["haré", "I-shall-make"], ["tu", "thy"], ["cuerno", "horn"], ["de", "of"], ["hierro", "iron"], ["y", "and"], ["tus", "thy"], ["uñas", "thy"], ["de", "of"], ["bronce,", "brass,"], ["y", "and"], ["desmenuzarás", "shalt"], ["a", "to"], ["muchos", "many"], ["pueblos;", "peoples;"], ["y", "and"], ["consagraré", "i"], ["a", "to"], ["Jehová", "jehovah"], ["su", "his/her"], ["botín,", "spoil,"], ["y", "and"], ["sus", "his/her"], ["riquezas", "riches"], ["al", "to-the"], ["Señor", "Lord"], ["de", "of"], ["toda", "all"], ["la", "the"], ["tierra.", "land/earth."]]},
];
renderVerseSet(v4, 'mic-ch4-verses');

var v5 = [
  {num:1,words:[["Agrúpate", "now"], ["ahora", "now"], ["en", "in"], ["tropas,", "bands,"], ["oh", "oh"], ["hija", "daughter"], ["de", "of"], ["tropas;", "bands;"], ["nos", "us"], ["han", "have"], ["sitiado;", "against;"], ["con", "with"], ["vara", "rod"], ["herirán", "shall-smite"], ["en", "in"], ["la", "the"], ["mejilla", "cheek"], ["al", "to-the"], ["juez", "judge"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:2,words:[["Mas", "but"], ["tú,", "thou,"], ["Belén", "bethlehem"], ["Efrata,", "the,"], ["pequeña", "small"], ["para", "for"], ["estar", "be"], ["entre", "among"], ["los", "the"], ["millares", "thousands"], ["de", "of"], ["Judá,", "Judah,"], ["de", "of"], ["ti", "thee"], ["me", "me"], ["saldrá", "forth"], ["el", "the"], ["que", "that"], ["será", "shall-be"], ["gobernante", "ruler"], ["en", "in"], ["Israel;", "Israel;"], ["y", "and"], ["sus", "his/her"], ["orígenes", "ruler"], ["son", "are"], ["desde", "from"], ["tiempos", "times"], ["antiguos,", "ancient,"], ["desde", "from"], ["los", "the"], ["días", "days"], ["de", "of"], ["la", "the"], ["eternidad.", "eternity."]]},
  {num:3,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["los", "the"], ["dejará", "leave"], ["hasta", "until"], ["el", "the"], ["tiempo", "time"], ["en", "in"], ["que", "that"], ["dé", "yield"], ["a", "to"], ["luz", "light"], ["la", "the"], ["que", "that"], ["ha", "has"], ["de", "of"], ["dar", "give"], ["a", "to"], ["luz;", "light;"], ["entonces", "then"], ["el", "the"], ["resto", "remnant"], ["de", "of"], ["sus", "his/her"], ["hermanos", "brethren"], ["volverá", "return"], ["a", "to"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:4,words:[["Y", "and"], ["él", "he"], ["se", "[refl.]"], ["levantará", "raise"], ["y", "and"], ["apacentará", "shall-feed"], ["con", "with"], ["el", "the"], ["poder", "power/can"], ["de", "of"], ["Jehová,", "jehovah,"], ["con", "with"], ["la", "the"], ["grandeza", "greatness"], ["del", "of-the"], ["nombre", "name"], ["de", "of"], ["Jehová", "jehovah"], ["su", "his/her"], ["Dios;", "God;"], ["y", "and"], ["permanecerán,", "shall,"], ["porque", "because"], ["entonces", "then"], ["él", "he"], ["será", "shall-be"], ["engrandecido", "magnified"], ["hasta", "until"], ["los", "the"], ["confines", "ends"], ["de", "of"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:5,words:[["Y", "and"], ["ese", "that"], ["hombre", "man"], ["será", "shall-be"], ["la", "the"], ["paz.", "peace."], ["Cuando", "when"], ["el", "the"], ["asirio", "assyrian"], ["venga", "let-come"], ["a", "to"], ["nuestra", "our"], ["tierra", "land/earth"], ["y", "and"], ["pisotee", "shall"], ["nuestros", "our"], ["palacios,", "palaces,"], ["entonces", "then"], ["levantaremos", "shall-raise"], ["contra", "against"], ["él", "he"], ["siete", "seven"], ["pastores", "pastors"], ["y", "and"], ["ocho", "eight"], ["hombres", "men"], ["principales;", "chief;"]]},
  {num:6,words:[["y", "and"], ["devastarán", "they"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Asiria", "assyria"], ["a", "to"], ["espada,", "sword,"], ["y", "and"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Nimrod", "in"], ["en", "in"], ["sus", "his/her"], ["entradas;", "in;"], ["y", "and"], ["nos", "us"], ["librará", "deliver"], ["del", "of-the"], ["asirio", "assyrian"], ["cuando", "when"], ["venga", "let-come"], ["a", "to"], ["nuestra", "our"], ["tierra", "land/earth"], ["y", "and"], ["pise", "treadeth"], ["nuestras", "provisions"], ["fronteras.", "borders."]]},
  {num:7,words:[["Y", "and"], ["el", "the"], ["remanente", "remnant"], ["de", "of"], ["Jacob", "Jacob"], ["será", "shall-be"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["muchos", "many"], ["pueblos", "peoples"], ["como", "as"], ["el", "the"], ["rocío", "dew"], ["que", "that"], ["viene", "comes"], ["de", "of"], ["Jehová,", "jehovah,"], ["como", "as"], ["las", "the"], ["lluvias", "the"], ["sobre", "upon"], ["la", "the"], ["hierba,", "herb,"], ["las", "the"], ["cuales", "which"], ["no", "not"], ["esperan", "wait"], ["al", "to-the"], ["hombre", "man"], ["ni", "nor"], ["aguardan", "nor"], ["a", "to"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["los", "the"], ["hombres.", "men."]]},
  {num:8,words:[["Asimismo,", "likewise,"], ["el", "the"], ["remanente", "remnant"], ["de", "of"], ["Jacob", "Jacob"], ["será", "shall-be"], ["entre", "among"], ["las", "the"], ["naciones,", "nations,"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["muchos", "many"], ["pueblos,", "peoples,"], ["como", "as"], ["el", "the"], ["león", "lion"], ["entre", "among"], ["las", "the"], ["bestias", "beasts"], ["del", "of-the"], ["bosque,", "forest,"], ["como", "as"], ["el", "the"], ["cachorro", "lion"], ["del", "of-the"], ["león", "lion"], ["entre", "among"], ["los", "the"], ["rebaños", "flocks"], ["de", "of"], ["las", "the"], ["ovejas,", "sheep,"], ["el", "the"], ["cual", "which"], ["si", "if"], ["pasa,", "passeth,"], ["y", "and"], ["pisotea", "and"], ["y", "and"], ["arrebata,", "the,"], ["no", "not"], ["hay", "there-is"], ["quien", "who"], ["escape.", "escape."]]},
  {num:9,words:[["Tu", "thy"], ["mano", "hand"], ["se", "[refl.]"], ["alzará", "lift"], ["sobre", "upon"], ["tus", "thy"], ["enemigos,", "enemies,"], ["y", "and"], ["todos", "all"], ["tus", "thy"], ["adversarios", "adversaries"], ["serán", "shall-be"], ["talados.", "hewn."]]},
  {num:10,words:[["Y", "and"], ["acontecerá", "shall-come-to-pass"], ["en", "in"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["que", "that"], ["haré", "I-shall-make"], ["matar", "slay"], ["tus", "thy"], ["caballos", "horses"], ["de", "of"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti", "thee"], ["y", "and"], ["haré", "I-shall-make"], ["destruir", "destroy"], ["tus", "thy"], ["carros.", "chariots."]]},
  {num:11,words:[["Haré", "I-shall-make"], ["también", "also"], ["destruir", "destroy"], ["las", "the"], ["ciudades", "cities"], ["de", "of"], ["tu", "thy"], ["tierra,", "land/earth,"], ["y", "and"], ["derribaré", "down"], ["todas", "all"], ["tus", "thy"], ["fortalezas.", "holds."]]},
  {num:12,words:[["Asimismo,", "likewise,"], ["destruiré", "destroy"], ["de", "of"], ["tu", "thy"], ["mano", "hand"], ["las", "the"], ["hechicerías,", "of,"], ["y", "and"], ["no", "not"], ["se", "[refl.]"], ["hallarán", "find"], ["en", "in"], ["ti", "thee"], ["agoreros.", "soothsayers."]]},
  {num:13,words:[["Y", "and"], ["haré", "I-shall-make"], ["destruir", "destroy"], ["tus", "thy"], ["esculturas", "gravens"], ["y", "and"], ["tus", "thy"], ["imágenes", "groves"], ["talladas", "graven"], ["de", "of"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti,", "thee,"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["te", "thee"], ["inclinarás", "no"], ["ante", "before"], ["la", "the"], ["obra", "work"], ["de", "of"], ["tus", "thy"], ["manos;", "hands;"]]},
  {num:14,words:[["y", "and"], ["arrancaré", "will"], ["tus", "thy"], ["imágenes", "groves"], ["de", "of"], ["Asera", "groves"], ["de", "of"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti", "thee"], ["y", "and"], ["destruiré", "destroy"], ["tus", "thy"], ["ciudades.", "cities."]]},
  {num:15,words:[["Y", "and"], ["con", "with"], ["ira", "wrath"], ["y", "and"], ["con", "with"], ["furor", "fury"], ["haré", "I-shall-make"], ["venganza", "vengeance"], ["en", "in"], ["las", "the"], ["naciones", "nations"], ["que", "that"], ["no", "not"], ["escucharon.", "hearkened."]]},
];
renderVerseSet(v5, 'mic-ch5-verses');

var v6 = [
  {num:1,words:[["Oíd", "hear"], ["ahora", "now"], ["lo", "it/him"], ["que", "that"], ["dice", "says"], ["Jehová:", "jehovah:"], ["Levántate,", "arise,"], ["contiende", "contend"], ["con", "with"], ["los", "the"], ["montes,", "mountains,"], ["y", "and"], ["oigan", "hear"], ["los", "the"], ["collados", "hills"], ["tu", "thy"], ["voz.", "voice."]]},
  {num:2,words:[["Oíd,", "hear,"], ["montes", "mountains"], ["y", "and"], ["fuertes", "strong"], ["cimientos", "foundations"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["el", "the"], ["pleito", "the"], ["de", "of"], ["Jehová,", "jehovah,"], ["porque", "because"], ["Jehová", "jehovah"], ["tiene", "has"], ["pleito", "the"], ["con", "with"], ["su", "his/her"], ["pueblo", "people"], ["y", "and"], ["altercará", "will"], ["con", "with"], ["Israel.", "Israel."]]},
  {num:3,words:[["Pueblo", "people"], ["mío,", "mine,"], ["¿qué", "what"], ["te", "thee"], ["he", "I-have"], ["hecho", "done/made"], ["o", "or"], ["en", "in"], ["qué", "what"], ["te", "thee"], ["he", "I-have"], ["molestado?", "wearied?"], ["Responde", "unto"], ["contra", "against"], ["mí.", "me."]]},
  {num:4,words:[["Porque", "because"], ["yo", "I"], ["te", "thee"], ["hice", "I-did"], ["subir", "go-up"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["de", "of"], ["Egipto,", "Egypt,"], ["y", "and"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["servidumbre", "bondage"], ["te", "thee"], ["redimí;", "the;"], ["y", "and"], ["envié", "sent"], ["delante", "before"], ["de", "of"], ["ti", "thee"], ["a", "to"], ["Moisés,", "Moses,"], ["y", "and"], ["a", "to"], ["Aarón", "Aaron"], ["y", "and"], ["a", "to"], ["María.", "miriam."]]},
  {num:5,words:[["Pueblo", "people"], ["mío,", "mine,"], ["acuérdate", "remember"], ["ahora", "now"], ["de", "of"], ["lo", "it/him"], ["que", "that"], ["aconsejó", "king"], ["Balac,", "balak,"], ["rey", "king"], ["de", "of"], ["Moab,", "moab,"], ["y", "and"], ["de", "of"], ["lo", "it/him"], ["que", "that"], ["le", "him/her"], ["respondió", "answered"], ["Balaam", "balaam"], ["hijo", "son"], ["de", "of"], ["Beor,", "beor,"], ["desde", "from"], ["Sitim", "gilgal;"], ["hasta", "until"], ["Gilgal,", "gilgal,"], ["para", "for"], ["que", "that"], ["conozcas", "knows"], ["las", "the"], ["justicias", "justice/righteousnesss"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:6,words:[["¿Con", "with"], ["qué", "what"], ["me", "me"], ["presentaré", "shall-to"], ["ante", "before"], ["Jehová", "jehovah"], ["y", "and"], ["adoraré", "shall-worship"], ["al", "to-the"], ["Dios", "God"], ["Altísimo?", "most?"], ["¿Me", "me"], ["presentaré", "shall-to"], ["ante", "before"], ["él", "he"], ["con", "with"], ["holocaustos,", "sacrifices,"], ["con", "with"], ["becerros", "calves"], ["de", "of"], ["un", "a"], ["año?", "year?"]]},
  {num:7,words:[["¿Se", "[refl.]"], ["agradará", "shall-please"], ["Jehová", "jehovah"], ["de", "of"], ["millares", "thousands"], ["de", "of"], ["carneros", "rams"], ["o", "or"], ["de", "of"], ["diez", "ten"], ["mil", "thousand"], ["arroyos", "rivers"], ["de", "of"], ["aceite?", "oil?"], ["¿Daré", "I-shall-give"], ["mi", "my"], ["primogénito", "firstborn"], ["por", "by/for"], ["mi", "my"], ["rebelión,", "rebellion,"], ["el", "the"], ["fruto", "fruit"], ["de", "of"], ["mis", "my"], ["entrañas", "bowels"], ["por", "by/for"], ["el", "the"], ["pecado", "sin"], ["de", "of"], ["mi", "my"], ["alma?", "soul?"]]},
  {num:8,words:[["Oh", "oh"], ["hombre,", "man,"], ["él", "he"], ["te", "thee"], ["ha", "has"], ["declarado", "declared"], ["lo", "it/him"], ["que", "that"], ["es", "is"], ["bueno", "good"], ["y", "and"], ["lo", "it/him"], ["que", "that"], ["pide", "ask"], ["Jehová", "jehovah"], ["de", "of"], ["ti:", "thee:"], ["solamente", "only"], ["hacer", "make/do"], ["justicia,", "justice/righteousness,"], ["y", "and"], ["amar", "love"], ["la", "the"], ["misericordia", "mercy"], ["y", "and"], ["humillarte", "to"], ["para", "for"], ["andar", "walk"], ["con", "with"], ["tu", "thy"], ["Dios.", "God."]]},
  {num:9,words:[["La", "the"], ["voz", "voice"], ["de", "of"], ["Jehová", "jehovah"], ["clama", "crieth"], ["a", "to"], ["la", "the"], ["ciudad,", "city,"], ["y", "and"], ["sabio", "wise"], ["es", "is"], ["temer", "fear"], ["tu", "thy"], ["nombre.", "name."], ["Oíd", "hear"], ["la", "the"], ["vara,", "rod,"], ["y", "and"], ["a", "to"], ["quien", "who"], ["la", "the"], ["establece.", "it."]]},
  {num:10,words:[["¿Hay", "there-is"], ["aún", "still/yet"], ["en", "in"], ["casa", "house"], ["del", "of-the"], ["impío", "wicked"], ["tesoros", "treasures"], ["de", "of"], ["impiedad", "of"], ["y", "and"], ["medida", "measure"], ["escasa", "scant"], ["que", "that"], ["sea", "let-be/be"], ["detestable?", "abominable?"]]},
  {num:11,words:[["¿Debo", "must"], ["considerar", "i"], ["justas", "are"], ["la", "the"], ["balanza", "the"], ["falsa", "false"], ["y", "and"], ["la", "the"], ["bolsa", "purse"], ["de", "of"], ["pesas", "thes"], ["engañosas?", "weights?"]]},
  {num:12,words:[["Sus", "his/her"], ["ricos", "rich"], ["se", "[refl.]"], ["llenaron", "filled"], ["de", "of"], ["rapiña,", "to,"], ["y", "and"], ["sus", "his/her"], ["moradores", "inhabitants"], ["hablaron", "spake"], ["mentira,", "lies,"], ["y", "and"], ["su", "his/her"], ["lengua", "tongue"], ["es", "is"], ["engañosa", "is"], ["en", "in"], ["su", "his/her"], ["boca.", "mouth."]]},
  {num:13,words:[["Por", "by/for"], ["eso", "that"], ["yo", "I"], ["también", "also"], ["te", "thee"], ["debilitaré", "smiting"], ["hiriéndote,", "in,"], ["asolándote", "making"], ["por", "by/for"], ["tus", "thy"], ["pecados.", "sins."]]},
  {num:14,words:[["Tú", "thou"], ["comerás", "eat"], ["y", "and"], ["no", "not"], ["te", "thee"], ["saciarás,", "shalls,"], ["y", "and"], ["tu", "thy"], ["escasez", "down"], ["estará", "shall-be"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti;", "thee;"], ["y", "and"], ["tú", "thou"], ["recogerás,", "thou,"], ["pero", "but"], ["no", "not"], ["retendrás;", "not;"], ["y", "and"], ["lo", "it/him"], ["que", "that"], ["retengas,", "thou,"], ["lo", "it/him"], ["entregaré", "deliver"], ["yo", "I"], ["a", "to"], ["la", "the"], ["espada.", "sword."]]},
  {num:15,words:[["Tú", "thou"], ["sembrarás,", "shall-sow,"], ["mas", "but"], ["no", "not"], ["segarás;", "not;"], ["pisarás", "reap;"], ["aceitunas,", "thou,"], ["mas", "but"], ["no", "not"], ["te", "thee"], ["ungirás", "anoint"], ["con", "with"], ["el", "the"], ["aceite;", "oil;"], ["y", "and"], ["mosto,", "corn,"], ["mas", "but"], ["no", "not"], ["beberás", "drink"], ["el", "the"], ["vino.", "wine."]]},
  {num:16,words:[["Porque", "because"], ["los", "the"], ["estatutos", "statutes"], ["de", "of"], ["Omri", "omri"], ["se", "[refl.]"], ["han", "have"], ["guardado", "kept"], ["y", "and"], ["toda", "all"], ["obra", "work"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Acab;", "ahab;"], ["y", "and"], ["en", "in"], ["los", "the"], ["consejos", "counsels"], ["de", "of"], ["ellos", "they"], ["anduvisteis,", "counsels,"], ["para", "for"], ["que", "that"], ["yo", "I"], ["te", "thee"], ["entregase", "of-[refl.]"], ["a", "to"], ["la", "the"], ["desolación,", "desolation,"], ["y", "and"], ["a", "to"], ["tus", "thy"], ["moradores", "inhabitants"], ["a", "to"], ["la", "the"], ["burla.", "an."], ["Llevaréis,", "your,"], ["por", "by/for"], ["tanto,", "therefore,"], ["el", "the"], ["oprobio", "reproach"], ["de", "of"], ["mi", "my"], ["pueblo.", "people."]]},
];
renderVerseSet(v6, 'mic-ch6-verses');

var v7 = [
  {num:1,words:[["¡Ay", "wo"], ["de", "of"], ["mí!,", "me!,"], ["porque", "because"], ["he", "I-have"], ["venido", "come"], ["a", "to"], ["ser", "be"], ["como", "as"], ["cuando", "when"], ["han", "have"], ["recogido", "gathered"], ["los", "the"], ["frutos", "fruits"], ["del", "of-the"], ["verano,", "summer,"], ["como", "as"], ["cuando", "when"], ["han", "have"], ["rebuscado", "of"], ["después", "after/afterward"], ["de", "of"], ["la", "the"], ["vendimia", "there"], ["y", "and"], ["no", "not"], ["queda", "remaineth"], ["racimo", "to"], ["para", "for"], ["comer;", "eat;"], ["mi", "my"], ["alma", "soul"], ["deseó", "the"], ["los", "the"], ["primeros", "parents"], ["frutos.", "fruits."]]},
  {num:2,words:[["Ha", "has"], ["desaparecido", "of"], ["el", "the"], ["misericordioso", "merciful"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["y", "and"], ["ninguno", "none"], ["hay", "there-is"], ["recto", "upright"], ["entre", "among"], ["los", "the"], ["hombres;", "men;"], ["todos", "all"], ["acechan", "lie"], ["para", "for"], ["derramar", "shedding"], ["sangre;", "blood;"], ["cada", "each"], ["cual", "which"], ["tiende", "man"], ["red", "net"], ["a", "to"], ["su", "his/her"], ["hermano.", "brother."]]},
  {num:3,words:[["Para", "for"], ["completar", "they"], ["la", "the"], ["maldad", "wickedness"], ["con", "with"], ["sus", "his/her"], ["manos,", "hands,"], ["el", "the"], ["príncipe", "prince"], ["exige,", "prince,"], ["y", "and"], ["el", "the"], ["juez", "judge"], ["juzga", "judgeth"], ["por", "by/for"], ["recompensa;", "reward;"], ["y", "and"], ["el", "the"], ["poderoso", "mighty"], ["habla", "speaks"], ["según", "according-to"], ["el", "the"], ["capricho", "uttereth"], ["de", "of"], ["su", "his/her"], ["alma,", "soul,"], ["y", "and"], ["juntos", "together"], ["lo", "it/him"], ["traman.", "they."]]},
  {num:4,words:[["El", "the"], ["mejor", "better"], ["de", "of"], ["ellos", "they"], ["es", "is"], ["como", "as"], ["el", "the"], ["espino;", "brier;"], ["el", "the"], ["más", "more"], ["recto,", "upright,"], ["peor", "worse"], ["que", "that"], ["el", "the"], ["zarzal;", "thorn;"], ["el", "the"], ["día", "day"], ["de", "of"], ["tus", "thy"], ["atalayas", "watchmans"], ["y", "and"], ["de", "of"], ["tu", "thy"], ["castigo", "punishment"], ["viene;", "comes;"], ["ahora", "now"], ["será", "shall-be"], ["su", "his/her"], ["confusión.", "confusion."]]},
  {num:5,words:[["No", "not"], ["creáis", "believe"], ["en", "in"], ["amigo", "friend"], ["ni", "nor"], ["confiéis", "ye"], ["en", "in"], ["compañero;", "companion;"], ["de", "of"], ["la", "the"], ["que", "that"], ["duerme", "sleepeth"], ["a", "to"], ["tu", "thy"], ["lado,", "side,"], ["cuídate", "her"], ["de", "of"], ["abrir", "open"], ["tu", "thy"], ["boca.", "mouth."]]},
  {num:6,words:[["Porque", "because"], ["el", "the"], ["hijo", "son"], ["deshonra", "dishonoureth"], ["al", "to-the"], ["padre,", "father,"], ["la", "the"], ["hija", "daughter"], ["se", "[refl.]"], ["levanta", "raiseth"], ["contra", "against"], ["la", "the"], ["madre,", "mother,"], ["la", "the"], ["nuera", "daughter"], ["contra", "against"], ["su", "his/her"], ["suegra,", "mother,"], ["y", "and"], ["los", "the"], ["enemigos", "enemies"], ["del", "of-the"], ["hombre", "man"], ["son", "are"], ["los", "the"], ["de", "of"], ["su", "his/her"], ["propia", "own"], ["casa.", "house."]]},
  {num:7,words:[["Pero", "but"], ["yo", "I"], ["acudiré", "shall-come"], ["a", "to"], ["Jehová;", "jehovah;"], ["esperaré", "will"], ["al", "to-the"], ["Dios", "God"], ["de", "of"], ["mi", "my"], ["salvación;", "salvation;"], ["el", "the"], ["Dios", "God"], ["mío", "mine"], ["me", "me"], ["oirá.", "hear."]]},
  {num:8,words:[["Tú,", "thou,"], ["enemiga", "enemy"], ["mía,", "mother,"], ["no", "not"], ["te", "thee"], ["alegres", "tidings"], ["de", "of"], ["mí,", "me,"], ["porque", "because"], ["aunque", "although"], ["caí,", "me,"], ["he", "I-have"], ["de", "of"], ["levantarme;", "raise-me;"], ["aunque", "although"], ["more", "dwell"], ["en", "in"], ["tinieblas,", "darkness,"], ["Jehová", "jehovah"], ["será", "shall-be"], ["mi", "my"], ["luz.", "light."]]},
  {num:9,words:[["La", "the"], ["ira", "wrath"], ["de", "of"], ["Jehová", "jehovah"], ["soportaré,", "shall-bear,"], ["porque", "because"], ["pequé", "sinneth"], ["contra", "against"], ["él,", "he,"], ["hasta", "until"], ["que", "that"], ["juzgue", "judge"], ["mi", "my"], ["causa", "cause/sake"], ["y", "and"], ["me", "me"], ["haga", "let-do"], ["justicia.", "justice/righteousness."], ["Él", "he"], ["me", "me"], ["sacará", "bring"], ["a", "to"], ["la", "the"], ["luz;", "light;"], ["veré", "see"], ["su", "his/her"], ["justicia.", "justice/righteousness."]]},
  {num:10,words:[["Y", "and"], ["mi", "my"], ["enemiga", "enemy"], ["lo", "it/him"], ["verá", "see"], ["y", "and"], ["se", "[refl.]"], ["cubrirá", "cover"], ["de", "of"], ["vergüenza,", "shame,"], ["la", "the"], ["que", "that"], ["me", "me"], ["decía:", "said:"], ["¿Dónde", "where"], ["está", "is"], ["Jehová", "jehovah"], ["tu", "thy"], ["Dios?", "God?"], ["Mis", "my"], ["ojos", "eyes"], ["la", "the"], ["verán;", "see;"], ["ahora", "now"], ["será", "shall-be"], ["hollada", "trodden"], ["como", "as"], ["el", "the"], ["lodo", "mire"], ["de", "of"], ["las", "the"], ["calles.", "streets."]]},
  {num:11,words:[["El", "the"], ["día", "day"], ["en", "in"], ["que", "that"], ["se", "[refl.]"], ["reedifiquen", "to"], ["tus", "thy"], ["muros,", "walls,"], ["aquel", "that"], ["día", "day"], ["se", "[refl.]"], ["extenderán", "spread"], ["los", "the"], ["límites.", "bounds."]]},
  {num:12,words:[["En", "in"], ["ese", "that"], ["día", "day"], ["vendrán", "far"], ["hasta", "until"], ["ti", "thee"], ["desde", "from"], ["Asiria", "assyria"], ["y", "and"], ["desde", "from"], ["las", "the"], ["ciudades", "cities"], ["de", "of"], ["Egipto,", "Egypt,"], ["y", "and"], ["desde", "from"], ["Egipto", "Egypt"], ["hasta", "until"], ["el", "the"], ["río,", "river,"], ["y", "and"], ["de", "of"], ["mar", "sea"], ["a", "to"], ["mar", "sea"], ["y", "and"], ["de", "of"], ["monte", "mount"], ["a", "to"], ["monte.", "mount."]]},
  {num:13,words:[["Y", "and"], ["la", "the"], ["tierra", "land/earth"], ["será", "shall-be"], ["asolada", "desolate"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["sus", "his/her"], ["moradores,", "inhabitants,"], ["por", "by/for"], ["el", "the"], ["fruto", "fruit"], ["de", "of"], ["sus", "his/her"], ["obras.", "works."]]},
  {num:14,words:[["Apacienta", "he"], ["a", "to"], ["tu", "thy"], ["pueblo", "people"], ["con", "with"], ["tu", "thy"], ["cayado,", "the,"], ["el", "the"], ["rebaño", "flock"], ["de", "of"], ["tu", "thy"], ["heredad,", "heritage,"], ["que", "that"], ["mora", "dwelleth"], ["solitario", "in"], ["en", "in"], ["el", "the"], ["bosque,", "forest,"], ["en", "in"], ["medio", "midst"], ["del", "of-the"], ["Carmelo;", "carmel;"], ["que", "that"], ["se", "[refl.]"], ["apacienten", "in"], ["en", "in"], ["Basán", "bashan"], ["y", "and"], ["Galaad,", "Gilead,"], ["como", "as"], ["en", "in"], ["el", "the"], ["tiempo", "time"], ["pasado.", "past."]]},
  {num:15,words:[["Yo", "I"], ["les", "them"], ["mostraré", "I-shall-show"], ["maravillas", "wondrous"], ["como", "as"], ["el", "the"], ["día", "day"], ["en", "in"], ["que", "that"], ["saliste", "out"], ["de", "of"], ["Egipto.", "Egypt."]]},
  {num:16,words:[["Las", "the"], ["naciones", "nations"], ["verán", "see"], ["y", "and"], ["se", "[refl.]"], ["avergonzarán", "ashamed"], ["de", "of"], ["todo", "all"], ["su", "his/her"], ["poderío;", "shall;"], ["pondrán", "lay"], ["la", "the"], ["mano", "hand"], ["sobre", "upon"], ["su", "his/her"], ["boca;", "mouth;"], ["se", "[refl.]"], ["ensordecerán", "ears"], ["sus", "his/her"], ["oídos.", "ears."]]},
  {num:17,words:[["Lamerán", "they"], ["el", "the"], ["polvo", "dust"], ["como", "as"], ["la", "the"], ["culebra,", "a,"], ["como", "as"], ["las", "the"], ["serpientes", "serpents"], ["de", "of"], ["la", "the"], ["tierra;", "land/earth;"], ["saldrán", "forth"], ["temblando", "and"], ["de", "of"], ["sus", "his/her"], ["escondrijos;", "places;"], ["tendrán", "power"], ["miedo", "afraid"], ["de", "of"], ["Jehová", "jehovah"], ["nuestro", "our"], ["Dios", "God"], ["y", "and"], ["temerán", "fear"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["ti.", "thee."]]},
  {num:18,words:[["¿Qué", "what"], ["Dios", "God"], ["hay", "there-is"], ["como", "as"], ["tú,", "thou,"], ["que", "that"], ["perdona", "forgive"], ["la", "the"], ["iniquidad", "iniquity"], ["y", "and"], ["olvida", "passeth"], ["el", "the"], ["pecado", "sin"], ["del", "of-the"], ["remanente", "remnant"], ["de", "of"], ["su", "his/her"], ["heredad?", "heritage?"], ["No", "not"], ["retiene", "he"], ["para", "for"], ["siempre", "always"], ["su", "his/her"], ["enojo,", "fury,"], ["porque", "because"], ["se", "[refl.]"], ["deleita", "delighteth"], ["en", "in"], ["la", "the"], ["misericordia.", "mercy."]]},
  {num:19,words:[["Él", "he"], ["volverá;", "return;"], ["volverá", "return"], ["a", "to"], ["tener", "have"], ["misericordia", "mercy"], ["de", "of"], ["nosotros;", "we;"], ["él", "he"], ["hollará", "will"], ["nuestras", "provisions"], ["iniquidades", "iniquities"], ["y", "and"], ["echará", "cast"], ["en", "in"], ["lo", "it/him"], ["profundo", "deep"], ["del", "of-the"], ["mar", "sea"], ["todos", "all"], ["nuestros", "our"], ["pecados.", "sins."]]},
  {num:20,words:[["Otorgarás", "thou"], ["a", "to"], ["Jacob", "Jacob"], ["la", "the"], ["verdad", "truth"], ["y", "and"], ["a", "to"], ["Abraham", "Abraham"], ["la", "the"], ["misericordia,", "mercy,"], ["como", "as"], ["juraste", "sweareths-thee"], ["a", "to"], ["nuestros", "our"], ["padres", "parents"], ["desde", "from"], ["tiempos", "times"], ["antiguos.", "ancient."]]},
];
renderVerseSet(v7, 'mic-ch7-verses');

})();
