(function() {
var v1 = [
  {num:1,words:[["Profecía", "prophecy"], ["acerca", "about"], ["de", "of"], ["Nínive.", "nineveh."], ["Libro", "book"], ["de", "of"], ["la", "the"], ["visión", "vision"], ["de", "of"], ["Nahúm", "nahum"], ["de", "of"], ["Elcos.", "elkoshite."]]},
  {num:2,words:[["Dios", "God"], ["celoso", "jealous"], ["y", "and"], ["vengador", "blood"], ["es", "is"], ["Jehová;", "jehovah;"], ["vengador", "blood"], ["es", "is"], ["Jehová", "jehovah"], ["y", "and"], ["lleno", "full"], ["de", "of"], ["indignación;", "indignation;"], ["Jehová", "jehovah"], ["se", "[refl.]"], ["venga", "let-come"], ["de", "of"], ["sus", "his/her"], ["adversarios", "adversaries"], ["y", "and"], ["guarda", "keeps"], ["enojo", "fury"], ["para", "for"], ["sus", "his/her"], ["enemigos.", "enemies."]]},
  {num:3,words:[["Jehová", "jehovah"], ["es", "is"], ["tardo", "slow"], ["para", "for"], ["la", "the"], ["ira", "wrath"], ["y", "and"], ["grande", "great"], ["en", "in"], ["poder,", "power/can,"], ["y", "and"], ["no", "not"], ["tendrá", "shall-have"], ["por", "by/for"], ["inocente", "innocent"], ["al", "to-the"], ["culpable.", "guilty."], ["Jehová", "jehovah"], ["marcha", "march"], ["en", "in"], ["el", "the"], ["torbellino", "whirlwind"], ["y", "and"], ["en", "in"], ["la", "the"], ["tempestad,", "storm,"], ["y", "and"], ["las", "the"], ["nubes", "clouds"], ["son", "are"], ["el", "the"], ["polvo", "dust"], ["de", "of"], ["sus", "his/her"], ["pies.", "feet."]]},
  {num:4,words:[["Él", "he"], ["reprende", "of"], ["al", "to-the"], ["mar", "sea"], ["y", "and"], ["lo", "it/him"], ["hace", "does/makes"], ["secar", "up"], ["y", "and"], ["agota", "drieth"], ["todos", "all"], ["los", "the"], ["ríos.", "rivers."], ["Basán", "bashan"], ["y", "and"], ["el", "the"], ["Carmelo", "carmel"], ["languidecen,", "and,"], ["y", "and"], ["la", "the"], ["flor", "flower"], ["del", "of-the"], ["Líbano", "lebanon"], ["se", "[refl.]"], ["marchita.", "little-march."]]},
  {num:5,words:[["Los", "the"], ["montes", "mountains"], ["tiemblan", "quake"], ["delante", "before"], ["de", "of"], ["él,", "he,"], ["y", "and"], ["los", "the"], ["collados", "hills"], ["se", "[refl.]"], ["derriten;", "melt;"], ["y", "and"], ["la", "the"], ["tierra", "land/earth"], ["se", "[refl.]"], ["agita", "burned"], ["ante", "before"], ["su", "his/her"], ["presencia,", "presence,"], ["y", "and"], ["también", "also"], ["el", "the"], ["mundo", "world"], ["y", "and"], ["todos", "all"], ["los", "the"], ["que", "that"], ["en", "in"], ["él", "he"], ["habitan.", "dwell."]]},
  {num:6,words:[["¿Quién", "who"], ["permanecerá", "stand"], ["delante", "before"], ["de", "of"], ["su", "his/her"], ["ira?", "wrath?"], ["¿Quién", "who"], ["quedará", "shall-remain"], ["en", "in"], ["pie", "foot"], ["ante", "before"], ["el", "the"], ["furor", "fury"], ["de", "of"], ["su", "his/her"], ["enojo?", "fury?"], ["Su", "his/her"], ["ira", "wrath"], ["se", "[refl.]"], ["derrama", "upon"], ["como", "as"], ["fuego,", "fire,"], ["y", "and"], ["por", "by/for"], ["él", "he"], ["se", "[refl.]"], ["hienden", "down"], ["las", "the"], ["peñas.", "rocks."]]},
  {num:7,words:[["Jehová", "jehovah"], ["es", "is"], ["bueno,", "good,"], ["fortaleza", "castle"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["angustia,", "anguish,"], ["y", "and"], ["conoce", "knoweth"], ["a", "to"], ["los", "the"], ["que", "that"], ["en", "in"], ["él", "he"], ["confían.", "trust."]]},
  {num:8,words:[["Mas", "but"], ["con", "with"], ["inundación", "overrunning"], ["impetuosa", "flood"], ["hará", "shall-make"], ["consumación", "shall"], ["de", "of"], ["su", "his/her"], ["lugar,", "place,"], ["y", "and"], ["las", "the"], ["tinieblas", "darkness"], ["perseguirán", "shall"], ["a", "to"], ["sus", "his/her"], ["enemigos.", "enemies."]]},
  {num:9,words:[["¿Qué", "what"], ["tramáis", "ye"], ["contra", "against"], ["Jehová?", "jehovah?"], ["Él", "he"], ["hará", "shall-make"], ["consumación;", "shall;"], ["la", "the"], ["tribulación", "tribulation"], ["no", "not"], ["se", "[refl.]"], ["levantará", "raise"], ["dos", "two"], ["veces.", "times."]]},
  {num:10,words:[["Porque", "because"], ["como", "as"], ["espinos", "briers"], ["entretejidos", "folden"], ["y", "and"], ["como", "as"], ["ebrios", "while"], ["en", "in"], ["su", "his/her"], ["embriaguez,", "as,"], ["serán", "shall-be"], ["consumidos", "consumed"], ["como", "as"], ["rastrojo", "stubble"], ["completamente", "utterly"], ["seco.", "dry."]]},
  {num:11,words:[["De", "of"], ["ti", "thee"], ["salió", "departed"], ["el", "the"], ["que", "that"], ["tramó", "thee,"], ["el", "the"], ["mal", "evil"], ["contra", "against"], ["Jehová,", "jehovah,"], ["un", "a"], ["consejero", "counselor"], ["perverso.", "wicked."]]},
  {num:12,words:[["Así", "thus"], ["ha", "has"], ["dicho", "said"], ["Jehová:", "jehovah:"], ["Aunque", "although"], ["reposo", "rest"], ["tengan", "let-have"], ["y", "and"], ["sean", "let-be"], ["muchos,", "many,"], ["aun", "even"], ["así", "thus"], ["serán", "shall-be"], ["talados,", "hewn,"], ["y", "and"], ["pasarán.", "away."], ["Aunque", "although"], ["te", "thee"], ["he", "I-have"], ["afligido,", "afflicted,"], ["no", "not"], ["te", "thee"], ["afligiré", "thee"], ["más.", "more."]]},
  {num:13,words:[["Porque", "because"], ["ahora", "now"], ["quebraré", "i"], ["su", "his/her"], ["yugo", "yoke"], ["de", "of"], ["sobre", "upon"], ["ti", "thee"], ["y", "and"], ["romperé", "thy"], ["tus", "thy"], ["coyundas.", "and."]]},
  {num:14,words:[["Pero", "but"], ["acerca", "about"], ["de", "of"], ["ti", "thee"], ["ha", "has"], ["mandado", "commanded"], ["Jehová", "jehovah"], ["que", "that"], ["no", "not"], ["sea", "let-be/be"], ["perpetuado", "name"], ["tu", "thy"], ["nombre;", "name;"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["tu", "thy"], ["dios", "God"], ["talaré", "cut"], ["imágenes", "groves"], ["talladas", "graven"], ["e", "and"], ["imágenes", "groves"], ["de", "of"], ["fundición;", "molten;"], ["prepararé", "will"], ["tu", "thy"], ["sepulcro,", "sepulchre,"], ["porque", "because"], ["fuiste", "wast"], ["vil.", "the."]]},
  {num:15,words:[["¡He", "I-have"], ["aquí", "here"], ["sobre", "upon"], ["los", "the"], ["montes", "mountains"], ["los", "the"], ["pies", "feet"], ["del", "of-the"], ["que", "that"], ["trae", "bringeth"], ["buenas", "good"], ["nuevas,", "new,"], ["del", "of-the"], ["que", "that"], ["anuncia", "the"], ["la", "the"], ["paz!", "peace!"], ["Celebra,", "keep,"], ["oh", "oh"], ["Judá,", "Judah,"], ["tus", "thy"], ["fiestas", "moons"], ["solemnes,", "moons,"], ["cumple", "thou"], ["tus", "thy"], ["votos,", "vows,"], ["porque", "because"], ["ya", "already"], ["nunca", "never"], ["más", "more"], ["pasará", "through"], ["sobre", "upon"], ["ti", "thee"], ["el", "the"], ["malvado;", "wicked;"], ["ha", "has"], ["perecido", "perished"], ["del", "of-the"], ["todo.", "all."]]},
];
renderVerseSet(v1, 'nah-ch1-verses');

var v2 = [
  {num:1,words:[["Un", "a"], ["destructor", "spoiler"], ["ha", "has"], ["subido", "gone-up"], ["contra", "against"], ["ti;", "thee;"], ["guarda", "keeps"], ["la", "the"], ["fortaleza,", "castle,"], ["vigila", "the"], ["el", "the"], ["camino,", "way,"], ["fortifica", "way,"], ["tus", "thy"], ["lomos,", "loins,"], ["fortalece", "strong,"], ["mucho", "much"], ["tu", "thy"], ["poder.", "power/can."]]},
  {num:2,words:[["Porque", "because"], ["Jehová", "jehovah"], ["restaurará", "hath"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["Jacob", "Jacob"], ["como", "as"], ["la", "the"], ["gloria", "glory"], ["de", "of"], ["Israel;", "Israel;"], ["porque", "because"], ["saqueadores", "have"], ["los", "the"], ["saquearon", "them"], ["y", "and"], ["destruyeron", "destroyed"], ["sus", "his/her"], ["sarmientos.", "of."]]},
  {num:3,words:[["El", "the"], ["escudo", "shield"], ["de", "of"], ["sus", "his/her"], ["guerreros", "the"], ["se", "[refl.]"], ["ha", "has"], ["enrojecido,", "red,"], ["los", "the"], ["hombres", "men"], ["valientes", "valour"], ["vestidos", "garments"], ["de", "of"], ["grana;", "scarlet;"], ["el", "the"], ["día", "day"], ["en", "in"], ["que", "that"], ["se", "[refl.]"], ["preparen,", "the,"], ["los", "the"], ["carros", "chariots"], ["serán", "shall-be"], ["como", "as"], ["fuego", "fire"], ["de", "of"], ["antorchas,", "the,"], ["y", "and"], ["temblarán", "tremble"], ["los", "the"], ["cipreses.", "fir."]]},
  {num:4,words:[["Los", "the"], ["carros", "chariots"], ["se", "[refl.]"], ["precipitarán", "in"], ["a", "to"], ["las", "the"], ["plazas;", "strongholds;"], ["con", "with"], ["estruendo", "noise"], ["rodarán", "against"], ["por", "by/for"], ["las", "the"], ["calles;", "streets;"], ["su", "his/her"], ["aspecto", "appearance"], ["será", "shall-be"], ["como", "as"], ["antorchas", "the"], ["encendidas;", "offerings;"], ["correrán", "run"], ["como", "as"], ["relámpagos.", "lightnings."]]},
  {num:5,words:[["Convocará", "he"], ["él", "he"], ["a", "to"], ["sus", "his/her"], ["valientes;", "valour;"], ["al", "to-the"], ["andar", "walk"], ["tropezarán;", "shall;"], ["se", "[refl.]"], ["apresurarán", "make"], ["hacia", "toward"], ["su", "his/her"], ["muro,", "wall,"], ["y", "and"], ["la", "the"], ["defensa", "defense"], ["se", "[refl.]"], ["preparará.", "prepare."]]},
  {num:6,words:[["Las", "the"], ["compuertas", "gates"], ["de", "of"], ["los", "the"], ["ríos", "rivers"], ["se", "[refl.]"], ["abrirán,", "shall,"], ["y", "and"], ["el", "the"], ["palacio", "palace"], ["será", "shall-be"], ["arrasado.", "dissolved."]]},
  {num:7,words:[["Y", "and"], ["la", "the"], ["reina", "queen"], ["será", "shall-be"], ["llevada", "into"], ["cautiva;", "captive;"], ["mandarán", "shall"], ["que", "that"], ["suba,", "up,"], ["y", "and"], ["sus", "his/her"], ["criadas", "in"], ["la", "the"], ["llevarán", "bear"], ["gimiendo", "the"], ["como", "as"], ["palomas,", "doves,"], ["golpeándose", "tabering"], ["el", "the"], ["pecho.", "breast."]]},
  {num:8,words:[["Y", "and"], ["Nínive", "nineveh"], ["es", "is"], ["de", "of"], ["tiempo", "time"], ["antiguo", "ancient"], ["como", "as"], ["estanque", "pool"], ["de", "of"], ["aguas;", "waters;"], ["mas", "but"], ["ellos", "they"], ["huyen", "away."], ["y", "and"], ["dicen:", "say:"], ["¡Deteneos,", "shall,"], ["deteneos!,", "they!,"], ["pero", "but"], ["ninguno", "none"], ["mira", "look"], ["hacia", "toward"], ["atrás.", "backward."]]},
  {num:9,words:[["Saquead", "take"], ["plata,", "silver,"], ["saquead", "spoil"], ["oro;", "gold;"], ["no", "not"], ["hay", "there-is"], ["fin", "end"], ["de", "of"], ["las", "the"], ["riquezas", "riches"], ["ni", "nor"], ["de", "of"], ["la", "the"], ["suntuosidad", "store"], ["de", "of"], ["toda", "all"], ["clase", "class/kind"], ["de", "of"], ["objetos", "things"], ["preciosos.", "precious."]]},
  {num:10,words:[["Vacía,", "void,"], ["y", "and"], ["agotada", "empty,"], ["y", "and"], ["desolada", "desolate"], ["está,", "is,"], ["y", "and"], ["el", "the"], ["corazón", "heart"], ["desfallecido;", "and;"], ["temblor", "trembling"], ["de", "of"], ["rodillas", "knees"], ["y", "and"], ["dolor", "pain"], ["en", "in"], ["todos", "all"], ["los", "the"], ["lomos,", "loins,"], ["y", "and"], ["los", "the"], ["rostros", "faces"], ["de", "of"], ["todos", "all"], ["se", "[refl.]"], ["demudan.", "blackness."]]},
  {num:11,words:[["¿Dónde", "where"], ["está", "is"], ["la", "the"], ["guarida", "a"], ["de", "of"], ["los", "the"], ["leones", "lions"], ["y", "and"], ["el", "the"], ["lugar", "place"], ["donde", "where"], ["comen", "eat"], ["los", "the"], ["cachorros", "whelps"], ["de", "of"], ["los", "the"], ["leones,", "lions,"], ["donde", "where"], ["andaba", "walked"], ["el", "the"], ["león,", "lion,"], ["la", "the"], ["leona", "lion,"], ["y", "and"], ["el", "the"], ["cachorro", "lion"], ["de", "of"], ["león,", "lion,"], ["y", "and"], ["no", "not"], ["había", "had"], ["quien", "who"], ["los", "the"], ["espantase?", "afraid?"]]},
  {num:12,words:[["El", "the"], ["león", "lion"], ["arrebataba", "did"], ["lo", "it/him"], ["suficiente", "sufficient"], ["para", "for"], ["sus", "his/her"], ["cachorros", "whelps"], ["y", "and"], ["estrangulaba", "whelps,"], ["para", "for"], ["sus", "his/her"], ["leonas;", "for;"], ["y", "and"], ["llenaba", "and"], ["de", "of"], ["presas", "preys"], ["sus", "his/her"], ["madrigueras", "with"], ["y", "and"], ["de", "of"], ["carne", "flesh"], ["desgarrada", "dens"], ["sus", "his/her"], ["guaridas.", "as."]]},
  {num:13,words:[["Heme", "here"], ["aquí", "here"], ["contra", "against"], ["ti,", "thee,"], ["dice", "says"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos,", "armies,"], ["y", "and"], ["quemaré", "will"], ["tus", "thy"], ["carros", "chariots"], ["y", "and"], ["los", "the"], ["reduciré", "smoke,"], ["a", "to"], ["humo,", "smoke,"], ["y", "and"], ["la", "the"], ["espada", "sword"], ["devorará", "devour"], ["tus", "thy"], ["leoncillos;", "lions;"], ["y", "and"], ["raeré", "will"], ["de", "of"], ["la", "the"], ["tierra", "land/earth"], ["tu", "thy"], ["presa,", "prey,"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["se", "[refl.]"], ["oirá", "hear"], ["la", "the"], ["voz", "voice"], ["de", "of"], ["tus", "thy"], ["mensajeros.", "messengers."]]},
];
renderVerseSet(v2, 'nah-ch2-verses');

var v3 = [
  {num:1,words:[["¡Ay", "wo"], ["de", "of"], ["la", "the"], ["ciudad", "city"], ["sanguinaria,", "it,"], ["toda", "all"], ["llena", "full"], ["de", "of"], ["mentira", "lies"], ["y", "and"], ["de", "of"], ["rapiña,", "to,"], ["de", "of"], ["incesante", "departeth"], ["pillaje!", "not!"]]},
  {num:2,words:[["Chasquido", "the"], ["de", "of"], ["látigo", "a"], ["y", "and"], ["estruendo", "noise"], ["de", "of"], ["movimiento", "of"], ["de", "of"], ["ruedas;", "wheels;"], ["y", "and"], ["caballo", "horse"], ["al", "to-the"], ["galope", "pransing"], ["y", "and"], ["carro", "cart"], ["que", "that"], ["salta;", "chariots;"]]},
  {num:3,words:[["el", "the"], ["jinete", "the"], ["a", "to"], ["la", "the"], ["carga,", "burden,"], ["y", "and"], ["resplandor", "luster"], ["de", "of"], ["espada", "sword"], ["y", "and"], ["brillo", "brightness"], ["de", "of"], ["lanza;", "spear;"], ["y", "and"], ["multitud", "multitude"], ["de", "of"], ["muertos", "dead"], ["y", "and"], ["multitud", "multitude"], ["de", "of"], ["cadáveres;", "bodies;"], ["y", "and"], ["cadáveres", "bodies"], ["sin", "without"], ["fin,", "end,"], ["y", "and"], ["con", "with"], ["los", "the"], ["cadáveres", "bodies"], ["tropezarán.", "shall."]]},
  {num:4,words:[["Y", "and"], ["esto", "this"], ["a", "to"], ["causa", "cause/sake"], ["de", "of"], ["la", "the"], ["multitud", "multitude"], ["de", "of"], ["las", "the"], ["fornicaciones", "whoredoms"], ["de", "of"], ["la", "the"], ["ramera", "whore"], ["de", "of"], ["hermosa", "beautiful"], ["gracia,", "grace,"], ["maestra", "teacher"], ["de", "of"], ["brujerías,", "witchcrafts,"], ["que", "that"], ["vende", "he"], ["a", "to"], ["las", "the"], ["naciones", "nations"], ["con", "with"], ["sus", "his/her"], ["fornicaciones", "whoredoms"], ["y", "and"], ["a", "to"], ["las", "the"], ["familias", "families"], ["con", "with"], ["sus", "his/her"], ["hechicerías.", "of."]]},
  {num:5,words:[["Heme", "here"], ["aquí", "here"], ["contra", "against"], ["ti,", "thee,"], ["dice", "says"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos;", "armies;"], ["y", "and"], ["levantaré", "raise"], ["tus", "thy"], ["faldas", "the"], ["hasta", "until"], ["tu", "thy"], ["cara", "face"], ["y", "and"], ["mostraré", "show"], ["a", "to"], ["las", "the"], ["naciones", "nations"], ["tu", "thy"], ["desnudez,", "nakedness,"], ["y", "and"], ["a", "to"], ["los", "the"], ["reinos", "kingdoms"], ["tu", "thy"], ["vergüenza.", "shame."]]},
  {num:6,words:[["Y", "and"], ["echaré", "cast"], ["sobre", "upon"], ["ti", "thee"], ["inmundicias,", "filthinesss,"], ["y", "and"], ["te", "thee"], ["haré", "I-shall-make"], ["despreciable", "vile,"], ["y", "and"], ["te", "thee"], ["pondré", "I-shall-put"], ["como", "as"], ["espectáculo.", "gazingstock."]]},
  {num:7,words:[["Y", "and"], ["acontecerá", "shall-come-to-pass"], ["que", "that"], ["todos", "all"], ["los", "the"], ["que", "that"], ["te", "thee"], ["vean", "see"], ["se", "[refl.]"], ["apartarán", "upon"], ["de", "of"], ["ti", "thee"], ["y", "and"], ["dirán:", "say:"], ["¡Nínive", "nineveh"], ["ha", "has"], ["sido", "been"], ["asolada!", "desolate!"], ["¿Quién", "who"], ["se", "[refl.]"], ["compadecerá", "bemoan"], ["de", "of"], ["ella?", "she?"], ["¿Dónde", "where"], ["te", "thee"], ["buscaré", "will"], ["consoladores?", "comforters?"]]},
  {num:8,words:[["¿Eres", "thou-art"], ["tú", "thou"], ["mejor", "better"], ["que", "that"], ["Tebas,", "no,"], ["que", "that"], ["estaba", "was"], ["asentada", "among"], ["entre", "among"], ["ríos,", "rivers,"], ["rodeada", "surrounded"], ["de", "of"], ["aguas,", "waters,"], ["cuyo", "whose"], ["baluarte", "whose"], ["era", "was"], ["el", "the"], ["mar", "sea"], ["y", "and"], ["el", "the"], ["mar", "sea"], ["su", "his/her"], ["muralla?", "wall?"]]},
  {num:9,words:[["Etiopía", "ethiopia"], ["era", "was"], ["su", "his/her"], ["fortaleza,", "castle,"], ["y", "and"], ["Egipto,", "Egypt,"], ["y", "and"], ["eso", "that"], ["sin", "without"], ["límite;", "border;"], ["Fut", "infinite;"], ["y", "and"], ["Libia", "and"], ["estaban", "were"], ["entre", "among"], ["tus", "thy"], ["ayudadores.", "helpers."]]},
  {num:10,words:[["No", "not"], ["obstante,", "withstanding,"], ["ella", "she"], ["fue", "was/went"], ["desterrada,", "the,"], ["llevada", "into"], ["al", "to-the"], ["cautiverio;", "captivity;"], ["también", "also"], ["sus", "his/her"], ["niños", "children"], ["fueron", "were"], ["estrellados", "dashed"], ["en", "in"], ["las", "the"], ["encrucijadas", "the"], ["de", "of"], ["todas", "all"], ["las", "the"], ["calles;", "streets;"], ["y", "and"], ["sobre", "upon"], ["sus", "his/her"], ["nobles", "nobles"], ["echaron", "lots"], ["suertes,", "lots,"], ["y", "and"], ["todos", "all"], ["sus", "his/her"], ["grandes", "great"], ["fueron", "were"], ["aprisionados", "were"], ["con", "with"], ["grilletes.", "chains."]]},
  {num:11,words:[["Tú", "thou"], ["también", "also"], ["quedarás", "shalt"], ["embriagada;", "drunken;"], ["serás", "thou-shalt-be"], ["ocultada;", "shalt;"], ["tú", "thou"], ["también", "also"], ["buscarás", "also"], ["refugio", "refuge"], ["a", "to"], ["causa", "cause/sake"], ["del", "of-the"], ["enemigo.", "enemy."]]},
  {num:12,words:[["Todas", "all"], ["tus", "thy"], ["fortalezas", "holds"], ["serán", "shall-be"], ["cual", "which"], ["higueras", "figs"], ["cargadas", "fig"], ["de", "of"], ["brevas,", "with,"], ["que,", "that,"], ["si", "if"], ["las", "the"], ["sacuden,", "they,"], ["caen", "fall"], ["en", "in"], ["la", "the"], ["boca", "mouth"], ["del", "of-the"], ["que", "that"], ["las", "the"], ["ha", "has"], ["de", "of"], ["comer.", "eat."]]},
  {num:13,words:[["He", "I-have"], ["aquí,", "here,"], ["tu", "thy"], ["pueblo", "people"], ["será", "shall-be"], ["como", "as"], ["mujeres", "women"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti;", "thee;"], ["las", "the"], ["puertas", "gates"], ["de", "of"], ["tu", "thy"], ["tierra", "land/earth"], ["se", "[refl.]"], ["abrirán", "shall"], ["de", "of"], ["par", "of"], ["en", "in"], ["par", "of"], ["a", "to"], ["tus", "thy"], ["enemigos;", "enemies;"], ["fuego", "fire"], ["consumirá", "palaces"], ["tus", "thy"], ["cerrojos.", "bars."]]},
  {num:14,words:[["Provéete", "draw"], ["de", "of"], ["agua", "water"], ["para", "for"], ["el", "the"], ["asedio;", "siege;"], ["fortifica", "thy"], ["tus", "thy"], ["fortalezas;", "holds;"], ["entra", "enter"], ["en", "in"], ["el", "the"], ["lodo;", "mire;"], ["pisa", "tread"], ["el", "the"], ["barro;", "earthen;"], ["refuerza", "strong"], ["el", "the"], ["horno.", "furnace."]]},
  {num:15,words:[["Allí", "there"], ["te", "thee"], ["consumirá", "palaces"], ["el", "the"], ["fuego;", "fire;"], ["te", "thee"], ["talará", "cut"], ["la", "the"], ["espada.", "sword."], ["Te", "thee"], ["devorará", "devour"], ["como", "as"], ["el", "the"], ["pulgón.", "cankerworm."], ["¡Multiplícate", "make"], ["como", "as"], ["el", "the"], ["pulgón!", "cankerworm!"], ["¡Multiplícate", "make"], ["como", "as"], ["la", "the"], ["langosta!", "locust!"]]},
  {num:16,words:[["Multiplicaste", "thou"], ["tus", "thy"], ["mercaderes", "merchants"], ["más", "more"], ["que", "that"], ["las", "the"], ["estrellas", "stars"], ["del", "of-the"], ["cielo;", "heaven;"], ["el", "the"], ["pulgón", "cankerworm"], ["hizo", "made/did"], ["presa", "prey"], ["y", "and"], ["voló.", "away."]]},
  {num:17,words:[["Tus", "thy"], ["príncipes", "princes"], ["serán", "shall-be"], ["como", "as"], ["langostas", "as"], ["y", "and"], ["tus", "thy"], ["oficiales", "officers"], ["como", "as"], ["nubes", "clouds"], ["de", "of"], ["langostas", "as"], ["que", "that"], ["se", "[refl.]"], ["posan", "the"], ["en", "in"], ["vallados", "ands"], ["en", "in"], ["día", "day"], ["de", "of"], ["frío;", "cold;"], ["salido", "gone-out"], ["el", "the"], ["sol", "sun"], ["se", "[refl.]"], ["van,", "go,"], ["y", "and"], ["no", "not"], ["se", "[refl.]"], ["conoce", "knoweth"], ["el", "the"], ["lugar", "place"], ["donde", "where"], ["están.", "are."]]},
  {num:18,words:[["Durmieron", "they"], ["tus", "thy"], ["pastores,", "pastors,"], ["oh", "oh"], ["rey", "king"], ["de", "of"], ["Asiria;", "assyria;"], ["reposaron", "nobles"], ["tus", "thy"], ["nobles;", "nobles;"], ["tu", "thy"], ["pueblo", "people"], ["se", "[refl.]"], ["dispersó", "people"], ["por", "by/for"], ["los", "the"], ["montes,", "mountains,"], ["y", "and"], ["no", "not"], ["hay", "there-is"], ["quien", "who"], ["lo", "it/him"], ["junte.", "them."]]},
  {num:19,words:[["No", "not"], ["hay", "there-is"], ["curación", "no"], ["para", "for"], ["tu", "thy"], ["quebradura;", "thy;"], ["tu", "thy"], ["herida", "wound"], ["es", "is"], ["grave.", "grievous."], ["Todos", "all"], ["los", "the"], ["que", "that"], ["oigan", "hear"], ["noticias", "theys"], ["de", "of"], ["ti", "thee"], ["batirán", "thee"], ["las", "the"], ["palmas", "hands"], ["de", "of"], ["las", "the"], ["manos", "hands"], ["acerca", "about"], ["de", "of"], ["ti,", "thee,"], ["porque,", "because,"], ["¿sobre", "upon"], ["quién", "who"], ["no", "not"], ["pasó", "passed"], ["continuamente", "continually"], ["tu", "thy"], ["maldad?", "wickedness?"]]},
];
renderVerseSet(v3, 'nah-ch3-verses');

})();
