(function() {
var v1 = [
  {num:1,words:[["Profecía", "prophecy"], ["acerca", "about"], ["de", "of"], ["Nínive.","Nineveh."], ["Libro", "book"], ["de", "of"], ["la", "the"], ["visión", "vision"], ["de", "of"], ["Nahúm", "nahum"], ["de", "of"], ["Elcos.", "elkoshite."]]},
  {num:2,words:[["Dios", "God"], ["celoso", "jealous"], ["y", "and"], ["vengador", "blood"], ["es", "is"], ["Jehová;", "jehovah;"], ["vengador", "blood"], ["es", "is"], ["Jehová", "jehovah"], ["y", "and"], ["lleno", "full"], ["de", "of"], ["indignación;", "indignation;"], ["Jehová", "jehovah"], ["se", "[refl.]"], ["venga", "let-come"], ["de", "of"], ["sus","his"], ["adversarios", "adversaries"], ["y", "and"], ["guarda", "keeps"], ["enojo", "fury"], ["para", "for"], ["sus","his"], ["enemigos.", "enemies."]]},
  {num:3,words:[["Jehová","jehovah"],["es","is"],["tardo","slow"],["para","for"],["la","the"],["ira","wrath"],["y","and"],["grande","great"],["en","in"],["poder,","power,"],["y","and"],["no","not"],["tendrá","will have"],["por","by/for"],["inocente","innocent"],["al","to-the"],["culpable.","guilty."],["Jehová","jehovah"],["marcha","march"],["en","in"],["el","the"],["torbellino","whirlwind"],["y","and"],["en","in"],["la","the"],["tempestad,","storm,"],["y","and"],["las","the"],["nubes","clouds"],["son","they-are"],["el","the"],["polvo","dust"],["de","of"],["sus","his"],["pies.","feet."]]},
  {num:4,words:[["Él","he"],["reprende","reprimands"],["al","to-the"],["mar","sea"],["y","and"],["lo","it"],["hace","does/makes"],["secar","up"],["y","and"],["agota","dries"],["todos","all"],["los","the"],["ríos.","rivers."],["Basán","Bashan"],["y","and"],["el","the"],["Carmelo","Carmel"],["languidecen,","they-languish,"],["y","and"],["la","the"],["flor","flower"],["del","of-the"],["Líbano","lebanon"],["se","[refl.]"],["marchita.","little-his."]]},
  {num:5,words:[["Los","the"],["montes","mountains"],["tiemblan","they-quake"],["delante","before"],["de","of"],["él,","he,"],["y","and"],["los","the"],["collados","hills"],["se","[refl.]"],["derriten;","melt;"],["y","and"],["la","the"],["tierra","earth"],["se","[refl.]"],["agita","burned"],["ante","before"],["su","his"],["presencia,","presence,"],["y","and"],["también","also"],["el","the"],["mundo","world"],["y","and"],["todos","all"],["los","the"],["que","that"],["en","in"],["él","he"],["habitan.","they-dwell."]]},
  {num:6,words:[["¿Quién","who"],["permanecerá","stand"],["delante","before"],["de","of"],["su","his"],["ira?","wrath?"],["¿Quién","who"],["quedará","shall-remain"],["en","in"],["pie","foot"],["ante","before"],["el","the"],["furor","fury"],["de","of"],["su","his"],["enojo?","fury?"],["Su","his"],["ira","wrath"],["se","[refl.]"],["derrama","spills"],["como","as"],["fuego,","fire,"],["y","and"],["por","by"],["él","he"],["se","[refl.]"],["hienden","down"],["las","the"],["peñas.","rocks."]]},
  {num:7,words:[["Jehová","jehovah"],["es","is"],["bueno,","good,"],["fortaleza","castle"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["angustia,","anguish,"],["y","and"],["conoce","knows"],["a","to"],["los","the"],["que","that"],["en","in"],["él","he"],["confían.","they-trust."]]},
  {num:8,words:[["Mas","but"],["con","with"],["inundación","overrunning"],["impetuosa","flood"],["hará","shall-make"],["consumación","shall"],["de","of"],["su","his"],["lugar,","place,"],["y","and"],["las","the"],["tinieblas","darkness"],["perseguirán","they-shall"],["a","to"],["sus","his"],["enemigos.","enemies."]]},
  {num:9,words:[["¿Qué", "what"], ["tramáis","you"], ["contra", "against"], ["Jehová?", "jehovah?"], ["Él", "he"], ["hará", "shall-make"], ["consumación;", "shall;"], ["la", "the"], ["tribulación", "tribulation"], ["no", "not"], ["se", "[refl.]"], ["levantará", "raise"], ["dos", "two"], ["veces.", "times."]]},
  {num:10,words:[["Porque","because"],["como","as"],["espinos","briers"],["entretejidos","folden"],["y","and"],["como","as"],["ebrios","while"],["en","in"],["su","his/her"],["embriaguez,","as,"],["serán","they-shall-be"],["consumidos","consumed"],["como","as"],["rastrojo","stubble"],["completamente","utterly"],["seco.","I-dry."]]},
  {num:11,words:[["De","of"],["ti","you"],["salió","departed"],["el","the"],["que","that"],["tramó","plotted"],["el","the"],["mal","evil"],["contra","against"],["Jehová,","jehovah,"],["un","a"],["consejero","counselor"],["perverso.","wicked."]]},
  {num:12,words:[["Así","thus"],["ha","has"],["dicho","said"],["Jehová:","jehovah:"],["Aunque","although"],["reposo","I-rest"],["tengan","they-let-have"],["y","and"],["sean","they-let-be"],["muchos,","many,"],["aun","even"],["así","thus"],["serán","they-shall-be"],["talados,","hewn,"],["y","and"],["pasarán.","away."],["Aunque","although"],["te","you"],["he","I-have"],["afligido,","afflicted,"],["no","not"],["te","you"],["afligiré","you"],["más.","more."]]},
  {num:13,words:[["Porque","because"],["ahora","now"],["quebraré","i"],["su","his"],["yugo","yoke"],["de","of"],["sobre","upon"],["ti","you"],["y","and"],["romperé","I-shall-that"],["tus","your"],["coyundas.","and."]]},
  {num:14,words:[["Pero","but"],["acerca","about"],["de","of"],["ti","you"],["ha","has"],["mandado","commanded"],["Jehová","jehovah"],["que","that"],["no","not"],["sea","be"],["perpetuado","name"],["tu","your"],["nombre;","name;"],["de","of"],["la","the"],["casa","house"],["de","of"],["tu","your"],["dios","God"],["talaré","I-cut"],["imágenes","groves"],["talladas","graven"],["e","and"],["imágenes","groves"],["de","of"],["fundición;","molten;"],["prepararé","I-will"],["tu","your"],["sepulcro,","sepulchre,"],["porque","because"],["fuiste","you-were"],["vil.","vile."]]},
  {num:15,words:[["¡He aquí","¡look"],["sobre","upon"],["los","the"],["montes","mountains"],["los","the"],["pies","feet"],["del","of-the"],["que","that"],["trae","brings"],["buenas","good"],["nuevas,","new,"],["del","of-the"],["que","that"],["anuncia","announces"],["la","the"],["paz!","peace!"],["Celebra,","keep,"],["oh","oh"],["Judá,","Judah,"],["tus","your"],["fiestas","moons"],["solemnes,","moons,"],["cumple","you"],["tus","your"],["votos,","vows,"],["porque","because"],["ya","already"],["nunca","never"],["más","more"],["pasará","will-pass"],["sobre","upon"],["ti","you"],["el","the"],["malvado;","wicked;"],["ha","has"],["perecido","perished"],["del","of-the"],["todo.","all."]]},
];
renderVerseSet(v1, 'nah-ch1-verses');

var v2 = [
  {num:1,words:[["Un","a"],["destructor","spoiler"],["ha","has"],["subido","gone-up"],["contra","against"],["ti;","you;"],["guarda","keeps"],["la","the"],["fortaleza,","castle,"],["vigila","watches"],["el","the"],["camino,","way,"],["fortifica","fortifies"],["tus","your"],["lomos,","loins,"],["fortalece","strong,"],["mucho","much"],["tu","your"],["poder.","power."]]},
  {num:2,words:[["Porque","because"],["Jehová","jehovah"],["restaurará","shall-restore"],["la","the"],["gloria","glory"],["de","of"],["Jacob","Jacob"],["como","as"],["la","the"],["gloria","glory"],["de","of"],["Israel;","Israel;"],["porque","because"],["saqueadores","have"],["los","the"],["saquearon","they-looted"],["y","and"],["destruyeron","they-destroyed"],["sus","their"],["sarmientos.","of."]]},
  {num:3,words:[["El","the"],["escudo","shield"],["de","of"],["sus","his"],["guerreros","warriors"],["se","[refl.]"],["ha","has"],["enrojecido,","red,"],["los","the"],["hombres","men"],["valientes","valour"],["vestidos","garments"],["de","of"],["grana;","scarlet;"],["el","the"],["día","day"],["en","in"],["que","that"],["se","[refl.]"],["preparen,","they-may-prepare,"],["los","the"],["carros","chariots"],["serán","they-shall-be"],["como","as"],["fuego","fire"],["de","of"],["antorchas,","the,"],["y","and"],["temblarán","they-will-tremble"],["los","the"],["cipreses.","fir."]]},
  {num:4,words:[["Los","the"],["carros","chariots"],["se","[refl.]"],["precipitarán","they-will-precipitate"],["a","to"],["las","the"],["plazas;","strongholds;"],["con","with"],["estruendo","noise"],["rodarán","they-shall-and"],["por","by/for"],["las","the"],["calles;","streets;"],["su","his/her"],["aspecto","appearance"],["será","shall-be"],["como","as"],["antorchas","the"],["encendidas;","offerings;"],["correrán","they-will-run"],["como","as"],["relámpagos.","lightnings."]]},
  {num:5,words:[["Convocará","he"],["él","he"],["a","to"],["sus","his/her"],["valientes;","valour;"],["al","to-the"],["andar","to-walk"],["tropezarán;","they-shall;"],["se","[refl.]"],["apresurarán","make"],["hacia","toward"],["su","his/her"],["muro,","wall,"],["y","and"],["la","the"],["defensa","defense"],["se","[refl.]"],["preparará.","prepare."]]},
  {num:6,words:[["Las", "the"], ["compuertas", "gates"], ["de", "of"], ["los", "the"], ["ríos", "rivers"], ["se", "[refl.]"], ["abrirán,", "shall,"], ["y", "and"], ["el", "the"], ["palacio", "palace"], ["será", "shall-be"], ["arrasado.", "dissolved."]]},
  {num:7,words:[["Y","and"],["la","the"],["reina","queen"],["será","shall-be"],["llevada","into"],["cautiva;","captive;"],["mandarán","they-shall-command"],["que","that"],["suba,","up,"],["y","and"],["sus","his/her"],["criadas","in"],["la","the"],["llevarán","bear"],["gimiendo","moaning"],["como","as"],["palomas,","doves,"],["golpeándose","tabering"],["el","the"],["pecho.","breast."]]},
  {num:8,words:[["Y","and"],["Nínive","Nineveh"],["es","is"],["de","of"],["tiempo","time"],["antiguo","ancient"],["como","as"],["estanque","pool"],["de","of"],["aguas;","waters;"],["mas","but"],["ellos","they"],["huyen","they-away."],["y","and"],["dicen:","they-say:"],["¡Deteneos,","shall,"],["deteneos!,","they!,"],["pero","but"],["ninguno","none"],["mira","looks"],["hacia","toward"],["atrás.","backward."]]},
  {num:9,words:[["Saquead","you-take"],["plata,","silver,"],["saquead","you-spoil"],["oro;","gold;"],["no","not"],["hay","there-is"],["fin","end"],["de","of"],["las","the"],["riquezas","riches"],["ni","nor"],["de","of"],["la","the"],["suntuosidad","store"],["de","of"],["toda","all"],["clase","class/kind"],["de","of"],["objetos","things"],["preciosos.","precious."]]},
  {num:10,words:[["Vacía,","void,"],["y","and"],["agotada","empty,"],["y","and"],["desolada","desolate"],["está,","is,"],["y","and"],["el","the"],["corazón","heart"],["desfallecido;","fainted;"],["temblor","trembling"],["de","of"],["rodillas","knees"],["y","and"],["dolor","pain"],["en","in"],["todos","all"],["los","the"],["lomos,","loins,"],["y","and"],["los","the"],["rostros","faces"],["de","of"],["todos","all"],["se","[refl.]"],["demudan.","blackness."]]},
  {num:11,words:[["¿Dónde","where"],["está","is"],["la","the"],["guarida","lair"],["de","of"],["los","the"],["leones","lions"],["y","and"],["el","the"],["lugar","place"],["donde","where"],["comen","they-eat"],["los","the"],["cachorros","whelps"],["de","of"],["los","the"],["leones,","lions,"],["donde","where"],["andaba","walked"],["el","the"],["león,","lion,"],["la","the"],["leona","lion,"],["y","and"],["el","the"],["cachorro","lion"],["de","of"],["león,","lion,"],["y","and"],["no","not"],["había","had"],["quien","who"],["los","the"],["espantase?","astonishment-[refl.]?"]]},
  {num:12,words:[["El","the"],["león","lion"],["arrebataba","did"],["lo","it/him"],["suficiente","sufficient"],["para","for"],["sus","his"],["cachorros","whelps"],["y","and"],["estrangulaba","whelps,"],["para","for"],["sus","his"],["leonas;","for;"],["y","and"],["llenaba","filled"],["de","of"],["presas","preys"],["sus","his"],["madrigueras","with"],["y","and"],["de","of"],["carne","flesh"],["desgarrada","dens"],["sus","his"],["guaridas.","lair."]]},
  {num:13,words:[["Heme","here"],["aquí","here"],["contra","against"],["ti,","you,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["y","and"],["quemaré","I-will-burn"],["tus","your"],["carros","chariots"],["y","and"],["los","the"],["reduciré","smoke,"],["a","to"],["humo,","smoke,"],["y","and"],["la","the"],["espada","sword"],["devorará","devour"],["tus","your"],["leoncillos;","lions;"],["y","and"],["raeré","will"],["de","of"],["la","the"],["tierra","earth"],["tu","your"],["presa,","prey,"],["y","and"],["nunca","never"],["más","more"],["se","[refl.]"],["oirá","hear"],["la","the"],["voz","voice"],["de","of"],["tus","your"],["mensajeros.","messengers."]]},
];
renderVerseSet(v2, 'nah-ch2-verses');

var v3 = [
  {num:1,words:[["¡Ay", "wo"], ["de", "of"], ["la", "the"], ["ciudad", "city"], ["sanguinaria,", "it,"], ["toda", "all"], ["llena", "full"], ["de", "of"], ["mentira", "lies"], ["y", "and"], ["de", "of"], ["rapiña,", "to,"], ["de", "of"], ["incesante","departs"], ["pillaje!", "not!"]]},
  {num:2,words:[["Chasquido","the"],["de","of"],["látigo","a"],["y","and"],["estruendo","noise"],["de","of"],["movimiento","movement"],["de","of"],["ruedas;","wheels;"],["y","and"],["caballo","horse"],["al","to-the"],["galope","pransing"],["y","and"],["carro","cart"],["que","that"],["salta;","chariots;"]]},
  {num:3,words:[["el","the"],["jinete","the"],["a","to"],["la","the"],["carga,","burden,"],["y","and"],["resplandor","luster"],["de","of"],["espada","sword"],["y","and"],["brillo","brightness"],["de","of"],["lanza;","spear;"],["y","and"],["multitud","multitude"],["de","of"],["muertos","dead"],["y","and"],["multitud","multitude"],["de","of"],["cadáveres;","bodies;"],["y","and"],["cadáveres","bodies"],["sin","without"],["fin,","end,"],["y","and"],["con","with"],["los","the"],["cadáveres","bodies"],["tropezarán.","they-shall."]]},
  {num:4,words:[["Y", "and"], ["esto", "this"], ["a causa de","because of"], ["la", "the"], ["multitud", "multitude"], ["de", "of"], ["las", "the"], ["fornicaciones", "whoredoms"], ["de", "of"], ["la", "the"], ["ramera", "whore"], ["de", "of"], ["hermosa", "beautiful"], ["gracia,", "grace,"], ["maestra", "teacher"], ["de", "of"], ["brujerías,", "witchcrafts,"], ["que", "that"], ["vende", "he"], ["a", "to"], ["las", "the"], ["naciones", "nations"], ["con", "with"], ["sus","her"], ["fornicaciones", "whoredoms"], ["y", "and"], ["a", "to"], ["las", "the"], ["familias", "families"], ["con", "with"], ["sus","her"], ["hechicerías.", "of."]]},
  {num:5,words:[["Heme","here"],["aquí","here"],["contra","against"],["ti,","you,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos;","armies;"],["y","and"],["levantaré","I-raise"],["tus","your"],["faldas","skirts"],["hasta","until"],["tu","your"],["cara","face"],["y","and"],["mostraré","I-will-show"],["a","to"],["las","the"],["naciones","nations"],["tu","your"],["desnudez,","nakedness,"],["y","and"],["a","to"],["los","the"],["reinos","kingdoms"],["tu","your"],["vergüenza.","shame."]]},
  {num:6,words:[["Y","and"],["echaré","I-cast"],["sobre","upon"],["ti","you"],["inmundicias,","filthinesss,"],["y","and"],["te","you"],["haré","I will make"],["despreciable","vile,"],["y","and"],["te","you"],["pondré","I-shall-put"],["como","as"],["espectáculo.","gazingstock."]]},
  {num:7,words:[["Y","and"],["acontecerá","shall-come-to-pass"],["que","that"],["todos","all"],["los","the"],["que","that"],["te","you"],["vean","see"],["se","[refl.]"],["apartarán","shall-turn"],["de","of"],["ti","you"],["y","and"],["dirán:","they-will-say:"],["¡Nínive","Nineveh"],["ha","has"],["sido","been"],["asolada!","desolate!"],["¿Quién","who"],["se","[refl.]"],["compadecerá","bemoan"],["de","of"],["ella?","she?"],["¿Dónde","where"],["te","you"],["buscaré","will"],["consoladores?","comforters?"]]},
  {num:8,words:[["¿Eres","you-are"],["tú","you"],["mejor","better"],["que","that"],["Tebas,","no,"],["que","that"],["estaba","was"],["asentada","settled"],["entre","among"],["ríos,","rivers,"],["rodeada","surrounded"],["de","of"],["aguas,","waters,"],["cuyo","whose"],["baluarte","whose"],["era","was"],["el","the"],["mar","sea"],["y","and"],["el","the"],["mar","sea"],["su","her"],["muralla?","wall?"]]},
  {num:9,words:[["Etiopía","Ethiopia"],["era","was"],["su","her"],["fortaleza,","castle,"],["y","and"],["Egipto,","Egypt,"],["y","and"],["eso","that"],["sin","without"],["límite;","border;"],["Fut","infinite;"],["y","and"],["Libia","and"],["estaban","they-were"],["entre","among"],["tus","your"],["ayudadores.","helpers."]]},
  {num:10,words:[["No obstante,","nevertheless,"],["ella","she"],["fue","was/went"],["desterrada,","banished,"],["llevada","into"],["al","to-the"],["cautiverio;","captivity;"],["también","also"],["sus","her"],["niños","children"],["fueron","they-were"],["estrellados","dashed"],["en","in"],["las","the"],["encrucijadas","the"],["de","of"],["todas","all"],["las","the"],["calles;","streets;"],["y","and"],["sobre","upon"],["sus","her"],["nobles","nobles"],["echaron","they-lots"],["suertes,","lots,"],["y","and"],["todos","all"],["sus","her"],["grandes","great"],["fueron","they-were"],["aprisionados","were"],["con","with"],["grilletes.","chains."]]},
  {num:11,words:[["Tú","you"],["también","also"],["quedarás","you-will"],["embriagada;","drunken;"],["serás","you-will-be"],["ocultada;","will;"],["tú","you"],["también","also"],["buscarás","you-shall-seek"],["refugio","I-refuge"],["a","to"],["causa","cause/sake"],["del","of-the"],["enemigo.","enemy."]]},
  {num:12,words:[["Todas","all"],["tus","your"],["fortalezas","holds"],["serán","they-shall-be"],["cual","which"],["higueras","figs"],["cargadas","fig"],["de","of"],["brevas,","with,"],["que,","that,"],["si","if"],["las","the"],["sacuden,","they,"],["caen","they-fall"],["en","in"],["la","the"],["boca","mouth"],["del","of-the"],["que","that"],["las","the"],["ha","has"],["de","of"],["comer.","to-eat."]]},
  {num:13,words:[["He aquí,","behold,"], ["tu","your"], ["pueblo", "people"], ["será", "shall-be"], ["como", "as"], ["mujeres", "women"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti;","you;"], ["las", "the"], ["puertas", "gates"], ["de", "of"], ["tu","your"], ["tierra","land"], ["se", "[refl.]"], ["abrirán", "shall"], ["de", "of"], ["par", "of"], ["en", "in"], ["par", "of"], ["a", "to"], ["tus","your"], ["enemigos;", "enemies;"], ["fuego", "fire"], ["consumirá", "palaces"], ["tus","your"], ["cerrojos.", "bars."]]},
  {num:14,words:[["Provéete","draw"],["de","of"],["agua","water"],["para","for"],["el","the"],["asedio;","siege;"],["fortifica","fortifies"],["tus","your"],["fortalezas;","holds;"],["entra","enter"],["en","in"],["el","the"],["lodo;","mire;"],["pisa","tread"],["el","the"],["barro;","earthen;"],["refuerza","strong"],["el","the"],["horno.","furnace."]]},
  {num:15,words:[["Allí", "there"], ["te","you"], ["consumirá", "palaces"], ["el", "the"], ["fuego;", "fire;"], ["te","you"], ["talará", "shall-cut"], ["la", "the"], ["espada.", "sword."], ["Te","you"], ["devorará", "devour"], ["como", "as"], ["el", "the"], ["pulgón.", "cankerworm."], ["¡Multiplícate", "make"], ["como", "as"], ["el", "the"], ["pulgón!", "cankerworm!"], ["¡Multiplícate", "make"], ["como", "as"], ["la", "the"], ["langosta!", "locust!"]]},
  {num:16,words:[["Multiplicaste","you"], ["tus","your"], ["mercaderes", "merchants"], ["más", "more"], ["que", "that"], ["las", "the"], ["estrellas", "stars"], ["del", "of-the"], ["cielo;", "heaven;"], ["el", "the"], ["pulgón", "cankerworm"], ["hizo", "made/did"], ["presa", "prey"], ["y", "and"], ["voló.", "away."]]},
  {num:17,words:[["Tus","your"],["príncipes","princes"],["serán","they-shall-be"],["como","as"],["langostas","as"],["y","and"],["tus","your"],["oficiales","officers"],["como","as"],["nubes","clouds"],["de","of"],["langostas","as"],["que","that"],["se","[refl.]"],["posan","they-pose"],["en","in"],["vallados","ands"],["en","in"],["día","day"],["de","of"],["frío;","cold;"],["salido","gone-out"],["el","the"],["sol","sun"],["se","[refl.]"],["van,","go,"],["y","and"],["no","not"],["se","[refl.]"],["conoce","knows"],["el","the"],["lugar","place"],["donde","where"],["están.","they-are."]]},
  {num:18,words:[["Durmieron","they"],["tus","your"],["pastores,","pastors,"],["oh","oh"],["rey","king"],["de","of"],["Asiria;","Assyria;"],["reposaron","they-rested"],["tus","your"],["nobles;","nobles;"],["tu","your"],["pueblo","people"],["se","[refl.]"],["dispersó","people"],["por","by/for"],["los","the"],["montes,","mountains,"],["y","and"],["no","not"],["hay","there-is"],["quien","who"],["lo","it/him"],["junte.","may-gather."]]},
  {num:19,words:[["No","not"],["hay","there-is"],["curación","healing"],["para","for"],["tu","your"],["quebradura;","your;"],["tu","your"],["herida","wound"],["es","is"],["grave.","grievous."],["Todos","all"],["los","the"],["que","that"],["oigan","they-hear"],["noticias","theys"],["de","of"],["ti","you"],["batirán","you"],["las","the"],["palmas","hands"],["de","of"],["las","the"],["manos","hands"],["acerca","about"],["de","of"],["ti,","you,"],["porque,","because,"],["¿sobre","upon"],["quién","who"],["no","not"],["pasó","passed"],["continuamente","continually"],["tu","your"],["maldad?","wickedness?"]]},
];
renderVerseSet(v3, 'nah-ch3-verses');

})();
