(function() {
var v1 = [
  {num:1,words:[["Visión", "vision"], ["de", "of"], ["Abdías.", "obadiah."], ["Jehová", "jehovah"], ["el", "the"], ["Señor", "Lord"], ["ha", "has"], ["dicho", "said"], ["así", "thus"], ["en cuanto a","as for"], ["Edom:","Edom:"], ["Hemos", "we-have"], ["oído", "heard"], ["el", "the"], ["pregón", "of"], ["de", "of"], ["parte", "part"], ["de", "of"], ["Jehová,", "jehovah,"], ["y", "and"], ["mensajero", "messenger"], ["ha", "has"], ["sido", "been"], ["enviado", "sent"], ["a", "to"], ["las", "the"], ["naciones.", "nations."], ["Levantaos,", "arise,"], ["y", "and"], ["levantémonos", "rise"], ["contra", "against"], ["este", "this"], ["pueblo", "people"], ["en", "in"], ["batalla.", "battle."]]},
  {num:2,words:[["He aquí,","behold,"], ["pequeño", "small"], ["te","you"], ["he", "I-have"], ["hecho","made"], ["entre", "among"], ["las", "the"], ["naciones;", "nations;"], ["despreciado", "despised"], ["eres","you-are"], ["tú","you"], ["en", "in"], ["gran", "great"], ["manera.", "manner."]]},
  {num:3,words:[["La","the"],["soberbia","pride"],["de","of"],["tu","your"],["corazón","heart"],["te","you"],["ha","has"],["engañado,","deceived,"],["tú","you"],["que","that"],["moras","you-dwell"],["en","in"],["las","the"],["hendiduras","of"],["de","of"],["las","the"],["peñas,","rocks,"],["en","in"],["tu","your"],["altísima","most"],["morada,","habitation,"],["que","that"],["dices","you-say"],["en","in"],["tu","your"],["corazón:","heart:"],["¿Quién","who"],["me","me"],["derribará","shall"],["a","to"],["tierra?","land?"]]},
  {num:4,words:[["Aunque","although"],["te","you"],["remontes","myself"],["como","as"],["águila","eagle"],["y","and"],["entre","among"],["las","the"],["estrellas","stars"],["pongas","you"],["tu","your"],["nido,","nest,"],["de","of"],["ahí","be"],["te","you"],["derribaré,","down,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:5,words:[["Si","if"],["ladrones","thieves"],["vinieran","they-might-come"],["a","to"],["ti,","you,"],["o","or"],["robadores","night,"],["de","of"],["noche","night"],["(¡cómo","how"],["has","you-have"],["sido","been"],["destruido!),","destroyed!),"],["¿no","not"],["robarían","they-would-their"],["lo","it/him"],["que","that"],["les","them"],["bastara?","if?"],["Si","if"],["vinieran","they-might-come"],["a","to"],["ti","you"],["vendimiadores,","would,"],["¿no","not"],["dejarían","they-would-leave"],["algún","some"],["rebusco?","grapes?"]]},
  {num:6,words:[["¡Cómo","how"],["fueron","they-were"],["escudriñadas","things"],["las","the"],["cosas","things"],["de","of"],["Esaú!","Esau!"],["Sus","his"],["cosas","things"],["escondidas","things"],["fueron","they-were"],["buscadas.","up."]]},
  {num:7,words:[["Hasta","until"],["el","the"],["límite","border"],["te","you"],["han","have"],["llevado","carried"],["todos","all"],["tus","your"],["aliados;","ally;"],["los","the"],["que","that"],["estaban","they-were"],["en","in"],["paz","peace"],["contigo","with-you"],["te","you"],["han","have"],["engañado,","deceived,"],["y","and"],["han","they-have"],["prevalecido","you,"],["contra","against"],["ti;","you;"],["los","the"],["que","that"],["comían","they-ate"],["tu","your"],["pan","bread"],["han","they-have"],["puesto","placed"],["trampa","snare"],["debajo","beneath"],["de","of"],["ti;","you;"],["no","not"],["hay","there-is"],["en","in"],["él","he"],["entendimiento.","understanding."]]},
  {num:8,words:[["¿No","not"],["haré","I-shall-make"],["que","that"],["perezcan","they-may-perish"],["en","in"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová,","jehovah,"],["los","the"],["sabios","wise"],["de","of"],["Edom","Edom"],["y","and"],["la","the"],["prudencia","wisdom"],["del","of-the"],["monte","mount"],["de","of"],["Esaú?","Esau?"]]},
  {num:9,words:[["Y","and"],["tus","your"],["valientes,","valour,"],["oh","oh"],["Temán,","Teman,"],["serán","they-shall-be"],["amedrentados,","dismayed,"],["para","for"],["que","that"],["todo","all"],["hombre","man"],["sea","be"],["talado","cut"],["del","of-the"],["monte","mount"],["de","of"],["Esaú","Esau"],["por","by"],["el","the"],["estrago.","the."]]},
  {num:10,words:[["Por","for"], ["la", "the"], ["violencia", "violence"], ["contra", "against"], ["tu","your"], ["hermano", "brother"], ["Jacob", "Jacob"], ["te","you"], ["cubrirá", "cover"], ["la", "the"], ["vergüenza,", "shame,"], ["y", "and"], ["serás","you-will-be"], ["talado", "cut"], ["para", "for"], ["siempre.", "always."]]},
  {num:11,words:[["El","the"],["día","day"],["en","in"],["que","that"],["te","you"],["pusiste","have"],["del","of-the"],["lado","side"],["contrario,","contrary,"],["el","the"],["día","day"],["en","in"],["que","that"],["extraños","strangers"],["llevaban","they-ark"],["cautivo","captive"],["su","his"],["ejército,","army,"],["y","and"],["extranjeros","strangers"],["entraban","they-entered"],["por","for"],["sus","his"],["puertas","gates"],["y","and"],["echaban","they-threw"],["suertes","lots"],["sobre","upon"],["Jerusalén,","Jerusalem,"],["tú","you"],["también","also"],["eras","you-were"],["como","as"],["uno","one"],["de","of"],["ellos.","they."]]},
  {num:12,words:[["Pues","for"],["no","not"],["debiste","you-have"],["haberte","have-you"],["quedado","remained"],["mirando","looking"],["en","in"],["el","the"],["día","day"],["de","of"],["tu","your"],["hermano,","brother,"],["el","the"],["día","day"],["de","of"],["su","their"],["infortunio;","misfortune;"],["no","not"],["debiste","you-have"],["haberte","have-you"],["alegrado","have"],["de","of"],["los","the"],["hijos","children"],["de","of"],["Judá","Judah"],["el","the"],["día","day"],["en","in"],["que","that"],["perecieron","they-many"],["ni","nor"],["debiste","you-have"],["haberte","have-you"],["jactado","have"],["en","in"],["el","the"],["día","day"],["de","of"],["su","their"],["angustia.","anguish."]]},
  {num:13,words:[["No","not"],["debiste","you-have"],["haber","have"],["entrado","entered"],["por","for"],["la","the"],["puerta","gate"],["de","of"],["mi","my"],["pueblo","people"],["en","in"],["el","the"],["día","day"],["de","of"],["su","his"],["calamidad;","calamity;"],["no,","not,"],["no","not"],["debiste","you-have"],["haber","have"],["mirado","looked"],["su","his"],["mal","evil"],["el","the"],["día","day"],["de","of"],["su","his"],["desgracia","misfortune"],["ni","nor"],["haber","have"],["echado","hewn"],["mano","hand"],["a","to"],["sus","his"],["bienes","goods"],["el","the"],["día","day"],["de","of"],["su","his"],["calamidad.","calamity."]]},
  {num:14,words:[["Tampoco","neither"],["debiste","you-have"],["haberte","have-you"],["puesto","placed"],["en","in"],["las","the"],["encrucijadas","crossway,"],["para","for"],["matar","slay"],["a","to"],["los","the"],["que","that"],["de","of"],["ellos","they"],["escapaban;","were-escapeing;"],["ni","nor"],["debiste","you-have"],["haber","have"],["entregado","betrayed"],["a","to"],["los","the"],["que","that"],["quedaban","they-remained"],["en","in"],["el","the"],["día","day"],["de","of"],["su","his"],["angustia.","anguish."]]},
  {num:15,words:[["Porque","because"],["cercano","near"],["está","is"],["el","the"],["día","day"],["de","of"],["Jehová","jehovah"],["sobre","upon"],["todas","all"],["las","the"],["naciones;","nations;"],["como","as"],["tú","you"],["hiciste","made"],["se","itself"],["hará","shall-make"],["contigo;","with-you;"],["tu","your"],["recompensa","reward"],["volverá","will-return"],["sobre","upon"],["tu","your"],["propia","own"],["cabeza.","head."]]},
  {num:16,words:[["De","of"],["la","the"],["manera","manner"],["que","that"],["vosotros","you"],["bebisteis","holy"],["en","in"],["mi","my"],["santo","holy"],["monte,","mount,"],["beberán","they-will-drink"],["continuamente","continually"],["todas","all"],["las","the"],["naciones;","nations;"],["beberán,","they-will-drink,"],["y","and"],["engullirán","down,"],["y","and"],["serán","they-shall-be"],["como","as"],["si","if"],["no","not"],["hubieran","they-had"],["existido.","been."]]},
  {num:17,words:[["Mas","but"],["en","in"],["el","the"],["monte","mount"],["Sion","Zion"],["habrá","there-shall-be"],["salvamento,","rescue,"],["y","and"],["será","shall-be"],["santo,","holy,"],["y","and"],["la","the"],["casa","house"],["de","of"],["Jacob","Jacob"],["recuperará","possess"],["sus","their"],["posesiones.","possessions."]]},
  {num:18,words:[["Y","and"],["la","the"],["casa","house"],["de","of"],["Jacob","Jacob"],["será","shall-be"],["fuego,","fire,"],["y","and"],["la","the"],["casa","house"],["de","of"],["José","Joseph"],["será","shall-be"],["llama,","flame,"],["y","and"],["la","the"],["casa","house"],["de","of"],["Esaú","Esau"],["estopa,","lint,"],["y","and"],["los","the"],["quemarán","burn"],["y","and"],["los","the"],["consumirán;","devour;"],["ni","nor"],["aun","even"],["quedará","shall-remain"],["sobreviviente","survivor"],["alguno","some"],["en","in"],["la","the"],["casa","house"],["de","of"],["Esaú,","Esau,"],["porque","because"],["Jehová","jehovah"],["lo","it"],["ha","has"],["dicho.","said."]]},
  {num:19,words:[["Y","and"],["los","the"],["del","of-the"],["sur","south"],["poseerán","they-will-possess"],["el","the"],["monte","mount"],["de","of"],["Esaú","Esau"],["y","and"],["las","the"],["llanuras","plains"],["de","of"],["los","the"],["filisteos;","philistines;"],["poseerán","they-will-possess"],["también","also"],["los","the"],["campos","fields"],["de","of"],["Efraín","Ephraim"],["y","and"],["los","the"],["campos","fields"],["de","of"],["Samaria;","Samaria;"],["y","and"],["Benjamín","Benjamin"],["poseerá","will-possess"],["Galaad.","Gilead."]]},
  {num:20,words:[["Y","and"],["los","the"],["cautivos","captives"],["de","of"],["este","this"],["ejército","army"],["de","of"],["los","the"],["hijos","children"],["de","of"],["Israel","Israel"],["poseerán","they-will-possess"],["lo","it/him"],["de","of"],["los","the"],["cananeos","canaanites"],["hasta","until"],["Sarepta;","zarephath;"],["y","and"],["los","the"],["cautivos","captives"],["de","of"],["Jerusalén","Jerusalem"],["que","that"],["están","they-are"],["en","in"],["Sefarad","shall"],["poseerán","they-will-possess"],["las","the"],["ciudades","cities"],["del","of-the"],["sur.","south."]]},
  {num:21,words:[["Y","and"],["subirán","up"],["salvadores","saviors"],["al","to-the"],["monte","mount"],["Sion","Zion"],["para","for"],["juzgar","to-judge"],["al","to-the"],["monte","mount"],["de","of"],["Esaú;","Esau;"],["y","and"],["el","the"],["reino","kingdom"],["será","shall-be"],["de","of"],["Jehová.","jehovah."]]},
];
renderVerseSet(v1, 'oba-ch1-verses');

})();
