(function() {
var v1 = [
  {num:1,words:[["Pablo,", "paul,"], ["prisionero", "of"], ["de", "of"], ["Jesucristo,", "Jesus-Christ,"], ["y", "and"], ["el", "the"], ["hermano", "brother"], ["Timoteo,", "timotheus,"], ["al", "to-the"], ["amado", "beloved"], ["Filemón,", "dearly,"], ["colaborador", "beloved,"], ["nuestro,", "our,"]]},
  {num:2,words:[["y", "and"], ["a", "to"], ["la", "the"], ["amada", "beloved"], ["hermana", "sister"], ["Apia,", "apphia,"], ["y", "and"], ["a", "to"], ["Arquipo,", "archippus,"], ["nuestro", "our"], ["compañero", "companion"], ["de", "of"], ["milicia,", "and,"], ["y", "and"], ["a", "to"], ["la", "the"], ["iglesia", "church"], ["que", "that"], ["está", "is"], ["en", "in"], ["tu", "thy"], ["casa:", "house:"]]},
  {num:3,words:[["Gracia", "grace"], ["a", "to"], ["vosotros", "you"], ["y", "and"], ["paz", "peace"], ["de", "of"], ["parte", "part"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["y", "and"], ["del", "of-the"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:4,words:[["Doy", "I-give"], ["gracias", "thanks"], ["a", "to"], ["mi", "my"], ["Dios,", "God,"], ["haciendo", "doing/making"], ["siempre", "always"], ["memoria", "remembrance"], ["de", "of"], ["ti", "thee"], ["en", "in"], ["mis", "my"], ["oraciones,", "prayers,"]]},
  {num:5,words:[["porque", "because"], ["oigo", "hear"], ["del", "of-the"], ["amor", "love"], ["y", "and"], ["de", "of"], ["la", "the"], ["fe", "faith"], ["que", "that"], ["tienes", "hast"], ["hacia", "toward"], ["el", "the"], ["Señor", "Lord"], ["Jesús,", "Jesus,"], ["y", "and"], ["para", "for"], ["con", "with"], ["todos", "all"], ["los", "the"], ["santos;", "saints;"]]},
  {num:6,words:[["para", "for"], ["que", "that"], ["la", "the"], ["comunicación", "of"], ["de", "of"], ["tu", "thy"], ["fe", "faith"], ["sea", "let-be/be"], ["eficaz", "effectual"], ["en", "in"], ["el", "the"], ["conocimiento", "knowledge"], ["de", "of"], ["todo", "all"], ["el", "the"], ["bien", "well"], ["que", "that"], ["está", "is"], ["en", "in"], ["vosotros", "you"], ["mediante", "through"], ["Cristo", "Christ"], ["Jesús.", "Jesus."]]},
  {num:7,words:[["Porque", "because"], ["tenemos", "we-have"], ["gran", "great"], ["gozo", "joy"], ["y", "and"], ["consolación", "consolation"], ["en", "in"], ["tu", "thy"], ["amor,", "love,"], ["pues", "for"], ["por", "by/for"], ["ti,", "thee,"], ["oh", "oh"], ["hermano,", "brother,"], ["ha", "has"], ["sido", "been"], ["reconfortado", "saints"], ["el", "the"], ["corazón", "heart"], ["de", "of"], ["los", "the"], ["santos.", "saints."]]},
  {num:8,words:[["Por", "by/for"], ["lo", "it/him"], ["cual,", "which,"], ["aunque", "although"], ["tengo", "I-have"], ["mucha", "much"], ["franqueza", "in"], ["en", "in"], ["Cristo", "Christ"], ["para", "for"], ["mandarte", "command-thee"], ["lo", "it/him"], ["que", "that"], ["conviene,", "expedient,"]]},
  {num:9,words:[["más", "more"], ["bien", "well"], ["por", "by/for"], ["amor", "love"], ["te", "thee"], ["ruego,", "I-pray/beseech,"], ["siendo", "being"], ["como", "as"], ["soy,", "I-am,"], ["Pablo", "paul"], ["ya", "already"], ["anciano,", "ancient,"], ["y", "and"], ["ahora,", "now,"], ["además,", "moreover,"], ["prisionero", "of"], ["de", "of"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:10,words:[["Te", "thee"], ["ruego", "I-pray/beseech"], ["por", "by/for"], ["mi", "my"], ["hijo", "son"], ["Onésimo,", "son,"], ["a", "to"], ["quien", "who"], ["he", "I-have"], ["engendrado", "begotten"], ["en", "in"], ["mis", "my"], ["prisiones,", "bonds,"]]},
  {num:11,words:[["el", "the"], ["que", "that"], ["en", "in"], ["otro", "other"], ["tiempo", "time"], ["te", "thee"], ["fue", "was/went"], ["inútil,", "thee,"], ["pero", "but"], ["ahora", "now"], ["a", "to"], ["ti", "thee"], ["y", "and"], ["a", "to"], ["mí", "me"], ["nos", "us"], ["es", "is"], ["útil,", "me,"]]},
  {num:12,words:[["el", "the"], ["que", "that"], ["te", "thee"], ["vuelvo", "again"], ["a", "to"], ["enviar;", "send;"], ["tú,", "thou,"], ["pues,", "for,"], ["recíbele", "him,"], ["como", "as"], ["a", "to"], ["mi", "my"], ["propio", "own"], ["corazón.", "heart."]]},
  {num:13,words:[["Yo", "I"], ["quisiera", "would-like"], ["retenerle", "retain-him/her"], ["conmigo,", "with-me,"], ["para", "for"], ["que", "that"], ["en", "in"], ["lugar", "place"], ["de", "of"], ["ti", "thee"], ["me", "me"], ["sirviese", "have"], ["en", "in"], ["las", "the"], ["prisiones", "bonds"], ["por", "by/for"], ["causa", "cause/sake"], ["del", "of-the"], ["evangelio;", "gospel;"]]},
  {num:14,words:[["pero", "but"], ["nada", "nothing"], ["quise", "would"], ["hacer", "make/do"], ["sin", "without"], ["tu", "thy"], ["consentimiento,", "nothing,"], ["para", "for"], ["que", "that"], ["tu", "thy"], ["favor", "favor"], ["no", "not"], ["fuese", "might-be"], ["como", "as"], ["por", "by/for"], ["obligación,", "that,"], ["sino", "but"], ["voluntario.", "willingly."]]},
  {num:15,words:[["Porque", "because"], ["quizá", "perhaps"], ["por", "by/for"], ["esto", "this"], ["se", "[refl.]"], ["ha", "has"], ["apartado", "separated"], ["de", "of"], ["ti", "thee"], ["por", "by/for"], ["algún", "some"], ["tiempo,", "time,"], ["para", "for"], ["que", "that"], ["le", "him/her"], ["recibieses", "for"], ["para", "for"], ["siempre;", "always;"]]},
  {num:16,words:[["no", "not"], ["ya", "already"], ["como", "as"], ["esclavo,", "free,"], ["sino", "but"], ["como", "as"], ["más", "more"], ["que", "that"], ["esclavo,", "free,"], ["como", "as"], ["hermano", "brother"], ["amado,", "beloved,"], ["mayormente", "of"], ["para", "for"], ["mí,", "me,"], ["pero", "but"], ["cuánto", "how-much"], ["más", "more"], ["para", "for"], ["ti,", "thee,"], ["tanto", "so-much"], ["en", "in"], ["la", "the"], ["carne", "flesh"], ["como", "as"], ["en", "in"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:17,words:[["Así", "thus"], ["que,", "that,"], ["si", "if"], ["me", "me"], ["tienes", "hast"], ["por", "by/for"], ["compañero,", "companion,"], ["recíbele", "partner,"], ["como", "as"], ["a", "to"], ["mí", "me"], ["mismo.", "same."]]},
  {num:18,words:[["Y", "and"], ["si", "if"], ["en", "in"], ["algo", "something"], ["te", "thee"], ["dañó,", "or,"], ["o", "or"], ["te", "thee"], ["debe,", "must,"], ["ponlo", "prophesy-it"], ["a", "to"], ["mi", "my"], ["cuenta.", "account."]]},
  {num:19,words:[["Yo,", "I,"], ["Pablo,", "paul,"], ["lo", "it/him"], ["escribo", "I-write"], ["de", "of"], ["mi", "my"], ["mano,", "hand,"], ["yo", "I"], ["lo", "it/him"], ["pagaré;", "will;"], ["por", "by/for"], ["no", "not"], ["decirte", "somewhat"], ["que", "that"], ["aun", "even"], ["tú", "thou"], ["mismo", "same"], ["te", "thee"], ["me", "me"], ["debes", "thou"], ["también.", "also."]]},
  {num:20,words:[["Sí,", "yea,"], ["hermano,", "brother,"], ["reciba", "receiveth"], ["yo", "I"], ["de", "of"], ["ti", "thee"], ["algún", "some"], ["beneficio", "benefit"], ["en", "in"], ["el", "the"], ["Señor;", "Lord;"], ["conforta", "refresh"], ["mi", "my"], ["corazón", "heart"], ["en", "in"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:21,words:[["Te", "thee"], ["he", "I-have"], ["escrito", "written"], ["confiando", "in"], ["en", "in"], ["tu", "thy"], ["obediencia,", "obedience,"], ["sabiendo", "knowing"], ["que", "that"], ["harás", "thou-shalt-make"], ["aún", "still/yet"], ["más", "more"], ["de", "of"], ["lo", "it/him"], ["que", "that"], ["te", "thee"], ["digo.", "I-say."]]},
  {num:22,words:[["Y", "and"], ["asimismo,", "likewise,"], ["prepárame", "me"], ["también", "also"], ["alojamiento,", "a,"], ["porque", "because"], ["espero", "trust"], ["que", "that"], ["por", "by/for"], ["vuestras", "your"], ["oraciones", "prayers"], ["yo", "I"], ["os", "you"], ["sea", "let-be/be"], ["concedido.", "granted."]]},
  {num:23,words:[["Te", "thee"], ["saludan", "salute"], ["Epafras,", "thee,"], ["mi", "my"], ["compañero", "companion"], ["de", "of"], ["prisión", "prison"], ["por", "by/for"], ["Cristo", "Christ"], ["Jesús,", "Jesus,"]]},
  {num:24,words:[["Marcos,", "and,"], ["Aristarco,", "aristarchus,"], ["Demas", "demas,"], ["y", "and"], ["Lucas,", "lucas,"], ["mis", "my"], ["colaboradores.", "fellowlabourers."]]},
  {num:25,words:[["La", "the"], ["gracia", "grace"], ["de", "of"], ["nuestro", "our"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["sea", "let-be/be"], ["con", "with"], ["vuestro", "your"], ["espíritu.", "Spirit."], ["Amén.", "amen."]]},
];
renderVerseSet(v1, 'phm-ch1-verses');

})();
