(function() {
var v1 = [
  {num:1,words:[["Pablo,","Paul,"],["prisionero","of"],["de","of"],["Jesucristo,","Jesus-Christ,"],["y","and"],["el","the"],["hermano","brother"],["Timoteo,","timotheus,"],["al","to-the"],["amado","beloved"],["Filemón,","dearly,"],["colaborador","beloved"],["nuestro,","our,"]]},
  {num:2,words:[["y","and"],["a","to"],["la","the"],["amada","beloved"],["hermana","sister"],["Apia,","apphia,"],["y","and"],["a","to"],["Arquipo,","Archippus,"],["nuestro","our"],["compañero","companion"],["de","of"],["milicia,","militia,"],["y","and"],["a","to"],["la","the"],["iglesia","church"],["que","that"],["está","is"],["en","in"],["tu","your"],["casa:","house:"]]},
  {num:3,words:[["Gracia", "grace"], ["a", "to"], ["vosotros", "you"], ["y", "and"], ["paz", "peace"], ["de", "of"], ["parte", "part"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Padre", "father"], ["y", "and"], ["del", "of-the"], ["Señor", "Lord"], ["Jesucristo.", "Jesus-Christ."]]},
  {num:4,words:[["Doy", "I-give"], ["gracias", "thanks"], ["a", "to"], ["mi", "my"], ["Dios,", "God,"], ["haciendo","making"], ["siempre", "always"], ["memoria", "remembrance"], ["de", "of"], ["ti","you"], ["en", "in"], ["mis", "my"], ["oraciones,", "prayers,"]]},
  {num:5,words:[["porque","because"],["oigo","I-hear"],["del","of-the"],["amor","love"],["y","and"],["de","of"],["la","the"],["fe","faith"],["que","that"],["tienes","you-have"],["hacia","toward"],["el","the"],["Señor","Lord"],["Jesús,","Jesus,"],["y","and"],["para","for"],["con","with"],["todos","all"],["los","the"],["santos;","saints;"]]},
  {num:6,words:[["para que","that"],["la","the"],["comunicación","communication"],["de","of"],["tu","your"],["fe","faith"],["sea","be"],["eficaz","effectual"],["en","in"],["el","the"],["conocimiento","knowledge"],["de","of"],["todo","all"],["el","the"],["bien","well"],["que","that"],["está","is"],["en","in"],["vosotros","you"],["mediante","through"],["Cristo","Christ"],["Jesús.","Jesus."]]},
  {num:7,words:[["Porque","because"],["tenemos","we-have"],["gran","great"],["gozo","I-joy"],["y","and"],["consolación","consolation"],["en","in"],["tu","your"],["amor,","love,"],["pues","for"],["por","for"],["ti,","you,"],["oh","oh"],["hermano,","brother,"],["ha","has"],["sido","been"],["reconfortado","saints"],["el","the"],["corazón","heart"],["de","of"],["los","the"],["santos.","saints."]]},
  {num:8,words:[["Por","for"],["lo","it/him"],["cual,","which,"],["aunque","although"],["tengo","I-have"],["mucha","much"],["franqueza","frankness"],["en","in"],["Cristo","Christ"],["para","for"],["mandarte","command-you"],["lo","it/him"],["que","that"],["conviene,","expedient,"]]},
  {num:9,words:[["más","more"],["bien","well"],["por","for"],["amor","love"],["te","you"],["ruego,","beseech,"],["siendo","being"],["como","as"],["soy,","I-am,"],["Pablo","Paul"],["ya","already"],["anciano,","ancient,"],["y","and"],["ahora,","now,"],["además,","also,"],["prisionero","of"],["de","of"],["Jesucristo.","Jesus-Christ."]]},
  {num:10,words:[["Te","you"], ["ruego","beseech"], ["por","for"], ["mi", "my"], ["hijo", "son"], ["Onésimo,", "son,"], ["a", "to"], ["quien", "who"], ["he", "I-have"], ["engendrado", "begotten"], ["en", "in"], ["mis", "my"], ["prisiones,", "bonds,"]]},
  {num:11,words:[["el","the"],["que","that"],["en","in"],["otro","other"],["tiempo","time"],["te","you"],["fue","was"],["inútil,","useless,"],["pero","but"],["ahora","now"],["a","to"],["ti","you"],["y","and"],["a","to"],["mí","me"],["nos","us"],["es","is"],["útil,","useful,"]]},
  {num:12,words:[["el","the"],["que","that"],["te","you"],["vuelvo","again"],["a","to"],["enviar;","send;"],["tú,","you,"],["pues,","for,"],["recíbele","receives-him"],["como","as"],["a","to"],["mi","my"],["propio","own"],["corazón.","heart."]]},
  {num:13,words:[["Yo","I"],["quisiera","would-like"],["retenerle","retain-him"],["conmigo,","with-me,"],["para que","that"],["en","in"],["lugar","place"],["de","of"],["ti","you"],["me","me"],["sirviese","might-serve"],["en","in"],["las","the"],["prisiones","bonds"],["por","for"],["causa","cause/sake"],["del","of-the"],["evangelio;","gospel;"]]},
  {num:14,words:[["pero","but"],["nada","nothing"],["quise","I-loved"],["hacer","do"],["sin","without"],["tu","your"],["consentimiento,","nothing,"],["para que","that"],["tu","your"],["favor","favor"],["no","not"],["fuese","might-be"],["como","as"],["por","for"],["obligación,","obligation,"],["sino","but"],["voluntario.","willingly."]]},
  {num:15,words:[["Porque","because"],["quizá","perhaps"],["por","for"],["esto","this"],["se","himself"],["ha","has"],["apartado","separated"],["de","of"],["ti","you"],["por","for"],["algún","some"],["tiempo,","time,"],["para que","that"],["le","him"],["recibieses","you-might-receive"],["para","for"],["siempre;","always;"]]},
  {num:16,words:[["no", "not"], ["ya", "already"], ["como", "as"], ["esclavo,", "free,"], ["sino", "but"], ["como", "as"], ["más", "more"], ["que", "that"], ["esclavo,", "free,"], ["como", "as"], ["hermano", "brother"], ["amado,", "beloved,"], ["mayormente", "of"], ["para", "for"], ["mí,", "me,"], ["pero", "but"], ["cuánto", "how-much"], ["más", "more"], ["para", "for"], ["ti,","you,"], ["tanto", "therefore"], ["en", "in"], ["la", "the"], ["carne", "flesh"], ["como", "as"], ["en", "in"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:17,words:[["Así que,","so,"],["si","if"],["me","me"],["tienes","have"],["por","for"],["compañero,","companion,"],["recíbele","receives-him"],["como","as"],["a","to"],["mí","me"],["mismo.","same."]]},
  {num:18,words:[["Y","and"],["si","if"],["en","in"],["algo","something"],["te","you"],["dañó,","harm,"],["o","or"],["te","you"],["debe,","must,"],["ponlo","put"],["a","to"],["mi","my"],["cuenta.","account."]]},
  {num:19,words:[["Yo,","I,"],["Pablo,","Paul,"],["lo","it"],["escribo","I-write"],["de","of"],["mi","my"],["mano,","hand,"],["yo","I"],["lo","it"],["pagaré;","I-will-pay;"],["por","for"],["no","not"],["decirte","says"],["que","that"],["aun","even"],["tú","you"],["mismo","same"],["te","you"],["me","me"],["debes","you"],["también.","also."]]},
  {num:20,words:[["Sí,","yes,"], ["hermano,", "brother,"], ["reciba","receives"], ["yo", "I"], ["de", "of"], ["ti","you"], ["algún", "some"], ["beneficio", "benefit"], ["en", "in"], ["el", "the"], ["Señor;", "Lord;"], ["conforta", "refresh"], ["mi", "my"], ["corazón", "heart"], ["en", "in"], ["el", "the"], ["Señor.", "Lord."]]},
  {num:21,words:[["Te","you"],["he","I-have"],["escrito","written"],["confiando","trusting"],["en","in"],["tu","your"],["obediencia,","obedience,"],["sabiendo","knowing"],["que","that"],["harás","you-will-make"],["aún","yet"],["más","more"],["de","of"],["lo","it/him"],["que","that"],["te","you"],["digo.","I-say."]]},
  {num:22,words:[["Y","and"],["asimismo,","likewise,"],["prepárame","for-me"],["también","also"],["alojamiento,","lodging,"],["porque","because"],["espero","I-trust"],["que","that"],["por","for"],["vuestras","your"],["oraciones","prayers"],["yo","I"],["os","you"],["sea","be"],["concedido.","granted."]]},
  {num:23,words:[["Te","you"],["saludan","salute"],["Epafras,","Epaphras,"],["mi","my"],["compañero","companion"],["de","of"],["prisión","prison"],["por","for"],["Cristo","Christ"],["Jesús,","Jesus,"]]},
  {num:24,words:[["Marcos,","Mark,"],["Aristarco,","Aristarchus,"],["Demas","Demas"],["y","and"],["Lucas,","lucas,"],["mis","my"],["colaboradores.","fellowlabourers."]]},
  {num:25,words:[["La","the"],["gracia","grace"],["de","of"],["nuestro","our"],["Señor","Lord"],["Jesucristo","Jesus-Christ"],["sea","be"],["con","with"],["vuestro","your"],["espíritu.","Spirit."],["Amén.","Amen."]]},
];
renderVerseSet(v1, 'phm-ch1-verses');

})();
