(function() {
var v1 = [
  {num:1,words:[["Cantar", "sing"], ["de", "of"], ["los", "the"], ["cantares,", "sings,"], ["el", "the"], ["cual", "which"], ["es", "is"], ["de", "of"], ["Salomón.", "Solomon."]]},
  {num:2,words:[["¡Oh", "oh"], ["si", "if"], ["él", "he"], ["me", "me"], ["besara", "with"], ["con", "with"], ["besos", "kisseds"], ["de", "of"], ["su", "his/her"], ["boca!Porque", "mouth:"], ["mejores", "better"], ["son", "are"], ["tus", "thy"], ["amores", "loves"], ["que", "that"], ["el", "the"], ["vino.", "wine."]]},
  {num:3,words:[["Olorosos", "because"], ["son", "are"], ["tus", "thy"], ["suaves", "thy"], ["ungüentos;ungüento", "good"], ["derramado", "shed"], ["es", "is"], ["tu", "thy"], ["nombre;por", "ointment"], ["eso", "that"], ["las", "the"], ["doncellas", "the"], ["te", "thee"], ["aman.", "love."]]},
  {num:4,words:[["Llévame", "bringeth-me"], ["en", "in"], ["pos", "follow"], ["de", "of"], ["ti.", "thee."], ["¡Corramos!El", "thee:"], ["rey", "king"], ["me", "me"], ["ha", "has"], ["llevado", "carried"], ["a", "to"], ["sus", "his/her"], ["habitaciones.Nos", "in-us"], ["gozaremos", "shall-to"], ["y", "and"], ["nos", "us"], ["alegraremos", "and"], ["contigo.Nos", "with-thee-us"], ["acordaremos", "thee,"], ["de", "of"], ["tus", "thy"], ["amores", "loves"], ["más", "more"], ["que", "that"], ["del", "of-the"], ["vino.Los", "wine-them"], ["justos", "righteous"], ["te", "thee"], ["aman.", "love."]]},
  {num:5,words:[["Morena", "i"], ["soy,", "I-am,"], ["oh", "oh"], ["hijas", "daughters"], ["de", "of"], ["Jerusalén,pero", "daughters"], ["hermosacomo", "of"], ["las", "the"], ["tiendas", "tents"], ["de", "of"], ["Cedar,como", "of"], ["las", "the"], ["cortinas", "curtains"], ["de", "of"], ["Salomón.", "Solomon."]]},
  {num:6,words:[["No", "not"], ["os", "you"], ["fijéis", "upon"], ["en", "in"], ["que", "that"], ["soy", "I-am"], ["morena,porque", "black,"], ["el", "the"], ["sol", "sun"], ["me", "me"], ["miró.Los", "looked-them"], ["hijos", "children"], ["de", "of"], ["mi", "my"], ["madre", "mother"], ["se", "[refl.]"], ["airaron", "with"], ["contra", "against"], ["mí;me", "me-me"], ["hicieron", "did/made"], ["guarda", "keeps"], ["de", "of"], ["las", "the"], ["viñas;y", "the"], ["mi", "my"], ["viña,", "vineyard,"], ["que", "that"], ["era", "was"], ["mía,", "mother,"], ["no", "not"], ["guardé.", "keep."]]},
  {num:7,words:[["Hazme", "me"], ["saber,", "know,"], ["oh", "oh"], ["tú", "thou"], ["a", "to"], ["quien", "who"], ["ama", "loveth"], ["mi", "my"], ["alma,dónde", "where"], ["apacientas,dónde", "thou"], ["haces", "doest"], ["descansar", "rest"], ["tu", "thy"], ["rebaño", "flock"], ["al", "to-the"], ["mediodía;pues,", "flock,"], ["¿por", "by/for"], ["qué", "what"], ["he", "I-have"], ["de", "of"], ["ser", "be"], ["yo", "I"], ["como", "as"], ["una", "a"], ["que", "that"], ["se", "[refl.]"], ["cubre", "covereth"], ["con", "with"], ["velojunto", "aside"], ["a", "to"], ["los", "the"], ["rebaños", "flocks"], ["de", "of"], ["tus", "thy"], ["compañeros?", "companions?"]]},
  {num:8,words:[["Si", "if"], ["tú", "thou"], ["no", "not"], ["lo", "it/him"], ["sabes,", "knowest,"], ["oh", "oh"], ["la", "the"], ["más", "more"], ["hermosa", "beautiful"], ["entre", "among"], ["las", "the"], ["mujeres,ve;", "way;"], ["sigue", "follow"], ["las", "the"], ["huellas", "the"], ["del", "of-the"], ["rebañoy", "of"], ["apacienta", "he"], ["tus", "thy"], ["cabritas", "little-goat"], ["junto", "together"], ["a", "to"], ["las", "the"], ["tiendas", "tents"], ["de", "of"], ["los", "the"], ["pastores.", "pastors."]]},
  {num:9,words:[["A", "to"], ["las", "the"], ["yeguas", "thee,"], ["de", "of"], ["los", "the"], ["carros", "chariots"], ["de", "of"], ["Faraónte", "Pharaoh-thee"], ["he", "I-have"], ["comparado,", "horses,"], ["amada", "beloved"], ["mía.", "mother."]]},
  {num:10,words:[["Hermosas", "and"], ["son", "are"], ["tus", "thy"], ["mejillas", "cheeks"], ["entre", "among"], ["los", "the"], ["pendientes,tu", "thy"], ["cuello", "neck"], ["entre", "among"], ["los", "the"], ["collares.", "gold."]]},
  {num:11,words:[["Adornos", "of"], ["de", "of"], ["oro", "gold"], ["te", "thee"], ["haremoscon", "gold"], ["incrustaciones", "with"], ["de", "of"], ["plata.", "silver."]]},
  {num:12,words:[["Mientras", "while"], ["el", "the"], ["rey", "king"], ["estaba", "was"], ["a", "to"], ["la", "the"], ["mesa,mi", "spikenard"], ["nardo", "sendeth"], ["esparció", "it"], ["su", "his/her"], ["olor.", "savour."]]},
  {num:13,words:[["Mi", "my"], ["amado", "beloved"], ["es", "is"], ["para", "for"], ["mí", "me"], ["un", "a"], ["manojito", "wellbeloved"], ["de", "of"], ["mirraque", "he"], ["reposa", "the"], ["toda", "all"], ["la", "the"], ["noche", "night"], ["entre", "among"], ["mis", "my"], ["pechos.", "breasts."]]},
  {num:14,words:[["Racimo", "my"], ["de", "of"], ["flores", "flowers"], ["de", "of"], ["alheña", "me"], ["en", "in"], ["las", "the"], ["viñas", "vineyards"], ["de", "of"], ["En-gadies", "in"], ["para", "for"], ["mí", "me"], ["mi", "my"], ["amado.", "beloved."]]},
  {num:15,words:[["He", "I-have"], ["aquí", "here"], ["que", "that"], ["tú", "thou"], ["eres", "thou-art"], ["hermosa,", "beautiful,"], ["amada", "beloved"], ["mía;he", "love;"], ["aquí", "here"], ["que", "that"], ["eres", "thou-art"], ["bella.", "fair."], ["Tus", "thy"], ["ojos", "eyes"], ["son", "are"], ["como", "as"], ["de", "of"], ["paloma.", "dove."]]},
  {num:16,words:[["He", "I-have"], ["aquí", "here"], ["que", "that"], ["tú", "thou"], ["eres", "thou-art"], ["hermoso,", "fair,"], ["amado", "beloved"], ["mío,", "mine,"], ["y", "and"], ["agradable;nuestro", "our"], ["lecho", "bed"], ["todo", "all"], ["verdor.", "green."]]},
  {num:17,words:[["Las", "the"], ["vigas", "beams"], ["de", "of"], ["nuestra", "our"], ["casa", "house"], ["son", "are"], ["de", "of"], ["cedro,y", "and"], ["de", "of"], ["ciprés,", "fir,"], ["los", "the"], ["artesonados.", "fir."]]},
];
renderVerseSet(v1, 'sng-ch1-verses');

var v2 = [
  {num:1,words:[["Yo", "I"], ["soy", "I-am"], ["la", "the"], ["rosa", "of"], ["de", "of"], ["Sarón,el", "and"], ["lirio", "the"], ["de", "of"], ["los", "the"], ["valles.", "valleys."]]},
  {num:2,words:[["Como", "as"], ["el", "the"], ["lirio", "lily"], ["entre", "among"], ["los", "the"], ["espinos,así", "so"], ["es", "is"], ["mi", "my"], ["amada", "beloved"], ["entre", "among"], ["las", "the"], ["doncellas.", "the."]]},
  {num:3,words:[["Como", "as"], ["el", "the"], ["manzano", "tree"], ["entre", "among"], ["los", "the"], ["árboles", "trees"], ["silvestres,así", "the"], ["es", "is"], ["mi", "my"], ["amado", "beloved"], ["entre", "among"], ["los", "the"], ["jóvenes;bajo", "sons."], ["su", "his/her"], ["sombra", "shadow"], ["con", "with"], ["deleite", "shall"], ["me", "me"], ["senté,y", "great"], ["su", "his/her"], ["fruto", "fruit"], ["fue", "was/went"], ["dulce", "sweet"], ["a", "to"], ["mi", "my"], ["paladar.", "mouth."]]},
  {num:4,words:[["Me", "me"], ["llevó", "carried"], ["a", "to"], ["la", "the"], ["casa", "house"], ["del", "of-the"], ["banquete,y", "house,"], ["su", "his/her"], ["bandera", "standard"], ["sobre", "upon"], ["mí", "me"], ["fue", "was/went"], ["amor.", "love."]]},
  {num:5,words:[["Sustentadme", "stay"], ["con", "with"], ["tortas,refrescadme", "flagons,"], ["con", "with"], ["manzanas;porque", "with"], ["estoy", "I-am"], ["enferma", "sick"], ["de", "of"], ["amor.", "love."]]},
  {num:6,words:[["Su", "his/her"], ["izquierda", "left"], ["esté", "be"], ["debajo", "beneath"], ["de", "of"], ["mi", "my"], ["cabeza,y", "his"], ["su", "his/her"], ["derecha", "right"], ["me", "me"], ["abrace.", "me."]]},
  {num:7,words:[["Yo", "I"], ["os", "you"], ["ruego,", "I-pray/beseech,"], ["oh", "oh"], ["hijas", "daughters"], ["de", "of"], ["Jerusalén,por", "by"], ["las", "the"], ["gacelas", "thes"], ["y", "and"], ["por", "by/for"], ["las", "the"], ["ciervas", "the"], ["del", "of-the"], ["campo,que", "that"], ["no", "not"], ["despertéis", "not"], ["ni", "nor"], ["desveléis", "nor"], ["al", "to-the"], ["amadohasta", "love,"], ["que", "that"], ["quiera.", "whosoever."]]},
  {num:8,words:[["¡La", "the"], ["voz", "voice"], ["de", "of"], ["mi", "my"], ["amado!", "beloved!"], ["He", "I-have"], ["aquí,", "here,"], ["él", "he"], ["viene,saltando", "upon"], ["por", "by/for"], ["los", "the"], ["montes,brincando", "skipping"], ["por", "by/for"], ["los", "the"], ["collados.", "hills."]]},
  {num:9,words:[["Mi", "my"], ["amado", "beloved"], ["es", "is"], ["semejante", "like"], ["a", "to"], ["la", "the"], ["gacela", "the"], ["o", "or"], ["al", "to-the"], ["cervatillo.Helo", "he"], ["aquí,", "here,"], ["está", "is"], ["detrás", "behind"], ["de", "of"], ["nuestro", "our"], ["muro,mirando", "forth"], ["por", "by/for"], ["las", "the"], ["ventanas,atisbando", "shewing"], ["por", "by/for"], ["las", "the"], ["celosías.", "lattice."]]},
  {num:10,words:[["Mi", "my"], ["amado", "beloved"], ["habló", "spoke"], ["y", "and"], ["me", "me"], ["dijo:Levántate,", "rise,"], ["oh", "oh"], ["amada", "beloved"], ["mía,", "mother,"], ["hermosa", "beautiful"], ["mía,", "mother,"], ["y", "and"], ["ven.", "come/see."]]},
  {num:11,words:[["Porque", "because"], ["he", "I-have"], ["aquí", "here"], ["ha", "has"], ["pasado", "past"], ["el", "the"], ["invierno,la", "winter-her"], ["lluvia", "rain"], ["ha", "has"], ["cesado", "ceased"], ["y", "and"], ["se", "[refl.]"], ["ha", "has"], ["ido;", "gone;"]]},
  {num:12,words:[["han", "have"], ["aparecido", "appeared"], ["las", "the"], ["flores", "flowers"], ["en", "in"], ["la", "the"], ["tierra,el", "time"], ["tiempo", "time"], ["de", "of"], ["la", "the"], ["canción", "the"], ["ha", "has"], ["venido,y", "come,"], ["en", "in"], ["nuestro", "our"], ["país", "country"], ["se", "[refl.]"], ["oye", "hears"], ["el", "the"], ["arrullo", "is"], ["de", "of"], ["la", "the"], ["tórtola.", "land."]]},
  {num:13,words:[["La", "the"], ["higuera", "fig"], ["ha", "has"], ["dado", "given"], ["sus", "his/her"], ["verdes", "truths"], ["higos,y", "and"], ["las", "the"], ["vides", "and"], ["en", "in"], ["cierne", "tender"], ["han", "have"], ["esparcidosu", "a"], ["fragancia.Levántate,", "good,"], ["oh", "oh"], ["amada", "beloved"], ["mía,", "mother,"], ["hermosa", "beautiful"], ["mía,", "mother,"], ["y", "and"], ["ven.", "come/see."]]},
  {num:14,words:[["Paloma", "dove"], ["mía,", "mother,"], ["que", "that"], ["anidas", "art"], ["en", "in"], ["las", "the"], ["grietas", "of"], ["de", "of"], ["la", "the"], ["peña,en", "the"], ["lo", "it/him"], ["escondido", "hid"], ["de", "of"], ["escarpados", "stairs,"], ["parajes,muéstrame", "let"], ["tu", "thy"], ["rostro,", "face,"], ["hazme", "me"], ["oír", "hear"], ["tu", "thy"], ["voz,porque", "thy"], ["dulce", "sweet"], ["es", "is"], ["tu", "thy"], ["voz", "voice"], ["y", "and"], ["hermoso", "fair"], ["tu", "thy"], ["aspecto.", "appearance."]]},
  {num:15,words:[["Cazadnos", "take"], ["las", "the"], ["zorras,las", "the"], ["zorras", "foxes,"], ["pequeñasque", "little"], ["echan", "cast"], ["a", "to"], ["perder", "lose"], ["las", "the"], ["viñas,pues", "vines:"], ["nuestras", "provisions"], ["viñas", "vineyards"], ["están", "are"], ["en", "in"], ["flor.", "flower."]]},
  {num:16,words:[["Mi", "my"], ["amado", "beloved"], ["es", "is"], ["mío,", "mine,"], ["y", "and"], ["yo", "I"], ["suya;él", "his:"], ["apacienta", "he"], ["entre", "among"], ["los", "the"], ["lirios.", "lilies."]]},
  {num:17,words:[["Hasta", "until"], ["que", "that"], ["despunte", "day"], ["el", "the"], ["día", "day"], ["y", "and"], ["huyan", "flee"], ["las", "the"], ["sombras,vuelve,", "my,"], ["amado", "beloved"], ["mío;sé", "and"], ["semejante", "like"], ["a", "to"], ["la", "the"], ["gacela", "the"], ["o", "or"], ["al", "to-the"], ["cervatillosobre", "hart"], ["los", "the"], ["montes", "mountains"], ["de", "of"], ["Beter.", "bether."]]},
];
renderVerseSet(v2, 'sng-ch2-verses');

var v3 = [
  {num:1,words:[["Por", "by/for"], ["las", "the"], ["noches", "nights"], ["busqué", "sought"], ["en", "in"], ["mi", "my"], ["lechoal", "whom"], ["que", "that"], ["ama", "loveth"], ["mi", "my"], ["alma;lo", "soul-it"], ["busqué,", "sought,"], ["mas", "but"], ["no", "not"], ["lo", "it/him"], ["hallé.", "found."]]},
  {num:2,words:[["Me", "me"], ["levantaré", "raise"], ["ahora", "now"], ["y", "and"], ["recorreré", "about"], ["la", "the"], ["ciudad;por", "in"], ["las", "the"], ["calles", "streets"], ["y", "and"], ["por", "by/for"], ["las", "the"], ["plazasbuscaré", "i"], ["al", "to-the"], ["que", "that"], ["ama", "loveth"], ["mi", "my"], ["alma;lo", "soul-it"], ["busqué,", "sought,"], ["mas", "but"], ["no", "not"], ["lo", "it/him"], ["hallé.", "found."]]},
  {num:3,words:[["Me", "me"], ["hallaron", "found"], ["los", "the"], ["guardias", "guards"], ["que", "that"], ["rondan", "city"], ["la", "the"], ["ciudad,y", "me:"], ["les", "them"], ["dije:", "I-said:"], ["¿Habéis", "you-have"], ["visto", "seen"], ["al", "to-the"], ["que", "that"], ["ama", "loveth"], ["mi", "my"], ["alma?", "soul?"]]},
  {num:4,words:[["Apenas", "scarcely"], ["me", "me"], ["aparté", "i"], ["de", "of"], ["ellos", "they"], ["un", "a"], ["poco,hallé", "from"], ["luego", "then"], ["al", "to-the"], ["que", "that"], ["ama", "loveth"], ["mi", "my"], ["alma;me", "soul-me"], ["aferré", "i"], ["a", "to"], ["él,", "he,"], ["y", "and"], ["no", "not"], ["lo", "it/him"], ["dejéhasta", "go,"], ["llevarlo", "carry-it"], ["a", "to"], ["casa", "house"], ["de", "of"], ["mi", "my"], ["madre,a", "mothers"], ["la", "the"], ["habitación", "habitation"], ["de", "of"], ["la", "the"], ["que", "that"], ["me", "me"], ["concibió.", "conceived."]]},
  {num:5,words:[["Yo", "I"], ["os", "you"], ["ruego,", "I-pray/beseech,"], ["oh", "oh"], ["hijas", "daughters"], ["de", "of"], ["Jerusalén,por", "by"], ["las", "the"], ["gacelas", "thes"], ["y", "and"], ["por", "by/for"], ["las", "the"], ["ciervas", "the"], ["del", "of-the"], ["campo,que", "that"], ["no", "not"], ["despertéis", "not"], ["ni", "nor"], ["desveléis", "nor"], ["al", "to-the"], ["amado,hasta", "love,"], ["que", "that"], ["quiera.", "whosoever."]]},
  {num:6,words:[["¿Quién", "who"], ["es", "is"], ["esta", "this"], ["que", "that"], ["sube", "goeth"], ["del", "of-the"], ["desiertocual", "the"], ["columna", "pillar"], ["de", "of"], ["humo,perfumada", "pillars"], ["de", "of"], ["mirra", "myrrh"], ["y", "and"], ["de", "of"], ["incienso,y", "and"], ["de", "of"], ["todo", "all"], ["polvo", "dust"], ["aromático", "anointing"], ["del", "of-the"], ["mercader?", "merchant?"]]},
  {num:7,words:[["He", "I-have"], ["aquí,", "here,"], ["la", "the"], ["litera", "is"], ["de", "of"], ["Salomón;sesenta", "valiant"], ["valientes", "valour"], ["la", "the"], ["rodean,de", "about"], ["los", "the"], ["valientes", "valour"], ["de", "of"], ["Israel.", "Israel."]]},
  {num:8,words:[["Todos", "all"], ["ellos", "they"], ["tienen", "have"], ["espadas", "swords"], ["y", "and"], ["son", "are"], ["diestros", "of"], ["en", "in"], ["la", "the"], ["guerra;cada", "man"], ["uno", "one"], ["su", "his/her"], ["espada", "sword"], ["sobre", "upon"], ["el", "the"], ["muslo,por", "because"], ["los", "the"], ["temores", "fears"], ["de", "of"], ["la", "the"], ["noche.", "night."]]},
  {num:9,words:[["El", "the"], ["rey", "king"], ["Salomón", "Solomon"], ["se", "[refl.]"], ["hizo", "made/did"], ["una", "a"], ["carrozade", "the"], ["madera", "wood"], ["del", "of-the"], ["Líbano.", "lebanon."]]},
  {num:10,words:[["Sus", "his/her"], ["columnas", "fillets"], ["hizo", "made/did"], ["de", "of"], ["plata,su", "silver,"], ["respaldo", "bottom"], ["de", "of"], ["oro,", "gold,"], ["su", "his/her"], ["asiento", "seat"], ["de", "of"], ["grana,su", "purple,"], ["interior", "inner"], ["tapizado", "thereof"], ["de", "of"], ["amorpor", "with"], ["las", "the"], ["hijas", "daughters"], ["de", "of"], ["Jerusalén.", "Jerusalem."]]},
  {num:11,words:[["Salid,", "go,"], ["oh", "oh"], ["hijas", "daughters"], ["de", "of"], ["Sion,", "Zion,"], ["y", "and"], ["ved", "see"], ["al", "to-the"], ["rey", "king"], ["Salomóncon", "with"], ["la", "the"], ["corona", "crown"], ["con", "with"], ["que", "that"], ["le", "him/her"], ["coronó", "him"], ["su", "his/her"], ["madreel", "day"], ["día", "day"], ["de", "of"], ["su", "his/her"], ["boda,y", "and"], ["el", "the"], ["día", "day"], ["del", "of-the"], ["gozo", "joy"], ["de", "of"], ["su", "his/her"], ["corazón.", "heart."]]},
];
renderVerseSet(v3, 'sng-ch3-verses');

var v4 = [
  {num:1,words:[["He", "I-have"], ["aquí,", "here,"], ["¡qué", "what"], ["hermosa", "beautiful"], ["eres,", "thou-art,"], ["amada", "beloved"], ["mía!,he", "behold,"], ["aquí,", "here,"], ["¡qué", "what"], ["hermosa", "beautiful"], ["eres!Tus", "fair;"], ["ojos", "eyes"], ["son", "are"], ["como", "as"], ["de", "of"], ["paloma", "dove"], ["detrás", "behind"], ["de", "of"], ["tu", "thy"], ["velo;tus", "hair"], ["cabellos,", "hairs,"], ["como", "as"], ["manada", "of"], ["de", "of"], ["cabrasque", "of"], ["se", "[refl.]"], ["recuestan", "goats,"], ["en", "in"], ["el", "the"], ["monte", "mount"], ["de", "of"], ["Galaad.", "Gilead."]]},
  {num:2,words:[["Tus", "thy"], ["dientes,", "gnashing,"], ["como", "as"], ["manada", "of"], ["de", "of"], ["ovejas", "sheep"], ["trasquiladasque", "are"], ["suben", "of"], ["del", "of-the"], ["lavadero,todas", "came"], ["con", "with"], ["crías", "young"], ["gemelas,y", "washing;"], ["ninguna", "none"], ["de", "of"], ["ellas", "they"], ["ha", "has"], ["perdido", "lost"], ["su", "his/her"], ["cría.", "thy."]]},
  {num:3,words:[["Tus", "thy"], ["labios,", "lips,"], ["como", "as"], ["hilo", "and"], ["de", "of"], ["grana,y", "scarlet,"], ["tu", "thy"], ["boca", "mouth"], ["hermosa;tus", "comely:"], ["sienes,", "thy,"], ["como", "as"], ["gajos", "like"], ["de", "of"], ["granadadetrás", "of"], ["de", "of"], ["tu", "thy"], ["velo.", "vail."]]},
  {num:4,words:[["Tu", "thy"], ["cuello,", "neck,"], ["como", "as"], ["la", "the"], ["torre", "tower"], ["de", "of"], ["David,edificada", "for"], ["para", "for"], ["armería;de", "whereon"], ["ella", "she"], ["cuelgan", "hang"], ["mil", "thousand"], ["escudos,escudos", "bucklers,"], ["todos", "all"], ["de", "of"], ["valientes.", "valour."]]},
  {num:5,words:[["Tus", "thy"], ["dos", "two"], ["pechos,", "breasts,"], ["como", "as"], ["crías", "young"], ["gemelas", "roes"], ["de", "of"], ["gacelaque", "are"], ["se", "[refl.]"], ["apacientan", "feed"], ["entre", "among"], ["lirios.", "lilies."]]},
  {num:6,words:[["Hasta", "until"], ["que", "that"], ["despunte", "break,"], ["el", "the"], ["día", "day"], ["y", "and"], ["huyan", "flee"], ["las", "the"], ["sombras,me", "shadows-me"], ["iré", "go"], ["al", "to-the"], ["monte", "mount"], ["de", "of"], ["la", "the"], ["mirra,y", "and"], ["al", "to-the"], ["collado", "hill"], ["del", "of-the"], ["incienso.", "incense."]]},
  {num:7,words:[["Toda", "all"], ["tú", "thou"], ["eres", "thou-art"], ["hermosa,", "beautiful,"], ["amada", "beloved"], ["mía,y", "love;"], ["en", "in"], ["ti", "thee"], ["no", "not"], ["hay", "there-is"], ["mancha.", "spotless."]]},
  {num:8,words:[["Ven", "come/see"], ["conmigo", "with-me"], ["del", "of-the"], ["Líbano,", "lebanon,"], ["oh", "oh"], ["esposa", "wife"], ["mía,del", "spouse,"], ["Líbano", "lebanon"], ["conmigo", "with-me"], ["ven.Mira", "lebanon:"], ["desde", "from"], ["la", "the"], ["cumbre", "top"], ["del", "of-the"], ["Amana,desde", "of"], ["la", "the"], ["cumbre", "top"], ["del", "of-the"], ["Senir", "top"], ["y", "and"], ["del", "of-the"], ["Hermón,desde", "and"], ["las", "the"], ["guaridas", "as"], ["de", "of"], ["los", "the"], ["leones,desde", "from"], ["los", "the"], ["montes", "mountains"], ["de", "of"], ["los", "the"], ["leopardos.", "leopards."]]},
  {num:9,words:[["Has", "thou-hast"], ["cautivado", "hast"], ["mi", "my"], ["corazón,", "heart,"], ["hermana", "sister"], ["mía,", "mother,"], ["esposa", "wife"], ["mía;has", "spouse;"], ["cautivado", "thou"], ["mi", "my"], ["corazón", "heart"], ["con", "with"], ["una", "a"], ["mirada", "that"], ["de", "of"], ["tus", "thy"], ["ojos,con", "thine"], ["un", "a"], ["solo", "alone"], ["dije", "I-said"], ["de", "of"], ["tu", "thy"], ["gargantilla.", "neck."]]},
  {num:10,words:[["¡Cuán", "how"], ["hermosos", "beautiful"], ["son", "are"], ["tus", "thy"], ["amores,", "loves,"], ["hermana", "sister"], ["mía,", "mother,"], ["esposa", "wife"], ["mía!¡Cuánto", "spouse!"], ["mejores", "better"], ["que", "that"], ["el", "the"], ["vino", "wine"], ["tus", "thy"], ["amores,y", "than"], ["la", "the"], ["fragancia", "and"], ["de", "of"], ["tus", "thy"], ["ungüentosmejor", "of"], ["que", "that"], ["todas", "all"], ["las", "the"], ["especias", "spices"], ["aromáticas!", "spices!"]]},
  {num:11,words:[["Como", "as"], ["panal", "honeycomb"], ["de", "of"], ["miel", "floweth"], ["destilan", "spouse,"], ["tus", "thy"], ["labios,", "lips,"], ["oh", "oh"], ["esposa;miel", "honey"], ["y", "and"], ["leche", "floweth"], ["hay", "there-is"], ["debajo", "beneath"], ["de", "of"], ["tu", "thy"], ["lengua;y", "and"], ["la", "the"], ["fragancia", "smell"], ["de", "of"], ["tus", "thy"], ["vestidos", "garments"], ["como", "as"], ["el", "the"], ["olor", "savour"], ["del", "of-the"], ["Líbano.", "lebanon."]]},
  {num:12,words:[["Huerto", "garden"], ["cerrado", "closed"], ["eres,", "thou-art,"], ["hermana", "sister"], ["mía,", "mother,"], ["esposa", "wife"], ["mía;fuente", "spring"], ["cerrada,", "shut,"], ["fuente", "laver"], ["sellada.", "sealed."]]},
  {num:13,words:[["Tus", "thy"], ["renuevos", "the"], ["paraíso", "paradise"], ["de", "of"], ["granados,con", "of"], ["frutos", "fruits"], ["exquisitos,de", "with"], ["alheña", "pleasant"], ["y", "and"], ["de", "of"], ["nardos,", "spikenard,"]]},
  {num:14,words:[["nardo", "spikenard"], ["y", "and"], ["azafrán,caña", "saffron;"], ["aromática", "anointing"], ["y", "and"], ["canela,con", "cinnamon,"], ["todos", "all"], ["los", "the"], ["árboles", "trees"], ["de", "of"], ["incienso;mirra", "myrrh"], ["y", "and"], ["áloes,con", "aloes,"], ["todas", "all"], ["las", "the"], ["principales", "chief"], ["especias", "spices"], ["aromáticas.", "spices."]]},
  {num:15,words:[["Fuente", "laver"], ["de", "of"], ["huertos,pozo", "gardens,"], ["de", "of"], ["aguas", "waters"], ["vivas,y", "living"], ["corrientes", "of"], ["del", "of-the"], ["Líbano.", "lebanon."]]},
  {num:16,words:[["Despierta,", "awake,"], ["Aquilón,y", "north"], ["ven,", "come/see,"], ["Austro;soplad", "come,"], ["en", "in"], ["mi", "my"], ["huerto;", "garden;"], ["despréndanse", "garden,"], ["sus", "his/her"], ["aromas.Venga", "spices"], ["mi", "my"], ["amado", "beloved"], ["a", "to"], ["su", "his/her"], ["huertoy", "come"], ["coma", "eateth"], ["de", "of"], ["su", "his/her"], ["dulce", "sweet"], ["fruta.", "the."]]},
];
renderVerseSet(v4, 'sng-ch4-verses');

var v5 = [
  {num:1,words:[["He", "I-have"], ["venido", "come"], ["a", "to"], ["mi", "my"], ["huerto,", "garden,"], ["oh", "oh"], ["hermana,", "sister,"], ["esposa", "wife"], ["mía;he", "i"], ["recogido", "gathered"], ["mi", "my"], ["mirra", "myrrh"], ["y", "and"], ["mis", "my"], ["especias", "spices"], ["aromáticas;he", "i"], ["comido", "eaten"], ["mi", "my"], ["panal", "honeycomb"], ["y", "and"], ["mi", "my"], ["miel,mi", "i"], ["vino", "wine"], ["y", "and"], ["mi", "my"], ["leche", "floweth"], ["he", "I-have"], ["bebido.Comed,", "milk,"], ["oh", "oh"], ["amigos;bebed,", "friends,"], ["oh", "oh"], ["amados,", "beloved,"], ["bebed", "drink"], ["en", "in"], ["abundancia.", "abundance."]]},
  {num:2,words:[["Yo", "I"], ["dormía,", "was-toing,"], ["pero", "but"], ["mi", "my"], ["corazón", "heart"], ["velaba.La", "was-watching-her"], ["voz", "voice"], ["de", "of"], ["mi", "my"], ["amado", "beloved"], ["que", "that"], ["llama:Ábreme,", "knocketh,"], ["hermana", "sister"], ["mía,", "mother,"], ["amiga", "friend"], ["mía,", "mother,"], ["paloma", "dove"], ["mía,", "mother,"], ["perfecta", "perfect"], ["mía;porque", "dove,"], ["mi", "my"], ["cabeza", "head"], ["está", "is"], ["cubierta", "badgers"], ["de", "of"], ["rocíoy", "with"], ["mis", "my"], ["cabellos", "hairs"], ["de", "of"], ["las", "the"], ["gotas", "the"], ["de", "of"], ["la", "the"], ["noche.", "night."]]},
  {num:3,words:[["Me", "me"], ["he", "I-have"], ["quitado", "taken"], ["la", "the"], ["ropa;¿cómo", "coat;"], ["he", "I-have"], ["de", "of"], ["ponérmela", "put/place-me-her"], ["otra", "other"], ["vez?He", "i"], ["lavado", "washed"], ["mis", "my"], ["pies;¿cómo", "feet;"], ["los", "the"], ["he", "I-have"], ["de", "of"], ["ensuciar?", "them?"]]},
  {num:4,words:[["Mi", "my"], ["amado", "beloved"], ["metió", "the"], ["su", "his/her"], ["mano", "hand"], ["por", "by/for"], ["la", "the"], ["abertura", "the"], ["de", "of"], ["la", "the"], ["puerta,y", "door,"], ["mis", "my"], ["entrañas", "bowels"], ["se", "[refl.]"], ["conmovieron", "moved"], ["por", "by/for"], ["él.", "he."]]},
  {num:5,words:[["Yo", "I"], ["me", "me"], ["levanté", "arose"], ["para", "for"], ["abrir", "open"], ["a", "to"], ["mi", "my"], ["amado,y", "and"], ["de", "of"], ["mis", "my"], ["manos", "hands"], ["goteaba", "myrrh,"], ["mirra,y", "and"], ["de", "of"], ["mis", "my"], ["dedos", "fingers"], ["corría", "the"], ["mirrasobre", "myrrh,"], ["el", "the"], ["pestillo", "the"], ["de", "of"], ["la", "the"], ["cerradura.", "lock."]]},
  {num:6,words:[["Abrí", "i"], ["yo", "I"], ["a", "to"], ["mi", "my"], ["amado,pero", "but"], ["mi", "my"], ["amado", "beloved"], ["se", "[refl.]"], ["había", "had"], ["retirado,", "from,"], ["ya", "already"], ["se", "[refl.]"], ["había", "had"], ["ido;y", "failed"], ["tras", "after"], ["su", "his/her"], ["hablar", "speak"], ["salió", "departed"], ["mi", "my"], ["alma.Lo", "soul-it"], ["busqué", "sought"], ["y", "and"], ["no", "not"], ["lo", "it/him"], ["hallé;lo", "found-it"], ["llamé,", "called,"], ["y", "and"], ["no", "not"], ["me", "me"], ["respondió.", "answered."]]},
  {num:7,words:[["Me", "me"], ["hallaron", "found"], ["los", "the"], ["guardias", "guards"], ["que", "that"], ["rondan", "found"], ["la", "the"], ["ciudad;me", "city-me"], ["golpearon,", "they,"], ["me", "me"], ["hirieron,me", "edge-me"], ["quitaron", "away"], ["mi", "my"], ["manto", "mantle"], ["los", "the"], ["guardias", "guards"], ["de", "of"], ["los", "the"], ["muros.", "walls."]]},
  {num:8,words:[["Yo", "I"], ["os", "you"], ["ruego,", "I-pray/beseech,"], ["oh", "oh"], ["hijas", "daughters"], ["de", "of"], ["Jerusalén,si", "ye"], ["halláis", "ye"], ["a", "to"], ["mi", "my"], ["amado,hacedle", "ye"], ["saber", "know"], ["que", "that"], ["estoy", "I-am"], ["enferma", "sick"], ["de", "of"], ["amor.", "love."]]},
  {num:9,words:[["¿Qué", "what"], ["es", "is"], ["tu", "thy"], ["amado", "beloved"], ["más", "more"], ["que", "that"], ["otro", "other"], ["amado,oh", "beloved,"], ["tú,", "thou,"], ["la", "the"], ["más", "more"], ["hermosa", "beautiful"], ["de", "of"], ["todas", "all"], ["las", "the"], ["mujeres?¿Qué", "is"], ["es", "is"], ["tu", "thy"], ["amado", "beloved"], ["más", "more"], ["que", "that"], ["otro", "other"], ["amado,para", "that"], ["que", "that"], ["así", "thus"], ["nos", "us"], ["hagas", "pray"], ["jurar?", "swear?"]]},
  {num:10,words:[["Mi", "my"], ["amado", "beloved"], ["es", "is"], ["blanco", "white"], ["y", "and"], ["sonrosado,distinguido", "the"], ["entre", "among"], ["diez", "ten"], ["mil.", "thousand."]]},
  {num:11,words:[["Su", "his/her"], ["cabeza,", "head,"], ["como", "as"], ["oro", "gold"], ["finísimo;sus", "fine"], ["cabellos", "hairs"], ["crespos,", "locks,"], ["negros", "bushy,"], ["como", "as"], ["el", "the"], ["cuervo.", "a."]]},
  {num:12,words:[["Sus", "his/her"], ["ojos,", "eyes,"], ["como", "as"], ["palomas", "doves"], ["junto", "together"], ["a", "to"], ["los", "the"], ["arroyos", "rivers"], ["de", "of"], ["aguas,bañados", "of"], ["en", "in"], ["leche,y", "washed"], ["a", "to"], ["la", "the"], ["perfección", "perfection"], ["colocados.", "tos."]]},
  {num:13,words:[["Sus", "his/her"], ["mejillas,", "cheeks,"], ["como", "as"], ["una", "a"], ["era", "was"], ["de", "of"], ["especias", "spices"], ["aromáticas,como", "as"], ["fragantes", "sweet"], ["flores;sus", "flowers:"], ["labios,", "lips,"], ["como", "as"], ["lirios", "lilies"], ["que", "that"], ["destilan", "sweet"], ["mirra", "myrrh"], ["fragante.", "myrrh."]]},
  {num:14,words:[["Sus", "his/her"], ["manos,", "hands,"], ["como", "as"], ["anillos", "rings"], ["de", "of"], ["oro", "gold"], ["engastados", "with"], ["de", "of"], ["piedras", "stones"], ["preciosas;su", "his"], ["vientre,", "belly,"], ["como", "as"], ["claro", "and"], ["marfil", "ivory"], ["cubierto", "covered"], ["de", "of"], ["zafiros.", "sapphires."]]},
  {num:15,words:[["Sus", "his/her"], ["piernas,", "legs,"], ["como", "as"], ["columnas", "fillets"], ["de", "of"], ["mármolfundadas", "marble,"], ["sobre", "upon"], ["basas", "fillets"], ["de", "of"], ["oro", "gold"], ["fino;su", "gold:"], ["aspecto,", "appearance,"], ["como", "as"], ["el", "the"], ["Líbano,escogido", "lebanon,"], ["como", "as"], ["los", "the"], ["cedros.", "cedars."]]},
  {num:16,words:[["Su", "his/her"], ["paladar,", "mouth,"], ["dulcísimo;y", "most"], ["todo", "all"], ["él,", "he,"], ["deseable.Tal", "is"], ["es", "is"], ["mi", "my"], ["amado,", "beloved,"], ["tal", "such"], ["es", "is"], ["mi", "my"], ["amigo,oh", "my"], ["hijas", "daughters"], ["de", "of"], ["Jerusalén.", "Jerusalem."]]},
];
renderVerseSet(v5, 'sng-ch5-verses');

var v6 = [
  {num:1,words:[["¿Adónde", "whither"], ["se", "[refl.]"], ["ha", "has"], ["ido", "gone"], ["tu", "thy"], ["amado,oh", "o"], ["tú,", "thou,"], ["la", "the"], ["más", "more"], ["hermosa", "beautiful"], ["entre", "among"], ["las", "the"], ["mujeres?¿Adónde", "beloved"], ["se", "[refl.]"], ["ha", "has"], ["dirigido", "toed"], ["tu", "thy"], ["amado,para", "may"], ["que", "that"], ["le", "him/her"], ["busquemos", "with"], ["contigo?", "with-thee?"]]},
  {num:2,words:[["Mi", "my"], ["amado", "beloved"], ["descendió", "descended"], ["a", "to"], ["su", "his/her"], ["huerto,a", "his"], ["las", "the"], ["eras", "wast"], ["de", "of"], ["las", "the"], ["especias", "spices"], ["aromáticas,a", "spices,"], ["apacentar", "feed"], ["en", "in"], ["los", "the"], ["huertosy", "gardens,"], ["a", "to"], ["recoger", "gather"], ["los", "the"], ["lirios.", "lilies."]]},
  {num:3,words:[["Yo", "I"], ["soy", "I-am"], ["de", "of"], ["mi", "my"], ["amado,", "beloved,"], ["y", "and"], ["mi", "my"], ["amado", "beloved"], ["es", "is"], ["mío;él", "he"], ["apacienta", "he"], ["entre", "among"], ["los", "the"], ["lirios.", "lilies."]]},
  {num:4,words:[["Hermosa", "beautiful"], ["eres", "thou-art"], ["tú,", "thou,"], ["oh", "oh"], ["amiga", "friend"], ["mía,", "mother,"], ["como", "as"], ["Tirsa;deseable,", "as,"], ["como", "as"], ["Jerusalén;imponente", "terrible"], ["como", "as"], ["ejércitos", "armies"], ["con", "with"], ["estandartes.", "banners."]]},
  {num:5,words:[["Aparta", "turn"], ["tus", "thy"], ["ojos", "eyes"], ["de", "of"], ["delante", "before"], ["de", "of"], ["mí,porque", "they"], ["ellos", "they"], ["me", "me"], ["han", "have"], ["cautivado.Tu", "thy"], ["cabello", "hair"], ["es", "is"], ["como", "as"], ["manada", "of"], ["de", "of"], ["cabrasque", "goats"], ["se", "[refl.]"], ["recuestan", "appear"], ["en", "in"], ["Galaad.", "Gilead."]]},
  {num:6,words:[["Tus", "thy"], ["dientes,", "gnashing,"], ["como", "as"], ["manada", "of"], ["de", "of"], ["ovejasque", "sheep"], ["suben", "of"], ["del", "of-the"], ["lavadero,todas", "from"], ["con", "with"], ["crías", "young"], ["gemelas,y", "one"], ["ninguna", "none"], ["de", "of"], ["ellas", "they"], ["ha", "has"], ["perdido", "lost"], ["su", "his/her"], ["cría.", "thy."]]},
  {num:7,words:[["Como", "as"], ["gajos", "a"], ["de", "of"], ["granada", "a"], ["son", "are"], ["tus", "thy"], ["sienesdetrás", "thy"], ["de", "of"], ["tu", "thy"], ["velo.", "vail."]]},
  {num:8,words:[["Sesenta", "sixty"], ["son", "are"], ["las", "the"], ["reinas,y", "queens,"], ["ochenta", "eighty"], ["las", "the"], ["concubinas,y", "concubines,"], ["las", "the"], ["doncellas", "the"], ["sin", "without"], ["número;", "number;"]]},
  {num:9,words:[["mas", "but"], ["una", "a"], ["es", "is"], ["la", "the"], ["paloma", "dove"], ["mía,", "mother,"], ["la", "the"], ["perfecta", "perfect"], ["mía;es", "mothers"], ["la", "the"], ["única", "and"], ["de", "of"], ["su", "his/her"], ["madre,la", "mother-her"], ["escogida", "choice"], ["de", "of"], ["la", "the"], ["que", "that"], ["la", "the"], ["dio", "gave"], ["a", "to"], ["luz.La", "light-her"], ["vieron", "saw"], ["las", "the"], ["doncellasy", "and"], ["la", "the"], ["llamaron", "called"], ["bienaventurada;las", "happy-them"], ["reinas", "queens"], ["y", "and"], ["las", "the"], ["concubinas,", "concubines,"], ["y", "and"], ["la", "the"], ["alabaron.", "praiseed."]]},
  {num:10,words:[["¿Quién", "who"], ["es", "is"], ["esta", "this"], ["que", "that"], ["se", "[refl.]"], ["muestra", "and"], ["como", "as"], ["el", "the"], ["alba,hermosa", "fair"], ["como", "as"], ["la", "the"], ["luna,esclarecida", "clear"], ["como", "as"], ["el", "the"], ["sol,imponente", "sun,"], ["como", "as"], ["un", "a"], ["ejército", "army"], ["con", "with"], ["sus", "his/her"], ["banderas?", "standards?"]]},
  {num:11,words:[["Al", "to-the"], ["huerto", "garden"], ["de", "of"], ["los", "the"], ["nogales", "garden"], ["descendía", "descending"], ["ver", "see"], ["los", "the"], ["frutos", "fruits"], ["del", "of-the"], ["valle,a", "the"], ["ver", "see"], ["si", "if"], ["brotaban", "were-theing"], ["las", "the"], ["videsy", "vine"], ["si", "if"], ["florecían", "and"], ["los", "the"], ["granados.", "budded."]]},
  {num:12,words:[["Antes", "before"], ["de", "of"], ["darme", "the"], ["cuenta,mi", "aware,"], ["alma", "soul"], ["me", "me"], ["pusoentre", "me"], ["los", "the"], ["carros", "chariots"], ["de", "of"], ["Aminadab.", "amminadab."]]},
  {num:13,words:[["Vuelve,", "return,"], ["vuelve,", "return,"], ["oh", "oh"], ["sulamita;vuelve,", "return,"], ["vuelve,", "return,"], ["y", "and"], ["te", "thee"], ["miraremos.¿Qué", "thee."], ["veréis", "see"], ["en", "in"], ["la", "the"], ["sulamita,como", "the"], ["en", "in"], ["la", "the"], ["danza", "were"], ["de", "of"], ["dos", "two"], ["campamentos?", "camps?"]]},
];
renderVerseSet(v6, 'sng-ch6-verses');

var v7 = [
  {num:1,words:[["¡Cuán", "how"], ["hermosos", "beautiful"], ["son", "are"], ["tus", "thy"], ["pies", "feet"], ["en", "in"], ["las", "the"], ["sandalias,oh", "princes"], ["hija", "daughter"], ["de", "of"], ["príncipe!Los", "prince-them"], ["contornos", "of"], ["de", "of"], ["tus", "thy"], ["muslos", "thighs"], ["son", "are"], ["como", "as"], ["joyas,obra", "of"], ["de", "of"], ["mano", "hand"], ["de", "of"], ["excelente", "excellent"], ["artífice.", "in."]]},
  {num:2,words:[["Tu", "thy"], ["ombligo,", "navel,"], ["como", "as"], ["una", "a"], ["copa", "cup"], ["redondaa", "goblet,"], ["la", "the"], ["que", "that"], ["no", "not"], ["le", "him/her"], ["falta", "want"], ["vino", "wine"], ["mezclado;tu", "like"], ["vientre,", "belly,"], ["como", "as"], ["montón", "heap"], ["de", "of"], ["trigorodeado", "about"], ["de", "of"], ["lirios.", "lilies."]]},
  {num:3,words:[["Tus", "thy"], ["dos", "two"], ["pechos,", "breasts,"], ["como", "as"], ["dos", "two"], ["críasgemelas", "roes"], ["de", "of"], ["gacela.", "the."]]},
  {num:4,words:[["Tu", "thy"], ["cuello,", "neck,"], ["como", "as"], ["torre", "tower"], ["de", "of"], ["marfil;tus", "of"], ["ojos,", "eyes,"], ["como", "as"], ["los", "the"], ["estanques", "the"], ["de", "of"], ["Hesbónjunto", "heshbon,"], ["a", "to"], ["la", "the"], ["puerta", "gate"], ["de", "of"], ["Bat-rabim;tu", "thy"], ["nariz,", "nose,"], ["como", "as"], ["la", "the"], ["torre", "tower"], ["del", "of-the"], ["Líbano,que", "lebanon"], ["mira", "look"], ["hacia", "toward"], ["Damasco.", "damascus."]]},
  {num:5,words:[["Tu", "thy"], ["cabeza", "head"], ["en", "in"], ["ti,", "thee,"], ["como", "as"], ["el", "the"], ["Carmelo;y", "and"], ["el", "the"], ["cabello", "hair"], ["de", "of"], ["tu", "thy"], ["cabeza,", "head,"], ["como", "as"], ["púrpura;el", "purple;"], ["rey", "king"], ["está", "is"], ["cautivo", "captive"], ["en", "in"], ["tus", "thy"], ["trenzas.", "galleries."]]},
  {num:6,words:[["¡Qué", "what"], ["hermosa", "beautiful"], ["y", "and"], ["cuán", "how"], ["encantadora", "thou,"], ["eres,oh", "o"], ["amor", "love"], ["deleitoso!", "delights!"]]},
  {num:7,words:[["Y", "and"], ["tu", "thy"], ["estatura", "stature"], ["es", "is"], ["semejante", "like"], ["a", "to"], ["la", "the"], ["palmera,y", "and"], ["tus", "thy"], ["pechos,", "breasts,"], ["a", "to"], ["sus", "his/her"], ["racimos.", "and."]]},
  {num:8,words:[["Yo", "I"], ["dije:", "I-said:"], ["Subiré", "go"], ["a", "to"], ["la", "the"], ["palmera,asiré", "palm"], ["sus", "his/her"], ["ramas.Y", "will"], ["tus", "thy"], ["pechos", "breasts"], ["serán", "shall-be"], ["ahora", "now"], ["como", "as"], ["racimos", "and"], ["de", "of"], ["vid,y", "be"], ["la", "the"], ["fragancia", "of"], ["de", "of"], ["tu", "thy"], ["aliento", "breath"], ["como", "as"], ["de", "of"], ["manzanas;", "like;"]]},
  {num:9,words:[["y", "and"], ["tu", "thy"], ["paladar,", "mouth,"], ["como", "as"], ["el", "the"], ["buen", "cheer"], ["vinoque", "best"], ["entra", "enter"], ["en", "in"], ["mi", "my"], ["amadoy", "goeth"], ["pasa", "passeth"], ["suavemente", "sweetly,"], ["por", "by/for"], ["los", "the"], ["labios", "lips"], ["de", "of"], ["los", "the"], ["que", "that"], ["duermen.", "speak."]]},
  {num:10,words:[["Yo", "I"], ["soy", "I-am"], ["de", "of"], ["mi", "my"], ["amado,y", "and"], ["su", "his/her"], ["deseo", "desire"], ["tiende", "is"], ["hacia", "toward"], ["mí.", "me."]]},
  {num:11,words:[["Ven,", "come/see,"], ["oh", "oh"], ["amado", "beloved"], ["mío,", "mine,"], ["salgamos", "forth"], ["al", "to-the"], ["campo,moremos", "let"], ["en", "in"], ["las", "the"], ["aldeas.", "villages."]]},
  {num:12,words:[["Levantémonos", "let"], ["de", "of"], ["mañana", "morning"], ["y", "and"], ["vayamos", "go"], ["a", "to"], ["las", "the"], ["viñas;veamos", "us"], ["si", "if"], ["brotan", "the"], ["las", "the"], ["vides,", "and,"], ["si", "if"], ["ya", "already"], ["están", "are"], ["en", "in"], ["cierne,si", "and"], ["han", "have"], ["florecido", "bud"], ["los", "the"], ["granados;allí", "will"], ["te", "thee"], ["daré", "I-shall-give"], ["mis", "my"], ["amores.", "loves."]]},
  {num:13,words:[["Las", "the"], ["mandrágoras", "mandrakes"], ["exhalan", "a"], ["su", "his/her"], ["fragancia,y", "and"], ["a", "to"], ["nuestras", "provisions"], ["puertashay", "are"], ["toda", "all"], ["clase", "class/kind"], ["de", "of"], ["frutas", "thes"], ["deliciosas,frescas", "new"], ["y", "and"], ["secas,que", "which"], ["para", "for"], ["ti,", "thee,"], ["oh", "oh"], ["amado", "beloved"], ["mío,", "mine,"], ["he", "I-have"], ["guardado.", "kept."]]},
];
renderVerseSet(v7, 'sng-ch7-verses');

var v8 = [
  {num:1,words:[["¡Ah,", "ah,"], ["si", "if"], ["fueras", "outside/weres"], ["tú", "thou"], ["como", "as"], ["mi", "my"], ["hermanocriado", "that"], ["a", "to"], ["los", "the"], ["pechos", "breasts"], ["de", "of"], ["mi", "my"], ["madre!Así", "when"], ["cuando", "when"], ["te", "thee"], ["hallara", "find"], ["yo", "I"], ["fuera", "outside/were"], ["de", "of"], ["casa,", "house,"], ["te", "thee"], ["besaría,y", "i"], ["no", "not"], ["me", "me"], ["menospreciarían.", "despised."]]},
  {num:2,words:[["Yo", "I"], ["te", "thee"], ["llevaría", "would-carry"], ["y", "and"], ["te", "thee"], ["haría", "would"], ["entrar", "enter"], ["en", "in"], ["casa", "house"], ["de", "of"], ["mi", "my"], ["madre;tú", "me:"], ["me", "me"], ["enseñarías.Yo", "would"], ["te", "thee"], ["daría", "sware"], ["a", "to"], ["beber", "drink"], ["vinoaromatizado", "wine"], ["del", "of-the"], ["zumo", "the"], ["de", "of"], ["mis", "my"], ["granadas.", "pomegranates."]]},
  {num:3,words:[["Su", "his/her"], ["izquierda", "left"], ["esté", "be"], ["debajo", "beneath"], ["de", "of"], ["mi", "my"], ["cabeza,y", "and"], ["su", "his/her"], ["derecha", "right"], ["me", "me"], ["abrace.", "me."]]},
  {num:4,words:[["Os", "you"], ["ruego,", "I-pray/beseech,"], ["oh", "oh"], ["hijas", "daughters"], ["de", "of"], ["Jerusalén,que", "that"], ["no", "not"], ["despertéis", "not"], ["ni", "nor"], ["desveléis", "nor"], ["al", "to-the"], ["amado,hasta", "love,"], ["que", "that"], ["quiera.", "whosoever."]]},
  {num:5,words:[["¿Quién", "who"], ["es", "is"], ["esta", "this"], ["que", "that"], ["sube", "goeth"], ["del", "of-the"], ["desierto,recostada", "wilderness,"], ["sobre", "upon"], ["su", "his/her"], ["amado?Debajo", "beloved?"], ["de", "of"], ["un", "a"], ["manzano", "up"], ["te", "thee"], ["desperté;allí", "the"], ["tuvo", "had"], ["tu", "thy"], ["madre", "mother"], ["dolores,allí", "mother"], ["tuvo", "had"], ["dolores", "sorrows"], ["la", "the"], ["que", "that"], ["te", "thee"], ["dio", "gave"], ["a", "to"], ["luz.", "light."]]},
  {num:6,words:[["Ponme", "prophesy-me"], ["como", "as"], ["un", "a"], ["sello", "seal"], ["sobre", "upon"], ["tu", "thy"], ["corazón,como", "as"], ["una", "a"], ["marca", "mark"], ["sobre", "upon"], ["tu", "thy"], ["brazo,porque", "for"], ["fuerte", "strong"], ["como", "as"], ["la", "the"], ["muerte", "death"], ["es", "is"], ["el", "the"], ["amor;duros", "as"], ["como", "as"], ["el", "the"], ["Seol", "grave"], ["son", "are"], ["los", "the"], ["celos;sus", "of"], ["brasas,", "coals,"], ["brasas", "coals"], ["de", "of"], ["fuego,poderosa", "most"], ["llama.", "calls/flame."]]},
  {num:7,words:[["Las", "the"], ["muchas", "many"], ["aguas", "waters"], ["no", "not"], ["podrán", "be"], ["apagar", "can"], ["el", "the"], ["amorni", "floods"], ["lo", "it/him"], ["ahogarán", "it:"], ["los", "the"], ["ríos.Si", "a"], ["dieseel", "man"], ["hombre", "man"], ["todos", "all"], ["los", "the"], ["bienes", "goods"], ["de", "of"], ["su", "his/her"], ["casaa", "house"], ["cambio", "change"], ["del", "of-the"], ["amor,de", "would"], ["cierto", "certain"], ["lo", "it/him"], ["menospreciarían.", "contemned."]]},
  {num:8,words:[["Tenemos", "we-have"], ["una", "a"], ["pequeña", "small"], ["hermanaque", "and"], ["no", "not"], ["tiene", "has"], ["pechos;¿qué", "what"], ["haremos", "we"], ["por", "by/for"], ["nuestra", "our"], ["hermanael", "sister"], ["día", "day"], ["en", "in"], ["que", "that"], ["la", "the"], ["pidan?", "spoken?"]]},
  {num:9,words:[["Si", "if"], ["ella", "she"], ["es", "is"], ["muro,edificaremos", "we"], ["sobre", "upon"], ["ella", "she"], ["una", "a"], ["torrecilla", "palace"], ["de", "of"], ["plata;y", "and"], ["si", "if"], ["es", "is"], ["puerta,la", "gate-her"], ["enclaustraremos", "we"], ["con", "with"], ["tablas", "boards"], ["de", "of"], ["cedro.", "cedar."]]},
  {num:10,words:[["Yo", "I"], ["soy", "I-am"], ["muro,", "wall,"], ["y", "and"], ["mis", "my"], ["pechos", "breasts"], ["como", "as"], ["torres;entonces", "then"], ["fui", "am"], ["ante", "before"], ["sus", "his/her"], ["ojoscomo", "eyes"], ["la", "the"], ["que", "that"], ["halla", "findeth"], ["paz.", "peace."]]},
  {num:11,words:[["Salomón", "Solomon"], ["tuvo", "had"], ["una", "a"], ["viña", "vineyard"], ["en", "in"], ["Baal-hamón,la", "he"], ["cual", "which"], ["encomendó", "the"], ["a", "to"], ["cuidadores,cada", "unto"], ["uno", "one"], ["de", "of"], ["los", "the"], ["cuales", "which"], ["debía", "ought"], ["traermil", "thereof"], ["monedas", "to"], ["de", "of"], ["plata", "silver"], ["por", "by/for"], ["su", "his/her"], ["fruto.", "fruit."]]},
  {num:12,words:[["Mi", "my"], ["viña,", "vineyard,"], ["que", "that"], ["es", "is"], ["mía,", "mother,"], ["está", "is"], ["delante", "before"], ["de", "of"], ["mí;las", "me-them"], ["mil", "thousand"], ["serán", "shall-be"], ["tuyas,", "thines,"], ["oh", "oh"], ["Salomón,y", "and"], ["doscientas", "hundred"], ["para", "for"], ["los", "the"], ["que", "that"], ["cuidan", "thereof"], ["su", "his/her"], ["fruto.", "fruit."]]},
  {num:13,words:[["Tú,", "thou,"], ["que", "that"], ["moras", "dwellest"], ["en", "in"], ["los", "the"], ["huertos,los", "gardens-them"], ["compañeros", "companions"], ["escuchan", "hearken"], ["tu", "thy"], ["voz.¡Házmela", "to"], ["oír!", "hear!"]]},
  {num:14,words:[["Apresúrate,", "to-thee,"], ["amado", "beloved"], ["mío,y", "beloved,"], ["sé", "I-know"], ["semejante", "like"], ["a", "to"], ["la", "the"], ["gacela,", "the,"], ["o", "or"], ["al", "to-the"], ["cervatillo,sobre", "a"], ["los", "the"], ["montes", "mountains"], ["de", "of"], ["los", "the"], ["aromas.", "spices."]]},
];
renderVerseSet(v8, 'sng-ch8-verses');

})();
