(function() {
var v1 = [
  {num:1,words:[["Pablo,", "Paul,"], ["siervo", "servant"], ["de", "of"], ["Dios", "God"], ["y", "and"], ["apóstol", "apostle"], ["de", "of"], ["Jesucristo,", "Jesus-Christ,"], ["según", "according-to"], ["la", "the"], ["fe", "faith"], ["de", "of"], ["los", "the"], ["escogidos", "elect"], ["de", "of"], ["Dios,", "God,"], ["y", "and"], ["el", "the"], ["pleno", "in"], ["conocimiento", "knowledge"], ["de", "of"], ["la", "the"], ["verdad", "truth"], ["que", "that"], ["es", "is"], ["según", "according-to"], ["la", "the"], ["piedad,", "godliness,"]]},
  {num:2,words:[["en", "in"], ["la", "the"], ["esperanza", "hope"], ["de", "of"], ["la", "the"], ["vida", "life"], ["eterna,", "eternal,"], ["la", "the"], ["cual", "which"], ["Dios,", "God,"], ["que", "that"], ["no", "not"], ["miente,", "lie,"], ["prometió", "promised"], ["desde", "from"], ["antes", "before"], ["del", "of-the"], ["principio", "beginning"], ["de", "of"], ["los", "the"], ["tiempos,", "times,"]]},
  {num:3,words:[["y", "and"], ["a", "to"], ["su", "his/her"], ["debido", "due"], ["tiempo", "time"], ["manifestó", "did"], ["su", "his/her"], ["palabra", "word"], ["por", "by/for"], ["medio", "midst"], ["de", "of"], ["la", "the"], ["predicación,", "preaching,"], ["que", "that"], ["me", "me"], ["fue", "was/went"], ["encomendada", "committed"], ["por", "by/for"], ["mandamiento", "commandment"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Salvador,", "savior,"]]},
  {num:4,words:[["a", "to"], ["Tito,", "titus,"], ["verdadero", "true"], ["hijo", "son"], ["en", "in"], ["la", "the"], ["común", "common"], ["fe:", "faith:"], ["Gracia,", "grace,"], ["misericordia", "mercy"], ["y", "and"], ["paz", "peace"], ["de", "of"], ["parte", "part"], ["de", "of"], ["Dios", "God"], ["el", "the"], ["Padre,", "father,"], ["y", "and"], ["del", "of-the"], ["Señor", "Lord"], ["Jesucristo", "Jesus-Christ"], ["nuestro", "our"], ["Salvador.", "savior."]]},
  {num:5,words:[["Por", "by/for"], ["esta", "this"], ["causa", "cause/sake"], ["te", "thee"], ["dejé", "i"], ["en", "in"], ["Creta,", "that,"], ["para", "for"], ["que", "that"], ["corrigieses", "set"], ["lo", "it/him"], ["que", "that"], ["faltaba,", "things,"], ["y", "and"], ["pusieses", "wanting,"], ["ancianos", "elders"], ["en", "in"], ["cada", "each"], ["ciudad,", "city,"], ["así", "thus"], ["como", "as"], ["yo", "I"], ["te", "thee"], ["mandé:", "commanded:"]]},
  {num:6,words:[["el", "the"], ["que", "that"], ["sea", "let-be/be"], ["irreprensible,", "be,"], ["marido", "husband"], ["de", "of"], ["una", "a"], ["sola", "alone"], ["mujer,", "woman,"], ["y", "and"], ["que", "that"], ["tenga", "may-have"], ["hijos", "children"], ["creyentes", "them"], ["que", "that"], ["no", "not"], ["estén", "be"], ["acusados", "accuseds"], ["de", "of"], ["disolución", "riot"], ["ni", "nor"], ["de", "of"], ["rebeldía.", "unruly."]]},
  {num:7,words:[["Porque", "because"], ["es", "is"], ["necesario", "needful"], ["que", "that"], ["el", "the"], ["obispo", "bishop"], ["sea", "let-be/be"], ["irreprensible", "the"], ["como", "as"], ["administrador", "of"], ["de", "of"], ["Dios;", "God;"], ["no", "not"], ["soberbio,", "proud,"], ["no", "not"], ["iracundo,", "angry,"], ["no", "not"], ["dado", "given"], ["al", "to-the"], ["vino,", "wine,"], ["no", "not"], ["pendenciero,", "striker,"], ["no", "not"], ["codicioso", "given"], ["de", "of"], ["ganancias", "of"], ["deshonestas,", "lucre,"]]},
  {num:8,words:[["sino", "but"], ["hospitalario,", "a,"], ["amador", "lover"], ["de", "of"], ["lo", "it/him"], ["bueno,", "good,"], ["prudente,", "prudent,"], ["justo,", "just/righteous,"], ["santo,", "holy,"], ["dueño", "owner"], ["de", "of"], ["sí", "yea"], ["mismo,", "same,"]]},
  {num:9,words:[["retenedor", "holding"], ["de", "of"], ["la", "the"], ["palabra", "word"], ["fiel", "faithful"], ["que", "that"], ["es", "is"], ["conforme", "according-to"], ["a", "to"], ["la", "the"], ["enseñanza,", "of,"], ["para", "for"], ["que", "that"], ["también", "also"], ["pueda", "whereby"], ["exhortar", "exhort"], ["con", "with"], ["sana", "sound"], ["doctrina", "doctrine"], ["y", "and"], ["convencer", "of"], ["a", "to"], ["los", "the"], ["que", "that"], ["contradicen.", "gainsayers."]]},
  {num:10,words:[["Porque", "because"], ["hay", "there-is"], ["aún", "still/yet"], ["muchos", "many"], ["rebeldes,", "rebellious,"], ["habladores", "unruly"], ["de", "of"], ["vanidades", "vanities"], ["y", "and"], ["engañadores,", "and,"], ["mayormente", "of"], ["los", "the"], ["que", "that"], ["son", "are"], ["de", "of"], ["la", "the"], ["circuncisión,", "circumcision,"]]},
  {num:11,words:[["a", "to"], ["los", "the"], ["que", "that"], ["es", "is"], ["preciso", "needs"], ["tapar", "who"], ["la", "the"], ["boca,", "mouth,"], ["porque", "because"], ["trastornan", "houses,"], ["casas", "houses"], ["enteras,", "wholes,"], ["enseñando", "teaching"], ["lo", "it/him"], ["que", "that"], ["no", "not"], ["es", "is"], ["debido,", "due,"], ["por", "by/for"], ["ganancia", "gain"], ["deshonesta.", "sake."]]},
  {num:12,words:[["Dijo", "said"], ["uno", "one"], ["de", "of"], ["ellos,", "they,"], ["su", "his/her"], ["propio", "own"], ["profeta:", "prophet:"], ["Los", "the"], ["cretenses", "the"], ["son", "are"], ["siempre", "always"], ["mentirosos,", "and,"], ["malas", "evil"], ["bestias,", "beasts,"], ["glotones", "slow"], ["perezosos.", "slothfuls."]]},
  {num:13,words:[["Este", "this"], ["testimonio", "testimony"], ["es", "is"], ["verdadero;", "true;"], ["por", "by/for"], ["tanto,", "therefore,"], ["repréndelos", "of-them"], ["duramente", "stiffneckedly"], ["para", "for"], ["que", "that"], ["sean", "let-be"], ["sanos", "whole"], ["en", "in"], ["la", "the"], ["fe,", "faith,"]]},
  {num:14,words:[["no", "not"], ["atendiendo", "giving"], ["a", "to"], ["fábulas", "to"], ["judaicas", "jewish"], ["ni", "nor"], ["a", "to"], ["mandamientos", "commandments"], ["de", "of"], ["hombres", "men"], ["que", "that"], ["se", "[refl.]"], ["apartan", "turn"], ["de", "of"], ["la", "the"], ["verdad.", "truth."]]},
  {num:15,words:[["Todas", "all"], ["las", "the"], ["cosas", "things"], ["son", "are"], ["puras", "pure"], ["para", "for"], ["los", "the"], ["puros;", "pure;"], ["pero", "but"], ["para", "for"], ["los", "the"], ["corrompidos", "corrupteds"], ["e", "and"], ["incrédulos", "unbelievers"], ["nada", "nothing"], ["es", "is"], ["puro,", "pure,"], ["pues", "for"], ["hasta", "until"], ["su", "his/her"], ["mente", "mind"], ["y", "and"], ["su", "his/her"], ["conciencia", "conscience"], ["están", "are"], ["corrompidas.", "defiled."]]},
  {num:16,words:[["Profesan", "they"], ["conocer", "know"], ["a", "to"], ["Dios,", "God,"], ["pero", "but"], ["con", "with"], ["los", "the"], ["hechos", "proceedings"], ["lo", "it/him"], ["niegan,", "deny,"], ["siendo", "being"], ["abominables", "abominable"], ["y", "and"], ["rebeldes,", "rebellious,"], ["reprobados", "disobedient,"], ["en", "in"], ["cuanto", "as-much-as"], ["a", "to"], ["toda", "all"], ["buena", "good"], ["obra.", "work."]]},
];
renderVerseSet(v1, 'tit-ch1-verses');

var v2 = [
  {num:1,words:[["Pero", "but"], ["tú,", "thou,"], ["habla", "speaks"], ["lo", "it/him"], ["que", "that"], ["está", "is"], ["de", "of"], ["acuerdo", "agreement"], ["con", "with"], ["la", "the"], ["sana", "sound"], ["doctrina.", "doctrine."]]},
  {num:2,words:[["Que", "that"], ["los", "the"], ["ancianos", "elders"], ["sean", "let-be"], ["sobrios,", "be,"], ["serios,", "men,"], ["prudentes,", "wise,"], ["sanos", "whole"], ["en", "in"], ["la", "the"], ["fe,", "faith,"], ["en", "in"], ["el", "the"], ["amor,", "love,"], ["en", "in"], ["la", "the"], ["paciencia.", "patience."]]},
  {num:3,words:[["Las", "the"], ["ancianas,", "aged,"], ["asimismo,", "likewise,"], ["sean", "let-be"], ["reverentes", "they"], ["en", "in"], ["su", "his/her"], ["porte;", "by/for-thee;"], ["no", "not"], ["calumniadoras,", "holiness,"], ["no", "not"], ["dadas", "given"], ["a", "to"], ["mucho", "much"], ["vino,", "wine,"], ["maestras", "wine,"], ["de", "of"], ["lo", "it/him"], ["bueno;", "good;"]]},
  {num:4,words:[["que", "that"], ["enseñen", "teach"], ["a", "to"], ["las", "the"], ["mujeres", "women"], ["jóvenes", "young-men"], ["a", "to"], ["amar", "love"], ["a", "to"], ["sus", "his/her"], ["maridos", "husbands"], ["y", "and"], ["a", "to"], ["amar", "love"], ["a", "to"], ["sus", "his/her"], ["hijos,", "children,"]]},
  {num:5,words:[["a", "to"], ["ser", "be"], ["prudentes,", "wise,"], ["castas,", "chaste,"], ["cuidadosas", "keepers"], ["de", "of"], ["su", "his/her"], ["casa,", "house,"], ["buenas,", "good,"], ["sujetas", "unto"], ["a", "to"], ["sus", "his/her"], ["maridos,", "husbands,"], ["para", "for"], ["que", "that"], ["la", "the"], ["palabra", "word"], ["de", "of"], ["Dios", "God"], ["no", "not"], ["sea", "let-be/be"], ["blasfemada.", "blasphemed."]]},
  {num:6,words:[["Exhorta,", "young,"], ["asimismo,", "likewise,"], ["a", "to"], ["los", "the"], ["jóvenes", "young-men"], ["a", "to"], ["ser", "be"], ["sensatos;", "minded;"]]},
  {num:7,words:[["preséntate", "in"], ["en", "in"], ["todo", "all"], ["como", "as"], ["ejemplo", "example"], ["de", "of"], ["buenas", "good"], ["obras;", "works;"], ["en", "in"], ["la", "the"], ["enseñanza,", "of,"], ["mostrando", "showing"], ["integridad,", "integrity,"], ["seriedad,", "sincerity,"]]},
  {num:8,words:[["palabra", "word"], ["sana", "sound"], ["e", "and"], ["irreprensible,", "be,"], ["de", "of"], ["modo", "manner/way"], ["que", "that"], ["el", "the"], ["adversario", "adversary"], ["se", "[refl.]"], ["avergüence", "part"], ["y", "and"], ["no", "not"], ["tenga", "may-have"], ["nada", "nothing"], ["malo", "evil"], ["que", "that"], ["decir", "say"], ["de", "of"], ["vosotros.", "you."]]},
  {num:9,words:[["Exhorta", "exhort"], ["a", "to"], ["los", "the"], ["esclavos", "bond"], ["a", "to"], ["que", "that"], ["estén", "be"], ["sujetos", "subject"], ["a", "to"], ["sus", "his/her"], ["amos,", "masters,"], ["que", "that"], ["les", "them"], ["agraden", "may-please"], ["en", "in"], ["todo", "all"], ["y", "and"], ["que", "that"], ["no", "not"], ["sean", "let-be"], ["respondones;", "again;"]]},
  {num:10,words:[["no", "not"], ["defraudando,", "purloining,"], ["sino", "but"], ["mostrándose", "shewing"], ["fieles", "faithful"], ["en", "in"], ["todo,", "all,"], ["para", "for"], ["que", "that"], ["adornen", "adorn"], ["en", "in"], ["todo", "all"], ["la", "the"], ["doctrina", "doctrine"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Salvador.", "savior."]]},
  {num:11,words:[["Porque", "because"], ["la", "the"], ["gracia", "grace"], ["de", "of"], ["Dios", "God"], ["que", "that"], ["trae", "bringeth"], ["salvación", "salvation"], ["a", "to"], ["todos", "all"], ["los", "the"], ["hombres", "men"], ["se", "[refl.]"], ["ha", "has"], ["manifestado,", "manifested,"]]},
  {num:12,words:[["enseñándonos", "teaching-us"], ["que,", "that,"], ["rechazando", "that,"], ["la", "the"], ["impiedad", "of"], ["y", "and"], ["los", "the"], ["deseos", "desires"], ["mundanos,", "world-us,"], ["vivamos", "live"], ["en", "in"], ["este", "this"], ["mundo", "world"], ["sobria,", "in,"], ["justa", "just"], ["y", "and"], ["piadosamente,", "world,"]]},
  {num:13,words:[["aguardando", "looking"], ["la", "the"], ["esperanza", "hope"], ["bienaventurada", "happy"], ["y", "and"], ["la", "the"], ["manifestación", "manifestation"], ["gloriosa", "glorious"], ["de", "of"], ["nuestro", "our"], ["gran", "great"], ["Dios", "God"], ["y", "and"], ["Salvador", "savior"], ["Jesucristo,", "Jesus-Christ,"]]},
  {num:14,words:[["quien", "who"], ["se", "[refl.]"], ["dio", "gave"], ["a", "to"], ["sí", "yea"], ["mismo", "same"], ["por", "by/for"], ["nosotros", "we"], ["para", "for"], ["redimirnos", "redeem-us"], ["de", "of"], ["toda", "all"], ["iniquidad,", "iniquity,"], ["y", "and"], ["purificar", "purify"], ["para", "for"], ["sí", "yea"], ["un", "a"], ["pueblo", "people"], ["propio,", "own,"], ["celoso", "jealous"], ["de", "of"], ["buenas", "good"], ["obras.", "works."]]},
  {num:15,words:[["Esto", "this"], ["habla", "speaks"], ["y", "and"], ["exhorta,", "exhort,"], ["y", "and"], ["reprende", "of"], ["con", "with"], ["toda", "all"], ["autoridad.", "authority."], ["Nadie", "no-one"], ["te", "thee"], ["desprecie.", "thee."]]},
];
renderVerseSet(v2, 'tit-ch2-verses');

var v3 = [
  {num:1,words:[["Recuérdales", "remember-them"], ["que", "that"], ["se", "[refl.]"], ["sujeten", "mind"], ["a", "to"], ["los", "the"], ["gobernantes", "rulers"], ["y", "and"], ["a", "to"], ["las", "the"], ["autoridades,", "unto,"], ["que", "that"], ["obedezcan,", "magistrates,"], ["que", "that"], ["estén", "be"], ["dispuestos", "willing"], ["para", "for"], ["toda", "all"], ["buena", "good"], ["obra.", "work."]]},
  {num:2,words:[["Que", "that"], ["a", "to"], ["nadie", "no-one"], ["difamen,", "of,"], ["que", "that"], ["no", "not"], ["sean", "let-be"], ["pendencieros,", "be,"], ["sino", "but"], ["amables,", "brawlers,"], ["mostrando", "showing"], ["toda", "all"], ["mansedumbre", "meekness"], ["para", "for"], ["con", "with"], ["todos", "all"], ["los", "the"], ["hombres.", "men."]]},
  {num:3,words:[["Porque", "because"], ["nosotros", "we"], ["también", "also"], ["éramos", "we"], ["necios", "fools"], ["en", "in"], ["otro", "other"], ["tiempo,", "time,"], ["rebeldes,", "rebellious,"], ["extraviados,", "disobedient,"], ["esclavos", "bond"], ["de", "of"], ["concupiscencias", "lusts"], ["y", "and"], ["deleites", "and"], ["diversos,", "divers,"], ["viviendo", "liveing"], ["en", "in"], ["malicia", "malice"], ["y", "and"], ["en", "in"], ["envidia,", "envy,"], ["aborrecibles", "envy,"], ["y", "and"], ["aborreciéndonos", "hateful,"], ["los", "the"], ["unos", "some"], ["a", "to"], ["los", "the"], ["otros.", "others."]]},
  {num:4,words:[["Pero", "but"], ["cuando", "when"], ["se", "[refl.]"], ["manifestó", "did"], ["la", "the"], ["bondad", "goodness"], ["de", "of"], ["Dios", "God"], ["nuestro", "our"], ["Salvador,", "savior,"], ["y", "and"], ["su", "his/her"], ["amor", "love"], ["para", "for"], ["con", "with"], ["los", "the"], ["hombres,", "men,"]]},
  {num:5,words:[["nos", "us"], ["salvó,", "saved,"], ["no", "not"], ["por", "by/for"], ["obras", "works"], ["de", "of"], ["justicia", "justice/righteousness"], ["que", "that"], ["nosotros", "we"], ["hubiésemos", "our"], ["hecho,", "done/made,"], ["sino", "but"], ["por", "by/for"], ["su", "his/her"], ["misericordia,", "mercy,"], ["por", "by/for"], ["el", "the"], ["lavamiento", "by"], ["de", "of"], ["la", "the"], ["regeneración", "of"], ["y", "and"], ["la", "the"], ["renovación", "renewing"], ["por", "by/for"], ["el", "the"], ["Espíritu", "Spirit"], ["Santo,", "holy,"]]},
  {num:6,words:[["el", "the"], ["que", "that"], ["derramó", "vial"], ["en", "in"], ["nosotros", "we"], ["abundantemente", "abundantly"], ["por", "by/for"], ["Jesucristo", "Jesus-Christ"], ["nuestro", "our"], ["Salvador,", "savior,"]]},
  {num:7,words:[["para", "for"], ["que,", "that,"], ["justificados", "justified"], ["por", "by/for"], ["su", "his/her"], ["gracia,", "grace,"], ["fuésemos", "should"], ["hechos", "proceedings"], ["herederos", "heirs"], ["según", "according-to"], ["la", "the"], ["esperanza", "hope"], ["de", "of"], ["la", "the"], ["vida", "life"], ["eterna.", "eternal."]]},
  {num:8,words:[["Palabra", "word"], ["fiel", "faithful"], ["es", "is"], ["esta,", "this,"], ["y", "and"], ["en", "in"], ["estas", "these"], ["cosas", "things"], ["quiero", "would"], ["que", "that"], ["insistas", "thou"], ["con", "with"], ["firmeza,", "with,"], ["para", "for"], ["que", "that"], ["los", "the"], ["que", "that"], ["creen", "believe"], ["en", "in"], ["Dios", "God"], ["procuren", "may-seek"], ["ocuparse", "to-[refl.]"], ["en", "in"], ["buenas", "good"], ["obras.", "works."], ["Estas", "these"], ["cosas", "things"], ["son", "are"], ["buenas", "good"], ["y", "and"], ["útiles", "and"], ["a", "to"], ["los", "the"], ["hombres.", "men."]]},
  {num:9,words:[["Pero", "but"], ["evita", "little-Eve"], ["las", "the"], ["cuestiones", "foolish"], ["necias,", "questions,"], ["y", "and"], ["las", "the"], ["genealogías,", "by,"], ["y", "and"], ["las", "the"], ["contenciones", "contentions"], ["y", "and"], ["los", "the"], ["debates", "about"], ["acerca", "about"], ["de", "of"], ["la", "the"], ["ley,", "law,"], ["porque", "because"], ["son", "are"], ["sin", "without"], ["provecho", "profit"], ["y", "and"], ["vanos.", "vain."]]},
  {num:10,words:[["Al", "to-the"], ["hombre", "man"], ["que", "that"], ["cause", "is"], ["divisiones,", "the,"], ["después", "after/afterward"], ["de", "of"], ["una", "a"], ["y", "and"], ["otra", "other"], ["amonestación,", "in,"], ["recházale,", "reject,"]]},
  {num:11,words:[["sabiendo", "knowing"], ["que", "that"], ["el", "the"], ["tal", "such"], ["se", "[refl.]"], ["ha", "has"], ["descarriado,", "have,"], ["y", "and"], ["peca,", "sinneth,"], ["siendo", "being"], ["condenado", "damned"], ["por", "by/for"], ["su", "his/her"], ["propio", "own"], ["juicio.", "judgment."]]},
  {num:12,words:[["Cuando", "when"], ["te", "thee"], ["envíe", "send"], ["a", "to"], ["Artemas,", "unto,"], ["o", "or"], ["a", "to"], ["Tíquico,", "tychicus,"], ["procura", "seeketh"], ["venir", "come"], ["a", "to"], ["mí", "me"], ["a", "to"], ["Nicópolis,", "to,"], ["porque", "because"], ["allí", "there"], ["he", "I-have"], ["determinado", "determined"], ["pasar", "pass"], ["el", "the"], ["invierno.", "winter."]]},
  {num:13,words:[["A", "to"], ["Zenas,", "zenas,"], ["doctor", "the"], ["de", "of"], ["la", "the"], ["ley,", "law,"], ["y", "and"], ["a", "to"], ["Apolos,", "apollos,"], ["encamínalos", "journey"], ["con", "with"], ["diligencia,", "diligence,"], ["procurando", "the"], ["que", "that"], ["nada", "nothing"], ["les", "them"], ["falte.", "be."]]},
  {num:14,words:[["Y", "and"], ["también", "also"], ["aprendan", "ours"], ["los", "the"], ["nuestros", "our"], ["a", "to"], ["ocuparse", "to-[refl.]"], ["en", "in"], ["buenas", "good"], ["obras", "works"], ["para", "for"], ["los", "the"], ["casos", "cases"], ["de", "of"], ["necesidad,", "need,"], ["para", "for"], ["que", "that"], ["no", "not"], ["sean", "let-be"], ["sin", "without"], ["fruto.", "fruit."]]},
  {num:15,words:[["Todos", "all"], ["los", "the"], ["que", "that"], ["están", "are"], ["conmigo", "with-me"], ["te", "thee"], ["saludan.", "salute."], ["Saluda", "thee."], ["a", "to"], ["los", "the"], ["que", "that"], ["nos", "us"], ["aman", "love"], ["en", "in"], ["la", "the"], ["fe.", "faith."], ["La", "the"], ["gracia", "grace"], ["sea", "let-be/be"], ["con", "with"], ["todos", "all"], ["vosotros.", "you."], ["Amén.", "amen."]]},
];
renderVerseSet(v3, 'tit-ch3-verses');

})();
