(function() {
var v1 = [
  {num:1,words:[["La", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["que", "that"], ["vino", "wine"], ["a", "to"], ["Sofonías", "zephaniah"], ["hijo", "son"], ["de", "of"], ["Cusi,", "cushi,"], ["hijo", "son"], ["de", "of"], ["Gedalías,", "gedaliah,"], ["hijo", "son"], ["de", "of"], ["Amarías,", "amariah,"], ["hijo", "son"], ["de", "of"], ["Ezequías,", "Hezekiah,"], ["en", "in"], ["los", "the"], ["días", "days"], ["de", "of"], ["Josías", "josiah"], ["hijo", "son"], ["de", "of"], ["Amón,", "amon,"], ["rey", "king"], ["de", "of"], ["Judá:", "Judah:"]]},
  {num:2,words:[["Destruiré", "destroy"], ["por", "by/for"], ["completo", "utterly"], ["todas", "all"], ["las", "the"], ["cosas", "things"], ["de", "of"], ["sobre", "upon"], ["la", "the"], ["faz", "face"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:3,words:[["Destruiré", "destroy"], ["a", "to"], ["los", "the"], ["hombres", "men"], ["y", "and"], ["las", "the"], ["bestias;", "beasts;"], ["destruiré", "destroy"], ["las", "the"], ["aves", "fowl"], ["del", "of-the"], ["cielo,", "heaven,"], ["y", "and"], ["los", "the"], ["peces", "fish"], ["del", "of-the"], ["mar", "sea"], ["y", "and"], ["las", "the"], ["piedras", "stones"], ["de", "of"], ["tropiezo", "stumblingblock"], ["junto", "together"], ["con", "with"], ["los", "the"], ["malvados;", "wicked;"], ["y", "and"], ["talaré", "cut"], ["a", "to"], ["los", "the"], ["hombres", "men"], ["de", "of"], ["sobre", "upon"], ["la", "the"], ["faz", "face"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
  {num:4,words:[["Y", "and"], ["extenderé", "stretch"], ["mi", "my"], ["mano", "hand"], ["contra", "against"], ["Judá", "Judah"], ["y", "and"], ["contra", "against"], ["todos", "all"], ["los", "the"], ["moradores", "inhabitants"], ["de", "of"], ["Jerusalén;", "Jerusalem;"], ["y", "and"], ["exterminaré", "and"], ["de", "of"], ["este", "this"], ["lugar", "place"], ["los", "the"], ["restos", "remnants"], ["de", "of"], ["Baal,", "baal,"], ["y", "and"], ["el", "the"], ["nombre", "name"], ["de", "of"], ["los", "the"], ["ministros", "ministers"], ["idólatras", "of"], ["junto", "together"], ["con", "with"], ["los", "the"], ["sacerdotes,", "priests,"]]},
  {num:5,words:[["y", "and"], ["a", "to"], ["los", "the"], ["que", "that"], ["sobre", "upon"], ["los", "the"], ["terrados", "thes"], ["se", "[refl.]"], ["postran", "last"], ["ante", "before"], ["el", "the"], ["ejército", "army"], ["del", "of-the"], ["cielo,", "heaven,"], ["y", "and"], ["a", "to"], ["los", "the"], ["que", "that"], ["se", "[refl.]"], ["postran", "last"], ["jurando", "hand"], ["por", "by/for"], ["Jehová", "jehovah"], ["y", "and"], ["jurando", "hand"], ["por", "by/for"], ["Moloc,", "molech,"]]},
  {num:6,words:[["y", "and"], ["a", "to"], ["los", "the"], ["que", "that"], ["se", "[refl.]"], ["apartan", "turn"], ["de", "of"], ["en", "in"], ["pos", "follow"], ["de", "of"], ["Jehová", "jehovah"], ["y", "and"], ["a", "to"], ["los", "the"], ["que", "that"], ["no", "not"], ["buscaron", "sought"], ["a", "to"], ["Jehová", "jehovah"], ["ni", "nor"], ["le", "him/her"], ["consultaron.", "the."]]},
  {num:7,words:[["Calla", "hold"], ["ante", "before"], ["la", "the"], ["presencia", "presence"], ["de", "of"], ["Jehová", "jehovah"], ["el", "the"], ["Señor,", "Lord,"], ["porque", "because"], ["el", "the"], ["día", "day"], ["de", "of"], ["Jehová", "jehovah"], ["está", "is"], ["cercano;", "near;"], ["porque", "because"], ["Jehová", "jehovah"], ["ha", "has"], ["preparado", "prepared"], ["un", "a"], ["sacrificio", "sacrifice"], ["y", "and"], ["ha", "has"], ["consagrado", "consecrated"], ["a", "to"], ["sus", "his/her"], ["convidados.", "were."]]},
  {num:8,words:[["Y", "and"], ["sucederá", "pass"], ["que", "that"], ["en", "in"], ["el", "the"], ["día", "day"], ["del", "of-the"], ["sacrificio", "sacrifice"], ["de", "of"], ["Jehová,", "jehovah,"], ["castigaré", "punish"], ["a", "to"], ["los", "the"], ["príncipes,", "princes,"], ["y", "and"], ["a", "to"], ["los", "the"], ["hijos", "children"], ["del", "of-the"], ["rey", "king"], ["y", "and"], ["a", "to"], ["todos", "all"], ["los", "the"], ["que", "that"], ["llevan", "are"], ["vestido", "clothed"], ["extranjero.", "sojourneth."]]},
  {num:9,words:[["Asimismo,", "likewise,"], ["castigaré", "punish"], ["en", "in"], ["aquel", "that"], ["día", "day"], ["a", "to"], ["todos", "all"], ["los", "the"], ["que", "that"], ["saltan", "all"], ["sobre", "upon"], ["el", "the"], ["umbral,", "threshold,"], ["los", "the"], ["que", "that"], ["llenan", "fill"], ["de", "of"], ["violencia", "violence"], ["y", "and"], ["de", "of"], ["engaño", "guile"], ["las", "the"], ["casas", "houses"], ["de", "of"], ["sus", "his/her"], ["señores.", "shechem."]]},
  {num:10,words:[["Y", "and"], ["acontecerá", "shall-come-to-pass"], ["en", "in"], ["aquel", "that"], ["día,", "day,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["que", "that"], ["habrá", "there-shall-be"], ["voz", "voice"], ["de", "of"], ["clamor", "cry"], ["desde", "from"], ["la", "the"], ["puerta", "gate"], ["del", "of-the"], ["Pescado,", "fish,"], ["y", "and"], ["aullido", "gate,"], ["desde", "from"], ["el", "the"], ["segundo,", "second,"], ["y", "and"], ["gran", "great"], ["quebranto", "destruction"], ["desde", "from"], ["los", "the"], ["collados.", "hills."]]},
  {num:11,words:[["Aullad,", "howl,"], ["moradores", "inhabitants"], ["de", "of"], ["Mactes,", "of,"], ["porque", "because"], ["todo", "all"], ["el", "the"], ["pueblo", "people"], ["mercader", "merchant"], ["ha", "has"], ["sido", "been"], ["destruido;", "destroyed;"], ["talados", "hewn"], ["han", "have"], ["sido", "been"], ["todos", "all"], ["los", "the"], ["que", "that"], ["traían", "brought"], ["dinero.", "sacks."]]},
  {num:12,words:[["Y", "and"], ["acontecerá", "shall-come-to-pass"], ["en", "in"], ["aquel", "that"], ["día", "day"], ["que", "that"], ["yo", "I"], ["escudriñaré", "time,"], ["a", "to"], ["Jerusalén", "Jerusalem"], ["con", "with"], ["lámpara,", "lamp,"], ["y", "and"], ["castigaré", "punish"], ["a", "to"], ["los", "the"], ["hombres", "men"], ["que", "that"], ["reposan", "rest"], ["tranquilos", "settled"], ["como", "as"], ["el", "the"], ["vino", "wine"], ["asentado,", "say,"], ["los", "the"], ["cuales", "which"], ["dicen", "say"], ["en", "in"], ["su", "his/her"], ["corazón:", "heart:"], ["Jehová", "jehovah"], ["no", "not"], ["hará", "shall-make"], ["bien", "well"], ["ni", "nor"], ["mal.", "evil."]]},
  {num:13,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["serán", "shall-be"], ["saqueados", "become"], ["sus", "his/her"], ["bienes", "goods"], ["y", "and"], ["sus", "his/her"], ["casas", "houses"], ["asoladas;", "desolate;"], ["y", "and"], ["edificarán", "build"], ["casas,", "houses,"], ["mas", "but"], ["no", "not"], ["las", "the"], ["habitarán;", "dwell;"], ["y", "and"], ["plantarán", "shall"], ["viñas,", "vineyards,"], ["mas", "but"], ["no", "not"], ["beberán", "drink"], ["el", "the"], ["vino", "wine"], ["de", "of"], ["ellas.", "they."]]},
  {num:14,words:[["Cercano", "near"], ["está", "is"], ["el", "the"], ["día", "day"], ["grande", "great"], ["de", "of"], ["Jehová,", "jehovah,"], ["cercano", "near"], ["y", "and"], ["viene", "comes"], ["muy", "very"], ["rápido;", "even;"], ["amargo", "bitter"], ["será", "shall-be"], ["el", "the"], ["clamor", "cry"], ["del", "of-the"], ["día", "day"], ["de", "of"], ["Jehová;", "jehovah;"], ["allí", "there"], ["gritará", "shall-cry-out"], ["el", "the"], ["valiente.", "valiant."]]},
  {num:15,words:[["Será", "shall-be"], ["día", "day"], ["de", "of"], ["ira", "wrath"], ["aquel", "that"], ["día,", "day,"], ["día", "day"], ["de", "of"], ["angustia", "anguish"], ["y", "and"], ["de", "of"], ["aflicción,", "affliction,"], ["día", "day"], ["de", "of"], ["destrucción", "destruction"], ["y", "and"], ["de", "of"], ["desolación,", "desolation,"], ["día", "day"], ["de", "of"], ["tinieblas", "darkness"], ["y", "and"], ["de", "of"], ["oscuridad,", "darkness,"], ["día", "day"], ["nublado", "and"], ["y", "and"], ["tenebroso,", "of,"]]},
  {num:16,words:[["día", "day"], ["de", "of"], ["trompeta", "trump"], ["y", "and"], ["de", "of"], ["alarido", "and"], ["contra", "against"], ["las", "the"], ["ciudades", "cities"], ["fortificadas", "fenced"], ["y", "and"], ["contra", "against"], ["las", "the"], ["altas", "highs"], ["torres.", "towers."]]},
  {num:17,words:[["Y", "and"], ["atribularé", "i"], ["a", "to"], ["los", "the"], ["hombres,", "men,"], ["y", "and"], ["andarán", "walk"], ["como", "as"], ["ciegos", "deaf"], ["porque", "because"], ["pecaron", "sinned"], ["contra", "against"], ["Jehová;", "jehovah;"], ["y", "and"], ["la", "the"], ["sangre", "blood"], ["de", "of"], ["ellos", "they"], ["será", "shall-be"], ["derramada", "shed"], ["como", "as"], ["polvo,", "dust,"], ["y", "and"], ["su", "his/her"], ["carne", "flesh"], ["como", "as"], ["estiércol.", "dung."]]},
  {num:18,words:[["Ni", "nor"], ["su", "his/her"], ["plata", "silver"], ["ni", "nor"], ["su", "his/her"], ["oro", "gold"], ["podrán", "be"], ["librarlos", "deliver"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["ira", "wrath"], ["de", "of"], ["Jehová,", "jehovah,"], ["pues", "for"], ["toda", "all"], ["la", "the"], ["tierra", "land/earth"], ["será", "shall-be"], ["consumida", "be"], ["con", "with"], ["el", "the"], ["fuego", "fire"], ["de", "of"], ["su", "his/her"], ["celo;", "zeal;"], ["porque", "because"], ["ciertamente", "surely"], ["destrucción", "destruction"], ["apresurada", "a"], ["hará", "shall-make"], ["de", "of"], ["todos", "all"], ["los", "the"], ["moradores", "inhabitants"], ["de", "of"], ["la", "the"], ["tierra.", "land/earth."]]},
];
renderVerseSet(v1, 'zep-ch1-verses');

var v2 = [
  {num:1,words:[["Congregaos", "together"], ["y", "and"], ["reuníos,", "yourselves,"], ["oh", "oh"], ["nación", "nation"], ["sin", "without"], ["pudor,", "desired,"]]},
  {num:2,words:[["antes", "before"], ["que", "that"], ["tenga", "may-have"], ["efecto", "effect"], ["el", "the"], ["decreto", "decree"], ["y", "and"], ["el", "the"], ["día", "day"], ["se", "[refl.]"], ["pase", "passeth"], ["como", "as"], ["el", "the"], ["tamo,", "chaff,"], ["antes", "before"], ["que", "that"], ["venga", "let-come"], ["sobre", "upon"], ["vosotros", "you"], ["el", "the"], ["furor", "fury"], ["de", "of"], ["la", "the"], ["ira", "wrath"], ["de", "of"], ["Jehová,", "jehovah,"], ["antes", "before"], ["que", "that"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["ira", "wrath"], ["de", "of"], ["Jehová", "jehovah"], ["venga", "let-come"], ["sobre", "upon"], ["vosotros.", "you."]]},
  {num:3,words:[["Buscad", "seek"], ["a", "to"], ["Jehová", "jehovah"], ["todos", "all"], ["los", "the"], ["humildes", "humble"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["los", "the"], ["que", "that"], ["pusisteis", "wrought"], ["por", "by/for"], ["obra", "work"], ["su", "his/her"], ["juicio;", "judgment;"], ["buscad", "seek"], ["justicia,", "justice/righteousness,"], ["buscad", "seek"], ["mansedumbre;", "meekness;"], ["quizá", "perhaps"], ["seréis", "you-shall-be"], ["guardados", "kepts"], ["en", "in"], ["el", "the"], ["día", "day"], ["de", "of"], ["la", "the"], ["ira", "wrath"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:4,words:[["Porque", "because"], ["Gaza", "gaza"], ["será", "shall-be"], ["desamparada,", "forsaken,"], ["y", "and"], ["Ascalón", "ashkelon"], ["desolada;", "desolate;"], ["saquearán", "drive"], ["a", "to"], ["Asdod", "ashdod"], ["al", "to-the"], ["mediodía,", "noonday,"], ["y", "and"], ["Ecrón", "ekron"], ["será", "shall-be"], ["desarraigada.", "up."]]},
  {num:5,words:[["¡Ay", "wo"], ["de", "of"], ["los", "the"], ["que", "that"], ["moran", "dwell"], ["en", "in"], ["la", "the"], ["costa", "sea"], ["del", "of-the"], ["mar,", "sea,"], ["del", "of-the"], ["pueblo", "people"], ["de", "of"], ["los", "the"], ["cereteos!", "cherethites!"], ["La", "the"], ["palabra", "word"], ["de", "of"], ["Jehová", "jehovah"], ["es", "is"], ["contra", "against"], ["vosotros,", "you,"], ["oh", "oh"], ["Canaán,", "canaan,"], ["tierra", "land/earth"], ["de", "of"], ["los", "the"], ["filisteos;", "philistines;"], ["te", "thee"], ["haré", "I-shall-make"], ["destruir", "destroy"], ["hasta", "until"], ["no", "not"], ["dejar", "leave"], ["morador.", "inhabitant."]]},
  {num:6,words:[["Y", "and"], ["la", "the"], ["costa", "sea"], ["del", "of-the"], ["mar", "sea"], ["será", "shall-be"], ["praderas", "and"], ["para", "for"], ["pastores", "pastors"], ["y", "and"], ["corrales", "folds"], ["de", "of"], ["ovejas.", "sheep."]]},
  {num:7,words:[["Y", "and"], ["será", "shall-be"], ["aquel", "that"], ["lugar", "place"], ["para", "for"], ["el", "the"], ["remanente", "remnant"], ["de", "of"], ["la", "the"], ["casa", "house"], ["de", "of"], ["Judá;", "Judah;"], ["allí", "there"], ["apacentarán;", "shall-feed;"], ["en", "in"], ["las", "the"], ["casas", "houses"], ["de", "of"], ["Ascalón", "ashkelon"], ["dormirán", "shall-to"], ["al", "to-the"], ["anochecer,", "in,"], ["porque", "because"], ["Jehová", "jehovah"], ["su", "his/her"], ["Dios", "God"], ["los", "the"], ["visitará", "visit"], ["y", "and"], ["hará", "shall-make"], ["volver", "return"], ["sus", "his/her"], ["cautivos.", "captives."]]},
  {num:8,words:[["Yo", "I"], ["he", "I-have"], ["oído", "heard"], ["las", "the"], ["afrentas", "reproachs"], ["de", "of"], ["Moab", "moab"], ["y", "and"], ["los", "the"], ["denuestos", "revilings"], ["de", "of"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Amón", "amon"], ["con", "with"], ["que", "that"], ["deshonraron", "have"], ["a", "to"], ["mi", "my"], ["pueblo,", "people,"], ["y", "and"], ["se", "[refl.]"], ["engrandecieron", "themselves"], ["sobre", "upon"], ["su", "his/her"], ["territorio.", "coast."]]},
  {num:9,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["vivo", "live"], ["yo,", "I,"], ["dice", "says"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos,", "armies,"], ["Dios", "God"], ["de", "of"], ["Israel,", "Israel,"], ["que", "that"], ["Moab", "moab"], ["será", "shall-be"], ["como", "as"], ["Sodoma,", "gomorrah,"], ["y", "and"], ["los", "the"], ["hijos", "children"], ["de", "of"], ["Amón", "amon"], ["como", "as"], ["Gomorra:", "gomorrah:"], ["serán", "shall-be"], ["un", "a"], ["campo", "field"], ["de", "of"], ["ortigas,", "of,"], ["y", "and"], ["una", "a"], ["mina", "saltpits,"], ["de", "of"], ["sal", "salt"], ["y", "and"], ["desolación", "desolation"], ["perpetua;", "perpetual;"], ["el", "the"], ["remanente", "remnant"], ["de", "of"], ["mi", "my"], ["pueblo", "people"], ["los", "the"], ["saqueará,", "and,"], ["y", "and"], ["el", "the"], ["resto", "remnant"], ["de", "of"], ["mi", "my"], ["nación", "nation"], ["los", "the"], ["heredará.", "inherit."]]},
  {num:10,words:[["Esto", "this"], ["les", "them"], ["vendrá", "shall-come"], ["por", "by/for"], ["su", "his/her"], ["soberbia,", "pride,"], ["porque", "because"], ["afrentaron", "they"], ["al", "to-the"], ["pueblo", "people"], ["de", "of"], ["Jehová", "jehovah"], ["de", "of"], ["los", "the"], ["ejércitos", "armies"], ["y", "and"], ["se", "[refl.]"], ["engrandecieron", "lord"], ["contra", "against"], ["él.", "he."]]},
  {num:11,words:[["Terrible", "awful"], ["será", "shall-be"], ["Jehová", "jehovah"], ["con", "with"], ["ellos,", "they,"], ["porque", "because"], ["hará", "shall-make"], ["venir", "come"], ["a", "to"], ["menos", "less"], ["a", "to"], ["todos", "all"], ["los", "the"], ["dioses", "gods"], ["de", "of"], ["la", "the"], ["tierra;", "land/earth;"], ["y", "and"], ["cada", "each"], ["uno", "one"], ["desde", "from"], ["su", "his/her"], ["lugar", "place"], ["se", "[refl.]"], ["inclinará", "from"], ["ante", "before"], ["él", "he"], ["en", "in"], ["todas", "all"], ["las", "the"], ["costas", "of"], ["de", "of"], ["las", "the"], ["naciones.", "nations."]]},
  {num:12,words:[["También", "also"], ["vosotros,", "you,"], ["los", "the"], ["de", "of"], ["Etiopía,", "ethiopia,"], ["seréis", "you-shall-be"], ["muertos", "dead"], ["con", "with"], ["mi", "my"], ["espada.", "sword."]]},
  {num:13,words:[["Y", "and"], ["extenderá", "hand"], ["su", "his/her"], ["mano", "hand"], ["contra", "against"], ["el", "the"], ["norte", "north"], ["y", "and"], ["destruirá", "destroy"], ["a", "to"], ["Asiria;", "assyria;"], ["y", "and"], ["convertirá", "shall"], ["a", "to"], ["Nínive", "nineveh"], ["en", "in"], ["desolación", "desolation"], ["y", "and"], ["en", "in"], ["sequedal,", "dry,"], ["como", "as"], ["un", "a"], ["desierto.", "wilderness."]]},
  {num:14,words:[["Y", "and"], ["rebaños", "flocks"], ["se", "[refl.]"], ["echarán", "cast"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ella", "she"], ["y", "and"], ["todas", "all"], ["las", "the"], ["bestias", "beasts"], ["del", "of-the"], ["campo;", "field;"], ["también", "also"], ["el", "the"], ["pelícano", "and"], ["y", "and"], ["el", "the"], ["erizo", "lodge"], ["dormirán", "shall-to"], ["en", "in"], ["sus", "his/her"], ["dinteles;", "lintels;"], ["su", "his/her"], ["voz", "voice"], ["cantará", "shall"], ["en", "in"], ["las", "the"], ["ventanas;", "windows;"], ["habrá", "there-shall-be"], ["desolación", "desolation"], ["en", "in"], ["los", "the"], ["umbrales,", "thresholds,"], ["porque", "because"], ["su", "his/her"], ["obra", "work"], ["de", "of"], ["cedro", "cedar"], ["quedará", "shall-remain"], ["descubierta.", "of."]]},
  {num:15,words:[["Esta", "this"], ["es", "is"], ["la", "the"], ["ciudad", "city"], ["alegre", "merry"], ["que", "that"], ["estaba", "was"], ["confiada,", "trust,"], ["la", "the"], ["que", "that"], ["decía", "said"], ["en", "in"], ["su", "his/her"], ["corazón:", "heart:"], ["Yo,", "I,"], ["y", "and"], ["nadie", "no-one"], ["más.", "more."], ["¡Cómo", "how"], ["fue", "was/went"], ["desolada,", "desolate,"], ["hecha", "done"], ["guarida", "a"], ["de", "of"], ["fieras!", "beasts!"], ["Todo", "all"], ["el", "the"], ["que", "that"], ["pase", "passeth"], ["junto", "together"], ["a", "to"], ["ella", "she"], ["se", "[refl.]"], ["burlará", "shall-mock"], ["y", "and"], ["agitará", "and"], ["su", "his/her"], ["mano.", "hand."]]},
];
renderVerseSet(v2, 'zep-ch2-verses');

var v3 = [
  {num:1,words:[["¡Ay", "wo"], ["de", "of"], ["la", "the"], ["ciudad", "city"], ["opresora,", "and,"], ["inmunda", "unclean"], ["y", "and"], ["contaminada!", "defiled!"]]},
  {num:2,words:[["No", "not"], ["escuchó", "hearkened"], ["la", "the"], ["voz", "voice"], ["ni", "nor"], ["recibió", "received"], ["la", "the"], ["corrección;", "but;"], ["no", "not"], ["confió", "trusted"], ["en", "in"], ["Jehová", "jehovah"], ["ni", "nor"], ["se", "[refl.]"], ["acercó", "drew"], ["a", "to"], ["su", "his/her"], ["Dios.", "God."]]},
  {num:3,words:[["Sus", "his/her"], ["príncipes", "princes"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ella", "she"], ["son", "are"], ["leones", "lions"], ["rugientes;", "judges;"], ["sus", "his/her"], ["jueces,", "judges,"], ["lobos", "wolves"], ["del", "of-the"], ["atardecer", "bathe"], ["que", "that"], ["no", "not"], ["dejan", "they"], ["hueso", "bone"], ["para", "for"], ["la", "the"], ["mañana;", "morning;"]]},
  {num:4,words:[["sus", "his/her"], ["profetas,", "prophets,"], ["insolentes,", "light,"], ["hombres", "men"], ["pérfidos;", "persons;"], ["sus", "his/her"], ["sacerdotes", "priests"], ["contaminaron", "the"], ["el", "the"], ["santuario;", "sanctuary;"], ["falsearon", "done"], ["la", "the"], ["ley.", "law."]]},
  {num:5,words:[["Jehová", "jehovah"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ella", "she"], ["es", "is"], ["justo;", "just/righteous;"], ["no", "not"], ["hará", "shall-make"], ["iniquidad;", "iniquity;"], ["cada", "each"], ["mañana", "morning"], ["sacará", "bring"], ["a", "to"], ["luz", "light"], ["su", "his/her"], ["juicio,", "judgment,"], ["sin", "without"], ["falta,", "want,"], ["pero", "but"], ["el", "the"], ["perverso", "wicked"], ["no", "not"], ["conoce", "knoweth"], ["la", "the"], ["vergüenza.", "shame."]]},
  {num:6,words:[["He", "I-have"], ["talado", "cut"], ["naciones;", "nations;"], ["sus", "his/her"], ["torres", "towers"], ["están", "are"], ["desoladas;", "desolate;"], ["he", "I-have"], ["dejado", "left"], ["desiertas", "desolates"], ["sus", "his/her"], ["calles", "streets"], ["hasta", "until"], ["no", "not"], ["quedar", "remain"], ["quien", "who"], ["pase.", "passeth."], ["Sus", "his/her"], ["ciudades", "cities"], ["han", "have"], ["quedado", "remained"], ["destruidas", "destroyed"], ["hasta", "until"], ["no", "not"], ["quedar", "remain"], ["hombre", "man"], ["alguno,", "some,"], ["hasta", "until"], ["no", "not"], ["quedar", "remain"], ["morador.", "inhabitant."]]},
  {num:7,words:[["Dije:", "I-said:"], ["Ciertamente", "surely"], ["me", "me"], ["temerás;", "shalt;"], ["recibirás", "receive"], ["corrección.", "but."], ["Y", "and"], ["no", "not"], ["será", "shall-be"], ["destruida", "destroyed"], ["su", "his/her"], ["morada", "habitation"], ["según", "according-to"], ["todo", "all"], ["aquello", "thing"], ["por", "by/for"], ["lo", "it/him"], ["cual", "which"], ["la", "the"], ["castigué.", "them."], ["Mas", "but"], ["ellos", "they"], ["madrugaron", "rose"], ["para", "for"], ["corromper", "and"], ["todas", "all"], ["sus", "his/her"], ["obras.", "works."]]},
  {num:8,words:[["Por", "by/for"], ["tanto,", "therefore,"], ["esperadme,", "ye,"], ["dice", "says"], ["Jehová,", "jehovah,"], ["hasta", "until"], ["el", "the"], ["día", "day"], ["en", "in"], ["que", "that"], ["me", "me"], ["levante", "up"], ["para", "for"], ["el", "the"], ["despojo,", "spoil,"], ["porque", "because"], ["mi", "my"], ["determinación", "determination"], ["es", "is"], ["reunir", "gather"], ["las", "the"], ["naciones", "nations"], ["y", "and"], ["juntar", "gather"], ["los", "the"], ["reinos", "kingdoms"], ["para", "for"], ["derramar", "shedding"], ["sobre", "upon"], ["ellos", "they"], ["mi", "my"], ["enojo,", "fury,"], ["todo", "all"], ["el", "the"], ["furor", "fury"], ["de", "of"], ["mi", "my"], ["ira;", "wrath;"], ["porque", "because"], ["por", "by/for"], ["el", "the"], ["fuego", "fire"], ["de", "of"], ["mi", "my"], ["celo", "zeal"], ["será", "shall-be"], ["consumida", "be"], ["toda", "all"], ["la", "the"], ["tierra.", "land/earth."]]},
  {num:9,words:[["Porque", "because"], ["en", "in"], ["aquel", "that"], ["entonces", "then"], ["devolveré", "turn"], ["yo", "I"], ["a", "to"], ["los", "the"], ["pueblos", "peoples"], ["un", "a"], ["lenguaje", "language"], ["puro", "pure"], ["para", "for"], ["que", "that"], ["todos", "all"], ["invoquen", "upon"], ["el", "the"], ["nombre", "name"], ["de", "of"], ["Jehová,", "jehovah,"], ["para", "for"], ["que", "that"], ["le", "him/her"], ["sirvan", "serve"], ["de", "of"], ["común", "common"], ["acuerdo.", "agreement."]]},
  {num:10,words:[["Desde", "from"], ["la", "the"], ["región", "region"], ["más", "more"], ["allá", "thither"], ["de", "of"], ["los", "the"], ["ríos", "rivers"], ["de", "of"], ["Etiopía,", "ethiopia,"], ["mis", "my"], ["suplicantes,", "daughter,"], ["la", "the"], ["hija", "daughter"], ["de", "of"], ["mis", "my"], ["esparcidos,", "scattered,"], ["traerán", "bring"], ["mi", "my"], ["ofrenda.", "offering."]]},
  {num:11,words:[["En", "in"], ["aquel", "that"], ["día", "day"], ["no", "not"], ["serás", "thou-shalt-be"], ["avergonzada", "ashamed"], ["por", "by/for"], ["ninguna", "none"], ["de", "of"], ["tus", "thy"], ["obras", "works"], ["con", "with"], ["que", "that"], ["te", "thee"], ["rebelaste", "against"], ["contra", "against"], ["mí,", "me,"], ["porque", "because"], ["entonces", "then"], ["quitaré", "take"], ["de", "of"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti", "thee"], ["a", "to"], ["los", "the"], ["que", "that"], ["se", "[refl.]"], ["alegran", "rejoice"], ["en", "in"], ["tu", "thy"], ["soberbia,", "pride,"], ["y", "and"], ["nunca", "never"], ["más", "more"], ["te", "thee"], ["ensoberbecerás", "haughty"], ["en", "in"], ["mi", "my"], ["santo", "holy"], ["monte.", "mount."]]},
  {num:12,words:[["Y", "and"], ["dejaré", "leave"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti", "thee"], ["un", "a"], ["pueblo", "people"], ["humilde", "humble"], ["y", "and"], ["pobre,", "poor,"], ["el", "the"], ["cual", "which"], ["se", "[refl.]"], ["refugiará", "trust"], ["en", "in"], ["el", "the"], ["nombre", "name"], ["de", "of"], ["Jehová.", "jehovah."]]},
  {num:13,words:[["El", "the"], ["remanente", "remnant"], ["de", "of"], ["Israel", "Israel"], ["no", "not"], ["cometerá", "shall-commit"], ["iniquidad", "iniquity"], ["ni", "nor"], ["dirá", "shall-say"], ["mentira,", "lies,"], ["ni", "nor"], ["en", "in"], ["boca", "mouth"], ["de", "of"], ["ellos", "they"], ["se", "[refl.]"], ["hallará", "find"], ["lengua", "tongue"], ["engañosa,", "mouth,"], ["porque", "because"], ["ellos", "they"], ["serán", "shall-be"], ["apacentados", "feed"], ["y", "and"], ["reposarán,", "shall-rest,"], ["y", "and"], ["no", "not"], ["habrá", "there-shall-be"], ["quien", "who"], ["los", "the"], ["espante.", "and."]]},
  {num:14,words:[["¡Canta,", "in,"], ["oh", "oh"], ["hija", "daughter"], ["de", "of"], ["Sion!", "Zion!"], ["¡Da", "gives"], ["voces", "voices"], ["de", "of"], ["júbilo,", "shout,"], ["oh", "oh"], ["Israel!", "Israel!"], ["¡Alégrate", "and"], ["y", "and"], ["regocíjate", "rejoice"], ["de", "of"], ["todo", "all"], ["corazón,", "heart,"], ["oh", "oh"], ["hija", "daughter"], ["de", "of"], ["Jerusalén!", "Jerusalem!"]]},
  {num:15,words:[["Jehová", "jehovah"], ["ha", "has"], ["retirado", "from"], ["tus", "thy"], ["juicios;", "judgments;"], ["ha", "has"], ["echado", "hewn"], ["fuera", "outside/were"], ["tus", "thy"], ["enemigos;", "enemies;"], ["Jehová", "jehovah"], ["es", "is"], ["Rey", "king"], ["de", "of"], ["Israel", "Israel"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti;", "thee;"], ["nunca", "never"], ["más", "more"], ["temerás", "shalt"], ["mal", "evil"], ["alguno.", "some."]]},
  {num:16,words:[["En", "in"], ["aquel", "that"], ["tiempo", "time"], ["se", "[refl.]"], ["dirá", "shall-say"], ["a", "to"], ["Jerusalén:", "Jerusalem:"], ["No", "not"], ["temas,", "dismayed,"], ["Sion;", "Zion;"], ["no", "not"], ["se", "[refl.]"], ["debiliten", "thine"], ["tus", "thy"], ["manos.", "hands."]]},
  {num:17,words:[["Jehová", "jehovah"], ["tu", "thy"], ["Dios", "God"], ["está", "is"], ["en", "in"], ["medio", "midst"], ["de", "of"], ["ti:", "thee:"], ["¡Él", "he"], ["es", "is"], ["poderoso!", "mighty!"], ["¡Él", "he"], ["salvará!", "save!"], ["Se", "[refl.]"], ["regocijará", "rejoice"], ["por", "by/for"], ["ti", "thee"], ["con", "with"], ["alegría;", "mirth;"], ["guardará", "keep"], ["silencio", "silence"], ["por", "by/for"], ["su", "his/her"], ["amor;", "love;"], ["se", "[refl.]"], ["regocijará", "rejoice"], ["por", "by/for"], ["ti", "thee"], ["con", "with"], ["cánticos.", "songs."]]},
  {num:18,words:[["Reuniré", "gather"], ["a", "to"], ["los", "the"], ["que", "that"], ["se", "[refl.]"], ["entristecían", "sorrowful"], ["por", "by/for"], ["las", "the"], ["fiestas", "moons"], ["señaladas;", "who;"], ["tuyos", "thine"], ["fueron;", "were;"], ["para", "for"], ["quienes", "who"], ["el", "the"], ["oprobio", "reproach"], ["era", "was"], ["una", "a"], ["carga.", "burden."]]},
  {num:19,words:[["He", "I-have"], ["aquí,", "here,"], ["en", "in"], ["aquel", "that"], ["tiempo", "time"], ["me", "me"], ["ocuparé", "shall-to"], ["de", "of"], ["todos", "all"], ["tus", "thy"], ["opresores;", "and;"], ["y", "and"], ["salvaré", "save"], ["a", "to"], ["la", "the"], ["que", "that"], ["cojea", "her"], ["y", "and"], ["recogeré", "gather"], ["a", "to"], ["la", "the"], ["desterrada;", "the;"], ["y", "and"], ["cambiaré", "them"], ["su", "his/her"], ["vergüenza", "shame"], ["en", "in"], ["alabanza", "praise"], ["y", "and"], ["en", "in"], ["renombre", "renown"], ["en", "in"], ["todo", "all"], ["país.", "country."]]},
  {num:20,words:[["En", "in"], ["aquel", "that"], ["tiempo", "time"], ["yo", "I"], ["os", "you"], ["traeré;", "bring;"], ["en", "in"], ["aquel", "that"], ["tiempo", "time"], ["os", "you"], ["reuniré", "gather"], ["yo.", "I."], ["Pues", "for"], ["os", "you"], ["haré", "I-shall-make"], ["objeto", "intent"], ["de", "of"], ["renombre", "renown"], ["y", "and"], ["de", "of"], ["alabanza", "praise"], ["entre", "among"], ["todos", "all"], ["los", "the"], ["pueblos", "peoples"], ["de", "of"], ["la", "the"], ["tierra,", "land/earth,"], ["cuando", "when"], ["haga", "let-do"], ["volver", "return"], ["a", "to"], ["vuestros", "your"], ["cautivos", "captives"], ["ante", "before"], ["vuestros", "your"], ["propios", "own"], ["ojos,", "eyes,"], ["dice", "says"], ["Jehová.", "jehovah."]]},
];
renderVerseSet(v3, 'zep-ch3-verses');

})();
