(function() {
var v1 = [
  {num:1,words:[["La","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["que","that"],["vino","came"],["a","to"],["Sofonías","Zephaniah"],["hijo","son"],["de","of"],["Cusi,","Cushi,"],["hijo","son"],["de","of"],["Gedalías,","Gedaliah,"],["hijo","son"],["de","of"],["Amarías,","Amariah,"],["hijo","son"],["de","of"],["Ezequías,","Hezekiah,"],["en","in"],["los","the"],["días","days"],["de","of"],["Josías","Josiah"],["hijo","son"],["de","of"],["Amón,","Amon,"],["rey","king"],["de","of"],["Judá:","Judah:"]]},
  {num:2,words:[["Destruiré","I-will-destroy"],["por","for"],["completo","utterly"],["todas","all"],["las","the"],["cosas","things"],["de","of"],["sobre","upon"],["la","the"],["faz","face"],["de","of"],["la","the"],["tierra,","land,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:3,words:[["Destruiré","I-will-destroy"],["a","to"],["los","the"],["hombres","men"],["y","and"],["las","the"],["bestias;","beasts;"],["destruiré","I-will-destroy"],["las","the"],["aves","fowls"],["del","of-the"],["cielo,","heaven,"],["y","and"],["los","the"],["peces","fish"],["del","of-the"],["mar","sea"],["y","and"],["las","the"],["piedras","stones"],["de","of"],["tropiezo","stumblingblock"],["junto","together"],["con","with"],["los","the"],["malvados;","wicked;"],["y","and"],["talaré","I-cut"],["a","to"],["los","the"],["hombres","men"],["de","of"],["sobre","upon"],["la","the"],["faz","face"],["de","of"],["la","the"],["tierra,","land,"],["dice","says"],["Jehová.","jehovah."]]},
  {num:4,words:[["Y","and"],["extenderé","I-stretch"],["mi","my"],["mano","hand"],["contra","against"],["Judá","Judah"],["y","and"],["contra","against"],["todos","all"],["los","the"],["moradores","inhabitants"],["de","of"],["Jerusalén;","Jerusalem;"],["y","and"],["exterminaré","I-will-exterminate"],["de","of"],["este","this"],["lugar","place"],["los","the"],["restos","remnants"],["de","of"],["Baal,","Baal,"],["y","and"],["el","the"],["nombre","name"],["de","of"],["los","the"],["ministros","ministers"],["idólatras","idolaters"],["junto","together"],["con","with"],["los","the"],["sacerdotes,","priests,"]]},
  {num:5,words:[["y","and"],["a","to"],["los","the"],["que","that"],["sobre","upon"],["los","the"],["terrados","thes"],["se","themselves"],["postran","last"],["ante","before"],["el","the"],["ejército","army"],["del","of-the"],["cielo,","heaven,"],["y","and"],["a","to"],["los","the"],["que","that"],["se","themselves"],["postran","last"],["jurando","swearing"],["por","by"],["Jehová","jehovah"],["y","and"],["jurando","swearing"],["por","by"],["Moloc,","Molech,"]]},
  {num:6,words:[["y","and"],["a","to"],["los","the"],["que","that"],["se","themselves"],["apartan","turn"],["de","of"],["en pos de","after"],["Jehová","jehovah"],["y","and"],["a","to"],["los","the"],["que","that"],["no","not"],["buscaron","they-sought"],["a","to"],["Jehová","jehovah"],["ni","nor"],["le","him"],["consultaron.","they-enquired."]]},
  {num:7,words:[["Calla","is-silent"],["ante","before"],["la","the"],["presencia","presence"],["de","of"],["Jehová","jehovah"],["el","the"],["Señor,","Lord,"],["porque","because"],["el","the"],["día","day"],["de","of"],["Jehová","jehovah"],["está","is"],["cercano;","near;"],["porque","because"],["Jehová","jehovah"],["ha","has"],["preparado","prepared"],["un","a"],["sacrificio","sacrifice"],["y","and"],["ha","has"],["consagrado","consecrated"],["a","to"],["sus","his"],["convidados.","were."]]},
  {num:8,words:[["Y","and"],["sucederá","pass"],["que","that"],["en","in"],["el","the"],["día","day"],["del","of-the"],["sacrificio","sacrifice"],["de","of"],["Jehová,","jehovah,"],["castigaré","I-will-punish"],["a","to"],["los","the"],["príncipes,","princes,"],["y","and"],["a","to"],["los","the"],["hijos","children"],["del","of-the"],["rey","king"],["y","and"],["a","to"],["todos","all"],["los","the"],["que","that"],["llevan","they-carry"],["vestido","clothed"],["extranjero.","sojourns."]]},
  {num:9,words:[["Asimismo,","likewise,"],["castigaré","I-will-punish"],["en","in"],["aquel","that"],["día","day"],["a","to"],["todos","all"],["los","the"],["que","that"],["saltan","they-jump"],["sobre","upon"],["el","the"],["umbral,","threshold,"],["los","the"],["que","that"],["llenan","they-fill"],["de","of"],["violencia","violence"],["y","and"],["de","of"],["engaño","deceit"],["las","the"],["casas","houses"],["de","of"],["sus","their"],["señores.","shechem."]]},
  {num:10,words:[["Y","and"],["acontecerá","shall-come-to-pass"],["en","in"],["aquel","that"],["día,","day,"],["dice","says"],["Jehová,","jehovah,"],["que","that"],["habrá","there-shall-be"],["voz","voice"],["de","of"],["clamor","cry"],["desde","from"],["la","the"],["puerta","gate"],["del","of-the"],["Pescado,","fish,"],["y","and"],["aullido","gate"],["desde","from"],["el","the"],["segundo,","second,"],["y","and"],["gran","great"],["quebranto","destruction"],["desde","from"],["los","the"],["collados.","hills."]]},
  {num:11,words:[["Aullad,","you-howl,"],["moradores","inhabitants"],["de","of"],["Mactes,","Maktesh,"],["porque","because"],["todo","all"],["el","the"],["pueblo","people"],["mercader","merchant"],["ha","has"],["sido","been"],["destruido;","destroyed;"],["talados","cut"],["han","they-have"],["sido","been"],["todos","all"],["los","the"],["que","that"],["traían","they-brought"],["dinero.","sacks."]]},
  {num:12,words:[["Y","and"],["acontecerá","shall-come-to-pass"],["en","in"],["aquel","that"],["día","day"],["que","that"],["yo","I"],["escudriñaré","time"],["a","to"],["Jerusalén","Jerusalem"],["con","with"],["lámpara,","lamp,"],["y","and"],["castigaré","I-will-punish"],["a","to"],["los","the"],["hombres","men"],["que","that"],["reposan","they-rest"],["tranquilos","settled"],["como","as"],["el","the"],["vino","wine"],["asentado,","settled,"],["los","the"],["cuales","which"],["dicen","they-say"],["en","in"],["su","their"],["corazón:","heart:"],["Jehová","jehovah"],["no","not"],["hará","shall-make"],["bien","well"],["ni","nor"],["mal.","evil."]]},
  {num:13,words:[["Por tanto,","therefore,"],["serán","they-shall-be"],["saqueados","become"],["sus","their"],["bienes","goods"],["y","and"],["sus","their"],["casas","houses"],["asoladas;","desolate;"],["y","and"],["edificarán","they-will-build"],["casas,","houses,"],["mas","but"],["no","not"],["las","the"],["habitarán;","dwell;"],["y","and"],["plantarán","they-will-plant"],["viñas,","vineyards,"],["mas","but"],["no","not"],["beberán","they-will-drink"],["el","the"],["vino","wine"],["de","of"],["ellas.","they."]]},
  {num:14,words:[["Cercano","near"],["está","is"],["el","the"],["día","day"],["grande","great"],["de","of"],["Jehová,","jehovah,"],["cercano","near"],["y","and"],["viene","comes"],["muy","very"],["rápido;","fast;"],["amargo","bitter"],["será","shall-be"],["el","the"],["clamor","cry"],["del","of-the"],["día","day"],["de","of"],["Jehová;","jehovah;"],["allí","there"],["gritará","shall-cry-out"],["el","the"],["valiente.","valiant."]]},
  {num:15,words:[["Será","shall-be"],["día","day"],["de","of"],["ira","wrath"],["aquel","that"],["día,","day,"],["día","day"],["de","of"],["angustia","anguish"],["y","and"],["de","of"],["aflicción,","affliction,"],["día","day"],["de","of"],["destrucción","destruction"],["y","and"],["de","of"],["desolación,","desolation,"],["día","day"],["de","of"],["tinieblas","darkness"],["y","and"],["de","of"],["oscuridad,","darkness,"],["día","day"],["nublado","clouded"],["y","and"],["tenebroso,","of,"]]},
  {num:16,words:[["día","day"],["de","of"],["trompeta","trumpet"],["y","and"],["de","of"],["alarido","and"],["contra","against"],["las","the"],["ciudades","cities"],["fortificadas","fenced"],["y","and"],["contra","against"],["las","the"],["altas","loud"],["torres.","towers."]]},
  {num:17,words:[["Y","and"],["atribularé","I-will-distress"],["a","to"],["los","the"],["hombres,","men,"],["y","and"],["andarán","they-will-walk"],["como","as"],["ciegos","blind"],["porque","because"],["pecaron","they-sinned"],["contra","against"],["Jehová;","jehovah;"],["y","and"],["la","the"],["sangre","blood"],["de","of"],["ellos","they"],["será","shall-be"],["derramada","poured"],["como","as"],["polvo,","dust,"],["y","and"],["su","their"],["carne","flesh"],["como","as"],["estiércol.","dung."]]},
  {num:18,words:[["Ni","nor"],["su","his"],["plata","silver"],["ni","nor"],["su","his"],["oro","gold"],["podrán","they-be"],["librarlos","to-deliver-them"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["ira","wrath"],["de","of"],["Jehová,","jehovah,"],["pues","for"],["toda","all"],["la","the"],["tierra","land"],["será","shall-be"],["consumida","consumed"],["con","with"],["el","the"],["fuego","fire"],["de","of"],["su","his"],["celo;","zeal;"],["porque","because"],["ciertamente","surely"],["destrucción","destruction"],["apresurada","hurry"],["hará","shall-make"],["de","of"],["todos","all"],["los","the"],["moradores","inhabitants"],["de","of"],["la","the"],["tierra.","land."]]},
];
renderVerseSet(v1, 'zep-ch1-verses');

var v2 = [
  {num:1,words:[["Congregaos","together"],["y","and"],["reuníos,","himself,"],["oh","oh"],["nación","nation"],["sin","without"],["pudor,","desired,"]]},
  {num:2,words:[["antes que","before"],["tenga","may-have"],["efecto","effect"],["el","the"],["decreto","decree"],["y","and"],["el","the"],["día","day"],["se","itself"],["pase","passes"],["como","as"],["el","the"],["tamo,","chaff,"],["antes que","before"],["venga","let-come"],["sobre","upon"],["vosotros","you"],["el","the"],["furor","fury"],["de","of"],["la","the"],["ira","anger"],["de","of"],["Jehová,","jehovah,"],["antes que","before"],["el","the"],["día","day"],["de","of"],["la","the"],["ira","anger"],["de","of"],["Jehová","jehovah"],["venga","let-come"],["sobre","upon"],["vosotros.","you."]]},
  {num:3,words:[["Buscad","you-seek"],["a","to"],["Jehová","jehovah"],["todos","all"],["los","the"],["humildes","humble"],["de","of"],["la","the"],["tierra,","earth,"],["los","the"],["que","that"],["pusisteis","you-wrought"],["por","for"],["obra","work"],["su","his"],["juicio;","judgment;"],["buscad","you-seek"],["justicia,","righteousness,"],["buscad","you-seek"],["mansedumbre;","meekness;"],["quizá","perhaps"],["seréis","you-shall-be"],["guardados","kept"],["en","in"],["el","the"],["día","day"],["de","of"],["la","the"],["ira","anger"],["de","of"],["Jehová.","jehovah."]]},
  {num:4,words:[["Porque","because"],["Gaza","Gaza"],["será","shall-be"],["desamparada,","forsaken,"],["y","and"],["Ascalón","Ashkelon"],["desolada;","desolate;"],["saquearán","they-drive"],["a","to"],["Asdod","Ashdod"],["al","to-the"],["mediodía,","noon,"],["y","and"],["Ecrón","Ekron"],["será","shall-be"],["desarraigada.","up."]]},
  {num:5,words:[["¡Ay","wo"],["de","of"],["los","the"],["que","that"],["moran","they-dwell"],["en","in"],["la","the"],["costa","sea"],["del","of-the"],["mar,","sea,"],["del","of-the"],["pueblo","people"],["de","of"],["los","the"],["cereteos!","Cherethites!"],["La","the"],["palabra","word"],["de","of"],["Jehová","jehovah"],["es","is"],["contra","against"],["vosotros,","you,"],["oh","oh"],["Canaán,","Canaan,"],["tierra","land"],["de","of"],["los","the"],["filisteos;","Philistines;"],["te","you"],["haré","I will make"],["destruir","to-destroy"],["hasta","until"],["no","not"],["dejar","to-leave"],["morador.","inhabitant."]]},
  {num:6,words:[["Y","and"],["la","the"],["costa","sea"],["del","of-the"],["mar","sea"],["será","shall-be"],["praderas","meadows"],["para","for"],["pastores","shepherds"],["y","and"],["corrales","folds"],["de","of"],["ovejas.","sheep."]]},
  {num:7,words:[["Y","and"],["será","shall-be"],["aquel","that"],["lugar","place"],["para","for"],["el","the"],["remanente","remnant"],["de","of"],["la","the"],["casa","house"],["de","of"],["Judá;","Judah;"],["allí","there"],["apacentarán;","shall-feed;"],["en","in"],["las","the"],["casas","houses"],["de","of"],["Ascalón","Ashkelon"],["dormirán","they-shall-to"],["al","to-the"],["anochecer,","nightfall,"],["porque","because"],["Jehová","jehovah"],["su","their"],["Dios","God"],["los","the"],["visitará","visit"],["y","and"],["hará","shall-make"],["volver","to-return"],["sus","their"],["cautivos.","captives."]]},
  {num:8,words:[["Yo","I"],["he","have"],["oído","heard"],["las","the"],["afrentas","offense"],["de","of"],["Moab","Moab"],["y","and"],["los","the"],["denuestos","revilings"],["de","of"],["los","the"],["hijos","children"],["de","of"],["Amón","Ammon"],["con que","wherewith"],["deshonraron","dishonored"],["a","to"],["mi","my"],["pueblo,","people,"],["y","and"],["se","themselves"],["engrandecieron","themselves"],["sobre","upon"],["su","his"],["territorio.","coast."]]},
  {num:9,words:[["Por tanto,","therefore,"],["vivo","live"],["yo,","I,"],["dice","says"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos,","armies,"],["Dios","God"],["de","of"],["Israel,","Israel,"],["que","that"],["Moab","Moab"],["será","shall-be"],["como","as"],["Sodoma,","Sodom,"],["y","and"],["los","the"],["hijos","children"],["de","of"],["Amón","Ammon"],["como","as"],["Gomorra:","Gomorrah:"],["serán","they-shall-be"],["un","a"],["campo","field"],["de","of"],["ortigas,","of,"],["y","and"],["una","a"],["mina","saltpits"],["de","of"],["sal","salt"],["y","and"],["desolación","desolation"],["perpetua;","perpetual;"],["el","the"],["remanente","remnant"],["de","of"],["mi","my"],["pueblo","people"],["los","the"],["saqueará,","will-loot,"],["y","and"],["el","the"],["resto","remnant"],["de","of"],["mi","my"],["nación","nation"],["los","the"],["heredará.","inherit."]]},
  {num:10,words:[["Esto","this"],["les","them"],["vendrá","shall-come"],["por","for"],["su","their"],["soberbia,","pride,"],["porque","because"],["afrentaron","they-reproached"],["al","to-the"],["pueblo","people"],["de","of"],["Jehová","jehovah"],["de","of"],["los","the"],["ejércitos","armies"],["y","and"],["se","themselves"],["engrandecieron","lord"],["contra","against"],["él.","he."]]},
  {num:11,words:[["Terrible","awful"],["será","shall-be"],["Jehová","jehovah"],["con","with"],["ellos,","they,"],["porque","because"],["hará","shall-make"],["venir","to-come"],["a","to"],["menos","less"],["a","to"],["todos","all"],["los","the"],["dioses","gods"],["de","of"],["la","the"],["tierra;","earth;"],["y","and"],["cada","each"],["uno","one"],["desde","from"],["su","his"],["lugar","place"],["se","himself"],["inclinará","will-incline"],["ante","before"],["él","he"],["en","in"],["todas","all"],["las","the"],["costas","of"],["de","of"],["las","the"],["naciones.","nations."]]},
  {num:12,words:[["También", "also"], ["vosotros,", "you,"], ["los", "the"], ["de", "of"], ["Etiopía,","Ethiopia,"], ["seréis", "you-shall-be"], ["muertos", "dead"], ["con", "with"], ["mi", "my"], ["espada.", "sword."]]},
  {num:13,words:[["Y","and"],["extenderá","will-stretch"],["su","his"],["mano","hand"],["contra","against"],["el","the"],["norte","north"],["y","and"],["destruirá","destroy"],["a","to"],["Asiria;","Assyria;"],["y","and"],["convertirá","will-convert"],["a","to"],["Nínive","Nineveh"],["en","in"],["desolación","desolation"],["y","and"],["en","in"],["sequedal,","dry,"],["como","as"],["un","a"],["desierto.","wilderness."]]},
  {num:14,words:[["Y","and"],["rebaños","flocks"],["se","themselves"],["echarán","cast"],["en","in"],["medio","midst"],["de","of"],["ella","she"],["y","and"],["todas","all"],["las","the"],["bestias","beasts"],["del","of-the"],["campo;","field;"],["también","also"],["el","the"],["pelícano","and"],["y","and"],["el","the"],["erizo","lodge"],["dormirán","they-shall-to"],["en","in"],["sus","her"],["dinteles;","lintels;"],["su","her"],["voz","voice"],["cantará","will-sing"],["en","in"],["las","the"],["ventanas;","windows;"],["habrá","there-shall-be"],["desolación","desolation"],["en","in"],["los","the"],["umbrales,","thresholds,"],["porque","because"],["su","her"],["obra","work"],["de","of"],["cedro","cedar"],["quedará","shall-remain"],["descubierta.","discovers."]]},
  {num:15,words:[["Esta","this"],["es","is"],["la","the"],["ciudad","city"],["alegre","merry"],["que","that"],["estaba","was"],["confiada,","trust,"],["la","the"],["que","that"],["decía","said"],["en","in"],["su","his"],["corazón:","heart:"],["Yo,","I,"],["y","and"],["nadie","no-one"],["más.","more."],["¡Cómo","how"],["fue","was"],["desolada,","desolate,"],["hecha","done"],["guarida","lair"],["de","of"],["fieras!","beasts!"],["Todo","all"],["el","the"],["que","that"],["pase","passes"],["junto","together"],["a","to"],["ella","she"],["se","himself"],["burlará","shall-mock"],["y","and"],["agitará","will-shake"],["su","his"],["mano.","hand."]]},
];
renderVerseSet(v2, 'zep-ch2-verses');

var v3 = [
  {num:1,words:[["¡Ay","wo"],["de","of"],["la","the"],["ciudad","city"],["opresora,","and,"],["inmunda","filthy"],["y","and"],["contaminada!","pollute!"]]},
  {num:2,words:[["No","not"],["escuchó","hearkened"],["la","the"],["voz","voice"],["ni","nor"],["recibió","received"],["la","the"],["corrección;","but;"],["no","not"],["confió","trusted"],["en","in"],["Jehová","jehovah"],["ni","nor"],["se","itself"],["acercó","drew"],["a","to"],["su","her"],["Dios.","God."]]},
  {num:3,words:[["Sus","her"],["príncipes","princes"],["en","in"],["medio","midst"],["de","of"],["ella","she"],["son","they-are"],["leones","lions"],["rugientes;","roaring;"],["sus","her"],["jueces,","judges,"],["lobos","wolves"],["del","of-the"],["atardecer","evening"],["que","that"],["no","not"],["dejan","they-leave"],["hueso","bone"],["para","for"],["la","the"],["mañana;","morning;"]]},
  {num:4,words:[["sus","her"],["profetas,","prophets,"],["insolentes,","light,"],["hombres","men"],["pérfidos;","persons;"],["sus","her"],["sacerdotes","priests"],["contaminaron","they-contaminated"],["el","the"],["santuario;","sanctuary;"],["falsearon","done"],["la","the"],["ley.","law."]]},
  {num:5,words:[["Jehová","jehovah"],["en","in"],["medio","midst"],["de","of"],["ella","she"],["es","is"],["justo;","just;"],["no","not"],["hará","shall-make"],["iniquidad;","iniquity;"],["cada","each"],["mañana","morning"],["sacará","bring"],["a","to"],["luz","light"],["su","his"],["juicio,","judgment,"],["sin","without"],["falta,","want,"],["pero","but"],["el","the"],["perverso","wicked"],["no","not"],["conoce","knows"],["la","the"],["vergüenza.","shame."]]},
  {num:6,words:[["He","I-have"],["talado","cut"],["naciones;","nations;"],["sus","their"],["torres","towers"],["están","they-are"],["desoladas;","desolate;"],["he","I-have"],["dejado","left"],["desiertas","desolates"],["sus","their"],["calles","streets"],["hasta","until"],["no","not"],["quedar","remain"],["quien","who"],["pase.","passes."],["Sus","their"],["ciudades","cities"],["han","they-have"],["quedado","remained"],["destruidas","destroyed"],["hasta","until"],["no","not"],["quedar","remain"],["hombre","man"],["alguno,","some,"],["hasta","until"],["no","not"],["quedar","remain"],["morador.","inhabitant."]]},
  {num:7,words:[["Dije:","I-said:"],["Ciertamente","surely"],["me","me"],["temerás;","you-will-fear;"],["recibirás","you-receive"],["corrección.","but."],["Y","and"],["no","not"],["será","shall-be"],["destruida","destroyed"],["su","their"],["morada","dwelling"],["según","according-to"],["todo","all"],["aquello","thing"],["por","for"],["lo","it/him"],["cual","which"],["la","the"],["castigué.","I-punished."],["Mas","but"],["ellos","they"],["madrugaron","rose"],["para","for"],["corromper","to-corrupt"],["todas","all"],["sus","their"],["obras.","works."]]},
  {num:8,words:[["Por tanto,","therefore,"],["esperadme,","you,"],["dice","says"],["Jehová,","jehovah,"],["hasta","until"],["el","the"],["día","day"],["en que","that"],["me","me"],["levante","up"],["para","for"],["el","the"],["despojo,","spoil,"],["porque","because"],["mi","my"],["determinación","determination"],["es","is"],["reunir","to-gather"],["las","the"],["naciones","nations"],["y","and"],["juntar","gather"],["los","the"],["reinos","kingdoms"],["para","for"],["derramar","pour"],["sobre","upon"],["ellos","they"],["mi","my"],["enojo,","fury,"],["todo","all"],["el","the"],["furor","fury"],["de","of"],["mi","my"],["ira;","anger;"],["porque","because"],["por","for"],["el","the"],["fuego","fire"],["de","of"],["mi","my"],["celo","zeal"],["será","shall-be"],["consumida","consumed"],["toda","all"],["la","the"],["tierra.","earth."]]},
  {num:9,words:[["Porque","because"],["en","in"],["aquel","that"],["entonces","then"],["devolveré","will-return"],["yo","I"],["a","to"],["los","the"],["pueblos","peoples"],["un","a"],["lenguaje","language"],["puro","pure"],["para que","that"],["todos","all"],["invoquen","may-call"],["el","the"],["nombre","name"],["de","of"],["Jehová,","jehovah,"],["para que","that"],["le","him"],["sirvan","they-serve"],["de","of"],["común","common"],["acuerdo.","agreement."]]},
  {num:10,words:[["Desde","from"],["la","the"],["región","region"],["más","more"],["allá","there"],["de","of"],["los","the"],["ríos","rivers"],["de","of"],["Etiopía,","Ethiopia,"],["mis","my"],["suplicantes,","daughter,"],["la","the"],["hija","daughter"],["de","of"],["mis","my"],["esparcidos,","scattered,"],["traerán","they-will-bring"],["mi","my"],["ofrenda.","offering."]]},
  {num:11,words:[["En","in"],["aquel","that"],["día","day"],["no","not"],["serás","you-will-be"],["avergonzada","ashamed"],["por","for"],["ninguna","none"],["de","of"],["tus","your"],["obras","works"],["con que","wherewith"],["te","you"],["rebelaste","against"],["contra","against"],["mí,","me,"],["porque","because"],["entonces","then"],["quitaré","I-take"],["de","of"],["en","in"],["medio","midst"],["de","of"],["ti","you"],["a","to"],["los","the"],["que","that"],["se","themselves"],["alegran","rejoice"],["en","in"],["tu","your"],["soberbia,","pride,"],["y","and"],["nunca","never"],["más","more"],["te","you"],["ensoberbecerás","haughty"],["en","in"],["mi","my"],["santo","holy"],["monte.","mountain."]]},
  {num:12,words:[["Y","and"],["dejaré","I-will-leave"],["en","in"],["medio","midst"],["de","of"],["ti","you"],["un","a"],["pueblo","people"],["humilde","humble"],["y","and"],["pobre,","poor,"],["el","the"],["cual","which"],["se","himself"],["refugiará","trust"],["en","in"],["el","the"],["nombre","name"],["de","of"],["Jehová.","jehovah."]]},
  {num:13,words:[["El","the"],["remanente","remnant"],["de","of"],["Israel","Israel"],["no","not"],["cometerá","will-commit"],["iniquidad","iniquity"],["ni","nor"],["dirá","will-say"],["mentira,","lies,"],["ni","nor"],["en","in"],["boca","mouth"],["de","of"],["ellos","they"],["se","himself"],["hallará","find"],["lengua","tongue"],["engañosa,","mouth,"],["porque","because"],["ellos","they"],["serán","shall-be"],["apacentados","feed"],["y","and"],["reposarán,","they-will-rest,"],["y","and"],["no","not"],["habrá","there-shall-be"],["quien","who"],["los","the"],["espante.","may-scare."]]},
  {num:14,words:[["¡Canta,","sings,"],["oh","oh"],["hija","daughter"],["de","of"],["Sion!","Zion!"],["¡Da","gives"],["voces","voices"],["de","of"],["júbilo,","shout,"],["oh","oh"],["Israel!","Israel!"],["¡Alégrate","and"],["y","and"],["regocíjate","rejoice"],["de","of"],["todo","all"],["corazón,","heart,"],["oh","oh"],["hija","daughter"],["de","of"],["Jerusalén!","Jerusalem!"]]},
  {num:15,words:[["Jehová","jehovah"],["ha","has"],["retirado","withdrawn"],["tus","your"],["juicios;","judgments;"],["ha","has"],["echado","cast"],["fuera","were"],["tus","your"],["enemigos;","enemies;"],["Jehová","jehovah"],["es","is"],["Rey","king"],["de","of"],["Israel","Israel"],["en","in"],["medio","midst"],["de","of"],["ti;","you;"],["nunca","never"],["más","more"],["temerás","you-will-fear"],["mal","evil"],["alguno.","some."]]},
  {num:16,words:[["En","in"],["aquel","that"],["tiempo","time"],["se","itself"],["dirá","shall-say"],["a","to"],["Jerusalén:","Jerusalem:"],["No","not"],["temas,","dismayed,"],["Sion;","Zion;"],["no","not"],["se","themselves"],["debiliten","yours"],["tus","your"],["manos.","hands."]]},
  {num:17,words:[["Jehová","jehovah"],["tu","your"],["Dios","God"],["está","is"],["en","in"],["medio","midst"],["de","of"],["ti:","you:"],["¡Él","he"],["es","is"],["poderoso!","mighty!"],["¡Él","he"],["salvará!","will-save!"],["Se","himself"],["regocijará","rejoice"],["por","for"],["ti","you"],["con","with"],["alegría;","joy;"],["guardará","will-keep"],["silencio","silence"],["por","for"],["su","his"],["amor;","love;"],["se","himself"],["regocijará","rejoice"],["por","for"],["ti","you"],["con","with"],["cánticos.","songs."]]},
  {num:18,words:[["Reuniré","I-will-gather"],["a","to"],["los","the"],["que","that"],["se","themselves"],["entristecían","sorrowful"],["por","for"],["las","the"],["fiestas","moons"],["señaladas;","appointed;"],["tuyos","yours"],["fueron;","they-were;"],["para","for"],["quienes","who"],["el","the"],["oprobio","reproach"],["era","was"],["una","a"],["carga.","burden."]]},
  {num:19,words:[["He aquí,","behold,"],["en","in"],["aquel","that"],["tiempo","time"],["me","me"],["ocuparé","shall-to"],["de","of"],["todos","all"],["tus","your"],["opresores;","and;"],["y","and"],["salvaré","I-will-save"],["a","to"],["la","the"],["que","that"],["cojea","limps"],["y","and"],["recogeré","I-gather"],["a","to"],["la","the"],["desterrada;","banished;"],["y","and"],["cambiaré","I-will-change"],["su","her"],["vergüenza","shame"],["en","in"],["alabanza","praise"],["y","and"],["en","in"],["renombre","renown"],["en","in"],["todo","all"],["país.","country."]]},
  {num:20,words:[["En","in"],["aquel","that"],["tiempo","time"],["yo","I"],["os","you"],["traeré;","bring;"],["en","in"],["aquel","that"],["tiempo","time"],["os","you"],["reuniré","gather"],["yo.","I."],["Pues","for"],["os","you"],["haré","I will make"],["objeto","intent"],["de","of"],["renombre","renown"],["y","and"],["de","of"],["alabanza","praise"],["entre","among"],["todos","all"],["los","the"],["pueblos","peoples"],["de","of"],["la","the"],["tierra,","earth,"],["cuando","when"],["haga","let-do"],["volver","to-return"],["a","to"],["vuestros","your"],["cautivos","captives"],["ante","before"],["vuestros","your"],["propios","own"],["ojos,","eyes,"],["dice","says"],["Jehová.","jehovah."]]},
];
renderVerseSet(v3, 'zep-ch3-verses');

})();
