(function() {
var v1 = [
  {num:1,words:[["Paulo,","Paul,"],["e","and"],["Silvano,","Silvanus,"],["e","and"],["Timóteo,","Timotheus,"],["à","to-the"],["igreja","church"],["dos","of-the"],["tessalonicenses","thessalonians"],["em","in"],["Deus,","God,"],["o","the"],["Pai,","Father,"],["e","and"],["no","in-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo:","Christ:"],["Graça","Grace"],["e","and"],["paz","peace"],["tenhais","you-have"],["de","of"],["Deus,","God,"],["nosso","our"],["Pai,","Father,"],["e","and"],["do","of-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:2,words:[["Sempre","Always"],["damos","we-give"],["graças","thanks"],["a","to"],["Deus","God"],["por","by"],["vós","you"],["todos,","all,"],["fazendo","making"],["menção","mention"],["de","of"],["vós","you"],["em","in"],["nossas","our"],["orações,","prayers,"]]},
  {num:3,words:[["Lembrando-nos","Remembering-us"],["sem","without"],["cessar","cease"],["da","of-the"],["obra","work"],["da","of-the"],["vossa","your"],["fé,","faith,"],["e","and"],["do","of-the"],["trabalho","work"],["de","of"],["caridade,","charity,"],["e","and"],["da","of-the"],["paciência","patience"],["da","of-the"],["esperança","hope"],["em","in"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["diante de","before"],["nosso","our"],["Deus","God"],["e","and"],["Pai;","Father;"]]},
  {num:4,words:[["Sabendo,","Knowing,"],["amados","beloved"],["irmãos,","brethren,"],["que","that"],["a","the"],["vossa","your"],["eleição","election"],["é","is"],["de","of"],["Deus;","God;"]]},
  {num:5,words:[["Porque","Because"],["o","the"],["nosso","our"],["evangelho","gospel"],["não","not"],["foi","was"],["a","the"],["vós","you"],["somente","only"],["em","in"],["palavras,","words,"],["mas","but"],["também","also"],["em","in"],["poder,","power,"],["e","and"],["no","in-the"],["Espírito","Spirit"],["Santo,","Holy,"],["e","and"],["em","in"],["muita","much"],["certeza;","surety;"],["bem","good"],["sabeis","you-know"],["como","as"],["fomos","we-were"],["entre","among"],["vós,","you,"],["por causa de","because-of"],["vós.","you."]]},
  {num:6,words:[["E","And"],["vós","you"],["fostes","you-were"],["feitos","acts"],["nossos","our"],["imitadores,","followers,"],["e","and"],["do","of-the"],["Senhor,","Lord,"],["recebendo","receiving"],["a","the"],["palavra","word"],["em","in"],["muita","much"],["tribulação,","tribulation,"],["com","with"],["alegria","joy"],["do","of-the"],["Espírito","Spirit"],["Santo.","Holy."]]},
  {num:7,words:[["De maneira que","so-that"],["fostes","you-were"],["exemplo","example"],["para","for"],["todos","all"],["os","the"],["fiéis","faithful"],["na","in-the"],["Macedônia","Macedonia"],["e","and"],["Acaia.","Achaia."]]},
  {num:8,words:[["Porque","Because"],["por","by"],["vós","you"],["soou","sounded"],["a","the"],["palavra","word"],["do","of-the"],["Senhor,","Lord,"],["não","not"],["somente","only"],["na","in-the"],["Macedônia","Macedonia"],["e","and"],["Acaia,","Achaia,"],["mas","but"],["também","also"],["a","the"],["vossa","your"],["fé","faith"],["para","for"],["com","with"],["Deus","God"],["se","himself"],["espalhou","disseminated"],["por","by"],["todos","all"],["os","the"],["lugares,","places,"],["de tal maneira que","insomuch-that"],["já","already"],["dela","of-her"],["não","not"],["temos","we-have"],["necessidade","need"],["de","of"],["falar","to-speak"],["coisa","thing"],["alguma;","some;"]]},
  {num:9,words:[["Porque","Because"],["eles","they"],["mesmos","themselves"],["anunciam","they-advertise"],["de","of"],["nós","we"],["qual","which"],["a","the"],["entrada","entrance"],["que","that"],["tivemos","we-had"],["para","for"],["convosco,","with-you,"],["e","and"],["como","as"],["dos","of-the"],["ídolos","idols"],["vos","you"],["convertestes","you-converted"],["a","to"],["Deus,","God,"],["para","to"],["servir","to-serve"],["ao","to-the"],["Deus","God"],["vivo","alive"],["e","and"],["verdadeiro,","true,"]]},
  {num:10,words:[["E","And"],["para","to"],["esperar","to-abide"],["dos","of-the"],["céus","heaven"],["seu","his"],["Filho,","Son,"],["a","to"],["quem","who"],["ressuscitou","risen"],["dos","of-the"],["mortos,","dead,"],["a saber,","namely"],["Jesus,","Jesus,"],["que","that"],["nos","us"],["livra","deliver"],["da","of-the"],["ira","anger"],["futura.","future."]]}
];
var v2 = [
  {num:1,words:[["Porque","Because"],["vós","you"],["mesmos,","yourselves,"],["irmãos,","brethren,"],["bem","good"],["sabeis","you-know"],["que","that"],["a","the"],["nossa","our"],["entrada","entrance"],["para","for"],["convosco","with-you"],["não","not"],["foi","was"],["vã;","vain;"]]},
  {num:2,words:[["Antes,","Before,"],["havendo","having"],["primeiro","first"],["padecido,","abode,"],["e","and"],["sido","been"],["agravados","appeal"],["em","in"],["Filipos,","Philippi,"],["como","as"],["sabeis,","you-know,"],["tivemos","we-had"],["ousadia","boldness"],["em","in"],["nosso","our"],["Deus,","God,"],["para","for"],["vos","you"],["falar","to-speak"],["o","the"],["evangelho","gospel"],["de","of"],["Deus","God"],["com","with"],["grande","great"],["combate.","action."]]},
  {num:3,words:[["Porque","Because"],["a","the"],["nossa","our"],["exortação","exhortation"],["não","not"],["procede","acts"],["de","of"],["erro,","error,"],["nem","nor"],["de","of"],["imundície,","filthiness,"],["nem","nor"],["de","of"],["fraudulência;","guile;"]]},
  {num:4,words:[["Mas,","But,"],["como","as"],["fomos","we-were"],["aprovados","approved"],["por","by"],["Deus","God"],["para que","that"],["o","the"],["evangelho","gospel"],["nos","us"],["fosse","was"],["confiado,","trusted,"],["assim","thus"],["falamos,","we-speak,"],["não","not"],["como","as"],["para","to"],["comprazer","porcius"],["aos","to-the"],["homens,","men,"],["mas","but"],["a","to"],["Deus,","God,"],["que","that"],["põe","places"],["à","to-the"],["prova","test"],["o","the"],["nosso","our"],["coração.","heart."]]},
  {num:5,words:[["Porque,","Because,"],["como","as"],["bem","good"],["sabeis,","you-know,"],["nunca","never"],["usamos","we-costly"],["de","of"],["palavras","words"],["lisonjeiras,","flattering,"],["nem","nor"],["de","of"],["pretexto","widows'"],["de","of"],["avareza;","covetousness;"],["Deus","God"],["é","is"],["testemunha;","witness;"]]},
  {num:6,words:[["Não","Not"],["buscando","seeking"],["a","the"],["glória","glory"],["dos","of-the"],["homens,","men,"],["nem","nor"],["de","of"],["vós,","you,"],["nem","nor"],["de","of"],["outros,","others,"],["ainda que","although"],["pudéssemos,","we-could,"],["como","as"],["apóstolos","apostles"],["de","of"],["Cristo,","Christ,"],["ser-vos","be-you"],["pesados;","chargeable;"]]},
  {num:7,words:[["Antes,","Before,"],["fomos","we-were"],["brandos","dainty"],["entre","among"],["vós,","you,"],["como","as"],["a","to"],["ama","love"],["que","that"],["cria","believed"],["seus","her"],["filhos.","children."]]},
  {num:8,words:[["Assim","Thus"],["nós,","we,"],["estando-vos","being-you"],["tão","so"],["afeiçoados,","affectionately,"],["de","of"],["boa","good"],["vontade","will"],["quiséramos","we-had-willed"],["comunicar-vos","to-advise-you"],["não","not"],["somente","only"],["o","the"],["evangelho","gospel"],["de","of"],["Deus,","God,"],["mas","but"],["ainda","yet"],["a","the"],["nossa","our"],["própria","own"],["alma;","soul;"],["porquanto","because"],["nos","us"],["éreis","you-were"],["muito","much"],["queridos.","dear."]]},
  {num:9,words:[["Porque","Because"],["bem","good"],["vos","you"],["lembrais,","you-remember,"],["irmãos,","brethren,"],["do","of-the"],["nosso","our"],["trabalho","work"],["e","and"],["fadiga;","stress;"],["pois,","for,"],["trabalhando","laboring"],["noite","night"],["e","and"],["dia,","day,"],["vos","you"],["pregamos","we-preach"],["o","the"],["evangelho","gospel"],["de","of"],["Deus,","God,"],["para","for"],["não","not"],["sermos","to-be"],["pesados","chargeable"],["a","to"],["cada","every"],["um","a"],["de","of"],["vós.","you."]]},
  {num:10,words:[["Vós","You"],["e","and"],["Deus","God"],["sois","you-are"],["testemunhas","testimony"],["de","of"],["quão","how"],["santa,","holy,"],["e","and"],["justa,","fair,"],["e","and"],["irrepreensívelmente","holily"],["nos","us"],["houvemos","we-had"],["para","for"],["convosco,","with-you,"],["os","the"],["que","that"],["crestes.","you-believed."]]},
  {num:11,words:[["Assim como","even-as"],["bem","good"],["sabeis","you-know"],["que","that"],["exortávamos","we-exhorted"],["e","and"],["consolávamos","we-comforted"],["a","to"],["cada","every"],["um","a"],["de","of"],["vós,","you,"],["como","as"],["o","the"],["pai","father"],["a","to"],["seus","his"],["filhos,","children,"]]},
  {num:12,words:[["Para que","that"],["vos","you"],["conduzísseis","you-led"],["dignamente","acceptationly"],["para","for"],["com","with"],["Deus,","God,"],["que","that"],["vos","you"],["chama","flame"],["para","for"],["o","the"],["seu","his"],["reino","kingdom"],["e","and"],["glória.","glory."]]},
  {num:13,words:[["Pelo","By-the"],["que","that"],["também","also"],["damos,","we-give,"],["sem","without"],["cessar,","cease,"],["graças","thanks"],["a","to"],["Deus,","God,"],["porque","because"],["havendo","having"],["recebido","received"],["de","of"],["nós","we"],["a","the"],["palavra","word"],["da","of-the"],["pregação","preaching"],["de","of"],["Deus,","God,"],["a","it"],["recebestes,","you-received,"],["não","not"],["como","as"],["palavra","word"],["de","of"],["homens,","men,"],["mas","but"],["(segundo","(according-to"],["é,","is,"],["na","in-the"],["verdade)","truth)"],["como","as"],["palavra","word"],["de","of"],["Deus,","God,"],["a","the"],["qual","which"],["também","also"],["opera","work"],["em","in"],["vós,","you,"],["os","the"],["que","that"],["crestes.","you-believed."]]},
  {num:14,words:[["Porque","Because"],["vós,","you,"],["irmãos,","brethren,"],["fostes","you-were"],["feitos","acts"],["imitadores","followers"],["das","of-the"],["igrejas","churches"],["de","of"],["Deus","God"],["que","that"],["estão","they-are"],["na","in-the"],["Judeia,","Judaea,"],["em","in"],["Jesus","Jesus"],["Cristo;","Christ;"],["porquanto","because"],["também","also"],["padecestes","you-abode"],["de","of"],["vossos","your"],["próprios","own"],["concidadãos","fellowcitizens"],["as","the"],["mesmas","same"],["coisas,","things,"],["como","as"],["eles","they"],["também,","also,"],["dos","of-the"],["judeus;","Jews;"]]},
  {num:15,words:[["Os","The"],["quais","what"],["também","also"],["mataram","they-slew"],["o","the"],["Senhor","Lord"],["Jesus","Jesus"],["e","and"],["seus","their"],["próprios","own"],["profetas,","prophets,"],["e","and"],["nos","us"],["têm","they-have"],["perseguido;","persecuted;"],["e","and"],["não","not"],["agradam","they-please"],["a","to"],["Deus,","God,"],["e","and"],["são","they-are"],["contrários","contrary"],["a","to"],["todos","all"],["os","the"],["homens;","men;"]]},
  {num:16,words:[["E","And"],["nos","us"],["impedem","they-oppose"],["de","of"],["falar","to-speak"],["aos","to-the"],["gentios","gentiles"],["para que","that"],["possam","they-can"],["salvar-se,","to-save-himself,"],["a fim de","in-order-to"],["encherem","to-fill"],["sempre","always"],["a","the"],["medida","measure"],["de","of"],["seus","their"],["pecados;","sins;"],["porque","because"],["a","to"],["ira","anger"],["de","of"],["Deus","God"],["caiu","fell"],["sobre","upon"],["eles","they"],["até","until"],["o","the"],["fim.","end."]]},
  {num:17,words:[["Nós,","We,"],["porém,","but,"],["irmãos,","brethren,"],["sendo","being"],["privados","close"],["de","of"],["vós","you"],["por","by"],["um","a"],["momento","moment"],["de","of"],["tempo,","time,"],["de","of"],["vista,","picture,"],["mas","but"],["não","not"],["do","of-the"],["coração,","heart,"],["tanto mais","the-more"],["procuramos","we-seek"],["com","with"],["grande","great"],["desejo","desire"],["ver","see"],["o","the"],["vosso","your"],["rosto.","face."]]},
  {num:18,words:[["Pelo","By-the"],["que","that"],["bem","good"],["quisemos","we-willed"],["uma","a"],["e","and"],["outra vez","again"],["ir","go"],["ter","have"],["convosco,","with-you,"],["pelo","by-the"],["menos","less"],["eu,","I,"],["Paulo,","Paul,"],["mas","but"],["Satanás","Satan"],["no-lo","to-us-it"],["impediu.","opposed."]]},
  {num:19,words:[["Porque,","Because,"],["qual","which"],["é","is"],["a","the"],["nossa","our"],["esperança,","hope,"],["ou","or"],["alegria,","joy,"],["ou","or"],["coroa","crown"],["de","of"],["glória?","glory?"],["Porventura","Perchance"],["não","not"],["o","him"],["sois","you-are"],["vós","you"],["também","also"],["diante de","before"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["em","in"],["sua","his"],["vinda?","coming?"]]},
  {num:20,words:[["Porque","Because"],["vós","you"],["sois","you-are"],["a","the"],["nossa","our"],["glória","glory"],["e","and"],["alegria.","joy."]]}
];
var v3 = [
  {num:1,words:[["Pelo","By-the"],["que,","that,"],["não","not"],["podendo","canning"],["esperar","to-abide"],["mais,","more,"],["de","of"],["bom","good"],["grado","I-harrow"],["quisemos","we-willed"],["deixar-nos","leave-us"],["ficar","remain"],["sós","exclusively"],["em","in"],["Atenas;","Athens;"]]},
  {num:2,words:[["E","And"],["enviamos","we-send"],["Timóteo,","Timotheus,"],["nosso","our"],["irmão,","brother,"],["e","and"],["ministro","minister"],["de","of"],["Deus,","God,"],["e","and"],["nosso","our"],["cooperador","fellowlabourer"],["no","in-the"],["evangelho","gospel"],["de","of"],["Cristo,","Christ,"],["para","for"],["vos","you"],["confortar","to-comfort"],["e","and"],["vos","you"],["exortar","exhort"],["acerca","concerning"],["da","of-the"],["vossa","your"],["fé;","faith;"]]},
  {num:3,words:[["Para que","that"],["ninguém","none"],["se","himself"],["comova","moves"],["por","by"],["essas","those"],["tribulações;","tribulation;"],["porque","because"],["vós","you"],["mesmos","yourselves"],["sabeis","you-know"],["que","that"],["para","for"],["isso","that"],["fomos","we-were"],["ordenados.","ordained."]]},
  {num:4,words:[["Pois,","For,"],["estando","being"],["ainda","yet"],["convosco,","with-you,"],["vos","you"],["predizíamos","we-forecasted"],["que","that"],["haveríamos","we-should-have"],["de","of"],["ser","be"],["afligidos,","afflicted,"],["como","as"],["também","also"],["sucedeu,","happened,"],["e","and"],["vós","you"],["o","it"],["sabeis.","you-know."]]},
  {num:5,words:[["Portanto,","Therefore,"],["não","not"],["podendo","canning"],["eu","I"],["também","also"],["esperar","to-abide"],["mais,","more,"],["mandei","I-commanded"],["saber","know"],["da","of-the"],["vossa","your"],["fé,","faith,"],["temendo","fearing"],["que","that"],["o","the"],["tentador","temptser"],["vos","you"],["tentasse,","tempted,"],["e","and"],["o","the"],["nosso","our"],["trabalho","work"],["viesse","came"],["a","to"],["ser","be"],["inútil.","needless."]]},
  {num:6,words:[["Vindo,","Coming,"],["porém,","but,"],["agora","now"],["Timóteo","Timotheus"],["de","of"],["vós","you"],["para","for"],["nós,","we,"],["e","and"],["trazendo-nos","bringing-us"],["boas","tidings"],["novas","tidings"],["acerca","concerning"],["da","of-the"],["vossa","your"],["fé","faith"],["e","and"],["caridade,","charity,"],["e","and"],["de","of"],["como","as"],["sempre","always"],["tendes","you-have"],["boa","good"],["lembrança","remembrance"],["de","of"],["nós,","we,"],["desejando","desiring"],["muito","much"],["ver-nos,","see-us,"],["como","as"],["nós","we"],["também,","also,"],["a","to"],["vós;","you;"]]},
  {num:7,words:[["Pelo","By-the"],["que,","that,"],["irmãos,","brethren,"],["nós","we"],["ficamos","we-remain"],["consolados","comforted"],["acerca de","concerning"],["vós","you"],["em","in"],["toda","all"],["a","the"],["nossa","our"],["aflição","affliction"],["e","and"],["necessidade,","need,"],["pela","by-the"],["vossa","your"],["fé,","faith,"]]},
  {num:8,words:[["Porque","Because"],["agora","now"],["vivemos,","we-live,"],["se","if"],["estais","you-are"],["firmes","you-firm"],["no","in-the"],["Senhor.","Lord."]]},
  {num:9,words:[["Porque,","Because,"],["que","that"],["ação","act"],["de","of"],["graças","thanks"],["poderemos","we-can"],["dar","give"],["a","to"],["Deus","God"],["por","by"],["vós,","you,"],["por toda a","throughout"],["alegria","joy"],["com","with"],["que","that"],["nos","us"],["regozijamos","we-rejoice"],["por","by"],["vossa","your"],["causa","sake"],["diante","before"],["do","of-the"],["nosso","our"],["Deus,","God,"]]},
  {num:10,words:[["Orando","Praying"],["abundantemente","abundantly"],["dia","day"],["e","and"],["noite,","night,"],["para que","that"],["possamos","we-can"],["ver","see"],["o","the"],["vosso","your"],["rosto,","face,"],["e","and"],["supramos","let-us-provide"],["o","the"],["que","that"],["falta","lack"],["à","to-the"],["vossa","your"],["fé?","faith?"]]},
  {num:11,words:[["Ora,","Now,"],["o","the"],["mesmo","same"],["nosso","our"],["Deus","God"],["e","and"],["Pai,","Father,"],["e","and"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["encaminhem","they-direct"],["a","the"],["nossa","our"],["viagem","journey"],["para","for"],["vós.","you."]]},
  {num:12,words:[["E","And"],["o","the"],["Senhor","Lord"],["vos","you"],["aumente,","increases,"],["e","and"],["faça","makes"],["crescer","to-grow"],["em","in"],["caridade","charity"],["uns","some"],["para","for"],["com","with"],["os","the"],["outros,","others,"],["e","and"],["para","for"],["com","with"],["todos,","all,"],["como","as"],["também","also"],["nós,","we,"],["para","for"],["convosco;","with-you;"]]},
  {num:13,words:[["Para","To"],["confortar","to-comfort"],["o","the"],["vosso","your"],["coração,","heart,"],["para que","that"],["sejais","you-are"],["irrepreensíveis","blameless"],["em","in"],["santificação","sanctification"],["diante de","before"],["nosso","our"],["Deus","God"],["e","and"],["Pai,","Father,"],["na","in-the"],["vinda","coming"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["com","with"],["todos","all"],["os","the"],["seus","his"],["santos.","saints."]]}
];
var v4 = [
  {num:1,words:[["Assim que,","as-soon-as"],["irmãos,","brethren,"],["no","in-the"],["demais","moreover"],["vos","you"],["rogamos","furthermore"],["e","and"],["exortamos","we-exhort"],["no","in-the"],["Senhor","Lord"],["Jesus","Jesus"],["que,","that,"],["assim como","even-as"],["recebestes","you-received"],["de","of"],["nós,","we,"],["como","as"],["vos","you"],["convenha","befits"],["andar","to-walk"],["e","and"],["agradar","please"],["a","to"],["Deus,","God,"],["assim","thus"],["nisso","in-that"],["possais","you-can"],["progredir","to-advance"],["cada","every"],["vez","time"],["mais.","more."]]},
  {num:2,words:[["Porque","Because"],["vós","you"],["bem","good"],["sabeis","you-know"],["quais","what"],["mandamentos","commandments"],["nós","we"],["vos","you"],["temos","we-have"],["dado","given"],["pelo","by-the"],["Senhor","Lord"],["Jesus.","Jesus."]]},
  {num:3,words:[["Porque","Because"],["esta","this"],["é","is"],["a","the"],["vontade","will"],["de","of"],["Deus,","God,"],["a","the"],["vossa","your"],["santificação:","sanctification:"],["que","that"],["vos","you"],["abstenhais","you-refrain"],["da","of-the"],["fornicação;","fornication;"]]},
  {num:4,words:[["Que","That"],["cada","every"],["um","a"],["de","of"],["vós","you"],["saiba","knows"],["possuir","to-possess"],["o","the"],["seu","his"],["vaso","vessel"],["em","in"],["santificação","sanctification"],["e","and"],["honra;","honour;"]]},
  {num:5,words:[["Não","Not"],["em","in"],["paixão","flame"],["de","of"],["concupiscência,","lust,"],["como","as"],["os","the"],["gentios,","gentiles,"],["que","that"],["não","not"],["conhecem","they-know"],["a","to"],["Deus.","God."]]},
  {num:6,words:[["Ninguém","None"],["oprima","forewarned"],["nem","nor"],["engane","deceive"],["seu","his"],["irmão","brother"],["em","in"],["assunto","matter"],["algum,","some,"],["porque","because"],["o","the"],["Senhor","Lord"],["é","is"],["vingador","avenger"],["de","of"],["todas","all"],["essas","those"],["coisas,","things,"],["como","as"],["também","also"],["já","already"],["dantes","of-ahead"],["vo-lo","to-you-it"],["dissemos","we-said"],["e","and"],["testificamos.","we-testify."]]},
  {num:7,words:[["Porque","Because"],["não","not"],["nos","us"],["chamou","called"],["Deus","God"],["para","for"],["a","the"],["imundície,","filthiness,"],["senão","save"],["para","for"],["a","the"],["santificação.","sanctification."]]},
  {num:8,words:[["Porque","Because"],["quem","who"],["despreza","despise"],["isso","that"],["não","not"],["despreza","despise"],["o","the"],["homem,","man,"],["mas","but"],["sim","yea"],["a","to"],["Deus,","God,"],["o","the"],["qual","which"],["nos","us"],["deu","gave"],["também","also"],["o","the"],["seu","his"],["Espírito","Spirit"],["Santo.","Holy."]]},
  {num:9,words:[["Quanto,","As,"],["porém,","but,"],["à","to-the"],["caridade","charity"],["fraternal,","brotherly,"],["não","not"],["necessitais","you-need"],["de","of"],["que","that"],["vos","you"],["escreva,","writes,"],["porque","because"],["já","already"],["vós","you"],["mesmos","yourselves"],["estais","you-are"],["instruídos","learned"],["por","by"],["Deus","God"],["que","that"],["vos","you"],["ameis","you-mammon"],["uns","some"],["aos","to-the"],["outros.","others."]]},
  {num:10,words:[["Porque","Because"],["também","also"],["já","already"],["assim","thus"],["o","it"],["fazeis,","you-make,"],["para","for"],["com","with"],["todos","all"],["os","the"],["irmãos","brethren"],["que","that"],["estão","they-are"],["por toda a","throughout"],["Macedônia.","Macedonia."],["Exortamo-vos,","Exhort-you,"],["porém,","but,"],["irmãos,","brethren,"],["a","to"],["que","that"],["ainda","yet"],["nisso","in-that"],["possais","you-can"],["progredir","to-advance"],["cada","every"],["vez","time"],["mais,","more,"]]},
  {num:11,words:[["E","And"],["que","that"],["procureis","you-seek"],["viver","to-live"],["quietos,","resting,"],["e","and"],["tratar","to-attend"],["dos","of-the"],["vossos","your"],["próprios","own"],["negócios,","affairs,"],["e","and"],["trabalhar","to-labor"],["com","with"],["vossas","your"],["próprias","own"],["mãos,","hands,"],["como","as"],["já","already"],["vo-lo","to-you-it"],["mandamos;","we-command;"]]},
  {num:12,words:[["Para que","that"],["andeis","you-walk"],["honestamente","honestly"],["para","for"],["com","with"],["os","the"],["que","that"],["estão","they-are"],["de","of"],["fora,","outside,"],["e","and"],["não","not"],["necessiteis","you-need"],["de","of"],["coisa","thing"],["alguma.","some."]]},
  {num:13,words:[["Não","Not"],["quero,","I-will,"],["porém,","but,"],["irmãos,","brethren,"],["que","that"],["sejais","you-are"],["ignorantes","ignorant"],["acerca","concerning"],["dos","of-the"],["que","that"],["já","already"],["dormem,","they-sleep,"],["para que","that"],["não","not"],["vos","you"],["entristeçais,","stilled,"],["como","as"],["também","also"],["os","the"],["demais,","moreover,"],["que","that"],["não","not"],["têm","they-have"],["esperança.","hope."]]},
  {num:14,words:[["Porque,","Because,"],["se","if"],["cremos","we-believe"],["que","that"],["Jesus","Jesus"],["morreu","died"],["e","and"],["ressuscitou,","risen,"],["assim","thus"],["também","also"],["aos","to-the"],["que","that"],["em","in"],["Jesus","Jesus"],["dormem,","they-sleep,"],["Deus","God"],["os","them"],["tornará","will-become"],["a","to"],["trazer","to-bring"],["com","with"],["ele.","he."]]},
  {num:15,words:[["Dizemo-vos,","Say-you,"],["portanto,","therefore,"],["isto","this"],["pela","by-the"],["palavra","word"],["do","of-the"],["Senhor:","Lord:"],["que","that"],["nós,","we,"],["os","the"],["que","that"],["ficarmos","to-remain"],["vivos","alive"],["para","for"],["a","the"],["vinda","coming"],["do","of-the"],["Senhor,","Lord,"],["não","not"],["precederemos","we-will-precede"],["os","the"],["que","that"],["dormem.","they-sleep."]]},
  {num:16,words:[["Porque","Because"],["o","the"],["mesmo","same"],["Senhor","Lord"],["descerá","will-descend"],["do","of-the"],["céu","heaven"],["com","with"],["um","a"],["brado,","I-scream,"],["e","and"],["com","with"],["voz","voice"],["de","of"],["arcanjo,","archangel,"],["e","and"],["com","with"],["a","the"],["trombeta","trumpet"],["de","of"],["Deus;","God;"],["e","and"],["os","the"],["que","that"],["morreram","they-died"],["em","in"],["Cristo","Christ"],["ressuscitarão","they-deceased"],["primeiro.","first."]]},
  {num:17,words:[["Depois","Afterwards"],["nós,","we,"],["os","the"],["que","that"],["ficarmos","to-remain"],["vivos,","alive,"],["seremos","we-will-be"],["arrebatados","carried-away"],["juntamente","together"],["com","with"],["eles","them"],["nas","in-the"],["nuvens,","clouds,"],["para","to"],["encontrar","find"],["o","the"],["Senhor","Lord"],["nos","in-the"],["ares,","Ares,"],["e","and"],["assim","thus"],["estaremos","we-will-be"],["sempre","always"],["com","with"],["o","the"],["Senhor.","Lord."]]},
  {num:18,words:[["Portanto,","Therefore,"],["consolai-vos","comfort-you"],["uns","some"],["aos","to-the"],["outros","other"],["com","with"],["essas","those"],["palavras.","words."]]}
];
var v5 = [
  {num:1,words:[["Porém,","But,"],["irmãos,","brethren,"],["acerca","concerning"],["dos","of-the"],["tempos","times"],["e","and"],["das","of-the"],["estações,","seasons,"],["não","not"],["necessitais","you-need"],["de","of"],["que","that"],["se","itself"],["vos","you"],["escreva;","writes;"]]},
  {num:2,words:[["Porque","Because"],["vós","you"],["mesmos","yourselves"],["sabeis","you-know"],["muito","much"],["bem","good"],["que","that"],["o","the"],["dia","day"],["do","of-the"],["Senhor","Lord"],["virá","will-come"],["como","as"],["o","the"],["ladrão","thief"],["de","of"],["noite;","night;"]]},
  {num:3,words:[["Pois,","For,"],["quando","when"],["disserem:","they-will-say:"],["Há","There-is"],["paz","peace"],["e","and"],["segurança;","surety;"],["então","then"],["lhes","to-them"],["sobrevirá","will-ensue"],["repentina","abrupt"],["destruição,","destruction,"],["como","as"],["as","the"],["dores","sorrows"],["de","of"],["parto","travail"],["àquela","to-that"],["que","that"],["está","is"],["grávida;","espoused;"],["e","and"],["de modo algum","in-no-wise"],["escaparão.","they-will-escape."]]},
  {num:4,words:[["Mas","But"],["vós,","you,"],["irmãos,","brethren,"],["já","already"],["não","not"],["estais","you-are"],["em","in"],["trevas,","darkness,"],["para que","that"],["aquele","that"],["dia","day"],["vos","you"],["surpreenda","surprises"],["como","as"],["um","a"],["ladrão.","thief."]]},
  {num:5,words:[["Porque","Because"],["todos","all"],["vós","you"],["sois","you-are"],["filhos","children"],["da","of-the"],["luz","light"],["e","and"],["filhos","children"],["do","of-the"],["dia;","day;"],["nós","we"],["não","not"],["somos","we-are"],["da","of-the"],["noite","night"],["nem","nor"],["das","of-the"],["trevas.","darkness."]]},
  {num:6,words:[["Não","Not"],["durmamos,","we-sleep,"],["pois,","for,"],["como","as"],["os","the"],["demais,","moreover,"],["mas","but"],["vigiemos,","let-us-guard,"],["e","and"],["sejamos","let-us-be"],["sóbrios.","sober."]]},
  {num:7,words:[["Porque","Because"],["os","the"],["que","that"],["dormem,","they-sleep,"],["dormem","they-sleep"],["de","of"],["noite,","night,"],["e","and"],["os","the"],["que","that"],["se","themselves"],["embebedam,","folden,"],["embebedam-se","folden-themselves"],["de","of"],["noite.","night."]]},
  {num:8,words:[["Mas","But"],["nós,","we,"],["que","that"],["somos","we-are"],["do","of-the"],["dia,","day,"],["sejamos","let-us-be"],["sóbrios,","sober,"],["vestindo-nos","clothing-us"],["da","of-the"],["couraça","helmet"],["da","of-the"],["fé","faith"],["e","and"],["da","of-the"],["caridade,","charity,"],["e","and"],["tendo","having"],["por","by"],["capacete","helmet"],["a","the"],["esperança","hope"],["da","of-the"],["salvação.","salvation."]]},
  {num:9,words:[["Porque","Because"],["Deus","God"],["não","not"],["nos","us"],["designou","assigned"],["para","for"],["a","to"],["ira,","anger,"],["mas","but"],["para","for"],["a","the"],["aquisição","acquirement"],["da","of-the"],["salvação,","salvation,"],["por","by"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"]]},
  {num:10,words:[["O","The"],["qual","which"],["morreu","died"],["por","by"],["nós,","we,"],["para que,","that"],["quer","will"],["vigiemos,","we-guard,"],["quer","will"],["durmamos,","we-sleep,"],["vivamos","let-us-live"],["juntamente","together"],["com","with"],["ele.","he."]]},
  {num:11,words:[["Pelo","By-the"],["que","that"],["exortai-vos","exhort-you"],["uns","some"],["aos","to-the"],["outros,","others,"],["e","and"],["edificai-vos","build-you"],["uns","some"],["aos","to-the"],["outros,","others,"],["como","as"],["também","also"],["o","him"],["fazeis.","you-make."]]},
  {num:12,words:[["E","And"],["rogamo-vos,","feebleminded,"],["irmãos,","brethren,"],["que","that"],["reconheçais","you-acknowledge"],["os","the"],["que","that"],["trabalham","they-labor"],["entre","among"],["vós","you"],["e","and"],["que","that"],["vos","you"],["presidem","they-preside"],["no","in-the"],["Senhor,","Lord,"],["e","and"],["vos","you"],["admoestam;","they-admonish;"]]},
  {num:13,words:[["E","And"],["tende-os","have-them"],["em","in"],["grande","great"],["estima","esteems"],["e","and"],["amor,","love,"],["por causa da","because-of"],["sua","their"],["obra.","work."],["Tende","Have"],["paz","peace"],["entre","among"],["vós.","you."]]},
  {num:14,words:[["Rogamo-vos","Feebleminded"],["também,","also,"],["irmãos,","brethren,"],["que","that"],["admoesteis","you-admonish"],["os","the"],["desordeiros,","feebleminded,"],["consoleis","you-comfort"],["os","the"],["de","of"],["pouco","few"],["ânimo,","courage,"],["sustenteis","you-laziness"],["os","the"],["fracos,","weak,"],["e","and"],["sejais","you-are"],["pacientes","patient"],["para","for"],["com","with"],["todos.","all."]]},
  {num:15,words:[["Vede","See"],["que","that"],["ninguém","none"],["dê","gives"],["a","to"],["outrem","another"],["mal","evil"],["por","by"],["mal,","evil,"],["mas","but"],["segui","I-followed"],["sempre","always"],["o","the"],["bem,","good,"],["assim","thus"],["uns","some"],["para","for"],["com","with"],["os","the"],["outros,","others,"],["como","as"],["para","for"],["com","with"],["todos.","all."]]},
  {num:16,words:[["Regozijai-vos","Rejoice-you"],["sempre.","always."]]},
  {num:17,words:[["Orai","Pray"],["sem","without"],["cessar.","cease."]]},
  {num:18,words:[["Em","In"],["tudo","all"],["dai","give"],["graças,","thanks,"],["porque","because"],["esta","this"],["é","is"],["a","the"],["vontade","will"],["de","of"],["Deus","God"],["em","in"],["Cristo","Christ"],["Jesus","Jesus"],["para","for"],["convosco.","with-you."]]},
  {num:19,words:[["Não","Not"],["apagueis","you-extinguish"],["o","the"],["Espírito.","Spirit."]]},
  {num:20,words:[["Não","Not"],["desprezeis","you-mammon"],["as","the"],["profecias.","prophecies."]]},
  {num:21,words:[["Examinai","Examine"],["todas","all"],["as","the"],["coisas;","things;"],["retende","restrain"],["o","the"],["bem.","good."]]},
  {num:22,words:[["Abstende-vos","Refrain-you"],["de","of"],["toda","all"],["a","the"],["aparência","appearance"],["do","of-the"],["mal.","evil."]]},
  {num:23,words:[["E","And"],["o","the"],["mesmo","same"],["Deus","God"],["de","of"],["paz","peace"],["vos","you"],["santifique","sanctifies"],["em","in"],["tudo;","all;"],["e","and"],["todo","all"],["o","the"],["vosso","your"],["sincero","sincere"],["espírito,","spirit,"],["e","and"],["alma,","soul,"],["e","and"],["corpo","body"],["sejam","they-are"],["conservados","conserved"],["irrepreensíveis","blameless"],["para","for"],["a","the"],["vinda","coming"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:24,words:[["Fiel","Faithful"],["é","is"],["o","the"],["que","that"],["vos","you"],["chama,","flame,"],["o","the"],["qual","which"],["também","also"],["o","it"],["fará.","will-make."]]},
  {num:25,words:[["Irmãos,","Brethren,"],["orai","pray"],["por","by"],["nós.","we."]]},
  {num:26,words:[["Saudai","Greet"],["todos","all"],["os","the"],["irmãos","brethren"],["com","with"],["ósculo","ósculo"],["santo.","holy."]]},
  {num:27,words:[["Pelo","By-the"],["Senhor","Lord"],["vos","you"],["conjuro","I-conspire"],["que","that"],["esta","this"],["epístola","epistle"],["se","himself"],["leia","reads"],["a","to"],["todos","all"],["os","the"],["santos","holy"],["irmãos.","brethren."]]},
  {num:28,words:[["A","The"],["graça","grace"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["seja","is"],["convosco.","with-you."],["Amém.","Amen."]]}
];
renderVerseSet(v1, '1th-ch1-verses');
renderVerseSet(v2, '1th-ch2-verses');
renderVerseSet(v3, '1th-ch3-verses');
renderVerseSet(v4, '1th-ch4-verses');
renderVerseSet(v5, '1th-ch5-verses');
})();
