(function() {
var v1 = [
  {num:1,words:[["O","The"],["ancião","ancient"],["à","to-the"],["senhora","lady"],["eleita,","lady,"],["e","and"],["a","to"],["seus","his"],["filhos,","children,"],["os","the"],["quais","what"],["eu","I"],["amo","boss"],["na","in-the"],["verdade,","truth,"],["e","and"],["não","no"],["somente","only"],["eu,","I,"],["mas","but"],["também","also"],["todos","all"],["os","the"],["que","that"],["conhecem","they-know"],["a","to"],["verdade,","truth,"]]},
  {num:2,words:[["Por","By"],["causa","sake"],["da","of-the"],["verdade","truth"],["que","that"],["está","is"],["em","in"],["nós","we"],["e","and"],["para sempre","for-ever"],["estará","will-be"],["conosco:","with-us:"]]},
  {num:3,words:[["Graça,","Grace,"],["misericórdia,","mercy,"],["paz,","peace,"],["da","of-the"],["parte","part"],["de","of"],["Deus","God"],["Pai,","Father,"],["e","and"],["do","of-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["o","the"],["Filho","Son"],["do","of-the"],["Pai,","Father,"],["seja","is"],["convosco","with-you"],["em verdade","verily"],["e","and"],["amor.","love."]]},
  {num:4,words:[["Muito","Much"],["me","me"],["alegrei","I-gladdened"],["por","by"],["ter","have"],["encontrado","I-should-encounter"],["dentre","from"],["teus","your"],["filhos","children"],["alguns","some"],["que","that"],["andam","walk"],["na","in-the"],["verdade,","truth,"],["assim como","even-as"],["recebemos","we-receive"],["o","the"],["mandamento","commandment"],["do","of-the"],["Pai.","Father."]]},
  {num:5,words:[["E","And"],["agora,","now,"],["senhora,","lady,"],["rogo-te,","pray,"],["não","no"],["como","as"],["escrevendo-te","I-write-you"],["um","a"],["novo","new"],["mandamento,","commandment,"],["mas","but"],["aquele","that ... over there"],["que","that"],["desde o","beginning"],["princípio","beginning"],["tivemos:","we-had:"],["que","that"],["nos","us"],["amemos","lady"],["uns","some"],["aos","to-the"],["outros.","another."]]},
  {num:6,words:[["E","And"],["isto é","that-is"],["amor:","love:"],["que","that"],["andemos","we-walk"],["segundo","according-to"],["os","the"],["seus","his"],["mandamentos.","commandments."],["Este","This"],["é","is"],["o","the"],["mandamento,","commandment,"],["como","as"],["já","already"],["desde o","beginning"],["princípio","beginning"],["ouvistes:","you-heard:"],["que","that"],["nele","in-him"],["andeis.","you-walk."]]},
  {num:7,words:[["Porque","Because"],["já","already"],["muitos","many"],["enganadores","deceivers"],["entraram","entered"],["no","in-the"],["mundo,","world,"],["os","the"],["quais","what"],["não","no"],["confessam","they-confess"],["que","that"],["Jesus","Jesus"],["Cristo","Christ"],["veio","came"],["em","in"],["carne.","flesh."],["Esse","That ... over there"],["tal","same"],["é","is"],["o","the"],["enganador","deceiver"],["e","and"],["o","the"],["anticristo.","antichrist."]]},
  {num:8,words:[["Acautelai-vos,","Beware,"],["para que","that"],["não","no"],["percamos","we-lose"],["aquilo","that"],["pelo","by-the"],["qual","which"],["trabalhamos,","we-labor,"],["antes","before"],["recebamos","we-receive"],["o","the"],["inteiro","entire"],["galardão.","reward."]]},
  {num:9,words:[["Todo","Every"],["aquele","that ... over there"],["que","that"],["transgride,","transgresseth,"],["e","and"],["não","no"],["persevera","continueth"],["na","in-the"],["doutrina","doctrine"],["de","of"],["Cristo,","Christ,"],["não","no"],["tem","has"],["Deus;","God;"],["quem","who"],["persevera","continueth"],["na","in-the"],["doutrina","doctrine"],["de","of"],["Cristo,","Christ,"],["esse","that ... over there"],["tem","has"],["tanto","both"],["o","the"],["Pai","Father"],["como","as"],["o","the"],["Filho.","Son."]]},
  {num:10,words:[["Se","If"],["alguém","any"],["vem","comes"],["ter","have"],["convosco,","with-you,"],["e","and"],["não","no"],["traz","bringeth"],["essa","that ... over there"],["doutrina,","doctrine,"],["não","no"],["o","the"],["recebais","you-receive"],["em","in"],["casa,","house,"],["nem","nor"],["tampouco","neither"],["o","the"],["saudeis.","you-greet."]]},
  {num:11,words:[["Porque","Because"],["quem","who"],["o","the"],["saúda","greets"],["participa","acquaints"],["nas","in-the"],["suas","his"],["más","deeds"],["obras.","works."]]},
  {num:12,words:[["Muitas","Many"],["coisas","things"],["tenho","I-have"],["que","that"],["vos","you"],["escrever,","write,"],["porém","but"],["não","no"],["quis","willed"],["fazê-lo","reality"],["com","with"],["papel","paper"],["e","and"],["tinta;","ink;"],["mas","but"],["espero","trust"],["ir","go"],["ter","have"],["convosco","with-you"],["e","and"],["falar","speak"],["face","face"],["a","to"],["face,","face,"],["para que","that"],["a","to"],["nossa","our"],["alegria","joy"],["seja","is"],["completa.","utter."]]},
  {num:13,words:[["Saúdam-te","They-greet-you"],["os","the"],["filhos","children"],["de","of"],["tua","your"],["irmã,","sister,"],["a","to"],["eleita.","lady."],["Amém.","Amen."]]}
];
renderVerseSet(v1, '2jn-ch1-verses');
})();
