(function() {
var v1 = [
  {num:1,words:[["O","The"],["ancião","ancient"],["à","to-the"],["senhora","lady"],["eleita,","chosen,"],["e","and"],["a","to"],["seus","her"],["filhos,","children,"],["os","the"],["quais","what"],["eu","I"],["amo","I-love"],["na","in-the"],["verdade,","truth,"],["e","and"],["não","not"],["somente","only"],["eu,","I,"],["mas","but"],["também","also"],["todos","all"],["os","the"],["que","that"],["conhecem","they-know"],["a","the"],["verdade,","truth,"]]},
  {num:2,words:[["Por causa da","because-of"],["verdade","truth"],["que","that"],["está","is"],["em","in"],["nós","we"],["e","and"],["para sempre","for-ever"],["estará","will-be"],["conosco:","with-us:"]]},
  {num:3,words:[["Graça,","Grace,"],["misericórdia,","mercy,"],["paz,","peace,"],["da","of-the"],["parte","part"],["de","of"],["Deus","God"],["Pai,","Father,"],["e","and"],["do","of-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["o","the"],["Filho","Son"],["do","of-the"],["Pai,","Father,"],["seja","be"],["convosco","with-you"],["em verdade","verily"],["e","and"],["amor.","love."]]},
  {num:4,words:[["Muito","Much"],["me","me"],["alegrei","I-gladdened"],["por","by"],["ter","have"],["encontrado","found"],["dentre","from"],["teus","your"],["filhos","children"],["alguns","some"],["que","that"],["andam","they-walk"],["na","in-the"],["verdade,","truth,"],["assim como","even-as"],["recebemos","we-received"],["o","the"],["mandamento","commandment"],["do","of-the"],["Pai.","Father."]]},
  {num:5,words:[["E","And"],["agora,","now,"],["senhora,","lady,"],["rogo-te,","wretchedness-you,"],["não","not"],["como","as"],["escrevendo-te","writing-you"],["um","a"],["novo","new"],["mandamento,","commandment,"],["mas","but"],["aquele","that"],["que","that"],["desde","since"],["o","the"],["princípio","beginning"],["tivemos:","we-had:"],["que","that"],["nos","us"],["amemos","we-love"],["uns","some"],["aos","to-the"],["outros.","others."]]},
  {num:6,words:[["E","And"],["isto","this"],["é","is"],["amor:","love:"],["que","that"],["andemos","we-walk"],["segundo","according-to"],["os","the"],["seus","his"],["mandamentos.","commandments."],["Este","This"],["é","is"],["o","the"],["mandamento,","commandment,"],["como","as"],["já","already"],["desde","since"],["o","the"],["princípio","beginning"],["ouvistes:","you-heard:"],["que","that"],["nele","in-him"],["andeis.","you-walk."]]},
  {num:7,words:[["Porque","Because"],["já","already"],["muitos","many"],["enganadores","deceivers"],["entraram","they-entered"],["no","in-the"],["mundo,","world,"],["os","the"],["quais","what"],["não","not"],["confessam","they-confess"],["que","that"],["Jesus","Jesus"],["Cristo","Christ"],["veio","came"],["em","in"],["carne.","flesh."],["Esse","That"],["tal","such"],["é","is"],["o","the"],["enganador","deceiver"],["e","and"],["o","the"],["anticristo.","antichrist."]]},
  {num:8,words:[["Acautelai-vos,","To-acautelar-you,"],["para que","that"],["não","not"],["percamos","we-lose"],["aquilo","that"],["pelo","by-the"],["qual","which"],["trabalhamos,","we-labor,"],["antes","before"],["recebamos","we-receive"],["o","the"],["inteiro","entire"],["galardão.","reward."]]},
  {num:9,words:[["Todo","Every"],["aquele","he"],["que","that"],["transgride,","transgresses,"],["e","and"],["não","not"],["persevera","endures"],["na","in-the"],["doutrina","doctrine"],["de","of"],["Cristo,","Christ,"],["não","not"],["tem","has"],["Deus;","God;"],["quem","who"],["persevera","endures"],["na","in-the"],["doutrina","doctrine"],["de","of"],["Cristo,","Christ,"],["esse","that"],["tem","has"],["tanto","both"],["o","the"],["Pai","Father"],["como","as"],["o","the"],["Filho.","Son."]]},
  {num:10,words:[["Se","If"],["alguém","any"],["vem","comes"],["ter","have"],["convosco,","with-you,"],["e","and"],["não","not"],["traz","brings"],["essa","that"],["doutrina,","doctrine,"],["não","not"],["o","him"],["recebais","you-receive"],["em","in"],["casa,","house,"],["nem","nor"],["tampouco","neither"],["o","him"],["saudeis.","you-greet."]]},
  {num:11,words:[["Porque","Because"],["quem","who"],["o","him"],["saúda","greets"],["participa","acquaints"],["nas","in-the"],["suas","his"],["más","deeds"],["obras.","works."]]},
  {num:12,words:[["Muitas","Many"],["coisas","things"],["tenho","I-have"],["que","that"],["vos","you"],["escrever,","write,"],["porém","but"],["não","not"],["quis","would"],["fazê-lo","make-him"],["com","with"],["papel","paper"],["e","and"],["tinta;","ink;"],["mas","but"],["espero","I-abide"],["ir","go"],["ter","have"],["convosco","with-you"],["e","and"],["falar","to-speak"],["face","face"],["a","the"],["face,","face,"],["para que","that"],["a","the"],["nossa","our"],["alegria","joy"],["seja","is"],["completa.","full."]]},
  {num:13,words:[["Saúdam-te","They-greet-you"],["os","the"],["filhos","children"],["de","of"],["tua","your"],["irmã,","sister,"],["a","the"],["eleita.","chosen."],["Amém.","Amen."]]}
];
renderVerseSet(v1, '2jn-ch1-verses');
})();
