(function() {
var v1 = [
  {num:1,words:[["Simão","Simon"],["Pedro,","Peter,"],["servo","servant"],["e","and"],["apóstolo","apostle"],["de","of"],["Jesus","Jesus"],["Cristo,","Christ,"],["aos","to-the"],["que","that"],["conosco","with-us"],["alcançaram","they-obtained"],["fé","faith"],["igualmente","alike"],["preciosa","precious"],["pela","by-the"],["justiça","righteousness"],["do","of-the"],["nosso","our"],["Deus","God"],["e","and"],["Salvador","Savior"],["Jesus","Jesus"],["Cristo:","Christ:"]]},
  {num:2,words:[["Graça","Grace"],["e","and"],["paz","peace"],["vos","you"],["sejam","they-are"],["multiplicadas,","multiplied,"],["pelo","by-the"],["conhecimento","knowledge"],["de","of"],["Deus,","God,"],["e","and"],["de","of"],["Jesus,","Jesus,"],["nosso","our"],["Senhor;","Lord;"]]},
  {num:3,words:[["Como","As"],["o","the"],["seu","his"],["divino","divine"],["poder","power"],["nos","us"],["deu","gave"],["tudo","all"],["o","the"],["que","that"],["diz","says"],["respeito","concerning"],["à","to-the"],["vida","life"],["e","and"],["piedade,","pity,"],["pelo","by-the"],["conhecimento","knowledge"],["daquele","of-that"],["que","that"],["nos","us"],["chamou","called"],["por","by"],["sua","his"],["glória","glory"],["e","and"],["virtude;","virtue;"]]},
  {num:4,words:[["Pelas","By-the"],["quais","what"],["ele","he"],["nos","us"],["tem","has"],["dado","given"],["grandíssimas","great"],["e","and"],["preciosas","precious"],["promessas,","promises,"],["para que","that"],["por","by"],["elas","they"],["vos","you"],["torneis","you-become"],["participantes","partakers"],["da","of-the"],["natureza","nature"],["divina,","divine,"],["havendo","having"],["escapado","escaped"],["da","of-the"],["corrupção,","corruption,"],["que","that"],["pela","by-the"],["concupiscência","lust"],["há","there-is"],["no","in-the"],["mundo.","world."]]},
  {num:5,words:[["E","And"],["vós","you"],["também,","also,"],["pondo","placing"],["nisso","in-that"],["mesmo","same"],["toda","all"],["a","the"],["diligência,","diligence,"],["acrescentai","add"],["à","to-the"],["vossa","your"],["fé","faith"],["a","the"],["virtude,","virtue,"],["e","and"],["à","to-the"],["virtude,","virtue,"],["o","the"],["conhecimento,","knowledge,"]]},
  {num:6,words:[["E","And"],["ao","to-the"],["conhecimento,","knowledge,"],["temperança;","temperance;"],["e","and"],["à","to-the"],["temperança,","temperance,"],["paciência;","patience;"],["e","and"],["à","to-the"],["paciência,","patience,"],["piedade;","pity;"]]},
  {num:7,words:[["E","And"],["à","to-the"],["piedade,","pity,"],["amor","love"],["fraternal;","brotherly;"],["e","and"],["ao","to-the"],["amor","love"],["fraternal,","brotherly,"],["caridade.","charity."]]},
  {num:8,words:[["Porque","Because"],["se","if"],["em","in"],["vós","you"],["houver","will-have"],["e","and"],["abundarem","to-abound"],["essas","those"],["coisas,","things,"],["não","not"],["vos","you"],["deixarão","they-will-leave"],["ociosos","idle"],["nem","nor"],["estéreis","barren"],["no","in-the"],["conhecimento","knowledge"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:9,words:[["Pois","For"],["aquele","that"],["em","in"],["quem","who"],["não","not"],["há","there-is"],["essas","those"],["coisas","things"],["é","is"],["cego,","blind,"],["nada","nothing"],["vendo","seeing"],["ao longe,","afar-off"],["havendo-se","having-himself"],["esquecido","forgetful"],["da","of-the"],["purificação","distillation"],["dos","of-the"],["seus","his"],["antigos","ancient"],["pecados.","sins."]]},
  {num:10,words:[["Portanto,","Therefore,"],["irmãos,","brethren,"],["procurai","seek"],["fazer","make"],["cada","every"],["vez","time"],["mais","more"],["firmes","you-firm"],["a","the"],["vossa","your"],["vocação","calling"],["e","and"],["eleição;","election;"],["porque,","because,"],["fazendo","making"],["isso,","that,"],["nunca","never"],["jamais","never"],["tropeçareis.","you-will-stumble."]]},
  {num:11,words:[["Porque","Because"],["assim","thus"],["vos","you"],["será","will-be"],["abundantemente","abundantly"],["concedida","granted"],["a","the"],["entrada","entrance"],["no","in-the"],["eterno","everlasting"],["reino","kingdom"],["de","of"],["nosso","our"],["Senhor","Lord"],["e","and"],["Salvador","Savior"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:12,words:[["Pelo","By-the"],["que","that"],["não","not"],["deixarei","I-will-leave"],["de","of"],["exortar-vos","exhort-you"],["sempre","always"],["acerca","concerning"],["dessas","of-that"],["coisas,","things,"],["ainda que","although"],["bem","good"],["as","them"],["saibais,","you-know,"],["e","and"],["estejais","you-are"],["confirmados","confirmed"],["na","in-the"],["presente","present"],["verdade.","truth."]]},
  {num:13,words:[["E","And"],["tenho","I-have"],["por","by"],["justo,","fair,"],["enquanto","while"],["estiver","will-be"],["neste","in-this"],["tabernáculo,","tabernacle,"],["despertar-vos","to-awaken-you"],["com","with"],["admoestações.","admonition."]]},
  {num:14,words:[["Sabendo","Knowing"],["que","that"],["brevemente","shortly"],["hei","I-have"],["de","of"],["deixar","leave"],["este","this"],["meu","my"],["tabernáculo,","tabernacle,"],["como","as"],["também","also"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["já","already"],["me","me"],["revelou.","revealed."]]},
  {num:15,words:[["Mas","But"],["também","also"],["eu","I"],["procurarei","I-will-seek"],["em","in"],["toda","every"],["ocasião","occasion"],["que","that"],["depois","afterwards"],["da","of-the"],["minha","my"],["morte","death"],["tenhais","you-have"],["lembrança","remembrance"],["dessas","of-that"],["coisas.","things."]]},
  {num:16,words:[["Porque","Because"],["não","not"],["vos","you"],["fizemos","we-made"],["saber","know"],["a","the"],["virtude","virtue"],["e","and"],["a","the"],["vinda","coming"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["seguindo","following"],["fábulas","fables"],["artificialmente","artificially"],["compostas,","composed,"],["mas","but"],["nós","we"],["mesmos","ourselves"],["vimos","we-saw"],["a","to"],["sua","his"],["majestade.","majesty."]]},
  {num:17,words:[["Porque","Because"],["recebeu","received"],["de","of"],["Deus","God"],["Pai","Father"],["honra","honour"],["e","and"],["glória,","glory,"],["quando","when"],["da","of-the"],["magnífica","terrific"],["glória","glory"],["lhe","to-him"],["foi","was"],["enviada","sent"],["a","to"],["seguinte","next"],["voz:","voice:"],["Este","This"],["é","is"],["o","the"],["meu","my"],["Filho","Son"],["amado,","beloved,"],["em","in"],["quem","who"],["me","me"],["comprazo.","pleased."]]},
  {num:18,words:[["E","And"],["ouvimos","we-heard"],["essa","that"],["voz","voice"],["enviada","sent"],["do","of-the"],["céu,","heaven,"],["estando","being"],["nós","we"],["com","with"],["ele","he"],["no","in-the"],["monte","mountain"],["santo;","holy;"]]},
  {num:19,words:[["E","And"],["temos","we-have"],["muito","much"],["firme","firm"],["a","the"],["palavra","word"],["dos","of-the"],["profetas,","prophets,"],["à","to-the"],["qual","which"],["bem","good"],["fazeis","you-make"],["em","in"],["estar","be"],["atentos,","attentive,"],["como","as"],["a","to"],["uma","a"],["luz","light"],["que","that"],["alumia","lightens"],["em","in"],["lugar","place"],["escuro,","dark,"],["até que","until"],["o","the"],["dia","day"],["clareie,","fade out,"],["e","and"],["a","the"],["estrela","star"],["da","of-the"],["alva","dawning"],["surja","wading"],["em","in"],["vosso","your"],["coração.","heart."]]},
  {num:20,words:[["Sabendo","Knowing"],["primeiramente","firstly"],["isto:","this:"],["que","that"],["nenhuma","neither"],["profecia","prophecy"],["da","of-the"],["escritura","scripture"],["é","is"],["de","of"],["particular","apart"],["interpretação.","interpretation."]]},
  {num:21,words:[["Porque","Because"],["a","the"],["profecia","prophecy"],["nunca","never"],["foi","was"],["produzida","activated"],["por","by"],["vontade","will"],["de","of"],["homem","man"],["algum,","some,"],["mas","but"],["os","the"],["homens","men"],["santos","holy"],["de","of"],["Deus","God"],["falaram","they-spoke"],["inspirados","suffers"],["pelo","by-the"],["Espírito","Spirit"],["Santo.","Holy."]]}
];
var v2 = [
  {num:1,words:[["E","And"],["também","also"],["houve","there-was"],["entre","among"],["o","the"],["povo","people"],["falsos","false"],["profetas,","prophets,"],["como","as"],["entre","among"],["vós","you"],["haverá","there-will-be"],["também","also"],["falsos","false"],["mestres,","teachers,"],["que","that"],["introduzirão","they-will-enter"],["encobertamente","covertly"],["heresias","heresy"],["destruidoras,","destroyer,"],["e","and"],["negarão","they-will-deny"],["o","the"],["Senhor","Lord"],["que","that"],["os","them"],["resgatou,","redeemed,"],["trazendo","bringing"],["sobre","upon"],["si","himself"],["mesmos","themselves"],["repentina","abrupt"],["destruição.","destruction."]]},
  {num:2,words:[["E","And"],["muitos","many"],["seguirão","they-will-follow"],["as","to"],["suas","their"],["dissoluções,","wantonness,"],["pelos","by-the"],["quais","what"],["será","will-be"],["blasfemado","pernicious"],["o","the"],["caminho","way"],["da","of-the"],["verdade.","truth."]]},
  {num:3,words:[["E","And"],["por","by"],["avareza","covetousness"],["farão","they-will-make"],["de","of"],["vós","you"],["negócio","affair"],["com","with"],["palavras","words"],["fingidas,","bogus,"],["sobre","upon"],["os","the"],["quais","what"],["já","already"],["de","of"],["largo","broad"],["tempo","time"],["não","not"],["está","is"],["ocioso","idler"],["o","the"],["juízo,","judgment,"],["e","and"],["a","the"],["sua","their"],["destruição","destruction"],["não","not"],["dorme.","sleeps."]]},
  {num:4,words:[["Porque,","Because,"],["se","if"],["Deus","God"],["não","not"],["poupou","avoided"],["os","the"],["anjos","angels"],["que","that"],["pecaram,","they-sinned,"],["mas,","but,"],["havendo-os","having-them"],["lançado","cast"],["no","in-the"],["inferno,","hell,"],["os","them"],["entregou","delivered"],["às","to-the"],["cadeias","chains"],["da","of-the"],["escuridão,","darkness,"],["ficando","remaining"],["reservados","apart"],["para","for"],["o","the"],["juízo;","judgment;"]]},
  {num:5,words:[["E","And"],["não","not"],["poupou","avoided"],["o","the"],["mundo","world"],["antigo,","ancient,"],["mas","but"],["preservou","preserved"],["Noé,","Noah,"],["o","the"],["oitavo","eighth"],["na","in-the"],["arca,","ark,"],["pregador","preacher"],["da","of-the"],["justiça,","righteousness,"],["trazendo","bringing"],["o","the"],["dilúvio","flood"],["sobre","upon"],["o","the"],["mundo","world"],["dos","of-the"],["ímpios;","wicked;"]]},
  {num:6,words:[["E","And"],["condenou","berated"],["à","to-the"],["ruína","ruin"],["as","the"],["cidades","cities"],["de","of"],["Sodoma","Sodom"],["e","and"],["Gomorra,","Gomorrah,"],["reduzindo-as","reducing-them"],["a","the"],["cinzas,","ashes,"],["e","and"],["pondo-as","placing-them"],["para","for"],["exemplo","example"],["aos","to-the"],["que","that"],["vivessem","they-lived"],["impiamente;","wickedly;"]]},
  {num:7,words:[["E","And"],["livrou","freed"],["o","the"],["justo","fair"],["Ló,","Lot,"],["enfadado","bored"],["da","of-the"],["vida","life"],["dissoluta","vexed"],["dos","of-the"],["homens","men"],["abomináveis","you-abhorred"]]},
  {num:8,words:[["(Porque","(Because"],["este","this"],["justo,","fair,"],["habitando","dwelling"],["entre","among"],["eles,","them,"],["afligia","afflicted"],["todos","all"],["os","the"],["dias","days"],["a","the"],["sua","his"],["alma","soul"],["justa,","fair,"],["vendo","seeing"],["e","and"],["ouvindo","hearing"],["suas","their"],["obras","works"],["iníquas);","obstruction);"]]},
  {num:9,words:[["Assim,","Thus,"],["sabe","knows"],["o","the"],["Senhor","Lord"],["livrar","to-free"],["da","of-the"],["tentação","temptation"],["os","the"],["piedosos,","gracious,"],["e","and"],["reservar","to-destine"],["os","the"],["injustos","unjust"],["para","for"],["o","the"],["dia","day"],["do","of-the"],["juízo,","judgment,"],["para","to"],["serem","to-be"],["castigados;","punished;"]]},
  {num:10,words:[["E","And"],["principalmente","especially"],["aos","to-the"],["que","that"],["segundo","according-to"],["a","the"],["carne","flesh"],["andam","they-walk"],["em","in"],["concupiscências","lusts"],["de","of"],["imundície,","filthiness,"],["e","and"],["desprezam","they-mammon"],["a","the"],["autoridade;","authority;"],["atrevidos,","impertinent,"],["agradando-se","pleasing-himself"],["a","to"],["si","himself"],["mesmos,","themselves,"],["não","not"],["receando","fearing"],["blasfemar","to-blaspheme"],["das","of-the"],["glórias","glories"],["celestes;","celestial;"]]},
  {num:11,words:[["Ao passo que","whereas"],["os","the"],["anjos,","angels,"],["sendo","being"],["maiores","greater"],["em","in"],["força","strength"],["e","and"],["poder,","power,"],["não","not"],["pronunciam","they-pronounce"],["contra","against"],["eles","them"],["juízo","judgment"],["blasfemo","I-blaspheme"],["diante","before"],["do","of-the"],["Senhor.","Lord."]]},
  {num:12,words:[["Mas","But"],["esses,","those,"],["como","as"],["animais","beasts"],["irracionais,","brute,"],["que","that"],["seguem","they-cut"],["a","the"],["natureza,","nature,"],["feitos","acts"],["para","to"],["serem","to-be"],["presos","prisoner"],["e","and"],["mortos,","dead,"],["blasfemando","blaspheming"],["do que","than"],["não","not"],["entendem,","they-understand,"],["perecerão","they-will-perish"],["na","in-the"],["sua","their"],["corrupção,","corruption,"]]},
  {num:13,words:[["Recebendo","Receiving"],["o","the"],["galardão","reward"],["da","of-the"],["injustiça,","injustice,"],["tendo","having"],["por","by"],["prazer","pleasure"],["os","them"],["deleites","pleasures"],["quotidianos,","daily,"],["sendo","being"],["nódoas","blot"],["e","and"],["máculas,","blot,"],["deleitando-se","to-deleitar-himself"],["em","in"],["seus","their"],["engodos,","bait,"],["quando","when"],["se","themselves"],["banqueteiam","they-feast"],["convosco;","with-you;"]]},
  {num:14,words:[["Tendo","Having"],["os","the"],["olhos","eyes"],["cheios","full"],["de","of"],["adultério,","adultery,"],["e","and"],["não","not"],["cessando","ceasing"],["de","of"],["pecar,","to-sin,"],["engodando","attracting"],["as","the"],["almas","souls"],["inconstantes,","unstable,"],["tendo","having"],["o","the"],["coração","heart"],["exercitado","exercised"],["na","in-the"],["avareza,","covetousness,"],["filhos","children"],["de","of"],["maldição,","curse,"]]},
  {num:15,words:[["Os","The"],["quais,","what,"],["deixando","leaving"],["o","the"],["caminho","way"],["reto,","fair,"],["erraram","they-erred"],["seguindo","following"],["o","the"],["caminho","way"],["de","of"],["Balaão,","Balaam,"],["filho","son"],["de","of"],["Beor,","Beor,"],["que","that"],["amou","loved"],["o","the"],["galardão","reward"],["da","of-the"],["injustiça;","injustice;"]]},
  {num:16,words:[["Porém","But"],["teve","had"],["a","to"],["repreensão","reproof"],["da","of-the"],["sua","his"],["transgressão;","transgression;"],["o","the"],["mudo","dumb"],["animal","beast"],["do","of-the"],["jugo,","I-yoke,"],["falando","speaking"],["com","with"],["voz","voice"],["humana,","human,"],["impediu","opposed"],["a","the"],["loucura","foolishness"],["do","of-the"],["profeta.","prophet."]]},
  {num:17,words:[["Esses","Those"],["são","they-are"],["fontes","fountains"],["sem","without"],["água,","water,"],["nuvens","clouds"],["levadas","brought"],["pelo","by-the"],["redemoinho","horses'"],["do","of-the"],["vento,","wind,"],["para","for"],["os","the"],["quais","what"],["a","to"],["escuridão","darkness"],["das","of-the"],["trevas","darkness"],["eternamente","always"],["se","himself"],["reserva.","thrust."]]},
  {num:18,words:[["Porque,","Because,"],["falando","speaking"],["coisas","things"],["muito","much"],["arrogantes","arrogant"],["de","of"],["vaidades,","vanities,"],["engodam","they-attract"],["com","with"],["as","the"],["concupiscências","lusts"],["da","of-the"],["carne,","flesh,"],["e","and"],["com","with"],["dissoluções,","wantonness,"],["os","the"],["que","that"],["se","themselves"],["estavam","they-were"],["afastando","removing"],["daqueles","of-that"],["que","that"],["andam","they-walk"],["no","in-the"],["erro,","error,"]]},
  {num:19,words:[["Prometendo-lhes","Promising-to-them"],["liberdade,","liberty,"],["sendo","being"],["eles","they"],["mesmos","themselves"],["servos","servants"],["da","of-the"],["corrupção.","corruption."],["Porque","Because"],["aquele","he"],["que","that"],["é","is"],["vencido","overcome"],["por","by"],["alguém,","any,"],["do","of-the"],["tal","such"],["faz-se","becomes"],["também","also"],["servo.","servant."]]},
  {num:20,words:[["Porque","Because"],["se,","if,"],["depois de","after"],["terem","to-have"],["escapado","escaped"],["das","of-the"],["corrupções","corruption"],["do","of-the"],["mundo,","world,"],["pelo","by-the"],["conhecimento","knowledge"],["do","of-the"],["Senhor","Lord"],["e","and"],["Salvador","Savior"],["Jesus","Jesus"],["Cristo,","Christ,"],["forem","they-will-be"],["outra vez","again"],["envolvidos","to-entangle"],["nelas","in-him"],["e","and"],["vencidos,","detected,"],["tornou-se-lhes","became-himself-to-them"],["o","the"],["último","last"],["estado","state"],["pior","worse"],["do que","than"],["o","the"],["primeiro.","first."]]},
  {num:21,words:[["Porque","Because"],["melhor","better"],["lhes","to-them"],["teria","should-have"],["sido","been"],["não","not"],["conhecerem","to-know"],["o","the"],["caminho","way"],["da","of-the"],["justiça,","righteousness,"],["do que,","than"],["conhecendo-o,","knowing-it,"],["desviarem-se","to-bypass-themselves"],["do","of-the"],["santo","holy"],["mandamento","commandment"],["que","that"],["lhes","to-them"],["fora","had-been"],["dado;","given;"]]},
  {num:22,words:[["Deste","Of-this"],["modo,","manner,"],["sobreveio-lhes","ensued-to-them"],["o","the"],["que","that"],["por","by"],["um","a"],["verdadeiro","true"],["provérbio","proverb"],["se","himself"],["diz:","says:"],["O","The"],["cão","dog"],["voltou","returned"],["ao","to-the"],["seu","his"],["próprio","own"],["vômito,","vomit,"],["e","and"],["a","the"],["porca","nut"],["lavada,","rinsed,"],["ao","to-the"],["espojadouro","wallowing"],["de","of"],["lama.","mire."]]}
];
var v3 = [
  {num:1,words:[["Amados,","Beloved,"],["escrevo-vos","I-write-you"],["agora","now"],["esta","this"],["segunda","second"],["carta,","letter,"],["em","in"],["ambas","both"],["as","to"],["quais","what"],["desperto","I-awaken"],["com","with"],["exortação","exhortation"],["o","the"],["vosso","your"],["ânimo","courage"],["sincero;","sincere;"]]},
  {num:2,words:[["Para que","that"],["vos","you"],["lembreis","you-remember"],["das","of-the"],["palavras","words"],["que","that"],["dantes","of-ahead"],["foram","they-were"],["ditas","spoken"],["pelos","by-the"],["santos","holy"],["profetas,","prophets,"],["e","and"],["do","of-the"],["mandamento","commandment"],["do","of-the"],["Senhor","Lord"],["e","and"],["Salvador,","Savior,"],["mediante","by-means-of"],["vossos","your"],["apóstolos.","apostles."]]},
  {num:3,words:[["Sabendo","Knowing"],["primeiro","first"],["isto:","this:"],["que","that"],["nos","in-the"],["últimos","last"],["dias","days"],["virão","they-will-come"],["escarnecedores,","scorners,"],["andando","walking"],["segundo as suas","families"],["próprias","own"],["concupiscências,","lusts,"]]},
  {num:4,words:[["E","And"],["dizendo:","saying:"],["Onde","Where"],["está","is"],["a","the"],["promessa","promise"],["da","of-the"],["sua","his"],["vinda?","coming?"],["Porque","Because"],["desde","since"],["que","that"],["os","the"],["pais","fathers"],["dormiram","they-slept"],["todas","all"],["as","the"],["coisas","things"],["permanecem","they-remain"],["como","as"],["desde o","beginning"],["princípio","beginning"],["da","of-the"],["criação.","creation."]]},
  {num:5,words:[["Porque","Because"],["voluntariamente","willingly"],["ignoram","they-ignore"],["isto:","this:"],["que","that"],["pela","by-the"],["palavra","word"],["de","of"],["Deus","God"],["já","already"],["desde","since"],["a","the"],["antiguidade","antiguidade"],["existiram","they-existed"],["os","the"],["céus,","heaven,"],["e","and"],["a","the"],["terra,","earth,"],["que","that"],["foi","was"],["tirada","taken-away"],["da","of-the"],["água","water"],["e","and"],["no","in-the"],["meio","midst"],["da","of-the"],["água","water"],["subsiste.","subsists."]]},
  {num:6,words:[["Pela","By-the"],["qual","which"],["pereceu","perished"],["o","the"],["mundo","world"],["de","of"],["então,","then,"],["coberto","covered"],["com","with"],["as","the"],["águas","waters"],["do","of-the"],["dilúvio.","flood."]]},
  {num:7,words:[["Mas","But"],["os","the"],["céus","heaven"],["e","and"],["a","the"],["terra","earth"],["que","that"],["agora","now"],["existem","they-exist"],["pela","by-the"],["mesma","same"],["palavra","word"],["se","themselves"],["reservam","they-destine"],["como","as"],["tesouro","treasure"],["e","and"],["se","if"],["guardam","they-keep"],["para","for"],["o","the"],["fogo,","fire,"],["até","until"],["o","the"],["dia","day"],["do","of-the"],["juízo,","judgment,"],["e","and"],["da","of-the"],["perdição","perdition"],["dos","of-the"],["homens","men"],["ímpios.","wicked."]]},
  {num:8,words:[["Porém,","But,"],["amados,","beloved,"],["não","not"],["ignoreis","you-ignore"],["uma","a"],["coisa:","thing:"],["que","that"],["um","a"],["dia","day"],["para","for"],["o","the"],["Senhor","Lord"],["é","is"],["como","as"],["mil","thousand"],["anos,","years,"],["e","and"],["mil","thousand"],["anos,","years,"],["como","as"],["um","a"],["dia.","day."]]},
  {num:9,words:[["O","The"],["Senhor","Lord"],["não","not"],["retarda","delay"],["a","the"],["sua","his"],["promessa,","promise,"],["como","as"],["alguns","some"],["a","it"],["têm","they-have"],["por","by"],["tardia;","late;"],["mas","but"],["é","is"],["longânimo","slow"],["para","for"],["conosco,","with-us,"],["não","not"],["querendo","willing"],["que","that"],["alguns","some"],["se","themselves"],["percam,","they-lose,"],["senão","save"],["que","that"],["todos","all"],["venham","they-come"],["a","to"],["arrepender-se.","to-repent."]]},
  {num:10,words:[["Mas","But"],["o","the"],["dia","day"],["do","of-the"],["Senhor","Lord"],["virá","will-come"],["como","as"],["o","the"],["ladrão","thief"],["de","of"],["noite;","night;"],["no","in-the"],["qual","which"],["os","the"],["céus","heaven"],["passarão","they-will-fare"],["com","with"],["grande","great"],["estrondo,","noise,"],["e","and"],["os","the"],["elementos,","elements,"],["ardendo,","glowing,"],["se","if"],["desfarão,","they-will-disrupt,"],["e","and"],["a","the"],["terra,","earth,"],["e","and"],["as","the"],["obras","works"],["que","that"],["nela","in-it"],["há","there-is"],["se","themselves"],["queimarão.","they-will-burn."]]},
  {num:11,words:[["Havendo,","Having,"],["pois,","for,"],["de","of"],["perecer","to-perish"],["todas","all"],["essas","those"],["coisas,","things,"],["que","that"],["tipo","kind"],["de","of"],["pessoas","persons"],["vos","you"],["convém","befits"],["a","to"],["vós","you"],["ser","be"],["em","in"],["santa","holy"],["conduta","conversation"],["e","and"],["piedade,","pity,"]]},
  {num:12,words:[["Aguardando,","Abiding,"],["e","and"],["apressando-vos","accelerating-you"],["para","for"],["a","the"],["vinda","coming"],["do","of-the"],["dia","day"],["de","of"],["Deus,","God,"],["em","in"],["que","that"],["os","the"],["céus,","heaven,"],["incendiados,","burn,"],["se","if"],["desfarão,","they-will-disrupt,"],["e","and"],["os","the"],["elementos,","elements,"],["ardendo,","glowing,"],["se","if"],["derreterão?","they-will-melt?"]]},
  {num:13,words:[["Porém,","But,"],["segundo","according-to"],["a","the"],["sua","his"],["promessa,","promise,"],["aguardamos","we-abide"],["novos","bottles"],["céus","heaven"],["e","and"],["nova","new"],["terra,","earth,"],["nos","in-the"],["quais","what"],["habita","dwell"],["a","the"],["justiça.","righteousness."]]},
  {num:14,words:[["Pelo","By-the"],["que,","that,"],["amados,","beloved,"],["aguardando","abiding"],["essas","those"],["coisas,","things,"],["procurai","seek"],["que","that"],["dele","of-him"],["sejais","you-are"],["achados","reprobates"],["imaculados","immaculate"],["e","and"],["irrepreensíveis","blameless"],["em","in"],["paz.","peace."]]},
  {num:15,words:[["E","And"],["tende","have"],["por","by"],["salvação","salvation"],["a","the"],["longanimidade","longsuffering"],["de","of"],["nosso","our"],["Senhor;","Lord;"],["como","as"],["também","also"],["o","the"],["nosso","our"],["amado","beloved"],["irmão","brother"],["Paulo","Paul"],["vos","you"],["escreveu,","wrote,"],["segundo","according-to"],["a","the"],["sabedoria","wisdom"],["que","that"],["lhe","to-him"],["foi","was"],["dada;","given;"]]},
  {num:16,words:[["Como","As"],["também","also"],["em","in"],["todas","all"],["as","to"],["suas","their"],["epístolas,","epistle,"],["falando","speaking"],["nelas","in-him"],["dessas","of-that"],["coisas,","things,"],["entre","among"],["as","the"],["quais","what"],["há","there-is"],["algumas","some"],["difíceis","difficult"],["de","of"],["entender,","to-understand,"],["que","that"],["os","the"],["ignorantes","ignorant"],["e","and"],["inconstantes","unstable"],["distorcem,","epistles,"],["como","as"],["também","also"],["as","the"],["outras","other"],["escrituras,","scriptures,"],["para","for"],["sua","his"],["própria","own"],["perdição.","perdition."]]},
  {num:17,words:[["Vós,","You,"],["portanto,","therefore,"],["amados,","beloved,"],["sabendo","knowing"],["isso","that"],["de","of"],["antemão,","beforehand,"],["guardai-vos","keep-you"],["de","of"],["que,","that,"],["pelo","by-the"],["erro","error"],["dos","of-the"],["homens","men"],["abomináveis,","you-abhorred,"],["sejais","you-are"],["juntamente","together"],["arrebatados,","carried-away,"],["e","and"],["descaiais","stedfastness"],["de","of"],["vossa","your"],["firmeza;","firmness;"]]},
  {num:18,words:[["Antes,","Before,"],["crescei","grow"],["na","in-the"],["graça","grace"],["e","and"],["no","in-the"],["conhecimento","knowledge"],["de","of"],["nosso","our"],["Senhor","Lord"],["e","and"],["Salvador,","Savior,"],["Jesus","Jesus"],["Cristo.","Christ."],["A","The"],["ele","he"],["seja","is"],["a","the"],["glória,","glory,"],["assim","thus"],["agora,","now,"],["como","as"],["no","in-the"],["dia","day"],["da","of-the"],["eternidade.","eternity."],["Amém.","Amen."]]}
];
renderVerseSet(v1, '2pe-ch1-verses');
renderVerseSet(v2, '2pe-ch2-verses');
renderVerseSet(v3, '2pe-ch3-verses');
})();
