(function() {
var v1 = [
  {num:1,words:[["Paulo,","Paul,"],["e","and"],["Silvano,","Silvanus,"],["e","and"],["Timóteo,","Timotheus,"],["à","to-the"],["igreja","church"],["dos","of-the"],["tessalonicenses,","thessalonians,"],["em","in"],["Deus,","God,"],["nosso","our"],["Pai,","Father,"],["e","and"],["no","in-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo:","Christ:"]]},
  {num:2,words:[["Graça","Grace"],["e","and"],["paz","peace"],["de","of"],["Deus,","God,"],["nosso","our"],["Pai,","Father,"],["e","and"],["do","of-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:3,words:[["Sempre","Always"],["devemos,","we-duty,"],["irmãos,","brethren,"],["dar","give"],["graças","thanks"],["a","to"],["Deus","God"],["por","by"],["vós,","you,"],["como","as"],["é","is"],["de","of"],["razão,","account,"],["porquanto","because"],["a","to"],["vossa","your"],["fé","faith"],["cresce","groweth"],["muitíssimo","enormously"],["e","and"],["a","to"],["caridade","charity"],["de","of"],["cada","every"],["um","a"],["de","of"],["vós","you"],["é","is"],["abundante","abundant"],["de","of"],["uns","some"],["para","for"],["com","with"],["os","the"],["outros;","another;"]]},
  {num:4,words:[["De maneira que","so-that"],["nós","we"],["mesmos","even"],["nos","us"],["gloriamos","access"],["de","of"],["vós","you"],["nas","in-the"],["igrejas","churches"],["de","of"],["Deus","God"],["por","by"],["causa","sake"],["da","of-the"],["vossa","your"],["paciência","patience"],["e","and"],["fé,","faith,"],["em","in"],["todas","things"],["as","the"],["vossas","your"],["perseguições","persecutions"],["e","and"],["aflições","afflictions"],["que","that"],["suportais;","you-abide;"]]},
  {num:5,words:[["Prova","Investigation"],["clara","clear"],["do","of-the"],["justo","fair"],["juízo","judgment"],["de","of"],["Deus,","God,"],["para que","that"],["sejais","you-are"],["tidos","I-should-have"],["por","by"],["dignos","worthy"],["do","of-the"],["reino","kingdom"],["de","of"],["Deus,","God,"],["pelo","by-the"],["qual","which"],["também","also"],["padeceis;","you-abide;"]]},
  {num:6,words:[["Pois","For"],["é","is"],["justo","fair"],["diante de","before"],["Deus","God"],["que","that"],["dê","gives"],["em","in"],["paga","pays"],["tribulação","tribulation"],["aos","to-the"],["que","that"],["vos","you"],["atribulam,","to-atribular,"]]},
  {num:7,words:[["E","And"],["a","to"],["vós,","you,"],["que","that"],["sois","you-are"],["atribulados,","fightings,"],["descanso","rest"],["conosco,","with-us,"],["quando","when"],["se","if"],["manifestar","demonstrate"],["o","the"],["Senhor","Lord"],["Jesus","Jesus"],["desde o","beginning"],["céu","heaven"],["com","with"],["os","the"],["anjos","angels"],["do","of-the"],["seu","his"],["poder,","can,"]]},
  {num:8,words:[["Como","As"],["labareda","flame"],["de","of"],["fogo,","fire,"],["tomando","taking"],["vingança","vengeance"],["dos","of-the"],["que","that"],["não","no"],["conhecem","they-know"],["a","to"],["Deus","God"],["e","and"],["dos","of-the"],["que","that"],["não","no"],["obedecem","obey"],["ao","to-the"],["evangelho","gospel"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo;","Christ;"]]},
  {num:9,words:[["Os","The"],["quais,","what,"],["por","by"],["castigo,","punishment,"],["padecerão","they-will-abide"],["eterna","eternal"],["perdição","perdition"],["ante","before"],["a","to"],["face","face"],["do","of-the"],["Senhor","Lord"],["e","and"],["a","to"],["glória","glory"],["do","of-the"],["seu","his"],["poder,","can,"]]},
  {num:10,words:[["Quando","When"],["vier","will-come"],["para","for"],["ser","be"],["glorificado","glorified"],["nos","us"],["seus","his"],["santos,","Seneca,"],["e","and"],["para","for"],["fazer-se","become"],["admirável","admirable"],["naquele","in-that"],["dia","day"],["em","in"],["todos","all"],["os","the"],["que","that"],["creem","they-believe"],["(porquanto","(because"],["o","the"],["nosso","our"],["testemunho","testimony"],["foi","was"],["acreditado","I-should-believe"],["entre","between"],["vós).","you)."]]},
  {num:11,words:[["Pelo","By-the"],["que","that"],["também","also"],["rogamos","furthermore"],["sempre","always"],["por","by"],["vós,","you,"],["para que","that"],["o","the"],["nosso","our"],["Deus","God"],["vos","you"],["faça","makes"],["dignos","worthy"],["da","of-the"],["sua","his"],["vocação,","calling,"],["e","and"],["cumpra","observes"],["todo","every"],["o","the"],["desejo","desire"],["da","of-the"],["sua","his"],["bondade,","goodness,"],["e","and"],["a","to"],["obra","work"],["da","of-the"],["fé","faith"],["com","with"],["poder;","can;"]]},
  {num:12,words:[["Para que","that"],["o","the"],["nome","name"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["seja","is"],["em","in"],["vós","you"],["glorificado,","glorified,"],["e","and"],["vós","you"],["nele,","in-him,"],["segundo","according-to"],["a","to"],["graça","grace"],["de","of"],["nosso","our"],["Deus","God"],["e","and"],["do","of-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo.","Christ."]]}
];
var v2 = [
  {num:1,words:[["Ora,","Now,"],["irmãos,","brethren,"],["rogamo-vos,","feebleminded,"],["pela","by-the"],["vinda","coming"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["e","and"],["pela","by-the"],["nossa","our"],["reunião","gathering"],["com","with"],["ele,","he,"]]},
  {num:2,words:[["Que","That"],["não","no"],["vos","you"],["movais","you-actuate"],["facilmente","easily"],["do","of-the"],["vosso","your"],["entendimento,","understanding,"],["e","and"],["não","no"],["vos","you"],["perturbeis,","you-confuse,"],["nem","nor"],["por","by"],["espírito,","spirit,"],["nem","nor"],["por","by"],["palavra,","word,"],["nem","nor"],["por","by"],["epístola,","epistle,"],["como","as"],["escrita","writing"],["por","by"],["nós,","we,"],["como","as"],["se","if"],["o","the"],["dia","day"],["de","of"],["Cristo","Christ"],["estivesse","was"],["já","already"],["perto.","near."]]},
  {num:3,words:[["Ninguém","None"],["de","of"],["maneira","manner"],["alguma","any"],["vos","you"],["engane;","deceive;"],["porque","because"],["aquele","that ... over there"],["dia","day"],["não","no"],["virá","will-come"],["sem","without"],["que","that"],["antes","before"],["venha","comes"],["a","to"],["apostasia,","slidden,"],["e","and"],["se","if"],["manifeste","demonstrates"],["o","the"],["homem","man"],["do","of-the"],["pecado,","sin,"],["o","the"],["filho","son"],["da","of-the"],["perdição;","perdition;"]]},
  {num:4,words:[["O","The"],["qual","which"],["se","if"],["opõe,","combats,"],["e","and"],["se","if"],["levanta","hoists"],["sobre","upon"],["tudo","whatsoever"],["o","the"],["que","that"],["se","if"],["chama","flame"],["Deus,","God,"],["ou","or"],["se","if"],["adora;","worships;"],["a","to"],["ponto","stitch"],["de","of"],["assentar-se,","sit down,"],["como","as"],["Deus,","God,"],["no","in-the"],["templo","temple"],["de","of"],["Deus,","God,"],["fazendo-se","I-become"],["parecer","seem"],["Deus.","God."]]},
  {num:5,words:[["Não","No"],["vos","you"],["lembrais","you-caution"],["de","of"],["que","that"],["essas","those"],["coisas","things"],["vos","you"],["dizia","said"],["eu","I"],["quando","when"],["ainda","yet"],["estava","was"],["convosco?","with-you?"]]},
  {num:6,words:[["E","And"],["agora","now"],["vós","you"],["sabeis","you-know"],["o","the"],["que","that"],["o","the"],["detém,","restrains,"],["para que","that"],["a","to"],["seu","his"],["próprio","own"],["tempo","time"],["seja","is"],["manifestado.","manifested."]]},
  {num:7,words:[["Porque","Because"],["já","already"],["o","the"],["mistério","mystery"],["da","of-the"],["iniquidade","iniquity"],["opera;","worketh;"],["somente","only"],["há","has"],["um","a"],["que","that"],["agora","now"],["resiste","resisteth"],["até que","until"],["do","of-the"],["meio","midst"],["seja","is"],["ele","he"],["tirado;","I-should-deduct;"]]},
  {num:8,words:[["E","And"],["então","said"],["será","will-be"],["manifestado","manifested"],["o","the"],["iníquo,","wicked,"],["o","the"],["qual","which"],["o","the"],["Senhor","Lord"],["desfará","will-disrupt"],["pelo","by-the"],["espírito","spirit"],["da","of-the"],["sua","his"],["boca,","mouth,"],["e","and"],["aniquilará","famish"],["pelo","by-the"],["esplendor","brightness"],["da","of-the"],["sua","his"],["vinda;","coming;"]]},
  {num:9,words:[["Aquele","That ... over there"],["cuja","whose"],["vinda","coming"],["é","is"],["segundo","according-to"],["a","to"],["eficácia","efficacity"],["de","of"],["Satanás,","Satan,"],["com","with"],["todo","every"],["o","the"],["poder,","can,"],["e","and"],["sinais","signs"],["e","and"],["prodígios","wonders"],["de","of"],["mentira,","lie,"]]},
  {num:10,words:[["E","And"],["com","with"],["todo","every"],["engano","deceit"],["da","of-the"],["injustiça","injustice"],["para","for"],["os","the"],["que","that"],["perecem,","they-perish,"],["porquanto","because"],["não","no"],["receberam","received"],["o","the"],["amor","love"],["da","of-the"],["verdade","truth"],["para","for"],["se","if"],["salvarem.","they-will-save."]]},
  {num:11,words:[["E,","And,"],["portanto,","therefore,"],["Deus","God"],["lhes","to-them"],["enviará","leanness"],["a","to"],["operação","operation"],["do","of-the"],["erro,","error,"],["para que","that"],["creiam","delusion"],["na","in-the"],["mentira;","lie;"]]},
  {num:12,words:[["Para que","that"],["sejam","they-are"],["condenados","berate"],["todos","all"],["os","the"],["que","that"],["não","no"],["creram","believed"],["na","in-the"],["verdade;","truth;"],["antes,","before,"],["tiveram","they-had"],["prazer","pleasure"],["na","in-the"],["iniquidade.","iniquity."]]},
  {num:13,words:[["Mas","But"],["devemos","we-duty"],["sempre","always"],["dar","give"],["graças","thanks"],["a","to"],["Deus","God"],["por","by"],["vós,","you,"],["irmãos","brethren"],["amados","beloved"],["do","of-the"],["Senhor,","Lord,"],["por","by"],["vos","you"],["ter","have"],["Deus","God"],["escolhido","chosen"],["desde o","beginning"],["princípio","beginning"],["para","for"],["a","to"],["salvação,","salvation,"],["em","in"],["santificação","sanctification"],["do","of-the"],["Espírito,","Spirit,"],["e","and"],["fé","faith"],["da","of-the"],["verdade;","truth;"]]},
  {num:14,words:[["Para","For"],["o","the"],["que","that"],["pelo","by-the"],["nosso","our"],["evangelho","gospel"],["vos","you"],["chamou,","called,"],["para","for"],["alcançardes","you-will-accomplish"],["a","to"],["glória","glory"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:15,words:[["Pelo","By-the"],["que,","that,"],["irmãos,","brethren,"],["estai","be"],["firmes","you-firm"],["e","and"],["retende","restrain"],["as","the"],["tradições","traditions"],["que","that"],["vos","you"],["foram","they-were"],["ensinadas,","teach,"],["seja","is"],["por","by"],["palavra,","word,"],["seja","is"],["por","by"],["epístola","epistle"],["nossa.","our."]]},
  {num:16,words:[["E","And"],["o","the"],["próprio","own"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["e","and"],["nosso","our"],["Deus","God"],["e","and"],["Pai,","Father,"],["que","that"],["nos","us"],["amou,","loved,"],["e","and"],["nos","us"],["deu","gave"],["uma","a"],["eterna","eternal"],["consolação","consolation"],["e","and"],["boa","good"],["esperança","hope"],["pela","by-the"],["graça,","grace,"]]},
  {num:17,words:[["Consolem","They-comfort"],["o","the"],["vosso","your"],["coração,","heart,"],["e","and"],["vos","you"],["confortem","they-comfort"],["em","in"],["toda","every"],["boa","good"],["palavra","word"],["e","and"],["obra.","work."]]}
];
var v3 = [
  {num:1,words:[["No","In-the"],["demais,","moreover,"],["irmãos,","brethren,"],["rogai","labourers"],["por","by"],["nós,","we,"],["para que","that"],["a","to"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["tenha","has"],["livre","free"],["curso","course"],["e","and"],["seja","is"],["glorificada,","commend,"],["como","as"],["também","also"],["o","the"],["é","is"],["entre","between"],["vós;","you;"]]},
  {num:2,words:[["E","And"],["para que","that"],["sejamos","we-are"],["livres","free"],["de","of"],["homens","men"],["dissolutos","unreasonable"],["e","and"],["maus,","bad,"],["porque","because"],["a","to"],["fé","faith"],["não","no"],["é","is"],["de","of"],["todos.","all."]]},
  {num:3,words:[["Mas","But"],["fiel","faithful"],["é","is"],["o","the"],["Senhor,","Lord,"],["que","that"],["vos","you"],["confortará,","will-comfort,"],["e","and"],["guardará","will-keep"],["do","of-the"],["maligno.","delicate."]]},
  {num:4,words:[["E","And"],["confiamos","we-confide"],["quanto","as"],["a","to"],["vós","you"],["no","in-the"],["Senhor,","Lord,"],["que","that"],["também","also"],["fazeis","you-make"],["e","and"],["fareis","you-will-make"],["o","the"],["que","that"],["vos","you"],["mandamos.","we-command."]]},
  {num:5,words:[["Ora,","Now,"],["o","the"],["Senhor","Lord"],["encaminhe","directs"],["o","the"],["vosso","your"],["coração","heart"],["na","in-the"],["caridade","charity"],["de","of"],["Deus,","God,"],["e","and"],["na","in-the"],["paciência","patience"],["de","of"],["Cristo.","Christ."]]},
  {num:6,words:[["Mandamo-vos,","Command-you,"],["porém,","but,"],["irmãos,","brethren,"],["em","in"],["nome","name"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["que","that"],["vos","you"],["aparteis","you-divide"],["de todo","wholly"],["irmão","brother"],["que","that"],["andar","walk"],["desordenadamente,","messly,"],["e","and"],["não","no"],["segundo","according-to"],["a","to"],["tradição","tradition"],["que","that"],["de","of"],["nós","we"],["recebeu.","received."]]},
  {num:7,words:[["Porque","Because"],["vós","you"],["mesmos","even"],["sabeis","you-know"],["como","as"],["convém","expedient"],["imitar-nos,","imitate-us,"],["pois","for"],["que","that"],["não","no"],["nos","us"],["houvemos","we-had"],["desordenadamente","messly"],["entre","between"],["vós;","you;"]]},
  {num:8,words:[["Nem","Nor"],["de","of"],["graça","grace"],["comemos","we-eat"],["o","the"],["pão","bread"],["de","of"],["ninguém,","none,"],["mas","but"],["com","with"],["trabalho","work"],["e","and"],["fadiga,","stress,"],["trabalhando","laboring"],["noite","night"],["e","and"],["dia,","day,"],["para","for"],["não","no"],["sermos","to-be"],["pesados","chargeable"],["a","to"],["nenhum","none"],["de","of"],["vós.","you."]]},
  {num:9,words:[["Não","No"],["porque","because"],["não","no"],["tivéssemos","we-had"],["autoridade,","authority,"],["mas","but"],["para","for"],["vos","you"],["dar","give"],["em","in"],["nós","we"],["mesmos","even"],["exemplo,","example,"],["para","for"],["nos","us"],["imitardes.","you-will-imitate."]]},
  {num:10,words:[["Porque,","Because,"],["quando","when"],["ainda","yet"],["estávamos","we-were"],["convosco,","with-you,"],["vos","you"],["mandamos","we-command"],["isto:","it:"],["que","that"],["se","if"],["alguém","any"],["não","no"],["quiser","will-will"],["trabalhar,","labor,"],["não","no"],["coma","coma"],["também.","also."]]},
  {num:11,words:[["Porque","Because"],["ouvimos","we-hear"],["que","that"],["alguns","some"],["entre","between"],["vós","you"],["andam","walk"],["desordenadamente,","messly,"],["não","no"],["trabalhando;","laboring;"],["antes,","before,"],["fazendo","doing"],["coisas","things"],["vãs.","vain."]]},
  {num:12,words:[["Aos","To-the"],["tais,","such,"],["porém,","but,"],["mandamos,","we-command,"],["e","and"],["admoestamos","we-admonish"],["por","by"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["que,","that,"],["trabalhando","laboring"],["com","with"],["sossego,","quietness,"],["comam","piss"],["o","the"],["seu","his"],["próprio","own"],["pão.","bread."]]},
  {num:13,words:[["E","And"],["vós,","you,"],["irmãos,","brethren,"],["não","no"],["vos","you"],["canseis","well-doing"],["de","of"],["fazer","make"],["o","the"],["bem.","good."]]},
  {num:14,words:[["Porém,","But,"],["se","if"],["alguém","any"],["não","no"],["obedecer","obey"],["à","to-the"],["nossa","our"],["palavra","word"],["escrita","writing"],["nesta","in-this"],["carta,","letter,"],["notai","notice"],["o","the"],["tal,","same,"],["e","and"],["não","no"],["vos","you"],["mistureis","you-mingle"],["com","with"],["ele,","he,"],["para que","that"],["se","if"],["envergonhe.","abashes."]]},
  {num:15,words:[["Todavia","Nevertheless"],["não","no"],["o","the"],["tenhais","you-have"],["como","as"],["inimigo,","enemy,"],["mas","but"],["admoestai-o","admonish-the"],["como","as"],["irmão.","brother."]]},
  {num:16,words:[["Ora,","Now,"],["o","the"],["próprio","own"],["Senhor","Lord"],["da","of-the"],["paz","peace"],["vos","you"],["dê","gives"],["sempre","always"],["paz","peace"],["em","in"],["toda","every"],["maneira.","manner."],["O","The"],["Senhor","Lord"],["seja","is"],["com","with"],["todos","all"],["vós.","you."]]},
  {num:17,words:[["Saudação","Greeting"],["da","of-the"],["minha","my"],["própria","own"],["mão,","hand,"],["de","of"],["mim,","me,"],["Paulo,","Paul,"],["que","that"],["é","is"],["o","the"],["sinal","sign"],["em","in"],["todas","things"],["as","the"],["epístolas;","epistle;"],["assim","thus"],["escrevo.","write."]]},
  {num:18,words:[["A","To"],["graça","grace"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["seja","is"],["com","with"],["todos","all"],["vós.","you."],["Amém.","Amen."]]}
];
renderVerseSet(v1, '2th-ch1-verses');
renderVerseSet(v2, '2th-ch2-verses');
renderVerseSet(v3, '2th-ch3-verses');
})();
