(function() {
var v1 = [
  {num:1,words:[["As","The"],["palavras","words"],["de","of"],["Amós,","Amos,"],["que","that"],["estava","was"],["entre","among"],["os","the"],["pastores","shepherds"],["de","of"],["Tecoa,","Tekoa,"],["as","the"],["quais","what"],["viu","saw"],["sobre","upon"],["Israel,","Israel,"],["nos","in-the"],["dias","days"],["de","of"],["Uzias,","Uzziah,"],["rei","king"],["de","of"],["Judá,","Judah,"],["e","and"],["nos","in-the"],["dias","days"],["de","of"],["Jeroboão,","Jeroboam,"],["filho","son"],["de","of"],["Joás,","Joash,"],["rei","king"],["de","of"],["Israel,","Israel,"],["dois","two"],["anos","years"],["antes","before"],["do","of-the"],["terremoto.","earthquake."]]},
  {num:2,words:[["E","And"],["disse:","said:"],["O","The"],["Senhor","Lord"],["bramará","roar"],["de","of"],["Sião,","Zion,"],["e","and"],["de","of"],["Jerusalém","Jerusalem"],["dará","will-give"],["a","the"],["sua","his"],["voz;","voice;"],["as","the"],["habitações","habitation"],["dos","of-the"],["pastores","shepherds"],["prantearão,","they-will-mourn,"],["e","and"],["secar-se-á","will-wither-himself"],["o","the"],["cume","top"],["do","of-the"],["Carmelo.","Carmel."]]},
  {num:3,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["de","of"],["Damasco,","Damascus,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["trilharam","they-threshed"],["Gileade","Gilead"],["com","with"],["trilhos","path"],["de","of"],["ferro.","iron."]]},
  {num:4,words:[["Por isso","therefore"],["porei","I-will-place"],["fogo","fire"],["à","to-the"],["casa","house"],["de","of"],["Hazael,","Hazael,"],["e","and"],["consumirá","devour"],["os","the"],["palácios","palaces"],["de","of"],["Ben-Hadade.","Ben-Hadad."]]},
  {num:5,words:[["E","And"],["quebrarei","I-will-crush"],["o","the"],["ferrolho","bolt"],["de","of"],["Damasco,","Damascus,"],["e","and"],["exterminarei","I-will-reverse"],["o","the"],["morador","inhabitant"],["de","of"],["Biqueate-Áven,","Aven,"],["e","and"],["ao","to-the"],["que","that"],["tem","has"],["o","the"],["cetro","sceptre"],["de","of"],["Bete-Éden;","Aven;"],["e","and"],["o","the"],["povo","people"],["da","of-the"],["Síria","Syria"],["será","will-be"],["levado","brought"],["em","in"],["cativeiro","bondage"],["a","to"],["Quir,","Kir,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:6,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["de","of"],["Gaza,","Gaza,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["levaram","they-carried"],["em","in"],["cativeiro","bondage"],["todos","all"],["os","the"],["cativos","captives"],["para","for"],["os","the"],["entregarem","to-deliver"],["a","to"],["Edom.","Edom."]]},
  {num:7,words:[["Por isso","therefore"],["porei","I-will-place"],["fogo","fire"],["ao","to-the"],["muro","wall"],["de","of"],["Gaza,","Gaza,"],["que","that"],["consumirá","devour"],["os","the"],["seus","their"],["palácios.","palaces."]]},
  {num:8,words:[["E","And"],["exterminarei","I-will-reverse"],["o","the"],["morador","inhabitant"],["de","of"],["Asdode,","Ashdod,"],["e","and"],["o","the"],["que","that"],["tem","has"],["o","the"],["cetro","sceptre"],["de","of"],["Ascalom,","Ashkelon,"],["e","and"],["tornarei","I-will-become"],["a","the"],["minha","my"],["mão","hand"],["contra","against"],["Ecrom;","Ekron;"],["e","and"],["o","the"],["restante","remaining"],["dos","of-the"],["filisteus","philistines"],["perecerá,","will-perish,"],["diz","says"],["o","the"],["Senhor","Lord"],["Deus.","God."]]},
  {num:9,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["de","of"],["Tiro,","Tyre,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["entregaram","they-delivered"],["todos","all"],["os","the"],["cativos","captives"],["a","to"],["Edom,","Edom,"],["e","and"],["não","not"],["se","themselves"],["lembraram","they-remembered"],["da","of-the"],["aliança","alliance"],["dos","of-the"],["irmãos.","brethren."]]},
  {num:10,words:[["Por isso","therefore"],["porei","I-will-place"],["fogo","fire"],["ao","to-the"],["muro","wall"],["de","of"],["Tiro,","Tyre,"],["que","that"],["consumirá","devour"],["os","the"],["seus","their"],["palácios.","palaces."]]},
  {num:11,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["de","of"],["Edom,","Edom,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["perseguiu","persecuted"],["seu","his"],["irmão","brother"],["à","to-the"],["espada,","sword,"],["e","and"],["corrompeu","bribed"],["as","the"],["suas","his"],["misericórdias;","mercies;"],["e","and"],["a","to"],["sua","his"],["ira","anger"],["despedaça","ravin"],["eternamente,","always,"],["e","and"],["retém","restrains"],["a","the"],["sua","his"],["indignação","indignation"],["para sempre.","for-ever"]]},
  {num:12,words:[["Por isso","therefore"],["porei","I-will-place"],["fogo","fire"],["a","to"],["Temã,","Teman,"],["que","that"],["consumirá","devour"],["os","the"],["palácios","palaces"],["de","of"],["Bozra.","Bozrah."]]},
  {num:13,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["dos","of-the"],["filhos","children"],["de","of"],["Amom,","Ammon,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["fenderam","they-split"],["as","the"],["grávidas","ripped"],["de","of"],["Gileade,","Gilead,"],["para","to"],["dilatarem","to-enlarge"],["os","the"],["seus","their"],["termos.","coasts."]]},
  {num:14,words:[["Por isso","therefore"],["porei","I-will-place"],["fogo","fire"],["ao","to-the"],["muro","wall"],["de","of"],["Rabá,","Rabbah,"],["que","that"],["consumirá","devour"],["os","the"],["seus","their"],["palácios,","palaces,"],["com","with"],["alarido","shouting"],["no","in-the"],["dia","day"],["da","of-the"],["batalha,","battle,"],["com","with"],["tempestade","hurricane"],["no","in-the"],["dia","day"],["da","of-the"],["tormenta.","torment."]]},
  {num:15,words:[["E","And"],["o","the"],["seu","his"],["rei","king"],["irá","will-go"],["para","for"],["o","the"],["cativeiro,","bondage,"],["ele","he"],["e","and"],["os","the"],["seus","their"],["príncipes","princes"],["juntamente,","together,"],["diz","says"],["o","the"],["Senhor.","Lord."]]}
];
var v2 = [
  {num:1,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["de","of"],["Moabe,","Moab,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["queimou","burnt"],["os","the"],["ossos","bones"],["do rei","king's"],["de","of"],["Edom,","Edom,"],["até","until"],["os","the"],["tornar","become"],["em","in"],["cal.","lime."]]},
  {num:2,words:[["Por isso","therefore"],["porei","I-will-place"],["fogo","fire"],["a","to"],["Moabe,","Moab,"],["e","and"],["consumirá","devour"],["os","the"],["palácios","palaces"],["de","of"],["Queriote;","Kerioth;"],["e","and"],["Moabe","Moab"],["morrerá","will-die"],["com","with"],["grande","great"],["estrondo,","noise,"],["com","with"],["alarido,","shouting,"],["com","with"],["sonido","sound"],["de","of"],["buzina.","trumpet."]]},
  {num:3,words:[["E","And"],["exterminarei","I-will-reverse"],["o","the"],["juiz","judge"],["do","of-the"],["meio","midst"],["dele,","of-him,"],["e","and"],["todos","all"],["os","of"],["seus","their"],["príncipes","princes"],["com","with"],["ele","he"],["matarei,","I-will-slay,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:4,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["de","of"],["Judá,","Judah,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["rejeitaram","they-rejected"],["a","the"],["lei","law"],["do","of-the"],["Senhor,","Lord,"],["e","and"],["não","not"],["guardaram","they-kept"],["os","the"],["seus","their"],["estatutos,","statutes,"],["e","and"],["as","the"],["suas","their"],["mentiras","lies"],["os","them"],["enganaram,","they-deceived,"],["após","after"],["as","the"],["quais","what"],["andaram","they-walked"],["seus","their"],["pais.","fathers."]]},
  {num:5,words:[["Por isso","therefore"],["porei","I-will-place"],["fogo","fire"],["a","to"],["Judá,","Judah,"],["e","and"],["consumirá","devour"],["os","the"],["palácios","palaces"],["de","of"],["Jerusalém.","Jerusalem."]]},
  {num:6,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["três","three"],["transgressões","transgressions"],["de","of"],["Israel,","Israel,"],["e","and"],["por","by"],["quatro,","four,"],["não","not"],["afastarei","I-will-remove"],["o","the"],["castigo,","chastisement,"],["porque","because"],["vendem","sparrows"],["o","the"],["justo","fair"],["por","by"],["dinheiro,","money,"],["e","and"],["o","him"],["necessitado,","needy,"],["por","by"],["um","a"],["par","pair"],["de","of"],["sapatos,","shoes,"]]},
  {num:7,words:[["Suspirando","Aching"],["pelo","by-the"],["pó","dust"],["da","of-the"],["terra","earth"],["sobre","upon"],["a","the"],["cabeça","head"],["dos","of-the"],["pobres,","poor,"],["e","and"],["pervertem","pant"],["o","the"],["caminho","way"],["dos","of-the"],["mansos;","meek;"],["e","and"],["o","the"],["homem","man"],["e","and"],["seu","his"],["pai","father"],["achegam-se","they-draw-near-themselves"],["a","to"],["uma","a"],["mesma","same"],["moça,","damsel,"],["para","to"],["profanarem","to-profane"],["o","the"],["meu","my"],["santo","holy"],["nome.","name."]]},
  {num:8,words:[["E","And"],["se","if"],["deitam","they-lay"],["junto a","beside"],["qualquer","any"],["altar","altar"],["sobre","upon"],["as","the"],["roupas","clothes"],["empenhadas,","pledge,"],["e","and"],["bebem","they-drink"],["o","the"],["vinho","wine"],["dos","of-the"],["que","that"],["foram","they-were"],["multados","pledge"],["na","in-the"],["casa","house"],["de","of"],["seus","their"],["deuses.","gods."]]},
  {num:9,words:[["Não obstante","nevertheless"],["eu","I"],["ter","have"],["destruído","destroyed"],["diante","before"],["deles","of-them"],["o","the"],["amorreu,","amorite,"],["cuja","whose"],["altura","height"],["foi","was"],["como","as"],["a","the"],["altura","height"],["dos","of-the"],["cedros,","cedars,"],["e","and"],["foi","was"],["forte","strong"],["como","as"],["os","the"],["carvalhos;","oaks;"],["mas","but"],["destruí","I-destroyed"],["o","the"],["seu","his"],["fruto","fruit"],["por","by"],["cima,","above,"],["e","and"],["as","the"],["suas","his"],["raízes","roots"],["por","by"],["baixo.","downward."]]},
  {num:10,words:[["Também","Also"],["vos","you"],["fiz","I-made"],["subir","go-up"],["da","of-the"],["terra do","egypt"],["Egito,","Egypt,"],["e","and"],["quarenta","forty"],["anos","years"],["vos","you"],["guiei","I-directed"],["no","in-the"],["deserto,","wilderness,"],["para que","that"],["possuísseis","you-possessed"],["a","to"],["terra do","egypt"],["amorreu.","amorite."]]},
  {num:11,words:[["E","And"],["alguns","some"],["dentre","from"],["vossos","your"],["filhos","children"],["suscitei","I-raised-up"],["para","for"],["profetas,","prophets,"],["e","and"],["alguns","some"],["dentre","from"],["os","the"],["vossos","your"],["jovens,","young,"],["para","for"],["nazireus.","nazarite."],["E","And"],["não","not"],["é","is"],["isso","that"],["assim,","thus,"],["filhos","children"],["de","of"],["Israel?","Israel?"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:12,words:[["Mas","But"],["vós","you"],["aos","to-the"],["nazireus","nazarite"],["destes","of-this"],["vinho","wine"],["para","to"],["beber,","drink,"],["e","and"],["aos","to-the"],["profetas","prophets"],["mandastes,","you-commanded,"],["dizendo:","saying:"],["Não","Not"],["profetizareis.","you-will-prophesy."]]},
  {num:13,words:[["Eis que","behold"],["eu","I"],["vos","you"],["apertarei","I-will-press"],["no","in-the"],["vosso","your"],["lugar","place"],["como se","as-if"],["aperta","presses"],["um","a"],["carro","chariot"],["cheio","full"],["de","of"],["feixes.","sheaves."]]},
  {num:14,words:[["Assim,","Thus,"],["perecerá","will-perish"],["a","the"],["fuga","flight"],["ao","to-the"],["ligeiro;","light;"],["nem","nor"],["o","the"],["forte","strong"],["corroborará","flight"],["a","the"],["sua","his"],["força,","strength,"],["nem","nor"],["o","the"],["valente","brave"],["livrará","will-free"],["a","the"],["sua","his"],["vida.","life."]]},
  {num:15,words:[["E","And"],["não","not"],["ficará","will-remain"],["em","in"],["pé","foot"],["o","the"],["que","that"],["leva","carries"],["o","the"],["arco,","bow,"],["nem","nor"],["o","the"],["ligeiro","light"],["de","of"],["pés","feet"],["se","himself"],["livrará,","will-free,"],["nem","nor"],["tampouco","neither"],["o","the"],["que","that"],["vai","goes"],["montado","rid"],["a","to"],["cavalo","horse"],["livrará","will-free"],["a","the"],["sua","his"],["alma.","soul."]]},
  {num:16,words:[["E","And"],["o","the"],["mais","more"],["corajoso","brave"],["entre","among"],["os","the"],["valentes","brave"],["fugirá","will-flee"],["nu","naked"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor.","Lord."]]}
];
var v3 = [
  {num:1,words:[["Ouvi","Hear"],["esta","this"],["palavra","word"],["que","that"],["o","the"],["Senhor","Lord"],["fala","speech"],["contra","against"],["vós,","you,"],["filhos","children"],["de","of"],["Israel,","Israel,"],["a saber,","namely"],["contra","against"],["toda","all"],["a","the"],["geração","generation"],["que","that"],["fiz","I-made"],["subir","go-up"],["da","of-the"],["terra do","egypt"],["Egito,","Egypt,"],["dizendo:","saying:"]]},
  {num:2,words:[["De","Of"],["todas","all"],["as","the"],["gerações","generations"],["da","of-the"],["terra","earth"],["só","only"],["a","to"],["vós","you"],["vos","you"],["conheci;","I-knew;"],["portanto,","therefore,"],["vos","you"],["castigarei","I-punish"],["por","by"],["todas","all"],["as","of"],["vossas","your"],["injustiças.","insult."]]},
  {num:3,words:[["Porventura","Perchance"],["andarão","they-will-walk"],["dois","two"],["juntos,","together,"],["se","if"],["não","not"],["estiverem","they-will-be"],["de","of"],["acordo?","according?"]]},
  {num:4,words:[["Bramará","Roar"],["o","the"],["leão","lion"],["no","in-the"],["bosque,","forest,"],["sem","without"],["que","that"],["ele","he"],["tenha","has"],["presa?","arrested?"],["levantará","will-raise-up"],["o","the"],["leãozinho","lion"],["a","the"],["sua","his"],["voz","voice"],["da","of-the"],["sua","his"],["cova,","pit,"],["se","if"],["nada","nothing"],["tiver","will-have"],["apanhado?","caught?"]]},
  {num:5,words:[["Cairá","Will-fall"],["a","the"],["ave","bird"],["no","in-the"],["laço","I-snare"],["em","in"],["terra,","earth,"],["se","if"],["não","not"],["houver","will-have"],["armadilha","snare"],["para","for"],["ela?","she?"],["levantar-se-á","will-arise"],["o","the"],["laço","I-snare"],["da","of-the"],["terra,","earth,"],["sem","without"],["que","that"],["tenha","has"],["apanhado","caught"],["alguma","some"],["coisa?","thing?"]]},
  {num:6,words:[["Tocar-se-á","Will-touch-himself"],["a","the"],["buzina","trumpet"],["na","in-the"],["cidade,","city,"],["e","and"],["o","the"],["povo","people"],["não","not"],["estremecerá?","will-tremble?"],["Sucederá","Will-happen"],["algum","some"],["mal","evil"],["na","in-the"],["cidade,","city,"],["o","the"],["qual","which"],["o","the"],["Senhor","Lord"],["não","not"],["tenha","has"],["feito?","made?"]]},
  {num:7,words:[["Certamente","Certainly"],["o","the"],["Senhor","Lord"],["Deus","God"],["não","not"],["fará","will-make"],["coisa","thing"],["alguma,","some,"],["sem","without"],["ter","have"],["revelado","revealed"],["o","the"],["seu","his"],["segredo","secret"],["aos","to-the"],["seus","his"],["servos,","servants,"],["os","the"],["profetas.","prophets."]]},
  {num:8,words:[["Bramou","Ranted"],["o","the"],["leão,","lion,"],["quem","who"],["não","not"],["temerá?","will-fear?"],["Falou","Spoke"],["o","the"],["Senhor","Lord"],["Deus,","God,"],["quem","who"],["não","not"],["profetizará?","will-prophesy?"]]},
  {num:9,words:[["Fazei","Make"],["ouvir","to-hear"],["isso","that"],["nos","in-the"],["palácios","palaces"],["de","of"],["Asdode,","Ashdod,"],["e","and"],["nos","in-the"],["palácios","palaces"],["da","of-the"],["terra do","egypt"],["Egito,","Egypt,"],["e","and"],["dizei:","say:"],["Ajuntai-vos","Add-you"],["sobre","upon"],["os","the"],["montes","mountains"],["de","of"],["Samaria,","Samaria,"],["e","and"],["vede","see"],["os","the"],["grandes","great"],["alvoroços","excitement"],["no","in-the"],["meio","midst"],["dela,","of-her,"],["e","and"],["os","the"],["oprimidos","oppressed"],["dentro","within"],["dela.","of-her."]]},
  {num:10,words:[["Porque","Because"],["não","not"],["sabem","they-know"],["fazer","make"],["o","the"],["que","that"],["é","is"],["reto,","fair,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["entesourando","lastsing"],["nos","in-the"],["seus","their"],["palácios","palaces"],["a","the"],["violência","violence"],["e","and"],["a","the"],["destruição.","destruction."]]},
  {num:11,words:[["Portanto,","Therefore,"],["o","the"],["Senhor","Lord"],["Deus","God"],["diz","says"],["assim:","thus:"],["O","The"],["inimigo","enemy"],["virá,","will-come,"],["e","and"],["cercará","will-besiege"],["a","the"],["terra,","land,"],["derrubará","will-overthrow"],["de","of"],["ti","you"],["a","the"],["tua","your"],["fortaleza,","fortification,"],["e","and"],["os","the"],["teus","your"],["palácios","palaces"],["serão","they-will-be"],["saqueados.","booty."]]},
  {num:12,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Assim como","even-as"],["o","the"],["pastor","shepherd"],["livra","deliver"],["da","of-the"],["boca","mouth"],["do","of-the"],["leão","lion"],["as","to"],["duas","two"],["pernas,","legs,"],["ou","or"],["um","a"],["pedacinho","piece"],["da","of-the"],["orelha,","ear,"],["assim","thus"],["serão","they-will-be"],["livrados","freed"],["os","the"],["filhos","children"],["de","of"],["Israel","Israel"],["que","that"],["habitam","they-dwell"],["em","in"],["Samaria,","Samaria,"],["no","in-the"],["canto","corner"],["da","of-the"],["cama,","bed,"],["e","and"],["em","in"],["Damasco,","Damascus,"],["num","in-a"],["leito.","bed."]]},
  {num:13,words:[["Ouvi,","Hear,"],["e","and"],["protestai","protest"],["na","in-the"],["casa","house"],["de","of"],["Jacó,","Jacob,"],["diz","says"],["o","the"],["Senhor","Lord"],["Deus,","God,"],["o","the"],["Deus","God"],["dos","of-the"],["Exércitos;","Armies;"]]},
  {num:14,words:[["Naquele","In-that"],["dia,","day,"],["em","in"],["que","that"],["eu","I"],["castigar","to-punish"],["Israel","Israel"],["pelas","by-the"],["suas","their"],["transgressões,","transgressions,"],["também","also"],["castigarei","I-punish"],["os","the"],["altares","altars"],["de","of"],["Betel;","Beth-El;"],["e","and"],["os","them"],["chifres","horns"],["do","of-the"],["altar","altar"],["serão","they-will-be"],["cortados,","hewn,"],["e","and"],["cairão","they-will-fall"],["em","in"],["terra.","ground."]]},
  {num:15,words:[["E","And"],["ferirei","I-will-hurt"],["a","the"],["casa","house"],["de","of"],["inverno","winter"],["com","with"],["a","the"],["casa","house"],["de","of"],["verão;","summer;"],["e","and"],["as","the"],["casas","houses"],["de","of"],["marfim","ivory"],["perecerão,","they-will-perish,"],["e","and"],["as","to"],["grandes","great"],["casas","houses"],["terão","they-will-have"],["fim,","end,"],["diz","says"],["o","the"],["Senhor.","Lord."]]}
];
var v4 = [
  {num:1,words:[["Ouvi","Hear"],["esta","this"],["palavra,","word,"],["vós,","you,"],["vacas","cow"],["de","of"],["Basã,","Bashan,"],["vós,","you,"],["que","that"],["estais","you-are"],["no","in-the"],["monte","mountain"],["de","of"],["Samaria,","Samaria,"],["vós,","you,"],["que","that"],["oprimis","crush"],["os","the"],["pobres,","poor,"],["que","that"],["quebrantais","crush"],["os","the"],["necessitados,","needy,"],["vós,","you,"],["que","that"],["dizeis","you-say"],["a","to"],["seus","their"],["senhores:","masters:"],["Dai","Give"],["cá,","here,"],["para que","that"],["bebamos.","we-drink."]]},
  {num:2,words:[["Jurou","Swore"],["o","the"],["Senhor","Lord"],["Deus,","God,"],["pela","by-the"],["sua","his"],["santidade,","holiness,"],["que","that"],["eis que","behold"],["dias","days"],["estão","they-are"],["para","to"],["vir","come"],["sobre","upon"],["vós,","you,"],["em","in"],["que","that"],["vos","you"],["levarão","they-will-carry"],["com","with"],["anzóis,","hook,"],["e","and"],["a","to"],["vossos","your"],["descendentes,","descendants,"],["com","with"],["anzóis","hook"],["de","of"],["pesca.","fish."]]},
  {num:3,words:[["E","And"],["saireis","you-will-go-forth"],["pelas","by-the"],["brechas,","breach,"],["uma","a"],["após","after"],["outra,","another,"],["e","and"],["lançareis","you-will-cast"],["fora","outside"],["o","the"],["que","that"],["levastes","you-carried"],["para","for"],["o","the"],["palácio,","palace,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:4,words:[["Vinde","Come"],["a","to"],["Betel,","Beth-El,"],["e","and"],["transgredi;","I-transgressed;"],["em","in"],["Gilgal","Gilgal"],["aumentai","increase"],["as","the"],["transgressões,","transgressions,"],["e","and"],["de","of"],["manhã","morning"],["trazei","bring"],["os","the"],["vossos","your"],["sacrifícios,","sacrifices,"],["e","and"],["os","the"],["vossos","your"],["dízimos","tithes"],["ao","to-the"],["terceiro","third"],["dia.","day."]]},
  {num:5,words:[["E","And"],["queimai","burn"],["o","the"],["sacrifício","sacrifice"],["de","of"],["louvores","praises"],["do","of-the"],["pão","bread"],["levedado,","leavened,"],["e","and"],["apregoai","brokenhearted"],["os","the"],["sacrifícios","sacrifices"],["voluntários,","voluntary,"],["fazei-o","make-him"],["ouvir;","to-hear;"],["porque","because"],["assim","thus"],["o","him"],["quereis,","you-will,"],["ó","O"],["filhos","children"],["de","of"],["Israel,","Israel,"],["disse","said"],["o","the"],["Senhor","Lord"],["Deus.","God."]]},
  {num:6,words:[["Por isso","therefore"],["também","also"],["vos","you"],["dei","I-gave"],["dentes","teeth"],["limpos","clean"],["em","in"],["todas","all"],["as","of"],["vossas","your"],["cidades,","cities,"],["e","and"],["falta","lack"],["de","of"],["pão","bread"],["em","in"],["todos","all"],["os","of"],["vossos","your"],["lugares;","places;"],["contudo","yet"],["não","not"],["vos","you"],["convertestes","you-converted"],["a","to"],["mim,","me,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:7,words:[["Além","Beyond"],["disso,","of-that,"],["retive","I-restrained"],["de","of"],["vós","you"],["a","the"],["chuva,","rain,"],["faltando","wantinging"],["ainda","yet"],["três","three"],["meses","months"],["até","until"],["a","it"],["ceifa;","harvest;"],["e","and"],["fiz","I-made"],["chover","to-rain"],["sobre","upon"],["uma","a"],["cidade,","city,"],["e","and"],["sobre","upon"],["outra","other"],["cidade","city"],["não","not"],["fiz","I-made"],["chover;","to-rain;"],["sobre","upon"],["um","a"],["campo","field"],["choveu,","rained,"],["mas","but"],["o","the"],["outro,","another,"],["sobre","upon"],["o","the"],["qual","which"],["não","not"],["choveu,","rained,"],["secou.","withered."]]},
  {num:8,words:[["E","And"],["andaram","they-walked"],["errantes","erratic"],["duas","two"],["ou","or"],["três","three"],["cidades","cities"],["indo","going"],["a","the"],["outra","other"],["cidade,","city,"],["para","to"],["beberem","to-drink"],["água,","water,"],["mas","but"],["não","not"],["se","themselves"],["saciaram;","they-husks;"],["contudo","yet"],["não","not"],["vos","you"],["convertestes","you-converted"],["a","to"],["mim,","me,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:9,words:[["Feri-vos","I-hurt-you"],["com","with"],["queimadura,","blasting,"],["e","and"],["com","with"],["ferrugem;","rust;"],["a","the"],["multidão","multitude"],["das","of-the"],["vossas","your"],["hortas,","orchards,"],["e","and"],["das","of-the"],["vossas","your"],["vinhas,","vineyards,"],["e","and"],["das","of-the"],["vossas","your"],["figueiras,","sycomore,"],["e","and"],["das","of-the"],["vossas","your"],["oliveiras","olive-trees"],["a","the"],["locusta","grasshopper"],["comeu;","ate;"],["contudo","yet"],["não","not"],["vos","you"],["convertestes","you-converted"],["a","to"],["mim,","me,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:10,words:[["Enviei","I-sent"],["a","the"],["peste","pestilence"],["contra","against"],["vós,","you,"],["à","to-the"],["maneira","manner"],["do","of-the"],["Egito;","Egypt;"],["os","the"],["vossos","your"],["jovens","young"],["matei","I-slew"],["à","to-the"],["espada,","sword,"],["e","and"],["os","the"],["vossos","your"],["cavalos","horses"],["deixei","I-left"],["levar","to-carry"],["presos,","prisoner,"],["e","and"],["o","the"],["fedor","stink"],["dos","of-the"],["vossos","your"],["exércitos","armies"],["fiz","I-made"],["subir","go-up"],["às","to-the"],["vossas","your"],["narinas;","nostrils;"],["contudo","yet"],["não","not"],["vos","you"],["convertestes","you-converted"],["a","to"],["mim,","me,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:11,words:[["Subverti","I-destroyed"],["alguns","some"],["dentre","from"],["vós,","you,"],["como","as"],["Deus","God"],["subverteu","destroyed"],["Sodoma","Sodom"],["e","and"],["Gomorra,","Gomorrah,"],["sendo","being"],["vós","you"],["como","as"],["um","a"],["tição","brand"],["arrebatado","carried-away"],["do","of-the"],["incêndio;","bewail;"],["contudo","yet"],["não","not"],["vos","you"],["convertestes","you-converted"],["a","to"],["mim,","me,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:12,words:[["Portanto,","Therefore,"],["assim","thus"],["te","you"],["farei,","I-will-make,"],["ó","O"],["Israel!","Israel!"],["Porquanto","Because"],["isto","this"],["te","you"],["farei,","I-will-make,"],["prepara-te,","prepares-you,"],["ó","O"],["Israel,","Israel,"],["para","to"],["encontrares","to-find"],["o","the"],["teu","your"],["Deus.","God."]]},
  {num:13,words:[["Porque","Because"],["eis que","behold"],["aquele","that"],["que","that"],["forma","form"],["os","the"],["montes,","mountains,"],["e","and"],["cria","believed"],["o","the"],["vento,","wind,"],["e","and"],["declara","declares"],["ao","to-the"],["homem","man"],["qual","which"],["seja","is"],["o","the"],["seu","his"],["pensamento,","thought,"],["o","the"],["que","that"],["faz","makes"],["da","of-the"],["manhã","morning"],["trevas,","darkness,"],["e","and"],["pisa","crushes"],["os","the"],["altos","places"],["da","of-the"],["terra,","earth,"],["o","the"],["Senhor","Lord"],["Deus","God"],["dos","of-the"],["Exércitos","Armies"],["é","is"],["o","the"],["seu","his"],["nome.","name."]]}
];
var v5 = [
  {num:1,words:[["Ouvi","Hear"],["esta","this"],["palavra,","word,"],["que","that"],["levanto","I-raise-up"],["sobre","upon"],["vós","you"],["como","as"],["lamentação,","lamentation,"],["ó","O"],["casa","house"],["de","of"],["Israel.","Israel."]]},
  {num:2,words:[["A","The"],["virgem","virgin"],["de","of"],["Israel","Israel"],["caiu,","fell,"],["nunca","never"],["mais","more"],["tornará","will-become"],["a","to"],["levantar-se;","arise;"],["desamparada","abandoned"],["está","is"],["na","in-the"],["sua","her"],["terra,","land,"],["não","not"],["há","there-is"],["quem","who"],["a","to"],["levante.","raises-up."]]},
  {num:3,words:[["Porque","Because"],["assim diz","thus-saith"],["o","the"],["Senhor","Lord"],["Deus:","God:"],["A","The"],["cidade","city"],["da","of-the"],["qual","which"],["saem","they-go-forth"],["mil","thousand"],["conservará","will-conserve"],["cem,","hundred,"],["e","and"],["aquela","that"],["da","of-the"],["qual","which"],["saem","they-go-forth"],["cem","hundred"],["conservará","will-conserve"],["dez","ten"],["à","to-the"],["casa","house"],["de","of"],["Israel.","Israel."]]},
  {num:4,words:[["Porque","Because"],["assim diz","thus-saith"],["o","the"],["Senhor","Lord"],["à","to-the"],["casa","house"],["de","of"],["Israel:","Israel:"],["Buscai-me,","Seek-me,"],["e","and"],["vivei.","weaker."]]},
  {num:5,words:[["Porém","But"],["não","not"],["busqueis","you-seek"],["Betel,","Beth-El,"],["nem","nor"],["venhais","you-come"],["a","to"],["Gilgal,","Gilgal,"],["nem","nor"],["passeis","you-pass"],["a","the"],["Berseba,","Beer-Sheba,"],["porque","because"],["Gilgal","Gilgal"],["certamente","certainly"],["será","will-be"],["levado","brought"],["cativo,","captive,"],["e","and"],["Betel","Beth-El"],["será","will-be"],["desfeito","disrupted"],["em","in"],["nada.","nothing."]]},
  {num:6,words:[["Buscai","Seek"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["vivei,","weaker,"],["para que","that"],["não","not"],["acometa","assaults"],["a","the"],["casa","house"],["de","of"],["José","Joseph"],["como","as"],["um","a"],["fogo,","fire,"],["e","and"],["a","it"],["consuma,","consummates,"],["e","and"],["não","not"],["haja","has"],["em","in"],["Betel","Beth-El"],["quem","who"],["o","it"],["apague.","extinguishes."]]},
  {num:7,words:[["Vós","You"],["que","that"],["perverteis","wormwood"],["o","the"],["juízo","judgment"],["em","in"],["absinto,","wormwood,"],["e","and"],["deitais","you-lay"],["por","by"],["terra","earth"],["a","the"],["justiça,","righteousness,"]]},
  {num:8,words:[["Buscai","Seek"],["o","the"],["que","that"],["faz","makes"],["o","the"],["Sete-Estrelo,","Sete-estrelo,"],["e","and"],["o","the"],["Órion,","Orion,"],["e","and"],["torna","becomes"],["a","the"],["sombra","shadow"],["da","of-the"],["noite","night"],["em","in"],["manhã,","morning,"],["e","and"],["escurece","to-escurecer"],["o","the"],["dia","day"],["como","as"],["a","the"],["noite,","night,"],["que","that"],["chama","flame"],["as","the"],["águas","waters"],["do","of-the"],["mar,","sea,"],["e","and"],["as","them"],["derrama","pours"],["sobre","upon"],["a","the"],["terra,","earth,"],["o","the"],["Senhor","Lord"],["é","is"],["o","the"],["seu","his"],["nome.","name."]]},
  {num:9,words:[["O","The"],["que","that"],["promove","promotes"],["súbita","abrupt"],["destruição","destruction"],["contra","against"],["o","the"],["forte,","strong,"],["de modo que","so-that"],["venha","comes"],["a","the"],["assolação","desolation"],["contra","against"],["a","the"],["fortaleza.","fortification."]]},
  {num:10,words:[["Na","In-the"],["porta","exit"],["odeiam","they-hate"],["o","the"],["que","that"],["os","them"],["repreende,","admonishes,"],["e","and"],["abominam","they-abhor"],["o","the"],["que","that"],["fala","speech"],["sinceramente.","sincerely."]]},
  {num:11,words:[["Portanto,","Therefore,"],["visto que","seeing-that"],["pisais","you-crush"],["o","the"],["pobre,","poor,"],["e","and"],["dele","of-him"],["tomais","you-take"],["um","a"],["tributo","tribute"],["de","of"],["trigo,","wheat,"],["edificastes","you-built"],["casas","houses"],["de","of"],["pedras","stones"],["lavradas,","embroidered,"],["mas","but"],["nelas","in-him"],["não","not"],["habitareis;","you-will-dwell;"],["vinhas","vineyards"],["desejáveis","you-desired"],["plantastes,","you-planted,"],["mas","but"],["não","not"],["bebereis","you-will-drink"],["do","of-the"],["seu","your"],["vinho.","wine."]]},
  {num:12,words:[["Porque","Because"],["sei","I-know"],["que","that"],["são","they-are"],["muitas","many"],["as","the"],["vossas","your"],["transgressões,","transgressions,"],["e","and"],["graves,","you-engrave,"],["os","the"],["vossos","your"],["pecados;","sins;"],["afligem","they-afflict"],["o","the"],["justo,","fair,"],["tomam","they-take"],["resgate,","ransom,"],["e","and"],["rejeitam","they-reject"],["os","the"],["necessitados","needy"],["na","in-the"],["porta.","exit."]]},
  {num:13,words:[["Portanto,","Therefore,"],["o","the"],["prudente","prudent"],["naquele","in-that"],["tempo","time"],["se","himself"],["calará,","will-still,"],["porque","because"],["o","the"],["tempo","time"],["será","will-be"],["mau.","bad."]]},
  {num:14,words:[["Buscai","Seek"],["o","the"],["bem,","good,"],["e","and"],["não","not"],["o","the"],["mal,","evil,"],["para que","that"],["vivais;","live;"],["e","and"],["assim","thus"],["o","the"],["Senhor,","Lord,"],["o","the"],["Deus","God"],["dos","of-the"],["Exércitos,","Armies,"],["estará","will-be"],["convosco,","with-you,"],["como","as"],["dizeis.","you-say."]]},
  {num:15,words:[["Odiai","Hate"],["o","the"],["mal,","evil,"],["e","and"],["amai","mammon"],["o","the"],["bem,","good,"],["e","and"],["estabelecei","establish"],["o","the"],["juízo","judgment"],["na","in-the"],["porta;","exit;"],["porventura","perchance"],["o","the"],["Senhor,","Lord,"],["o","the"],["Deus","God"],["dos","of-the"],["Exércitos,","Armies,"],["terá","will-have"],["piedade","pity"],["do","of-the"],["remanescente","remnant"],["de","of"],["José.","Joseph."]]},
  {num:16,words:[["Portanto,","Therefore,"],["assim diz","thus-saith"],["o","the"],["Senhor","Lord"],["Deus","God"],["dos","of-the"],["Exércitos,","Armies,"],["o","the"],["Senhor:","Lord:"],["Em","In"],["todas","all"],["as","the"],["ruas","streets"],["haverá","there-will-be"],["pranto,","mourning,"],["e","and"],["em","in"],["todas","all"],["as","the"],["estradas","highways"],["dirão:","they-will-say:"],["Ai!","Wo!"],["ai!","wo!"],["E","And"],["o","the"],["lavrador","husbandman"],["chamarão","they-will-call"],["para","for"],["o","the"],["choro,","I-weeping,"],["e","and"],["para","for"],["o","the"],["pranto","mourning"],["os","the"],["que","that"],["souberem","they-will-know"],["prantear.","mourn."]]},
  {num:17,words:[["E","And"],["em","in"],["todas","all"],["as","the"],["vinhas","vineyards"],["haverá","there-will-be"],["pranto;","mourning;"],["porque","because"],["passarei","I-will-pass"],["pelo","by-the"],["meio","midst"],["de","of"],["ti,","you,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:18,words:[["Ai","Wo"],["daqueles","of-that"],["que","that"],["desejam","they-desire"],["o","the"],["dia","day"],["do","of-the"],["Senhor!","Lord!"],["Para que,","that"],["pois,","for,"],["vos","you"],["será","will-be"],["este","this"],["dia","day"],["do","of-the"],["Senhor?","Lord?"],["Trevas","Darkness"],["será","will-be"],["e","and"],["não","not"],["luz.","light."]]},
  {num:19,words:[["Como","As"],["o","the"],["que","that"],["foge","flees"],["de","of"],["diante","before"],["do","of-the"],["leão,","lion,"],["e","and"],["se","if"],["encontra","finds"],["com","with"],["ele","he"],["o","the"],["urso;","bear;"],["ou","or"],["como se","as-if"],["entrasse","entered"],["numa","in-a"],["casa,","house,"],["e","and"],["a","the"],["sua","his"],["mão","hand"],["encostasse","leant"],["à","to-the"],["parede,","wall,"],["e","and"],["fosse","was"],["mordido","bitten"],["por","by"],["uma","a"],["cobra.","serpent."]]},
  {num:20,words:[["Não","Not"],["será,","will-be,"],["pois,","for,"],["o","the"],["dia","day"],["do","of-the"],["Senhor","Lord"],["trevas","darkness"],["e","and"],["não","not"],["luz?","light?"],["E","And"],["escuridão,","darkness,"],["sem","without"],["que","that"],["haja","has"],["resplendor?","brightness?"]]},
  {num:21,words:[["Odeio,","I-hate,"],["desprezo","contempt"],["as","the"],["vossas","your"],["festas,","feasts,"],["e","and"],["as","the"],["vossas","your"],["assembleias","assemblies"],["solenes","solemn"],["não","not"],["me","me"],["darão","they-will-give"],["bom","good"],["cheiro.","smell."]]},
  {num:22,words:[["Porque","Because"],["ainda que","although"],["me","me"],["ofereceis","you-dedicate"],["holocaustos,","burnt,"],["como","as"],["também","also"],["as","the"],["vossas","your"],["ofertas","offerings"],["de","of"],["manjares,","meat,"],["não","not"],["me","me"],["agrado","I-please"],["delas;","of-them;"],["nem","nor"],["atentarei","I-will-assault"],["para","for"],["as","the"],["ofertas","offerings"],["pacíficas","offerings"],["de","of"],["vossos","your"],["animais","beasts"],["gordos.","leanness."]]},
  {num:23,words:[["Afasta","Removes"],["de","of"],["mim","me"],["o","the"],["estrépito","stamping"],["dos","of-the"],["teus","your"],["cânticos;","songs;"],["porque","because"],["não","not"],["ouvirei","I-will-hear"],["as","the"],["melodias","melody"],["dos","of-the"],["teus","your"],["instrumentos.","instruments."]]},
  {num:24,words:[["Corra,","Flows,"],["porém,","but,"],["o","the"],["juízo","judgment"],["como","as"],["as","the"],["águas,","waters,"],["e","and"],["a","the"],["justiça,","righteousness,"],["como","as"],["o","the"],["ribeiro","brook"],["impetuoso.","lawless."]]},
  {num:25,words:[["Haveis-me","Exist-me"],["porventura","perchance"],["oferecido","departure"],["sacrifícios","sacrifices"],["e","and"],["ofertas","offerings"],["no","in-the"],["deserto","wilderness"],["por","by"],["quarenta","forty"],["anos,","years,"],["ó","O"],["casa","house"],["de","of"],["Israel?","Israel?"]]},
  {num:26,words:[["Antes","Before"],["levastes","you-carried"],["a","the"],["tenda","tent"],["de","of"],["vosso","your"],["Moloque,","Molech,"],["e","and"],["a","the"],["estátua","statue"],["das","of-the"],["vossas","your"],["imagens,","images,"],["a","the"],["estrela","star"],["do","of-the"],["vosso","your"],["deus,","god,"],["que","that"],["fizestes","you-made"],["para","for"],["vós","you"],["mesmos.","yourselves."]]},
  {num:27,words:[["Portanto,","Therefore,"],["vos","you"],["levarei","I-will-carry"],["cativos,","captives,"],["para","for"],["além de","besides"],["Damasco,","Damascus,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["cujo","whose"],["nome","name"],["é","is"],["o","the"],["Deus","God"],["dos","of-the"],["Exércitos.","Armies."]]}
];
var v6 = [
  {num:1,words:[["Ai","Wo"],["dos","of-the"],["sossegados","calm"],["em","in"],["Sião,","Zion,"],["e","and"],["dos","of-the"],["seguros","safely"],["no","in-the"],["monte","mountain"],["de","of"],["Samaria,","Samaria,"],["que","that"],["têm","they-have"],["nome","name"],["entre","among"],["as","the"],["primeiras","first"],["das","of-the"],["nações,","nations,"],["e","and"],["aos","to-the"],["quais","what"],["se","if"],["foi","was"],["a","the"],["casa","house"],["de","of"],["Israel!","Israel!"]]},
  {num:2,words:[["Passai","Pass"],["a","to"],["Calne,","Calneh,"],["e","and"],["vede;","see;"],["e","and"],["dali","of-at that place"],["ide","go"],["à","to-the"],["grande","great"],["Hamate;","Hamath;"],["e","and"],["descei","descend"],["a","to"],["Gate","Gath"],["dos","of-the"],["filisteus;","philistines;"],["são","they-are"],["melhores","better"],["que","that"],["estes","these"],["reinos?","kingdoms?"],["ou","or"],["maior","greater"],["o","the"],["seu","their"],["termo","border"],["do que","than"],["o","the"],["vosso","your"],["termo?","border?"]]},
  {num:3,words:[["Vós","You"],["que","that"],["afastais","you-remove"],["o","the"],["dia","day"],["mau,","bad,"],["e","and"],["fazeis","you-make"],["chegar","to-come"],["o","the"],["assento","seat"],["de","of"],["violência;","violence;"]]},
  {num:4,words:[["Os","The"],["que","that"],["dormem","they-sleep"],["em","in"],["camas","beds"],["de","of"],["marfim,","ivory,"],["e","and"],["se","if"],["estendem","they-stretch"],["sobre","upon"],["os","the"],["seus","their"],["leitos,","bed,"],["e","and"],["comem","they-eat"],["os","the"],["cordeiros","lambs"],["do","of-the"],["rebanho,","flock,"],["e","and"],["os","the"],["bezerros","calf"],["do","of-the"],["meio","midst"],["da","of-the"],["manada;","swine;"]]},
  {num:5,words:[["Que","That"],["cantam","they-sing"],["ao","to-the"],["som","sound"],["do","of-the"],["alaúde,","viol,"],["e","and"],["inventam","they-invent"],["para","for"],["si","himself"],["instrumentos","instruments"],["musicais,","musick,"],["assim como","even-as"],["Davi;","David;"]]},
  {num:6,words:[["Que","That"],["bebem","they-drink"],["vinho","wine"],["em","in"],["taças,","vials,"],["e","and"],["se","if"],["ungem","they-anoint"],["com","with"],["o","the"],["mais","more"],["excelente","excellent"],["óleo,","oil,"],["mas","but"],["não","not"],["se","themselves"],["afligem","they-afflict"],["pela","by-the"],["ruína","ruin"],["de","of"],["José;","Joseph;"]]},
  {num:7,words:[["Portanto,","Therefore,"],["agora","now"],["irão","they-will-go"],["em","in"],["cativeiro","bondage"],["entre","among"],["os","the"],["primeiros","first"],["dos","of-the"],["que","that"],["forem","they-will-be"],["em","in"],["cativeiro,","bondage,"],["e","and"],["cessarão","they-will-cease"],["as","to"],["orgias","orgy"],["dos","of-the"],["banqueteadores.","banquet."]]},
  {num:8,words:[["Jurou","Swore"],["o","the"],["Senhor","Lord"],["Deus","God"],["pela","by-the"],["sua","his"],["alma","soul"],["(diz","(says"],["o","the"],["Senhor","Lord"],["Deus","God"],["dos","of-the"],["Exércitos):","Armies):"],["Abomino","I-abhor"],["a","the"],["soberba","pride"],["de","of"],["Jacó,","Jacob,"],["e","and"],["odeio","I-hate"],["os","the"],["seus","his"],["palácios;","palaces;"],["e","and"],["entregarei","I-will-deliver"],["a","the"],["cidade","city"],["e","and"],["a","the"],["sua","his"],["plenitude.","fulness."]]},
  {num:9,words:[["E","And"],["acontecerá","will-come-to-pass"],["que,","that,"],["restando","remaining"],["dez","ten"],["homens","men"],["numa","in-a"],["casa,","house,"],["morrerão.","they-will-die."]]},
  {num:10,words:[["E","And"],["o","the"],["tio","uncle"],["de","of"],["alguém,","any,"],["aquele","that"],["que","that"],["o","the"],["queima,","burn,"],["o","him"],["tomará","will-take"],["para","to"],["levar","to-carry"],["os","the"],["ossos","bones"],["para","for"],["fora","outside"],["da","of-the"],["casa;","house;"],["e","and"],["dirá","will-say"],["ao","to-the"],["que","that"],["estiver","will-be"],["nos","in-the"],["cantos","corners"],["da","of-the"],["casa:","house:"],["Está","Is"],["ainda","yet"],["alguém","any"],["contigo?","with-you?"],["E","And"],["ele","he"],["dirá:","will-say:"],["Ninguém.","None."],["E","And"],["dirá","will-say"],["este:","this:"],["Cala-te,","Stilled-you,"],["porque","because"],["não","not"],["convém","befits"],["fazer","make"],["menção","mention"],["do","of-the"],["nome","name"],["do","of-the"],["Senhor.","Lord."]]},
  {num:11,words:[["Porque,","Because,"],["eis que","behold"],["o","the"],["Senhor","Lord"],["dá","gives"],["ordem,","order,"],["e","and"],["ferirá","will-hurt"],["a","the"],["casa","house"],["grande","great"],["de","of"],["quebraduras,","clefts,"],["e","and"],["a","the"],["casa","house"],["pequena,","small,"],["de","of"],["fendas.","you-split."]]},
  {num:12,words:[["Porventura","Perchance"],["correrão","they-will-flow"],["cavalos","horses"],["na","in-the"],["rocha?","rock?"],["arar-se-á","plough-himself"],["nela","in-it"],["com","with"],["bois?","oxen?"],["Porque","Because"],["vós","you"],["tornastes","you-became"],["o","the"],["juízo","judgment"],["em","in"],["fel,","gall,"],["e","and"],["o","the"],["fruto","fruit"],["da","of-the"],["justiça","righteousness"],["em","in"],["absinto.","wormwood."]]},
  {num:13,words:[["Vós","You"],["que","that"],["vos","you"],["alegrais","you-gladden"],["de","of"],["nada,","nothing,"],["vós","you"],["que","that"],["dizeis:","you-say:"],["Não","Not"],["nos","us"],["temos","we-have"],["nós","we"],["tornado","become"],["poderosos","mighty"],["por","by"],["nossa","our"],["força?","strength?"]]},
  {num:14,words:[["Porque,","Because,"],["eis que","behold"],["eu","I"],["levantarei","I-will-raise-up"],["sobre","upon"],["vós,","you,"],["ó","O"],["casa","house"],["de","of"],["Israel,","Israel,"],["um","a"],["povo,","people,"],["diz","says"],["o","the"],["Senhor","Lord"],["Deus","God"],["dos","of-the"],["Exércitos,","Armies,"],["e","and"],["oprimir-vos-ão,","oppress-you,"],["desde","since"],["a","the"],["entrada","entrance"],["de","of"],["Hamate","Hamath"],["até","until"],["o","the"],["ribeiro","brook"],["do","of-the"],["deserto.","wilderness."]]}
];
var v7 = [
  {num:1,words:[["O","The"],["Senhor","Lord"],["Deus","God"],["assim","thus"],["me","me"],["fez","made"],["ver,","see,"],["e eis que","and-behold"],["formava","achieved"],["gafanhotos","locusts"],["no","in-the"],["princípio","beginning"],["do","of-the"],["rebento","I-bud"],["da","of-the"],["erva","grass"],["serôdia,","mowings,"],["e eis que","and-behold"],["havia","there-was"],["a","the"],["erva","grass"],["serôdia","mowings"],["depois","afterwards"],["da","of-the"],["ceifa","harvest"],["do rei.","king's"]]},
  {num:2,words:[["E aconteceu que,","and-it-came-to-pass-that"],["como","as"],["eles","they"],["de todo","wholly"],["tivessem","they-had"],["comido","eaten"],["a","the"],["erva","grass"],["da","of-the"],["terra,","land,"],["eu","I"],["disse:","said:"],["Senhor","Lord"],["Deus,","God,"],["ora,","now,"],["perdoa;","forgives;"],["como se","as-if"],["levantará","will-raise-up"],["Jacó?","Jacob?"],["porque","because"],["é","is"],["pequeno.","small."]]},
  {num:3,words:[["Então","Then"],["o","the"],["Senhor","Lord"],["se","himself"],["arrependeu","repented"],["disso.","of-that."],["Isso","That"],["não","not"],["acontecerá,","will-come-to-pass,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:4,words:[["Assim","Thus"],["me","me"],["mostrou","showed"],["o","the"],["Senhor","Lord"],["Deus,","God,"],["e eis que","and-behold"],["o","the"],["Senhor","Lord"],["Deus","God"],["chamava","called"],["para","to"],["contender","to-contend"],["por","by"],["fogo;","fire;"],["este","this"],["consumiu","consumed"],["o","the"],["grande","great"],["abismo,","gulf,"],["e","and"],["também","also"],["consumiu","consumed"],["uma","a"],["parte","part"],["da","of-the"],["terra.","land."]]},
  {num:5,words:[["Então","Then"],["eu","I"],["disse:","said:"],["Senhor","Lord"],["Deus,","God,"],["cessa","ceases"],["agora;","now;"],["como se","as-if"],["levantará","will-raise-up"],["Jacó?","Jacob?"],["porque","because"],["é","is"],["pequeno.","small."]]},
  {num:6,words:[["E","And"],["o","the"],["Senhor","Lord"],["se","himself"],["arrependeu","repented"],["disso.","of-that."],["Nem","Nor"],["isso","that"],["acontecerá,","will-come-to-pass,"],["disse","said"],["o","the"],["Senhor","Lord"],["Deus.","God."]]},
  {num:7,words:[["Mostrou-me","Showed-me"],["também","also"],["assim;","thus;"],["e eis que","and-behold"],["o","the"],["Senhor","Lord"],["estava","was"],["sobre","upon"],["um","a"],["muro,","wall,"],["feito","made"],["a","to"],["prumo;","I-plummet;"],["e","and"],["tinha","had"],["um","a"],["prumo","I-plummet"],["na","in-the"],["sua","his"],["mão.","hand."]]},
  {num:8,words:[["E","And"],["o","the"],["Senhor","Lord"],["me","me"],["disse:","said:"],["Que","That"],["vês","you-see"],["tu,","you,"],["Amós?","Amos?"],["E","And"],["eu","I"],["disse:","said:"],["Um","A"],["prumo.","I-plummet."],["Então","Then"],["disse","said"],["o","the"],["Senhor:","Lord:"],["Eis que","behold"],["eu","I"],["porei","I-will-place"],["o","the"],["prumo","I-plummet"],["no","in-the"],["meio","midst"],["do","of-the"],["meu","my"],["povo","people"],["Israel,","Israel,"],["e","and"],["daqui","of-here"],["por diante","onward"],["nunca","never"],["mais","more"],["passarei","I-will-pass"],["por","by"],["ele.","he."]]},
  {num:9,words:[["Mas","But"],["os","the"],["altos","places"],["de","of"],["Isaque","Isaac"],["serão","they-will-be"],["assolados,","wastes,"],["e","and"],["destruídos,","destroyed,"],["os","the"],["santuários","sanctuaries"],["de","of"],["Israel;","Israel;"],["e","and"],["levantar-me-ei","I-will-raise-up-me"],["com","with"],["a","the"],["espada","sword"],["contra","against"],["a","the"],["casa","house"],["de","of"],["Jeroboão.","Jeroboam."]]},
  {num:10,words:[["Então","Then"],["Amazias,","Amaziah,"],["o","the"],["sacerdote","priest"],["em","in"],["Betel,","Beth-El,"],["mandou","commanded"],["dizer","say"],["a","to"],["Jeroboão,","Jeroboam,"],["rei","king"],["de","of"],["Israel:","Israel:"],["Amós","Amos"],["conspirou","conspired"],["contra","against"],["ti,","you,"],["no","in-the"],["meio","midst"],["da","of-the"],["casa","house"],["de","of"],["Israel;","Israel;"],["a","the"],["terra","land"],["não","not"],["poderá","can"],["suportar","to-abide"],["todas","all"],["as","of"],["suas","his"],["palavras.","words."]]},
  {num:11,words:[["Porque","Because"],["assim diz","thus-saith"],["Amós:","Amos:"],["Jeroboão","Jeroboam"],["morrerá","will-die"],["à","to-the"],["espada,","sword,"],["e","and"],["Israel","Israel"],["certamente","certainly"],["será","will-be"],["levado","brought"],["para","for"],["fora","outside"],["da","of-the"],["sua","their"],["terra","land"],["em","in"],["cativeiro.","bondage."]]},
  {num:12,words:[["Depois","Afterwards"],["Amazias","Amaziah"],["disse","said"],["a","to"],["Amós:","Amos:"],["Vai-te,","Go-you,"],["ó","O"],["vidente,","seer,"],["e","and"],["foge","flees"],["para","for"],["a","the"],["terra","land"],["de","of"],["Judá,","Judah,"],["e","and"],["ali","there"],["come","eat"],["o","the"],["pão,","bread,"],["e","and"],["ali","there"],["profetiza;","prophesy;"]]},
  {num:13,words:[["Mas","But"],["em","in"],["Betel","Beth-El"],["daqui","of-here"],["por diante","onward"],["não","not"],["profetizarás","you-will-prophesy"],["mais,","more,"],["porque","because"],["é","is"],["o","the"],["santuário","sanctuary"],["do rei e","king's"],["a","the"],["casa","house"],["do","of-the"],["reino.","kingdom."]]},
  {num:14,words:[["E","And"],["respondeu","answered"],["Amós,","Amos,"],["e","and"],["disse","said"],["a","to"],["Amazias:","Amaziah:"],["Eu","I"],["não","not"],["era","was"],["profeta,","prophet,"],["nem","nor"],["filho","son"],["de","of"],["profeta,","prophet,"],["mas","but"],["boiadeiro,","cowboy,"],["e","and"],["colhia","gleaned"],["figos","figs"],["bravos.","brave."]]},
  {num:15,words:[["Porém","But"],["o","the"],["Senhor","Lord"],["me","me"],["tomou","took"],["de","of"],["detrás","behind"],["do","of-the"],["gado,","cattle,"],["e","and"],["o","the"],["Senhor","Lord"],["me","me"],["disse:","said:"],["Vai,","Go,"],["e","and"],["profetiza","prophesy"],["ao","to-the"],["meu","my"],["povo","people"],["Israel.","Israel."]]},
  {num:16,words:[["Ora,","Now,"],["pois,","for,"],["ouve","hears"],["a","the"],["palavra","word"],["do","of-the"],["Senhor:","Lord:"],["Tu","You"],["dizes:","you-say:"],["Não","Not"],["profetizarás","you-will-prophesy"],["contra","against"],["Israel,","Israel,"],["nem","nor"],["derramarás","you-will-pour"],["as","the"],["tuas","your"],["palavras","words"],["contra","against"],["a","the"],["casa","house"],["de","of"],["Isaque.","Isaac."]]},
  {num:17,words:[["Portanto,","Therefore,"],["assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Tua","Your"],["mulher","dame"],["se","himself"],["prostituirá","will-prostitute"],["na","in-the"],["cidade,","city,"],["e","and"],["teus","your"],["filhos e","daughters"],["tuas","your"],["filhas","daughters"],["cairão","they-will-fall"],["à","to-the"],["espada,","sword,"],["e","and"],["a","the"],["tua","your"],["terra","land"],["será","will-be"],["repartida","divided"],["a","to"],["cordel,","line,"],["e","and"],["tu","you"],["morrerás","you-will-die"],["na","in-the"],["terra","land"],["imunda,","unclean,"],["e","and"],["Israel","Israel"],["certamente","certainly"],["será","will-be"],["levado","brought"],["cativo","captive"],["para","for"],["fora","outside"],["da","of-the"],["sua","his"],["terra.","land."]]}
];
var v8 = [
  {num:1,words:[["O","The"],["Senhor","Lord"],["Deus","God"],["assim","thus"],["me","me"],["mostrou;","showed;"],["e","and"],["eis","behold"],["aqui","here"],["um","a"],["cesto","basket"],["de","of"],["frutos","fruit"],["do","of-the"],["verão.","summer."]]},
  {num:2,words:[["E","And"],["disse:","said:"],["Que","That"],["vês,","you-see,"],["Amós?","Amos?"],["E","And"],["eu","I"],["disse:","said:"],["Um","A"],["cesto","basket"],["de","of"],["frutos","fruit"],["do","of-the"],["verão.","summer."],["Então","Then"],["o","the"],["Senhor","Lord"],["me","me"],["disse:","said:"],["Chegou","Came"],["o","the"],["fim","end"],["sobre","upon"],["o","the"],["meu","my"],["povo","people"],["Israel;","Israel;"],["daqui","of-here"],["por diante","onward"],["nunca","never"],["mais","more"],["passarei","I-will-pass"],["por","by"],["ele.","he."]]},
  {num:3,words:[["Mas","But"],["os","the"],["cânticos","songs"],["do","of-the"],["templo","temple"],["serão","they-will-be"],["ouvidos","heard"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor","Lord"],["Deus;","God;"],["multiplicar-se-ão","they-will-multiply-themselves"],["os","the"],["cadáveres;","carcases;"],["em","in"],["todos","all"],["os","the"],["lugares,","places,"],["serão","they-will-be"],["lançados","cast"],["fora.","outside."],["Silêncio!","Silence!"]]},
  {num:4,words:[["Ouvi","Hear"],["isto,","this,"],["vós","you"],["que","that"],["ansiais","you-yearn"],["pelo","by-the"],["abatimento","abatement"],["do","of-the"],["necessitado;","needy;"],["e","and"],["isso","that"],["para","to"],["destruirdes","to-destroy"],["os","the"],["miseráveis","miserable"],["da","of-the"],["terra,","land,"]]},
  {num:5,words:[["Dizendo:","Saying:"],["Quando","When"],["passará","will-pass"],["a","the"],["lua","moon"],["nova,","new,"],["para","to"],["vendermos","to-sell"],["o","the"],["grão?","grain?"],["e","and"],["o","the"],["sábado,","sabbath,"],["para","to"],["abrirmos","to-open"],["os","the"],["celeiros","barns"],["de","of"],["trigo,","wheat,"],["diminuindo","reducing"],["o","the"],["efa,","ephah,"],["e","and"],["aumentando","increasing"],["o","the"],["siclo,","shekel,"],["e","and"],["falsificando","falsifying"],["as","the"],["balanças","you-rock"],["enganosas;","deceptive;"]]},
  {num:6,words:[["Para","To"],["comprarmos","to-buy"],["os","the"],["pobres","poor"],["por","by"],["dinheiro,","money,"],["e","and"],["os","the"],["necessitados,","needy,"],["por","by"],["um","a"],["par","pair"],["de","of"],["sapatos,","shoes,"],["e","and"],["então","then"],["vendermos","to-sell"],["as","the"],["cascas","bark"],["do","of-the"],["trigo?","wheat?"]]},
  {num:7,words:[["Jurou","Swore"],["o","the"],["Senhor","Lord"],["pela","by-the"],["glória","glory"],["de","of"],["Jacó:","Jacob:"],["Eu","I"],["não","not"],["me","me"],["esquecerei","I-will-forget"],["de","of"],["todas","all"],["as","of"],["suas","their"],["obras","works"],["para sempre.","for-ever"]]},
  {num:8,words:[["Por","By"],["causa","sake"],["disso","of-that"],["não","not"],["se","himself"],["comoveria","should-move"],["a","the"],["terra,","land,"],["e","and"],["não","not"],["choraria","should-weep"],["todo","every"],["aquele","that"],["que","that"],["habita","dwell"],["nela?","in-it?"],["Certamente","Certainly"],["levantar-se-á","will-arise"],["toda","every"],["como","as"],["um","a"],["rio,","river,"],["e","and"],["transbordará,","will-overflow,"],["e","and"],["baixará","drowned"],["como","as"],["o","the"],["rio","river"],["do","of-the"],["Egito.","Egypt."]]},
  {num:9,words:[["E","And"],["sucederá","will-happen"],["que,","that,"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor","Lord"],["Deus,","God,"],["farei","I-will-make"],["que","that"],["o","the"],["sol","sun"],["se","himself"],["ponha","footstool"],["ao","to-the"],["meio","midst"],["dia,","day,"],["e","and"],["a","the"],["terra","earth"],["se","himself"],["entenebreça","darken"],["no","in-the"],["dia","day"],["claro.","clear."]]},
  {num:10,words:[["E","And"],["tornarei","I-will-become"],["as","the"],["vossas","your"],["festas","feasts"],["em","in"],["luto,","mourning,"],["e","and"],["todos","all"],["os","of"],["vossos","your"],["cânticos,","songs,"],["em","in"],["lamentações;","lamentations;"],["e","and"],["farei","I-will-make"],["pôr","to-place"],["panos","sackcloth"],["de","of"],["saco","sack"],["sobre","upon"],["todos","all"],["os","the"],["lombos,","loins,"],["e","and"],["calva,","baldness,"],["sobre","upon"],["toda","every"],["cabeça;","head;"],["e","and"],["farei","I-will-make"],["que","that"],["isso","that"],["seja","is"],["como","as"],["luto","mourning"],["do","of-the"],["filho","son"],["único,","alone,"],["e","and"],["o","the"],["seu","your"],["fim,","end,"],["como","as"],["dia","day"],["de","of"],["amarguras.","you-writ."]]},
  {num:11,words:[["Eis que","behold"],["vêm","they-come"],["dias,","days,"],["diz","says"],["o","the"],["Senhor","Lord"],["Deus,","God,"],["em","in"],["que","that"],["enviarei","I-will-send"],["fome","hunger"],["sobre","upon"],["a","the"],["terra,","land,"],["não","not"],["fome","hunger"],["de","of"],["pão,","bread,"],["nem","nor"],["sede","thirst"],["de","of"],["água,","water,"],["mas","but"],["de","of"],["ouvir","to-hear"],["as","the"],["palavras","words"],["do","of-the"],["Senhor.","Lord."]]},
  {num:12,words:[["E","And"],["irão","they-will-go"],["errantes","erratic"],["de","of"],["um","a"],["mar","sea"],["até","until"],["outro","other"],["mar,","sea,"],["e","and"],["do","of-the"],["norte","north"],["até","until"],["o","the"],["oriente;","east;"],["correrão","they-will-flow"],["por toda a","throughout"],["parte,","part,"],["buscando","seeking"],["a","the"],["palavra","word"],["do","of-the"],["Senhor,","Lord,"],["mas","but"],["não","not"],["a","it"],["acharão.","they-will-find."]]},
  {num:13,words:[["Naquele","In-that"],["dia","day"],["as","the"],["virgens","virgins"],["formosas","beautiful"],["e","and"],["os","the"],["jovens","young"],["desmaiarão","they-will-faint"],["de","of"],["sede.","thirst."]]},
  {num:14,words:[["Os","The"],["que","that"],["juram","they-swear"],["pelo","by-the"],["delito","blame"],["de","of"],["Samaria,","Samaria,"],["e","and"],["dizem:","they-say:"],["Vive","Live"],["o","the"],["teu","your"],["deus,","god,"],["ó","O"],["Dã;","Dan;"],["e:","and:"],["Vive","Live"],["o","the"],["caminho","way"],["de","of"],["Berseba;","Beer-Sheba;"],["esses","those"],["mesmos","same"],["cairão,","they-will-fall,"],["e","and"],["não","not"],["se","themselves"],["levantarão","they-will-raise-up"],["mais.","more."]]}
];
var v9 = [
  {num:1,words:[["Vi","I-saw"],["o","the"],["Senhor,","Lord,"],["que","that"],["estava","was"],["em","in"],["pé","foot"],["sobre","upon"],["o","the"],["altar,","altar,"],["e","and"],["me","me"],["disse:","said:"],["Fere","Hurts"],["o","the"],["capitel,","chapiter,"],["e","and"],["estremeçam","they-tremble"],["os","the"],["umbrais,","posts,"],["e","and"],["corta-lhes","hews-to-them"],["em","in"],["pedaços","pieces"],["a","the"],["cabeça","head"],["a","to"],["todos","all"],["eles;","them;"],["e","and"],["eu","I"],["matarei","I-will-slay"],["à","to-the"],["espada","sword"],["até","until"],["o","the"],["último","last"],["deles;","of-them;"],["o","the"],["que","that"],["fugir","flee"],["dentre","from"],["eles","them"],["não","not"],["escapará,","will-escape,"],["nem","nor"],["o","the"],["que","that"],["escapar","to-escape"],["dentre","from"],["eles","them"],["se","himself"],["salvará.","will-save."]]},
  {num:2,words:[["Ainda que","although"],["cavem","they-dig"],["até","until"],["o","the"],["inferno,","hell,"],["a","the"],["minha","my"],["mão","hand"],["os","them"],["tirará","will-take-away"],["dali,","of-at that place,"],["e","and"],["se","if"],["subirem","to-go-up"],["ao","to-the"],["céu,","heaven,"],["dali","of-at that place"],["os","the"],["farei","I-will-make"],["descer.","to-descend."]]},
  {num:3,words:[["E","And"],["se","if"],["eles","they"],["se","themselves"],["esconderem","to-hide"],["no","in-the"],["cume","top"],["do","of-the"],["Carmelo,","Carmel,"],["buscá-los-ei,","I-will-seek-them,"],["e","and"],["dali","of-at that place"],["os","the"],["tirarei;","I-will-take-away;"],["e","and"],["se","if"],["eles","they"],["se","themselves"],["ocultarem","to-withhold"],["aos","to-the"],["meus","my"],["olhos","eyes"],["no","in-the"],["fundo","fund"],["do","of-the"],["mar,","sea,"],["ali","there"],["darei","I-will-give"],["ordem","order"],["à","to-the"],["serpente,","serpent,"],["e","and"],["ela","she"],["os","them"],["morderá.","will-bite."]]},
  {num:4,words:[["E","And"],["se","if"],["forem","they-will-be"],["em","in"],["cativeiro","bondage"],["diante de","before"],["seus","their"],["inimigos,","enemies,"],["ali","there"],["darei","I-will-give"],["ordem","order"],["à","to-the"],["espada","sword"],["que","that"],["os","the"],["mate;","slays;"],["e","and"],["eu","I"],["porei","I-will-place"],["o","the"],["meu","my"],["olho","eye"],["sobre","upon"],["eles","they"],["para","for"],["o","the"],["mal,","evil,"],["e","and"],["não","not"],["para","for"],["o","the"],["bem.","good."]]},
  {num:5,words:[["Porque","Because"],["o","the"],["Senhor","Lord"],["Deus","God"],["dos","of-the"],["Exércitos","Armies"],["é","is"],["o","the"],["que","that"],["toca","touches"],["a","the"],["terra,","land,"],["e","and"],["ela","it"],["se","himself"],["derreterá,","will-melt,"],["e","and"],["todos","all"],["os","the"],["que","that"],["habitam","they-dwell"],["nela","in-it"],["chorarão;","they-will-weep;"],["e","and"],["ela","it"],["subirá","will-go-up"],["toda","every"],["como","as"],["um","a"],["rio,","river,"],["e","and"],["submergirá","drowned"],["como","as"],["o","the"],["rio","river"],["do","of-the"],["Egito.","Egypt."]]},
  {num:6,words:[["Ele","He"],["é","is"],["o","the"],["que","that"],["edifica","builds"],["as","the"],["suas","his"],["câmaras","chambers"],["superiores","superior"],["no","in-the"],["céu,","heaven,"],["e","and"],["o","the"],["seu","his"],["firmamento","firmament"],["fundou","erected"],["sobre","upon"],["a","the"],["terra,","earth,"],["e","and"],["o","the"],["que","that"],["chama","flame"],["as","the"],["águas","waters"],["do","of-the"],["mar,","sea,"],["e","and"],["as","them"],["derrama","pours"],["sobre","upon"],["a","the"],["terra;","earth;"],["o","the"],["Senhor","Lord"],["é","is"],["o","the"],["seu","his"],["nome.","name."]]},
  {num:7,words:[["Não","Not"],["me","me"],["sois,","you-are,"],["vós,","you,"],["ó","O"],["filhos","children"],["de","of"],["Israel,","Israel,"],["como","as"],["os","the"],["filhos","children"],["dos","of-the"],["etíopes?","ethiopians?"],["diz","says"],["o","the"],["Senhor.","Lord."],["Não","Not"],["fiz","I-made"],["eu","I"],["subir","go-up"],["Israel","Israel"],["da","of-the"],["terra do","egypt"],["Egito,","Egypt,"],["e","and"],["os","the"],["filisteus,","philistines,"],["de","of"],["Caftor,","Caphtor,"],["e","and"],["os","the"],["sírios,","syrians,"],["de","of"],["Quir?","Kir?"]]},
  {num:8,words:[["Eis que","behold"],["os","the"],["olhos","eyes"],["do","of-the"],["Senhor","Lord"],["Deus","God"],["estão","they-are"],["contra","against"],["este","this"],["reino","kingdom"],["pecador,","sinner,"],["e","and"],["eu","I"],["o","the"],["destruirei","I-will-destroy"],["de","of"],["sobre","upon"],["a","the"],["face","face"],["da","of-the"],["terra,","earth,"],["exceto","except"],["que","that"],["não","not"],["destruirei","I-will-destroy"],["de todo","wholly"],["a","the"],["casa","house"],["de","of"],["Jacó,","Jacob,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:9,words:[["Porque","Because"],["eis que","behold"],["darei","I-will-give"],["ordem,","order,"],["e","and"],["sacudirei","I-will-abet"],["a","the"],["casa","house"],["de","of"],["Israel","Israel"],["entre","among"],["todas","all"],["as","the"],["nações,","nations,"],["assim como","even-as"],["se","himself"],["sacode","abets"],["grão","grain"],["na","in-the"],["peneira,","sifts,"],["sem","without"],["que","that"],["caia","whites-wash"],["na","in-the"],["terra","earth"],["um","a"],["só","only"],["grão.","grain."]]},
  {num:10,words:[["Todos","All"],["os","the"],["pecadores","sinners"],["do","of-the"],["meu","my"],["povo","people"],["morrerão","they-will-die"],["à","to-the"],["espada,","sword,"],["os","the"],["que","that"],["dizem:","they-say:"],["Não","Not"],["se","himself"],["avizinhará","to-avizinhar"],["nem","nor"],["nos","us"],["encontrará","will-find"],["o","the"],["mal.","evil."]]},
  {num:11,words:[["Naquele","In-that"],["dia","day"],["tornarei","I-will-become"],["a","to"],["levantar","raise-up"],["a","the"],["caída","fallen"],["tenda","tent"],["de","of"],["Davi,","David,"],["e","and"],["cercarei","I-will-besiege"],["as","the"],["suas","his"],["aberturas,","aperture,"],["e","and"],["tornarei","I-will-become"],["a","to"],["levantar","raise-up"],["as","the"],["suas","his"],["ruínas,","ruins,"],["e","and"],["a","to"],["edificarei","I-will-build"],["como","as"],["nos","in-the"],["dias","days"],["da","of-the"],["antiguidade;","antiguidade;"]]},
  {num:12,words:[["Para que","that"],["possuam","they-possess"],["o","the"],["restante","remaining"],["de","of"],["Edom,","Edom,"],["e","and"],["todas","all"],["as","the"],["nações","nations"],["que","that"],["são","they-are"],["chamadas","called"],["pelo","by-the"],["meu","my"],["nome,","name,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["que","that"],["faz","makes"],["isso.","that."]]},
  {num:13,words:[["Eis que","behold"],["vêm","they-come"],["dias,","days,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["em","in"],["que","that"],["o","the"],["que","that"],["lavra","plowman"],["alcançará","will-obtain"],["ao","to-the"],["que","that"],["ceifa,","harvest,"],["e","and"],["o","the"],["que","that"],["pisa","crushes"],["as","the"],["uvas,","grapes,"],["ao","to-the"],["que","that"],["semeia","sow"],["a","the"],["semente;","seed;"],["e","and"],["os","the"],["montes","mountains"],["destilarão","they-will-distill"],["mosto,","corn,"],["e","and"],["todos","all"],["os","the"],["outeiros","hills"],["se","themselves"],["derreterão.","they-will-melt."]]},
  {num:14,words:[["E","And"],["farei","I-will-make"],["retornar","return"],["os","the"],["cativos","captives"],["do","of-the"],["meu","my"],["povo","people"],["Israel,","Israel,"],["e","and"],["reedificarão","troublous"],["as","the"],["cidades","cities"],["assoladas,","desolate,"],["e","and"],["nelas","in-him"],["habitarão,","they-will-dwell,"],["e","and"],["plantarão","they-will-plant"],["vinhas,","vineyards,"],["e","and"],["beberão","they-will-drink"],["o","the"],["seu","his"],["vinho,","wine,"],["e","and"],["farão","they-will-make"],["jardins,","gardens,"],["e","and"],["lhes","to-them"],["comerão","they-will-eat"],["o","the"],["fruto.","fruit."]]},
  {num:15,words:[["E","And"],["os","the"],["plantarei","I-will-plant"],["na","in-the"],["sua","their"],["terra,","land,"],["e","and"],["não","not"],["mais","more"],["serão","they-will-be"],["arrancados","plucked"],["da","of-the"],["sua","their"],["terra","land"],["que","that"],["lhes","to-them"],["dei,","I-gave,"],["diz","says"],["o","the"],["Senhor","Lord"],["teu","your"],["Deus.","God."]]}
];
renderVerseSet(v1, 'amo-ch1-verses');
renderVerseSet(v2, 'amo-ch2-verses');
renderVerseSet(v3, 'amo-ch3-verses');
renderVerseSet(v4, 'amo-ch4-verses');
renderVerseSet(v5, 'amo-ch5-verses');
renderVerseSet(v6, 'amo-ch6-verses');
renderVerseSet(v7, 'amo-ch7-verses');
renderVerseSet(v8, 'amo-ch8-verses');
renderVerseSet(v9, 'amo-ch9-verses');
})();
