(function() {
var v1 = [
  {num:1,words:[["Cremos","We-believe"],["em","in"],["Deus,","God,"],["o","the"],["Pai","Father"],["Eterno,","Everlasting,"],["e","and"],["em","in"],["Seu","His"],["Filho,","Son,"],["Jesus","Jesus"],["Cristo,","Christ,"],["e","and"],["no","in-the"],["Espírito","Spirit"],["Santo.","Holy."]]},
  {num:2,words:[["Cremos","We-believe"],["que","that"],["os","the"],["homens","men"],["serão","they-will-be"],["punidos","punished"],["por","by"],["seus","their"],["próprios","own"],["pecados","sins"],["e","and"],["não","not"],["pela","by-the"],["transgressão","transgression"],["de","of"],["Adão.","Adam."]]},
  {num:3,words:[["Cremos","We-believe"],["que,","that,"],["por","by"],["meio","midst"],["da","of-the"],["Expiação","Atonement"],["de","of"],["Cristo,","Christ,"],["toda","every"],["a","the"],["humanidade","mankind"],["pode","can"],["ser","be"],["salva,","save,"],["pela","by-the"],["obediência","obedience"],["às","to-the"],["leis","laws"],["e","and"],["ordenanças","ordinances"],["do","of-the"],["Evangelho.","Gospel."]]},
  {num:4,words:[["Cremos","We-believe"],["que","that"],["os","the"],["primeiros","first"],["princípios","principles"],["e","and"],["ordenanças","ordinances"],["do","of-the"],["Evangelho","Gospel"],["são:","they-are:"],["primeiro,","first,"],["Fé","Faith"],["no","in-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo;","Christ;"],["segundo,","according-to,"],["Arrependimento;","Repentance;"],["terceiro,","third,"],["Batismo","Baptism"],["por","by"],["imersão","immersion"],["para","for"],["a","to"],["remissão","remission"],["de","of"],["pecados;","sins;"],["quarto,","fourth,"],["Imposição","Laying"],["de","of"],["mãos","hands"],["para","for"],["o","the"],["dom","gift"],["do","of-the"],["Espírito","Spirit"],["Santo.","Holy."]]},
  {num:5,words:[["Cremos","We-believe"],["que","that"],["um","a"],["homem","man"],["deve","must"],["ser","be"],["chamado","called"],["por","by"],["Deus,","God,"],["por","by"],["profecia,","prophecy,"],["e","and"],["pela","by-the"],["imposição","laying"],["de","of"],["mãos,","hands,"],["por","by"],["quem","who"],["possua","possesses"],["autoridade,","authority,"],["para","to"],["pregar","preach"],["o","the"],["Evangelho","Gospel"],["e","and"],["administrar","to-administer"],["as","the"],["suas","their"],["ordenanças.","ordinances."]]},
  {num:6,words:[["Cremos","We-believe"],["na","in-the"],["mesma","same"],["organização","organization"],["que","that"],["existia","existed"],["na","in-the"],["Igreja","Church"],["Primitiva,","Primitive,"],["isto é,","that-is"],["apóstolos,","apostles,"],["profetas,","prophets,"],["pastores,","shepherds,"],["mestres,","teachers,"],["evangelistas,","evangelists,"],["etc.","etc."]]},
  {num:7,words:[["Cremos","We-believe"],["no","in-the"],["dom","gift"],["de","of"],["línguas,","tongues,"],["profecia,","prophecy,"],["revelação,","revelation,"],["visões,","visions,"],["cura,","healing,"],["interpretação","interpretation"],["de","of"],["línguas,","tongues,"],["etc.","etc."]]},
  {num:8,words:[["Cremos","We-believe"],["ser","be"],["a","the"],["Bíblia","Bible"],["a","the"],["palavra","word"],["de","of"],["Deus,","God,"],["desde","since"],["que","that"],["esteja","is"],["traduzida","interpreted"],["corretamente;","correctly;"],["também","also"],["cremos","we-believe"],["ser","be"],["o","the"],["Livro","Book"],["de","of"],["Mórmon","Mormon"],["a","the"],["palavra","word"],["de","of"],["Deus.","God."]]},
  {num:9,words:[["Cremos","We-believe"],["em","in"],["tudo","all"],["o","the"],["que","that"],["Deus","God"],["revelou,","revealed,"],["em","in"],["tudo","all"],["o","the"],["que","that"],["Ele","He"],["revela","reveal"],["agora,","now,"],["e","and"],["cremos","we-believe"],["que","that"],["Ele","He"],["ainda","yet"],["revelará","will-reveal"],["muitas","many"],["coisas","things"],["grandiosas","reveal"],["e","and"],["importantes","important"],["relativas","pertaining"],["ao","to-the"],["Reino","Kingdom"],["de","of"],["Deus.","God."]]},
  {num:10,words:[["Cremos","We-believe"],["na","in-the"],["coligação","coligação"],["literal","literal"],["de","of"],["Israel","Israel"],["e","and"],["na","in-the"],["restauração","restoration"],["das","of-the"],["Dez","Ten"],["Tribos;","Tribes;"],["que","that"],["Sião","Zion"],["(a","(the"],["Nova","New"],["Jerusalém)","Jerusalem)"],["será","will-be"],["construída","built"],["no","in-the"],["continente","continent"],["americano;","American;"],["que","that"],["Cristo","Christ"],["reinará","assuredly"],["pessoalmente","personally"],["na","in-the"],["Terra;","Land;"],["e","and"],["que","that"],["a","the"],["Terra","Land"],["será","will-be"],["renovada","bud"],["e","and"],["receberá","will-receive"],["a","to"],["sua","its"],["glória","glory"],["paradisíaca.","paradisíaca."]]},
  {num:11,words:[["Pretendemos","We-intend"],["o","the"],["privilégio","privilege"],["de","of"],["adorar","to-worship"],["a","to"],["Deus","God"],["Todo-Poderoso","Almighty"],["de acordo com","according-to"],["os","the"],["ditames","force"],["de","of"],["nossa","our"],["própria","own"],["consciência;","conscience;"],["e","and"],["concedemos","we-bestow"],["a","to"],["todos","all"],["os","the"],["homens","men"],["o","the"],["mesmo","even"],["privilégio,","privilege,"],["deixando-os","allowing-them"],["adorar","to-worship"],["como,","as,"],["onde,","where,"],["ou","or"],["o","the"],["que","that"],["desejarem.","to-desire."]]},
  {num:12,words:[["Cremos","We-believe"],["na","in-the"],["submissão","abandonment"],["a","to"],["reis,","kings,"],["presidentes,","presidents,"],["governantes,","rulers,"],["e","and"],["magistrados;","magistrates;"],["na","in-the"],["obediência,","obedience,"],["honra,","honour,"],["e","and"],["manutenção","maintainership"],["da","of-the"],["lei.","law."]]},
  {num:13,words:[["Cremos","We-believe"],["em","in"],["ser","be"],["honestos,","hone,"],["verdadeiros,","believers,"],["castos,","chaste,"],["benevolentes,","benevolent,"],["virtuosos,","virtuose,"],["e","and"],["em","in"],["fazer","make"],["o","the"],["bem","good"],["a","to"],["todos","all"],["os","the"],["homens;","men;"],["na","in-the"],["realidade,","reality,"],["podemos","we-can"],["dizer","say"],["que","that"],["seguimos","we-follow"],["a","the"],["admoestação","admonition"],["de","of"],["Paulo:","Paul:"],["Cremos","We-believe"],["em","in"],["todas","things"],["as","the"],["coisas,","things,"],["confiamos","we-confide"],["em","in"],["todas","things"],["as","the"],["coisas,","things,"],["suportamos","we-abide"],["muitas","many"],["coisas","things"],["e","and"],["esperamos","we-abide"],["ter","have"],["a","the"],["capacidade","ability"],["de","of"],["tudo","all"],["suportar.","to-abide."],["Se","If"],["houver","will-have"],["qualquer","any"],["coisa","thing"],["virtuosa,","virtuous,"],["amável,","affable,"],["de","of"],["boa","good"],["fama","fame"],["ou","or"],["louvável,","worthwhile,"],["nós","we"],["a","it"],["procuraremos.","we-will-search."]]}
];
renderVerseSet(v1, 'af-ch1-verses');
})();
