(function() {
var v1 = [
  {num:1,words:[["E","And"],["sucedeu","happened"],["nos","in-the"],["dias","days"],["de","of"],["Assuero","Ahasuerus"],["(este","(this"],["é","is"],["aquele","that"],["Assuero","Ahasuerus"],["que","that"],["reinou","reigned"],["desde","since"],["a","the"],["Índia","India"],["até","until"],["a","the"],["Etiópia,","Ethiopia,"],["sobre","upon"],["cento","hundred"],["e","and"],["vinte","twenty"],["e","and"],["sete","seven"],["províncias)","provinces)"]]},
  {num:2,words:[["Que,","That,"],["naqueles","in-that"],["dias,","days,"],["assentando-se","settling-himself"],["o","the"],["rei","king"],["Assuero","Ahasuerus"],["sobre","upon"],["o","the"],["trono","throne"],["do","of-the"],["seu","his"],["reino,","kingdom,"],["que","that"],["estava","was"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã,","Shushan,"]]},
  {num:3,words:[["No","In-the"],["terceiro","third"],["ano","year"],["do","of-the"],["seu","his"],["reinado,","reign,"],["fez","made"],["um","a"],["convite","invitation"],["a","to"],["todos","all"],["os","of"],["seus","his"],["príncipes","princes"],["e","and"],["seus","his"],["servos","servants"],["(o","(the"],["poder","power"],["da","of-the"],["Pérsia","Persia"],["e","and"],["Média","Media"],["e","and"],["os","the"],["maiores","greater"],["senhores","masters"],["das","of-the"],["províncias","provinces"],["estavam","they-were"],["perante","before"],["ele),","he),"]]},
  {num:4,words:[["Para","To"],["mostrar","to-show"],["as","the"],["riquezas","riches"],["da","of-the"],["glória","glory"],["do","of-the"],["seu","his"],["reino,","kingdom,"],["e","and"],["o","the"],["esplendor","brightness"],["da","of-the"],["sua","his"],["excelente","excellent"],["grandeza,","greatness,"],["por","by"],["muitos","many"],["dias,","days,"],["a saber,","namely"],["cento","hundred"],["e","and"],["oitenta","eighty"],["dias.","days."]]},
  {num:5,words:[["E","And"],["acabados","finished"],["aqueles","those"],["dias,","days,"],["fez","made"],["o","the"],["rei","king"],["um","a"],["convite","invitation"],["a","to"],["todo","all"],["o","the"],["povo","people"],["que","that"],["se","itself"],["achava","found"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã,","Shushan,"],["desde o","beginning"],["maior","greater"],["até","until"],["o","the"],["menor,","least,"],["por","by"],["sete","seven"],["dias,","days,"],["no","in-the"],["pátio","court"],["do","of-the"],["jardim","garden"],["do","of-the"],["palácio","palace"],["real.","royal."]]},
  {num:6,words:[["As","The"],["tapeçarias","marble"],["eram","they-were"],["de","of"],["branco,","white,"],["verde,","green,"],["e","and"],["azul","blue"],["celeste,","celestial,"],["pendentes","earrings"],["de","of"],["cordões","wreathen"],["de","of"],["linho","linen"],["fino","dainty"],["e","and"],["púrpura,","purple,"],["e","and"],["argolas","rings"],["de","of"],["prata,","silver,"],["e","and"],["colunas","pillars"],["de","of"],["mármore;","marble;"],["os","the"],["leitos","bed"],["de","of"],["ouro","gold"],["e","and"],["de","of"],["prata,","silver,"],["sobre","upon"],["um","a"],["pavimento","pavement"],["de","of"],["pórfiro,","marble,"],["e","and"],["de","of"],["mármore,","marble,"],["e","and"],["de","of"],["alabastro,","alabaster,"],["e","and"],["de","of"],["pedras","stones"],["preciosas.","precious."]]},
  {num:7,words:[["E","And"],["dava-se","gave-himself"],["de","of"],["beber","drink"],["em","in"],["copos","cup"],["de","of"],["ouro,","gold,"],["e","and"],["os","the"],["copos","cup"],["eram","they-were"],["diferentes","different"],["uns","some"],["dos","of-the"],["outros;","others;"],["e","and"],["havia","there-was"],["muito","much"],["vinho","wine"],["real,","royal,"],["segundo","according-to"],["a","the"],["disposição","disposition"],["do rei.","king's"]]},
  {num:8,words:[["E","And"],["o","the"],["beber","drink"],["era,","was,"],["por","by"],["lei,","law,"],["que","that"],["ninguém","none"],["forçasse","compelled"],["a","to"],["outro,","another,"],["porque","because"],["assim","thus"],["o","him"],["tinha","had"],["ordenado","ordained"],["o","the"],["rei","king"],["expressamente","expressly"],["a","to"],["todos","all"],["os","the"],["grandes","great"],["da","of-the"],["sua","his"],["casa,","house,"],["que","that"],["fizessem","they-made"],["conforme a","according-to"],["vontade","will"],["de","of"],["cada","every"],["um.","a."]]},
  {num:9,words:[["Também","Also"],["a","the"],["rainha","queen"],["Vasti","Vashti"],["fez","made"],["um","a"],["convite","invitation"],["às","to-the"],["mulheres,","women,"],["na","in-the"],["casa","house"],["real","royal"],["que","that"],["tinha","had"],["o","the"],["rei","king"],["Assuero.","Ahasuerus."]]},
  {num:10,words:[["E","And"],["ao","to-the"],["sétimo","seventh"],["dia,","day,"],["estando","being"],["já","already"],["o","the"],["coração","heart"],["do rei","king's"],["alegre","merry"],["do","of-the"],["vinho,","wine,"],["mandou","commanded"],["Meumã,","Mehuman,"],["Bizta,","Mehuman,"],["Harbona,","Harbona,"],["Bigtá,","Mehuman,"],["e","and"],["Abagta,","Mehuman,"],["Zetar,","Mehuman,"],["e","and"],["Carcas,","Carcas,"],["os","the"],["sete","seven"],["eunucos","eunuchs"],["que","that"],["serviam","they-served"],["na","in-the"],["presença","presence"],["do rei","king's"],["Assuero,","Ahasuerus,"]]},
  {num:11,words:[["Que","That"],["introduzissem","they-entered"],["na","in-the"],["presença","presence"],["do rei","king's"],["a","the"],["rainha","queen"],["Vasti,","Vashti,"],["com","with"],["a","the"],["coroa","crown"],["real,","royal,"],["para","to"],["mostrar","to-show"],["aos","to-the"],["povos","nations"],["e","and"],["aos","to-the"],["príncipes","princes"],["a","the"],["sua","her"],["formosura,","beauty,"],["porque","because"],["era","was"],["formosa","fair"],["à","to-the"],["vista.","picture."]]},
  {num:12,words:[["Porém","But"],["a","the"],["rainha","queen"],["Vasti","Vashti"],["recusou-se","refused-himself"],["a","to"],["vir,","come,"],["conforme a","according-to"],["palavra","word"],["do rei","king's"],["pela","by-the"],["mão","hand"],["dos","of-the"],["eunucos;","eunuchs;"],["pelo","by-the"],["que","that"],["o","the"],["rei","king"],["muito","much"],["se","himself"],["enfureceu,","manifesting,"],["e","and"],["ardeu","glowed"],["nele","in-him"],["a","to"],["sua","his"],["ira.","anger."]]},
  {num:13,words:[["Então","Then"],["perguntou","asked"],["o","the"],["rei","king"],["aos","to-the"],["sábios","wise"],["que","that"],["entendiam","they-understood"],["dos","of-the"],["tempos","times"],["(porque","(because"],["assim","thus"],["se","themselves"],["tratavam","they-attended"],["os","the"],["negócios","affairs"],["do rei","king's"],["na","in-the"],["presença","presence"],["de","of"],["todos","all"],["os","the"],["que","that"],["sabiam","they-knew"],["a","the"],["lei","law"],["e","and"],["o","the"],["direito;","right;"]]},
  {num:14,words:[["E","And"],["os","the"],["mais","more"],["chegados","come"],["a","the"],["ele","he"],["eram:","they-were:"],["Carsena,","Carshena,"],["Setar,","Carshena,"],["Admata,","Carshena,"],["Társis,","Tarshish,"],["Meres,","Meres,"],["Marsena,","Marsena,"],["Memucã,","Memucan,"],["os","the"],["sete","seven"],["príncipes","princes"],["dos","of-the"],["persas","persians"],["e","and"],["dos","of-the"],["medos,","medes,"],["que","that"],["viam","they-saw"],["a","the"],["face","face"],["do rei,","king's"],["e","and"],["se","if"],["assentavam","they-settled"],["como","as"],["os","the"],["primeiros","first"],["no","in-the"],["reino)","kingdom)"]]},
  {num:15,words:[["O","The"],["que,","that,"],["segundo","according-to"],["a","the"],["lei,","law,"],["se","if"],["devia","musted"],["fazer","make"],["da","of-the"],["rainha","queen"],["Vasti,","Vashti,"],["por","by"],["não","not"],["haver","have"],["cumprido","fulfilled"],["o","the"],["mandado","commandment"],["do rei","king's"],["Assuero,","Ahasuerus,"],["pela","by-the"],["mão","hand"],["dos","of-the"],["eunucos.","eunuchs."]]},
  {num:16,words:[["Então","Then"],["disse","said"],["Memucã","Memucan"],["na","in-the"],["presença","presence"],["do rei e","king's"],["dos","of-the"],["príncipes:","princes:"],["Não","Not"],["somente","only"],["pecou","sinned"],["contra","against"],["o","the"],["rei","king"],["a","the"],["rainha","queen"],["Vasti,","Vashti,"],["porém","but"],["também","also"],["contra","against"],["todos","all"],["os","the"],["príncipes,","princes,"],["e","and"],["contra","against"],["todos","all"],["os","the"],["povos","nations"],["que","that"],["há","there-is"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["do rei","king's"],["Assuero.","Ahasuerus."]]},
  {num:17,words:[["Porque","Because"],["a","the"],["notícia","news"],["deste","of-this"],["feito","made"],["da","of-the"],["rainha","queen"],["chegará","will-come"],["a","the"],["todas","all"],["as","the"],["mulheres,","women,"],["de modo que","so-that"],["desprezarão","they-will-mammon"],["seus","their"],["maridos","husbands"],["aos","to-the"],["seus","their"],["olhos","eyes"],["quando","when"],["se","himself"],["disser:","will-say:"],["Mandou","Commanded"],["o","the"],["rei","king"],["Assuero","Ahasuerus"],["que","that"],["introduzissem","they-entered"],["à","to-the"],["sua","their"],["presença","presence"],["a","the"],["rainha","queen"],["Vasti,","Vashti,"],["porém","but"],["ela","she"],["não","not"],["veio.","came."]]},
  {num:18,words:[["E","And"],["neste","in-this"],["mesmo","same"],["dia","day"],["as","the"],["princesas","prince"],["da","of-the"],["Pérsia","Persia"],["e","and"],["da","of-the"],["Média","Media"],["dirão","they-will-say"],["o","the"],["mesmo","same"],["a","to"],["todos","all"],["os","the"],["príncipes","princes"],["do rei,","king's"],["ouvindo","hearing"],["o","the"],["feito","made"],["da","of-the"],["rainha,","queen,"],["e","and"],["assim","thus"],["haverá","there-will-be"],["muito","much"],["desprezo","contempt"],["e","and"],["indignação.","indignation."]]},
  {num:19,words:[["Se","If"],["bem","good"],["parecer","seem"],["ao","to-the"],["rei,","king,"],["saia","skirt"],["da","of-the"],["sua","her"],["parte","part"],["um","a"],["édito","haman's"],["real,","royal,"],["e","and"],["escreva-se","writes-himself"],["nas","in-the"],["leis","laws"],["dos","of-the"],["persas","persians"],["e","and"],["dos","of-the"],["medos,","medes,"],["e","and"],["não","not"],["se","himself"],["revogue,","abjures,"],["a saber,","namely"],["que","that"],["Vasti","Vashti"],["não","not"],["entre","among"],["mais","more"],["na","in-the"],["presença","presence"],["do rei","king's"],["Assuero,","Ahasuerus,"],["e","and"],["o","the"],["rei","king"],["dê","gives"],["o","the"],["reino","kingdom"],["dela","of-her"],["a","the"],["outra","another"],["que","that"],["seja","is"],["melhor","better"],["do que","than"],["ela.","she."]]},
  {num:20,words:[["E","And"],["ouvindo-se","hearing-himself"],["o","the"],["mandado,","commandment,"],["que","that"],["o","the"],["rei","king"],["decretar","to-decree"],["em","in"],["todo","all"],["o","of"],["seu","his"],["reino","kingdom"],["(porque","(because"],["é","is"],["grande),","great),"],["todas","all"],["as","the"],["mulheres","women"],["darão","they-will-give"],["honra","honour"],["a","to"],["seus","their"],["maridos,","husbands,"],["desde","since"],["a","the"],["maior","greater"],["até","until"],["a","the"],["menor.","least."]]},
  {num:21,words:[["E","And"],["pareceram","they-seemed"],["bem","good"],["estas","these"],["palavras","words"],["aos","to-the"],["olhos","eyes"],["do rei e","king's"],["dos","of-the"],["príncipes;","princes;"],["e","and"],["fez","made"],["o","the"],["rei","king"],["conforme a","according-to"],["palavra","word"],["de","of"],["Memucã.","Memucan."]]},
  {num:22,words:[["Então","Then"],["enviou","sent"],["cartas","letters"],["a","the"],["todas","all"],["as","the"],["províncias","provinces"],["do rei,","king's"],["a","to"],["cada","every"],["província","province"],["segundo","according-to"],["a","the"],["sua","his"],["escrita,","writing,"],["e","and"],["a","to"],["cada","every"],["povo","people"],["segundo","according-to"],["a","the"],["sua","his"],["língua:","tongue:"],["que","that"],["cada","every"],["homem","man"],["fosse","was"],["senhor","lord"],["em","in"],["sua","his"],["casa,","house,"],["e","and"],["que","that"],["se","itself"],["publicasse","issued"],["conforme a","according-to"],["língua","tongue"],["de","of"],["cada","every"],["povo.","people."]]}
];
var v2 = [
  {num:1,words:[["Passadas","Former"],["essas","those"],["coisas,","things,"],["e","and"],["apaziguado","reconciled"],["já","already"],["o","the"],["furor","fury"],["do rei","king's"],["Assuero,","Ahasuerus,"],["lembrou-se","remembered"],["de","of"],["Vasti,","Vashti,"],["e","and"],["do que","than"],["ela","she"],["fizera,","had-made,"],["e","and"],["do que","than"],["se","if"],["tinha","had"],["decretado","appeased"],["a seu respeito.","concerning-him"]]},
  {num:2,words:[["Então","Then"],["disseram","they-said"],["os","the"],["servos","servants"],["do rei,","king's"],["que","that"],["lhe","to-him"],["serviam:","they-served:"],["Busquem-se","They-seek-themselves"],["para","for"],["o","the"],["rei","king"],["moças","maidens"],["virgens,","virgins,"],["formosas","beautiful"],["à","to-the"],["vista.","picture."]]},
  {num:3,words:[["E","And"],["ponha","footstool"],["o","the"],["rei","king"],["comissários","commissar"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["do","of-the"],["seu","his"],["reino,","kingdom,"],["que","that"],["ajuntem","they-add"],["todas","all"],["as","the"],["moças","maidens"],["virgens,","virgins,"],["formosas","beautiful"],["à","to-the"],["vista,","picture,"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã,","Shushan,"],["na","in-the"],["casa","house"],["das","of-the"],["mulheres,","women,"],["aos","to-the"],["cuidados","care"],["de","of"],["Hegai,","Hegai,"],["eunuco","eunuch"],["do rei,","king's"],["guarda","guard"],["das","of-the"],["mulheres,","women,"],["e","and"],["deem-se-lhes","they-give-themselves-to-them"],["os","the"],["seus","their"],["unguentos.","ointments."]]},
  {num:4,words:[["E","And"],["a","the"],["moça","damsel"],["que","that"],["parecer","seem"],["bem","good"],["aos","to-the"],["olhos","eyes"],["do rei","king's"],["reine","reigning"],["em lugar de","in-place-of"],["Vasti.","Vashti."],["E","And"],["isto","this"],["pareceu","seemed"],["bem","good"],["aos","to-the"],["olhos","eyes"],["do rei,","king's"],["e","and"],["assim","thus"],["fez.","made."]]},
  {num:5,words:[["Havia","There-was"],["então","then"],["um","a"],["homem","man"],["judeu","Jew"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã,","Shushan,"],["cujo","whose"],["nome","name"],["era","was"],["Mardoqueu,","Mordecai,"],["filho","son"],["de","of"],["Jair,","Jair,"],["filho","son"],["de","of"],["Simei,","Shimei,"],["filho","son"],["de","of"],["Quis,","Willed,"],["homem","man"],["benjamita,","benjamite,"]]},
  {num:6,words:[["Que","That"],["fora","had-been"],["transportado","laden"],["de","of"],["Jerusalém,","Jerusalem,"],["com","with"],["os","the"],["exilados","exile"],["que","that"],["foram","they-were"],["transportados","laden"],["com","with"],["Jeconias,","Jeconiah,"],["rei","king"],["de","of"],["Judá,","Judah,"],["o","the"],["qual","which"],["transportara","had-laden"],["Nabucodonosor,","Nebuchadnezzar,"],["rei","king"],["de","of"],["Babilônia.","Babylon."]]},
  {num:7,words:[["Este","This"],["criara","had-appertained"],["Hadassa","Hadassah"],["(que","(that"],["é","is"],["Ester,","Esther,"],["filha","daughter"],["de","of"],["seu","his"],["tio),","uncle),"],["porque","because"],["não","not"],["tinha","had"],["pai","father"],["nem","nor"],["mãe,","mother,"],["e","and"],["era","was"],["moça","damsel"],["bela","beautiful"],["de","of"],["parecer,","seem,"],["e","and"],["formosa","fair"],["à","to-the"],["vista;","picture;"],["e","and"],["morrendo","dying"],["seu","his"],["pai","father"],["e","and"],["sua","his"],["mãe,","mother,"],["Mardoqueu","Mordecai"],["a","the"],["tomara","had-taken"],["por","by"],["sua","his"],["filha.","daughter."]]},
  {num:8,words:[["E sucedeu que,","and-it-came-to-pass-that"],["divulgando-se","spreading-himself"],["o","the"],["mandado","commandment"],["do rei e","king's"],["a","the"],["sua","his"],["lei,","law,"],["e","and"],["ajuntando-se","adding-himself"],["muitas","many"],["moças","maidens"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã,","Shushan,"],["aos","to-the"],["cuidados","care"],["de","of"],["Hegai,","Hegai,"],["também","also"],["levaram","they-carried"],["Ester","Esther"],["à","to-the"],["casa","house"],["do rei,","king's"],["aos","to-the"],["cuidados","care"],["de","of"],["Hegai,","Hegai,"],["guarda","guard"],["das","of-the"],["mulheres.","women."]]},
  {num:9,words:[["E","And"],["a","the"],["moça","damsel"],["pareceu","seemed"],["formosa","fair"],["aos","to-the"],["seus","her"],["olhos,","eyes,"],["e","and"],["alcançou","obtained"],["graça","grace"],["perante","before"],["ele,","he,"],["pelo","by-the"],["que","that"],["se","itself"],["apressurou","preferred"],["com","with"],["os","the"],["seus","her"],["cosméticos,","cosmetic,"],["e","and"],["em","in"],["lhe","to-him"],["dar","give"],["os","the"],["seus","her"],["alimentos,","meats,"],["como","as"],["também","also"],["em","in"],["lhe","to-him"],["dar","give"],["sete","seven"],["moças","maidens"],["de","of"],["respeito","concerning"],["da","of-the"],["casa","house"],["do rei;","king's"],["e","and"],["a","her"],["fez","made"],["passar","pass"],["com","with"],["as","the"],["suas","her"],["moças","maidens"],["ao","to-the"],["melhor","better"],["lugar","place"],["da","of-the"],["casa","house"],["das","of-the"],["mulheres.","women."]]},
  {num:10,words:[["Ester,","Esther,"],["porém,","but,"],["não","not"],["declarou","declared"],["o","the"],["seu","her"],["povo","people"],["e","and"],["a","the"],["sua","her"],["parentela,","kindred,"],["porque","because"],["Mardoqueu","Mordecai"],["lhe","to-her"],["tinha","had"],["ordenado","ordained"],["que","that"],["não","not"],["o","it"],["declarasse.","declared."]]},
  {num:11,words:[["E","And"],["passeava","strolled"],["Mardoqueu","Mordecai"],["cada","every"],["dia","day"],["diante","before"],["do","of-the"],["pátio","court"],["da","of-the"],["casa","house"],["das","of-the"],["mulheres,","women,"],["para","for"],["se","himself"],["informar","to-acquaint"],["de","of"],["como","as"],["Ester","Esther"],["passava,","passed,"],["e","and"],["do que","than"],["lhe","to-her"],["sucederia.","should-happen."]]},
  {num:12,words:[["E","And"],["chegando","coming"],["já","already"],["a","the"],["vez","time"],["de","of"],["cada","every"],["moça,","damsel,"],["para","to"],["ir","go"],["ao","to-the"],["rei","king"],["Assuero,","Ahasuerus,"],["depois que","after"],["fora","outside"],["feito","made"],["a","the"],["ela","she"],["segundo","according-to"],["a","the"],["lei","law"],["das","of-the"],["mulheres,","women,"],["por","by"],["doze","twelve"],["meses","months"],["(porque","(because"],["assim","thus"],["se","themselves"],["cumpriam","they-fulfil"],["os","the"],["dias","days"],["das","of-the"],["suas","their"],["purificações,","distillation,"],["seis","six"],["meses","months"],["com","with"],["óleo","oil"],["de","of"],["mirra,","myrrh,"],["e","and"],["seis","six"],["meses","months"],["com","with"],["especiarias,","spices,"],["e","and"],["com","with"],["as","the"],["coisas","things"],["para","for"],["a","the"],["purificação","distillation"],["das","of-the"],["mulheres),","women),"]]},
  {num:13,words:[["Dessa","Of-that"],["maneira,","manner,"],["pois,","for,"],["entrava","entered"],["a","the"],["moça","damsel"],["à","to-the"],["presença","presence"],["do rei;","king's"],["tudo","all"],["quanto","as"],["ela","she"],["dizia","said"],["se","if"],["lhe","to-her"],["dava,","gave,"],["para","to"],["levar","to-carry"],["consigo","with-him"],["da","of-the"],["casa","house"],["das","of-the"],["mulheres","women"],["à","to-the"],["casa","house"],["do rei;","king's"]]},
  {num:14,words:[["À","To-the"],["tarde","evening"],["entrava,","entered,"],["e","and"],["pela","by-the"],["manhã","morning"],["retornava","returned"],["à","to-the"],["segunda","second"],["casa","house"],["das","of-the"],["mulheres,","women,"],["aos","to-the"],["cuidados","care"],["de","of"],["Saasgaz,","Shaashgaz,"],["eunuco","eunuch"],["do rei,","king's"],["guarda","guard"],["das","of-the"],["concubinas;","concubines;"],["não","not"],["retornava","returned"],["mais","more"],["ao","to-the"],["rei,","king,"],["salvo se","unless"],["o","the"],["rei","king"],["a","her"],["desejasse,","desired,"],["e","and"],["fosse","was"],["chamada","called"],["por","by"],["nome.","name."]]},
  {num:15,words:[["Chegando,","Coming,"],["pois,","for,"],["a","the"],["vez","time"],["de","of"],["Ester,","Esther,"],["filha","daughter"],["de","of"],["Abiail,","Abihail,"],["tio","uncle"],["de","of"],["Mardoqueu","Mordecai"],["(que","(that"],["a","the"],["tomara","had-taken"],["por","by"],["sua","his"],["filha),","daughter),"],["para","to"],["ir","go"],["ao","to-the"],["rei,","king,"],["coisa","thing"],["nenhuma","neither"],["pediu,","asked,"],["senão","save"],["o","the"],["que","that"],["disse","said"],["Hegai,","Hegai,"],["eunuco","eunuch"],["do rei,","king's"],["guarda","guard"],["das","of-the"],["mulheres;","women;"],["e","and"],["alcançava","obtained"],["Ester","Esther"],["graça","grace"],["aos","to-the"],["olhos","eyes"],["de","of"],["todos","all"],["quantos","how many"],["a","her"],["viam.","they-saw."]]},
  {num:16,words:[["Assim,","Thus,"],["foi","was"],["levada","brought"],["Ester","Esther"],["ao","to-the"],["rei","king"],["Assuero,","Ahasuerus,"],["à","to-the"],["sua","his"],["casa","house"],["real,","royal,"],["no","in-the"],["décimo","tenth"],["mês,","month,"],["que","that"],["é","is"],["o","the"],["mês","month"],["de","of"],["Tebete,","Tebeth,"],["no","in-the"],["sétimo","seventh"],["ano","year"],["do","of-the"],["seu","his"],["reinado.","reign."]]},
  {num:17,words:[["E","And"],["o","the"],["rei","king"],["amou","loved"],["Ester","Esther"],["mais","more"],["do que","than"],["todas","all"],["as","the"],["mulheres,","women,"],["e","and"],["alcançou","obtained"],["perante","before"],["ele","he"],["graça","grace"],["e","and"],["benevolência","kindness"],["mais","more"],["do que","than"],["todas","all"],["as","the"],["virgens;","virgins;"],["e","and"],["pôs","placed"],["a","the"],["coroa","crown"],["real","royal"],["na","in-the"],["sua","his"],["cabeça,","head,"],["e","and"],["a","her"],["fez","made"],["rainha","queen"],["em lugar de","in-place-of"],["Vasti.","Vashti."]]},
  {num:18,words:[["Então","Then"],["o","the"],["rei","king"],["fez","made"],["um","a"],["grande","great"],["banquete","banquet"],["a","to"],["todos","all"],["os","of"],["seus","his"],["príncipes","princes"],["e","and"],["aos","to-the"],["seus","his"],["servos,","servants,"],["que","that"],["era","was"],["o","the"],["banquete","banquet"],["de","of"],["Ester,","Esther,"],["e","and"],["deu","gave"],["repouso","rest"],["às","to-the"],["províncias,","provinces,"],["e","and"],["deu","gave"],["presentes","presents"],["segundo","according-to"],["a","the"],["disposição","disposition"],["do rei.","king's"]]},
  {num:19,words:[["E","And"],["ajuntando-se","adding-himself"],["pela","by-the"],["segunda","second"],["vez","time"],["as","the"],["virgens,","virgins,"],["Mardoqueu","Mordecai"],["estava","was"],["assentado","sat"],["à","to-the"],["porta","exit"],["do rei.","king's"]]},
  {num:20,words:[["Ester,","Esther,"],["porém,","but,"],["não","not"],["declarava","declared"],["a","the"],["sua","her"],["parentela","kindred"],["e","and"],["o","the"],["seu","her"],["povo,","people,"],["como","as"],["Mardoqueu","Mordecai"],["lhe","to-him"],["ordenara,","had-ordained,"],["porque","because"],["Ester","Esther"],["cumpria","fulfil"],["o","the"],["mandado","commandment"],["de","of"],["Mardoqueu,","Mordecai,"],["como","as"],["quando","when"],["a","her"],["criara.","had-appertained."]]},
  {num:21,words:[["Naqueles","In-that"],["dias,","days,"],["assentando-se","settling-himself"],["Mardoqueu","Mordecai"],["à","to-the"],["porta","exit"],["do rei,","king's"],["dois","two"],["eunucos","eunuchs"],["do rei,","king's"],["dos","of-the"],["guardas","guards"],["da","of-the"],["porta,","exit,"],["Bigtã","Teresh"],["e","and"],["Teres,","To-have,"],["grandemente","greatly"],["se","themselves"],["indignaram,","bigthan,"],["e","and"],["tramaram","they-brewed"],["atentar","to-assault"],["contra","against"],["o","the"],["rei","king"],["Assuero.","Ahasuerus."]]},
  {num:22,words:[["E","And"],["veio","came"],["isso","that"],["ao","to-the"],["conhecimento","knowledge"],["de","of"],["Mardoqueu,","Mordecai,"],["e","and"],["ele","it"],["fez","made"],["saber","know"],["à","to-the"],["rainha","queen"],["Ester,","Esther,"],["e","and"],["Ester","Esther"],["o","it"],["disse","said"],["ao","to-the"],["rei,","king,"],["em","in"],["nome","name"],["de","of"],["Mardoqueu.","Mordecai."]]},
  {num:23,words:[["E","And"],["inquiriu-se","inquired-himself"],["o","the"],["assunto,","matter,"],["e","and"],["se","if"],["descobriu,","uncovered,"],["e","and"],["ambos","both"],["foram","they-were"],["enforcados","inquisition"],["numa","in-a"],["forca;","gallows;"],["e","and"],["foi","was"],["escrito","written"],["nas","in-the"],["crônicas","chronicles"],["perante","before"],["o","the"],["rei.","king."]]}
];
var v3 = [
  {num:1,words:[["Depois","Afterwards"],["dessas","of-that"],["coisas,","things,"],["o","the"],["rei","king"],["Assuero","Ahasuerus"],["engrandeceu","magnified"],["Hamã,","Haman,"],["filho","son"],["de","of"],["Hamedata,","Hammedatha,"],["agagita,","agagite,"],["e","and"],["o","him"],["exaltou,","abased,"],["e","and"],["pôs","placed"],["o","the"],["seu","his"],["assento","seat"],["acima","above"],["de","of"],["todos","all"],["os","the"],["príncipes","princes"],["que","that"],["estavam","they-were"],["com","with"],["ele.","he."]]},
  {num:2,words:[["E","And"],["todos","all"],["os","the"],["servos","servants"],["do rei,","king's"],["que","that"],["estavam","they-were"],["à","to-the"],["porta","exit"],["do rei,","king's"],["se","if"],["inclinavam","reverenced"],["e","and"],["se","if"],["prostravam","reverenced"],["perante","before"],["Hamã,","Haman,"],["porque","because"],["assim","thus"],["tinha","had"],["ordenado","ordained"],["o","the"],["rei","king"],["acerca","concerning"],["dele;","of-him;"],["porém","but"],["Mardoqueu","Mordecai"],["não","not"],["se","himself"],["inclinava","reverenced"],["nem","nor"],["se","himself"],["prostrava.","reverenced."]]},
  {num:3,words:[["Então","Then"],["os","the"],["servos","servants"],["do rei,","king's"],["que","that"],["estavam","they-were"],["à","to-the"],["porta","exit"],["do rei,","king's"],["disseram","they-said"],["a","to"],["Mardoqueu:","Mordecai:"],["Por","By"],["que","that"],["transgrides","you-transgress"],["o","the"],["mandado","commandment"],["do rei?","king's"]]},
  {num:4,words:[["E sucedeu que,","and-it-came-to-pass-that"],["dizendo-lhe","saying-to-him"],["eles","they"],["isso","that"],["de","of"],["dia","day"],["em","in"],["dia,","day,"],["e","and"],["não","not"],["lhes","to-them"],["dando","giving"],["ele","he"],["ouvidos,","ears,"],["o","him"],["fizeram","they-made"],["saber","know"],["a","the"],["Hamã,","Haman,"],["para","to"],["verem","to-see"],["se","if"],["as","the"],["palavras","words"],["de","of"],["Mardoqueu","Mordecai"],["se","themselves"],["sustentariam,","they-should-laziness,"],["porque","because"],["ele","he"],["lhes","to-them"],["tinha","had"],["declarado","declared"],["que","that"],["era","was"],["judeu.","Jew."]]},
  {num:5,words:[["Vendo,","Seeing,"],["pois,","for,"],["Hamã","Haman"],["que","that"],["Mardoqueu","Mordecai"],["não","not"],["se","himself"],["inclinava","reverenced"],["nem","nor"],["se","himself"],["prostrava","reverenced"],["diante","before"],["dele,","of-him,"],["Hamã","Haman"],["se","himself"],["encheu","filled"],["de","of"],["furor.","fury."]]},
  {num:6,words:[["Porém","But"],["considerou","accounted"],["pouco","few"],["atentar","to-assault"],["só","only"],["contra","against"],["Mardoqueu","Mordecai"],["(porque","(because"],["lhe","to-him"],["haviam","they-had"],["declarado","declared"],["de","of"],["que","that"],["povo","people"],["era","was"],["Mardoqueu);","Mordecai);"],["Hamã,","Haman,"],["pois,","for,"],["procurou","sought"],["destruir","destroy"],["todos","all"],["os","the"],["judeus","Jews"],["que","that"],["havia","there-was"],["em","in"],["todo","all"],["o","the"],["reino","kingdom"],["de","of"],["Assuero,","Ahasuerus,"],["o povo de","nephi"],["Mardoqueu.","Mordecai."]]},
  {num:7,words:[["No","In-the"],["primeiro","first"],["mês","month"],["(que","(that"],["é","is"],["o","the"],["mês","month"],["de","of"],["Nisã),","Nisan),"],["no","in-the"],["ano","year"],["duodécimo","twelfth"],["do rei","king's"],["Assuero,","Ahasuerus,"],["se","if"],["lançou","cast"],["Pur,","Pur,"],["isto é,","that-is"],["sorte,","lot,"],["perante","before"],["Hamã,","Haman,"],["de","of"],["dia","day"],["em","in"],["dia,","day,"],["e","and"],["de","of"],["mês","month"],["em","in"],["mês,","month,"],["até","until"],["o","the"],["duodécimo","twelfth"],["mês,","month,"],["que","that"],["é","is"],["o","the"],["mês","month"],["de","of"],["Adar.","Adar."]]},
  {num:8,words:[["E","And"],["Hamã","Haman"],["disse","said"],["ao","to-the"],["rei","king"],["Assuero:","Ahasuerus:"],["Há","There-is"],["um","a"],["povo","people"],["espalhado","disseminated"],["e","and"],["dividido","divided"],["entre","among"],["os","the"],["povos","nations"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["do","of-the"],["teu","your"],["reino,","kingdom,"],["cujas","whose"],["leis","laws"],["são","they-are"],["diferentes","different"],["das","of-the"],["leis","laws"],["de","of"],["todos","all"],["os","the"],["povos,","nations,"],["e","and"],["tampouco","neither"],["cumprem","they-fulfil"],["as","the"],["leis","laws"],["do rei,","king's"],["pelo","by-the"],["que","that"],["não","not"],["convém","befits"],["ao","to-the"],["rei","king"],["deixá-los","leave-them"],["ficar.","remain."]]},
  {num:9,words:[["Se","If"],["bem","good"],["parecer","seem"],["ao","to-the"],["rei,","king,"],["escreva-se","writes-himself"],["que","that"],["os","them"],["matem;","they-slay;"],["e","and"],["eu","I"],["porei","I-will-place"],["nas","in-the"],["mãos","hands"],["dos","of-the"],["que","that"],["fizerem","they-will-make"],["a","the"],["obra","work"],["dez","ten"],["mil","thousand"],["talentos","talents"],["de","of"],["prata,","silver,"],["para que","that"],["se","themselves"],["depositem","they-deposit"],["nos","in-the"],["tesouros","treasures"],["do rei.","king's"]]},
  {num:10,words:[["Então","Then"],["tirou","took-away"],["o","the"],["rei","king"],["o","the"],["seu","his"],["anel","ring"],["da","of-the"],["sua","his"],["mão,","hand,"],["e","and"],["o","it"],["deu","gave"],["a","to"],["Hamã,","Haman,"],["filho","son"],["de","of"],["Hamedata,","Hammedatha,"],["agagita,","agagite,"],["adversário","adversary"],["dos","of-the"],["judeus.","Jews."]]},
  {num:11,words:[["E","And"],["disse","said"],["o","the"],["rei","king"],["a","the"],["Hamã:","Haman:"],["Esta","This"],["prata","silver"],["te","you"],["é","is"],["dada,","given,"],["como","as"],["também","also"],["esse","that"],["povo,","people,"],["para","to"],["fazeres","to-make"],["dele","of-it"],["o","the"],["que","that"],["bem","good"],["parecer","seem"],["aos","to-the"],["teus","your"],["olhos.","eyes."]]},
  {num:12,words:[["Então","Then"],["chamaram","they-called"],["os","the"],["escrivães","scribe"],["do rei","king's"],["no","in-the"],["primeiro","first"],["mês,","month,"],["no","in-the"],["dia","day"],["treze","thirteen"],["do","of-the"],["mesmo,","even,"],["e","and"],["conforme","according-to"],["tudo","all"],["quanto","as"],["Hamã","Haman"],["mandou","commanded"],["se","himself"],["escreveu","wrote"],["aos","to-the"],["príncipes","princes"],["do rei,","king's"],["e","and"],["aos","to-the"],["governadores","governors"],["que","that"],["havia","there-was"],["sobre","upon"],["cada","every"],["província,","province,"],["e","and"],["aos","to-the"],["principais","chief"],["de","of"],["cada","every"],["povo;","people;"],["a","to"],["cada","every"],["província","province"],["segundo","according-to"],["a","the"],["sua","their"],["escrita,","writing,"],["e","and"],["a","to"],["cada","every"],["povo","people"],["segundo","according-to"],["a","the"],["sua","their"],["escrita,","writing,"],["e","and"],["a","to"],["cada","every"],["povo","people"],["segundo","according-to"],["a","the"],["sua","their"],["língua;","tongue;"],["em","in"],["nome","name"],["do rei","king's"],["Assuero","Ahasuerus"],["se","himself"],["escreveu,","wrote,"],["e","and"],["com","with"],["o","the"],["anel","ring"],["do rei","king's"],["se","himself"],["selou.","prepaid."]]},
  {num:13,words:[["E","And"],["as","the"],["cartas","letters"],["se","themselves"],["enviaram","they-sent"],["pela","by-the"],["mão","hand"],["dos","of-the"],["correios","mail"],["a","the"],["todas","all"],["as","the"],["províncias","provinces"],["do rei,","king's"],["que","that"],["destruíssem,","they-destroyed,"],["matassem,","they-slew,"],["e","and"],["fizessem","they-made"],["perecer","to-perish"],["todos","all"],["os","the"],["judeus,","Jews,"],["desde o","beginning"],["moço","lad"],["até","until"],["o","the"],["velho,","old,"],["crianças","children"],["e","and"],["mulheres,","women,"],["em","in"],["um","a"],["mesmo","same"],["dia,","day,"],["a","to"],["treze","thirteen"],["do","of-the"],["duodécimo","twelfth"],["mês","month"],["(que","(that"],["é","is"],["o","the"],["mês","month"],["de","of"],["Adar),","Adar),"],["e","and"],["que","that"],["saqueassem","assault"],["o","the"],["seu","his"],["despojo.","I-spoil."]]},
  {num:14,words:[["Uma","A"],["cópia","copy"],["do","of-the"],["escrito","written"],["que","that"],["se","itself"],["proclamasse","proclaimed"],["como","as"],["lei","law"],["em","in"],["cada","every"],["província","province"],["era","was"],["publicada","issued"],["a","to"],["todos","all"],["os","the"],["povos,","nations,"],["para que","that"],["estivessem","they-were"],["preparados","prepared"],["para","for"],["aquele","that"],["dia.","day."]]},
  {num:15,words:[["Os","The"],["correios,","mail,"],["pois,","for,"],["impelidos","hastened"],["pela","by-the"],["palavra","word"],["do rei,","king's"],["saíram,","they-went-forth,"],["e","and"],["a","the"],["lei","law"],["se","himself"],["proclamou","proclaimed"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã;","Shushan;"],["e","and"],["o","the"],["rei e","king's"],["Hamã","Haman"],["se","themselves"],["assentaram","they-settled"],["para","to"],["beber;","drink;"],["porém","but"],["a","the"],["cidade","city"],["de","of"],["Susã","Shushan"],["estava","was"],["agitada.","abet."]]}
];
var v4 = [
  {num:1,words:[["Quando","When"],["Mardoqueu","Mordecai"],["soube","knew"],["tudo","all"],["quanto","as"],["se","if"],["havia","had"],["passado,","passed,"],["rasgou","rent"],["Mardoqueu","Mordecai"],["as","the"],["suas","his"],["vestes,","garments,"],["e","and"],["vestiu-se","clothed-himself"],["de","of"],["saco","sack"],["e","and"],["de","of"],["cinza,","ashes,"],["e","and"],["saiu","went-forth"],["pelo","by-the"],["meio","midst"],["da","of-the"],["cidade,","city,"],["e","and"],["clamou","cried"],["com","with"],["grande","great"],["e","and"],["amargo","bitter"],["clamor;","cry;"]]},
  {num:2,words:[["E","And"],["chegou","came"],["até","until"],["diante","before"],["da","of-the"],["porta","exit"],["do rei,","king's"],["porque","because"],["ninguém","none"],["vestido","clothed"],["de","of"],["saco","sack"],["podia","could"],["entrar","to-enter"],["pelas","by-the"],["portas","gates"],["do rei.","king's"]]},
  {num:3,words:[["E","And"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["aonde","whither"],["a","the"],["palavra","word"],["do rei e","king's"],["a","the"],["sua","his"],["lei","law"],["chegavam,","they-came,"],["havia","there-was"],["entre","among"],["os","the"],["judeus","Jews"],["grande","great"],["luto,","mourning,"],["com","with"],["jejum,","fasting,"],["e","and"],["choro,","I-weeping,"],["e","and"],["lamentação,","lamentation,"],["e","and"],["muitos","many"],["estavam","they-were"],["deitados","lay"],["em","in"],["saco","sack"],["e","and"],["em","in"],["cinza.","ashes."]]},
  {num:4,words:[["Então","Then"],["vieram","they-came"],["as","the"],["moças","maidens"],["de","of"],["Ester,","Esther,"],["e","and"],["os","the"],["seus","his"],["eunucos,","eunuchs,"],["e","and"],["fizeram-lhe","they-made-to-him"],["saber,","know,"],["do que","than"],["a","the"],["rainha","queen"],["muito","much"],["se","himself"],["doeu;","ached;"],["e","and"],["mandou","commanded"],["roupas","clothes"],["para","to"],["vestir","to-clothe"],["Mardoqueu,","Mordecai,"],["e","and"],["tirar-lhe","to-take-from-him"],["o","the"],["pano","cloth"],["de","of"],["saco,","sack,"],["porém","but"],["ele","he"],["não","not"],["as","them"],["aceitou.","shared."]]},
  {num:5,words:[["Então","Then"],["Ester","Esther"],["chamou","called"],["Hatá","Hatach"],["(um","(a"],["dos","of-the"],["eunucos","eunuchs"],["do rei,","king's"],["que","that"],["este","this"],["tinha","had"],["posto","placed"],["na","in-the"],["presença","presence"],["dela),","of-her),"],["e","and"],["deu-lhe","gave-to-him"],["mandado","commandment"],["para","to"],["ir","go"],["a","the"],["Mardoqueu,","Mordecai,"],["para","to"],["saber","know"],["o","the"],["que","that"],["era","was"],["aquilo,","that,"],["e","and"],["o","the"],["seu","her"],["motivo.","cause."]]},
  {num:6,words:[["E","And"],["saindo","I-go-forth"],["Hatá","Hatach"],["a","to"],["Mardoqueu,","Mordecai,"],["à","to-the"],["praça","street"],["da","of-the"],["cidade,","city,"],["que","that"],["estava","was"],["diante","before"],["da","of-the"],["porta","exit"],["do rei,","king's"]]},
  {num:7,words:[["Mardoqueu","Mordecai"],["lhe","to-him"],["fez","made"],["saber","know"],["tudo","all"],["quanto","as"],["lhe","to-him"],["tinha","had"],["sucedido,","happened,"],["como","as"],["também","also"],["a","the"],["oferta","offering"],["da","of-the"],["prata,","silver,"],["que","that"],["Hamã","Haman"],["dissera","had-said"],["que","that"],["daria","should-give"],["para","for"],["os","the"],["tesouros","treasures"],["do rei,","king's"],["pelo","by-the"],["extermínio","treasuries"],["dos","of-the"],["judeus.","Jews."]]},
  {num:8,words:[["Também","Also"],["lhe","to-him"],["deu","gave"],["a","the"],["cópia","copy"],["da","of-the"],["lei","law"],["escrita,","writing,"],["que","that"],["se","itself"],["publicara","had-issued"],["em","in"],["Susã","Shushan"],["para","for"],["os","the"],["destruir,","destroy,"],["para","for"],["a","to"],["mostrar","to-show"],["a","to"],["Ester,","Esther,"],["e","and"],["lhe","to-him"],["fazer","make"],["saber,","know,"],["e","and"],["para","for"],["lhe","to-him"],["ordenar","to-ordain"],["que","that"],["fosse","was"],["ter","have"],["com","with"],["o","the"],["rei,","king,"],["e","and"],["lhe","to-him"],["pedisse","asked"],["e","and"],["suplicasse","besought"],["na","in-the"],["sua","her"],["presença","presence"],["pelo","by-the"],["seu","her"],["povo.","people."]]},
  {num:9,words:[["Foi,","Was,"],["pois,","for,"],["Hatá,","Hatach,"],["e","and"],["fez","made"],["saber","know"],["a","the"],["Ester","Esther"],["as","the"],["palavras","words"],["de","of"],["Mardoqueu.","Mordecai."]]},
  {num:10,words:[["Então","Then"],["falou","spoke"],["Ester","Esther"],["a","to"],["Hatá,","Hatach,"],["e","and"],["mandou-lhe","commanded-to-him"],["dizer","say"],["a","to"],["Mardoqueu:","Mordecai:"]]},
  {num:11,words:[["Todos","All"],["os","the"],["servos","servants"],["do rei,","king's"],["e","and"],["o","the"],["povo","people"],["das","of-the"],["províncias","provinces"],["do rei,","king's"],["bem","good"],["sabem","they-know"],["que","that"],["para","for"],["todo","every"],["homem","man"],["ou","or"],["mulher","dame"],["que","that"],["entrar","to-enter"],["no","in-the"],["pátio","court"],["interior","inner"],["à","to-the"],["presença","presence"],["do rei,","king's"],["sem","without"],["ser","be"],["chamado,","called,"],["não","not"],["há","there-is"],["senão","save"],["uma","a"],["sentença,","sentence,"],["que","that"],["morra,","dies,"],["salvo se","unless"],["o","the"],["rei","king"],["estender","to-stretch"],["para","for"],["ele","he"],["o","the"],["cetro","sceptre"],["de","of"],["ouro,","gold,"],["para que","that"],["viva;","hurray;"],["e","and"],["eu","I"],["estes","these"],["trinta","thirty"],["dias","days"],["não","not"],["fui","I-was"],["chamada","called"],["para","to"],["entrar","to-enter"],["na","in-the"],["presença","presence"],["do rei.","king's"]]},
  {num:12,words:[["E","And"],["fizeram","they-made"],["saber","know"],["a","the"],["Mardoqueu","Mordecai"],["as","the"],["palavras","words"],["de","of"],["Ester.","Esther."]]},
  {num:13,words:[["Então","Then"],["disse","said"],["Mardoqueu","Mordecai"],["que","that"],["tornassem","they-became"],["a","to"],["dizer","say"],["a","to"],["Ester:","Esther:"],["Não","Not"],["imagines","you-fancy"],["na","in-the"],["tua","your"],["alma","soul"],["que","that"],["escaparás","you-will-escape"],["na","in-the"],["casa","house"],["do rei,","king's"],["mais","more"],["do que","than"],["todos","all"],["os","the"],["outros","other"],["judeus.","Jews."]]},
  {num:14,words:[["Porque,","Because,"],["se","if"],["de todo","wholly"],["te","you"],["calares","to-still"],["neste","in-this"],["tempo,","time,"],["socorro","help"],["e","and"],["livramento","deliverance"],["de","of"],["outra","other"],["parte","part"],["sairá","will-go-forth"],["para","for"],["os","the"],["judeus,","Jews,"],["mas","but"],["tu","you"],["e","and"],["a","the"],["casa","house"],["de","of"],["teu","your"],["pai","father"],["perecereis;","you-will-perish;"],["e","and"],["quem","who"],["sabe","knows"],["se","himself"],["para","for"],["tal","such"],["tempo","time"],["como","as"],["este","this"],["chegaste","you-came"],["a","to"],["este","this"],["reino?","kingdom?"]]},
  {num:15,words:[["Então","Then"],["disse","said"],["Ester","Esther"],["que","that"],["respondessem","they-answered"],["a","to"],["Mardoqueu:","Mordecai:"]]},
  {num:16,words:[["Vai,","Go,"],["ajunta","gathereth"],["todos","all"],["os","the"],["judeus","Jews"],["que","that"],["se","themselves"],["acharem","to-find"],["em","in"],["Susã,","Shushan,"],["e","and"],["jejuai","bridechamber"],["por","by"],["mim,","me,"],["e","and"],["não","not"],["comais","you-eat"],["nem","nor"],["bebais","you-drink"],["por","by"],["três","three"],["dias,","days,"],["nem","nor"],["de","of"],["dia","day"],["nem","nor"],["de","of"],["noite,","night,"],["e","and"],["eu","I"],["e","and"],["as","the"],["minhas","my"],["moças","maidens"],["também","also"],["assim","thus"],["jejuaremos;","we-will-bridechamber;"],["e","and"],["assim","thus"],["irei","I-will-go"],["ter","have"],["com","with"],["o","the"],["rei,","king,"],["ainda que","although"],["não","not"],["seja","is"],["segundo","according-to"],["a","the"],["lei;","law;"],["e","and"],["se","if"],["perecer,","to-perish,"],["pereci.","I-perished."]]},
  {num:17,words:[["Então","Then"],["Mardoqueu","Mordecai"],["foi,","was,"],["e","and"],["fez","made"],["conforme","according-to"],["tudo","all"],["quanto","as"],["Ester","Esther"],["lhe","to-him"],["ordenou.","commanded."]]}
];
var v5 = [
  {num:1,words:[["E sucedeu que,","and-it-came-to-pass-that"],["ao","to-the"],["terceiro","third"],["dia,","day,"],["Ester","Esther"],["se","himself"],["vestiu","clothed"],["de","of"],["seus","his"],["vestidos","clothed"],["reais,","royal,"],["e","and"],["se","if"],["pôs","placed"],["no","in-the"],["pátio","court"],["interior","inner"],["da","of-the"],["casa","house"],["do rei,","king's"],["defronte","in-front-of"],["do","of-the"],["aposento","closet"],["do rei;","king's"],["e","and"],["o","the"],["rei","king"],["estava","was"],["assentado","sat"],["sobre","upon"],["o","the"],["seu","his"],["trono","throne"],["real,","royal,"],["na","in-the"],["casa","house"],["real,","royal,"],["defronte","in-front-of"],["da","of-the"],["porta","exit"],["do","of-the"],["aposento.","closet."]]},
  {num:2,words:[["E sucedeu que,","and-it-came-to-pass-that"],["vendo","seeing"],["o","the"],["rei","king"],["a","the"],["rainha","queen"],["Ester,","Esther,"],["que","that"],["estava","was"],["no","in-the"],["pátio,","court,"],["alcançou","obtained"],["ela","she"],["graça","grace"],["aos","to-the"],["seus","his"],["olhos,","eyes,"],["e","and"],["o","the"],["rei","king"],["apontou","aimed"],["para","for"],["Ester","Esther"],["com","with"],["o","the"],["cetro","sceptre"],["de","of"],["ouro","gold"],["que","that"],["tinha","had"],["na","in-the"],["sua","his"],["mão,","hand,"],["e","and"],["Ester","Esther"],["chegou,","came,"],["e","and"],["tocou","touched"],["a","the"],["ponta","end"],["do","of-the"],["cetro.","sceptre."]]},
  {num:3,words:[["Então","Then"],["o","the"],["rei","king"],["lhe","to-her"],["disse:","said:"],["Que","That"],["é","is"],["o","the"],["que","that"],["tens,","you-have,"],["rainha","queen"],["Ester?","Esther?"],["Ou","Or"],["qual","which"],["é","is"],["a","the"],["tua","your"],["petição?","petition?"],["Até","Until"],["metade","half"],["do","of-the"],["reino","kingdom"],["se","if"],["te","you"],["dará.","will-give."]]},
  {num:4,words:[["E","And"],["disse","said"],["Ester:","Esther:"],["Se","If"],["bem","good"],["parecer","seem"],["ao","to-the"],["rei,","king,"],["venha","comes"],["hoje","today"],["o","the"],["rei","king"],["com","with"],["Hamã","Haman"],["ao","to-the"],["banquete","banquet"],["que","that"],["lhe","to-him"],["preparei.","I-prepared."]]},
  {num:5,words:[["Então","Then"],["disse","said"],["o","the"],["rei:","king:"],["Fazei","Make"],["apressar","to-accelerate"],["Hamã,","Haman,"],["para que","that"],["cumpra","fulfil"],["o","the"],["mandado","commandment"],["de","of"],["Ester.","Esther."],["Indo,","Going,"],["pois,","for,"],["o","the"],["rei e","king's"],["Hamã","Haman"],["ao","to-the"],["banquete","banquet"],["que","that"],["Ester","Esther"],["tinha","had"],["preparado,","prepared,"]]},
  {num:6,words:[["Disse","Said"],["o","the"],["rei","king"],["a","the"],["Ester,","Esther,"],["no","in-the"],["banquete","banquet"],["do","of-the"],["vinho:","wine:"],["Qual","Which"],["é","is"],["a","the"],["tua","your"],["petição?","petition?"],["E","And"],["se","if"],["te","you"],["dará.","will-give."],["E","And"],["qual","which"],["é","is"],["o","the"],["teu","your"],["desejo?","desire?"],["E","And"],["se","if"],["fará,","will-make,"],["ainda que","although"],["seja","is"],["a","the"],["metade","half"],["do","of-the"],["reino.","kingdom."]]},
  {num:7,words:[["Então","Then"],["respondeu","answered"],["Ester,","Esther,"],["e","and"],["disse:","said:"],["Minha","My"],["petição","petition"],["e","and"],["desejo","desire"],["é:","is:"]]},
  {num:8,words:[["Se","If"],["achei","I-found"],["graça","grace"],["aos","to-the"],["olhos","eyes"],["do rei,","king's"],["e","and"],["se","if"],["bem","good"],["parecer","seem"],["ao","to-the"],["rei","king"],["conceder-me","to-bestow-me"],["a","the"],["minha","my"],["petição,","petition,"],["e","and"],["outorgar-me","to-outorgar-me"],["o","the"],["meu","my"],["desejo,","desire,"],["venha","comes"],["o","the"],["rei","king"],["com","with"],["Hamã","Haman"],["ao","to-the"],["banquete","banquet"],["que","that"],["lhes","to-them"],["hei","I-have"],["de","of"],["preparar,","to-prepare,"],["e","and"],["amanhã","tomorrow"],["farei","I-will-make"],["conforme","according-to"],["o","the"],["mandado","commandment"],["do rei.","king's"]]},
  {num:9,words:[["Então","Then"],["saiu","went-forth"],["Hamã","Haman"],["naquele","in-that"],["dia","day"],["alegre","merry"],["e","and"],["de","of"],["bom","good"],["ânimo;","courage;"],["porém,","but,"],["quando","when"],["Hamã","Haman"],["viu","saw"],["Mardoqueu","Mordecai"],["à","to-the"],["porta","exit"],["do rei,","king's"],["e","and"],["que","that"],["não","not"],["se","himself"],["levantara","had-raised-up"],["nem","nor"],["se","himself"],["movera","had-actuated"],["por","by"],["ele,","he,"],["então","then"],["Hamã","Haman"],["se","himself"],["encheu","filled"],["de","of"],["furor","fury"],["contra","against"],["Mardoqueu.","Mordecai."]]},
  {num:10,words:[["Hamã,","Haman,"],["porém,","but,"],["se","if"],["refreou,","curbed,"],["e","and"],["foi","was"],["à","to-the"],["sua","his"],["casa,","house,"],["e","and"],["mandou","commanded"],["chamar","to-call"],["os","the"],["seus","his"],["amigos,","friends,"],["e","and"],["Zeres,","Zeresh,"],["sua","his"],["mulher.","dame."]]},
  {num:11,words:[["E","And"],["contou-lhes","told-to-them"],["Hamã","Haman"],["a","the"],["glória","glory"],["das","of-the"],["suas","his"],["riquezas,","riches,"],["e","and"],["a","the"],["multidão","multitude"],["de","of"],["seus","his"],["filhos,","children,"],["e","and"],["tudo","all"],["em","in"],["que","that"],["o","the"],["rei","king"],["o","him"],["tinha","had"],["engrandecido,","magnified,"],["e","and"],["em","in"],["que","that"],["o","him"],["tinha","had"],["exaltado","exalted"],["sobre","upon"],["os","the"],["príncipes","princes"],["e","and"],["servos","servants"],["do rei.","king's"]]},
  {num:12,words:[["Disse","Said"],["mais","more"],["Hamã:","Haman:"],["Tampouco","Neither"],["a","the"],["rainha","queen"],["Ester","Esther"],["a","to"],["ninguém","none"],["fez","made"],["vir","come"],["com","with"],["o","the"],["rei","king"],["ao","to-the"],["banquete","banquet"],["que","that"],["tinha","had"],["preparado,","prepared,"],["senão","save"],["a","to"],["mim;","me;"],["e","and"],["também","also"],["para","for"],["amanhã","tomorrow"],["estou","I-am"],["convidado","invited"],["por","by"],["ela","she"],["juntamente","together"],["com","with"],["o","the"],["rei.","king."]]},
  {num:13,words:[["Porém","But"],["tudo","all"],["isso","that"],["não","not"],["me","me"],["satisfaz,","satisfies,"],["enquanto","while"],["vir","come"],["o","the"],["judeu","Jew"],["Mardoqueu","Mordecai"],["assentado","sat"],["à","to-the"],["porta","exit"],["do rei.","king's"]]},
  {num:14,words:[["Então","Then"],["lhe","to-him"],["disse","said"],["Zeres,","Zeresh,"],["sua","his"],["mulher,","dame,"],["e","and"],["todos","all"],["os","of"],["seus","his"],["amigos:","friends:"],["Faça-se","Makes-himself"],["uma","a"],["forca","gallows"],["de","of"],["cinquenta","fifty"],["côvados","cubits"],["de","of"],["altura,","height,"],["e","and"],["amanhã","tomorrow"],["dize","say"],["ao","to-the"],["rei","king"],["que","that"],["enforquem","hang"],["nela","in-it"],["Mardoqueu,","Mordecai,"],["e","and"],["então","then"],["entra","enters"],["com","with"],["o","the"],["rei,","king,"],["alegre,","merry,"],["ao","to-the"],["banquete.","banquet."],["E","And"],["este","this"],["conselho","counsel"],["bem","good"],["pareceu","seemed"],["a","to"],["Hamã,","Haman,"],["e","and"],["mandou","commanded"],["fazer","make"],["a","the"],["forca.","gallows."]]}
];
var v6 = [
  {num:1,words:[["Naquela","In-that"],["mesma","same"],["noite","night"],["fugiu","fled"],["o","the"],["sono","sleep"],["do rei;","king's"],["então","then"],["mandou","commanded"],["trazer","to-bring"],["o","the"],["livro","book"],["dos","of-the"],["registros","records"],["das","of-the"],["crônicas,","chronicles,"],["e","and"],["as","them"],["leram","they-read"],["diante","before"],["do rei.","king's"]]},
  {num:2,words:[["E","And"],["achou-se","found-himself"],["escrito","written"],["que","that"],["Mardoqueu","Mordecai"],["tinha","had"],["denunciado","accused"],["Bigtã","Teresh"],["e","and"],["Teres,","To-have,"],["dois","two"],["eunucos","eunuchs"],["do rei,","king's"],["dos","of-the"],["da","of-the"],["guarda","guard"],["da","of-the"],["porta,","exit,"],["que","that"],["procuraram","they-sought"],["pôr","to-place"],["as","the"],["mãos","hands"],["no","in-the"],["rei","king"],["Assuero.","Ahasuerus."]]},
  {num:3,words:[["Então","Then"],["disse","said"],["o","the"],["rei:","king:"],["Que","That"],["honra","honour"],["e","and"],["distinção","distinction"],["se","himself"],["fez","made"],["por isso","therefore"],["a","to"],["Mardoqueu?","Mordecai?"],["E","And"],["os","the"],["moços","lad"],["do rei,","king's"],["seus","their"],["servos,","servants,"],["disseram:","they-said:"],["Coisa","Thing"],["nenhuma","neither"],["se","if"],["lhe","to-him"],["fez.","made."]]},
  {num:4,words:[["Então","Then"],["disse","said"],["o","the"],["rei:","king:"],["Quem","Who"],["está","is"],["no","in-the"],["pátio?","court?"],["E","And"],["Hamã","Haman"],["tinha","had"],["entrado","entered"],["no","in-the"],["pátio","court"],["exterior","external"],["do rei,","king's"],["para","to"],["dizer","say"],["ao","to-the"],["rei","king"],["que","that"],["enforcassem","hang"],["Mardoqueu","Mordecai"],["na","in-the"],["forca","gallows"],["que","that"],["lhe","to-him"],["tinha","had"],["preparado.","prepared."]]},
  {num:5,words:[["E","And"],["os","the"],["moços","lad"],["do rei","king's"],["lhe","to-him"],["disseram:","they-said:"],["Eis que","behold"],["Hamã","Haman"],["está","is"],["no","in-the"],["pátio.","court."],["E","And"],["disse","said"],["o","the"],["rei","king"],["que","that"],["entrasse.","entered."]]},
  {num:6,words:[["E","And"],["entrando","entering"],["Hamã,","Haman,"],["o","the"],["rei","king"],["lhe","to-him"],["disse:","said:"],["Que","That"],["se","itself"],["fará","will-make"],["ao","to-the"],["homem","man"],["a","to"],["quem","who"],["o","the"],["rei","king"],["deseja","desire"],["honrar?","to-horseback?"],["Então","Then"],["Hamã","Haman"],["disse","said"],["no","in-the"],["seu","his"],["coração:","heart:"],["De","Of"],["quem","who"],["se","himself"],["agradará","will-please"],["o","the"],["rei","king"],["para","for"],["lhe","to-him"],["fazer","make"],["honra","honour"],["mais","more"],["do que","than"],["a","to"],["mim?","me?"]]},
  {num:7,words:[["Pelo","By-the"],["que","that"],["disse","said"],["Hamã","Haman"],["ao","to-the"],["rei:","king:"],["Para","For"],["o","the"],["homem","man"],["a","to"],["quem","who"],["o","the"],["rei","king"],["deseja","desire"],["honrar,","to-horseback,"]]},
  {num:8,words:[["Traga-se","Swallows-himself"],["a","it"],["veste","garment"],["real","royal"],["com","with"],["que","that"],["o","the"],["rei","king"],["se","himself"],["costuma","accustoms"],["vestir,","to-clothe,"],["como","as"],["também","also"],["o","the"],["cavalo","horse"],["em","in"],["que","that"],["o","the"],["rei","king"],["costuma","accustoms"],["andar","to-walk"],["montado,","rid,"],["e","and"],["ponha-se-lhe","footstool-himself-to-him"],["a","the"],["coroa","crown"],["real","royal"],["na","in-the"],["sua","his"],["cabeça;","head;"]]},
  {num:9,words:[["E","And"],["entregue-se","delivered-himself"],["a","to"],["veste","garment"],["e","and"],["o","the"],["cavalo","horse"],["à","to-the"],["mão","hand"],["de","of"],["um","a"],["dos","of-the"],["príncipes","princes"],["do rei,","king's"],["dos","of-the"],["maiores","greater"],["senhores,","masters,"],["e","and"],["vistam","they-clothe"],["com","with"],["ela","it"],["aquele","that"],["homem","man"],["a","to"],["quem","who"],["o","the"],["rei","king"],["deseja","desire"],["honrar,","to-horseback,"],["e","and"],["levem-no","they-carry-him"],["a","to"],["cavalo","horse"],["pelas","by-the"],["ruas","streets"],["da","of-the"],["cidade,","city,"],["e","and"],["apregoe-se","brokenhearted-himself"],["diante","before"],["dele:","of-him:"],["Assim","Thus"],["se","himself"],["fará","will-make"],["ao","to-the"],["homem","man"],["a","to"],["quem","who"],["o","the"],["rei","king"],["deseja","desire"],["honrar!","to-horseback!"]]},
  {num:10,words:[["Então","Then"],["disse","said"],["o","the"],["rei","king"],["a","the"],["Hamã:","Haman:"],["Apressa-te,","Accelerates-you,"],["toma","takes"],["a","to"],["veste","garment"],["e","and"],["o","the"],["cavalo,","horse,"],["como","as"],["disseste,","you-said,"],["e","and"],["faze","make"],["assim","thus"],["para","for"],["com","with"],["o","the"],["judeu","Jew"],["Mardoqueu,","Mordecai,"],["que","that"],["está","is"],["assentado","sat"],["à","to-the"],["porta","exit"],["do rei;","king's"],["e","and"],["coisa","thing"],["nenhuma","neither"],["deixes","you-leave"],["falhar","to-miss"],["de","of"],["tudo","all"],["quanto","as"],["disseste.","you-said."]]},
  {num:11,words:[["E","And"],["Hamã","Haman"],["tomou","took"],["a","to"],["veste","garment"],["e","and"],["o","the"],["cavalo,","horse,"],["e","and"],["vestiu","clothed"],["Mardoqueu,","Mordecai,"],["e","and"],["o","him"],["levou","carried"],["a","to"],["cavalo","horse"],["pelas","by-the"],["ruas","streets"],["da","of-the"],["cidade,","city,"],["e","and"],["apregoou","brokenhearted"],["diante","before"],["dele:","of-him:"],["Assim","Thus"],["se","himself"],["fará","will-make"],["ao","to-the"],["homem","man"],["a","to"],["quem","who"],["o","the"],["rei","king"],["deseja","desire"],["honrar!","to-horseback!"]]},
  {num:12,words:[["Depois","Afterwards"],["disso","of-that"],["Mardoqueu","Mordecai"],["voltou","returned"],["para","for"],["a","the"],["porta","exit"],["do rei;","king's"],["porém","but"],["Hamã","Haman"],["se","himself"],["retirou","gittite"],["correndo","flowing"],["à","to-the"],["sua","his"],["casa,","house,"],["desgostoso,","discontented,"],["e","and"],["com","with"],["a","the"],["cabeça","head"],["coberta.","deck."]]},
  {num:13,words:[["E","And"],["contou","told"],["Hamã","Haman"],["a","the"],["Zeres,","Zeresh,"],["sua","his"],["mulher,","dame,"],["e","and"],["a","to"],["todos","all"],["os","of"],["seus","his"],["amigos,","friends,"],["tudo","all"],["quanto","as"],["lhe","to-him"],["tinha","had"],["sucedido.","happened."],["Então","Then"],["os","the"],["seus","his"],["sábios,","wise,"],["e","and"],["Zeres,","Zeresh,"],["sua","his"],["mulher,","dame,"],["lhe","to-him"],["disseram:","they-said:"],["Se","If"],["Mardoqueu,","Mordecai,"],["diante de","before"],["quem","who"],["já","already"],["começaste","you-began"],["a","to"],["cair,","to-fall,"],["é","is"],["da","of-the"],["semente","seed"],["dos","of-the"],["judeus,","Jews,"],["não","not"],["prevalecerás","you-will-prevail"],["contra","against"],["ele,","he,"],["antes","before"],["certamente","certainly"],["cairás","you-will-fall"],["perante","before"],["ele.","he."]]},
  {num:14,words:[["Estando","Being"],["eles","they"],["ainda","yet"],["falando","speaking"],["com","with"],["ele,","he,"],["chegaram","they-came"],["os","the"],["eunucos","eunuchs"],["do rei,","king's"],["e","and"],["se","if"],["apressaram","they-accelerated"],["a","to"],["levar","to-carry"],["Hamã","Haman"],["ao","to-the"],["banquete","banquet"],["que","that"],["Ester","Esther"],["preparara.","had-prepared."]]}
];
var v7 = [
  {num:1,words:[["Indo,","Going,"],["pois,","for,"],["o","the"],["rei","king"],["com","with"],["Hamã,","Haman,"],["para","to"],["beber","drink"],["com","with"],["a","the"],["rainha","queen"],["Ester,","Esther,"]]},
  {num:2,words:[["Disse","Said"],["também","also"],["o","the"],["rei","king"],["a","the"],["Ester","Esther"],["no","in-the"],["segundo","according-to"],["dia,","day,"],["no","in-the"],["banquete","banquet"],["do","of-the"],["vinho:","wine:"],["Qual","Which"],["é","is"],["a","the"],["tua","your"],["petição,","petition,"],["rainha","queen"],["Ester?","Esther?"],["E","And"],["se","if"],["te","you"],["dará.","will-give."],["E","And"],["qual","which"],["é","is"],["o","the"],["teu","your"],["desejo?","desire?"],["Até","Until"],["metade","half"],["do","of-the"],["reino","kingdom"],["se","if"],["te","you"],["dará.","will-give."]]},
  {num:3,words:[["Então","Then"],["respondeu","answered"],["a","the"],["rainha","queen"],["Ester,","Esther,"],["e","and"],["disse:","said:"],["Se,","If,"],["ó","O"],["rei,","king,"],["achei","I-found"],["graça","grace"],["aos","to-the"],["teus","your"],["olhos,","eyes,"],["e","and"],["se","if"],["bem","good"],["parecer","seem"],["ao","to-the"],["rei,","king,"],["dê-se-me","gives-himself-me"],["a","the"],["minha","my"],["vida","life"],["como","as"],["minha","my"],["petição,","petition,"],["e","and"],["o","the"],["meu","my"],["povo","people"],["como","as"],["meu","my"],["desejo.","desire."]]},
  {num:4,words:[["Porque","Because"],["estamos","we-are"],["vendidos,","bondwomen,"],["eu","I"],["e","and"],["o","the"],["meu","my"],["povo,","people,"],["para","for"],["nos","us"],["destruírem,","to-destroy,"],["matarem,","to-slay,"],["e","and"],["exterminarem;","to-reverse;"],["se","if"],["ainda","yet"],["por","by"],["servos","servants"],["e","and"],["por","by"],["servas","servant"],["nos","us"],["vendessem,","they-sold,"],["calar-me-ia,","stilled-me,"],["ainda que","although"],["o","the"],["opressor","oppressor"],["não","not"],["compensaria","should-indemnify"],["a","the"],["perda","loss"],["do rei.","king's"]]},
  {num:5,words:[["Então","Then"],["falou","spoke"],["o","the"],["rei","king"],["Assuero,","Ahasuerus,"],["e","and"],["disse","said"],["à","to-the"],["rainha","queen"],["Ester:","Esther:"],["Quem","Who"],["é","is"],["esse?","that?"],["E","And"],["onde","where"],["está","is"],["esse,","that,"],["cujo","whose"],["coração","heart"],["o","him"],["instigou","encouraged"],["a","to"],["assim","thus"],["fazer?","make?"]]},
  {num:6,words:[["E","And"],["disse","said"],["Ester:","Esther:"],["O","The"],["homem,","man,"],["o","the"],["opressor,","oppressor,"],["e","and"],["o","the"],["inimigo,","enemy,"],["é","is"],["este","this"],["iníquo","wicked"],["Hamã.","Haman."],["Então","Then"],["Hamã","Haman"],["ficou","remained"],["aterrorizado","frightened"],["perante","before"],["o","the"],["rei e","king's"],["a","the"],["rainha.","queen."]]},
  {num:7,words:[["E","And"],["o","the"],["rei","king"],["no","in-the"],["seu","his"],["furor","fury"],["se","himself"],["levantou","arose"],["do","of-the"],["banquete","banquet"],["do","of-the"],["vinho","wine"],["e","and"],["foi","was"],["para","for"],["o","the"],["jardim","garden"],["do","of-the"],["palácio;","palace;"],["e","and"],["Hamã","Haman"],["se","himself"],["pôs","placed"],["em","in"],["pé,","foot,"],["para","to"],["rogar","arising"],["à","to-the"],["rainha","queen"],["Ester","Esther"],["pela","by-the"],["sua","his"],["vida,","life,"],["porque","because"],["viu","saw"],["que","that"],["já","already"],["o","the"],["mal","evil"],["lhe","to-him"],["era","was"],["determinado","determined"],["pelo","by-the"],["rei.","king."]]},
  {num:8,words:[["Tornando","Becoming"],["pois,","for,"],["o","the"],["rei","king"],["do","of-the"],["jardim","garden"],["do","of-the"],["palácio","palace"],["à","to-the"],["casa","house"],["do","of-the"],["banquete","banquet"],["do","of-the"],["vinho,","wine,"],["Hamã","Haman"],["tinha","had"],["caído","fallen"],["prostrado","nisroch"],["sobre","upon"],["o","the"],["leito","bed"],["em","in"],["que","that"],["estava","was"],["Ester.","Esther."],["Então","Then"],["disse","said"],["o","the"],["rei:","king:"],["Porventura","Perchance"],["quereria","would"],["ele","he"],["também","also"],["forçar","to-compel"],["a","the"],["rainha","queen"],["perante","before"],["mim","me"],["nesta","in-this"],["casa?","house?"],["Saindo","I-go-forth"],["esta","this"],["palavra","word"],["da","of-the"],["boca","mouth"],["do rei,","king's"],["cobriram","they-covered"],["o","the"],["rosto","face"],["de","of"],["Hamã.","Haman."]]},
  {num:9,words:[["Então","Then"],["disse","said"],["Harbona,","Mehuman,"],["um","a"],["dos","of-the"],["eunucos","eunuchs"],["que","that"],["serviam","they-served"],["diante","before"],["do rei:","king's"],["Eis","Behold"],["aqui","here"],["também","also"],["a","the"],["forca","gallows"],["de","of"],["cinquenta","fifty"],["côvados","cubits"],["de","of"],["altura","height"],["que","that"],["Hamã","Haman"],["fizera","had-made"],["para","for"],["Mardoqueu,","Mordecai,"],["que","that"],["falara","had-spoken"],["para","for"],["o","the"],["bem","good"],["do rei;","king's"],["está","is"],["junto","amassed"],["à","to-the"],["casa","house"],["de","of"],["Hamã.","Haman."],["Então","Then"],["disse","said"],["o","the"],["rei:","king:"],["Enforcai-o","Hang-him"],["nela.","in-it."]]},
  {num:10,words:[["Enforcaram,","Gallows,"],["pois,","for,"],["Hamã","Haman"],["na","in-the"],["forca","gallows"],["que","that"],["ele","he"],["tinha","had"],["preparado","prepared"],["para","for"],["Mardoqueu.","Mordecai."],["Então","Then"],["o","the"],["furor","fury"],["do rei","king's"],["se","himself"],["aplacou.","intreated."]]}
];
var v8 = [
  {num:1,words:[["Naquele","In-that"],["mesmo","same"],["dia","day"],["deu","gave"],["o","the"],["rei","king"],["Assuero","Ahasuerus"],["à","to-the"],["rainha","queen"],["Ester","Esther"],["a","the"],["casa","house"],["de","of"],["Hamã,","Haman,"],["inimigo","enemy"],["dos","of-the"],["judeus;","Jews;"],["e","and"],["Mardoqueu","Mordecai"],["foi","was"],["perante","before"],["o","the"],["rei,","king,"],["porque","because"],["Ester","Esther"],["tinha","had"],["declarado","declared"],["quem","who"],["ele","he"],["era.","was."]]},
  {num:2,words:[["E","And"],["tirou","took-away"],["o","the"],["rei","king"],["o","the"],["seu","his"],["anel,","ring,"],["que","that"],["tinha","had"],["tomado","taken"],["de","of"],["Hamã,","Haman,"],["e","and"],["o","it"],["deu","gave"],["a","to"],["Mardoqueu.","Mordecai."],["E","And"],["Ester","Esther"],["encarregou","to-encarregar"],["Mardoqueu","Mordecai"],["da","of-the"],["casa","house"],["de","of"],["Hamã.","Haman."]]},
  {num:3,words:[["Falou","Spoke"],["mais","more"],["Ester","Esther"],["perante","before"],["o","the"],["rei,","king,"],["e","and"],["lançou-se","fisher's"],["aos","to-the"],["seus","his"],["pés,","feet,"],["e","and"],["chorou,","wept,"],["e","and"],["lhe","to-him"],["suplicou","besought"],["que","that"],["revogasse","abjured"],["a","the"],["maldade","wickedness"],["de","of"],["Hamã,","Haman,"],["o","the"],["agagita,","agagite,"],["e","and"],["o","the"],["seu","his"],["intento","intent"],["que","that"],["tinha","had"],["intentado","intended"],["contra","against"],["os","the"],["judeus.","Jews."]]},
  {num:4,words:[["E","And"],["estendeu","stretched"],["o","the"],["rei","king"],["para","for"],["Ester","Esther"],["o","the"],["cetro","sceptre"],["de","of"],["ouro.","gold."],["Então","Then"],["Ester","Esther"],["se","himself"],["levantou,","arose,"],["e","and"],["se","if"],["pôs","placed"],["em","in"],["pé","foot"],["perante","before"],["o","the"],["rei,","king,"]]},
  {num:5,words:[["E","And"],["disse:","said:"],["Se","If"],["bem","good"],["parecer","seem"],["ao","to-the"],["rei,","king,"],["e","and"],["se","if"],["eu","I"],["achei","I-found"],["graça","grace"],["perante","before"],["ele,","he,"],["e","and"],["se","if"],["isso","that"],["parecer","seem"],["justo","fair"],["diante","before"],["do rei,","king's"],["e","and"],["se","if"],["eu","I"],["lhe","to-him"],["agrado","I-please"],["aos","to-the"],["seus","his"],["olhos,","eyes,"],["escreva-se","writes-himself"],["que","that"],["se","themselves"],["revoguem","they-abjure"],["as","the"],["cartas","letters"],["e","and"],["o","the"],["intento","intent"],["de","of"],["Hamã,","Haman,"],["filho","son"],["de","of"],["Hamedata,","Hammedatha,"],["o","the"],["agagita,","agagite,"],["as","the"],["quais","what"],["ele","he"],["escreveu","wrote"],["para","to"],["exterminar","to-reverse"],["os","the"],["judeus","Jews"],["que","that"],["há","there-is"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["do rei.","king's"]]},
  {num:6,words:[["Porque","Because"],["como","as"],["poderei","I-can"],["ver","see"],["o","the"],["mal","evil"],["que","that"],["sobrevirá","will-ensue"],["ao","to-the"],["meu","my"],["povo?","people?"],["E","And"],["como","as"],["poderei","I-can"],["ver","see"],["a","the"],["destruição","destruction"],["da","of-the"],["minha","my"],["parentela?","kindred?"]]},
  {num:7,words:[["Então","Then"],["disse","said"],["o","the"],["rei","king"],["Assuero","Ahasuerus"],["à","to-the"],["rainha","queen"],["Ester","Esther"],["e","and"],["ao","to-the"],["judeu","Jew"],["Mardoqueu:","Mordecai:"],["Eis que","behold"],["dei","I-gave"],["a","the"],["Ester","Esther"],["a","the"],["casa","house"],["de","of"],["Hamã,","Haman,"],["e","and"],["a","the"],["ele","he"],["enforcaram","gallows"],["numa","in-a"],["forca,","gallows,"],["porquanto","because"],["quisera","I-would"],["pôr","to-place"],["as","the"],["mãos","hands"],["nos","in-the"],["judeus.","Jews."]]},
  {num:8,words:[["Escrevei,","Write,"],["pois,","for,"],["aos","to-the"],["judeus,","Jews,"],["como","as"],["parecer","seem"],["bem","good"],["aos","to-the"],["vossos","your"],["olhos,","eyes,"],["em","in"],["nome","name"],["do rei,","king's"],["e","and"],["selai-o","prepay-it"],["com","with"],["o","the"],["anel","ring"],["do rei,","king's"],["porque","because"],["a","the"],["escrita","writing"],["que","that"],["se","itself"],["escreve","writes"],["em","in"],["nome","name"],["do rei,","king's"],["e","and"],["se","if"],["sela","prepays"],["com","with"],["o","the"],["anel","ring"],["do rei,","king's"],["não","not"],["é","is"],["para","to"],["revogar.","to-abjure."]]},
  {num:9,words:[["Então","Then"],["foram","they-were"],["chamados","called"],["os","the"],["escrivães","scribe"],["do rei,","king's"],["naquele","in-that"],["mesmo","same"],["tempo,","time,"],["e","and"],["no","in-the"],["mês","month"],["terceiro","third"],["(que","(that"],["é","is"],["o","the"],["mês","month"],["de","of"],["Sivã),","Sivã),"],["aos","to-the"],["vinte","twenty"],["e","and"],["três","three"],["do","of-the"],["mesmo,","even,"],["e","and"],["se","if"],["escreveu","wrote"],["conforme","according-to"],["tudo","all"],["quanto","as"],["ordenou","commanded"],["Mardoqueu","Mordecai"],["aos","to-the"],["judeus,","Jews,"],["como","as"],["também","also"],["aos","to-the"],["sátrapas,","lieutenants,"],["e","and"],["aos","to-the"],["governadores,","governors,"],["e","and"],["aos","to-the"],["chefes","authority"],["das","of-the"],["províncias,","provinces,"],["que","that"],["se","themselves"],["estendem","they-stretch"],["da","of-the"],["Índia","India"],["até","until"],["a","the"],["Etiópia,","Ethiopia,"],["cento","hundred"],["e","and"],["vinte","twenty"],["e","and"],["sete","seven"],["províncias,","provinces,"],["a","to"],["cada","every"],["província","province"],["segundo","according-to"],["a","the"],["sua","their"],["escrita,","writing,"],["e","and"],["a","to"],["cada","every"],["povo","people"],["conforme a","according-to"],["sua","their"],["língua,","tongue,"],["como","as"],["também","also"],["aos","to-the"],["judeus","Jews"],["segundo","according-to"],["a","the"],["sua","their"],["escrita,","writing,"],["e","and"],["conforme a","according-to"],["sua","their"],["língua.","tongue."]]},
  {num:10,words:[["E","And"],["se","if"],["escreveu","wrote"],["em","in"],["nome","name"],["do rei","king's"],["Assuero,","Ahasuerus,"],["e","and"],["se","if"],["selou","prepaid"],["com","with"],["o","the"],["anel","ring"],["do rei,","king's"],["e","and"],["se","if"],["enviaram","they-sent"],["as","the"],["cartas","letters"],["pela","by-the"],["mão","hand"],["de","of"],["correios","mail"],["a","to"],["cavalo,","horse,"],["e","and"],["que","that"],["cavalgavam","they-rode"],["sobre","upon"],["ginetes,","dromedaries,"],["e","and"],["sobre","upon"],["mulas","mules"],["e","and"],["filhos","children"],["de","of"],["éguas.","ahasuerus'."]]},
  {num:11,words:[["Nelas","In-him"],["o","the"],["rei","king"],["concedia","bestowed"],["aos","to-the"],["judeus","Jews"],["que","that"],["havia","there-was"],["em","in"],["cada","every"],["cidade,","city,"],["que","that"],["se","themselves"],["ajuntassem,","they-added,"],["e","and"],["se","if"],["dispusessem","they-arranged"],["para","to"],["defender","to-defend"],["as","the"],["suas","their"],["vidas,","life,"],["para","to"],["destruir,","destroy,"],["matar","slay"],["e","and"],["assolar","assault"],["todas","all"],["as","the"],["forças","you-compel"],["do","of-the"],["povo","people"],["e","and"],["província","province"],["que","that"],["os","them"],["atacassem,","they-attacked,"],["crianças","children"],["e","and"],["mulheres,","women,"],["e","and"],["que","that"],["se","themselves"],["saqueassem","assault"],["os","the"],["seus","their"],["despojos,","spoil,"]]},
  {num:12,words:[["Num","In-a"],["mesmo","same"],["dia,","day,"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["do rei","king's"],["Assuero,","Ahasuerus,"],["no","in-the"],["dia","day"],["treze","thirteen"],["do","of-the"],["duodécimo","twelfth"],["mês,","month,"],["que","that"],["é","is"],["o","the"],["mês","month"],["de","of"],["Adar.","Adar."]]},
  {num:13,words:[["E","And"],["a","the"],["cópia","copy"],["da","of-the"],["carta","letter"],["foi","was"],["que","that"],["uma","a"],["ordem","order"],["se","himself"],["anunciaria","should-advertise"],["em","in"],["todas","all"],["as","the"],["províncias,","provinces,"],["publicamente","openly"],["a","to"],["todos","all"],["os","the"],["povos,","nations,"],["para que","that"],["os","the"],["judeus","Jews"],["estivessem","they-were"],["preparados","prepared"],["para","for"],["aquele","that"],["dia,","day,"],["para","for"],["se","themselves"],["vingarem","to-avenge"],["dos","of-the"],["seus","their"],["inimigos.","enemies."]]},
  {num:14,words:[["Os","The"],["correios","mail"],["sobre","upon"],["ginetes","dromedaries"],["e","and"],["mulas","mules"],["apressuradamente","tatnai"],["saíram,","they-went-forth,"],["impelidos","hastened"],["pela","by-the"],["palavra","word"],["do rei;","king's"],["e","and"],["foi","was"],["publicada","issued"],["esta","this"],["ordem","order"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã.","Shushan."]]},
  {num:15,words:[["Então","Then"],["Mardoqueu","Mordecai"],["saiu","went-forth"],["da","of-the"],["presença","presence"],["do rei","king's"],["com","with"],["uma","a"],["veste","garment"],["real","royal"],["azul","blue"],["celeste","celestial"],["e","and"],["branco,","white,"],["como","as"],["também","also"],["com","with"],["uma","a"],["grande","great"],["coroa","crown"],["de","of"],["ouro,","gold,"],["e","and"],["com","with"],["uma","a"],["capa","cover"],["de","of"],["linho","linen"],["fino","dainty"],["e","and"],["púrpura,","purple,"],["e","and"],["a","the"],["cidade","city"],["de","of"],["Susã","Shushan"],["jubilou","shouted"],["e","and"],["se","if"],["alegrou.","gladdened."]]},
  {num:16,words:[["E","And"],["para","for"],["os","the"],["judeus","Jews"],["houve","there-was"],["luz,","light,"],["e","and"],["alegria,","joy,"],["e","and"],["regozijo,","rejoicing,"],["e","and"],["honra.","honour."]]},
  {num:17,words:[["Também","Also"],["em","in"],["toda","all"],["a","the"],["província,","province,"],["e","and"],["em","in"],["toda","all"],["a","the"],["cidade,","city,"],["aonde","whither"],["chegava","came"],["a","the"],["palavra","word"],["do rei,","king's"],["e","and"],["a","the"],["sua","his"],["ordem,","order,"],["havia","there-was"],["entre","among"],["os","the"],["judeus","Jews"],["alegria,","joy,"],["e","and"],["regozijo,","rejoicing,"],["banquetes","feasting"],["e","and"],["dias","days"],["de","of"],["festa;","feast;"],["e","and"],["muitos","many"],["dos","of-the"],["povos","nations"],["da","of-the"],["terra","land"],["se","themselves"],["fizeram","they-made"],["judeus,","Jews,"],["porque","because"],["o","the"],["temor","fear"],["dos","of-the"],["judeus","Jews"],["tinha","had"],["caído","fallen"],["sobre","upon"],["eles.","them."]]}
];
var v9 = [
  {num:1,words:[["E","And"],["no","in-the"],["mês","month"],["duodécimo,","twelfth,"],["que","that"],["é","is"],["o","the"],["mês","month"],["de","of"],["Adar,","Adar,"],["no","in-the"],["dia","day"],["treze","thirteen"],["do","of-the"],["mesmo","same"],["mês","month"],["em","in"],["que","that"],["chegou","came"],["a","the"],["palavra","word"],["do rei e","king's"],["a","the"],["sua","his"],["ordem","order"],["para","for"],["a","to"],["executar,","to-execute,"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["os","the"],["inimigos","enemies"],["dos","of-the"],["judeus","Jews"],["esperavam","they-abode"],["assenhorear-se","to-assenhorear-himself"],["deles,","of-them,"],["sucedeu","happened"],["o","the"],["contrário,","contrary,"],["porque","because"],["os","the"],["judeus","Jews"],["foram","they-were"],["os","the"],["que","that"],["se","themselves"],["assenhorearam","execution"],["dos","of-the"],["que","that"],["os","them"],["odiavam.","they-hated."]]},
  {num:2,words:[["Porque","Because"],["os","the"],["judeus","Jews"],["nas","in-the"],["suas","their"],["cidades,","cities,"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["do rei","king's"],["Assuero,","Ahasuerus,"],["se","if"],["ajuntaram","they-added"],["para","to"],["pôr","to-place"],["as","the"],["mãos","hands"],["naqueles","in-that"],["que","that"],["procuravam","they-sought"],["o","the"],["seu","their"],["mal;","evil;"],["e","and"],["ninguém","none"],["podia","could"],["resistir-lhes,","resist-to-them,"],["porque","because"],["o","the"],["seu","their"],["terror","terror"],["caiu","fell"],["sobre","upon"],["todos","all"],["aqueles","those"],["povos.","nations."]]},
  {num:3,words:[["E","And"],["todos","all"],["os","the"],["chefes","authority"],["das","of-the"],["províncias,","provinces,"],["e","and"],["os","the"],["sátrapas,","lieutenants,"],["e","and"],["os","the"],["governadores,","governors,"],["e","and"],["os","the"],["que","that"],["faziam","they-made"],["a","the"],["obra","work"],["do rei","king's"],["exaltavam","they-abased"],["os","the"],["judeus,","Jews,"],["porque","because"],["tinha","had"],["caído","fallen"],["sobre","upon"],["eles","them"],["o","the"],["temor","fear"],["de","of"],["Mardoqueu.","Mordecai."]]},
  {num:4,words:[["Porque","Because"],["Mardoqueu","Mordecai"],["era","was"],["grande","great"],["na","in-the"],["casa","house"],["do rei,","king's"],["e","and"],["a","the"],["sua","his"],["fama","fame"],["saía","went-forth"],["por","by"],["todas","all"],["as","the"],["províncias,","provinces,"],["porque","because"],["o","the"],["homem","man"],["Mardoqueu","Mordecai"],["se","himself"],["ia","went"],["engrandecendo.","waxed."]]},
  {num:5,words:[["Derrotaram,","To-derrotar,"],["pois,","for,"],["os","the"],["judeus","Jews"],["todos","all"],["os","of"],["seus","their"],["inimigos","enemies"],["a","the"],["cutiladas","stroke"],["de","of"],["espada,","sword,"],["e","and"],["de","of"],["matança,","slaughter,"],["e","and"],["de","of"],["destruição,","destruction,"],["e","and"],["fizeram","they-made"],["dos","of-the"],["que","that"],["os","them"],["odiavam","they-hated"],["o","the"],["que","that"],["quiseram.","they-willed."]]},
  {num:6,words:[["E","And"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã","Shushan"],["os","the"],["judeus","Jews"],["mataram","they-slew"],["e","and"],["destruíram","they-destroyed"],["quinhentos","five-hundred"],["homens,","men,"]]},
  {num:7,words:[["Como","As"],["também","also"],["Parsandata,","Parshandatha,"],["e","and"],["Dalfom,","Parshandatha,"],["e","and"],["Aspata,","Parshandatha,"]]},
  {num:8,words:[["E","And"],["Porata,","Poratha,"],["e","and"],["Adalia,","Adalia,"],["e","and"],["Aridata,","Poratha,"]]},
  {num:9,words:[["E","And"],["Farmasta,","Parmashta,"],["e","and"],["Arisai,","Arisai,"],["e","and"],["Aridai,","Aridai,"],["e","and"],["Vaisata;","Parmashta;"]]},
  {num:10,words:[["Os","The"],["dez","ten"],["filhos","children"],["de","of"],["Hamã,","Haman,"],["filho","son"],["de","of"],["Hamedata,","Hammedatha,"],["o","the"],["inimigo","enemy"],["dos","of-the"],["judeus,","Jews,"],["mataram,","they-slew,"],["porém","but"],["ao","to-the"],["despojo","I-spoil"],["não","not"],["estenderam","they-stretched"],["a","the"],["sua","their"],["mão.","hand."]]},
  {num:11,words:[["No","In-the"],["mesmo","same"],["dia","day"],["foi","was"],["comunicado","advised"],["ao","to-the"],["rei","king"],["o","the"],["número","number"],["dos","of-the"],["mortos","dead"],["na","in-the"],["fortaleza","fortification"],["de","of"],["Susã.","Shushan."]]},
  {num:12,words:[["E","And"],["disse","said"],["o","the"],["rei","king"],["à","to-the"],["rainha","queen"],["Ester:","Esther:"],["Na","In-the"],["fortaleza","fortification"],["de","of"],["Susã","Shushan"],["os","the"],["judeus","Jews"],["mataram","they-slew"],["e","and"],["destruíram","they-destroyed"],["quinhentos","five-hundred"],["homens,","men,"],["e","and"],["os","the"],["dez","ten"],["filhos","children"],["de","of"],["Hamã;","Haman;"],["nas","in-the"],["demais","moreover"],["províncias","provinces"],["do rei","king's"],["o","the"],["que","that"],["terão","they-will-have"],["feito?","made?"],["Qual","Which"],["é,","is,"],["pois,","for,"],["a","the"],["tua","your"],["petição,","petition,"],["e","and"],["dar-se-te-á.","petition."],["Ou","Or"],["qual","which"],["é","is"],["ainda","yet"],["o","the"],["teu","your"],["desejo?","desire?"],["E","And"],["far-se-á.","will-make-himself."]]},
  {num:13,words:[["Então","Then"],["disse","said"],["Ester:","Esther:"],["Se","If"],["bem","good"],["parecer","seem"],["ao","to-the"],["rei,","king,"],["conceda-se","bestows-himself"],["também","also"],["amanhã","tomorrow"],["aos","to-the"],["judeus","Jews"],["que","that"],["se","themselves"],["acham","they-find"],["em","in"],["Susã","Shushan"],["que","that"],["façam","they-make"],["conforme","according-to"],["o","the"],["mandado","commandment"],["de","of"],["hoje,","today,"],["e","and"],["enforquem","hang"],["os","the"],["dez","ten"],["filhos","children"],["de","of"],["Hamã","Haman"],["numa","in-a"],["forca.","gallows."]]},
  {num:14,words:[["Então","Then"],["disse","said"],["o","the"],["rei","king"],["que","that"],["assim","thus"],["se","himself"],["fizesse;","made;"],["e","and"],["deu-se","peres"],["um","a"],["édito","haman's"],["em","in"],["Susã,","Shushan,"],["e","and"],["enforcaram","gallows"],["os","the"],["dez","ten"],["filhos","children"],["de","of"],["Hamã.","Haman."]]},
  {num:15,words:[["E","And"],["ajuntaram-se","they-added-themselves"],["os","the"],["judeus","Jews"],["que","that"],["se","themselves"],["achavam","they-found"],["em","in"],["Susã","Shushan"],["também","also"],["no","in-the"],["dia","day"],["quatorze","fourteen"],["do","of-the"],["mês","month"],["de","of"],["Adar,","Adar,"],["e","and"],["mataram","they-slew"],["em","in"],["Susã","Shushan"],["trezentos","three-hundred"],["homens;","men;"],["porém","but"],["ao","to-the"],["despojo","I-spoil"],["não","not"],["estenderam","they-stretched"],["a","the"],["sua","their"],["mão.","hand."]]},
  {num:16,words:[["Também","Also"],["os","the"],["demais","moreover"],["judeus","Jews"],["que","that"],["se","themselves"],["achavam","they-found"],["nas","in-the"],["províncias","provinces"],["do rei","king's"],["se","themselves"],["ajuntaram,","they-added,"],["para","for"],["se","themselves"],["porem","to-place"],["em","in"],["defesa","protection"],["da","of-the"],["sua","their"],["vida,","life,"],["e","and"],["tiveram","they-had"],["repouso","rest"],["dos","of-the"],["seus","their"],["inimigos;","enemies;"],["e","and"],["mataram","they-slew"],["dos","of-the"],["que","that"],["os","them"],["odiavam","they-hated"],["setenta","seventy"],["e","and"],["cinco","five"],["mil;","thousand;"],["porém","but"],["ao","to-the"],["despojo","I-spoil"],["não","not"],["estenderam","they-stretched"],["a","the"],["sua","their"],["mão.","hand."]]},
  {num:17,words:[["Sucedeu","Happened"],["isso","that"],["no","in-the"],["dia","day"],["treze","thirteen"],["do","of-the"],["mês","month"],["de","of"],["Adar;","Adar;"],["e","and"],["repousaram","they-reposed"],["no","in-the"],["dia","day"],["quatorze","fourteen"],["do","of-the"],["mesmo,","even,"],["e","and"],["fizeram","they-made"],["daquele","of-that"],["dia,","day,"],["dia","day"],["de","of"],["banquetes","feasting"],["e","and"],["de","of"],["alegria.","joy."]]},
  {num:18,words:[["Também","Also"],["os","the"],["judeus,","Jews,"],["que","that"],["se","themselves"],["achavam","they-found"],["em","in"],["Susã,","Shushan,"],["se","if"],["ajuntaram","they-added"],["nos","in-the"],["dias","days"],["treze","thirteen"],["e","and"],["quatorze","fourteen"],["do","of-the"],["mesmo;","even;"],["e","and"],["repousaram","they-reposed"],["no","in-the"],["dia","day"],["quinze","fifteen"],["do","of-the"],["mesmo,","even,"],["e","and"],["fizeram","they-made"],["daquele","of-that"],["dia,","day,"],["dia","day"],["de","of"],["banquetes","feasting"],["e","and"],["de","of"],["alegria.","joy."]]},
  {num:19,words:[["Porém","But"],["os","the"],["judeus","Jews"],["das","of-the"],["aldeias,","villages,"],["que","that"],["habitavam","they-dwelt"],["nas","in-the"],["vilas,","towns,"],["fizeram","they-made"],["do","of-the"],["dia","day"],["quatorze","fourteen"],["do","of-the"],["mês","month"],["de","of"],["Adar","Adar"],["dia","day"],["de","of"],["alegria","joy"],["e","and"],["de","of"],["banquetes,","feasting,"],["e","and"],["dia","day"],["de","of"],["festa,","feast,"],["e","and"],["de","of"],["mandarem","to-command"],["presentes","presents"],["uns","some"],["aos","to-the"],["outros.","others."]]},
  {num:20,words:[["E","And"],["Mardoqueu","Mordecai"],["escreveu","wrote"],["essas","those"],["coisas,","things,"],["e","and"],["enviou","sent"],["cartas","letters"],["a","to"],["todos","all"],["os","the"],["judeus","Jews"],["que","that"],["se","themselves"],["achavam","they-found"],["em","in"],["todas","all"],["as","the"],["províncias","provinces"],["do rei","king's"],["Assuero,","Ahasuerus,"],["aos","to-the"],["de perto,","near-by"],["e","and"],["aos","to-the"],["de longe,","from-afar"]]},
  {num:21,words:[["Ordenando-lhes","Ordaining-to-them"],["que","that"],["guardassem","they-kept"],["o","the"],["dia","day"],["quatorze","fourteen"],["do","of-the"],["mês","month"],["de","of"],["Adar,","Adar,"],["e","and"],["o","the"],["dia","day"],["quinze","fifteen"],["do","of-the"],["mesmo,","even,"],["todos","all"],["os","the"],["anos,","years,"]]},
  {num:22,words:[["Conforme","According-to"],["os","the"],["dias","days"],["em","in"],["que","that"],["os","the"],["judeus","Jews"],["tiveram","they-had"],["repouso","rest"],["dos","of-the"],["seus","their"],["inimigos,","enemies,"],["e","and"],["o","the"],["mês","month"],["que","that"],["se","itself"],["lhes","to-them"],["mudou","varied"],["de","of"],["tristeza","sorrow"],["em","in"],["alegria,","joy,"],["e","and"],["de","of"],["luto,","mourning,"],["em","in"],["dia","day"],["de","of"],["festa,","feast,"],["para que","that"],["os","them"],["fizessem","they-made"],["dias","days"],["de","of"],["banquetes","feasting"],["e","and"],["de","of"],["alegria,","joy,"],["e","and"],["de","of"],["mandarem","to-command"],["presentes","presents"],["uns","some"],["aos","to-the"],["outros,","others,"],["e","and"],["aos","to-the"],["pobres,","poor,"],["dádivas.","gifts."]]},
  {num:23,words:[["E","And"],["se","if"],["encarregaram","undertook"],["os","the"],["judeus","Jews"],["de","of"],["fazer","make"],["o","the"],["que","that"],["já","already"],["tinham","they-had"],["começado,","begun,"],["como","as"],["também","also"],["o","the"],["que","that"],["Mardoqueu","Mordecai"],["lhes","to-them"],["tinha","had"],["escrito.","written."]]},
  {num:24,words:[["Porque","Because"],["Hamã,","Haman,"],["filho","son"],["de","of"],["Hamedata,","Hammedatha,"],["o","the"],["agagita,","agagite,"],["inimigo","enemy"],["de","of"],["todos","all"],["os","the"],["judeus,","Jews,"],["tinha","had"],["intentado","intended"],["destruir","destroy"],["os","the"],["judeus,","Jews,"],["e","and"],["tinha","had"],["lançado","cast"],["Pur,","Pur,"],["isto é,","that-is"],["a","the"],["sorte,","lot,"],["para","for"],["os","the"],["assolar","assault"],["e","and"],["destruir.","destroy."]]},
  {num:25,words:[["Mas,","But,"],["vindo","coming"],["isto","this"],["perante","before"],["o","the"],["rei,","king,"],["ordenou","commanded"],["ele","he"],["por","by"],["cartas","letters"],["que","that"],["o","the"],["seu","his"],["mau","bad"],["intento,","intent,"],["que","that"],["intentara","had-intended"],["contra","against"],["os","the"],["judeus,","Jews,"],["se","if"],["tornasse","became"],["sobre","upon"],["a","the"],["sua","his"],["cabeça;","head;"],["pelo","by-the"],["que","that"],["o","the"],["enforcaram,","gallows,"],["ele","he"],["e","and"],["seus","his"],["filhos,","children,"],["numa","in-a"],["forca.","gallows."]]},
  {num:26,words:[["Por isso","therefore"],["àqueles","to-that"],["dias","days"],["chamam","they-call"],["Purim,","Purim,"],["do","of-the"],["nome","name"],["Pur;","Pur;"],["pelo","by-the"],["que","that"],["também","also"],["por causa de","because-of"],["todas","all"],["as","the"],["palavras","words"],["daquela","of-that"],["carta,","letter,"],["e","and"],["do que","than"],["viram","they-saw"],["sobre","upon"],["isso,","that,"],["e","and"],["do que","than"],["lhes","to-them"],["tinha","had"],["sucedido,","happened,"]]},
  {num:27,words:[["Confirmaram","They-confirmed"],["os","the"],["judeus,","Jews,"],["e","and"],["tomaram","they-took"],["sobre","upon"],["si,","himself,"],["e","and"],["sobre","upon"],["a","the"],["sua","their"],["semente,","seed,"],["e","and"],["sobre","upon"],["todos","all"],["os","the"],["que","that"],["se","themselves"],["achegassem","they-drew-near"],["a","to"],["eles,","they,"],["que","that"],["não","not"],["se","himself"],["deixaria","should-leave"],["de","of"],["guardar","to-keep"],["estes","these"],["dois","two"],["dias","days"],["conforme","according-to"],["o","the"],["que","that"],["se","itself"],["escrevera","had-written"],["deles,","of-them,"],["e","and"],["segundo","according-to"],["o","the"],["seu","their"],["tempo","time"],["determinado,","determined,"],["todos","all"],["os","the"],["anos.","years."]]},
  {num:28,words:[["E","And"],["que","that"],["estes","these"],["dias","days"],["seriam","they-should-be"],["lembrados","remembered"],["e","and"],["guardados","purim"],["em","in"],["cada","every"],["geração,","generation,"],["família,","family,"],["província,","province,"],["e","and"],["cidade,","city,"],["e","and"],["que","that"],["estes","these"],["dias","days"],["de","of"],["Purim","Purim"],["não","not"],["seriam","they-should-be"],["revogados","abjured"],["dentre","from"],["os","the"],["judeus,","Jews,"],["e","and"],["que","that"],["a","the"],["memória","memory"],["deles","of-them"],["nunca","never"],["teria","should-have"],["fim","end"],["entre","among"],["os","the"],["de","of"],["sua","their"],["semente.","seed."]]},
  {num:29,words:[["Depois","Afterwards"],["disso","of-that"],["escreveu","wrote"],["a","the"],["rainha","queen"],["Ester,","Esther,"],["filha","daughter"],["de","of"],["Abiail,","Abihail,"],["e","and"],["Mardoqueu,","Mordecai,"],["o","the"],["judeu,","Jew,"],["com","with"],["toda","all"],["a","the"],["autoridade,","authority,"],["para","to"],["confirmarem","to-confirm"],["uma","a"],["segunda","second"],["vez","time"],["esta","this"],["carta","letter"],["de","of"],["Purim.","Purim."]]},
  {num:30,words:[["E","And"],["mandaram","they-commanded"],["cartas","letters"],["a","to"],["todos","all"],["os","the"],["judeus,","Jews,"],["às","to-the"],["cento","hundred"],["e","and"],["vinte","twenty"],["e","and"],["sete","seven"],["províncias","provinces"],["do","of-the"],["reino","kingdom"],["de","of"],["Assuero,","Ahasuerus,"],["com","with"],["palavras","words"],["de","of"],["paz","peace"],["e","and"],["fidelidade,","faithfulness,"]]},
  {num:31,words:[["Para","To"],["confirmarem","to-confirm"],["estes","these"],["dias","days"],["de","of"],["Purim","Purim"],["nos","in-the"],["seus","their"],["tempos","times"],["determinados,","determined,"],["como","as"],["Mardoqueu,","Mordecai,"],["o","the"],["judeu,","Jew,"],["e","and"],["a","the"],["rainha","queen"],["Ester","Esther"],["lhes","to-them"],["tinham","they-had"],["estabelecido,","established,"],["e","and"],["como","as"],["eles","they"],["mesmos","themselves"],["já","already"],["o","him"],["tinham","they-had"],["estabelecido","established"],["sobre","upon"],["si","himself"],["e","and"],["sobre","upon"],["a","the"],["sua","their"],["semente,","seed,"],["acerca","concerning"],["do","of-the"],["jejum","fasting"],["e","and"],["do","of-the"],["seu","their"],["clamor.","cry."]]},
  {num:32,words:[["E","And"],["o","the"],["mandado","commandment"],["de","of"],["Ester","Esther"],["confirmou","confirmed"],["os","the"],["fatos","facts"],["daquele","of-that"],["Purim;","Purim;"],["e","and"],["escreveu-se","wrote-himself"],["num","in-a"],["livro.","book."]]}
];
var v10 = [
  {num:1,words:[["Depois","Afterwards"],["disso","of-that"],["pôs","placed"],["o","the"],["rei","king"],["Assuero","Ahasuerus"],["tributo","tribute"],["sobre","upon"],["a","the"],["terra,","land,"],["e","and"],["sobre","upon"],["as","the"],["ilhas","isles"],["do","of-the"],["mar.","sea."]]},
  {num:2,words:[["E","And"],["todas","all"],["as","the"],["obras","works"],["do","of-the"],["seu","his"],["poder","power"],["e","and"],["do","of-the"],["seu","his"],["valor,","worth,"],["e","and"],["a","the"],["declaração","proclamation"],["da","of-the"],["grandeza","greatness"],["de","of"],["Mardoqueu,","Mordecai,"],["a","to"],["quem","who"],["o","the"],["rei","king"],["engrandeceu,","magnified,"],["porventura","perchance"],["não","not"],["estão","they-are"],["escritas","written"],["no","in-the"],["livro","book"],["das","of-the"],["crônicas","chronicles"],["dos","of-the"],["reis","kings"],["da","of-the"],["Média","Media"],["e","and"],["da","of-the"],["Pérsia?","Persia?"]]},
  {num:3,words:[["Porque","Because"],["o","the"],["judeu","Jew"],["Mardoqueu","Mordecai"],["foi","was"],["o segundo","second"],["depois","afterwards"],["do rei","king's"],["Assuero,","Ahasuerus,"],["e","and"],["grande","great"],["para","for"],["com","with"],["os","the"],["judeus,","Jews,"],["e","and"],["agradável","agreeable"],["para","for"],["com","with"],["a","the"],["multidão","multitude"],["de","of"],["seus","his"],["irmãos,","brethren,"],["que","that"],["procurava","sought"],["o","the"],["bem","good"],["do","of-the"],["seu","his"],["povo,","people,"],["e","and"],["falava","spoke"],["pela","by-the"],["prosperidade","prosperity"],["de","of"],["toda","all"],["a","of"],["sua","his"],["nação.","nation."]]}
];
renderVerseSet(v1, 'est-ch1-verses');
renderVerseSet(v2, 'est-ch2-verses');
renderVerseSet(v3, 'est-ch3-verses');
renderVerseSet(v4, 'est-ch4-verses');
renderVerseSet(v5, 'est-ch5-verses');
renderVerseSet(v6, 'est-ch6-verses');
renderVerseSet(v7, 'est-ch7-verses');
renderVerseSet(v8, 'est-ch8-verses');
renderVerseSet(v9, 'est-ch9-verses');
renderVerseSet(v10, 'est-ch10-verses');
})();
