(function() {
var v1 = [
  {num:1,words:[["O","The"],["peso","weight"],["que","that"],["viu","saw"],["o","the"],["profeta","prophet"],["Habacuque.","Habakkuk."]]},
  {num:2,words:[["Até","Until"],["quando,","when,"],["Senhor,","Lord,"],["clamarei","I-will-cry"],["eu,","I,"],["e","and"],["tu","you"],["não","no"],["me","me"],["escutarás?","you-will-listen?"],["Até","Until"],["quando","when"],["gritarei","I-will-scream"],["a","to"],["ti:","you:"],["Violência!","Violence!"],["e","and"],["não","no"],["salvarás?","you-will-save?"]]},
  {num:3,words:[["Por","By"],["que","that"],["razão","account"],["me","me"],["fazes","you-make"],["ver","see"],["a","to"],["iniquidade,","iniquity,"],["e","and"],["contemplas","you-contemplate"],["a","to"],["opressão?","oppression?"],["Porque","Because"],["a","to"],["destruição","destruction"],["e","and"],["a","to"],["violência","violence"],["estão","they-are"],["diante de","before"],["mim,","me,"],["havendo","having"],["também","also"],["quem","who"],["suscite","moabitess"],["a","to"],["contenda","strife"],["e","and"],["o","the"],["litígio.","grievance."]]},
  {num:4,words:[["Por","By"],["essa","that ... over there"],["causa","sake"],["a","to"],["lei","law"],["se","if"],["afrouxa,","slacked,"],["e","and"],["a","to"],["sentença","sentence"],["nunca","never"],["sai;","exits;"],["porque","because"],["o","the"],["ímpio","wicked"],["cerca","about"],["o","the"],["justo,","fair,"],["e","and"],["sai","exits"],["a","to"],["sentença","sentence"],["distorcida.","slacked."]]},
  {num:5,words:[["Vede","See"],["entre","between"],["as","the"],["nações,","nations,"],["e","and"],["olhai,","glance,"],["e","and"],["maravilhai-vos,","marvellously,"],["e","and"],["ficai","remain"],["maravilhados;","marveling;"],["porque","because"],["realizo","I-accomplish"],["uma","a"],["obra","work"],["em","in"],["vossos","your"],["dias","days"],["que","that"],["não","no"],["crereis,","you-will-believe,"],["quando","when"],["se","if"],["vos","you"],["contar.","narrate."]]},
  {num:6,words:[["Porque","Because"],["eis que","behold"],["suscito","I-moabitess"],["os","the"],["caldeus,","chaldeans,"],["nação","nation"],["amarga","bitter"],["e","and"],["impetuosa,","lawless,"],["que","that"],["marcha","march"],["sobre","upon"],["a","to"],["largura","breadth"],["da","of-the"],["terra,","land,"],["para","for"],["possuir","possess"],["moradas","dwellings"],["que","that"],["não","no"],["são","they-are"],["suas.","his."]]},
  {num:7,words:[["Horrível","Horrible"],["e","and"],["terrível","abysmal"],["é;","is;"],["dela","of-it"],["mesma","same"],["sairá","will-exit"],["o","the"],["seu","his"],["juízo","judgment"],["e","and"],["a","to"],["sua","his"],["grandeza.","greatness."]]},
  {num:8,words:[["E","And"],["os","the"],["seus","his"],["cavalos","horses"],["são","they-are"],["mais","still"],["ligeiros","swifter"],["do","of-the"],["que","that"],["os","the"],["leopardos,","leopard,"],["e","and"],["mais","still"],["perspicazes","leopards"],["do","of-the"],["que","that"],["os","the"],["lobos","wolves"],["à","to-the"],["tarde,","evening,"],["e","and"],["os","the"],["seus","his"],["cavaleiros","horsemen"],["se","if"],["espalham;","they-disseminate;"],["os","the"],["seus","his"],["cavaleiros","horsemen"],["virão","they-will-come"],["de longe;","from-afar"],["voarão","leopards"],["como","as"],["águias","eagles"],["que","that"],["se","if"],["apressam","they-accelerate"],["à","to-the"],["comida.","meat."]]},
  {num:9,words:[["Eles","They"],["todos","all"],["virão","they-will-come"],["a fim de","in-order-to"],["fazer","make"],["violência;","violence;"],["o","the"],["rosto","face"],["deles","of-them"],["buscará","will-seek"],["o","the"],["oriente,","east,"],["e","and"],["congregarão","nebaioth"],["os","the"],["cativos","captives"],["como","as"],["areia.","sand."]]},
  {num:10,words:[["E","And"],["escarnecerão","they-will-mock"],["dos","of-the"],["reis,","kings,"],["e","and"],["dos","of-the"],["príncipes","princes"],["farão","they-will-make"],["zombaria;","scorning;"],["eles","they"],["se","if"],["rirão","they-will-laugh"],["de","of"],["todas","things"],["as","the"],["fortalezas,","fortification,"],["porque","because"],["amontoarão","they-will-accumulate"],["terra,","land,"],["e","and"],["as","the"],["tomarão.","they-will-get."]]},
  {num:11,words:[["Então","Said"],["passará","overflow"],["como","as"],["o","the"],["vento,","wind,"],["e","and"],["seguirá,","imputing,"],["e","and"],["se","if"],["fará","will-make"],["culpada,","guilty,"],["atribuindo","I-accredit"],["este","this"],["seu","his"],["poder","can"],["ao","to-the"],["seu","his"],["deus.","god."]]},
  {num:12,words:[["Porventura","Perchance"],["não","no"],["és","you-are"],["tu","you"],["desde","since"],["sempre,","always,"],["ó","O"],["Senhor","Lord"],["meu","my"],["Deus,","God,"],["meu","my"],["Santo?","Holy?"],["Nós","We"],["não","no"],["morreremos.","tomorrow."],["Ó","O"],["Senhor,","Lord,"],["para","for"],["juízo","judgment"],["o","the"],["puseste,","you-placed,"],["e","and"],["tu,","you,"],["ó","O"],["Rocha,","Rock,"],["o","the"],["fundaste","you-erected"],["para","for"],["castigar.","punish."]]},
  {num:13,words:[["Tu","You"],["és","you-are"],["tão","that much"],["puro","pure"],["de","of"],["olhos,","eyes,"],["que","that"],["não","no"],["podes","you-can"],["ver","see"],["o","the"],["mal,","evil,"],["e","and"],["a","to"],["opressão","oppression"],["não","no"],["podes","you-can"],["contemplar.","contemplate."],["Por","By"],["que","that"],["olhas","you-glance"],["para","for"],["os","the"],["que","that"],["procedem","they-act"],["traiçoeiramente?","treacherously?"],["Por","By"],["que","that"],["te","you"],["calas","you-stilled"],["quando","when"],["o","the"],["ímpio","wicked"],["devora","devours"],["aquele","that ... over there"],["que","that"],["é","is"],["mais","still"],["justo","fair"],["do","of-the"],["que","that"],["ele?","he?"]]},
  {num:14,words:[["E","And"],["por","by"],["que","that"],["farias","forbare"],["os","the"],["homens","men"],["como","as"],["os","the"],["peixes","fishes"],["do","of-the"],["mar,","sea,"],["como","as"],["os","the"],["répteis,","creeping,"],["que","that"],["não","no"],["têm","they-have"],["quem","who"],["os","the"],["governe?","directs?"]]},
  {num:15,words:[["Ele","He"],["a","to"],["todos","all"],["tira","ribbon"],["com","with"],["o","the"],["anzol,","hook,"],["apanhá-los-á","will-catch-the"],["com","with"],["a","to"],["sua","his"],["rede,","net,"],["e","and"],["os","the"],["ajunta","gathereth"],["na","in-the"],["sua","his"],["rede","net"],["varredoura;","varredoura;"],["por isso","therefore"],["ele","he"],["se","if"],["alegra","rejoiceth"],["e","and"],["se","if"],["regozija.","typifying."]]},
  {num:16,words:[["Por isso","therefore"],["sacrifica","sacrificeth"],["à","to-the"],["sua","his"],["rede,","net,"],["e","and"],["queima","burneth"],["incenso","incense"],["à","to-the"],["sua","his"],["varredoura;","varredoura;"],["porque","because"],["com","with"],["elas","they"],["se","if"],["engordou","to-engordar"],["a","to"],["sua","his"],["porção,","portion,"],["e","and"],["aumentou","accrued"],["a","to"],["sua","his"],["comida.","meat."]]},
  {num:17,words:[["Porventura","Perchance"],["por isso","therefore"],["esvaziará","will-empty"],["a","to"],["sua","his"],["rede,","net,"],["e","and"],["continuará","will-continue"],["a","to"],["matar","butcher"],["os","the"],["povos","nations"],["sem","without"],["os","the"],["poupar?","avoid?"]]}
];
var v2 = [
  {num:1,words:[["Sobre","Upon"],["a","to"],["minha","my"],["guarda","guard"],["estarei,","I-will-be,"],["e","and"],["sobre","upon"],["a","to"],["fortaleza","fortification"],["me","me"],["apresentarei","I-will-exhibit"],["e","and"],["vigiarei,","I-will-guard,"],["para","for"],["ver","see"],["o","the"],["que","that"],["ele","he"],["me","me"],["dirá,","will-say,"],["e","and"],["o","the"],["que","that"],["eu","I"],["responderei,","I-will-answer,"],["quando","when"],["eu","I"],["for","will-be"],["arguido.","I-should-accuse."]]},
  {num:2,words:[["Então","Said"],["o","the"],["Senhor","Lord"],["me","me"],["respondeu,","answered,"],["e","and"],["disse:","said:"],["Escreve","Write"],["a","to"],["visão,","vision,"],["e","and"],["grava-a","engraves-the"],["claramente","clearly"],["em","in"],["tábuas,","boards,"],["para que","that"],["nelas","in-him"],["leia","reads"],["o","the"],["que","that"],["correndo","I-flow"],["passa.","passeth."]]},
  {num:3,words:[["Porque","Because"],["a","to"],["visão","vision"],["é","is"],["ainda","yet"],["para","for"],["o","the"],["tempo","time"],["determinado,","determined,"],["pois","for"],["no","in-the"],["fim","end"],["falará,","will-speak,"],["e","and"],["não","no"],["mentirá;","will-pretended;"],["se","if"],["tardar,","oughtest,"],["espera-o,","waiteth-the,"],["porque","because"],["certamente","certainly"],["virá,","will-come,"],["não","no"],["tardará.","prolonged."]]},
  {num:4,words:[["Eis que","behold"],["sua","his"],["alma","soul"],["se","if"],["ensoberbece,","envieth,"],["não","no"],["é","is"],["reta","straight"],["nele;","in-him;"],["mas","but"],["o","the"],["justo","fair"],["pela","by-the"],["sua","his"],["fé","faith"],["viverá.","live."]]},
  {num:5,words:[["Quanto","As"],["mais","still"],["se","if"],["é","is"],["dado","given"],["ao","to-the"],["vinho","wine"],["mais","still"],["desleal","disloyal"],["se","if"],["é;","is;"],["aquele","that ... over there"],["homem","man"],["soberbo,","proud,"],["que","that"],["alarga","enlarge"],["como","as"],["o","the"],["sepulcro","sepulchre"],["a","to"],["sua","his"],["alma,","soul,"],["não","no"],["permanecerá,","will-remain,"],["e","and"],["é","is"],["como","as"],["a","to"],["morte","death"],["que","that"],["não","no"],["se","if"],["farta,","satiated,"],["e","and"],["ajunta","gathereth"],["a","to"],["si","himself"],["todas","things"],["as","the"],["nações,","nations,"],["e","and"],["congrega","enlargeth"],["a","to"],["si","himself"],["todos","all"],["os","the"],["povos.","nations."]]},
  {num:6,words:[["Não","No"],["levantariam,","they-should-hoist,"],["pois,","for,"],["todos","all"],["estes","these"],["contra","against"],["ele","he"],["uma","a"],["parábola,","parable,"],["e","and"],["provérbio","proverb"],["sarcástico","acid"],["contra","against"],["ele?","he?"],["E","And"],["se","if"],["dirá:","will-say:"],["Ai","Ouch"],["daquele","of-that"],["que","that"],["multiplica","increaseth"],["o","the"],["que","that"],["não","no"],["é","is"],["seu!","his!"],["(Até","(Until"],["quando?)","when?)"],["e","and"],["daquele","of-that"],["que","that"],["carrega","carries"],["sobre","upon"],["si","himself"],["dívida!","debt!"]]},
  {num:7,words:[["Porventura","Perchance"],["não","no"],["se","if"],["levantarão","they-will-hoist"],["de repente","suddenly"],["os","the"],["teus","your"],["credores?","creditor?"],["e","and"],["não","no"],["despertarão","they-will-awaken"],["os","the"],["que","that"],["te","you"],["abalarão?","they-will-move?"],["e","and"],["não","no"],["lhes","to-them"],["servirás","you-will-serve"],["tu","you"],["de","of"],["despojo?","spoil?"]]},
  {num:8,words:[["Porquanto","Because"],["despojaste","men's"],["muitas","many"],["nações,","nations,"],["todos","all"],["os","the"],["demais","moreover"],["povos","nations"],["te","you"],["despojarão","forests"],["a","to"],["ti,","you,"],["por","by"],["causa","sake"],["do","of-the"],["sangue","blood"],["dos","of-the"],["homens,","men,"],["e","and"],["da","of-the"],["violência","violence"],["acerca","concerning"],["da","of-the"],["terra,","land,"],["da","of-the"],["cidade,","city,"],["e","and"],["de","of"],["todos","all"],["os","the"],["que","that"],["habitam","dwell"],["nela.","in-it."]]},
  {num:9,words:[["Ai","Ouch"],["daquele","of-that"],["que","that"],["ajunta","gathereth"],["bens","good"],["para","for"],["a","to"],["sua","his"],["casa,","house,"],["por","by"],["uma","a"],["avareza","covetousness"],["criminosa,","criminal,"],["para que","that"],["ponha","footstool"],["o","the"],["seu","his"],["ninho","nest"],["no","in-the"],["alto,","high,"],["a fim de","in-order-to"],["se","if"],["livrar","free"],["da","of-the"],["mão","hand"],["do","of-the"],["mal!","evil!"]]},
  {num:10,words:[["Vergonha","Shame"],["maquinaste","cutting"],["para","for"],["a","to"],["tua","your"],["casa;","house;"],["destruindo","I-destroy"],["tu","you"],["a","to"],["muitos","many"],["povos,","nations,"],["pecaste","you-sinned"],["contra","against"],["a","to"],["tua","your"],["alma.","soul."]]},
  {num:11,words:[["Porque","Because"],["a","to"],["pedra","stone"],["clamará","will-cry"],["da","of-the"],["parede,","wall,"],["e","and"],["a","to"],["trave","beam"],["lhe","to-him"],["responderá","will-answer"],["do","of-the"],["madeiramento.","beam."]]},
  {num:12,words:[["Ai","Ouch"],["daquele","of-that"],["que","that"],["edifica","builds"],["a","to"],["cidade","city"],["com","with"],["sangue,","blood,"],["e","and"],["que","that"],["funda","sling"],["a","to"],["cidade","city"],["com","with"],["iniquidade!","iniquity!"]]},
  {num:13,words:[["Eis que","behold"],["porventura","perchance"],["não","no"],["vem","comes"],["do","of-the"],["Senhor dos","hosts"],["Exércitos","Hosts"],["que","that"],["os","the"],["povos","nations"],["trabalhem","they-labor"],["para","for"],["o","the"],["fogo","fire"],["e","and"],["os","the"],["homens","men"],["se","if"],["cansem","weary"],["em vão?","in-vain"]]},
  {num:14,words:[["Porque","Because"],["a","to"],["terra","land"],["se","if"],["encherá","will-replenish"],["do","of-the"],["conhecimento","knowledge"],["da","of-the"],["glória","glory"],["do","of-the"],["Senhor,","Lord,"],["como","as"],["as","the"],["águas","waters"],["cobrem","cover"],["o","the"],["mar.","sea."]]},
  {num:15,words:[["Ai","Ouch"],["daquele","of-that"],["que","that"],["dá","gives"],["de","of"],["beber","drink"],["ao","to-the"],["seu","his"],["próximo!","near!"],["Tu,","You,"],["que","that"],["lhe","to-him"],["chegas","you-come"],["o","the"],["teu","your"],["odre,","bottle,"],["e","and"],["o","the"],["embebedas,","puttest,"],["para","for"],["ver","see"],["a","to"],["sua","his"],["nudez!","nakedness!"]]},
  {num:16,words:[["Também","Also"],["tu","you"],["serás","you-will-be"],["farto","full"],["de","of"],["vergonha","shame"],["em lugar de","in-place-of"],["honra;","honour;"],["bebe","drinketh"],["tu","you"],["também,","also,"],["e","and"],["sê","be"],["como","as"],["um","a"],["incircunciso;","uncircumcised;"],["o","the"],["cálice","cup"],["da","of-the"],["mão","hand"],["direita","right"],["do","of-the"],["Senhor","Lord"],["voltará","will-return"],["a","to"],["ti,","you,"],["e","and"],["a","to"],["desonra","dishonour"],["cairá","fall"],["sobre","upon"],["a","to"],["tua","your"],["glória.","glory."]]},
  {num:17,words:[["Porque","Because"],["a","to"],["violência","violence"],["cometida","committed"],["contra","against"],["o","the"],["Líbano","Lebanon"],["te","you"],["cobrirá,","cover,"],["e","and"],["a","to"],["destruição","destruction"],["dos","of-the"],["animais","beasts"],["os","the"],["assombrará,","men's,"],["por","by"],["causa","sake"],["do","of-the"],["sangue","blood"],["dos","of-the"],["homens,","men,"],["e","and"],["da","of-the"],["violência","violence"],["acerca","concerning"],["da","of-the"],["terra,","land,"],["da","of-the"],["cidade,","city,"],["e","and"],["de","of"],["todos","all"],["os","the"],["moradores.","inhabitants."]]},
  {num:18,words:[["Que","That"],["aproveitará","will-profit"],["a","to"],["imagem","image"],["de","of"],["escultura,","graven,"],["depois que","after"],["a","to"],["esculpiu","profiteth"],["o","the"],["seu","his"],["artífice?","workman?"],["ou","or"],["a","to"],["imagem","image"],["de","of"],["fundição,","molten,"],["que","that"],["ensina","teacheth"],["a","to"],["mentira,","lie,"],["para que","that"],["o","the"],["artífice","workman"],["confie","unnoticed"],["na","in-the"],["obra,","work,"],["fazendo","doing"],["ídolos","idols"],["mudos?","dumb?"]]},
  {num:19,words:[["Ai","Ouch"],["daquele","of-that"],["que","that"],["diz","says"],["à","to-the"],["madeira:","wood:"],["Acorda!","Awaketh!"],["e","and"],["à","to-the"],["pedra","stone"],["muda:","changeth:"],["Desperta!","Awake!"],["Porventura","Perchance"],["ensinará?","will-teach?"],["Eis que","behold"],["está","is"],["coberto","covered"],["de","of"],["ouro","gold"],["e","and"],["de","of"],["prata,","silver,"],["mas","but"],["no","in-the"],["meio","midst"],["dele","of-him"],["não","no"],["há","has"],["espírito","spirit"],["algum.","any."]]},
  {num:20,words:[["Porém","But"],["o","the"],["Senhor","Lord"],["está","is"],["no","in-the"],["seu","his"],["santo","holy"],["templo;","temple;"],["cale-se","be quiet"],["diante","before"],["dele","of-him"],["toda","every"],["a","to"],["terra.","land."]]}
];
var v3 = [
  {num:1,words:[["Oração","Prayer"],["do","of-the"],["profeta","prophet"],["Habacuque","Habakkuk"],["sobre","upon"],["Sigionote.","Shigionoth."]]},
  {num:2,words:[["Ouvi,","I-heard,"],["Senhor,","Lord,"],["a","to"],["tua","your"],["palavra,","word,"],["e","and"],["temi;","I-feared;"],["aviva,","refreshes,"],["ó","O"],["Senhor,","Lord,"],["a","to"],["tua","your"],["obra","work"],["no","in-the"],["meio","midst"],["dos","of-the"],["anos,","years,"],["no","in-the"],["meio","midst"],["dos","of-the"],["anos","years"],["faze-a","gallim"],["conhecida;","known;"],["na","in-the"],["tua","your"],["ira","anger"],["lembra-te","remember"],["da","of-the"],["misericórdia.","mercy."]]},
  {num:3,words:[["Deus","God"],["veio","came"],["de","of"],["Temã,","Teman,"],["e","and"],["o","the"],["Santo","Holy"],["do","of-the"],["monte","mountain"],["Parã.","Paran."],["(Selá.)","(Selah.)"],["A","To"],["sua","his"],["glória","glory"],["cobriu","overlaid"],["os","the"],["céus,","heaven,"],["e","and"],["a","to"],["terra","land"],["encheu-se","courage"],["do","of-the"],["seu","his"],["louvor.","praise."]]},
  {num:4,words:[["E","And"],["o","the"],["resplendor","brightness"],["se","if"],["fez","made"],["como","as"],["a","to"],["luz,","light,"],["raios","lightning"],["brilhantes","stains"],["lhe","to-him"],["saíam","they-exited"],["da","of-the"],["sua","his"],["mão,","hand,"],["e","and"],["ali","there"],["estava","was"],["o","the"],["esconderijo","hiding"],["da","of-the"],["sua","his"],["força.","strength."]]},
  {num:5,words:[["Diante","Before"],["dele","of-him"],["ia","went"],["a","to"],["peste,","pestilence,"],["e","and"],["brasas","coals"],["ardentes","fiery"],["passavam","wagging"],["diante","before"],["dos","of-the"],["seus","his"],["pés.","feet."]]},
  {num:6,words:[["Parou,","Halt,"],["e","and"],["mediu","measured"],["a","to"],["terra;","land;"],["olhou,","looked,"],["e","and"],["fez","made"],["sair","exit"],["as","the"],["nações;","nations;"],["e","and"],["os","the"],["montes","mountains"],["perpétuos","perpetual"],["foram","they-were"],["esmiuçados;","threshingfloors;"],["os","the"],["outeiros","hills"],["eternos","purposes"],["se","if"],["encurvaram,","ashtoreth,"],["porque","because"],["os","the"],["seus","his"],["caminhos","ways"],["são","they-are"],["eternos.","purposes."]]},
  {num:7,words:[["Vi","I-saw"],["as","the"],["tendas","tents"],["de","of"],["Cusã","Cushan"],["em","in"],["aflição;","affliction;"],["as","the"],["cortinas","curtains"],["da","of-the"],["terra","land"],["de","of"],["Midiã","Midian"],["tremiam.","they-trembled."]]},
  {num:8,words:[["Acaso","Perchance"],["é","is"],["contra","against"],["os","the"],["rios,","rivers,"],["Senhor,","Lord,"],["que","that"],["tu","you"],["estás","you-are"],["irado?","angry?"],["contra","against"],["os","the"],["ribeiros","brooks"],["foi","was"],["a","to"],["tua","your"],["ira?","anger?"],["contra","against"],["o","the"],["mar","sea"],["foi","was"],["o","the"],["teu","your"],["furor","fury"],["quando","when"],["andaste","you-walked"],["montado","rideth"],["sobre","upon"],["os","the"],["teus","your"],["cavalos,","horses,"],["os","the"],["teus","your"],["carros","chariots"],["de","of"],["salvação?","salvation?"]]},
  {num:9,words:[["Desnudou-se","To-desnudar-se"],["inteiramente","entirely"],["o","the"],["teu","your"],["arco,","bow,"],["pelos","by-the"],["juramentos","oaths"],["feitos","acts"],["às","to-the"],["tribos,","tribes,"],["pela","by-the"],["tua","your"],["palavra.","word."],["(Selá.)","(Selah.)"],["Tu","You"],["fendeste","you-split"],["a","to"],["terra","land"],["com","with"],["rios.","rivers."]]},
  {num:10,words:[["Os","The"],["montes","mountains"],["te","you"],["viram,","they-saw,"],["e","and"],["tremeram;","they-trembled;"],["a","to"],["inundação","flood"],["das","of-the"],["águas","waters"],["passou;","passed;"],["o","the"],["abismo","gulf"],["fez","made"],["ouvir","hear"],["a","to"],["sua","his"],["voz,","voice,"],["levantou","arose"],["as","the"],["suas","his"],["mãos","hands"],["ao","to-the"],["alto.","high."]]},
  {num:11,words:[["O","The"],["sol","sun"],["e","and"],["a","to"],["lua","moon"],["pararam","they-halt"],["nas","in-the"],["suas","his"],["moradas;","dwellings;"],["andaram","walked"],["à","to-the"],["luz","light"],["das","of-the"],["tuas","your"],["flechas,","arrows,"],["ao","to-the"],["resplendor","brightness"],["do","of-the"],["relâmpago","lightning"],["da","of-the"],["tua","your"],["lança.","spear."]]},
  {num:12,words:[["Com","With"],["indignação","indignation"],["marchaste","you-abandoned"],["pela","by-the"],["terra,","land,"],["com","with"],["ira","anger"],["trilhaste","you-threshed"],["as","the"],["nações.","nations."]]},
  {num:13,words:[["Tu","You"],["saíste","you-exited"],["para","for"],["salvamento","woundedst"],["do","of-the"],["teu","your"],["povo,","people,"],["para","for"],["salvamento","woundedst"],["do","of-the"],["teu","your"],["ungido;","anointed;"],["tu","you"],["feriste","you-hurt"],["a","to"],["cabeça","head"],["da","of-the"],["casa","house"],["do","of-the"],["ímpio,","wicked,"],["descobrindo","I-uncover"],["o","the"],["alicerce","foundation"],["até","until"],["o","the"],["pescoço.","neck."],["(Selá.)","(Selah.)"]]},
  {num:14,words:[["Tu","You"],["furaste","you-bored"],["com","with"],["os","the"],["teus","your"],["cajados","staff"],["a","to"],["cabeça","head"],["das","of-the"],["suas","his"],["aldeias;","villages;"],["eles","they"],["me","me"],["acometeram","they-assaulted"],["tempestuosos","stormy"],["para","for"],["me","me"],["espalharem;","they-will-disseminate;"],["alegravam-se,","they-hereunto,"],["como","as"],["se","if"],["estivessem","they-were"],["para","for"],["devorar","devour"],["o","the"],["pobre","poor"],["em","in"],["segredo.","secret."]]},
  {num:15,words:[["Tu","You"],["com","with"],["os","the"],["teus","your"],["cavalos","horses"],["marchaste","you-abandoned"],["pelo","by-the"],["mar,","sea,"],["pelo","by-the"],["montão","heap"],["de","of"],["grandes","great"],["águas.","waters."]]},
  {num:16,words:[["Ouvindo-o","Heard-the"],["eu,","I,"],["o","the"],["meu","my"],["ventre","abdomen"],["se","if"],["comoveu,","moved,"],["à","to-the"],["sua","his"],["voz","voice"],["tremeram","they-trembled"],["os","the"],["meus","my"],["lábios;","lips;"],["entrou","entered"],["a","to"],["podridão","rottenness"],["nos","us"],["meus","my"],["ossos,","bones,"],["e","and"],["estremeci","I-agitated"],["dentro de","within"],["mim;","me;"],["no","in-the"],["dia","day"],["da","of-the"],["angústia","anguish"],["descansarei,","I-will-repose,"],["quando","when"],["subir","climb"],["contra","against"],["o","the"],["povo","people"],["que","that"],["nos","us"],["atacará.","will-attack."]]},
  {num:17,words:[["Porque","Because"],["ainda que","although"],["a","to"],["figueira","fig"],["não","no"],["floresça,","stalls,"],["nem","nor"],["haja","has"],["fruto","fruit"],["na","in-the"],["vide;","vine;"],["o","the"],["produto","product"],["da","of-the"],["oliveira","olive"],["decepcione,","stalls,"],["e","and"],["os","the"],["campos","fields"],["não","no"],["produzam","they-activate"],["mantimento;","food;"],["as","the"],["ovelhas","sheep"],["da","of-the"],["malhada","beat"],["sejam","they-are"],["arrebatadas,","snap up,"],["e","and"],["nos","us"],["currais","folds"],["não","no"],["haja","has"],["vacas;","cow;"]]},
  {num:18,words:[["Todavia","Nevertheless"],["eu","I"],["me","me"],["alegrarei","adversities"],["no","in-the"],["Senhor;","Lord;"],["regozijar-me-ei","I-will-cure"],["no","in-the"],["Deus","God"],["da","of-the"],["minha","my"],["salvação.","salvation."]]},
  {num:19,words:[["O","The"],["Senhor","Lord"],["Deus","God"],["é","is"],["minha","my"],["força,","strength,"],["e","and"],["fará","will-make"],["os","the"],["meus","my"],["pés","feet"],["como","as"],["os","the"],["das","of-the"],["cervas,","deer,"],["e","and"],["me","me"],["fará","will-make"],["andar","walk"],["sobre","upon"],["as","the"],["minhas","my"],["alturas.","heights."],["Para","For"],["o","the"],["cantor-mor","cantor-mor"],["sobre","upon"],["os","the"],["meus","my"],["instrumentos","instruments"],["de","of"],["música.","music."]]}
];
renderVerseSet(v1, 'hab-ch1-verses');
renderVerseSet(v2, 'hab-ch2-verses');
renderVerseSet(v3, 'hab-ch3-verses');
})();
