(function() {
var v1 = [
  {num:1,words:[["Palavra","Word"],["do","of-the"],["Senhor,","Lord,"],["que","that"],["foi","was"],["dita","forces"],["a","to"],["Oseias,","Hoshea,"],["filho","son"],["de","of"],["Beeri,","Beeri,"],["nos","us"],["dias","days"],["de","of"],["Uzias,","Uzziah,"],["Jotão,","Jotham,"],["Acaz,","Ahaz,"],["Ezequias,","Hezekiah,"],["reis","kings"],["de","of"],["Judá,","Judah,"],["e","and"],["nos","us"],["dias","days"],["de","of"],["Jeroboão,","Jeroboam,"],["filho","son"],["de","of"],["Joás,","Joash,"],["rei","king"],["de","of"],["Israel.","Israel."]]},
  {num:2,words:[["O","The"],["princípio","beginning"],["da","of-the"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["por","by"],["Oseias:","Hoshea:"],["Disse,","Said,"],["pois,","for,"],["o","the"],["Senhor","Lord"],["a","to"],["Oseias:","Hoshea:"],["Vai,","Goes,"],["toma","take"],["uma","a"],["mulher","dame"],["de","of"],["prostituições,","whoredoms,"],["e","and"],["filhos","children"],["de","of"],["prostituições;","whoredoms;"],["porque","because"],["a","to"],["terra","land"],["certamente","certainly"],["se","if"],["prostitui,","prostitutes,"],["desviando-se","I-meddling"],["do","of-the"],["Senhor.","Lord."]]},
  {num:3,words:[["E","And"],["foi,","was,"],["e","and"],["tomou","took"],["Gômer,","Diblaim,"],["filha","daughter"],["de","of"],["Diblaim,","Diblaim,"],["e","and"],["ela","she"],["concebeu,","conceived,"],["e","and"],["lhe","to-him"],["deu","gave"],["um","a"],["filho.","son."]]},
  {num:4,words:[["E","And"],["disse-lhe","said"],["o","the"],["Senhor:","Lord:"],["Chama","Flame"],["o","the"],["seu","his"],["nome","name"],["Jezreel;","Jezreel;"],["porque","because"],["daqui","of-here"],["a","to"],["pouco","few"],["vingarei","I-will-avenge"],["o","the"],["sangue","blood"],["de","of"],["Jezreel","Jezreel"],["sobre","upon"],["a","to"],["casa","house"],["de","of"],["Jeú,","Jehu,"],["e","and"],["farei","I-will-make"],["cessar","cease"],["o","the"],["reino","kingdom"],["da","of-the"],["casa","house"],["de","of"],["Israel.","Israel."]]},
  {num:5,words:[["E","And"],["acontecerá","will-become"],["naquele","in-that"],["dia","day"],["que","that"],["quebrarei","I-will-crush"],["o","the"],["arco","bow"],["de","of"],["Israel","Israel"],["no","in-the"],["vale","valley"],["de","of"],["Jezreel.","Jezreel."]]},
  {num:6,words:[["E","And"],["tornou","became"],["ela","she"],["a","to"],["conceber,","conceive,"],["e","and"],["deu","gave"],["à","to-the"],["luz","light"],["uma","a"],["filha;","daughter;"],["e","and"],["Deus","God"],["lhe","to-him"],["disse:","said:"],["Chama","Flame"],["o","the"],["seu","his"],["nome","name"],["Lo-Ruama;","Lo-Ruhamah;"],["porque","because"],["eu","I"],["não","no"],["tornarei","I-will-become"],["mais","still"],["a","to"],["me","me"],["compadecer","lo-ruhamah"],["da","of-the"],["casa","house"],["de","of"],["Israel,","Israel,"],["mas","but"],["tudo","whatsoever"],["lhe","to-him"],["tirarei.","I-will-deduct."]]},
  {num:7,words:[["Mas","But"],["me","me"],["apiedarei","pity"],["da","of-the"],["casa","house"],["de","of"],["Judá,","Judah,"],["e","and"],["os","the"],["salvarei","I-will-save"],["pelo","by-the"],["Senhor","Lord"],["seu","his"],["Deus,","God,"],["pois","for"],["não","no"],["os","the"],["salvarei","I-will-save"],["pelo","by-the"],["arco,","bow,"],["nem","nor"],["pela","by-the"],["espada,","sword,"],["nem","nor"],["pela","by-the"],["guerra,","war,"],["nem","nor"],["pelos","by-the"],["cavalos,","horses,"],["nem","nor"],["pelos","by-the"],["cavaleiros.","horsemen."]]},
  {num:8,words:[["E","And"],["depois","afterwards"],["de","of"],["haver","have"],["desmamado","weaned"],["Lo-Ruama,","Lo-Ruhamah,"],["ela","she"],["concebeu","conceived"],["e","and"],["deu","gave"],["à","to-the"],["luz","light"],["um","a"],["filho.","son."]]},
  {num:9,words:[["E","And"],["Deus","God"],["disse:","said:"],["Chama","Flame"],["o","the"],["seu","his"],["nome","name"],["Lo-Ami;","Lo-ammi;"],["porque","because"],["vós","you"],["não","no"],["sois","you-are"],["meu","my"],["povo,","people,"],["nem","nor"],["eu","I"],["serei","I-will-be"],["vosso","your"],["Deus.","God."]]},
  {num:10,words:[["Todavia","Nevertheless"],["o","the"],["número","number"],["dos","of-the"],["filhos","children"],["de","of"],["Israel","Israel"],["será","will-be"],["como","as"],["a","to"],["areia","sand"],["do","of-the"],["mar,","sea,"],["que","that"],["não","no"],["se","if"],["pode","can"],["medir","measuring"],["nem","nor"],["contar;","narrate;"],["e","and"],["acontecerá","will-become"],["que","that"],["no","in-the"],["lugar","place"],["onde","where"],["se","if"],["lhes","to-them"],["dizia:","said:"],["Vós","You"],["não","no"],["sois","you-are"],["meu","my"],["povo,","people,"],["se","if"],["lhes","to-them"],["dirá:","will-say:"],["Vós","You"],["sois","you-are"],["filhos","children"],["do","of-the"],["Deus","God"],["vivo.","alive."]]},
  {num:11,words:[["E","And"],["os","the"],["filhos","children"],["de","of"],["Judá","Judah"],["e","and"],["os","the"],["filhos","children"],["de","of"],["Israel","Israel"],["juntos","together"],["se","if"],["congregarão,","nebaioth,"],["e","and"],["constituirão","they-will-constitute"],["sobre","upon"],["si","himself"],["uma","a"],["única","alone"],["cabeça,","head,"],["e","and"],["subirão","climb"],["da","of-the"],["terra;","land;"],["porque","because"],["grande","great"],["será","will-be"],["o","the"],["dia","day"],["de","of"],["Jezreel.","Jezreel."]]}
];
var v2 = [
  {num:1,words:[["Dizei","Say"],["a","to"],["vossos","your"],["irmãos:","brethren:"],["Ami,","Ami,"],["e","and"],["a","to"],["vossas","your"],["irmãs:","sisters:"],["Ruama.","Drop."]]},
  {num:2,words:[["Contendei","Contend"],["com","with"],["vossa","your"],["mãe,","mother,"],["contendei,","contend,"],["porque","because"],["ela","she"],["não","no"],["é","is"],["minha","my"],["mulher,","dame,"],["e","and"],["eu","I"],["não","no"],["sou","I-am"],["seu","his"],["marido,","husband,"],["e","and"],["tire","deducts"],["ela","she"],["as","the"],["suas","his"],["prostituições","whoredoms"],["da","of-the"],["sua","his"],["face","face"],["e","and"],["os","the"],["seus","his"],["adultérios","adulteries"],["de","of"],["entre","between"],["os","the"],["seus","his"],["peitos.","breasts."]]},
  {num:3,words:[["Para que","that"],["eu","I"],["não","no"],["a","to"],["deixe","allows"],["despida,","bare,"],["e","and"],["a","to"],["ponha","footstool"],["como","as"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["nasceu,","born,"],["e","and"],["a","to"],["faça","makes"],["como","as"],["um","a"],["deserto,","desert,"],["e","and"],["a","to"],["ponha","footstool"],["como","as"],["uma","a"],["terra","land"],["seca,","dry,"],["e","and"],["a","to"],["mate","butchers"],["de","of"],["sede,","thirst,"]]},
  {num:4,words:[["E","And"],["não","no"],["me","me"],["apiede","whoredoms"],["de","of"],["seus","his"],["filhos,","children,"],["porque","because"],["são","they-are"],["filhos","children"],["de","of"],["prostituições.","whoredoms."]]},
  {num:5,words:[["Porque","Because"],["sua","his"],["mãe","mother"],["se","if"],["prostituiu;","prostituted;"],["aquela","that ... over there"],["que","that"],["os","the"],["concebeu","conceived"],["houve-se","to-haver-se"],["torpemente,","lucrely,"],["porque","because"],["diz:","says:"],["Irei","I-will-go"],["atrás","behind"],["de","of"],["meus","my"],["amantes,","lovers,"],["que","that"],["me","me"],["dão","they-give"],["o","the"],["meu","my"],["pão","bread"],["e","and"],["a","to"],["minha","my"],["água,","water,"],["a","to"],["minha","my"],["lã","wool"],["e","and"],["o","the"],["meu","my"],["linho,","linen,"],["o","the"],["meu","my"],["óleo","oil"],["e","and"],["as","the"],["minhas","my"],["bebidas.","drinks."]]},
  {num:6,words:[["Portanto,","Therefore,"],["eis que","behold"],["cercarei","I-will-besiege"],["o","the"],["teu","your"],["caminho","way"],["com","with"],["espinhos;","thorns;"],["e","and"],["levantarei","raise"],["uma","a"],["parede","wall"],["de","of"],["sebe,","hedge,"],["e","and"],["ela","she"],["não","no"],["achará","will-find"],["as","the"],["suas","his"],["veredas.","paths."]]},
  {num:7,words:[["E","And"],["irá","will-go"],["atrás","behind"],["de","of"],["seus","his"],["amantes,","lovers,"],["mas","but"],["não","no"],["os","the"],["alcançará;","will-accomplish;"],["e","and"],["buscá-los-á,","will-seek-the,"],["mas","but"],["não","no"],["os","the"],["achará;","will-find;"],["então","said"],["dirá:","will-say:"],["Ir-me-ei,","To-ir-se,"],["e","and"],["retornarei","I-will-recur"],["a","to"],["meu","my"],["primeiro","first"],["marido,","husband,"],["porque","because"],["melhor","better"],["me","me"],["ia","went"],["então","said"],["do","of-the"],["que","that"],["agora.","now."]]},
  {num:8,words:[["Ela,","She,"],["pois,","for,"],["não","no"],["reconhece","acknowledge"],["que","that"],["eu","I"],["lhe","to-him"],["dei","I-gave"],["o","the"],["grão,","grain,"],["e","and"],["o","the"],["mosto,","corn,"],["e","and"],["o","the"],["óleo,","oil,"],["e","and"],["lhe","to-him"],["multipliquei","I-multiplied"],["a","to"],["prata","silver"],["e","and"],["o","the"],["ouro,","gold,"],["que","that"],["eles","they"],["usaram","they-costly"],["para","for"],["Baal.","Baal."]]},
  {num:9,words:[["Portanto,","Therefore,"],["retornarei,","I-will-recur,"],["e","and"],["a","to"],["seu","his"],["tempo","time"],["tirarei","I-will-deduct"],["o","the"],["meu","my"],["grão","grain"],["e","and"],["o","the"],["meu","my"],["mosto","corn"],["ao","to-the"],["seu","his"],["determinado","determined"],["tempo;","time;"],["e","and"],["arrebatarei","I-will-snap up"],["a","to"],["minha","my"],["lã","wool"],["e","and"],["o","the"],["meu","my"],["linho,","linen,"],["que","that"],["tinha","had"],["dado","given"],["para","for"],["cobrir","cover"],["a","to"],["sua","his"],["nudez.","nakedness."]]},
  {num:10,words:[["E","And"],["agora","now"],["descobrirei","plantings"],["a","to"],["sua","his"],["vileza","vileness"],["diante","before"],["dos","of-the"],["olhos","eyes"],["dos","of-the"],["seus","his"],["amantes,","lovers,"],["e","and"],["ninguém","none"],["a","to"],["livrará","deliver"],["da","of-the"],["minha","my"],["mão.","hand."]]},
  {num:11,words:[["E","And"],["farei","I-will-make"],["cessar","cease"],["todo","every"],["o","the"],["seu","his"],["regozijo,","gladness,"],["as","the"],["suas","his"],["festas,","feasts,"],["as","the"],["suas","his"],["luas","moons"],["novas,","tidings,"],["e","and"],["os","the"],["seus","his"],["sábados,","sabbaths,"],["e","and"],["todas","things"],["as","the"],["suas","his"],["festividades.","moons."]]},
  {num:12,words:[["E","And"],["assolarei","travailing"],["a","to"],["sua","his"],["vide","vine"],["e","and"],["a","to"],["sua","his"],["figueira,","fig,"],["de","of"],["que","that"],["ela","she"],["diz:","says:"],["Estas","These"],["são","they-are"],["a","to"],["minha","my"],["paga","pays"],["que","that"],["me","me"],["deram","they-gave"],["os","the"],["meus","my"],["amantes;","lovers;"],["eu,","I,"],["pois,","for,"],["farei","I-will-make"],["delas","of-him"],["um","a"],["bosque,","forest,"],["e","and"],["as","the"],["feras","beast"],["do","of-the"],["campo","field"],["as","the"],["devorarão.","they-will-devour."]]},
  {num:13,words:[["E","And"],["castigá-la-ei","punish-the"],["pelos","by-the"],["dias","days"],["de","of"],["Baal,","Baal,"],["em","in"],["que","that"],["lhe","to-him"],["queimou","burnt"],["incenso,","incense,"],["e","and"],["se","if"],["adornou","adorn"],["dos","of-the"],["seus","his"],["pendentes","earrings"],["e","and"],["das","of-the"],["suas","his"],["joias,","jewels,"],["e","and"],["andou","walked"],["atrás","behind"],["de","of"],["seus","his"],["amantes,","lovers,"],["mas","but"],["de","of"],["mim","me"],["se","if"],["esqueceu,","attire,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:14,words:[["Portanto,","Therefore,"],["eis que","behold"],["eu","I"],["a","to"],["atrairei,","I-will-attract,"],["e","and"],["a","to"],["levarei","I-will-carry"],["para","for"],["o","the"],["deserto,","desert,"],["e","and"],["lhe","to-him"],["falarei","talk"],["ao","to-the"],["coração.","heart."]]},
  {num:15,words:[["E","And"],["lhe","to-him"],["darei","I-will-give"],["as","the"],["suas","his"],["vinhas","vineyards"],["dali,","of-at that place,"],["e","and"],["o","the"],["vale","valley"],["de","of"],["Acor,","Achor,"],["como","as"],["porta","exit"],["de","of"],["esperança;","hope;"],["e","and"],["ali","there"],["cantará,","crow,"],["como","as"],["nos","us"],["dias","days"],["da","of-the"],["sua","his"],["mocidade,","youth,"],["e","and"],["como","as"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["subiu","climbed"],["da","of-the"],["terra do","egypt"],["Egito.","Egypt."]]},
  {num:16,words:[["E","And"],["acontecerá","will-become"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["que","that"],["me","me"],["chamarás:","you-will-call:"],["Meu","My"],["marido;","husband;"],["e","and"],["não","no"],["me","me"],["chamarás","you-will-call"],["mais:","still:"],["Meu","My"],["Baal.","Baal."]]},
  {num:17,words:[["E","And"],["da","of-the"],["sua","his"],["boca","mouth"],["tirarei","I-will-deduct"],["os","the"],["nomes","names"],["dos","of-the"],["baalins,","baalim,"],["e","and"],["os","the"],["seus","his"],["nomes","names"],["não","no"],["virão","they-will-come"],["mais","still"],["em","in"],["memória.","memory."]]},
  {num:18,words:[["E","And"],["naquele","in-that"],["dia","day"],["lhes","to-them"],["farei","I-will-make"],["aliança","alliance"],["com","with"],["as","the"],["feras","beast"],["do","of-the"],["campo,","field,"],["e","and"],["com","with"],["as","the"],["aves","fowls"],["do","of-the"],["céu,","heaven,"],["e","and"],["com","with"],["os","the"],["répteis","creeping"],["da","of-the"],["terra;","land;"],["e","and"],["da","of-the"],["terra","land"],["quebrarei","I-will-crush"],["o","the"],["arco,","bow,"],["e","and"],["a","to"],["espada,","sword,"],["e","and"],["a","to"],["guerra,","war,"],["e","and"],["os","the"],["farei","I-will-make"],["deitar","lay"],["em","in"],["segurança.","safety."]]},
  {num:19,words:[["E","And"],["desposar-te-ei","betroth"],["comigo","with-me"],["para sempre;","for-ever"],["desposar-te-ei","betroth"],["comigo","with-me"],["em","in"],["justiça,","righteousness,"],["e","and"],["em","in"],["juízo,","judgment,"],["e","and"],["em","in"],["benignidade,","endureth,"],["e","and"],["em","in"],["misericórdias.","mercies."]]},
  {num:20,words:[["E","And"],["desposar-te-ei","betroth"],["comigo","with-me"],["em","in"],["fidelidade,","faithfulness,"],["e","and"],["conhecerás","you-will-know"],["ao","to-the"],["Senhor.","Lord."]]},
  {num:21,words:[["E","And"],["acontecerá","will-become"],["naquele","in-that"],["dia","day"],["que","that"],["eu","I"],["responderei,","I-will-answer,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["eu","I"],["responderei","I-will-answer"],["aos","to-the"],["céus,","heaven,"],["e","and"],["estes","these"],["responderão","hungred"],["à","to-the"],["terra.","land."]]},
  {num:22,words:[["E","And"],["a","to"],["terra","land"],["responderá","will-answer"],["ao","to-the"],["trigo,","wheat,"],["como","as"],["também","also"],["ao","to-the"],["mosto,","corn,"],["e","and"],["ao","to-the"],["óleo,","oil,"],["e","and"],["estes","these"],["responderão","hungred"],["a","to"],["Jezreel.","Jezreel."]]},
  {num:23,words:[["E","And"],["semeá-la-ei","I-will-sow-the"],["para","for"],["mim","me"],["na","in-the"],["terra,","land,"],["e","and"],["apiedar-me-ei","to-apiedar-se"],["de","of"],["Lo-Ruama;","Lo-Ruhamah;"],["e","and"],["a","to"],["Lo-Ami","Lo-ammi"],["direi:","I-will-say:"],["Tu","You"],["és","you-are"],["meu","my"],["povo;","people;"],["e","and"],["ele","he"],["dirá:","will-say:"],["Ó","O"],["meu","my"],["Deus!","God!"]]}
];
var v3 = [
  {num:1,words:[["E","And"],["o","the"],["Senhor","Lord"],["me","me"],["disse:","said:"],["Vai","Goes"],["outra","another"],["vez,","occasion,"],["ama","loveth"],["uma","a"],["mulher,","dame,"],["amada","doves'"],["de","of"],["seu","his"],["amigo,","friend,"],["contudo","yet"],["adúltera,","adulteress,"],["como","as"],["o","the"],["Senhor","Lord"],["ama","loveth"],["os","the"],["filhos","children"],["de","of"],["Israel;","Israel;"],["mas","but"],["eles","they"],["olham","they-glance"],["para","for"],["outros","another"],["deuses,","gods,"],["e","and"],["amam","love"],["os","the"],["bolos","cakes"],["de","of"],["passas.","you-fare."]]},
  {num:2,words:[["E","And"],["comprei-a","excused-the"],["para","for"],["mim","me"],["por","by"],["quinze","fifteen"],["peças","parcel"],["de","of"],["prata","silver"],["e","and"],["um","a"],["ômer","Emer"],["de","of"],["cevada,","barley,"],["e","and"],["meio","midst"],["ômer","Emer"],["de","of"],["cevada;","barley;"]]},
  {num:3,words:[["E","And"],["lhe","to-him"],["disse:","said:"],["Tu","You"],["ficarás","you-will-remain"],["comigo","with-me"],["muitos","many"],["dias","days"],["(não","(no"],["te","you"],["prostituirás,","you-will-prostitute,"],["nem","nor"],["serás","you-will-be"],["de","of"],["outro","another"],["homem),","man),"],["e","and"],["também","also"],["eu","I"],["ficarei","I-will-remain"],["contigo.","with-you."]]},
  {num:4,words:[["Porque","Because"],["os","the"],["filhos","children"],["de","of"],["Israel","Israel"],["ficarão","they-will-remain"],["por","by"],["muitos","many"],["dias","days"],["sem","without"],["rei,","king,"],["e","and"],["sem","without"],["príncipe,","prince,"],["e","and"],["sem","without"],["sacrifício,","sacrifice,"],["e","and"],["sem","without"],["estátua,","statue,"],["e","and"],["sem","without"],["éfode,","ephod,"],["e","and"],["sem","without"],["terafim.","teraphim."]]},
  {num:5,words:[["Depois","Afterwards"],["retornarão","they-will-recur"],["os","the"],["filhos","children"],["de","of"],["Israel,","Israel,"],["e","and"],["buscarão","they-will-seek"],["ao","to-the"],["Senhor","Lord"],["seu","his"],["Deus,","God,"],["e","and"],["a","to"],["Davi,","David,"],["seu","his"],["rei;","king;"],["e","and"],["temerão","they-will-fear"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["à","to-the"],["sua","his"],["bondade,","goodness,"],["nos","us"],["últimos","last"],["dias.","days."]]}
];
var v4 = [
  {num:1,words:[["Ouvi","I-heard"],["a","to"],["palavra","word"],["do","of-the"],["Senhor,","Lord,"],["vós,","you,"],["filhos","children"],["de","of"],["Israel,","Israel,"],["porque","because"],["o","the"],["Senhor","Lord"],["tem","has"],["uma","a"],["contenda","strife"],["com","with"],["os","the"],["habitantes","inhabitants"],["da","of-the"],["terra,","land,"],["porque","because"],["não","no"],["há","has"],["verdade,","truth,"],["nem","nor"],["benignidade,","endureth,"],["nem","nor"],["conhecimento","knowledge"],["de","of"],["Deus","God"],["na","in-the"],["terra.","land."]]},
  {num:2,words:[["Mas","But"],["o","the"],["perjurar,","perjure,"],["e","and"],["o","the"],["mentir,","pretended,"],["e","and"],["o","the"],["matar,","butcher,"],["e","and"],["o","the"],["furtar,","steal,"],["e","and"],["o","the"],["adulterar","dilute"],["prevalecem,","they-prevail,"],["e","and"],["o","the"],["derramamento","shedding"],["de","of"],["sangue","blood"],["leva","leadeth"],["ao","to-the"],["derramamento","shedding"],["de","of"],["sangue.","blood."]]},
  {num:3,words:[["Por isso","therefore"],["a","to"],["terra","land"],["pranteará,","doleful,"],["e","and"],["qualquer que","whosoever"],["morar","brawling"],["nela","in-it"],["desfalecerá,","will-faint,"],["com","with"],["os","the"],["animais","beasts"],["do","of-the"],["campo","field"],["e","and"],["com","with"],["as","the"],["aves","fowls"],["do","of-the"],["céu;","heaven;"],["e","and"],["até","until"],["os","the"],["peixes","fishes"],["do","of-the"],["mar","sea"],["desaparecerão.","vanish."]]},
  {num:4,words:[["Porém","But"],["ninguém","none"],["contenda,","strife,"],["nem","nor"],["repreenda","admonishes"],["a","to"],["alguém,","any,"],["porque","because"],["o","the"],["teu","your"],["povo","people"],["é","is"],["como","as"],["os","the"],["que","that"],["contendem","strive"],["com","with"],["o","the"],["sacerdote.","priest."]]},
  {num:5,words:[["Por isso","therefore"],["cairás","you-will-fall"],["de","of"],["dia,","day,"],["e","and"],["o","the"],["profeta","prophet"],["contigo","with-you"],["cairá","fall"],["de","of"],["noite,","night,"],["e","and"],["destruirei","destroy"],["a","to"],["tua","your"],["mãe.","mother."]]},
  {num:6,words:[["O","The"],["meu","my"],["povo","people"],["foi","was"],["destruído,","destroyed,"],["porque","because"],["lhe","to-him"],["faltou","missed"],["o","the"],["conhecimento;","knowledge;"],["porque","because"],["tu","you"],["rejeitaste","you-rejected"],["o","the"],["conhecimento,","knowledge,"],["também","also"],["eu","I"],["te","you"],["rejeitarei,","I-will-reject,"],["para que","that"],["não","no"],["sejas","you-are"],["sacerdote","priest"],["diante de","before"],["mim;","me;"],["e","and"],["visto que","seeing-that"],["te","you"],["esqueceste","you-forgot"],["da","of-the"],["lei","law"],["do","of-the"],["teu","your"],["Deus,","God,"],["também","also"],["eu","I"],["me","me"],["esquecerei","I-will-forget"],["de","of"],["teus","your"],["filhos.","children."]]},
  {num:7,words:[["Assim como","even-as"],["eles","they"],["se","if"],["multiplicaram,","they-multiplied,"],["assim","thus"],["contra","against"],["mim","me"],["pecaram;","sinned;"],["eu","I"],["mudarei","I-will-vary"],["a","to"],["sua","his"],["honra","honour"],["em","in"],["vergonha.","shame."]]},
  {num:8,words:[["Comem","They-eat"],["do","of-the"],["pecado","sin"],["do","of-the"],["meu","my"],["povo,","people,"],["e","and"],["da","of-the"],["maldade","wickedness"],["dele","of-him"],["têm","they-have"],["desejo","desire"],["ardente.","fiery."]]},
  {num:9,words:[["Portanto,","Therefore,"],["como","as"],["o","the"],["povo,","people,"],["assim","thus"],["será","will-be"],["o","the"],["sacerdote;","priest;"],["e","and"],["castigá-lo-ei","chastise"],["segundo","according-to"],["os","the"],["seus","his"],["caminhos,","ways,"],["e","and"],["lhe","to-him"],["recompensarei","I-will-compensate"],["as","the"],["suas","his"],["obras.","works."]]},
  {num:10,words:[["Comerão,","They-will-eat,"],["mas","but"],["não","no"],["se","if"],["fartarão;","they-will-satiate;"],["prostituir-se-ão,","to-prostituir-se,"],["mas","but"],["não","no"],["se","if"],["multiplicarão;","estates;"],["porque","because"],["deixaram","forsaken"],["de","of"],["olhar","glance"],["para","for"],["o","the"],["Senhor.","Lord."]]},
  {num:11,words:[["A","To"],["prostituição,","whoredom,"],["e","and"],["o","the"],["vinho,","wine,"],["e","and"],["o","the"],["mosto","corn"],["tiram","drawing"],["o","the"],["entendimento.","understanding."]]},
  {num:12,words:[["O","The"],["meu","my"],["povo","people"],["consulta","consultation"],["a","to"],["sua","his"],["madeira,","wood,"],["e","and"],["a","to"],["sua","his"],["vara","rod"],["lhe","to-him"],["responde,","answereth,"],["porque","because"],["o","the"],["espírito","spirit"],["de","of"],["prostituições","whoredoms"],["os","the"],["engana,","deceiveth,"],["e","and"],["se","if"],["prostituem,","spouses,"],["apartando-se","I-separate"],["da","of-the"],["sujeição","bondage"],["do","of-the"],["seu","his"],["Deus.","God."]]},
  {num:13,words:[["Sacrificam","Spouses"],["sobre","upon"],["os","the"],["cumes","tops"],["dos","of-the"],["montes,","mountains,"],["e","and"],["queimam","they-burn"],["incenso","incense"],["sobre","upon"],["os","the"],["outeiros,","hills,"],["debaixo","under"],["do","of-the"],["carvalho,","oak,"],["e","and"],["do","of-the"],["álamo,","poplar,"],["e","and"],["do","of-the"],["olmeiro,","poplars,"],["porque","because"],["é","is"],["boa","good"],["a","to"],["sua","his"],["sombra;","shadow;"],["por isso","therefore"],["vossas","your"],["filhas","daughters"],["se","if"],["prostituem,","spouses,"],["e","and"],["as","the"],["vossas","your"],["noras","spouses"],["adulteram.","they-dilute."]]},
  {num:14,words:[["Não","No"],["castigarei","punish"],["vossas","your"],["filhas,","daughters,"],["que","that"],["se","if"],["prostituem,","spouses,"],["nem","nor"],["vossas","your"],["noras,","spouses,"],["que","that"],["adulteram,","they-dilute,"],["porque","because"],["eles","they"],["mesmos","even"],["com","with"],["as","the"],["prostitutas","whore"],["se","if"],["desviam,","they-bypass,"],["e","and"],["com","with"],["as","the"],["meretrizes","harlots"],["sacrificam;","spouses;"],["pois","for"],["o","the"],["povo","people"],["que","that"],["não","no"],["tem","has"],["entendimento","understanding"],["cairá.","fall."]]},
  {num:15,words:[["Se","If"],["tu,","you,"],["ó","O"],["Israel,","Israel,"],["queres","you-will"],["te","you"],["prostituir,","prostitute,"],["ao","to-the"],["menos","less"],["não","no"],["se","if"],["faça","makes"],["culpado","guilty"],["Judá;","Judah;"],["não","no"],["venhais","you-come"],["a","to"],["Gilgal,","Gilgal,"],["e","and"],["não","no"],["subais","you-climb"],["a","to"],["Bete-Áven,","Beth-Aven,"],["e","and"],["não","no"],["jureis,","you-swear,"],["dizendo:","saying:"],["Vive","Liveth"],["o","the"],["Senhor.","Lord."]]},
  {num:16,words:[["Porque","Because"],["como","as"],["uma","a"],["novilha","heifer"],["obstinada","obstinate"],["se","if"],["rebelou","rebelled"],["Israel;","Israel;"],["agora","now"],["o","the"],["Senhor","Lord"],["os","the"],["apascentará","will-feed"],["como","as"],["a","to"],["um","a"],["cordeiro","lamb"],["num","in-a"],["lugar","place"],["espaçoso.","spacious."]]},
  {num:17,words:[["Efraim","Ephraim"],["aliou-se","to-aliar-se"],["a","to"],["ídolos;","idols;"],["deixa-o.","allows-the."]]},
  {num:18,words:[["A","To"],["sua","his"],["bebida","beverage"],["se","if"],["foi;","was;"],["certamente","certainly"],["se","if"],["prostituíram;","they-prostituted;"],["certamente","certainly"],["os","the"],["seus","his"],["príncipes","princes"],["amaram","they-mammon"],["a","to"],["vergonha.","shame."]]},
  {num:19,words:[["Um","A"],["vento","wind"],["os","the"],["envolveu","entangled"],["nas","in-the"],["suas","his"],["asas,","wings,"],["e","and"],["envergonhar-se-ão","they-will-be ashamed"],["por","by"],["causa","sake"],["dos","of-the"],["seus","his"],["sacrifícios.","sacrifices."]]}
];
var v5 = [
  {num:1,words:[["Ouvi","I-heard"],["isto,","it,"],["ó","O"],["sacerdotes,","priests,"],["e","and"],["escutai,","listen,"],["ó","O"],["casa","house"],["de","of"],["Israel,","Israel,"],["e","and"],["escutai,","listen,"],["ó","O"],["casa","house"],["do rei,","king's"],["porque","because"],["este","this"],["juízo","judgment"],["é","is"],["contra","against"],["vós,","you,"],["visto que","seeing-that"],["fostes","you-were"],["um","a"],["laço","snare"],["para","for"],["Mizpá,","Mizpah,"],["e","and"],["rede","net"],["estendida","I-should-stretch"],["sobre","upon"],["Tabor.","Tabor."]]},
  {num:2,words:[["E","And"],["os","the"],["revoltosos","rebuker"],["se","if"],["aprofundaram","rebuker"],["na","in-the"],["matança;","slaughter;"],["mas","but"],["eu","I"],["castigarei","punish"],["todos","all"],["eles.","they."]]},
  {num:3,words:[["Eu","I"],["conheço","I-know"],["Efraim,","Ephraim,"],["e","and"],["Israel","Israel"],["não","no"],["se","if"],["esconde","hideth"],["de","of"],["mim;","me;"],["porque","because"],["agora","now"],["te","you"],["tens","you-have"],["prostituído,","I-should-prostitute,"],["ó","O"],["Efraim,","Ephraim,"],["e","and"],["se","if"],["contaminou","defiled"],["Israel.","Israel."]]},
  {num:4,words:[["As","The"],["suas","his"],["ações","act"],["não","no"],["lhes","to-them"],["permitem","they-permit"],["voltar","return"],["para","for"],["o","the"],["seu","his"],["Deus,","God,"],["porque","because"],["o","the"],["espírito","spirit"],["das","of-the"],["prostituições","whoredoms"],["está","is"],["no","in-the"],["meio","midst"],["deles,","of-them,"],["e","and"],["não","no"],["conhecem","they-know"],["ao","to-the"],["Senhor.","Lord."]]},
  {num:5,words:[["E","And"],["a","to"],["soberba","pride"],["de","of"],["Israel","Israel"],["testificará","brown"],["no","in-the"],["seu","his"],["rosto;","face;"],["e","and"],["Israel","Israel"],["e","and"],["Efraim","Ephraim"],["cairão","fall"],["pela","by-the"],["sua","his"],["injustiça,","injustice,"],["e","and"],["Judá","Judah"],["cairá","fall"],["juntamente","together"],["com","with"],["eles.","they."]]},
  {num:6,words:[["Então","Said"],["irão","they-will-go"],["com","with"],["as","the"],["suas","his"],["ovelhas,","sheep,"],["e","and"],["com","with"],["as","the"],["suas","his"],["vacas,","cow,"],["para","for"],["buscarem","they-will-seek"],["ao","to-the"],["Senhor,","Lord,"],["mas","but"],["não","no"],["o","the"],["acharão;","they-will-find;"],["ele","he"],["se","if"],["retirou","withdrawn"],["deles.","of-them."]]},
  {num:7,words:[["Traiçoeiramente","Treacherously"],["se","if"],["houveram","they-had"],["contra","against"],["o","the"],["Senhor,","Lord,"],["porque","because"],["geraram","they-begot"],["filhos","children"],["ilegítimos;","portions;"],["agora","now"],["a","to"],["lua","moon"],["nova","new"],["os","the"],["consumirá","devour"],["com","with"],["as","the"],["suas","his"],["porções.","portions."]]},
  {num:8,words:[["Tocai","Blow"],["a","to"],["buzina","trumpet"],["em","in"],["Gibeá,","Gibeah,"],["a","to"],["trombeta","trumpet"],["em","in"],["Ramá;","Ramah;"],["gritai","scream"],["altamente","highly"],["em","in"],["Bete-Áven;","Beth-Aven;"],["após","after"],["ti,","you,"],["Benjamim.","Benjamin."]]},
  {num:9,words:[["Efraim","Ephraim"],["será","will-be"],["uma","a"],["assolação","desolation"],["no","in-the"],["dia","day"],["do","of-the"],["castigo;","punishment;"],["entre","between"],["as","the"],["tribos","tribes"],["de","of"],["Israel","Israel"],["manifestei","I-demonstrated"],["o","the"],["que","that"],["certo","certain"],["está.","is."]]},
  {num:10,words:[["Os","The"],["príncipes","princes"],["de","of"],["Judá","Judah"],["são","they-are"],["como","as"],["os","the"],["que","that"],["mudam","they-vary"],["os","the"],["limites;","bounds;"],["derramarei,","pour,"],["pois,","for,"],["o","the"],["meu","my"],["furor","fury"],["sobre","upon"],["eles","they"],["como","as"],["água.","water."]]},
  {num:11,words:[["Efraim","Ephraim"],["está","is"],["oprimido","oppressed"],["e","and"],["quebrantado","contrite"],["no","in-the"],["juízo,","judgment,"],["porque","because"],["quis","willed"],["andar","walk"],["após","after"],["a","to"],["vaidade.","vanity."]]},
  {num:12,words:[["Portanto,","Therefore,"],["para","for"],["Efraim","Ephraim"],["serei","I-will-be"],["como","as"],["a","to"],["traça,","moth,"],["e","and"],["para","for"],["a","to"],["casa","house"],["de","of"],["Judá,","Judah,"],["como","as"],["a","to"],["podridão.","rottenness."]]},
  {num:13,words:[["Vendo,","Saw,"],["pois,","for,"],["Efraim","Ephraim"],["a","to"],["sua","his"],["enfermidade,","sickness,"],["e","and"],["Judá","Judah"],["a","to"],["sua","his"],["chaga,","wound,"],["subiu","climbed"],["Efraim","Ephraim"],["à","to-the"],["Assíria","Assyria"],["e","and"],["recorreu","calls"],["ao","to-the"],["rei","king"],["Jarebe;","Jareb;"],["mas","but"],["ele","he"],["não","no"],["poderá","will-can"],["sarar-vos,","cure-you,"],["nem","nor"],["vos","you"],["curará","will-cure"],["a","to"],["chaga.","wound."]]},
  {num:14,words:[["Porque","Because"],["para","for"],["Efraim","Ephraim"],["serei","I-will-be"],["como","as"],["um","a"],["leão,","lion,"],["e","and"],["como","as"],["um","a"],["leãozinho,","lion,"],["para","for"],["a","to"],["casa","house"],["de","of"],["Judá;","Judah;"],["eu,","I,"],["eu","I"],["mesmo","even"],["o","the"],["despedaçarei,","rescue,"],["e","and"],["ir-me-ei","to-ir-se"],["embora;","although;"],["eu","I"],["levarei,","I-will-carry,"],["e","and"],["não","no"],["haverá","will-have"],["quem","who"],["livre.","free."]]},
  {num:15,words:[["Andarei,","Unshod,"],["e","and"],["retornarei","I-will-recur"],["ao","to-the"],["meu","my"],["lugar,","place,"],["até que","until"],["se","if"],["reconheçam","they-acknowledge"],["culpados","guilty"],["e","and"],["busquem","they-seek"],["a","to"],["minha","my"],["face;","face;"],["estando","I-am"],["eles","they"],["angustiados,","troublous,"],["de","of"],["madrugada","early"],["me","me"],["buscarão.","they-will-seek."]]}
];
var v6 = [
  {num:1,words:[["Vinde,","Come,"],["e","and"],["retornemos","we-recur"],["ao","to-the"],["Senhor,","Lord,"],["porque","because"],["ele","he"],["despedaçou,","dodavah,"],["e","and"],["nos","us"],["sarará;","will-cure;"],["feriu,","smote,"],["e","and"],["nos","us"],["atará","will-bind"],["a","to"],["ferida.","wound."]]},
  {num:2,words:[["Depois","Afterwards"],["de","of"],["dois","two"],["dias","days"],["nos","us"],["dará","will-give"],["a","to"],["vida;","life;"],["ao","to-the"],["terceiro","third"],["dia","day"],["nos","us"],["ressuscitará,","scourge,"],["e","and"],["viveremos","we-will-live"],["diante","before"],["dele.","of-him."]]},
  {num:3,words:[["Então","Said"],["conheceremos,","we-will-know,"],["e","and"],["prosseguiremos","we-will-continue"],["em","in"],["conhecer","know"],["ao","to-the"],["Senhor;","Lord;"],["como","as"],["a","to"],["alva,","dawning,"],["é","is"],["certa","certain"],["a","to"],["sua","his"],["vinda;","coming;"],["e","and"],["ele","he"],["a","to"],["nós","we"],["virá","will-come"],["como","as"],["a","to"],["chuva,","rain,"],["como","as"],["chuva","rain"],["serôdia","mowings"],["que","that"],["rega","watereth"],["a","to"],["terra.","land."]]},
  {num:4,words:[["Que","That"],["te","you"],["farei,","I-will-make,"],["ó","O"],["Efraim?","Ephraim?"],["que","that"],["te","you"],["farei,","I-will-make,"],["ó","O"],["Judá?","Judah?"],["Visto que","seeing-that"],["a","to"],["vossa","your"],["benevolência","kindness"],["é","is"],["como","as"],["a","to"],["nuvem","cloud"],["da","of-the"],["manhã,","morning,"],["e","and"],["como","as"],["o","the"],["orvalho","dew"],["da","of-the"],["madrugada,","early,"],["que","that"],["passa.","passeth."]]},
  {num:5,words:[["Por isso","therefore"],["os","the"],["abati","I-butchered"],["por","by"],["meio","midst"],["dos","of-the"],["profetas;","prophets;"],["pelas","by-the"],["palavras","words"],["da","of-the"],["minha","my"],["boca","mouth"],["os","the"],["matei;","I-butchered;"],["e","and"],["os","the"],["teus","your"],["juízos","judgments"],["sairão","they-will-exit"],["como","as"],["a","to"],["luz.","light."]]},
  {num:6,words:[["Porque","Because"],["o","the"],["que","that"],["eu","I"],["quero","I-will"],["é","is"],["a","to"],["misericórdia,","mercy,"],["e","and"],["não","no"],["o","the"],["sacrifício;","sacrifice;"],["e","and"],["o","the"],["conhecimento","knowledge"],["de","of"],["Deus,","God,"],["mais","still"],["do","of-the"],["que","that"],["os","the"],["holocaustos.","burnt."]]},
  {num:7,words:[["Porém","But"],["eles","they"],["transgrediram","transgressed"],["o","the"],["convênio,","covenant,"],["como","as"],["Adão;","Adam;"],["ali","there"],["se","if"],["portaram","they-ported"],["traiçoeiramente","treacherously"],["contra","against"],["mim.","me."]]},
  {num:8,words:[["Gileade","Gilead"],["é","is"],["uma","a"],["cidade","city"],["dos","of-the"],["que","that"],["praticam","workers"],["iniquidade,","iniquity,"],["manchada","soil"],["de","of"],["sangue.","blood."]]},
  {num:9,words:[["Como","As"],["as","the"],["tropas","bands"],["dos","of-the"],["salteadores","thieves"],["a","to"],["alguns","some"],["esperam,","wait,"],["assim","thus"],["é","is"],["a","to"],["companhia","company"],["dos","of-the"],["sacerdotes;","priests;"],["matam","they-butcher"],["no","in-the"],["caminho","way"],["para","for"],["Siquém,","Shechem,"],["porque","because"],["cometem","oven"],["abominações.","abominations."]]},
  {num:10,words:[["Vejo","I-see"],["uma","a"],["coisa","thing"],["horrenda","horrible"],["na","in-the"],["casa","house"],["de","of"],["Israel;","Israel;"],["ali","there"],["está","is"],["a","to"],["prostituição","whoredom"],["de","of"],["Efraim;","Ephraim;"],["Israel","Israel"],["está","is"],["contaminado.","I-should-defile."]]},
  {num:11,words:[["Também","Also"],["para","for"],["ti,","you,"],["ó","O"],["Judá,","Judah,"],["foi","was"],["determinada","consumption"],["uma","a"],["ceifa;","harvest;"],["quando","when"],["eu","I"],["tornar","become"],["a","to"],["trazer","bring"],["os","the"],["cativos","captives"],["do","of-the"],["meu","my"],["povo.","people."]]}
];
var v7 = [
  {num:1,words:[["Quando","When"],["eu","I"],["quis","willed"],["sarar","cure"],["Israel,","Israel,"],["se","if"],["descobriu","uncovered"],["a","to"],["iniquidade","iniquity"],["de","of"],["Efraim,","Ephraim,"],["como","as"],["também","also"],["as","the"],["maldades","evils"],["de","of"],["Samaria,","Samaria,"],["porque","because"],["praticaram","they-practiced"],["a","to"],["falsidade;","falsehood;"],["e","and"],["o","the"],["ladrão","thief"],["entra,","entereth,"],["e","and"],["a","to"],["tropa","troop"],["dos","of-the"],["salteadores","thieves"],["despoja","spoil"],["por","by"],["fora.","outside."]]},
  {num:2,words:[["E","And"],["não","no"],["dizem","they-say"],["no","in-the"],["seu","his"],["coração","heart"],["que","that"],["eu","I"],["me","me"],["lembro","I-caution"],["de","of"],["toda","every"],["a","to"],["sua","his"],["maldade;","wickedness;"],["agora,","now,"],["pois,","for,"],["os","the"],["cercam","they-besiege"],["as","the"],["suas","his"],["obras;","works;"],["diante","before"],["da","of-the"],["minha","my"],["face","face"],["estão.","they-are."]]},
  {num:3,words:[["Com","With"],["a","to"],["sua","his"],["maldade","wickedness"],["alegram","feller"],["o","the"],["rei,","king,"],["e","and"],["com","with"],["as","the"],["suas","his"],["mentiras,","lies,"],["os","the"],["príncipes.","princes."]]},
  {num:4,words:[["Todos","All"],["eles","they"],["adulteram;","they-dilute;"],["semelhantes","like"],["são","they-are"],["ao","to-the"],["forno","oven"],["aceso","I-kindle"],["pelo","by-the"],["padeiro,","baker,"],["que","that"],["o","the"],["cessa","ceaseth"],["de","of"],["atiçar","agitate"],["depois que","after"],["amassou","creased"],["a","to"],["massa,","block,"],["até que","until"],["seja","is"],["levedada.","leavened."]]},
  {num:5,words:[["E","And"],["no","in-the"],["dia","day"],["do","of-the"],["nosso","our"],["rei","king"],["os","the"],["príncipes","princes"],["o","the"],["fazem","they-make"],["adoecer,","scorners,"],["pela","by-the"],["excitação","excitation"],["do","of-the"],["vinho;","wine;"],["ele","he"],["estende","stretches"],["a","to"],["sua","his"],["mão","hand"],["com","with"],["os","the"],["escarnecedores.","scorners."]]},
  {num:6,words:[["Porque,","Because,"],["como","as"],["um","a"],["forno,","oven,"],["prepararam","they-prepared"],["o","the"],["coração,","heart,"],["emboscando-se;","to-emboscar-se;"],["toda","every"],["a","to"],["noite","night"],["dorme","sleepeth"],["o","the"],["seu","his"],["padeiro,","baker,"],["pela","by-the"],["manhã","morning"],["arde","ard"],["como","as"],["fogo","fire"],["de","of"],["chama.","flame."]]},
  {num:7,words:[["Todos","All"],["juntos","together"],["se","if"],["esquentam","they-heat"],["como","as"],["o","the"],["forno,","oven,"],["e","and"],["consomem","rust"],["os","the"],["seus","his"],["juízes;","judges;"],["todos","all"],["os","the"],["seus","his"],["reis","kings"],["caem,","fadeth,"],["ninguém","none"],["entre","between"],["eles","they"],["há","has"],["que","that"],["clame","hosannas"],["a","to"],["mim.","me."]]},
  {num:8,words:[["Efraim","Ephraim"],["com","with"],["os","the"],["povos","nations"],["se","if"],["mistura;","admixture;"],["Efraim","Ephraim"],["é","is"],["um","a"],["bolo","cake"],["que","that"],["não","no"],["foi","was"],["virado.","I-should-turn."]]},
  {num:9,words:[["Estrangeiros","Strangers"],["lhe","to-him"],["devoraram","they-devoured"],["a","to"],["força,","strength,"],["e","and"],["não","no"],["o","the"],["sabe;","knows;"],["também","also"],["as","the"],["cãs","gray"],["se","if"],["espalharam","rephaim"],["sobre","upon"],["ele,","he,"],["e","and"],["não","no"],["o","the"],["sabe.","knows."]]},
  {num:10,words:[["E","And"],["a","to"],["soberba","pride"],["de","of"],["Israel","Israel"],["testificará","brown"],["no","in-the"],["seu","his"],["rosto;","face;"],["e","and"],["não","no"],["voltarão","they-will-return"],["para","for"],["o","the"],["Senhor","Lord"],["seu","his"],["Deus,","God,"],["nem","nor"],["o","the"],["buscarão","they-will-seek"],["em","in"],["tudo","whatsoever"],["isso.","that."]]},
  {num:11,words:[["Porque","Because"],["Efraim","Ephraim"],["é","is"],["como","as"],["uma","a"],["pomba","dove"],["ingênua,","naïf,"],["sem","without"],["entendimento;","understanding;"],["invocam","they-invoke"],["o","the"],["Egito,","Egypt,"],["vão","they-go"],["para","for"],["a","to"],["Assíria.","Assyria."]]},
  {num:12,words:[["Quando","When"],["forem,","they-will-be,"],["sobre","upon"],["eles","they"],["estenderei","stretch"],["a","to"],["minha","my"],["rede,","net,"],["e","and"],["como","as"],["aves","fowls"],["do","of-the"],["céu","heaven"],["os","the"],["farei","I-will-make"],["descer;","descend;"],["castigá-los-ei,","punish-the,"],["conforme","according-to"],["o","the"],["que","that"],["eles","they"],["ouviram","heard"],["na","in-the"],["sua","his"],["congregação.","congregation."]]},
  {num:13,words:[["Ai","Ouch"],["deles,","of-them,"],["porque","because"],["fugiram","fled"],["de","of"],["mim;","me;"],["destruição","destruction"],["sobre","upon"],["eles,","they,"],["porque","because"],["se","if"],["rebelaram","rebelled"],["contra","against"],["mim;","me;"],["eu","I"],["os","the"],["remiria,","should-shortened,"],["porém","but"],["falam","they-speak"],["mentiras","lies"],["contra","against"],["mim.","me."]]},
  {num:14,words:[["E","And"],["não","no"],["clamaram","cried"],["a","to"],["mim","me"],["do","of-the"],["seu","his"],["coração,","heart,"],["quando","when"],["davam","they-gave"],["uivos","howling"],["nas","in-the"],["suas","his"],["camas;","beds;"],["para","for"],["o","the"],["trigo","wheat"],["e","and"],["para","for"],["o","the"],["vinho","wine"],["se","if"],["ajuntam,","they-add,"],["mas","but"],["contra","against"],["mim","me"],["se","if"],["rebelam.","howled."]]},
  {num:15,words:[["Eu","I"],["os","the"],["adestrei,","I-coached,"],["e","and"],["lhes","to-them"],["fortaleci","sustained"],["os","the"],["braços,","arms,"],["mas","but"],["maquinam","imagine"],["o","the"],["mal","evil"],["contra","against"],["mim.","me."]]},
  {num:16,words:[["Retornaram,","Returned,"],["mas","but"],["não","no"],["ao","to-the"],["Altíssimo.","Most."],["Fizeram-se","They-became"],["como","as"],["um","a"],["arco","bow"],["enganoso;","deceptive;"],["caem","fadeth"],["à","to-the"],["espada","sword"],["os","the"],["seus","his"],["príncipes,","princes,"],["por","by"],["causa","sake"],["da","of-the"],["cólera","cholera"],["da","of-the"],["sua","his"],["língua;","tongue;"],["esse","that ... over there"],["será","will-be"],["o","the"],["seu","his"],["escárnio","derision"],["na","in-the"],["terra do","egypt"],["Egito.","Egypt."]]}
];
var v8 = [
  {num:1,words:[["Põe","Places"],["a","to"],["buzina","trumpet"],["à","to-the"],["tua","your"],["boca;","mouth;"],["ele","he"],["vem","comes"],["como","as"],["a","to"],["águia","eagle"],["contra","against"],["a","to"],["casa","house"],["do","of-the"],["Senhor,","Lord,"],["porque","because"],["transgrediram","transgressed"],["o","the"],["meu","my"],["convênio,","covenant,"],["e","and"],["se","if"],["rebelaram","rebelled"],["contra","against"],["a","to"],["minha","my"],["lei.","law."]]},
  {num:2,words:[["Então","Said"],["a","to"],["mim","me"],["clamarão:","simpleness:"],["Deus","God"],["meu!","my!"],["Nós,","We,"],["Israel,","Israel,"],["te","you"],["conhecemos.","hereby."]]},
  {num:3,words:[["Israel","Israel"],["rejeitou","rejected"],["o","the"],["bem;","good;"],["o","the"],["inimigo","enemy"],["persegui-lo-á.","pursue."]]},
  {num:4,words:[["Eles","They"],["fizeram","they-made"],["reis,","kings,"],["porém","but"],["não","no"],["de","of"],["mim;","me;"],["constituíram","they-constituted"],["príncipes,","princes,"],["porém","but"],["eu","I"],["não","no"],["o","the"],["soube;","knew;"],["da","of-the"],["sua","his"],["prata","silver"],["e","and"],["do","of-the"],["seu","his"],["ouro","gold"],["fizeram","they-made"],["ídolos","idols"],["para","for"],["si,","himself,"],["para","for"],["serem","to-be"],["destruídos.","destroyed."]]},
  {num:5,words:[["O","The"],["teu","your"],["bezerro,","calf,"],["ó","O"],["Samaria,","Samaria,"],["te","you"],["rejeitou;","rejected;"],["a","to"],["minha","my"],["ira","anger"],["se","if"],["acendeu","kindled"],["contra","against"],["eles;","they;"],["até","until"],["quando","when"],["serão","they-will-be"],["eles","they"],["incapazes","impotent"],["de","of"],["alcançar","accomplish"],["a","to"],["purificação?","distillation?"]]},
  {num:6,words:[["Porque","Because"],["também","also"],["isso","that"],["é","is"],["de","of"],["Israel,","Israel,"],["um","a"],["artífice","workman"],["o","the"],["fez,","made,"],["e","and"],["não","no"],["é","is"],["Deus,","God,"],["mas","but"],["em","in"],["pedaços","pieces"],["será","will-be"],["desfeito","undone"],["o","the"],["bezerro","calf"],["de","of"],["Samaria.","Samaria."]]},
  {num:7,words:[["Porque","Because"],["vento","wind"],["semearam,","they-sowed,"],["e","and"],["ceifarão","they-will-cut"],["tormenta,","torment,"],["seara","labourers"],["não","no"],["haverá,","will-have,"],["a","to"],["erva","grass"],["não","no"],["dará","will-give"],["farinha;","flour;"],["se","if"],["a","to"],["der,","will-give,"],["tragá-la-ão","swallow-the"],["os","the"],["estrangeiros.","strangers."]]},
  {num:8,words:[["Israel","Israel"],["foi","was"],["tragado;","I-should-swallow;"],["agora","now"],["entre","between"],["as","the"],["nações","nations"],["será","will-be"],["tido","I-should-have"],["como","as"],["um","a"],["vaso","vessel"],["em","in"],["que","that"],["ninguém","none"],["tem","has"],["prazer.","pleasure."]]},
  {num:9,words:[["Porque","Because"],["subiram","they-climbed"],["à","to-the"],["Assíria,","Assyria,"],["como","as"],["um","a"],["jumento","ass"],["montês,","deer,"],["por","by"],["si","himself"],["só;","exclusively;"],["Efraim","Ephraim"],["contratou","employed"],["amantes.","lovers."]]},
  {num:10,words:[["Ainda que","although"],["eles","they"],["contratem","they-employ"],["entre","between"],["as","the"],["nações,","nations,"],["agora","now"],["as","the"],["congregarei;","halteth;"],["já","already"],["começaram","began"],["a","to"],["ser","be"],["diminuídos","diminished"],["por","by"],["causa","sake"],["da","of-the"],["carga","burden"],["do rei","king's"],["dos","of-the"],["príncipes.","princes."]]},
  {num:11,words:[["Porquanto","Because"],["Efraim","Ephraim"],["multiplicou","multiplied"],["os","the"],["altares","altars"],["para","for"],["pecar;","sin;"],["teve","had"],["altares","altars"],["para","for"],["pecar.","sin."]]},
  {num:12,words:[["Escrevi-lhe","I-wrote-to-him"],["as","the"],["grandezas","cretes"],["da","of-the"],["minha","my"],["lei,","law,"],["porém","but"],["essas","those"],["são","they-are"],["estimadas","esteem"],["como","as"],["coisa","thing"],["estranha.","strange."]]},
  {num:13,words:[["Quanto","As"],["aos","to-the"],["sacrifícios","sacrifices"],["das","of-the"],["minhas","my"],["ofertas,","offerings,"],["sacrificam","spouses"],["carne,","flesh,"],["e","and"],["a","to"],["comem,","they-eat,"],["mas","but"],["o","the"],["Senhor","Lord"],["não","no"],["se","if"],["deleitou","accepteth"],["neles;","therein;"],["agora","now"],["se","if"],["lembrará","will-caution"],["da","of-the"],["sua","his"],["injustiça,","injustice,"],["e","and"],["castigará","will-punish"],["os","the"],["seus","his"],["pecados;","sins;"],["eles","they"],["voltarão","they-will-return"],["para","for"],["o","the"],["Egito.","Egypt."]]},
  {num:14,words:[["Porque","Because"],["Israel","Israel"],["se","if"],["esqueceu","attire"],["do","of-the"],["seu","his"],["Criador,","Creator,"],["e","and"],["edificou","built"],["templos,","temples,"],["e","and"],["Judá","Judah"],["multiplicou","multiplied"],["cidades","cities"],["fortificadas;","fenced;"],["mas","but"],["eu","I"],["enviarei","send"],["um","a"],["fogo","fire"],["contra","against"],["as","the"],["suas","his"],["cidades,","cities,"],["que","that"],["consumirá","devour"],["os","the"],["seus","his"],["palácios.","palaces."]]}
];
var v9 = [
  {num:1,words:[["Não","No"],["te","you"],["alegres,","you-gladden,"],["ó","O"],["Israel,","Israel,"],["não","no"],["exultes,","cornfloor,"],["como","as"],["os","the"],["povos;","nations;"],["porque","because"],["pela","by-the"],["prostituição","whoredom"],["abandonaste","you-zemnarihah"],["o","the"],["teu","your"],["Deus;","God;"],["amaste","you-mammon"],["a","to"],["paga","pays"],["de","of"],["meretriz","harlot"],["sobre","upon"],["todas","things"],["as","the"],["eiras","threshingfloors"],["de","of"],["trigo.","wheat."]]},
  {num:2,words:[["A","To"],["eira","threshingfloor"],["e","and"],["o","the"],["lagar","winepress"],["não","no"],["os","the"],["alimentarão;","they-will-feed;"],["e","and"],["o","the"],["mosto","corn"],["lhe","to-him"],["faltará.","will-wanting."]]},
  {num:3,words:[["Na","In-the"],["terra do","egypt"],["Senhor","Lord"],["não","no"],["permanecerão;","molest;"],["mas","but"],["Efraim","Ephraim"],["retornará","will-recur"],["ao","to-the"],["Egito,","Egypt,"],["e","and"],["na","in-the"],["Assíria","Assyria"],["comerão","they-will-eat"],["coisas","things"],["imundas.","roofs."]]},
  {num:4,words:[["Não","No"],["derramarão","they-will-pour"],["libações","offerings"],["de","of"],["vinho","wine"],["ao","to-the"],["Senhor,","Lord,"],["nem","nor"],["lhe","to-him"],["serão","they-will-be"],["agradáveis;","pleasing;"],["os","the"],["seus","his"],["sacrifícios","sacrifices"],["lhes","to-them"],["serão","they-will-be"],["como","as"],["pão","bread"],["de","of"],["pranto;","mourning;"],["todos","all"],["os","the"],["que","that"],["dele","of-him"],["comerem","they-will-eat"],["serão","they-will-be"],["imundos,","unclean,"],["porque","because"],["o","the"],["seu","his"],["pão","bread"],["será","will-be"],["para","for"],["eles","they"],["mesmos;","even;"],["não","no"],["entrará","enter"],["na","in-the"],["casa","house"],["do","of-the"],["Senhor.","Lord."]]},
  {num:5,words:[["Que","That"],["fareis","you-will-make"],["vós","you"],["no","in-the"],["dia","day"],["da","of-the"],["solenidade,","solemnity,"],["e","and"],["no","in-the"],["dia","day"],["da","of-the"],["festa","feast"],["do","of-the"],["Senhor?","Lord?"]]},
  {num:6,words:[["Porque","Because"],["eis que","behold"],["eles","they"],["se","if"],["foram","they-were"],["por","by"],["causa","sake"],["da","of-the"],["destruição;","destruction;"],["o","the"],["Egito","Egypt"],["os","the"],["recolherá,","will-clauda,"],["Mênfis","Noph"],["os","the"],["sepultará;","will-bury;"],["o","the"],["desejável","desirable"],["da","of-the"],["sua","his"],["prata,","silver,"],["as","the"],["urtigas","nettles"],["o","the"],["possuirão","they-will-possess"],["por","by"],["herança;","inheritance;"],["espinhos","thorns"],["haverá","will-have"],["nas","in-the"],["suas","his"],["tendas.","tents."]]},
  {num:7,words:[["Já","Already"],["chegaram","they-came"],["os","the"],["dias","days"],["do","of-the"],["castigo,","punishment,"],["já","already"],["chegaram","they-came"],["os","the"],["dias","days"],["da","of-the"],["retribuição;","recompence;"],["os","the"],["de","of"],["Israel","Israel"],["o","the"],["saberão;","they-will-know;"],["o","the"],["profeta","prophet"],["é","is"],["tolo,","foolish,"],["o","the"],["homem","man"],["de","of"],["espírito","spirit"],["é","is"],["louco;","mad;"],["por","by"],["causa","sake"],["da","of-the"],["abundância","abundance"],["da","of-the"],["tua","your"],["iniquidade","iniquity"],["também","also"],["abundará","will-abound"],["o","the"],["ódio.","hatred."]]},
  {num:8,words:[["Efraim","Ephraim"],["era","was"],["o","the"],["vigia","watcher"],["com","with"],["o","the"],["meu","my"],["Deus,","God,"],["mas","but"],["o","the"],["profeta","prophet"],["é","is"],["como","as"],["um","a"],["laço","snare"],["de","of"],["caçador","hunter"],["de","of"],["aves","fowls"],["em","in"],["todos","all"],["os","the"],["seus","his"],["caminhos,","ways,"],["ódio","hatred"],["na","in-the"],["casa","house"],["do","of-the"],["seu","his"],["Deus.","God."]]},
  {num:9,words:[["Muito","Much"],["profundamente","deeply"],["se","if"],["corromperam,","they-bribed,"],["como","as"],["nos","us"],["dias","days"],["de","of"],["Gibeá;","Gibeah;"],["ele","he"],["se","if"],["lembrará","will-caution"],["das","of-the"],["injustiças","insult"],["deles,","of-them,"],["castigará","will-punish"],["os","the"],["seus","his"],["pecados.","sins."]]},
  {num:10,words:[["Achei","I-found"],["Israel","Israel"],["como","as"],["uvas","grapes"],["no","in-the"],["deserto,","desert,"],["vi","I-saw"],["vossos","your"],["pais","parents"],["como","as"],["a","to"],["fruta","fruit"],["temporã","moderately"],["da","of-the"],["figueira","fig"],["no","in-the"],["seu","his"],["princípio;","beginning;"],["porém","but"],["foram","they-were"],["a","to"],["Baal-Peor,","Baal-Peor,"],["e","and"],["se","if"],["apartaram","they-divided"],["para","for"],["essa","that ... over there"],["vergonha,","shame,"],["e","and"],["se","if"],["tornaram","they-became"],["abomináveis","you-abhorred"],["como","as"],["aquilo","that"],["que","that"],["amaram.","they-mammon."]]},
  {num:11,words:[["Quanto","As"],["a","to"],["Efraim,","Ephraim,"],["a","to"],["sua","his"],["glória","glory"],["como","as"],["ave","bird"],["voará","will-fly"],["desde o","beginning"],["nascimento,","birth,"],["e","and"],["desde o","beginning"],["ventre,","abdomen,"],["e","and"],["desde","since"],["a","to"],["concepção.","conception."]]},
  {num:12,words:[["Ainda que","although"],["venham","they-come"],["a","to"],["criar","appertain"],["seus","his"],["filhos,","children,"],["contudo","yet"],["os","the"],["privarei","bereave"],["deles","of-them"],["dentre","from"],["os","the"],["homens;","men;"],["porque","because"],["também","also"],["ai","ouch"],["deles,","of-them,"],["quando","when"],["me","me"],["apartar","divide"],["deles!","of-them!"]]},
  {num:13,words:[["Efraim,","Ephraim,"],["assim como","even-as"],["vi","I-saw"],["Tiro,","Tyre,"],["plantada","planted"],["está","is"],["num","in-a"],["lugar","place"],["deleitoso;","collectivelyful;"],["mas","but"],["Efraim","Ephraim"],["tirará","will-deduct"],["para","for"],["fora","outside"],["seus","his"],["filhos","children"],["para","for"],["o","the"],["matador.","killer."]]},
  {num:14,words:[["Dá-lhes,","Cupbearer,"],["ó","O"],["Senhor;","Lord;"],["que,","that,"],["pois,","for,"],["lhes","to-them"],["darás?","you-will-give?"],["Dá-lhes","Cupbearer"],["uma","a"],["madre","womb"],["que","that"],["aborte","aborts"],["e","and"],["seios","breasts"],["secos.","dry."]]},
  {num:15,words:[["Toda","Every"],["a","to"],["sua","his"],["maldade","wickedness"],["se","if"],["acha","findeth"],["em","in"],["Gilgal,","Gilgal,"],["porque","because"],["ali","there"],["os","the"],["odiei","I-hated"],["pela","by-the"],["maldade","wickedness"],["das","of-the"],["suas","his"],["obras;","works;"],["lançá-los-ei","I-will-vomit-the"],["para","for"],["fora de","outside"],["minha","my"],["casa;","house;"],["não","no"],["os","the"],["amarei","revolters"],["mais;","still;"],["todos","all"],["os","the"],["seus","his"],["príncipes","princes"],["são","they-are"],["rebeldes.","rebellious."]]},
  {num:16,words:[["Efraim","Ephraim"],["foi","was"],["ferido,","wounded,"],["secou-se","scorched"],["a","to"],["sua","his"],["raiz;","root;"],["não","no"],["darão","they-will-give"],["fruto;","fruit;"],["e","and"],["ainda que","although"],["gerem,","they-beget,"],["todavia","nevertheless"],["matarei","I-will-butcher"],["os","the"],["desejáveis","you-desired"],["do","of-the"],["seu","his"],["ventre.","abdomen."]]},
  {num:17,words:[["O","The"],["meu","my"],["Deus","God"],["os","the"],["rejeitará,","will-reject,"],["porque","because"],["não","no"],["o","the"],["ouvem,","they-hear,"],["e","and"],["errantes","erratic"],["andarão","fatling"],["entre","between"],["as","the"],["nações.","nations."]]}
];
var v10 = [
  {num:1,words:[["Israel","Israel"],["é","is"],["uma","a"],["vide","vine"],["vazia;","empty;"],["dá","gives"],["fruto","fruit"],["para","for"],["si","himself"],["mesmo;","even;"],["segundo","according-to"],["a","to"],["multidão","multitude"],["do","of-the"],["seu","his"],["fruto,","fruit,"],["multiplicou","multiplied"],["os","the"],["altares;","altars;"],["segundo","according-to"],["a","to"],["bondade","goodness"],["da","of-the"],["sua","his"],["terra,","land,"],["fizeram","they-made"],["belas","beautiful"],["as","the"],["estátuas.","statue."]]},
  {num:2,words:[["Lisonjeia-os","Flattereth-the"],["o","the"],["seu","his"],["coração,","heart,"],["agora","now"],["serão","they-will-be"],["culpados;","guilty;"],["cortará","will-hew"],["os","the"],["seus","his"],["altares,","altars,"],["e","and"],["destruirá","destroy"],["as","the"],["suas","his"],["estátuas.","statue."]]},
  {num:3,words:[["Porque","Because"],["agora","now"],["dirão:","they-will-say:"],["Não","No"],["temos","we-have"],["rei,","king,"],["porque","because"],["não","no"],["tememos","faction"],["ao","to-the"],["Senhor;","Lord;"],["que,","that,"],["pois,","for,"],["nos","us"],["faria","should-make"],["o","the"],["rei?","king?"]]},
  {num:4,words:[["Falaram","They-spoke"],["palavras,","words,"],["jurando","I-swear"],["falsamente,","falsely,"],["ao","to-the"],["fazerem","to-make"],["um","a"],["convênio;","covenant;"],["e","and"],["florescerá","blossom"],["o","the"],["juízo","judgment"],["como","as"],["erva","grass"],["peçonhenta","hemlock"],["nos","us"],["sulcos","furrows"],["dos","of-the"],["campos.","fields."]]},
  {num:5,words:[["Os","The"],["moradores","inhabitants"],["de","of"],["Samaria","Samaria"],["serão","they-will-be"],["atemorizados","affrighted"],["pelo","by-the"],["bezerro","calf"],["de","of"],["Bete-Áven,","Beth-Aven,"],["porque","because"],["o","the"],["seu","his"],["povo","people"],["lamentará","will-regret"],["por","by"],["causa","sake"],["dele,","of-him,"],["como","as"],["também","also"],["os","the"],["seus","his"],["sacerdotes","priests"],["(que","(that"],["por","by"],["causa","sake"],["dele","of-him"],["se","if"],["alegravam),","they-gladdened),"],["por","by"],["causa","sake"],["da","of-the"],["sua","his"],["glória,","glory,"],["que","that"],["se","if"],["apartou","nebat"],["dela.","of-it."]]},
  {num:6,words:[["Também","Also"],["a","to"],["Assíria","Assyria"],["será","will-be"],["levada","parties"],["como","as"],["um","a"],["presente","present"],["ao","to-the"],["rei","king"],["Jarebe;","Jareb;"],["Efraim","Ephraim"],["ficará","will-remain"],["confuso,","jumbled up,"],["e","and"],["Israel","Israel"],["se","if"],["envergonhará","will-abash"],["por","by"],["causa","sake"],["do","of-the"],["seu","his"],["conselho.","counsel."]]},
  {num:7,words:[["O","The"],["rei","king"],["de","of"],["Samaria","Samaria"],["será","will-be"],["cortado","I-should-hew"],["como","as"],["a","to"],["espuma","foam"],["sobre","upon"],["a","to"],["face","face"],["da","of-the"],["água.","water."]]},
  {num:8,words:[["E","And"],["os","the"],["altos","places"],["de","of"],["Áven,","Aven,"],["pecado","sin"],["de","of"],["Israel,","Israel,"],["serão","they-will-be"],["destruídos;","destroyed;"],["espinhos","thorns"],["e","and"],["cardos","thistles"],["crescerão","they-will-grow"],["sobre","upon"],["os","the"],["seus","his"],["altares;","altars;"],["e","and"],["dirão","they-will-say"],["aos","to-the"],["montes:","mountains:"],["Cobri-nos!","I-covered-us!"],["E","And"],["aos","to-the"],["outeiros:","hills:"],["Caí","I-fell"],["sobre","upon"],["nós!","we!"]]},
  {num:9,words:[["Desde","Since"],["os","the"],["dias","days"],["de","of"],["Gibeá","Gibeah"],["pecaste,","you-sinned,"],["ó","O"],["Israel;","Israel;"],["ali","there"],["pararam;","they-halt;"],["a","to"],["peleja","battle"],["em","in"],["Gibeá","Gibeah"],["contra","against"],["os","the"],["filhos","children"],["da","of-the"],["perversidade","maliciousity"],["não","no"],["os","the"],["acometerá.","will-assault."]]},
  {num:10,words:[["Eu","I"],["os","the"],["castigarei","punish"],["na","in-the"],["medida","measure"],["do","of-the"],["meu","my"],["desejo;","desire;"],["e","and"],["congregar-se-ão","furrows"],["contra","against"],["eles","they"],["os","the"],["povos,","nations,"],["quando","when"],["os","the"],["atar","bind"],["nos","us"],["seus","his"],["dois","two"],["sulcos.","furrows."]]},
  {num:11,words:[["Porque","Because"],["Efraim","Ephraim"],["é","is"],["uma","a"],["bezerra","heifer"],["domada,","tame,"],["que","that"],["gosta","esteems"],["de","of"],["trilhar;","thresh;"],["coloquei","governing"],["o","the"],["jugo","yoke"],["sobre","upon"],["a","to"],["formosura","beauty"],["do","of-the"],["seu","his"],["pescoço;","neck;"],["farei","I-will-make"],["cavalgar","ride"],["Efraim;","Ephraim;"],["Judá","Judah"],["lavrará;","will-embroider;"],["Jacó","Jacob"],["lhe","to-him"],["desfará","will-disrupt"],["os","the"],["torrões.","clods."]]},
  {num:12,words:[["Semeai","Sow"],["para","for"],["vós","you"],["em","in"],["justiça,","righteousness,"],["ceifai","springeth"],["segundo","according-to"],["a","to"],["benevolência,","kindness,"],["e","and"],["lavrai","embroider"],["o","the"],["campo","field"],["de","of"],["lavoura;","tillage;"],["porque","because"],["o","the"],["tempo","time"],["é","is"],["de","of"],["buscar","seek"],["ao","to-the"],["Senhor,","Lord,"],["até que","until"],["venha","comes"],["e","and"],["chova","rains"],["a","to"],["justiça","righteousness"],["sobre","upon"],["vós.","you."]]},
  {num:13,words:[["Lavrastes","You-embroidered"],["a","to"],["impiedade,","wickedness,"],["ceifastes","you-cut"],["a","to"],["perversidade,","maliciousity,"],["e","and"],["comestes","you-ate"],["o","the"],["fruto","fruit"],["da","of-the"],["mentira;","lie;"],["porque","because"],["confiaste","you-confided"],["no","in-the"],["teu","your"],["caminho,","way,"],["na","in-the"],["multidão","multitude"],["dos","of-the"],["teus","your"],["valentes.","brave."]]},
  {num:14,words:[["Portanto,","Therefore,"],["entre","between"],["os","the"],["seus","his"],["povos","nations"],["se","if"],["levantará","will-hoist"],["um","a"],["grande","great"],["tumulto,","tumult,"],["e","and"],["todas","things"],["as","the"],["tuas","your"],["fortalezas","fortification"],["serão","they-will-be"],["destruídas,","ruined,"],["como","as"],["Salmã","Shalman"],["destruiu","destroyed"],["Bete-Arbel","Shalman"],["no","in-the"],["dia","day"],["da","of-the"],["guerra;","war;"],["a","to"],["mãe","mother"],["ali","there"],["foi","was"],["despedaçada","torn"],["com","with"],["os","the"],["filhos.","children."]]},
  {num:15,words:[["Assim","Thus"],["vos","you"],["fará","will-make"],["Betel,","Beth-El,"],["por","by"],["causa","sake"],["da","of-the"],["vossa","your"],["imensa","enormous"],["maldade;","wickedness;"],["o","the"],["rei","king"],["de","of"],["Israel","Israel"],["de","of"],["madrugada","early"],["será","will-be"],["totalmente","utterly"],["destruído.","destroyed."]]}
];
var v11 = [
  {num:1,words:[["Quando","When"],["Israel","Israel"],["era","was"],["menino,","boy,"],["eu","I"],["o","the"],["amei;","loved;"],["e","and"],["do","of-the"],["Egito","Egypt"],["chamei","I-called"],["meu","my"],["filho.","son."]]},
  {num:2,words:[["Quanto","As"],["mais","still"],["os","the"],["chamavam,","they-called,"],["mais","still"],["se","if"],["afastavam","they-eliminated"],["da","of-the"],["sua","his"],["presença;","presence;"],["sacrificavam","sacrificed"],["a","to"],["baalins,","baalim,"],["e","and"],["queimavam","they-burnt"],["incenso","incense"],["às","to-the"],["imagens","images"],["de","of"],["escultura.","graven."]]},
  {num:3,words:[["Eu,","I,"],["todavia,","nevertheless,"],["ensinei","I-taught"],["Efraim","Ephraim"],["a","to"],["andar;","walk;"],["tomei-os","I-got-the"],["pelos","by-the"],["seus","his"],["braços,","arms,"],["mas","but"],["não","no"],["reconheceram","they-acknowledged"],["que","that"],["eu","I"],["os","the"],["curava.","cured."]]},
  {num:4,words:[["Atraí-os","I-attracted-the"],["com","with"],["cordas","cords"],["humanas,","human,"],["com","with"],["laços","snares"],["de","of"],["amor,","love,"],["e","and"],["fui","I-was"],["para","for"],["eles","they"],["como","as"],["os","the"],["que","that"],["levantam","they-hoist"],["o","the"],["jugo","yoke"],["de","of"],["sobre","upon"],["as","the"],["suas","his"],["queixadas,","jawbone,"],["e","and"],["lhes","to-them"],["dei","I-gave"],["mantimento.","food."]]},
  {num:5,words:[["Não","No"],["voltará","will-return"],["para","for"],["a","to"],["terra do","egypt"],["Egito,","Egypt,"],["mas","but"],["a","to"],["Assíria","Assyria"],["será","will-be"],["seu","his"],["rei;","king;"],["porque","because"],["recusam","robbery"],["converter-se.","convert-himself."]]},
  {num:6,words:[["E","And"],["ficará","will-remain"],["a","to"],["espada","sword"],["sobre","upon"],["as","the"],["suas","his"],["cidades,","cities,"],["e","and"],["consumirá","devour"],["os","the"],["seus","his"],["ferrolhos,","bars,"],["e","and"],["as","the"],["devorará,","thickets,"],["por","by"],["causa","sake"],["dos","of-the"],["seus","his"],["conselhos.","counsels."]]},
  {num:7,words:[["Porque","Because"],["o","the"],["meu","my"],["povo","people"],["se","if"],["inclina","incline"],["a","to"],["desviar-se","meddling"],["de","of"],["mim;","me;"],["ainda que","although"],["chamem","they-call"],["ao","to-the"],["Altíssimo,","Most,"],["nenhum","none"],["deles","of-them"],["o","the"],["exalta.","exalteth."]]},
  {num:8,words:[["Como","As"],["te","you"],["deixaria,","promoted,"],["ó","O"],["Efraim?","Ephraim?"],["Como","As"],["te","you"],["entregaria,","should-betray,"],["ó","O"],["Israel?","Israel?"],["Como","As"],["te","you"],["faria","should-make"],["como","as"],["Admá?","Admah?"],["Te","You"],["poria","should-place"],["como","as"],["Zeboim?","Zeboim?"],["Virou-se","Repentings"],["em","in"],["mim","me"],["o","the"],["meu","my"],["coração,","heart,"],["todos","all"],["os","the"],["meus","my"],["pesares","you-will-affliction"],["juntamente","together"],["estão","they-are"],["acendidos.","I-should-kindle."]]},
  {num:9,words:[["Não","No"],["executarei","execute"],["o","the"],["furor","fury"],["da","of-the"],["minha","my"],["ira;","anger;"],["não","no"],["retornarei","I-will-recur"],["para","for"],["destruir","destroy"],["Efraim,","Ephraim,"],["porque","because"],["eu","I"],["sou","I-am"],["Deus","God"],["e","and"],["não","no"],["homem,","man,"],["o","the"],["Santo","Holy"],["no","in-the"],["meio","midst"],["de","of"],["ti,","you,"],["e","and"],["não","no"],["entrarei","I-will-enter"],["na","in-the"],["cidade.","city."]]},
  {num:10,words:[["Andarão","Fatling"],["após","after"],["o","the"],["Senhor,","Lord,"],["ele","he"],["bramará","roar"],["como","as"],["leão;","lion;"],["bramando","vigilant"],["ele,","he,"],["os","the"],["filhos","children"],["do","of-the"],["ocidente","west"],["tremerão.","they-will-tremble."]]},
  {num:11,words:[["Tremendo,","Trembling,"],["se","if"],["achegarão","stroke"],["como","as"],["um","a"],["passarinho","little bird"],["os","the"],["do","of-the"],["Egito,","Egypt,"],["e","and"],["como","as"],["uma","a"],["pomba,","dove,"],["os","the"],["da","of-the"],["terra","land"],["da","of-the"],["Assíria,","Assyria,"],["e","and"],["os","the"],["farei","I-will-make"],["habitar","dwell"],["em","in"],["suas","his"],["casas,","houses,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:12,words:[["Efraim","Ephraim"],["me","me"],["cercou","besieged"],["com","with"],["mentira,","lie,"],["e","and"],["a","to"],["casa","house"],["de","of"],["Israel,","Israel,"],["com","with"],["engano;","deceit;"],["mas","but"],["Judá","Judah"],["ainda","yet"],["anda","walketh"],["com","with"],["Deus,","God,"],["e","and"],["com","with"],["os","the"],["santos","Seneca"],["está","is"],["fiel.","faithful."]]}
];
var v12 = [
  {num:1,words:[["Efraim","Ephraim"],["se","if"],["apascenta","feedeth"],["de","of"],["vento,","wind,"],["e","and"],["segue","followeth"],["o","the"],["vento","wind"],["leste;","east;"],["todo","every"],["o","the"],["dia","day"],["multiplica","increaseth"],["a","to"],["mentira","lie"],["e","and"],["a","to"],["destruição;","destruction;"],["e","and"],["fazem","they-make"],["aliança","alliance"],["com","with"],["a","to"],["Assíria,","Assyria,"],["e","and"],["o","the"],["azeite","oil"],["se","if"],["leva","leadeth"],["ao","to-the"],["Egito.","Egypt."]]},
  {num:2,words:[["O","The"],["Senhor","Lord"],["também","also"],["com","with"],["Judá","Judah"],["tem","has"],["contenda,","strife,"],["e","and"],["castigará","will-punish"],["Jacó","Jacob"],["segundo","according-to"],["os","the"],["seus","his"],["caminhos;","ways;"],["segundo as suas","families"],["obras","works"],["lhe","to-him"],["recompensará.","will-compensate."]]},
  {num:3,words:[["No","In-the"],["ventre","abdomen"],["pegou","caught"],["no","in-the"],["calcanhar","heel"],["de","of"],["seu","his"],["irmão,","brother,"],["e","and"],["pela","by-the"],["sua","his"],["força","strength"],["como","as"],["príncipe","prince"],["lutou","contended"],["com","with"],["Deus.","God."]]},
  {num:4,words:[["Como","As"],["príncipe","prince"],["lutou","contended"],["com","with"],["o","the"],["anjo,","angel,"],["e","and"],["prevaleceu;","prevailed;"],["chorou,","wept,"],["e","and"],["lhe","to-him"],["suplicou;","besought;"],["em","in"],["Betel","Beth-El"],["o","the"],["achou,","found,"],["e","and"],["ali","there"],["falou","spake"],["conosco,","with-us,"]]},
  {num:5,words:[["A saber,","namely"],["o","the"],["Senhor,","Lord,"],["o","the"],["Deus","God"],["dos","of-the"],["Exércitos;","Hosts;"],["o","the"],["Senhor","Lord"],["é","is"],["o","the"],["seu","his"],["memorial.","memorial."]]},
  {num:6,words:[["Tu,","You,"],["pois,","for,"],["converte-te","converts-you"],["ao","to-the"],["teu","your"],["Deus;","God;"],["guarda","guard"],["a","to"],["benevolência","kindness"],["e","and"],["o","the"],["juízo,","judgment,"],["e","and"],["em","in"],["teu","your"],["Deus","God"],["espera","waiteth"],["sempre.","always."]]},
  {num:7,words:[["Na","In-the"],["mão","hand"],["do","of-the"],["mercador","trader"],["está","is"],["uma","a"],["balança","balances"],["enganosa;","deceitful;"],["ele","he"],["ama","loveth"],["a","to"],["opressão.","oppression."]]},
  {num:8,words:[["Ainda","Yet"],["diz","says"],["Efraim:","Ephraim:"],["Contudo","Yet"],["eu","I"],["estou","I-am"],["enriquecido,","I-should-enrich,"],["e","and"],["tenho","I-have"],["adquirido","acquired"],["para","for"],["mim","me"],["grandes","great"],["bens;","good;"],["em","in"],["todo","every"],["o","the"],["meu","my"],["trabalho","work"],["não","no"],["acharão","they-will-find"],["em","in"],["mim","me"],["iniquidade","iniquity"],["alguma","any"],["que","that"],["seja","is"],["pecado.","sin."]]},
  {num:9,words:[["Mas","But"],["eu","I"],["sou","I-am"],["o","the"],["Senhor","Lord"],["teu","your"],["Deus","God"],["desde","since"],["a","to"],["terra do","egypt"],["Egito;","Egypt;"],["eu","I"],["ainda","yet"],["te","you"],["farei","I-will-make"],["habitar","dwell"],["em","in"],["tendas,","tents,"],["como","as"],["nos","us"],["dias","days"],["da","of-the"],["festa","feast"],["solene.","solemn."]]},
  {num:10,words:[["E","And"],["falarei","talk"],["aos","to-the"],["profetas,","prophets,"],["e","and"],["multiplicarei","multiply"],["a","to"],["visão;","vision;"],["e","and"],["pelo","by-the"],["ministério","ministry"],["dos","of-the"],["profetas","prophets"],["proporei","I-will-propose"],["símiles.","analogy."]]},
  {num:11,words:[["Porventura","Perchance"],["não","no"],["é","is"],["Gileade","Gilead"],["iniquidade?","iniquity?"],["Pura","Pure"],["vaidade","vanity"],["são;","they-are;"],["em","in"],["Gilgal","Gilgal"],["sacrificam","spouses"],["bois;","oxen;"],["os","the"],["seus","his"],["altares","altars"],["são","they-are"],["como","as"],["montões","heaps"],["de","of"],["pedras","stones"],["nos","us"],["sulcos","furrows"],["dos","of-the"],["campos.","fields."]]},
  {num:12,words:[["Jacó","Jacob"],["fugiu","fled"],["para","for"],["o","the"],["campo","field"],["da","of-the"],["Síria,","Syria,"],["e","and"],["Israel","Israel"],["serviu","served"],["por","by"],["sua","his"],["mulher,","dame,"],["e","and"],["por","by"],["sua","his"],["mulher","dame"],["guardou","kept"],["o","the"],["gado.","cattle."]]},
  {num:13,words:[["Mas","But"],["o","the"],["Senhor","Lord"],["por","by"],["um","a"],["profeta","prophet"],["fez","made"],["subir","climb"],["Israel","Israel"],["do","of-the"],["Egito,","Egypt,"],["e","and"],["por","by"],["um","a"],["profeta","prophet"],["foi","was"],["ele","he"],["guardado.","I-should-keep."]]},
  {num:14,words:[["Efraim,","Ephraim,"],["porém,","but,"],["muito","much"],["amargamente","bitterly"],["o","the"],["irou;","chargest;"],["portanto,","therefore,"],["deixará","leave"],["ficar","remain"],["sobre","upon"],["ele","he"],["o","the"],["seu","his"],["sangue,","blood,"],["e","and"],["o","the"],["seu","his"],["Senhor","Lord"],["lhe","to-him"],["recompensará","will-compensate"],["o","the"],["seu","his"],["opróbrio.","reproach."]]}
];
var v13 = [
  {num:1,words:[["Quando","When"],["Efraim","Ephraim"],["falava,","talked,"],["havia","had"],["tremor;","trembling;"],["foi","was"],["exalçado","exalted"],["em","in"],["Israel;","Israel;"],["mas","but"],["quando","when"],["se","if"],["fez","made"],["culpado","guilty"],["em","in"],["Baal,","Baal,"],["então","said"],["morreu.","died."]]},
  {num:2,words:[["E","And"],["agora","now"],["acumularam","they-accumulated"],["pecados","sins"],["sobre","upon"],["pecados,","sins,"],["e","and"],["da","of-the"],["sua","his"],["prata","silver"],["fizeram","they-made"],["uma","a"],["imagem","image"],["de","of"],["fundição,","molten,"],["ídolos","idols"],["segundo","according-to"],["o","the"],["seu","his"],["entendimento,","understanding,"],["que","that"],["todos","all"],["são","they-are"],["obra","work"],["de","of"],["artífices,","craftsmen,"],["dos","of-the"],["quais","what"],["dizem:","they-say:"],["Os","The"],["homens","men"],["que","that"],["sacrificam","spouses"],["beijem","they-kiss"],["os","the"],["bezerros.","calf."]]},
  {num:3,words:[["Por isso","therefore"],["serão","they-will-be"],["como","as"],["a","to"],["nuvem","cloud"],["de","of"],["manhã,","morning,"],["e","and"],["como","as"],["orvalho","dew"],["da","of-the"],["madrugada,","early,"],["que","that"],["passa;","passeth;"],["como","as"],["palha","straw"],["que","that"],["a","to"],["tempestade","hurricane"],["lança","spear"],["da","of-the"],["eira,","threshingfloor,"],["e","and"],["como","as"],["a","to"],["fumaça","smoke"],["da","of-the"],["chaminé.","chimney."]]},
  {num:4,words:[["Eu,","I,"],["pois,","for,"],["sou","I-am"],["o","the"],["Senhor","Lord"],["teu","your"],["Deus","God"],["desde","since"],["a","to"],["terra do","egypt"],["Egito;","Egypt;"],["portanto,","therefore,"],["não","no"],["reconhecerás","you-will-acknowledge"],["outro","another"],["deus","god"],["além de","besides"],["mim,","me,"],["porque","because"],["não","no"],["há","has"],["Salvador","Saver"],["senão","save"],["eu.","I."]]},
  {num:5,words:[["Eu","I"],["te","you"],["conheci","profess"],["no","in-the"],["deserto,","desert,"],["na","in-the"],["terra","land"],["muito","much"],["seca.","dry."]]},
  {num:6,words:[["Depois","Afterwards"],["eles","they"],["se","if"],["fartaram","oliveyards"],["à","to-the"],["proporção","proportion"],["do","of-the"],["seu","his"],["pasto;","pasture;"],["estando,","I-am,"],["pois,","for,"],["fartos,","full,"],["ensoberbeceu-se","pasture"],["o","the"],["seu","his"],["coração;","heart;"],["por isso","therefore"],["se","if"],["esqueceram","they-forgot"],["de","of"],["mim.","me."]]},
  {num:7,words:[["Portanto,","Therefore,"],["serei","I-will-be"],["para","for"],["eles","they"],["como","as"],["leão;","lion;"],["como","as"],["leopardo","leopard"],["espreitarei","leopard"],["no","in-the"],["caminho.","way."]]},
  {num:8,words:[["Como","As"],["a","to"],["ursa","bear"],["que","that"],["perdeu","savor"],["seus","his"],["filhotes,","whelps,"],["os","the"],["encontrarei,","bereaved,"],["lhes","to-them"],["romperei","I-will-break"],["as","the"],["teias","structure"],["do","of-the"],["seu","his"],["coração,","heart,"],["e","and"],["ali","there"],["os","the"],["devorarei","I-will-devour"],["como","as"],["leão;","lion;"],["as","the"],["feras","beast"],["do","of-the"],["campo","field"],["os","the"],["despedaçarão.","dash."]]},
  {num:9,words:[["Isso","That"],["foi","was"],["a","to"],["tua","your"],["ruína,","ruin,"],["ó","O"],["Israel,","Israel,"],["que","that"],["te","you"],["rebelaste","haughty"],["contra","against"],["mim,","me,"],["a saber,","namely"],["contra","against"],["a","to"],["tua","your"],["ajuda.","aid."]]},
  {num:10,words:[["Onde","Where"],["está","is"],["agora","now"],["o","the"],["teu","your"],["rei,","king,"],["para que","that"],["te","you"],["guarde","keeps"],["em","in"],["todas","things"],["as","the"],["tuas","your"],["cidades?","cities?"],["E","And"],["os","the"],["teus","your"],["juízes,","judges,"],["dos","of-the"],["quais","what"],["disseste:","you-said:"],["Dá-me","Gives-me"],["rei e","king's"],["príncipes?","princes?"]]},
  {num:11,words:[["Dei-te","I-gave-you"],["um","a"],["rei","king"],["na","in-the"],["minha","my"],["ira,","anger,"],["e","and"],["to","to-you-it"],["tirarei","I-will-deduct"],["no","in-the"],["meu","my"],["furor.","fury."]]},
  {num:12,words:[["A","To"],["iniquidade","iniquity"],["de","of"],["Efraim","Ephraim"],["está","is"],["atada,","bind,"],["o","the"],["seu","his"],["pecado","sin"],["está","is"],["oculto.","occult."]]},
  {num:13,words:[["Dores","Sorrows"],["de","of"],["mulher","dame"],["de","of"],["parto","travail"],["lhe","to-him"],["virão;","they-will-come;"],["ele","he"],["é","is"],["um","a"],["filho","son"],["insensato","foolish"],["porque","because"],["não","no"],["está","is"],["no","in-the"],["seu","his"],["lugar","place"],["no","in-the"],["tempo","time"],["em","in"],["que","that"],["se","if"],["abre","openeth"],["a","to"],["madre.","womb."]]},
  {num:14,words:[["Eu,","I,"],["pois,","for,"],["os","the"],["remirei","I-will-shortened"],["da","of-the"],["violência","violence"],["do","of-the"],["inferno,","hell,"],["e","and"],["os","the"],["resgatarei","I-will-redeem"],["da","of-the"],["morte.","death."],["Onde","Where"],["estão,","they-are,"],["ó","O"],["morte,","death,"],["as","the"],["tuas","your"],["pestes?","pestilence?"],["Onde","Where"],["está,","is,"],["ó","O"],["inferno,","hell,"],["a","to"],["tua","your"],["perdição?","perdition?"],["A","To"],["compaixão","compassion"],["será","will-be"],["escondida","hid"],["de","of"],["meus","my"],["olhos.","eyes."]]},
  {num:15,words:[["Ainda que","although"],["ele","he"],["dê","gives"],["fruto","fruit"],["entre","between"],["os","the"],["irmãos,","brethren,"],["virá","will-come"],["o","the"],["vento","wind"],["leste,","east,"],["vento","wind"],["do","of-the"],["Senhor,","Lord,"],["subindo","I-climb"],["do","of-the"],["deserto,","desert,"],["e","and"],["secar-se-á","to-secar-se"],["a","to"],["sua","his"],["nascente,","sunrising,"],["e","and"],["secar-se-á","to-secar-se"],["a","to"],["sua","his"],["fonte;","fountain;"],["ele","he"],["saqueará","breeding"],["o","the"],["tesouro","treasure"],["de","of"],["todos","all"],["os","the"],["objetos","jewels"],["desejáveis.","you-desired."]]},
  {num:16,words:[["Samaria","Samaria"],["virá","will-come"],["a","to"],["ser","be"],["deserta,","desert,"],["porque","because"],["se","if"],["rebelou","rebelled"],["contra","against"],["o","the"],["seu","his"],["Deus;","God;"],["cairão","fall"],["à","to-the"],["espada,","sword,"],["seus","his"],["filhos","children"],["serão","they-will-be"],["despedaçados,","dashed,"],["e","and"],["as","the"],["suas","his"],["grávidas","ripped"],["serão","they-will-be"],["fendidas","I-should-split"],["pelo","by-the"],["meio.","midst."]]}
];
var v14 = [
  {num:1,words:[["Converte-te,","Converts-you,"],["ó","O"],["Israel,","Israel,"],["ao","to-the"],["Senhor","Lord"],["teu","your"],["Deus;","God;"],["porque","because"],["pelos","by-the"],["teus","your"],["pecados","sins"],["caíste.","you-fell."]]},
  {num:2,words:[["Tomai","Get"],["convosco","with-you"],["palavras,","words,"],["e","and"],["conver-tei-vos","graciously"],["ao","to-the"],["Senhor;","Lord;"],["dizei-lhe:","say-to-him:"],["Tira","Ribbon"],["toda","every"],["a","to"],["iniquidade,","iniquity,"],["e","and"],["recebe","receiveth"],["o","the"],["bem;","good;"],["e","and"],["ofereceremos","we-will-dedicate"],["os","the"],["frutos","fruit"],["dos","of-the"],["nossos","our"],["lábios.","lips."]]},
  {num:3,words:[["Não","No"],["nos","us"],["salvará","will-save"],["a","to"],["Assíria,","Assyria,"],["não","no"],["iremos","we-will-go"],["montados","riding"],["em","in"],["cavalos,","horses,"],["e","and"],["à","to-the"],["obra","work"],["das","of-the"],["nossas","our"],["mãos","hands"],["não","no"],["diremos","we-will-say"],["mais:","still:"],["Vós","You"],["sois","you-are"],["os","the"],["nossos","our"],["deuses;","gods;"],["porque","because"],["por","by"],["ti","you"],["o","the"],["órfão","fatherless"],["alcançará","will-accomplish"],["misericórdia.","mercy."]]},
  {num:4,words:[["Eu","I"],["sararei","heal"],["a","to"],["sua","his"],["perversão,","vice,"],["eu","I"],["voluntariamente","willingly"],["os","the"],["amarei;","revolters;"],["porque","because"],["a","to"],["minha","my"],["ira","anger"],["se","if"],["apartou","nebat"],["deles.","of-them."]]},
  {num:5,words:[["Eu","I"],["serei","I-will-be"],["para","for"],["Israel","Israel"],["como","as"],["orvalho,","dew,"],["ele","he"],["florescerá","blossom"],["como","as"],["o","the"],["lírio,","lily,"],["e","and"],["espalhará","will-disseminate"],["as","the"],["suas","his"],["raízes","roots"],["como","as"],["o","the"],["Líbano.","Lebanon."]]},
  {num:6,words:[["Estender-se-ão","They-will-comprise"],["os","the"],["seus","his"],["ramos,","branches,"],["e","and"],["a","to"],["sua","his"],["glória","glory"],["será","will-be"],["como","as"],["a","to"],["da","of-the"],["oliveira,","olive,"],["e","and"],["cheirará","will-smell"],["como","as"],["o","the"],["Líbano.","Lebanon."]]},
  {num:7,words:[["Voltarão","They-will-return"],["os","the"],["que","that"],["se","if"],["assentarem","they-will-settle"],["debaixo","under"],["da","of-the"],["sua","his"],["sombra;","shadow;"],["serão","they-will-be"],["vivificados","quickened"],["como","as"],["o","the"],["trigo,","wheat,"],["e","and"],["florescerão","flourish"],["como","as"],["a","to"],["vide;","vine;"],["a","to"],["sua","his"],["memória","memory"],["será","will-be"],["como","as"],["o","the"],["vinho","wine"],["do","of-the"],["Líbano.","Lebanon."]]},
  {num:8,words:[["Efraim","Ephraim"],["então","said"],["dirá:","will-say:"],["Que","That"],["mais","still"],["tenho","I-have"],["eu","I"],["com","with"],["os","the"],["ídolos?","idols?"],["Eu","I"],["o","the"],["tenho","I-have"],["ouvido,","ear,"],["e","and"],["olharei","trembleth"],["para","for"],["ele;","he;"],["ser-lhe-ei","I-will-be-to-him"],["como","as"],["a","to"],["faia","fir"],["verde;","green;"],["de","of"],["mim","me"],["procede","proceedeth"],["o","the"],["teu","your"],["fruto.","fruit."]]},
  {num:9,words:[["Quem","Who"],["é","is"],["sabio,","transgressors,"],["para que","that"],["entenda","readeth"],["essas","those"],["coisas?","things?"],["Quem","Who"],["é","is"],["prudente,","prudent,"],["para que","that"],["as","the"],["saiba?","knows?"],["Porque","Because"],["os","the"],["caminhos","ways"],["do","of-the"],["Senhor","Lord"],["são","they-are"],["retos,","upright,"],["e","and"],["os","the"],["justos","righteous"],["andarão","fatling"],["neles,","therein,"],["mas","but"],["os","the"],["transgressores","transgressors"],["cairão","fall"],["neles.","therein."]]}
];
renderVerseSet(v1, 'hos-ch1-verses');
renderVerseSet(v2, 'hos-ch2-verses');
renderVerseSet(v3, 'hos-ch3-verses');
renderVerseSet(v4, 'hos-ch4-verses');
renderVerseSet(v5, 'hos-ch5-verses');
renderVerseSet(v6, 'hos-ch6-verses');
renderVerseSet(v7, 'hos-ch7-verses');
renderVerseSet(v8, 'hos-ch8-verses');
renderVerseSet(v9, 'hos-ch9-verses');
renderVerseSet(v10, 'hos-ch10-verses');
renderVerseSet(v11, 'hos-ch11-verses');
renderVerseSet(v12, 'hos-ch12-verses');
renderVerseSet(v13, 'hos-ch13-verses');
renderVerseSet(v14, 'hos-ch14-verses');
})();
