(function() {
var v1 = [
  {num:1,words:[["E","And"],["veio","came"],["a","to"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["a","to"],["Jonas,","Jonas,"],["filho","son"],["de","of"],["Amitai,","Amittai,"],["dizendo:","saying:"]]},
  {num:2,words:[["Levanta-te,","Arise,"],["vai","goes"],["à","to-the"],["grande","great"],["cidade","city"],["de","of"],["Nínive,","Nineveh,"],["e","and"],["clama","crieth"],["contra","against"],["ela,","she,"],["porque","because"],["a","to"],["sua","his"],["maldade","wickedness"],["subiu","climbed"],["até","until"],["mim.","me."]]},
  {num:3,words:[["E","And"],["Jonas","Jonas"],["se","if"],["levantou","arose"],["para","for"],["fugir","flee"],["de","of"],["diante","before"],["da","of-the"],["face","face"],["do","of-the"],["Senhor","Lord"],["para","for"],["Társis,","Tarshish,"],["e","and"],["desceu","descended"],["a","to"],["Jope,","Joppa,"],["e","and"],["achou","found"],["um","a"],["navio","ship"],["que","that"],["ia","went"],["para","for"],["Társis,","Tarshish,"],["e","and"],["pagou","requited"],["a","to"],["sua","his"],["passagem,","passage,"],["e","and"],["desceu","descended"],["para","for"],["dentro","within"],["dele,","of-him,"],["para","for"],["ir","go"],["com","with"],["eles","they"],["para","for"],["Társis,","Tarshish,"],["para","for"],["longe","far"],["da","of-the"],["face","face"],["do","of-the"],["Senhor.","Lord."]]},
  {num:4,words:[["Mas","But"],["o","the"],["Senhor","Lord"],["lançou","vomited"],["ao","to-the"],["mar","sea"],["um","a"],["grande","great"],["vento,","wind,"],["e","and"],["fez-se","became"],["no","in-the"],["mar","sea"],["uma","a"],["grande","great"],["tempestade,","hurricane,"],["e","and"],["o","the"],["navio","ship"],["estava","was"],["para","for"],["quebrar-se.","to-quebrar-se."]]},
  {num:5,words:[["Então","Said"],["temeram","feared"],["os","the"],["marinheiros,","sailor,"],["e","and"],["clamavam","they-cried"],["cada","every"],["um","a"],["ao","to-the"],["seu","his"],["deus,","god,"],["e","and"],["lançavam","they-vomited"],["no","in-the"],["mar","sea"],["a","to"],["carga","burden"],["que","that"],["estava","was"],["no","in-the"],["navio,","ship,"],["para","for"],["o","the"],["aliviarem","they-will-comfort"],["do","of-the"],["seu","his"],["peso;","weight;"],["porém","but"],["Jonas","Jonas"],["desceu","descended"],["aos","to-the"],["lados","sides"],["do","of-the"],["porão,","badgers',"],["e","and"],["se","if"],["deitou,","lain,"],["e","and"],["dormia","slept"],["um","a"],["profundo","deep"],["sono.","sleep."]]},
  {num:6,words:[["E","And"],["o","the"],["mestre","master"],["do","of-the"],["navio","ship"],["chegou-se","to-chegar-se"],["a","to"],["ele,","he,"],["e","and"],["disse-lhe:","said:"],["Que","That"],["tens,","you-have,"],["ó","O"],["tu","you"],["que","that"],["dormes?","you-sleep?"],["Levanta-te,","Arise,"],["clama","crieth"],["ao","to-the"],["teu","your"],["Deus;","God;"],["porventura","perchance"],["Deus","God"],["se","if"],["lembrará","will-caution"],["de","of"],["nós","we"],["para que","that"],["não","no"],["pereçamos.","we-perish."]]},
  {num:7,words:[["E","And"],["diziam","they-said"],["cada","every"],["um","a"],["ao","to-the"],["seu","his"],["companheiro:","companion:"],["Vinde,","Come,"],["e","and"],["lancemos","we-vomit"],["sortes,","lots,"],["para que","that"],["saibamos","we-know"],["por","by"],["que","that"],["causa","sake"],["nos","us"],["sobreveio","befallen"],["este","this"],["mal.","evil."],["E","And"],["lançaram","lots"],["sortes,","lots,"],["e","and"],["a","to"],["sorte","lot"],["caiu","fell"],["sobre","upon"],["Jonas.","Jonas."]]},
  {num:8,words:[["Então","Said"],["lhe","to-him"],["disseram:","they-said:"],["Declara-nos","Declareth-us"],["tu","you"],["agora,","now,"],["por causa de","because-of"],["quem","who"],["nos","us"],["sobreveio","befallen"],["este","this"],["mal.","evil."],["Que","That"],["ocupação","occupation"],["é","is"],["a","to"],["tua?","your?"],["Donde","Whence"],["vens?","you-come?"],["Qual","Which"],["é","is"],["a","to"],["tua","your"],["terra?","land?"],["E","And"],["de","of"],["que","that"],["povo","people"],["és","you-are"],["tu?","you?"]]},
  {num:9,words:[["E","And"],["ele","he"],["lhes","to-them"],["disse:","said:"],["Eu","I"],["sou","I-am"],["hebreu,","hebrew,"],["e","and"],["temo","striving"],["ao","to-the"],["Senhor,","Lord,"],["o","the"],["Deus","God"],["do","of-the"],["céu,","heaven,"],["que","that"],["fez","made"],["o","the"],["mar","sea"],["e","and"],["a","to"],["terra","land"],["seca.","dry."]]},
  {num:10,words:[["Então","Said"],["esses","those"],["homens","men"],["tremeram","they-trembled"],["com","with"],["grande","great"],["temor,","fear,"],["e","and"],["lhe","to-him"],["disseram:","they-said:"],["Por","By"],["que","that"],["fizeste","you-made"],["tu","you"],["isso?","that?"],["Pois","For"],["sabiam","they-knew"],["os","the"],["homens","men"],["que","that"],["fugia","fled"],["de","of"],["diante","before"],["do","of-the"],["Senhor,","Lord,"],["porque","because"],["ele","he"],["lho","to-him-it"],["tinha","had"],["declarado.","declared."]]},
  {num:11,words:[["E","And"],["disseram-lhe:","they-said-to-him:"],["Que","That"],["te","you"],["faremos","we-will-make"],["nós,","we,"],["para que","that"],["o","the"],["mar","sea"],["se","if"],["nos","us"],["aquiete?","facilitates?"],["Porque","Because"],["o","the"],["mar","sea"],["se","if"],["ia","went"],["tornando","I-become"],["cada","every"],["vez","occasion"],["mais","still"],["tempestuoso.","stormy."]]},
  {num:12,words:[["E","And"],["ele","he"],["lhes","to-them"],["disse:","said:"],["Levantai-me,","Hoist-me,"],["e","and"],["lançai-me","vomit-me"],["ao","to-the"],["mar,","sea,"],["e","and"],["o","the"],["mar","sea"],["se","if"],["vos","you"],["aquietará;","will-facilitate;"],["porque","because"],["eu","I"],["sei","I-know"],["que","that"],["por","by"],["minha","my"],["causa","sake"],["é","is"],["que","that"],["vos","you"],["sobreveio","befallen"],["esta","this"],["grande","great"],["tempestade.","hurricane."]]},
  {num:13,words:[["Mas","But"],["os","the"],["homens","men"],["remavam,","they-rowed,"],["para","for"],["tornar","become"],["a","to"],["levar","carry"],["o","the"],["navio","ship"],["para","for"],["terra,","land,"],["mas","but"],["não","no"],["podiam;","they-could;"],["porquanto","because"],["o","the"],["mar","sea"],["se","if"],["ia","went"],["embravecendo","rowed"],["cada","every"],["vez","occasion"],["mais","still"],["contra","against"],["eles.","they."]]},
  {num:14,words:[["Então","Said"],["clamaram","cried"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["disseram:","they-said:"],["Ah,","Ah,"],["Senhor!","Lord!"],["Não","No"],["pereçamos","we-perish"],["por","by"],["causa","sake"],["da","of-the"],["alma","soul"],["deste","of-this"],["homem,","man,"],["e","and"],["não","no"],["ponhas","place"],["sobre","upon"],["nós","we"],["o","the"],["sangue","blood"],["inocente;","innocent;"],["porque","because"],["tu,","you,"],["Senhor,","Lord,"],["fizeste","you-made"],["como","as"],["quiseste.","you-willed."]]},
  {num:15,words:[["E","And"],["levantaram","rose"],["Jonas,","Jonas,"],["e","and"],["o","the"],["lançaram","lots"],["ao","to-the"],["mar,","sea,"],["e","and"],["cessou","ceased"],["o","the"],["mar","sea"],["da","of-the"],["sua","his"],["fúria.","raging."]]},
  {num:16,words:[["Temeram,","Feared,"],["pois,","for,"],["estes","these"],["homens","men"],["ao","to-the"],["Senhor","Lord"],["com","with"],["grande","great"],["temor;","fear;"],["e","and"],["ofereceram","offered"],["sacrifícios","sacrifices"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["fizeram","they-made"],["votos.","vows."]]},
  {num:17,words:[["Preparou,","Prepared,"],["pois,","for,"],["o","the"],["Senhor","Lord"],["um","a"],["grande","great"],["peixe,","fish,"],["para que","that"],["tragasse","swallowed"],["Jonas;","Jonas;"],["e","and"],["esteve","was"],["Jonas","Jonas"],["três","three"],["dias","days"],["e","and"],["três","three"],["noites","nights"],["nas","in-the"],["entranhas","bowels"],["do","of-the"],["peixe.","fish."]]}
];
var v2 = [
  {num:1,words:[["E","And"],["orou","prayed"],["Jonas","Jonas"],["ao","to-the"],["Senhor","Lord"],["seu","his"],["Deus,","God,"],["das","of-the"],["entranhas","bowels"],["do","of-the"],["peixe.","fish."]]},
  {num:2,words:[["E","And"],["disse:","said:"],["Da","Of-the"],["minha","my"],["angústia","anguish"],["clamei","cried"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["ele","he"],["me","me"],["respondeu;","answered;"],["do","of-the"],["ventre","abdomen"],["do","of-the"],["inferno","hell"],["gritei,","I-screamed,"],["e","and"],["tu","you"],["ouviste","you-heard"],["a","to"],["minha","my"],["voz.","voice."]]},
  {num:3,words:[["Porque","Because"],["tu","you"],["me","me"],["lançaste","you-vomited"],["nas","in-the"],["profundezas,","depths,"],["no","in-the"],["coração","heart"],["dos","of-the"],["mares,","seas,"],["e","and"],["a","to"],["correnteza","fluentness"],["me","me"],["cercou;","besieged;"],["todas","things"],["as","the"],["tuas","your"],["ondas","waves"],["e","and"],["as","the"],["tuas","your"],["vagas","you-be vacant"],["passaram","passed"],["por cima de","above"],["mim.","me."]]},
  {num:4,words:[["E","And"],["eu","I"],["dizia:","said:"],["Lançado","Offend"],["estou","I-am"],["de","of"],["diante","before"],["dos","of-the"],["teus","your"],["olhos;","eyes;"],["todavia","nevertheless"],["tornarei","I-will-become"],["a","to"],["ver","see"],["o","the"],["templo","temple"],["da","of-the"],["tua","your"],["santidade.","holiness."]]},
  {num:5,words:[["As","The"],["águas","waters"],["me","me"],["cercaram","compassed"],["até","until"],["a","to"],["alma,","soul,"],["o","the"],["abismo","gulf"],["me","me"],["rodeou,","weeds,"],["e","and"],["as","the"],["algas","alga"],["se","if"],["enrolavam","they-bandaged"],["à","to-the"],["minha","my"],["cabeça.","head."]]},
  {num:6,words:[["Eu","I"],["desci","I-descended"],["até","until"],["os","the"],["fundamentos","foundations"],["dos","of-the"],["montes;","mountains;"],["os","the"],["ferrolhos","bars"],["da","of-the"],["terra","land"],["me","me"],["encerrariam","they-should-accomodate"],["para sempre;","for-ever"],["mas","but"],["tu","you"],["fizeste","you-made"],["subir","climb"],["a","to"],["minha","my"],["vida","life"],["da","of-the"],["perdição,","perdition,"],["ó","O"],["Senhor","Lord"],["meu","my"],["Deus.","God."]]},
  {num:7,words:[["Desfalecendo","I-faint"],["em","in"],["mim","me"],["a","to"],["minha","my"],["alma,","soul,"],["me","me"],["lembrei","harrowed"],["do","of-the"],["Senhor;","Lord;"],["e","and"],["chegou","came"],["a","to"],["ti","you"],["a","to"],["minha","my"],["oração,","prayer,"],["no","in-the"],["templo","temple"],["da","of-the"],["tua","your"],["santidade.","holiness."]]},
  {num:8,words:[["Os","The"],["que","that"],["observam","they-observe"],["vaidades","vanities"],["enganosas","deceptive"],["abandonam","calved"],["a","to"],["sua","his"],["própria","own"],["misericórdia.","mercy."]]},
  {num:9,words:[["Mas","But"],["eu","I"],["sacrificarei","ruin"],["a","to"],["ti","you"],["com","with"],["a","to"],["voz","voice"],["do","of-the"],["agradecimento;","gratitude;"],["o","the"],["que","that"],["prometi","I-promised"],["pagarei;","I-will-pay;"],["do","of-the"],["Senhor","Lord"],["vem","comes"],["a","to"],["salvação.","salvation."]]},
  {num:10,words:[["Falou,","Spake,"],["pois,","for,"],["o","the"],["Senhor","Lord"],["ao","to-the"],["peixe,","fish,"],["e","and"],["este","this"],["vomitou","vomited"],["Jonas","Jonas"],["na","in-the"],["terra.","land."]]}
];
var v3 = [
  {num:1,words:[["E","And"],["veio","came"],["a","to"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["pela","by-the"],["segunda","second"],["vez","occasion"],["a","to"],["Jonas,","Jonas,"],["dizendo:","saying:"]]},
  {num:2,words:[["Levanta-te,","Arise,"],["e","and"],["vai","goes"],["à","to-the"],["grande","great"],["cidade","city"],["de","of"],["Nínive,","Nineveh,"],["e","and"],["proclama","publisheth"],["contra","against"],["ela","she"],["a","to"],["pregação","preaching"],["que","that"],["eu","I"],["te","you"],["digo.","I-say."]]},
  {num:3,words:[["E","And"],["levantou-se","thoroughly"],["Jonas,","Jonas,"],["e","and"],["foi","was"],["a","to"],["Nínive,","Nineveh,"],["segundo","according-to"],["a","to"],["palavra","word"],["do","of-the"],["Senhor.","Lord."],["Era,","Was,"],["pois,","for,"],["Nínive","Nineveh"],["uma","a"],["grande","great"],["cidade","city"],["diante de","before"],["Deus,","God,"],["de","of"],["três","three"],["dias","days"],["de","of"],["caminho.","way."]]},
  {num:4,words:[["E","And"],["começou","began"],["Jonas","Jonas"],["a","to"],["entrar","enter"],["pela","by-the"],["cidade","city"],["caminho","way"],["de","of"],["um","a"],["dia,","day,"],["e","and"],["pregava,","preached,"],["e","and"],["dizia:","said:"],["Ainda","Yet"],["quarenta","forty"],["dias,","days,"],["e","and"],["Nínive","Nineveh"],["será","will-be"],["subvertida.","destroy."]]},
  {num:5,words:[["E","And"],["os","the"],["homens","men"],["de","of"],["Nínive","Nineveh"],["creram","believed"],["em","in"],["Deus;","God;"],["e","and"],["proclamaram","they-proclaimed"],["um","a"],["jejum,","fasting,"],["e","and"],["vestiram-se","they-dressed"],["de","of"],["panos","sackcloth"],["de","of"],["saco,","sack,"],["desde o","beginning"],["maior","greater"],["até","until"],["o","the"],["menor.","least."]]},
  {num:6,words:[["Porque","Because"],["essa","that ... over there"],["palavra","word"],["chegou","came"],["ao","to-the"],["rei","king"],["de","of"],["Nínive,","Nineveh,"],["e","and"],["levantou-se","thoroughly"],["do","of-the"],["seu","his"],["trono,","throne,"],["e","and"],["tirou","deducted"],["de","of"],["si","himself"],["a","to"],["sua","his"],["capa,","cover,"],["e","and"],["cobriu-se","clad"],["de","of"],["panos","sackcloth"],["de","of"],["saco,","sack,"],["e","and"],["assentou-se","sat"],["sobre","upon"],["a","to"],["cinza.","ashes."]]},
  {num:7,words:[["E","And"],["fez","made"],["apregoar,","brokenhearted,"],["e","and"],["falou-se","to-falar-se"],["em","in"],["Nínive,","Nineveh,"],["pelo","by-the"],["mandado","commandment"],["do rei e","king's"],["dos","of-the"],["seus","his"],["nobres,","nobles,"],["dizendo:","saying:"],["Nem","Nor"],["homens,","men,"],["nem","nor"],["animais,","beasts,"],["nem","nor"],["bois,","oxen,"],["nem","nor"],["ovelhas","sheep"],["provem","they-prove"],["coisa","thing"],["alguma,","any,"],["nem","nor"],["se","if"],["lhes","to-them"],["dê","gives"],["pasto,","pasture,"],["nem","nor"],["bebam","piss"],["água.","water."]]},
  {num:8,words:[["Mas","But"],["os","the"],["homens","men"],["e","and"],["os","the"],["animais","beasts"],["estarão","they-will-be"],["cobertos","cover"],["de","of"],["panos","sackcloth"],["de","of"],["saco,","sack,"],["e","and"],["clamarão","simpleness"],["fortemente","strongly"],["a","to"],["Deus,","God,"],["e","and"],["se","if"],["converterão","pruninghooks"],["cada","every"],["um","a"],["do","of-the"],["seu","his"],["mau","bad"],["caminho,","way,"],["e","and"],["da","of-the"],["violência","violence"],["que","that"],["há","has"],["nas","in-the"],["suas","his"],["mãos.","hands."]]},
  {num:9,words:[["Quem","Who"],["sabe","knows"],["se","if"],["Deus","God"],["se","if"],["voltará,","will-return,"],["e","and"],["se","if"],["arrependerá,","melchisedec,"],["e","and"],["se","if"],["apartará","will-divide"],["do","of-the"],["furor","fury"],["da","of-the"],["sua","his"],["ira,","anger,"],["de sorte que","so-that"],["não","no"],["pereçamos?","we-perish?"]]},
  {num:10,words:[["E","And"],["Deus","God"],["viu","saw"],["as","the"],["obras","works"],["deles,","of-them,"],["como","as"],["se","if"],["converteram","they-converted"],["do","of-the"],["seu","his"],["mau","bad"],["caminho;","way;"],["e","and"],["Deus","God"],["se","if"],["arrependeu","repented"],["do","of-the"],["mal","evil"],["que","that"],["tinha","had"],["dito","spoken"],["lhes","to-them"],["faria,","should-make,"],["e","and"],["não","no"],["o","the"],["fez.","made."]]}
];
var v4 = [
  {num:1,words:[["E","And"],["desagradou-se","to-desagradar-se"],["Jonas","Jonas"],["extremamente","extremely"],["disso,","of-that,"],["e","and"],["ficou","remained"],["irado.","angry."]]},
  {num:2,words:[["E","And"],["orou","prayed"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["disse:","said:"],["Ah,","Ah,"],["Senhor!","Lord!"],["Não","No"],["foi","was"],["essa","that ... over there"],["a","to"],["minha","my"],["palavra,","word,"],["estando","I-am"],["eu","I"],["ainda","yet"],["na","in-the"],["minha","my"],["terra?","land?"],["Por isso","therefore"],["é","is"],["que","that"],["me","me"],["preveni,","I-cautioned,"],["fugindo","I-flee"],["para","for"],["Társis,","Tarshish,"],["pois","for"],["sabia","knew"],["que","that"],["és","you-are"],["Deus","God"],["piedoso,","gracious,"],["e","and"],["misericordioso,","merciful,"],["longânimo","slow"],["e","and"],["grande","great"],["em","in"],["benignidade,","endureth,"],["e","and"],["que","that"],["te","you"],["arrependes","repenteth"],["do","of-the"],["mal.","evil."]]},
  {num:3,words:[["Peço-te,","I-ask-you,"],["pois,","for,"],["ó","O"],["Senhor,","Lord,"],["tira-me","ribbon-me"],["a","to"],["minha","my"],["vida,","life,"],["porque","because"],["melhor","better"],["me","me"],["é","is"],["morrer","die"],["do","of-the"],["que","that"],["viver.","live."]]},
  {num:4,words:[["E","And"],["disse","said"],["o","the"],["Senhor:","Lord:"],["Fazes","You-make"],["bem","good"],["que","that"],["assim","thus"],["te","you"],["ires?","to-go?"]]},
  {num:5,words:[["Jonas,","Jonas,"],["pois,","for,"],["saiu","went"],["da","of-the"],["cidade,","city,"],["e","and"],["assentou-se","sat"],["ao","to-the"],["oriente","east"],["da","of-the"],["cidade;","city;"],["e","and"],["ali","there"],["fez","made"],["uma","a"],["cabana,","booth,"],["e","and"],["se","if"],["assentou","sat"],["debaixo","under"],["dela,","of-it,"],["à","to-the"],["sombra,","shadow,"],["até","until"],["ver","see"],["o","the"],["que","that"],["aconteceria","should-become"],["à","to-the"],["cidade.","city."]]},
  {num:6,words:[["E","And"],["preparou","prepared"],["o","the"],["Senhor","Lord"],["Deus","God"],["uma","a"],["aboboreira,","gourd,"],["e","and"],["a","to"],["fez","made"],["subir","climb"],["por cima de","above"],["Jonas,","Jonas,"],["para que","that"],["fizesse","made"],["sombra","shadow"],["sobre","upon"],["a","to"],["sua","his"],["cabeça,","head,"],["a fim de","in-order-to"],["o","the"],["livrar","free"],["do","of-the"],["seu","his"],["desconforto;","discomfort;"],["e","and"],["Jonas","Jonas"],["se","if"],["alegrou","rejoiced"],["grandemente","greatly"],["por","by"],["causa","sake"],["da","of-the"],["aboboreira.","gourd."]]},
  {num:7,words:[["Mas","But"],["Deus","God"],["enviou","sent"],["um","a"],["bicho,","worm,"],["no","in-the"],["dia","day"],["seguinte","next"],["ao","to-the"],["subir","climb"],["da","of-the"],["alva,","dawning,"],["e","and"],["feriu","smote"],["a","to"],["aboboreira,","gourd,"],["e","and"],["ela","she"],["secou.","drieth."]]},
  {num:8,words:[["E aconteceu que,","and-it-came-to-pass-that"],["aparecendo","I-appear"],["o","the"],["sol,","sun,"],["Deus","God"],["ordenou","commanded"],["um","a"],["vento","wind"],["quente","warm"],["oriental,","east,"],["e","and"],["o","the"],["sol","sun"],["feriu","smote"],["a","to"],["cabeça","head"],["de","of"],["Jonas;","Jonas;"],["e","and"],["ele","he"],["desmaiou,","fainted,"],["e","and"],["desejou","desired"],["com","with"],["toda","every"],["a","to"],["sua","his"],["alma","soul"],["morrer,","die,"],["dizendo:","saying:"],["Melhor","Better"],["me","me"],["é","is"],["morrer","die"],["do","of-the"],["que","that"],["viver.","live."]]},
  {num:9,words:[["Então","Said"],["disse","said"],["Deus","God"],["a","to"],["Jonas:","Jonas:"],["Fazes","You-make"],["bem","good"],["que","that"],["assim","thus"],["te","you"],["ires","to-go"],["por","by"],["causa","sake"],["da","of-the"],["aboboreira?","gourd?"],["E","And"],["ele","he"],["disse:","said:"],["Faço","I-make"],["bem","good"],["em","in"],["irar-me","I-will-acquit"],["até","until"],["a","to"],["morte.","death."]]},
  {num:10,words:[["E","And"],["disse","said"],["o","the"],["Senhor:","Lord:"],["Tiveste","You-had"],["tu","you"],["compaixão","compassion"],["da","of-the"],["aboboreira,","gourd,"],["na","in-the"],["qual","which"],["não","no"],["trabalhaste,","you-labor,"],["nem","nor"],["a","to"],["fizeste","you-made"],["crescer,","grow,"],["que","that"],["numa","in-a"],["noite","night"],["nasceu,","born,"],["e","and"],["numa","in-a"],["noite","night"],["pereceu;","perished;"]]},
  {num:11,words:[["E","And"],["não","no"],["hei","I-have"],["de","of"],["eu","I"],["ter","have"],["compaixão","compassion"],["da","of-the"],["grande","great"],["cidade","city"],["de","of"],["Nínive,","Nineveh,"],["em","in"],["que","that"],["estão","they-are"],["mais","still"],["de","of"],["cento","hundred"],["e","and"],["vinte","twenty"],["mil","thousand"],["homens","men"],["que","that"],["não","no"],["sabem","they-know"],["discernir","discern"],["entre","between"],["a","to"],["sua","his"],["mão","hand"],["direita","right"],["e","and"],["a","to"],["sua","his"],["mão","hand"],["esquerda,","left,"],["e","and"],["muitos","many"],["animais?","beasts?"]]}
];
renderVerseSet(v1, 'jon-ch1-verses');
renderVerseSet(v2, 'jon-ch2-verses');
renderVerseSet(v3, 'jon-ch3-verses');
renderVerseSet(v4, 'jon-ch4-verses');
})();
