(function() {
var v1 = [
  {num:1,words:[["E","And"],["veio","came"],["a","the"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["a","to"],["Jonas,","Jonas,"],["filho","son"],["de","of"],["Amitai,","Amittai,"],["dizendo:","saying:"]]},
  {num:2,words:[["Levanta-te,","Raises-up-you,"],["vai","goes"],["à","to-the"],["grande","great"],["cidade","city"],["de","of"],["Nínive,","Nineveh,"],["e","and"],["clama","cries"],["contra","against"],["ela,","it,"],["porque","because"],["a","the"],["sua","their"],["maldade","wickedness"],["subiu","went-up"],["até","until"],["mim.","me."]]},
  {num:3,words:[["E","And"],["Jonas","Jonas"],["se","himself"],["levantou","arose"],["para","to"],["fugir","flee"],["de","of"],["diante","before"],["da","of-the"],["face","face"],["do","of-the"],["Senhor","Lord"],["para","for"],["Társis,","Tarshish,"],["e","and"],["desceu","descended"],["a","to"],["Jope,","Joppa,"],["e","and"],["achou","found"],["um","a"],["navio","ship"],["que","that"],["ia","went"],["para","for"],["Társis,","Tarshish,"],["e","and"],["pagou","payed"],["a","the"],["sua","his"],["passagem,","passage,"],["e","and"],["desceu","descended"],["para","for"],["dentro","within"],["dele,","of-it,"],["para","to"],["ir","go"],["com","with"],["eles","them"],["para","for"],["Társis,","Tarshish,"],["para","for"],["longe","far"],["da","of-the"],["face","face"],["do","of-the"],["Senhor.","Lord."]]},
  {num:4,words:[["Mas","But"],["o","the"],["Senhor","Lord"],["lançou","cast"],["ao","to-the"],["mar","sea"],["um","a"],["grande","great"],["vento,","wind,"],["e","and"],["fez-se","made-himself"],["no","in-the"],["mar","sea"],["uma","a"],["grande","great"],["tempestade,","hurricane,"],["e","and"],["o","the"],["navio","ship"],["estava","was"],["para","to"],["quebrar-se.","to-crush-himself."]]},
  {num:5,words:[["Então","Then"],["temeram","they-feared"],["os","the"],["marinheiros,","sailor,"],["e","and"],["clamavam","they-cried"],["cada","every"],["um","a"],["ao","to-the"],["seu","his"],["deus,","god,"],["e","and"],["lançavam","they-cast"],["no","in-the"],["mar","sea"],["a","the"],["carga","burden"],["que","that"],["estava","was"],["no","in-the"],["navio,","ship,"],["para","for"],["o","the"],["aliviarem","to-comfort"],["do","of-the"],["seu","his"],["peso;","weight;"],["porém","but"],["Jonas","Jonas"],["desceu","descended"],["aos","to-the"],["lados","sides"],["do","of-the"],["porão,","badgers',"],["e","and"],["se","if"],["deitou,","lay,"],["e","and"],["dormia","slept"],["um","a"],["profundo","deep"],["sono.","sleep."]]},
  {num:6,words:[["E","And"],["o","the"],["mestre","master"],["do","of-the"],["navio","ship"],["chegou-se","came-himself"],["a","to"],["ele,","he,"],["e","and"],["disse-lhe:","said-to-him:"],["Que","That"],["tens,","you-have,"],["ó","O"],["tu","you"],["que","that"],["dormes?","you-sleep?"],["Levanta-te,","Raises-up-you,"],["clama","cries"],["ao","to-the"],["teu","your"],["Deus;","God;"],["porventura","perchance"],["Deus","God"],["se","himself"],["lembrará","will-remember"],["de","of"],["nós","we"],["para que","that"],["não","not"],["pereçamos.","we-perish."]]},
  {num:7,words:[["E","And"],["diziam","they-said"],["cada","every"],["um","a"],["ao","to-the"],["seu","his"],["companheiro:","companion:"],["Vinde,","Come,"],["e","and"],["lancemos","let-us-cast"],["sortes,","lots,"],["para que","that"],["saibamos","we-know"],["por","by"],["que","that"],["causa","sake"],["nos","us"],["sobreveio","ensued"],["este","this"],["mal.","evil."],["E","And"],["lançaram","they-cast"],["sortes,","lots,"],["e","and"],["a","the"],["sorte","lot"],["caiu","fell"],["sobre","upon"],["Jonas.","Jonas."]]},
  {num:8,words:[["Então","Then"],["lhe","to-him"],["disseram:","they-said:"],["Declara-nos","Declares-us"],["tu","you"],["agora,","now,"],["por causa de","because-of"],["quem","who"],["nos","us"],["sobreveio","ensued"],["este","this"],["mal.","evil."],["Que","That"],["ocupação","occupation"],["é","is"],["a","to"],["tua?","your?"],["Donde","Whence"],["vens?","you-come?"],["Qual","Which"],["é","is"],["a","the"],["tua","your"],["terra?","land?"],["E","And"],["de","of"],["que","that"],["povo","people"],["és","you-are"],["tu?","you?"]]},
  {num:9,words:[["E","And"],["ele","he"],["lhes","to-them"],["disse:","said:"],["Eu","I"],["sou","I-am"],["hebreu,","hebrew,"],["e","and"],["temo","I-fear"],["ao","to-the"],["Senhor,","Lord,"],["o","the"],["Deus","God"],["do","of-the"],["céu,","heaven,"],["que","that"],["fez","made"],["o","the"],["mar","sea"],["e","and"],["a","the"],["terra","land"],["seca.","dry."]]},
  {num:10,words:[["Então","Then"],["esses","those"],["homens","men"],["tremeram","they-trembled"],["com","with"],["grande","great"],["temor,","fear,"],["e","and"],["lhe","to-him"],["disseram:","they-said:"],["Por","By"],["que","that"],["fizeste","you-made"],["tu","you"],["isso?","that?"],["Pois","For"],["sabiam","they-knew"],["os","the"],["homens","men"],["que","that"],["fugia","fled"],["de","of"],["diante","before"],["do","of-the"],["Senhor,","Lord,"],["porque","because"],["ele","he"],["lho","to-him-it"],["tinha","had"],["declarado.","declared."]]},
  {num:11,words:[["E","And"],["disseram-lhe:","they-said-to-him:"],["Que","That"],["te","you"],["faremos","we-will-make"],["nós,","we,"],["para que","that"],["o","the"],["mar","sea"],["se","if"],["nos","us"],["aquiete?","facilitates?"],["Porque","Because"],["o","the"],["mar","sea"],["se","himself"],["ia","went"],["tornando","becoming"],["cada","every"],["vez","time"],["mais","more"],["tempestuoso.","stormy."]]},
  {num:12,words:[["E","And"],["ele","he"],["lhes","to-them"],["disse:","said:"],["Levantai-me,","Raise-up-me,"],["e","and"],["lançai-me","cast-me"],["ao","to-the"],["mar,","sea,"],["e","and"],["o","the"],["mar","sea"],["se","if"],["vos","you"],["aquietará;","will-facilitate;"],["porque","because"],["eu","I"],["sei","I-know"],["que","that"],["por","by"],["minha","my"],["causa","sake"],["é","is"],["que","that"],["vos","you"],["sobreveio","ensued"],["esta","this"],["grande","great"],["tempestade.","hurricane."]]},
  {num:13,words:[["Mas","But"],["os","the"],["homens","men"],["remavam,","they-rowed,"],["para","to"],["tornar","become"],["a","to"],["levar","to-carry"],["o","the"],["navio","ship"],["para","for"],["terra,","land,"],["mas","but"],["não","not"],["podiam;","they-could;"],["porquanto","because"],["o","the"],["mar","sea"],["se","himself"],["ia","went"],["embravecendo","rowed"],["cada","every"],["vez","time"],["mais","more"],["contra","against"],["eles.","they."]]},
  {num:14,words:[["Então","Then"],["clamaram","they-cried"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["disseram:","they-said:"],["Ah,","Ah,"],["Senhor!","Lord!"],["Não","Not"],["pereçamos","we-perish"],["por causa da","because-of"],["alma","soul"],["deste","of-this"],["homem,","man,"],["e","and"],["não","not"],["ponhas","place"],["sobre","upon"],["nós","we"],["o","the"],["sangue","blood"],["inocente;","innocent;"],["porque","because"],["tu,","you,"],["Senhor,","Lord,"],["fizeste","you-made"],["como","as"],["quiseste.","you-willed."]]},
  {num:15,words:[["E","And"],["levantaram","they-raised-up"],["Jonas,","Jonas,"],["e","and"],["o","him"],["lançaram","they-cast"],["ao","to-the"],["mar,","sea,"],["e","and"],["cessou","ceased"],["o","the"],["mar","sea"],["da","of-the"],["sua","her"],["fúria.","raging."]]},
  {num:16,words:[["Temeram,","They-feared,"],["pois,","for,"],["estes","these"],["homens","men"],["ao","to-the"],["Senhor","Lord"],["com","with"],["grande","great"],["temor;","fear;"],["e","and"],["ofereceram","they-offered"],["sacrifícios","sacrifices"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["fizeram","they-made"],["votos.","vows."]]},
  {num:17,words:[["Preparou,","Prepared,"],["pois,","for,"],["o","the"],["Senhor","Lord"],["um","a"],["grande","great"],["peixe,","fish,"],["para que","that"],["tragasse","swallowed"],["Jonas;","Jonas;"],["e","and"],["esteve","was"],["Jonas","Jonas"],["três","three"],["dias","days"],["e","and"],["três","three"],["noites","nights"],["nas","in-the"],["entranhas","bowels"],["do","of-the"],["peixe.","fish."]]}
];
var v2 = [
  {num:1,words:[["E","And"],["orou","prayed"],["Jonas","Jonas"],["ao","to-the"],["Senhor","Lord"],["seu","his"],["Deus,","God,"],["das","of-the"],["entranhas","bowels"],["do","of-the"],["peixe.","fish."]]},
  {num:2,words:[["E","And"],["disse:","said:"],["Da","Of-the"],["minha","my"],["angústia","anguish"],["clamei","I-cried"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["ele","he"],["me","me"],["respondeu;","answered;"],["do","of-the"],["ventre","abdomen"],["do","of-the"],["inferno","hell"],["gritei,","I-screamed,"],["e","and"],["tu","you"],["ouviste","you-heard"],["a","the"],["minha","my"],["voz.","voice."]]},
  {num:3,words:[["Porque","Because"],["tu","you"],["me","me"],["lançaste","you-cast"],["nas","in-the"],["profundezas,","depths,"],["no","in-the"],["coração","heart"],["dos","of-the"],["mares,","seas,"],["e","and"],["a","the"],["correnteza","fluentness"],["me","me"],["cercou;","besieged;"],["todas","all"],["as","the"],["tuas","your"],["ondas","waves"],["e","and"],["as","the"],["tuas","your"],["vagas","you-be vacant"],["passaram","they-fared"],["por cima de","above"],["mim.","me."]]},
  {num:4,words:[["E","And"],["eu","I"],["dizia:","said:"],["Lançado","Cast"],["estou","I-am"],["de","of"],["diante","before"],["dos","of-the"],["teus","your"],["olhos;","eyes;"],["todavia","nevertheless"],["tornarei","I-will-become"],["a","to"],["ver","see"],["o","the"],["templo","temple"],["da","of-the"],["tua","your"],["santidade.","holiness."]]},
  {num:5,words:[["As","The"],["águas","waters"],["me","me"],["cercaram","they-compassed"],["até","until"],["a","the"],["alma,","soul,"],["o","the"],["abismo","gulf"],["me","me"],["rodeou,","surrounded,"],["e","and"],["as","the"],["algas","alga"],["se","themselves"],["enrolavam","they-bandaged"],["à","to-the"],["minha","my"],["cabeça.","head."]]},
  {num:6,words:[["Eu","I"],["desci","I-descended"],["até","until"],["os","the"],["fundamentos","foundations"],["dos","of-the"],["montes;","mountains;"],["os","the"],["ferrolhos","bars"],["da","of-the"],["terra","earth"],["me","me"],["encerrariam","they-should-accomodate"],["para sempre;","for-ever"],["mas","but"],["tu","you"],["fizeste","you-made"],["subir","go-up"],["a","the"],["minha","my"],["vida","life"],["da","of-the"],["perdição,","perdition,"],["ó","O"],["Senhor","Lord"],["meu","my"],["Deus.","God."]]},
  {num:7,words:[["Desfalecendo","Fainting"],["em","in"],["mim","me"],["a","the"],["minha","my"],["alma,","soul,"],["me","me"],["lembrei","I-remembered"],["do","of-the"],["Senhor;","Lord;"],["e","and"],["chegou","came"],["a","the"],["ti","you"],["a","the"],["minha","my"],["oração,","prayer,"],["no","in-the"],["templo","temple"],["da","of-the"],["tua","your"],["santidade.","holiness."]]},
  {num:8,words:[["Os","The"],["que","that"],["observam","they-observe"],["vaidades","vanities"],["enganosas","deceptive"],["abandonam","they-zemnarihah"],["a","the"],["sua","their"],["própria","own"],["misericórdia.","mercy."]]},
  {num:9,words:[["Mas","But"],["eu","I"],["sacrificarei","ruin"],["a","to"],["ti","you"],["com","with"],["a","the"],["voz","voice"],["do","of-the"],["agradecimento;","gratitude;"],["o","the"],["que","that"],["prometi","I-promised"],["pagarei;","I-will-pay;"],["do","of-the"],["Senhor","Lord"],["vem","comes"],["a","the"],["salvação.","salvation."]]},
  {num:10,words:[["Falou,","Spoke,"],["pois,","for,"],["o","the"],["Senhor","Lord"],["ao","to-the"],["peixe,","fish,"],["e","and"],["este","this"],["vomitou","vomited"],["Jonas","Jonas"],["na","in-the"],["terra.","land."]]}
];
var v3 = [
  {num:1,words:[["E","And"],["veio","came"],["a","the"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["pela","by-the"],["segunda","second"],["vez","time"],["a","to"],["Jonas,","Jonas,"],["dizendo:","saying:"]]},
  {num:2,words:[["Levanta-te,","Raises-up-you,"],["e","and"],["vai","goes"],["à","to-the"],["grande","great"],["cidade","city"],["de","of"],["Nínive,","Nineveh,"],["e","and"],["proclama","proclaims"],["contra","against"],["ela","it"],["a","the"],["pregação","preaching"],["que","that"],["eu","I"],["te","you"],["digo.","I-say."]]},
  {num:3,words:[["E","And"],["levantou-se","arose"],["Jonas,","Jonas,"],["e","and"],["foi","was"],["a","to"],["Nínive,","Nineveh,"],["segundo","according-to"],["a","the"],["palavra","word"],["do","of-the"],["Senhor.","Lord."],["Era,","Was,"],["pois,","for,"],["Nínive","Nineveh"],["uma","a"],["grande","great"],["cidade","city"],["diante de","before"],["Deus,","God,"],["de","of"],["três","three"],["dias","days"],["de","of"],["caminho.","way."]]},
  {num:4,words:[["E","And"],["começou","began"],["Jonas","Jonas"],["a","to"],["entrar","to-enter"],["pela","by-the"],["cidade","city"],["caminho","way"],["de","of"],["um","a"],["dia,","day,"],["e","and"],["pregava,","preached,"],["e","and"],["dizia:","said:"],["Ainda","Yet"],["quarenta","forty"],["dias,","days,"],["e","and"],["Nínive","Nineveh"],["será","will-be"],["subvertida.","destroy."]]},
  {num:5,words:[["E","And"],["os","the"],["homens","men"],["de","of"],["Nínive","Nineveh"],["creram","they-believed"],["em","in"],["Deus;","God;"],["e","and"],["proclamaram","they-proclaimed"],["um","a"],["jejum,","fasting,"],["e","and"],["vestiram-se","they-clothed-themselves"],["de","of"],["panos","sackcloth"],["de","of"],["saco,","sack,"],["desde o","beginning"],["maior","greater"],["até","until"],["o","the"],["menor.","least."]]},
  {num:6,words:[["Porque","Because"],["essa","that"],["palavra","word"],["chegou","came"],["ao","to-the"],["rei","king"],["de","of"],["Nínive,","Nineveh,"],["e","and"],["levantou-se","arose"],["do","of-the"],["seu","his"],["trono,","throne,"],["e","and"],["tirou","took-away"],["de","of"],["si","himself"],["a","the"],["sua","his"],["capa,","cover,"],["e","and"],["cobriu-se","clad"],["de","of"],["panos","sackcloth"],["de","of"],["saco,","sack,"],["e","and"],["assentou-se","sit down"],["sobre","upon"],["a","the"],["cinza.","ashes."]]},
  {num:7,words:[["E","And"],["fez","made"],["apregoar,","to-brokenhearted,"],["e","and"],["falou-se","spoke-himself"],["em","in"],["Nínive,","Nineveh,"],["pelo","by-the"],["mandado","commandment"],["do rei e","king's"],["dos","of-the"],["seus","his"],["nobres,","nobles,"],["dizendo:","saying:"],["Nem","Nor"],["homens,","men,"],["nem","nor"],["animais,","beasts,"],["nem","nor"],["bois,","oxen,"],["nem","nor"],["ovelhas","sheep"],["provem","they-prove"],["coisa","thing"],["alguma,","some,"],["nem","nor"],["se","if"],["lhes","to-them"],["dê","gives"],["pasto,","pasture,"],["nem","nor"],["bebam","they-drink"],["água.","water."]]},
  {num:8,words:[["Mas","But"],["os","the"],["homens","men"],["e","and"],["os","the"],["animais","beasts"],["estarão","they-will-be"],["cobertos","covered"],["de","of"],["panos","sackcloth"],["de","of"],["saco,","sack,"],["e","and"],["clamarão","they-will-cry"],["fortemente","strongly"],["a","to"],["Deus,","God,"],["e","and"],["se","if"],["converterão","they-will-convert"],["cada","every"],["um","a"],["do","of-the"],["seu","his"],["mau","bad"],["caminho,","way,"],["e","and"],["da","of-the"],["violência","violence"],["que","that"],["há","there-is"],["nas","in-the"],["suas","their"],["mãos.","hands."]]},
  {num:9,words:[["Quem","Who"],["sabe","knows"],["se","himself"],["Deus","God"],["se","himself"],["voltará,","will-return,"],["e","and"],["se","if"],["arrependerá,","melchisedec,"],["e","and"],["se","if"],["apartará","will-divide"],["do","of-the"],["furor","fury"],["da","of-the"],["sua","his"],["ira,","anger,"],["de sorte que","so-that"],["não","not"],["pereçamos?","we-perish?"]]},
  {num:10,words:[["E","And"],["Deus","God"],["viu","saw"],["as","the"],["obras","works"],["deles,","of-them,"],["como se","as-if"],["converteram","they-converted"],["do","of-the"],["seu","their"],["mau","bad"],["caminho;","way;"],["e","and"],["Deus","God"],["se","himself"],["arrependeu","repented"],["do","of-the"],["mal","evil"],["que","that"],["tinha","had"],["dito","said"],["lhes","to-them"],["faria,","should-make,"],["e","and"],["não","not"],["o","it"],["fez.","made."]]}
];
var v4 = [
  {num:1,words:[["E","And"],["desagradou-se","horonite-himself"],["Jonas","Jonas"],["extremamente","extremely"],["disso,","of-that,"],["e","and"],["ficou","remained"],["irado.","angry."]]},
  {num:2,words:[["E","And"],["orou","prayed"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["disse:","said:"],["Ah,","Ah,"],["Senhor!","Lord!"],["Não","Not"],["foi","was"],["essa","that"],["a","the"],["minha","my"],["palavra,","word,"],["estando","being"],["eu","I"],["ainda","yet"],["na","in-the"],["minha","my"],["terra?","land?"],["Por isso","therefore"],["é","is"],["que","that"],["me","me"],["preveni,","I-cautioned,"],["fugindo","fleeing"],["para","for"],["Társis,","Tarshish,"],["pois","for"],["sabia","knew"],["que","that"],["és","you-are"],["Deus","God"],["piedoso,","gracious,"],["e","and"],["misericordioso,","merciful,"],["longânimo","slow"],["e","and"],["grande","great"],["em","in"],["benignidade,","endureth,"],["e","and"],["que","that"],["te","you"],["arrependes","repenteth"],["do","of-the"],["mal.","evil."]]},
  {num:3,words:[["Peço-te,","I-ask-you,"],["pois,","for,"],["ó","O"],["Senhor,","Lord,"],["tira-me","takes-away-me"],["a","the"],["minha","my"],["vida,","life,"],["porque","because"],["melhor","better"],["me","me"],["é","is"],["morrer","to-die"],["do que","than"],["viver.","to-live."]]},
  {num:4,words:[["E","And"],["disse","said"],["o","the"],["Senhor:","Lord:"],["Fazes","You-make"],["bem","good"],["que","that"],["assim","thus"],["te","you"],["ires?","to-go?"]]},
  {num:5,words:[["Jonas,","Jonas,"],["pois,","for,"],["saiu","went-forth"],["da","of-the"],["cidade,","city,"],["e","and"],["assentou-se","sit down"],["ao","to-the"],["oriente","east"],["da","of-the"],["cidade;","city;"],["e","and"],["ali","there"],["fez","made"],["uma","a"],["cabana,","booth,"],["e","and"],["se","if"],["assentou","settled"],["debaixo","under"],["dela,","of-it,"],["à","to-the"],["sombra,","shadow,"],["até","even"],["ver","see"],["o","the"],["que","that"],["aconteceria","would-come-to-pass"],["à","to-the"],["cidade.","city."]]},
  {num:6,words:[["E","And"],["preparou","prepared"],["o","the"],["Senhor","Lord"],["Deus","God"],["uma","a"],["aboboreira,","gourd,"],["e","and"],["a","it"],["fez","made"],["subir","go-up"],["por cima de","above"],["Jonas,","Jonas,"],["para que","that"],["fizesse","made"],["sombra","shadow"],["sobre","upon"],["a","the"],["sua","his"],["cabeça,","head,"],["a fim de","in-order-to"],["o","the"],["livrar","to-free"],["do","of-the"],["seu","his"],["desconforto;","discomfort;"],["e","and"],["Jonas","Jonas"],["se","himself"],["alegrou","gladdened"],["grandemente","greatly"],["por causa da","because-of"],["aboboreira.","gourd."]]},
  {num:7,words:[["Mas","But"],["Deus","God"],["enviou","sent"],["um","a"],["bicho,","worm,"],["no","in-the"],["dia","day"],["seguinte","next"],["ao","to-the"],["subir","go-up"],["da","of-the"],["alva,","dawning,"],["e","and"],["feriu","struck"],["a","the"],["aboboreira,","gourd,"],["e","and"],["ela","it"],["secou.","withered."]]},
  {num:8,words:[["E aconteceu que,","and-it-came-to-pass-that"],["aparecendo","appearing"],["o","the"],["sol,","sun,"],["Deus","God"],["ordenou","commanded"],["um","a"],["vento","wind"],["quente","warm"],["oriental,","east,"],["e","and"],["o","the"],["sol","sun"],["feriu","struck"],["a","the"],["cabeça","head"],["de","of"],["Jonas;","Jonas;"],["e","and"],["ele","he"],["desmaiou,","fainted,"],["e","and"],["desejou","desired"],["com","with"],["toda","all"],["a","the"],["sua","his"],["alma","soul"],["morrer,","to-die,"],["dizendo:","saying:"],["Melhor","Better"],["me","me"],["é","is"],["morrer","to-die"],["do que","than"],["viver.","to-live."]]},
  {num:9,words:[["Então","Then"],["disse","said"],["Deus","God"],["a","to"],["Jonas:","Jonas:"],["Fazes","You-make"],["bem","good"],["que","that"],["assim","thus"],["te","you"],["ires","to-go"],["por causa da","because-of"],["aboboreira?","gourd?"],["E","And"],["ele","he"],["disse:","said:"],["Faço","I-make"],["bem","good"],["em","in"],["irar-me","abhorred-me"],["até","until"],["a","the"],["morte.","death."]]},
  {num:10,words:[["E","And"],["disse","said"],["o","the"],["Senhor:","Lord:"],["Tiveste","You-had"],["tu","you"],["compaixão","compassion"],["da","of-the"],["aboboreira,","gourd,"],["na","in-the"],["qual","which"],["não","not"],["trabalhaste,","you-labor,"],["nem","nor"],["a","it"],["fizeste","you-made"],["crescer,","to-grow,"],["que","that"],["numa","in-a"],["noite","night"],["nasceu,","born,"],["e","and"],["numa","in-a"],["noite","night"],["pereceu;","perished;"]]},
  {num:11,words:[["E","And"],["não","not"],["hei","I-have"],["de","of"],["eu","I"],["ter","have"],["compaixão","compassion"],["da","of-the"],["grande","great"],["cidade","city"],["de","of"],["Nínive,","Nineveh,"],["em","in"],["que","that"],["estão","they-are"],["mais","more"],["de","of"],["cento","hundred"],["e","and"],["vinte","twenty"],["mil","thousand"],["homens","men"],["que","that"],["não","not"],["sabem","they-know"],["discernir","discern"],["entre","between"],["a","the"],["sua","their"],["mão","hand"],["direita","right"],["e","and"],["a","the"],["sua","their"],["mão","hand"],["esquerda,","left,"],["e","and"],["muitos","many"],["animais?","beasts?"]]}
];
renderVerseSet(v1, 'jon-ch1-verses');
renderVerseSet(v2, 'jon-ch2-verses');
renderVerseSet(v3, 'jon-ch3-verses');
renderVerseSet(v4, 'jon-ch4-verses');
})();
