(function() {
var v1 = [
  {num:1,words:[["Judas,","Judas,"],["servo","servant"],["de","of"],["Jesus","Jesus"],["Cristo,","Christ,"],["e","and"],["irmão","brother"],["de","of"],["Tiago,","James,"],["aos","to-the"],["chamados,","called,"],["santificados","sanctified"],["pelo","by-the"],["Deus","God"],["Pai,","Father,"],["e","and"],["preservados","preserved"],["por","by"],["Jesus","Jesus"],["Cristo:","Christ:"]]},
  {num:2,words:[["Misericórdia,","Mercy,"],["e","and"],["paz,","peace,"],["e","and"],["amor","love"],["vos","you"],["sejam","they-are"],["multiplicados.","multiply."]]},
  {num:3,words:[["Amados,","Beloved,"],["procurando","seeking"],["eu","I"],["escrever-vos","write-you"],["com","with"],["toda","every"],["a","to"],["diligência","diligence"],["acerca","concerning"],["da","of-the"],["salvação","salvation"],["comum,","common,"],["tive","I-had"],["por","by"],["necessidade","need"],["escrever-vos,","write-you,"],["e","and"],["exortar-vos","admonish-you"],["a","to"],["batalhar","battle"],["pela","by-the"],["fé","faith"],["que","that"],["uma","a"],["vez","occasion"],["foi","was"],["entregue","betrays"],["aos","to-the"],["santos.","Seneca."]]},
  {num:4,words:[["Porque","Because"],["se","if"],["introduziram","they-entered"],["alguns,","some,"],["que","that"],["já","already"],["dantes","of-ahead"],["estavam","they-were"],["marcados","define"],["para","for"],["esta","this"],["mesma","same"],["condenação,","damnation,"],["homens","men"],["ímpios,","wicked,"],["que","that"],["convertem","they-convert"],["em","in"],["dissolução","dissolution"],["a","to"],["graça","grace"],["de","of"],["Deus,","God,"],["e","and"],["negam","they-deny"],["a","to"],["Deus,","God,"],["único","alone"],["Soberano","Sovereign"],["e","and"],["Senhor","Lord"],["nosso,","our,"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:5,words:[["Porém","But"],["quero","I-will"],["lembrar-vos,","caution-you,"],["como","as"],["a","to"],["quem","who"],["já","already"],["uma","a"],["vez","occasion"],["soube","knew"],["isto,","it,"],["que,","that,"],["havendo","having"],["o","the"],["Senhor","Lord"],["salvo","except"],["um","a"],["povo","people"],["tirando-o","evil-merodach"],["da","of-the"],["terra do","egypt"],["Egito,","Egypt,"],["destruiu","destroyed"],["depois","afterwards"],["os","the"],["que","that"],["não","no"],["creram;","believed;"]]},
  {num:6,words:[["E","And"],["aos","to-the"],["anjos","angels"],["que","that"],["não","no"],["guardaram","kept"],["o","the"],["seu","his"],["estado","state"],["original,","original,"],["mas","but"],["deixaram","forsaken"],["a","to"],["sua","his"],["própria","own"],["habitação,","habitation,"],["reservou","houghed"],["debaixo","under"],["da","of-the"],["escuridão,","darkness,"],["e","and"],["em","in"],["prisões","prison"],["eternas","everlasting"],["até","until"],["o","the"],["juízo","judgment"],["daquele","of-that"],["grande","great"],["dia;","day;"]]},
  {num:7,words:[["Como","As"],["Sodoma","Sodom"],["e","and"],["Gomorra,","Gomorrah,"],["e","and"],["as","the"],["cidades","cities"],["circunvizinhas,","regions,"],["que,","that,"],["havendo","having"],["fornicado","gomorrha"],["como","as"],["aqueles,","those,"],["e","and"],["ido","iddo"],["após","after"],["outra","another"],["carne,","flesh,"],["foram","they-were"],["postas","post"],["como","as"],["exemplo,","example,"],["sofrendo","suffering"],["a","to"],["pena","penalty"],["do","of-the"],["fogo","fire"],["eterno.","everlasting."]]},
  {num:8,words:[["E","And"],["contudo","yet"],["também","also"],["estes,","these,"],["semelhantemente","likely"],["adormecidos,","dormant,"],["contaminam","they-defile"],["a","to"],["carne,","flesh,"],["e","and"],["rejeitam","they-reject"],["a","to"],["dominação,","domination,"],["e","and"],["vituperam","dreamers"],["as","the"],["dignidades.","dignity."]]},
  {num:9,words:[["Porém","But"],["Miguel,","Michael,"],["o","the"],["arcanjo,","archangel,"],["quando","when"],["contendia","contended"],["com","with"],["o","the"],["diabo,","devil,"],["e","and"],["disputava","disputed"],["a","to"],["respeito","concerning"],["do","of-the"],["corpo","body"],["de","of"],["Moisés,","Moses,"],["não","no"],["ousou","dared"],["pronunciar","pronounce"],["juízo","judgment"],["de","of"],["maldição","curse"],["contra","against"],["ele;","he;"],["porém","but"],["disse:","said:"],["O","The"],["Senhor","Lord"],["te","you"],["repreenda.","admonishes."]]},
  {num:10,words:[["Estes,","These,"],["porém,","but,"],["falam","they-speak"],["mal","evil"],["do","of-the"],["que","that"],["não","no"],["sabem;","they-know;"],["e","and"],["o","the"],["que","that"],["naturalmente","naturally"],["conhecem,","they-know,"],["como","as"],["animais","beasts"],["irracionais,","brute,"],["nisso","in-that"],["se","if"],["corrompem.","they-bribe."]]},
  {num:11,words:[["Ai","Ouch"],["deles!","of-them!"],["porque","because"],["entraram","entered"],["pelo","by-the"],["caminho","way"],["de","of"],["Caim,","Cain,"],["e","and"],["foram","they-were"],["levados","captive"],["pelo","by-the"],["erro","error"],["do","of-the"],["galardão","reward"],["de","of"],["Balaão,","Balaam,"],["e","and"],["pereceram","perished"],["pela","by-the"],["contradição","contradiction"],["de","of"],["Coré.","Korah."]]},
  {num:12,words:[["Estes","These"],["são","they-are"],["manchas","spots"],["em","in"],["vossas","your"],["festas","feasts"],["de","of"],["caridade,","charity,"],["banqueteando-se","spots"],["convosco,","with-you,"],["e","and"],["apascentando-se","to-apascentar-se"],["a","to"],["si","himself"],["mesmos","even"],["sem","without"],["temor;","fear;"],["são","they-are"],["nuvens","clouds"],["sem","without"],["água,","water,"],["levadas","carry"],["dos","of-the"],["ventos","winds"],["de","of"],["uma","a"],["a","to"],["outra","another"],["parte;","part;"],["são","they-are"],["como","as"],["árvores","trees"],["murchas,","languisheth,"],["infrutíferas,","spots,"],["duas","two"],["vezes","times"],["mortas,","dead,"],["desarraigadas;","succeedest;"]]},
  {num:13,words:[["Ondas","Waves"],["impetuosas","foaming"],["do","of-the"],["mar,","sea,"],["que","that"],["escumam","foaming"],["as","the"],["suas","his"],["próprias","own"],["abominações;","abominations;"],["estrelas","stars"],["errantes,","erratic,"],["para","for"],["os","the"],["quais","what"],["está","is"],["eternamente","always"],["reservada","destine"],["a","to"],["escuridão","darkness"],["das","of-the"],["trevas.","darkness."]]},
  {num:14,words:[["E","And"],["destes","of-this"],["profetizou","prophesied"],["também","also"],["Enoque,","Enoch,"],["o","the"],["sétimo","seventh"],["depois","afterwards"],["de","of"],["Adão,","Adam,"],["dizendo:","saying:"],["Eis que","behold"],["vem","comes"],["o","the"],["Senhor","Lord"],["com","with"],["milhares","thousands"],["de","of"],["seus","his"],["santos;","Seneca;"]]},
  {num:15,words:[["Para","For"],["executar","execute"],["juízo","judgment"],["contra","against"],["todos","all"],["e","and"],["castigar","punish"],["dentre","from"],["eles","they"],["todos","all"],["os","the"],["ímpios,","wicked,"],["por","by"],["todas","things"],["as","the"],["suas","his"],["obras","works"],["de","of"],["impiedade,","wickedness,"],["que","that"],["impiamente","wickedly"],["cometeram,","they-committed,"],["e","and"],["por","by"],["todas","things"],["as","the"],["duras","you-lasts"],["palavras","words"],["que","that"],["os","the"],["ímpios","wicked"],["pecadores","sinners"],["disseram","they-said"],["contra","against"],["ele.","he."]]},
  {num:16,words:[["Estes","These"],["são","they-are"],["murmuradores,","murmurer,"],["queixosos","cheekful"],["da","of-the"],["sua","his"],["sorte,","lot,"],["andando","walking"],["segundo as suas","families"],["concupiscências,","lusts,"],["e","and"],["cuja","whose"],["boca","mouth"],["fala","speech"],["coisas","things"],["muito","much"],["arrogantes,","arrogant,"],["admirando","I-admire"],["as","the"],["pessoas","persons"],["por","by"],["causa","sake"],["do","of-the"],["proveito.","profit."]]},
  {num:17,words:[["Mas","But"],["vós,","you,"],["amados,","beloved,"],["lembrai-vos","remember"],["das","of-the"],["palavras","words"],["que","that"],["vos","you"],["foram","they-were"],["preditas","forecast"],["pelos","by-the"],["apóstolos","apostles"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo;","Christ;"]]},
  {num:18,words:[["Como","As"],["vos","you"],["diziam","they-said"],["que","that"],["haveria","should-have"],["escarnecedores","scorners"],["nos","us"],["últimos","last"],["tempos","times"],["que","that"],["andariam","they-should-walk"],["segundo as suas","families"],["ímpias","wicked"],["concupiscências.","lusts."]]},
  {num:19,words:[["Estes","These"],["são","they-are"],["os","the"],["que","that"],["causam","they-correspondence"],["divisões,","divisions,"],["sensuais,","sensual,"],["que","that"],["não","no"],["têm","they-have"],["o","the"],["Espírito.","Spirit."]]},
  {num:20,words:[["Mas","But"],["vós,","you,"],["amados,","beloved,"],["edificando-vos","I-build-you"],["a","to"],["vós","you"],["mesmos","even"],["sobre","upon"],["a","to"],["vossa","your"],["santíssima","holy"],["fé,","faith,"],["orando","praying"],["no","in-the"],["Espírito","Spirit"],["Santo,","Holy,"]]},
  {num:21,words:[["Conservai-vos","To-conservar-se"],["a","to"],["vós","you"],["mesmos","even"],["no","in-the"],["amor","love"],["de","of"],["Deus,","God,"],["esperando","waiting"],["a","to"],["misericórdia","mercy"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["para","for"],["a","to"],["vida","life"],["eterna.","eternal."]]},
  {num:22,words:[["E","And"],["apiedai-vos","difference"],["de","of"],["alguns","some"],["que","that"],["estão","they-are"],["na","in-the"],["dúvida;","doubt;"]]},
  {num:23,words:[["Mas","But"],["salvai","save"],["os","the"],["outros","another"],["por","by"],["temor,","fear,"],["e","and"],["arrebatai-os","snap up-the"],["do","of-the"],["fogo,","fire,"],["odiando","hating"],["até","until"],["a","to"],["roupa","garment"],["manchada","soil"],["da","of-the"],["carne.","flesh."]]},
  {num:24,words:[["Ora,","Now,"],["àquele","to-that"],["que","that"],["é","is"],["poderoso","mighty"],["para","for"],["vos","you"],["guardar","keep"],["de","of"],["tropeçar,","stumble,"],["e","and"],["apresentar-vos","exhibit-you"],["irrepreensíveis,","blameless,"],["com","with"],["alegria,","joy,"],["perante","before"],["a","to"],["sua","his"],["glória,","glory,"]]},
  {num:25,words:[["Ao","To-the"],["único","alone"],["Deus,","God,"],["Salvador","Saver"],["nosso,","our,"],["por","by"],["Jesus","Jesus"],["Cristo,","Christ,"],["nosso","our"],["Senhor,","Lord,"],["seja","is"],["glória","glory"],["e","and"],["majestade,","majesty,"],["domínio","dominion"],["e","and"],["poder,","can,"],["agora,","now,"],["e","and"],["para todo o sempre.","for-ever-and-ever"],["Amém.","Amen."]]}
];
renderVerseSet(v1, 'jud-ch1-verses');
})();
