(function() {
var v1 = [
  {num:1,words:[["Peso","Weight"],["da","of-the"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["contra","against"],["Israel,","Israel,"],["pelo","by-the"],["ministério","ministry"],["de","of"],["Malaquias.","Malachi."]]},
  {num:2,words:[["Eu","I"],["vos","you"],["amei,","I-mammon,"],["diz","says"],["o","the"],["Senhor;","Lord;"],["mas","but"],["vós","you"],["dizeis:","you-say:"],["Em","In"],["que","that"],["nos","us"],["amastes?","you-mammon?"],["Não","Not"],["foi","was"],["Esaú","Esau"],["irmão","brother"],["de","of"],["Jacó?","Jacob?"],["disse","said"],["o","the"],["Senhor;","Lord;"],["todavia","nevertheless"],["amei","I-mammon"],["Jacó,","Jacob,"]]},
  {num:3,words:[["E","And"],["odiei","I-hated"],["Esaú;","Esau;"],["e","and"],["fiz","I-made"],["dos","of-the"],["seus","his"],["montes","mountains"],["uma","a"],["assolação,","desolation,"],["e","and"],["dei","I-gave"],["a","the"],["sua","his"],["herança","inheritance"],["aos","to-the"],["chacais","dragons"],["do","of-the"],["deserto.","wilderness."]]},
  {num:4,words:[["Ainda que","although"],["Edom","Edom"],["diga:","says:"],["Arruinados","Damaged"],["estamos,","we-are,"],["porém","but"],["tornaremos","we-will-become"],["a","to"],["edificar","build"],["os","the"],["lugares","places"],["desertos;","wildernesses;"],["assim diz","thus-saith"],["o Senhor dos","hosts"],["Exércitos:","Armies:"],["Eles","They"],["edificarão,","they-will-build,"],["e","and"],["eu","I"],["destruirei;","I-will-destroy;"],["e","and"],["lhes","to-them"],["chamarão:","they-will-call:"],["termo","border"],["de","of"],["impiedade,","wickedness,"],["e","and"],["povo","people"],["contra","against"],["quem","who"],["o","the"],["Senhor","Lord"],["está","is"],["irado","angry"],["para sempre.","for-ever"]]},
  {num:5,words:[["E","And"],["os","the"],["vossos","your"],["olhos","eyes"],["o","the"],["verão,","summer,"],["e","and"],["direis:","you-will-say:"],["O","The"],["Senhor","Lord"],["seja","is"],["engrandecido","magnified"],["para","for"],["além","beyond"],["dos","of-the"],["termos","coasts"],["de","of"],["Israel.","Israel."]]},
  {num:6,words:[["O","The"],["filho","son"],["honrará","will-horseback"],["a","to"],["seu","his"],["pai,","father,"],["e","and"],["o","the"],["servo,","servant,"],["ao","to-the"],["seu","his"],["senhor;","lord;"],["e","and"],["se","if"],["eu","I"],["sou","I-am"],["pai,","father,"],["onde","where"],["está","is"],["a","the"],["minha","my"],["honra?","honour?"],["e","and"],["se","if"],["eu","I"],["sou","I-am"],["o","the"],["senhor,","lord,"],["onde","where"],["está","is"],["o","the"],["meu","my"],["temor?","fear?"],["diz","says"],["o Senhor dos","hosts"],["Exércitos","Armies"],["a","to"],["vós,","you,"],["ó","O"],["sacerdotes,","priests,"],["que","that"],["desprezais","you-mammon"],["o","the"],["meu","my"],["nome;","name;"],["mas","but"],["vós","you"],["dizeis:","you-say:"],["Em","In"],["que","that"],["desprezamos","we-mammon"],["nós","we"],["o","the"],["teu","your"],["nome?","name?"]]},
  {num:7,words:[["Ofereceis","You-dedicate"],["sobre","upon"],["o","the"],["meu","my"],["altar","altar"],["pão","bread"],["imundo,","unclean,"],["e","and"],["dizeis:","you-say:"],["Em","In"],["que","that"],["te","you"],["profanamos?","we-profane?"],["Nisto","In-this"],["que","that"],["dizeis:","you-say:"],["A","The"],["mesa","table"],["do","of-the"],["Senhor","Lord"],["é","is"],["desprezível.","contemptible."]]},
  {num:8,words:[["Porque","Because"],["quando","when"],["trazeis","you-bring"],["animal","beast"],["cego","blind"],["para","for"],["o","the"],["sacrificardes,","lame,"],["não","not"],["é","is"],["isso","that"],["mau?","bad?"],["e","and"],["quando","when"],["ofereceis","you-dedicate"],["animal","beast"],["coxo","lame"],["ou","or"],["o","the"],["enfermo,","sick,"],["não","not"],["é","is"],["isso","that"],["mau?","bad?"],["Ora,","Now,"],["apresenta-o","exhibits-it"],["ao","to-the"],["teu","your"],["príncipe;","prince;"],["porventura","perchance"],["terá","will-have"],["ele","he"],["agrado","I-please"],["em","in"],["ti?","you?"],["ou","or"],["aceitará","will-share"],["ele","he"],["a","the"],["tua","your"],["pessoa?","person?"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:9,words:[["Agora,","Now,"],["pois,","for,"],["suplicai","beseech"],["o","the"],["favor","favor"],["de","of"],["Deus,","God,"],["e","and"],["ele","he"],["terá","will-have"],["piedade","pity"],["de","of"],["nós;","we;"],["isto","this"],["veio","came"],["da","of-the"],["vossa","your"],["mão;","hand;"],["aceitará","will-share"],["ele","he"],["a","the"],["vossa","your"],["pessoa?","person?"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:10,words:[["Quem","Who"],["há","there-is"],["também","also"],["entre","among"],["vós","you"],["que","that"],["feche","twinkling"],["as","the"],["portas","gates"],["por","by"],["nada?","nothing?"],["e","and"],["não","not"],["acendeis","you-kindle"],["por","by"],["nada","nothing"],["o","the"],["fogo","fire"],["do","of-the"],["meu","my"],["altar.","altar."],["Eu","I"],["não","not"],["tenho","I-have"],["prazer","pleasure"],["em","in"],["vós,","you,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Armies,"],["nem","nor"],["aceitarei","I-will-share"],["da","of-the"],["vossa","your"],["mão","hand"],["a","the"],["oblação.","dog's."]]},
  {num:11,words:[["Mas","But"],["desde o","beginning"],["nascente","head"],["do","of-the"],["sol","sun"],["até","until"],["o","the"],["poente","occident"],["será","will-be"],["grande","great"],["o","the"],["meu","my"],["nome","name"],["entre","among"],["as","the"],["nações;","nations;"],["e","and"],["em","in"],["todo","every"],["lugar","place"],["se","himself"],["oferecerá","will-dedicate"],["ao","to-the"],["meu","my"],["nome","name"],["incenso","incense"],["e","and"],["uma","a"],["oblação","dog's"],["pura;","pure;"],["porque","because"],["o","the"],["meu","my"],["nome","name"],["será","will-be"],["grande","great"],["entre","among"],["as","the"],["nações,","nations,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:12,words:[["Mas","But"],["vós","you"],["o","it"],["profanais,","you-profane,"],["quando","when"],["dizeis:","you-say:"],["A","The"],["mesa","table"],["do","of-the"],["Senhor","Lord"],["é","is"],["imunda;","unclean;"],["e","and"],["quanto","as"],["ao","to-the"],["seu","his"],["produto,","product,"],["sua","his"],["comida","meat"],["é","is"],["desprezível.","contemptible."]]},
  {num:13,words:[["E","And"],["dizeis:","you-say:"],["Eis","Behold"],["aqui,","here,"],["que","that"],["canseira!","stoopeth!"],["E","And"],["o","it"],["lançastes","you-cast"],["ao","to-the"],["desprezo,","contempt,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos;","Armies;"],["vós","you"],["também","also"],["ofereceis","you-dedicate"],["o","the"],["roubado,","plundered,"],["e","and"],["o","the"],["coxo,","lame,"],["e","and"],["o","the"],["enfermo,","sick,"],["e","and"],["fazeis","you-make"],["a","the"],["oferta;","offering;"],["ser-me-á","will-be-me"],["aceito","I-accepted"],["isso","that"],["de","of"],["vossa","your"],["mão?","hand?"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:14,words:[["Pois","For"],["maldito","cursed"],["seja","is"],["o","the"],["enganador","deceiver"],["que,","that,"],["tendo","having"],["no","in-the"],["seu","his"],["rebanho","flock"],["um","a"],["animal,","beast,"],["promete","promises"],["e","and"],["oferece","dedicates"],["ao","to-the"],["Senhor","Lord"],["o","the"],["que","that"],["é","is"],["corrompido;","corrupted;"],["porque","because"],["eu","I"],["sou","I-am"],["grande","great"],["Rei,","King,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Armies,"],["o","the"],["meu","my"],["nome","name"],["será","will-be"],["temível","fearful"],["entre","among"],["as","the"],["nações.","nations."]]}
];
var v2 = [
  {num:1,words:[["Agora,","Now,"],["pois,","for,"],["ó","O"],["sacerdotes,","priests,"],["este","this"],["mandamento","commandment"],["é","is"],["para","for"],["vós.","you."]]},
  {num:2,words:[["Se","If"],["não","not"],["o","it"],["ouvirdes,","to-hear,"],["e","and"],["se","if"],["não","not"],["propuserdes","you-will-propose"],["no","in-the"],["coração","heart"],["dar","give"],["honra","honour"],["ao","to-the"],["meu","my"],["nome,","name,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Armies,"],["enviarei","I-will-send"],["a","the"],["maldição","curse"],["contra","against"],["vós,","you,"],["e","and"],["amaldiçoarei","I-will-curse"],["as","the"],["vossas","your"],["bênçãos;","blessings;"],["e","and"],["também","also"],["já","already"],["as","them"],["amaldiçoei,","I-cursed,"],["porque","because"],["vós","you"],["não","not"],["pondes","you-place"],["isso","that"],["no","in-the"],["coração.","heart."]]},
  {num:3,words:[["Eis que","behold"],["repreenderei","I-will-admonish"],["a","the"],["vossa","your"],["semente,","seed,"],["e","and"],["espalharei","I-scatter"],["esterco","I-dung"],["sobre","upon"],["os","the"],["vossos","your"],["rostos,","faces,"],["o","the"],["esterco","I-dung"],["das","of-the"],["vossas","your"],["festas;","feasts;"],["e","and"],["com","with"],["ele","it"],["sereis","you-will-be"],["levados.","brought."]]},
  {num:4,words:[["Então","Then"],["sabereis","you-will-know"],["que","that"],["eu","I"],["vos","you"],["enviei","I-sent"],["este","this"],["mandamento,","commandment,"],["para que","that"],["o","the"],["meu","my"],["convênio","covenant"],["seja","is"],["com","with"],["Levi,","Levi,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:5,words:[["Meu","My"],["convênio","covenant"],["com","with"],["ele","he"],["foi","was"],["a","the"],["vida","life"],["e","and"],["a","the"],["paz,","peace,"],["e","and"],["eu","I"],["lhas","to-him-them"],["dei","I-gave"],["para","for"],["temor,","fear,"],["e","and"],["ele","he"],["me","me"],["temeu,","feared,"],["e","and"],["assombrou-se","to-assombrar-himself"],["por causa do","because-of"],["meu","my"],["nome.","name."]]},
  {num:6,words:[["A","The"],["lei","law"],["da","of-the"],["verdade","truth"],["esteve","was"],["na","in-the"],["sua","his"],["boca,","mouth,"],["e","and"],["a","the"],["iniquidade","iniquity"],["não","not"],["se","himself"],["achou","found"],["nos","in-the"],["seus","his"],["lábios;","lips;"],["andou","walked"],["comigo","with-me"],["em","in"],["paz","peace"],["e","and"],["em","in"],["retidão,","righteousness,"],["e","and"],["converteu","converted"],["muitos","many"],["da","of-the"],["iniquidade.","iniquity."]]},
  {num:7,words:[["Porque","Because"],["os","the"],["lábios","lips"],["do","of-the"],["sacerdote","priest"],["guardarão","they-will-keep"],["o","the"],["conhecimento,","knowledge,"],["e","and"],["da","of-the"],["sua","his"],["boca","mouth"],["buscarão","they-will-seek"],["a","the"],["lei,","law,"],["porque","because"],["ele","he"],["é","is"],["o","the"],["mensageiro","messenger"],["do","of-the"],["Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:8,words:[["Mas","But"],["vós","you"],["vos","you"],["desviastes","you-bypassed"],["do","of-the"],["caminho,","way,"],["a","to"],["muitos","many"],["fizestes","you-made"],["tropeçar","to-stumble"],["na","in-the"],["lei;","law;"],["corrompestes","you-bribed"],["o","the"],["convênio","covenant"],["de","of"],["Levi,","Levi,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:9,words:[["Por isso","therefore"],["também","also"],["eu","I"],["vos","you"],["fiz","I-made"],["desprezíveis,","contemptible,"],["e","and"],["indignos","unworthy"],["diante de","before"],["todo","every"],["o","the"],["povo,","people,"],["visto que","seeing-that"],["não","not"],["guardastes","you-kept"],["os","the"],["meus","my"],["caminhos,","ways,"],["mas","but"],["fizestes","you-made"],["acepção","persons"],["de","of"],["pessoas","persons"],["na","in-the"],["lei.","law."]]},
  {num:10,words:[["Não","Not"],["temos","we-have"],["nós","we"],["todos","all"],["um","a"],["mesmo","same"],["Pai?","Father?"],["não","not"],["nos","us"],["criou","created"],["um","a"],["mesmo","same"],["Deus?","God?"],["por","by"],["que","that"],["seremos","we-will-be"],["desleais","disloyal"],["cada","every"],["um","a"],["com","with"],["seu","his"],["irmão,","brother,"],["profanando","profaning"],["o","the"],["convênio","covenant"],["de","of"],["nossos","our"],["pais?","fathers?"]]},
  {num:11,words:[["Judá","Judah"],["foi","was"],["desleal,","disloyal,"],["e","and"],["abominação","abomination"],["se","himself"],["cometeu","committed"],["em","in"],["Israel","Israel"],["e","and"],["em","in"],["Jerusalém;","Jerusalem;"],["porque","because"],["Judá","Judah"],["profanou","profaned"],["a","the"],["santidade","holiness"],["do","of-the"],["Senhor,","Lord,"],["a","to"],["qual","which"],["ele","he"],["ama,","love,"],["e","and"],["se","if"],["casou","married"],["com","with"],["a","the"],["filha","daughter"],["de","of"],["deus","god"],["estranho.","alien."]]},
  {num:12,words:[["O","The"],["Senhor","Lord"],["destruirá","will-destroy"],["das","of-the"],["tendas","tents"],["de","of"],["Jacó","Jacob"],["o","the"],["homem","man"],["que","that"],["fizer","will-make"],["isso,","that,"],["o","the"],["que","that"],["vela,","candle,"],["e","and"],["o","the"],["que","that"],["responde,","answers,"],["e","and"],["o","the"],["que","that"],["apresenta","exhibits"],["oferta","offering"],["ao","to-the"],["Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:13,words:[["Também","Also"],["fazeis","you-make"],["esta","this"],["segunda","second"],["coisa:","thing:"],["cobris","you-cover"],["o","the"],["altar","altar"],["do","of-the"],["Senhor","Lord"],["de","of"],["lágrimas,","tears,"],["com","with"],["choros","weeping"],["e","and"],["com","with"],["gemidos;","groaning;"],["de sorte que","so-that"],["ele","he"],["não","not"],["olha","looks"],["mais","more"],["para","for"],["a","the"],["oferta,","offering,"],["nem","nor"],["a","it"],["aceitará","will-share"],["com","with"],["prazer","pleasure"],["da","of-the"],["vossa","your"],["mão.","hand."]]},
  {num:14,words:[["E","And"],["dizeis:","you-say:"],["Por","By"],["quê?","stumblingstone?"],["Porque","Because"],["o","the"],["Senhor","Lord"],["foi","was"],["testemunha","witness"],["entre","between"],["ti","you"],["e","and"],["a","the"],["mulher","dame"],["da","of-the"],["tua","your"],["mocidade,","youth,"],["contra","against"],["a","to"],["qual","which"],["tu","you"],["foste","you-were"],["desleal,","disloyal,"],["sendo","being"],["ela","she"],["a","the"],["tua","your"],["companheira,","companion,"],["e","and"],["a","the"],["mulher","dame"],["do","of-the"],["teu","your"],["convênio.","covenant."]]},
  {num:15,words:[["E","And"],["não","not"],["fez","made"],["ele","he"],["somente","only"],["um,","a,"],["sobejando-lhe","abounding-to-him"],["espírito?","spirit?"],["e","and"],["por","by"],["que","that"],["somente","only"],["este","this"],["um?","a?"],["Ele","He"],["buscava","sought"],["uma","a"],["semente","seed"],["de","of"],["Deus.","God."],["Portanto,","Therefore,"],["guardai-vos","keep-you"],["em","in"],["vosso","your"],["espírito,","spirit,"],["e","and"],["contra","against"],["a","the"],["mulher","dame"],["da","of-the"],["vossa","your"],["mocidade","youth"],["nenhum","none"],["seja","is"],["desleal.","disloyal."]]},
  {num:16,words:[["Porque","Because"],["o","the"],["Senhor","Lord"],["Deus","God"],["de","of"],["Israel","Israel"],["diz","says"],["que","that"],["odeia","hate"],["o","the"],["repúdio,","repudiation,"],["e","and"],["aquele","he"],["que","that"],["encobre","cover"],["a","the"],["violência","violence"],["com","with"],["as","the"],["suas","his"],["vestes,","garments,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos;","Armies;"],["portanto,","therefore,"],["guardai-vos","keep-you"],["em","in"],["vosso","your"],["espírito,","spirit,"],["e","and"],["não","not"],["sejais","you-are"],["desleais.","disloyal."]]},
  {num:17,words:[["Enfadais","You-bore"],["ao","to-the"],["Senhor","Lord"],["com","with"],["vossas","your"],["palavras;","words;"],["e","and"],["ainda","yet"],["dizeis:","you-say:"],["Em","In"],["que","that"],["o","him"],["enfadamos?","we-bore?"],["Nisto","In-this"],["que","that"],["dizeis:","you-say:"],["Qualquer que","whosoever"],["faz","makes"],["o","the"],["mal","evil"],["é","is"],["bom","good"],["aos","to-the"],["olhos","eyes"],["do","of-the"],["Senhor,","Lord,"],["e","and"],["desses","of-that"],["tais","such"],["é","is"],["que","that"],["ele","he"],["se","himself"],["agrada;","pleases;"],["ou:","or:"],["Onde","Where"],["está","is"],["o","the"],["Deus","God"],["do","of-the"],["juízo?","judgment?"]]}
];
var v3 = [
  {num:1,words:[["Eis que","behold"],["eu","I"],["envio","I-send"],["o","the"],["meu","my"],["mensageiro,","messenger,"],["que","that"],["preparará","will-prepare"],["o","the"],["caminho","way"],["diante de","before"],["mim;","me;"],["e","and"],["de repente","suddenly"],["virá","will-come"],["ao","to-the"],["seu","his"],["templo","temple"],["o","the"],["Senhor,","Lord,"],["a","to"],["quem","who"],["vós","you"],["buscais,","you-seek,"],["e","and"],["o","the"],["mensageiro","messenger"],["do","of-the"],["convênio,","covenant,"],["em","in"],["quem","who"],["vos","you"],["deleitais;","malachi;"],["eis que","behold"],["ele","he"],["vem,","comes,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:2,words:[["Mas","But"],["quem","who"],["suportará","will-abide"],["o","the"],["dia","day"],["da","of-the"],["sua","his"],["vinda?","coming?"],["e","and"],["quem","who"],["subsistirá,","will-subsist,"],["quando","when"],["ele","he"],["aparecer?","to-appear?"],["Porque","Because"],["ele","he"],["será","will-be"],["como","as"],["o","the"],["fogo","fire"],["do","of-the"],["ourives","goldsmith"],["e","and"],["como","as"],["o","the"],["sabão","soap"],["dos","of-the"],["lavandeiros.","refiner's."]]},
  {num:3,words:[["E","And"],["assentar-se-á,","will-settle-himself,"],["refinando","refining"],["e","and"],["purificando","cleansing"],["a","the"],["prata;","silver;"],["e","and"],["purificará","will-cleanse"],["os","the"],["filhos","children"],["de","of"],["Levi,","Levi,"],["e","and"],["os","them"],["refinará","will-refine"],["como","as"],["ouro","gold"],["e","and"],["como","as"],["prata;","silver;"],["então","then"],["ao","to-the"],["Senhor","Lord"],["trarão","they-will-bring"],["oferta","offering"],["em","in"],["justiça.","righteousness."]]},
  {num:4,words:[["E","And"],["a","to"],["oferta de","meat"],["Judá","Judah"],["e","and"],["de","of"],["Jerusalém","Jerusalem"],["será","will-be"],["suave","sweet"],["ao","to-the"],["Senhor,","Lord,"],["como","as"],["nos","in-the"],["dias","days"],["antigos,","ancient,"],["e","and"],["como","as"],["nos","in-the"],["primeiros","first"],["anos.","years."]]},
  {num:5,words:[["E","And"],["chegar-me-ei","I-will-come-me"],["a","the"],["vós","you"],["para","for"],["juízo,","judgment,"],["e","and"],["serei","I-will-be"],["uma","a"],["testemunha","witness"],["veloz","fast"],["contra","against"],["os","the"],["feiticeiros","sorcerers"],["e","and"],["contra","against"],["os","the"],["adúlteros,","adulterers,"],["e","and"],["contra","against"],["os","the"],["que","that"],["juram","they-swear"],["falsamente,","falsely,"],["e","and"],["contra","against"],["os","the"],["que","that"],["defraudam","they-defraud"],["o","the"],["jornaleiro","hireling"],["em","in"],["seu","his"],["salário,","wages,"],["e","and"],["a","the"],["viúva,","widow,"],["e","and"],["o","the"],["órfão,","fatherless,"],["que","that"],["pervertem","pant"],["o","the"],["direito","right"],["do","of-the"],["estrangeiro,","stranger,"],["e","and"],["não","not"],["me","me"],["temem,","they-fear,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:6,words:[["Porque","Because"],["eu,","I,"],["o","the"],["Senhor,","Lord,"],["não","not"],["mudo;","dumb;"],["por isso","therefore"],["vós,","you,"],["ó","O"],["filhos","children"],["de","of"],["Jacó,","Jacob,"],["não","not"],["sois","you-are"],["consumidos.","consumed."]]},
  {num:7,words:[["Desde","Since"],["os","the"],["dias","days"],["de","of"],["vossos","your"],["pais","fathers"],["vos","you"],["desviastes","you-bypassed"],["dos","of-the"],["meus","my"],["estatutos,","statutes,"],["e","and"],["não","not"],["os","them"],["guardastes;","you-kept;"],["retornai","return"],["a","to"],["mim,","me,"],["e","and"],["eu","I"],["retornarei","I-will-return"],["a","to"],["vós,","you,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos;","Armies;"],["mas","but"],["vós","you"],["dizeis:","you-say:"],["Em","In"],["que","that"],["havemos","exist"],["de","of"],["retornar?","return?"]]},
  {num:8,words:[["Roubará","Will-plunder"],["o","the"],["homem","man"],["a","to"],["Deus?","God?"],["Porque","Because"],["vós","you"],["me","me"],["roubais,","you-plunder,"],["e","and"],["dizeis:","you-say:"],["Em","In"],["que","that"],["te","you"],["roubamos?","we-plunder?"],["Nos","In-the"],["dízimos","tithes"],["e","and"],["nas","in-the"],["ofertas.","offerings."]]},
  {num:9,words:[["Com","With"],["maldição","curse"],["sois","you-are"],["amaldiçoados,","cursed,"],["porque","because"],["me","me"],["roubais","you-plunder"],["a","to"],["mim,","me,"],["sim,","yea,"],["toda","all"],["a","the"],["nação.","nation."]]},
  {num:10,words:[["Trazei","Bring"],["todos","all"],["os","the"],["dízimos","tithes"],["à","to-the"],["casa","house"],["do","of-the"],["tesouro,","treasure,"],["para que","that"],["haja","has"],["mantimento","food"],["na","in-the"],["minha","my"],["casa,","house,"],["e","and"],["provai-me","prove-me"],["nisto,","in-this,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Armies,"],["se","if"],["eu","I"],["não","not"],["vos","you"],["abrir","to-open"],["as","the"],["janelas","windows"],["do","of-the"],["céu,","heaven,"],["e","and"],["não","not"],["derramar","to-pour"],["sobre","upon"],["vós","you"],["uma","a"],["bênção","blessing"],["tal,","such,"],["até que","until"],["não","not"],["haja","has"],["mais","more"],["lugar","place"],["para","for"],["a","to"],["recolherdes.","to-clauda."]]},
  {num:11,words:[["E","And"],["por causa de","because-of"],["vós","you"],["repreenderei","I-will-admonish"],["o","the"],["devorador,","devourser,"],["para que","that"],["não","not"],["vos","you"],["destrua","destroys"],["o","the"],["fruto","fruit"],["da","of-the"],["terra;","ground;"],["e","and"],["a","the"],["vide","vine"],["no","in-the"],["campo","field"],["não","not"],["vos","you"],["será","will-be"],["estéril,","barren,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:12,words:[["E","And"],["todas","all"],["as","the"],["nações","nations"],["vos","you"],["chamarão","they-will-call"],["bem-aventurados;","blessed;"],["porque","because"],["vós","you"],["sereis","you-will-be"],["uma","a"],["terra","land"],["deleitosa,","collectivelyful,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:13,words:[["As","The"],["vossas","your"],["palavras","words"],["foram","they-were"],["duras","you-lasts"],["contra","against"],["mim,","me,"],["diz","says"],["o","the"],["Senhor;","Lord;"],["mas","but"],["vós","you"],["dizeis:","you-say:"],["Que","That"],["falamos","we-speak"],["contra","against"],["ti?","you?"]]},
  {num:14,words:[["Vós","You"],["dizeis:","you-say:"],["Inútil","Needless"],["é","is"],["servir","to-serve"],["a","to"],["Deus;","God;"],["que","that"],["nos","us"],["aproveita","profits"],["termos","coasts"],["guardado","kept"],["os","the"],["seus","his"],["preceitos,","precepts,"],["e","and"],["andarmos","to-walk"],["pesarosos","inso"],["diante","before"],["do","of-the"],["Senhor dos","hosts"],["Exércitos?","Armies?"]]},
  {num:15,words:[["Ora,","Now,"],["pois,","for,"],["nós","we"],["reputamos","uncomely"],["por","by"],["bem-aventurados","blessed"],["os","the"],["soberbos;","proud;"],["também","also"],["os","the"],["que","that"],["cometem","they-commit"],["impiedade","wickedness"],["se","themselves"],["edificam;","they-build;"],["também","also"],["tentam","they-tempt"],["a","to"],["Deus,","God,"],["e","and"],["escapam.","they-escape."]]},
  {num:16,words:[["Então","Then"],["aqueles","those"],["que","that"],["temem","they-fear"],["ao","to-the"],["Senhor","Lord"],["falam","they-speak"],["um","a"],["com","with"],["o","the"],["outro;","another;"],["e","and"],["o","the"],["Senhor","Lord"],["atenta","assaults"],["e","and"],["ouve;","hears;"],["e","and"],["há","there-is"],["um","a"],["livro","book"],["de","of"],["recordações","inspiration"],["escrito","written"],["diante","before"],["dele,","of-him,"],["para","for"],["os","the"],["que","that"],["temem","they-fear"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["para","for"],["os","the"],["que","that"],["se","themselves"],["lembram","they-remember"],["do","of-the"],["seu","his"],["nome.","name."]]},
  {num:17,words:[["E","And"],["eles","they"],["serão","they-will-be"],["meus,","my,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Armies,"],["naquele","in-that"],["dia","day"],["que","that"],["farei","I-will-make"],["deles","of-them"],["minha","my"],["propriedade;","property;"],["poupá-los-ei,","I-will-avoid-them,"],["como","as"],["um","a"],["homem","man"],["poupa","avoids"],["seu","his"],["filho,","son,"],["que","that"],["o","him"],["serve.","serves."]]},
  {num:18,words:[["Então","Then"],["voltareis","you-will-return"],["e","and"],["vereis","you-will-see"],["a","the"],["diferença","difference"],["entre","between"],["o","the"],["justo","fair"],["e","and"],["o","the"],["ímpio,","wicked,"],["entre","between"],["o","the"],["que","that"],["serve","serves"],["a","to"],["Deus,","God,"],["e","and"],["o","the"],["que","that"],["não","not"],["o","him"],["serve.","serves."]]}
];
var v4 = [
  {num:1,words:[["Porque","Because"],["eis que","behold"],["aquele","that"],["dia","day"],["vem","comes"],["ardendo","glowing"],["como","as"],["fornalha;","furnace;"],["todos","all"],["os","the"],["soberbos,","proud,"],["e","and"],["todos","all"],["os","the"],["que","that"],["cometem","they-commit"],["impiedade","wickedness"],["serão","they-will-be"],["como","as"],["a","the"],["palha;","straw;"],["e","and"],["o","the"],["dia","day"],["que","that"],["está","is"],["para","to"],["vir","come"],["os","the"],["abrasará,","will-scorch,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Armies,"],["de modo que","so-that"],["não","not"],["lhes","to-them"],["deixará","will-leave"],["nem","nor"],["raiz","root"],["nem","nor"],["ramo.","branch."]]},
  {num:2,words:[["Mas","But"],["a","to"],["vós,","you,"],["que","that"],["temeis","you-fear"],["o","the"],["meu","my"],["nome,","name,"],["o","the"],["sol","sun"],["da","of-the"],["justiça","righteousness"],["nascerá,","will-born,"],["e","and"],["trará","will-bring"],["cura","healing"],["debaixo","under"],["das","of-the"],["suas","his"],["asas;","wings;"],["e","and"],["saireis,","you-will-go-forth,"],["e","and"],["crescereis","you-will-grow"],["como","as"],["os","the"],["bezerros","calf"],["do","of-the"],["cevadouro.","stall."]]},
  {num:3,words:[["E","And"],["pisareis","you-will-crush"],["os","the"],["ímpios,","wicked,"],["porque","because"],["se","if"],["farão","they-will-make"],["cinza","ashes"],["debaixo","under"],["das","of-the"],["plantas","you-plant"],["de","of"],["vossos","your"],["pés,","feet,"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["eu","I"],["fizer","will-make"],["isso,","that,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos.","Armies."]]},
  {num:4,words:[["Lembrai-vos","Remember"],["da","of-the"],["lei","law"],["de","of"],["Moisés,","Moses,"],["meu","my"],["servo,","servant,"],["que","that"],["lhe","to-him"],["prescrevi","I-commanded"],["em","in"],["Horebe","Horeb"],["para","for"],["todo","every"],["o","the"],["Israel,","Israel,"],["dos","of-the"],["estatutos","statutes"],["e","and"],["juízos.","judgments."]]},
  {num:5,words:[["Eis que","behold"],["eu","I"],["vos","you"],["envio","I-send"],["o","the"],["profeta","prophet"],["Elias,","Elias,"],["antes que","before"],["venha","comes"],["o","the"],["grande","great"],["e","and"],["terrível","abysmal"],["dia","day"],["do","of-the"],["Senhor;","Lord;"]]},
  {num:6,words:[["E","And"],["ele","he"],["converterá","will-convert"],["o","the"],["coração","heart"],["dos","of-the"],["pais","fathers"],["aos","to-the"],["filhos,","children,"],["e","and"],["o","the"],["coração","heart"],["dos","of-the"],["filhos","children"],["a","to"],["seus","their"],["pais;","fathers;"],["para que","that"],["eu","I"],["não","not"],["venha,","comes,"],["e","and"],["fira","hurts"],["a","the"],["terra","earth"],["com","with"],["maldição.","curse."]]}
];
renderVerseSet(v1, 'mal-ch1-verses');
renderVerseSet(v2, 'mal-ch2-verses');
renderVerseSet(v3, 'mal-ch3-verses');
renderVerseSet(v4, 'mal-ch4-verses');
})();
