(function() {
var v1 = [
  {num:1,words:[["Palavra","Word"],["do","of-the"],["Senhor,","Lord,"],["que","that"],["veio","came"],["a","to"],["Miqueias,","Morasthite,"],["morastita,","morasthite,"],["nos","us"],["dias","days"],["de","of"],["Jotão,","Jotham,"],["Acaz","Ahaz"],["e","and"],["Ezequias,","Hezekiah,"],["reis","kings"],["de","of"],["Judá,","Judah,"],["a","to"],["qual","which"],["ele","he"],["viu","saw"],["sobre","upon"],["Samaria","Samaria"],["e","and"],["Jerusalém.","Jerusalem."]]},
  {num:2,words:[["Ouvi,","I-heard,"],["todos","all"],["os","the"],["povos,","nations,"],["atenta","assaults"],["tu,","you,"],["ó","O"],["terra,","land,"],["e","and"],["a","to"],["plenitude","fulness"],["dela,","of-it,"],["e","and"],["seja","is"],["o","the"],["Senhor","Lord"],["Deus","God"],["testemunha","witness"],["contra","against"],["vós,","you,"],["o","the"],["Senhor,","Lord,"],["desde o","beginning"],["templo","temple"],["da","of-the"],["sua","his"],["santidade.","holiness."]]},
  {num:3,words:[["Porque","Because"],["eis que","behold"],["o","the"],["Senhor","Lord"],["está","is"],["para","for"],["sair","exit"],["do","of-the"],["seu","his"],["lugar,","place,"],["e","and"],["descerá,","descend,"],["e","and"],["pisará","will-crush"],["as","the"],["alturas","heights"],["da","of-the"],["terra.","land."]]},
  {num:4,words:[["E","And"],["os","the"],["montes","mountains"],["debaixo","under"],["dele","of-him"],["se","if"],["derreterão,","they-will-melt,"],["e","and"],["os","the"],["vales","valleys"],["se","if"],["fenderão,","they-will-split,"],["como","as"],["a","to"],["cera","cleft"],["diante","before"],["do","of-the"],["fogo,","fire,"],["como","as"],["as","the"],["águas","waters"],["que","that"],["se","if"],["precipitam","they-precipitate"],["num","in-a"],["abismo.","gulf."]]},
  {num:5,words:[["Tudo","Whatsoever"],["isso","that"],["por","by"],["causa","sake"],["da","of-the"],["transgressão","transgression"],["de","of"],["Jacó,","Jacob,"],["e","and"],["dos","of-the"],["pecados","sins"],["da","of-the"],["casa","house"],["de","of"],["Israel.","Israel."],["Qual","Which"],["é","is"],["a","to"],["transgressão","transgression"],["de","of"],["Jacó?","Jacob?"],["Não","No"],["é","is"],["Samaria?","Samaria?"],["E","And"],["quais","what"],["são","they-are"],["os","the"],["altos","places"],["de","of"],["Judá?","Judah?"],["Não","No"],["é","is"],["Jerusalém?","Jerusalem?"]]},
  {num:6,words:[["Por isso","therefore"],["farei","I-will-make"],["de","of"],["Samaria","Samaria"],["um","a"],["montão","heap"],["de","of"],["pedras","stones"],["do","of-the"],["campo,","field,"],["uma","a"],["terra","land"],["de","of"],["plantar","plant"],["vinhas,","vineyards,"],["e","and"],["farei","I-will-make"],["rolar","roll"],["as","the"],["suas","his"],["pedras","stones"],["no","in-the"],["vale,","valley,"],["e","and"],["descobrirei","plantings"],["os","the"],["seus","his"],["fundamentos.","foundations."]]},
  {num:7,words:[["E","And"],["todas","things"],["as","the"],["suas","his"],["imagens","images"],["de","of"],["escultura","graven"],["serão","they-will-be"],["esmiuçadas,","hires,"],["e","and"],["todos","all"],["os","the"],["seus","his"],["salários","wages"],["serão","they-will-be"],["queimados","burned"],["pelo","by-the"],["fogo,","fire,"],["e","and"],["de","of"],["todos","all"],["os","the"],["seus","his"],["ídolos","idols"],["eu","I"],["farei","I-will-make"],["uma","a"],["assolação;","desolation;"],["porque","because"],["da","of-the"],["paga","pays"],["de","of"],["prostitutas","whore"],["os","the"],["ajuntou,","gathered,"],["e","and"],["para","for"],["a","to"],["paga","pays"],["de","of"],["prostitutas","whore"],["voltarão.","they-will-return."]]},
  {num:8,words:[["Por isso","therefore"],["lamentarei,","I-will-regret,"],["e","and"],["uivarei,","I-will-howl,"],["andarei","unshod"],["despojado","spoilest"],["e","and"],["nu;","naked;"],["farei","I-will-make"],["lamentação","lamentation"],["como","as"],["de","of"],["chacais,","dragons,"],["e","and"],["pranto,","mourning,"],["como","as"],["de","of"],["avestruzes.","owls."]]},
  {num:9,words:[["Porque","Because"],["a","to"],["sua","his"],["chaga","wound"],["é","is"],["incurável,","cureless,"],["porque","because"],["chegou","came"],["até","until"],["Judá;","Judah;"],["estendeu-se","comprised"],["até","until"],["a","to"],["porta","exit"],["do","of-the"],["meu","my"],["povo,","people,"],["até","until"],["Jerusalém.","Jerusalem."]]},
  {num:10,words:[["Não","No"],["o","the"],["anuncieis","you-advertise"],["em","in"],["Gate,","Gath,"],["nem","nor"],["choreis","you-weep"],["muito;","much;"],["revolve-te","to-revolver-se"],["no","in-the"],["pó,","dust,"],["na","in-the"],["casa","house"],["de","of"],["Afra.","Aphrah."]]},
  {num:11,words:[["Passa,","Passeth,"],["ó","O"],["moradora","inhabitant"],["de","of"],["Safir,","Saphir,"],["com","with"],["nudez","nakedness"],["vergonhosa;","shameful;"],["a","to"],["moradora","inhabitant"],["de","of"],["Zaanã","Saphir"],["não","no"],["sai","exits"],["para","for"],["fora;","outside;"],["o","the"],["pranto","mourning"],["de","of"],["Bete-Ezel","Saphir"],["tirará","will-deduct"],["de","of"],["vós","you"],["a","to"],["sua","his"],["posição.","rules."]]},
  {num:12,words:[["Porque","Because"],["a","to"],["moradora","inhabitant"],["de","of"],["Marote","Maroth"],["ansiou","yearned"],["intensamente","intensely"],["pelo","by-the"],["bem;","good;"],["porque","because"],["desceu","descended"],["do","of-the"],["Senhor","Lord"],["o","the"],["mal","evil"],["até","until"],["a","to"],["porta","exit"],["de","of"],["Jerusalém.","Jerusalem."]]},
  {num:13,words:[["Ata","Bindeth"],["os","the"],["animais","beasts"],["ligeiros","swifter"],["ao","to-the"],["carro,","chariot,"],["ó","O"],["moradora","inhabitant"],["de","of"],["Laquis","Lachish"],["(esta","(this"],["é","is"],["o","the"],["princípio","beginning"],["do","of-the"],["pecado","sin"],["para","for"],["a","to"],["filha","daughter"],["de","of"],["Sião),","Zion),"],["porque","because"],["em","in"],["ti","you"],["se","if"],["acharam","found"],["as","the"],["transgressões","transgressions"],["de","of"],["Israel.","Israel."]]},
  {num:14,words:[["Por isso","therefore"],["dá","gives"],["presentes","presents"],["a","to"],["Moresete-Gate;","Moresheth-gath;"],["as","the"],["casas","houses"],["de","of"],["Aczibe","Achzib"],["serão","they-will-be"],["casas","houses"],["de","of"],["mentira","lie"],["para","for"],["os","the"],["reis","kings"],["de","of"],["Israel.","Israel."]]},
  {num:15,words:[["Ainda","Yet"],["te","you"],["trarei","I-will-bring"],["um","a"],["herdeiro,","heir,"],["ó","O"],["moradora","inhabitant"],["de","of"],["Maressa;","Mareshah;"],["chegar-se-á","to-chegar-se"],["até","until"],["Adulão,","Adullam,"],["para","for"],["glória","glory"],["de","of"],["Israel.","Israel."]]},
  {num:16,words:[["Faze-te","Become"],["calva,","baldness,"],["e","and"],["tosquia-te,","to-tosquiar-se,"],["por","by"],["causa","sake"],["dos","of-the"],["filhos","children"],["dos","of-the"],["teus","your"],["deleites;","pleasures;"],["alarga","enlarge"],["a","to"],["tua","your"],["calva","baldness"],["como","as"],["a","to"],["águia,","eagle,"],["porque","because"],["de","of"],["ti","you"],["foram","they-were"],["levados","captive"],["cativos.","captives."]]}
];
var v2 = [
  {num:1,words:[["Ai","Ouch"],["daqueles","of-that"],["que","that"],["nas","in-the"],["suas","his"],["camas","beds"],["intentam","they-intend"],["a","to"],["iniquidade,","iniquity,"],["e","and"],["planejam","they-plan"],["o","the"],["mal;","evil;"],["à","to-the"],["luz","light"],["da","of-the"],["alva","dawning"],["o","the"],["põem","they-place"],["em","in"],["obra,","work,"],["porque","because"],["está","is"],["no","in-the"],["poder","can"],["da","of-the"],["sua","his"],["mão!","hand!"]]},
  {num:2,words:[["E","And"],["cobiçam","covet"],["campos,","fields,"],["e","and"],["os","the"],["arrebatam;","they-snap up;"],["e","and"],["casas,","houses,"],["e","and"],["as","the"],["tomam;","they-get;"],["assim","thus"],["fazem","they-make"],["violência","violence"],["a","to"],["um","a"],["homem","man"],["e","and"],["à","to-the"],["sua","his"],["casa,","house,"],["a","to"],["uma","a"],["pessoa","person"],["e","and"],["à","to-the"],["sua","his"],["herança.","inheritance."]]},
  {num:3,words:[["Portanto,","Therefore,"],["assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Eis que","behold"],["intento","intent"],["um","a"],["mal","evil"],["contra","against"],["esta","this"],["família,","family,"],["de","of"],["onde","where"],["não","no"],["tirareis","you-will-deduct"],["o","the"],["vosso","your"],["pescoço,","neck,"],["nem","nor"],["andareis","you-will-walk"],["tão","that much"],["altivos,","lofty,"],["porque","because"],["o","the"],["tempo","time"],["será","will-be"],["mau.","bad."]]},
  {num:4,words:[["Naquele","In-that"],["dia","day"],["se","if"],["levantará","will-hoist"],["um","a"],["provérbio","proverb"],["sobre","upon"],["vós,","you,"],["e","and"],["se","if"],["pranteará","doleful"],["pranto","mourning"],["lastimoso,","luhith,"],["dizendo:","saying:"],["Nós","We"],["estamos","we-are"],["inteiramente","entirely"],["desolados!","waste!"],["a","to"],["porção","portion"],["do","of-the"],["meu","my"],["povo","people"],["ele","he"],["a","to"],["troca!","exchange!"],["como","as"],["ele","he"],["me","me"],["despoja!","spoil!"],["para","for"],["nos","us"],["tirar","deduct"],["os","the"],["nossos","our"],["campos","fields"],["ele","he"],["os","the"],["reparte!","divides!"]]},
  {num:5,words:[["Portanto,","Therefore,"],["não","no"],["terás","you-will-have"],["tu","you"],["na","in-the"],["congregação","congregation"],["do","of-the"],["Senhor","Lord"],["quem","who"],["lance","lasts"],["o","the"],["cordel","line"],["pela","by-the"],["sorte.","lot."]]},
  {num:6,words:[["Não","No"],["profetizeis,","you-prophesy,"],["os","the"],["que","that"],["profetizam,","prophesy,"],["não","no"],["profetizem","they-prophesy"],["deste","of-this"],["modo,","manner,"],["porque","because"],["não","no"],["se","if"],["apartará","will-divide"],["a","to"],["vergonha.","shame."]]},
  {num:7,words:[["Ó","O"],["vós","you"],["que","that"],["sois","you-are"],["chamados","called"],["a","to"],["casa","house"],["de","of"],["Jacó,","Jacob,"],["porventura","perchance"],["se","if"],["tem","has"],["restringido","I-should-abridge"],["o","the"],["Espírito","Spirit"],["do","of-the"],["Senhor?","Lord?"],["são","they-are"],["estas","these"],["as","the"],["suas","his"],["obras?","works?"],["e","and"],["não","no"],["fazem","they-make"],["bem","good"],["as","the"],["minhas","my"],["palavras","words"],["ao","to-the"],["que","that"],["anda","walketh"],["retamente?","uprightly?"]]},
  {num:8,words:[["Mas","But"],["assim como","even-as"],["fora","outside"],["ontem,","yesterday,"],["se","if"],["levantou","arose"],["o","the"],["meu","my"],["povo","people"],["por","by"],["inimigo;","enemy;"],["de","of"],["sobre","upon"],["a","to"],["vestidura","swaddlingband"],["tirastes","you-deducted"],["a","to"],["capa","cover"],["daqueles","of-that"],["que","that"],["passavam","wagging"],["seguros,","safely,"],["como","as"],["os","the"],["que","that"],["voltavam","they-returned"],["da","of-the"],["guerra.","war."]]},
  {num:9,words:[["Lançais","You-vomit"],["fora","outside"],["as","the"],["mulheres","women"],["do","of-the"],["meu","my"],["povo,","people,"],["do","of-the"],["seu","his"],["lar","firebox"],["querido;","dear;"],["das","of-the"],["suas","his"],["crianças","child"],["tirastes","you-deducted"],["o","the"],["meu","my"],["louvor","praise"],["para sempre.","for-ever"]]},
  {num:10,words:[["Levantai-vos,","Arise,"],["pois,","for,"],["e","and"],["andai,","walk,"],["porque","because"],["não","no"],["será","will-be"],["esta","this"],["terra","land"],["o","the"],["descanso;","rest;"],["porquanto","because"],["está","is"],["contaminada,","defile,"],["vos","you"],["corromperá,","will-bribe,"],["e","and"],["isso","that"],["com","with"],["grande","great"],["corrupção.","corruption."]]},
  {num:11,words:[["Se","If"],["houver","will-have"],["alguém","any"],["que","that"],["siga","follows"],["o","the"],["seu","his"],["espírito","spirit"],["de","of"],["falsidade,","falsehood,"],["e","and"],["minta,","pretended,"],["dizendo:","saying:"],["Eu","I"],["te","you"],["profetizarei","I-will-prophesy"],["de","of"],["vinho","wine"],["e","and"],["de","of"],["bebida","beverage"],["forte;","strong;"],["far-se-á,","will-make-himself,"],["então,","said,"],["este","this"],["tal","same"],["o","the"],["profeta","prophet"],["deste","of-this"],["povo.","people."]]},
  {num:12,words:[["Certamente","Certainly"],["te","you"],["ajuntarei","I-will-add"],["todo,","every,"],["ó","O"],["Jacó;","Jacob;"],["certamente","certainly"],["congregarei","halteth"],["o","the"],["restante","remaining"],["de","of"],["Israel;","Israel;"],["pô-lo-ei","bozrah"],["todo","every"],["junto,","adjacent,"],["como","as"],["ovelhas","sheep"],["de","of"],["Bozra;","Bozrah;"],["como","as"],["o","the"],["rebanho","flock"],["no","in-the"],["meio","midst"],["do","of-the"],["seu","his"],["curral,","stable,"],["farão","they-will-make"],["estrondo","noise"],["por","by"],["causa","sake"],["da","of-the"],["multidão","multitude"],["dos","of-the"],["homens.","men."]]},
  {num:13,words:[["Subirá","Ascend"],["diante","before"],["deles","of-them"],["o","the"],["que","that"],["romperá","will-break"],["o","the"],["caminho;","way;"],["eles","they"],["romperão,","they-will-break,"],["e","and"],["entrarão","enter"],["pela","by-the"],["porta,","exit,"],["e","and"],["sairão","they-will-exit"],["por","by"],["ela;","she;"],["e","and"],["o","the"],["rei","king"],["irá","will-go"],["adiante","onward"],["deles,","of-them,"],["e","and"],["o","the"],["Senhor","Lord"],["à","to-the"],["testa","forehead"],["deles.","of-them."]]}
];
var v3 = [
  {num:1,words:[["Mais","Still"],["disse","said"],["eu:","I:"],["Ouvi","I-heard"],["agora","now"],["vós,","you,"],["chefes","authority"],["de","of"],["Jacó,","Jacob,"],["e","and"],["vós,","you,"],["príncipes","princes"],["da","of-the"],["casa","house"],["de","of"],["Israel:","Israel:"],["Porventura","Perchance"],["não","no"],["é","is"],["a","to"],["vós","you"],["que","that"],["pertence","belongeth"],["saber","know"],["o","the"],["direito?","right?"]]},
  {num:2,words:[["A","To"],["vós","you"],["que","that"],["odiais","you-hate"],["o","the"],["bem,","good,"],["e","and"],["amais","you-mammon"],["o","the"],["mal,","evil,"],["que","that"],["lhes","to-them"],["arrancais","you-pick"],["a","to"],["pele","skin"],["de","of"],["cima","above"],["deles,","of-them,"],["e","and"],["a","to"],["sua","his"],["carne,","flesh,"],["de","of"],["cima","above"],["dos","of-the"],["seus","his"],["ossos,","bones,"]]},
  {num:3,words:[["E","And"],["que","that"],["comeis","you-eat"],["a","to"],["carne","flesh"],["do","of-the"],["meu","my"],["povo,","people,"],["e","and"],["lhes","to-them"],["esfolais","chop"],["a","to"],["sua","his"],["pele,","skin,"],["e","and"],["lhes","to-them"],["esmiuçais","chop"],["os","the"],["ossos,","bones,"],["e","and"],["os","the"],["repartis","you-divide"],["como","as"],["para","for"],["a","to"],["panela","pot"],["e","and"],["como","as"],["carne","flesh"],["no","in-the"],["meio","midst"],["do","of-the"],["caldeirão.","boiler."]]},
  {num:4,words:[["Então","Said"],["clamarão","simpleness"],["ao","to-the"],["Senhor,","Lord,"],["mas","but"],["não","no"],["os","the"],["ouvirá,","will-hear,"],["antes","before"],["esconderá","hurled"],["deles","of-them"],["a","to"],["sua","his"],["face","face"],["naquele","in-that"],["tempo,","time,"],["visto que","seeing-that"],["eles","they"],["fizeram","they-made"],["o","the"],["mal","evil"],["com","with"],["as","the"],["suas","his"],["obras.","works."]]},
  {num:5,words:[["Assim diz","thus-saith"],["o","the"],["Senhor","Lord"],["contra","against"],["os","the"],["profetas","prophets"],["que","that"],["fazem","they-make"],["errar","err"],["o","the"],["meu","my"],["povo,","people,"],["que","that"],["mordem","they-bite"],["com","with"],["os","the"],["seus","his"],["dentes,","teeth,"],["e","and"],["clamam","they-cry"],["paz;","peace;"],["mas","but"],["contra","against"],["aquele","that ... over there"],["que","that"],["nada","nothing"],["lhes","to-them"],["dá","gives"],["na","in-the"],["boca","mouth"],["declaram","they-declare"],["guerra.","war."]]},
  {num:6,words:[["Portanto,","Therefore,"],["se","if"],["vos","you"],["fará","will-make"],["noite","night"],["sem","without"],["profecia,","prophecy,"],["e","and"],["vos","you"],["serão","they-will-be"],["trevas","darkness"],["sem","without"],["adivinhação,","divination,"],["e","and"],["se","if"],["porá","will-place"],["o","the"],["sol","sun"],["sobre","upon"],["esses","those"],["profetas,","prophets,"],["e","and"],["o","the"],["dia","day"],["sobre","upon"],["eles","they"],["se","if"],["enegrecerá.","divine."]]},
  {num:7,words:[["E","And"],["os","the"],["videntes","seers"],["se","if"],["envergonharão,","they-will-abash,"],["e","and"],["os","the"],["adivinhos","fortune teller"],["serão","they-will-be"],["humilhados;","confounded;"],["e","and"],["todos","all"],["juntos","together"],["cobrirão","they-will-cover"],["os","the"],["lábios,","lips,"],["porque","because"],["não","no"],["haverá","will-have"],["resposta","answer"],["de","of"],["Deus.","God."]]},
  {num:8,words:[["Mas","But"],["decerto","of course"],["eu","I"],["estou","I-am"],["cheio","full"],["da","of-the"],["força","strength"],["do","of-the"],["Espírito","Spirit"],["do","of-the"],["Senhor,","Lord,"],["e","and"],["cheio","full"],["de","of"],["juízo","judgment"],["e","and"],["ânimo,","courage,"],["para","for"],["anunciar","advertise"],["a","to"],["Jacó","Jacob"],["a","to"],["sua","his"],["transgressão","transgression"],["e","and"],["a","to"],["Israel,","Israel,"],["o","the"],["seu","his"],["pecado.","sin."]]},
  {num:9,words:[["Ouvi","I-heard"],["agora","now"],["isto,","it,"],["vós,","you,"],["chefes","authority"],["da","of-the"],["casa","house"],["de","of"],["Jacó,","Jacob,"],["e","and"],["vós,","you,"],["príncipes","princes"],["da","of-the"],["casa","house"],["de","of"],["Israel,","Israel,"],["que","that"],["abominais","you-abhor"],["o","the"],["juízo","judgment"],["e","and"],["perverteis","wormwood"],["tudo","whatsoever"],["o","the"],["que","that"],["é","is"],["direito,","right,"]]},
  {num:10,words:[["Edificando","I-build"],["Sião","Zion"],["com","with"],["sangue,","blood,"],["e","and"],["Jerusalém,","Jerusalem,"],["com","with"],["injustiça.","injustice."]]},
  {num:11,words:[["Os","The"],["seus","his"],["chefes","authority"],["dão","they-give"],["as","the"],["sentenças","sentence"],["por","by"],["suborno,","I-bribe,"],["e","and"],["os","the"],["seus","his"],["sacerdotes","priests"],["ensinam","they-teach"],["por","by"],["interesse,","interest,"],["e","and"],["os","the"],["seus","his"],["profetas","prophets"],["adivinham","they-forecast"],["por","by"],["dinheiro;","money;"],["e","and"],["ainda","yet"],["se","if"],["encostam","they-lean"],["ao","to-the"],["Senhor,","Lord,"],["dizendo:","saying:"],["Porventura","Perchance"],["não","no"],["está","is"],["o","the"],["Senhor","Lord"],["no","in-the"],["meio","midst"],["de","of"],["nós?","we?"],["Nenhum","None"],["mal","evil"],["nos","us"],["sobrevirá.","will-ensue."]]},
  {num:12,words:[["Portanto,","Therefore,"],["por causa de","because-of"],["vós,","you,"],["Sião","Zion"],["será","will-be"],["lavrada","embroider"],["como","as"],["um","a"],["campo,","field,"],["e","and"],["Jerusalém","Jerusalem"],["se","if"],["tornará","will-become"],["em","in"],["montões","heaps"],["de","of"],["pedras,","stones,"],["e","and"],["o","the"],["monte","mountain"],["desta","of-this"],["casa,","house,"],["em","in"],["altos","places"],["de","of"],["um","a"],["bosque.","forest."]]}
];
var v4 = [
  {num:1,words:[["Mas","But"],["nos","us"],["últimos","last"],["dias","days"],["acontecerá","will-become"],["que","that"],["o","the"],["monte","mountain"],["da","of-the"],["casa","house"],["do","of-the"],["Senhor","Lord"],["será","will-be"],["estabelecido","reckoning"],["no","in-the"],["cume","top"],["dos","of-the"],["montes,","mountains,"],["e","and"],["se","if"],["elevará","will-lever"],["sobre","upon"],["os","the"],["outeiros,","hills,"],["e","and"],["concorrerão","they-will-compete"],["a","to"],["ele","he"],["os","the"],["povos.","nations."]]},
  {num:2,words:[["E","And"],["irão","they-will-go"],["muitas","many"],["nações,","nations,"],["e","and"],["dirão:","they-will-say:"],["Vinde,","Come,"],["e","and"],["subamos","we-climb"],["ao","to-the"],["monte","mountain"],["do","of-the"],["Senhor,","Lord,"],["e","and"],["à","to-the"],["casa","house"],["do","of-the"],["Deus","God"],["de","of"],["Jacó,","Jacob,"],["para que","that"],["nos","us"],["ensine","teaches"],["os","the"],["seus","his"],["caminhos,","ways,"],["e","and"],["nós","we"],["andemos","we-walk"],["pelas","by-the"],["suas","his"],["veredas;","paths;"],["porque","because"],["a","to"],["lei","law"],["sairá","will-exit"],["de","of"],["Sião,","Zion,"],["e","and"],["a","to"],["palavra","word"],["do","of-the"],["Senhor,","Lord,"],["de","of"],["Jerusalém.","Jerusalem."]]},
  {num:3,words:[["E","And"],["julgará","will-judge"],["entre","between"],["muitos","many"],["povos,","nations,"],["e","and"],["castigará","will-punish"],["nações","nations"],["poderosas","mightier"],["e","and"],["longínquas,","furthermost,"],["e","and"],["converterão","pruninghooks"],["as","the"],["suas","his"],["espadas","swords"],["em","in"],["enxadas,","pruninghooks,"],["e","and"],["as","the"],["suas","his"],["lanças,","spears,"],["em","in"],["foices;","you-cut;"],["uma","a"],["nação","nation"],["não","no"],["levantará","will-hoist"],["a","to"],["espada","sword"],["contra","against"],["outra","another"],["nação,","nation,"],["nem","nor"],["aprenderão","pruninghooks"],["mais","still"],["a","to"],["guerra.","war."]]},
  {num:4,words:[["Mas","But"],["assentar-se-ão,","they-will-sit down,"],["cada","every"],["um","a"],["debaixo","under"],["da","of-the"],["sua","his"],["videira,","vine,"],["e","and"],["debaixo","under"],["da","of-the"],["sua","his"],["figueira,","fig,"],["e","and"],["não","no"],["haverá","will-have"],["quem","who"],["os","the"],["espante,","terrify,"],["porque","because"],["a","to"],["boca","mouth"],["do","of-the"],["Senhor dos","hosts"],["Exércitos","Hosts"],["o","the"],["falou.","spake."]]},
  {num:5,words:[["Porque","Because"],["todos","all"],["os","the"],["povos","nations"],["andarão,","fatling,"],["cada","every"],["um","a"],["no","in-the"],["nome","name"],["do","of-the"],["seu","his"],["deus;","god;"],["mas","but"],["nós","we"],["andaremos","we-will-walk"],["no","in-the"],["nome","name"],["do","of-the"],["Senhor","Lord"],["nosso","our"],["Deus,","God,"],["eternamente","always"],["e","and"],["para sempre.","for-ever"]]},
  {num:6,words:[["Naquele","In-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["congregarei","halteth"],["a","to"],["que","that"],["coxeava,","limped,"],["e","and"],["recolherei","halteth"],["a","to"],["que","that"],["eu","I"],["tinha","had"],["expulsado,","I-should-eliminate,"],["e","and"],["a","to"],["que","that"],["eu","I"],["tinha","had"],["maltratado.","I-should-misuse."]]},
  {num:7,words:[["E","And"],["da","of-the"],["que","that"],["coxeava","limped"],["farei","I-will-make"],["um","a"],["remanescente,","remnant,"],["e","and"],["da","of-the"],["que","that"],["fora","outside"],["desterrada","exile"],["para","for"],["longe,","far,"],["uma","a"],["nação","nation"],["poderosa;","mighty;"],["e","and"],["o","the"],["Senhor","Lord"],["reinará","assuredly"],["sobre","upon"],["eles","they"],["no","in-the"],["monte","mountain"],["Sião,","Zion,"],["desde","since"],["agora","now"],["e","and"],["para sempre.","for-ever"]]},
  {num:8,words:[["E","And"],["tu,","you,"],["ó","O"],["torre","tower"],["do","of-the"],["rebanho,","flock,"],["monte","mountain"],["da","of-the"],["filha","daughter"],["de","of"],["Sião,","Zion,"],["até","until"],["a","to"],["ti","you"],["virá;","will-come;"],["certamente","certainly"],["virá","will-come"],["o","the"],["primeiro","first"],["domínio,","dominion,"],["o","the"],["reino","kingdom"],["da","of-the"],["filha","daughter"],["de","of"],["Jerusalém.","Jerusalem."]]},
  {num:9,words:[["Ora,","Now,"],["por","by"],["que","that"],["farias","forbare"],["tão","that much"],["grande","great"],["pranto?","mourning?"],["não","no"],["há","has"],["em","in"],["ti","you"],["rei?","king?"],["pereceu","perished"],["o","the"],["teu","your"],["conselheiro?","counsellor?"],["apoderou-se","ahah"],["de","of"],["ti","you"],["dor,","pain,"],["como","as"],["da","of-the"],["que","that"],["está","is"],["de","of"],["parto?","travail?"]]},
  {num:10,words:[["Sofre","Suffereth"],["dores,","sorrows,"],["e","and"],["trabalhos,","labours,"],["para","for"],["dar","give"],["à","to-the"],["luz,","light,"],["ó","O"],["filha","daughter"],["de","of"],["Sião,","Zion,"],["como","as"],["a","to"],["que","that"],["está","is"],["de","of"],["parto,","travail,"],["porque","because"],["agora","now"],["sairás","you-will-exit"],["da","of-the"],["cidade,","city,"],["e","and"],["morarás","you-will-brawling"],["no","in-the"],["campo,","field,"],["e","and"],["irás","you-will-go"],["até","until"],["Babilônia;","Babylon;"],["ali,","there,"],["porém,","but,"],["serás","you-will-be"],["livrada;","free;"],["ali","there"],["te","you"],["remirá","will-shortened"],["o","the"],["Senhor","Lord"],["da","of-the"],["mão","hand"],["de","of"],["teus","your"],["inimigos.","enemies."]]},
  {num:11,words:[["Agora","Now"],["se","if"],["congregaram","ethanim"],["muitas","many"],["nações","nations"],["contra","against"],["ti,","you,"],["que","that"],["dizem:","they-say:"],["Seja","Is"],["profanada,","profane,"],["e","and"],["os","the"],["nossos","our"],["olhos","eyes"],["verão","summer"],["seus","his"],["desejos","desires"],["sobre","upon"],["Sião.","Zion."]]},
  {num:12,words:[["Mas","But"],["não","no"],["sabem","they-know"],["os","the"],["pensamentos","thoughts"],["do","of-the"],["Senhor,","Lord,"],["nem","nor"],["entendem","they-understand"],["o","the"],["seu","his"],["conselho;","counsel;"],["porque","because"],["as","the"],["ajuntou","gathered"],["como","as"],["feixes","sheaves"],["à","to-the"],["eira.","threshingfloor."]]},
  {num:13,words:[["Levanta-te,","Arise,"],["e","and"],["trilha,","threshes,"],["ó","O"],["filha","daughter"],["de","of"],["Sião;","Zion;"],["porque","because"],["eu","I"],["farei","I-will-make"],["de","of"],["ferro","iron"],["o","the"],["teu","your"],["chifre,","horn,"],["e","and"],["de","of"],["bronze,","brass,"],["os","the"],["teus","your"],["cascos;","barrel;"],["e","and"],["esmiuçarás","hoofs"],["muitos","many"],["povos,","nations,"],["e","and"],["o","the"],["seu","his"],["ganho","gain"],["consagrarei","I-will-dedicate"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["os","the"],["seus","his"],["bens","good"],["ao","to-the"],["Senhor","Lord"],["de","of"],["toda","every"],["a","to"],["terra.","land."]]}
];
var v5 = [
  {num:1,words:[["Agora","Now"],["ajunta-te","to-ajuntar-se"],["em","in"],["tropas,","bands,"],["ó","O"],["filha","daughter"],["de","of"],["tropas;","bands;"],["pôr-se-á","avails"],["cerco","siege"],["sobre","upon"],["nós;","we;"],["ferirão","they-will-hurt"],["com","with"],["a","to"],["vara","rod"],["o","the"],["queixo","cheek"],["do","of-the"],["juiz","judge"],["de","of"],["Israel.","Israel."]]},
  {num:2,words:[["E","And"],["tu,","you,"],["Belém","Bethlehem"],["Efrata,","Ephratah,"],["ainda que","although"],["sejas","you-are"],["pequena","small"],["entre","between"],["os","the"],["milhares","thousands"],["de","of"],["Judá,","Judah,"],["de","of"],["ti","you"],["me","me"],["sairá","will-exit"],["o","the"],["que","that"],["será","will-be"],["governante","ruler"],["em","in"],["Israel,","Israel,"],["e","and"],["cujas","whose"],["origens","lineage"],["são","they-are"],["desde","since"],["os","the"],["tempos","times"],["antigos,","ancient,"],["desde","since"],["os","the"],["dias","days"],["da","of-the"],["eternidade.","eternity."]]},
  {num:3,words:[["Portanto,","Therefore,"],["os","the"],["entregará","ramoth-gilead"],["até","until"],["o","the"],["tempo","time"],["em","in"],["que","that"],["a","to"],["que","that"],["está","is"],["de","of"],["parto","travail"],["tiver","will-have"],["dado","given"],["à","to-the"],["luz;","light;"],["então","said"],["o","the"],["restante","remaining"],["de","of"],["seus","his"],["irmãos","brethren"],["voltará","will-return"],["com","with"],["os","the"],["filhos","children"],["de","of"],["Israel.","Israel."]]},
  {num:4,words:[["E","And"],["ele","he"],["estará","will-be"],["em","in"],["pé,","foot,"],["e","and"],["apascentará","will-feed"],["o","the"],["povo","people"],["na","in-the"],["força","strength"],["do","of-the"],["Senhor,","Lord,"],["na","in-the"],["excelência","excellency"],["do","of-the"],["nome","name"],["do","of-the"],["Senhor","Lord"],["seu","his"],["Deus;","God;"],["e","and"],["eles","they"],["permanecerão,","molest,"],["porque","because"],["agora","now"],["será","will-be"],["ele","he"],["engrandecido","magnified"],["até","until"],["os","the"],["confins","ends"],["da","of-the"],["terra.","land."]]},
  {num:5,words:[["E","And"],["este","this"],["será","will-be"],["a","to"],["paz;","peace;"],["quando","when"],["a","to"],["Assíria","Assyria"],["vier","will-come"],["à","to-the"],["nossa","our"],["terra,","land,"],["e","and"],["quando","when"],["passar","fare"],["sobre","upon"],["os","the"],["nossos","our"],["palácios,","palaces,"],["levantaremos","we-will-hoist"],["contra","against"],["ele","he"],["sete","seven"],["pastores","shepherds"],["e","and"],["oito","eight"],["príncipes","princes"],["dentre","from"],["os","the"],["homens.","men."]]},
  {num:6,words:[["Esses","Those"],["consumirão","they-will-consume"],["a","to"],["terra","land"],["da","of-the"],["Assíria","Assyria"],["à","to-the"],["espada,","sword,"],["e","and"],["a","to"],["terra","land"],["de","of"],["Ninrode","Nimrod"],["nas","in-the"],["suas","his"],["entradas.","enter."],["Assim","Thus"],["nos","us"],["livrará","deliver"],["da","of-the"],["Assíria,","Assyria,"],["quando","when"],["vier","will-come"],["à","to-the"],["nossa","our"],["terra,","land,"],["e","and"],["quando","when"],["pisar","crush"],["os","the"],["nossos","our"],["termos.","coasts."]]},
  {num:7,words:[["E","And"],["estará","will-be"],["o","the"],["remanescente","remnant"],["de","of"],["Jacó","Jacob"],["no","in-the"],["meio","midst"],["de","of"],["muitos","many"],["povos,","nations,"],["como","as"],["orvalho","dew"],["do","of-the"],["Senhor,","Lord,"],["como","as"],["uns","some"],["chuviscos","tarrieth"],["sobre","upon"],["a","to"],["terra,","land,"],["que","that"],["não","no"],["espera","waiteth"],["pelo","by-the"],["homem,","man,"],["nem","nor"],["aguarda","abides"],["filhos","children"],["de","of"],["homens.","men."]]},
  {num:8,words:[["E","And"],["o","the"],["remanescente","remnant"],["de","of"],["Jacó","Jacob"],["estará","will-be"],["entre","between"],["as","the"],["nações,","nations,"],["no","in-the"],["meio","midst"],["de","of"],["muitos","many"],["povos,","nations,"],["como","as"],["um","a"],["leão","lion"],["entre","between"],["os","the"],["animais","beasts"],["do","of-the"],["bosque,","forest,"],["como","as"],["um","a"],["leãozinho","lion"],["entre","between"],["os","the"],["rebanhos","flocks"],["de","of"],["ovelhas,","sheep,"],["o","the"],["qual,","which,"],["quando","when"],["passar,","fare,"],["pisará","will-crush"],["e","and"],["despedaçará,","claws,"],["sem","without"],["que","that"],["haja","has"],["quem","who"],["as","the"],["livre.","free."]]},
  {num:9,words:[["A","To"],["tua","your"],["mão","hand"],["se","if"],["exaltará","exalt"],["sobre","upon"],["os","the"],["seus","his"],["adversários;","adversaries;"],["e","and"],["todos","all"],["os","the"],["teus","your"],["inimigos","enemies"],["serão","they-will-be"],["exterminados.","reverse."]]},
  {num:10,words:[["E","And"],["sucederá","gog"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["que","that"],["eu","I"],["exterminarei","I-will-reverse"],["do","of-the"],["meio","midst"],["de","of"],["ti","you"],["os","the"],["teus","your"],["cavalos,","horses,"],["e","and"],["destruirei","destroy"],["os","the"],["teus","your"],["carros;","chariots;"]]},
  {num:11,words:[["E","And"],["destruirei","destroy"],["as","the"],["cidades","cities"],["da","of-the"],["tua","your"],["terra,","land,"],["e","and"],["derrubarei","pull"],["todas","things"],["as","the"],["tuas","your"],["fortalezas;","fortification;"]]},
  {num:12,words:[["E","And"],["exterminarei","I-will-reverse"],["as","the"],["feitiçarias","sorceries"],["da","of-the"],["tua","your"],["mão;","hand;"],["e","and"],["não","no"],["terás","you-will-have"],["agoureiros;","stargazers;"]]},
  {num:13,words:[["E","And"],["exterminarei","I-will-reverse"],["do","of-the"],["meio","midst"],["de","of"],["ti","you"],["as","the"],["tuas","your"],["imagens","images"],["de","of"],["escultura","graven"],["e","and"],["as","the"],["tuas","your"],["estátuas;","statue;"],["e","and"],["tu","you"],["não","no"],["te","you"],["inclinarás","quite"],["mais","still"],["diante","before"],["da","of-the"],["obra","work"],["das","of-the"],["tuas","your"],["mãos.","hands."]]},
  {num:14,words:[["E","And"],["arrancarei","pluck"],["os","the"],["teus","your"],["postes-ídolos","groves"],["do","of-the"],["meio","midst"],["de","of"],["ti;","you;"],["e","and"],["destruirei","destroy"],["as","the"],["tuas","your"],["cidades.","cities."]]},
  {num:15,words:[["E","And"],["com","with"],["ira","anger"],["e","and"],["com","with"],["furor","fury"],["farei","I-will-make"],["vingança","vengeance"],["contra","against"],["as","the"],["nações","nations"],["que","that"],["não","no"],["ouvem.","they-hear."]]}
];
var v6 = [
  {num:1,words:[["Ouvi","I-heard"],["agora","now"],["o","the"],["que","that"],["diz","says"],["o","the"],["Senhor:","Lord:"],["Levanta-te,","Arise,"],["contende","contends"],["com","with"],["os","the"],["montes,","mountains,"],["e","and"],["ouçam","they-hear"],["os","the"],["outeiros","hills"],["a","to"],["tua","your"],["voz.","voice."]]},
  {num:2,words:[["Ouvi","I-heard"],["montes,","mountains,"],["a","to"],["contenda","strife"],["do","of-the"],["Senhor,","Lord,"],["e","and"],["vós,","you,"],["fortes","strong"],["fundamentos","foundations"],["da","of-the"],["terra;","land;"],["porque","because"],["o","the"],["Senhor","Lord"],["tem","has"],["uma","a"],["contenda","strife"],["com","with"],["o","the"],["seu","his"],["povo,","people,"],["e","and"],["com","with"],["Israel","Israel"],["entrará","enter"],["em","in"],["juízo.","judgment."]]},
  {num:3,words:[["Ó","O"],["povo","people"],["meu,","my,"],["que","that"],["te","you"],["tenho","I-have"],["feito?","done?"],["e","and"],["com","with"],["que","that"],["te","you"],["enfadei?","I-bored?"],["Testifica","Testifieth"],["contra","against"],["mim.","me."]]},
  {num:4,words:[["Certamente","Certainly"],["te","you"],["fiz","I-made"],["subir","climb"],["da","of-the"],["terra do","egypt"],["Egito","Egypt"],["e","and"],["da","of-the"],["casa","house"],["da","of-the"],["servidão","bondage"],["te","you"],["remi;","I-shortened;"],["e","and"],["enviei","sent"],["adiante","onward"],["de","of"],["ti","you"],["Moisés,","Moses,"],["Aarão","Aaron"],["e","and"],["Miriã.","Miriam."]]},
  {num:5,words:[["Povo","People"],["meu,","my,"],["lembra-te","remember"],["agora","now"],["do","of-the"],["que","that"],["consultou","enquired"],["Balaque,","Balak,"],["rei","king"],["de","of"],["Moabe,","Moab,"],["e","and"],["o","the"],["que","that"],["lhe","to-him"],["respondeu","answered"],["Balaão,","Balaam,"],["filho","son"],["de","of"],["Beor,","Beor,"],["desde","since"],["Sitim","Harlot's"],["até","until"],["Gilgal;","Gilgal;"],["para que","that"],["conheças","you-know"],["as","the"],["justiças","righteousnesses"],["do","of-the"],["Senhor.","Lord."]]},
  {num:6,words:[["Com","With"],["que","that"],["me","me"],["apresentarei","I-will-exhibit"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["me","me"],["inclinarei","incline"],["ao","to-the"],["Deus","God"],["altíssimo?","most?"],["apresentar-me-ei","I-will-zabdi"],["com","with"],["holocaustos?","burnt?"],["com","with"],["bezerros","calf"],["de","of"],["um","a"],["ano?","year?"]]},
  {num:7,words:[["Agradar-se-á","To-agradar-se"],["o","the"],["Senhor","Lord"],["de","of"],["milhares","thousands"],["de","of"],["carneiros?","rams?"],["de","of"],["dez","ten"],["mil","thousand"],["ribeiros","brooks"],["de","of"],["azeite?","oil?"],["darei","I-will-give"],["o","the"],["meu","my"],["primogênito","firstborn"],["pela","by-the"],["minha","my"],["transgressão?","transgression?"],["o","the"],["fruto","fruit"],["do","of-the"],["meu","my"],["ventre,","abdomen,"],["pelo","by-the"],["pecado","sin"],["da","of-the"],["minha","my"],["alma?","soul?"]]},
  {num:8,words:[["Ele","He"],["te","you"],["declarou,","nabal,"],["ó","O"],["homem,","man,"],["o","the"],["que","that"],["é","is"],["bom;","good;"],["e","and"],["o","the"],["que","that"],["o","the"],["Senhor","Lord"],["pede","asks"],["de","of"],["ti,","you,"],["senão","save"],["que","that"],["pratiques","you-practice"],["a","to"],["justiça,","righteousness,"],["e","and"],["ames","humbly"],["a","to"],["benevolência,","kindness,"],["e","and"],["andes","you-walk"],["humildemente","humbly"],["com","with"],["o","the"],["teu","your"],["Deus?","God?"]]},
  {num:9,words:[["A","To"],["voz","voice"],["do","of-the"],["Senhor","Lord"],["clama","crieth"],["à","to-the"],["cidade","city"],["(porque","(because"],["o","the"],["que","that"],["é","is"],["sábio","wise"],["temerá","will-fear"],["o","the"],["teu","your"],["nome).","name)."],["Ouvi","I-heard"],["a","to"],["vara,","rod,"],["e","and"],["quem","who"],["a","to"],["ordenou.","commanded."]]},
  {num:10,words:[["Ainda","Yet"],["há","has"],["na","in-the"],["casa","house"],["do","of-the"],["ímpio","wicked"],["tesouros","treasures"],["da","of-the"],["impiedade,","wickedness,"],["e","and"],["efa","ephah"],["pequeno,","small,"],["que","that"],["é","is"],["detestável?","nasty?"]]},
  {num:11,words:[["Seria","Should-be"],["eu","I"],["limpo","clean"],["com","with"],["balanças","you-rock"],["falsas,","doctrines,"],["e","and"],["com","with"],["uma","a"],["bolsa","purse"],["de","of"],["pesos","weights"],["enganosos?","deceptive?"]]},
  {num:12,words:[["Porque","Because"],["os","the"],["seus","his"],["ricos","rich"],["estão","they-are"],["cheios","full"],["de","of"],["violência,","violence,"],["e","and"],["os","the"],["seus","his"],["habitantes","inhabitants"],["falam","they-speak"],["mentiras;","lies;"],["e","and"],["a","to"],["sua","his"],["língua","tongue"],["é","is"],["enganosa","deceitful"],["na","in-the"],["sua","his"],["boca.","mouth."]]},
  {num:13,words:[["Assim,","Thus,"],["eu","I"],["também","also"],["te","you"],["enfraquecerei,","I-will-abate,"],["ferindo-te","I-hurt-you"],["e","and"],["assolando-te","smiting"],["por","by"],["causa","sake"],["dos","of-the"],["teus","your"],["pecados.","sins."]]},
  {num:14,words:[["Tu","You"],["comerás,","you-will-eat,"],["mas","but"],["não","no"],["te","you"],["fartarás;","you-will-satiate;"],["e","and"],["a","to"],["tua","your"],["humilhação","humiliation"],["estará","will-be"],["no","in-the"],["meio","midst"],["de","of"],["ti;","you;"],["e","and"],["tu","you"],["removerás,","you-will-shovel,"],["mas","but"],["não","no"],["livrarás;","you-will-free;"],["e","and"],["aquilo","that"],["que","that"],["livrares,","you-will-free,"],["eu","I"],["o","the"],["entregarei","nebuchadrezzar"],["à","to-the"],["espada.","sword."]]},
  {num:15,words:[["Tu","You"],["semearás,","you-will-sow,"],["mas","but"],["não","no"],["ceifarás;","you-will-cut;"],["pisarás","you-will-crush"],["a","to"],["azeitona,","olive,"],["mas","but"],["não","no"],["te","you"],["ungirás","you-will-anoint"],["com","with"],["azeite,","oil,"],["e","and"],["o","the"],["mosto,","corn,"],["mas","but"],["não","no"],["beberás","you-will-drink"],["vinho.","wine."]]},
  {num:16,words:[["Porque","Because"],["se","if"],["guardaram","kept"],["os","the"],["estatutos","statutes"],["de","of"],["Onri,","Omri,"],["e","and"],["toda","every"],["a","to"],["obra","work"],["da","of-the"],["casa","house"],["de","of"],["Acabe,","Ahab,"],["e","and"],["vós","you"],["andais","you-walk"],["nos","us"],["conselhos","counsels"],["deles;","of-them;"],["para que","that"],["eu","I"],["te","you"],["faça","makes"],["uma","a"],["desolação,","desolation,"],["e","and"],["dos","of-the"],["seus","his"],["habitantes,","inhabitants,"],["um","a"],["assobio;","hissing;"],["assim","thus"],["trareis","you-will-bring"],["sobre","upon"],["vós","you"],["o","the"],["opróbrio","reproach"],["do","of-the"],["meu","my"],["povo.","people."]]}
];
var v7 = [
  {num:1,words:[["Ai","Ouch"],["de","of"],["mim!","me!"],["Porque","Because"],["estou","I-am"],["feito","done"],["como","as"],["quando","when"],["se","if"],["tem","has"],["colhido","I-should-glean"],["as","the"],["frutas","fruit"],["do","of-the"],["verão,","summer,"],["como","as"],["os","the"],["respigos","gleaning"],["da","of-the"],["vindima;","vintage;"],["não","no"],["há","has"],["cacho","cluster"],["de","of"],["uvas","grapes"],["para","for"],["comer;","eat;"],["a","to"],["minha","my"],["alma","soul"],["desejou","desired"],["figos","figs"],["temporãos.","firstripe."]]},
  {num:2,words:[["Já","Already"],["pereceu","perished"],["da","of-the"],["terra","land"],["o","the"],["piedoso,","gracious,"],["e","and"],["não","no"],["há","has"],["entre","between"],["os","the"],["homens","men"],["um","a"],["que","that"],["seja","is"],["reto;","fair;"],["todos","all"],["armam","bend"],["ciladas","wait"],["para","for"],["sangue;","blood;"],["caça","game"],["cada","every"],["um","a"],["seu","his"],["irmão","brother"],["com","with"],["rede,","net,"]]},
  {num:3,words:[["Para","For"],["com","with"],["ambas","both"],["as","the"],["mãos","hands"],["fazerem","to-make"],["diligentemente","diligently"],["o","the"],["mal;","evil;"],["assim","thus"],["demanda","controversy"],["o","the"],["príncipe,","prince,"],["e","and"],["o","the"],["juiz","judge"],["julga","judgeth"],["pela","by-the"],["recompensa,","reward,"],["e","and"],["o","the"],["grande","great"],["fala","speech"],["da","of-the"],["corrupção","corruption"],["da","of-the"],["sua","his"],["alma,","soul,"],["e","and"],["todos","all"],["tramam","they-brew"],["em","in"],["conjunto.","lump."]]},
  {num:4,words:[["O","The"],["melhor","better"],["deles","of-them"],["é","is"],["como","as"],["um","a"],["espinho;","thorn;"],["o","the"],["mais","still"],["reto","fair"],["é","is"],["pior","worse"],["do","of-the"],["que","that"],["o","the"],["espinhal;","brier;"],["veio","came"],["o","the"],["dia","day"],["dos","of-the"],["teus","your"],["vigias,","you-guard,"],["veio","came"],["o","the"],["teu","your"],["castigo;","punishment;"],["agora","now"],["será","will-be"],["a","to"],["sua","his"],["confusão.","confusion."]]},
  {num:5,words:[["Não","No"],["creiais","you-believe"],["no","in-the"],["amigo,","friend,"],["nem","nor"],["confieis","you-confide"],["no","in-the"],["vosso","your"],["guia;","guide;"],["daquela","of-that"],["que","that"],["repousa","resteth"],["no","in-the"],["teu","your"],["seio","bosom"],["guarda","guard"],["as","the"],["portas","gates"],["da","of-the"],["tua","your"],["boca.","mouth."]]},
  {num:6,words:[["Porque","Because"],["o","the"],["filho","son"],["despreza","despiseth"],["o","the"],["pai,","father,"],["a","to"],["filha","daughter"],["se","if"],["levanta","hoists"],["contra","against"],["sua","his"],["mãe,","mother,"],["a","to"],["nora","daughter-in-law"],["contra","against"],["sua","his"],["sogra,","father-in-law,"],["os","the"],["inimigos","enemies"],["do","of-the"],["homem","man"],["são","they-are"],["os","the"],["da","of-the"],["sua","his"],["própria","own"],["casa.","house."]]},
  {num:7,words:[["Eu,","I,"],["porém,","but,"],["olharei","trembleth"],["para","for"],["o","the"],["Senhor;","Lord;"],["esperarei","I-will-abide"],["no","in-the"],["Deus","God"],["da","of-the"],["minha","my"],["salvação;","salvation;"],["o","the"],["meu","my"],["Deus","God"],["me","me"],["ouvirá.","will-hear."]]},
  {num:8,words:[["Ó","O"],["inimiga","enemy"],["minha,","my,"],["não","no"],["te","you"],["alegres","you-gladden"],["de","of"],["mim;","me;"],["ainda que","although"],["eu","I"],["tenha","has"],["caído,","fallen,"],["levantar-me-ei;","nephew;"],["se","if"],["eu","I"],["morar","brawling"],["nas","in-the"],["trevas,","darkness,"],["o","the"],["Senhor","Lord"],["será","will-be"],["a","to"],["minha","my"],["luz.","light."]]},
  {num:9,words:[["Sofrerei","Faithless"],["a","to"],["ira","anger"],["do","of-the"],["Senhor,","Lord,"],["porque","because"],["pequei","sinned"],["contra","against"],["ele,","he,"],["até que","until"],["pleiteie","sue"],["a","to"],["minha","my"],["causa,","sake,"],["e","and"],["execute","executes"],["o","the"],["meu","my"],["direito;","right;"],["ele","he"],["tirar-me-á","will-deduct-me"],["para","for"],["a","to"],["luz,","light,"],["verei","I-will-see"],["satisfeito","contented"],["a","to"],["sua","his"],["justiça.","righteousness."]]},
  {num:10,words:[["E","And"],["a","to"],["minha","my"],["inimiga","enemy"],["o","the"],["verá,","will-see,"],["e","and"],["cobri-la-á","mire"],["a","to"],["vergonha;","shame;"],["e","and"],["aquela","that ... over there"],["que","that"],["me","me"],["diz:","says:"],["Onde","Where"],["está","is"],["o","the"],["Senhor","Lord"],["teu","your"],["Deus?","God?"],["Os","The"],["meus","my"],["olhos","eyes"],["a","to"],["verão","summer"],["satisfeitos;","contented;"],["agora","now"],["será","will-be"],["ela","she"],["pisada","trodden"],["como","as"],["a","to"],["lama","mire"],["das","of-the"],["ruas.","streets."]]},
  {num:11,words:[["No","In-the"],["dia","day"],["em","in"],["que","that"],["forem","they-will-be"],["reedificados","decree"],["os","the"],["teus","your"],["muros,","walls,"],["nesse","in-that"],["dia","day"],["longe","far"],["estará","will-be"],["ainda","yet"],["o","the"],["estatuto.","statute."]]},
  {num:12,words:[["Naquele","In-that"],["dia","day"],["virá","will-come"],["até","until"],["ti,","you,"],["desde","since"],["a","to"],["Assíria","Assyria"],["até","until"],["as","the"],["cidades","cities"],["fortificadas,","fenced,"],["e","and"],["das","of-the"],["fortalezas","fortification"],["até","until"],["o","the"],["rio,","river,"],["e","and"],["do","of-the"],["mar","sea"],["até","until"],["o","the"],["mar,","sea,"],["e","and"],["da","of-the"],["montanha","mountain"],["até","until"],["a","to"],["montanha.","mountain."]]},
  {num:13,words:[["Porém","But"],["esta","this"],["terra","land"],["será","will-be"],["posta","builders"],["em","in"],["desolação","desolation"],["por","by"],["causa","sake"],["dos","of-the"],["seus","his"],["moradores,","inhabitants,"],["por","by"],["causa","sake"],["do","of-the"],["fruto","fruit"],["das","of-the"],["suas","his"],["obras.","works."]]},
  {num:14,words:[["Apascenta","Feedeth"],["o","the"],["teu","your"],["povo","people"],["com","with"],["a","to"],["tua","your"],["vara,","rod,"],["o","the"],["rebanho","flock"],["da","of-the"],["tua","your"],["herança,","inheritance,"],["que","that"],["mora","brawling"],["solitário","palestina"],["no","in-the"],["bosque,","forest,"],["no","in-the"],["meio","midst"],["da","of-the"],["terra","land"],["fértil;","fruitful;"],["apascentem-se","to-apascentar-se"],["em","in"],["Basã","Bashan"],["e","and"],["Gileade,","Gilead,"],["como","as"],["nos","us"],["dias","days"],["da","of-the"],["antiguidade.","antiguidade."]]},
  {num:15,words:[["Eu","I"],["lhes","to-them"],["mostrarei","show"],["maravilhas,","wonders,"],["como","as"],["nos","us"],["dias","days"],["da","of-the"],["tua","your"],["subida","ascent"],["da","of-the"],["terra do","egypt"],["Egito.","Egypt."]]},
  {num:16,words:[["As","The"],["nações","nations"],["o","the"],["verão,","summer,"],["e","and"],["envergonhar-se-ão,","they-will-be ashamed,"],["por causa de","because-of"],["todo","every"],["o","the"],["seu","his"],["poder;","can;"],["porão","badgers'"],["a","to"],["mão","hand"],["sobre","upon"],["a","to"],["boca,","mouth,"],["e","and"],["os","the"],["seus","his"],["ouvidos","ears"],["ficarão","they-will-remain"],["surdos.","deaf."]]},
  {num:17,words:[["Lamberão","Lick"],["o","the"],["pó","dust"],["como","as"],["serpentes,","serpents,"],["como","as"],["répteis","creeping"],["da","of-the"],["terra,","land,"],["tremendo,","trembling,"],["sairão","they-will-exit"],["dos","of-the"],["seus","his"],["esconderijos;","hiding;"],["com","with"],["pavor","alarm"],["virão","they-will-come"],["ao","to-the"],["Senhor","Lord"],["nosso","our"],["Deus,","God,"],["e","and"],["terão","they-will-have"],["medo","fear"],["de","of"],["ti.","you."]]},
  {num:18,words:[["Quem","Who"],["é","is"],["Deus","God"],["semelhante","like"],["a","to"],["ti,","you,"],["que","that"],["perdoa","forgive"],["a","to"],["iniquidade,","iniquity,"],["e","and"],["que","that"],["passa","passeth"],["por","by"],["cima","above"],["da","of-the"],["transgressão","transgression"],["do","of-the"],["restante","remaining"],["da","of-the"],["sua","his"],["herança?","inheritance?"],["Ele","He"],["não","no"],["retém","restrains"],["a","to"],["sua","his"],["ira","anger"],["para sempre,","for-ever"],["porque","because"],["tem","has"],["prazer","pleasure"],["na","in-the"],["benignidade.","endureth."]]},
  {num:19,words:[["Tornará","Will-become"],["a","to"],["apiedar-se","subdue"],["de","of"],["nós;","we;"],["sujeitará","will-overpower"],["as","the"],["nossas","our"],["iniquidades,","iniquities,"],["e","and"],["tu","you"],["lançarás","you-will-vomit"],["todos","all"],["os","the"],["seus","his"],["pecados","sins"],["nas","in-the"],["profundezas","depths"],["do","of-the"],["mar.","sea."]]},
  {num:20,words:[["Darás","You-will-give"],["a","to"],["Jacó","Jacob"],["a","to"],["fidelidade,","faithfulness,"],["e","and"],["a","to"],["Abraão,","Abraham,"],["a","to"],["benignidade,","endureth,"],["que","that"],["juraste","you-swore"],["a","to"],["nossos","our"],["pais","parents"],["desde","since"],["os","the"],["dias","days"],["antigos.","ancient."]]}
];
renderVerseSet(v1, 'mic-ch1-verses');
renderVerseSet(v2, 'mic-ch2-verses');
renderVerseSet(v3, 'mic-ch3-verses');
renderVerseSet(v4, 'mic-ch4-verses');
renderVerseSet(v5, 'mic-ch5-verses');
renderVerseSet(v6, 'mic-ch6-verses');
renderVerseSet(v7, 'mic-ch7-verses');
})();
