(function() {
var v1 = [
  {num:1,words:[["Peso","Weight"],["de","of"],["Nínive.","Nineveh."],["Livro","Book"],["da","of-the"],["visão","vision"],["de","of"],["Naum,","Naum,"],["o","the"],["elcosita.","elcosita."]]},
  {num:2,words:[["O","The"],["Senhor","Lord"],["é","is"],["Deus","God"],["zeloso","zealous"],["e","and"],["que","that"],["toma","take"],["vingança;","vengeance;"],["o","the"],["Senhor","Lord"],["toma","take"],["vingança","vengeance"],["e","and"],["tem","has"],["furor;","fury;"],["o","the"],["Senhor","Lord"],["toma","take"],["vingança","vengeance"],["contra","against"],["os","the"],["seus","his"],["adversários,","adversaries,"],["e","and"],["guarda","guard"],["a","to"],["ira","anger"],["contra","against"],["os","the"],["seus","his"],["inimigos.","enemies."]]},
  {num:3,words:[["O","The"],["Senhor","Lord"],["é","is"],["tardio","late"],["em","in"],["irar-se,","acquit,"],["porém","but"],["grande","great"],["em","in"],["força,","strength,"],["e","and"],["ao","to-the"],["culpado","guilty"],["não","no"],["tem","has"],["por","by"],["inocente;","innocent;"],["o","the"],["Senhor,","Lord,"],["cujo","whose"],["caminho","way"],["é","is"],["na","in-the"],["tormenta,","torment,"],["e","and"],["na","in-the"],["tempestade,","hurricane,"],["e","and"],["as","the"],["nuvens","clouds"],["são","they-are"],["o","the"],["pó","dust"],["dos","of-the"],["seus","his"],["pés.","feet."]]},
  {num:4,words:[["Ele","He"],["repreende","admonishes"],["o","the"],["mar,","sea,"],["e","and"],["o","the"],["faz","makes"],["secar,","drieth,"],["e","and"],["esgota","consumes"],["todos","all"],["os","the"],["rios;","rivers;"],["desfalecem","they-faint"],["Basã","Bashan"],["e","and"],["Carmelo,","Carmel,"],["e","and"],["a","to"],["flor","flour"],["do","of-the"],["Líbano","Lebanon"],["murcha.","languisheth."]]},
  {num:5,words:[["Os","The"],["montes","mountains"],["tremem","tremble"],["perante","before"],["ele,","he,"],["e","and"],["os","the"],["outeiros","hills"],["se","if"],["derretem;","vein;"],["e","and"],["a","to"],["terra","land"],["se","if"],["agita","abets"],["na","in-the"],["sua","his"],["presença,","presence,"],["e","and"],["o","the"],["mundo,","world,"],["e","and"],["todos","all"],["os","the"],["que","that"],["nele","in-him"],["habitam.","dwell."]]},
  {num:6,words:[["Quem","Who"],["parará","will-halt"],["diante","before"],["do","of-the"],["seu","his"],["furor?","fury?"],["e","and"],["quem","who"],["persistirá","will-abide"],["diante","before"],["do","of-the"],["ardor","glow"],["da","of-the"],["sua","his"],["ira?","anger?"],["A","To"],["sua","his"],["cólera","cholera"],["se","if"],["derramou","poured"],["como","as"],["um","a"],["fogo,","fire,"],["e","and"],["as","the"],["rochas","rocks"],["foram","they-were"],["por","by"],["ele","he"],["derrubadas.","overthrow."]]},
  {num:7,words:[["O","The"],["Senhor","Lord"],["é","is"],["bom,","good,"],["ele","he"],["serve","serveth"],["de","of"],["fortaleza","fortification"],["no","in-the"],["dia","day"],["da","of-the"],["angústia,","anguish,"],["e","and"],["conhece","knoweth"],["os","the"],["que","that"],["confiam","trust"],["nele.","in-him."]]},
  {num:8,words:[["E","And"],["com","with"],["uma","a"],["inundação","flood"],["transbordante","overrunning"],["acabará","overrunning"],["de","of"],["uma","a"],["vez","occasion"],["com","with"],["o","the"],["seu","his"],["lugar;","place;"],["e","and"],["as","the"],["trevas","darkness"],["perseguirão","they-will-persecute"],["os","the"],["seus","his"],["inimigos.","enemies."]]},
  {num:9,words:[["Que","That"],["pensais","you-reality"],["vós","you"],["contra","against"],["o","the"],["Senhor?","Lord?"],["Ele","He"],["mesmo","even"],["vos","you"],["consumirá","devour"],["de todo;","wholly"],["não","no"],["se","if"],["levantará","will-hoist"],["uma","a"],["segunda","second"],["vez","occasion"],["a","to"],["angústia.","anguish."]]},
  {num:10,words:[["Porque","Because"],["eles","they"],["se","if"],["entrelaçam","folden"],["como","as"],["os","the"],["espinhos,","thorns,"],["e","and"],["se","if"],["embebedam","folden"],["como","as"],["bêbados;","drunkards;"],["serão","they-will-be"],["inteiramente","entirely"],["consumidos","consumed"],["como","as"],["palha","straw"],["seca.","dry."]]},
  {num:11,words:[["De","Of"],["ti","you"],["saiu","went"],["um","a"],["que","that"],["pensou","reality"],["mal","evil"],["contra","against"],["o","the"],["Senhor,","Lord,"],["um","a"],["conselheiro","counsellor"],["ímpio.","wicked."]]},
  {num:12,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["mais","still"],["seguros","safely"],["que","that"],["estejam,","they-are,"],["e","and"],["por","by"],["mais","still"],["numerosos","numerous"],["que","that"],["sejam,","they-are,"],["ainda","yet"],["assim","thus"],["serão","they-will-be"],["tosquiados,","clip,"],["e","and"],["ele","he"],["passará;","overflow;"],["eu","I"],["te","you"],["afligi,","I-afflicted,"],["porém","but"],["não","no"],["te","you"],["afligirei","I-will-afflict"],["mais.","still."]]},
  {num:13,words:[["Mas","But"],["agora","now"],["quebrarei","I-will-crush"],["o","the"],["seu","his"],["jugo","yoke"],["de","of"],["sobre","upon"],["ti,","you,"],["e","and"],["romperei","I-will-break"],["os","the"],["teus","your"],["laços.","snares."]]},
  {num:14,words:[["Porém","But"],["contra","against"],["ti","you"],["o","the"],["Senhor","Lord"],["deu","gave"],["ordem,","order,"],["para que","that"],["não","no"],["haja","has"],["mais","still"],["semente","seed"],["do","of-the"],["teu","your"],["nome;","name;"],["da","of-the"],["casa","house"],["do","of-the"],["teu","your"],["deus","god"],["exterminarei","I-will-reverse"],["as","the"],["imagens","images"],["de","of"],["escultura","graven"],["e","and"],["de","of"],["fundição;","molten;"],["ali","there"],["te","you"],["farei","I-will-make"],["o","the"],["teu","your"],["sepulcro,","sepulchre,"],["porque","because"],["és","you-are"],["vil.","vile."]]},
  {num:15,words:[["Eis","Behold"],["sobre","upon"],["os","the"],["montes","mountains"],["os","the"],["pés","feet"],["do","of-the"],["que","that"],["traz","bringeth"],["as","the"],["boas","tidings"],["novas,","tidings,"],["do","of-the"],["que","that"],["anuncia","publisheth"],["a","to"],["paz!","peace!"],["Celebra","Celebrates"],["as","the"],["tuas","your"],["festas,","feasts,"],["ó","O"],["Judá,","Judah,"],["cumpre","filleth"],["os","the"],["teus","your"],["votos,","vows,"],["porque","because"],["o","the"],["ímpio","wicked"],["não","no"],["tornará","will-become"],["mais","still"],["a","to"],["passar","fare"],["por","by"],["ti;","you;"],["ele","he"],["é","is"],["inteiramente","entirely"],["exterminado.","publisheth."]]}
];
var v2 = [
  {num:1,words:[["O","The"],["destruidor","destroyer"],["subiu","climbed"],["contra","against"],["ti;","you;"],["guarda","guard"],["tu","you"],["a","to"],["fortaleza,","fortification,"],["observa","observes"],["o","the"],["caminho,","way,"],["fortifica","dasheth"],["os","the"],["lombos,","loins,"],["reforça","booster"],["muito","much"],["o","the"],["poder.","can."]]},
  {num:2,words:[["Porque","Because"],["o","the"],["Senhor","Lord"],["tornará","will-become"],["a","to"],["excelência","excellency"],["de","of"],["Jacó","Jacob"],["como","as"],["a","to"],["excelência","excellency"],["de","of"],["Israel;","Israel;"],["porque","because"],["os","the"],["despojadores","spoilester"],["os","the"],["despojaram,","stripped,"],["e","and"],["arruinaram","they-damaged"],["os","the"],["seus","his"],["sarmentos.","sprigs."]]},
  {num:3,words:[["Os","The"],["escudos","shields"],["dos","of-the"],["seus","his"],["valentes","brave"],["serão","they-will-be"],["tintos","torches"],["de","of"],["vermelho,","red,"],["os","the"],["homens","men"],["valorosos","valour"],["andarão","fatling"],["vestidos","clothe"],["de","of"],["escarlate,","scarlet,"],["os","the"],["carros","chariots"],["correrão","they-will-flow"],["como","as"],["fogo","fire"],["de","of"],["tochas","torches"],["no","in-the"],["dia","day"],["do","of-the"],["seu","his"],["aparelhamento,","torches,"],["e","and"],["as","the"],["lanças","spears"],["serão","they-will-be"],["brandidas.","torches."]]},
  {num:4,words:[["Os","The"],["carros","chariots"],["correrão","they-will-flow"],["furiosamente","furiously"],["nas","in-the"],["ruas,","streets,"],["vaguearão","justle"],["pelas","by-the"],["praças;","markets;"],["a","to"],["sua","his"],["aparência","appearance"],["é","is"],["como","as"],["a","to"],["de","of"],["tochas,","torches,"],["correrão","they-will-flow"],["como","as"],["relâmpagos.","lightnings."]]},
  {num:5,words:[["Ele","He"],["se","if"],["lembrará","will-caution"],["dos","of-the"],["seus","his"],["valentes,","brave,"],["eles","they"],["porém","but"],["tropeçarão","stumble"],["na","in-the"],["sua","his"],["marcha;","march;"],["apressar-se-ão","they-will-hurry"],["para","for"],["o","the"],["seu","his"],["muro,","wall,"],["quando","when"],["a","to"],["defesa","protection"],["for","will-be"],["preparada.","prepared."]]},
  {num:6,words:[["As","The"],["portas","gates"],["do","of-the"],["rio","river"],["se","if"],["abrirão,","they-will-open,"],["e","and"],["o","the"],["palácio","palace"],["se","if"],["derreterá.","ice."]]},
  {num:7,words:[["Pois","For"],["determinado","determined"],["está;","is;"],["ela","she"],["será","will-be"],["levada","parties"],["cativa,","captive,"],["será","will-be"],["levada","parties"],["para","for"],["cima,","above,"],["e","and"],["as","the"],["suas","his"],["servas","servant"],["a","to"],["acompanharão,","they-will-accompany,"],["gemendo","I-sigh"],["como","as"],["pombas,","doves,"],["batendo","I-knocking"],["no","in-the"],["peito.","breast."]]},
  {num:8,words:[["Nínive","Nineveh"],["desde","since"],["que","that"],["existe","exists"],["tem","has"],["sido","I-should-be"],["como","as"],["um","a"],["tanque","pool"],["de","of"],["águas,","waters,"],["porém","but"],["elas","they"],["agora","now"],["fogem.","grievousness."],["Parai,","Halt,"],["parai,","halt,"],["clamar-se-á;","will-cry-himself;"],["mas","but"],["ninguém","none"],["olhará","will-glance"],["para","for"],["trás.","behind."]]},
  {num:9,words:[["Saqueai","Furniture"],["a","to"],["prata,","silver,"],["saqueai","furniture"],["o","the"],["ouro,","gold,"],["porque","because"],["não","no"],["têm","they-have"],["fim","end"],["as","the"],["provisões,","provisions,"],["abastança","straits"],["há","has"],["de todo","wholly"],["gênero","clan"],["de","of"],["objetos","jewels"],["desejáveis.","you-desired."]]},
  {num:10,words:[["Vazia,","Empty,"],["e","and"],["despojada,","carefulness,"],["e","and"],["esgotada","consume"],["está,","is,"],["e","and"],["desfaleceu","forborn"],["o","the"],["seu","his"],["coração,","heart,"],["e","and"],["tremem","tremble"],["os","the"],["joelhos,","knees,"],["e","and"],["em","in"],["todos","all"],["os","the"],["lombos","loins"],["há","has"],["dor,","pain,"],["e","and"],["o","the"],["rosto","face"],["de","of"],["todos","all"],["eles","they"],["empalidece.","melteth."]]},
  {num:11,words:[["Onde","Where"],["estão","they-are"],["agora","now"],["o","the"],["covil","den"],["dos","of-the"],["leões","lions"],["e","and"],["as","the"],["pastagens","feedingplace"],["dos","of-the"],["leõezinhos,","lion,"],["onde","where"],["passeava","strolled"],["o","the"],["leão","lion"],["velho,","ancient,"],["e","and"],["o","the"],["filhote","roe"],["do","of-the"],["leão,","lion,"],["sem","without"],["haver","have"],["ninguém","none"],["que","that"],["os","the"],["espantasse?","feedingplace?"]]},
  {num:12,words:[["O","The"],["leão","lion"],["arrebatava","snap up"],["o","the"],["que","that"],["bastava","sufficed"],["para","for"],["os","the"],["seus","his"],["filhotes,","whelps,"],["e","and"],["estrangulava","choked"],["a","to"],["presa","prey"],["para","for"],["as","the"],["suas","his"],["leoas,","lion,"],["e","and"],["enchia","replenished"],["de","of"],["presas","prisoner"],["as","the"],["suas","his"],["cavernas,","caves,"],["e","and"],["de","of"],["rapina,","booty,"],["os","the"],["seus","his"],["covis.","den."]]},
  {num:13,words:[["Eis que","behold"],["eu","I"],["estou","I-am"],["contra","against"],["ti,","you,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Hosts,"],["e","and"],["queimarei","I-will-burn"],["na","in-the"],["fumaça","smoke"],["os","the"],["teus","your"],["carros,","chariots,"],["e","and"],["a","to"],["espada","sword"],["devorará","thickets"],["os","the"],["teus","your"],["leõezinhos,","lion,"],["e","and"],["arrancarei","pluck"],["da","of-the"],["terra","land"],["a","to"],["tua","your"],["presa,","prey,"],["e","and"],["não","no"],["se","if"],["ouvirá","will-hear"],["mais","still"],["a","to"],["voz","voice"],["dos","of-the"],["teus","your"],["embaixadores.","ambassadors."]]}
];
var v3 = [
  {num:1,words:[["Ai","Ouch"],["da","of-the"],["cidade","city"],["ensanguentada,","robbery,"],["que","that"],["está","is"],["toda","every"],["cheia","full"],["de","of"],["mentiras","lies"],["e","and"],["de","of"],["rapina!","booty!"],["Não","No"],["se","if"],["aparta","departeth"],["dela","of-it"],["o","the"],["roubo.","highjack."]]},
  {num:2,words:[["Estrépito","Stamping"],["de","of"],["açoite","scourge"],["há,","has,"],["e","and"],["o","the"],["estrondo","noise"],["do","of-the"],["ruído","noise"],["das","of-the"],["rodas;","wheels;"],["e","and"],["os","the"],["cavalos","horses"],["atropelam,","rattling,"],["e","and"],["carros","chariots"],["vão","they-go"],["saltando.","leaping."]]},
  {num:3,words:[["O","The"],["cavaleiro","horseman"],["levanta","hoists"],["assim","thus"],["a","to"],["espada","sword"],["flamejante,","flaming,"],["e","and"],["a","to"],["lança","spear"],["relampejante,","horseman,"],["e","and"],["ali","there"],["haverá","will-have"],["uma","a"],["multidão","multitude"],["de","of"],["mortos,","dead,"],["e","and"],["abundância","abundance"],["de","of"],["cadáveres,","carcases,"],["e","and"],["não","no"],["terão","they-will-have"],["fim","end"],["os","the"],["defuntos;","cadaver;"],["tropeçarão","stumble"],["nos","us"],["seus","his"],["corpos;","bodies;"]]},
  {num:4,words:[["Por","By"],["causa","sake"],["da","of-the"],["multidão","multitude"],["das","of-the"],["prostituições","whoredoms"],["da","of-the"],["meretriz","harlot"],["muito","much"],["graciosa,","elegant,"],["da","of-the"],["mestra","teacher"],["das","of-the"],["feitiçarias,","sorceries,"],["que","that"],["vendeu","sold"],["os","the"],["povos","nations"],["com","with"],["as","the"],["suas","his"],["prostituições,","whoredoms,"],["e","and"],["as","the"],["famílias,","families,"],["com","with"],["as","the"],["suas","his"],["feitiçarias.","sorceries."]]},
  {num:5,words:[["Eis que","behold"],["eu","I"],["estou","I-am"],["contra","against"],["ti,","you,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Hosts,"],["e","and"],["levantarei","raise"],["a","to"],["tua","your"],["saia","skirt"],["sobre","upon"],["a","to"],["tua","your"],["face,","face,"],["e","and"],["às","to-the"],["nações","nations"],["mostrarei","show"],["a","to"],["tua","your"],["nudez,","nakedness,"],["e","and"],["aos","to-the"],["reinos,","kingdoms,"],["a","to"],["tua","your"],["vergonha.","shame."]]},
  {num:6,words:[["E","And"],["lançarei","I-will-vomit"],["sobe","climbs"],["ti","you"],["coisas","things"],["abomináveis,","you-abhorred,"],["e","and"],["te","you"],["envergonharei,","I-will-abash,"],["e","and"],["por-te-ei","I-will-place-you"],["como","as"],["espetáculo.","spectacle."]]},
  {num:7,words:[["E","And"],["há","has"],["de","of"],["ser que","except"],["todos","all"],["os","the"],["que","that"],["te","you"],["virem","they-will-see"],["fugirão","they-will-flee"],["de","of"],["ti,","you,"],["e","and"],["dirão:","they-will-say:"],["Nínive","Nineveh"],["está","is"],["destruída,","destroyed,"],["quem","who"],["terá","will-have"],["compaixão","compassion"],["dela?","of-it?"],["donde","whence"],["te","you"],["buscarei","I-will-seek"],["consoladores?","comforters?"]]},
  {num:8,words:[["És","You-are"],["tu","you"],["melhor","better"],["do","of-the"],["que","that"],["Nô-Amom,","Populous,"],["que","that"],["está","is"],["assentada","settle"],["nos","us"],["rios,","rivers,"],["cercada","besiege"],["de","of"],["águas,","waters,"],["que","that"],["tinha","had"],["por","by"],["esplanada","populous"],["o","the"],["mar,","sea,"],["cuja","whose"],["muralha","rampart"],["é","is"],["o","the"],["mar?","sea?"]]},
  {num:9,words:[["Etiópia","Ethiopia"],["e","and"],["Egito","Egypt"],["eram","they-were"],["a","to"],["sua","his"],["força,","strength,"],["e","and"],["ela","she"],["não","no"],["tinha","had"],["fim;","end;"],["Pute","Phut"],["e","and"],["Líbia","Lubim"],["foram","they-were"],["o","the"],["teu","your"],["socorro.","help."]]},
  {num:10,words:[["Todavia","Nevertheless"],["foi","was"],["levada","parties"],["cativa","captive"],["para","for"],["o","the"],["desterro;","dashed;"],["também","also"],["os","the"],["seus","his"],["filhos","children"],["foram","they-were"],["despedaçados","dashed"],["no","in-the"],["topo","end"],["de","of"],["todas","things"],["as","the"],["ruas,","streets,"],["e","and"],["sobre","upon"],["os","the"],["seus","his"],["honrados","horseback"],["lançaram","lots"],["sortes,","lots,"],["e","and"],["todos","all"],["os","the"],["seus","his"],["nobres","nobles"],["foram","they-were"],["presos","prisoner"],["com","with"],["grilhões.","fetters."]]},
  {num:11,words:[["Tu","You"],["também","also"],["serás","you-will-be"],["embriagada,","intoxicate,"],["e","and"],["te","you"],["esconderás;","you-will-hide;"],["também","also"],["buscarás","you-will-seek"],["força","strength"],["por","by"],["causa","sake"],["do","of-the"],["inimigo.","enemy."]]},
  {num:12,words:[["Todas","Things"],["as","the"],["tuas","your"],["fortalezas","fortification"],["serão","they-will-be"],["como","as"],["figueiras","sycomore"],["com","with"],["figos","figs"],["temporãos;","firstripe;"],["se","if"],["as","the"],["sacodem,","they-abet,"],["eles","they"],["caem","fadeth"],["na","in-the"],["boca","mouth"],["do","of-the"],["que","that"],["os","the"],["há","has"],["de","of"],["comer.","eat."]]},
  {num:13,words:[["Eis que","behold"],["o","the"],["teu","your"],["povo","people"],["no","in-the"],["meio","midst"],["de","of"],["ti","you"],["será","will-be"],["como","as"],["mulheres;","women;"],["as","the"],["portas","gates"],["da","of-the"],["tua","your"],["terra","land"],["estarão","they-will-be"],["de todo","wholly"],["abertas","carved"],["aos","to-the"],["teus","your"],["inimigos;","enemies;"],["o","the"],["fogo","fire"],["consumirá","devour"],["os","the"],["teus","your"],["ferrolhos.","bars."]]},
  {num:14,words:[["Tira","Ribbon"],["águas","waters"],["para","for"],["o","the"],["cerco,","siege,"],["fortifica","dasheth"],["as","the"],["tuas","your"],["fortalezas,","fortification,"],["entra","entereth"],["no","in-the"],["lodo,","mud,"],["e","and"],["pisa","treadeth"],["o","the"],["barro,","clay,"],["pega","gets"],["a","to"],["forma","form"],["para","for"],["tijolos.","brick."]]},
  {num:15,words:[["O","The"],["fogo","fire"],["ali","there"],["te","you"],["consumirá,","devour,"],["a","to"],["espada","sword"],["te","you"],["exterminará,","will-reverse,"],["te","you"],["consumirá,","devour,"],["como","as"],["a","to"],["locusta;","grasshopper;"],["multiplica-te","to-multiplicar-se"],["como","as"],["a","to"],["locusta,","grasshopper,"],["multiplica-te","to-multiplicar-se"],["como","as"],["os","the"],["gafanhotos.","locusts."]]},
  {num:16,words:[["Multiplicaste","You-multiplied"],["os","the"],["teus","your"],["negociantes","merchants"],["mais","still"],["do","of-the"],["que","that"],["as","the"],["estrelas","stars"],["do","of-the"],["céu;","heaven;"],["a","to"],["locusta","grasshopper"],["se","if"],["espalhará","will-disseminate"],["e","and"],["voará.","will-fly."]]},
  {num:17,words:[["Os","The"],["teus","your"],["príncipes","princes"],["são","they-are"],["como","as"],["os","the"],["gafanhotos,","locusts,"],["e","and"],["os","the"],["teus","your"],["chefes,","authority,"],["como","as"],["os","the"],["gafanhotos","locusts"],["grandes,","great,"],["que","that"],["se","if"],["acampam","they-camp"],["nas","in-the"],["sebes","hedge"],["nos","us"],["dias","days"],["de","of"],["frio;","cold;"],["ao","to-the"],["sair","exit"],["o","the"],["sol","sun"],["voam,","they-fly,"],["de sorte que","so-that"],["não","no"],["se","if"],["sabe","knows"],["mais","still"],["o","the"],["lugar","place"],["onde","where"],["estão.","they-are."]]},
  {num:18,words:[["Os","The"],["teus","your"],["pastores","shepherds"],["dormitarão,","they-will-doze,"],["ó","O"],["rei","king"],["da","of-the"],["Assíria;","Assyria;"],["os","the"],["teus","your"],["ilustres","you-illustrate"],["deitar-se-ão;","they-will-lie down;"],["o","the"],["teu","your"],["povo","people"],["se","if"],["derramará","bottom"],["pelos","by-the"],["montes,","mountains,"],["sem","without"],["que","that"],["haja","has"],["quem","who"],["o","the"],["ajunte.","adds."]]},
  {num:19,words:[["Não","No"],["há","has"],["cura","healing"],["para","for"],["a","to"],["tua","your"],["ferida,","wound,"],["a","to"],["tua","your"],["chaga","wound"],["é","is"],["dolorosa;","painful;"],["todos","all"],["os","the"],["que","that"],["ouvirem","they-will-hear"],["a","to"],["tua","your"],["fama","fame"],["baterão","they-will-knocking"],["palmas","palm"],["sobre","upon"],["ti;","you;"],["porque,","because,"],["sobre","upon"],["quem","who"],["não","no"],["passou","passed"],["continuamente","continually"],["a","to"],["tua","your"],["maldade?","wickedness?"]]}
];
renderVerseSet(v1, 'nah-ch1-verses');
renderVerseSet(v2, 'nah-ch2-verses');
renderVerseSet(v3, 'nah-ch3-verses');
})();
