(function() {
var v1 = [
  {num:1,words:[["Peso","Weight"],["de","of"],["Nínive.","Nineveh."],["Livro","Book"],["da","of-the"],["visão","vision"],["de","of"],["Naum,","Naum,"],["o","the"],["elcosita.","elcosita."]]},
  {num:2,words:[["O","The"],["Senhor","Lord"],["é","is"],["Deus","God"],["zeloso","zealous"],["e","and"],["que","that"],["toma","gets"],["vingança;","vengeance;"],["o","the"],["Senhor","Lord"],["toma","gets"],["vingança","vengeance"],["e","and"],["tem","has"],["furor;","fury;"],["o","the"],["Senhor","Lord"],["toma","gets"],["vingança","vengeance"],["contra","against"],["os","the"],["seus","his"],["adversários,","adversaries,"],["e","and"],["guarda","guard"],["a","to"],["ira","anger"],["contra","against"],["os","the"],["seus","his"],["inimigos.","enemies."]]},
  {num:3,words:[["O","The"],["Senhor","Lord"],["é","is"],["tardio","late"],["em","in"],["irar-se,","to-acquit,"],["porém","but"],["grande","great"],["em","in"],["força,","strength,"],["e","and"],["ao","to-the"],["culpado","guilty"],["não","not"],["tem","has"],["por","by"],["inocente;","innocent;"],["o","the"],["Senhor,","Lord,"],["cujo","whose"],["caminho","way"],["é","is"],["na","in-the"],["tormenta,","torment,"],["e","and"],["na","in-the"],["tempestade,","hurricane,"],["e","and"],["as","the"],["nuvens","clouds"],["são","they-are"],["o","the"],["pó","dust"],["dos","of-the"],["seus","his"],["pés.","feet."]]},
  {num:4,words:[["Ele","He"],["repreende","admonishes"],["o","the"],["mar,","sea,"],["e","and"],["o","him"],["faz","makes"],["secar,","wither,"],["e","and"],["esgota","consumes"],["todos","all"],["os","the"],["rios;","rivers;"],["desfalecem","they-faint"],["Basã","Bashan"],["e","and"],["Carmelo,","Carmel,"],["e","and"],["a","the"],["flor","flour"],["do","of-the"],["Líbano","Lebanon"],["murcha.","languish."]]},
  {num:5,words:[["Os","The"],["montes","mountains"],["tremem","tremble"],["perante","before"],["ele,","he,"],["e","and"],["os","the"],["outeiros","hills"],["se","himself"],["derretem;","they-melt;"],["e","and"],["a","the"],["terra","land"],["se","himself"],["agita","abets"],["na","in-the"],["sua","his"],["presença,","presence,"],["e","and"],["o","the"],["mundo,","world,"],["e","and"],["todos","all"],["os","the"],["que","that"],["nele","in-him"],["habitam.","they-dwell."]]},
  {num:6,words:[["Quem","Who"],["parará","will-halt"],["diante","before"],["do","of-the"],["seu","his"],["furor?","fury?"],["e","and"],["quem","who"],["persistirá","will-abide"],["diante","before"],["do","of-the"],["ardor","glow"],["da","of-the"],["sua","his"],["ira?","anger?"],["A","To"],["sua","his"],["cólera","cholera"],["se","himself"],["derramou","poured"],["como","as"],["um","a"],["fogo,","fire,"],["e","and"],["as","the"],["rochas","rocks"],["foram","they-were"],["por","by"],["ele","he"],["derrubadas.","overthrown."]]},
  {num:7,words:[["O","The"],["Senhor","Lord"],["é","is"],["bom,","good,"],["ele","he"],["serve","serves"],["de","of"],["fortaleza","fortification"],["no","in-the"],["dia","day"],["da","of-the"],["angústia,","anguish,"],["e","and"],["conhece","know"],["os","the"],["que","that"],["confiam","they-confide"],["nele.","in-him."]]},
  {num:8,words:[["E","And"],["com","with"],["uma","a"],["inundação","flood"],["transbordante","overrunning"],["acabará","will-finish"],["de","of"],["uma vez","once"],["com","with"],["o","the"],["seu","his"],["lugar;","place;"],["e","and"],["as","the"],["trevas","darkness"],["perseguirão","they-will-persecute"],["os","the"],["seus","his"],["inimigos.","enemies."]]},
  {num:9,words:[["Que","That"],["pensais","you-reality"],["vós","you"],["contra","against"],["o","the"],["Senhor?","Lord?"],["Ele","He"],["mesmo","himself"],["vos","you"],["consumirá","devour"],["de todo;","wholly"],["não","not"],["se","himself"],["levantará","will-hoist"],["uma","a"],["segunda","second"],["vez","time"],["a","the"],["angústia.","anguish."]]},
  {num:10,words:[["Porque","Because"],["eles","they"],["se","himself"],["entrelaçam","folden"],["como","as"],["os","the"],["espinhos,","thorns,"],["e","and"],["se","if"],["embebedam","folden"],["como","as"],["bêbados;","drunkards;"],["serão","they-will-be"],["inteiramente","entirely"],["consumidos","consumed"],["como","as"],["palha","straw"],["seca.","withers."]]},
  {num:11,words:[["De","Of"],["ti","you"],["saiu","went-forth"],["um","a"],["que","that"],["pensou","reality"],["mal","evil"],["contra","against"],["o","the"],["Senhor,","Lord,"],["um","a"],["conselheiro","counsellor"],["ímpio.","wicked."]]},
  {num:12,words:[["Assim diz","thus-saith"],["o","the"],["Senhor:","Lord:"],["Por","By"],["mais","more"],["seguros","safely"],["que","that"],["estejam,","they-are,"],["e","and"],["por","by"],["mais","more"],["numerosos","numerous"],["que","that"],["sejam,","they-are,"],["ainda","yet"],["assim","thus"],["serão","they-will-be"],["tosquiados,","clip,"],["e","and"],["ele","he"],["passará;","will-fare;"],["eu","I"],["te","you"],["afligi,","I-afflicted,"],["porém","but"],["não","not"],["te","you"],["afligirei","I-will-afflict"],["mais.","more."]]},
  {num:13,words:[["Mas","But"],["agora","now"],["quebrarei","I-will-crush"],["o","the"],["seu","his"],["jugo","I-yoke"],["de","of"],["sobre","upon"],["ti,","you,"],["e","and"],["romperei","I-will-break"],["os","the"],["teus","your"],["laços.","snares."]]},
  {num:14,words:[["Porém","But"],["contra","against"],["ti","you"],["o","the"],["Senhor","Lord"],["deu","gave"],["ordem,","order,"],["para que","that"],["não","not"],["haja","has"],["mais","more"],["semente","seed"],["do","of-the"],["teu","your"],["nome;","name;"],["da","of-the"],["casa","house"],["do","of-the"],["teu","your"],["deus","god"],["exterminarei","I-will-reverse"],["as","the"],["imagens","images"],["de","of"],["escultura","graven"],["e","and"],["de","of"],["fundição;","molten;"],["ali","there"],["te","you"],["farei","I-will-make"],["o","the"],["teu","your"],["sepulcro,","sepulchre,"],["porque","because"],["és","you-are"],["vil.","vile."]]},
  {num:15,words:[["Eis","Behold"],["sobre","upon"],["os","the"],["montes","mountains"],["os","the"],["pés","feet"],["do que","than"],["traz","brings"],["as","the"],["boas","tidings"],["novas,","tidings,"],["do que","than"],["anuncia","advertise"],["a","the"],["paz!","peace!"],["Celebra","Celebrates"],["as","the"],["tuas","your"],["festas,","feasts,"],["ó","O"],["Judá,","Judah,"],["cumpre","observes"],["os","the"],["teus","your"],["votos,","vows,"],["porque","because"],["o","the"],["ímpio","wicked"],["não","not"],["tornará","will-become"],["mais","more"],["a","to"],["passar","to-fare"],["por","by"],["ti;","you;"],["ele","he"],["é","is"],["inteiramente","entirely"],["exterminado.","publish."]]}
];
var v2 = [
  {num:1,words:[["O","The"],["destruidor","destroyer"],["subiu","climbed"],["contra","against"],["ti;","you;"],["guarda","guard"],["tu","you"],["a","the"],["fortaleza,","fortification,"],["observa","observes"],["o","the"],["caminho,","way,"],["fortifica","dasheth"],["os","the"],["lombos,","loins,"],["reforça","booster"],["muito","much"],["o","the"],["poder.","power."]]},
  {num:2,words:[["Porque","Because"],["o","the"],["Senhor","Lord"],["tornará","will-become"],["a","the"],["excelência","excellency"],["de","of"],["Jacó","Jacob"],["como","as"],["a","the"],["excelência","excellency"],["de","of"],["Israel;","Israel;"],["porque","because"],["os","the"],["despojadores","spoilester"],["os","them"],["despojaram,","they-stripped,"],["e","and"],["arruinaram","they-damaged"],["os","the"],["seus","their"],["sarmentos.","sprigs."]]},
  {num:3,words:[["Os","The"],["escudos","shields"],["dos","of-the"],["seus","his"],["valentes","brave"],["serão","they-will-be"],["tintos","dyed"],["de","of"],["vermelho,","red,"],["os","the"],["homens","men"],["valorosos","valour"],["andarão","they-will-walk"],["vestidos","clothed"],["de","of"],["escarlate,","scarlet,"],["os","the"],["carros","chariots"],["correrão","they-will-flow"],["como","as"],["fogo","fire"],["de","of"],["tochas","torches"],["no","in-the"],["dia","day"],["do","of-the"],["seu","his"],["aparelhamento,","torches,"],["e","and"],["as","the"],["lanças","spears"],["serão","they-will-be"],["brandidas.","torches."]]},
  {num:4,words:[["Os","The"],["carros","chariots"],["correrão","they-will-flow"],["furiosamente","furiously"],["nas","in-the"],["ruas,","streets,"],["vaguearão","justle"],["pelas","by-the"],["praças;","markets;"],["a","to"],["sua","his"],["aparência","appearance"],["é","is"],["como","as"],["a","to"],["de","of"],["tochas,","torches,"],["correrão","they-will-flow"],["como","as"],["relâmpagos.","lightnings."]]},
  {num:5,words:[["Ele","He"],["se","himself"],["lembrará","will-remember"],["dos","of-the"],["seus","their"],["valentes,","brave,"],["eles","they"],["porém","but"],["tropeçarão","they-will-stumble"],["na","in-the"],["sua","his"],["marcha;","march;"],["apressar-se-ão","accelerate-himself"],["para","for"],["o","the"],["seu","his"],["muro,","wall,"],["quando","when"],["a","the"],["defesa","protection"],["for","will-be"],["preparada.","prepared."]]},
  {num:6,words:[["As","The"],["portas","gates"],["do","of-the"],["rio","river"],["se","himself"],["abrirão,","they-will-open,"],["e","and"],["o","the"],["palácio","palace"],["se","himself"],["derreterá.","will-melt."]]},
  {num:7,words:[["Pois","For"],["determinado","determined"],["está;","is;"],["ela","she"],["será","will-be"],["levada","brought"],["cativa,","captive,"],["será","will-be"],["levada","brought"],["para","for"],["cima,","above,"],["e","and"],["as","them"],["suas","their"],["servas","servant"],["a","it"],["acompanharão,","they-will-accompany,"],["gemendo","sighing"],["como","as"],["pombas,","doves,"],["batendo","knockinging"],["no","in-the"],["peito.","breast."]]},
  {num:8,words:[["Nínive","Nineveh"],["desde","since"],["que","that"],["existe","exists"],["tem","has"],["sido","been"],["como","as"],["um","a"],["tanque","pool"],["de","of"],["águas,","waters,"],["porém","but"],["elas","they"],["agora","now"],["fogem.","they-flee."],["Parai,","Halt,"],["parai,","halt,"],["clamar-se-á;","will-cry-himself;"],["mas","but"],["ninguém","none"],["olhará","will-glance"],["para","for"],["trás.","behind."]]},
  {num:9,words:[["Saqueai","Furniture"],["a","the"],["prata,","silver,"],["saqueai","furniture"],["o","the"],["ouro,","gold,"],["porque","because"],["não","not"],["têm","they-have"],["fim","end"],["as","the"],["provisões,","provisions,"],["abastança","straits"],["há","there-is"],["de todo","wholly"],["gênero","clan"],["de","of"],["objetos","jewels"],["desejáveis.","you-desired."]]},
  {num:10,words:[["Vazia,","Empty,"],["e","and"],["despojada,","carefulness,"],["e","and"],["esgotada","exhausted"],["está,","is,"],["e","and"],["desfaleceu","fainted"],["o","the"],["seu","his"],["coração,","heart,"],["e","and"],["tremem","tremble"],["os","the"],["joelhos,","knees,"],["e","and"],["em","in"],["todos","all"],["os","the"],["lombos","loins"],["há","there-is"],["dor,","pain,"],["e","and"],["o","the"],["rosto","face"],["de","of"],["todos","all"],["eles","they"],["empalidece.","melteth."]]},
  {num:11,words:[["Onde","Where"],["estão","they-are"],["agora","now"],["o","the"],["covil","den"],["dos","of-the"],["leões","lions"],["e","and"],["as","to"],["pastagens","feedingplace"],["dos","of-the"],["leõezinhos,","lion,"],["onde","where"],["passeava","strolled"],["o","the"],["leão","lion"],["velho,","ancient,"],["e","and"],["o","the"],["filhote","roe"],["do","of-the"],["leão,","lion,"],["sem","without"],["haver","have"],["ninguém","none"],["que","that"],["os","them"],["espantasse?","feedingplace?"]]},
  {num:12,words:[["O","The"],["leão","lion"],["arrebatava","snap up"],["o","the"],["que","that"],["bastava","sufficed"],["para","for"],["os","the"],["seus","his"],["filhotes,","whelps,"],["e","and"],["estrangulava","choked"],["a","the"],["presa","prey"],["para","for"],["as","the"],["suas","his"],["leoas,","lion,"],["e","and"],["enchia","replenished"],["de","of"],["presas","prisoner"],["as","the"],["suas","his"],["cavernas,","caves,"],["e","and"],["de","of"],["rapina,","booty,"],["os","the"],["seus","his"],["covis.","den."]]},
  {num:13,words:[["Eis que","behold"],["eu","I"],["estou","I-am"],["contra","against"],["ti,","you,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Hosts,"],["e","and"],["queimarei","I-will-burn"],["na","in-the"],["fumaça","smoke"],["os","the"],["teus","your"],["carros,","chariots,"],["e","and"],["a","the"],["espada","sword"],["devorará","will-devour"],["os","the"],["teus","your"],["leõezinhos,","lion,"],["e","and"],["arrancarei","I-will-pluck"],["da","of-the"],["terra","land"],["a","to"],["tua","your"],["presa,","prey,"],["e","and"],["não","not"],["se","himself"],["ouvirá","will-hear"],["mais","more"],["a","the"],["voz","voice"],["dos","of-the"],["teus","your"],["embaixadores.","ambassadors."]]}
];
var v3 = [
  {num:1,words:[["Ai","Ouch"],["da","of-the"],["cidade","city"],["ensanguentada,","robbery,"],["que","that"],["está","is"],["toda","every"],["cheia","full"],["de","of"],["mentiras","lies"],["e","and"],["de","of"],["rapina!","booty!"],["Não","Not"],["se","himself"],["aparta","divides"],["dela","of-it"],["o","the"],["roubo.","highjack."]]},
  {num:2,words:[["Estrépito","Stamping"],["de","of"],["açoite","scourge"],["há,","there-is,"],["e","and"],["o","the"],["estrondo","noise"],["do","of-the"],["ruído","noise"],["das","of-the"],["rodas;","wheels;"],["e","and"],["os","the"],["cavalos","horses"],["atropelam,","rattling,"],["e","and"],["carros","chariots"],["vão","they-go"],["saltando.","jumping."]]},
  {num:3,words:[["O","The"],["cavaleiro","horseman"],["levanta","hoists"],["assim","thus"],["a","the"],["espada","sword"],["flamejante,","flaming,"],["e","and"],["a","it"],["lança","casts"],["relampejante,","horseman,"],["e","and"],["ali","there"],["haverá","will-have"],["uma","a"],["multidão","multitude"],["de","of"],["mortos,","dead,"],["e","and"],["abundância","abundance"],["de","of"],["cadáveres,","carcases,"],["e","and"],["não","not"],["terão","they-will-have"],["fim","end"],["os","the"],["defuntos;","cadaver;"],["tropeçarão","they-will-stumble"],["nos","us"],["seus","their"],["corpos;","bodies;"]]},
  {num:4,words:[["Por causa da","because-of"],["multidão","multitude"],["das","of-the"],["prostituições","whoredoms"],["da","of-the"],["meretriz","harlot"],["muito","much"],["graciosa,","elegant,"],["da","of-the"],["mestra","teacher"],["das","of-the"],["feitiçarias,","sorceries,"],["que","that"],["vendeu","sold"],["os","the"],["povos","nations"],["com","with"],["as","them"],["suas","her"],["prostituições,","whoredoms,"],["e","and"],["as","the"],["famílias,","families,"],["com","with"],["as","them"],["suas","her"],["feitiçarias.","sorceries."]]},
  {num:5,words:[["Eis que","behold"],["eu","I"],["estou","I-am"],["contra","against"],["ti,","you,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Hosts,"],["e","and"],["levantarei","I-will-hoist"],["a","to"],["tua","your"],["saia","skirt"],["sobre","upon"],["a","to"],["tua","your"],["face,","face,"],["e","and"],["às","to-the"],["nações","nations"],["mostrarei","I-will-show"],["a","to"],["tua","your"],["nudez,","nakedness,"],["e","and"],["aos","to-the"],["reinos,","kingdoms,"],["a","to"],["tua","your"],["vergonha.","shame."]]},
  {num:6,words:[["E","And"],["lançarei","I-will-cast"],["sobe","climbs"],["ti","you"],["coisas","things"],["abomináveis,","you-abhorred,"],["e","and"],["te","you"],["envergonharei,","I-will-abash,"],["e","and"],["por-te-ei","I-will-place-you"],["como","as"],["espetáculo.","spectacle."]]},
  {num:7,words:[["E","And"],["há","there-is"],["de","of"],["ser que","except"],["todos","all"],["os","the"],["que","that"],["te","you"],["virem","to-come"],["fugirão","they-will-flee"],["de","of"],["ti,","you,"],["e","and"],["dirão:","they-will-say:"],["Nínive","Nineveh"],["está","is"],["destruída,","destroyed,"],["quem","who"],["terá","will-have"],["compaixão","compassion"],["dela?","of-it?"],["donde","whence"],["te","you"],["buscarei","I-will-seek"],["consoladores?","comforters?"]]},
  {num:8,words:[["És","You-are"],["tu","you"],["melhor","better"],["do que","than"],["Nô-Amom,","Populous,"],["que","that"],["está","is"],["assentada","settle"],["nos","us"],["rios,","rivers,"],["cercada","besieged"],["de","of"],["águas,","waters,"],["que","that"],["tinha","had"],["por","by"],["esplanada","populous"],["o","the"],["mar,","sea,"],["cuja","whose"],["muralha","rampart"],["é","is"],["o","the"],["mar?","sea?"]]},
  {num:9,words:[["Etiópia","Ethiopia"],["e","and"],["Egito","Egypt"],["eram","they-were"],["a","to"],["sua","her"],["força,","strength,"],["e","and"],["ela","it"],["não","not"],["tinha","had"],["fim;","end;"],["Pute","Phut"],["e","and"],["Líbia","Lubim"],["foram","they-were"],["o","the"],["teu","your"],["socorro.","help."]]},
  {num:10,words:[["Todavia","Nevertheless"],["foi","was"],["levada","brought"],["cativa","captive"],["para","for"],["o","the"],["desterro;","I-exile;"],["também","also"],["os","the"],["seus","her"],["filhos","children"],["foram","they-were"],["despedaçados","dashed"],["no","in-the"],["topo","end"],["de","of"],["todas","things"],["as","the"],["ruas,","streets,"],["e","and"],["sobre","upon"],["os","the"],["seus","her"],["honrados","upright"],["lançaram","they-cast"],["sortes,","lots,"],["e","and"],["todos","all"],["os","the"],["seus","her"],["nobres","nobles"],["foram","they-were"],["presos","prisoner"],["com","with"],["grilhões.","fetters."]]},
  {num:11,words:[["Tu","You"],["também","also"],["serás","you-will-be"],["embriagada,","drunk,"],["e","and"],["te","you"],["esconderás;","you-will-hide;"],["também","also"],["buscarás","you-will-seek"],["força","strength"],["por causa do","because-of"],["inimigo.","enemy."]]},
  {num:12,words:[["Todas","Things"],["as","the"],["tuas","your"],["fortalezas","fortification"],["serão","they-will-be"],["como","as"],["figueiras","sycomore"],["com","with"],["figos","figs"],["temporãos;","firstripe;"],["se","if"],["as","them"],["sacodem,","they-abet,"],["eles","they"],["caem","they-fall"],["na","in-the"],["boca","mouth"],["do que","than"],["os","them"],["há","there-is"],["de","of"],["comer.","to-eat."]]},
  {num:13,words:[["Eis que","behold"],["o","the"],["teu","your"],["povo","people"],["no","in-the"],["meio","midst"],["de","of"],["ti","you"],["será","will-be"],["como","as"],["mulheres;","women;"],["as","the"],["portas","gates"],["da","of-the"],["tua","your"],["terra","land"],["estarão","they-will-be"],["de todo","wholly"],["abertas","carved"],["aos","to-the"],["teus","your"],["inimigos;","enemies;"],["o","the"],["fogo","fire"],["consumirá","devour"],["os","the"],["teus","your"],["ferrolhos.","bars."]]},
  {num:14,words:[["Tira","Deducts"],["águas","waters"],["para","for"],["o","the"],["cerco,","siege,"],["fortifica","dasheth"],["as","the"],["tuas","your"],["fortalezas,","fortification,"],["entra","enters"],["no","in-the"],["lodo,","mud,"],["e","and"],["pisa","crushes"],["o","the"],["barro,","clay,"],["pega","gets"],["a","the"],["forma","form"],["para","for"],["tijolos.","brick."]]},
  {num:15,words:[["O","The"],["fogo","fire"],["ali","there"],["te","you"],["consumirá,","devour,"],["a","the"],["espada","sword"],["te","you"],["exterminará,","will-reverse,"],["te","you"],["consumirá,","devour,"],["como","as"],["a","the"],["locusta;","grasshopper;"],["multiplica-te","multiplies-you"],["como","as"],["a","the"],["locusta,","grasshopper,"],["multiplica-te","multiplies-you"],["como","as"],["os","the"],["gafanhotos.","locusts."]]},
  {num:16,words:[["Multiplicaste","You-multiplied"],["os","the"],["teus","your"],["negociantes","merchants"],["mais","more"],["do que","than"],["as","the"],["estrelas","stars"],["do","of-the"],["céu;","heaven;"],["a","the"],["locusta","grasshopper"],["se","himself"],["espalhará","will-disseminate"],["e","and"],["voará.","will-fly."]]},
  {num:17,words:[["Os","The"],["teus","your"],["príncipes","princes"],["são","they-are"],["como","as"],["os","the"],["gafanhotos,","locusts,"],["e","and"],["os","the"],["teus","your"],["chefes,","authority,"],["como","as"],["os","the"],["gafanhotos","locusts"],["grandes,","great,"],["que","that"],["se","themselves"],["acampam","they-camp"],["nas","in-the"],["sebes","hedge"],["nos","us"],["dias","days"],["de","of"],["frio;","cold;"],["ao","to-the"],["sair","go-forth"],["o","the"],["sol","sun"],["voam,","they-fly,"],["de sorte que","so-that"],["não","not"],["se","himself"],["sabe","knows"],["mais","more"],["o","the"],["lugar","place"],["onde","where"],["estão.","they-are."]]},
  {num:18,words:[["Os","The"],["teus","your"],["pastores","shepherds"],["dormitarão,","they-will-doze,"],["ó","O"],["rei","king"],["da","of-the"],["Assíria;","Assyria;"],["os","the"],["teus","your"],["ilustres","you-illustrate"],["deitar-se-ão;","they-will-lay-himself;"],["o","the"],["teu","your"],["povo","people"],["se","himself"],["derramará","will-pour"],["pelos","by-the"],["montes,","mountains,"],["sem","without"],["que","that"],["haja","has"],["quem","who"],["o","him"],["ajunte.","adds."]]},
  {num:19,words:[["Não","Not"],["há","there-is"],["cura","healing"],["para","for"],["a","to"],["tua","your"],["ferida,","wound,"],["a","to"],["tua","your"],["chaga","wound"],["é","is"],["dolorosa;","painful;"],["todos","all"],["os","the"],["que","that"],["ouvirem","to-hear"],["a","to"],["tua","your"],["fama","fame"],["baterão","they-will-knock"],["palmas","palm"],["sobre","upon"],["ti;","you;"],["porque,","because,"],["sobre","upon"],["quem","who"],["não","not"],["passou","fared"],["continuamente","continually"],["a","to"],["tua","your"],["maldade?","wickedness?"]]}
];
renderVerseSet(v1, 'nah-ch1-verses');
renderVerseSet(v2, 'nah-ch2-verses');
renderVerseSet(v3, 'nah-ch3-verses');
})();
