(function() {
var v1 = [
  {num:1,words:[["Visão","Vision"],["de","of"],["Obadias:","Obadiah:"],["Assim diz","thus-saith"],["o","the"],["Senhor","Lord"],["Deus","God"],["a","the"],["Edom:","Edom:"],["Ouvimos","We-heard"],["a","the"],["pregação","preaching"],["do","of-the"],["Senhor,","Lord,"],["e","and"],["foi","was"],["enviado","sent"],["entre","among"],["as","the"],["nações","nations"],["um","a"],["embaixador;","ambassador;"],["levantai-vos,","raise-up-you,"],["e","and"],["levantemo-nos","raise-up-us"],["contra","against"],["ela","her"],["para","for"],["a","the"],["guerra.","war."]]},
  {num:2,words:[["Eis que","behold"],["te","you"],["fiz","I-made"],["pequeno","small"],["entre","among"],["as","the"],["nações;","nations;"],["tu","you"],["és","you-are"],["muito","much"],["desprezado.","despised."]]},
  {num:3,words:[["A","The"],["soberba","pride"],["do","of-the"],["teu","your"],["coração","heart"],["te","you"],["enganou,","deceived,"],["como","as"],["o","the"],["que","that"],["habita","dwell"],["nas","in-the"],["fendas","you-split"],["das","of-the"],["rochas,","rocks,"],["na","in-the"],["sua","his"],["alta","loud"],["morada,","dwelt,"],["que","that"],["diz","says"],["no","in-the"],["seu","his"],["coração:","heart:"],["Quem","Who"],["me","me"],["derrubará","will-overthrow"],["em","in"],["terra?","ground?"]]},
  {num:4,words:[["Se","If"],["te","you"],["elevares","to-lever"],["como","as"],["águia,","eagle,"],["e","and"],["puseres","you-will-place"],["o","the"],["teu","your"],["ninho","nest"],["entre","among"],["as","the"],["estrelas,","stars,"],["dali","of-at that place"],["te","you"],["derrubarei,","I-will-overthrow,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:5,words:[["Se","If"],["viessem","they-came"],["a","to"],["ti","you"],["ladrões,","robbers,"],["ou","or"],["roubadores","extortioners"],["de","of"],["noite","night"],["(como","(as"],["estás","you-are"],["destruído!),","destroyed!),"],["porventura","perchance"],["não","not"],["furtariam","steal"],["o","the"],["que","that"],["lhes","to-them"],["bastasse?","sufficed?"],["se","if"],["a","to"],["ti","you"],["viessem","they-came"],["os","the"],["vindimadores,","vintager,"],["porventura","perchance"],["não","not"],["deixariam","they-should-leave"],["respigo?","grapegatherers?"]]},
  {num:6,words:[["Como","As"],["foram","they-were"],["esquadrinhadas","searched"],["as","the"],["coisas","things"],["de","of"],["Esaú!","Esau!"],["como","as"],["foram","they-were"],["investigados","examined"],["os","the"],["seus","his"],["esconderijos!","hiding!"]]},
  {num:7,words:[["Todos","All"],["os","the"],["teus","your"],["confederados","confederate"],["te","you"],["levaram","they-carried"],["para","for"],["fora","outside"],["até","until"],["os","the"],["limites;","bounds;"],["os","the"],["que","that"],["gozam","they-enjoy"],["da","of-the"],["tua","your"],["paz","peace"],["te","you"],["enganaram,","they-deceived,"],["prevaleceram","they-prevailed"],["contra","against"],["ti;","you;"],["os","the"],["que","that"],["comem","they-eat"],["o","the"],["teu","your"],["pão","bread"],["puseram","they-placed"],["debaixo de","under"],["ti","you"],["uma","a"],["armadilha;","snare;"],["não","not"],["há","there-is"],["nele","in-him"],["entendimento.","understanding."]]},
  {num:8,words:[["Porventura","Perchance"],["não","not"],["acontecerá","will-come-to-pass"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["que","that"],["farei","I-will-make"],["perecer","to-perish"],["os","the"],["sábios","wise"],["de","of"],["Edom,","Edom,"],["e","and"],["o","the"],["entendimento,","understanding,"],["da","of-the"],["montanha","mountain"],["de","of"],["Esaú?","Esau?"]]},
  {num:9,words:[["E","And"],["os","the"],["teus","your"],["valentes,","brave,"],["ó","O"],["Temã,","Teman,"],["estarão","they-will-be"],["atemorizados,","affrighted,"],["para que","that"],["da","of-the"],["montanha","mountain"],["de","of"],["Esaú","Esau"],["seja","is"],["cada","every"],["um","a"],["exterminado","publish"],["pela","by-the"],["matança.","slaughter."]]},
  {num:10,words:[["Por causa da","because-of"],["violência","violence"],["feita","occasion"],["a","to"],["teu","your"],["irmão","brother"],["Jacó,","Jacob,"],["cobrir-te-á","will-cover-you"],["a","the"],["vergonha,","shame,"],["e","and"],["serás","you-will-be"],["exterminado","publish"],["para sempre.","for-ever"]]},
  {num:11,words:[["No","In-the"],["dia","day"],["em","in"],["que","that"],["o","him"],["confrontaste,","foreigners,"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["os","the"],["forasteiros","foreigners"],["levavam","they-carried"],["cativo","captive"],["o","the"],["seu","his"],["exército,","army,"],["e","and"],["os","the"],["estranhos","strangers"],["entravam","they-entered"],["pelas","by-the"],["suas","his"],["portas,","gates,"],["e","and"],["lançavam","they-cast"],["sortes","lots"],["sobre","upon"],["Jerusalém,","Jerusalem,"],["tu","you"],["eras","you-were"],["também","also"],["como","as"],["um","a"],["deles.","of-them."]]},
  {num:12,words:[["Então","Then"],["tu","you"],["não","not"],["devias","you-musted"],["ver","see"],["satisfeito","contented"],["o","the"],["dia","day"],["de","of"],["teu","your"],["irmão,","brother,"],["no","in-the"],["dia","day"],["do","of-the"],["seu","their"],["desterro;","I-exile;"],["nem","nor"],["alegrar-te","to-gladden-you"],["sobre","upon"],["os","the"],["filhos","children"],["de","of"],["Judá,","Judah,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","their"],["ruína;","ruin;"],["nem","nor"],["falar","to-speak"],["arrogantemente,","arrogantly,"],["no","in-the"],["dia","day"],["da","of-the"],["angústia;","anguish;"]]},
  {num:13,words:[["Nem","Nor"],["entrar","to-enter"],["pela","by-the"],["porta","exit"],["do","of-the"],["meu","my"],["povo,","people,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","their"],["calamidade;","calamity;"],["nem","nor"],["tampouco","neither"],["devias","you-musted"],["ver","see"],["satisfeito","contented"],["o","the"],["seu","their"],["mal,","evil,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","their"],["calamidade;","calamity;"],["nem","nor"],["pôr","to-place"],["as","the"],["mãos","hands"],["nos","in-the"],["seus","their"],["bens,","property,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","their"],["calamidade;","calamity;"]]},
  {num:14,words:[["Nem","Nor"],["parar","to-halt"],["nas","in-the"],["encruzilhadas,","knot,"],["para","for"],["lhe","to-him"],["exterminares","to-reverse"],["os","the"],["que","that"],["escapassem;","they-scaped;"],["nem","nor"],["entregar","deliver"],["os","the"],["que","that"],["lhe","to-him"],["restassem,","they-remained,"],["no","in-the"],["dia","day"],["da","of-the"],["angústia.","anguish."]]},
  {num:15,words:[["Porque","Because"],["o","the"],["dia","day"],["do","of-the"],["Senhor","Lord"],["está","is"],["perto,","near,"],["sobre","upon"],["todas","all"],["as","the"],["nações;","nations;"],["como","as"],["tu","you"],["fizeste,","you-made,"],["assim","thus"],["se","himself"],["fará","will-make"],["contigo;","with-you;"],["a","the"],["tua","your"],["recompensa","reward"],["retornará","will-return"],["sobre","upon"],["a","the"],["tua","your"],["cabeça.","head."]]},
  {num:16,words:[["Porque,","Because,"],["como","as"],["vós","you"],["bebestes","you-drank"],["no","in-the"],["monte","mountain"],["da","of-the"],["minha","my"],["santidade,","holiness,"],["beberão","they-will-drink"],["também","also"],["continuamente","continually"],["todas","all"],["as","the"],["nações;","nations;"],["beberão,","they-will-drink,"],["e","and"],["engulirão,","swallow,"],["e","and"],["serão","they-will-be"],["como se","as-if"],["nunca","never"],["tivessem","they-had"],["existido.","existed."]]},
  {num:17,words:[["Porém","But"],["no","in-the"],["monte","mountain"],["Sião","Zion"],["haverá","there-will-be"],["livramento;","deliverance;"],["e","and"],["ele","he"],["será","will-be"],["santo;","holy;"],["e","and"],["os","the"],["da","of-the"],["casa","house"],["de","of"],["Jacó","Jacob"],["possuirão","they-will-possess"],["as","the"],["suas","their"],["herdades.","heritages."]]},
  {num:18,words:[["E","And"],["a","the"],["casa","house"],["de","of"],["Jacó","Jacob"],["será","will-be"],["fogo,","fire,"],["e","and"],["a","the"],["casa","house"],["de","of"],["José","Joseph"],["chama,","flame,"],["e","and"],["a","the"],["casa","house"],["de","of"],["Esaú,","Esau,"],["palha;","straw;"],["e","and"],["se","if"],["acenderão","they-will-kindle"],["contra","against"],["eles,","they,"],["e","and"],["os","them"],["consumirão;","they-will-consume;"],["e","and"],["ninguém","none"],["mais","more"],["restará","will-remain"],["da","of-the"],["casa","house"],["de","of"],["Esaú,","Esau,"],["porque","because"],["o","the"],["Senhor","Lord"],["o","it"],["falou.","spoke."]]},
  {num:19,words:[["E","And"],["os","the"],["do","of-the"],["sul","south"],["possuirão","they-will-possess"],["a","the"],["montanha","mountain"],["de","of"],["Esaú,","Esau,"],["e","and"],["os","the"],["das","of-the"],["planícies,","plains,"],["os","the"],["filisteus;","philistines;"],["possuirão","they-will-possess"],["também","also"],["os","the"],["campos","fields"],["de","of"],["Efraim,","Ephraim,"],["e","and"],["os","the"],["campos","fields"],["de","of"],["Samaria;","Samaria;"],["e","and"],["Benjamim","Benjamin"],["possuirá","will-possess"],["Gileade.","Gilead."]]},
  {num:20,words:[["E","And"],["os","the"],["cativos","captives"],["deste","of-this"],["exército,","army,"],["dos","of-the"],["filhos","children"],["de","of"],["Israel,","Israel,"],["possuirão","they-will-possess"],["o","the"],["que","that"],["era","was"],["dos","of-the"],["cananeus,","canaanites,"],["até","until"],["Sarepta;","Zarephath;"],["e","and"],["os","the"],["cativos","captives"],["de","of"],["Jerusalém,","Jerusalem,"],["que","that"],["estão","they-are"],["em","in"],["Sefarade,","Sepharad,"],["possuirão","they-will-possess"],["as","the"],["cidades","cities"],["do","of-the"],["sul.","south."]]},
  {num:21,words:[["E","And"],["levantar-se-ão","they-will-arise"],["salvadores","Savior"],["no","in-the"],["monte","mountain"],["Sião,","Zion,"],["para","to"],["julgarem","to-judge"],["a","the"],["montanha","mountain"],["de","of"],["Esaú;","Esau;"],["e","and"],["o","the"],["reino","kingdom"],["será","will-be"],["do","of-the"],["Senhor.","Lord."]]}
];
renderVerseSet(v1, 'oba-ch1-verses');
})();
