(function() {
var v1 = [
  {num:1,words:[["Visão","Vision"],["de","of"],["Obadias:","Obadiah:"],["Assim diz","thus-saith"],["o","the"],["Senhor","Lord"],["Deus","God"],["a","to"],["Edom:","Edom:"],["Ouvimos","We-hear"],["a","to"],["pregação","preaching"],["do","of-the"],["Senhor,","Lord,"],["e","and"],["foi","was"],["enviado","sent"],["entre","between"],["as","the"],["nações","nations"],["um","a"],["embaixador;","ambassador;"],["levantai-vos,","arise,"],["e","and"],["levantemo-nos","loves"],["contra","against"],["ela","she"],["para","for"],["a","to"],["guerra.","war."]]},
  {num:2,words:[["Eis que","behold"],["te","you"],["fiz","I-made"],["pequeno","small"],["entre","between"],["as","the"],["nações;","nations;"],["tu","you"],["és","you-are"],["muito","much"],["desprezado.","despised."]]},
  {num:3,words:[["A","To"],["soberba","pride"],["do","of-the"],["teu","your"],["coração","heart"],["te","you"],["enganou,","beguiled,"],["como","as"],["o","the"],["que","that"],["habita","dwelleth"],["nas","in-the"],["fendas","you-split"],["das","of-the"],["rochas,","rocks,"],["na","in-the"],["sua","his"],["alta","loud"],["morada,","dwelling,"],["que","that"],["diz","says"],["no","in-the"],["seu","his"],["coração:","heart:"],["Quem","Who"],["me","me"],["derrubará","will-overthrow"],["em","in"],["terra?","land?"]]},
  {num:4,words:[["Se","If"],["te","you"],["elevares","you-will-lever"],["como","as"],["águia,","eagle,"],["e","and"],["puseres","you-will-place"],["o","the"],["teu","your"],["ninho","nest"],["entre","between"],["as","the"],["estrelas,","stars,"],["dali","of-at that place"],["te","you"],["derrubarei,","pull,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:5,words:[["Se","If"],["viessem","they-came"],["a","to"],["ti","you"],["ladrões,","robbers,"],["ou","or"],["roubadores","extortioners"],["de","of"],["noite","night"],["(como","(as"],["estás","you-are"],["destruído!),","destroyed!),"],["porventura","perchance"],["não","no"],["furtariam","steal"],["o","the"],["que","that"],["lhes","to-them"],["bastasse?","sufficed?"],["se","if"],["a","to"],["ti","you"],["viessem","they-came"],["os","the"],["vindimadores,","vintager,"],["porventura","perchance"],["não","no"],["deixariam","they-should-allow"],["respigo?","grapegatherers?"]]},
  {num:6,words:[["Como","As"],["foram","they-were"],["esquadrinhadas","searched"],["as","the"],["coisas","things"],["de","of"],["Esaú!","Esau!"],["como","as"],["foram","they-were"],["investigados","examine"],["os","the"],["seus","his"],["esconderijos!","hiding!"]]},
  {num:7,words:[["Todos","All"],["os","the"],["teus","your"],["confederados","confederate"],["te","you"],["levaram","carried"],["para","for"],["fora","outside"],["até","until"],["os","the"],["limites;","bounds;"],["os","the"],["que","that"],["gozam","they-enjoy"],["da","of-the"],["tua","your"],["paz","peace"],["te","you"],["enganaram,","they-deceived,"],["prevaleceram","prevailed"],["contra","against"],["ti;","you;"],["os","the"],["que","that"],["comem","they-eat"],["o","the"],["teu","your"],["pão","bread"],["puseram","they-placed"],["debaixo de","under"],["ti","you"],["uma","a"],["armadilha;","snare;"],["não","no"],["há","has"],["nele","in-him"],["entendimento.","understanding."]]},
  {num:8,words:[["Porventura","Perchance"],["não","no"],["acontecerá","will-become"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["que","that"],["farei","I-will-make"],["perecer","perish"],["os","the"],["sábios","wise"],["de","of"],["Edom,","Edom,"],["e","and"],["o","the"],["entendimento,","understanding,"],["da","of-the"],["montanha","mountain"],["de","of"],["Esaú?","Esau?"]]},
  {num:9,words:[["E","And"],["os","the"],["teus","your"],["valentes,","brave,"],["ó","O"],["Temã,","Teman,"],["estarão","they-will-be"],["atemorizados,","affrighted,"],["para que","that"],["da","of-the"],["montanha","mountain"],["de","of"],["Esaú","Esau"],["seja","is"],["cada","every"],["um","a"],["exterminado","publisheth"],["pela","by-the"],["matança.","slaughter."]]},
  {num:10,words:[["Por","By"],["causa","sake"],["da","of-the"],["violência","violence"],["feita","occasion"],["a","to"],["teu","your"],["irmão","brother"],["Jacó,","Jacob,"],["cobrir-te-á","cover-you"],["a","to"],["vergonha,","shame,"],["e","and"],["serás","you-will-be"],["exterminado","publisheth"],["para sempre.","for-ever"]]},
  {num:11,words:[["No","In-the"],["dia","day"],["em","in"],["que","that"],["o","the"],["confrontaste,","foreigners,"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["os","the"],["forasteiros","foreigners"],["levavam","they-carried"],["cativo","captive"],["o","the"],["seu","his"],["exército,","army,"],["e","and"],["os","the"],["estranhos","strangers"],["entravam","courses"],["pelas","by-the"],["suas","his"],["portas,","gates,"],["e","and"],["lançavam","they-vomited"],["sortes","lots"],["sobre","upon"],["Jerusalém,","Jerusalem,"],["tu","you"],["eras","you-were"],["também","also"],["como","as"],["um","a"],["deles.","of-them."]]},
  {num:12,words:[["Então","Said"],["tu","you"],["não","no"],["devias","you-duty"],["ver","see"],["satisfeito","contented"],["o","the"],["dia","day"],["de","of"],["teu","your"],["irmão,","brother,"],["no","in-the"],["dia","day"],["do","of-the"],["seu","his"],["desterro;","dashed;"],["nem","nor"],["alegrar-te","gladden-you"],["sobre","upon"],["os","the"],["filhos","children"],["de","of"],["Judá,","Judah,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","his"],["ruína;","ruin;"],["nem","nor"],["falar","speak"],["arrogantemente,","arrogantly,"],["no","in-the"],["dia","day"],["da","of-the"],["angústia;","anguish;"]]},
  {num:13,words:[["Nem","Nor"],["entrar","enter"],["pela","by-the"],["porta","exit"],["do","of-the"],["meu","my"],["povo,","people,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","his"],["calamidade;","calamity;"],["nem","nor"],["tampouco","neither"],["devias","you-duty"],["ver","see"],["satisfeito","contented"],["o","the"],["seu","his"],["mal,","evil,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","his"],["calamidade;","calamity;"],["nem","nor"],["pôr","place"],["as","the"],["mãos","hands"],["nos","us"],["seus","his"],["bens,","good,"],["no","in-the"],["dia","day"],["da","of-the"],["sua","his"],["calamidade;","calamity;"]]},
  {num:14,words:[["Nem","Nor"],["parar","halt"],["nas","in-the"],["encruzilhadas,","knot,"],["para","for"],["lhe","to-him"],["exterminares","you-will-reverse"],["os","the"],["que","that"],["escapassem;","they-scaped;"],["nem","nor"],["entregar","betray"],["os","the"],["que","that"],["lhe","to-him"],["restassem,","they-remained,"],["no","in-the"],["dia","day"],["da","of-the"],["angústia.","anguish."]]},
  {num:15,words:[["Porque","Because"],["o","the"],["dia","day"],["do","of-the"],["Senhor","Lord"],["está","is"],["perto,","near,"],["sobre","upon"],["todas","things"],["as","the"],["nações;","nations;"],["como","as"],["tu","you"],["fizeste,","you-made,"],["assim","thus"],["se","if"],["fará","will-make"],["contigo;","with-you;"],["a","to"],["tua","your"],["recompensa","reward"],["retornará","will-recur"],["sobre","upon"],["a","to"],["tua","your"],["cabeça.","head."]]},
  {num:16,words:[["Porque,","Because,"],["como","as"],["vós","you"],["bebestes","you-drank"],["no","in-the"],["monte","mountain"],["da","of-the"],["minha","my"],["santidade,","holiness,"],["beberão","they-will-drink"],["também","also"],["continuamente","continually"],["todas","things"],["as","the"],["nações;","nations;"],["beberão,","they-will-drink,"],["e","and"],["engulirão,","swallow,"],["e","and"],["serão","they-will-be"],["como","as"],["se","if"],["nunca","never"],["tivessem","they-had"],["existido.","I-should-exist."]]},
  {num:17,words:[["Porém","But"],["no","in-the"],["monte","mountain"],["Sião","Zion"],["haverá","will-have"],["livramento;","deliverance;"],["e","and"],["ele","he"],["será","will-be"],["santo;","holy;"],["e","and"],["os","the"],["da","of-the"],["casa","house"],["de","of"],["Jacó","Jacob"],["possuirão","they-will-possess"],["as","the"],["suas","his"],["herdades.","heritages."]]},
  {num:18,words:[["E","And"],["a","to"],["casa","house"],["de","of"],["Jacó","Jacob"],["será","will-be"],["fogo,","fire,"],["e","and"],["a","to"],["casa","house"],["de","of"],["José","Joseph"],["chama,","flame,"],["e","and"],["a","to"],["casa","house"],["de","of"],["Esaú,","Esau,"],["palha;","straw;"],["e","and"],["se","if"],["acenderão","handstaves"],["contra","against"],["eles,","they,"],["e","and"],["os","the"],["consumirão;","they-will-consume;"],["e","and"],["ninguém","none"],["mais","still"],["restará","will-remain"],["da","of-the"],["casa","house"],["de","of"],["Esaú,","Esau,"],["porque","because"],["o","the"],["Senhor","Lord"],["o","the"],["falou.","spake."]]},
  {num:19,words:[["E","And"],["os","the"],["do","of-the"],["sul","south"],["possuirão","they-will-possess"],["a","to"],["montanha","mountain"],["de","of"],["Esaú,","Esau,"],["e","and"],["os","the"],["das","of-the"],["planícies,","plains,"],["os","the"],["filisteus;","philistines;"],["possuirão","they-will-possess"],["também","also"],["os","the"],["campos","fields"],["de","of"],["Efraim,","Ephraim,"],["e","and"],["os","the"],["campos","fields"],["de","of"],["Samaria;","Samaria;"],["e","and"],["Benjamim","Benjamin"],["possuirá","will-possess"],["Gileade.","Gilead."]]},
  {num:20,words:[["E","And"],["os","the"],["cativos","captives"],["deste","of-this"],["exército,","army,"],["dos","of-the"],["filhos","children"],["de","of"],["Israel,","Israel,"],["possuirão","they-will-possess"],["o","the"],["que","that"],["era","was"],["dos","of-the"],["cananeus,","canaanites,"],["até","until"],["Sarepta;","Zarephath;"],["e","and"],["os","the"],["cativos","captives"],["de","of"],["Jerusalém,","Jerusalem,"],["que","that"],["estão","they-are"],["em","in"],["Sefarade,","Sepharad,"],["possuirão","they-will-possess"],["as","the"],["cidades","cities"],["do","of-the"],["sul.","south."]]},
  {num:21,words:[["E","And"],["levantar-se-ão","saviours"],["salvadores","saver"],["no","in-the"],["monte","mountain"],["Sião,","Zion,"],["para","for"],["julgarem","they-will-judge"],["a","to"],["montanha","mountain"],["de","of"],["Esaú;","Esau;"],["e","and"],["o","the"],["reino","kingdom"],["será","will-be"],["do","of-the"],["Senhor.","Lord."]]}
];
renderVerseSet(v1, 'oba-ch1-verses');
})();
