(function() {
var v1 = [
  {num:1,words:[["Paulo,","Paul,"],["prisioneiro","prisoner"],["de","of"],["Jesus","Jesus"],["Cristo,","Christ,"],["e","and"],["o","the"],["irmão","brother"],["Timóteo,","Timotheus,"],["ao","to-the"],["amado","beloved"],["Filemom,","Philemon,"],["nosso","our"],["cooperador,","fellowlabourer,"]]},
  {num:2,words:[["E","And"],["à","to-the"],["amada","doves'"],["Áfia,","Apphia,"],["e","and"],["a","to"],["Arquipo,","Archippus,"],["nosso","our"],["companheiro","companion"],["de","of"],["lutas,","you-contend,"],["e","and"],["à","to-the"],["igreja","church"],["que","that"],["está","is"],["em","in"],["tua","your"],["casa:","house:"]]},
  {num:3,words:[["Graça","Grace"],["a","to"],["vós","you"],["e","and"],["paz","peace"],["da","of-the"],["parte","part"],["de","of"],["Deus","God"],["nosso","our"],["Pai,","Father,"],["e","and"],["do","of-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:4,words:[["Graças","Thanks"],["dou","I-give"],["ao","to-the"],["meu","my"],["Deus,","God,"],["lembrando-me","I-caution-me"],["sempre","always"],["de","of"],["ti","you"],["nas","in-the"],["minhas","my"],["orações;","prayers;"]]},
  {num:5,words:[["Ouvindo","Heard"],["da","of-the"],["tua","your"],["caridade","charity"],["e","and"],["da","of-the"],["fé","faith"],["que","that"],["tens","you-have"],["para","for"],["com","with"],["o","the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["e","and"],["para","for"],["com","with"],["todos","all"],["os","the"],["santos;","Seneca;"]]},
  {num:6,words:[["Para que","that"],["a","to"],["comunhão","communion"],["da","of-the"],["tua","your"],["fé","faith"],["seja","is"],["eficaz","effectual"],["no","in-the"],["conhecimento","knowledge"],["de todo","wholly"],["o","the"],["bem","good"],["que","that"],["em","in"],["vós","you"],["há","has"],["por","by"],["Cristo","Christ"],["Jesus.","Jesus."]]},
  {num:7,words:[["Porque","Because"],["tive","I-had"],["grande","great"],["alegria","joy"],["e","and"],["consolação","consolation"],["na","in-the"],["tua","your"],["caridade,","charity,"],["porque","because"],["por","by"],["ti,","you,"],["ó","O"],["irmão,","brother,"],["o","the"],["coração","heart"],["dos","of-the"],["santos","Seneca"],["foi","was"],["reanimado.","joyed."]]},
  {num:8,words:[["Pelo","By-the"],["que,","that,"],["ainda que","although"],["tenha","has"],["em","in"],["Cristo","Christ"],["grande","great"],["confiança","confidence"],["para","for"],["te","you"],["mandar","command"],["fazer","make"],["o","the"],["que","that"],["convém,","expedient,"]]},
  {num:9,words:[["Todavia","Nevertheless"],["peço-te","I-ask-you"],["antes","before"],["por","by"],["caridade,","charity,"],["sendo","being"],["eu","I"],["tal","same"],["como","as"],["sou,","I-am,"],["Paulo,","Paul,"],["o","the"],["velho,","ancient,"],["e","and"],["também","also"],["agora","now"],["prisioneiro","prisoner"],["de","of"],["Jesus","Jesus"],["Cristo.","Christ."]]},
  {num:10,words:[["Peço-te","I-ask-you"],["por","by"],["meu","my"],["filho","son"],["Onésimo,","Onesimus,"],["que","that"],["gerei","I-begot"],["nas","in-the"],["minhas","my"],["prisões;","prison;"]]},
  {num:11,words:[["O","The"],["qual","which"],["dantes","of-ahead"],["te","you"],["era","was"],["inútil,","needless,"],["mas","but"],["agora","now"],["a","to"],["ti","you"],["e","and"],["a","to"],["mim,","me,"],["muito","much"],["útil;","profitable;"],["eu","I"],["to","to-you-it"],["tornei","I-became"],["a","to"],["enviar;","send;"]]},
  {num:12,words:[["E","And"],["tu,","you,"],["recebe-o,","receiveth-the,"],["ele","he"],["que","that"],["é","is"],["o","the"],["meu","my"],["próprio","own"],["coração.","heart."]]},
  {num:13,words:[["Eu","I"],["bem","good"],["o","the"],["quisera","willed"],["reter","restrain"],["comigo,","with-me,"],["para que","that"],["por","by"],["ti","you"],["me","me"],["servisse","served"],["nas","in-the"],["prisões","prison"],["do","of-the"],["evangelho;","gospel;"]]},
  {num:14,words:[["Porém","But"],["nada","nothing"],["quis","willed"],["fazer","make"],["sem","without"],["o","the"],["teu","your"],["parecer,","seem,"],["para que","that"],["o","the"],["teu","your"],["benefício","benefit"],["não","no"],["fosse","was"],["como","as"],["por","by"],["força,","strength,"],["mas","but"],["voluntário.","voluntary."]]},
  {num:15,words:[["Porque","Because"],["bem","good"],["pode","can"],["ser que","except"],["ele","he"],["se","if"],["tenha","has"],["por isso","therefore"],["apartado","alienated"],["de","of"],["ti","you"],["por","by"],["algum","any"],["tempo,","time,"],["para que","that"],["o","the"],["retivesses","you-restrained"],["para sempre,","for-ever"]]},
  {num:16,words:[["Não","No"],["já","already"],["como","as"],["servo,","servant,"],["antes,","before,"],["mais","still"],["do","of-the"],["que","that"],["servo,","servant,"],["como","as"],["irmão","brother"],["amado,","beloved,"],["particularmente","particularly"],["para","for"],["mim;","me;"],["e","and"],["quanto","as"],["mais","still"],["para","for"],["ti,","you,"],["assim","thus"],["na","in-the"],["carne","flesh"],["como","as"],["no","in-the"],["Senhor?","Lord?"]]},
  {num:17,words:[["Assim,","Thus,"],["pois,","for,"],["se","if"],["me","me"],["tens","you-have"],["por","by"],["companheiro,","companion,"],["recebe-o","receiveth-the"],["como","as"],["a","to"],["mim","me"],["mesmo.","even."]]},
  {num:18,words:[["E","And"],["se","if"],["te","you"],["fez","made"],["algum","any"],["dano,","damage,"],["ou","or"],["te","you"],["deve","debit"],["alguma","any"],["coisa,","thing,"],["põe-no","oweth"],["na","in-the"],["minha","my"],["conta.","account."]]},
  {num:19,words:[["Eu,","I,"],["Paulo,","Paul,"],["de","of"],["minha","my"],["própria","own"],["mão","hand"],["o","the"],["escrevi:","I-wrote:"],["Eu","I"],["o","the"],["pagarei;","I-will-pay;"],["para","for"],["não","no"],["te","you"],["dizer","say"],["que","that"],["tu","you"],["me","me"],["deves","you-duty"],["até","until"],["a","to"],["ti","you"],["mesmo.","even."]]},
  {num:20,words:[["Sim,","Yea,"],["irmão,","brother,"],["eu","I"],["me","me"],["regozijarei","mete"],["de","of"],["ti","you"],["no","in-the"],["Senhor;","Lord;"],["reanima","refresh"],["o","the"],["meu","my"],["coração","heart"],["no","in-the"],["Senhor.","Lord."]]},
  {num:21,words:[["Escrevi-te","I-wrote-you"],["confiado","I-should-confide"],["na","in-the"],["tua","your"],["obediência,","obedience,"],["sabendo","knowing"],["que","that"],["ainda","yet"],["farás","you-will-make"],["mais","still"],["do","of-the"],["que","that"],["digo.","I-say."]]},
  {num:22,words:[["E","And"],["ao","to-the"],["mesmo","even"],["tempo","time"],["prepara-me","sup"],["também","also"],["pousada,","lodging,"],["porque","because"],["espero","trust"],["que","that"],["pelas","by-the"],["vossas","your"],["orações","prayers"],["vos","you"],["hei","I-have"],["de","of"],["ser","be"],["concedido.","granted."]]},
  {num:23,words:[["Saúdam-te","They-greet-you"],["Epafras,","Epaphras,"],["meu","my"],["companheiro","companion"],["de","of"],["prisão","prison"],["por","by"],["Cristo","Christ"],["Jesus,","Jesus,"]]},
  {num:24,words:[["Marcos,","Marcus,"],["Aristarco,","Aristarchus,"],["Demas","Demas"],["e","and"],["Lucas,","Marcus,"],["meus","my"],["cooperadores.","fellowlabourers."]]},
  {num:25,words:[["A","To"],["graça","grace"],["de","of"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo","Christ"],["seja","is"],["com","with"],["o","the"],["vosso","your"],["espírito.","spirit."],["Amém.","Amen."]]}
];
renderVerseSet(v1, 'phm-ch1-verses');
})();
