(function() {
var v1 = [
  {num:1,words:[["Cântico","Song"],["dos","of-the"],["cânticos,","songs,"],["que","that"],["é","is"],["de","of"],["Salomão.","Solomon."]]},
  {num:2,words:[["Beije-me","I-squabble"],["ele","he"],["com","with"],["os","the"],["beijos","kiss"],["da","of-the"],["sua","his"],["boca;","mouth;"],["porque","because"],["melhor","better"],["é","is"],["o","the"],["teu","your"],["amor","love"],["do","of-the"],["que","that"],["o","the"],["vinho.","wine."]]},
  {num:3,words:[["Suave","Sweet"],["é","is"],["o","the"],["aroma","aroma"],["dos","of-the"],["teus","your"],["unguentos,","ointments,"],["como","as"],["o","the"],["unguento","ointment"],["derramado","shed"],["o","the"],["teu","your"],["nome","name"],["é;","is;"],["por isso","therefore"],["as","the"],["virgens","virgins"],["te","you"],["amam.","love."]]},
  {num:4,words:[["Leva-me","Leadeth-me"],["tu,","you,"],["correremos","we-will-flow"],["após","after"],["ti.","you."],["O","The"],["rei","king"],["me","me"],["introduziu","arioch"],["nas","in-the"],["suas","his"],["recâmaras;","parlours;"],["em","in"],["ti","you"],["nos","us"],["regozijaremos","waited"],["e","and"],["nos","us"],["alegraremos;","we-will-gladden;"],["do","of-the"],["teu","your"],["amor","love"],["nos","us"],["lembraremos,","we-will-caution,"],["mais","still"],["do","of-the"],["que","that"],["do","of-the"],["vinho;","wine;"],["com","with"],["razão","account"],["te","you"],["amam.","love."]]},
  {num:5,words:[["Morena","Brown"],["sou,","I-am,"],["porém","but"],["formosa,","fair,"],["ó","O"],["filhas","daughters"],["de","of"],["Jerusalém,","Jerusalem,"],["como","as"],["as","the"],["tendas","tents"],["de","of"],["Quedar,","Kedar,"],["como","as"],["as","the"],["cortinas","curtains"],["de","of"],["Salomão.","Solomon."]]},
  {num:6,words:[["Não","No"],["olheis","you-glance"],["para","for"],["o","the"],["eu","I"],["ser","be"],["morena,","brown,"],["porque","because"],["o","the"],["sol","sun"],["resplandeceu","shined"],["sobre","upon"],["mim;","me;"],["os","the"],["filhos","children"],["de","of"],["minha","my"],["mãe","mother"],["se","if"],["indignaram","bigthan"],["contra","against"],["mim,","me,"],["puseram-me","they-placed-me"],["por","by"],["guarda","guard"],["de","of"],["vinhas;","vineyards;"],["a","to"],["minha","my"],["vinha,","came,"],["que","that"],["me","me"],["pertence,","belongeth,"],["não","no"],["guardei.","I-kept."]]},
  {num:7,words:[["Dize-me,","Say-me,"],["ó","O"],["tu,","you,"],["a","to"],["quem","who"],["a","to"],["minha","my"],["alma","soul"],["ama:","loveth:"],["Onde","Where"],["apascentas","you-feed"],["o","the"],["teu","your"],["rebanho,","flock,"],["onde","where"],["o","the"],["recolhes","you-clauda"],["pelo","by-the"],["meio-dia,","midday,"],["pois","for"],["por","by"],["que","that"],["razão","account"],["seria","should-be"],["eu","I"],["como","as"],["a","to"],["que","that"],["anda","walketh"],["errante","erratic"],["ao","to-the"],["pé","foot"],["dos","of-the"],["rebanhos","flocks"],["de","of"],["teus","your"],["companheiros?","companion?"]]},
  {num:8,words:[["Se","If"],["tu","you"],["não","no"],["o","the"],["sabes,","you-know,"],["ó","O"],["mais","still"],["formosa","fair"],["entre","between"],["as","the"],["mulheres,","women,"],["vai-te","to-ir-se"],["pelas","by-the"],["pisadas","shepherds'"],["das","of-the"],["ovelhas,","sheep,"],["e","and"],["apascenta","feedeth"],["as","the"],["tuas","your"],["cabras","goat"],["junto","adjacent"],["às","to-the"],["moradas","dwellings"],["dos","of-the"],["pastores.","shepherds."]]},
  {num:9,words:[["Às","To-the"],["éguas","ahasuerus'"],["dos","of-the"],["carros","chariots"],["de","of"],["Faraó","Pharaoh"],["te","you"],["comparo,","I-compared,"],["ó","O"],["amada","doves'"],["minha.","my."]]},
  {num:10,words:[["Formosas","Beautiful"],["são","they-are"],["as","the"],["tuas","your"],["faces","cheeks"],["entre","between"],["os","the"],["teus","your"],["enfeites,","ornaments,"],["o","the"],["teu","your"],["pescoço,","neck,"],["com","with"],["os","the"],["colares.","you-will-glue."]]},
  {num:11,words:[["Enfeites","Ornaments"],["de","of"],["ouro","gold"],["te","you"],["faremos,","we-will-make,"],["com","with"],["incrustações","studs"],["de","of"],["prata.","silver."]]},
  {num:12,words:[["Enquanto","While"],["o","the"],["rei","king"],["está","is"],["assentado","sat"],["à","to-the"],["sua","his"],["mesa,","table,"],["o","the"],["meu","my"],["nardo","spikenard"],["exala","spikenard"],["o","the"],["seu","his"],["perfume.","perfume."]]},
  {num:13,words:[["O","The"],["meu","my"],["amado","beloved"],["é","is"],["para","for"],["mim","me"],["um","a"],["ramalhete","bouquet"],["de","of"],["mirra,","myrrh,"],["passará","overflow"],["a","to"],["noite","night"],["entre","between"],["os","the"],["meus","my"],["seios.","breasts."]]},
  {num:14,words:[["Um","A"],["ramalhete","bouquet"],["de","of"],["hena","Hena"],["nas","in-the"],["vinhas","vineyards"],["de","of"],["En-Gedi","En-Gedi"],["é","is"],["para","for"],["mim","me"],["o","the"],["meu","my"],["amado.","beloved."]]},
  {num:15,words:[["Eis que","behold"],["és","you-are"],["formosa,","fair,"],["ó","O"],["amada","doves'"],["minha,","my,"],["eis que","behold"],["és","you-are"],["formosa;","fair;"],["os","the"],["teus","your"],["olhos","eyes"],["são","they-are"],["como","as"],["os","the"],["das","of-the"],["pombas.","doves."]]},
  {num:16,words:[["Eis que","behold"],["és","you-are"],["formoso","beautiful"],["e","and"],["amável,","affable,"],["ó","O"],["amado","beloved"],["meu;","my;"],["o","the"],["nosso","our"],["leito","bed"],["é","is"],["viçoso.","shooteth."]]},
  {num:17,words:[["As","The"],["traves","you-bar"],["da","of-the"],["nossa","our"],["casa","house"],["são","they-are"],["de","of"],["cedro,","cedar,"],["as","the"],["nossas","our"],["varandas,","rafters,"],["de","of"],["cipreste.","cypres."]]}
];
var v2 = [
  {num:1,words:[["Eu","I"],["sou","I-am"],["a","to"],["rosa","rose"],["de","of"],["Sarom,","Sharon,"],["o","the"],["lírio","lily"],["dos","of-the"],["vales.","valleys."]]},
  {num:2,words:[["Qual","Which"],["o","the"],["lírio","lily"],["entre","between"],["os","the"],["espinhos,","thorns,"],["tal","same"],["é","is"],["a","to"],["minha","my"],["amada","doves'"],["entre","between"],["as","the"],["filhas.","daughters."]]},
  {num:3,words:[["Qual","Which"],["a","to"],["macieira","apple-tree"],["entre","between"],["as","the"],["árvores","trees"],["do","of-the"],["bosque,","forest,"],["tal","same"],["é","is"],["o","the"],["meu","my"],["amado","beloved"],["entre","between"],["os","the"],["filhos;","children;"],["desejo","desire"],["muito","much"],["a","to"],["sua","his"],["sombra,","shadow,"],["e","and"],["debaixo","under"],["dela","of-it"],["me","me"],["assento,","seat,"],["e","and"],["o","the"],["seu","his"],["fruto","fruit"],["é","is"],["doce","sweet"],["ao","to-the"],["meu","my"],["paladar.","taste."]]},
  {num:4,words:[["Levou-me","Carried-me"],["à","to-the"],["sala","living-room"],["do","of-the"],["banquete,","banquet,"],["e","and"],["o","the"],["seu","his"],["estandarte","standard"],["sobre","upon"],["mim","me"],["era","was"],["o","the"],["amor.","love."]]},
  {num:5,words:[["Sustentai-me","Laziness-me"],["com","with"],["passas,","you-fare,"],["confortai-me","comfort-me"],["com","with"],["maçãs,","apple,"],["porque","because"],["desfaleço","I-faint"],["de","of"],["amor.","love."]]},
  {num:6,words:[["A","To"],["sua","his"],["mão","hand"],["esquerda","left"],["esteja","is"],["debaixo","under"],["da","of-the"],["minha","my"],["cabeça,","head,"],["e","and"],["a","to"],["sua","his"],["mão","hand"],["direita","right"],["me","me"],["abrace.","embraces."]]},
  {num:7,words:[["Conjuro-vos,","I-conspire-you,"],["ó","O"],["filhas","daughters"],["de","of"],["Jerusalém,","Jerusalem,"],["pelas","by-the"],["corças","doe"],["e","and"],["cervas","deer"],["do","of-the"],["campo,","field,"],["que","that"],["não","no"],["acordeis","you-accord"],["nem","nor"],["desperteis","you-awaken"],["o","the"],["meu","my"],["amor,","love,"],["até que","until"],["ele","he"],["o","the"],["queira.","will."]]},
  {num:8,words:[["Esta","This"],["é","is"],["a","to"],["voz","voice"],["do","of-the"],["meu","my"],["amado!","beloved!"],["Ei-lo","Behold-the"],["aí,","there,"],["que","that"],["já","already"],["vem","comes"],["saltando","leaping"],["sobre","upon"],["os","the"],["montes,","mountains,"],["pulando","I-jump"],["sobre","upon"],["os","the"],["outeiros.","hills."]]},
  {num:9,words:[["O","The"],["meu","my"],["amado","beloved"],["é","is"],["semelhante","like"],["ao","to-the"],["corço,","roe,"],["ou","or"],["ao","to-the"],["filhote","roe"],["do","of-the"],["cervo;","deer;"],["eis que","behold"],["está","is"],["detrás","behind"],["da","of-the"],["nossa","our"],["parede,","wall,"],["olhando","I-glance"],["pelas","by-the"],["janelas,","windows,"],["espreitando","lattice"],["pelas","by-the"],["grades.","lattice."]]},
  {num:10,words:[["O","The"],["meu","my"],["amado","beloved"],["responde","answereth"],["e","and"],["me","me"],["diz:","says:"],["Levanta-te,","Arise,"],["amada","doves'"],["minha,","my,"],["formosa","fair"],["minha,","my,"],["e","and"],["vem.","comes."]]},
  {num:11,words:[["Porque","Because"],["eis que","behold"],["passou","passed"],["o","the"],["inverno;","winter;"],["a","to"],["chuva","rain"],["cessou,","ceased,"],["e","and"],["se","if"],["foi;","was;"]]},
  {num:12,words:[["As","The"],["flores","flowers"],["se","if"],["mostram","they-show"],["na","in-the"],["terra,","land,"],["o","the"],["tempo","time"],["de","of"],["cantar","sing"],["chega,","reacheth,"],["e","and"],["a","to"],["voz","voice"],["da","of-the"],["pombinha","dove"],["se","if"],["ouve","heareth"],["em","in"],["nossa","our"],["terra;","land;"]]},
  {num:13,words:[["A","To"],["figueira","fig"],["brotou","budded"],["os","the"],["seus","his"],["figuinhos,","grape,"],["e","and"],["as","the"],["vides","vines"],["em","in"],["flor","flour"],["exalam","mandrakes"],["o","the"],["seu","his"],["perfume;","perfume;"],["levanta-te,","arise,"],["amada","doves'"],["minha,","my,"],["formosa","fair"],["minha,","my,"],["e","and"],["vem.","comes."]]},
  {num:14,words:[["Pomba","Dove"],["minha,","my,"],["que","that"],["andas","you-walk"],["pelas","by-the"],["fendas","you-split"],["das","of-the"],["penhas,","rock,"],["no","in-the"],["oculto","occult"],["das","of-the"],["ladeiras,","acclivity,"],["mostra-me","seer's"],["a","to"],["tua","your"],["face,","face,"],["faze-me","savoury"],["ouvir","hear"],["a","to"],["tua","your"],["voz,","voice,"],["porque","because"],["a","to"],["tua","your"],["voz","voice"],["é","is"],["doce,","sweet,"],["e","and"],["a","to"],["tua","your"],["face,","face,"],["formosa.","fair."]]},
  {num:15,words:[["Apanhai-nos","Catch-us"],["as","the"],["raposas,","foxes,"],["as","the"],["raposinhas,","little-grate,"],["que","that"],["fazem","they-make"],["mal","evil"],["às","to-the"],["vinhas,","vineyards,"],["porque","because"],["as","the"],["nossas","our"],["vinhas","vineyards"],["estão","they-are"],["em","in"],["flor.","flour."]]},
  {num:16,words:[["O","The"],["meu","my"],["amado","beloved"],["é","is"],["meu,","my,"],["e","and"],["eu","I"],["sou","I-am"],["dele;","of-him;"],["ele","he"],["apascenta","feedeth"],["o","the"],["seu","his"],["rebanho","flock"],["entre","between"],["os","the"],["lírios.","lilies."]]},
  {num:17,words:[["Antes que","before"],["rompa","breaks"],["o","the"],["dia,","day,"],["e","and"],["fujam","shadows"],["as","the"],["sombras,","shadows,"],["volta,","bend,"],["amado","beloved"],["meu;","my;"],["faze-te","become"],["semelhante","like"],["ao","to-the"],["corço","roe"],["ou","or"],["ao","to-the"],["filhote","roe"],["do","of-the"],["cervo","deer"],["sobre","upon"],["os","the"],["montes","mountains"],["de","of"],["Beter.","Bether."]]}
];
var v3 = [
  {num:1,words:[["De","Of"],["noite","night"],["busquei","I-sought"],["em","in"],["minha","my"],["cama","bed"],["a","to"],["quem","who"],["ama","loveth"],["a","to"],["minha","my"],["alma;","soul;"],["busquei-o,","I-sought-the,"],["e","and"],["não","no"],["o","the"],["achei.","I-found."]]},
  {num:2,words:[["Levantar-me-ei,","Nephew,"],["pois,","for,"],["e","and"],["rodearei","I-will-harnessed"],["a","to"],["cidade;","city;"],["pelas","by-the"],["ruas","streets"],["e","and"],["pelas","by-the"],["praças","markets"],["buscarei","I-will-seek"],["a","to"],["quem","who"],["ama","loveth"],["a","to"],["minha","my"],["alma;","soul;"],["busquei-o,","I-sought-the,"],["e","and"],["não","no"],["o","the"],["achei.","I-found."]]},
  {num:3,words:[["Acharam-me","Found-me"],["os","the"],["guardas,","guards,"],["que","that"],["rondavam","to-rondar"],["pela","by-the"],["cidade;","city;"],["eu","I"],["lhes","to-them"],["perguntei:","I-asketh:"],["Vistes","You-saw"],["a","to"],["quem","who"],["ama","loveth"],["a","to"],["minha","my"],["alma?","soul?"]]},
  {num:4,words:[["Apartando-me","I-divide-me"],["eu","I"],["um","a"],["pouco","few"],["deles,","of-them,"],["logo","therefore"],["achei","I-found"],["a","to"],["quem","who"],["ama","loveth"],["a","to"],["minha","my"],["alma;","soul;"],["agarrei-me","to-agarrar-se"],["a","to"],["ele,","he,"],["e","and"],["não","no"],["o","the"],["larguei,","I-allowed,"],["até que","until"],["o","the"],["introduzi","I-entered"],["em","in"],["casa","house"],["de","of"],["minha","my"],["mãe,","mother,"],["na","in-the"],["câmara","chamber"],["daquela","of-that"],["que","that"],["me","me"],["gerou.","begat."]]},
  {num:5,words:[["Conjuro-vos,","I-conspire-you,"],["ó","O"],["filhas","daughters"],["de","of"],["Jerusalém,","Jerusalem,"],["pelas","by-the"],["corças","doe"],["e","and"],["cervas","deer"],["do","of-the"],["campo,","field,"],["que","that"],["não","no"],["acordeis,","you-accord,"],["nem","nor"],["desperteis","you-awaken"],["o","the"],["meu","my"],["amor,","love,"],["até que","until"],["ele","he"],["o","the"],["queira.","will."]]},
  {num:6,words:[["Quem","Who"],["é","is"],["esta","this"],["que","that"],["sobe","climbs"],["do","of-the"],["deserto,","desert,"],["como","as"],["colunas","pillars"],["de","of"],["fumaça,","smoke,"],["perfumada","perfume"],["de","of"],["mirra,","myrrh,"],["de","of"],["incenso,","incense,"],["e","and"],["de","of"],["toda","every"],["a","to"],["sorte","lot"],["de","of"],["pós","dust"],["aromáticos","anointing"],["do","of-the"],["mercador?","trader?"]]},
  {num:7,words:[["Eis que","behold"],["é","is"],["a","to"],["liteira","solomon's"],["de","of"],["Salomão;","Solomon;"],["sessenta","sixty"],["valentes","brave"],["estão","they-are"],["ao redor","round-about"],["dela,","of-it,"],["dos","of-the"],["valentes","brave"],["de","of"],["Israel.","Israel."]]},
  {num:8,words:[["Todos","All"],["armados","armed"],["de","of"],["espadas,","swords,"],["destros","warriors"],["na","in-the"],["guerra,","war,"],["cada","every"],["um","a"],["com","with"],["a","to"],["sua","his"],["espada","sword"],["à","to-the"],["coxa","thigh"],["por","by"],["causa","sake"],["dos","of-the"],["temores","fears"],["noturnos.","nocturnal."]]},
  {num:9,words:[["O","The"],["rei","king"],["Salomão","Solomon"],["fez","made"],["para","for"],["si","himself"],["um","a"],["liteira","solomon's"],["de","of"],["madeira","wood"],["do","of-the"],["Líbano.","Lebanon."]]},
  {num:10,words:[["Fez-lhe","Made-to-him"],["as","the"],["colunas","pillars"],["de","of"],["prata,","silver,"],["o","the"],["estrado","platform"],["de","of"],["ouro,","gold,"],["o","the"],["assento","seat"],["de","of"],["púrpura,","purple,"],["o","the"],["interior","inner"],["coberto","covered"],["com","with"],["o","the"],["amor","love"],["pelas","by-the"],["filhas","daughters"],["de","of"],["Jerusalém.","Jerusalem."]]},
  {num:11,words:[["Saí,","I-exited,"],["ó","O"],["filhas","daughters"],["de","of"],["Sião,","Zion,"],["e","and"],["contemplai","contemplate"],["o","the"],["rei","king"],["Salomão","Solomon"],["com","with"],["a","to"],["coroa","crown"],["com","with"],["que","that"],["o","the"],["coroou","crowned"],["sua","his"],["mãe","mother"],["no","in-the"],["dia","day"],["do","of-the"],["seu","his"],["casamento","marriage"],["e","and"],["no","in-the"],["dia","day"],["do","of-the"],["júbilo","shouting"],["do","of-the"],["seu","his"],["coração.","heart."]]}
];
var v4 = [
  {num:1,words:[["Eis que","behold"],["és","you-are"],["formosa,","fair,"],["amada","doves'"],["minha,","my,"],["eis que","behold"],["és","you-are"],["formosa;","fair;"],["os","the"],["teus","your"],["olhos","eyes"],["são","they-are"],["como","as"],["os","the"],["das","of-the"],["pombas","doves"],["por","by"],["detrás","behind"],["do","of-the"],["teu","your"],["véu;","veil;"],["o","the"],["teu","your"],["cabelo","hair"],["é","is"],["como","as"],["o","the"],["rebanho","flock"],["de","of"],["cabras","goat"],["que","that"],["pastam","they-graze"],["no","in-the"],["monte","mountain"],["de","of"],["Gileade.","Gilead."]]},
  {num:2,words:[["Os","The"],["teus","your"],["dentes","teeth"],["são","they-are"],["como","as"],["o","the"],["rebanho","flock"],["das","of-the"],["ovelhas","sheep"],["tosquiadas,","clip,"],["que","that"],["sobem","twins"],["do","of-the"],["lavadouro,","lavadouro,"],["e","and"],["todas","things"],["elas","they"],["produzem","twins"],["gêmeos,","twins,"],["e","and"],["nenhuma","neither"],["há","has"],["estéril","barren"],["entre","between"],["elas.","they."]]},
  {num:3,words:[["Os","The"],["teus","your"],["lábios","lips"],["são","they-are"],["como","as"],["um","a"],["fio","thread"],["de","of"],["escarlata,","pearls,"],["e","and"],["o","the"],["teu","your"],["falar","speak"],["é","is"],["doce;","sweet;"],["a","to"],["fonte","fountain"],["da","of-the"],["tua","your"],["cabeça","head"],["é","is"],["como","as"],["um","a"],["pedaço","piece"],["de","of"],["romã","romã"],["por","by"],["detrás","behind"],["do","of-the"],["teu","your"],["véu.","veil."]]},
  {num:4,words:[["O","The"],["teu","your"],["pescoço","neck"],["é","is"],["como","as"],["a","to"],["torre","tower"],["de","of"],["Davi,","David,"],["edificada","build"],["para","for"],["pendurar","hook"],["armas;","weapons;"],["mil","thousand"],["escudos","shields"],["pendem","they-droop"],["dela,","of-it,"],["todos","all"],["broquéis","bucklers"],["de","of"],["valorosos.","valour."]]},
  {num:5,words:[["Os","The"],["teus","your"],["dois","two"],["seios","breasts"],["são","they-are"],["como","as"],["dois","two"],["filhotes","whelps"],["gêmeos","twins"],["da","of-the"],["corça,","doe,"],["que","that"],["se","if"],["apascentam","landmarks"],["entre","between"],["os","the"],["lírios.","lilies."]]},
  {num:6,words:[["Antes que","before"],["rompa","breaks"],["o","the"],["dia,","day,"],["e","and"],["fujam","shadows"],["as","the"],["sombras,","shadows,"],["irei","I-will-go"],["ao","to-the"],["monte","mountain"],["da","of-the"],["mirra","myrrh"],["e","and"],["ao","to-the"],["outeiro","hill"],["do","of-the"],["incenso.","incense."]]},
  {num:7,words:[["Tu","You"],["és","you-are"],["toda","every"],["formosa,","fair,"],["amada","doves'"],["minha,","my,"],["e","and"],["em","in"],["ti","you"],["não","no"],["há","has"],["mancha.","spot."]]},
  {num:8,words:[["Vem","Comes"],["comigo","with-me"],["do","of-the"],["Líbano,","Lebanon,"],["ó","O"],["esposa,","wife,"],["comigo","with-me"],["do","of-the"],["Líbano","Lebanon"],["vem;","comes;"],["olha","look"],["desde o","beginning"],["cume","top"],["de","of"],["Amana,","Amana,"],["desde o","beginning"],["cume","top"],["de","of"],["Senir","Senir"],["e","and"],["de","of"],["Hermom,","Hermon,"],["desde","since"],["as","the"],["moradas","dwellings"],["dos","of-the"],["leões,","lions,"],["desde","since"],["os","the"],["montes","mountains"],["dos","of-the"],["leopardos.","leopard."]]},
  {num:9,words:[["Arrebataste-me","You-snap up-me"],["o","the"],["coração,","heart,"],["minha","my"],["irmã,","sister,"],["ó","O"],["esposa;","wife;"],["arrebataste-me","you-snap up-me"],["o","the"],["coração","heart"],["com","with"],["um","a"],["dos","of-the"],["teus","your"],["olhos,","eyes,"],["com","with"],["um","a"],["colar","glue"],["do","of-the"],["teu","your"],["pescoço.","neck."]]},
  {num:10,words:[["Que","That"],["belos","beautiful"],["são","they-are"],["os","the"],["teus","your"],["amores,","love,"],["minha","my"],["irmã!","sister!"],["Ó,","O,"],["esposa","wife"],["minha,","my,"],["quão","how"],["melhores","better"],["são","they-are"],["os","the"],["teus","your"],["amores","love"],["do","of-the"],["que","that"],["o","the"],["vinho!","wine!"],["e","and"],["o","the"],["aroma","aroma"],["dos","of-the"],["teus","your"],["unguentos,","ointments,"],["do","of-the"],["que","that"],["o","the"],["de","of"],["todas","things"],["as","the"],["especiarias!","spices!"]]},
  {num:11,words:[["Favos","Honeycomb"],["de","of"],["mel","honey"],["estão","they-are"],["manando","spouse"],["dos","of-the"],["teus","your"],["lábios,","lips,"],["ó","O"],["esposa!","wife!"],["mel","honey"],["e","and"],["leite","milk"],["estão","they-are"],["debaixo","under"],["da","of-the"],["tua","your"],["língua,","tongue,"],["e","and"],["o","the"],["cheiro","smell"],["dos","of-the"],["teus","your"],["vestidos","clothe"],["é","is"],["como","as"],["o","the"],["cheiro","smell"],["do","of-the"],["Líbano.","Lebanon."]]},
  {num:12,words:[["Jardim","Garden"],["fechado","closed"],["és","you-are"],["tu,","you,"],["minha","my"],["irmã,","sister,"],["esposa","wife"],["minha,","my,"],["manancial","fountain"],["fechado,","closed,"],["fonte","fountain"],["selada.","prepay."]]},
  {num:13,words:[["Os","The"],["teus","your"],["renovos","offspring"],["são","they-are"],["um","a"],["pomar","orchard"],["de","of"],["romãs,","pomegranates,"],["com","with"],["frutos","fruit"],["excelentes,","excellent,"],["a","to"],["hena","Hena"],["com","with"],["o","the"],["nardo,","spikenard,"]]},
  {num:14,words:[["O","The"],["nardo,","spikenard,"],["e","and"],["o","the"],["açafrão,","saffron,"],["o","the"],["cálamo,","calamus,"],["e","and"],["a","to"],["canela,","cinnamon,"],["com","with"],["toda","every"],["a","to"],["sorte","lot"],["de","of"],["árvores","trees"],["de","of"],["incenso,","incense,"],["a","to"],["mirra","myrrh"],["e","and"],["aloés,","aloes,"],["com","with"],["todas","things"],["as","the"],["principais","chief"],["especiarias.","spices."]]},
  {num:15,words:[["És","You-are"],["a","to"],["fonte","fountain"],["dos","of-the"],["jardins,","gardens,"],["poço","well"],["das","of-the"],["águas","waters"],["vivas,","alive,"],["que","that"],["correm","they-flow"],["do","of-the"],["Líbano!","Lebanon!"]]},
  {num:16,words:[["Levanta-te,","Arise,"],["vento","wind"],["norte,","north,"],["e","and"],["vem","comes"],["tu,","you,"],["vento","wind"],["sul;","south;"],["assopra","waster"],["no","in-the"],["meu","my"],["jardim,","garden,"],["para que","that"],["destilem","they-distill"],["os","the"],["seus","his"],["aromas.","aroma."],["Ah,","Ah,"],["se","if"],["viesse","came"],["o","the"],["meu","my"],["amado","beloved"],["para","for"],["o","the"],["seu","his"],["jardim,","garden,"],["e","and"],["comesse","pharisee's"],["os","the"],["seus","his"],["frutos","fruit"],["excelentes!","excellent!"]]}
];
var v5 = [
  {num:1,words:[["Já","Already"],["vim","I-came"],["para","for"],["o","the"],["meu","my"],["jardim,","garden,"],["minha","my"],["irmã,","sister,"],["ó","O"],["esposa;","wife;"],["colhi","I-gleaned"],["a","to"],["minha","my"],["mirra","myrrh"],["com","with"],["a","to"],["minha","my"],["especiaria,","dropping,"],["comi","I-ate"],["o","the"],["meu","my"],["favo","honeycomb"],["com","with"],["o","the"],["meu","my"],["mel,","honey,"],["bebi","drunk"],["o","the"],["meu","my"],["vinho","wine"],["com","with"],["o","the"],["meu","my"],["leite;","milk;"],["comei,","eat,"],["amigos,","friends,"],["bebei,","tomorrow,"],["ó","O"],["amados,","beloved,"],["e","and"],["embriagai-vos.","get drunk."]]},
  {num:2,words:[["Eu","I"],["estava","was"],["dormindo,","asleep,"],["mas","but"],["o","the"],["meu","my"],["coração","heart"],["vigiava;","guarded;"],["eis","behold"],["a","to"],["voz","voice"],["do","of-the"],["meu","my"],["amado","beloved"],["que","that"],["estava","was"],["batendo:","I-knocking:"],["Abre-me,","Openeth-me,"],["minha","my"],["irmã,","sister,"],["minha","my"],["amiga,","friend,"],["minha","my"],["pomba,","dove,"],["minha","my"],["perfeita,","perfect,"],["porque","because"],["a","to"],["minha","my"],["cabeça","head"],["está","is"],["cheia","full"],["de","of"],["orvalho,","dew,"],["e","and"],["os","the"],["meus","my"],["cabelos,","hair,"],["das","of-the"],["gotas","drops"],["da","of-the"],["noite.","night."]]},
  {num:3,words:[["Já","Already"],["despi","uncovered"],["os","the"],["meus","my"],["vestidos;","clothe;"],["como","as"],["os","the"],["tornarei","I-will-become"],["a","to"],["vestir?","clothe?"],["Já","Already"],["lavei","I-washed"],["os","the"],["meus","my"],["pés;","feet;"],["como","as"],["os","the"],["tornarei","I-will-become"],["a","to"],["sujar?","coat?"]]},
  {num:4,words:[["O","The"],["meu","my"],["amado","beloved"],["pôs","put"],["a","to"],["sua","his"],["mão","hand"],["pela","by-the"],["fresta","aperture"],["da","of-the"],["porta,","exit,"],["e","and"],["as","the"],["minhas","my"],["entranhas","bowels"],["estremeceram","they-agitated"],["por","by"],["causa","sake"],["dele.","of-him."]]},
  {num:5,words:[["Eu","I"],["me","me"],["levantei","lifted"],["para","for"],["abrir","open"],["ao","to-the"],["meu","my"],["amado,","beloved,"],["e","and"],["as","the"],["minhas","my"],["mãos","hands"],["destilavam","they-distilled"],["mirra,","myrrh,"],["e","and"],["os","the"],["meus","my"],["dedos","fingers"],["gotejavam","handles"],["mirra","myrrh"],["sobre","upon"],["as","the"],["aldravas","handles"],["da","of-the"],["fechadura.","lock."]]},
  {num:6,words:[["Eu","I"],["abri","I-opened"],["ao","to-the"],["meu","my"],["amado,","beloved,"],["mas","but"],["já","already"],["o","the"],["meu","my"],["amado","beloved"],["se","if"],["tinha","had"],["retirado,","retired,"],["e","and"],["se","if"],["tinha","had"],["ido;","iddo;"],["a","to"],["minha","my"],["alma","soul"],["se","if"],["derreteu","melted"],["quando","when"],["ele","he"],["falou;","spake;"],["busquei-o","I-sought-the"],["e","and"],["não","no"],["o","the"],["achei,","I-found,"],["chamei-o,","I-called-the,"],["e","and"],["não","no"],["me","me"],["respondeu.","answered."]]},
  {num:7,words:[["Acharam-me","Found-me"],["os","the"],["guardas","guards"],["que","that"],["rondavam","to-rondar"],["pela","by-the"],["cidade;","city;"],["espancaram-me,","they-fellow-servants-me,"],["feriram-me,","edge-me,"],["tiraram-me","they-deducted-me"],["o","the"],["meu","my"],["véu","veil"],["os","the"],["guardas","guards"],["dos","of-the"],["muros.","walls."]]},
  {num:8,words:[["Conjuro-vos,","I-conspire-you,"],["ó","O"],["filhas","daughters"],["de","of"],["Jerusalém,","Jerusalem,"],["que,","that,"],["se","if"],["achardes","you-will-find"],["o","the"],["meu","my"],["amado,","beloved,"],["lhe","to-him"],["digais","you-say"],["que","that"],["estou","I-am"],["enferma","prevaileth"],["de","of"],["amor.","love."]]},
  {num:9,words:[["Que","That"],["é","is"],["o","the"],["teu","your"],["amado","beloved"],["mais","still"],["do","of-the"],["que","that"],["outro","another"],["amado,","beloved,"],["ó","O"],["tu,","you,"],["a","to"],["mais","still"],["formosa","fair"],["entre","between"],["as","the"],["mulheres?","women?"],["Que","That"],["é","is"],["o","the"],["teu","your"],["amado","beloved"],["mais","still"],["do","of-the"],["que","that"],["outro","another"],["amado,","beloved,"],["que","that"],["tanto","both"],["nos","us"],["conjuraste?","you-conspired?"]]},
  {num:10,words:[["O","The"],["meu","my"],["amado","beloved"],["é","is"],["alvo","aim"],["e","and"],["rubro,","red,"],["o","the"],["mais","still"],["distinto","distinctive"],["entre","between"],["dez","ten"],["mil.","thousand."]]},
  {num:11,words:[["A","To"],["sua","his"],["cabeça","head"],["é","is"],["como","as"],["o","the"],["ouro","gold"],["mais","still"],["apurado,","I-should-refine,"],["os","the"],["seus","his"],["cabelos","hair"],["crespos,","bushy,"],["pretos","black"],["como","as"],["o","the"],["corvo.","raven."]]},
  {num:12,words:[["Os","The"],["seus","his"],["olhos","eyes"],["são","they-are"],["como","as"],["os","the"],["das","of-the"],["pombas","doves"],["junto","adjacent"],["às","to-the"],["correntes","fluent"],["das","of-the"],["águas,","waters,"],["lavados","wash"],["em","in"],["leite,","milk,"],["postos","post"],["em","in"],["engaste.","onyx."]]},
  {num:13,words:[["As","The"],["suas","his"],["faces","cheeks"],["são","they-are"],["como","as"],["um","a"],["canteiro","dropping"],["de","of"],["especiaria,","dropping,"],["como","as"],["caixas","cashier"],["aromáticas;","anointing;"],["os","the"],["seus","his"],["lábios","lips"],["são","they-are"],["como","as"],["lírios","lilies"],["que","that"],["gotejam","distil"],["mirra","myrrh"],["destilante.","dropping."]]},
  {num:14,words:[["As","The"],["suas","his"],["mãos,","hands,"],["como","as"],["anéis","rings"],["de","of"],["ouro","gold"],["que","that"],["têm","they-have"],["engastadas","inclosings"],["as","the"],["turquesas;","beryl;"],["o","the"],["seu","his"],["ventre,","abdomen,"],["como","as"],["alvo","aim"],["marfim,","ivory,"],["coberto","covered"],["de","of"],["safiras.","sapphire."]]},
  {num:15,words:[["As","The"],["suas","his"],["pernas,","legs,"],["como","as"],["colunas","pillars"],["de","of"],["mármore,","marble,"],["fundadas","erect"],["sobre","upon"],["bases","sockets"],["de","of"],["ouro","gold"],["puro;","pure;"],["o","the"],["seu","his"],["aspecto,","appearance,"],["como","as"],["o","the"],["Líbano,","Lebanon,"],["excelente","excellent"],["como","as"],["os","the"],["cedros.","cedars."]]},
  {num:16,words:[["O","The"],["seu","his"],["falar","speak"],["é","is"],["muitíssimo","enormously"],["suave,","sweet,"],["e","and"],["todo","every"],["ele","he"],["totalmente","utterly"],["desejável.","desirable."],["Tal","Same"],["é","is"],["o","the"],["meu","my"],["amado,","beloved,"],["e","and"],["tal","same"],["o","the"],["meu","my"],["amigo,","friend,"],["ó","O"],["filhas","daughters"],["de","of"],["Jerusalém.","Jerusalem."]]}
];
var v6 = [
  {num:1,words:[["Para","For"],["onde","where"],["foi","was"],["o","the"],["teu","your"],["amado,","beloved,"],["ó","O"],["mais","still"],["formosa","fair"],["entre","between"],["as","the"],["mulheres?","women?"],["Que","That"],["rumo","traveled"],["tomou","took"],["o","the"],["teu","your"],["amado,","beloved,"],["para que","that"],["o","the"],["busquemos","we-seek"],["contigo?","with-you?"]]},
  {num:2,words:[["O","The"],["meu","my"],["amado","beloved"],["desceu","descended"],["ao","to-the"],["seu","his"],["jardim,","garden,"],["aos","to-the"],["canteiros","plantation"],["da","of-the"],["especiaria,","dropping,"],["para","for"],["se","if"],["apascentar","feed"],["nos","us"],["jardins","gardens"],["e","and"],["para","for"],["colher","glean"],["os","the"],["lírios.","lilies."]]},
  {num:3,words:[["Eu","I"],["sou","I-am"],["do","of-the"],["meu","my"],["amado,","beloved,"],["e","and"],["o","the"],["meu","my"],["amado","beloved"],["é","is"],["meu;","my;"],["ele","he"],["se","if"],["apascenta","feedeth"],["entre","between"],["os","the"],["lírios.","lilies."]]},
  {num:4,words:[["Formosa","Fair"],["és,","you-are,"],["amada","doves'"],["minha,","my,"],["como","as"],["Tirza,","Tirzah,"],["aprazível","agreeable"],["como","as"],["Jerusalém,","Jerusalem,"],["formidável","wonderfully"],["como","as"],["um","a"],["exército","army"],["com","with"],["bandeiras.","standards."]]},
  {num:5,words:[["Desvia","Vary"],["de","of"],["mim","me"],["os","the"],["teus","your"],["olhos,","eyes,"],["porque","because"],["eles","they"],["me","me"],["perturbam.","they-confuse."],["O","The"],["teu","your"],["cabelo","hair"],["é","is"],["como","as"],["o","the"],["rebanho","flock"],["das","of-the"],["cabras","goat"],["que","that"],["pastam","they-graze"],["em","in"],["Gileade.","Gilead."]]},
  {num:6,words:[["Os","The"],["teus","your"],["dentes","teeth"],["são","they-are"],["como","as"],["o","the"],["rebanho","flock"],["de","of"],["ovelhas","sheep"],["que","that"],["sobem","twins"],["do","of-the"],["lavadouro,","lavadouro,"],["e","and"],["todas","things"],["produzem","twins"],["gêmeos,","twins,"],["e","and"],["não","no"],["há","has"],["estéril","barren"],["entre","between"],["elas.","they."]]},
  {num:7,words:[["Como","As"],["um","a"],["pedaço","piece"],["de","of"],["romã,","romã,"],["assim","thus"],["são","they-are"],["as","the"],["tuas","your"],["faces","cheeks"],["por","by"],["detrás","behind"],["do","of-the"],["teu","your"],["véu.","veil."]]},
  {num:8,words:[["Sessenta","Sixty"],["são","they-are"],["as","the"],["rainhas,","queens,"],["e","and"],["oitenta,","eighty,"],["as","the"],["concubinas,","concubines,"],["e","and"],["as","the"],["virgens,","virgins,"],["sem","without"],["número.","number."]]},
  {num:9,words:[["Porém","But"],["uma","a"],["é","is"],["a","to"],["minha","my"],["pomba,","dove,"],["a","to"],["minha","my"],["perfeita,","perfect,"],["a","to"],["única","alone"],["de","of"],["sua","his"],["mãe,","mother,"],["e","and"],["a","to"],["mais","still"],["querida","dear"],["daquela","of-that"],["que","that"],["a","to"],["deu","gave"],["à","to-the"],["luz;","light;"],["vendo-a,","saw-the,"],["as","the"],["filhas","daughters"],["a","to"],["chamarão","delightsome"],["bem-aventurada,","happy,"],["as","the"],["rainhas","queens"],["e","and"],["as","the"],["concubinas","concubines"],["a","to"],["louvarão.","they-will-acclaim."]]},
  {num:10,words:[["Quem","Who"],["é","is"],["esta","this"],["que","that"],["aparece","appeareth"],["como","as"],["a","to"],["alva","dawning"],["do","of-the"],["dia,","day,"],["formosa","fair"],["como","as"],["a","to"],["lua,","moon,"],["brilhante","banners"],["como","as"],["o","the"],["sol,","sun,"],["terrível","abysmal"],["como","as"],["um","a"],["exército","army"],["com","with"],["bandeiras?","standards?"]]},
  {num:11,words:[["Desci","I-descended"],["ao","to-the"],["jardim","garden"],["das","of-the"],["nogueiras,","walnut-tree,"],["para","for"],["ver","see"],["os","the"],["novos","bottles"],["frutos","fruit"],["do","of-the"],["vale,","valley,"],["para","for"],["ver","see"],["se","if"],["floresciam","nuts"],["as","the"],["vides","vines"],["e","and"],["brotavam","blasted"],["as","the"],["romãzeiras.","nuts."]]},
  {num:12,words:[["Antes","Before"],["de","of"],["eu","I"],["o","the"],["sentir,","regret,"],["me","me"],["pôs","put"],["a","to"],["minha","my"],["alma","soul"],["nos","us"],["carros","chariots"],["do","of-the"],["meu","my"],["nobre","nobleman"],["povo.","people."]]},
  {num:13,words:[["Volta,","Bend,"],["volta,","bend,"],["ó","O"],["sulamita,","shulamite,"],["volta,","bend,"],["volta,","bend,"],["para que","that"],["nós","we"],["te","you"],["vejamos.","we-see."],["Por","By"],["que","that"],["olhas","you-glance"],["para","for"],["a","to"],["sulamita","shulamite"],["como","as"],["para","for"],["as","the"],["fileiras","rows"],["de","of"],["dois","two"],["exércitos?","hosts?"]]}
];
var v7 = [
  {num:1,words:[["Que","That"],["formosos","beautiful"],["são","they-are"],["os","the"],["teus","your"],["pés","feet"],["nos","us"],["sapatos,","shoes,"],["ó","O"],["filha","daughter"],["do","of-the"],["príncipe!","prince!"],["Os","The"],["contornos","contour"],["de","of"],["tuas","your"],["coxas","thighs"],["são","they-are"],["como","as"],["joias,","jewels,"],["segundo","according-to"],["a","to"],["obra","work"],["de","of"],["mãos","hands"],["de","of"],["artífice.","workman."]]},
  {num:2,words:[["O","The"],["teu","your"],["umbigo,","navel,"],["como","as"],["uma","a"],["taça","spoon"],["redonda,","round,"],["a","to"],["que","that"],["não","no"],["falta","lack"],["bebida;","beverage;"],["o","the"],["teu","your"],["ventre,","abdomen,"],["como","as"],["montão","heap"],["de","of"],["trigo,","wheat,"],["sitiado","I-should-besiege"],["de","of"],["lírios.","lilies."]]},
  {num:3,words:[["Os","The"],["teus","your"],["dois","two"],["seios,","breasts,"],["como","as"],["dois","two"],["filhos","children"],["gêmeos","twins"],["da","of-the"],["corça.","doe."]]},
  {num:4,words:[["O","The"],["teu","your"],["pescoço,","neck,"],["como","as"],["a","to"],["torre","tower"],["de","of"],["marfim;","ivory;"],["os","the"],["teus","your"],["olhos,","eyes,"],["como","as"],["os","the"],["viveiros","nursery"],["de","of"],["Hesbom,","Heshbon,"],["junto","adjacent"],["à","to-the"],["porta","exit"],["de","of"],["Bate-Rabim;","Fishpools;"],["o","the"],["teu","your"],["nariz,","nose,"],["como","as"],["torre","tower"],["do","of-the"],["Líbano,","Lebanon,"],["que","that"],["olha","look"],["para","for"],["Damasco.","Damascus."]]},
  {num:5,words:[["A","To"],["tua","your"],["cabeça","head"],["sobre","upon"],["ti","you"],["é","is"],["como","as"],["o","the"],["monte","mountain"],["Carmelo,","Carmel,"],["e","and"],["os","the"],["cabelos","hair"],["da","of-the"],["tua","your"],["cabeça,","head,"],["como","as"],["a","to"],["púrpura;","purple;"],["o","the"],["rei","king"],["está","is"],["preso","prisoner"],["às","to-the"],["tuas","your"],["tranças.","web."]]},
  {num:6,words:[["Quão","How"],["formosa,","fair,"],["e","and"],["quão","how"],["aprazível","agreeable"],["és,","you-are,"],["ó","O"],["amor,","love,"],["em","in"],["delícias!","fun!"]]},
  {num:7,words:[["Esta","This"],["tua","your"],["estatura","stature"],["é","is"],["semelhante","like"],["à","to-the"],["palmeira,","palm,"],["e","and"],["os","the"],["teus","your"],["seios","breasts"],["são","they-are"],["semelhantes","like"],["aos","to-the"],["cachos","clusters"],["de","of"],["uvas.","grapes."]]},
  {num:8,words:[["Dizia","Said"],["eu:","I:"],["Subirei","I-will-climb"],["à","to-the"],["palmeira,","palm,"],["pegarei","I-will-get"],["em","in"],["seus","his"],["ramos;","branches;"],["e","and"],["então","said"],["os","the"],["teus","your"],["seios","breasts"],["serão","they-will-be"],["como","as"],["os","the"],["cachos","clusters"],["na","in-the"],["vide,","vine,"],["e","and"],["o","the"],["aroma","aroma"],["das","of-the"],["tuas","your"],["narinas,","nostrils,"],["como","as"],["o","the"],["das","of-the"],["maçãs.","apple."]]},
  {num:9,words:[["E","And"],["o","the"],["teu","your"],["paladar,","taste,"],["como","as"],["o","the"],["bom","good"],["vinho","wine"],["para","for"],["o","the"],["meu","my"],["amado,","beloved,"],["que","that"],["se","if"],["bebe","drinketh"],["suavemente,","smoothly,"],["e","and"],["faz","makes"],["com","with"],["que","that"],["falem","they-speak"],["os","the"],["lábios","lips"],["dos","of-the"],["que","that"],["dormem.","asleep."]]},
  {num:10,words:[["Eu","I"],["sou","I-am"],["do","of-the"],["meu","my"],["amado,","beloved,"],["e","and"],["ele","he"],["me","me"],["tem","has"],["afeição.","friendship."]]},
  {num:11,words:[["Vem,","Comes,"],["ó","O"],["amado","beloved"],["meu,","my,"],["saiamos","ropes"],["nós","we"],["ao","to-the"],["campo,","field,"],["passemos","we-fare"],["as","the"],["noites","nights"],["nas","in-the"],["aldeias.","villages."]]},
  {num:12,words:[["Levantemo-nos","Loves"],["de","of"],["manhã","morning"],["para","for"],["ir","go"],["às","to-the"],["vinhas,","vineyards,"],["vejamos","we-see"],["se","if"],["florescem","loves"],["as","the"],["vides,","vines,"],["se","if"],["a","to"],["flor","flour"],["se","if"],["abre,","openeth,"],["se","if"],["já","already"],["brotam","bud"],["as","the"],["romãzeiras;","nuts;"],["ali","there"],["te","you"],["darei","I-will-give"],["o","the"],["meu","my"],["grande","great"],["amor.","love."]]},
  {num:13,words:[["As","The"],["mandrágoras","mandrakes"],["exalam","mandrakes"],["o","the"],["seu","his"],["cheiro,","smell,"],["e","and"],["às","to-the"],["nossas","our"],["portas","gates"],["há","has"],["toda","every"],["a","to"],["sorte","lot"],["de","of"],["excelentes","excellent"],["frutos,","fruit,"],["novos","bottles"],["e","and"],["velhos;","ancient;"],["ó","O"],["amado","beloved"],["meu,","my,"],["eu","I"],["os","the"],["guardei","I-kept"],["para","for"],["ti.","you."]]}
];
var v8 = [
  {num:1,words:[["Ah!","Ah!"],["Quem","Who"],["me","me"],["dera","gave"],["que","that"],["me","me"],["foras","you-were"],["como","as"],["irmão,","brother,"],["que","that"],["mamou","sucked"],["nos","us"],["peitos","breasts"],["de","of"],["minha","my"],["mãe!","mother!"],["Quando","When"],["te","you"],["achasse","found"],["na","in-the"],["rua,","street,"],["te","you"],["beijaria,","should-kiss,"],["e","and"],["não","no"],["me","me"],["desprezariam!","they-should-mammon!"]]},
  {num:2,words:[["Te","You"],["levaria","should-carry"],["e","and"],["introduziria","should-enter"],["na","in-the"],["casa","house"],["de","of"],["minha","my"],["mãe,","mother,"],["e","and"],["tu","you"],["me","me"],["ensinarias;","you-should-teach;"],["e","and"],["te","you"],["daria","should-give"],["de","of"],["beber","drink"],["vinho","wine"],["aromático","anointing"],["e","and"],["do","of-the"],["mosto","corn"],["das","of-the"],["minhas","my"],["romãs.","pomegranates."]]},
  {num:3,words:[["A","To"],["sua","his"],["mão","hand"],["esquerda","left"],["esteja","is"],["debaixo","under"],["da","of-the"],["minha","my"],["cabeça,","head,"],["e","and"],["a","to"],["sua","his"],["direita","right"],["me","me"],["abrace.","embraces."]]},
  {num:4,words:[["Conjuro-vos,","I-conspire-you,"],["ó","O"],["filhas","daughters"],["de","of"],["Jerusalém,","Jerusalem,"],["que","that"],["não","no"],["acordeis","you-accord"],["nem","nor"],["desperteis","you-awaken"],["o","the"],["meu","my"],["amor,","love,"],["até que","until"],["ele","he"],["o","the"],["queira.","will."]]},
  {num:5,words:[["Quem","Who"],["é","is"],["esta","this"],["que","that"],["sobe","climbs"],["do","of-the"],["deserto,","desert,"],["e","and"],["vem","comes"],["encostada","lean"],["ao","to-the"],["seu","his"],["amado?","beloved?"],["Debaixo de","under"],["uma","a"],["macieira","apple-tree"],["te","you"],["despertei,","leaning,"],["ali","there"],["te","you"],["gerou","begat"],["tua","your"],["mãe","mother"],["com","with"],["dores;","sorrows;"],["ali","there"],["te","you"],["gerou","begat"],["com","with"],["dores","sorrows"],["aquela","that ... over there"],["que","that"],["te","you"],["deu","gave"],["à","to-the"],["luz.","light."]]},
  {num:6,words:[["Põe-me","Places-me"],["como","as"],["selo","seal"],["sobre","upon"],["o","the"],["teu","your"],["coração,","heart,"],["como","as"],["selo","seal"],["sobre","upon"],["o","the"],["teu","your"],["braço,","arm,"],["porque","because"],["o","the"],["amor","love"],["é","is"],["forte","strong"],["como","as"],["a","to"],["morte,","death,"],["e","and"],["duro","hard"],["como","as"],["a","to"],["sepultura,","grave,"],["o","the"],["ciúme;","jealousy;"],["as","the"],["suas","his"],["brasas","coals"],["são","they-are"],["brasas","coals"],["de","of"],["fogo,","fire,"],["labaredas","flame"],["intensas.","wrapt."]]},
  {num:7,words:[["As","The"],["muitas","many"],["águas","waters"],["não","no"],["poderiam","they-should-can"],["apagar","extinguish"],["esse","that ... over there"],["amor,","love,"],["nem","nor"],["os","the"],["rios","rivers"],["afogá-lo;","drown-the;"],["ainda que","although"],["desse","of-that"],["alguém","any"],["todos","all"],["os","the"],["bens","good"],["de","of"],["sua","his"],["casa","house"],["por","by"],["esse","that ... over there"],["amor,","love,"],["certamente","certainly"],["os","the"],["desprezariam.","they-should-mammon."]]},
  {num:8,words:[["Temos","We-have"],["uma","a"],["irmã","sister"],["pequena,","small,"],["que","that"],["ainda","yet"],["não","no"],["tem","has"],["seios;","breasts;"],["que","that"],["faremos","we-will-make"],["a","to"],["esta","this"],["nossa","our"],["irmã,","sister,"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["dela","of-it"],["se","if"],["falar?","speak?"]]},
  {num:9,words:[["Se","If"],["ela","she"],["for","will-be"],["um","a"],["muro,","wall,"],["edificaremos","we-will-build"],["sobre","upon"],["ela","she"],["um","a"],["palácio","palace"],["de","of"],["prata;","silver;"],["e","and"],["se","if"],["ela","she"],["for","will-be"],["uma","a"],["porta,","exit,"],["a","to"],["cercaremos","we-will-besiege"],["com","with"],["tábuas","boards"],["de","of"],["cedro.","cedar."]]},
  {num:10,words:[["Eu","I"],["sou","I-am"],["um","a"],["muro,","wall,"],["e","and"],["os","the"],["meus","my"],["seios","breasts"],["são","they-are"],["como","as"],["torres;","towers;"],["então","said"],["eu","I"],["era","was"],["aos","to-the"],["seus","his"],["olhos","eyes"],["como","as"],["aquela","that ... over there"],["que","that"],["encontrou","met"],["a","to"],["paz.","peace."]]},
  {num:11,words:[["Teve","Had"],["Salomão","Solomon"],["uma","a"],["vinha","came"],["em","in"],["Baal-Hamom;","Baal-hamon;"],["entregou","delivered"],["essa","that ... over there"],["vinha","came"],["a","to"],["uns","some"],["guardas;","guards;"],["e","and"],["cada","every"],["um","a"],["lhe","to-him"],["trazia,","brought,"],["pelo","by-the"],["seu","his"],["fruto,","fruit,"],["mil","thousand"],["peças","parcel"],["de","of"],["prata.","silver."]]},
  {num:12,words:[["A","To"],["minha","my"],["vinha,","came,"],["que","that"],["tenho,","I-have,"],["está","is"],["diante de","before"],["mim;","me;"],["as","the"],["mil","thousand"],["peças","parcel"],["de","of"],["prata","silver"],["são","they-are"],["para","for"],["ti,","you,"],["ó","O"],["Salomão;","Solomon;"],["e","and"],["duzentas,","hundred,"],["para","for"],["os","the"],["guardas","guards"],["do","of-the"],["seu","his"],["fruto.","fruit."]]},
  {num:13,words:[["Ó","O"],["tu,","you,"],["a","to"],["que","that"],["habitas","you-dwell"],["nos","us"],["jardins,","gardens,"],["para","for"],["a","to"],["tua","your"],["voz","voice"],["os","the"],["companheiros","companion"],["atentam;","they-assault;"],["faze-ma,","gardens,"],["pois,","for,"],["também","also"],["ouvir.","hear."]]},
  {num:14,words:[["Vem","Comes"],["depressa,","quickly,"],["amado","beloved"],["meu,","my,"],["e","and"],["faz-te","makes-you"],["semelhante","like"],["ao","to-the"],["corço","roe"],["ou","or"],["ao","to-the"],["filhote","roe"],["do","of-the"],["cervo","deer"],["sobre","upon"],["os","the"],["montes","mountains"],["aromáticos.","anointing."]]}
];
renderVerseSet(v1, 'sng-ch1-verses');
renderVerseSet(v2, 'sng-ch2-verses');
renderVerseSet(v3, 'sng-ch3-verses');
renderVerseSet(v4, 'sng-ch4-verses');
renderVerseSet(v5, 'sng-ch5-verses');
renderVerseSet(v6, 'sng-ch6-verses');
renderVerseSet(v7, 'sng-ch7-verses');
renderVerseSet(v8, 'sng-ch8-verses');
})();
