(function() {
var v1 = [
  {num:1,words:[["Paulo,","Paul,"],["servo","servant"],["de","of"],["Deus,","God,"],["e","and"],["apóstolo","apostle"],["de","of"],["Jesus","Jesus"],["Cristo,","Christ,"],["segundo","according-to"],["a","to"],["fé","faith"],["dos","of-the"],["eleitos","elect"],["de","of"],["Deus,","God,"],["e","and"],["o","the"],["conhecimento","knowledge"],["da","of-the"],["verdade,","truth,"],["que","that"],["é","is"],["segundo","according-to"],["a","to"],["piedade,","pity,"]]},
  {num:2,words:[["Em","In"],["esperança","hope"],["da","of-the"],["vida","life"],["eterna,","eternal,"],["a","to"],["qual","which"],["Deus,","God,"],["que","that"],["não","no"],["pode","can"],["mentir,","pretended,"],["prometeu","promised"],["antes","before"],["dos","of-the"],["tempos","times"],["dos","of-the"],["séculos;","ages;"]]},
  {num:3,words:[["Mas","But"],["a","to"],["seu","his"],["tempo","time"],["manifestou","manifested"],["a","to"],["sua","his"],["palavra","word"],["pela","by-the"],["pregação","preaching"],["que","that"],["me","me"],["é","is"],["confiada","confide"],["segundo","according-to"],["o","the"],["mandamento","commandment"],["de","of"],["Deus,","God,"],["nosso","our"],["Salvador;","Saver;"]]},
  {num:4,words:[["A","To"],["Tito,","Titus,"],["verdadeiro","true"],["filho,","son,"],["segundo","according-to"],["a","to"],["fé","faith"],["comum:","common:"],["Graça,","Grace,"],["misericórdia,","mercy,"],["e","and"],["paz","peace"],["da","of-the"],["parte","part"],["de","of"],["Deus","God"],["Pai,","Father,"],["e","and"],["do","of-the"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo,","Christ,"],["nosso","our"],["Salvador.","Saver."]]},
  {num:5,words:[["Por","By"],["esta","this"],["causa","sake"],["te","you"],["deixei","owing"],["em","in"],["Creta,","Crete,"],["para que","that"],["pusesses","you-placed"],["em","in"],["boa","good"],["ordem","order"],["as","the"],["coisas","things"],["que","that"],["ainda","yet"],["restam,","earing,"],["e","and"],["de","of"],["cidade","city"],["em","in"],["cidade","city"],["estabelecesses","you-established"],["anciãos,","elders,"],["como","as"],["já","already"],["te","you"],["mandei:","I-commanded:"]]},
  {num:6,words:[["Aquele","That ... over there"],["que","that"],["for","will-be"],["irrepreensível,","blameless,"],["marido","husband"],["de","of"],["uma","a"],["única","alone"],["mulher,","dame,"],["que","that"],["tenha","has"],["filhos","children"],["fiéis,","faithful,"],["que","that"],["não","no"],["possam","they-can"],["ser","be"],["acusados","accuse"],["de","of"],["dissolução","dissolution"],["ou","or"],["desobedientes.","disobedient."]]},
  {num:7,words:[["Porque","Because"],["convém","expedient"],["que","that"],["o","the"],["bispo","bishop"],["seja","is"],["irrepreensível,","blameless,"],["como","as"],["administrador","manager"],["da","of-the"],["casa","house"],["de","of"],["Deus,","God,"],["não","no"],["soberbo,","proud,"],["nem","nor"],["irascível,","appeaseth,"],["nem","nor"],["dado","given"],["ao","to-the"],["vinho,","wine,"],["nem","nor"],["espancador,","striker,"],["nem","nor"],["cobiçoso","acquisitive"],["de","of"],["torpe","lucre"],["ganância;","lucre;"]]},
  {num:8,words:[["Mas","But"],["dado","given"],["à","to-the"],["hospitalidade,","hospitality,"],["amigo","friend"],["do","of-the"],["bem,","good,"],["moderado,","moderate,"],["justo,","fair,"],["santo,","holy,"],["continente;","continent;"]]},
  {num:9,words:[["Retendo","I-restrain"],["firme","firm"],["a","to"],["fiel","faithful"],["palavra,","word,"],["que","that"],["é","is"],["conforme a","according-to"],["doutrina,","doctrine,"],["para que","that"],["seja","is"],["poderoso,","mighty,"],["tanto","both"],["para","for"],["admoestar","admonish"],["com","with"],["a","to"],["sã","soundness"],["doutrina,","doctrine,"],["como","as"],["para","for"],["convencer","convince"],["os","the"],["contradizentes.","gainsayers."]]},
  {num:10,words:[["Porque","Because"],["também","also"],["há","has"],["muitos","many"],["insubordinados,","talkers,"],["faladores","talkative"],["de","of"],["vaidades,","vanities,"],["e","and"],["enganadores,","deceivers,"],["principalmente","especially"],["os","the"],["da","of-the"],["circuncisão,","circumcision,"]]},
  {num:11,words:[["Aos","To-the"],["quais","what"],["convém","expedient"],["tapar","bar"],["a","to"],["boca;","mouth;"],["os","the"],["que","that"],["transtornam","lucre's"],["casas","houses"],["inteiras","entire"],["ensinando","teaching"],["o","the"],["que","that"],["não","no"],["convém,","expedient,"],["por","by"],["torpe","lucre"],["ganância.","lucre."]]},
  {num:12,words:[["Um","A"],["deles,","of-them,"],["seu","his"],["próprio","own"],["profeta,","prophet,"],["disse:","said:"],["Os","The"],["cretenses","cretes"],["são","they-are"],["sempre","always"],["mentirosos,","liars,"],["bestas","beast"],["ruins,","rotten,"],["ventres","abdomen"],["preguiçosos.","lazy."]]},
  {num:13,words:[["Esse","That ... over there"],["testemunho","testimony"],["é","is"],["verdadeiro.","true."],["Portanto,","Therefore,"],["repreende-os","admonishes-the"],["severamente,","sharply,"],["para que","that"],["sejam","they-are"],["sãos","physician"],["na","in-the"],["fé;","faith;"]]},
  {num:14,words:[["Não","No"],["dando","giving"],["ouvidos","ears"],["às","to-the"],["fábulas","fables"],["judaicas,","jews',"],["e","and"],["aos","to-the"],["mandamentos","commandments"],["de","of"],["homens","men"],["que","that"],["se","if"],["desviam","they-bypass"],["da","of-the"],["verdade.","truth."]]},
  {num:15,words:[["Para","For"],["os","the"],["puros,","pure,"],["todas","things"],["as","the"],["coisas","things"],["são","they-are"],["puras,","pure,"],["mas","but"],["nada","nothing"],["é","is"],["puro","pure"],["para","for"],["os","the"],["contaminados","defile"],["e","and"],["infiéis;","unbelievers;"],["antes,","before,"],["o","the"],["seu","his"],["entendimento","understanding"],["e","and"],["consciência","conscience"],["estão","they-are"],["contaminados.","defile."]]},
  {num:16,words:[["Confessam","They-confess"],["que","that"],["conhecem","they-know"],["a","to"],["Deus,","God,"],["porém","but"],["com","with"],["as","the"],["obras","works"],["o","the"],["negam,","they-deny,"],["sendo","being"],["abomináveis,","you-abhorred,"],["e","and"],["desobedientes,","disobedient,"],["e","and"],["reprovados","reprobates"],["para","for"],["toda","every"],["boa","good"],["obra.","work."]]}
];
var v2 = [
  {num:1,words:[["Tu,","You,"],["porém,","but,"],["fala","speech"],["o","the"],["que","that"],["convém","expedient"],["à","to-the"],["sã","soundness"],["doutrina:","doctrine:"]]},
  {num:2,words:[["Aos","To-the"],["homens","men"],["idosos,","aged,"],["que","that"],["sejam","they-are"],["sóbrios,","sober,"],["respeitáveis,","you-respected,"],["prudentes,","prudent,"],["sãos","physician"],["na","in-the"],["fé,","faith,"],["na","in-the"],["caridade,","charity,"],["e","and"],["na","in-the"],["paciência;","patience;"]]},
  {num:3,words:[["Às","To-the"],["mulheres","women"],["idosas,","sen,"],["semelhantemente,","likely,"],["que","that"],["sejam","they-are"],["sérias","serious"],["no","in-the"],["seu","his"],["viver,","live,"],["como","as"],["convém","expedient"],["a","to"],["santas,","holy,"],["não","no"],["caluniadoras,","calumniator,"],["não","no"],["dadas","give"],["a","to"],["muito","much"],["vinho,","wine,"],["mestras","master"],["do","of-the"],["bem;","good;"]]},
  {num:4,words:[["Para que","that"],["ensinem","they-teach"],["as","the"],["moças","maidens"],["a","to"],["serem","to-be"],["prudentes,","prudent,"],["a","to"],["amarem","they-will-mammon"],["seu","his"],["marido,","husband,"],["a","to"],["amarem","they-will-mammon"],["seus","his"],["filhos,","children,"]]},
  {num:5,words:[["A","To"],["serem","to-be"],["moderadas,","bridle,"],["castas,","chaste,"],["boas","tidings"],["donas","owner"],["de","of"],["casa,","house,"],["sujeitas","you-overpower"],["a","to"],["seu","his"],["marido;","husband;"],["para que","that"],["a","to"],["palavra","word"],["de","of"],["Deus","God"],["não","no"],["seja","is"],["blasfemada.","blaspheme."]]},
  {num:6,words:[["Exorta","Admonishes"],["semelhantemente","likely"],["os","the"],["jovens","young"],["a","to"],["que","that"],["sejam","they-are"],["moderados.","bridle."]]},
  {num:7,words:[["Em","In"],["tudo","whatsoever"],["mostra-te","appear"],["exemplo","example"],["de","of"],["boas","tidings"],["obras;","works;"],["na","in-the"],["doutrina","doctrine"],["mostra","showeth"],["incorrupção,","incorruption,"],["respeitabilidade,","uncorruptness,"],["sinceridade,","sincerity,"]]},
  {num:8,words:[["Linguagem","Language"],["sã","soundness"],["e","and"],["irrepreensível,","blameless,"],["para que","that"],["o","the"],["adversário","adversary"],["se","if"],["envergonhe,","abashes,"],["não","no"],["tendo","having"],["nenhum","none"],["mal","evil"],["que","that"],["dizer","say"],["de","of"],["vós.","you."]]},
  {num:9,words:[["Exorta","Admonishes"],["os","the"],["servos","servants"],["a","to"],["que","that"],["se","if"],["sujeitem","they-overpower"],["a","to"],["seus","his"],["senhores,","masters,"],["e","and"],["em","in"],["tudo","whatsoever"],["agradem,","they-please,"],["não","no"],["contradizendo,","I-contradict,"]]},
  {num:10,words:[["Não","No"],["defraudando,","I-defraud,"],["antes,","before,"],["mostrando","shewing"],["toda","every"],["a","to"],["boa","good"],["lealdade,","loyalty,"],["para que","that"],["em","in"],["tudo","whatsoever"],["adornem","adorn"],["a","to"],["doutrina","doctrine"],["de","of"],["Deus,","God,"],["nosso","our"],["Salvador.","Saver."]]},
  {num:11,words:[["Porque","Because"],["a","to"],["graça","grace"],["de","of"],["Deus","God"],["se","if"],["manifestou,","manifested,"],["trazendo","bringing"],["salvação","salvation"],["a","to"],["todos","all"],["os","the"],["homens,","men,"]]},
  {num:12,words:[["Ensinando-nos","Teaching-us"],["que,","that,"],["renunciando","I-abjure"],["à","to-the"],["impiedade","wickedness"],["e","and"],["às","to-the"],["concupiscências","lusts"],["mundanas,","soberly,"],["vivamos","live"],["neste","in-this"],["presente","present"],["mundo","world"],["sóbria,","sober,"],["e","and"],["justa,","fair,"],["e","and"],["piamente,","laverly,"]]},
  {num:13,words:[["Aguardando","I-abide"],["a","to"],["bem-aventurada","happy"],["esperança","hope"],["e","and"],["o","the"],["aparecimento","appearing"],["da","of-the"],["glória","glory"],["do","of-the"],["grande","great"],["Deus","God"],["e","and"],["nosso","our"],["Senhor","Lord"],["Jesus","Jesus"],["Cristo;","Christ;"]]},
  {num:14,words:[["O","The"],["qual","which"],["se","if"],["deu","gave"],["a","to"],["si","himself"],["mesmo","even"],["por","by"],["nós","we"],["para","for"],["nos","us"],["redimir","redeem"],["de","of"],["toda","every"],["a","to"],["iniquidade,","iniquity,"],["e","and"],["purificar","cleanse"],["para","for"],["si","himself"],["mesmo","even"],["um","a"],["povo","people"],["particular,","apart,"],["zeloso","zealous"],["de","of"],["boas","tidings"],["obras.","works."]]},
  {num:15,words:[["Fala","Speech"],["disso,","of-that,"],["e","and"],["exorta,","admonishes,"],["e","and"],["repreende","admonishes"],["com","with"],["toda","every"],["a","to"],["autoridade.","authority."],["Ninguém","None"],["te","you"],["despreze.","mammon."]]}
];
var v3 = [
  {num:1,words:[["Admoesta-os","Admonishes-the"],["a","to"],["que","that"],["se","if"],["sujeitem","they-overpower"],["aos","to-the"],["principados","principalities"],["e","and"],["potestades,","principalities,"],["que","that"],["lhes","to-them"],["obedeçam,","they-obey,"],["e","and"],["estejam","they-are"],["preparados","prepared"],["para","for"],["toda","every"],["boa","good"],["obra;","work;"]]},
  {num:2,words:[["Que","That"],["a","to"],["ninguém","none"],["infamem,","brawlers,"],["nem","nor"],["sejam","they-are"],["contenciosos,","brawlers,"],["porém","but"],["afáveis,","affable,"],["mostrando","shewing"],["toda","every"],["a","to"],["mansidão","meekness"],["para","for"],["com","with"],["todos","all"],["os","the"],["homens.","men."]]},
  {num:3,words:[["Porque","Because"],["também","also"],["nós","we"],["dantes","of-ahead"],["éramos","we-were"],["insensatos,","sanctifieth,"],["desobedientes,","disobedient,"],["extraviados,","misguide,"],["servindo","serving"],["a","to"],["várias","any"],["concupiscências","lusts"],["e","and"],["deleites,","pleasures,"],["vivendo","I-live"],["em","in"],["malícia","malice"],["e","and"],["inveja,","envy,"],["odiosos","nasty"],["e","and"],["odiando","hating"],["uns","some"],["aos","to-the"],["outros.","another."]]},
  {num:4,words:[["Mas","But"],["quando","when"],["apareceu","appeared"],["a","to"],["benignidade","endureth"],["e","and"],["caridade","charity"],["de","of"],["Deus,","God,"],["nosso","our"],["Salvador,","Saver,"],["para","for"],["com","with"],["os","the"],["homens,","men,"]]},
  {num:5,words:[["Não","No"],["pelas","by-the"],["obras","works"],["de","of"],["justiça","righteousness"],["que","that"],["houvéssemos","we-had"],["feito,","done,"],["mas","but"],["segundo","according-to"],["a","to"],["sua","his"],["misericórdia,","mercy,"],["nos","us"],["salvou","saved"],["pela","by-the"],["lavagem","regeneration"],["da","of-the"],["regeneração","regeneration"],["e","and"],["da","of-the"],["renovação","renewing"],["do","of-the"],["Espírito","Spirit"],["Santo;","Holy;"]]},
  {num:6,words:[["O","The"],["qual","which"],["abundantemente","abundantly"],["derramou","poured"],["sobre","upon"],["nós","we"],["por","by"],["Jesus","Jesus"],["Cristo,","Christ,"],["nosso","our"],["Salvador;","Saver;"]]},
  {num:7,words:[["Para que,","that"],["sendo","being"],["justificados","justified"],["pela","by-the"],["sua","his"],["graça,","grace,"],["sejamos","we-are"],["feitos","acts"],["herdeiros","heirs"],["segundo","according-to"],["a","to"],["esperança","hope"],["da","of-the"],["vida","life"],["eterna.","eternal."]]},
  {num:8,words:[["Fiel","Faithful"],["é","is"],["a","to"],["palavra,","word,"],["e","and"],["isto","it"],["quero","I-will"],["que","that"],["deveras","genuinly"],["afirmes,","you-affirm,"],["para que","that"],["os","the"],["que","that"],["creem","they-believe"],["em","in"],["Deus","God"],["procurem","they-search"],["aplicar-se","to-aplicar-se"],["às","to-the"],["boas","tidings"],["obras;","works;"],["essas","those"],["coisas","things"],["são","they-are"],["boas","tidings"],["e","and"],["proveitosas","fruitful"],["aos","to-the"],["homens.","men."]]},
  {num:9,words:[["Mas","But"],["resiste","resisteth"],["às","to-the"],["questões","questions"],["loucas,","avoid,"],["e","and"],["às","to-the"],["genealogias","genealogy"],["e","and"],["contendas,","you-contend,"],["e","and"],["aos","to-the"],["debates","you-beat off"],["acerca","concerning"],["da","of-the"],["lei,","law,"],["porque","because"],["são","they-are"],["inúteis","unprofitable"],["e","and"],["vãos.","babblings."]]},
  {num:10,words:[["Ao","To-the"],["homem","man"],["herege,","heretic,"],["depois","afterwards"],["de","of"],["uma","a"],["e","and"],["outra","another"],["admoestação,","admonition,"],["rejeita-o,","rejects-the,"]]},
  {num:11,words:[["Sabendo","Knowing"],["que","that"],["o","the"],["tal","same"],["está","is"],["pervertido,","pervert,"],["e","and"],["peca,","pekah,"],["estando","I-am"],["já","already"],["em","in"],["si","himself"],["mesmo","even"],["condenado.","I-should-berate."]]},
  {num:12,words:[["Quando","When"],["te","you"],["enviar","send"],["Artemas,","Artemas,"],["ou","or"],["Tíquico,","Tychicus,"],["procura","seeketh"],["vir","come"],["ter","have"],["comigo","with-me"],["a","to"],["Nicópolis,","Artemas,"],["porque","because"],["deliberei","I-decided"],["invernar","commodious"],["ali.","there."]]},
  {num:13,words:[["Acompanha","Accompanies"],["com","with"],["muito","much"],["cuidado","care"],["Zenas,","Zenas,"],["doutor","doctor"],["da","of-the"],["lei,","law,"],["e","and"],["Apolo,","Apollos,"],["para que","that"],["nada","nothing"],["lhes","to-them"],["falte.","wanting."]]},
  {num:14,words:[["E","And"],["os","the"],["nossos","our"],["aprendam","they-learn"],["também","also"],["a","to"],["aplicar-se","to-aplicar-se"],["às","to-the"],["boas","tidings"],["obras,","works,"],["para","for"],["os","the"],["usos","use"],["necessários,","appendages,"],["para que","that"],["não","no"],["sejam","they-are"],["infrutíferos.","uses."]]},
  {num:15,words:[["Saúdam-te","They-greet-you"],["todos","all"],["os","the"],["que","that"],["estão","they-are"],["comigo.","with-me."],["Saúda","Greets"],["tu","you"],["os","the"],["que","that"],["nos","us"],["amam","love"],["na","in-the"],["fé.","faith."],["A","To"],["graça","grace"],["seja","is"],["com","with"],["todos","all"],["vós.","you."],["Amém.","Amen."]]}
];
renderVerseSet(v1, 'tit-ch1-verses');
renderVerseSet(v2, 'tit-ch2-verses');
renderVerseSet(v3, 'tit-ch3-verses');
})();
