(function() {
var v1 = [
  {num:1,words:[["Palavra","Word"],["do","of-the"],["Senhor,","Lord,"],["que","that"],["veio","came"],["a","to"],["Sofonias,","Zephaniah,"],["filho","son"],["de","of"],["Cusi,","Cushi,"],["filho","son"],["de","of"],["Gedalias,","Gedaliah,"],["filho","son"],["de","of"],["Amarias,","You-should-mammon,"],["filho","son"],["de","of"],["Ezequias,","Hezekiah,"],["nos","us"],["dias","days"],["de","of"],["Josias,","Josiah,"],["filho","son"],["de","of"],["Amom,","Ammon,"],["rei","king"],["de","of"],["Judá.","Judah."]]},
  {num:2,words:[["Eu","I"],["indubitavelmente","doubtless"],["hei","I-have"],["de","of"],["arrebatar","snap up"],["tudo","whatsoever"],["de","of"],["sobre","upon"],["a","to"],["face","face"],["da","of-the"],["terra,","land,"],["diz","says"],["o","the"],["Senhor.","Lord."]]},
  {num:3,words:[["Arrebatarei","I-will-snap up"],["os","the"],["homens","men"],["e","and"],["os","the"],["animais,","beasts,"],["arrebatarei","I-will-snap up"],["as","the"],["aves","fowls"],["do","of-the"],["céu,","heaven,"],["e","and"],["os","the"],["peixes","fishes"],["do","of-the"],["mar,","sea,"],["e","and"],["os","the"],["tropeços","stumblingblocks"],["com","with"],["os","the"],["ímpios;","wicked;"],["e","and"],["exterminarei","I-will-reverse"],["os","the"],["homens","men"],["de","of"],["cima","above"],["da","of-the"],["terra,","land,"],["disse","said"],["o","the"],["Senhor.","Lord."]]},
  {num:4,words:[["E","And"],["estenderei","stretch"],["a","to"],["minha","my"],["mão","hand"],["contra","against"],["Judá,","Judah,"],["e","and"],["contra","against"],["todos","all"],["os","the"],["habitantes","inhabitants"],["de","of"],["Jerusalém,","Jerusalem,"],["e","and"],["exterminarei","I-will-reverse"],["deste","of-this"],["lugar","place"],["o","the"],["resto","I-remain"],["de","of"],["Baal,","Baal,"],["e","and"],["o","the"],["nome","name"],["dos","of-the"],["ministros","ministers"],["idólatras","idolaters"],["com","with"],["os","the"],["sacerdotes;","priests;"]]},
  {num:5,words:[["E","And"],["os","the"],["que","that"],["sobre","upon"],["os","the"],["telhados","housetops"],["se","if"],["encurvam","malcham"],["ao","to-the"],["exército","army"],["do","of-the"],["céu;","heaven;"],["e","and"],["os","the"],["que","that"],["se","if"],["inclinam","malcham"],["jurando","I-swear"],["pelo","by-the"],["Senhor,","Lord,"],["e","and"],["juram","swearers"],["por","by"],["Milcom;","Milcom;"]]},
  {num:6,words:[["E","And"],["os","the"],["que","that"],["deixam","they-allow"],["de","of"],["seguir","follow"],["ao","to-the"],["Senhor,","Lord,"],["e","and"],["os","the"],["que","that"],["não","no"],["buscam","seek"],["ao","to-the"],["Senhor,","Lord,"],["nem","nor"],["perguntam","they-asketh"],["por","by"],["ele.","he."]]},
  {num:7,words:[["Cala-te","Be quiet"],["diante","before"],["do","of-the"],["Senhor","Lord"],["Deus,","God,"],["porque","because"],["o","the"],["dia","day"],["do","of-the"],["Senhor","Lord"],["está","is"],["perto,","near,"],["porque","because"],["o","the"],["Senhor","Lord"],["preparou","prepared"],["o","the"],["sacrifício,","sacrifice,"],["e","and"],["santificou","sanctified"],["os","the"],["seus","his"],["convidados.","invite."]]},
  {num:8,words:[["E","And"],["há","has"],["de","of"],["ser que,","except"],["no","in-the"],["dia","day"],["do","of-the"],["sacrifício","sacrifice"],["do","of-the"],["Senhor,","Lord,"],["hei","I-have"],["de","of"],["castigar","punish"],["os","the"],["príncipes,","princes,"],["e","and"],["os","the"],["filhos","children"],["do rei,","king's"],["e","and"],["todos","all"],["os","the"],["que","that"],["se","if"],["vestem","they-clothe"],["de","of"],["trajes","robes"],["estrangeiros.","strangers."]]},
  {num:9,words:[["Também","Also"],["castigarei","punish"],["naquele","in-that"],["dia","day"],["todo","every"],["aquele","that ... over there"],["que","that"],["salta","jumps"],["sobre","upon"],["o","the"],["umbral,","threshold,"],["que","that"],["enche","filleth"],["de","of"],["violência","violence"],["e","and"],["engano","deceit"],["a","to"],["casa","house"],["dos","of-the"],["seus","his"],["senhores.","masters."]]},
  {num:10,words:[["E","And"],["naquele","in-that"],["dia,","day,"],["diz","says"],["o","the"],["Senhor,","Lord,"],["haverá","will-have"],["uma","a"],["voz","voice"],["de","of"],["clamor","cry"],["desde","since"],["a","to"],["porta","exit"],["do","of-the"],["peixe,","fish,"],["e","and"],["um","a"],["uivo","howling"],["desde","since"],["a","to"],["segunda","second"],["parte,","part,"],["e","and"],["grande","great"],["quebrantamento","crashing"],["desde","since"],["os","the"],["outeiros.","hills."]]},
  {num:11,words:[["Uivai","Howl"],["vós,","you,"],["moradores","inhabitants"],["de","of"],["Mactés,","Maktesh,"],["porque","because"],["todo","every"],["o","the"],["povo","people"],["mercador","trader"],["está","is"],["arruinado,","I-should-damage,"],["todos","all"],["os","the"],["carregados","carry"],["de","of"],["dinheiro","money"],["são","they-are"],["destruídos.","destroyed."]]},
  {num:12,words:[["E","And"],["há","has"],["de","of"],["ser que,","except"],["naquele","in-that"],["tempo,","time,"],["esquadrinharei","candles"],["Jerusalém","Jerusalem"],["com","with"],["lanternas,","lantern,"],["e","and"],["castigarei","punish"],["os","the"],["homens","men"],["que","that"],["estão","they-are"],["assentados","sitting"],["como","as"],["a","to"],["borra","sludge"],["do","of-the"],["vinho,","wine,"],["que","that"],["dizem","they-say"],["no","in-the"],["seu","his"],["coração:","heart:"],["O","The"],["Senhor","Lord"],["não","no"],["faz","makes"],["o","the"],["bem","good"],["nem","nor"],["faz","makes"],["o","the"],["mal.","evil."]]},
  {num:13,words:[["Por isso","therefore"],["serão","they-will-be"],["saqueados","booty"],["os","the"],["seus","his"],["bens,","good,"],["e","and"],["assoladas","desolate"],["as","the"],["suas","his"],["casas;","houses;"],["e","and"],["edificarão","inhabit"],["casas,","houses,"],["mas","but"],["não","no"],["habitarão","safely"],["nelas,","in-him,"],["e","and"],["plantarão","inhabit"],["vinhas,","vineyards,"],["mas","but"],["não","no"],["lhes","to-them"],["beberão","they-will-drink"],["o","the"],["seu","his"],["vinho.","wine."]]},
  {num:14,words:[["O","The"],["grande","great"],["dia","day"],["do","of-the"],["Senhor","Lord"],["está","is"],["perto,","near,"],["perto","near"],["está,","is,"],["e","and"],["se","if"],["apressa","hasteth"],["muito,","much,"],["sim,","yea,"],["a","to"],["voz","voice"],["do","of-the"],["dia","day"],["do","of-the"],["Senhor;","Lord;"],["amargamente","bitterly"],["clamará","will-cry"],["ali","there"],["o","the"],["valente.","brave."]]},
  {num:15,words:[["Aquele","That ... over there"],["dia","day"],["será","will-be"],["um","a"],["dia","day"],["de","of"],["indignação,","indignation,"],["dia","day"],["de","of"],["angústia","anguish"],["e","and"],["de","of"],["aflição,","affliction,"],["dia","day"],["de","of"],["alvoroço","excitement"],["e","and"],["de","of"],["assolação,","desolation,"],["dia","day"],["de","of"],["trevas","darkness"],["e","and"],["de","of"],["escuridão,","darkness,"],["dia","day"],["de","of"],["nuvens","clouds"],["e","and"],["de","of"],["densas","concentrated"],["trevas,","darkness,"]]},
  {num:16,words:[["Dia","Day"],["de","of"],["buzina","trumpet"],["e","and"],["de","of"],["alarido","shouting"],["contra","against"],["as","the"],["cidades","cities"],["fortificadas","fenced"],["e","and"],["contra","against"],["as","the"],["torres","towers"],["altas.","pickets."]]},
  {num:17,words:[["E","And"],["angustiarei","I-will-afflict"],["os","the"],["homens,","men,"],["que","that"],["andarão","fatling"],["como","as"],["cegos,","blind,"],["porque","because"],["pecaram","sinned"],["contra","against"],["o","the"],["Senhor;","Lord;"],["e","and"],["o","the"],["seu","his"],["sangue","blood"],["se","if"],["derramará","bottom"],["como","as"],["pó,","dust,"],["e","and"],["a","to"],["sua","his"],["carne","flesh"],["será","will-be"],["como","as"],["esterco.","dung."]]},
  {num:18,words:[["Nem","Nor"],["a","to"],["sua","his"],["prata","silver"],["nem","nor"],["o","the"],["seu","his"],["ouro","gold"],["os","the"],["poderá","will-can"],["livrar","free"],["no","in-the"],["dia","day"],["do","of-the"],["furor","fury"],["do","of-the"],["Senhor,","Lord,"],["mas","but"],["pelo","by-the"],["fogo","fire"],["do","of-the"],["seu","his"],["zelo","zeal"],["toda","every"],["esta","this"],["terra","land"],["será","will-be"],["consumida,","consume,"],["porque","because"],["ele","he"],["certamente","certainly"],["fará","will-make"],["de","of"],["todos","all"],["os","the"],["moradores","inhabitants"],["desta","of-this"],["terra","land"],["uma","a"],["destruição","destruction"],["total","entire"],["e","and"],["apressada.","accelerate."]]}
];
var v2 = [
  {num:1,words:[["Congregai-vos,","Feathered,"],["sim,","yea,"],["congregai-vos,","feathered,"],["ó","O"],["nação","nation"],["não","no"],["desejável,","desirable,"]]},
  {num:2,words:[["Antes que","before"],["o","the"],["decreto","decree"],["produza","activates"],["o","the"],["seu","his"],["efeito,","effect,"],["antes que","before"],["o","the"],["dia","day"],["passe","pass"],["como","as"],["a","to"],["pragana,","chaff,"],["antes que","before"],["venha","comes"],["sobre","upon"],["vós","you"],["a","to"],["ira","anger"],["do","of-the"],["Senhor,","Lord,"],["antes que","before"],["venha","comes"],["sobre","upon"],["vós","you"],["o","the"],["dia","day"],["da","of-the"],["ira","anger"],["do","of-the"],["Senhor.","Lord."]]},
  {num:3,words:[["Buscai","Seek"],["ao","to-the"],["Senhor,","Lord,"],["vós","you"],["todos","all"],["os","the"],["mansos","meek"],["da","of-the"],["terra,","land,"],["que","that"],["cumpris","you-observe"],["o","the"],["seu","his"],["juízo;","judgment;"],["buscai","seek"],["a","to"],["justiça,","righteousness,"],["buscai","seek"],["a","to"],["mansidão;","meekness;"],["porventura","perchance"],["sereis","you-will-be"],["escondidos","hid"],["no","in-the"],["dia","day"],["da","of-the"],["ira","anger"],["do","of-the"],["Senhor.","Lord."]]},
  {num:4,words:[["Porque","Because"],["Gaza","Gaza"],["será","will-be"],["desamparada,","abandon,"],["e","and"],["Ascalom","Ashkelon"],["será","will-be"],["assolada;","desolate;"],["Asdode","Ashdod"],["ao","to-the"],["meio","midst"],["dia","day"],["será","will-be"],["expulsa,","beelzebub,"],["e","and"],["Ecrom","Ekron"],["será","will-be"],["desarraigada.","succeedest."]]},
  {num:5,words:[["Ai","Ouch"],["dos","of-the"],["habitantes","inhabitants"],["da","of-the"],["costa","seashore"],["do","of-the"],["mar,","sea,"],["do","of-the"],["povo","people"],["dos","of-the"],["quereteus!","cherethites!"],["A","To"],["palavra","word"],["do","of-the"],["Senhor","Lord"],["será","will-be"],["contra","against"],["vós,","you,"],["ó","O"],["Canaã,","Canaan,"],["terra","land"],["dos","of-the"],["filisteus,","philistines,"],["e","and"],["eu","I"],["vos","you"],["farei","I-will-make"],["destruir,","destroy,"],["até que","until"],["não","no"],["haja","has"],["morador.","inhabitant."]]},
  {num:6,words:[["E","And"],["a","to"],["costa","seashore"],["do","of-the"],["mar","sea"],["será","will-be"],["de","of"],["pastagens","feedingplace"],["e","and"],["cabanas","booths"],["para","for"],["os","the"],["pastores,","shepherds,"],["e","and"],["currais","folds"],["para","for"],["os","the"],["rebanhos.","flocks."]]},
  {num:7,words:[["E","And"],["será","will-be"],["a","to"],["costa","seashore"],["para","for"],["o","the"],["remanescente","remnant"],["da","of-the"],["casa","house"],["de","of"],["Judá,","Judah,"],["nela","in-it"],["apascentarão;","they-will-feed;"],["à","to-the"],["tarde","evening"],["se","if"],["assentarão","pitch"],["nas","in-the"],["casas","houses"],["de","of"],["Ascalom,","Ashkelon,"],["porque","because"],["o","the"],["Senhor","Lord"],["seu","his"],["Deus","God"],["os","the"],["visitará,","will-frequent,"],["e","and"],["os","the"],["fará","will-make"],["retornar","recur"],["do","of-the"],["seu","his"],["cativeiro.","bondage."]]},
  {num:8,words:[["Eu","I"],["ouvi","I-heard"],["o","the"],["escárnio","derision"],["de","of"],["Moabe,","Moab,"],["e","and"],["as","the"],["injúrias","revilings"],["dos","of-the"],["filhos","children"],["de","of"],["Amom,","Ammon,"],["com","with"],["que","that"],["escarneceram","they-mocked"],["do","of-the"],["meu","my"],["povo,","people,"],["e","and"],["se","if"],["engrandeceram","to-engrandecer"],["contra","against"],["o","the"],["seu","his"],["termo.","border."]]},
  {num:9,words:[["Portanto,","Therefore,"],["vivo","alive"],["eu,","I,"],["diz","says"],["o Senhor dos","hosts"],["Exércitos,","Hosts,"],["o","the"],["Deus","God"],["de","of"],["Israel,","Israel,"],["certamente","certainly"],["Moabe","Moab"],["será","will-be"],["como","as"],["Sodoma,","Sodom,"],["e","and"],["os","the"],["filhos","children"],["de","of"],["Amom,","Ammon,"],["como","as"],["Gomorra,","Gomorrah,"],["campo","field"],["de","of"],["urtigas","nettles"],["e","and"],["poços","wells"],["de","of"],["sal,","salt,"],["e","and"],["assolação","desolation"],["perpétua;","perpetual;"],["o","the"],["restante","remaining"],["do","of-the"],["meu","my"],["povo","people"],["os","the"],["saqueará,","breeding,"],["e","and"],["o","the"],["restante","remaining"],["do","of-the"],["meu","my"],["povo","people"],["os","the"],["possuirá.","will-possess."]]},
  {num:10,words:[["Isso","That"],["terão","they-will-have"],["em","in"],["recompensa","reward"],["da","of-the"],["sua","his"],["soberba,","pride,"],["porque","because"],["escarneceram,","they-mocked,"],["e","and"],["se","if"],["engrandeceram","to-engrandecer"],["contra","against"],["o","the"],["povo","people"],["do","of-the"],["Senhor dos","hosts"],["Exércitos.","Hosts."]]},
  {num:11,words:[["O","The"],["Senhor","Lord"],["será","will-be"],["terrível","abysmal"],["contra","against"],["eles,","they,"],["porque","because"],["aniquilará","famish"],["todos","all"],["os","the"],["deuses","gods"],["da","of-the"],["terra;","land;"],["e","and"],["cada","every"],["um","a"],["se","if"],["inclinará","famish"],["a","to"],["ele","he"],["desde o","beginning"],["seu","his"],["lugar,","place,"],["todas","things"],["as","the"],["ilhas","isles"],["das","of-the"],["nações.","nations."]]},
  {num:12,words:[["Também","Also"],["vós,","you,"],["ó","O"],["etíopes,","ethiopians,"],["sereis","you-will-be"],["mortos","dead"],["com","with"],["a","to"],["minha","my"],["espada.","sword."]]},
  {num:13,words:[["Estenderá","Will-stretch"],["também","also"],["a","to"],["sua","his"],["mão","hand"],["contra","against"],["o","the"],["norte,","north,"],["e","and"],["destruirá","destroy"],["a","to"],["Assíria;","Assyria;"],["e","and"],["fará","will-make"],["de","of"],["Nínive","Nineveh"],["uma","a"],["assolação,","desolation,"],["terra","land"],["seca","dry"],["como","as"],["o","the"],["deserto.","desert."]]},
  {num:14,words:[["E","And"],["no","in-the"],["meio","midst"],["dela","of-it"],["repousarão","they-will-repose"],["os","the"],["rebanhos,","flocks,"],["todos","all"],["os","the"],["animais","beasts"],["dos","of-the"],["povos;","nations;"],["e","and"],["alojar-se-ão","to-alojar-se"],["nos","us"],["seus","his"],["capitéis","chapiters"],["tanto","both"],["o","the"],["pelicano","pelican"],["como","as"],["o","the"],["ouriço;","lintels;"],["a","to"],["voz","voice"],["do","of-the"],["seu","his"],["canto","corner"],["retinirá","will-jingle"],["nas","in-the"],["janelas,","windows,"],["a","to"],["assolação","desolation"],["estará","will-be"],["no","in-the"],["umbral,","threshold,"],["quando","when"],["tiver","will-have"],["posto","post"],["a","to"],["descoberto","I-should-uncover"],["a","to"],["sua","his"],["obra","work"],["de","of"],["cedro.","cedar."]]},
  {num:15,words:[["Esta","This"],["é","is"],["a","to"],["cidade","city"],["que","that"],["salta","jumps"],["de","of"],["alegria,","joy,"],["que","that"],["habita","dwelleth"],["segura,","carelessly,"],["que","that"],["diz","says"],["no","in-the"],["seu","his"],["coração:","heart:"],["Eu","I"],["sou,","I-am,"],["e","and"],["não","no"],["há","has"],["outra","another"],["além de","besides"],["mim;","me;"],["como","as"],["se","if"],["tornou","became"],["em","in"],["assolação,","desolation,"],["em","in"],["pousada","lodging"],["de","of"],["animais!","beasts!"],["Qualquer que","whosoever"],["passar","fare"],["por","by"],["ela","she"],["assobiará,","hiss,"],["e","and"],["meneará","will-rock"],["a","to"],["sua","his"],["mão.","hand."]]}
];
var v3 = [
  {num:1,words:[["Ai","Ouch"],["da","of-the"],["rebelde","rebellious"],["e","and"],["da","of-the"],["contaminada,","defile,"],["da","of-the"],["cidade","city"],["opressora!","oppressor!"]]},
  {num:2,words:[["Não","No"],["obedeceu","obeyed"],["à","to-the"],["voz,","voice,"],["não","no"],["aceitou","shared"],["o","the"],["castigo;","punishment;"],["não","no"],["confiou","trusted"],["no","in-the"],["Senhor;","Lord;"],["nem","nor"],["se","if"],["aproximou","approximated"],["do","of-the"],["seu","his"],["Deus.","God."]]},
  {num:3,words:[["Os","The"],["seus","his"],["príncipes","princes"],["são","they-are"],["leões","lions"],["bramantes","gnaw"],["no","in-the"],["meio","midst"],["dela;","of-it;"],["os","the"],["seus","his"],["juízes","judges"],["são","they-are"],["lobos","wolves"],["da","of-the"],["tarde,","evening,"],["que","that"],["não","no"],["deixam","they-allow"],["os","the"],["ossos","bones"],["até","until"],["a","to"],["manhã.","morning."]]},
  {num:4,words:[["Os","The"],["seus","his"],["profetas","prophets"],["são","they-are"],["levianos,","flighty,"],["homens","men"],["traiçoeiros;","treacherous;"],["os","the"],["seus","his"],["sacerdotes","priests"],["profanaram","sabbaths"],["o","the"],["santuário,","sanctuary,"],["e","and"],["fizeram","they-made"],["violência","violence"],["à","to-the"],["lei.","law."]]},
  {num:5,words:[["O","The"],["Senhor,","Lord,"],["o","the"],["Justo,","Fair,"],["está","is"],["no","in-the"],["meio","midst"],["dela;","of-it;"],["ele","he"],["não","no"],["comete","committeth"],["iniquidade;","iniquity;"],["cada","every"],["manhã","morning"],["traz","bringeth"],["o","the"],["seu","his"],["juízo","judgment"],["à","to-the"],["luz;","light;"],["nunca","never"],["falha;","absence;"],["porém","but"],["o","the"],["perverso","malicious"],["não","no"],["conhece","knoweth"],["a","to"],["vergonha.","shame."]]},
  {num:6,words:[["Exterminei","I-reversed"],["as","the"],["nações,","nations,"],["as","the"],["suas","his"],["torres","towers"],["estão","they-are"],["assoladas;","desolate;"],["fiz","I-made"],["desertas","desert"],["as","the"],["suas","his"],["praças,","markets,"],["até","until"],["não","no"],["ficar","remain"],["quem","who"],["passe","pass"],["por","by"],["elas;","they;"],["as","the"],["suas","his"],["cidades","cities"],["estão","they-are"],["destruídas,","ruined,"],["até","until"],["não","no"],["ficar","remain"],["ninguém,","none,"],["até","until"],["não","no"],["haver","have"],["quem","who"],["as","the"],["habite.","dwells."]]},
  {num:7,words:[["Eu","I"],["dizia:","said:"],["Certamente","Certainly"],["me","me"],["temerás,","you-will-fear,"],["e","and"],["aceitarás","you-will-share"],["a","to"],["correção,","correction,"],["para que","that"],["a","to"],["sua","his"],["morada","dwelling"],["não","no"],["seja","is"],["destruída,","destroyed,"],["por","by"],["tudo","whatsoever"],["pelo","by-the"],["que","that"],["a","to"],["castiguei,","I-punished,"],["mas","but"],["eles","they"],["se","if"],["levantaram","rose"],["de","of"],["madrugada,","early,"],["corromperam","they-bribed"],["todas","things"],["as","the"],["suas","his"],["obras.","works."]]},
  {num:8,words:[["Portanto,","Therefore,"],["esperai-me","abide-me"],["diz","says"],["o","the"],["Senhor,","Lord,"],["no","in-the"],["dia","day"],["em","in"],["que","that"],["eu","I"],["me","me"],["levantar","hoist"],["para","for"],["o","the"],["despojo;","spoil;"],["porque","because"],["o","the"],["meu","my"],["juízo","judgment"],["é","is"],["ajuntar","add"],["as","the"],["nações","nations"],["e","and"],["congregar","unlearned"],["os","the"],["reinos,","kingdoms,"],["para","for"],["sobre","upon"],["eles","they"],["derramar","pour"],["a","to"],["minha","my"],["indignação,","indignation,"],["e","and"],["todo","every"],["o","the"],["ardor","glow"],["da","of-the"],["minha","my"],["ira;","anger;"],["porque","because"],["toda","every"],["esta","this"],["terra","land"],["será","will-be"],["consumida","consume"],["pelo","by-the"],["fogo","fire"],["do","of-the"],["meu","my"],["zelo.","zeal."]]},
  {num:9,words:[["Porque","Because"],["então","said"],["darei","I-will-give"],["uma","a"],["linguagem","language"],["pura","pure"],["aos","to-the"],["povos,","nations,"],["para que","that"],["todos","all"],["invoquem","they-invoke"],["o","the"],["nome","name"],["do","of-the"],["Senhor,","Lord,"],["para que","that"],["o","the"],["sirvam","priest's"],["ombro","shoulder"],["a","to"],["ombro.","shoulder."]]},
  {num:10,words:[["De","Of"],["além","beyond"],["dos","of-the"],["rios","rivers"],["dos","of-the"],["etíopes,","ethiopians,"],["meus","my"],["zelosos","zealous"],["adoradores,","adorer,"],["a saber,","namely"],["a","to"],["filha","daughter"],["de","of"],["meus","my"],["dispersos,","scattered,"],["me","me"],["trarão","they-will-bring"],["sacrifício.","sacrifice."]]},
  {num:11,words:[["Naquele","In-that"],["dia","day"],["não","no"],["te","you"],["envergonharás","you-will-abash"],["de","of"],["nenhuma","neither"],["das","of-the"],["tuas","your"],["obras,","works,"],["com","with"],["as","the"],["quais","what"],["te","you"],["rebelaste","haughty"],["contra","against"],["mim;","me;"],["porque","because"],["então","said"],["tirarei","I-will-deduct"],["de","of"],["teu","your"],["meio","midst"],["os","the"],["que","that"],["exultam","highness"],["na","in-the"],["tua","your"],["soberba,","pride,"],["e","and"],["tu","you"],["nunca","never"],["mais","still"],["te","you"],["ensoberbecerás","haughty"],["no","in-the"],["meu","my"],["monte","mountain"],["santo.","holy."]]},
  {num:12,words:[["Mas","But"],["deixarei","I-will-allow"],["em","in"],["teu","your"],["meio","midst"],["um","a"],["povo","people"],["humilde","humble"],["e","and"],["pobre;","poor;"],["e","and"],["eles","they"],["confiarão","they-will-confide"],["no","in-the"],["nome","name"],["do","of-the"],["Senhor.","Lord."]]},
  {num:13,words:[["O","The"],["remanescente","remnant"],["de","of"],["Israel","Israel"],["não","no"],["cometerá","borroweth"],["iniquidade,","iniquity,"],["nem","nor"],["falará","will-speak"],["mentira,","lie,"],["e","and"],["na","in-the"],["sua","his"],["boca","mouth"],["não","no"],["se","if"],["achará","will-find"],["língua","tongue"],["enganosa;","deceitful;"],["mas","but"],["serão","they-will-be"],["apascentados,","feed,"],["e","and"],["deitar-se-ão,","they-will-lie down,"],["e","and"],["não","no"],["haverá","will-have"],["quem","who"],["os","the"],["espante.","terrify."]]},
  {num:14,words:[["Canta","Sings"],["alegremente,","joyfully,"],["ó","O"],["filha","daughter"],["de","of"],["Sião;","Zion;"],["jubila,","to-jubilar,"],["ó","O"],["Israel;","Israel;"],["regozija-te,","droop,"],["e","and"],["exulta","travailest"],["de todo","wholly"],["o","the"],["coração,","heart,"],["ó","O"],["filha","daughter"],["de","of"],["Jerusalém.","Jerusalem."]]},
  {num:15,words:[["O","The"],["Senhor","Lord"],["afastou","eliminated"],["os","the"],["teus","your"],["juízos,","judgments,"],["exterminou","reversed"],["o","the"],["teu","your"],["inimigo;","enemy;"],["o","the"],["Senhor,","Lord,"],["o","the"],["rei","king"],["de","of"],["Israel,","Israel,"],["está","is"],["em","in"],["teu","your"],["meio;","midst;"],["tu","you"],["não","no"],["verás","you-will-see"],["mais","still"],["mal","evil"],["algum.","any."]]},
  {num:16,words:[["Naquele","In-that"],["dia","day"],["se","if"],["dirá","will-say"],["a","to"],["Jerusalém:","Jerusalem:"],["Não","No"],["temas,","you-fear,"],["ó","O"],["Sião,","Zion,"],["não","no"],["se","if"],["enfraqueçam","they-abate"],["as","the"],["tuas","your"],["mãos.","hands."]]},
  {num:17,words:[["O","The"],["Senhor","Lord"],["teu","your"],["Deus","God"],["está","is"],["em","in"],["teu","your"],["meio,","midst,"],["poderoso","mighty"],["para","for"],["te","you"],["salvar;","save;"],["ele","he"],["se","if"],["deleitará","plucked"],["em","in"],["ti","you"],["com","with"],["alegria;","joy;"],["calar-se-á","will-be quiet"],["por","by"],["seu","his"],["amor,","love,"],["regozijar-se-á","will-cure"],["em","in"],["ti","you"],["com","with"],["júbilo.","shouting."]]},
  {num:18,words:[["Os","The"],["entristecidos","ministers"],["por","by"],["causa","sake"],["da","of-the"],["assembleia","assembly"],["solene","solemn"],["congregarei,","halteth,"],["para","for"],["quem","who"],["a","to"],["afronta","confronts"],["foi","was"],["um","a"],["peso.","weight."]]},
  {num:19,words:[["Eis que","behold"],["naquele","in-that"],["tempo","time"],["desfarei","I-will-disrupt"],["todos","all"],["os","the"],["teus","your"],["opressores,","oppressors,"],["e","and"],["salvarei","I-will-save"],["a","to"],["que","that"],["coxeia,","limps,"],["e","and"],["recolherei","halteth"],["a","to"],["que","that"],["foi","was"],["expulsa;","beelzebub;"],["e","and"],["farei","I-will-make"],["deles","of-them"],["um","a"],["louvor","praise"],["e","and"],["um","a"],["nome","name"],["em","in"],["toda","every"],["a","to"],["terra","land"],["em","in"],["que","that"],["foram","they-were"],["envergonhados.","abash."]]},
  {num:20,words:[["Naquele","In-that"],["tempo","time"],["vos","you"],["trarei","I-will-bring"],["para","for"],["cá,","here,"],["a saber,","namely"],["no","in-the"],["tempo","time"],["em","in"],["que","that"],["vos","you"],["recolher;","clauda;"],["certamente","certainly"],["farei","I-will-make"],["de","of"],["vós","you"],["um","a"],["nome","name"],["e","and"],["um","a"],["louvor","praise"],["entre","between"],["todos","all"],["os","the"],["povos","nations"],["da","of-the"],["terra,","land,"],["quando","when"],["reconduzir","bloodthirsty"],["os","the"],["vossos","your"],["cativos","captives"],["diante","before"],["dos","of-the"],["vossos","your"],["olhos,","eyes,"],["diz","says"],["o","the"],["Senhor.","Lord."]]}
];
renderVerseSet(v1, 'zep-ch1-verses');
renderVerseSet(v2, 'zep-ch2-verses');
renderVerseSet(v3, 'zep-ch3-verses');
})();
